Term entry math pow
Codecademy/docs pull request #1000
Opened 2022-09-10 19:41 UTC by Libens-bufo

### Description

Closes #959 

Created `pow.md` in `/terms/pow/` and authored relevant entry.

### Type of Change

- Adding a new entry

### Checklist

- [ x] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-09-10 19:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1000) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1000) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1000) it.</sub>

2022-09-12 16:10 UTC, SSwiniarski requested changes
@Libens-bufo, I did a first review and left you a few comments.

2022-09-12 16:10 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/pow/pow.md
> +The following example is runnable and uses the `pow()` function to raise `3` to the power of `2`:
Both examples are largely the same. It'd be better if you did something to differentiate the two. Maybe having one use fractional exponents to find the roots of a number:

double base = 27;
double root = 3;
double exponent = 1 / root;

That's just a suggestion, you could also do something like finding the volume of a cube or a sphere.

2022-09-12 16:14 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/pow/pow.md
> +
```suggestion
```

2022-09-12 16:15 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/pow/pow.md
> +
```suggestion
```

2022-09-12 23:08 UTC, Libens-bufo commented
I have made the suggested changes, have requested another review, and would like your thoughts on the new example and output string.

2022-09-13 15:51 UTC, SSwiniarski commented
> I have made the suggested changes, have requested another review, and would like your thoughts on the new example and output string.

@Libens-bufo, I think the second example looks good.

2022-09-13 21:27 UTC, Libens-bufo commented
Checks are good now (did `yarn format`).

Requesting second review. @Dusch4593

2022-09-14 13:47 UTC, Dusch4593 requested changes
@Libens-bufo Finished with my review and left you some comments/suggestions. 😄

2022-09-14 13:47 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/pow/pow.md
> +The **`pow()`** function returns the result of a base raised to the power of an exponent.
```suggestion
The **`pow()`** function returns the result of a base value raised to the power of an exponent.
```

2022-09-14 13:47 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/pow/pow.md
> +
Can we put some text below the syntax snippet that describes the domain and range of `base` and `exponent` as well as what errors are caused by which invalid input(s)?

2022-09-14 13:47 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/pow/pow.md
> +
```suggestion
    //Output: 2 raised to the power of 2 equals 4.
```

2022-09-14 13:47 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/pow/pow.md
> +
```suggestion
    std::cout << base << " raised to the power of " << exponent << " equals " << result <<", which is the " << root << "-root of " << base << ".\n";
```

2022-09-14 13:47 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/pow/pow.md
> +The following example is runnable and uses the `pow()` function to find the `3`-root (cube root) of `27` by raising the base to the reciprocal of the desired root:
This example seems too similar to the [example](https://www.codecademy.com/resources/docs/cpp/math-functions/cbrt#:~:text=Use%20cbrt()%20to%20return%20the%20cube%20root%20of%2027%3A) under the existing `cbrt()` C++ entry. Wondering if we could change the values but keep the reciprocal?

```suggestion
The following example is runnable and uses the `pow()` function to find the nth-root of `16` by raising the base to the reciprocal of the desired root:
```

2022-09-14 13:47 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/pow/pow.md
> +    double root = 3;
```suggestion
    double base = 16;
    double root = 4;
```

2022-09-26 19:01 UTC, Dusch4593 commented
Hey @Libens-bufo! Just wanted to check in on things with this PR? Any questions or anything we can do to help?

2022-09-26 20:47 UTC, Libens-bufo commented
Apologies, been swamped. Will submit requested changes this week. From: Brandon Dusch ***@***.***>Sent: Monday, September 26, 2022 3:01 PMTo: Codecademy/docs ***@***.***>Cc: Jason Swinehart ***@***.***>; Mention ***@***.***>Subject: Re: [Codecademy/docs] [Term Entry] C++ Math Functions: `pow()` (PR #1000) 
Hey @Libens-bufo! Just wanted to check in on things with this PR? Any questions or anything we can do to help?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-10-25 22:09 UTC, yangc95 commented
Hey @Libens-bufo, did you need some assistance with these open comments?

2022-10-31 14:27 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/pow/pow.md
> +  double base = 27;
```suggestion
  double base = 16;
```

2022-10-31 15:50 UTC, SSwiniarski approved these changes
@yangc95 Looks good to me.

2022-10-31 16:49 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/pow/pow.md
> +- A range error may occue due to underflow.
```suggestion
- A range error may occur due to underflow.
```

2022-10-31 16:50 UTC, yangc95 approved these changes

2022-10-31 16:57 UTC, Dusch4593 approved these changes
cc: @yangc95 @SSwiniarski

@Libens-bufo LGTM! 👍🏻

Made a few small edits in 93fdb16746fb8fe12e70b35a3bb226d9d6103b45 but this looks good to merge now. 🚀

2022-10-31 16:59 UTC, merged

2022-10-31 17:02 UTC, Dusch4593 commented
Congrats and thank you so much for contributing to Codecademy Docs, @Libens-bufo!! 🚀 🙌🏻 🥳

The entry should now be live: https://www.codecademy.com/resources/docs/cpp/math-functions/pow

Currently, your Codecademy profile anonymously listed on the live entry. To have it listed, you'll need to add your GitHub username to your Codecademy profile, log out of Codecademy, and log back in through your GitHub account. Let us know if you'd like any help with this:

<img width="944" alt="Screen Shot 2022-10-31 at 1 01 04 PM" src="https://user-images.githubusercontent.com/23144845/199065735-b5cb8fce-17ca-44eb-9d8e-5a9aa97abaf1.png">

Looking forward to your next contribution to Docs! 😄