Created hr tag entry
Codecademy/docs pull request #1002
Opened 2022-09-12 00:12 UTC by sharkipelago

### Description

Closes #827

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-09-12 11:08 UTC, SSwiniarski requested changes
@sharkipelago I did a first review and left some comments.

2022-09-12 11:08 UTC, SSwiniarski commented on content/html/concepts/elements/terms/hr/hr.md
> +The `<b>` element should only contain text or other tags meant for text content.
```suggestion
```

2022-09-12 11:08 UTC, SSwiniarski commented on content/html/concepts/elements/terms/hr/hr.md
> +
We like to have a one sentence description preceding the example.

2022-09-12 11:08 UTC, SSwiniarski commented on content/html/concepts/elements/terms/hr/hr.md
> +**Note:** The **`<hr>`** tag is only for semantic distinction. Best practice to create a horizontal line for presentational purposes is to use [CSS](https://www.codecademy.com/resources/docs/css).
```suggestion
> **Note:** The **`<hr>`** tag is only for semantic distinction. Best practice to create a horizontal line for presentational purposes is to use [CSS](https://www.codecademy.com/resources/docs/css).
```

Our current preference is to set off **Note** items in a blockquote.

2022-09-12 11:08 UTC, SSwiniarski commented on content/html/concepts/elements/terms/hr/hr.md
> +**Note:** The **`<hr>`** tag is only for semantic distinction. Best practice to create a horizontal line for presentational purposes is to use [CSS](https://www.codecademy.com/resources/docs/css).
It might be worth it to explain past usage vs. current usage. We have many historical notes like that through the HTML elements entries.

2022-09-12 18:15 UTC, sharkipelago commented
@SSwiniarski Thanks for the feedback I implemented the changes. 

I also noticed that the b element Note section is not in blockquotes, like it doesn't have the ">" at the front. I wasn't sure if I should change it in this pr because this one is focused on hr tag. So I haven't touched it yet, but just wanted to let you know.

2022-09-13 15:42 UTC, SSwiniarski approved these changes
@sharkipelago Looks good for the second review.

2022-09-13 15:44 UTC, SSwiniarski commented
> @SSwiniarski Thanks for the feedback I implemented the changes.
> 
> I also noticed that the b element Note section is not in blockquotes, like it doesn't have the ">" at the front. I wasn't sure if I should change it in this pr because this one is focused on hr tag. So I haven't touched it yet, but just wanted to let you know.

If you wanted to go ahead and fix that, that would be cool. However, you should probably do it in a separate PR.

2022-09-14 02:46 UTC, Dusch4593 requested changes
@sharkipelago Finished with my review and left you some comments/suggestions 😄

2022-09-14 02:46 UTC, Dusch4593 commented on content/html/concepts/elements/terms/hr/hr.md
> +  - 'Tags'
```suggestion
  - 'Elements'
  - 'Semantic'
  - 'Tags'
```

2022-09-14 02:46 UTC, Dusch4593 commented on content/html/concepts/elements/terms/hr/hr.md
> +The `<hr>` element should be used to seperate other elements at a semantic break.
```suggestion
The `<hr>` element is self-closing and the forward slash `/` is optional. This should be used to semantically separate other elements (e.g., a topic-change within a section).
```

2022-09-14 02:46 UTC, Dusch4593 commented on content/html/concepts/elements/terms/hr/hr.md
> +<p>This is a different paragraph</p>
```suggestion
<p>This is a paragraph.</p>
<hr />
<p>This is a different paragraph.</p>
```

2022-09-14 02:46 UTC, Dusch4593 commented on content/html/concepts/elements/terms/hr/hr.md
> +
```suggestion

In the following example, the `<hr>` element provides a semantic break between the text of two [`<p>`](https://www.codecademy.com/resources/docs/html/paragraphs) elements:

```

2022-09-14 02:46 UTC, Dusch4593 commented on content/html/concepts/elements/terms/hr/hr.md
> +> **Note:** Originally, the tag was used to create a horizontal line for visual purposes. However, now the **`<hr>`** tag is only for semantic distinction. Best practice to create a horizontal line f
```suggestion
> **Note:** While the `<hr>` element was originally created for visual purposes, it is now used for semantic distinction. Styling with [CSS](https://www.codecademy.com/resources/docs/css) is now recommended for creating a horizontal line for presentational purposes.
```

No need to bold `<hr>` after the first mention on line # 15.

2022-09-14 02:46 UTC, Dusch4593 commented on content/html/concepts/elements/terms/hr/hr.md
> +The **`<hr>`** element is used to represent a semantic break between text elements. For example, a switch in topic.
```suggestion
The **`<hr>`** (or horizontal rule) element represents a semantic line break between text elements (e.g., a topic-change within a section).
```

2022-09-14 02:46 UTC, Dusch4593 commented on content/html/concepts/elements/terms/hr/hr.md
> +Description: 'Used to draw represent a semantic break between text elements.'
```suggestion
Description: 'Represents a semantic, horizontal line break between text elements.'
```

2022-09-14 19:18 UTC, sharkipelago commented
@Dusch4593 Changes have been made 😃

2022-09-14 20:08 UTC, Dusch4593 approved these changes
Thanks @sharkipelago! I just took a look and noticed the example text was above the "Example" header and moved it in 4de56e756426519afd3d814801ef32758da8c0b4 😄 I think this is good to merge 🚀

2022-09-14 20:08 UTC, merged