[New Entry] C: data types
Codecademy/docs pull request #1003
Opened 2022-09-13 09:24 UTC by Nessvah

### Description

Closes  #886 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-09-15 16:22 UTC, SSwiniarski requested changes
@Nessvah I finished a first review and left some comments.

2022-09-15 16:22 UTC, SSwiniarski commented on content/c/concepts/data-types/data-types.md
> +Description: 'Java’s most basic data types are known as primitive data types and are in the system by default. The available types are as follows: - int - char - boolean - byte - long'
```suggestion
Description: 'Java’s most basic data types are known as primitive data types and are in the system by default. The available types are as follows: - int - char - boolean - byte - long'
```
```suggestion
Description: 'The most basic data types in C are known as primitive data types and are in the system by default.'
```

2022-09-15 16:22 UTC, SSwiniarski commented on content/c/concepts/data-types/data-types.md
> +Description: 'Java’s most basic data types are known as primitive data types and are in the system by default. The available types are as follows: - int - char - boolean - byte - long'
Removed reference to Java. Also, descriptions are best as one sentence.

2022-09-15 16:22 UTC, SSwiniarski commented on content/c/concepts/data-types/data-types.md
> +It contains only integral values. A minus sign preceding the data type indicates that the value is negative.
```suggestion
Ints contain only integral values. A minus sign preceding the data type indicates that the value is negative.
```

2022-09-15 16:22 UTC, SSwiniarski commented on content/c/concepts/data-types/data-types.md
> +Can be expressed in hexadecimal notation (base 16).
```suggestion
They can be expressed in hexadecimal notation (base 16).
```

2022-09-15 16:22 UTC, SSwiniarski commented on content/c/concepts/data-types/data-types.md
> +Can be expressed in hexadecimal notation (base 16).
I'd add an explanation of the syntax for hexadecimal values.

2022-09-15 16:22 UTC, SSwiniarski commented on content/c/concepts/data-types/data-types.md
> +Spaces aren't allowed between digits and the values larger than 999 don't need a comma.
```suggestion
Spaces aren't allowed between digits and the values larger than 999 don't use commas.
```

2022-09-15 16:22 UTC, SSwiniarski commented on content/c/concepts/data-types/data-types.md
> +Floats are used to store floating-point numbers, values that contain decimal plates. They can be expressed in scientific notation and has 6 decimal digits of precision.
```suggestion
Floats are used to store floating-point numbers, values that contain decimal places. They can be expressed in scientific notation and have 6 decimal digits of precision.
```

2022-09-15 16:22 UTC, SSwiniarski commented on content/c/concepts/data-types/data-types.md
> +Floats are used to store floating-point numbers, values that contain decimal plates. They can be expressed in scientific notation and has 6 decimal digits of precision.
I'd add a sentence explaining the syntax of scientific notation.

2022-09-15 16:22 UTC, SSwiniarski commented on content/c/concepts/data-types/data-types.md
> +Doubles are the same but they are needed when more precision is required since it has 15 decimal digits of precision.
```suggestion
Doubles are the same but they are used when more precision is required. They have 15 decimal digits of precision.
```

2022-09-15 16:22 UTC, SSwiniarski commented on content/c/concepts/data-types/data-types.md
> +
We're missing a section on the `char` datatype.

2022-09-15 16:22 UTC, SSwiniarski commented on content/c/concepts/data-types/data-types.md
> +| Double | 8 bytes | 1.7E-308 to 1.7E+308            | %lf              |
There's no mention of what the "Format Specifier" means in this entry. That column should probably be omitted.

2022-09-15 17:27 UTC, Nessvah commented
> @Nessvah I finished the first review and left some comments.

thank you. I'll make the changes as soon as possible. 
I was considering including how to make the conversions and talk about the signed and unsigned types, what do you think?

2022-09-16 11:18 UTC, SSwiniarski commented
> > @Nessvah I finished the first review and left some comments.
> 
> thank you. I'll make the changes as soon as possible. I was considering including how to make the conversions and talk about the signed and unsigned types, what do you think?

@Nessvah, both would be good additions if they're relatively brief. We don't want Docs entries to become overlong.

2022-09-21 16:04 UTC, Nessvah commented
> > > @Nessvah I finished the first review and left some comments.
> > 
> > 
> > thank you. I'll make the changes as soon as possible. I was considering including how to make the conversions and talk about the signed and unsigned types, what do you think?
> 
> @Nessvah, both would be good additions if they're relatively brief. We don't want Docs entries to become overlong.

@SSwiniarski  Let me know if after this review there's still space to improve and maybe add those two topics.

2022-09-29 18:23 UTC, Dusch4593 requested changes
@Nessvah Finished with my review and left some comments/suggestions. The content in this entry seems to only cover _primitive data types_. But we should also include information about these other classifications:

- Derived types ([arrays](https://www.codecademy.com/resources/docs/c/arrays), [functions](https://www.codecademy.com/resources/docs/c/functions), [pointers](https://www.codecademy.com/resources/docs/c/pointers))
- User defined types ([structures](https://www.codecademy.com/resources/docs/c/structures))

2022-09-29 18:23 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +Description: 'C’s most basic data types are known as primitive data types and are in the system by default.'
```suggestion
Description: 'Data types are units of value stored in memory through variables, each with different functionalities and size-ranges.'
```

2022-09-29 18:23 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +They can be expressed in hexadecimal notation (base 16).\*
```suggestion
Ints contains only integral values. A minus sign preceding the data type indicates that the value is negative. They can be expressed in hexadecimal notation (base 16).
```

2022-09-29 18:23 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +\* Hexadecimal integer literals begin always with the 0 followed by either an `x` or `X`, followed by different combinations of digits going from `0` through `9`, and the letters `a` through `f` or `
```suggestion
> **Note:** Hexadecimal integer literals begin always with the `0` followed by either an `x` or `X`, followed by different combinations of digits (`0` - `9`) and letters (`a` - `f` or `A` - `F`).
```

2022-09-29 18:23 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +int hundreds2 = 12000 // Correct!
```suggestion
int hundreds2 = 12000; // This is correct
```

2022-09-29 18:23 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +Floats are used to store floating-point numbers, values that contain decimal places. They can be expressed in scientific notation\* and has 6 decimal digits of precision.
```suggestion
Floating-point values are non-whole numbers that contain decimal places. They can have up to 6 decimal digits of precision and can be expressed in scientific notation.
```

2022-09-29 18:23 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +\*Scientific notation is a form of expressing numbers that are too large or too small to be conveniently written in decimal form. E.g. `6.022E23`
```suggestion
> **Note:** Scientific notation is a form of expressing numbers that are too large or too small to be conveniently written in decimal form ( e.g., `6.022E23`).
```

2022-09-29 18:23 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +Doubles are the same but they are used when more precision is required. They have 15 decimal digits of precision.
```suggestion
Doubles are like floats but more precise with up to 15 decimal digits. The following is an example of `float` and `double` type values:
```

2022-09-29 18:23 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +float counterFactor = 15.87e4;
```suggestion
float counterFactor = 15.87E4;
```

2022-09-29 18:23 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +float counterFactor = 15.87e4;
Not sure if capitalization matters but suggesting uppercase "E" for consistency.

2022-09-29 18:23 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +
I would remove this section altogether and, instead, place this table right above the "### Int" header.

2022-09-29 18:23 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +In C, a sequence of chars are called [strings](https://www.codecademy.com/resources/docs/c/strings).
```suggestion
Chars use single quotation marks `'` to present single characters such as letters, [numbers](https://www.codecademy.com/resources/docs/general/number), [whitespace](https://www.codecademy.com/resources/docs/general/whitespace), special characters, and symbols. Each char only occupies one byte in memory. In C, a sequence of chars are called [strings](https://www.codecademy.com/resources/docs/c/strings).
```

2022-09-29 18:23 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +C is a statically-typed language (such as C++ and Java) where variable types are known at compile time instead of the runtime. In this case, types must be expressly indicated by the programmer.
This section should be moved somewhere near the top of this file (in lines # 15-18).

2022-09-30 02:06 UTC, Nessvah commented on content/c/concepts/data-types/data-types.md
> +  - 'Booleans'
I should always write the tags in order, right? For a matter of consistency?

2022-09-30 15:28 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +  - 'Booleans'
Nope! Order does not matter 😄

2022-10-23 16:43 UTC, Dusch4593 requested changes
@Nessvah Just a few more comments/suggestions from me 😄

2022-10-23 16:43 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +These data types are mostly numeric (integers, doubles, floating-point numbers, etc.) and can be used for arithmetic operations like subtraction and division. Values that use the `void` keyword (for
```suggestion
These data types are mostly numeric (integers, doubles, floating-point numbers, etc.) and can be used for arithmetic operations like subtraction and division. Values that use the `void` keyword (for no data) are also regarded as primitive data types.
```

2022-10-23 16:43 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +Chars use single quotations marks `'` to present single characters such as letters, [numbers](https://www.codecademy.com/resources/docs/general/number), [whitespace](https://www.codecademy.com/resour
```suggestion
Chars use single quotations marks `'` to represent single characters such as letters, [numbers](https://www.codecademy.com/resources/docs/general/number), [whitespace](https://www.codecademy.com/resources/docs/general/whitespace), special characters, and symbols. Each char only occupies one byte in memory. In C, a sequence of chars is called [strings](https://www.codecademy.com/resources/docs/c/strings).
```

2022-10-23 16:43 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +In C, **data types** are units of value stored in memory through [variables](https://www.codecademy.com/resources/docs/c/variables). Different kinds of data types determine their size and functionali
```suggestion
In C, **data types** are units of value stored in [memory](https://www.codecademy.com/resources/docs/c/memory-management) through [variables](https://www.codecademy.com/resources/docs/c/variables). Different kinds of data types determine their size and functionality.
```

2022-10-23 16:43 UTC, Dusch4593 commented on content/c/concepts/data-types/data-types.md
> +| Double | 8 bytes | 1.7E-308 to 1.7E+308            |
```suggestion
| Char   | 1 byte  | -128 - 127 or 0 - 255           |
| Int    | 4 bytes | -2,147,483,648 - 2,147,483,647  |
| Float  | 4 bytes | 1.2E-38 - 3.4E+38               |
| Double | 8 bytes | 1.7E-308 - 1.7E+308             |
```

2022-10-24 16:59 UTC, Nessvah commented
> @Nessvah Just a few more comments/suggestions from me smile

😃 Awesome! I'll take a look at it later today.

2022-10-25 22:24 UTC, yangc95 commented on content/c/concepts/data-types/data-types.md
> +Like with C++ and Java, C is a statically-typed language where variable types are known at compile time instead of the [runtime](https://www.codecademy.com/resources/docs/general/runtime). In this ca
Do we mean that types are explicitly indicated?

2022-10-26 11:30 UTC, SSwiniarski approved these changes
@Nessvah Looks good to me, I just had one additional comment.

2022-10-26 11:30 UTC, SSwiniarski commented on content/c/concepts/data-types/data-types.md
> +Chars use single quotations marks `'` to represent single characters such as letters, [numbers](https://www.codecademy.com/resources/docs/general/number), [whitespace](https://www.codecademy.com/reso
```suggestion
Chars use single quotations marks `'` to represent single characters such as letters, [numbers](https://www.codecademy.com/resources/docs/general/number), [whitespace](https://www.codecademy.com/resources/docs/general/whitespace), special characters, and symbols. Each char only occupies one byte in memory. In C, sequences of chars are called [strings](https://www.codecademy.com/resources/docs/c/strings).
```

2022-10-31 18:25 UTC, Dusch4593 approved these changes
@Nessvah LGTM! 🚀

2022-10-31 18:27 UTC, merged

2022-10-31 18:35 UTC, Dusch4593 commented
Congrats and thank you so much for another awesome contribution to Codecademy Docs, @Nessvah! 🚀

The entry should now be live: https://www.codecademy.com/resources/docs/c/data-types

<img width="860" alt="Screen Shot 2022-10-31 at 2 34 41 PM" src="https://user-images.githubusercontent.com/23144845/199083707-41b4a20d-1014-48ad-961b-4f0bde572ba6.png">

Looking forward to your next contribution! 😄

2022-11-01 06:02 UTC, Nessvah commented
@Dusch4593 Thank you so much! It's always a pleasure to help and learn with you guys 😄 👍🏻