New Entry: General MFA
Codecademy/docs pull request #1007
Opened 2022-09-16 00:00 UTC by yangc95

### Description

Created entry for MFA. 
Unsure what to add as second tag.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-09-16 22:09 UTC, Dusch4593 requested changes
@yangc95 Finished with my review and left you some comments/suggestions.

2022-09-16 22:09 UTC, Dusch4593 commented on content/general/concepts/mfa/mfa.md
> +Other factors, depending on the verification system, can be a physical item, pin, key or token, biometric marker, or location.
Wondering if we can turn this into an unordered list?

```suggestion
Other factors, depending on the verification system, include the following:

- A physical item belonging to the user (e.g., a mobile phone).
- A password, personal identity number (PIN), key, or token that only the user should know.
- Some biometric marker for the user (fingerprints, voice-recognition, key-stroke patterns, etc.).
- Information about the user's [geolocation](https://www.codecademy.com/resources/docs/general/geolocation).
```

2022-09-16 22:09 UTC, Dusch4593 commented on content/general/concepts/mfa/mfa.md
> +ATMs often require a physical card and a memorized pin to successfully take out cash.
```suggestion
ATMs often require a physical card and a memorized PIN to successfully withdraw cash.
```

2022-09-16 22:09 UTC, Dusch4593 commented on content/general/concepts/mfa/mfa.md
> +More factors in the verification process results in greater security.
```suggestion
More factors in the verification process results in greater [security](https://www.codecademy.com/resources/docs/general/cybersecurity).
```

2022-09-16 22:09 UTC, Dusch4593 commented on content/general/concepts/mfa/mfa.md
> +  - 'Computer Science'
```suggestion
  - 'Computer Science'
  - 'Cybersecurity'
```

Wouldn't this concept more closely related to the field of cybersecurity as opposed to web development?

2022-09-16 22:09 UTC, Dusch4593 commented on content/general/concepts/mfa/mfa.md
> +  - 'paths/computer-science'
```suggestion
  - 'introduction-to-cybersecurity'
  - 'paths/full-stack-engineer-career-path'
```

Both of the these pages contain lessons and modules pertaining to user authentication/authorization.

2022-09-20 19:57 UTC, yangc95 commented on content/general/concepts/mfa/mfa.md
> +Title: 'MFA'
Can do~

2022-10-05 15:27 UTC, yangc95 commented
@Dusch4593 thanks for your patience! Finally made some edits, please let me know if anything else needs tweaking~

2022-10-06 01:31 UTC, Dusch4593 approved these changes
@yangc95 LGTM! I have just one minor suggestion but we can proceed to the next review. 😄

2022-10-06 01:31 UTC, Dusch4593 commented on content/general/concepts/multi-factor-authentication/multi-factor-authentication.md
> +  - 'paths/code-foundations'
```suggestion
  - 'introduction-to-cybersecurity'
```

I would add at least one free course/path if possible. This one seemed like the most relevant.

2022-10-10 22:04 UTC, yangc95 commented
> @yangc95 LGTM! I have just one minor suggestion but we can proceed to the next review. 😄

Thanks @Dusch4593 for the suggestion!

2022-10-15 13:41 UTC, SSwiniarski requested changes
@yangc95, I did a review and only had a couple of comments.

2022-10-15 13:41 UTC, SSwiniarski commented on content/general/concepts/multi-factor-authentication/multi-factor-authentication.md
> +One factor is typically a username or email and password combination. This is the basic log-in functionality that most websites require user's to create when initially signing up for an account.
```suggestion
One factor is typically a username or email and password combination. This is the basic log-in functionality that most websites require users to create when initially signing up for an account.
```

2022-10-15 13:41 UTC, SSwiniarski commented on content/general/concepts/multi-factor-authentication/multi-factor-authentication.md
> +- A password, personal identity number (PIN), key, or token that only the user should know.
You already mentioned "password." Why not mention authentication codes that are e-mailed or texted or phoned in to the user.

2022-10-16 20:20 UTC, yangc95 commented on content/general/concepts/multi-factor-authentication/multi-factor-authentication.md
> +- A password, personal identity number (PIN), key, or token that only the user should know.
```suggestion
- A personal identity number (PIN), key, or token that only the user should know prior, or an authentication code that is e-mailed, texted, or phoned-in to the user in real-time.
```

2022-10-16 20:21 UTC, yangc95 commented
@SSwiniarski Thanks for taking a look! Please let me know if anything else needs changing

2022-10-17 00:52 UTC, HishamT approved these changes
LGTM!

2022-10-17 13:32 UTC, SSwiniarski approved these changes
Looks Good.

2022-10-17 18:51 UTC, merged

2022-10-17 18:56 UTC, yangc95 commented
live link: https://www.codecademy.com/resources/docs/general/multi-factor-authentication

TY cc: @Dusch4593 @HishamT @SSwiniarski