new sql content
Codecademy/docs pull request #1022
Opened 2022-09-28 23:06 UTC by caupolicandiaz

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ x] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-09-28 23:14 UTC, caupolicandiaz commented
I would submit that the data types table is admittedly limited, and simply based on the types that were included on the Monday board. I'm happy to expand this to include any other types that are recommended. Unfortunately, this table is complicated by the fact that there are many differences in the supported types among SQL dialects, I chose arbitrarily, to show examples from Postgres. I'm happy to hear any alternative ways of organizing and displaying types.

2022-09-30 00:00 UTC, Dusch4593 requested changes
@caupolicandiaz Finished with my review and left you some comment/suggestions.

2022-09-30 20:50 UTC, caupolicandiaz commented
@Dusch4593 I've incorporated all your edits, ready for another review. Thanks

2022-10-01 03:00 UTC, Dusch4593 approved these changes
@caupolicandiaz LGTM for the next review! 👍🏻

2022-10-01 12:31 UTC, SSwiniarski requested changes
@caupolicandiaz, I finished a review and left a few comments.

2022-10-01 12:31 UTC, SSwiniarski commented on content/sql/concepts/data-types/data-types.md
> +- `date`: A date (without any time value), examples include 2022-06-21 (ISO 8601 format) and 6/21/2022.
I'd add CHAR and VARCHAR data types as they're common across SQL flavors.

2022-10-01 12:31 UTC, SSwiniarski commented on content/sql/concepts/data-types/data-types.md
> +These data types are found across all flavors of SQl; however, some versions of SQL may support several distinct data types within a class while others may only have one (the definitions below are sp
```suggestion
These data types are found across all flavors of SQl; however, some versions of SQL may support several distinct data types of a particular class while others may only have one (the definitions below are specific to PostgreSQL).
```

2022-10-01 12:31 UTC, SSwiniarski commented on content/sql/concepts/data-types/data-types.md
> +  - 'Documentation'
```suggestion
```

2022-10-01 12:31 UTC, SSwiniarski commented on content/sql/concepts/commands/terms/round/round.md
> +## Examples
```suggestion
## Example
```

2022-10-01 12:31 UTC, SSwiniarski commented on content/sql/concepts/commands/terms/round/round.md
> +  - 'Documentation'
```suggestion
```

2022-10-03 21:10 UTC, caupolicandiaz commented
@SSwiniarski @Dusch4593 Thanks for edits, I've made all the updates in response to your comments. Ready for the next review

2022-10-04 16:00 UTC, SSwiniarski approved these changes
@caupolicandiaz, Looks good on my end.

2022-10-07 10:47 UTC, Dusch4593 commented
This looks ready to merge! 🚀 I made some minor edits in b79f37fe685bd64635a713327030a66c30b1819e.

2022-10-07 10:48 UTC, merged