add sin function cpp
Codecademy/docs pull request #1030
Opened 2022-10-02 18:04 UTC by Yash-Var

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-03 15:53 UTC, SSwiniarski requested changes
@Yash-Var, I did a first review and left a few comments.

2022-10-03 15:53 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/sin/sin.md
> +Description: 'Returns the sine of an angle (argument) given in radians in the range[-1,1].'
```suggestion
Description: 'Returns the sine of an angle given in radians in the range [-1,1].'
```

2022-10-03 15:53 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/sin/sin.md
> +Returns the sine of an angle (argument) given in radians in the range[-1,1].
```suggestion
Returns the sine of an angle (argument) given in radians in the range [-1,1].
```

2022-10-03 15:53 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/sin/sin.md
> +The following example showcases the `sin()` function :
```suggestion
The following example illustrates the `sin()` function:
```

2022-10-03 15:53 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/sin/sin.md
> +  double degree=60;
```suggestion
  double degree = 60;  
```

2022-10-03 15:53 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/sin/sin.md
> +  double radian=degree*3.14/180;
```suggestion
  double radian = degree*3.14/180;  
```

2022-10-03 15:53 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/sin/sin.md
> +  cout<<"Sine of an angle is : "<<sin(radian);
It would be good to output the angle as well so it reads "Sine of 60 degrees is 0.86576"

2022-10-03 15:53 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/sin/sin.md
> +
```suggestion

The argument `n` is an angle given in radians.

```

2022-10-03 17:11 UTC, Yash-Var commented
@SSwiniarski i have made the changes review it ....

2022-10-04 12:12 UTC, Dusch4593 commented
Hey @Yash-Var make sure to always check off those boxes under ["Checklist"](https://github.com/Codecademy/docs/pull/1030#:~:text=a%20new%20entry-,Checklist,-All%20writings%20are) after creating the PR.

2022-10-04 15:50 UTC, SSwiniarski commented
> @SSwiniarski i have made the changes review it ....

@Yash-Var, you didn't address my last comment about outputting the angle in your example.

2022-10-06 12:10 UTC, Yash-Var commented
@SSwiniarski review ...

2022-10-06 19:32 UTC, Dusch4593 requested changes
@Yash-Var Finished with my review and left you some comments/suggestions. 😄

2022-10-06 19:32 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/sin/sin.md
> +Returns the sine of an angle (argument) given in radians in the range [-1,1].
```suggestion
The **`sin()`** function returns the sine of an angle argument, given in radians, in the range [-1,1].
```

2022-10-06 19:32 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/sin/sin.md
> +std::sin(n)
```suggestion
std::sin(angle)
```

2022-10-06 19:32 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/sin/sin.md
> +The argument `n` is an angle given in radians.
```suggestion
The `angle` parameter is expressed in radians.
```

2022-10-06 19:32 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/sin/sin.md
> +  cout<<"Sine of 60 degrees is "<<sin(radian);
```suggestion
  cout << "Sine of 60 degrees is " << sin(radian);  
```

2022-10-06 19:32 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/sin/sin.md
> +  double radian = degree*3.14/180;
To improve this output, I would suggest utilizing the `M_PI` constant (more precise than 3.14):

```suggestion
  // convert degrees to radians
  double pi = M_PI;
  double degree = 60;  
  double radian = degree * pi/180;  
```

2022-10-06 19:32 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/sin/sin.md
> +Sine of 60 degrees is 0.86576
If we go with the `M_PI` constant, let's implement the following:

```suggestion
Sine of 60 degrees is 0.866025   
```

2022-10-06 19:32 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/sin/sin.md
> +Description: 'Returns the sine of an angle given in radians in the range [-1,1].'
```suggestion
Description: 'Returns the sine of an angle, given in radians, in the range [-1,1].'
```

2022-10-07 12:42 UTC, Yash-Var commented
@Dusch4593 done review my changes....

2022-10-07 13:49 UTC, Dusch4593 requested changes
@Yash-Var This is almost ready for merge, let's implement these last two suggestions and then we'll be good to go. 😄

2022-10-07 13:49 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/sin/sin.md
> +{
```suggestion

int main()  {  
```

2022-10-07 13:49 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/sin/sin.md
> +  cout << "Sine of 60 degrees is " << sin(radian);
```suggestion
  cout << "Sine of 60 degrees is " << sin(radian) << "\n";  
```

2022-10-07 19:32 UTC, Yash-Var commented
@Dusch4593 review and merge ...

2022-10-08 12:32 UTC, Dusch4593 approved these changes
@Yash-Var LGTM! I made a super small edit in 233a4ffcf71fddfe391f47eddb9ccdd602a54e08, in the Syntax section where I replaced with the \```pseudo code block and removed `std::`.

2022-10-08 12:37 UTC, merged

2022-10-08 12:44 UTC, Dusch4593 commented
Congrats @Yash-Var! Your contribution should now be live: https://www.codecademy.com/resources/docs/cpp/math-functions/sin

Thank you again for this contribution to Docs!

P.S. For your next contribution, can you push your commits from a branch besides your fork's `main` branch? (It's actually [one of the checklist items](https://github.com/Codecademy/docs/pull/1030#:~:text=I%20have%20confirmed%20my%20changes%20are%20not%20being%20pushed%20from%20my%20forked%20main%20branch.) on top of every PR.)