C: Basic Output documentation update
Codecademy/docs pull request #1031
Opened 2022-10-03 09:29 UTC by TheZal

### Description

PR that closes the issue #893.

### Type of Change
- Updating the documentation.

- Shortened the description Line # 3
- Name of concept in bold Line # 15
- Replaced "typically" with "commonly" Line # 19
- Created new entries: `basic-output/terms/putchar/putchar.md` - `basic-output/terms/puts/puts.md` - `basic-output/terms/printf/printf.md`

### Checklist

- [✔] All writings are my own.
- [✔] My entry follows the Codecademy Docs style guide.
- [✔] My changes generate no new warnings.
- [✔] I have performed a self-review of my own writing and code.
- [✔] I have checked my entry and corrected any misspellings.
- [✔] I have made corresponding changes to the documentation if needed.
- [✔] I have confirmed my changes are not being pushed from my forked `main` branch.
- [✔] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [✔] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-03 09:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1031) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1031) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1031) it.</sub>

2022-10-03 16:50 UTC, SSwiniarski requested changes
@TheZal, I did a first review and left a few comments. Most important is editing that's required on the new term entries. They need to follow the term entry template [here](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md).

2022-10-03 16:50 UTC, SSwiniarski commented on content/c/concepts/basic-output/basic-output.md
>  ## Format Specifiers
The Format Specifier & Decimal Precision sections should go with the new printf() term now.

2022-10-03 16:50 UTC, SSwiniarski commented on content/c/concepts/basic-output/terms/printf/printf.md
> +## Print Formatted with `printf()`
This is missing the Metadata section at the head of the file. See the metadata section [here](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md). These also need some edits to be stand-alone entries. They need introductory material and Syntax and Example headers. You can look at the updated term entry template [here](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md).

2022-10-03 16:50 UTC, SSwiniarski commented on content/c/concepts/basic-output/terms/putchar/putchar.md
> +## Print Character with `putchar()`
See my comment on the `printf()` term entry.

2022-10-03 16:50 UTC, SSwiniarski commented on content/c/concepts/basic-output/terms/puts/puts.md
> +## Print String with `puts()`
See my comment on the printf() term entry.

2022-10-04 06:38 UTC, TheZal commented
Gonna fix that!

2022-10-05 13:21 UTC, SSwiniarski requested changes
@TheZal, I've included some more detailed suggestions after your last edit.

2022-10-05 13:21 UTC, SSwiniarski commented on content/c/concepts/basic-output/basic-output.md
> +Description: 'In the C lang the console output is managed by the library stdio.h which has to be included.
```suggestion
Description: 'In the C language the console output is managed by the library stdio.h which has to be included.
```

2022-10-05 13:21 UTC, SSwiniarski commented on content/c/concepts/basic-output/basic-output.md
> +Thanks to that you can use function like putchar() that target the C console.'
```suggestion
Thanks to that a functions that target the C console, like putchar(), can be used.'
```

2022-10-05 13:21 UTC, SSwiniarski commented on content/c/concepts/basic-output/basic-output.md
> +Thanks to that you can use function like putchar() that target the C console.'
We should avoid "you" and "we" in docs.

2022-10-05 13:21 UTC, SSwiniarski commented on content/c/concepts/basic-output/basic-output.md
>  ## Format Specifiers
These still need to be removed from this file.

2022-10-05 13:21 UTC, SSwiniarski commented on content/c/concepts/basic-output/terms/printf/printf.md
> +While the `puts()` function can only accept and print a single string, the **`printf()`** function can print variables within a string. So more flexibility!
```suggestion
The **`printf()`** function can print a string to the console, including variables within the string.
```

2022-10-05 13:21 UTC, SSwiniarski commented on content/c/concepts/basic-output/terms/printf/printf.md
> +printf(string)
```suggestion
printf(string, value1, value2 ... valueN)
```

2022-10-05 13:21 UTC, SSwiniarski commented on content/c/concepts/basic-output/terms/printf/printf.md
> +The `printf()` function, or "print formatted" function, takes a string with variable placeholders, also known as format specifiers, followed by the values to format in the string.
```suggestion
The `printf()` function, or "print formatted" function, takes a string with variable placeholders, also known as format specifiers, followed by any number of values to format in the string.
```

2022-10-05 13:21 UTC, SSwiniarski commented on content/c/concepts/basic-output/terms/putchar/putchar.md
> +The **`putchar()`** function, or "put character" function allow to print a char in the `stdout` file, normally the console
```suggestion
The **`putchar()`** function, or "put character" function allow to print a char to `stdout`, normally the console
```

2022-10-05 13:21 UTC, SSwiniarski commented on content/c/concepts/basic-output/terms/putchar/putchar.md
> +the **`putchar()`** takes a single `char` as an argument and prints it.
```suggestion
The **`putchar()`** takes a single `char` as an argument and prints it.
```

2022-10-05 13:21 UTC, SSwiniarski commented on content/c/concepts/basic-output/terms/puts/puts.md
> +The **`puts()`** function, or "put string" function, allow to print a char in the `stdout` file, normally the console followed by a newline character.
```suggestion
The **`puts()`** function, or "put string" function, allow to print a string to `stdout`, normally the console, followed by a newline character.
```

2022-10-05 13:21 UTC, SSwiniarski commented on content/c/concepts/basic-output/terms/puts/puts.md
> +the **`puts()`** takes a `string` as an argument and prints it adding a newline character at the end of it.
```suggestion
The **`puts()`** takes a `string` as an argument and prints it, adding a newline character at the end of it.
```

2022-10-05 13:21 UTC, SSwiniarski commented on content/c/concepts/basic-output/terms/puts/puts.md
> +
The content after this point (the extra output example) should be removed.

2022-10-05 13:35 UTC, TheZal commented
Now should be ok... I hope and sorry!

2022-10-05 13:51 UTC, SSwiniarski approved these changes
@TheZal, two more suggestions an I think this is ready for review two. And no apologies necessary, this is just how the process works.

2022-10-05 13:51 UTC, SSwiniarski commented on content/c/concepts/basic-output/terms/putchar/putchar.md
> +The **`putchar()`** function, or "put character" function allow to print a char to `stdout`, normally the console
```suggestion
The **`putchar()`** function, or "put character" function prints a char to `stdout`, normally the console
```

2022-10-05 13:51 UTC, SSwiniarski commented on content/c/concepts/basic-output/terms/puts/puts.md
> +The **`puts()`** function, or "put string" function, allow to print a string to `stdout`, normally the console, followed by a newline character.
```suggestion
The **`puts()`** function, or "put string" function prints a string to `stdout`, normally the console, followed by a newline character.
```

2022-10-28 10:07 UTC, Dusch4593 requested changes
@TheZal Finished with my review and left a few comments/suggestions. 😄

2022-10-28 10:07 UTC, Dusch4593 commented on content/c/concepts/basic-output/terms/printf/printf.md
> +The **`printf()`** function can print a string to the console, including variables within the string.
```suggestion
The **`printf()`**, or "print formatted", function can print a string to the console, including variables within the string.
```

2022-10-28 10:07 UTC, Dusch4593 commented on content/c/concepts/basic-output/terms/printf/printf.md
> +The `printf()` function, or "print formatted" function, takes a string with variable placeholders, also known as format specifiers, followed by any number of values to format in the string.
```suggestion
The `printf()` function takes a string with variable placeholders, also known as format specifiers, followed by any number of values to format in the string.
```

2022-10-28 10:07 UTC, Dusch4593 commented on content/c/concepts/basic-output/terms/printf/printf.md
> +To print 2 digits after the decimal place, `0.2f` can be used in `printf()`:
```suggestion
For example, to print two digits after the decimal place with `printf()`, `0.2f` can be used:
```

2022-10-28 10:07 UTC, Dusch4593 commented on content/c/concepts/basic-output/terms/puts/puts.md
> +The **`puts()`** function, or "put string" function prints a string to `stdout`, normally the console, followed by a newline character.
```suggestion
The **`puts()`**, or "put string", function prints a [string](https://www.codecademy.com/resources/docs/c/strings) to `stdout`, normally the console, followed by a newline character.
```

2022-10-28 10:07 UTC, Dusch4593 commented on content/c/concepts/basic-output/terms/puts/puts.md
> +putchar(char)
```suggestion
puts(str)
```

2022-10-28 10:07 UTC, Dusch4593 commented on content/c/concepts/basic-output/terms/puts/puts.md
> +The **`puts()`** takes a `string` as an argument and prints it, adding a newline character at the end of it.
```suggestion
The `puts()` function takes a `str` argument and prints it, adding a newline character at the end of it.
```

2022-10-28 11:07 UTC, TheZal commented
Thank you @Dusch4593 :)

2022-10-28 11:10 UTC, Dusch4593 approved these changes
@TheZal LGTM! 👍🏻

2022-10-28 11:15 UTC, merged

2022-10-28 11:27 UTC, Dusch4593 commented
Congrats on making your first contribution to Codecademy Docs, @TheZal!!! 🎊 🙌🏻 🎉 🥳

Here are the entry links:

- C: Basic Output - https://www.codecademy.com/resources/docs/c/basic-output
  - `printf()` - https://www.codecademy.com/resources/docs/c/basic-output/printf
  - `putchar()` - https://www.codecademy.com/resources/docs/c/basic-output/putchar
  - `puts()` - https://www.codecademy.com/resources/docs/c/basic-output/puts

I wanted to touch on a few things with you.

## Creating a PR Branch for Docs Contributions

For your next Docs contributions, I strongly recommend you branch away from your fork's `main` branch and make/push your changes from there.

<img width="973" alt="Screen Shot 2022-10-28 at 7 11 22 AM" src="https://user-images.githubusercontent.com/23144845/198576015-f5b92a7d-06ec-476f-b7d5-706ee79d92c5.png">

Part of the reason we discourage this is because if you are working on multiple PRs, you will run the risk of causing merge conflicts in one of your PRs which will inhibit our review process from moving forward.

## Anonymous Credit on Entries

Right now, you are listed as "Anonymous" on the list of credited contributors for these entries. To add your profile, you'll need to add your GitHub username to your Codecademy profile, log out of your Codecademy profile, and back in through your GitHub account.

<img width="870" alt="Screen Shot 2022-10-28 at 7 21 10 AM" src="https://user-images.githubusercontent.com/23144845/198576727-f1bcbb5f-5736-478b-aead-0b98a35864d3.png">