New Entry and Terms General: Programming Paradigms
Codecademy/docs pull request #1037
Opened 2022-10-04 03:47 UTC by yangc95

… term

### Description

- Created a new entry in General on programming paradigms.
- Nested functional programming and object oriented programming entries into the terms folder for programming paradigms.

### Type of Change

- Adding a new entry
- Adding a terms 
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-05 15:40 UTC, SSwiniarski requested changes
@yangc95, I did a first review and left a couple of comments.

2022-10-05 15:40 UTC, SSwiniarski commented on content/general/concepts/programming-paradigms/programming-paradigms.md
> +  - 'Object Oriented Programming'
We already have an OOP tag. Adding the tag spelled out is going to affect a lot of entries that already have the OOP tag.

2022-10-05 15:40 UTC, SSwiniarski commented on documentation/tags.md
> +Object Oriented Programming
Maybe just stick with the OOP tag?

2022-10-05 16:01 UTC, yangc95 commented on content/general/concepts/programming-paradigms/programming-paradigms.md
> +  - 'Object Oriented Programming'
```suggestion
  - 'OOP'
```

2022-10-05 16:02 UTC, yangc95 commented on documentation/tags.md
> +Object Oriented Programming
```suggestion
```

2022-10-05 16:05 UTC, yangc95 commented on content/general/concepts/programming-paradigms/programming-paradigms.md
> +Moving from low-level languages (e.g. assembly language) to high-level languages (e.g. Python), programming paradigms change.
```suggestion
Moving from low-level languages (e.g. [machine code](https://www.codecademy.com/resources/docs/general/machine-code)) to high-level languages (e.g. [Python](https://www.codecademy.com/resources/docs/python)), programming paradigms change.
```

2022-10-05 16:07 UTC, yangc95 commented
@SSwiniarski Thanks for conducting the first review! I incorporated your comments and suggestions. Please LMK if anything else needs adjusting

2022-10-05 16:52 UTC, SSwiniarski approved these changes
@yangc95 Looks good from here! Ready for a second review.

2022-10-11 15:20 UTC, Dusch4593 requested changes
@yangc95 Left some comments/suggestions below. Could we also add the `'Functional Programming'` tag to `fuctional-programming.md` and `'OOP'` to `object-oriented-programming.md`?

2022-10-11 15:20 UTC, Dusch4593 commented on content/general/concepts/programming-paradigms/programming-paradigms.md
> +Moving from low-level languages (e.g. [machine code](https://www.codecademy.com/resources/docs/general/machine-code)) to high-level languages (e.g. [Python](https://www.codecademy.com/resources/docs/
```suggestion
Moving from low-level languages (e.g., [machine code](https://www.codecademy.com/resources/docs/general/machine-code)) to high-level languages (e.g., [Python](https://www.codecademy.com/resources/docs/python)), programming paradigms change.
```

2022-10-11 15:20 UTC, Dusch4593 commented on content/general/concepts/programming-paradigms/programming-paradigms.md
> +A **programming paradigm** is an approach to programming. Depending on the language, the preferred paradigm may differ.
```suggestion
A **programming paradigm** is an approach to programming. Depending on the language, the preferred paradigm may differ. Some languages, such as [C++](https://www.codecademy.com/resources/docs/cpp) and [JavaScript](https://www.codecademy.com/resources/docs/javascript), cover multiple paradigms.
```

2022-10-13 17:14 UTC, yangc95 commented
@Dusch4593 @SSwiniarski does everything look good here before we merge?

2022-10-14 11:21 UTC, SSwiniarski commented
My only reservation is do we have any inbound links to either object oriented programming or functional programming that this breaks? If so, we need to add those links to this PR.

2022-10-14 15:19 UTC, Dusch4593 approved these changes
@yangc95 @SSwiniarski Everything LGTM! I went in and fixed the links in other entries that would have stopped working, otherwise. 😄

2022-10-14 15:19 UTC, merged