Updated description for `atan()` function
Codecademy/docs pull request #1040
Opened 2022-10-04 18:31 UTC by codewithdev

### Description

The https://www.codecademy.com/resources/docs/cpp/math-functions/atan page describes the use of `atan()` function. This PR adds the following changes to the page:
- Updated function description.
- Added one more example for clarity.

### Type of Change

- Adding a new Example
- Editing the description
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-04 18:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1040) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1040) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1040) it.</sub>

2022-10-05 11:10 UTC, Dusch4593 requested changes
@codewithdev Finished with my review and left you some comments/suggestions. Let me know when you've finished implementing the changes or if you have any questions. 😄

2022-10-05 11:10 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/atan/atan.md
> +The `<cmath>` header file defines `atan()` function that returns the inverse tangent of an argument in radians. It takes a single argument (positive, negative, or zero) and returns the output in radi
```suggestion
The **`atan()`** function that returns the inverse tangent of an argument (positive, negative, or zero) in radians.
```

2022-10-05 11:10 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/atan/atan.md
On line # 18, let's change \```py to \```pseudo.

2022-10-05 11:10 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/atan/atan.md
> +### Example 2
```suggestion
### Codebyte Example
```

2022-10-05 11:10 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/atan/atan.md
> +  result= atan(value);
```suggestion
  double value = 1.0, result;
  result = atan(value);
```

2022-10-05 11:10 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/atan/atan.md
> +  //Output: 0.785398 radians
```suggestion
  std::cout << result << " radians" << "\n";
```

2022-10-05 11:10 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/atan/atan.md
> +The following example uses the `atan()` function that returns the inverse tangent of value `1.0`:
```suggestion
The following example returns the inverse tangent of the `value` with the `atan()` function:
```

2022-10-05 11:10 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/atan/atan.md
Can we write 1-3 sentences here that explains the domain/range of the `n` parameter along with any edge cases (e.g., pos/neg infinity).

2022-10-31 18:31 UTC, Dusch4593 commented
@codewithdev Did you have any questions or need any help with implementing the requested changes? Just a reminder that today is the last day to merge your PRs and have them count for Hacktoberfest.

2022-11-09 16:39 UTC, Dusch4593 commented
@codewithdev Did you have any questions or need any help with implementing the requested changes? Even though Hacktoberfest is over, you can still contribute to Codecademy Docs anytime! 😄

2022-11-21 17:42 UTC, SSwiniarski commented
@codewithdev, because it's been a few weeks, I've gone ahead and committed all of @Dusch4593's suggestions in the interest of getting this merged.

2022-11-21 17:44 UTC, SSwiniarski approved these changes
@Dusch4593, this looks good to me now. Anything we need to add?

2022-11-21 17:56 UTC, Dusch4593 approved these changes
@codewithdev @SSwiniarski LGTM for merge! 😄

I made some last edits in f247c1318c2ca6f8c117e9b292b1ccb6a72b3210 that I wanted to note:

- Moved parenthetical statement from line # 14 to line # 22.
- On line # 22:
  - Changed "argument" to "parameter" for the "Syntax" section.
  - Turned last two sentences into list of edge cases.
- Removed " 1" from header on line # 27.
- Allocated output from "Example" to its own \```shell snippet.
- Added `codebyte/cpp` signature to "Codebyte Example" section.
- Moved opening curly brace `{` to same line as `int main()` to be in line with syntax in our C++ courses.

2022-11-21 17:57 UTC, merged

2022-11-21 18:01 UTC, Dusch4593 commented
Congrats and thank you for contributing to Codecademy Docs! 🥳 🎊 🎉

Your changes should now be live: https://www.codecademy.com/resources/docs/cpp/math-functions/atan

<img width="884" alt="Screen Shot 2022-11-21 at 1 00 36 PM" src="https://user-images.githubusercontent.com/23144845/203127408-beeb40ce-0cab-479e-92a6-c6a3a0f027f5.png">