[New Term] C++ Math Functions: fmin()
Codecademy/docs pull request #1046
Opened 2022-10-05 13:54 UTC by borntofrappe

### Description

Closes #965 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-05 17:37 UTC, SSwiniarski requested changes
@borntofrappe, I did a first review and left a couple of comments.

2022-10-05 17:37 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/fmin/fmin.md
> +Description: 'Returns the smaller of the two input arguments.'
```suggestion
Description: 'Returns the smaller of two arguments.'
```

2022-10-05 17:37 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/fmin/fmin.md
> +The **`fmin()`** function returns the smaller of the two input arguments.
```suggestion
The **`fmin()`** function returns the smaller of two arguments.
```

2022-10-05 19:26 UTC, SSwiniarski approved these changes
@borntofrappe, looks like we're ready for a second review.

2022-10-05 21:38 UTC, yangc95 commented
@borntofrappe I'll be taking this PR on for a second review~

2022-10-05 22:56 UTC, yangc95 requested changes
Hi @borntofrappe, I've added some new comments/suggestions.

Please tag me once you're done making edits or if you have any questions!

2022-10-05 22:56 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/fmin/fmin.md
> +The parameters `x` and `y` are usually a numeric [data type](https://www.codecademy.com/resources/docs/cpp/data-types) ranging from `-INFINITY` (negative) to `INFINITY` (positive). If one of the para
- Similar to the open PR for `fmax()` function, can we change  to to "negative `INFINITY` to positive `INFINITY`."
- Change `NAN` to `NaN`

2022-10-05 22:56 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/fmin/fmin.md
> +The following example is runnable and returns the smaller value between `-32.123` and `-32.231`:
```suggestion
The following example returns the smaller value between `-32.123` and `-32.231`:
```

2022-10-05 22:56 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/fmin/fmin.md
> +  std::cout << "The smaller value between " << x << " and " << y << " is " << result << "\n";
Can we add a "." period at the end of this output before the new line?

2022-10-05 22:56 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/fmin/fmin.md
> +  std::cout << "The smaller value between " << x << " and " << y << " is " << result << "\n";
```suggestion
  std::cout << "The smaller value between " << x << " and " << y << " is " << result << "." << "\n";
```

2022-10-26 00:26 UTC, yangc95 approved these changes

2022-10-26 00:30 UTC, merged

2022-10-26 00:36 UTC, yangc95 commented
Thanks for this entry @borntofrappe 🥳

live link: https://www.codecademy.com/resources/docs/cpp/math-functions/fmin
<img width="837" alt="Screen Shot 2022-10-25 at 8 35 46 PM" src="https://user-images.githubusercontent.com/72277593/197907255-1fd63f3c-933a-455c-a4d0-830e21e2ec7f.png">

cc: @SSwiniarski