Created to-radian function for java.
Codecademy/docs pull request #1048
Opened 2022-10-05 16:18 UTC by manish-singh-bisht

Created to radian function for java.
Solved issue #921.

2022-10-05 16:24 UTC, manish-singh-bisht commented
Hi completed the task ,please review it.

2022-10-05 16:49 UTC, manish-singh-bisht commented
Hey if there's any issue, I will resolve it.  Thank you.

2022-10-05 19:01 UTC, SSwiniarski requested changes
@manish-singh-bisht, I completed the first review and left some comments. Note you still need to sign the [CLA](https://cla-assistant.io/Codecademy/docs?pullRequest=1048).

2022-10-06 09:25 UTC, manish-singh-bisht commented
Hey resolved all the issues,please review it,

2022-10-06 11:55 UTC, SSwiniarski reviewed
@manish-singh-bisht, I had a few more comments.

2022-10-06 11:55 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/to radian/to-radian.md
> +The **`Math.toRadians`** method returns the measurement of an angle in deg to an equivalent angle in radians.
```suggestion
The **`Math.toRadians`** method returns the measurement of an angle in degrees to an equivalent angle in radians.
```

2022-10-06 11:55 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/to radian/to-radian.md
> +The conversion from degrees to radian is generally inexact.
```suggestion
The conversion from degrees to radians is generally inexact.
```

2022-10-06 11:55 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/to radian/to-radian.md
> +     double deg1 = 180.0;
```suggestion
    double deg1 = 180.0;
```

2022-10-06 11:55 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/to radian/to-radian.md
> +     double deg2= 45.0;
```suggestion
    double deg2= 45.0;
```

2022-10-06 12:31 UTC, manish-singh-bisht commented
Hey solved the issues, please review it.

2022-10-06 16:18 UTC, manish-singh-bisht commented
Hey solved all mentioned changes , please review it.

2022-10-06 16:32 UTC, SSwiniarski approved these changes
@manish-singh-bisht, Looks good for the second review.

2022-10-06 20:02 UTC, yangc95 commented
> Hey will it get merged?

Hi @manish-singh-bisht, the review process requires two maintainers to approve prior to merging. Currently, there is one approval, so half-way there!

2022-10-12 19:52 UTC, HishamT requested changes
Finished second review. Left some suggestions.

2022-10-12 19:52 UTC, HishamT commented on content/java/concepts/math-methods/terms/to radian/to-radian.md
> +The **`Math.toRadians`** method returns the measurement of an angle in degrees to an equivalent angle in radians.
~Math.toRadians~ Math.toRadians()

2022-10-12 19:52 UTC, HishamT commented on content/java/concepts/math-methods/terms/to radian/to-radian.md
> +The following example uses `Math.toRadians()` to return radian measurement of 180 and 45 degrees:
~The following example uses `Math.toRadians()` to return radian measurement of 180 and 45 degrees:~ 

Consider the following sentence instead:

The following example uses `Math.toRadians()` to convert 180 degrees and 45 degrees to radians:

2022-10-13 01:08 UTC, manish-singh-bisht commented
Hey @HishamT ,please review it.

2022-10-13 19:33 UTC, HishamT approved these changes
LGTM

2022-10-14 17:06 UTC, yangc95 reviewed
@manish-singh-bisht this almost looks ready for merge!

I just had one suggestion and also a request to change the directory name from `to radian` to `to-radian`

2022-10-14 17:53 UTC, manish-singh-bisht commented
Hey @yangc95  please review it.Thank you.

2022-10-17 17:35 UTC, yangc95 approved these changes

2022-10-17 17:36 UTC, merged

2022-10-17 17:44 UTC, yangc95 commented
@manish-singh-bisht merged! I made a small edit here [03be8f0](https://github.com/Codecademy/docs/pull/1048/commits/03be8f0b19093854b9966506c191fc9a1c887550) prior to merge

link: https://www.codecademy.com/resources/docs/java/math-methods/to-radian

cc: @HishamT @SSwiniarski

2022-10-18 13:07 UTC, manish-singh-bisht commented
@yangc95 Thank you for the advice of creating a new branch, I will definitely follow this practice. I will choose to remain anonymous. Thank you.