correct cosh readme file
Codecademy/docs pull request #1050
Opened 2022-10-05 23:18 UTC by kitrak-rev

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-06 06:46 UTC, kitrak-rev commented
@yangc95  Can you check and approve the workflow

2022-10-06 13:18 UTC, Dusch4593 commented
Hey @kitrak-rev make sure to check off those boxes under the "Checklist" at the top of this page to ensure you set up the PR correctly. 😄

2022-10-08 13:38 UTC, SSwiniarski requested changes
@kitrak-rev I did a first review and left a few comments.

2022-10-08 13:38 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/cosh/cosh.md
> +where `n` is the angle in `radians`
```suggestion
Where `n` is the angle in radians.
```

2022-10-08 13:38 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/cosh/cosh.md
> +`Return type is double, float or long double.
```suggestion
Return type is double, float or long double.
```

2022-10-08 13:38 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/cosh/cosh.md
> +cosh(x) =  (e <sup>x</sup> + e<sup>−x</sup> )/2
```suggestion
cosh(x) =  (e<sup>x</sup> + e<sup>−x</sup>)/2
```

2022-10-08 13:38 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/cosh/cosh.md
> +Use `cosh()` to return the hyperbolic cosine of `0.0` radians.
```suggestion
This example uses `cosh()` to return the hyperbolic cosine of `0.0` radians:
```

2022-10-08 13:38 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/cosh/cosh.md
> +Use `cosh()` to return the hyperbolic cosine of `1.0` radians.
```suggestion
This example uses `cosh()` to return the hyperbolic cosine of `1.0` radians:
```

2022-10-08 13:44 UTC, SSwiniarski commented
@kitrak-rev: This PR is a duplicate of [1069](https://github.com/Codecademy/docs/pull/1069), so I'm closing it.

2022-10-08 13:44 UTC, closed without merging