Added signbit() to cpp docs
Codecademy/docs pull request #1053
Opened 2022-10-06 04:41 UTC by AravindShounik

### Description

Closes #989 
Created folder named signbit at path: cpp/concepts/math-functions/terms/
Created a file named signbit.md, which includes all relevant data for a Term Entry Issue.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-08 01:55 UTC, AravindShounik commented
Could you please review the changes

2022-10-08 13:51 UTC, SSwiniarski requested changes
@AravindShounik, I did a first review and left a few comments.

2022-10-08 13:51 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/signbit/signbit.md
> +Description: 'Returns true if the floating point is negative and false if floating point is positive.'
```suggestion
Description: 'Returns true if the floating point argument is negative and false if floating point argument is positive.'
```

2022-10-08 13:51 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/signbit/signbit.md
> +The `signbit()` function returns true if the sign of the  number is negative and false if sign is positive.
```suggestion
The **`signbit()`** function returns true if the sign of the argument is negative and false if its sign is positive.
```

2022-10-08 13:51 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/signbit/signbit.md
> +    double a=9.0,b=0.0;
```suggestion
    double a=9.0, b=0.0;
```

2022-10-08 13:51 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/signbit/signbit.md
> +        std::cout<<"c tends to positive infinity";
```suggestion
        std::cout << "c tends to positive infinity";
```

2022-10-08 13:51 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/signbit/signbit.md
> +        std::cout<<"c tends to negative infinity";
```suggestion
        std::cout << "c tends to negative infinity";
```

2022-10-08 13:51 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/signbit/signbit.md
> +    std::cout<<"n is negative";
```suggestion
    std::cout << "n is negative";
```

2022-10-08 13:51 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/signbit/signbit.md
> +    std::cout<<"n is positive";
```suggestion
    std::cout << "n is positive";
```

2022-10-08 16:51 UTC, AravindShounik commented
I have updated the file according to your suggestions. @SSwiniarski. Please look into them

2022-10-08 17:37 UTC, SSwiniarski approved these changes
@AravindShounik one extra space needs to be trimmed, but otherwise looks good for a second review.

2022-10-08 17:37 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/signbit/signbit.md
> +The **`signbit()`** function returns true if the sign of the  argument is negative and false if its sign is positive.
```suggestion
The **`signbit()`** function returns true if the sign of the argument is negative and false if its sign is positive.
```

2022-10-09 16:22 UTC, AravindShounik commented
Thank you for taking your time to review my PR @SSwiniarski . Eagerly waiting for the next review.

2022-10-27 03:54 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/signbit/signbit.md
> +int main() {
```suggestion
int main()
{
```

2022-10-31 17:09 UTC, Dusch4593 commented
@AravindShounik let us know if you need any help with implementing the latest round of feedback. Today is the last day to have your merged PR count for Hacktoberfest!

2022-11-04 04:36 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/signbit/signbit.md
> +    if (std::signbit(c)==false)
```suggestion
    if (std::signbit(c) == false)
```

2022-11-04 04:36 UTC, yangc95 approved these changes

2022-11-04 04:37 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/signbit/signbit.md
> +Argument `n` must be of type `double`/`float`/`long double`/`int`, and the return value will be of that type. This function also detects the signs of zeroes, infinities and `NaN`s.
```suggestion
Argument `n` must be of type `double`/`float`/`long double`/`int`, and the return value will be of that type. This function also detects the signs of zeroes, infinities, and `NaN`s.
```

2022-11-04 04:38 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/signbit/signbit.md
> +Use `signbit()` and outputs a string about whether the integer is positive or negative:
```suggestion
The example below outputs a string about whether the integer is positive or negative:
```

2022-11-04 04:40 UTC, merged

2022-11-04 04:53 UTC, yangc95 commented
@AravindShounik very cool, this is the live link: https://www.codecademy.com/resources/docs/c-sharp/variables

<img width="830" alt="Screen Shot 2022-11-04 at 12 52 47 AM" src="https://user-images.githubusercontent.com/72277593/199890551-4276d1e7-aba5-4616-8320-2404aa4afe28.png">

cc: @SSwiniarski