fix typos in html documentations
Codecademy/docs pull request #1061
Opened 2022-10-06 08:48 UTC by garanews

fix typos in html documentations

2022-10-06 15:55 UTC, SSwiniarski approved these changes
@garanews, Looks good.

2022-10-06 17:08 UTC, Dusch4593 requested changes
@garanews Finished with my review. Aside from the comments I posted, here are other suggestions for this PR:

Under `noscript.md`:
- On line # 15, let's change "Javascript" to "JavaScript".
- On line # 19, under the "Syntax" section, let's change the code block signature from \```html to \```pseudo.

Under `u.md`:
- On line # 18, let's add a `>` in front of `**Note:**`.
- - On line # 22, under the "Syntax" section, let's change the code block signature from \```html to \```pseudo.

Under `videos.md`:
- On line # 3, let's shorten the `Description` to (ideally) 150 characters or less.
- On line # 15, let's **bold** "videos" like so: `Embedding **videos** within a site ...`.
- Let's add periods (`.`) to the end of the list items on lines # 47 through 50 as well as lines # 75 through # 78.

2022-10-06 17:08 UTC, Dusch4593 commented on content/html/concepts/elements/terms/noscript/noscript.md
> +The output might look like this if Javascript is disabled or not available:
```suggestion
The output might look like this if JavaScript is disabled or not available:
```

2022-10-06 17:08 UTC, Dusch4593 commented on content/html/concepts/videos/videos.md
>  - Use the `prefers-reduced-motion` CSS media query in order to disable autoplaying videos for certain users
```suggestion
- If the video is purely decorative, `aria-hidden="true"` can denote to screen readers that the video provides no additional context or content and is purely decorative.
- The `prefers-reduced-motion` CSS media query can be used to disable autoplaying videos for certain users.
```

2022-10-06 17:08 UTC, Dusch4593 commented on content/html/concepts/elements/terms/u/u.md
> +<p>You can use this tag to indicate things such as <u>misspelt</u> words.</p>
```suggestion
<p>You can use this element to indicate things such as <u>misspelt</u> words.</p>
```

2022-10-07 08:03 UTC, garanews commented
just missing the downsizing of description, I would't remove something relevant...

2022-10-07 09:56 UTC, Dusch4593 commented
@garanews Agreed, relevance shouldn't be left out. The `Description` (usually on line # 3 of any entry file) is more for SEO-purposes than anything else. For the one in `video.md`, maybe something like the following:

```
Embedding videos creates more lively and informative web pages that are more attractive to visitors but costly in bandwidth and accessibility.
```

2022-10-31 14:12 UTC, Dusch4593 approved these changes
@garanews LGTM for merge! 🚀 

I made a few small edits in 491f4ea7c57870834498d9c4677faeee57277610.

2022-10-31 14:14 UTC, merged