fix typos in c documentation
Codecademy/docs pull request #1065
Opened 2022-10-06 09:17 UTC by garanews

fix typos in c documentation

2022-10-06 16:05 UTC, SSwiniarski requested changes
@garanews, I did a review and left one comment.

2022-10-06 16:05 UTC, SSwiniarski commented on content/c/concepts/variables/variables.md
> +Description: 'A variable is a location in computer memory used to store data, usually for use in a program. To declare a variable in C, the type of variable is first included, followed by the name, a
```suggestion
Description: 'A variable is a location in computer memory used to store data.'
```

2022-10-29 14:08 UTC, Dusch4593 requested changes
@garanews Let's **bold** the concept "variable" on line # 15 in `variables.md`. That's all from me. 😄

cc: @SSwiniarski anything I might have missed?

2022-11-10 00:56 UTC, Dusch4593 approved these changes
@garanews LGTM! 👍🏻

I made the following edits in 1e22e811dbafb8555ee7f88195ba77989fc1cdf8:

- **Bolded** the first mention of the concept "variables" in `variables.md`.
- Light rephrasing/rearranging in the Syntax section including a new \```pseudo code block.

2022-11-19 14:16 UTC, SSwiniarski approved these changes
Looks good to merge

2022-11-19 14:16 UTC, merged