[New Term] C++ Math Functions: `rint()`
Codecademy/docs pull request #1071
Opened 2022-10-06 18:56 UTC by chiragcode11

Description
Closes #985 

Added rint() function within the C++ arithmetic library.
Added description with examples.
Type of Change
Added rint() function within the C++ Math library.
Checklist
 

- [x] All writings are my own.
- [x]  My entry follows the Codecademy Docs style guide.
- [x]  My changes generate no new warnings.
- [x]  I have performed a self-review of my own writing and code.
- [x]  I have checked my entry and corrected any misspellings.
- [x]  I have made corresponding changes to the documentation if needed.
- [x]  I have confirmed my changes are not being pushed from my forked main branch.
- [x]  I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x]  Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes # in the "Description" above).

2022-10-06 18:57 UTC, chiragcode11 commented
I have created a new PR from another branch

2022-10-06 18:58 UTC, Dusch4593 commented
Thank you very much @chiragcode11 😄 Taking a look at this now.

2022-10-06 19:10 UTC, Dusch4593 requested changes
@chiragcode11 Finished with my review and left you some comments/suggestions to implement. 😄

2022-10-06 19:10 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/rint/rint.md
> +
```suggestion

The **`rint()`** function rounds the argument to an integral value using the current rounding mode.

```

2022-10-06 19:10 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/rint/rint.md
> +Argument must be a `double`/`float`/`long double`, and the return value will be same type.
```suggestion
The `x` parameter must be a `double`, `float`, or `long double`. The return value will be the same data type.
```

2022-10-06 19:10 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/rint/rint.md
> +The rint() function rounds the argument x to an integral value, using the rounding direction specified by fegetround() and returns the value. By default, the rounding direction is set to 'to-nearest'
```suggestion

The rounding direction specified by the `fegetround()` function, with the default direction set as 'to-nearest'. The rounding direction can be set to other values using `fesetround()` function.
```

2022-10-06 19:10 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/rint/rint.md
> +The following example uses the `rint()` function to find the value of x after rounding off:
```suggestion
The following example uses the `rint()` function to find the value of `x` after rounding off:
```

2022-10-06 19:13 UTC, chiragcode11 commented
updated the suggestion you gave, thank you.

2022-10-06 19:21 UTC, Dusch4593 approved these changes
@chiragcode11 LGTM for the next review! 😄

Just left one minor suggestion.

2022-10-06 19:21 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/rint/rint.md
> +The rounding direction specified by the `fegetround()` function, with the default direction set as 'to-nearest'. The rounding direction can be set to other values using `fesetround()` function.
```suggestion
The rounding direction is specified by the `fegetround()` function, with the default direction set as 'to-nearest'. The rounding direction can be set to other values using `fesetround()` function.
```

2022-10-06 19:22 UTC, chiragcode11 commented
@Dusch4593 done as per your suggestion

2022-10-06 19:30 UTC, chiragcode11 commented
can we get a hacktoberfest verified label

2022-10-10 11:51 UTC, Dusch4593 commented
@chiragcode11 Since I conducted the 1st review, @HishamT will conduct the second. 😄

2022-10-22 15:42 UTC, SSwiniarski approved these changes
@chiragcode11, @Dusch4593 Dropped by for a second review, and everything looks good as-is.

2022-10-23 00:19 UTC, Dusch4593 approved these changes
@chiragcode11 I just had one more suggestion. 😄

2022-10-23 19:04 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/rint/rint.md
> +Description: 'The rint() function in C++ rounds the argument to an integral value using the current rounding mode.'
```suggestion
Description: 'Rounds the argument to an integral value using the current rounding mode.'
```

2022-10-25 21:11 UTC, Dusch4593 commented
@chiragcode11 This looks ready to merge! I made a few last-minute edits in bdf0589105c3a67be6b34123f9de4976c295b2c2, including the following:

- Removed extra newline.
- Converted text about `fegetround()`/`fesetround()` to a **note**.

2022-10-25 21:13 UTC, merged

2022-10-25 21:17 UTC, Dusch4593 commented
Congrats, @chiragcode11! Your contribution to Codecademy Docs should now be live! It can be viewed here: https://www.codecademy.com/resources/docs/cpp/math-functions/rint

You're currently anonymous, but if you want to make yourself public, make sure to add your GitHub handle to your Codecademy profile:

<img width="775" alt="Screen Shot 2022-10-25 at 5 16 25 PM" src="https://user-images.githubusercontent.com/23144845/197883786-f4cd6d49-f455-4e44-8392-98a5d4405080.png">