Added toDegrees doc
Codecademy/docs pull request #1078
Opened 2022-10-08 12:51 UTC by sotiriszogos

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-08 12:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1078) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1078) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1078) it.</sub>

2022-10-08 14:27 UTC, Dhanunjay18 commented
Please assignt it to me

2022-10-08 15:08 UTC, Dusch4593 commented
@Dhanunjay18 You've already been assigned to some issues; go ahead and get started on the PRs for those. We look forward to reviewing them. 😄

2022-10-09 14:20 UTC, SSwiniarski requested changes
@sotiriszogos, I did a first review and left some comments to be addressed. Also you should edit the description of this entry to complete the checklist.

2022-10-09 14:20 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/toDegrees/toDegrees.md
> +---
@sotiriszogos please review the content standards [here](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and the term entry template [here](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md) to properly add metadata to this entry. You can also look at the source of any of the existing term entries to get an idea of what we're looking for.

2022-10-09 14:20 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/toDegrees/toDegrees.md
> +Description: 'It returns the measurement of the angle x in degrees.'
```suggestion
Description: 'Returns the measurement in degrees of an angle given in radians.'
```

2022-10-09 14:20 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/toDegrees/toDegrees.md
> +The **`Math.toDegrees()`** method is a built-in math function in java which is used to convert an angle measured in radians to an approximately equivalent angle measured in degrees.
```suggestion
The **`.toDegrees()`** method is a built-in math function in Java which is used to convert an angle measured in radians to an approximately equivalent angle measured in degrees.
```

2022-10-09 14:20 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/toDegrees/toDegrees.md
> +The following example showcases the `.toDegrees()` method being applied to two variables:
```suggestion
The following example demonstrates the `.toDegrees()` method being applied to two variables:
```

2022-10-10 15:42 UTC, SSwiniarski approved these changes
@sotiriszogos, looks good for a second review.

2022-10-12 19:45 UTC, HishamT approved these changes
Looks good! One minor change requested.

2022-10-12 19:45 UTC, HishamT commented on content/java/concepts/math-methods/terms/toDegrees/toDegrees.md
> +The return type of the `.toDegrees()` method is a double. The data type of the `x` parameter is also a double.
"double" is a keyword in Java. It should be surrounded with backticks like so: `double`.

2022-10-19 14:36 UTC, Dusch4593 requested changes
@sotiriszogos Had some comments/suggestions to offer, as well. After this feedback is implemented, we should be good to merge. 😄

2022-10-19 14:36 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/toDegrees/toDegrees.md
> +The **`.toDegrees()`** method is a built-in math function in Java which is used to convert an angle measured in radians to an approximately equivalent angle measured in degrees.
```suggestion
The **`.toDegrees()`** method converts an angle, measured in radians, to an approximately equivalent angle, measured in degrees.
```

2022-10-19 14:36 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/toDegrees/toDegrees.md
> +Description: 'Returns the measurement in degrees of an angle in radians.'
```suggestion
Description: 'Returns an angle measurement converted from radians to degrees.'
```

2022-10-19 14:36 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/toDegrees/toDegrees.md
> +Math.toDegrees(double x)
```suggestion
Math.toDegrees(angle)
```

2022-10-19 14:36 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/toDegrees/toDegrees.md
> +The return type of the `.toDegrees()` method is a `double`. The data type of the `x` parameter is also a `double`.
```suggestion
The data type of the `angle` parameter and return value of the `.toDegrees()` method is a `double`.
```

2022-10-19 14:36 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/toDegrees/toDegrees.md
> +}
```suggestion
public class TestDegrees {
  public static void main(String args[]) {
    double x = 0.5235987756;
    System.out.println(Math.toDegrees(x));
    
    double y = 1.0471975512;
    System.out.println(Math.toDegrees(y));
  }
} 
```

2022-10-19 14:36 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/toDegrees/toDegrees.md
> +```java
```suggestion
```shell
```

2022-10-31 13:21 UTC, Dusch4593 commented
Hey @sotiriszogos just wanted to check in and see how things were going with you and my latest comments/suggestions. Happy to help and/or answer questions. And remember, today is the last day for this PR to count towards Hacktoberfest.

2022-10-31 17:21 UTC, sotiriszogos commented
Added all required changes

2022-10-31 17:45 UTC, Dusch4593 approved these changes
@sotiriszogos LGTM! 🚀

2022-10-31 17:46 UTC, merged

2022-10-31 17:53 UTC, Dusch4593 commented
Congrats and thank you so much for contributing to Codecademy Docs, @sotiriszogos! 🚀 🥳

The entry should now be live: https://www.codecademy.com/resources/docs/java/math-methods/toDegrees

Currently, your profile is listed anonymously on the entry page. To have it displayed, you'll need to add your GitHub username to your Codecademy profile, log out of Codecademy, and log back in through your GitHub account. Let us know if you'd need any help with doing this:

<img width="1000" alt="Screen Shot 2022-10-31 at 1 50 34 PM" src="https://user-images.githubusercontent.com/23144845/199075354-e9f314f1-3fbe-4234-bf61-2667725e73f0.png">

Looking forward to working with you on your next contribution! 😄

A few things to note for the next one:

- Make sure to make a **_new pull request branch_** for the changes you intend on making. We generally discourage contributors from pushing new changes from their `main` branch because this could cause merge conflicts with the base `main` branch for `Codecademy/docs`.
- When you create a PR, always make sure to the check off the boxes under "Checklist" so that you are assured that you have set up your PR correctly.