Add log10.md
Codecademy/docs pull request #1082
Opened 2022-10-08 18:45 UTC by Sparsh47

Description
added new term entry C++ Math Functions: log10()

#957 

Type of Change
Adding a new entry
Checklist
 

- [ ] All writings are my own.
- [ ]  My entry follows the Codecademy Docs style guide.
- [ ]  My changes generate no new warnings.
- [ ]  I have performed a self-review of my own writing and code.
- [ ]  I have checked my entry and corrected any misspellings.
- [ ]  I have made corresponding changes to the documentation if needed.
- [ ]  I have confirmed my changes are not being pushed from my forked main branch.
- [ ]  I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ]  Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes # in the "Description" above).

2022-10-08 18:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1082) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1082) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1082) it.</sub>

2022-10-09 09:05 UTC, Sparsh47 commented
I have already signed the cla agreement but it is still showing not signed yet. What to do  now?
![image](https://user-images.githubusercontent.com/95901042/194747980-0b92d80e-4a92-44b8-b73b-b25d2f5062f9.png)

2022-10-09 14:54 UTC, SSwiniarski commented
> I have already signed the cla agreement but it is still showing not signed yet. What to do now? ![image](https://user-images.githubusercontent.com/95901042/194747980-0b92d80e-4a92-44b8-b73b-b25d2f5062f9.png)

@Sparsh47, Do you have another account? It's actually complaining about @Sparsh1807. If that's also your account, signing with that may solve the issue.

2022-10-09 14:58 UTC, SSwiniarski requested changes
@Sparsh47, I did a first review and left a few comments to be addressed.

2022-10-09 14:58 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/log10/log10.md
> +If the `x` parameter is less than or equal to zero, then a domain error will occur. If `x` is equal to zero, a pole error may occur where the result has reached the point of infinity and cannot be ex
```suggestion
If the `x` parameter is less than or equal to zero, then a domain error will occur. If `x` is equal to zero, a pole error may occur where the result has reached the point of infinity and cannot be expressly returned.
```

2022-10-09 14:58 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/log10/log10.md
> +The following example uses the `log10()` function to find the natural log of `5`:
```suggestion
The following example uses the `log10()` function to find the base-10 log of `5`:
```

2022-10-09 14:58 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/log10/log10.md
> +The following example is runnable and returns the natural log of `10`:
```suggestion
The following example is runnable and returns the base-10 log of `10`:
```

2022-10-09 14:58 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/log10/log10.md
> +The **log10()** function returns the base-_10_ logarithm of the argument.
```suggestion
The **log10()** function returns the base-10 logarithm of the argument.
```

2022-10-09 15:16 UTC, Sparsh47 commented
i have successfully committed all the changes. Please review this again.

2022-10-21 15:52 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/log10/log10.md
> +```cpp
```suggestion
```pseudo
```

2022-10-21 15:54 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/log10/log10.md
> +If the `x` parameter is less than or equal to zero, then a domain error will occur. If `x` is equal to zero, a pole error may occur where the result has reached the point of infinity and cannot be ex
```suggestion
If the `x` parameter is negative (less than zero), then a domain error will occur. If `x` is equal to zero, a pole error may occur where the result has reached the point of infinity and cannot be expressly returned.
```

2022-10-21 16:48 UTC, Dusch4593 approved these changes
@Sparsh47 LGTM! 👍🏻

2022-10-21 16:51 UTC, merged

2022-10-21 16:56 UTC, Dusch4593 commented
Thank you so much for your contribution to Codecademy Docs, @Sparsh47! 🎉 🎊

The entry should now be live: https://www.codecademy.com/resources/docs/cpp/math-functions/log10

Also, let me know if you'd like to be credited on the entry page or remain anonymous 😄

<img width="834" alt="Screen Shot 2022-10-21 at 12 55 32 PM" src="https://user-images.githubusercontent.com/23144845/197249124-55375b48-86e3-4f54-9b40-94ec7cfcf6ff.png">

2022-11-14 19:19 UTC, yangc95 commented
@Sparsh47 congrats on the public entry!

I had two follow-up edits for this entry:
- Move the opening bracket to a new line for both code snippets.
- Remove the term "expressly" from line 23 due to its dual meaning which can be confusing (quick or explicit), it's also unnecessary.

Let's open a new PR for these edits. We can label this as a typo and it can be merged right away. Thanks!

cc: @Dusch4593 @SSwiniarski