Add new entry on file structure
Codecademy/docs pull request #1086
Opened 2022-10-09 04:03 UTC by YanisaHS

### Description

I added the file-system-structure concept and file-system-structure.md file inside. I also added file-system-structure.png to the media folder. The file:

1. Introduces the file system structure
2. Elaborates on the root, directories, and files
3. Gives an example of a file system structure using the Filesystem Hierarchy Standard (FHS) in Linux

Just noting that I also changed "file structure" to "file system structure" because I thought it was more descriptive. I can change it back though if the old name is preferred!

Closes #779 

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-13 15:55 UTC, SSwiniarski approved these changes
@YanisaHS, I did a first review and it looks good to go right to review 2.

2022-10-19 17:23 UTC, yangc95 reviewed
@YanisaHS I went ahead and did a second review!

Please let me know if you have any concerns with any of my comments and tag me once you've looked them over.

2022-10-19 17:23 UTC, yangc95 commented on content/general/concepts/file-system-structure/file-system-structure.md
> +The root or root directory is the highest level directory of the file system structure. In macOS, Linux, and other UNIX-like operating systems, the root is represented with a forward slash (/). In Wi
```suggestion
The root or root directory is the highest level directory of the file system structure. In macOS, Linux, and other UNIX-like operating systems, the root is represented with a forward slash (`/`). In Windows, the root is represented by the drive name and a backslash (`\`).
```

2022-10-19 17:23 UTC, yangc95 commented on content/general/concepts/file-system-structure/file-system-structure.md
> +Files are storage units on a computer which store information on the file contents, instructions needed to read these contents, and where the contents are stored. The file’s location in the directory
```suggestion
Files are storage units on a computer which contain information on file contents, instructions needed to read them, and where they are stored. A file’s location in the directory system is referred to as the [file path](https://www.codecademy.com/resources/docs/general/file-paths), and the [file format](https://www.codecademy.com/resources/docs/general/file-formats) or type determines how data in the file is created, stored, and read.
```

2022-10-19 17:23 UTC, yangc95 commented on content/general/concepts/file-system-structure/file-system-structure.md
> +The Filesystem Hierarchy Standard (FHS) is one example of a defined file system structure. The FHS is only for [UNIX](https://www.codecademy.com/resources/docs/general/unix) systems, and is most popu
```suggestion
The Filesystem Hierarchy Standard (FHS) is one example of a defined file system structure. The FHS is for [UNIX](https://www.codecademy.com/resources/docs/general/unix) systems, and is most popularly used in [Linux](https://www.codecademy.com/resources/docs/general/linux). It is maintained by the Linux Foundation, and most Linux distributions follow the FHS.
```

2022-10-19 17:23 UTC, yangc95 commented on content/general/concepts/file-system-structure/file-system-structure.md
> +- `/sys`: Stores information on the Linux kernel and various system devices
```suggestion
- `/bin` stores all binary executable files.
- `/tmp` stores all temporary files.
- `/sys` stores information on the Linux kernel and various system devices.
```
```suggestion
- `/bin`: Stores all binary executable files
- `/tmp`: Stores all temporary files
- `/sys`: Stores information on the Linux kernel and various system devices
```

2022-10-19 17:23 UTC, yangc95 commented on content/general/concepts/file-system-structure/file-system-structure.md
> +The purpose of using a defined file system structure like the FHS is so users and software can predict the locations of files and directories. This makes it easier to install, run, and use software.
```suggestion
The purpose of using a defined file system structure like the FHS is so users and software can predict the locations of files and directories. This makes it easier to compile, install, and run software.
```

2022-10-20 03:35 UTC, YanisaHS commented
Thank you for the feedback @yangc95 ! I've finished reviewing the changes for this one now 🥳

2022-10-20 14:45 UTC, yangc95 approved these changes

2022-10-20 16:11 UTC, Dusch4593 requested changes
Some comments/suggestions 😄

2022-10-20 16:11 UTC, Dusch4593 commented on content/general/concepts/file-system-structure/file-system-structure.md
> +The file system structure is a basic method for operating systems to organize information. This structure defines how certain key directories and files are organized, and how future directories and f
```suggestion
The **file system structure** defines how information in key (existing and future) directories and files are organized and how stored in an operating system.

Although different operating systems may have different standards, all major operating systems have similar characteristics and use a hierarchical structure of directories branching off the root directory. The image below illustrates an example of the hierarchy in a sample file system structure.
```

2022-10-20 16:11 UTC, Dusch4593 commented on content/general/concepts/file-system-structure/file-system-structure.md
> +The root or root directory is the highest level directory of the file system structure. In macOS, Linux, and other UNIX-like operating systems, the root is represented with a forward slash (`/`). In
```suggestion
The root directory, or "root", is the highest-level directory of the file system structure. In macOS, [Linux](https://www.codecademy.com/resources/docs/open-source/linux), and other [UNIX](https://www.codecademy.com/resources/docs/general/unix)-like operating systems, the root is represented with a forward slash (`/`). In Windows, the root is represented by the drive name and a backslash (`\`).
```

2022-10-20 16:11 UTC, Dusch4593 commented on content/general/concepts/file-system-structure/file-system-structure.md
> +The Filesystem Hierarchy Standard (FHS) is one example of a defined file system structure. The FHS is for [UNIX](https://www.codecademy.com/resources/docs/general/unix) systems, and is most popularly
```suggestion
The Filesystem Hierarchy Standard (FHS) is one example of a defined file system structure. The FHS is for UNIX systems, and is most popularly used in Linux. It is maintained by the Linux Foundation, and most Linux distributions follow the FHS.
```

2022-10-20 17:28 UTC, YanisaHS commented
Thank you for the feedback @Dusch4593 ! Done! 🥳

2022-10-22 17:04 UTC, yangc95 commented
@Dusch4593 did we have anything else to change here before merging?

2022-10-22 22:03 UTC, Dusch4593 commented
@yangc95 @YanisaHS This seems ready to merge. 🚀 

I made one little change in 91e878d46d6768700ad38d07fdd9f99334ec0b74 where I broke up the paragraph on line # 30 into separate ones (2-3 sentences each). The last two sentences seemed to explore a new idea in subdirectories and how they relate to their parents and to one another.

2022-10-22 22:03 UTC, Dusch4593 approved these changes

2022-10-22 22:54 UTC, merged

2022-10-22 22:59 UTC, Dusch4593 commented
Thank you for another awesome entry, @YanisaHS! 🚀 🎊

The live entry can be viewed here: https://www.codecademy.com/resources/docs/general/file-system-structure