Cpp math hypot
Codecademy/docs pull request #1087
Opened 2022-10-09 09:43 UTC by Sparsh47

Description
added new term entry C++ Math Functions: hypot()

#961 

Type of Change
Adding a new entry

Checklist
- [x] All writings are my own.
- [x]  My entry follows the Codecademy Docs style guide.
- [x]  My changes generate no new warnings.
- [x]  I have performed a self-review of my own writing and code.
- [x]  I have checked my entry and corrected any misspellings.
- [x]  I have made corresponding changes to the documentation if needed.
- [x]  I have confirmed my changes are not being pushed from my forked main branch.
- [x]  I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x]  Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes # in the "Description" above).

2022-10-09 09:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1087) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1087) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1087) it.</sub>

2022-10-10 17:15 UTC, SSwiniarski requested changes
@Sparsh47, I left a couple of comments. But yo also need to delete the log-10 entry from this branch to keep from conflicting with [1082](https://github.com/Codecademy/docs/pull/1082).

2022-10-11 08:40 UTC, Sparsh47 commented
Can I give a new PR in this as removing this second commit would be very difficult?

2022-10-11 16:03 UTC, SSwiniarski commented
> Can I give a new PR in this as removing this second commit would be very difficult?

@Sparsh47 : You can withdraw this and do a new PR if you want. Just make sure not to include the extra conflicting entry.

2022-10-11 17:58 UTC, closed without merging