Create atanh.md
Codecademy/docs pull request #1090
Opened 2022-10-10 19:07 UTC by sumedhav2004

## Description
 added new term entry C++ Math Functions: atanh() [#955](https://github.com/Codecademy/docs/issues/955)

 ## Type of Change
 Adding a new entry
 
 ## Checklist
 * [x]   All writings are my own.
 * [x]    My entry follows the Codecademy Docs style guide.
 * [x]    My changes generate no new warnings.
 * [x]    I have performed a self-review of my own writing and code.
 * [x]    I have checked my entry and corrected any misspellings.
 * [x]    I have made corresponding changes to the documentation if needed.
 * [x]    I have confirmed my changes are not being pushed from my forked main branch.
 * [x]    I have confirmed that I'm pushing from a new branch named after the changes I'm making.
 * [x]    Under "Development" on the right, I have linked any issues that are relevant to this PR.

2022-10-10 19:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1090) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1090) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1090) it.</sub>

2022-10-12 16:13 UTC, SSwiniarski requested changes
@sumedhav2004, I did a first review and left a few comments.

2022-10-12 16:13 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/atanh/atanh.md
> +The **`atanh()`** function in C++ returns the arc hyperbolic tangent (inverse hyperbolic tangent) of a number in `radians`.The area hyperbolic tangent is the inverse operation of the hyperbolic tange
```suggestion
The **`atanh()`** function in C++ returns the arc hyperbolic tangent (inverse hyperbolic tangent) of a number in radians.
```

2022-10-12 16:13 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/atanh/atanh.md
> +`x`: The value of mandatory argument in range `[-1,1]`.
```suggestion
`x` is the value of mandatory argument in range `[-1,1]`.
```

2022-10-12 16:13 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/atanh/atanh.md
> +## Parameter
Remove the parameter header and place this sentence at the end of the "Syntax" section.

2022-10-12 16:13 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/atanh/atanh.md
> +Output:
```suggestion
This example produces the following output:

```

2022-10-12 16:13 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/atanh/atanh.md
> +## Prototype [C++11 Standard]
I don't think we need this section. It's at odds with all the other math entries.

2022-10-12 16:13 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/atanh/atanh.md
> +## Error Handling
I'd remove the header and include this under "Syntax"

2022-10-12 16:13 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/atanh/atanh.md
> +If the argument is not on the interval `[-1, +1]`, a range error occurs.
I'd take all of these following lines and make them a bulleted list.

2022-11-15 17:05 UTC, SSwiniarski commented
@sumedhav2004, just checking up if you have any issues addressing the above comments. Let us know if you need any help.

2022-11-22 17:50 UTC, yangc95 commented
> @sumedhav2004, just checking up if you have any issues addressing the above comments. Let us know if you need any help.

_Direct changes will be made in T-1 week if there are no further communications._

2022-12-01 18:55 UTC, SSwiniarski commented
@sumedhav2004 in the interest of getting this merged, I went ahead and applied the above changes.

@Dusch4593, @yangc95 anything else that needs to be edited before we merge this?

2022-12-03 13:03 UTC, Dusch4593 approved these changes
cc: @sumedhav2004 @SSwiniarski @yangc95 

LGTM as well! 👍🏻

I made the following edits in ec6265212fb9642fffea6a11eb027e03badbb04b that I wanted to note here:

- Removed reference to "arc hyperbolic tangent" because [it's noted in other docs sites](https://en.cppreference.com/w/cpp/numeric/math/atanh#:~:text=Although%20the%20C,area%20hyperbolic%20tangent%22.) that these kinds of functions refer to the _area_, not the _arc_.
- Rephrasing on line # 22, including removal of backticks from range and insertion of link to C++ Data Types entry.
- Separated out last four list items to point out they refer to C++ versions that support IEEE floating-point arithmetic.
- Rephrase on lines # 36 and # 67.

2022-12-03 13:04 UTC, merged

2022-12-03 13:08 UTC, Dusch4593 commented
Congrats and thank you for your contribution to Codecademy Docs, @sumedhav2004! 

The entry should now be live: https://www.codecademy.com/resources/docs/cpp/math-functions/atanh

Your Codecademy profile is currently hidden from view on the entry page. To make it visible, you'll need to add your GitHub username to your Codecademy profile, log out of Codecademy, and log back in through your GitHub account:

<img width="920" alt="Screen Shot 2022-12-03 at 8 07 17 AM" src="https://user-images.githubusercontent.com/23144845/205442384-721847ed-038c-4080-ae45-c365c259f24d.png">

Looking forward to your next Docs contribution! 😄