Cpp math hypot
Codecademy/docs pull request #1114
Opened 2022-10-14 20:11 UTC by Sparsh47

### Checklist
- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-14 20:12 UTC, Sparsh47 commented
I have made all the changes asked  by you and also removed the two commits.

2022-10-15 13:49 UTC, SSwiniarski requested changes
@Sparsh47, I left a couple more review comments.

2022-10-15 13:49 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +Description: 'Returns the square root of sum of square of arguments passed.'
```suggestion
Description: 'Returns the square root of sum of squares of arguments passed.'
```

2022-10-15 13:49 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +It finds the hypotenuse, hypotenuse is the longest side of a right angled triangle.
```suggestion
The `hypot()` function finds the hypotenuse, the longest side of a right angled triangle. The parameters `x` and `y` are the lengths of the other two sides.
```

2022-10-15 13:49 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +The following example uses the `hypot()` function to find the hypotanuse of a right angled triangle with base and perpendicular as `9` & `10`:
```suggestion
The following example uses the `hypot()` function to find the hypotenuse of a right triangle with base and perpendicular sides of `9` & `10`:
```

2022-10-15 13:58 UTC, Sparsh47 commented
I have commited all the changes

2022-10-15 14:14 UTC, SSwiniarski requested changes
One more change.

2022-10-15 14:14 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +The following example uses the `hypot()` function to find the hypotenuse of a right triangle with base and perpendicular sides of `9` & `10`:
```suggestion
The following example uses the `hypot()` function to find the hypotenuse of a right triangle with base and height of `9` & `10`:
```

2022-10-15 14:21 UTC, Sparsh47 commented
I have commited this too.

2022-10-15 14:31 UTC, SSwiniarski approved these changes
@Sparsh47 This looks ready for a second review.

2022-10-26 15:58 UTC, Dusch4593 requested changes
@Sparsh47 Finished with my review and left you some comments/suggestions.

2022-10-26 15:58 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +```cpp
```suggestion
```pseudo
```

2022-10-26 15:58 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +}
```suggestion

int main() {
  double base = 9, height = 10, res;
  res = hypot(base, height);
  
  cout << res << endl;
  return 0;
}
```

The last part didn't seem to fit right in the \```cpp code block.

2022-10-26 15:58 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +
```suggestion

This results in the following output:

```

2022-10-26 15:58 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +
Then I'd suggest adding a new \```shell snippet that looks like this:

```
13.4536
```

2022-10-26 15:58 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +The following example is runnable and returns the square root of sum of squares of `4.525252` & `5.767676`:
```suggestion
The following example is runnable and returns the square root of sum of squares of `4.525252` and `5.767676`:
```

2022-10-26 15:58 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +}
```suggestion

int main() {
  long double a, b, result;
  a = 4.525252;
  b = 5.767676;
  
  result = hypot(a, b);
  cout << result;
  return 0;
}
```

2022-10-26 15:58 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +The **hypot()** function returns the square root of sum of square of arguments passed.
```suggestion
The **hypot()** function returns the value of the longest side of a right-angled triangle.
```

2022-10-26 15:58 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +The `hypot()` function finds the hypotenuse, the longest side of a right angled triangle. The parameters `x` and `y` are the lengths of the other two sides.
```suggestion
The `hypot()` function finds the hypotenuse, the longest side of a right-angled triangle. The parameters `x` and `y` are the floating-point lengths of the other two sides.
```

2022-10-26 15:58 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +The following example uses the `hypot()` function to find the hypotenuse of a right triangle with base and height of `9` & `10`:
```suggestion
The following example uses the `hypot()` function to find the hypotenuse of a right triangle with `base` and `height` values:
```

2022-10-31 18:38 UTC, Dusch4593 commented
@Sparsh47 did you have any questions or need any help with implementing the latest round of feedback? As a reminder, today is the last day to merge your PRs and have them count toward Hacktoberfest. 👀

2022-11-19 14:42 UTC, SSwiniarski commented
@Sparsh47 because it's been over two weeks of inactivity on this PR, I went and committed all of @Dusch4593's suggestions in the interest of getting this merged.

@Dusch4593, does anything else need to be done before approval?

2022-11-22 17:52 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +The **hypot()** function returns the value of the longest side of a right-angled triangle.
```suggestion
The **`hypot()`** function returns the value of the longest side of a right-angled triangle.
```

2022-11-22 17:52 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> + hypot(float x, float y)
```suggestion
hypot(float x, float y)
```

2022-11-22 17:53 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +int main()
```suggestion

int main()
```

2022-11-22 17:53 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +int main() {
```suggestion
int main()
{
```

2022-11-22 17:54 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/hypot/hypot.md
> +    return 0;
```suggestion
  double x = 9, y = 10, res;
  res = hypot(x, y);
  
  cout << res << endl;
  return 0;
```

2022-11-22 17:55 UTC, yangc95 reviewed
@Sparsh47 I had some additional comments.

2022-12-01 20:07 UTC, SSwiniarski commented
@yangc95, since I'd already committed @Dusch4593's comments for inactivity, in the interest of getting this merged I've also committed yours.

@yangc95, @Dusch4593, anything more we need before merging this?

2022-12-03 13:38 UTC, Dusch4593 approved these changes
cc: @Sparsh47 @yangc95 @SSwiniarski 

This LGTM 👍🏻

I made some edits in 601e5aa9f087c386b67ca37297a717cd2af00b03 that I'd like to note:

- Edited lines # 3 and # 15 to more closely resemble each other.
- Removed the data type markers from the \```shell snippet in the "Syntax" section.
  - These parameters can also be `double` or `long double`.
- Added a list of additional edge cases for the `x` and `y` parameters.
  - Included a link to the existing entry on the `fabs()` function.
- Light edit on lines # 34 and # 58.
- Adjusted syntax for `int main()` in the \```cpp snippet.

2022-12-05 17:51 UTC, merged

2022-12-05 17:58 UTC, SSwiniarski commented
Congrats and thank you so much for contributing to Codecademy Docs, @Sparsh47! 🎊 🎉 🥳

The entry should now be live: https://www.codecademy.com/resources/docs/cpp/math-functions/hypot

Currently, your Codecademy profile is listed anonymously on the entry page. To make it visible, you'll need to add your GitHub username to your Codecademy profile, log out of Codecademy, and log back in through your GitHub account: