New term entry for Java Math.hypot()
Codecademy/docs pull request #1115
Opened 2022-10-14 21:15 UTC by YanisaHS

### Description

I added the `.hypot()` Java Math method in `java/concepts/math-methods/terms/`. The file:
1. Defines `.hypot()`
2. Provides the syntax
3. Provides an example

Closes #900 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-15 14:15 UTC, SSwiniarski requested changes
@YanisaHS I made a first review and only had one comment.

2022-10-15 14:15 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/hypot/hypot.md
> +The return type for `.hypot()` is `double`. If either _x_ or _y_ parameter is infinite, the result is positive infinity. If neither argument is infinite, but one or both parameters are `NaN`, the res
```suggestion
The return type for `.hypot()` is `double`. If either the `x` or `y` parameter is infinite, the result is positive infinity. If neither argument is infinite, but one or both parameters are `NaN`, the result is `NaN`.
```

2022-10-15 15:05 UTC, YanisaHS commented
@SSwiniarski Thanks for your feedback! Just committed that change 🥳

2022-10-16 12:17 UTC, SSwiniarski approved these changes
@YanisaHS Looks good for a second review.

2022-10-19 17:35 UTC, yangc95 reviewed
@YanisaHS I went ahead and did a second review!

Please let me know if you have any concerns with any of my comments and tag me once you've looked them over.

2022-10-19 17:35 UTC, yangc95 commented on content/java/concepts/math-methods/terms/hypot/hypot.md
> +Description: 'A method used to get the hypotenuse of a right-angled triangle.'
```suggestion
Description: 'Returns the hypotenuse of a right-angled triangle.'
```

2022-10-19 17:35 UTC, yangc95 commented on content/java/concepts/math-methods/terms/hypot/hypot.md
> +The **`Math.hypot()`** method is used to get the hypotenuse of a right-angled triangle. It returns sqrt(x<sup>2</sup> + y<sup>2</sup>), where _x_ and _y_ are variable type `double`. It does not retur
```suggestion
The **`Math.hypot()`** method is returns the hypotenuse of a right-angled triangle. It returns sqrt(x<sup>2</sup> + y<sup>2</sup>), where `x` and `y` are of type `double`. It does not return intermediate overflow or underflow, which means the `.hypot()` method will not fail due to overflow or underflow of a `x<sup>2</sup>` or `y<sup>2</sup>` value.
```

2022-10-19 17:35 UTC, yangc95 commented on content/java/concepts/math-methods/terms/hypot/hypot.md
> +    public static void main(String args[]) {
Can we do 2-space indent?

2022-10-20 03:59 UTC, YanisaHS commented on content/java/concepts/math-methods/terms/hypot/hypot.md
> +    public static void main(String args[]) {
Added in a commit below!

2022-10-20 03:59 UTC, YanisaHS commented
Thanks for the feedback @yangc95 !! Done! 😃

2022-10-20 18:11 UTC, merged

2022-10-20 18:12 UTC, yangc95 commented
@YanisaHS live link: https://www.codecademy.com/resources/docs/java/math-methods/hypot

I made some edits prior to merge: [fdb2f2e](https://github.com/Codecademy/docs/pull/1115/commits/fdb2f2e1b942439f38796d2804601339b860a094)

cc: @SSwiniarski @Dusch4593