New Entry Set.union() (#1112)
Codecademy/docs pull request #1117
Opened 2022-10-14 22:35 UTC by hcz

* Create union.md

### Description

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-15 14:23 UTC, SSwiniarski requested changes
@hcz, I did a first review and left a few comments.

2022-10-15 14:23 UTC, SSwiniarski commented on content/swift/concepts/sets/terms/union/union.md
> +The **`.union()`** method creates a new set containing all elements of given sets.
```suggestion
The **`.union()`** method returns a new set containing all elements of one set combined with the elements of a given set.
```

2022-10-15 14:23 UTC, SSwiniarski commented on content/swift/concepts/sets/terms/union/union.md
> +Description: 'Populates a new set by taking all the values from two sets and combining them.'
```suggestion
Description: 'Returns a new set by taking all the values from two sets and combining them.'
```

2022-10-15 14:23 UTC, SSwiniarski commented on content/swift/concepts/sets/terms/union/union.md
> +firstSet.union(secondSet)
```suggestion
newSet = firstSet.union(secondSet)
```

2022-10-15 14:23 UTC, SSwiniarski commented on content/swift/concepts/sets/terms/union/union.md
> +Note that set is unordered data structure, so output elements may be ordered differently.
```suggestion
> **Note:** A set is an unordered data structure, so output elements may be ordered differently.
```

2022-10-15 17:47 UTC, hcz commented
I've applied all suggestions, thanks! 60e11534

2022-10-16 12:27 UTC, SSwiniarski approved these changes
@hcz, Looks good for a second review.

2022-10-23 20:23 UTC, yangc95 commented on content/swift/concepts/sets/sets.md
> +| `.union()`               | Returns a new set by taking all the values from two sets and combining them                        |
Let's restore this file since [this PR](https://github.com/Codecademy/docs/pull/1118/files) is going to remove this entire section

2022-10-24 01:09 UTC, yangc95 approved these changes

2022-10-24 01:11 UTC, merged

2022-10-24 01:57 UTC, yangc95 commented
@hcz I made some changes prior to merge here:[a2a5a18](https://github.com/Codecademy/docs/pull/1117/commits/a2a5a18c16e931e254aed7fb0eb87510f890b95e)

live link: https://www.codecademy.com/resources/docs/swift/sets/union
<img width="826" alt="Screen Shot 2022-10-23 at 9 57 33 PM" src="https://user-images.githubusercontent.com/72277593/197432775-02bfe266-fe58-4b1d-8d6f-92279608d82f.png">

cc: @SSwiniarski