shlok-2003
Codecademy/docs pull request #1123
Opened 2022-10-16 16:05 UTC by shlok-2003

### Description

Created documentation for `Math.tan()` function in java. It has a commented Codebyte example for future use.  The branch is named 'arguments'. Closes #917

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-16 16:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1123) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1123) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1123) it.</sub>

2022-10-17 13:44 UTC, SSwiniarski requested changes
@shlok-2003, I did a first review and left a few comments.

2022-10-17 13:44 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/tan/tan.md
> +Description: 'Returns the trigonometric tangent of an angle, in radians'
```suggestion
Description: 'Returns the tangent of an angle given in radians'
```

2022-10-17 13:44 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/tan/tan.md
> +The **`Math.tan()`** method returns trigonometric tangent of an angle, in radians. The _function_ accepts all real numbers *except* the values where cos(x) is equal to 0
```suggestion
The **`Math.tan()`** method returns tangent of an angle given in radians. The function accepts all real numbers *except* the values where `cos(x)` is equal to 0  
```

2022-10-17 13:44 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/tan/tan.md
> +Note, here `x` is the _argument_ passed to the function. It accepts all real numbers.
```suggestion

Here `x` is the argument passed to the function. It accepts all real numbers. 

```

2022-10-17 13:44 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/tan/tan.md
> +Use `Math.tan()` to return the trigonometric tangent for `(x)` in radians:
```suggestion
This example uses `.tan()` to return the tangent for `(x)`:
```

2022-10-17 13:44 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/tan/tan.md
> +    double x = 45.0;    // radians
The number 45 seems more like an example given in degrees. Maybe do an example that's some multiple or fraction of PI.

2022-10-17 13:44 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/tan/tan.md
> +<!-- ## Codebyte Example
You can remove this comment.

2022-10-17 15:41 UTC, shlok-2003 commented
@SSwiniarski Do I have to do this from my side, and push it again? Or is there any other way ?

2022-10-18 11:14 UTC, SSwiniarski approved these changes
@shlok-2003, I had two more minor comments. Otherwise looks good for review two,

2022-10-18 11:14 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/tan/tan.md
> +Description: 'Returns the tangent of an angle given in radians'
```suggestion
Description: 'Returns the tangent of an angle given in radians.'
```

2022-10-18 11:14 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/tan/tan.md
> +Here `x` is the argument passed to the function. It accepts all real numbers.
```suggestion
Here `x` is the argument passed to the function. It accepts all real numbers. 

```

2022-10-18 12:33 UTC, shlok-2003 commented
@SSwiniarski Required changes have been made

2022-10-19 15:29 UTC, shlok-2003 commented
@SSwiniarski I have made some more updates.

2022-10-20 02:28 UTC, HishamT requested changes
Hey @shlok-2003, I reviewed your entry. Left a few comments for you before approval. :smile:

2022-10-20 02:28 UTC, HishamT commented on content/java/concepts/math-methods/terms/tan/tan.md
> +The **`Math.tan()`** method returns tangent of an angle given in radians. The function accepts all real numbers *except* the values where `cos(x)` is equal to 0
"...returns *the* tangent of an angle given in radians."
"...is equal to zero."

2022-10-20 02:28 UTC, HishamT commented on content/java/concepts/math-methods/terms/tan/tan.md
> +Here `x` is the argument passed to the function. It accepts all real numbers.
Place a comma after "Here". The word "it" in the second sentence is unclear as to what it is referring to. Consider this sentence instead:

"`Math.tan()` accepts all real numbers as arguments."

2022-10-20 11:43 UTC, shlok-2003 commented
Hey @HishamT, I have made the changes in the files.

2022-10-20 23:48 UTC, HishamT approved these changes
LGTM!

2022-10-21 03:25 UTC, shlok-2003 commented
> LGTM!

hey @HishamT , is the pull request approved ?

2022-10-21 04:40 UTC, yangc95 commented
@shlok-2003 it looks like this PR has two approvals! When you get the chance, make sure to run the necessary scripts (we can also assist with this process or walk you through it) and update this PR branch.

2022-10-21 12:17 UTC, shlok-2003 commented
Hey @yangc95, I tried resolving the test by downloading yarn and using it. But, it didn't work for me, as I am not familiar with yarn. So if you help me with the functions and syntax of yarn, it would be of great help.

2022-10-21 14:08 UTC, merged

2022-10-21 14:19 UTC, yangc95 commented
Thanks for speeding up the process @Dusch4593!

@shlok-2003 live link: https://www.codecademy.com/resources/docs/java/math-methods/tan
Did you wish to remain anonymous for this?

cc: @HishamT @SSwiniarski