Add an entry for Java Round
Codecademy/docs pull request #1129
Opened 2022-10-16 23:20 UTC by Bobliuuu

### Description

Closes issue #890. 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-16 23:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1129) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1129) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1129) it.</sub>

2022-10-17 13:46 UTC, SSwiniarski commented
@Dusch4593, do you know why I can't link the issue to this PR? It doesn't show up in the search.

2022-10-17 13:47 UTC, SSwiniarski approved these changes
@Bobliuuu, I completed a first review. This looks good and I'm passing it on to review 2.

2022-10-20 02:15 UTC, HishamT commented on content/java/concepts/math-methods/terms/round/round.md
> +The **`Math.round()`** method returns the closest integer or long to the argument.
Mention that `round()` performs rounding on a number.

2022-10-20 02:17 UTC, HishamT commented on content/java/concepts/math-methods/terms/round/round.md
> +```
Use `shell` to show program output.

\```shell
2
\```

Also, try including a case when the number is rounded down.

2022-10-20 02:28 UTC, Bobliuuu commented
Thank you for your feedback @HishamT! I made the requested changes.

2022-10-20 23:54 UTC, HishamT requested changes
Looks good. Just one minor change requested.

2022-10-20 23:54 UTC, HishamT commented on content/java/concepts/math-methods/terms/round/round.md
> +The **`Math.round()`** method returns the closest `integer` or `long` to a number.
"integer" is not a data type in Java. It is either `int` or `Integer`.

2022-10-21 03:33 UTC, Bobliuuu commented
Whoops, thanks, fixed! @HishamT

2022-10-21 23:50 UTC, HishamT approved these changes
LGTM!

2022-10-24 18:47 UTC, merged