New term entry for Java Math.nextUp().
Codecademy/docs pull request #1142
Opened 2022-10-18 16:48 UTC by shivanshugour45

### Description

Creating next-up.md

Closes #908 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-19 15:52 UTC, SSwiniarski requested changes
@shivanshugour45 I did a first review and left a few comments.

2022-10-19 15:52 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/next-up/next-up.md
> +Following are some of the special cases for this method-
```suggestion
The following are some of the special cases for this method:
```

2022-10-19 15:52 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/next-up/next-up.md
> +The **`Math.nextUp()`** method returns the floating-point value adjacent to the argument passed as the parameter in the direction of positive infinity. Argument passed can be either of type `double`
Move "Argument passed can be either of type `double` or `float`." to the "Syntax" section, then you can have one ```pseudo block reading `Math.nextUp(val)`.

2022-10-19 15:52 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/next-up/next-up.md
> +```pseudo
See my prior comment about combining these into one ```pseudo block.

2022-10-19 16:07 UTC, shivanshugour45 commented
@SSwiniarski, Suggested changes are done.

2022-10-20 02:12 UTC, HishamT approved these changes
LGTM!

2022-10-20 11:24 UTC, SSwiniarski requested changes
@shivanshugour45 I have one more comment.

2022-10-20 11:24 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/next-up/next-up.md
> +#### Note: Argument passed can be either of type `double` or `float`.
```suggestion
Argument passed can be either of type `double` or `float`.
```

I'd also move this line after the ```pseudo block.

2022-10-20 12:45 UTC, shivanshugour45 commented
Suggested updates done.

2022-10-21 15:37 UTC, SSwiniarski approved these changes
@shivanshugour45 Looks good.

2022-10-22 01:36 UTC, merged

2022-10-22 02:30 UTC, yangc95 commented
@shivanshugour45 Live link: https://www.codecademy.com/resources/docs/java/math-methods/nextUp
(I made some changes prior to merge here: [87cf532](https://github.com/Codecademy/docs/pull/1142/commits/87cf532575406626d0e372cf8d926014ce2db3d5)). I changed the intro paragraph a bit to stray slightly away from existing documentation on this method.

<img width="823" alt="Screen Shot 2022-10-21 at 10 29 43 PM" src="https://user-images.githubusercontent.com/72277593/197315132-ab1a7863-9dd9-4f3b-82ef-5984f027e1d7.png">
You're currently anonymous but if you wish to become public, make sure to add your GitHub to your Codecademy profile.

cc: @HishamT @SSwiniarski