Edit Content Standards
Codecademy/docs pull request #1150
Opened 2022-10-20 18:00 UTC by yangc95

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-20 18:07 UTC, Dusch4593 requested changes
@yangc95 Had a few comments/suggestions. Thank you for opening this! 😎

2022-10-20 18:07 UTC, Dusch4593 commented on documentation/content-standards.md
> +  - If the title or name is meant to be in camelCase: ".forEach()" -> `forEach.md`.
```suggestion
  - If the title or name is meant to be in camelCase: ".forEach()" -> `forEach.md` (without the `.` and `()`).
```

2022-10-20 18:07 UTC, Dusch4593 commented on documentation/content-standards.md
>  - Punctuation must not be included in the file name, even if it exists in the entry name. (e.g., "Moore's Law" -> `moores-law.md`, "Three.js" -> `three-js.md`)
```suggestion
- Punctuation must not be included in the file name, even if it exists in the entry name. (e.g., "Moore's Law" -> `moores-law.md`, "Three.js" -> `three-js.md`, `.nextAfter()` -> `nextAfter.md`)
```

2022-10-20 18:07 UTC, Dusch4593 commented on documentation/content-standards.md
>  - The name should always be lowercase. (e.g., "Array" -> `array.md`, "HTML" -> `html.md`)
As its currently phrased, I'm not sure how this squares up with the list items above. Maybe we could rephrase as something like this:

```suggestion
- The name should always begin with a lowercase letter. (e.g., "Array" -> `array.md`, "HTML" -> `html.md`)
```

2022-10-20 18:20 UTC, Dusch4593 approved these changes
@yangc95 LGTM! 👍🏻

Anything left to add, change, or check @lucwhite?

2022-10-20 18:31 UTC, KTom101 approved these changes

2022-10-21 00:31 UTC, HishamT approved these changes
LGTM

2022-10-21 13:56 UTC, merged