Yukihiro matsumoto
Codecademy/docs pull request #1158
Opened 2022-10-21 21:30 UTC by mosmoo

### Description

I added an image and wrote up content for Yukihiro Matsumoto's page on Codecademy. 

### Type of Change

- Adding a new entry

### Checklist

- [o] All writings are my own.
- [o] My entry follows the Codecademy Docs style guide.
- [o] My changes generate no new warnings.
- [o] I have performed a self-review of my own writing and code.
- [o] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [0] I have confirmed my changes are not being pushed from my forked `main` branch.
- [o] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-21 21:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1158) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1158) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1158) it.</sub>

2022-10-22 14:48 UTC, SSwiniarski commented
@manasvislj, thanks for your contribution. Please remember to sign the CLA.

2022-10-22 15:00 UTC, SSwiniarski requested changes
@mosmoo. I performed a first review and left a couple of comments.

2022-10-22 23:09 UTC, Dusch4593 commented
> @manasvislj, thanks for your contribution. Please remember to sign the CLA.

@manasvislj link here: https://cla-assistant.io/Codecademy/docs?pullRequest=1158

2022-10-25 05:07 UTC, mosmoo commented
> @mosmoo. I performed a first review and left a couple of comments.

Thank you! I have updated it, please let me know if I am good to proceed with the new changes.

2022-10-25 11:12 UTC, SSwiniarski approved these changes
@mosmoo, looks good for a second review.

2022-10-25 19:17 UTC, Dusch4593 requested changes
@mosmoo Finished with my review and left some comments/suggestions. 😄

2022-10-25 19:17 UTC, Dusch4593 commented on content/general/concepts/Yukihiro_Matsumoto/Yukihiro_Matsumoto.md
> +As of 2011, Matz is the Chief Architect of Ruby at [Heroku](https://en.wikipedia.org/wiki/Heroku "Heroku"), an online cloud platform-as-a-service in San Francisco. He was appointed to the role of tec
```suggestion
## Recent Activity

As of 2011, Matz is the Chief Architect of Ruby at [Heroku](https://www.heroku.com/), an online cloud platform-as-a-service. Starting in June 2014, he was appointed to the role of Technical Advisor for VASILY Inc.
```

I think both the roles mentioned should either be lowercase or uppercase.

2022-10-25 19:17 UTC, Dusch4593 commented on content/general/concepts/Yukihiro_Matsumoto/Yukihiro_Matsumoto.md
> +In 2001, Matz published a book called _Ruby in a Nutshell_, and in 2008 he published _The Ruby Programming Language_. His demeanor has brought about a motto in the Ruby community: _"Matz is nice and
```suggestion
In 2001, Matz published a book called "Ruby in a Nutshell." This was later expanded and revised into a new book called "The Ruby Programming Language," released in 2008 and co-authored by David Flanagan.
```

With the exception of the first mention of the entry's concept/term, let's refrain from using emphasis and, instead, wrap a published work in quotes.

Also, I think the last sentence fits better under the opening sentences.

2022-10-26 18:31 UTC, mosmoo commented
Thank you so much for your edits and suggestions! I have also updated the branch with a resized image, please let me know I am good to proceed.

Thank you!

2022-10-27 17:37 UTC, Dusch4593 commented
Thanks! Before we go forward, I wanted to confirm that @mosmoo and @manasvislj are accounts owned/used by the same person?

2022-10-27 17:42 UTC, mosmoo commented
> Thanks! Before we go forward, I wanted to confirm that @mosmoo and @manasvislj are accounts owned/used by the same person?

Yes both of them are my accounts. I am not sure why the edits were made using my old github, but I am working on fixing that!

2022-10-28 17:59 UTC, Dusch4593 approved these changes
@mosmoo LGTM! 👍🏻

I made a few edits in 61acffec0c1ac905af3433e23142b75e327e7b45 and 5d714b1382e4dc7f55af5efce71e0ad1e57c2561 including:

- Fixing spacing to `CatalogContent` in metadata at top.
- Changed/reformatted name of folder and file to get GitHub checks to pass.

2022-10-28 18:00 UTC, merged

2022-10-28 18:09 UTC, Dusch4593 commented
Congrats on making your first contribution to Codecademy Docs, @mosmoo! The entry can be viewed here: https://www.codecademy.com/resources/docs/general/yukihiro-matsumoto

Also, you are currently anonymous on the entry. If you'd like to receive credit, you'll need to add your GitHub username to your Codecademy profile, log out of your Codecademy profile, and then back in with your GitHub account:

<img width="841" alt="Screen Shot 2022-10-28 at 2 07 12 PM" src="https://user-images.githubusercontent.com/23144845/198703827-b8b75e1b-b845-45b2-987e-a7b9249edfdf.png">

2023-01-02 07:19 UTC, yangc95 commented
@mosmoo This entry was moved to: https://www.codecademy.com/resources/docs/general/historical-technical-figures/yukihiro-matsumoto

Would you be able to make a small change to the introduction:

> **Yukihiro Matsumoto (Matz)** (1965-present) is a software programmer and computer scientist widely known for his work as the chief designer of the [Ruby](https://www.codecademy.com/resources/docs/ruby) programming language.

cc: @Dusch4593 @SSwiniarski