General object
Codecademy/docs pull request #1160
Opened 2022-10-22 17:36 UTC by Nessvah

### Description

Closes issue #1021 

### Type of Change

- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-23 12:23 UTC, SSwiniarski requested changes
@Nessvah I did a first review and only had a couple of comments.

2022-10-28 18:13 UTC, Dusch4593 requested changes
@Nessvah Had a few comments/suggestions to offer as well 😄

2022-10-28 18:13 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +An object is a data type created by the developer that has properties and methods, representing its state and behavior. Objects are often used to represent real-world objects found in everyday life a
```suggestion
An **object** is a data type created by the developer that has properties and methods, representing its state and behavior. Objects are often used to represent real-world objects found in everyday life and can interact with other objects and other elements of the program.
```

2022-10-31 18:52 UTC, Dusch4593 commented
Hey @Nessvah did you have any questions or need any help with implementing the feedback? As a reminder, today is the last day to merge your PRs and have them count toward Hacktoberfest. 👀

2022-11-01 06:11 UTC, Nessvah commented
@Dusch4593 I'm loaded with work and I missed the deadline on this PR but there's no harm. 😄  I'll work on it now that I have some spare time.

2022-11-01 06:33 UTC, Nessvah commented
Let me know if there's anything more I can do about this issue or something I should discuss.

2022-11-03 15:45 UTC, Dusch4593 requested changes
Hey @Nessvah! I applaud your continued contribution to Docs, even after Hacktoberfest! 🚀 😄

I had some more feedback to offer for this entry.

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +Description: 'An object is a data  type, created by the developer, that has properties and methods.'
```suggestion
Description: 'An object is associative data that commonly takes the form of a data structure, function, method, variable, or class.'
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
>  An **object** is an instance of a class. It contains the properties and functionalities of its class.
```suggestion
An **object** is associative data that commonly takes the form of a data structure, [function](https://www.codecademy.com/resources/docs/general/function), [method](https://www.codecademy.com/resources/docs/general/method), variable, or [class](https://www.codecademy.com/resources/docs/general/class).
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +Objects provide a structured programming approach and are the basic units of [Oject-Oriented-Programming (OOP)](https://www.codecademy.com/resources/docs/general/object-oriented-programming). Develop
```suggestion
Objects provide a structured programming approach and are the core units of [object-oriented-programming (OOP)](https://www.codecademy.com/resources/docs/general/programming-paradigms/object-oriented-programming). Developers can easily create various identical objects and modify existing ones within the program.
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +To allocate memory to an object at runtime, the use of the `new` keyword is needed and depending on the programming language, the memory can be allocated on Heap or Stack.
```suggestion
To allocate memory to an object at [runtime](https://www.codecademy.com/resources/docs/general/runtime), the use of the `new` keyword is needed and, depending on the programming language, the memory can be allocated to a heap or stack.
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +## Class and Object Example in Java
```suggestion
## Java Example
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
>  // Creating the Employee class
```suggestion
// Employee.java
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +In Java, an object is created from a class. The class is a blueprint for creating objects and it's required in classical OO/UML (C++/Java/C# etc.) objects.
```suggestion
In Java, [classes](https://www.codecademy.com/resources/docs/java/classes) are the blueprints for creating objects, which is required in object-orientation/unified modeling language (OO/UML).

The following snippet is an example of a defined class being used to instantiate new objects (instances of that class):
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +    System.out.println("Cooking some delicious bread.");
```suggestion
  // State or field
  int id;
  String firstName;
  String lastName;
  char middleInitial;
  float years;

  // Behavior or method
  void cookingBread() {
    System.out.println("Cooking some delicious bread.");
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +In the example above, five different objects were created from the class `Employee`. An object is called an instance of a class. `Tina`, `Louise`, etc, are objects of the class `Employee`. The `new`
```suggestion
In the example above, the `new` keyword was used to create five object instances of the `Employee` class according to the class constructor.
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +Patterns themselves are **not** objects but are used to develop objects that solve general problems during software development.
```suggestion
> **Note:** Patterns themselves are not objects but are used to develop objects that solve general problems during software development.
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +## Types of objects
```suggestion
## Types of Objects
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +
```suggestion
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +// Creating the Car class
```suggestion
// Car.java
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +  // constructor declaration of class
```suggestion
  // Constructor declaration of class
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +  // behavior or method
```suggestion
  // Behavior or method
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +## Access fields and methods of a Class
```suggestion
## Accessing Fields and Methods
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +By using the name of the objects, along with the `.` operator, it's possible to access members of a class.
```suggestion
Since objects are class instances in Java, they can use the `.` operator to access fields and methods in a class.
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +// Creating an object from the Car class
```suggestion
// Create object or class instance
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +System.out.println(mercedes.turnOn()); // sets the isOn variable to true and prints the output: The car has started? True
```suggestion
System.out.println(mercedes.turnOn());
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +
```suggestion

In the snippet above, a new `Car` object called `mercedes` is created with its `isOn` field set to `true`. When the `.turnOn()` is invoked with the `mercedes` object and its `numberOfDoors` field is accessed, the following is printed:

```

And then let's add a \```shell snippet of the output that looks like this:

```shell
5
The car has started? True
```

2022-11-03 15:45 UTC, Dusch4593 commented on content/general/concepts/object/object.md
> +System.out.println(mercedes.numberOfDoors) // Output: 5
```suggestion
System.out.println(mercedes.numberOfDoors)
```

2022-11-25 18:57 UTC, SSwiniarski approved these changes
@Nessvah, since it's been a few weeks of inactivity, I've gone ahead and implemented all of @Dusch4593's suggestions in the interest of getting this merged.

@Dusch4593, anything else you think this needs before merging?

2022-11-25 21:49 UTC, Dusch4593 approved these changes
@Nessvah @SSwiniarski LGTM! 👍🏻

2022-11-25 21:50 UTC, merged

2022-11-25 22:07 UTC, Dusch4593 commented
Congrats and thank you for another awesome contribution to Codecademy Docs, @Nessvah! 🚀 🎉 🎊

The changes should now be live: https://www.codecademy.com/resources/docs/general/object

<img width="845" alt="Screen Shot 2022-11-25 at 5 07 32 PM" src="https://user-images.githubusercontent.com/23144845/204059193-6aa3bb48-588e-458d-aec6-f863f9bb9160.png">

Looking forward to your next Docs contribution! 😄

2022-11-26 20:35 UTC, Nessvah commented
@SSwiniarski thank you so much! And @Dusch4593 I'm sorry for the overdue. Had some issues that I needed to address asap and took me a little longer that I expected. 😮‍💨 

Thank you all again! You guys are amazing! 👍🏻