New term entry for Java Math.negateExact()
Codecademy/docs pull request #1175
Opened 2022-10-25 03:21 UTC by YanisaHS

### Description

I added the .negateExact() Java Math method in java/concepts/math-methods/terms/. The file:

- Defines .negateExact()
- Provides the syntax
- Provides an example
Closes #905 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-10-26 14:27 UTC, Dusch4593 requested changes
Hey @YanisaHS! Thanks for creating this new entry for Docs! 🎉

I've finished my review and left you some comments/suggestions. Can we also rename the folder and file name to `negateExact` and `negateExact.md`, respectively?

2022-10-26 14:27 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/negate-exact/negate-exact.md
> +The `Math.negateExact()` method returns the negation of the argument and raises an [exception](https://www.codecademy.com/resources/docs/java/errors) if the result overflows.
```suggestion
The **`Math.negateExact()`** method returns the negation of the argument and raises an [exception](https://www.codecademy.com/resources/docs/java/errors) if the result overflows.
```

2022-10-26 14:27 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/negate-exact/negate-exact.md
> +```java
```suggestion
```shell
```

2022-10-26 14:27 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/negate-exact/negate-exact.md
> +The `num` argument can be of type `int` or `long`.
```suggestion
The `num` parameter can be of type `int` or `long`.
```

In the context of describing the makeup of a method/function, let's refer to any passed values as parameters and as arguments in examples. 😄

2022-10-27 16:40 UTC, Dusch4593 approved these changes
@YanisaHS LGTM for the next review 👍🏻

2022-10-29 20:46 UTC, HishamT approved these changes
LGTM!

2022-10-31 02:04 UTC, Dusch4593 commented
@YanisaHS LGTM for merge! 🚀

I made a small edit in 1ebb71303c8bd7e59a5eb35175978da5e8903e9e on line # 28.

2022-10-31 02:07 UTC, merged

2022-10-31 02:11 UTC, Dusch4593 commented
Thank you for another solid contribution to Codecademy Docs, @YanisaHS! 🥳

The new entry should now be live: https://www.codecademy.com/resources/docs/java/math-methods/negateExact