🎨 [New Terms]: Java Math Methods: `logarithmic functions` (#902)
Codecademy/docs pull request #1181
Opened 2022-10-27 06:35 UTC by tanishq-singh-2301

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #902 in the "Description" above).

2022-10-27 16:03 UTC, SSwiniarski requested changes
@tanishq-singh-2301, I did a first review and left some comments.

2022-10-27 16:03 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/log1p/log1p.md
> +The following example is runnable and return `ln (a + 1)`:
```suggestion
The following example is runnable and returns `ln (a + 1)`:
```

2022-10-27 16:03 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/log10/log10.md
> +The result of log10(10) is: 1
```suggestion
The result of log10(10.0) is: 1.0
```

2022-10-27 16:03 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/log10/log10.md
> +The result of log10(-6) is: NaN
```suggestion
The result of log10(-6.0) is: NaN
```

2022-10-27 16:03 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/log10/log10.md
> +The result of log10(0) is: -Infinity
```suggestion
The result of log10(0.0) is: -Infinity
```

2022-10-27 16:03 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/log/log.md
> +The result of log(10) is: 2.303
```suggestion
The result of log(10.0) is: 2.302585092994046
```

2022-10-27 16:03 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/log/log.md
> +The result of log(-6) is: NaN
```suggestion
The result of log(-6.0) is: NaN
```

2022-10-27 16:03 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/log/log.md
> +The result of log(0) is: -Infinity
```suggestion
The result of log(0.0) is: -Infinity
```

2022-10-29 13:40 UTC, SSwiniarski approved these changes
@tanishq-singh-2301, this looks ready for review two.

2022-10-30 22:24 UTC, HishamT requested changes
Hey @tanishq-singh-2301, I have finished the review of your entry and left some comments. :grin:

2022-10-30 22:24 UTC, HishamT commented on content/java/concepts/math-methods/terms/log10/log10.md
> +- If `a` is `positive infinity`, then return value is `positive infinity`.
```suggestion
If `a` is positive infinity, the return value is positive infinity.
```

2022-10-30 22:24 UTC, HishamT commented on content/java/concepts/math-methods/terms/log10/log10.md
> +The following example demonstrates using `.log10()` to find logs (with base 10):
```suggestion
The following example demonstrates using `Math.log10()` to find base-10 logarithms:
```

2022-10-30 22:24 UTC, HishamT commented on content/java/concepts/math-methods/terms/log1p/log1p.md
> +The **`.log1p()`** method returns `ln (a + 1)`, the natural logarithm of a + 1.
```suggestion
The **`Math.log1p()`** method returns the natural logarithm of a number plus 1.
```

2022-10-30 22:24 UTC, HishamT commented on content/java/concepts/math-methods/terms/log1p/log1p.md
> +Title: '.log1p()'
```suggestion
'Math.log1p()'
```

2022-10-30 22:24 UTC, HishamT commented on content/java/concepts/math-methods/terms/log10/log10.md
> +Title: '.log10()'
```suggestion
'Math.log10()'
```

2022-10-30 22:24 UTC, HishamT commented on content/java/concepts/math-methods/terms/log/log.md
> +Title: '.log()'
```suggestion
'Math.log()'
```

2022-10-30 22:24 UTC, HishamT commented on content/java/concepts/math-methods/terms/log/log.md
> +- The `.log()` method takes one parameter `a`.
This line is not necessary as the function has been previously explained.

2022-10-30 22:24 UTC, HishamT commented on content/java/concepts/math-methods/terms/log1p/log1p.md
> +- The `.log1p()` method takes one parameter `a`.
This line is not necessary as this function has been explained previously.

2022-10-30 22:24 UTC, HishamT commented on content/java/concepts/math-methods/terms/log1p/log1p.md
> +- If `a` is `NaN`, then return value is `NaN`.
Lines 23-27 should be the same as the ones in the entry for the previous two functions.

2022-10-30 22:24 UTC, HishamT commented on content/java/concepts/math-methods/terms/log1p/log1p.md
> +The following example demonstrates using `.log1p()` to find natural logs:
```suggestion
The following example demonstrates using `Math.log1p()` to find natural logs:
```

2022-10-31 18:48 UTC, Dusch4593 commented
Hey @tanishq-singh-2301 did you have any questions or need any help with implementing the latest round of feedback? As a reminder, today is the last today to merge your PRs and have them count toward Hacktoberfest. 👀

2022-10-31 19:42 UTC, HishamT approved these changes
LGTM!

2022-10-31 21:09 UTC, Dusch4593 commented
@tanishq-singh-2301 This looks ready to merge. I just made some changes across many commits prior to merging (cc: @HishamT @SSwiniarski):

- Revised the lists in the "Syntax" sections.
  - I noticed that the claimed return value for `a=0/-0` didn't seem quite right.
- Consolidated to a single \```java snippet in the "Example" section.
  - Java is not currently supported in Codebytes. 😢
  - Adjusted the \```shell output snippets to reflect the revised code.

2022-10-31 21:10 UTC, merged

2022-10-31 21:18 UTC, Dusch4593 commented
Congrats and thank you so much for contributing to Codecademy Docs, @tanishq-singh-2301! 🚀 🥳

The entries should now be live.

- `.log()`: https://www.codecademy.com/resources/docs/java/math-methods/log
- `.log10()`: https://www.codecademy.com/resources/docs/java/math-methods/log10
- `.log1p()`: https://www.codecademy.com/resources/docs/java/math-methods/log1p

<img width="872" alt="Screen Shot 2022-10-31 at 5 17 46 PM" src="https://user-images.githubusercontent.com/23144845/199112538-c25fb32f-d44b-4307-b152-3d54f3c76e04.png">

Looking forward to your next contribution to Docs! 😄

2022-11-09 23:50 UTC, Dusch4593 commented
Hey @tanishq-singh-2301! 👋🏻

I was wondering if you'd be open to creating a new PR to make some edits to the 3 entries you recently contributed?

- On line # 2 in each file, can we change the `Title` to `.log()`, `.log10()`, and `.log1p()` in `log.md`, `log10.md`, and `log1p.md` respectively?

2022-11-12 03:58 UTC, tanishq-singh-2301 commented
sure!

2022-11-12 04:10 UTC, tanishq-singh-2301 commented
There [**pr-link.**](https://github.com/Codecademy/docs/pull/1240)