added text.md
Codecademy/docs pull request #1208
Opened 2022-11-02 23:55 UTC by KarinaNi

### Description

I was assigned issue: #[1097](https://github.com/Codecademy/docs/issues/1097) SwiftUI Text. I have added a file under 
content/swiftui/concepts/views/terms/ called text and added files text.md and an image to show the output screen and the example. I had been going through the git course in codecademy and one of my challenges included contributing to the docs to get experience of making a pull request and working on the feedback and I am doing exactly that. 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-11-02 23:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1208) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1208) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1208) it.</sub>

2022-11-05 13:08 UTC, SSwiniarski requested changes
@KarinaNi, I did a first review and left a couple of comments. One stylistic note: There should be a blank like before and after each header and before and after each code block.

2022-11-05 13:08 UTC, SSwiniarski commented on content/swiftui/concepts/views/terms/text/text.md
> +![Image](https://i.ibb.co/C9yQ5z8/Screenshot-2022-11-03-at-1-54-49-AM.png)
The images should be housed in the docs/tree/main/media media folder, and the image here should link there. Also, you only have one image here, you should remove the other from this PR if you're not going to use it.

2022-11-05 13:08 UTC, SSwiniarski commented on content/swiftui/concepts/views/terms/text/text.md
> +## Syntax
```suggestion

## Syntax
```

2022-11-05 13:08 UTC, SSwiniarski commented on content/swiftui/concepts/views/terms/text/text.md
> +`Text("This is My App")`
This example should be in a ```pseudo block.

2022-11-05 13:08 UTC, SSwiniarski commented on content/swiftui/concepts/views/terms/text/text.md
> +Screen will display any information enclosed within the "" on the screen. In this case, it should show This is My App
```suggestion
Screen will display any information enclosed within the "" on the screen. In this case, it should show "This is My App."
```

2022-11-05 13:08 UTC, SSwiniarski commented on content/swiftui/concepts/views/terms/text/text.md
> +The following example adds the text Codecademy is Awesome on the display screen.
```suggestion

The following example adds the text Codecademy is Awesome on the display screen.
```

2022-11-05 13:08 UTC, SSwiniarski commented on content/swiftui/concepts/views/terms/text/text.md
> +This will display the following:
```suggestion

This will display the following:
```

2022-12-07 16:15 UTC, Dusch4593 commented
Hey @KarinaNi it's been a while since feedback from the last review was posted. Did you have any questions or require any assistance with implementing the changes?

2022-12-16 17:40 UTC, yangc95 commented
@Dusch4593 Thanks for bringing attention to this entry submission!

@KarinaNi I do see that you're currently busy. I've made some direct changes to this entry in an effort to get this PR merged here: https://github.com/Codecademy/docs/pull/1208/commits/21cdf58e88bc581d3c49f08b4f9283f18701f0d5. @SSwiniarski, is there anything else that needs improvement here?

2022-12-16 17:42 UTC, yangc95 commented on content/swiftui/concepts/views/terms/text/text.md
> +Screen will display any information enclosed within the "" on the screen. In this case, it should show This is My App
I've edited this suggestion*

2022-12-16 17:43 UTC, yangc95 commented on content/swiftui/concepts/views/terms/text/text.md
> +  - 'Buttons'
```suggestion
```

2022-12-17 14:30 UTC, yangc95 commented on content/swiftui/concepts/views/terms/text/text.md
> +A **Text view** in SwiftUI is a view that lets you display one or more lines of text. It is useful for read-only information and it is non-editable. For example, if you want to display a message on s
```suggestion
The **`Text`** view can display one or more lines of text on a screen. It is useful for read-only information and is non-editable, but can be dynamic.
```

2022-12-17 14:30 UTC, yangc95 commented on content/swiftui/concepts/views/terms/text/text.md
> +The following example adds the text `"Codecademy is Awesome!"` on the display screen.
```suggestion
The following example adds the text,`"Codecademy is Awesome!"`, on the display screen.
```

2022-12-17 14:31 UTC, yangc95 approved these changes
@KarinaNi LGTM after some direct edits.
cc: @SSwiniarski

2022-12-17 16:14 UTC, yangc95 commented on content/swiftui/concepts/views/terms/text/text.md
> +The **`Text`** view can display one or more lines of text on a screen. It is useful for read-only information and is non-editable, but can be dynamic.
```suggestion
The **`Text`** view can display one or more lines of text on a screen. It is useful for read-only information.
```

2022-12-17 16:15 UTC, yangc95 commented on content/swiftui/concepts/views/terms/text/text.md
> +Any information enclosed within the double quotes`"..."` will display on the screen.
```suggestion
Any information enclosed within the double quotes `"..."` will display on the screen.
```

2022-12-19 17:06 UTC, SSwiniarski approved these changes
@KarinaNi, @yangc95 looks good to merge.

2022-12-20 02:54 UTC, merged

2022-12-20 02:58 UTC, yangc95 commented
Thanks for this entry @KarinaNi live link: https://www.codecademy.com/resources/docs/swiftui/views/text
<img width="847" alt="Screen Shot 2022-12-19 at 9 58 06 PM" src="https://user-images.githubusercontent.com/72277593/208571237-be06bb1e-77e2-403f-9857-564985deff9a.png">
Looks like you're all set!

cc: @SSwiniarski