[Term Entry] Swift Sets: .subtracting() (#1125)
Codecademy/docs pull request #1212
Opened 2022-11-03 17:54 UTC by st3hall

### Description

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-11-05 14:31 UTC, SSwiniarski requested changes
@st3hall, I did a first review and left a few comments.

2022-11-05 14:31 UTC, SSwiniarski commented on content/swift/concepts/sets/terms/subtraction/subtract.md
> +Title: '.subtracting()'
This duplicate file should be removed from the PR.

2022-11-05 14:31 UTC, SSwiniarski commented on content/swift/concepts/sets/terms/subtracting/subtracting.md
> +
There should be an introduction to the example explaining what it is doing.

2022-11-05 14:31 UTC, SSwiniarski commented on content/swift/concepts/sets/terms/subtracting/subtracting.md
> +```
Generally we have a sentence explaining the syntax snippet. i.e. "The elements of `givenSet` are removed from the elements of `targetSet` and what elements remain are placed into `newSet`."

2022-11-05 14:31 UTC, SSwiniarski commented on content/swift/concepts/sets/terms/subtracting/subtracting.md
> +Description: 'Returns a new set containing the elements from the target set that are NOT in the given set.'
```suggestion
Description: 'Returns a new set containing the elements from the target set that are not in the given set.'
```

2022-11-05 14:31 UTC, SSwiniarski commented on content/swift/concepts/sets/terms/subtracting/subtracting.md
> +The **`.subtracting()`** method creates a new set containing the elements from the target set that are NOT in the given set.
```suggestion
The **`.subtracting()`** method creates a new set containing the elements from the target set that are not in the given set.
```

2022-11-07 16:35 UTC, st3hall reviewed
Revisions and intro to syntax and example made

2022-11-07 17:32 UTC, SSwiniarski approved these changes
@st3hall Looks good for a second review.

2022-11-14 11:46 UTC, Dusch4593 requested changes
@st3hall Finished with my review and left you some comments/suggestions. 😄

2022-11-14 11:46 UTC, Dusch4593 commented on content/swift/concepts/sets/terms/subtracting/subtracting.md
> +  - 'Computer Science'
```suggestion
  - 'Computer Science'
Subjects:
  - 'Mobile Development'
```

We were missing a list of subjects here. Adding this should get the "test" GitHub check to pass. 😄

2022-11-14 11:46 UTC, Dusch4593 commented on content/swift/concepts/sets/terms/subtracting/subtracting.md
> +In the example below, The elements from `fruit` set are removed from the elements in `produce` set and the remaining elements are placed in the new `veggies` set:
```suggestion
In the example below, the elements from the `fruit` set are removed from the elements in the `produce` set and the remaining elements are placed in the new `veggies` set:
```

2022-11-14 11:46 UTC, Dusch4593 commented on content/swift/concepts/sets/terms/subtracting/subtracting.md
> +
```suggestion
> **Note:** A set is an unordered data structure, so output elements may be ordered differently.
```

2022-11-14 15:00 UTC, st3hall commented on content/swift/concepts/sets/terms/subtracting/subtracting.md
> +In the example below, The elements from `fruit` set are removed from the elements in `produce` set and the remaining elements are placed in the new `veggies` set:
Good correction.

2022-11-14 20:03 UTC, Dusch4593 approved these changes
@st3hall LGTM! 👍🏻

I made a few small edits in f98500f813df6cba92aaf5fd9cbca4f6f8670da0 and 75167dc3a8371f256f16dfe22d9ea08a7439d527 to get the remaining GitHub checks to pass. 😄

2022-11-14 20:04 UTC, merged

2022-11-14 20:06 UTC, Dusch4593 commented
Congrats and thank you very much for contributing to Codecademy Docs! 🚀 🎊 🎉

The entry should now be live: https://www.codecademy.com/resources/docs/swift/sets/subtracting

<img width="883" alt="Screen Shot 2022-11-14 at 3 05 41 PM" src="https://user-images.githubusercontent.com/23144845/201755133-fbaab55b-c80c-4310-b11b-4cb10a5685c7.png">

Looking forward to your next Docs contribution! 😄