Create scalb.md
Codecademy/docs pull request #1238
Opened 2022-11-12 03:15 UTC by Bobliuuu

### Description

Closes issue #911 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-11-12 14:37 UTC, SSwiniarski requested changes
@Bobliuuu I did a first review and left a couple of comments.

2022-11-12 14:37 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/scalb/scalb.md
> +Math.scalb(a, b)
```suggestion
Math.scalb(value, scale)
```

2022-11-12 14:37 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/scalb/scalb.md
> +The parameter a is of type `double` and the parameter b is of type `int`.
```suggestion
The parameter `value` is of type `double` and the parameter `scale` is of type `int`.
```

2022-11-12 14:46 UTC, Bobliuuu commented
Thanks @SSwiniarski!

2022-11-12 15:31 UTC, SSwiniarski approved these changes
@Bobliuuu Looks good for second review.

2022-11-14 06:33 UTC, yangc95 commented on content/java/concepts/math-methods/terms/scalb/scalb.md
> +Title: 'scalb()'
```suggestion
Title: '.scalb()'
```

2022-11-16 04:49 UTC, yangc95 reviewed
Just one more addition, looks good to merge after.

Let us know if you need direct assistance passing the checks! If you'd like to try it out yourself, that's also an option.

2022-11-16 04:49 UTC, yangc95 commented on content/java/concepts/math-methods/terms/scalb/scalb.md
> +public class Main {
```suggestion
// Main.java
public class Main {
```

2022-11-16 05:31 UTC, Bobliuuu commented
Yeah, I'm not exactly sure why the checks are failing. Could you let me know why?

2022-11-28 15:46 UTC, merged

2022-11-28 15:52 UTC, yangc95 commented
@Bobliuuu Live link: https://www.codecademy.com/resources/docs/java/math-methods/scalb
<img width="783" alt="Screen Shot 2022-11-28 at 10 50 38 AM" src="https://user-images.githubusercontent.com/72277593/204321617-384ee28c-ef97-4183-b1a7-702fcd88bdd8.png">
You're currently an anonymous contributor, but if you'd like to make yourself visible, make sure to add your GitHub username to your Codecademy Profile and make your account public.

cc: @SSwiniarski

2023-01-06 18:49 UTC, lucwhite commented
Hello @Bobliuuu,

I hope this message finds you well! My name is Lucas, and I work on the Curriculum team at Codecademy. Our team is considering ways to encourage more individuals to contribute to Codecademy Docs, and improve the contribution experience. We would like to hear from people such as yourself who contribute to Docs and I was wondering if you would be willing to participate in an interview to provide information on your background and experience with Docs contribution? 

The interview will take about an hour and will be conducted over Zoom. Should you agree to participate, we will find a time window using Calendly that works for you within the next three weeks. Let us know if you are interested in participating in an interview or have any questions by emailing me at the address below!

Best, 
Lucas White
lucas@codecademy.com