:fire: [New Term]: C++ Math-Functions: `.tanh()` (#981)
Codecademy/docs pull request #1251
Opened 2022-11-14 19:53 UTC by tanishq-singh-2301

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #981 in the "Description" above).

2022-11-14 20:46 UTC, Dusch4593 requested changes
@tanishq-singh-2301 This entry is already off to a great start! I just had a few comments/suggestions from my review. 😄

2022-11-14 20:46 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/tanh/tanh.md
> +}
```suggestion
int main() {
  double value = 1.0;
  double result = std::tanh(value);

  std::cout << "The value of tanh(" << value << ") is: " << result << "\n";
}
```

2022-11-14 20:46 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/tanh/tanh.md
> +{
```suggestion
int main() {
```

2022-11-14 20:46 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/tanh/tanh.md
> +The **`Math.tanh()`** function returns the hyperbolic tangent of an `double`-type arguement given in radians.
```suggestion
The **`Math.tanh()`** function returns the hyperbolic tangent of an `double`-type argument given in radians.
```

2022-11-14 20:46 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/tanh/tanh.md
> +
```suggestion

tanh(x) = (e<sup>x</sup> - e<sup>-x</sup>) / (e<sup>x</sup> + e<sup>-x</sup>)

```

While the \```tex blocks [are technically supported](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/#latex) in our content, they haven't been rendering as expected in our Docs entries (e.g., [here](https://www.codecademy.com/resources/docs/cpp/math-functions/cosh)).

2022-11-17 04:30 UTC, Dusch4593 requested changes
@tanishq-singh-2301 Just a few more comments, and then I'll approve 😄

2022-11-17 04:30 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/tanh/tanh.md
> +The **`Math.tanh()`** function returns the hyperbolic tangent of an `double`-type argument given in radians.
```suggestion
The **`Math.tanh()`** function returns the hyperbolic tangent of an angle given in radians.
```

2022-11-17 04:30 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/tanh/tanh.md
> +Description: 'Returns the hyperbolic tangent of a double-type value.'
```suggestion
Description: 'Returns the hyperbolic tangent of an angle given in radians.'
```

2022-11-17 04:30 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/tanh/tanh.md
> +```
@tanishq-singh-2301 Unfortunately, we aren't able to combine \```tex code with GH-flavored HTML (`<sup></sup>`). We have two options:

- Remove the \```tex backticks and keep `<sup></sup>`. (recommended)
- Remove `<sup></sup>` and keep \``` tex code block.
  - Again, this is not likely to render correctly at this time.

2022-11-17 04:46 UTC, Dusch4593 approved these changes
@tanishq-singh-2301 LGTM for the next review! 👍🏻

2022-11-18 20:31 UTC, HishamT approved these changes
LGTM!

2022-11-19 14:17 UTC, tanishq-singh-2301 commented
any update? @Dusch4593 @HishamT

2022-11-21 14:41 UTC, merged

2022-11-21 14:47 UTC, Dusch4593 commented
Congrats and thank you for another solid contribution to Codecademy Docs, @tanishq-singh-2301! 🎊 🎉 🥳

The entry should now be live: https://www.codecademy.com/resources/docs/cpp/math-functions/tanh

<img width="827" alt="Screen Shot 2022-11-21 at 9 46 24 AM" src="https://user-images.githubusercontent.com/23144845/203084050-4b92bfd3-ff26-48e7-a2c3-2205d00cf4f6.png">