added more information on for loops
Codecademy/docs pull request #1260
Opened 2022-11-17 20:04 UTC by bordenmike518

### Description

I added some more information about how the syntax of a for loop can be altered to achieve different results. One example is to leave the for loop empty which will create a for loop. Another interesting point to make is that all the parameters of a for loop do not need to be a made inside the parameter space.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-11-17 20:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1260) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1260) before we can accept your contribution.<br/><hr/>**Borden** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1260) it.</sub>

2022-11-18 02:51 UTC, Dusch4593 requested changes
Hey @bordenmike518! Thank you for contributing to Codecademy Docs! 😄

I had some feedback to offer, and some more to follow. But first, I wanted to just ask if you happened to [push](https://github.com/Codecademy/docs/pull/1260/commits/d449f55c1750ee6a274e156efea3ed10c2f3bc84) from a possibly different account named "Borden"?

2022-11-18 02:51 UTC, Dusch4593 commented on content/cpp/concepts/loops/loops.md
>  ```
```suggestion
```

I wouldn't recommend adding code for an infinite loop.

2022-11-18 02:51 UTC, Dusch4593 commented on content/cpp/concepts/loops/loops.md
> +{
```suggestion
for( ; i < 10; ) {
```

2022-12-12 14:50 UTC, Dusch4593 commented
Hey @bordenmike518 it's been a couple of weeks of inactivity on this PR. Did you have any questions or need any assistance with [the feedback](https://github.com/Codecademy/docs/pull/1260#pullrequestreview-1185379234) I gave?

2022-12-22 02:02 UTC, yangc95 commented
@bordenmike518 I'm not actually sure about the lines of code that were added here. It doesn't look like good practice even though it's possible to omit certain parameters,

What do we think? @Dusch4593 @HishamT

2022-12-23 13:07 UTC, yangc95 commented
Closing out this PR as the change does not seem to be good practice.

2022-12-28 23:28 UTC, yangc95 commented
@bordenmike518 apologies, upon further evaluation, it looks like it's a common practice among developers to omit certain parameters like this (it applies for other languages as well like Swift).

2022-12-28 23:33 UTC, yangc95 commented on content/cpp/concepts/loops/loops.md
> +  i++;
@bordenmike518 I would also like to see something about how we can add more than one condition and action.

`i++;` can go here or in the parenthesis.

2022-12-28 23:33 UTC, yangc95 commented on content/cpp/concepts/loops/loops.md
> +for( ; i < 10; ) {
```suggestion
for ( ; i < 10; ) {
```

2023-01-20 02:13 UTC, Dusch4593 commented
Since there's been a few weeks of inactivity on this PR, and because the CLA still has yet to be signed, I am closing it for now. Let us know if you have any questions about how we can reconcile this issue with the two GitHub usernames and we'll be happy to help. 😄

2023-01-20 02:14 UTC, closed without merging