New html term label
Codecademy/docs pull request #1268
Opened 2022-11-19 23:53 UTC by Armania

### Description

Adding a new entry for HTML term "label" tag. I tried to copy as much of the formatting from the input definition but I will need help reviewing this and making sure the style is matched. This is my first draft.

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [ x] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-11-19 23:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1268) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1268) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1268) it.</sub>

2022-11-20 14:33 UTC, SSwiniarski requested changes
@Armania. I did a first review and left some comments. The most important thing is to add the missing Metadata to the top of the file.

2022-11-20 14:33 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +# Label
The metadata for this entry is missing. You can look at the source for one of the other HTML entries to see what it looks like.  Also review the [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and the [entry template](https://github.com/Codecademy/docs/blob/main/documentation/entry-template.md).

2022-11-20 14:33 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +**Note:** Labels are important for accessbility. They allow screenreaders to connect this caption to its coresponding ui elements.
```suggestion
> **Note:** Labels are important for accessibility. They allow screenreaders to connect this caption to its corresponding UI elements.
```

2022-11-20 14:33 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +The <label> tag defines a label for several elements:
```suggestion
The <label> tag can define a label for several elements:
```

2022-11-20 14:33 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +**Note:** UI elements can be connected to any **`<label>`** element when placed between **`<label></label>`** tags.
```suggestion
> **Note:** UI elements can be connected to any `<label>` element when placed between `<label></label>` tags.
```

2022-11-20 14:33 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +Also, when a user clicks the text within the **`<label>`** element, it toggles the coresponding input. This is great for users who have difficulty clicking on very small ui elements such as checkboxe
```suggestion
Also, when a user clicks the text within the `<label>` element, it toggles the corresponding input. This is great for users who have difficulty clicking on very small UI elements such as checkboxes.
```

2022-11-20 14:33 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +**warning:** Do not place anchors, buttons, or any interactive ui element, between  **`<label></label>`** tags.
```suggestion
> **Note:** Do not place anchors, buttons, or any interactive UI element, between  `<label></label>` tags.
```

2022-11-20 14:33 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +The following examples uses a `<form>` element that features `<input>` elements with coresponding `<label>` tags:
```suggestion
The following examples uses a `<form>` element that features `<input>` elements with corresponding `<label>` tags:
```

2022-11-20 14:33 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +Multiple label elements can be used for the same ui element.
```suggestion
Multiple label elements can be used for the same UI element.
```

2022-11-27 12:54 UTC, SSwiniarski requested changes
@Armania, I left several more comments. One thing that needs to be fixed: The suggestion block surrounding the various suggested edits is not part of the edit. It's only marking the text that needs to be changed. The opening \`\`\`suggestion and closing \`\`\` should not be included in the edit.

2022-11-27 12:54 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +The **`<label/>`** element is used to identify captions for other HTML elements. This is most commonly used with form elements such as the [**`<input>`**](../input/input.md) element. The <label> tag
```suggestion
The **`<label/>`** element is used to identify captions for other HTML elements. This is most commonly used with form elements such as the [`<input>`](https://www.codecademy.com/resources/docs/html/elements/input) element. The `<label>` tag also supports the *Event Attributes* and the *Global Attributes* in HTML.
```

2022-11-27 12:54 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +```suggestion
Remove the suggestion block, just leave the sentence.

2022-11-27 12:54 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +The <label> tag can define a label for several elements:
```suggestion
The `<label>` tag can define a label for several elements:
```

2022-11-27 12:54 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +- [**`<input>`**](../input/input.md)
Remove the bold on these.

2022-11-27 12:54 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +> - They allow screenreaders to connect this caption to its coresponding ui elements.
```suggestion
> - They allow screen readers to connect this caption to its corresponding UI elements.
```

2022-11-27 12:54 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +> - Also, when a user clicks the text within the **`<label>`** element, it toggles the coresponding input. This is great for users who have difficulty clicking on very small ui elements such as check
```suggestion
> - Also, when a user clicks the text within the `<label>` element, it toggles the corresponding input. This is great for users who have difficulty clicking on very small UI elements such as checkboxes.
```

2022-11-27 12:54 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +```suggestion
remove the suggestion block and just leave the sentence.

2022-11-27 12:54 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +```suggestion
Remove the suggestion block and just leave the sentence.

2022-11-27 12:54 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +```suggestion
Remove the suggestion block and just leave the sentence.

2022-11-27 12:54 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +```suggestion
Remove the suggestion block and just leave the sentence.

2022-12-09 18:17 UTC, Armania commented
Wanted to check-in and see if I left anything undone

2022-12-10 12:54 UTC, SSwiniarski requested changes
@Armania there are still a number of edits to be done, primarily removing the ```suggestion blocks around text. You marked these resolved without making any edits. They still need to be removed.

2022-12-10 12:54 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +The `<label/>` element is used to identify captions for other HTML elements. This is most commonly used with form elements such as the [**`<input>`**](https://www.codecademy.com/resources/docs/html/e
```suggestion
The **`<label/>`** element is used to identify captions for other HTML elements. This is most commonly used with form elements such as the [`<input>`](https://www.codecademy.com/resources/docs/html/elements/input/input.md) element. The `<label>` tag also supports the *Event Attributes* and the *Global Attributes* in HTML.
```

2022-12-10 12:54 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +```suggestion
You still need to remove ```suggestion blocks around text.

2022-12-10 12:54 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +```suggestion
Still needs to be done

2022-12-10 12:54 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +```suggestion
Remove ```suggestion blocks around text

2022-12-10 12:54 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +```suggestion
Remove ```suggestion blocks around text.

2022-12-10 12:54 UTC, SSwiniarski commented on content/html/concepts/elements/terms/label/label.md
> +The following examples uses a `<form>` element that features `<input>` elements with coresponding `<label>` tags:
This still needs to be done.

2022-12-22 02:43 UTC, yangc95 commented
@Armania did this branch get rebased? I think I'd be best to create another PR off the `main` branch so all the authors aren't an issue for the CLA check. Thanks in advance!

2023-01-03 15:34 UTC, Armania commented
@yangc95 + @SSwiniarski , please see https://github.com/Codecademy/docs/pull/1429 for my new pull request

2023-01-03 16:25 UTC, SSwiniarski commented
Closing this in favor of [1429](https://github.com/Codecademy/docs/pull/1429).

2023-01-03 16:25 UTC, closed without merging