New Term: Aggressive Scan
Codecademy/docs pull request #1280
Opened 2022-11-27 17:03 UTC by SSwiniarski

### Description

New Nmap entry

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-11-28 01:07 UTC, KTom101 requested changes
@SSwiniarski I've added a few suggestions for this entry, thanks!

2022-11-28 12:26 UTC, SSwiniarski commented
@KTom101, I implemented your changes.

2022-11-30 05:43 UTC, KTom101 approved these changes
@SSwiniarski Looks good for the next review 👍

2022-12-07 17:41 UTC, Dusch4593 requested changes
@SSwiniarski Finished with my review and left some comments/suggestions.

2022-12-07 17:41 UTC, Dusch4593 commented on content/cybersecurity/concepts/nmap/terms/aggressive-scan/aggressive-scan.md
> +Description: 'An aggressive scan provides far better information than a standard scan, but is more likely to be detected.'
```suggestion
Description: 'Provides far better information than a standard scan, but is more likely to be detected.'
```

2022-12-07 17:41 UTC, Dusch4593 commented on content/cybersecurity/concepts/nmap/terms/aggressive-scan/aggressive-scan.md
> +````shell
```suggestion
```shell
```

2022-12-07 17:41 UTC, Dusch4593 commented on content/cybersecurity/concepts/nmap/terms/aggressive-scan/aggressive-scan.md
> +
We're missing closing backticks here.

2022-12-07 17:41 UTC, Dusch4593 commented on content/cybersecurity/concepts/nmap/terms/aggressive-scan/aggressive-scan.md
> +> **Note:** The site `scanme.nmap.org` is a site explicitly set up for testing Nmap. Only perform scans on domains you have explicit permission to scan.
```suggestion
> **Note:** This is a site explicitly set up for testing Nmap. Scans should only be performed on domains with explicit permissions given to the user.
```

2022-12-07 17:41 UTC, Dusch4593 commented on content/cybersecurity/concepts/nmap/terms/aggressive-scan/aggressive-scan.md
> +The following example runs an aggressive scan on the site `scanme.nmap.org`:
```suggestion
The following example runs an aggressive scan on the site [scanme.nmap.org](http://scanme.nmap.org/):
```

2022-12-07 17:41 UTC, Dusch4593 commented on content/cybersecurity/concepts/nmap/terms/aggressive-scan/aggressive-scan.md
> +An **aggressive scan** provides far better information than a [regular scan](https://www.codecademy.com/resources/docs/cybersecurity/nmap/nmap-scan), but is more likely to be detected. It is performe
```suggestion
An **aggressive scan** provides far better information than a [regular scan](https://www.codecademy.com/resources/docs/cybersecurity/nmap/nmap-scan), but is more likely to be detected. It is performed by using the `-A` option and enables the following:

- OS detection (`-o`)
- Version detection (`-sV`)
- Script scanning (`-sC`)
- Traceroute (`--traceroute`)

Aggressive scans send out more probes than a regular scan, and are more likely to be detected during a security audit.
```

2022-12-08 00:40 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM! 👍🏻

2022-12-08 00:40 UTC, merged