Create acosh entry and test all changes
Codecademy/docs pull request #1284
Opened 2022-11-29 01:21 UTC by ddiegow

### Description

Create acosh() entry. Closes #953 

### Type of Change

- Adding a new entry

### Checklist

- [.] All writings are my own.
- [.] My entry follows the Codecademy Docs style guide.
- [.] My changes generate no new warnings.
- [.] I have performed a self-review of my own writing and code.
- [.] I have checked my entry and corrected any misspellings.
- [.] I have made corresponding changes to the documentation if needed.
- [.] I have confirmed my changes are not being pushed from my forked `main` branch.
- [.] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [.] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-11-29 16:54 UTC, SSwiniarski approved these changes
@ddiegow, this looks good for a second review.

2022-12-14 07:51 UTC, KTom101 requested changes
@ddiegow I've added changes to this entry for you to take a look at.

2022-12-14 07:51 UTC, KTom101 commented on content/cpp/concepts/math-functions/terms/acosh/acosh.md
> +The `n` parameter can be a floating-point value (e.g., a `long` or `double`) or an integral type (e.g., an `int` or `bool`). `n` is mandatory and must be greater or equal to 1. If it is less than 1,
```suggestion
The `n` parameter can be a floating-point value (e.g., a `long` or `double`) or an integral type (e.g., an `int` or `bool`). `n` is mandatory and must be greater or equal to 1. Values less than 1 will result in a domain error.
```

2022-12-14 07:51 UTC, KTom101 commented on content/cpp/concepts/math-functions/terms/acosh/acosh.md
> +This example results in the following output:
```suggestion
This results in the following output:
```

2022-12-15 15:26 UTC, KTom101 approved these changes
@ddiegow Looks good to me 👍


@SSwiniarski any additional changes you want to add before merging?

2022-12-15 16:59 UTC, SSwiniarski commented
@KTom101, nope, everything looks good to me.

2022-12-17 19:46 UTC, merged

2022-12-17 23:06 UTC, KTom101 commented
Hi @ddiegow thank you for your contribution! You can see the entry is live here: https://www.codecademy.com/resources/docs/cpp/math-functions/acosh

I've noticed that your username has not been added as a contributor. May I ask if you:

                1.  Added your GitHub username to your Codecademy profile;
<img width="749" alt="Screen Shot 2022-12-17 at 5 57 07 PM" src="https://user-images.githubusercontent.com/40783324/208269140-bf88c079-0570-4ee5-9bad-9b8bfb958991.png">

                2. Log out and then log back in on Codecademy using your GitHub login information.
<img width="1273" alt="Screen Shot 2022-12-17 at 6 00 50 PM" src="https://user-images.githubusercontent.com/40783324/208269146-a875b81e-209e-4ce5-a523-c0b36812e39a.png">
n Codecademy using your GitHub profile