SwiftUI View: Ellipse shape
Codecademy/docs pull request #1292
Opened 2022-11-30 10:30 UTC by cilippofilia

### Description
Adding new entry for SwiftUI built in Ellipse shape.

### Type of Change
- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-12-01 17:37 UTC, SSwiniarski requested changes
@cilippofilia I did a first review and left some comments.

2022-12-01 17:37 UTC, SSwiniarski commented on content/swiftui/concepts/views/terms/ellipse/ellipse.md
> +The **`Ellipse`** is one of SwiftUI pre-built shapes like rectangles, circle, capsule which can be modified as wanted.
```suggestion
The **`Ellipse`** is one of SwiftUI pre-built shapes like rectangles, circles, and capsules which can be modified as wanted.
```

2022-12-02 10:36 UTC, cilippofilia commented on content/swiftui/concepts/views/terms/ellipse/ellipse.md
> +The **`Ellipse`** is one of SwiftUI pre-built shapes like rectangles, circle, capsule which can be modified as wanted.
How to I link the capsule shape if its not available online yet? only through my PR

2022-12-02 12:33 UTC, SSwiniarski commented on content/swiftui/concepts/views/terms/ellipse/ellipse.md
> +The **`Ellipse`** is one of SwiftUI pre-built shapes like rectangles, circle, capsule which can be modified as wanted.
@cilippofilia, Good point. Leave that unlinked for the moment since we don't know what order these are going to be merged.

2022-12-02 13:05 UTC, cilippofilia reviewed
Everything seems up to date with first comments @SSwiniarski

2022-12-02 13:06 UTC, cilippofilia commented
> Everything seems up to date with first comments @SSwiniarski

Although it says there is 1 change requested and I can't see it.

2022-12-02 16:55 UTC, SSwiniarski approved these changes
@cilippofilia, Looks good for a second review.

2022-12-03 10:55 UTC, cilippofilia commented
> @cilippofilia, Looks good for a second review.

Amazing! :)

2022-12-08 16:59 UTC, yangc95 commented on content/swiftui/concepts/views/terms/ellipse/ellipse.md
> +    // modifiers
```suggestion
        Modifiers here
```

2022-12-09 18:11 UTC, yangc95 commented on content/swiftui/concepts/views/terms/ellipse/ellipse.md
> +![Ellipse](https://raw.githubusercontent.com/Codecademy/docs/main/media/ellipse.png)
Thanks for renaming the file @cilippofilia! Is it possible to crop the image as well?

2022-12-09 18:16 UTC, yangc95 commented on content/swiftui/concepts/views/terms/ellipse/ellipse.md
> +Description: 'Built-in ellipse shape that can be modified as needed.'
```suggestion
Description: 'Creates an ellipse shape that can be modified as needed.'
```

2022-12-12 19:07 UTC, yangc95 approved these changes

2022-12-12 19:12 UTC, merged

2022-12-12 19:17 UTC, yangc95 commented
Looks good! @cilippofilia live link: https://www.codecademy.com/resources/docs/swiftui/views/ellipse
![Screen Shot 2022-12-12 at 2 16 38 PM](https://user-images.githubusercontent.com/72277593/207134397-26bf730a-4f4b-4bcb-9eb4-e112170bafd5.png)

cc: @SSwiniarski