make a sin method in java
Codecademy/docs pull request #1311
Opened 2022-12-08 16:30 UTC by Yash-Var

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-12-08 17:02 UTC, SSwiniarski requested changes
@Yash-Var, I did a first review and left a few comments.

2022-12-08 17:02 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/sin/sin.md
> +The **`Math.sin()`** method returns the sine of an angle argument, given in radians, in the range [-1,1].
```suggestion
The **`Math.sin()`** method returns the sine of an angle argument, given in radians. The result is in the range [-1,1].
```

2022-12-08 17:02 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/sin/sin.md
> +## sin() Return Value
Remove this header so the below is part of the Syntax section.

2022-12-08 18:34 UTC, Yash-Var commented
@SSwiniarski i have made changes ps review and merge it...

2022-12-09 16:22 UTC, Yash-Var commented
@SSwiniarski 
ps review

2022-12-09 16:39 UTC, SSwiniarski requested changes
A couple of more comments before it goes to a second review. Just need to remove a pair of line breaks.

2022-12-09 16:39 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/sin/sin.md
> +
```suggestion
```

2022-12-09 16:39 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/sin/sin.md
> +
```suggestion
```

2022-12-09 18:32 UTC, Yash-Var commented
@SSwiniarski done

2022-12-10 12:57 UTC, SSwiniarski requested changes
@Yash-Var just two more things.

2022-12-10 12:57 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/sin/sin.md
> +   - returns the `trigonometric` sine of the specified angle
```suggestion
- Returns the `trigonometric` sine of the specified angle.
```

2022-12-10 12:57 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/sin/sin.md
> +  -  returns `NaN` if the specified angle is NaN or infinity
```suggestion
- Returns `NaN` if the specified angle is NaN or infinity.
```

2022-12-10 14:43 UTC, Yash-Var commented
@SSwiniarski done

2022-12-10 14:47 UTC, SSwiniarski reviewed
@Yash-Var This looks good for a second review.

2022-12-10 14:47 UTC, SSwiniarski approved these changes

2022-12-12 08:45 UTC, Yash-Var commented
@jakemhiller  ps review and merge it ...

2022-12-13 18:52 UTC, Yash-Var commented
@SSwiniarski ps merge it .......

2022-12-14 12:55 UTC, SSwiniarski commented
@Yash-Var before it's merged, it needs to undergo another review by one of the maintainers.

2022-12-14 17:51 UTC, Dusch4593 requested changes
@Yash-Var Just had a few comments/suggestions for you. 😄

2022-12-14 17:51 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/sin/sin.md
> +```java
```suggestion
```shell
```

2022-12-14 17:51 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/sin/sin.md
> +The **`Math.sin()`** method returns the sine of an angle argument, given in radians. The result is in the range [-1,1].
```suggestion
The **`Math.sin()`** method returns the trigonometric sine of an angle argument, given in radians.
```

2022-12-14 17:51 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/sin/sin.md
> +- Returns `NaN` if the specified angle is NaN or infinity.
```suggestion

The `angle` parameter is expressed in radians.

- The result is in the range [-1,1].
- If the `angle` is `NaN` or infinity, `NaN` is returned.
```

2022-12-14 18:39 UTC, Yash-Var commented
@Dusch4593 done ps review.

2022-12-14 18:52 UTC, Dusch4593 requested changes
@Yash-Var After we've implemented these last two suggestions, we should be good to merge. 😄

2022-12-14 18:52 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/sin/sin.md
> +}
```suggestion
public class Check {
  public static void main(String args[]) {
    // convert degrees to radians
    double pi = Math.PI;
    double degree = 60;
    double radian = degree * pi/180;
    System.out.println( "Sine of 60 degrees is " + Math.sin(radian));
  }
}
```

2022-12-14 19:34 UTC, Yash-Var commented
@Dusch4593 done Ps review and merge it ..

2022-12-15 13:34 UTC, Dusch4593 approved these changes
@Yash-Var LGTM! 👍🏻

Could you catch up your `main` branch with the base branch so we can merge?

<img width="949" alt="Screen Shot 2022-12-15 at 8 33 48 AM" src="https://user-images.githubusercontent.com/23144845/207872178-00b1f21c-c745-4e55-aba7-21fab1a5f3d7.png">

2022-12-15 16:54 UTC, Yash-Var commented
@Dusch4593 check.

2022-12-17 05:32 UTC, Yash-Var commented
@Dusch4593 ps review and merge it...

2022-12-17 14:12 UTC, Dusch4593 commented
@Yash-Var Sorry, let's fetch/merge the base `main` branch one more time and I'll be on standby to merge. 😄

(I would do this on my end but I think you have a branch protection setting in place that only lets the original PR author do this)

2022-12-17 16:45 UTC, Yash-Var commented
@Dusch4593  i have rebased the branch ps review..

2022-12-17 16:46 UTC, merged

2022-12-17 16:55 UTC, Yash-Var commented
@Dusch4593 @SSwiniarski do you have more project in which i can contribute ...
ps help in finding the project in which i can contribute...

2022-12-18 02:37 UTC, KTom101 commented
@Yash-Var Feel free to take a look at the [issues tab](https://github.com/Codecademy/docs/issues) to see if there are any unclaimed issues you're interested in working on. 

Otherwise, if there is a specific topic that you noticed is missing from Codecademy then you can make a new issue for it. One of us will review it and let you know if it looks ok to add.

2022-12-22 19:22 UTC, yangc95 commented
@Yash-Var live link: https://www.codecademy.com/resources/docs/java/math-methods/sin
<img width="823" alt="Screen Shot 2022-12-22 at 2 19 56 PM" src="https://user-images.githubusercontent.com/72277593/209210826-59dbfbab-31fe-409f-8ce8-36ba82a9370e.png">
Looks like you're all set with this entry, great work!

cc: @Dusch4593 @KTom101 @SSwiniarski