Add the arrays.md file
Codecademy/docs pull request #1326
Opened 2022-12-11 15:30 UTC by DominikFeret

### Description

I created an entry about arrays in go, trying to exhaust the topic as much as I can. I did it as a part of the "Learn Git & Github" course on Codecademy.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-12-11 15:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1326) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1326) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1326) it.</sub>

2022-12-13 00:02 UTC, Dusch4593 commented
Hi @DominikFeret! 👋🏻

Thank you for contributing to Docs! 🚀 I'll be conducting review 1️⃣ for this PR and will tag you again once I'm finished. 😄

2022-12-13 01:02 UTC, Dusch4593 requested changes
@DominikFeret Finished with taking a look a left some you some comments/suggestions to check out. Let me know if you have any questions with implementing the feedback. 😄

2022-12-13 01:02 UTC, Dusch4593 commented on content/go/concepts/arrays/arrays.md
> +// Output: {{1, 0}, {0, 2}, {3, 0}}
```suggestion

// Create an array of two arrays containing two floating point numbers
twoDim = [2][2]float64{{3.14, 2.72}, {2.1, 3.7}}

fmt.Println(twoDim)
```

2022-12-13 01:02 UTC, Dusch4593 commented on content/go/concepts/arrays/arrays.md
> +
```suggestion
```

This content could be incorporated in the previous \```go snippet (as suggested above).

2022-12-13 01:02 UTC, Dusch4593 commented on content/go/concepts/arrays/arrays.md
> +```go
Since Go is a compatible language with Codebytes, we should utilize it for the last example code block for this entry. 😄

2022-12-18 15:34 UTC, DominikFeret commented
Thank you for the review! I applied the suggested changes, along with fixing some inconsistencies within snippets. Looking forward to the next review 😄.

2022-12-20 14:01 UTC, Dusch4593 requested changes
Hey @DominikFeret thank you for implementing that feedback! 😄

I had just a few more comments/suggestions to offer before we proceed to the next review.

2022-12-20 14:01 UTC, Dusch4593 commented on content/go/concepts/arrays/arrays.md
> +**Arrays** are numbered sequences of elements of the same [data type](https://www.codecademy.com/resources/docs/go/data-types).
The meta-`Description` and opening sentence of an entry should be near-identical and include the same keywords like "numbered" and "fixed-length."

2022-12-20 23:00 UTC, DominikFeret commented
Done!

2022-12-20 23:32 UTC, Dusch4593 approved these changes
@DominikFeret Looks good for the next review! 👍🏻

2022-12-30 03:18 UTC, KTom101 requested changes
@DominikFeret I've added a second review.

2022-12-31 00:58 UTC, KTom101 approved these changes
@DominikFeret Thanks for uploading the changes! Do you need assistance with fixing the failed checks?

2022-12-31 18:00 UTC, DominikFeret commented
I followed the Docs Contribution Guide. Hopefully, this will work. Cheers!

2023-01-03 00:50 UTC, merged

2023-01-03 01:03 UTC, Dusch4593 commented
Congrats and thank you, @DominikFeret! 🥳

The new entry should now be live: https://www.codecademy.com/resources/docs/go/arrays

Currently, your profile is anonymously listed on the entry page. To make it visible, you'll need to add your GitHub username to your Codecademy profile, then log out of Codecademy and back in through your GitHub account:

<img width="839" alt="Screen Shot 2023-01-02 at 8 00 14 PM" src="https://user-images.githubusercontent.com/23144845/210288339-0bac6aed-80d5-4aa0-bd7f-ccd3ab211e77.png">

I also noticed that the Codebyte Example (lines # 98-115) doesn't run properly since the code isn't nested inside a `main()` function. Would you be open to opening a new PR to make the following change?

```
package main
import "fmt"
func main() {
  // Create an array of three arrays containing two integers
var twoDim [3][2]int

  // Accessing the first item of the first array
twoDim[0][0] = 1

  // Accessing the second item of the second array
twoDim[1][1] = 2

  // Accessing the first item of the third array
twoDim[2][0] = 3

  fmt.Println(twoDim)

  // Create an array of two arrays containing two floating-point numbers
twoDim := [2][2]float64{{3.14, 2.72}, {2.1, 3.7}}

  fmt.Println(twoDim)
}
```

2023-01-03 10:43 UTC, DominikFeret commented
Oh, that's right, I completely forgot that it's a Codebyte Example, will work on that. Thanks for pointing thit out!

2023-01-03 11:55 UTC, DominikFeret commented
I made a new pull request, making sure the code compiles this time 👉 👈 : https://github.com/Codecademy/docs/pull/1426