System.Math
Codecademy/docs pull request #1327
Opened 2022-12-11 17:34 UTC by Zakalvve

### Description
Closes #<issue 1322>
Added the system-math.md file to a new directory system-math within existing directory c-sharp. The   ##content covers basic use of the System.Math class that comes with C#. It also concludes by introducing a table that has currently not been created but is intended to contain a list of associated methods and properties of the Math class.

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-12-11 17:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1327) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1327) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1327) it.</sub>

2022-12-12 17:26 UTC, SSwiniarski requested changes
@Zakalvve, I did a first review and left a few comments.

2022-12-13 15:09 UTC, Zakalvve commented
Hi @SSwiniarski thanks for your review,

I have made the changes that you suggested. 

In addition I decided to keep the external link to learn more about .NET. You can see my reasoning in the commit. If the Codecademy docs were to grow to include .NET then the link would need to be changed.

If you decide it is not relevant then I will remove after a second review.

Thanks.

2022-12-13 15:11 UTC, Zakalvve commented on content/c-sharp/concepts/system-math/system-math.md
> +<details>
Point referenced in commit: [Re-formatted external link to conform with guidelines.](https://github.com/Codecademy/docs/pull/1327/commits/242341a552b9513f02213f2667a32d62f0e524e8).

2022-12-13 16:55 UTC, SSwiniarski approved these changes
@Zakalvve, looks good for a second review.

2022-12-15 14:54 UTC, Zakalvve commented
Are we just waiting for a second reviewer or is there something I need to do?

I see some of the checks failed. Is that something I need to correct? One says that all files should end with a new line character. Should I add that?

Sorry quite new to this!

2022-12-15 16:56 UTC, SSwiniarski commented
@Zakalvve we're just waiting on another maintainer to give this a second review.

2022-12-31 21:57 UTC, KTom101 requested changes
@Zakalvve I've added a second review. Please reach out with any questions. Note, one main change that needs to be made is changing the title from "system.math" to "Math Functions" this just makes it a little clearer and easier to find within the topics. Changing this means the file name will need to be changed too from 
`content/c-sharp/concepts/system-math/system-math.md` ---> `content/c-sharp/concepts/math-functions/math-functions.md`

2022-12-31 21:57 UTC, KTom101 commented on content/c-sharp/concepts/system-math/system-math.md
> +
```suggestion
```

2022-12-31 21:57 UTC, KTom101 commented on content/c-sharp/concepts/system-math/system-math.md
> +int x = Math.Pow(4,2); //raise 4 to the 2nd power
Can we add a line printing out the variable to make it more interactive? Also Math.Pow returns a "double".
```suggestion
public class Example
{
  public static void Main(string[] args)
  {
      // Raise 4 to power of 2
      double x = Math.Pow(4,2);
      
      Console.WriteLine("x = {0}", x);
      // Output: x = 16
  }
}
```

2022-12-31 21:57 UTC, KTom101 commented on content/c-sharp/concepts/system-math/system-math.md
> +//expected: x = 1
```suggestion
```

2022-12-31 21:57 UTC, KTom101 commented on content/c-sharp/concepts/system-math/system-math.md
> +
```suggestion
```

2023-01-14 15:10 UTC, SSwiniarski commented
@Zakalvve it's been a couple of weeks, do you need assistance in implementing the feedback?

2023-01-15 23:20 UTC, Zakalvve commented
@SSwiniarski Sorry for the delay. I have made a new commit to conform with KTom101's review. Thanks.

2023-01-17 23:27 UTC, KTom101 reviewed
@Zakalvve I've added a few more changes.

2023-01-17 23:27 UTC, KTom101 commented on content/c-sharp/concepts/math-functions/math-functions.md
> +
Add a quick explanation of what the following example is 
```suggestion

The following example uses the `Math.Pow()` method to return the result of 4 raised to the power of 2:

```

2023-01-17 23:27 UTC, KTom101 commented on content/c-sharp/concepts/math-functions/math-functions.md
> +In cases where access to System.Math is required but access to the entire System namespace is not. The following syntax can be used instead:
```suggestion
In cases where access to System.Math is required but access to the entire System namespace is not. The following example uses an alternative syntax and returns the floor of `3/2` using the `System.Math.Floor()` method:
```

2023-01-23 17:45 UTC, Zakalvve commented
@SSwiniarski @KTom101 I have made a new commit which implements the suggested changes.

2023-01-23 22:23 UTC, KTom101 commented
@Zakalvve Thank you for adding the changes. I'm noticing that some additional finals were added in the last commit. Would you be able to remove those files?

2023-01-23 22:32 UTC, Zakalvve commented
@KTom101 Thanks for your response. I have removed the erroneous directory.

2023-01-24 12:47 UTC, SSwiniarski approved these changes
@KTom101 looks good to merge.

2023-01-25 19:58 UTC, merged

2023-01-25 19:59 UTC, Zakalvve commented
@SSwiniarski @KTom101 Thanks for the support.

2023-01-25 22:32 UTC, KTom101 commented
@Zakalvve Thanks for contributing! You can look at the live link here: https://www.codecademy.com/resources/docs/c-sharp/math-functions

I'm noticing you're not coming up as a contributor, though. If you wish to receive credit can you make sure you've added your GitHub username to your Codecademy profile using the following steps:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

<img width="871" alt="YourGitHubName" src="https://user-images.githubusercontent.com/40783324/214706373-b2b0397b-da7d-4007-95f8-56ca8686ac24.png">

2) Then log out and log back into Codecademy using your GitHub login:

<img width="1273" alt="ReLogIn" src="https://user-images.githubusercontent.com/40783324/214706585-52d7394a-a1ce-4275-8674-4d3dc125b287.png">

Let me know if you need any help if you decide to do so! 😁