Milin edit documentation python threads example
Codecademy/docs pull request #1328
Opened 2022-12-11 22:18 UTC by milin-fr

### Description

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above). - There were no open issues corresponding to this pull request.

2022-12-11 22:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1328) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1328) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1328) it.</sub>

2022-12-12 17:16 UTC, SSwiniarski requested changes
@milin-fr, I did a first review and left a few comments, generally to do with the spacing of the code example. (We like indents to be two spaces rather than four.)

2022-12-12 17:32 UTC, milin-fr commented
Thank you for the review! I accepted the changes (and hope you didn’t get spammed with email for each action : )

2022-12-12 20:07 UTC, milin-fr reviewed
Thank you for the review! I accepted suggested changes and will keep in mind 2 spaces for future commits.

2022-12-13 16:49 UTC, SSwiniarski approved these changes
@milin-fr Looks good for a second review.

2022-12-21 18:42 UTC, Dusch4593 commented
Hey @milin-fr I'll do the next review for this PR! 😄

2022-12-21 19:04 UTC, Dusch4593 requested changes
@milin-fr Left you some comments/suggestions to check out and implement. 😄 Excellent example!

2022-12-21 19:04 UTC, Dusch4593 commented on content/python/concepts/threading/threading.md
> +run_threads()
```suggestion
def run_threads():
  threads = []
  
  for thread_index in range(5):
    individual_thread = threading.Thread(target=slow_function, args=(thread_index,))
    threads.append(individual_thread)
    individual_thread.start()

  # at this point threads are running independently from the main flow of application and each other
  print("Main flow of application")
  
  # This ensures that all threads finish before the main flow of application continues
  for individual_thread in threads:
    individual_thread.join()
  
  print("All threads are done")

run_threads()
```

2022-12-21 19:04 UTC, Dusch4593 commented on content/python/concepts/threading/threading.md
> +This results in output like the following
```suggestion
This results in output like the following:
```

2022-12-21 20:27 UTC, milin-fr commented
Thank you for the review !

2022-12-21 23:33 UTC, Dusch4593 approved these changes
@milin-fr LGTM! 👍🏻

Made a super small edit in 2ae8f4ec5d3153caf2602e5d21af7bbbc6980f07 but looks good for merge, otherwise! 😄

2022-12-21 23:36 UTC, merged

2022-12-21 23:44 UTC, Dusch4593 commented
Congrats and thank you so much for contributing to Codecademy Docs, @milin-fr! 🎊 🎉 🥳

The changes should be live: https://www.codecademy.com/resources/docs/python/threading

Currently, your Codecademy profile is anonymous on the entry page. To make it visible, you'll need to add to your GitHub username to your Codecademy profile, log out of Codecademy, and then log back in through your GitHub account.

Looking forward to your next Docs contribution! 😄