Term entry remquo
Codecademy/docs pull request #1339
Opened 2022-12-15 01:15 UTC by ddiegow

### Description

Create remquo entry.  Closes #988 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-12-15 17:47 UTC, SSwiniarski requested changes
@ddiegow I did a first review and only had one comment.

2022-12-15 17:47 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/remquo/remquo.md
> +The remquo function calculates the floating-point remainder `f` of `numerator / denominator` such that `numerator = n * denominator + f*`, where n is an integer, f has the same sign as x, and the abs
```suggestion
The remquo function calculates the floating-point remainder `f` of `numerator / denominator` such that `numerator = n * denominator + f*`, where n is an integer, `f` has the same sign as `numerator`, and the absolute value of `f` is less than the absolute value of `denominator`.
```

2023-01-05 02:00 UTC, KTom101 requested changes
@ddiegow I've added a second review.

2023-01-08 04:16 UTC, KTom101 approved these changes
@ddiegow This looks good, thank you for making the changes. 

@SSwiniarski Did you have any additional changes you would like to make to this?

2023-01-08 15:01 UTC, SSwiniarski approved these changes
@ddiegow Looks good to me.

2023-01-09 00:41 UTC, merged

2023-01-09 01:04 UTC, KTom101 commented
@ddiegow Thank you for contributing. The entry is live here: https://www.codecademy.com/resources/docs/cpp/math-functions/remquo

I noticed you are listed as an anonymous contributor:
![Screen Shot 2023-01-08 at 7 50 02 PM](https://user-images.githubusercontent.com/40783324/211227321-fd405350-a8f9-4233-b00f-a879ad804836.png)

If you want to be listed as a contributor, please follow the steps below to add your GitHub username to your Codecademy Profile:

1.  Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile"  in the drop-down box:

<img width="871" alt="Screen Shot 2023-01-08 at 7 56 27 PM" src="https://user-images.githubusercontent.com/40783324/211227735-d304fd9e-6590-44c6-b676-b8791e913a8a.png">

2. Then log out and log back into Codecademy using your GitHub login:

<img width="1273" alt="Log in to Codecademy" src="https://user-images.githubusercontent.com/40783324/211227804-b04d0db2-ef71-4fd8-adee-f3080974149c.png">

Let me know if you need any help if you decide to do so.