My branch
Codecademy/docs pull request #1344
Opened 2022-12-16 07:17 UTC by GregV3

### Description

I've decided to update the text about JavaScript's variables in the location Docs/JavaScript/Variables. I think it is worth mentioning that it is one of the dynamic typing languages.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [X ] All writings are my own.
- [X ] My entry follows the Codecademy Docs style guide.
- [X ] My changes generate no new warnings.
- [X ] I have performed a self-review of my own writing and code.
- [X ] I have checked my entry and corrected any misspellings.
- [X ] I have made corresponding changes to the documentation if needed.
- [X ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-12-16 07:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1344) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1344) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1344) it.</sub>

2022-12-16 16:54 UTC, SSwiniarski requested changes
@GregV3, I did a first review and left a couple of comments. You also need to sign the [CLA](https://cla-assistant.io/Codecademy/docs?pullRequest=1344).

2023-01-26 01:18 UTC, yangc95 commented on content/javascript/concepts/variables/variables.md
> +  - 'Dynamic typing'
```suggestion
```

2023-01-26 01:24 UTC, yangc95 commented
@GregV3 @SSwiniarski I helped push up some of the requested changes! Is there anything else that needs improving before moving this PR on to a second review?

TY for everyone's efforts here ^^ this looks to be a short and sweet addition to this entry.

2023-01-26 16:30 UTC, SSwiniarski approved these changes
@yangc95, @GregV3 Looks good to merge.

2023-01-28 03:55 UTC, yangc95 approved these changes

2023-01-28 03:57 UTC, yangc95 commented on content/javascript/concepts/variables/variables.md
> +## Dynamic typing
```suggestion
## Dynamic Typing
```

2023-01-28 04:02 UTC, yangc95 commented on content/javascript/concepts/variables/variables.md
> +Unlike many programming languages, JavaScript doesn't force the user to specify a variable's data type. It assumes the data type based on the way a user assigns a value. For example, the example belo
```suggestion
Unlike many programming languages, JavaScript doesn't force the user to specify a variable's [data type](https://www.codecademy.com/resources/docs/javascript/data-types). It assumes the data type based on the value. The example below assigns a string to a variable by enclosing some numbers in single quotation marks. Without them, JavaScript reads the value as a number.
```

2023-01-28 04:04 UTC, yangc95 commented on content/javascript/concepts/variables/variables.md
> +Unlike many programming languages, JavaScript doesn't force the user to specify a variable's [data type](https://www.codecademy.com/resources/docs/javascript/data-types). It assumes the data type bas
```suggestion
Unlike many programming languages, JavaScript doesn't require the user to specify a variable's [data type](https://www.codecademy.com/resources/docs/javascript/data-types). It assumes the data type based on the value. The example below assigns a string to a variable by enclosing some numbers in single quotation marks. Without them, JavaScript reads the value as a number.
```

2023-01-28 04:05 UTC, merged