SwiftUI View: Stepper
Codecademy/docs pull request #1351
Opened 2022-12-18 13:13 UTC by cilippofilia

### Description

Stepper is a great tool when giving user granulated control over a specific range of numbers

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-12-31 21:15 UTC, cilippofilia commented
@SSwiniarski @yangc95 @KTom101 can someone start reviewing this PR please?

2023-01-01 15:09 UTC, SSwiniarski requested changes
@cilippofilia, I did a first review and left a comment.

2023-01-01 15:09 UTC, SSwiniarski commented on content/swiftui/concepts/views/terms/stepper/stepper.md
> +- The first parameter that `Stepper` takes is `value:`. This parameter needs to be bound to a variable that tracks changes.
This bulleted list should be moved to the end of the syntax section.

2023-01-03 16:38 UTC, SSwiniarski approved these changes
@cilippofilia looks good for a second review.

2023-01-04 04:11 UTC, yangc95 approved these changes

2023-01-04 04:13 UTC, merged

2023-01-06 19:02 UTC, lucwhite commented
Hello @cilippofilia,

I hope this message finds you well! My name is Lucas, and I work on the Curriculum team at Codecademy. Our team is considering ways to encourage more individuals to contribute to Codecademy Docs and improve the contribution experience. I was wondering if you would be willing to participate in an interview to provide information on your background and experience with Docs contribution?

The interview would take about an hour and be conducted over Zoom. Should you agree to participate, we will find a time window using Calendly that works for you within the next three weeks. Let us know if you are interested in participating in an interview or have any questions by responding with your email address or emailing me at the address below!

Best,
Lucas White
lucas@codecademy.com

2023-01-06 19:09 UTC, cilippofilia commented
Hey Lucas,

Absolutely! I am available tuesdays, wednesdays, thursays all day. Any
other day before 11am.

Have a great weekend!

Filippo


On Fri, 6 Jan 2023 at 19:02, Lucas White ***@***.***> wrote:

> Hello @cilippofilia <https://github.com/cilippofilia>,
>
> I hope this message finds you well! My name is Lucas, and I work on the
> Curriculum team at Codecademy. Our team is considering ways to encourage
> more individuals to contribute to Codecademy Docs and improve the
> contribution experience. I was wondering if you would be willing to
> participate in an interview to provide information on your background and
> experience with Docs contribution?
>
> The interview would take about an hour and be conducted over Zoom. Should
> you agree to participate, we will find a time window using Calendly that
> works for you within the next three weeks. Let us know if you are
> interested in participating in an interview or have any questions by
> responding with your email address or emailing me at the address below!
>
> Best,
> Lucas White
> ***@***.***
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Codecademy/docs/pull/1351#issuecomment-1374014897>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK3C23BJNOIV5CHFKLWK3GLWRBT4HANCNFSM6AAAAAATCQTW3I>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-06 19:11 UTC, cilippofilia commented
Hey Lucas,

Absolutely! I am available tuesdays, wednesdays, thursays all day. Any
other day before 11am.

Have a great weekend!

Filippo