Functor branch
Codecademy/docs pull request #1366
Opened 2022-12-22 06:29 UTC by arestrepogiraldo2200

### Description
I created a new entry in the cpp/concepts/ directory called functors (not functions). Inside the cpp/concepts/functors there is a markdown functors.md with the topics and format according to the template suggested. 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-12-22 06:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1366) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1366) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1366) it.</sub>

2022-12-23 17:46 UTC, SSwiniarski requested changes
@arestrepogiraldo2200 I did a first review and left a few comments.

2022-12-23 17:46 UTC, SSwiniarski commented on content/cpp/concepts/functors/functors.md
> +
Remove the line break before the metadata.

2022-12-23 17:46 UTC, SSwiniarski commented on content/cpp/concepts/functors/functors.md
> +
Remove the extra line breaks between the metadata sections.

2022-12-23 17:46 UTC, SSwiniarski commented on content/cpp/concepts/functors/functors.md
> +
Remove extra line break after metadata.

2022-12-23 17:46 UTC, SSwiniarski commented on content/cpp/concepts/functors/functors.md
> +A **functor** is an object or struct that can be called like a function by overloading the function-call operator (). Public access must be granted to the overloading of () operator in order to be us
```suggestion
A **functor** is an object or struct that can be called like a function by overloading the function-call operator `()`. Public access must be granted to the overloading of the `()` operator in order to be used as intended. Functors can simplify tasks and improve efficiency in many cases.
```

2022-12-23 17:46 UTC, SSwiniarski commented on content/cpp/concepts/functors/functors.md
> +where `type` is the [data type](https://www.codecademy.com/resources/docs/cpp/data-types) to be returned and `(...)`are the arguments to be given for the execution. Then, to use the functor just crea
```suggestion

Where `type` is the [data type](https://www.codecademy.com/resources/docs/cpp/data-types) to be returned and `(...)`are the arguments to be given for the execution. Then, to use the functor just create an instance of the class and when needed call it passing the arguments required as
```

2022-12-23 17:46 UTC, SSwiniarski commented on content/cpp/concepts/functors/functors.md
> +returns
```suggestion
Results in the following output:
```

2022-12-23 17:46 UTC, SSwiniarski commented on content/cpp/concepts/functors/functors.md
> +The following code
```suggestion
The following code:
```

2022-12-24 15:00 UTC, arestrepogiraldo2200 commented
Hello @SSwiniarski, I just adopted the corrections you suggested. Merry christmas.

2022-12-26 14:31 UTC, SSwiniarski requested changes
@arestrepogiraldo2200 I had just a couple more comments.

2022-12-26 14:31 UTC, SSwiniarski commented on content/cpp/concepts/functors/functors.md
> +```cpp
change this to a ```pseudo block.

2022-12-26 14:31 UTC, SSwiniarski commented on content/cpp/concepts/functors/functors.md
> +```cpp
Make this a ```pseudo block

2022-12-26 17:44 UTC, arestrepogiraldo2200 commented
Done

2022-12-27 12:38 UTC, SSwiniarski requested changes
@arestrepogiraldo2200 just two more things.

2022-12-27 12:38 UTC, SSwiniarski commented on content/cpp/concepts/functors/functors.md
> +```pseudo block
just ```pseudo

2022-12-27 12:38 UTC, SSwiniarski commented on content/cpp/concepts/functors/functors.md
> +```pseudo block
just ```pseudo

2022-12-27 15:13 UTC, arestrepogiraldo2200 commented
@SSwiniarski correction done

2022-12-27 16:42 UTC, SSwiniarski approved these changes
@arestrepogiraldo2200 Looks good for a second review.

2023-01-18 22:11 UTC, arestrepogiraldo2200 commented
Hello guys I'm still waiting for feedback. Thanks a lot. :grinning:

2023-01-27 17:18 UTC, yangc95 reviewed
@arestrepogiraldo2200 thanks for following up! Just went over this entry and added some comments/suggestions. Tag me when you've resolved these 🙂 or if you want to discuss something

2023-01-27 17:18 UTC, yangc95 commented on content/cpp/concepts/functors/functors.md
> +        void operator()(int times){
It may be good to include something about this operator function.

2023-01-27 21:53 UTC, arestrepogiraldo2200 commented on content/cpp/concepts/functors/functors.md
> +Description: 'A functor is an object or struct that can be called like a function by overloading the function-call operator ().'
A functor can be created from either a `class` or a `struct`. I based mainly in the following:

[GeeksForGeeks](https://www.geeksforgeeks.org/functors-in-cpp/)
[Programiz](https://www.programiz.com/cpp-programming/functors)
[StackOverflow](https://stackoverflow.com/questions/356950/what-are-c-functors-and-their-uses)

I just wrote a little example with a struct:

```cpp
#include<iostream>
using namespace std;

int main(){

   struct functor{
      int x; 
      void operator ()(int y){ 
          x += y;
      }
   };
   
   functor example;               // creates struct instance
   example.x = 3;                  // sets x to 3
   example(4);                      // runs operator overload with instance "example"
   cout<<"Now x is: "<<example.x<<endl;        // prints "Now x is 7"

   return 0;
}
```

2023-01-27 22:13 UTC, yangc95 commented on content/cpp/concepts/functors/functors.md
> +Description: 'A functor is an object or struct that can be called like a function by overloading the function-call operator ().'
Thanks for sharing! Maybe it's a good idea to have both class and structure mentioned

2023-02-08 02:39 UTC, arestrepogiraldo2200 commented
Hello @yangc95 :wave:. I have implemented some of the corrections you indicated. Please tell me what do you think.

2023-02-27 03:02 UTC, yangc95 approved these changes

2023-02-27 03:04 UTC, merged

2023-02-27 03:07 UTC, yangc95 commented
@arestrepogiraldo2200 very happy to finally get this entry up! Thanks for your resilience throughout this process. Here's the live link: https://www.codecademy.com/resources/docs/cpp/functors

![Screen Shot 2023-02-26 at 10 05 42 PM](https://user-images.githubusercontent.com/72277593/221463569-b0133477-abe3-4b8a-8e18-d0da14a7c7ca.png)

> It looks as if you're anonymous. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.
> 
> To add your GitHub username to your Codecademy profile:
> 
> 1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
> 
> ![image](https://user-images.githubusercontent.com/86081858/220699030-55a1ef72-d1d1-40ab-942a-9e34ba4dbb13.png)
> 
> 2.) Then log out and log back into Codecademy using your GitHub login:
> 
> <img width="976" alt="githublogin" src="https://user-images.githubusercontent.com/72277593/221382073-53f7e2ed-5e39-4eb4-a993-b54a07ce72f6.png">


cc: @SSwiniarski @KTom101