New Term: Ping-Sweep
Codecademy/docs pull request #1368
Opened 2022-12-22 08:23 UTC by cscalora05

### Description

- Creating new directory ping-sweep
- Creating new ping-sweep documentation: .md
- Closes #1314

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [] I have checked my entry and corrected any misspellings.
- [] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-12-22 08:32 UTC, cscalora05 commented
sending this to review even though workflows haven't completed in draft as I believe someone needs to approve running the workflows since this is my first time contributing.

2022-12-22 12:55 UTC, SSwiniarski requested changes
@cscalora05 I did a first review and left a comment.

2022-12-22 12:55 UTC, SSwiniarski commented on content/cybersecurity/concepts/nmap/terms/ping-sweep/ping-sweep.md
> +The above identifies all of the IP addresses that are currently online without sending any packets to these hoss.
```suggestion
The above identifies all of the IP addresses that are currently online without sending any packets to these hosts.
```

2022-12-23 13:05 UTC, SSwiniarski approved these changes

2022-12-23 13:05 UTC, SSwiniarski commented
@cscalora05 Looks good for a second review.

2022-12-23 13:11 UTC, yangc95 commented on content/cybersecurity/concepts/nmap/terms/ping-sweep/ping-sweep.md
> +A **ping-sweep** is a network scanning technique to identify active devices on a network by pinging a range of IP addresses. It is specified with the `-sn` option.  Commpared to other methods, ping s
```suggestion
A **ping-sweep** is a network scanning technique to identify active devices on a network by pinging a range of IP addresses. It is specified with the `-sn` option.  Compared to other methods, ping sweeps can be harder to detect as it is not as aggressive and can skip regular scan stages, making it more of an advantage.
```

2022-12-23 13:11 UTC, yangc95 commented on content/cybersecurity/concepts/nmap/terms/ping-sweep/ping-sweep.md
> +nmap -sn <subnet>/<mask>
```suggestion
nmap -sn subnet/mask
```

2022-12-23 13:11 UTC, yangc95 commented on content/cybersecurity/concepts/nmap/terms/ping-sweep/ping-sweep.md
> +The above identifies all of the IP addresses that are currently online without sending any packets to these hosts.
Can we also include some description about `subnet` and `mask` here?

2022-12-23 13:15 UTC, yangc95 commented on content/cybersecurity/concepts/nmap/terms/ping-sweep/ping-sweep.md
> +The following example runs a ping-sweep on `192.168.0.1/24`:
Can we refer to subnet IP and mask as the host rather than the specific example? cc: @SSwiniarski

2022-12-23 13:17 UTC, yangc95 requested changes
@cscalora05 I did a second review on this PR. Please let me know if you have any questions/concerns by tagging me. Also, I have two comments up for discussion ([Comment1](https://github.com/Codecademy/docs/pull/1368/files#r1056334665) & [Comment2](https://github.com/Codecademy/docs/pull/1368/files#r1056334956)); hopefully we can find the best way to document this term 🙂 thanks for your efforts!

2022-12-29 18:52 UTC, cscalora05 commented
Hi @yangc95 - please see new commit with revised changes addressing your comments. Thank you

2022-12-30 13:47 UTC, yangc95 approved these changes

2022-12-30 14:16 UTC, yangc95 approved these changes

2022-12-30 14:17 UTC, merged

2022-12-30 14:23 UTC, yangc95 commented
Happy holidays @cscalora05, here is the live link for this entry: https://www.codecademy.com/resources/docs/cybersecurity/nmap/ping-sweep

<img width="810" alt="Screen Shot 2022-12-30 at 9 21 29 AM" src="https://user-images.githubusercontent.com/72277593/210080262-69445445-cce3-4c52-94f8-32f1e951604e.png">
You're currently an anonymous contributor, however if you'd like to make yourself public, make sure to add your GitHub username to your Codecademy profile, set the visibility, and log back in using the GitHub option.

Thank you!
cc: @SSwiniarski