Small change to bracket notation
Codecademy/docs pull request #1384
Opened 2022-12-26 13:02 UTC by dariru3

### Description
I've included a minor edit to the bracket notation example under content/javascript/concepts/objects/objects.md
before:
`objectName["propertyName"]`
`person['lastName'];`

after:
`objectName["property Name"]`
`person['last Name'];`

I think the examples are unclear about the difference between using dot notation and bracket notation.

One reason why I'm suggesting this change is that I recently came across this concept in a project. Also, there's not much in the documentation I can add to ^^;

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-12-26 13:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1384) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1384) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1384) it.</sub>

2022-12-26 15:51 UTC, SSwiniarski approved these changes
@dariru3 I did a first review and everything looks good as is.

2022-12-28 07:06 UTC, dariru3 commented
@SSwiniarski Thanks for letting me contribute! I've signed the CLA =)

2022-12-28 23:08 UTC, Dusch4593 requested changes
@dariru3 Thanks for making this edits! 🚀

I just took a look and left you some comments/suggestions. 😄

2022-12-28 23:08 UTC, Dusch4593 commented on content/javascript/concepts/objects/objects.md
>  Bracket notation must be used if the property name has numbers, spaces, or special characters:
```suggestion
Bracket notation must be used if the property name has spaces, special characters, or begins with a number:
```

It seems that numbers can be involved in the property name for dot notation as long as the prop name _does not_ begin with a number. (i.e., `obj.3blindMice` would not be valid whereas `obj.the3musketeers` would be)

2022-12-28 23:08 UTC, Dusch4593 commented on content/javascript/concepts/objects/objects.md
> +objectName["property Name"]
```suggestion
objectName['property Name']
```

Since the rest of the examples use them, let's switch this to single quotes.

2023-01-03 00:30 UTC, Dusch4593 approved these changes
@dariru3 LGTM! 👍🏻

2023-01-03 00:32 UTC, merged

2023-01-03 00:41 UTC, Dusch4593 commented
Congrats and thank you for contributing to Codecademy Docs, @dariru3! 🎊 🙌🏻

The changes should now be live: https://www.codecademy.com/resources/docs/javascript/objects

If you can't see your profile image under the list of contributors, you may need to still add your GitHub username to your Codecademy profile and/or log out of Codecademy and back in through your GitHub account:

<img width="859" alt="Screen Shot 2023-01-02 at 7 41 01 PM" src="https://user-images.githubusercontent.com/23144845/210287557-08ff7642-7242-4d99-b071-808dbb60b0c9.png">

Looking forward to your next Docs contribution! 😄

2023-01-03 21:43 UTC, yangc95 commented
Queue the song "We're all in this together" 🎵

2023-01-06 05:06 UTC, dariru3 commented
Great! Thanks, everyone! I'm glad I could contribute. It was a good experience and now I'm more confident to contribute to perhaps other depositories!

2023-01-06 05:11 UTC, dariru3 commented
@Dusch4593 I'm bitNinja58300 (😅) on Codecademy. Would that have anything to do with not being listed yet as a contributor?

2023-01-06 22:08 UTC, Dusch4593 commented
> @Dusch4593 I'm bitNinja58300 (😅) on Codecademy. Would that have anything to do with not being listed yet as a contributor?

Hmmm, I don't think this should matter as long as the correct _GitHub username_ is associated with your Codecademy account (without the "@"):

<img width="1110" alt="Screen Shot 2023-01-06 at 5 06 41 PM" src="https://user-images.githubusercontent.com/23144845/211108172-c805e7ef-4b8b-4f77-ab1c-4fc6956eaca6.png">

After saving this change, log out of Codecademy and back in with GitHub, and you should see your profile. 😄 

![Uploading Screen Shot 2023-01-06 at 5.05.19 PM.png…]()

2023-01-08 09:57 UTC, dariru3 commented
@Dusch4593 Thank you. That seems to work. However, account was created using my google account. When I logged in with Github, it does show that account's name on the Objects page, but that's not the account I'd like listed.

Interestingly enough, this is what was entered automatically into my profile when I logged in via Github. Should I add it this way on my main account?
![Screen Shot 2023-01-08 at 18 55 47](https://user-images.githubusercontent.com/107824734/211189967-728fbf3d-c4b0-4f42-a7a1-6e16a4662177.png)

2023-01-09 20:58 UTC, Dusch4593 commented
Hey @dariru3, that is correct! But under "GitHub Username", you could just add "dariru3" and then log out/re-log in to Codecademy and it should work. I'm wondering if this also has to do with your actual _Codecademy_ username, which is presently set to the following?

<img width="945" alt="Screen Shot 2023-01-09 at 3 57 08 PM" src="https://user-images.githubusercontent.com/23144845/211406948-87f509de-29e0-4e8b-b5a3-4eea9ba07ae8.png">

2023-01-10 11:06 UTC, dariru3 commented
That user name was automatically generated when I logged in with Github. It's a new account that I didn't intend on creating. I deleted the ruby203... account. I hope this get settled as I have update my profile, logged out and back in.

2023-02-16 20:54 UTC, yangc95 commented
@dariru3 See you! <img width="901" alt="Screen Shot 2023-02-16 at 3 53 51 PM" src="https://user-images.githubusercontent.com/72277593/219484469-873fb4ef-c95f-4ccf-9a16-42859bce2338.png">