Add new entry on the Linux Kernel
Codecademy/docs pull request #1400
Opened 2022-12-28 05:00 UTC by YanisaHS

### Description

I added the linux-kernel concept with linux-kernel.md file inside. The file:

1. Introduces the Linux kernel
2. Lists primary functions of the Linux kernel
3. Provides info on the usage of Linux kernel

I also linked this page to the [Linus Torvalds](https://www.codecademy.com/resources/docs/general/linus-torvalds) and [Linux](https://www.codecademy.com/resources/docs/open-source/linux) pages.

Closes #1271 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-12-28 19:34 UTC, SSwiniarski requested changes
@YanisaHS I did an initial review and only had a couple of comments.

2022-12-28 19:34 UTC, SSwiniarski commented on content/open-source/concepts/linux-kernel/linux-kernel.md
> +The Linux kernel is the core program that runs the [Linux](https://www.codecademy.com/resources/docs/open-source/linux) operating system (OS). It’s the most important component of Linux and serves as
```suggestion
The **Linux kernel** is the core program that runs the [Linux](https://www.codecademy.com/resources/docs/open-source/linux) operating system (OS). It’s the most important component of Linux and serves as a bridge between the software and hardware of Linux machines.
```

2022-12-28 19:34 UTC, SSwiniarski commented on content/open-source/concepts/linux-kernel/linux-kernel.md
> +## Usage of the Linux Kernel
I'd take the text in this section and move it to the introductory paragraph on line 18, and delete this header.

2022-12-29 03:34 UTC, YanisaHS commented
@SSwiniarski Thanks for your feedback!! Done! 🥳

2023-01-02 17:23 UTC, yangc95 commented on content/open-source/concepts/linux-kernel/linux-kernel.md
> +Title: 'Linux kernel'
```suggestion
Title: 'Linux Kernel'
```

2023-01-02 18:58 UTC, yangc95 commented on content/open-source/concepts/linux-kernel/linux-kernel.md
> +The Linux kernel is free and [open source](https://www.codecademy.com/resources/docs/open-source). It is derived from [Unix](https://www.codecademy.com/resources/docs/general/unix) and used in the Li
```suggestion
The Linux kernel is free and [open source](https://www.codecademy.com/resources/docs/open-source) operating system kernel that is derived from [Unix](https://www.codecademy.com/resources/docs/general/unix). Other Linux-derived kernels exist in operating systems such as Android and Chrome OS.
```

2023-01-02 19:12 UTC, yangc95 commented on content/open-source/concepts/linux-kernel/linux-kernel.md
> +The Linux kernel connects the Linux user space with the hardware. It interprets requests from applications and sends them to the appropriate hardware resources. This includes internal hardware, such
```suggestion
The Linux kernel connects the Linux user space with the hardware. It interprets requests from applications and sends them to the appropriate hardware resources. These include internal hardware, such as the [CPU](https://www.codecademy.com/resources/docs/general/cpu) or [RAM](https://www.codecademy.com/resources/docs/general/ram), and peripheral hardware, such as storage disks or monitors.
```

2023-01-02 19:16 UTC, yangc95 commented on content/open-source/concepts/linux-kernel/linux-kernel.md
> +When an application needs to perform a task, it sends a request to the Linux OS. Then, the Linux kernel determines where to send the request. For example, if a user began listening to music on their
```suggestion
When an application needs to perform a task, it sends a request to the Linux OS. Then, the Linux kernel determines where to send the request. For example, if a user began listening to music on their computer, the Linux kernel would have to send a request to multiple hardware resources, including speakers or headphones.
```

2023-01-02 19:19 UTC, yangc95 reviewed
@YanisaHS I had a few minor suggestions, but otherwise this is very well-written. Thanks and Happy New Year! Please tag me once you've finished looking over/resolving everything.

2023-01-03 03:58 UTC, YanisaHS commented
Thank you for your feedback @yangc95 !! Done 🥳

2023-01-14 03:54 UTC, yangc95 approved these changes

2023-01-14 03:56 UTC, merged

2023-01-14 04:15 UTC, yangc95 commented
@YanisaHS here is the live link for your entry: https://www.codecademy.com/resources/docs/open-source/linux-kernel

Thanks for you patience and consistent efforts 😄

cc: @SSwiniarski