added to dictionaries.md replacing key values
Codecademy/docs pull request #1407
Opened 2022-12-29 22:47 UTC by shortant

### Description

Added to Dictionary Documentation of python for changing a key's value in an already existing dictionary

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [X ] All writings are my own.
- [ X] My entry follows the Codecademy Docs style guide.
- [ X] My changes generate no new warnings.
- [ X] I have performed a self-review of my own writing and code.
- [ X] I have checked my entry and corrected any misspellings.
- [ X] I have made corresponding changes to the documentation if needed.
- [ X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-12-29 22:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1407) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1407) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1407) it.</sub>

2022-12-30 17:27 UTC, SSwiniarski requested changes
@shortant. I did a first review and left a couple of comments. The rephrasing is to avoid direct address to the reader, which is avoided in Docs entries.

2022-12-30 17:27 UTC, SSwiniarski commented on content/python/concepts/dictionaries/dictionaries.md
> +## Replacing an Entry in a current Dictionary
```suggestion
## Replacing an Entry in a Existing Dictionary
```

2022-12-30 17:27 UTC, SSwiniarski commented on content/python/concepts/dictionaries/dictionaries.md
> +If a key needs to be updated in an existing Dictionary, use the same syntax for adding an entry into your dictionary  ('dictionary[new_key]=new_value'), but instead replace the 'new_key' arguement fo
```suggestion
If a key needs to be updated in an existing dictionary, it uses the same syntax for adding an entry into a dictionary  ('dictionary[new_key]=new_value'), but instead the 'new_key' argument is replaced with an already 'existing_key' in the desired dictionary, 'dictionary[existing_key] = new_value'
```

2022-12-30 17:27 UTC, SSwiniarski commented on content/python/concepts/dictionaries/dictionaries.md
> +now when you call the value the "Mark" Key from the person_age dictionary it should produce the result: 56
```suggestion

Now when the value in the "Mark" key is called from the `person_age` dictionary it will produce the result 56.
```

2023-01-10 16:51 UTC, yangc95 commented on content/python/concepts/dictionaries/dictionaries.md
> +
```suggestion
# Looks like it's Mark's Birthday! Let's update our dictionary to reflect his new age:
```

2023-01-10 17:50 UTC, SSwiniarski approved these changes
@shortant, @yangc95, Looks good to merge from here.

2023-01-19 04:00 UTC, merged

2023-01-19 04:10 UTC, yangc95 commented
Amazing @shortant! The changes should appear live here: https://www.codecademy.com/resources/docs/python/dictionaries

Although it looks as if you're not a public contributor.
![Screen Shot 2023-01-18 at 11 08 08 PM](https://user-images.githubusercontent.com/72277593/213352964-4c374b02-bff0-42d0-8c4e-070d3f4445d0.png)
If you would like to be a public contributor, make sure to add your GitHub username to your Codecademy profile and make yourself public to everyone.

Please tag me if you have any questions or concerns!

cc: @SSwiniarski