New entry go goroutines
Codecademy/docs pull request #1410
Opened 2022-12-30 18:29 UTC by cslylla

### Description

- Added new concept for Go: goroutines

- Closes #944 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### Additional Information
I am using npm; I have node 18.12.
I was unable to run format:verify (prettier is not recognized)
I was unable to run lint:md (markdownlint is not recognized)
I was unable to run test (jest is not recognized)

2022-12-30 18:36 UTC, cslylla commented
Once #1242 is completed, I would like to refer to it when the definition of functions is described.

2022-12-31 14:59 UTC, SSwiniarski requested changes
@cslylla I did a first review and left a couple of comments.

2022-12-31 14:59 UTC, SSwiniarski commented on content/go/concepts/goroutines/goroutines.md
> +## The difference between threads and goroutines
I'd get rid of the header and incorporate the following paragraph into the introduction.

2022-12-31 14:59 UTC, SSwiniarski commented on content/go/concepts/goroutines/goroutines.md
> +
```suggestion
```

2023-01-02 12:31 UTC, SSwiniarski approved these changes
@cslylla Looks good for a second review.

2023-01-03 20:59 UTC, Dusch4593 requested changes
@cslylla Left some comments/suggestions for you. 😄

2023-01-03 20:59 UTC, Dusch4593 commented on content/go/concepts/goroutines/goroutines.md
> +Although goroutines share some similarities with threads, goroutines are not threads. Threads are different processes within a program that are running at the same time. Threads are created by the pr
```suggestion
Although goroutines share some similarities with threads, there are important differences that include the following:

- Threads depend on the hardware of the host computer's operating system, whereas goroutines do not.
- Compared with threads, goroutines are cost-effective and use less resources to function.
- Goroutines do not use thread-local storage and, thus, do not have a unique ID.

Comparatively, goroutines are light-weight versions of threads that operate within the context of the Go runtime.
```

2023-01-03 20:59 UTC, Dusch4593 commented on content/go/concepts/goroutines/goroutines.md
> +
```suggestion

```

2023-01-03 20:59 UTC, Dusch4593 commented on content/go/concepts/goroutines/goroutines.md
> +   //body of the function
```suggestion
   // function body
```

2023-01-03 20:59 UTC, Dusch4593 commented on content/go/concepts/goroutines/goroutines.md
> +> **Note:** for any goroutines to run, the `main()` function should be running. When the `main()` function terminates, the program will be terminated, and no other goroutine will run.
```suggestion
A goroutine is started by invoking a previously defined function or method, `myFunction()`, with the `go` keyword.

> **Note:** For any goroutines to run, the `main()` function must defined and executed. When the `main()` function terminates, the program will be terminated, and no other goroutine will run.
```

2023-01-03 20:59 UTC, Dusch4593 commented on content/go/concepts/goroutines/goroutines.md
> +func myGoroutine() {
```suggestion
package main
import (
  "fmt"
  "time"
)

func myGoroutine() {  
```

2023-01-03 20:59 UTC, Dusch4593 commented on content/go/concepts/goroutines/goroutines.md
> +In the example below, the `myGoroutine()` function is defined to print out the text `This is my first goroutine`. Then in the `main()` function, `myGoroutine()` is called as a goroutine with the `go`
```suggestion
In the following example, a goroutine is defined to print out text. Inside the `main()` function, `myGoroutine()` is called with the `go` keyword and causes a time delay of 2 seconds with `time.Sleep()` before printing the text:
```

2023-01-03 20:59 UTC, Dusch4593 commented on content/go/concepts/goroutines/goroutines.md
> +    fmt.Println("This is the main function")
```suggestion
  go myGoroutine()
  time.Sleep(2 * time.Second)
  fmt.Println("This is the main function")
```

2023-01-03 20:59 UTC, Dusch4593 commented on content/go/concepts/goroutines/goroutines.md
> +This example results in the following output:
```suggestion
This results in the following output:
```

2023-01-03 20:59 UTC, Dusch4593 commented on content/go/concepts/goroutines/goroutines.md
> +The example below defines a function called `print()` to print out a string, which is first called as a goroutine and then as a function:
```suggestion
The example below defines a `print()` function to print out a string, which is first called as a goroutine and then as a regular function:
```

2023-01-04 16:02 UTC, cslylla commented
@Dusch4593, thanks for the comments; they are really good suggestions. 🤓 I also changed a few words/spacing. Let me know if that is okay!

2023-01-04 17:04 UTC, Dusch4593 approved these changes
@cslylla LGTM! 👍🏻

Just removed some extra spacing in d34a7d78e20ae4fdf63b237e74f7b42498f21900 to get all the checks to pass. 😄

2023-01-04 17:04 UTC, merged

2023-01-04 17:07 UTC, Dusch4593 commented
Thank you for another wonderful contribution to Codecademy Docs, @cslylla! 🎉 🎊 🥳

The entry should now be live: https://www.codecademy.com/resources/docs/go/goroutines

<img width="814" alt="Screen Shot 2023-01-04 at 12 06 36 PM" src="https://user-images.githubusercontent.com/23144845/210610420-2448c16a-e572-4796-960d-5105f94a45f7.png">

Looking forward to your next Docs contribution! 😄

2023-01-07 17:28 UTC, cslylla commented
Hey @lucwhite, I have just sent you an email! 🤩

2023-01-23 14:18 UTC, Pavan-Nambi commented
sorry for tht i messed up few things while reverting ignore that

2023-01-23 15:55 UTC, yangc95 commented
@Pavan-Nambi That's alright! Please let me know if you need any assistance 🙂