[Term Entry] SwiftUI ViewModifier: `.bold()` #1333
Codecademy/docs pull request #1411
Opened 2022-12-31 07:23 UTC by gracekishino

### Description

* Added new folder `terms` inside `content/swiftui/concepts/viewmodifier/`.
* Added new folder `bold` inside `content/swiftui/concepts/viewmodifier/terms/`.
* Added new term entry file `content/swiftui/concepts/viewmodifier/terms/bold/bold.md` for SwiftUI ViewModifier: `.bold()`. 
* Added new image `media/swiftui-bold.png` for the SwiftUI ViewModifier: `.bold()` term entry.

Closes #1333

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-12-31 10:25 UTC, dakshdeepHERE commented
hey @gracekishino  can you tell me how you passed the lint check?

2022-12-31 11:08 UTC, gracekishino commented
> 

@dakshdeepHERE it just passed OK first time… might have some ideas so I’ll reply to you in #1409 😊

2022-12-31 15:04 UTC, SSwiniarski requested changes
@gracekishino I did a first review and left a couple of comments.

2022-12-31 15:04 UTC, SSwiniarski commented on content/swiftui/concepts/viewmodifier/terms/bold/bold.md
> +Title: '`.bold()`'
```suggestion
Title: '.bold()'
```

2022-12-31 15:04 UTC, SSwiniarski commented on content/swiftui/concepts/viewmodifier/terms/bold/bold.md
> +Description: 'Is a `ViewModifier` that applies a bold style to text characters in a `View`.'
```suggestion
Description: 'A ViewModifier that applies a bold style to text characters in a View.'
```

2022-12-31 15:53 UTC, gracekishino commented
@SSwiniarski thank you for reviewing so quickly! I committed your suggestions.

2023-01-01 13:13 UTC, SSwiniarski approved these changes
@gracekishino This looks good for a second review

2023-01-03 02:00 UTC, Dusch4593 commented
Hi @gracekishino and happy New Year! I'll perform the next review 😄

2023-01-05 12:20 UTC, Dusch4593 requested changes
@gracekishino Just had a few comments/suggestions 😄

2023-01-05 12:27 UTC, gracekishino commented
> @gracekishino Just had a few comments/suggestions 😄

@Dusch4593 thanks so much for reviewing and for the comments/suggestions. I committed the suggestions, hope it looks OK now :)

2023-01-05 12:31 UTC, Dusch4593 approved these changes
@gracekishino LGTM for merge! 👍🏻

2023-01-05 12:32 UTC, merged

2023-01-05 12:36 UTC, Dusch4593 commented
Thank you for another wonderful Docs contribution, @gracekishino! 🚀 🎊 🙌🏻

The entry should now be live: https://www.codecademy.com/resources/docs/swiftui/viewmodifier/bold

<img width="823" alt="Screen Shot 2023-01-05 at 7 35 42 AM" src="https://user-images.githubusercontent.com/23144845/210781575-423787a1-aca7-4c1c-806e-6b01594bbe07.png">

Looking forward to your next Docs contribution! 😄

2023-01-06 19:05 UTC, lucwhite commented
Hello @gracekishino,

I hope this message finds you well! My name is Lucas, and I work on the Curriculum team at Codecademy. Our team is considering ways to encourage more individuals to contribute to Codecademy Docs and improve the contribution experience. I was wondering if you would be willing to participate in an interview to provide information on your background and experience with Docs contribution?

The interview would take about an hour and be conducted over Zoom. Should you agree to participate, we will find a time window using Calendly that works for you within the next three weeks. Let us know if you are interested in participating in an interview or have any questions by responding with your email address or emailing me at the address below!

Best,
Lucas White
lucas@codecademy.com