Added variable-scope markdown file
Codecademy/docs pull request #1416
Opened 2023-01-01 17:07 UTC by walstromowen

### Description

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-01-01 17:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1416) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1416) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1416) it.</sub>

2023-01-01 17:17 UTC, walstromowen commented
Hello! Just a question I tried pushing two different commits from the same branch to the remote repo. The second push gets rejected with the following error.

error: failed to push some refs to 'https://github.com/walstromowen/CodecadeDocs.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

I assume this is because I created a pull request for the first commit and it has not been approved. I tried fetching and merging from the remote repo but errors persist. If you have any insight into this problem to share I would greatly appreciate it!

2023-01-02 15:18 UTC, SSwiniarski commented
A new PR should be a separate branch off your main branch. I'd sync the main branch, create a new branch off of it, and copy the changes to that branch.

2023-01-02 15:37 UTC, SSwiniarski requested changes
@walstromowen I did a first review and left a few comments. Most are just formatting issues, but importantly, you need to include a metadata section in your entry.

2023-01-02 15:37 UTC, SSwiniarski commented on content/javascript/concepts/variable-scope/variable-scope.md
> +# Javascript Scope
This is missing a metadata section, which is a requirement. Refer to the [entry template](https://github.com/Codecademy/docs/blob/main/documentation/entry-template.md) and the [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) to see what's required. You can also look at the source of other JavaScript entries to see what we want.

Also, with the metadata in place, we can remove this header. The title will be in the metadata and that's what will populate the entry.

2023-01-02 15:37 UTC, SSwiniarski commented on content/javascript/concepts/variable-scope/variable-scope.md
> +## Global Scope
There needs to be a line break before and after headers.

2023-01-02 15:37 UTC, SSwiniarski commented on content/javascript/concepts/variable-scope/variable-scope.md
> +**Scope** refers to the areas where variables are visible and accessible. Before ES6 was introduced in 2015, Javascript used only **Global Scope** and **Function Scope**.
```suggestion
**Variable scope** refers to the areas where variables are visible and accessible. Before ES6 was introduced in 2015, JavaScript used only "global scope" and "function scope".
```

Generally, we only bold the first occurrence of the subject term.

2023-01-02 15:37 UTC, SSwiniarski commented on content/javascript/concepts/variable-scope/variable-scope.md
> +A variable accessible anywhere in a program is said to have **Global Scope** and is called a **Global Variable**. A global variable must be declared outside all functions in a program.
```suggestion
A variable accessible anywhere in a program is said to have global scope and is called a global variable. A global variable must be declared outside all functions in a program.
```

2023-01-02 15:37 UTC, SSwiniarski commented on content/javascript/concepts/variable-scope/variable-scope.md
> +```
There need to be line breaks before and after code blocks.

2023-01-02 15:37 UTC, SSwiniarski commented on content/javascript/concepts/variable-scope/variable-scope.md
> +## Function Scope
Add a line break after header.

2023-01-02 15:37 UTC, SSwiniarski commented on content/javascript/concepts/variable-scope/variable-scope.md
> +A variable declared anywhere within a function is said to have **Function Scope** and is called a **Local Variable**. Once a local variable is declared, a local variable is said to be **Local** or, a
```suggestion
A variable declared anywhere within a function is said to have function scope and is called a local variable. Once a local variable is declared, a local variable is said to be local, or accessible, anywhere within the function it was declared in.
```

2023-01-02 15:37 UTC, SSwiniarski commented on content/javascript/concepts/variable-scope/variable-scope.md
> +## Block Scope
Add line break after header.

2023-01-02 15:37 UTC, SSwiniarski commented on content/javascript/concepts/variable-scope/variable-scope.md
> +A variable declared with ```let``` or ```const``` within a block { }, is said to have **Block Scope** and is also called a **Local Variable**. However this local variable is only considered local to
```suggestion
A variable declared with `let` or `const` within a block { }, is said to have block scope and is also called a local variable. However this local variable is only considered local to the block it was declared in.
```

2023-01-02 18:01 UTC, walstromowen commented
> @walstromowen: A new PR should be a separate branch off your main branch. I'd sync the main branch, create a new branch off of it, and copy the changes to that branch.

Do I need to make a new pull request every time I make a commit? I apologize, this is my first time contributing to an open source project with git. From my understanding, I can... 

1. Use git pull "remote-repo-name" "local-branch-name" to merge changes made by other contributors to my local repo
2. Make changes discussed above on local branch
3. Commit changes on local branch
4. Push committed changes from the local branch to remote repo

The first time I did this, I made a pull request right after step 4 to give editors access to my work. However, I just made a new commit today to the same branch and I am not sure you or other editors can see it?

2023-01-03 12:38 UTC, SSwiniarski commented
@walstromowen You shouldn't need to. Once you make a PR on a branch, you should see subsequent commits to that branch.

2023-01-03 17:49 UTC, walstromowen commented
Hi! I apologize for all of the redundant commits. I need to remove some commits from this pull request's history as there really is only one important commit. I believe this is achieved using the git rebase command? I tried closing this pull request and then pushed a new commit from the same using the same branch as the deleted request but I think it re-opened this pull request? Unfortunately I am confused and would appreciate any help!

2023-01-04 12:43 UTC, SSwiniarski commented
@walstromowen I wouldn't worry about the number of commits as long as the PR is just changing what you want to change.

2023-01-04 12:44 UTC, SSwiniarski approved these changes
@walstromowen It looks like this is ready for the next review.

2023-01-05 18:00 UTC, walstromowen commented
Thank you! Is there anything I need to do on my side or do I just need to wait for reviews to finish?

2023-01-06 12:37 UTC, SSwiniarski commented
@walstromowen nothing you need to do until another maintainer comes and reviews this PR.

2023-01-12 23:54 UTC, KTom101 requested changes
@walstromowen I've added a second review that includes a title change. Please also change the file name so that the file path is `content/javascript/concepts/variable-scope/variable-scope.md` Let me know if you have any questions.

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +    a = 1; //global variable
For code snippets in docs entries, use two spaces instead of the standard 4.
```suggestion
  a = 1; //global variable
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +	var a = 1;
```suggestion
  var a = 1;
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +    if(a === 1){
```suggestion
  if(a === 1){
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +    	var b = 2;
```suggestion
    var b = 2;
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +        alert(a); //code here can use variable a
Capitalize the first letter of the comments in doc entry snippets
```suggestion
    alert(a); // Code here can use variable a
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +        alert(b); //code here can use variable b
```suggestion
    alert(b); // Code here can use variable b
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +    alert(a); //code here can also use variable a
```suggestion
  alert(a); // Code here can also use variable a
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +    alert(b); //code here can also use variable b
```suggestion
  alert(b); // Code here can also use variable b
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +alert(a); //code here CANNOT use variable a
```suggestion
alert(a); // Code here CANNOT use variable a
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +	let a = 1;
```suggestion
  let a = 1;
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +    if(a === 1){
```suggestion
  if(a === 1){
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +    	let b = 2;
```suggestion
    let b = 2;
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +        alert(a); //code here can use variable a
```suggestion
    alert(a); // Code here can use variable a
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +        alert(b); //code here can use variable b
```suggestion
    alert(b); // Code here can use variable b
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +    alert(a); //code here can also use variable a
```suggestion
  alert(a); // Code here can also use variable a
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +    alert(b); //code here CANNOT use variable b
```suggestion
  alert(b); // Code here CANNOT use variable b
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +alert(a); //code here CANNOT use variable a
```suggestion
alert(a); // Code here CANNOT use variable a
```

2023-01-12 23:54 UTC, KTom101 commented on content/javascript/concepts/variable-scope-js/variable-scope-js.md
> +alert(b); //code here also CANNOT use variable b
```suggestion
alert(b); // Code here also CANNOT use variable b
```

2023-01-18 04:17 UTC, KTom101 reviewed
@walstromowen I added more changes. Mainly regarding the spacing in the last two examples.

2023-01-18 04:17 UTC, KTom101 commented on content/javascript/concepts/variable-scope/variable-scope.md
> +    }
```suggestion
  }
```

2023-01-18 04:17 UTC, KTom101 commented on content/javascript/concepts/variable-scope/variable-scope.md
> +	let a = 1;
```suggestion
  let a = 1;
```

2023-01-18 04:17 UTC, KTom101 commented on content/javascript/concepts/variable-scope/variable-scope.md
> +    if(a === 1){
```suggestion
  if(a === 1){
```

2023-01-18 04:17 UTC, KTom101 commented on content/javascript/concepts/variable-scope/variable-scope.md
> +    	let b = 2;
```suggestion
    let b = 2;
```

2023-01-18 04:17 UTC, KTom101 commented on content/javascript/concepts/variable-scope/variable-scope.md
> +      alert(a); // Code here can use variable a
```suggestion
    alert(a); // Code here can use variable a
```

2023-01-18 04:17 UTC, KTom101 commented on content/javascript/concepts/variable-scope/variable-scope.md
> +      alert(b); // Code here can use variable b
```suggestion
    alert(b); // Code here can use variable b
```

2023-01-18 04:17 UTC, KTom101 commented on content/javascript/concepts/variable-scope/variable-scope.md
> +    }
```suggestion
  }
```

2023-01-20 00:26 UTC, walstromowen commented
@KTom101 thank you for your review. I think I fixed it this time.

2023-01-20 16:37 UTC, SSwiniarski approved these changes
@KTom101, @walstromowen Looks good to me.

2023-01-21 16:05 UTC, walstromowen commented
@SSwiniarski and KTom101 Thank you! let me know if there is any other changes I should make.

2023-01-22 02:13 UTC, KTom101 reviewed
@walstrmowen I've added a few more changes to this.

2023-02-02 22:49 UTC, KTom101 commented
@walstromowen How are the changes coming along? Do you need any help with this?

2023-02-03 14:04 UTC, walstromowen commented
@ KTom101 I have made the changes as requested. Thank you

2023-02-03 22:40 UTC, KTom101 approved these changes
@walstromowen LGTM 👍

2023-02-03 22:44 UTC, KTom101 commented
@walstromowen Do you need any assistance fixing the failing checks?

2023-02-03 22:59 UTC, walstromowen commented
@ KTom101 I would appreciate that! thanks!

2023-02-03 23:26 UTC, KTom101 commented
@walstromowen I've fixed the checks. So you know I ran `npm run format:verify` and `npm run format:all` to do this.

2023-02-03 23:28 UTC, merged

2023-02-03 23:38 UTC, walstromowen commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
code
	{mso-style-priority:99;
	font-family:"Courier New";}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->Thank You!Do you know how I can get my profile to appear as a contributor on the docs page?   Owen Walstrom From: KTom101Sent: Friday, February 3, 2023 5:26 PMTo: Codecademy/docsCc: walstromowen; MentionSubject: Re: [Codecademy/docs] Added variable-scope markdown file (PR ***@***.*** I've fixed the checks. So you know I ran npm run format:verify and npm run format:all to do this.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> 

2023-02-03 23:45 UTC, KTom101 commented
@walstromowen You can add your GitHub username to your Codecademy profile by doing the following:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

<img width="871" alt="YourGitHubName" src="https://user-images.githubusercontent.com/40783324/216730735-258fb834-1171-4339-b894-f64a82ea5ede.png">

2.)	Then log out and log back into Codecademy using your GitHub login:

<img width="1273" alt="ReLogIn" src="https://user-images.githubusercontent.com/40783324/216730799-941fa3fe-1e21-4a56-8dbe-e1c637b71219.png">

Let me know if you need more detailed instructions! 😁

2023-02-03 23:48 UTC, KTom101 commented
@walstromowen Also, feel free to take a look at the [issues tab](https://github.com/Codecademy/docs/issues) to see if there are any recently added issues you want to work on or let us know if there is something not in Docs that you wish to add.

2023-02-04 01:06 UTC, walstromowen commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->Thank you!  Appreciate all of your help! Sincerely, Owen Walstrom From: KTom101Sent: Friday, February 3, 2023 5:48 PMTo: Codecademy/docsCc: walstromowen; MentionSubject: Re: [Codecademy/docs] Added variable-scope markdown file (PR ***@***.*** Also, feel free to take a look at the issues tab to see if there are any recently added issues you want to work on or let us know if there is something not in Docs that you wish to add.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> 