ds course link
Codecademy/docs pull request #1433
Opened 2023-01-04 05:45 UTC by caupolicandiaz

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ x] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-01-04 05:47 UTC, caupolicandiaz commented
Created a new pr for a course link, the first pr was closed because the link was added to the wrong page

2023-01-05 02:46 UTC, Dusch4593 requested changes
Thanks for adding this, @caupolicandiaz! I only had one comment/suggestion. After that, this should be good to merge. 😄

2023-01-05 02:46 UTC, Dusch4593 commented on content/pandas/pandas.md
>    - 'paths/data-science'
```suggestion
  - 'getting-started-with-python-for-data-science'
  - 'paths/data-science'
```

I agree that this new link is more relevant to pandas as a topic. Let's keep this to two slugs, though. (one free slug and one paid course slug)

2023-01-05 18:04 UTC, caupolicandiaz commented
@Dusch4593 should be all set now. Thanks

2023-01-05 18:07 UTC, Dusch4593 approved these changes
Thanks, @caupolicandiaz! Merging..

2023-01-05 18:09 UTC, merged