Css position edit
Codecademy/docs pull request #1456
Opened 2023-01-05 14:52 UTC by lindsaylearns

### Description

Closes issue #1443 . Edited opening statement to explicitly state the property and bold the term. Consolidated the four examples into two examples, showing multiple ways to position a box. Added an image to show the output.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-01-05 18:17 UTC, Dusch4593 commented
Thanks for submitting this, @lindsaylearns! 😄

I'll take a look at this for review 1️⃣

2023-01-05 18:38 UTC, Dusch4593 requested changes
@lindsaylearns Left you some comments/suggestions 😄

2023-01-05 18:38 UTC, Dusch4593 commented on content/css/concepts/position/terms/position/position.md
> +The __position__ property defines the location of an element.
```suggestion
The **position** property defines how elements are placed within the document.
```

I think "placed" makes more sense

2023-01-05 18:38 UTC, Dusch4593 commented on content/css/concepts/position/terms/position/position.md
Below, on line # 20, let's change from \```css to \```pseudo.

2023-01-05 18:38 UTC, Dusch4593 commented on content/css/concepts/position/terms/position/position.md
> +The __position__ property defines the location of an element.
Can we also edit the `Description` on line # 3 to say the following?

> Defines how elements are placed within the document.

2023-01-05 18:38 UTC, Dusch4593 commented on content/css/concepts/position/terms/position/position.md
> +![CSS Position Example](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-position-example.png "CSS position examples")
```suggestion
Here's what the above examples look like:

![CSS Position Example](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-position-example.png)

The first box is sticky to the top of the document. The second is set to a fixed position 40px from the top of the page. The third box position is 80px from the element's top edge.
```

2023-01-05 18:38 UTC, Dusch4593 commented on content/css/concepts/position/terms/position/position.md
> +Set the position of multiple `.box` elements with different `position` values. The first box is sticky to the top of the document. The second is set to a fixed position 40px from the top of the page.
```suggestion
The following example features three `.box` elements with different `position` values:
```

I would place the latter sentences after the image you provided.

2023-01-06 14:04 UTC, lindsaylearns commented
@Dusch4593 I have made all requested changes. Thank you for your review!

2023-01-06 17:58 UTC, lindsaylearns commented
@Dusch4593 Should I not rebase with the main branch when GitHub prompts? I'm happy to pull back and resubmit just my changes to this one file if that's preferred.

2023-01-06 23:02 UTC, Dusch4593 commented
> @Dusch4593 Should I not rebase with the main branch when GitHub prompts? I'm happy to pull back and resubmit just my changes to this one file if that's preferred.

I would advise against rebasing since that would overwrite parts of the commit history. Is this question in regards to keeping your Docs fork synced with the base `Codecademy/docs` repo?

2023-01-06 23:20 UTC, lindsaylearns commented
> > @Dusch4593 Should I not rebase with the main branch when GitHub prompts? I'm happy to pull back and resubmit just my changes to this one file if that's preferred.
> 
> I would advise against rebasing since that would overwrite parts of the commit history. Is this question in regards to keeping your Docs fork synced with the base `Codecademy/docs` repo (for the `main` branch)?

Yes - when the message says the branch is out-of-date with the base branch, I can either update my branch or update with rebase. I definitely worded question wrong. I am asking if I should update my branch or just leave it alone.

2023-01-06 23:25 UTC, Dusch4593 commented
@lindsaylearns Ok gotcha. You are certainly welcome to click "Update branch" if you'd like (sometimes myself or another maintainer may do it, as well). Again, I would avoid rebasing by keeping this button set to "Update with merge commit":

<img width="1100" alt="Screen Shot 2023-01-06 at 6 23 35 PM" src="https://user-images.githubusercontent.com/23144845/211116075-83a960fc-166f-4c0e-8be8-ece79bee7971.png">

Ultimately, this branch will need to be in sync with the base `main` branch in order to be merged.

2023-01-09 18:25 UTC, Dusch4593 approved these changes
@lindsaylearns Thank you for implementing those changes! 😄

This looks good for the next review 👍🏻

2023-01-10 17:11 UTC, SSwiniarski approved these changes
@lindsaylearns, @Dusch4593 Looks good to me, I don't have anything to add.

2023-01-10 17:24 UTC, SSwiniarski commented
@lindsaylearns, I did a npm format on the file to get the checks to pass.

@Dusch4593, anything else we need before we merge?

2023-01-10 17:41 UTC, merged

2023-01-10 17:51 UTC, Dusch4593 commented
Thank you for contributing to Codecademy Docs, @lindsaylearns! 🚀 🎊 🎉

The changes should now be live: https://www.codecademy.com/resources/docs/css/position/position

Currently, your profile seems to be anonymously listed on the entry page. To make it visible, you'll need to add your GitHub username to your Codecademy profile, log out of Codecademy, and log back in through your GitHub account:

<img width="929" alt="Screen Shot 2023-01-10 at 12 49 50 PM" src="https://user-images.githubusercontent.com/23144845/211625525-5ef601fb-5098-4a4c-b98f-c1d493de9bce.png">

Looking forward to your next Docs contribution! 😄