length.md added in the java folder
Codecademy/docs pull request #1460
Opened 2023-01-06 07:04 UTC by dakshdeepHERE

### Description

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-01-06 17:28 UTC, SSwiniarski requested changes
@dakshdeepHERE, I did a first review and left a couple of comments.

2023-01-06 17:28 UTC, SSwiniarski commented on content/java/concepts/array-list/terms/length/length.md
> +Here, `str` is a string variable or a string literal, and length is an integer variable that will hold the length of the string.
```suggestion
Here, `str` is a string variable or a string literal, and `length` is an integer variable that will hold the length of the string.
```

2023-01-06 17:28 UTC, SSwiniarski commented on content/java/concepts/array-list/terms/length/length.md
> +## Example
We'd like a sentence of description preceding the example describing what it's doing.

2023-01-06 17:44 UTC, SSwiniarski requested changes
@dakshdeepHERE, I looked a little closer and discovered a few things that change what needs to happen to this entry:

- This is for an `ArrayList` not a `String` so the wording and examples need to change.
- The actual issue was misstated, as an `ArrayList` doesn't have a `.legnth()` property, it has a `.size()` property, so the file and title need to be renamed.

If you can revise this along these lines, I can come back and do a line by line review.

2023-01-06 19:45 UTC, dakshdeepHERE commented
@SSwiniarski yes I also didnt notice this when making the doc as you can see I wrote string there too size() is used for arraylist and length() is used for strings Ok I can change this for arraylist that is size().

2023-01-07 17:28 UTC, SSwiniarski commented
@dakshdeepHERE I see you have a separate PR for ArrayList .size, were you going to change this to Array .legnth or did you just want to close it?

2023-01-07 17:43 UTC, dakshdeepHERE commented
@SSwiniarski just close it because I made a diff pr with .size() already :)

2023-01-07 18:14 UTC, closed without merging