Term entry isinf
Codecademy/docs pull request #1505
Opened 2023-01-17 02:02 UTC by ddiegow

### Description

Create isinf() entry. Closes #967 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-01-17 17:27 UTC, SSwiniarski commented
@ddiegow Just FYI, you should make new branches off your main branch, not off of prior PR branches. This isn't a big deal this time, because your remquo PR was already merged, but it could cause problems if you branch off a PR branch that's still being reviewed. You don't have to change anything in this PR because of this, but keep it in mind for future PRs.

2023-01-17 17:30 UTC, SSwiniarski requested changes
@ddiegow I did a first review and left a couple of comments.

2023-01-17 17:30 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/isinf/isinf.md
> +Description: 'Returns a value telling whether the argument is an infinite value.'
```suggestion
Description: 'Returns a value indicating whether the argument is an infinite value.'
```

2023-01-17 17:30 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/isinf/isinf.md
> +The **`isinf()`** function returns a value telling whether the argument has an infinite value.
```suggestion
The **`isinf()`** function returns a value indicating whether the argument has an infinite value.
```

2023-01-18 14:29 UTC, ddiegow commented
Thanks for letting me know @SSwiniarski , didn't realize I was still on that branch when I branched of for this task. I'll be more careful next time, but happy I learnt something new :)

2023-01-18 16:45 UTC, SSwiniarski approved these changes
@ddiegow, Looks good for a second review.

2023-01-18 16:47 UTC, Dusch4593 commented
@ddiegow Taking a look now for review 2️⃣  😄

2023-01-18 21:01 UTC, Dusch4593 requested changes
@ddiegow Left you some comments/suggestions 😄

2023-01-18 21:01 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/isinf/isinf.md
> +  }
```suggestion
  if (result == 0) {
    std::cout << "Result: Not infinite" << "\n";
  }
  else {
    std::cout << "Result: Is infinite" << "\n";
  }
  if (result2 == 0) {
    std::cout << "Result2: Not infinite" << "\n";
  }
  else {
    std::cout << "Result2: Is infinite" << "\n";
  }
```

2023-01-18 21:01 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/isinf/isinf.md
> +  result2 = std::isinf(1.0/0);
```suggestion
  result = std::isinf(1.0/2.0);
  result2 = std::isinf(1.0/0.0);
```

It seems that `result2` causes the program to crash unless the denominator is a floating-point value also.

2023-01-27 17:30 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/isinf/isinf.md
> +
@ddiegow Let's implement this.

2023-02-03 14:44 UTC, yangc95 approved these changes
Looks good to merge! I made a change here: https://github.com/Codecademy/docs/pull/1505/commits/e16f34b847cf7625257ff512a7df6d67c0abde75

2023-02-03 14:45 UTC, merged

2023-02-03 15:00 UTC, yangc95 commented
@ddiegow TY for your patience with this one! Here's the live link: https://www.codecademy.com/resources/docs/cpp/math-functions/isinf

Let us know if you'd like to become a public contributor so you don't appear an "anonymous contributor."
<img width="822" alt="Screen Shot 2023-02-03 at 6 54 00 AM" src="https://user-images.githubusercontent.com/72277593/216634165-6141b10e-145b-43f7-9235-4f0d543c2b93.png">

cc: @SSwiniarski @KTom101