Swiftui viewmodifier fontweight
Codecademy/docs pull request #1513
Opened 2023-01-18 00:38 UTC by pipcia

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-01-18 17:51 UTC, SSwiniarski requested changes
@pipcia I did a first review and left a few comments.

2023-01-18 17:51 UTC, SSwiniarski commented on content/swiftui/concepts/viewmodifier/terms/fontWeight/fontWeight.md
> +The **`.fontWeight()`** modifier sets the font weight. We can apply the following weights:
We should move the sentence "We can apply the following font weights:" and the following bulleted list to the Syntax section after the ```pseudo code block.

2023-01-18 17:51 UTC, SSwiniarski commented on content/swiftui/concepts/viewmodifier/terms/fontWeight/fontWeight.md
> +- ultraLight
Let's format the bulleted list like this:

- `.ultralight`

for each item

2023-01-18 17:51 UTC, SSwiniarski commented on content/swiftui/concepts/viewmodifier/terms/fontWeight/fontWeight.md
> +  .fontWeight(.ultraLight)
```suggestion
  .fontWeight(.weight)
```

I'd like the syntax example to be more general. Then in the following description you can say "`.weight` can be one of the following values" indicating the bulleted list that we're moving after the code block.

2023-01-18 17:51 UTC, SSwiniarski commented on content/swiftui/concepts/viewmodifier/terms/fontWeight/fontWeight.md
> +In the following example we use `regular` and `bold` expressions to set font weight.
```suggestion
In the following example we use `.regular` and `.bold` expressions to set font weight.
```

2023-01-18 17:51 UTC, SSwiniarski commented on content/swiftui/concepts/viewmodifier/terms/fontWeight/fontWeight.md
> +      Text("new font Weight")
Rather than both saying "new Font Weight" can we have them say "Regular Font Weight" and "Bold Font Weight"?

2023-01-19 12:07 UTC, pipcia commented
> @pipcia I did a first review and left a few comments.

thanks for review -  the changes u asked for are done now

2023-01-19 17:04 UTC, SSwiniarski approved these changes
@pipcia Looks good for a second review.

2023-02-07 23:54 UTC, KTom101 requested changes
@pipcia I've added a few minor changes.

2023-02-18 22:49 UTC, pipcia commented
changes done as requested

2023-02-18 23:32 UTC, KTom101 approved these changes
@pipcia Thanks for the changes! I made a couple of small changes in commit [d17031c](https://github.com/Codecademy/docs/pull/1513/commits/d17031c856faeed130bde72ee5d84052137fb72c) which included linking out [Text View](https://www.codecademy.com/resources/docs/swiftui/views/text) and adding the suggestion from the first review to include backticks around all the `.weight` elements.

Otherwise, this looks good in my opinion. 👍

2023-02-18 23:36 UTC, merged

2023-02-18 23:51 UTC, KTom101 commented
@pipcia The entry is live: https://www.codecademy.com/resources/docs/swiftui/viewmodifier/fontWeight 🎉 Right now you're listed as an anonymous contributor: 

<img width="906" alt="Screen Shot 2023-02-18 at 6 44 50 PM" src="https://user-images.githubusercontent.com/40783324/219904478-d60d39d0-eede-4c43-b067-71e522b34538.png">

If you want to remain anonymous, there is nothing you need to do. To be listed, add your GitHub username to your Codecademy profile using the following steps:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

<img width="871" alt="YourGitHubName" src="https://user-images.githubusercontent.com/40783324/219904565-58d40aaa-824e-4ba0-a78c-f02b6e90d773.png">

2.) Then log out and log back into Codecademy using your GitHub login:

<img width="1273" alt="ReLogIn" src="https://user-images.githubusercontent.com/40783324/219904584-2237e929-f0b9-4c72-9cd1-869a6b212bc9.png">

Also, feel free to take a look to see if there are other [issues](https://github.com/Codecademy/docs/issues) you want to work on or let us know if you want to add something else!