Added put.md in the terms folder of `hashmap`
Codecademy/docs pull request #1521
Opened 2023-01-21 16:56 UTC by dakshdeepHERE

### Description

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-01-22 14:55 UTC, SSwiniarski requested changes
@dakshdeepHERE I did a first review and left a couple of comments.

2023-01-22 14:55 UTC, SSwiniarski commented on content/kotlin/concepts/hashmap/terms/put/put.md
> +To add a key-value pair to a `HashMap` in Kotlin, you can use the `put()` function. For example:
```suggestion
To add a key-value pair to a `HashMap` in Kotlin, the `put()` function can be used. For example:
```

2023-01-22 14:55 UTC, SSwiniarski commented on content/kotlin/concepts/hashmap/terms/put/put.md
> +We can also use the index operator `[]` to add a key-value pair to the `HashMap`. For example:
```suggestion
The index operator `[]` can be used to add a key-value pair to a `HashMap`. For example:
```

2023-01-22 15:34 UTC, dakshdeepHERE commented
done @SSwiniarski

2023-01-23 16:40 UTC, SSwiniarski approved these changes
@dakshdeepHERE I think this is ready for a second review.

2023-01-24 17:22 UTC, yangc95 reviewed
This is great and straight to the point @dakshdeepHERE 👍 I left a few comments. Once they're all resolved, please tag me (or if you have any questions)!

2023-01-24 17:22 UTC, yangc95 commented on content/kotlin/concepts/hashmap/terms/put/put.md
> +To add a key-value pair to a `HashMap` in Kotlin, the `put()` function can be used. For example:
```suggestion
To add a key-value pair to a `HashMap` in Kotlin, the `.put()` method can be used. For example:
```

2023-01-24 17:22 UTC, yangc95 commented on content/kotlin/concepts/hashmap/terms/put/put.md
> +- value: the value of the key-value pair to add or update in the map.
```suggestion
- The `key` of the key-value pair to add or update in the map.
- The `value` of the key-value pair to add or update in the map.
```

We can also add on here what the functionality is for the key and value. For example, the key is a unique identifier that is used to access certain values within the hash map and the value is what's actually being stored or the data that associated with the key.

2023-01-24 18:03 UTC, dakshdeepHERE commented
done @yangc95

2023-01-29 03:46 UTC, yangc95 approved these changes
LGTM! I made some changes here: [daf90d9](https://github.com/Codecademy/docs/pull/1521/commits/daf90d93b91fd151125d3bffb057172720fe7f98)&[4a69569](https://github.com/Codecademy/docs/pull/1521/commits/4a695696a48f0195921a2b7a019feb3c54340efa)

2023-01-29 03:55 UTC, yangc95 commented on content/kotlin/concepts/hashmap/terms/put/put.md
> +Description: 'Used to add a key-value pair to a hash map.'
```suggestion
Description: 'Inserts a key-value pair to a hash map.'
```

2023-01-29 03:57 UTC, merged

2023-01-29 04:05 UTC, yangc95 commented
🍰 @dakshdeepHERE live link: https://www.codecademy.com/resources/docs/kotlin/hashmap/put

All set 🙌 
![Screen Shot 2023-01-28 at 11 04 27 PM](https://user-images.githubusercontent.com/72277593/215304309-2ab9297e-04a4-4ad7-9378-122001b5e385.png)

cc: @SSwiniarski

2023-01-29 08:12 UTC, dakshdeepHERE commented
Thanks @yangc95 🙏🏻