Created Java's ArrayList Get() method term entry
Codecademy/docs pull request #1524
Opened 2023-01-22 23:29 UTC by hectorconte

### Description

On this contribution, I have created the term entry for Java's ArrayList Get() method, following guidelines and giving an example.

Closes #1441 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-01-22 23:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1524) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1524) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1524) it.</sub>

2023-01-23 19:54 UTC, HishamT requested changes
Hey @hectorconte, I have finished the review of your entry and left you some comments.

2023-01-23 19:54 UTC, HishamT commented on content/java/concepts/array-list/terms/get/get.md
> +Description: 'Brings the element present in a specified position in an ArrayList.'
```suggestion
Retrieves the element present in a specified position in an ArrayList
```

2023-01-23 19:54 UTC, HishamT commented on content/java/concepts/array-list/terms/get/get.md
> +The **`.get()`** method brings the element at a specified position within an `ArrayList` instance.
```suggestion
The **`.get()`** method retrieves the element at some index in an `ArrayList`.
```

2023-01-23 19:54 UTC, HishamT commented on content/java/concepts/array-list/terms/get/get.md
> +The **`.get()`** method brings the element at a specified position within an `ArrayList` instance.
Add a mention to what `.get()` returns if the element is not found.

2023-01-23 19:54 UTC, HishamT commented on content/java/concepts/array-list/terms/get/get.md
> +    String StudentOne = studentList.set(0);
```suggestion
    String StudentOne = studentList.get(0);
```

2023-01-23 19:54 UTC, HishamT commented on content/java/concepts/array-list/terms/get/get.md
> +An element at a specified `index` is brought in an `arrayListInstance`.
```suggestion
The element at index `index` in `arrayListInstance` is returned.
```

2023-01-23 19:54 UTC, HishamT commented on content/java/concepts/array-list/terms/get/get.md
> +In the example below, an empty `ArrayList` instance `studentList` is created and can hold `String`-type elements. Next, a few elements are added with the [`.add()`](https://www.codecademy.com/resourc
```suggestion
In the example below, an empty `ArrayList`, `studentList`, is created containing a few elements of type `String`. The `.get()` method retrieves the students at indexes 0 and 1.
```

2023-01-23 19:54 UTC, HishamT commented on content/java/concepts/array-list/terms/get/get.md
> +    String StudentTwo = studentList.set(1);
```suggestion
    String StudentTwo = studentList.get(1);
```

2023-01-23 19:54 UTC, HishamT commented on content/java/concepts/array-list/terms/get/get.md
> +The output should look like this:
```suggestion
The output will look like this:
```

2023-01-23 20:00 UTC, hectorconte commented
Hi @HishamT, I will correct this ASAP, thanks for checking my work!

2023-01-23 20:21 UTC, hectorconte reviewed
All done! Will wait next review. Thanks again!

2023-01-24 21:14 UTC, HishamT approved these changes
Hey @hectorconte, I have made some minor changes. This looks good.

2023-01-24 21:17 UTC, hectorconte commented
@HishamT Thanks for reviewing it!

2023-01-28 21:42 UTC, caupolicandiaz requested changes
@hectorconte overall this looks pretty good, just made some minor edits for clarity

2023-01-28 21:42 UTC, caupolicandiaz commented on content/java/concepts/array-list/terms/get/get.md
> +The element at index `index` is `arrayListInstance` is returned. If the index is out of range, an `IndexOutOfBoundsException` will be thrown.
```suggestion
The element at index `index` in `arrayListInstance` is returned. If the index is out of range, an `IndexOutOfBoundsException` error will be thrown.
```

2023-01-28 21:42 UTC, caupolicandiaz commented on content/java/concepts/array-list/terms/get/get.md
> +In the example below, an empty `ArrayList`, `studentList`, is created containing a few elements of type `String`. The `.get()` method retrieves the students at indexes 0 and 1.
```suggestion
In the example below, an empty `ArrayList`, `studentList`, is created and populated with several elements of type `String`. The `.get()` method retrieves the students at indexes 0 and 1.
```

2023-01-28 21:42 UTC, caupolicandiaz commented on content/java/concepts/array-list/terms/get/get.md
> +import java.util.ArrayList;
```suggestion
// Students.java
import java.util.ArrayList;
```

2023-01-28 21:42 UTC, caupolicandiaz commented on content/java/concepts/array-list/terms/get/get.md
> +    // `.get()` method stores element's value
```suggestion
    // `.get()` method extracts the element's value
```

2023-01-28 22:11 UTC, closed without merging

2023-01-29 00:20 UTC, yangc95 commented
@hectorconte checking in to see if you meant to close out this PR. I notice the repository is still on your GitHub profile. Let me know if you need any assistance or of your intentions. Thank you! 🙂

2023-01-29 00:23 UTC, hectorconte commented
Hi @yangc95 ! Sorry, I closed this PR as a mistake, since I deleted (again, unintentionally) my forked repository which I re-forked afterwards. So I opened a new PR to keep working there. Sorry!

2023-01-29 02:50 UTC, yangc95 commented
@hectorconte gotcha! Thanks for letting me know ☺️ I see your PR here: https://github.com/Codecademy/docs/pull/1557

It would be a good idea to rename the PR similarly to how you did so here. In any case, if you have any further questions, reach out to any of us maintainers ^^

cc: @caupolicandiaz @HishamT

2023-01-29 03:06 UTC, hectorconte commented
@yangc95 Yes! That's the one! Thanks a lot