closes [Concept Entry] Go: Functions #1242
Codecademy/docs pull request #1526
Opened 2023-01-23 16:37 UTC by Pavan-Nambi

### Description

Added new concept functions closes https://github.com/Codecademy/docs/issues/1242#issue-1446487796

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-01-24 18:00 UTC, SSwiniarski requested changes
@Pavan-Nambi I did a first review and left comments on your PR. Because of the length, I may have more comments after you've addressed this round.

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +Description: 'Functions are a block of code that can be reused multiple times'
```suggestion
Description: 'Functions are a block of code that can be reused multiple times.'
```

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +Functions are defined using the func keyword, followed by the function name, parameters, and return type.
```suggestion
Functions are defined using the `func` keyword, followed by the function name, parameters, and return type. 
```

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +## Syntax
Let's move lines 18-20 to this syntax section after the ```pseudo code block.

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +output is:
```suggestion
The output is:
```

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +Note:Functions must be directly declared at package level, not inside other functions.
```suggestion
> **Note:** Functions must be directly declared at package level, not inside other functions.
```

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +```go
Each example should be introduced by a sentence summarizing what the example does.

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +we can define a function inside a function but it is not recommended as we can't call it outside the function.
```suggestion
We can define a function inside a function but it is not recommended as we can't call it outside the function.
```

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +// You can edit this code!
Remove the first two comments

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +
Remove the extra line breaks. Don't have multiple line breaks in a row in the code examples.

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +output:
```suggestion
This example produces the following output:
```

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +A function is called a method if it is defined with a receiver.
This all reads as one paragraph. It would be clearer if the following lines were a bulleted list.

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +In go complier does this automatically.
```suggestion
In go the complier does this automatically.
```

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +// You can edit this code!
Remove the first two comments.

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +
Remove the extra line breaks.

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +```go
Introduce the examples with a summary sentence.

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +output:
```suggestion
This example results in the following output:
```

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +Another usecase for blank identifier is to implement interfaces which can be covered in interfaces section
Also move this to the end of line 279 above.

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +Output:
```suggestion
This example results in the following output:
```

2023-01-24 18:00 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +use below codebyte to practice in broswer while learning
```suggestion
## Codebyte Example

The following example is runnable and can be edited:

```

2023-01-24 18:20 UTC, Pavan-Nambi commented on content/go/concepts/functions/functions.md
> +we can define a function inside a function but it is not recommended as we can't call it outside the function.
ok will either add explaination or merge both statements

2023-01-24 18:22 UTC, Pavan-Nambi commented on content/go/concepts/functions/functions.md
> +think about it we have been using a function that takes vardiac parameters..
gotcha i wasn't able to frame a sentence on it without using a perspective , can u guide me here pls @SSwiniarski

2023-01-24 18:31 UTC, Pavan-Nambi commented on content/go/concepts/functions/functions.md
> +Println is a variadic function refer [here](https://golang.org/pkg/fmt/#Println)
so should i remove 157 and 159 lines? one refer to go docs and one to direct code on how print is defined

2023-01-24 18:43 UTC, Pavan-Nambi commented on content/go/concepts/functions/functions.md
> +Each function can have at most one variadic parameter(keys ...int).
this i will update after getting clear ans to https://github.com/Codecademy/docs/pull/1526#discussion_r1085731909

2023-01-24 19:12 UTC, Pavan-Nambi commented
@SSwiniarski all the changes have completed except https://github.com/Codecademy/docs/pull/1526/files#r1085746551

2023-01-26 16:17 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +Println is a variadic function refer [here](https://golang.org/pkg/fmt/#Println)
@Pavan-Nambi remove the lines with third party links. Include any needed detail in the entry itself.

2023-01-27 10:36 UTC, Pavan-Nambi commented on content/go/concepts/functions/functions.md
> +Println is a variadic function refer [here](https://golang.org/pkg/fmt/#Println)
gotcha i will just include basic syntax of  how it was implemented under the hood

2023-01-27 10:37 UTC, Pavan-Nambi commented on content/go/concepts/functions/functions.md
> +think about it we have been using a function that takes vardiac parameters..
here i will just delete tht sentence ig

2023-02-09 05:12 UTC, Pavan-Nambi commented
hey @SSwiniarski  appolgies for taking so long on this can u do a quick check on this?

thankyou

2023-02-10 16:46 UTC, SSwiniarski requested changes
@Pavan-Nambi I have a few more comments.

2023-02-10 16:46 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +### Vardiac parameters
```suggestion
## Vardiac parameters
```

2023-02-10 16:46 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +
Remove the extra two line breaks.

2023-02-10 16:46 UTC, SSwiniarski commented on content/go/concepts/functions/functions.md
> +### Methods
```suggestion
## Methods
```

2023-02-10 17:09 UTC, Pavan-Nambi commented
> @Pavan-Nambi I have a few more comments.

can you do a quick recheck? thanks

2023-02-11 14:30 UTC, SSwiniarski approved these changes
@Pavan-Nambi , I'm sending this off for the second review.

2023-02-28 03:34 UTC, KTom101 requested changes
@Pavan-Nambi I've added a second review!

2023-02-28 03:34 UTC, KTom101 commented on content/go/concepts/functions/functions.md
> +		fmt.Println("Hey I am a function returned by function sounds cool right?")
```suggestion
		fmt.Println("This is a function returned by another function.")
```

2023-02-28 03:34 UTC, KTom101 commented on content/go/concepts/functions/functions.md
> +	greeting := "hey I am no name"
```suggestion
	greeting := "Hey, there."
```

2023-02-28 03:34 UTC, KTom101 commented on content/go/concepts/functions/functions.md
> +		fmt.Println("Hey I am no name")
```suggestion
		fmt.Println("Hey, I have no name")
```

2023-02-28 03:34 UTC, KTom101 commented on content/go/concepts/functions/functions.md
> +Hey I am no name
```suggestion
Hey, I have no name
```

2023-02-28 03:34 UTC, KTom101 commented on content/go/concepts/functions/functions.md
> +The following example is runnable and can be edited:
```suggestion
The following codebyte example provides another example of a function. It is runnable and can be edited:
```

2023-02-28 03:41 UTC, KTom101 commented on content/go/concepts/functions/functions.md
> +	fmt.Println(Hello("World"))
```suggestion
	fmt.Println(Hello("World!"))
```

2023-03-04 19:16 UTC, KTom101 commented
@Pavan-Nambi I see you've made some progress and there are only about 20 comments left, nice! Please tag me when you're finished or if you need help with anything! 😃

2023-03-05 04:21 UTC, Pavan-Nambi commented
@KTom101  sorry i havent checked comments under file section , should be done by now

2023-03-05 14:30 UTC, KTom101 commented
@Pavan-Nambi Thank you for making the changes. I just added one small change here [25ae981](https://github.com/Codecademy/docs/commit/25ae981116bb2898090e62f7074c66c96e7a2712). 

All we have to do now is fix the failed checks. Would you like me to do that for you?

2023-03-05 14:30 UTC, KTom101 approved these changes
@Pavan-Nambi Thank you for making the changes. I just added one small change here 25ae981.

All we have to do now is fix the failed checks. Would you like me to do that for you?

2023-03-10 23:31 UTC, KTom101 commented
@Pavan-Nambi I made some updates to this including adding the "Anonymous Function" tag to the `tags.md` file and removing numerous hard tabs from the code snippets that were causing the checks to fail. Please make sure in the future to use two spaces when indenting lines of code instead of 4 spaces or tabs.

2023-03-10 23:51 UTC, merged

2023-03-11 00:01 UTC, KTom101 commented
@Pavan-Nambi Live entry is here: https://www.codecademy.com/resources/docs/go/functions. You're all set 🎉

<img width="857" alt="Screenshot 2023-03-10 at 6 56 25 PM" src="https://user-images.githubusercontent.com/40783324/224450764-53d4cc95-e583-42ed-9add-849a5424c88b.png">

cc @yangc95 @SSwiniarski

2023-03-27 19:43 UTC, Pavan-04-08 commented
> @Pavan-04-08 Can we make an additional PR for this entry for some edits? This will be considered an enhancement.
> 
> * Let’s combine lines 17&18. Since the term is stated once, we can replace the second occurrence of “Functions” to “They”.
> * Either add a new line after line 30, or place the explanation onto one line.
> * Remove extra trailing spacing in codeblocks like on line 80, 107, 113, 139, etc, and add new lines where needed such as before a comment that leads to a line of code that differs in what is accomplishes from the previous line of code, e.g., before line 129.
> 
> > I can also assist with this change. Let me know how you would like to proceed.

yeah we surely can is it ok if i do this on friday?

2023-03-27 20:11 UTC, yangc95 commented
@Pavan-04-08 sounds good!