Made corrections according to review
Codecademy/docs pull request #1557
Opened 2023-01-28 22:37 UTC by hectorconte

### Description

Updated with some minor changes, but created a new pull request since the previous one was unintentionally deleted.

Closes #1441 

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-01-28 22:38 UTC, hectorconte commented
Sorry @HishamT, @caupolicandiaz, I accidentally deleted the previous pull request, but made the reviewed changes here. Sorry again.

2023-01-29 01:23 UTC, HishamT approved these changes
LGTM!

2023-01-30 00:57 UTC, caupolicandiaz requested changes
@hectorconte Looks good, just added a substitute for one of the tags that wasn't really relevant to this entry

2023-01-30 00:57 UTC, caupolicandiaz commented on content/java/concepts/array-list/terms/get/get.md
> +  - 'Data Types'
```suggestion
  - 'Methods'
```

2023-01-30 01:09 UTC, hectorconte commented
@caupolicandiaz Great, done!

2023-01-30 02:58 UTC, caupolicandiaz approved these changes
@hectorconte Nice, good to go

2023-02-01 00:15 UTC, merged

2023-02-03 02:55 UTC, yangc95 commented
@hectorconte live link: https://www.codecademy.com/resources/docs/java/array-list/get

It looks like you're currently an anonymous contributor:
<img width="820" alt="Screen Shot 2023-02-02 at 6 46 22 PM" src="https://user-images.githubusercontent.com/72277593/216500431-15096e9a-4398-474c-9e17-a5f692197bf1.png">

If you'd like to become a public contributor, make sure to add your GitHub username to your Codecademy profile and set your visibility to "everyone." 🙂

cc: @HishamT @caupolicandiaz

2023-02-03 03:19 UTC, hectorconte commented
@yangc95 I do have set it up that way, strange! Do you think I should contact codecademy support maybe? Thanks Chris!

2023-02-03 14:55 UTC, yangc95 commented
@hectorconte Try signing out and logging back in with the GitHub option!

2023-02-03 17:54 UTC, hectorconte commented
@yangc95 That did it! Thanks again!