Create toUpperCase.md
Codecademy/docs pull request #1572
Opened 2023-01-31 10:51 UTC by IskakovIZh

Add a new term entry under the Java: Strings concept, .toUpperCase() Method.

### Description

Add .toUpperCase() method markdown file.

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-01-31 10:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1572) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1572) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1572) it.</sub>

2023-01-31 21:43 UTC, caupolicandiaz requested changes
@IskakovIZh Looks good overall, just some small changes to align this with our standards

2023-01-31 21:43 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toUpperCase/toUpperCase.md
> +Description: 'Returns the string in uppercase letter'
```suggestion
Description: 'Returns a given string in all uppercase letters'
```

2023-01-31 21:43 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toUpperCase/toUpperCase.md
> +  - 'Booleans'
```suggestion

```

2023-01-31 21:43 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toUpperCase/toUpperCase.md
> +The **`.toUpperCase()`** method converts all the lowercase letters of a string into uppercase and returns that upper-cased string.
```suggestion
The **`.toUpperCase()`** method converts all the lowercase letters of a string to uppercase and returns that new string.
```

2023-01-31 21:43 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toUpperCase/toUpperCase.md
> +String toUpperCase() returns a new string, so you will have to assign that to another string.
```suggestion
The `.toUpperCase()` method returns a new string, so it must be assigned to a variable in order to reuse that new value.
```

2023-01-31 21:43 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toUpperCase/toUpperCase.md
> +The following example showcases the `.toUpperCase()` method:
```suggestion
The following example applies the `.toUpperCase()` method to the given text:
```

2023-01-31 21:43 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toUpperCase/toUpperCase.md
> +    System.out.println(textUp);
```suggestion
    System.out.println(text);
    System.out.println(textUp);
```

2023-01-31 21:43 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toUpperCase/toUpperCase.md
> +HELLO WORLD
```suggestion
Hello World
HELLO WORLD
```

2023-01-31 21:43 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toUpperCase/toUpperCase.md
> +
```suggestion
// MyClass.java
```

2023-02-01 10:30 UTC, IskakovIZh reviewed
Thank you, i accepted all the offers!

2023-02-01 17:53 UTC, caupolicandiaz approved these changes
@IskakovIZh Cool, this is ready for the next review

2023-02-07 09:27 UTC, IskakovIZh commented
What is required of me now?

2023-02-07 23:36 UTC, HishamT requested changes
Hey @IskakovIZh, I have finished reviewing your entry and left you some comments.

2023-02-07 23:36 UTC, HishamT commented on content/java/concepts/strings/terms/toUpperCase/toUpperCase.md
> +The **`.toUpperCase()`** method converts all the lowercase letters of a string to uppercase and returns that new string.
```suggestion
The **`.toUpperCase()`** method converts all lowercase letters of a string to uppercase and returns a new string.
```

2023-02-07 23:36 UTC, HishamT commented on content/java/concepts/strings/terms/toUpperCase/toUpperCase.md
> +The `.toUpperCase()` method returns a new string, so it must be assigned to a variable in order to reuse that new value.
```suggestion
The `.toUpperCase()` method returns a new string consisting of the upper case form of the letters in the original string. To use the new upper case string, the returned string must be assigned to a variable.
```

2023-02-09 23:58 UTC, HishamT approved these changes
LGTM!

2023-02-13 22:25 UTC, merged