Add term new
Codecademy/docs pull request #1573
Opened 2023-01-31 16:35 UTC by daniellanyi

### Description

Adding markdown file for the __new__() term in Python Dunder Methods

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-01 17:43 UTC, SSwiniarski requested changes
@daniellanyi I did a first review and have a first round of comments.

2023-02-01 17:43 UTC, SSwiniarski commented on content/python/concepts/dunder-methods/terms/new/new.md
> +Description: 'Static method which creates a new instance of a class'
```suggestion
Description: 'Static method which creates a new instance of a class.'
```

2023-02-01 17:43 UTC, SSwiniarski commented on content/python/concepts/dunder-methods/terms/new/new.md
> +The **`__new__()`** method creates a new instance of a class cls and takes in the class (of which the instance was requested) as the first argument.
```suggestion
The **`__new__()`** method creates a new instance of a class `cls` and takes in the class (of which the instance was requested) as the first argument.
```

2023-02-01 17:43 UTC, SSwiniarski commented on content/python/concepts/dunder-methods/terms/new/new.md
> +Object creation is typically done by invoking the superclass’ `__new__()` in two ways. The first argument of `__new__()` is always the class which is passed in as the first parameter automatically. T
```suggestion
Object creation is typically done by invoking the superclass’ `__new__()` in two ways. The first argument of `__new__()` is always the class which is passed in as the first parameter automatically. The name `cls` is not a keyword; it’s used to reference the class (the first parameter) by convention. When `__new__()` returns an instance of `cls` it automatically invokes the [`__init__()`](https://www.codecademy.com/resources/docs/python/dunder-methods/init) method of that instance with the arguments passed to it. The first argument passed to `__init__()` will be the instance itself (this happens automatically) which is by convention referenced by `self`.
```

2023-02-01 17:43 UTC, SSwiniarski commented on content/python/concepts/dunder-methods/terms/new/new.md
> +First `__new__()` is invoked during the construction of the object (instance of class ClassName) with the arguments 1 and 2 which are accepted within \*args. The object is created by calling the `__n
```suggestion

First `__new__()` is invoked during the construction of the object (instance of class `ClassName`) with the arguments `1` and `2` which are accepted within `\*args`. The object is created by calling the `__new__()` method of the object base class which only takes in the class `cls`. It then returns an object which is then stored in `obj` and returned. This invokes the `__init__()` method of the `ClassName` class with the arguments `(obj, \*args, \*\*kwargs)`.
```

2023-02-01 17:43 UTC, SSwiniarski commented on content/python/concepts/dunder-methods/terms/new/new.md
> +- Subclassing of immutable types which cannot be initialized via a simple __init__method.
```suggestion
- Subclassing of immutable types which cannot be initialized via a simple `__init__()` method.
```

2023-02-01 17:43 UTC, SSwiniarski commented on content/python/concepts/dunder-methods/terms/new/new.md
> +## Codebyte Example 1
We generally only have one codebyte example at the end of the entry.  We can make this just a regular example with a ```py block.

2023-02-01 17:43 UTC, SSwiniarski commented on content/python/concepts/dunder-methods/terms/new/new.md
> +[Official Python documentation](https://docs.python.org/3/reference/datamodel.html#object.__new__)
Remove this last link.

2023-02-01 17:43 UTC, SSwiniarski commented on content/python/concepts/dunder-methods/terms/new/new.md
> +
```suggestion
```
remove extra line break.

2023-02-01 17:43 UTC, SSwiniarski commented on content/python/concepts/dunder-methods/terms/new/new.md
> +
```suggestion
```
Remove extra line break

2023-02-01 17:43 UTC, SSwiniarski commented on content/python/concepts/dunder-methods/terms/new/new.md
> +
```suggestion
```
remove extra line break

2023-02-26 16:23 UTC, SSwiniarski commented
@daniellanyi, It's been a while, do you need assistance implementing the suggestions above?

2023-02-27 12:01 UTC, daniellanyi commented
Thank you!. I have applied the first round of changes you've suggested to
clean up the markdown. I'm sorry I didn't reply sooner; there is a time
zone difference (I live in the UK). I hope I've worded the description of
the '__new__()' method accurately and clearly. If you have more suggestions
on how to improve it feel free to let me know.

On Sun, Feb 26, 2023 at 4:23 PM SSwiniarski ***@***.***>
wrote:

> @daniellanyi <https://github.com/daniellanyi>, It's been a while, do you
> need assistance implementing the suggestions above?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Codecademy/docs/pull/1573#issuecomment-1445401551>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4YSOFIXE3TQC7KTQAHJC4LWZN7PXANCNFSM6AAAAAAUMU5D2M>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-27 12:46 UTC, SSwiniarski commented
@daniellanyi, you still have two codebyte blocks. I'd like you to turn the first one into a regular example with a ```py block.

2023-02-27 16:34 UTC, SSwiniarski commented
@daniellanyi don't forget to change the headers on the last two sections to reflect the change of the codebyte block. ie: change from "Codebyte Example 1" and "Codebyte Example 2" to "Example" and "Codebyte Example"

2023-02-27 17:36 UTC, SSwiniarski approved these changes
Looks good for review two.

2023-03-06 19:56 UTC, KTom101 requested changes
@daniellanyi Second review is complete!

2023-03-06 19:56 UTC, KTom101 commented on content/python/concepts/dunder-methods/terms/new/new.md
> +In the example above no parent class was specified therefore the class will directly inherit from the object base class (from which all classes inherit). Therefore calling it explicitly using `object
```suggestion
In the example above, no parent class was specified, therefore, the class will directly inherit from the object base class (from which all classes inherit). Calling it explicitly using `object.__new__(cls)` will have the same effect.
```

2023-03-06 19:56 UTC, KTom101 commented on content/python/concepts/dunder-methods/terms/new/new.md
> +In this example the number of instances of Test is limited to ‘MaxNumberOfInstances’:
```suggestion
In the following example, the number of instances of the class `Test` is limited to ‘MaxNumberOfInstances’:
```

2023-03-08 07:09 UTC, KTom101 approved these changes
@daniellanyi I made some small changes [6104f5f](https://github.com/Codecademy/docs/pull/1573/commits/6104f5fa247fc09df3ed050faddec8379653bc97) & [7ab2cfb](https://github.com/Codecademy/docs/pull/1573/commits/7ab2cfb8f62ea1881ba3d6df9e8207619f5d3ba9), otherwise looks good to me! 👍

2023-03-08 07:45 UTC, merged

2023-03-08 08:18 UTC, KTom101 commented
@daniellanyi Entry is live here: https://www.codecademy.com/resources/docs/python/dunder-methods/new

You're currently listed as an anonymous contributor:

<img width="804" alt="Screenshot 2023-03-08 at 3 10 28 AM" src="https://user-images.githubusercontent.com/40783324/223657512-d6c39d1b-8c46-4981-8474-9f489451e1b0.png">

To be credited, follow these steps below:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

<img width="871" alt="YourGitHubName" src="https://user-images.githubusercontent.com/40783324/223658035-08094819-751a-433f-b6ba-b7ffca052968.png">

2.) Then log out and log back into Codecademy using your GitHub login:

<img width="1273" alt="ReLogIn" src="https://user-images.githubusercontent.com/40783324/223658226-afdb403a-9508-44e1-8975-801959437604.png">

> Note:  Your email used for Codecademy will have to be listed in your GitHub profile for the login feature to properly work. If you use the same email for both GitHub and Codecademy already, then you're set.

Let me know if you need any help if you decide to do so! 😁