Tolowercase
Codecademy/docs pull request #1580
Opened 2023-02-02 10:58 UTC by M3RF3R

### Description

Creation of the folder toLowerCase and the toLowerCase file to explain this Java method
### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-02 17:04 UTC, SSwiniarski requested changes
@M3RF3R I did a first review and left a few comments. The most important is to remove the style.md file from this branch to avoid a conflict.

2023-02-06 14:48 UTC, M3RF3R commented on content/html/concepts/attributes/terms/style/style.md
> +---
done

2023-02-06 14:48 UTC, M3RF3R commented on content/java/concepts/strings/terms/toLoweCase/toLowerCase.md
> +Converting uppercase characters to lowercase characters:
done

2023-02-06 15:17 UTC, M3RF3R commented on content/java/concepts/strings/terms/toLoweCase/toLowerCase.md
> +```java
Hi! Thanks for your revision. I'm not sure I understand this comment. Everywhere I look they have this as syntax for the method: public String toLowerCase(). Should I just copy your suggestion (lowerCaseString = upperCaseString.toLowerCase();) and say that `lowerCaseString` stands for a string with lowercase characters and 'upperCaseString` stands for a string with some uppercase characters that will be converted?

2023-02-06 15:17 UTC, M3RF3R commented
@SSwiniarski Hi! I've left you a comment, since I need some clarification. Thanks!

2023-02-06 17:01 UTC, SSwiniarski commented on content/java/concepts/strings/terms/toLoweCase/toLowerCase.md
> +```java
@M3RF3R yes, if you could do that please.

2023-02-07 16:16 UTC, M3RF3R commented on content/java/concepts/strings/terms/toLoweCase/toLowerCase.md
> +```java
Is this correct?

2023-02-07 16:29 UTC, SSwiniarski approved these changes
@M3RF3R Looks good for a second review.

2023-02-14 22:51 UTC, caupolicandiaz requested changes
@M3RF3R Just a few minor changes

2023-02-14 22:51 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toLoweCase/toLowerCase.md
> +  - 'learn java'
```suggestion
  - 'learn-java'
```

2023-02-14 22:51 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toLoweCase/toLowerCase.md
> +lowerCaseString = upperCaseString.toLowerCase();
```suggestion
upperCaseString.toLowerCase();
```

2023-02-14 22:51 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toLoweCase/toLowerCase.md
> +Where `lowerCaseString` is the string with all lower case characters and `upperCaseString` is the string with some or all upper case characters that will be converted.
```suggestion
Where `upperCaseString` is the string with some or all upper case characters to be converted.
```

2023-02-14 22:51 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toLoweCase/toLowerCase.md
> +```java
```suggestion
```java
// Example.java

```

2023-02-21 16:31 UTC, M3RF3R commented on content/java/concepts/strings/terms/toLoweCase/toLowerCase.md
> +  - 'learn java'
done

2023-02-21 16:33 UTC, M3RF3R commented on content/java/concepts/strings/terms/toLoweCase/toLowerCase.md
> +Where `lowerCaseString` is the string with all lower case characters and `upperCaseString` is the string with some or all upper case characters that will be converted.
done

2023-02-21 16:35 UTC, M3RF3R commented on content/java/concepts/strings/terms/toLoweCase/toLowerCase.md
> +```java
done

2023-02-21 16:37 UTC, M3RF3R commented
@caupolicandiaz I added the changes!

2023-02-21 20:05 UTC, caupolicandiaz approved these changes
@M3RF3R Looks good

2023-02-22 16:41 UTC, merged

2023-02-22 16:52 UTC, SSwiniarski commented
Congrats on the new entry @M3RF3R. The live entry can be found here: https://www.codecademy.com/resources/docs/java/strings/toLowerCase

It looks as if you're anonymous:
![image](https://user-images.githubusercontent.com/86081858/220698807-d11acc88-dd53-4d0b-ac51-f0a2cdab8a17.png)

If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.

To add your GitHub username to your Codecademy profile:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

![image](https://user-images.githubusercontent.com/86081858/220699030-55a1ef72-d1d1-40ab-942a-9e34ba4dbb13.png)

2.) Then log out and log back into Codecademy using your GitHub login:

![image](https://user-images.githubusercontent.com/86081858/220699181-215bb100-e413-4871-8ddd-a308c1444246.png)