clarify unclear content and/or terms, add new content (definitions, c…
Codecademy/docs pull request #1598
Opened 2023-02-03 06:29 UTC by farah-qistina

…odeblocks, etc.)

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-03 06:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1598) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1598) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1598) it.</sub>

2023-02-03 17:40 UTC, SSwiniarski requested changes
@farah-qistina I did a first review and only have one comment.

2023-02-03 17:40 UTC, SSwiniarski commented on content/html/concepts/forms/forms.md
> +Description: 'In HTML, __forms__ are used for gathering and sending user input to an external source for processing.'
```suggestion
Description: 'In HTML, **forms** are used for gathering and sending user input to an external source for processing.'
```

2023-02-04 13:14 UTC, SSwiniarski approved these changes
@farah-qistina Looks good.

2023-02-08 02:11 UTC, yangc95 commented on content/html/concepts/forms/forms.md
> +Description: 'In HTML, **forms** are used for gathering and sending user input to an external source for processing.'
```suggestion
Description: 'In HTML, forms are used for gathering and sending user input to an external source for processing.'
```

2023-02-08 02:14 UTC, yangc95 commented on content/html/concepts/forms/forms.md
> +The following example shows what an HTML form would typically look like with a `<form>` element that features `<input>` elements and its corresponding `<label>` elements:
```suggestion
The following example shows what an HTML form that features `<input>` elements:
```

I actually don't see any labels in the example. Did you mean to add them to the example?

2023-02-08 02:15 UTC, yangc95 reviewed
@farah-qistina I conducted a quick review! Please tag me once you've resolved all the comments/suggestions or for discussion on something 🙂

2023-02-08 02:38 UTC, farah-qistina commented
@yangc95, I wrongly assumed that there were labels in the example, sorry about that! I've edited the file according to your reviews and committed the changes, please have a look :)

2023-02-26 15:02 UTC, yangc95 reviewed
Thanks for working on this edit @farah-qistina!

I mainly have one more rework request for this entry which is to create a new code block underneath syntax to only display a the form element rather than an example. We can then add back the original example header. It's okay if this entry follows term entries as this will most likely be moved into another concept.

Thanks for your patience and let me know if you need direct assistance ☺️

2023-03-09 16:44 UTC, SSwiniarski commented
@farah-qistina, It's been two weeks, do you need assistance doing @yangc95's suggested edit?

2023-03-10 02:44 UTC, farah-qistina commented
I've committed my changes @SSwiniarski @yangc95

2023-03-13 18:04 UTC, yangc95 commented on content/html/concepts/forms/forms.md
> +<!-- form elements -->
```suggestion
  <!-- Form elements -->
```

2023-03-13 18:05 UTC, yangc95 approved these changes

2023-03-13 18:09 UTC, merged

2023-03-14 04:17 UTC, yangc95 commented
Thanks for these edits @farah-qistina ☺️

live link: https://www.codecademy.com/resources/docs/html/forms

Feel free to take up open [Issues](https://github.com/Codecademy/docs/issues), if any.

2023-03-20 07:00 UTC, farah-qistina commented
@yangc95 thx for letting me work on this, I learned a lot!

2023-03-20 17:01 UTC, yangc95 commented
@farah-qistina yeah, follow these steps:

> To add your GitHub username to your Codecademy profile:
> 
> 1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
> 
> ![image](https://user-images.githubusercontent.com/86081858/220699030-55a1ef72-d1d1-40ab-942a-9e34ba4dbb13.png)
> 
> 2.) Then log out and log back into Codecademy using your GitHub login:
> 
> <img width="976" alt="githublogin" src="https://user-images.githubusercontent.com/72277593/221382073-53f7e2ed-5e39-4eb4-a993-b54a07ce72f6.png">
>
> If the steps above do not work, it may be due to an email or local configuration issue.
>
> In addition, we may reach out in the future if any adjustments to these entries are required.