[Term Entry] Pandas DataFrame: .sort_values()
Codecademy/docs pull request #1601
Opened 2023-02-03 18:49 UTC by alespros

### Description

Closes [#1575](https://github.com/Codecademy/docs/issues/1575)

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist
- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-03 18:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1601) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1601) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1601) it.</sub>

2023-02-03 22:04 UTC, caupolicandiaz requested changes
@alespros All set with this first review. It's mostly small formatting edits

2023-02-04 10:41 UTC, alespros commented on content/pandas/concepts/dataframe/terms/sortvalues/sortvalues.md
> +Description: 'Sorts values in a DataFrame based on the specified column or columns.'
I think this option would be more descriptive, but I can use the suggested change, too.
```suggestion
Description: 'Sorts values in a DataFrame by the specified column or row.'
```

2023-02-04 10:45 UTC, alespros commented on content/pandas/concepts/dataframe/terms/sortvalues/sortvalues.md
> +- `by`: `Name` or `list of names` to sort by.
```suggestion
- `by`: A label or list of labels to sort by (levels can also specified if applicable)..
```

2023-02-04 20:58 UTC, caupolicandiaz commented on content/pandas/concepts/dataframe/terms/sortvalues/sortvalues.md
> +Description: 'Sorts values in a DataFrame based on the specified column or columns.'
```suggestion
Description: 'Sorts values in a DataFrame based on a selection of columns or rows.'
```

2023-02-04 21:10 UTC, caupolicandiaz commented on content/pandas/concepts/dataframe/terms/sortvalues/sortvalues.md
> +Description: 'Sorts values in a DataFrame based on the specified column or columns.'
@alespros My edit is not as concise as I'd like, but I think it's important to detail that the sorting is not limited to one label in either direction.

2023-02-05 21:07 UTC, caupolicandiaz approved these changes
@alespros Looks good, this is ready for the next review

2023-02-06 17:46 UTC, SSwiniarski approved these changes
@alespros, @caupolicandiaz To me it looks good to merge.

2023-02-10 20:45 UTC, merged

2023-02-11 19:32 UTC, KTom101 commented
@alespros Congrats on the [.sort_values() entry](https://www.codecademy.com/resources/docs/pandas/dataframe/sortvalues)! 🎉 Please feel free to look to see if there is another unclaimed [issue](https://github.com/Codecademy/docs/issues) you want to work on or let us know if there is something currently not on Codecademy Docs you want to add!

<img width="819" alt="Screen Shot 2023-02-11 at 2 24 08 PM" src="https://user-images.githubusercontent.com/40783324/218277288-d43152f6-4049-404f-a8fa-36f9054a150d.png">