Ends with
Codecademy/docs pull request #1618
Opened 2023-02-06 05:54 UTC by JaceInglis

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-06 05:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1618) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1618) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1618) it.</sub>

2023-02-06 22:24 UTC, caupolicandiaz requested changes
@JaceInglis Just a few small edits

2023-02-06 22:24 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/endsWith/endsWith.md
> +- `suffix` (required): A string value that will be used to check given strings.
```suggestion
- `suffix` (required): The characters to be matched in the string.
```

2023-02-06 22:24 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/endsWith/endsWith.md
> +Description: 'Returns a boolean value depending on if a string ends with a given suffix'
```suggestion
Description: 'Returns true if a string ends with a given suffix, otherwise false.'
```

2023-02-06 22:24 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/endsWith/endsWith.md
> +The `.endsWith()` method only takes one parameter.
```suggestion

```

2023-02-06 22:24 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/endsWith/endsWith.md
> +## Example
```suggestion
## Example

The example below demonstrates the use of the `.endsWith()` method:
```

2023-02-07 01:20 UTC, JaceInglis commented
@caupolicandiaz thanks for suggestions. All changes have been made.

2023-02-07 16:59 UTC, caupolicandiaz approved these changes
@JaceInglis Looks good, this is ready for another review

2023-02-07 17:12 UTC, SSwiniarski commented on content/java/concepts/strings/terms/endsWith/endsWith.md
> +
```suggestion
```
Remove extra line break.

2023-02-07 19:34 UTC, JaceInglis commented
@SSwiniarski thanks. Fixed now.

2023-02-16 12:15 UTC, SSwiniarski approved these changes

2023-02-16 12:15 UTC, SSwiniarski commented on content/java/concepts/strings/terms/endsWith/endsWith.md
> +
```suggestion

```

2023-02-16 12:15 UTC, SSwiniarski commented on content/java/concepts/strings/terms/endsWith/endsWith.md
> +```
```suggestion
```

```

2023-02-16 12:20 UTC, merged

2023-02-16 12:29 UTC, SSwiniarski commented
@JaceInglis congrats on your new entry! The live entry can be seen here: https://www.codecademy.com/resources/docs/java/strings/endsWith

It looks like you're anonymous.
![image](https://user-images.githubusercontent.com/86081858/219365161-f77233c8-ff9d-4f63-b439-d95aaf95abe8.png)

If you'd like to become public, make sure to add your GitHub username to your Codecademy profile and set your visibility to everyone

cc: @caupolicandiaz

2023-02-17 10:41 UTC, JaceInglis commented
Thanks guys I added my GitHub username and set my profile to public for everone. How long will it take for my name to show on the codecademy page?

2023-02-19 23:10 UTC, yangc95 commented
@JaceInglis Thanks for checking back in! It looks like it's still not visible, in which case log out of your Codecademy account and log back in with GitHub.