[Term Entry] SwiftUI View Modifier: .overlay()
Codecademy/docs pull request #1621
Opened 2023-02-07 19:55 UTC by nickschelle

### Description

Under the swiftui concepts, I added an .overlay() information page to the viewmodifiers. This closes issue #1571 - [Term Entry] SwiftUI View Modifier: .overlay()

### Type of Change

I added:
- overlay/overlay.md to content/swiftui/concepts/viewmodifier/topic/terms/
- swiftui-viewmodifier-overlay.png to media/

### Checklist

- [*] All writings are my own.
- [*] My entry follows the Codecademy Docs style guide.
- [*] My changes generate no new warnings.
- [*] I have performed a self-review of my own writing and code.
- [*] I have checked my entry and corrected any misspellings.
- [*] I have made corresponding changes to the documentation if needed.
- [*] I have confirmed my changes are not being pushed from my forked `main` branch.
- [*] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [*] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-07 19:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1621) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1621) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1621) it.</sub>

2023-02-08 00:29 UTC, KTom101 requested changes
@nickschelle Thank you for contributing! I've added a first review of this entry 😁

2023-02-08 00:29 UTC, KTom101 commented on content/swiftui/concepts/viewmodifier/terms/overlay/overlay.md
> +  - 'Mobile Development
Missing a single quote here which is causing an error.
```suggestion
  - 'Mobile Development'
```

2023-02-08 00:29 UTC, KTom101 commented on content/swiftui/concepts/viewmodifier/terms/overlay/overlay.md
> +The **`.overlay()`** layers the views that you specify in front of a [`View`](https://www.codecademy.com/resources/docs/swiftui/views).
Avoid personal pronouns in Codecademy Docs
```suggestion
The **`.overlay()`** layers the specified [views](https://www.codecademy.com/resources/docs/swiftui/views) in front of another view.
```

2023-02-08 00:29 UTC, KTom101 commented on content/swiftui/concepts/viewmodifier/terms/overlay/overlay.md
> +- `content` is used to declare the views to add to the foreground, stacked in the order you list them. The last view that you list appears at the front of the stack.
```suggestion
- `content` is used to declare the views to add to the foreground, stacked in the order listed. The last view appears at the front of the stack.
```

2023-02-08 00:29 UTC, KTom101 commented on content/swiftui/concepts/viewmodifier/terms/overlay/overlay.md
> +
Add a description of the example. Something like:
```suggestion

The following example uses the `.overlay` modifier to lay a star over a `Circle`:

```

2023-02-08 00:29 UTC, KTom101 commented on content/swiftui/concepts/viewmodifier/terms/overlay/overlay.md
> +Description: 'Layers the specified views in front of a view.'
```suggestion
Description: 'Layers the specified views in front of another view.'
```

2023-02-08 00:29 UTC, KTom101 commented on content/swiftui/concepts/viewmodifier/terms/overlay/overlay.md
> +			Subviews here
```suggestion
			// Subviews here
```

2023-02-08 00:29 UTC, KTom101 commented on content/swiftui/concepts/viewmodifier/terms/overlay/overlay.md
> +```pseudo
Change this pseudo block so that everything is not shifted to the center. Keep left-aligned and use two spaces when indenting instead of 4.

2023-02-08 00:29 UTC, KTom101 commented on content/swiftui/concepts/viewmodifier/terms/overlay/overlay.md
> +	Color.blue
Same for this code-block as the pseudo-block above, align everything to the left and use two spaces when indenting.

2023-02-08 06:50 UTC, nickschelle commented
Thanks for reviewing my pull. I took a pass at those suggestions and pushed my commits. This is my first time making a pull request, so let me know if I need to do anything else.

2023-02-09 06:02 UTC, nickschelle commented
Hey @KTom101 this is my first pull request. I made the changes you suggested, committed them and pushed them. Is there something I'm supposed to do now? What happens next?

2023-02-10 04:00 UTC, KTom101 reviewed
@nickschelle I have a couple more changes for you to add. After, we can move on to the second review.

2023-02-10 04:00 UTC, KTom101 commented on content/swiftui/concepts/viewmodifier/terms/overlay/overlay.md
> +The following example uses the `.overlay` modifier to lay a star and a [`Circle`](https://www.codecademy.com/resources/docs/swiftui/views/terms/circle) over a over a `Color` view.:
```suggestion
The following example uses the `.overlay` modifier to lay a star and a [`Circle`](https://www.codecademy.com/resources/docs/swiftui/views/terms/circle) over a `Color` view:
```

2023-02-10 04:00 UTC, KTom101 commented on content/swiftui/concepts/viewmodifier/terms/overlay/overlay.md
> +	.frame(width: 200, height: 200)
For this example can we also change the tabbed indentation to two spaces instead? So for every tab replace with two spaces instead. For example, if there is one tab then change to two spaces. If there are two tabs then four spaces would replace them. Three tabs = six spaces and so on.

2023-02-10 06:16 UTC, nickschelle commented
Hey @KTom101 - Changes have been committed. LEt me know whats next!

2023-02-15 00:13 UTC, nickschelle commented
Hey @KTom101 - Anything for me to do on this?

2023-02-17 02:03 UTC, KTom101 approved these changes
@nickschelle Thank you for your patience. Just have to wait for a second reviewer to look at this.

2023-02-18 14:35 UTC, SSwiniarski approved these changes
@nickschelle, @KTom101 Looks good to me.

2023-02-18 19:41 UTC, KTom101 commented
@nickschelle I made a small change here: [dc19cd9](https://github.com/Codecademy/docs/pull/1621/commits/dc19cd9b5940c515bf990ce430809a1e44fa0ebf) to add the import line and body function to the code example. Otherwise, this is ready to merge.

2023-02-18 19:41 UTC, merged

2023-02-18 19:56 UTC, KTom101 commented
@nickschelle Entry is live here: https://www.codecademy.com/resources/docs/swiftui/viewmodifier/overlay 🎉 You're currently listed as an anonymous contributor. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.

<img width="838" alt="Screen Shot 2023-02-18 at 2 50 16 PM" src="https://user-images.githubusercontent.com/40783324/219885313-16a0505a-9af1-4470-bd7a-d1081c46794c.png">

To add your GitHub username to your Codecademy profile:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

<img width="871" alt="YourGitHubName" src="https://user-images.githubusercontent.com/40783324/219885435-840ed908-d4da-468f-a046-b859c8fc1f1e.png">

2.) Then log out and log back into Codecademy using your GitHub login:

<img width="1273" alt="ReLogIn" src="https://user-images.githubusercontent.com/40783324/219885451-6f22b6d7-194f-44bf-af60-9da39e510067.png">

Also, feel free to contribute to more [issues](https://github.com/Codecademy/docs/issues) or let us know if there is something you want to add!