Create toCharArray method
Codecademy/docs pull request #1624
Opened 2023-02-08 10:28 UTC by Othamae

### Description

Create a new term entry for java `.toCharArray()` method.

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-08 10:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1624) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1624) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1624) it.</sub>

2023-02-09 21:12 UTC, caupolicandiaz requested changes
@Othamae Just wrapped my initial review. Some additions and edits to better align this with our standards

2023-02-09 21:12 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toCharArray/toCharArray.md
> +Use `.toCharArray()` and then print all the characters from the array `"Hello CodeCademy!"` using a for loop:
```suggestion
The example below uses the `.toCharArray()` method to create a new array, and uses a loop to iterate through the array and print each character:
```

2023-02-09 21:12 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toCharArray/toCharArray.md
> +```java
```suggestion
```java
// Example2.java
```

2023-02-09 21:12 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toCharArray/toCharArray.md
> +The output would be:
```suggestion
This will produce the following output:
```

2023-02-09 21:12 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toCharArray/toCharArray.md
> +```
I would recommend deleting the first example. This is a pretty basic method and the additional example isn't really demonstrating some alternative functionality.

2023-02-09 21:12 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toCharArray/toCharArray.md
> +    String string = "Hello CodeCademy!";
```suggestion
    String salutation = "Hello CodeCademy!";
```

2023-02-09 21:12 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toCharArray/toCharArray.md
> +    char[] array = string.toCharArray();
```suggestion
    char[] textArray = salutation.toCharArray();
```

2023-02-09 21:12 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/toCharArray/toCharArray.md
> +        System.out.println(array[i]);
```suggestion
    for (int i = 0; i < textArray.length; i++) {
        System.out.println(textArray[i]);
```

2023-02-10 08:37 UTC, Othamae commented
@caupolicandiaz I have completed the changes :)
Please let me know if I did it correctly or should I complete any other steps?
Thanks a lot!

2023-02-11 21:51 UTC, caupolicandiaz approved these changes
@Othamae Looks good. This is ready for another review

2023-02-18 01:24 UTC, yangc95 reviewed
@Othamae I conducted a second review on this PR! Thanks for this addition 😄

2023-02-18 01:24 UTC, yangc95 commented on content/java/concepts/strings/terms/toCharArray/toCharArray.md
> +  - 'Java: Strings'
```suggestion
  - 'Computer Science'
```

For reference, you can check out the [subjects.md](https://github.com/Codecademy/docs/blob/main/documentation/subjects.md) file for future entry's subject field metadata 🙂

2023-02-18 01:24 UTC, yangc95 commented on content/java/concepts/strings/terms/toCharArray/toCharArray.md
> +The method `.toCharArray()` returns a new character array from the given string. The length of the array is equal to the length of the original string.
```suggestion
The method **`.toCharArray()`** returns a new character array from the given string. The length of the array is equal to the length of the original string.
```

2023-02-18 01:24 UTC, yangc95 commented on content/java/concepts/strings/terms/toCharArray/toCharArray.md
> +- Where `string` is the string to be transformed to a new array of characters.
```suggestion

- Where `string` is the string to be transformed to a new array of characters.
```

2023-02-18 01:24 UTC, yangc95 commented on content/java/concepts/strings/terms/toCharArray/toCharArray.md
> +```java
```suggestion
```pseudo
```

2023-02-18 01:24 UTC, yangc95 commented on content/java/concepts/strings/terms/toCharArray/toCharArray.md
> +
```suggestion
```

2023-02-18 01:24 UTC, yangc95 commented on content/java/concepts/strings/terms/toCharArray/toCharArray.md
> +```
```suggestion
```shell
```

2023-02-18 01:24 UTC, yangc95 commented on content/java/concepts/strings/terms/toCharArray/toCharArray.md
> +    String salutation = "Hello CodeCademy!";
```suggestion
    String salutation = "Hello Codecademy!";
```

2023-02-18 01:24 UTC, yangc95 commented on content/java/concepts/strings/terms/toCharArray/toCharArray.md
> +C
```suggestion
c
```

2023-02-18 01:24 UTC, yangc95 commented on content/java/concepts/strings/terms/toCharArray/toCharArray.md
> +The example below uses the `.toCharArray()` method to create a new array, and uses a loop to iterate through the array and print each character:
```suggestion
The example below uses the `.toCharArray()` method to create a new array, uses a loop to iterate through the array , and prints each character:
```

2023-02-18 08:29 UTC, Othamae commented
Hi @yangc95 changes completed :)
Thanks a lot!

2023-02-28 02:44 UTC, yangc95 approved these changes

2023-02-28 02:48 UTC, merged

2023-02-28 02:53 UTC, yangc95 commented
@Othamae Great term entry! Live link: https://www.codecademy.com/resources/docs/java/strings/toCharArray

<img width="793" alt="Screen Shot 2023-02-27 at 9 51 45 PM" src="https://user-images.githubusercontent.com/72277593/221741143-a77e021f-a339-417d-a667-5ebb2b075a60.png">

> It looks as if you're anonymous. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.
> 
> To add your GitHub username to your Codecademy profile:
> 
> 1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
> 
> ![image](https://user-images.githubusercontent.com/86081858/220699030-55a1ef72-d1d1-40ab-942a-9e34ba4dbb13.png)
> 
> 2.) Then log out and log back into Codecademy using your GitHub login:
> 
> <img width="976" alt="githublogin" src="https://user-images.githubusercontent.com/72277593/221382073-53f7e2ed-5e39-4eb4-a993-b54a07ce72f6.png">

cc: @caupolicandiaz @KTom101