class.md created
Codecademy/docs pull request #1625
Opened 2023-02-08 15:24 UTC by Cesarcas1958

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

I have created a file class.md as requested

2023-02-08 15:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1625) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1625) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1625) it.</sub>

2023-02-10 22:51 UTC, caupolicandiaz requested changes
@Cesarcas1958 I've finished an initial review. This entry is quite rough, I would ask that you please review our contribution guidelines and my notes carefully. And then make the appropriate changes. If you have any questions about what is being requested please reach out. Thanks

[https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md](url)

2023-02-10 22:51 UTC, caupolicandiaz commented on content/html/concepts/attributes/terms/class/class.md
> +
```suggestion
```

2023-02-10 22:51 UTC, caupolicandiaz commented on content/html/concepts/attributes/terms/class/class.md
> +Definition: 'Classes are HTML attributes used to select one or more elements for CSS styling or JavaScript purposes. The class attribute is commonly used for assigning styles to one or more elements.
```suggestion
Description: 'Classes are HTML attributes used to select one or more elements for the application of styling or logic.'
```

2023-02-10 22:51 UTC, caupolicandiaz commented on content/html/concepts/attributes/terms/class/class.md
> +
```suggestion
```

2023-02-10 22:51 UTC, caupolicandiaz commented on content/html/concepts/attributes/terms/class/class.md
> +
```suggestion

```

2023-02-10 22:51 UTC, caupolicandiaz commented on content/html/concepts/attributes/terms/class/class.md
> +  - 'Style'
```suggestion
  - 'Style'
CatalogContent:
  - 'learn-html'
  - 'paths/front-end-engineer-career-path'
---
```

2023-02-10 22:51 UTC, caupolicandiaz commented on content/html/concepts/attributes/terms/class/class.md
> +  - 'Style'
The formatting for the metadata section has several errors. Be sure to always use one of our templates or another entry as a starting point, you should never create an entry from scratch.

Additionally, you should never just copy a paste the written content from another source, even another Codecademy source. All entries should be original, which means you have to phrase the concept and other elements in your own words.

2023-02-10 22:51 UTC, caupolicandiaz commented on content/html/concepts/attributes/terms/class/class.md
> +Classes are HTML attributes used to select one or more elements for CSS styling or JavaScript purposes.
```suggestion
Classes are HTML attributes used to select one or more elements for the application of styling or logic. The class attribute is commonly used inside a stylesheet for the application of specific styling such as setting color and position parameters for elements on a page. Additionally, the class attribute is also used to reference elements relative to actions or interactivity that are implemented in the Javascript file.
```

2023-02-10 22:51 UTC, caupolicandiaz commented on content/html/concepts/attributes/terms/class/class.md
> +![Screenshot of styling for heading and sub-headings.](https://i.imgur.com/fMWV8DY.png)
Replace this example with an original of your own design

2023-02-10 22:51 UTC, caupolicandiaz commented on content/html/concepts/attributes/terms/class/class.md
> +![Screenshot of selecting heading and sub-headings with JavaScript](https://i.imgur.com/2uIJMAq.png)
Again replace this with original content

2023-02-10 23:31 UTC, Cesarcas1958 commented
Por tu nombre asumo que hablas español y de ser asi me pudieras enviar esos
detalles en español gracias. Si no es asi hazmelo saber
Gracias

El vie, 10 feb 2023 a la(s) 18:52, caupolicandiaz ***@***.***)
escribió:

> ***@***.**** requested changes on this pull request.
>
> @Cesarcas1958 <https://github.com/Cesarcas1958> I've finished an initial
> review. This entry is quite rough, I would ask that you please review our
> contribution guidelines and my notes carefully. And then make the
> appropriate changes. If you have any questions about what is being
> requested please reach out. Thanks
>
> https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md
> <http://url>
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1625#discussion_r1103303475>:
>
> > @@ -0,0 +1,82 @@
>
> +---
>
> +Title: 'Classes'
>
> +
>
>
> ⬇️ Suggested change
>
> -
>
>
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1625#discussion_r1103305077>:
>
> > @@ -0,0 +1,82 @@
>
> +---
>
> +Title: 'Classes'
>
> +
>
> +Definition: 'Classes are HTML attributes used to select one or more elements for CSS styling or JavaScript purposes. The class attribute is commonly used for assigning styles to one or more elements. Inside the stylesheet, a class name is selected with the following syntax: css .class-name { }  A class selector is a name preceded by a period (.).'
>
>
> ⬇️ Suggested change
>
> -Definition: 'Classes are HTML attributes used to select one or more elements for CSS styling or JavaScript purposes. The class attribute is commonly used for assigning styles to one or more elements. Inside the stylesheet, a class name is selected with the following syntax: css .class-name { }  A class selector is a name preceded by a period (.).'
>
> +Description: 'Classes are HTML attributes used to select one or more elements for the application of styling or logic.'
>
>
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1625#discussion_r1103305205>:
>
> > @@ -0,0 +1,82 @@
>
> +---
>
> +Title: 'Classes'
>
> +
>
> +Definition: 'Classes are HTML attributes used to select one or more elements for CSS styling or JavaScript purposes. The class attribute is commonly used for assigning styles to one or more elements. Inside the stylesheet, a class name is selected with the following syntax: css .class-name { }  A class selector is a name preceded by a period (.).'
>
> +
>
>
> ⬇️ Suggested change
>
> -
>
>
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1625#discussion_r1103305329>:
>
> > @@ -0,0 +1,82 @@
>
> +---
>
> +Title: 'Classes'
>
> +
>
> +Definition: 'Classes are HTML attributes used to select one or more elements for CSS styling or JavaScript purposes. The class attribute is commonly used for assigning styles to one or more elements. Inside the stylesheet, a class name is selected with the following syntax: css .class-name { }  A class selector is a name preceded by a period (.).'
>
> +
>
> +Subjects:
>
> +  - 'Web Development'
>
> +  - 'Web Design'
>
> +
>
>
> ⬇️ Suggested change
>
> -
>
>
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1625#discussion_r1103306736>:
>
> > @@ -0,0 +1,82 @@
>
> +---
>
> +Title: 'Classes'
>
> +
>
> +Definition: 'Classes are HTML attributes used to select one or more elements for CSS styling or JavaScript purposes. The class attribute is commonly used for assigning styles to one or more elements. Inside the stylesheet, a class name is selected with the following syntax: css .class-name { }  A class selector is a name preceded by a period (.).'
>
> +
>
> +Subjects:
>
> +  - 'Web Development'
>
> +  - 'Web Design'
>
> +
>
> +Tags:
>
> +  - 'Attributes'
>
> +  - 'Classes'
>
> +  - 'Style'
>
>
> ⬇️ Suggested change
>
> -  - 'Style'
>
> +  - 'Style'
>
> +CatalogContent:
>
> +  - 'learn-html'
>
> +  - 'paths/front-end-engineer-career-path'
>
> +---
>
>
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1625#discussion_r1103322050>:
>
> > @@ -0,0 +1,82 @@
>
> +---
>
> +Title: 'Classes'
>
> +
>
> +Definition: 'Classes are HTML attributes used to select one or more elements for CSS styling or JavaScript purposes. The class attribute is commonly used for assigning styles to one or more elements. Inside the stylesheet, a class name is selected with the following syntax: css .class-name { }  A class selector is a name preceded by a period (.).'
>
> +
>
> +Subjects:
>
> +  - 'Web Development'
>
> +  - 'Web Design'
>
> +
>
> +Tags:
>
> +  - 'Attributes'
>
> +  - 'Classes'
>
> +  - 'Style'
>
> +
>
> +Classes are HTML attributes used to select one or more elements for CSS styling or JavaScript purposes.
>
>
> ⬇️ Suggested change
>
> -Classes are HTML attributes used to select one or more elements for CSS styling or JavaScript purposes.
>
> +Classes are HTML attributes used to select one or more elements for the application of styling or logic. The class attribute is commonly used inside a stylesheet for the application of specific styling such as setting color and position parameters for elements on a page. Additionally, the class attribute is also used to reference elements relative to actions or interactivity that are implemented in the Javascript file.
>
>
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1625#discussion_r1103323259>:
>
> > +## For Styling
>
> +
>
> +The `class` attribute is used for assigning styles to elements. Multiple classes can be assigned to a single element in a space-separated list. (e.g. `class="class1 class2 class3"`)
>
> +
>
> +Inside the stylesheet, a class name is selected with the following syntax:
>
> +
>
> +```css
>
> +.class-1 {
>
> +}
>
> +```
>
> +
>
> +A class selector is a name preceded by a period (`.`).
>
> +
>
> +Below is some markup with an outer `cover-div`, containing a level 1 `headling` and three level 2 `sub-heading`s. The styling for the `headine` will be unique. However, all elements with the `sub-headline` class name received the same styling.
>
> +
>
> +```html
>
> +<!DOCTYPE html>
>
> +<html lang="en">
>
> +  <head>
>
> +    <style>
>
> +      .headline {
>
> +        background-color: lightblue;
>
> +      }
>
> +
>
> +      .sub-headline {
>
> +        background-color: lightskyblue;
>
> +        margin: 5px;
>
> +      }
>
> +    </style>
>
> +    <title>Classes</title>
>
> +  </head>
>
> +  <body>
>
> +    <div class="cover-div">
>
> +      <h1 class="headline">Welcome to Class!</h1>
>
> +
>
> +      <h2 class="sub-headline">_</h2>
>
> +
>
> +      <h2 class="sub-headline">_</h2>
>
> +
>
> +      <h2 class="sub-headline">_</h2>
>
> +    </div>
>
> +  </body>
>
> +</html>
>
> +```
>
> +
>
> +![Screenshot of styling for heading and sub-headings.](https://i.imgur.com/fMWV8DY.png)
>
>
> Replace this example with an original of your own design
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1625#discussion_r1103323697>:
>
> > +## For JavaScript
>
> +
>
> +The `class` attribute is used to perform JavaScript operations on HTML elements. Through the Document Object Model ("DOM"), there are various JavaScript methods built for selecting elements via their class.
>
> +
>
> +Assuming the markup from the last example is linked to a JavaScript file:
>
> +
>
> +```js
>
> +window.onload = function () {
>
> +  const subheadlines = document.getElementsByClassName('sub-headline');
>
> +
>
> +  for (let i = 0; i < subheadlines.length; i++) {
> [...]

2023-02-11 22:34 UTC, Cesarcas1958 commented
I made changes in class.md file as requested but I am having trouble to push the changes. Could you give some advice?
This is the message I am getting:
PS C:\Users\César Castellanos\Documents\GitHub\docs\content\html\concepts\attributes\terms\class> git pull origin new1
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

2023-02-12 14:59 UTC, closed without merging