[Term Entry] Java Strings: .trim() Method #1597
Codecademy/docs pull request #1629
Opened 2023-02-09 11:33 UTC by MiiPoikaj

### Description

A new term entry of .trim() for the Java: Strings concept. 

This contribution is part of the completion of "Learn Git&GitHub" course in Codecademy.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-09 11:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1629) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1629) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1629) it.</sub>

2023-02-09 21:43 UTC, caupolicandiaz requested changes
@MiiPoikaj Finished my initial review, just a handful of small edits.

2023-02-09 21:43 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/trim/trim.md
> +  - 'Whitespace'
```suggestion
  - 'Characters'
```

2023-02-09 21:43 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/trim/trim.md
> +The `.trim)` method is showcased in the following example:
```suggestion
The `.trim()` method is showcased in the following example:
```

2023-02-09 21:43 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/trim/trim.md
> +```java
```suggestion
```java
// Example.java
```

2023-02-09 21:43 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/trim/trim.md
> +In this example, the .trim() method removes leading and trailing whitespaces from the string greetings.
```suggestion
In the example below, the `.trim()` method removes leading and trailing whitespaces from the string `greetings`.
```

2023-02-09 21:43 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/trim/trim.md
> +In this example, the .trim() method removes leading and trailing whitespaces from the string greetings.
I'd recommend replacing the sentence introducing the example with this one.

2023-02-09 21:43 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/trim/trim.md
> +The output would be:
```suggestion
This will produce the following output:
```

2023-02-10 20:17 UTC, caupolicandiaz requested changes

2023-02-10 20:17 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/trim/trim.md
> +In the example below, the `.trim()` method removes leading and trailing whitespaces from the string `greetings`.
@MiiPoikaj I think my previous note may have been confusing. I was suggesting that you replace line 27 with 41. Having both is unnecessary, and 41 is the more descriptive of the two. Let me know if you have any additional questions.

2023-02-13 20:58 UTC, caupolicandiaz approved these changes
@MiiPoikaj Looks good! This is ready for another review

2023-02-13 22:20 UTC, HishamT approved these changes
LGTM!

2023-02-13 22:22 UTC, merged

2023-02-15 00:39 UTC, yangc95 commented
🥳 @MiiPoikaj Thanks for this entry! Here's the live link: https://www.codecademy.com/resources/docs/java/strings/trim

Although, you are currently anonymous. If you'd like to make yourself public, ensure that your GitHub username is added to your Codecademy profile and set your visibility to "everyone."
<img width="829" alt="Screen Shot 2023-02-14 at 7 36 51 PM" src="https://user-images.githubusercontent.com/72277593/218895129-81e0bb5e-7b64-4efd-aa8b-1270b2086c4b.png">

cc: @HishamT @caupolicandiaz