New Topic: Cybersecurity
Codecademy/docs pull request #1633
Opened 2023-02-09 19:11 UTC by realber

### Description

This is a cybersecurity concept, risk management.

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-10 17:23 UTC, SSwiniarski commented
@realber, just to note that you are pushing this from your main branch, which isn't recommended. You should create forks for each separate entry.

2023-02-10 17:34 UTC, SSwiniarski requested changes
@realber I did a first review, and left a couple of comments. The most important is we need to resolve the lack of metadata in these entries.

Also, because this was pushed from your main branch, you may want to wait until this is merged before submitting a new PR.

2023-02-10 17:34 UTC, SSwiniarski commented on content/cybersecurity/concepts/risk-management/risk-management.md
> +## Relevant Courses:
Course links will be provided with the Metadata.

2023-02-10 17:34 UTC, SSwiniarski commented on content/cybersecurity/concepts/spear-phishing/spear-phishing.md
> +# Spear phishing
We're missing the metadata for this entry. Look at the [source here](https://github.com/Codecademy/docs/blob/main/content/cybersecurity/concepts/cyber-attack/cyber-attack.md) to see an example of what we need.

Also, remove the h1 header, the metadata title will provide that.

2023-02-10 17:34 UTC, SSwiniarski commented on content/cybersecurity/concepts/spear-phishing/spear-phishing.md
> +Spear phishing is a type of social engineering scam that attempts to trick the recipient into providing confidential information to the attacker. Spear phishing is a more targeted cyber attack than p
```suggestion
**Spear phishing** is a type of social engineering scam that attempts to trick the recipient into providing confidential information to the attacker. Spear phishing is a more targeted cyber attack than phishing.
```

2023-02-10 17:34 UTC, SSwiniarski commented on content/cybersecurity/concepts/spear-phishing/spear-phishing.md
> +Spear phishing often is used interchangeably with phishing and whaling, but it is important to note the differences. Phishing is a more generic attempt to dupe a victim. It emphasizes quantity. Phish
You mention the comparison to whaling, but never define the term in opposition to spear phishing. There should be a sentence covering it.

2023-02-10 17:34 UTC, SSwiniarski commented on content/cybersecurity/concepts/spear-phishing/spear-phishing.md
> +## Relevant Courses:
Course links will be provided by the metadata.

2023-02-11 13:08 UTC, SSwiniarski commented
Closed per @jonchery

2023-03-02 01:11 UTC, yangc95 reviewed
@realber thanks for these entries! I left a few comments 🙂 when you're finished please let me know by tagging me and we can see if it's ready to merge

2023-03-02 01:11 UTC, yangc95 commented on content/cybersecurity/concepts/spear-phishing/spear-phishing.md
> +**Spear phishing** is a type of social engineering scam that attempts to trick the recipient into providing confidential information to the attacker. Spear phishing is a more targeted cyber attack th
Good op to link out to cyber attack entry: https://www.codecademy.com/resources/docs/cybersecurity/cyber-attack

2023-03-02 01:11 UTC, yangc95 commented on content/cybersecurity/concepts/spear-phishing/spear-phishing.md
> +The targeted nature of spear phishing makes it difficult to detect. For example, attackers who claim to be the CEO could trick finance executives into sending money to their bank account. An attacker
```suggestion
The targeted nature of spear phishing makes it difficult to detect. For example, attackers who claim to be the CEO could trick finance executives into sending money to their bank account. An attacker might create messages that seem like the IT (Information Technology) Department is asking for more information. Deploying [multi-factor authentication](https://www.codecademy.com/resources/docs/cybersecurity/multi-factor-authentication), strong password management policies, and participating in training and awareness campaigns are good measures to help mitigate risks.
```

2023-03-02 01:11 UTC, yangc95 commented on content/cybersecurity/concepts/spear-phishing/spear-phishing.md
> +Spear phishing often is used interchangeably with phishing and whaling, but it is important to note the differences. Phishing is a more generic attempt to dupe a victim. It emphasizes quantity. Phish
```suggestion
Spear phishing is often used interchangeably with phishing and whaling, but it is important to note the differences. Phishing is a more generic attempt to dupe a victim. It emphasizes quantity. Phishing emails or texts are usually sent to large groups of individuals as opposed to a targeted individual in a spear phishing campaign. Whaling prioritizes high-level targets, specifically the various chief officers of an organization.
```

2023-03-02 13:58 UTC, jonchery commented
@yangc95 

@realber is no longer working on this project. That said, he won't be able to make any of the requested changes. Since I'm not the author of this PR, I won't be able to submit or make those changes too.

2023-03-02 16:39 UTC, SSwiniarski commented
@yangc95, @jonchery I committed all the suggested changes. If @yangc95 approves them, I can go ahead and merge this.

2023-03-06 17:52 UTC, yangc95 approved these changes
@SSwiniarski LGTM

2023-03-07 16:45 UTC, SSwiniarski approved these changes

2023-03-07 16:46 UTC, merged

2023-03-08 20:30 UTC, yangc95 commented
@SSwiniarski Thanks for merging!

@realber here's the live links: 
- https://www.codecademy.com/resources/docs/cybersecurity/risk-management
- https://www.codecademy.com/resources/docs/cybersecurity/spear-phishing

<img width="813" alt="Screen Shot 2023-03-08 at 3 29 12 PM" src="https://user-images.githubusercontent.com/72277593/223842437-b045337d-2ce6-44a5-81af-fe994f78070a.png">
<img width="815" alt="Screen Shot 2023-03-08 at 3 30 05 PM" src="https://user-images.githubusercontent.com/72277593/223842588-076a1a9b-7ec5-4373-98ef-4d0b76243da5.png">

> It looks as if you're anonymous. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.
> 
> To add your GitHub username to your Codecademy profile:
> 
> 1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
> 
> ![image](https://user-images.githubusercontent.com/86081858/220699030-55a1ef72-d1d1-40ab-942a-9e34ba4dbb13.png)
> 
> 2.) Then log out and log back into Codecademy using your GitHub login:
> 
> <img width="976" alt="githublogin" src="https://user-images.githubusercontent.com/72277593/221382073-53f7e2ed-5e39-4eb4-a993-b54a07ce72f6.png">
>
> If the steps above do not work, it may be due to an email or local configuration issue.

2023-03-29 12:16 UTC, jonchery commented
Hi @yangc95 , unfortunately, @realber is not longer with us and won't be able to make those changes.

2023-03-29 16:23 UTC, yangc95 commented
@jonchery would you mind me asking how you became aware of @realber's absence? Thanks for any info that can be disclosed!

2023-03-29 17:50 UTC, jonchery commented
He was my content contributor (CC) working on the doc (as well as several others). Once the doc project was done, the contract was complete.

2023-03-29 19:19 UTC, yangc95 commented
🙂 @jonchery thank you for this transparency. In which case, I will go ahead and make these changes unless told otherwise