First commit of startsWith.md
Codecademy/docs pull request #1637
Opened 2023-02-10 16:07 UTC by en1g

### Description

Add a new term entry under the [Java: Strings](https://www.codecademy.com/resources/docs/java/strings) concept. 

/resources/docs/java/concepts/strings/startsWith/startsWith.md

Closes #1594 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own. (using .equals() as a guide)
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-10 16:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1637) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1637) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1637) it.</sub>

2023-02-13 23:45 UTC, HishamT requested changes
Hello @en1g. Thank you for your contribution to Codecademy Docs. I have reviewed your entry and left you some comments. :grin:

2023-02-13 23:45 UTC, HishamT commented on content/java/concepts/strings/terms/startsWith/startsWith.md
> +The **`.startsWith()`** method returns `true` if a string starts with given character(s). Otherwise, `false` is returned.
```suggestion
The **`.startsWith()`** method returns `true` if a string starts with a given character sequence. Otherwise, `false` is returned.
```

2023-02-13 23:45 UTC, HishamT commented on content/java/concepts/strings/terms/startsWith/startsWith.md
> +string.startsWith(object);
```suggestion
string.startsWith(stringOfCharacters);
```

2023-02-13 23:45 UTC, HishamT commented on content/java/concepts/strings/terms/startsWith/startsWith.md
> +The `object` can either be a string literal or a representation of a `String` value. This will return `true` if the `object` has the same starting character sequence as `string` .
This sentence is a bit confusing. Can you reword it? Also, `object` is now `stringOfCharacters`.

2023-02-13 23:45 UTC, HishamT commented on content/java/concepts/strings/terms/startsWith/startsWith.md
> +The following example showcases the `.startsWith()` method:
```suggestion
The following example demonstrates the `.startsWith()` method:
```

2023-02-15 09:33 UTC, en1g commented
Hi, @HishamT. I think I've committed all the changes you've requested. let me know if I need to do anything else. Cheers.

2023-02-16 20:25 UTC, HishamT approved these changes
LGTM! :+1:

2023-02-16 22:05 UTC, caupolicandiaz requested changes
@en1g Overall, this looks good. Just a couple of additional small edits.

2023-02-16 22:05 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/startsWith/startsWith.md
> +The `stringOfChcaracters` can either be a string literal or a representation of a `String` value (Variable/Constant etc).
```suggestion
The `stringOfChcaracters` can either be a string literal or a representation of a `String` value (variables, constants, etc.). 
```

2023-02-18 17:54 UTC, en1g commented
Hi @caupolicandiaz, I think I've got everything you asked for. let me know if I need to do anything else. Cheers

2023-02-18 20:32 UTC, caupolicandiaz approved these changes
@en1g Looks good.

2023-02-21 16:35 UTC, SSwiniarski approved these changes
Looks good to merge.

2023-02-21 16:41 UTC, merged

2023-02-21 16:58 UTC, SSwiniarski commented
Congrats @en1g on your new entry! You can see it live here: https://www.codecademy.com/resources/docs/java/strings/startsWith

It seems you are anonymous:
![image](https://user-images.githubusercontent.com/86081858/220410245-93f8cdaf-188f-4721-8ff4-cdcf63df9e5e.png)

If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.

To add your GitHub username to your Codecademy profile:
1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
![image](https://user-images.githubusercontent.com/86081858/220410498-9b91e853-4d9e-4e8f-a5c0-a97eda830cc2.png)

2.) Then log out and log back into Codecademy using your GitHub login:
![image](https://user-images.githubusercontent.com/86081858/220410642-10f77ea9-989d-4e1a-b74b-be506b778ee9.png)