Adding a new entry [Term Entry] java string
Codecademy/docs pull request #1644
Opened 2023-02-12 20:21 UTC by jaymay1979

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-12 20:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1644) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1644) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1644) it.</sub>

2023-02-12 22:32 UTC, jaymay1979 commented
[lastIndexOf.md](https://github.com/Codecademy/docs/files/10717466/lastIndexOf.md)

2023-02-12 22:33 UTC, jaymay1979 commented
Adding a new java entry as part of my "Open Source" code academy courses.

[lastIndexOf.md](https://github.com/Codecademy/docs/files/10717471/lastIndexOf.md)

2023-02-13 04:15 UTC, caupolicandiaz requested changes
@jaymay1979 Finished the first review on this entry. Please review and update.

2023-02-13 04:15 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/lastIndexOf/lastIndexOf.md
> +This outputes the following:
```suggestion
This will output the following:

```

2023-02-13 04:15 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/lastIndexOf/lastIndexOf.md
> +```java
```suggestion
```shell

```

2023-02-13 04:15 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/lastIndexOf/lastIndexOf.md
> +console.log(lastPos); // 31
public class Main {
  public static void main(String[] args) {
    String sentence = "The quick brown fox jumps over the lazy dog";

    System.out.print(sentence.lastIndexOf("the")); 
  }
}

2023-02-13 04:15 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/lastIndexOf/lastIndexOf.md
> +This example searches the string `str` for the value `the` and returns the index of the last occurrence of `the`:
```suggestion
This example below searches the string `sentence` for the value `the` and returns the index of the last occurrence:

```

2023-02-14 18:24 UTC, jaymay1979 commented
I've make the recommended updates on my local branch. What are the next steps?

2023-02-14 20:06 UTC, jaymay1979 commented
I pushed the new changes from my local branch to my remote repository..

2023-02-16 23:44 UTC, closed without merging