[Term Entry] Java Strings: .replaceAll method
Codecademy/docs pull request #1647
Opened 2023-02-14 04:41 UTC by marymkohn

### Java Strings: .replaceAll method
Created a term entry for Codecademy docs

### Type of Change
- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-14 04:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1647) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1647) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1647) it.</sub>

2023-02-14 17:02 UTC, SSwiniarski reviewed
@marymkohn I did a first review and left a few comments.

2023-02-14 17:02 UTC, SSwiniarski commented on content/java/concepts/strings/terms/replaceAll/replaceAll.md
> +The example below removes all whitespace
```suggestion
The example below removes all whitespace:
```

2023-02-14 17:02 UTC, SSwiniarski commented on content/java/concepts/strings/terms/replaceAll/replaceAll.md
> +Both the `.replace()` and `.replaceAll()` methods replace all occurrences of a matching string and accept `CharSequence` as input. However, the key difference is that `.replaceAll()` treats the given
```suggestion
> **Note:** Both the [`.replace()`](https://www.codecademy.com/resources/docs/java/strings/replace) and `.replaceAll()` methods replace all occurrences of a matching string and accept `CharSequence` as input. However, the key difference is that `.replaceAll()` treats the given `CharSequence` as a *regular expression* and searches for `regex` matches, while `.replace()` treats the input as plain text.
```

2023-02-15 16:55 UTC, SSwiniarski approved these changes
@marymkohn Looks ready for a second review.

2023-02-15 22:27 UTC, caupolicandiaz requested changes
@marymkohn Overall, this looks good. I've added a few additional edits

2023-02-15 22:27 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/replaceAll/replaceAll.md
> +  - 'Methods'
```suggestion
  - 'Methods'
  - 'Characters'
```

2023-02-15 22:27 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/replaceAll/replaceAll.md
> +The `String` class' `.replaceAll()` method replaces every matching subsequence in the input sequence with the specified replacement string.
```suggestion
The `String` class' **`.replaceAll()`** method replaces every matching subsequence in the input sequence with the specified replacement string.
```

2023-02-15 22:27 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/replaceAll/replaceAll.md
> +This method replaces all the substrings in the string that match the given regular expression (`regex`) with the given replacement (`repl`).
```suggestion

```

2023-02-15 22:27 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/replaceAll/replaceAll.md
> +`regex` represents the [regular expression](https://www.codecademy.com/resources/docs/general/regular-expressions) to which this string is to be matched.
```suggestion
`regex` represents the [regular expression](https://www.codecademy.com/resources/docs/general/regular-expressions): a set of special characters and letters used for matching specific text.
```

2023-02-15 22:27 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/replaceAll/replaceAll.md
> +This method replaces all the substrings in the string that match the given regular expression (`regex`) with the given replacement (`repl`).
this feels redundant

2023-02-15 22:27 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/replaceAll/replaceAll.md
> +String newString = myString.replaceAll(regex, replacement);
```suggestion
public class Main {
  public static void main(String[] args) {
    String myString = "Dog\t  \r\rComputer\n\n  \r House \t Yes \n  ";

    String regex = "\\s";   
    // The shorthand code \s represents spaces, tabs, and newline characters
    String replacement = "";

    String newString = myString.replaceAll(regex, replacement);
    System.out.println(newString);
```

2023-02-16 20:06 UTC, caupolicandiaz approved these changes
@marymkohn LGTM

2023-02-17 17:48 UTC, merged

2023-02-17 17:54 UTC, SSwiniarski commented
Congrats @marymkohn on your new entry. You can see it live here: https://www.codecademy.com/resources/docs/java/strings/replaceAll

It looks like you're currently anonymous:
![image](https://user-images.githubusercontent.com/86081858/219736860-b94a5b76-13f0-40af-8102-72cfb53c90aa.png)

If you'd like to become public, make sure to add your GitHub username to your Codecademy profile and set your visibility to everyone.

cc: @caupolicandiaz

2023-09-25 14:52 UTC, marjoriekohn commented
@SSwiniarski I recently underwent a legal name change and updated my GitHub and Codecademy usernames. Also, at the time of this contribution, my profile was private, but I’ve since made it public. Can we update this contribution to publicly reflect my current username on Codecademy Docs?

2023-09-27 16:08 UTC, SSwiniarski commented
@marjoriekohn I don't know if we can do this. Any advice: @yangc95, @KTom101, @caupolicandiaz?

2023-09-27 18:17 UTC, KTom101 commented
@marjoriekohn Have you gone about following the steps of adding the new GitHub username to your Codecademy account? Since you only changed the username on the account not create a new account, there shouldn't be a problem with getting authorship. The steps are [here](uhttps://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036rl).

2023-10-02 19:38 UTC, marjoriekohn commented
@KTom101 My information is up to date on Codecademy and my profile is public.

<img width="321" src="https://github.com/Codecademy/docs/assets/117579674/2a127b59-cdaa-431d-bb0d-ada68abc6214"><img width="321" src="https://github.com/Codecademy/docs/assets/117579674/e9e602b9-5b68-45a6-b274-51ae189129a2">

2023-10-03 14:28 UTC, yangc95 commented
@marjoriekohn Did you head over to [linked accounts](https://www.codecademy.com/account/linked_accts) in the[ link that was provided ](https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036) just to double-check that

2023-10-03 15:00 UTC, yangc95 commented
@marjoriekohn double checking now, I see that the newer PR you pushed up is showing up properly. I noticed that the emails you used for this one versus the new entry are different. Can you double check what you have as your email? The easiest way is to make a change to this file, after which you would appear here as a contributor.

In the future, just make sure you're pushing up with the same email. You can double check the email with `git log` and use `git config` to view your email is accurate.