Add MathExp-kpetrov2
Codecademy/docs pull request #1649
Opened 2023-02-14 12:35 UTC by kpetrov2

### Description

I have created a directory named exp/ in the section specified by the issue advertiser. Inside this directory is the exp.md file that contains the necessary information to understand the Math.Exp() method.
I have chosen this issue to contribute for the first time to the CodeCademy Docs in order to finish the GitHub course. I appreciate the chance to participate in a real task.

### Type of Change

- Adding a new entry

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-14 12:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1649) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1649) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1649) it.</sub>

2023-02-14 17:19 UTC, SSwiniarski requested changes
@kpetrov2, I did a first review and left a few comments.

2023-02-14 17:19 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/exp/exp.md
> +Description: 'Returns the result of raising e with a specific number.'
```suggestion
Description: 'Returns the result of raising e to the power of a specific number.'
```

2023-02-14 17:19 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/exp/exp.md
> +The **`Math.Exp()`** method returns the value of raising **`e`** with the number given as a **power**.
```suggestion
The **`Math.Exp()`** method returns the value of raising _e_ to the power of a given number.
```

2023-02-14 17:19 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/exp/exp.md
> +**`e`** stands for Euler's number, the **Euler's number** is an irrational number, with an approximate constant value of **2.71828** , that provides a constant base to the **natural logarithm** or **
```suggestion
_e_ stands for Euler's number, an irrational number, with an approximate constant value of 2.71828. It provides a constant base to the natural logarithm or log and can be understood as a limit of a given progression.
```

2023-02-14 17:19 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/exp/exp.md
> +Consequently, the **`Math.Exp()`** method is the inverse of the **`Math.Log()`** method.
```suggestion
Consequently, the `Math.Exp()` method is the inverse of the `Math.Log()` method.
```

2023-02-15 00:26 UTC, kpetrov2 commented
I've made the changes, should I wait or should I do another pull request?

2023-02-15 07:04 UTC, yangc95 commented
> I've made the changes, should I wait or should I do another pull request?

@kpetrov2 Please see: https://github.com/Codecademy/docs/issues/1606#issuecomment-1430853336

2023-02-15 17:19 UTC, SSwiniarski approved these changes
@kpetrov2 One minor typo, otherwise it looks good for a second review.

2023-02-15 17:19 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/exp/exp.md
> +The **`Math.Exp()`** method returns the value of raising _e_ the power of a given number.
```suggestion
The **`Math.Exp()`** method returns the value of raising _e_ to the power of a given number.
```

2023-02-15 19:47 UTC, kpetrov2 commented
Correct! Sorry I forgot that, thanks for the advice :)

2023-02-18 03:19 UTC, yangc95 approved these changes

2023-02-18 03:22 UTC, merged

2023-02-18 05:23 UTC, yangc95 commented
@kpetrov2 here is the live link for this one: https://www.codecademy.com/resources/docs/c-sharp/math-functions/exp

Would you be able to make an additional PR to resolve the issue with this section: `$$ \sum\limits_{n=0}^{\infty} \frac{1}{n!} = 1 + \frac{1}{n+1} + \frac{1}{(n+1)(n+2)} + \frac{1}{(n+1)(n+2)(n+3)} + \cdots $$`

Maybe an image can be swapped out for that line instead!

You're also currently anonymous:
![Screen Shot 2023-02-18 at 12 21 39 AM](https://user-images.githubusercontent.com/72277593/219842675-94319b50-b854-49d0-89d7-0c576c1ce391.png)
Make sure to add your GitHub username to your Codecademy profile and set the visibility to "everyone."

cc: @SSwiniarski @KTom101