new Color.md file
Codecademy/docs pull request #1675
Opened 2023-02-18 05:22 UTC by flodega

### Description

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-18 05:27 UTC, flodega commented
@SSwiniarski The issue is gone now.  Thanks for the help.  Awaiting final review now

2023-02-18 13:16 UTC, SSwiniarski approved these changes

2023-02-19 05:31 UTC, KTom101 requested changes
@flodega I've added a second review of this.

2023-02-19 05:31 UTC, KTom101 commented on content/swiftui/concepts/views/terms/color/color.md
> +var body: some View {
There is a lot of extra spacing in this code example, can we change this to remove the extraneous spacing? In Codecademy Docs entries, we typically use 2-spaces for indentation in code examples.

2023-02-19 06:07 UTC, flodega commented on content/swiftui/concepts/views/terms/color/color.md
> +## Example
@KTom101 What do you mean by this ?  Do you want me to remove that line of code entirely ?

2023-02-19 06:23 UTC, flodega commented
@KTom101 I made some changes.  Please let me know if it is okay now.

2023-02-28 04:51 UTC, KTom101 commented on content/swiftui/concepts/views/terms/color/color.md
> +## Example
@flodega You made the right correction. Line breaks are added before and after subheadings. 👍

2023-02-28 04:57 UTC, KTom101 approved these changes
@flodega This looks good. I made a small change directly in commit [865a804](https://github.com/Codecademy/docs/pull/1675/commits/865a8044f92e537f6c6b7179a6745b75819c3cac). The only thing that needs to be done now is fixing the [failed checks](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md#i-submitted-a-pr-but-tests-are-failing-how-do-i-fix-them:~:text=I%20submitted%20a%20PR%20but%20tests%20are%20failing%2C%20how%20do%20I%20fix%20them%3F). Will you be able to do this yourself or would you like me to do it?

2023-03-02 18:58 UTC, flodega commented
@KTom101 Thanks, and it would be helpful if you could help with the checks as I am currently not even sure why they are appearing.  I would also very much like to learn how you fix those said failed checks.  Thanks

2023-03-02 21:24 UTC, KTom101 commented
@flodega I already have npm installed so I ran `npm run format:verify` and `npm run format:all`  in my terminal on my local repo and pushed the changes up. You can see what was changed in commit [42b0c38](https://github.com/Codecademy/docs/pull/1675/commits/42b0c381173650993e088337a3a734f5ee1351d6), which were a couple of minor extra spacings that was causing the check errors.

2023-03-02 21:43 UTC, merged

2023-03-02 22:09 UTC, KTom101 commented
@flodega Link is live here: https://www.codecademy.com/resources/docs/swiftui/views/color You're currently listed as an anonymous contributor:

<img width="821" alt="Screen Shot 2023-03-02 at 5 01 15 PM" src="https://user-images.githubusercontent.com/40783324/222568494-0f651345-ae29-41aa-848e-a1eeed4e6dad.png">

If you would like to be listed follow these steps to add your GitHub username to your Codecademy Profile:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

<img width="871" alt="YourGitHubName" src="https://user-images.githubusercontent.com/40783324/222569088-173a9503-d6ae-4f5e-9a2e-f5c816f19d84.png">

2.) Then log out and log back into Codecademy using your GitHub login:

<img width="1273" alt="ReLogIn" src="https://user-images.githubusercontent.com/40783324/222569180-437b0569-7ce1-49bf-b9da-83105eb8c91a.png">

< **Note:** Your email used for Codecademy will have to be listed in your GitHub profile for the login feature to properly work. If you use the same email for both GitHub and Codecademy already, then you're set.