Math exp kpetrov2 patch 1
Codecademy/docs pull request #1681
Opened 2023-02-19 09:19 UTC by kpetrov2

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-19 09:25 UTC, kpetrov2 commented
@SSwiniarski that is the new PR with the requested changes. I made a new branch, because awgraves did commit on the previous branch. I thought he was one of the reviewers.

2023-02-19 15:01 UTC, SSwiniarski requested changes
@kpetrov2 I have one comment,

2023-02-19 15:01 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/exp/exp.md
> +https://raw.githubusercontent.com/Codecademy/docs/main/media/e-formula.jpg
```suggestion
![e formula](https://raw.githubusercontent.com/Codecademy/docs/main/media/e-formula.jpg)
```
The image must be in Markdown.

2023-02-19 16:11 UTC, kpetrov2 commented on content/c-sharp/concepts/math-functions/terms/exp/exp.md
> +https://raw.githubusercontent.com/Codecademy/docs/main/media/e-formula.jpg
Done :)

2023-02-19 16:38 UTC, SSwiniarski approved these changes
@kpetrov2 Looks good.

2023-02-24 07:01 UTC, kpetrov2 commented
Hi! Should I make any changes?

2023-02-24 16:42 UTC, SSwiniarski commented
@kpetrov2 Not yet. The entry needs another review by one of the other maintainers. They may have additional suggestions for you. But you don't need to do anything until then.

2023-02-24 18:48 UTC, yangc95 approved these changes

2023-02-24 18:49 UTC, merged

2023-02-24 18:53 UTC, yangc95 commented
@kpetrov2 Awesome! Thanks for adding that image:

<img width="812" alt="Screen Shot 2023-02-24 at 1 50 46 PM" src="https://user-images.githubusercontent.com/72277593/221266542-751a5166-5fd2-4771-82c8-7e8f29823129.png">
Much better 👏 also just checking, did you wish to remain anonymous? If yes, there's nothing else that needs to be done here 🙂

Otherwise, you can do the following:

> If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile.
> 
> To add your GitHub username to your Codecademy profile:
> 
> 1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
> 
> ![image](https://user-images.githubusercontent.com/86081858/220699030-55a1ef72-d1d1-40ab-942a-9e34ba4dbb13.png)
> 
> 2.) Then log out and log back into Codecademy using your GitHub login:
> 
> ![image](https://user-images.githubusercontent.com/86081858/220699181-215bb100-e413-4871-8ddd-a308c1444246.png)

cc: @SSwiniarski

2023-02-24 19:52 UTC, kpetrov2 commented
Hi! @yangc95 I have followed your instructions, but I'm still ana anonymous contributor, is there another solution?
Best regards!