Updated [Term Entry] java string
Codecademy/docs pull request #1686
Opened 2023-02-20 18:55 UTC by jaymay1979

### Description

Per the review of the new term entry java string file, lastIndexOf.md, the suggested updates and modifications have been made for review. Closes #1588

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-20 20:58 UTC, caupolicandiaz requested changes
@jaymay1979 Just a few edits, tag me when you've made the updates.

2023-02-20 20:58 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/lastIndexOf/lastIndexOf.md
> +  - 'String'
```suggestion
  - 'Strings'

```

2023-02-20 20:58 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/lastIndexOf/lastIndexOf.md
> +  - 'Method'
```suggestion
  - 'Methods'

```

2023-02-20 20:58 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/lastIndexOf/lastIndexOf.md
> +  - 'Method'
if in doubt check our list of tags- https://github.com/Codecademy/docs/blob/main/documentation/tags.md

2023-02-20 20:58 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/lastIndexOf/lastIndexOf.md
> +```
```java
class Main {
   public static void main(String[] args) {

     String sentence = "The quick brown fox jumps over the lazy dog";

     int lastPos = sentence.lastIndexOf("the");

     System.out.println(lastPos);
  }
}
```

2023-02-20 20:58 UTC, caupolicandiaz commented on content/java/concepts/strings/terms/lastIndexOf/lastIndexOf.md
> +```
generally we present the examples within the context of a class

2023-02-21 23:00 UTC, jaymay1979 reviewed
I made these final changes on my remote repo, lastIndexOf. Hope my workflow is making since.

2023-02-21 23:46 UTC, caupolicandiaz approved these changes
@jaymay1979 Looks good. This is ready for another review

2023-02-24 15:28 UTC, jaymay1979 commented
Is there anything on my end that needs to be done to get my next review?

2023-02-24 20:11 UTC, HishamT approved these changes
LGTM!

2023-03-02 20:28 UTC, merged

2023-03-02 20:45 UTC, yangc95 commented
🥳 Thanks for this entry @jaymay1979 here's the live link: https://www.codecademy.com/resources/docs/java/strings/lastIndexOf

<img width="808" alt="Screen Shot 2023-03-02 at 3 44 24 PM" src="https://user-images.githubusercontent.com/72277593/222547509-bb31a33d-eea6-4ba2-9363-b21cce9c905d.png">

> It looks as if you're anonymous. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.
> 
> To add your GitHub username to your Codecademy profile:
> 
> 1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
> 
> ![image](https://user-images.githubusercontent.com/86081858/220699030-55a1ef72-d1d1-40ab-942a-9e34ba4dbb13.png)
> 
> 2.) Then log out and log back into Codecademy using your GitHub login:
> 
> <img width="976" alt="githublogin" src="https://user-images.githubusercontent.com/72277593/221382073-53f7e2ed-5e39-4eb4-a993-b54a07ce72f6.png">