Keyboardtype modifier
Codecademy/docs pull request #1692
Opened 2023-02-21 14:41 UTC by Digital-Brendan

### Description

I wrote a new entry under: content/swiftui/concepts/viewmodifier/terms/ about the modifier .keyboardType() in Swift, giving a simple example and outlining the correct usage & syntax.

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-21 14:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1692) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1692) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1692) it.</sub>

2023-02-22 01:33 UTC, KTom101 requested changes
@Digital-Brendan I only see a couple of minor changes for this entry.

2023-02-22 01:33 UTC, KTom101 commented on content/swiftui/concepts/viewmodifier/terms/keyboardType/keyboardType.md
> +The **`.keyboardType`** view modifier method in SwiftUI is used to specify what keyboard type from the **UIKeyboardType** enumeration to use for text entry.
```suggestion
The **`.keyboardType()`** view modifier method in SwiftUI is used to specify the keyboard type from the **UIKeyboardType** enumeration to use for text entry.
```

2023-02-22 01:33 UTC, KTom101 commented on content/swiftui/concepts/viewmodifier/terms/keyboardType/keyboardType.md
> +Description: 'Specifies what keyboard type to use for text entry.'
```suggestion
Description: 'Specifies the keyboard type to use for text entry.'
```

2023-02-22 10:57 UTC, Digital-Brendan commented
No problem! I'll add the changes right away.

2023-02-23 02:14 UTC, KTom101 approved these changes
@Digital-Brendan This looks good for a second review 👍 Please wait for another maintainer to take a look at this.

2023-02-24 17:48 UTC, SSwiniarski commented on content/swiftui/concepts/viewmodifier/terms/keyboardType/keyboardType.md
> +- `type`: One of the keyboard types defined in the **UIKeyboardType** enumeration.
```suggestion
- `type`: One of the keyboard types defined in the `UIKeyboardType` enumeration.
```

2023-02-24 17:48 UTC, SSwiniarski commented on content/swiftui/concepts/viewmodifier/terms/keyboardType/keyboardType.md
> +The following example demonstrates how to use the `.keyboardType()` method to ensure the user can only enter a correctly formatted email address:
```suggestion
The following example demonstrates how to use the `.keyboardType()` method to ensure the user can enter a correctly formatted email address:
```

2023-02-26 12:38 UTC, Digital-Brendan commented
Thanks for pointing those out @SSwiniarski ! They should be corrected now.

2023-02-26 13:52 UTC, SSwiniarski approved these changes
@Digital-Brendan, looks good for another review.

2023-02-26 13:55 UTC, merged

2023-02-26 14:02 UTC, SSwiniarski commented
@Digital-Brendan, congrats on the new entry. The live entry can be found here: https://www.codecademy.com/resources/docs/swiftui/viewmodifier/keyboardType

![image](https://user-images.githubusercontent.com/86081858/221415205-a6817058-9568-4384-9890-476e3cec5e71.png)

2023-04-12 11:41 UTC, Digital-Brendan commented
@SSwiniarski Sorry for digging this back up but I noticed I associated this with the wrong Codecademy account, meaning the contributor listed on the docs page isn't me! My codecademy account is actually `@Digital-Brendan`. Thanks

2023-04-12 16:21 UTC, SSwiniarski commented
@KTom101, @yangc95, @caupolicandiaz Any idea of what to do here?

2023-04-14 02:14 UTC, KTom101 commented
@Digital-Brendan Can you remove the GitHub username under the brendan5024346943 Codecademy account within the profile details and then relink your GitHub username to the correct account using the steps below:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

<img width="871" alt="YourGitHubName" src="https://user-images.githubusercontent.com/40783324/231923822-787a4e6d-fd91-45ce-b267-ce45d4290de4.png">

2.) Then log out and log back into Codecademy using your GitHub login:

<img width="1273" alt="ReLogIn" src="https://user-images.githubusercontent.com/40783324/231923943-8b03799d-4972-4274-8915-5cf8cfd76a92.png">

Also, please make sure that you have the email associated with the correct Codecademy account listed as one of your emails under your GitHub profile.