Cybersecurity New Topic: Cyber Resilience
Codecademy/docs pull request #1694
Opened 2023-02-21 15:28 UTC by jonchery

### Description

Added a new cybersecurity folder and concept, Cyber Resilience

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-21 15:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1694) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1694) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1694) it.</sub>

2023-02-21 17:51 UTC, SSwiniarski requested changes
@jonchery I did a first review and left a few comments, most about formatting your bulleted list.

2023-02-21 17:51 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-resilience/cyber-resilience.md
> +  - 'paths/cyber-resilience-risk-management'
```suggestion
  - 'paths/cyber-resilience-risk-management'
  - 'paths/fundamentals-of-cybersecurity'
```
Generally we want two slugs under CatalogContent

2023-02-21 17:51 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-resilience/cyber-resilience.md
> +  - 'Cybersecurity'
```suggestion
  - 'Cybersecurity'
  - 'Infrastructure'
```
We generally want more than one tag.

2023-02-21 17:51 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-resilience/cyber-resilience.md
> +- _Redundancy_ -> In Cybersecurity, redundancy refers to having alternate ways to maintain the availability of a resource.
```suggestion
- **Redundancy:** Refers to having alternate ways to maintain the availability of a resource.
```

2023-02-21 17:51 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-resilience/cyber-resilience.md
> +- _Replication_ -> In Cybersecurity, replication refers to having multiple copies of the same data available in multiple locations.
```suggestion
- **Replication:** Refers to having multiple copies of the same data available in multiple locations.
```

2023-02-21 17:51 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-resilience/cyber-resilience.md
> +- _Non-Persistence_ -> This concept refers to the ability to maintain a system’s integrity despite multiple attempts of changes by the users or attackers.
```suggestion
- **Non-Persistence:** Refers to the ability to maintain a system’s integrity despite multiple attempts of changes by the users or attackers. 
```

2023-02-21 17:51 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-resilience/cyber-resilience.md
> +- _High Availability_ ->  Refers to the assurance that a system will be available to respond to requests and complete requested operations in a timely manner.
```suggestion
- **High Availability:** Refers to the assurance that a system will be available to respond to requests and complete requested operations in a timely manner.
```

2023-02-21 17:51 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-resilience/cyber-resilience.md
> +- _Restoration Order_ -> Refers to the sequence of mission-critical business processes that should be restored.
```suggestion
- **Restoration Order:** Refers to the sequence of mission-critical business processes that should be restored. 
```

2023-02-21 17:51 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-resilience/cyber-resilience.md
> +- _Diversity_ -> Refers to the multilayered security mechanism of having different types of access control provided by different entities/products.
```suggestion
- **Diversity:** Refers to the multilayered security mechanism of having different types of access control provided by different entities/products.
```

2023-02-21 17:51 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-resilience/cyber-resilience.md
> +
In addition to the edits below, remove the line breaks between each bullet item.

2023-02-25 14:10 UTC, SSwiniarski commented
@jonchery, one more edit. Can we remove the trailing punctuation from the headers? The colon `:` will cause this to fail one of the checks.

2023-02-28 18:28 UTC, jonchery reviewed
Removing ":"

2023-03-02 23:13 UTC, caupolicandiaz reviewed
@jonchery I've completed my review, please update and tag me when you've finished making changes. Thanks

2023-03-02 23:13 UTC, caupolicandiaz commented on content/cybersecurity/concepts/cyber-resilience/cyber-resilience.md
> +- **Replication:** Refers to having multiple copies of the same data available in multiple locations.
I think this definition should be tweaked a bit to differentiate it from redundancy. I see redundancy as having multiple copies or alternative ways to provide some service. I would expect that replication is a more active process, or set of systems to reproduce data in the event of loss or failure.

2023-03-02 23:13 UTC, caupolicandiaz commented on content/cybersecurity/concepts/cyber-resilience/cyber-resilience.md
> +- **Non-Persistence:** Refers to the ability to maintain a system’s integrity despite multiple attempts of changes by the users or attackers.
```suggestion
- Non-Persistence: Refers to the ability to maintain a system’s integrity despite multiple attempts of changes by the users or attackers. 
```

2023-03-02 23:13 UTC, caupolicandiaz commented on content/cybersecurity/concepts/cyber-resilience/cyber-resilience.md
> +- **Non-Persistence:** Refers to the ability to maintain a system’s integrity despite multiple attempts of changes by the users or attackers.
I don't think this actually gets at the core of non-persistence. I understand that this strategy is about limiting the availability of access, or data, etc. I don't think that idea is represented clearly in this definition.

2023-03-02 23:13 UTC, caupolicandiaz commented on content/cybersecurity/concepts/cyber-resilience/cyber-resilience.md
> +- **High Availability:** Refers to the assurance that a system will be available to respond to requests and complete requested operations in a timely manner.
```suggestion
- High Availability: Refers to the assurance that a system will be available to respond to requests and complete requested operations in a timely manner.
```

2023-03-02 23:13 UTC, caupolicandiaz commented on content/cybersecurity/concepts/cyber-resilience/cyber-resilience.md
> +- **Restoration Order:** Refers to the sequence of mission-critical business processes that should be restored.
```suggestion
- Restoration Order: Refers to the sequence of mission-critical business processes that should be restored. 
```

2023-03-02 23:13 UTC, caupolicandiaz commented on content/cybersecurity/concepts/cyber-resilience/cyber-resilience.md
> +- **Diversity:** Refers to the multilayered security mechanism of having different types of access control provided by different entities/products.
```suggestion
- Diversity: Refers to the multilayered security mechanism of having different types of access control provided by different entities/products.
```

2023-03-21 19:26 UTC, caupolicandiaz commented
@jonchery This entry has been sitting for quite some time. Please advise if you can't continue to work on this contribution.

2023-03-23 17:02 UTC, jonchery commented
> caupolicandiaz

This got lost in my spam. Resolved the issues.

2023-03-23 20:06 UTC, caupolicandiaz approved these changes
@jonchery Looks good.

2023-03-24 17:23 UTC, merged