Cybersecurity New Topic: Risk
Codecademy/docs pull request #1697
Opened 2023-02-21 15:35 UTC by jonchery

### Description

Added new cybersecurity folder and concept, Risk

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-21 15:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1697) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1697) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1697) it.</sub>

2023-02-23 16:54 UTC, SSwiniarski requested changes
@jonchery I did a first review and only had a couple of comments.

2023-02-23 16:54 UTC, SSwiniarski commented on content/cybersecurity/concepts/risk/risk.md
> +  - 'Cybersecurity'
If we could, can we add at least one more tag?

2023-02-23 16:54 UTC, SSwiniarski commented on content/cybersecurity/concepts/risk/risk.md
> +
Remove extra line break

2023-02-23 16:54 UTC, SSwiniarski commented on content/cybersecurity/concepts/risk/risk.md
> +- NIST (National Institute of Standards and Technology): This was established by President Obama in an effort to better define and understand cyber risk. NIST is probably the most recognizable and wi
Remove the line breaks between the bullet points.

2023-02-24 18:35 UTC, jonchery reviewed
Completed request

2023-02-25 13:17 UTC, SSwiniarski approved these changes
@jonchery Looks good for a second review.

2023-02-25 14:09 UTC, SSwiniarski commented
@jonchery, one more edit. Can we remove the trailing punctuation from the headers? The colon `:` will cause this to fail one of the checks.

2023-02-28 18:26 UTC, jonchery reviewed
Removed ":"

2023-03-06 17:40 UTC, yangc95 reviewed
@jonchery I left a few comments

2023-03-06 17:40 UTC, yangc95 commented on content/cybersecurity/concepts/risk/risk.md
> +A cybersecurity framework provides a common set of standards for organizations to assess and understand their overall security postures. Here are a few of the most common cybersecurity frameworks:
```suggestion
A cybersecurity framework provides a common set of standards for organizations to assess and understand their overall security postures. Here are a few of the most common cybersecurity frameworks:

```

2023-03-06 17:40 UTC, yangc95 commented on content/cybersecurity/concepts/risk/risk.md
> +- NIST (National Institute of Standards and Technology): This was established by President Obama in an effort to better define and understand cyber risk. NIST is probably the most recognizable and wi
Do these have official sites?

2023-03-06 17:40 UTC, yangc95 commented on content/cybersecurity/concepts/risk/risk.md
> +## Risk In-Use
Can we edit the heading to better reflect the info below?

2023-03-18 18:14 UTC, SSwiniarski commented
@jonchery, in the interests of getting this merged, I applied the above edits. Once @yangc95 reviews and approves, we can merge this.

2023-03-20 22:06 UTC, merged

2023-03-20 22:10 UTC, yangc95 commented
@jonchery live link: https://www.codecademy.com/resources/docs/cybersecurity/risk

<img width="840" alt="Screenshot 2023-03-20 at 6 10 41 PM" src="https://user-images.githubusercontent.com/72277593/226476672-d640884a-8d1f-4e6f-9e24-ca1ebd055a6a.png">

cc: @SSwiniarski