Cybersecurity New Topic: Vulnerability
Codecademy/docs pull request #1702
Opened 2023-02-21 15:42 UTC by jonchery

### Description

Created a new cybersecurity folder and concept, Vulnerability.

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-21 15:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1702) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1702) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1702) it.</sub>

2023-02-23 17:38 UTC, SSwiniarski requested changes
@jonchery I did a first review and left a few comments.

2023-02-23 17:38 UTC, SSwiniarski commented on content/cybersecurity/concepts/vulnerability/vulnerability.md
> +  - 'Cybersecurity'
Can we add more tags?

2023-02-24 18:21 UTC, jonchery reviewed
Completed the requests.

2023-02-25 13:11 UTC, SSwiniarski approved these changes
@jonchery looks good for a second review.

2023-02-25 14:06 UTC, SSwiniarski commented
@jonchery, one more edit. Can we remove the trailing punctuation from the headers? The colon `:` will cause this to fail one of the checks.

2023-02-28 18:21 UTC, jonchery reviewed
Removed ':'

2023-03-06 17:37 UTC, yangc95 reviewed
@jonchery thanks for your patience, I left a few comments

2023-03-06 17:37 UTC, yangc95 commented on content/cybersecurity/concepts/vulnerability/vulnerability.md
> +Some examples of vulnerabilities include: system misconfigurations, unpatched software, poor data encryptions, weak authorization credentials. All of these are weaknesses that can be used by cybercri
Can we take the mentioned vulnerabilities and list them in bullet point format? It would be nice to have a quick explanation for each as well.

2023-03-06 17:37 UTC, yangc95 commented on content/cybersecurity/concepts/vulnerability/vulnerability.md
> +The most common way to identify and prevent vulnerabilities is through a vulnerability assessment. This essentially is a systematic review to see what, if any, vulnerabilities exist, the criticality
```suggestion
The most common way to identify and prevent vulnerabilities is through a vulnerability assessment. This is a systematic review to see what, if any, vulnerabilities exist, the criticality of them, and recommendations to remediate them if needed. A vulnerability assessment will scan the network to identify any software and configurations with vulnerabilities that have not been remediated. This type of test can generally uncover things like unpatched software, network protocols using outdated encryption, or exposed ports not protected behind a firewall.
```

2023-03-06 17:37 UTC, yangc95 commented on content/cybersecurity/concepts/vulnerability/vulnerability.md
> +## Vulnerability In-Use
I'm unsure if this heading is accurate to the info below. If you think differently I'd love to discuss

2023-03-06 17:37 UTC, yangc95 commented on content/cybersecurity/concepts/vulnerability/vulnerability.md
> +Vulnerabilities and threats are often used interchangeably, however, it is important to distinguish these terms. First, a vulnerability can make an organization susceptible to threats. A threat is a
Can this be simplified:

```suggestion
A vulnerability can make an organization susceptible to threats. A threat is a malicious event that exploits a vulnerability. More specifically, a threat is when an adversary has the opportunity, capability, and intent to negatively impact an organization’s employees, processes, or technology. Some examples of threats include malware, ransomware, and phishing attacks.
```

2023-03-25 12:25 UTC, SSwiniarski commented
@jonchery It's been over two weeks, do you need any clarification on @yangc95's comments?

2023-04-06 14:06 UTC, SSwiniarski commented
@yangc95, as @jonchery is no longer with us, I took a shot at addressing your comments myself.

2023-04-06 16:12 UTC, merged

2023-04-06 16:21 UTC, yangc95 commented
Thanks @SSwiniarski !

live link: https://www.codecademy.com/resources/docs/cybersecurity/vulnerability