Ceiling
Codecademy/docs pull request #1703
Opened 2023-02-21 17:58 UTC by M3RF3R

### Description

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-21 20:49 UTC, caupolicandiaz requested changes
@M3RF3R Finished the first review. Please tag me when you've made the updates.

2023-02-21 20:49 UTC, caupolicandiaz commented on content/c-sharp/concepts/math-functions/terms/ceiling/ceiling.md
> +**Math.Celiling()** is a class method that always rounds up to the next full integer. It is used to return the smallest integer greater than or equal to the specified number.
```suggestion
**Math.Ceiling()** is a class method that always rounds up to the next full integer. It is used to return the smallest integer greater than or equal to the specified number.
```

2023-02-21 20:49 UTC, caupolicandiaz commented on content/c-sharp/concepts/math-functions/terms/ceiling/ceiling.md
> +public static double Ceiling(double val)
```suggestion

```

2023-02-21 20:49 UTC, caupolicandiaz commented on content/c-sharp/concepts/math-functions/terms/ceiling/ceiling.md
> +public static decimal Ceiling (decimal val);
```suggestion
Math.Ceiling(val);
```

2023-02-21 20:49 UTC, caupolicandiaz commented on content/c-sharp/concepts/math-functions/terms/ceiling/ceiling.md
> +- The Ceiling method operates both functionalities in decimal and double.
```suggestion
- The method takes only one parameter, `val`, the number to be rounded (as a `decimal` or `double` type). 
```

2023-02-21 20:49 UTC, caupolicandiaz commented on content/c-sharp/concepts/math-functions/terms/ceiling/ceiling.md
> +The following example uses `Math.Ceiling(decimal)` to return the next full integer.
```suggestion
The following example uses `Math.Ceiling()` to return the next full integer.
```

2023-02-21 20:49 UTC, caupolicandiaz commented on content/c-sharp/concepts/math-functions/terms/ceiling/ceiling.md
> +## Example 1
```suggestion
## Example
```

2023-02-21 20:49 UTC, caupolicandiaz commented on content/c-sharp/concepts/math-functions/terms/ceiling/ceiling.md
> +```
I would recommend deleting the second example. For simple methods we generally only do one example unless there is some distinct functionality demonstrated by a second.

2023-02-21 20:49 UTC, caupolicandiaz commented on content/c-sharp/concepts/math-functions/terms/ceiling/ceiling.md
> +
```suggestion
```

2023-02-22 09:09 UTC, M3RF3R commented
@caupolicandiaz done! Thanks for your corrections! I wasn't sure about the double and decimal approach but all the documentation I read explained the method like this.

2023-02-22 18:27 UTC, caupolicandiaz approved these changes
@M3RF3R Looks good, this is ready for another review.

2023-02-24 17:44 UTC, SSwiniarski requested changes
@M3RF3R Looks good, I only had one comment.

2023-02-24 17:44 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/ceiling/ceiling.md
> +Description: 'Returns the smallest integer which is greater or equal to a given number.'
```suggestion
Description: 'Returns the smallest integer which is greater than or equal to a given number.'
```

2023-02-25 08:27 UTC, M3RF3R commented
@SSwiniarski I've commited the last changes but it appears that there are some errors

2023-02-25 13:55 UTC, SSwiniarski commented
@caupolicandiaz @yangc95 @HishamT @KTom101 Any idea why the last test is failing?

2023-02-25 18:42 UTC, KTom101 commented
@M3RF3R @SSwiniarski `CatlogContent` in the metadata was written with a space like this -> `Catalog Content`. That was the error, I fixed it in commit [b79e708](https://github.com/Codecademy/docs/pull/1703/commits/b79e7087c04b2e4538165d3ab0b3ded4f4d8df92).

2023-02-25 21:18 UTC, M3RF3R commented
@KTom101 Thanks a lot! I thought I had changed that!

2023-02-26 12:40 UTC, SSwiniarski approved these changes

2023-02-26 12:42 UTC, merged

2023-02-26 12:48 UTC, SSwiniarski commented
@M3RF3R Congrats on the new entry! You can find it live here: https://www.codecademy.com/resources/docs/c-sharp/math-functions/ceiling
![image](https://user-images.githubusercontent.com/86081858/221411345-5f3bb632-3794-445c-9768-10a1c0143220.png)