class.md recreated
Codecademy/docs pull request #1719
Opened 2023-02-24 14:06 UTC by Cesarcas1958

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-24 17:17 UTC, SSwiniarski requested changes
@Cesarcas1958 I did a first review and left a few comments for you.

2023-02-24 17:17 UTC, SSwiniarski commented on content/html/concepts/attributes/terms/class/class.md
> +Title: 'Classes'
```suggestion
Title: 'class'
```

2023-02-24 17:17 UTC, SSwiniarski commented on content/html/concepts/attributes/terms/class/class.md
> +Description: 'Classes are HTML attributes used to select one or more elements for the application of styling or logic.'
```suggestion
Description: 'class is a HTML attribute used to select one or more elements for the application of styling or logic.'
```

2023-02-24 17:17 UTC, SSwiniarski commented on content/html/concepts/attributes/terms/class/class.md
> +  - 'Style'
The end of the metadata is missing. There needs to be a CatalogContent: section and a concluding three dashes: `---`

Also, the extra line breaks in the metadata need to be removed.

The complete Metadata should look like this:
```
---
Title: 'The Title'
Description: 'A brief description'
Subjects:
  - 'A subject name'
  - 'A second subject name'
  - 'An nth subject name'
Tags:
  - 'A tag'
  - 'A second tag'
  - 'An nth tag'
CatalogContent:
  - 'learn-example-course'
  - 'path/example-path'
---
```

You can find entries for CatalogContent: [here](https://github.com/Codecademy/docs/blob/main/documentation/catalog-content.md).

2023-02-24 17:17 UTC, SSwiniarski commented on content/html/concepts/attributes/terms/class/class.md
> +Classes are HTML attributes used to select one or more elements for CSS styling or JavaScript purposes.
```suggestion
**`class`** is a HTML attribute used to select one or more elements for CSS styling or JavaScript purposes.
```

2023-02-24 17:17 UTC, SSwiniarski commented on content/html/concepts/attributes/terms/class/class.md
> +Below is some markup with a `title`, containing a `header-1` and `P1` and  `P2`. The styling for the `header-1 `, elements with the `P1` and `P1`class name received different styling.
```suggestion
Below is some markup with the classes `header-1` and `P1` and  `P2`. Elements with the `header-1`, `P1` and `P2` class names receive different styling.
```

2023-02-24 17:17 UTC, SSwiniarski commented on content/html/concepts/attributes/terms/class/class.md
> +The `class` attribute is used to perform JavaScript operations on HTML elements. Through the Document Object Model ("DOM"), there are various JavaScript methods built for selecting elements via their
```suggestion
The `class` attribute is used to perform JavaScript operations on HTML elements. Through the Document Object Model ("DOM") there are various JavaScript methods built for selecting elements via their class.
```

2023-02-24 17:17 UTC, SSwiniarski commented on content/html/concepts/attributes/terms/class/class.md
> +
Remove the extra line breaks

2023-02-24 17:17 UTC, SSwiniarski commented on content/html/concepts/attributes/terms/class/class.md
> +The code above is getting an element with a class property and prints it to the console
```suggestion
The code above gets an element with a class property and prints it to the console.
```

2023-02-24 17:17 UTC, SSwiniarski commented on content/html/concepts/attributes/terms/class/class.md
> +recreated on 02/24/2023 again
```suggestion
```
Remove this line.

2023-02-24 19:35 UTC, Cesarcas1958 commented
Hi,
I made the changes requested. I added and committed and pushed. Is there
anything more I should do? Is it necessary to make a new pull request? I
did not see the option

El vie, 24 feb 2023 a la(s) 13:17, SSwiniarski ***@***.***)
escribió:

> ***@***.**** requested changes on this pull request.
>
> @Cesarcas1958 <https://github.com/Cesarcas1958> I did a first review and
> left a few comments for you.
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1719#discussion_r1117331964>:
>
> > @@ -0,0 +1,86 @@
>
> +---
>
> +Title: 'Classes'
>
>
> ⬇️ Suggested change
>
> -Title: 'Classes'
>
> +Title: 'class'
>
>
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1719#discussion_r1117332420>:
>
> > @@ -0,0 +1,86 @@
>
> +---
>
> +Title: 'Classes'
>
> +
>
> +Description: 'Classes are HTML attributes used to select one or more elements for the application of styling or logic.'
>
>
> ⬇️ Suggested change
>
> -Description: 'Classes are HTML attributes used to select one or more elements for the application of styling or logic.'
>
> +Description: 'class is a HTML attribute used to select one or more elements for the application of styling or logic.'
>
>
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1719#discussion_r1117336312>:
>
> > @@ -0,0 +1,86 @@
>
> +---
>
> +Title: 'Classes'
>
> +
>
> +Description: 'Classes are HTML attributes used to select one or more elements for the application of styling or logic.'
>
> +
>
> +Subjects:
>
> +  - 'Web Development'
>
> +  - 'Web Design'
>
> +
>
> +Tags:
>
> +  - 'Attributes'
>
> +  - 'Classes'
>
> +  - 'Style'
>
>
> The end of the metadata is missing. There needs to be a CatalogContent:
> section and a concluding three dashes: ---
>
> Also, the extra line breaks in the metadata need to be removed.
>
> The complete Metadata should look like this:
>
> ---
>
> Title: 'The Title'
>
> Description: 'A brief description'
>
> Subjects:
>
>   - 'A subject name'
>
>   - 'A second subject name'
>
>   - 'An nth subject name'
>
> Tags:
>
>   - 'A tag'
>
>   - 'A second tag'
>
>   - 'An nth tag'
>
> CatalogContent:
>
>   - 'learn-example-course'
>
>   - 'path/example-path'
>
> ---
>
>
> You can find entries for CatalogContent: here
> <https://github.com/Codecademy/docs/blob/main/documentation/catalog-content.md>
> .
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1719#discussion_r1117337516>:
>
> > @@ -0,0 +1,86 @@
>
> +---
>
> +Title: 'Classes'
>
> +
>
> +Description: 'Classes are HTML attributes used to select one or more elements for the application of styling or logic.'
>
> +
>
> +Subjects:
>
> +  - 'Web Development'
>
> +  - 'Web Design'
>
> +
>
> +Tags:
>
> +  - 'Attributes'
>
> +  - 'Classes'
>
> +  - 'Style'
>
> +
>
> +Classes are HTML attributes used to select one or more elements for CSS styling or JavaScript purposes.
>
>
> ⬇️ Suggested change
>
> -Classes are HTML attributes used to select one or more elements for CSS styling or JavaScript purposes.
>
> +**`class`** is a HTML attribute used to select one or more elements for CSS styling or JavaScript purposes.
>
>
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1719#discussion_r1117340767>:
>
> > +Classes are HTML attributes used to select one or more elements for CSS styling or JavaScript purposes.
>
> +
>
> +## For Styling
>
> +
>
> +The `class` attribute is used for assigning styles to elements. Multiple classes can be assigned to a single element in a space-separated list. (e.g. `class="class1 class2 class3"`)
>
> +
>
> +Inside the stylesheet, a class name is selected with the following syntax:
>
> +
>
> +```css
>
> +.class-1 {
>
> +}
>
> +```
>
> +
>
> +A class selector is a name preceded by a period (`.`).
>
> +
>
> +Below is some markup with a `title`, containing a `header-1` and `P1` and  `P2`. The styling for the `header-1 `, elements with the `P1` and `P1`class name received different styling.
>
>
> ⬇️ Suggested change
>
> -Below is some markup with a `title`, containing a `header-1` and `P1` and  `P2`. The styling for the `header-1 `, elements with the `P1` and `P1`class name received different styling.
>
> +Below is some markup with the classes `header-1` and `P1` and  `P2`. Elements with the `header-1`, `P1` and `P2` class names receive different styling.
>
>
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1719#discussion_r1117341830>:
>
> > +
>
> +    <div class="title">
>
> +    <h1 class="header-1">PIZZA MAN HE DELIVERS</h1>
>
> +  </div>
>
> +  <!--HISTORY-->
>
> +
>
> +    <p class="P1">Pizza Man he delivers is a family-owned business since 1964. Our goal is to make the best pizza and have it delivered to your place.</p>
>
> +    <p class="P2">We have 3 locations so far and growing. </p>
>
> +    </body>
>
> +
>
> +</html>
>
> +```
>
> +
>
> +## For JavaScript
>
> +
>
> +The `class` attribute is used to perform JavaScript operations on HTML elements. Through the Document Object Model ("DOM"), there are various JavaScript methods built for selecting elements via their class.
>
>
> ⬇️ Suggested change
>
> -The `class` attribute is used to perform JavaScript operations on HTML elements. Through the Document Object Model ("DOM"), there are various JavaScript methods built for selecting elements via their class.
>
> +The `class` attribute is used to perform JavaScript operations on HTML elements. Through the Document Object Model ("DOM") there are various JavaScript methods built for selecting elements via their class.
>
>
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1719#discussion_r1117342520>:
>
> > +    </body>
>
> +
>
> +</html>
>
> +```
>
> +
>
> +## For JavaScript
>
> +
>
> +The `class` attribute is used to perform JavaScript operations on HTML elements. Through the Document Object Model ("DOM"), there are various JavaScript methods built for selecting elements via their class.
>
> +
>
> +Assuming the markup from the last example is linked to a JavaScript file:
>
> +
>
> +```js
>
> +const innerDiv = document
>
> +  .getElementsByClassName('header-1')
>
> +  console.log(innerDiv)
>
> +
>
>
> Remove the extra line breaks
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1719#discussion_r1117343183>:
>
> > +
>
> +## For JavaScript
>
> +
>
> +The `class` attribute is used to perform JavaScript operations on HTML elements. Through the Document Object Model ("DOM"), there are various JavaScript methods built for selecting elements via their class.
>
> +
>
> +Assuming the markup from the last example is linked to a JavaScript file:
>
> +
>
> +```js
>
> +const innerDiv = document
>
> +  .getElementsByClassName('header-1')
>
> +  console.log(innerDiv)
>
> +
>
> +
>
> +```
>
> +
>
> +The code above is getting an element with a class property and prints it to the console
>
>
> ⬇️ Suggested change
>
> -The code above is getting an element with a class property and prints it to the console
>
> +The code above gets an element with a class property and prints it to the console.
>
>
> ------------------------------
>
> In content/html/concepts/attributes/terms/class/class.md
> <https://github.com/Codecademy/docs/pull/1719#discussion_r1117343800>:
>
> > +
>
> +The `class` attribute is used to perform JavaScript operations on HTML elements. Through the Document Object Model ("DOM"), there are various JavaScript methods built for selecting elements via their class.
>
> +
>
>  [...]

2023-02-25 13:28 UTC, SSwiniarski commented
@Cesarcas1958 You do not need to make a new PR. All your work should be visible on this PR.

2023-02-25 13:31 UTC, SSwiniarski commented
@Cesarcas1958 You shouldn't need to make a new PR, but you need to push changes to the branch you created this PR from. It doesn't seem if you've done that.

2023-03-21 16:48 UTC, SSwiniarski requested changes
@Cesarcas1958 Sorry for the delay. I reviewed this and had two comments about things that still need to be addressed.

Tag me in a comment when you've completed the edits.

2023-03-21 16:48 UTC, SSwiniarski commented on content/html/concepts/attributes/terms/class/class.md
> +---
You still need to fix the metadata. You have extra line breaks between sections and you're missing the concluding three dashes: `---`

Again, it should look like this:

```
---
Title: 'The Title'
Description: 'A brief description'
Subjects:
  - 'A subject name'
  - 'A second subject name'
  - 'An nth subject name'
Tags:
  - 'A tag'
  - 'A second tag'
  - 'An nth tag'
CatalogContent:
  - 'learn-example-course'
  - 'path/example-path'
---
```

2023-03-21 16:48 UTC, SSwiniarski commented on content/html/concepts/attributes/terms/class/class.md
> +
You still need to remove the extra line breaks in the code block.

2023-04-18 17:06 UTC, SSwiniarski commented
@Cesarcas1958 It's been three weeks. Are you able to continue working on this?

2023-04-21 21:56 UTC, caupolicandiaz commented
@Cesarcas1958 @SSwiniarski I've made the outstanding edits to keep this entry moving along.

2023-04-22 11:29 UTC, SSwiniarski approved these changes
@Cesarcas1958 @caupolicandiaz I had one more comment, otherwise good for a second review,

2023-04-22 11:29 UTC, SSwiniarski commented on content/html/concepts/attributes/terms/class/class.md
> +The `class` attribute is used to perform JavaScript operations on HTML elements. Through the Document Object Model ("DOM") there are various JavaScript methods built for selecting elements via their
```suggestion
The `class` attribute is used to perform [JavaScript](https://www.codecademy.com/resources/docs/javascript) operations on HTML elements. Through the Document Object Model ("DOM") there are various JavaScript methods built for selecting elements via their class.
```

2023-04-22 20:17 UTC, caupolicandiaz approved these changes
@Cesarcas1958 @SSwiniarski I think this looks good to go.

2023-04-22 20:19 UTC, merged

2023-04-23 11:50 UTC, SSwiniarski commented
@Cesarcas1958 congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/html/attributes/class

![image](https://user-images.githubusercontent.com/86081858/233837947-d4efa57b-8a90-4cce-b3ed-fd73311fe698.png)

@yangc95, @KTom101 this is another one showing @caupolicandiaz as the contributor, not @Cesarcas1958. Do we know what's causing this?

2023-04-24 17:47 UTC, yangc95 commented
I think we should first rule out any configuration issues.

If @Cesarcas1958 can double check in the Codecademy profile page that the GitHub handle matches, visibility is set to everyone, and emails for both GitHub/Codecademy match. Then log back in with the GitHub option.

If this issue still persists after double-checking profiles/emails, then we'll check for other potential causes.