added to kotlin hashmap docs information about accessing and adding items
Codecademy/docs pull request #1728
Opened 2023-02-26 18:07 UTC by shdsgm

…tems

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-26 18:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1728) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1728) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1728) it.</sub>

2023-02-26 19:56 UTC, SSwiniarski requested changes
@shdsgm I did a first review and left a few comments.

2023-02-26 19:56 UTC, SSwiniarski commented on content/kotlin/concepts/hashmap/hashmap.md
> +To access an item in a `HashMap`, you can use the indexing operator [] with the key of the desired value. If the key exists in the hashmap, the indexing operator will return the corresponding value.
```suggestion
To access an item in a `HashMap`, the indexing operator [] is used with the key of the desired value. If the key exists in the hashmap, the indexing operator will return the corresponding value. If the key does not exist in the hashmap, the indexing operator will return null.
```

2023-02-26 19:56 UTC, SSwiniarski commented on content/kotlin/concepts/hashmap/hashmap.md
> +You can also use the get(key) method to access the value associated with a specific key. This method returns the value associated with the key if it exists in the hashmap, or null if it does not.
```suggestion
You can also use the `.get(key)` method to access the value associated with a specific key. This method returns the value associated with the key if it exists in the hashmap, or null if it does not.
```

2023-02-26 19:56 UTC, SSwiniarski commented on content/kotlin/concepts/hashmap/hashmap.md
> +To add an item to a hashmap, you can use the put(key, value) method. This method adds a new key-value pair to the hashmap. If the key already exists in the hashmap, the value associated with the key
```suggestion
To add an item to a hashmap, you can use the `.put(key, value)` method. This method adds a new key-value pair to the hashmap. If the key already exists in the hashmap, the value associated with the key is updated.
```

2023-02-26 19:56 UTC, SSwiniarski commented on content/kotlin/concepts/hashmap/hashmap.md
> +You can also use the indexing operator [] to add a new key-value pair to the hashmap. This method is useful if you want to add a new item to the hashmap and you do not know if the key already exists.
```suggestion
You can also use the indexing operator `[]` to add a new key-value pair to the hashmap. This method is useful if you want to add a new item to the hashmap and you do not know if the key already exists.
```

2023-02-26 19:56 UTC, SSwiniarski commented on content/kotlin/concepts/hashmap/hashmap.md
> +Let's print the capital cities of the countries:
```suggestion
The following prints the capital cities of the countries:
```

2023-03-22 16:27 UTC, SSwiniarski commented
@shdsgm, It's been over two weeks, do you need assistance in completing the edits above?

2023-03-23 23:47 UTC, shdsgm commented
@SSwiniarski Hi! I'm sorry, thought that you made these changes. Now i understand that i need to do the changes myself in my branch and push again. I'll do it tomorrow. Also there are two failing test, can you please give advise how can i fix them. Sorry again for my mistake.

2023-04-06 14:26 UTC, SSwiniarski commented
@shdsgm It's been two weeks, are you still working on this? The comments above still need to be addressed.

2023-04-13 11:40 UTC, shdsgm commented
Hi! I'm still working on this, have some troubles with prettier module

2023-04-13 16:16 UTC, SSwiniarski commented
@shdsgm do you need assistance, are you working on the other edits?

2023-04-13 23:57 UTC, shdsgm reviewed
added changes from the first review

2023-04-14 16:18 UTC, SSwiniarski approved these changes
@shdsgm Looks good for another review.

2023-04-14 23:24 UTC, caupolicandiaz approved these changes
@shdsgm LGTM. I just added a couple of small corrections to the tags and the hash map link in the description.

2023-04-14 23:25 UTC, merged

2023-04-15 22:55 UTC, KTom101 commented
Link to entry that was edited: https://www.codecademy.com/resources/docs/kotlin/hashmap

@shdsgm I noticed you're not listed as a contributor. If you wish to remain anonymous there is nothing you have to do. Otherwise, you can follow the instructions below to be listed as a contributor:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

<img width="871" alt="YourGitHubName" src="https://user-images.githubusercontent.com/40783324/232256319-5d0b7916-8066-4e6e-b657-479361342fde.png">

2.) Then log out and log back into Codecademy using your GitHub login:

<img width="1273" alt="ReLogIn" src="https://user-images.githubusercontent.com/40783324/232256334-226aa6b0-0987-4f70-a565-2561cb21ee77.png">

> **Note:**  If your email associated with your Codecademy account is different from your GitHub emails, your Codecademy account email needs to be added to the emails in your GitHub settings. If you use the same email for both GitHub and Codecademy already, then you're set.

cc @yangc95