Mybranch #1736
Codecademy/docs pull request #1737
Opened 2023-02-28 08:11 UTC by japhet40

### Description

Python Time Module: .sleep() #1736

### Type of Change

Fix grammar, spelling, formatting

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-02-28 17:12 UTC, SSwiniarski commented
@japhet40, It seems you've gone beyond the scope of the Issue and replaced the whole sleep.md file, which is resulting in a conflict so we cannot merge. Can you replace the original sleep.md file and make the edits as requested?

2023-03-11 15:38 UTC, SSwiniarski commented
@japhet40 It's been two weeks. Let us know if you're intending to address the issues with this PR. If not we'll have to close this and unassign the issue in question.

2023-03-14 15:57 UTC, japhet40 commented
> @japhet40, It seems you've gone beyond the scope of the Issue and replaced the whole sleep.md file, which is resulting in a conflict so we cannot merge. Can you replace the original sleep.md file and make the edits as requested?

Is sleep.md suppose to be in this location /docs/content/python/concepts/time-module/terms/sleep ? This is where i have the file with the changes or do i have it all wrong?

2023-03-14 16:54 UTC, SSwiniarski commented
@japhet40 the file is in the right place. But the changes you made resulted in a conflict. I can resolve the conflicts and you can apply edits again, if that's all right.

2023-03-18 06:28 UTC, japhet40 commented
> @japhet40 the file is in the right place. But the changes you made resulted in a conflict. I can resolve the conflicts and you can apply edits again, if that's all right.

ok sounds good if you can resolve the conflict then i will make the edits again once the conflict has been resolved.

2023-03-18 14:36 UTC, SSwiniarski commented
@japhet40 I fixed the conflicts and adjusted the PR so it matches the issue being presented. As is it looks ready to merge.

2023-03-18 14:37 UTC, SSwiniarski requested changes
@japhet40 One more change. Can you remove the extra image file from this PR?

2023-03-18 14:37 UTC, SSwiniarski commented on media/sleepimage.png
Remove this unused file.

2023-03-21 16:28 UTC, japhet40 commented on media/sleepimage.png
File removed

2023-03-21 16:51 UTC, SSwiniarski commented
@japhet40 the image file is still appearing in this PR. Have you committed the changes to your branch?

2023-03-22 17:51 UTC, japhet40 commented
> @japhet40 the image file is still appearing in this PR. Have you committed the changes to your branch?

Yes i just committed the changes to my branch .

2023-03-23 15:31 UTC, SSwiniarski commented
@japhet40 The file is still appearing in this PR. Are you sure you removed it from your branch?

2023-03-26 15:19 UTC, SSwiniarski commented
@japhet40 I went ahead and deleted the file so we can move on to a second review.

2023-03-27 23:29 UTC, caupolicandiaz approved these changes
@japhet40 @SSwiniarski LGTM Just added a couple of minor edits

2023-03-28 16:42 UTC, SSwiniarski approved these changes

2023-03-28 16:44 UTC, merged

2023-03-28 16:47 UTC, SSwiniarski commented
@japhet40 Congrats on your entry. Live link is here: https://www.codecademy.com/resources/docs/python/time-module/sleep