Added documentation for matplotlib.pyplot.scatter()
Codecademy/docs pull request #1755
Opened 2023-03-02 15:50 UTC by alekseymor

### Description

Added documentation for the scatter() function of matplotlib library.
Closes #1662 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-02 15:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1755) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1755) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1755) it.</sub>

2023-03-02 17:31 UTC, SSwiniarski requested changes
@alekseymor I did a first review and found this a pretty solid entry. My comments are mostly typos and a few formatting issues.

2023-03-02 17:31 UTC, SSwiniarski commented on content/matplotlib/concepts/pyplot/terms/scatter/scatter.md
> +Title: '.scatter()
```suggestion
Title: '.scatter()'
```

2023-03-02 17:31 UTC, SSwiniarski commented on content/matplotlib/concepts/pyplot/terms/scatter/scatter.md
> + - ' Libraries'
```suggestion
 - 'Libraries'
```

2023-03-02 17:31 UTC, SSwiniarski commented on content/matplotlib/concepts/pyplot/terms/scatter/scatter.md
> +Output:
```suggestion

Output:

```
Added line breaks

2023-03-02 17:31 UTC, SSwiniarski commented on content/matplotlib/concepts/pyplot/terms/scatter/scatter.md
> +Output:
```suggestion
Output:

```
Added line break.

2023-03-02 17:31 UTC, SSwiniarski commented on content/matplotlib/concepts/pyplot/terms/scatter/scatter.md
> +## Example
```suggestion
## Examples
```

2023-03-03 23:21 UTC, caupolicandiaz requested changes
@alekseymor I've added my comments. Please update and tag me when you've finished making changes. Thanks

2023-03-03 23:21 UTC, caupolicandiaz commented on content/matplotlib/concepts/pyplot/terms/scatter/scatter.md
> +- `norm`: Normalization method used to scale scalar data to the [0, 1] range before mapping. Linear scaling is default.
```suggestion
- `norm`: Normalization method used to scale scalar data to a range (0 to 1) before mapping. Linear scaling is default.
```

2023-03-03 23:21 UTC, caupolicandiaz commented on content/matplotlib/concepts/pyplot/terms/scatter/scatter.md
> +- `vmin` and `vmax`: Define the data range that the colormap covers (if norm is not specified).
```suggestion
- `vmin` and `vmax`: Sets the data range for the colormap (if norm is not specified).
```

2023-03-03 23:21 UTC, caupolicandiaz commented on content/matplotlib/concepts/pyplot/terms/scatter/scatter.md
> +- `vmin` and `vmax`: Define the data range that the colormap covers (if norm is not specified).
Please be careful not repurpose descriptions in other documentation. All entry content should be original.

2023-03-03 23:21 UTC, caupolicandiaz commented on content/matplotlib/concepts/pyplot/terms/scatter/scatter.md
> +- `alpha`: Marker blending value, between 0 (transparent) and 1 (opaque).
```suggestion
- `alpha`: Sets the transparency value of markers (0: transparent, 1: opaque).
```

2023-03-03 23:21 UTC, caupolicandiaz commented on content/matplotlib/concepts/pyplot/terms/scatter/scatter.md
> +- `linewidths`: The linewidth of the marker edge.
```suggestion
- `linewidths`: Sets the linewidth of the marker edge.
```

2023-03-03 23:21 UTC, caupolicandiaz commented on content/matplotlib/concepts/pyplot/terms/scatter/scatter.md
> +- `edgecolors`: The edge color of the marker.
```suggestion
- `edgecolors`: Sets the edge color of the marker.
```

2023-03-05 16:25 UTC, alekseymor commented
Thanks for the feedback @caupolicandiaz. I've made the changes you requested. Back to you :)

2023-03-05 20:37 UTC, caupolicandiaz approved these changes
@alekseymor Looks good.

2023-03-06 12:23 UTC, merged

2023-03-06 13:32 UTC, SSwiniarski commented
@alekseymor Congrats on your new contribution. The live link is here:https://www.codecademy.com/resources/docs/matplotlib/pyplot/scatter

You're currently listed as an anonymous contributor. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.
![image](https://user-images.githubusercontent.com/86081858/223124225-a8b1d39d-6419-4d10-a9cb-d8b9fc3cdedd.png)

To add your GitHub username to your Codecademy profile:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
![image](https://user-images.githubusercontent.com/86081858/223124362-7d3d190d-7414-42f9-89ec-6f7fe5458804.png)

2.) Then log out and log back into Codecademy using your GitHub login:
![image](https://user-images.githubusercontent.com/86081858/223124457-0b07c73a-342d-46f4-a92c-04eb7d00fc5b.png)