create intern() string method definition
Codecademy/docs pull request #1760
Opened 2023-03-03 16:48 UTC by redpepper-nag

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-03 16:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1760) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1760) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1760) it.</sub>

2023-03-04 14:03 UTC, SSwiniarski requested changes
@redpepper-nag I did a first review and left several comments. I may have more after you make these changes. You also need to sign the [CLA](https://cla-assistant.io/Codecademy/docs?pullRequest=1760).

2023-03-04 14:03 UTC, SSwiniarski commented on content/java/concepts/strings/terms/intern/intern.md
> +String st3 = st1.intern(); // returns string same as st2
```suggestion
String st3 = st2.intern(); // returns string same as st2
```

2023-03-16 07:35 UTC, KTom101 commented
@redpepper-nag I've noticed it's been some time since the 1st review. Is there anything I can help with?

2023-03-22 16:35 UTC, SSwiniarski commented
@redpepper-nag, if we don't hear from you in a week we'll need to close this PR and re-open the issue so someone else can work on it.

2023-03-29 17:11 UTC, SSwiniarski commented
@redpepper-nag we're closing this as abandoned.

2023-03-29 17:11 UTC, closed without merging