Pull Request for Adding Content to C#
Codecademy/docs pull request #1761
Opened 2023-03-04 01:23 UTC by d-glennon

### Description
Hi there! I've created content for the Array.Copy() as part of my Git learning experience on Codecademy. 
Having been working on the C# coding , I thought this would be a good first attempt at navigating the GitHub world in real life!
Personally, I'm a little unsure on how to reference Microsoft's .NET platform in this but I've done what I could. This was quite challenging and I'm sure my inexperience shows but I welcome any feedback or suggestions. Thanks! D
### Type of Change
- Adding a new entry
### Checklist
- [ x] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-04 01:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1761) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1761) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1761) it.</sub>

2023-03-04 14:29 UTC, SSwiniarski requested changes
@d-glennon I did a first review and left a series of comments. Most are formatting issues.

2023-03-04 14:29 UTC, SSwiniarski commented on .vs/VSWorkspaceState.json
> +{
The following files must be removed from this PR:

.vs/VSWorkspaceState.json
.vs/docs/FileContentIndex/426e5a15-bb6a-42d5-a75e-f8f1f1c0d89b.vsidx
.vs/docs/FileContentIndex/4344c5be-b400-4bd6-b8a5-e31f8673206a.vsidx
.vs/docs/FileContentIndex/71177040-e0e0-4bdf-b4d1-74cf433ef051.vsidx
.vs/docs/FileContentIndex/ecf4d5c5-c83d-4472-9b5a-7eb80d2ed8a7.vsidx
.vs/docs/FileContentIndex/read.lock
.vs/docs/v17/.wsuo
.vs/docs/v17/workspaceFileList.bin
.vs/slnx.sqlite

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +`.Copy()` is a static method of the `Array` object. It takes the arguments `sourceArray`,
```suggestion

`.Copy()` is a static method of the `Array` object. It takes the arguments `sourceArray`, 
```
insert line break after coe block.

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +```
This should be a ` ```pseudo ` code block.

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +The `sourceArray` is copied, starting from the first element of the array,
```suggestion

The `sourceArray` is copied, starting from the first element of the array, 
```

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +to the `destinationArray` which also starts from its first element. It is possible to _overload_
Remove the link to off-site documentation.

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +### Syntax
```suggestion
## Syntax
```

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +### Example
```suggestion

## Example

```
h2 and line break before and after header.

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +```
Needs line break before and should be a ` ```cs ` code block.

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +                                    //sourceArray.Length returns the integer for the third parameter, length.
```suggestion
    //sourceArray.Length returns the integer for the third parameter, length. 
```

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +```
This should be a ` ```shell ` block.

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +
```suggestion
```
remove extra line break.

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +### Codebyte Example
```suggestion
## Codebyte Example

```
h2 and line break after header.

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +`sourceArray` is copied starting from the third element in the array **[2]**
```suggestion
`sourceArray` is copied starting from the third element in the array `[2]`
```

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +and stores elements **[2]**, **[3]**, **[4]** starting as the first element in `destinationArray`.
```suggestion
and stores elements `[2]`, `[3]`, `[4]` starting as the first element in `destinationArray`.
```

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +The remaining elements return **0**:
```suggestion
The remaining elements return `0`:  

```
Also line break before code block.

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +```
To be a codebyte, it needs to be prefaced with ` ```codebyte/csharp `

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +This is what is printed to the console:
```suggestion

This is what is printed to the console:

```
Line breaks before and after code blocks.

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +This is what is printed to the console:
```suggestion

This is what is printed to the console:

```
Line breaks before and after code blocks.

2023-03-04 14:29 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +```
This should be a ` ```shell ` block.

2023-03-06 12:14 UTC, SSwiniarski requested changes
@d-glennon I had a couple more comments.

2023-03-06 12:14 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +this method with multiple parameters and you can learn
```suggestion
this method with multiple parameters.
```

2023-03-06 12:14 UTC, SSwiniarski commented on content/c-sharp/concepts/arrays/terms/copy/copy.md
> +more from Microsoft's online .NET documentation.
```suggestion
```

2023-03-06 17:08 UTC, SSwiniarski approved these changes
@d-glennon, looks good for a second review

2023-03-20 00:18 UTC, yangc95 approved these changes
Thanks for your patience! I made the appropriate additions to speed up this PR. Looks good to merge now.
See https://github.com/Codecademy/docs/pull/1761/commits/ceabe24eeeb8d7018d01154212eb3680c9ec3c06 for specific changes that were made. TY

2023-03-20 00:24 UTC, merged

2023-03-20 00:26 UTC, yangc95 commented
@d-glennon here's the live link: https://www.codecademy.com/resources/docs/c-sharp/arrays/copy

<img width="861" alt="Screenshot 2023-03-19 at 8 25 41 PM" src="https://user-images.githubusercontent.com/72277593/226219990-103e2b01-f142-4635-bfb9-46d5673d4dcf.png">

> It looks as if you're anonymous. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.
> 
> To add your GitHub username to your Codecademy profile:
> 
> 1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
> 
> ![image](https://user-images.githubusercontent.com/86081858/220699030-55a1ef72-d1d1-40ab-942a-9e34ba4dbb13.png)
> 
> 2.) Then log out and log back into Codecademy using your GitHub login:
> 
> <img width="976" alt="githublogin" src="https://user-images.githubusercontent.com/72277593/221382073-53f7e2ed-5e39-4eb4-a993-b54a07ce72f6.png">
>
> If the steps above do not work, it may be due to an email or local configuration issue.
>
> In addition, we may reach out in the future if any adjustments to these entries are required.

cc: @SSwiniarski @KTom101