Add code-blocks.md
Codecademy/docs pull request #1781
Opened 2023-03-07 10:34 UTC by fuchenshi

### Description

Added an entry explaining the usage of code blocks in Markdown.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-07 10:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1781) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1781) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1781) it.</sub>

2023-03-08 17:10 UTC, SSwiniarski approved these changes
@fuchenshi, I did a first review and this looks good as is. Ready for a second review.

2023-03-10 22:41 UTC, caupolicandiaz requested changes
@fuchenshi Just a few minor edits. Please tag me when you've updated the entry.

2023-03-10 22:41 UTC, caupolicandiaz commented on content/markdown/concepts/code-blocks/code-blocks.md
> +  - 'GitHub'
```suggestion
  - 'GitHub'
  - 'Documentation' 
```

2023-03-10 22:41 UTC, caupolicandiaz commented on content/markdown/concepts/code-blocks/code-blocks.md
> +Description: 'Code blocks can be used to hold multiple lines of code. They preserve formatting and provide syntax highlighting when possible.'
```suggestion
Description: 'Code blocks can be used to display multiple lines of code. They preserve formatting and provide syntax highlighting when possible.'
```

2023-03-10 22:41 UTC, caupolicandiaz commented on content/markdown/concepts/code-blocks/code-blocks.md
> +Code blocks can be used to hold multiple lines of code. They preserve formatting and provide syntax highlighting when possible.
```suggestion
Code blocks can be used to display multiple lines of code. They preserve formatting and provide syntax highlighting when possible.
```

2023-03-11 01:51 UTC, fuchenshi commented
@caupolicandiaz Thanks for the review! I've applied your suggestions to the file.

2023-03-11 20:40 UTC, caupolicandiaz approved these changes
@fuchenshi Looks good.

2023-03-21 16:55 UTC, merged

2023-03-21 17:02 UTC, yangc95 commented
Congrats on this entry @fuchenshi here's the live link: https://www.codecademy.com/resources/docs/markdown/code-blocks

<img width="837" alt="Screenshot 2023-03-21 at 1 01 00 PM" src="https://user-images.githubusercontent.com/72277593/226685736-33c04f5b-7647-4d39-9a1f-e85caa2fae5e.png">

> It looks as if you're anonymous. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.
> 
> To add your GitHub username to your Codecademy profile:
> 
> 1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
> 
> ![image](https://user-images.githubusercontent.com/86081858/220699030-55a1ef72-d1d1-40ab-942a-9e34ba4dbb13.png)
> 
> 2.) Then log out and log back into Codecademy using your GitHub login:
> 
> <img width="976" alt="githublogin" src="https://user-images.githubusercontent.com/72277593/221382073-53f7e2ed-5e39-4eb4-a993-b54a07ce72f6.png">
>
> If the steps above do not work, it may be due to an email or local configuration issue.
>
> In addition, we may reach out in the future if any adjustments to these entries are required.

cc: @caupolicandiaz @SSwiniarski