adding C# switch article
Codecademy/docs pull request #1788
Opened 2023-03-10 22:54 UTC by kylestarr

### Description

I'm adding the topic of C# Switch Statements, file `/content/c-sharp/concepts/switch/switch.md`. I am currently enrolled in the iOS Developer Career Path. Contributing to the Codecademy Docs Repository is part of the curriculum.

Closes: #1733 

### Type of Change

- Adding a new entry

### Checklist

- [ x ] All writings are my own.
- [ x ] My entry follows the Codecademy Docs style guide.
- [ x ] My changes generate no new warnings.
- [ x ] I have performed a self-review of my own writing and code.
- [ x ] I have checked my entry and corrected any misspellings.
- [ x ] I have made corresponding changes to the documentation if needed.
- [ x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-10 22:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1788) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1788) before we can accept your contribution.<br/><hr/>**Kyle Starr** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1788) it.</sub>

2023-03-11 00:19 UTC, caupolicandiaz requested changes
@kylestarr I've completed my initial review. Please update the entry and tag me when you've finished making changes. Thanks

2023-03-11 00:19 UTC, caupolicandiaz commented on content/c-sharp/concepts/switch/switch.md
> +// Output: "Does machines!"
```suggestion
using System;

public class Example
{
  public static void Main(string[] args)
  {
  string favoriteTurtle = "Donatello";

  switch (favoriteTurtle) 
  {
    case "Leonardo":
      Console.WriteLine("Leads!");
      break;
    case "Donatello":
      Console.WriteLine("Does machines!");
      break;
    case "Raphael":
      Console.WriteLine("Cool, but rude!");
      break;
    case "Michelangelo":
      Console.WriteLine("Party dude!");
      break;
    default:
      Console.WriteLine($"{favoriteTurtle} sounds cool, but I'll bet they're not a ninja!");
      break;
  }
 }
}

// Output: "Does machines!"
```

2023-03-11 00:42 UTC, kylestarr commented on content/c-sharp/concepts/switch/switch.md
> +- `break` (recommended): Terminates the switch statement. Recommended at the end of each `case` and `default`. I.e. Once the code block within a `case` has been executed, terminate the `switch` state
@caupolicandiaz As I understand, leaving out a `break` statement in C# will result in a compile time error. Is this OK?

2023-03-11 15:00 UTC, SSwiniarski commented
@kylestarr please note that the email used for this commit is not attached to your GitHub account. (See the CLA notice above. Adding the e-mail to your GitHub account should resolve the issue.

2023-03-11 22:42 UTC, caupolicandiaz requested changes
@kylestarr Tag me when you finish making changes. Thanks

2023-03-11 22:42 UTC, caupolicandiaz commented on content/c-sharp/concepts/switch/switch.md
> +- `break` (recommended): Terminates the switch statement. Recommended at the end of each `case` and `default`. I.e. Once the code block within a `case` has been executed, terminate the `switch` state
I think it's fair to keep the original "recommended" assertion. But, I think the original text was not expansive enough. It did not suggest that there are multiple ways of moving through cases. Feel free to further revise the text if you feel there is additional information, or better phrasing, to aid in explaining the functionality and outcomes of these statements.

2023-03-12 17:54 UTC, kylestarr commented
> @kylestarr please note that the email used for this commit is not attached to your GitHub account. (See the CLA notice above. Adding the e-mail to your GitHub account should resolve the issue.

@SSwiniarski Unfortunately, the original commit was done with an email I cannot link to my personal GitHub account, nor can/should I change the email address. I believe I will need to create a new PR from a different machine. I can close this PR and open a new one with @caupolicandiaz's changes incorporated.

2023-03-12 17:54 UTC, closed without merging