Greetings. I've been doing new entry into pandas function .to_datetime(). Here's what I've got, please let me know if it's correct. Sorry for trouble that could occure but there is no much mine experience on that 😔
Codecademy/docs pull request #1790
Opened 2023-03-11 15:00 UTC by BartekKruczek

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-11 15:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1790) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1790) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1790) it.</sub>

2023-03-11 15:28 UTC, SSwiniarski commented
@BartekKruczek There are several problems with this entry that need to be addressed before it is reviewed:

1. The file is not in the proper location, nor does it have the proper filename. You need to move the file to `content/pandas/built-in-functions/to-datetime/to-datetime.md` as specified in the issue this is addressing.
2. You need to remove the empty file from your PR.
3. You need to have a proper metadata section at the head of your entry. Instructions on what this contains and how it is formatted are located in the [style guide section on metadata](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#metadata).
4. You need to format headers properly in Markdown. No boldface `**...**`. You precede headers by one `#` for each level. Entries do not have an top level header (the Title: in the metadata handles that) and you should only use h2 headers. (`##`). More information on using headers can be found in the [style guide under headers](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#headerssections).
5. Your Markdown table is incorrectly formatted. You can find instructions on constructing a table in the [Curriculum Markdown Style Guide.](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/)
6. Look at the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md) in the documentation to get an idea of how a basic term entry is structured. 

You are encouraged to look at the source for existing term entries to get an idea about how they are formatted. [`.read-csv()`](https://github.com/Codecademy/docs/blob/main/content/pandas/concepts/built-in-functions/terms/read-csv/read-csv.md) is a good one to look at.

In addition, I am going to edit the title of this PR to be a little less verbose.

2023-03-25 14:52 UTC, SSwiniarski commented
@BartekKruczek It's been two weeks. Are you still intending to work on this entry? Do you need more assistance?

2023-03-25 19:53 UTC, BartekKruczek commented
Yes, I am working on it. Much sorry for the delay caused by deadlines at the University. Could you give me few days more, please?

2023-04-01 18:45 UTC, BartekKruczek commented
Hi, the task is almost done. I've got problem with CLAs link, the text of the website is not loading (guess some internet or server issue). Is the another way of checking if I am signed in despite checking web status over time?

2023-04-02 13:18 UTC, SSwiniarski commented
@BartekKruczek no, you have to sign the CLA using the link. Try again later.

2023-04-06 14:45 UTC, SSwiniarski requested changes
@BartekKruczek I did a first review and left some comments. I may have more once these are addressed. Most important is you need to remove the files `New entry.md` and `new-entry,py` from this PR, and you need to add a proper metadata section to your entry. Also, in addition to my comments below, make sure there is one line break before and after each header and before and after each code block (and no more than one line break in a row).

Also tag me in a comment once you've completed addressing these issues.

2023-04-06 14:45 UTC, SSwiniarski commented on New entry.md
Remove this file.

2023-04-06 14:45 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +Output: `DatetimeIndex(['2039-11-09'], dtype='datetime64[ns]', freq=None)`
This should be in its own ` ```shell ` code block like this:

````
This example results in the following output:

```shell
DatetimeIndex(['2039-11-09'], dtype='datetime64[ns]', freq=None)
```
````

2023-04-07 13:57 UTC, BartekKruczek reviewed
Thank you for more info!

2023-04-07 17:27 UTC, SSwiniarski requested changes
@BartekKruczek I did another review and left some comments. Most important, you still need to add the metadata to your entry. You also added a bunch of extra files to this PR that need to be removed.

2023-04-07 17:27 UTC, SSwiniarski commented on .idea/.gitignore
Remove this file from the PR.

2023-04-07 17:27 UTC, SSwiniarski commented on .idea/codecademy_practice_docs.iml
Remove this file from the PR.

2023-04-07 17:27 UTC, SSwiniarski commented on .idea/inspectionProfiles/Project_Default.xml
Remove this file from the PR.

2023-04-07 17:27 UTC, SSwiniarski commented on .idea/inspectionProfiles/profiles_settings.xml
Remove this file from the PR.

2023-04-07 17:27 UTC, SSwiniarski commented on .idea/misc.xml
Remove this file from the PR.

2023-04-07 17:27 UTC, SSwiniarski commented on .idea/modules.xml
Remove this file from the PR.

2023-04-07 17:27 UTC, SSwiniarski commented on .idea/vcs.xml
Remove this file from the PR.

2023-04-07 17:27 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
You are still missing the metadata. There needs to be a metadata section at the start of your entry. Please follow this link: https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#metadata and read the instructions there about adding the metadata to your entry.

2023-04-07 17:27 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +# to_datetime()
Remove the first header `# to_datetime()` the title of the entry will be provided by the metadata, whiach you still need to add.

2023-04-07 17:27 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +## Syntax
```suggestion
## Syntax

```
line break before and after headers

2023-04-07 17:27 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +This function can be used via pandas library. It returns us structure in datetime format. We can use various input arguments as showned and described below.
```suggestion
This function can be used via the Pandas library. It returns a value in datetime format. Various input arguments can be used as shown and described below.

```
line break before and after code blocks

2023-04-07 17:27 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +## Example
```suggestion
## Example

```
line break before and after headers

2023-04-07 17:27 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +First section of the following code shows us how to import needed library and how to create list of string. After that, it calls our function and prints results into console.
```suggestion
First section of the following code shows how to import the needed library and how to create list of string. After that, it calls the `.to_datetime()` function and prints results onto the console.

```
line break before and after code blocks

2023-04-07 17:27 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +The following output will be showned:
```suggestion

This example results in the following output:

```

2023-04-08 17:57 UTC, SSwiniarski commented
@BartekKruczek You still don't seem to understand the metadata section. It needs to look like this:

```
---
Title: 'The Title'
Description: 'A brief description'
Subjects:
  - 'A subject name'
  - 'A second subject name'
  - 'An nth subject name'
Tags:
  - 'A tag'
  - 'A second tag'
  - 'An nth tag'
CatalogContent:
  - 'learn-example-course'
  - 'path/example-path'
---
```

You need to provide entries for each section of the metadata. 

This is what it says in the style guide about writing the metadata:
- The metadata starts on the first line of the entry.
- The metadata begins and ends with three dashes (`---`) on their own line.
- There should be a line-break after the last line of the metadata.
- There should not be extra line breaks within the metadata.
- The data for `Title:` and `Description:` appear as single-quoted strings on the same line.
- Do not use apostrophes or quotes in `Title:` or `Description:`.
- Do not use boldface or italics in `Title:` or `Description:`.
- `Description:` should be short, typically one sentence.
- `Description:` should be repeated in the introductory paragraph of the entry, i.e., The information in `Description:` should appear in the introduction to the entry.
- `Description:` for a coding term should begin with a present-tense verb, i.e., "Returns", "Calculates", "Outputs", etc.
- `CatalogContent:` appears without spaces.
- The items for `Subjects:`, `Tags:`, and `CatalogContent:` appear as bulleted lists of single-quoted strings, starting on the next line.
- The items for `Subjects:`, `Tags:`, and `CatalogContent:` are indented two spaces before the dash.
- For `Subjects:`
  - Items are languages and technical fields that the entry relates to.
  - Items come from [this list](https://github.com/Codecademy/docs/blob/main/documentation/subjects.md).
  - Should have one to two items. Always at least one.
- For `Tags:`
  - Items are key words that are relevant to the entry.
  - Items come from [this list](https://github.com/Codecademy/docs/blob/main/documentation/tags.md).
  - Should have three to four items.
  - If you wish to use a new tag, add it in the appropriate place (alphabetical order) in the [tags.md](https://github.com/Codecademy/docs/blob/main/documentation/tags.md) file as part of your PR.
- For `CatalogContent:`
  - Items are slugs of Codecademy courses and path landing pages that relate to the entry.
  - For items, use [this document](https://github.com/Codecademy/docs/blob/main/documentation/catalog-content.md) as a guide.
  - Should have two items.

2023-04-08 18:00 UTC, SSwiniarski commented
@BartekKruczek you also still need to remove those extra files.

2023-04-12 11:21 UTC, BartekKruczek commented
Ok, thank you. I was wrong, I thought (in metadata section) that I am forced to do it in another way. I see it now, I will fix it in a minute. Please tell me, removing files via git bash is better that trying to do it manually, or it has no difference?

2023-04-12 16:25 UTC, SSwiniarski commented
@BartekKruczek either way should work for the rest of those extra files.

2023-04-13 15:08 UTC, BartekKruczek commented
I deleted them, is everything all right now?

2023-04-13 15:52 UTC, SSwiniarski requested changes
@BartekKruczek I left some more comments. I think you misunderstood what I meant by "line break". Line break simply means the empty line between paragraphs and headers.

2023-04-13 15:52 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```suggestion
```
remove this

2023-04-13 15:52 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +
```suggestion
```
remove extra line break

2023-04-13 15:52 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```suggestion
```
remove this

2023-04-13 15:52 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +
```suggestion
```
remove extra line break

2023-04-13 15:52 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```suggestion
```
remove this

2023-04-13 15:52 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +
```suggestion
```
remove extra line break

2023-04-13 15:52 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```suggestion
```
remove this

2023-04-13 15:52 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +
```suggestion
```
remove extra line break

2023-04-14 16:27 UTC, SSwiniarski requested changes
@BartekKruczek I have a few more comments.

2023-04-14 16:27 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +The **to_datetime()** function in the Pandas library of Python. It reads a string (or another) representation of a **date** and **time** to a **datetime object**.
```suggestion
The **`to_datetime()`** function in the Pandas library of Python reads a string (or another) representation of a date and time into a datetime object.
```

2023-04-14 16:27 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +This function can be used via the Pandas library. It returns a value in datetime format. Various input arguments can be used as shown and described below.
```suggestion
This function returns a value in datetime format. Various input arguments can be used as shown and described below.
```

2023-04-14 16:27 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +| dayfirst | bool (default False) | if Trie is selected, the day will be given first |
```suggestion
| dayfirst | bool (default False) | if `True` is selected, the day will be given first |
```

2023-04-14 16:27 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +| yearfirst | bool (default True) | if True is selected, the year will be given first. If dayfirst and yearfirst is True, yearfirst is more important |
```suggestion
| yearfirst | bool (default True) | if `True` is selected, the year will be given first. If `dayfirst` and `yearfirst` is `True`, `yearfirst` is more important |
```

2023-04-14 16:27 UTC, SSwiniarski commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +| infer_datetime_format | bool (default False) | whenever True is selected, datetime string format is based on NaN element
```suggestion
| infer_datetime_format | bool (default False) | whenever `True` is selected, datetime string format is based on `NaN` element
```

2023-04-18 12:26 UTC, SSwiniarski approved these changes
@BartekKruczek, looks good for a second review.

2023-04-18 23:48 UTC, caupolicandiaz requested changes
@BartekKruczek I've completed my review. Please update the entry, and tag me when you have finished making changes. Thanks

2023-04-18 23:48 UTC, caupolicandiaz commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +| yearfirst | bool (default True) | if `True` is selected, the year will be given first. If `dayfirst` and `yearfirst` is `True`, `yearfirst` is more important |
```suggestion
| `yearfirst` | bool (default `True`) | Specifies that the str or list-like object begins with a year |
```

2023-04-18 23:48 UTC, caupolicandiaz commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +| utc | bool (default None) | whenever `True` is selected, output is converted into UTC time zone |
```suggestion
| `utc` | bool (default `None`) | When `True`, output is converted to UTC time zone |
```

2023-04-18 23:48 UTC, caupolicandiaz commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +| format | str (default None) | helpfull in analyzing time, more info. in 'str' docs |
```suggestion
| `format` | str (default `None`) | Pass a strftime to specify the format of the datetime conversion |
```

2023-04-18 23:48 UTC, caupolicandiaz commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +| exact | bool (default True) | defines how format is used |
```suggestion
| `exact` | bool (default `True`) | Determines how the format parameter is applied |
```

2023-04-18 23:48 UTC, caupolicandiaz commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +| unit | str (default 'ns') | defines a unit, float or integer number |
```suggestion
| `unit` | str (default 'ns') | Specifies the units of the passed object |
```

2023-04-18 23:48 UTC, caupolicandiaz commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +| infer_datetime_format | bool (default False) | whenever `True` is selected, datetime string format is based on `NaN` element
```suggestion
| `infer_datetime_format` | bool (default `False`) | When `True`, and no format has been passed, the datetime string will be based on the first non-`NaN` element within the object |
```

2023-04-18 23:48 UTC, caupolicandiaz commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +| origin | scalar (default unix) | reference date is based on that |
```suggestion
| `origin` | scalar (default unix) | Sets the reference date |
```

2023-04-18 23:48 UTC, caupolicandiaz commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +| cache | bool (default True) | is beeing used in datetime conversion, works only with at least 50 values |
```suggestion
| `cache` | bool (default `True`) | Allows the use of a unique set of converted dates to apply the conversion (only applied when object contains at least 50 values) |
```

2023-04-18 23:48 UTC, caupolicandiaz commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +First section of the following code shows how to import the needed library and how to create list of string. After that, it calls the `.to_datetime()` function and prints results onto the console.
```suggestion
The code below demonstrates the conversion of a string to a datetime object with the `.to_datetime()` function.
```

2023-04-18 23:48 UTC, caupolicandiaz commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +my_list = ['2039/11/09']
```suggestion
my_list = ['11/09/30']
```

2023-04-18 23:48 UTC, caupolicandiaz commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +xyz = pd.to_datetime(my_list)
```suggestion
xyz = pd.to_datetime(my_list, dayfirst=True)
```

2023-04-18 23:48 UTC, caupolicandiaz commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +xyz = pd.to_datetime(my_list)
I thought it might be instructive to demonstrate how the use of one of the parameters determines the parsing of the object

2023-04-18 23:48 UTC, caupolicandiaz commented on content/pandas/concepts/built-in-functions/to-datetime/to-datetime.md
> +DatetimeIndex(['2039-11-09'], dtype='datetime64[ns]', freq=None)
```suggestion
DatetimeIndex(['2030-11-09'], dtype='datetime64[ns]', freq=None)
```

2023-04-19 17:29 UTC, BartekKruczek commented
@caupolicandiaz Ok, I've changed it, thanks for comments

2023-04-19 19:58 UTC, caupolicandiaz approved these changes
@BartekKruczek @SSwiniarski LGTM. I did notice that the file was actually one step down from where it should be, and I went ahead and moved it into the terms folder. I think this entry is probably good to go.

2023-04-20 11:48 UTC, merged

2023-04-20 11:53 UTC, SSwiniarski commented
Congrats @BartekKruczek on the new entry. Live link here: https://www.codecademy.com/resources/docs/pandas/built-in-functions/to-datetime

You're currently listed as an anonymous contributor. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.

![image](https://user-images.githubusercontent.com/86081858/233357789-817c4ddd-2e58-473b-bb74-71738b812ffa.png)

To add your GitHub username to your Codecademy profile:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

![image](https://user-images.githubusercontent.com/86081858/233357914-e3686449-d148-4cec-9f95-a83e5690f5c7.png)

2.) Then log out and log back into Codecademy using your GitHub login:

![image](https://user-images.githubusercontent.com/86081858/233358031-084bc336-0874-48fd-b11c-3d0e2ee52270.png)

**Note**: Your email used for Codecademy will have to be listed in your GitHub profile for the login feature to properly work. If you use the same email for both GitHub and Codecademy already, then you're set.