Tanh term added
Codecademy/docs pull request #1815
Opened 2023-03-15 16:52 UTC by chandlermckane

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-16 18:37 UTC, SSwiniarski requested changes
@chandlermckane, I did a first review and left a few comments.

2023-03-16 18:37 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +Description: 'Computes the hyperbolic tangent of a given angle in radians'
```suggestion
Description: 'Computes the hyperbolic tangent of a given angle in radians.'
```

2023-03-16 18:37 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +The **`Math.tanh()`** method returns the hyperbolic tangent of a number.
```suggestion
The **`Math.tanh()`** method returns the hyperbolic tangent of a given angle in radians.
```

2023-03-16 18:37 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +
```suggestion
```
Remove extra line break.

2023-03-16 18:37 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +Parameter:This method accepts only single parameters.
```suggestion

Parameter: This method accepts only a single parameter.
```

2023-03-16 18:37 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +`x`:This parameter is the value to be passed to tanh()
```suggestion
`x`: This parameter is the angle in radians.
```

2023-03-16 18:37 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +`Returns`:This function returns the hyperbolic tangent value of a number.
```suggestion

Returns: This function returns the hyperbolic tangent value of `x`.
```

2023-03-16 18:37 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +
Can we have an introductory sentence explaining what the example is doing?

2023-03-17 11:45 UTC, SSwiniarski approved these changes
@chandlermckane Other than an additional line break, this seems good for a second review.

2023-03-17 11:45 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +Returns: This function returns the hyperbolic tangent value of `x`.
```suggestion

Returns: This function returns the hyperbolic tangent value of `x`.
```
Added line break.

2023-03-22 20:37 UTC, yangc95 commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +The code is declaring two constants, `x` and `y`, and then calculating the hyperbolic tangent of `x` using the Math.tanh() function. The resulting value is stored in `y`. Finally, the value of `y` is
```suggestion
The code is declaring two constants, `x` and `y`, and then calculating the hyperbolic tangent of `x` using the `Math.tanh()` function. The resulting value is stored in `y`. Finally, the value of `y` is printed to the console.
```

2023-03-22 20:37 UTC, yangc95 commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +console.log(y); // Output: 0.9640275800758169
```suggestion
console.log(y);
// Output: 0.9640275800758169
```

2023-03-22 20:37 UTC, yangc95 commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +const y = Math.tanh(x);
```suggestion
const y = Math.tanh(x);

```

2023-04-06 17:00 UTC, chandlermckane commented
> @chandlermckane It's been two weeks. Are you still working on this entry? Do you need assistance with @yangc95's comments?

I believe I have made the necessary changes.

2023-04-10 21:00 UTC, yangc95 commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +The example below declares two constants, `x` and `y`, and then calculates the hyperbolic tangent of `x` using the `Math.tanh()` function. The resulting value is stored in `y`. Finally, the value of
```suggestion
The example below declares two constants, `x` and `y`, and then calculates the hyperbolic tangent of `x` using the `Math.Tanh()` function. The resulting value is stored in `y`. Finally, the value of `y` is printed to the console.
```

2023-04-10 21:02 UTC, yangc95 commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +The example below declares two constants, `x` and `y`, and then calculates the hyperbolic tangent of `x` using the `Math.Tanh()` function. The resulting value is stored in `y`. Finally, the value of
```suggestion
The example below declares two double values, `x` and `y`, and then calculates the hyperbolic tangent of `x` using the `Math.Tanh()` function. The resulting value is stored in `y`. Finally, the value of `y` is printed to the console.
```

2023-04-10 21:03 UTC, yangc95 approved these changes
@chandlermckane Please see the changes I've made which include keeping the term consistent with the proper syntax throughout the entry. In addition, I edited some wording and wrote out the code to match standard C# syntax.

Please let me know if you have any concerns. Looks good for merge now!

2023-04-10 21:06 UTC, merged

2023-04-10 22:56 UTC, yangc95 commented
@chandlermckane here's the live link: https://www.codecademy.com/resources/docs/c-sharp/math-functions/tanh

<img width="816" alt="Screenshot 2023-04-10 at 6 49 25 PM" src="https://user-images.githubusercontent.com/72277593/231014310-97883124-fd73-4b45-b5f7-1a2cf0523d0a.png">

> It looks as if you're anonymous. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.
> 
> 
> To add your GitHub username to your Codecademy profile:
> 
> 1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
> 
> ![https://user-images.githubusercontent.com/72277593/228601403-8b7dc0df-0623-4560-9c9f-078b0759133a.png](https://user-images.githubusercontent.com/72277593/228601403-8b7dc0df-0623-4560-9c9f-078b0759133a.png)
> 
> Make sure to also set your visibility to “everyone” under privacy.
> 
> 2.) Then log out and log back into Codecademy using your GitHub login:
> 
> <img width="976" alt="githublogin" src="https://user-images.githubusercontent.com/72277593/231014420-68096559-830f-46ff-b00a-bf51fa197e7a.png">
>
> If the steps above do not work, it may be due to an email or local configuration issue.
> 
> In addition, we may reach out in the future if any adjustments to these entries are required.
>

cc: @SSwiniarski

2024-02-07 20:59 UTC, chandlermckane commented
I have updated my profile and linked my Github. How long will it take to populate me as a contributor?