Term entry c sharp sinh
Codecademy/docs pull request #1828
Opened 2023-03-17 10:52 UTC by cslylla

### Description

- Added new term for C# Math Functions: Math.Sinh()
- Closes #1764 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-17 16:43 UTC, SSwiniarski requested changes
@cslylla I did a first review and only had one comment.

2023-03-17 16:43 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/sinh/sinh.md
> +> **Note:** Depending on the used operating system or architecture, the exact result or the input range of the `Math.Sinh()` method may differ due to the differences in the C runtime environment.
```suggestion
> **Note:** Depending on the operating system or architecture, the exact result or the input range of the `Math.Sinh()` method may differ due to the differences in the C runtime environment.
```

2023-03-17 17:03 UTC, cslylla commented
@SSwiniarski I accepted the changes 👍🏻

2023-03-18 11:45 UTC, SSwiniarski approved these changes
@cslylla Looks good for a second review.

2023-03-28 18:08 UTC, yangc95 commented on content/c-sharp/concepts/math-functions/terms/sinh/sinh.md
> +
```suggestion
```

2023-03-28 18:15 UTC, merged

2023-03-28 18:24 UTC, yangc95 commented
👏 @cslylla here's the live link: https://www.codecademy.com/resources/docs/c-sharp/math-functions/sinh

![Screenshot 2023-03-28 at 2 22 29 PM](https://user-images.githubusercontent.com/72277593/228332108-ef88edeb-dcdf-4918-869d-4226145b3b87.png)

cc: @SSwiniarski