Term entry c sharp cosh
Codecademy/docs pull request #1830
Opened 2023-03-17 11:00 UTC by cslylla

### Description

- Added new term for C# Math Functions: Math.Cosh()
- Closes #1765 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-17 16:45 UTC, SSwiniarski requested changes
@cslylla I did a first review and left one comment.

2023-03-17 16:45 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/cosh/cosh.md
> +> **Note:** Depending on the used operating system or architecture, the exact result or the input range of the `Math.Cosh()` method may differ due to the differences in the C runtime environment.
```suggestion
> **Note:** Depending on the operating system or architecture, the exact result or the input range of the `Math.Cosh()` method may differ due to the differences in the C runtime environment.
```

2023-03-17 17:02 UTC, cslylla commented
@SSwiniarski Thank you, I accepted it!

2023-03-18 11:44 UTC, SSwiniarski approved these changes
@cslylla Looks good for review two.

2023-03-28 17:54 UTC, yangc95 approved these changes

2023-03-28 17:55 UTC, merged