.Atan() entry branch
Codecademy/docs pull request #1831
Opened 2023-03-17 16:18 UTC by OCollis

### Description

New .md file containing an entry for the C# math function .Atan() at ` docs/content/c-sharp/concepts/math-functions/terms/atan/atan.md`

### Type of Change

- Adding a new entry
- 
### Checklist

- [ x ] All writings are my own.
- [ x ] My entry follows the Codecademy Docs style guide.
- [ x ] My changes generate no new warnings.
- [ x ] I have performed a self-review of my own writing and code.
- [ x ] I have checked my entry and corrected any misspellings.
- [ x ] I have made corresponding changes to the documentation if needed.
- [ x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-17 16:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1831) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1831) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1831) it.</sub>

2023-03-17 16:54 UTC, SSwiniarski requested changes
@OCollis I did a first review and left some comments. Most important is that your PR contains a number of extra files that need to be removed.

2023-03-17 16:54 UTC, SSwiniarski commented on .vs/ProjectSettings.json
Remove this file

2023-03-17 16:54 UTC, SSwiniarski commented on .vs/VSWorkspaceState.json
Remove this file

2023-03-17 16:54 UTC, SSwiniarski commented on .vs/docs/FileContentIndex/021f9686-ce2d-49d5-b351-bb365cf49ef7.vsidx
Remove this file

2023-03-17 16:54 UTC, SSwiniarski commented on .vs/docs/FileContentIndex/7055da89-0860-4422-9ebe-a06db798e266.vsidx
remove this file

2023-03-17 16:54 UTC, SSwiniarski commented on .vs/docs/FileContentIndex/70f08246-1abd-4b3a-8a52-7cd9cfff4c09.vsidx
Remove this file

2023-03-17 16:54 UTC, SSwiniarski commented on .vs/docs/FileContentIndex/read.lock
Remove this file

2023-03-17 16:54 UTC, SSwiniarski commented on .vs/docs/v17/.wsuo
Remove this file

2023-03-17 16:54 UTC, SSwiniarski commented on .vs/docs/v17/workspaceFileList.bin
Remove this file

2023-03-17 16:54 UTC, SSwiniarski commented on .vs/slnx.sqlite
remove this file

2023-03-17 16:54 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/atan/atan.md
> +
```suggestion
```
Remove extra line break.

2023-03-17 16:54 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/atan/atan.md
> +- The `Math.Atan()` method takes one double as an argument and returns a double.
```suggestion

- The `Math.Atan()` method takes one double as an argument and returns a double.
```

Add line break.

2023-03-17 16:54 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/atan/atan.md
> +The example below shows the code in action:
The codebyte example:
1. Should have a header `## Codebyte Example`
2. Should be different from the example already given.

2023-03-21 12:13 UTC, OCollis commented
I have removed the unessesary files and updated `content/c-sharp/concepts/math-functions/terms/atan/atan.md` based on SSwiniarski's feedback

2023-03-21 16:09 UTC, SSwiniarski requested changes
@OCollis, two more comments.

2023-03-21 16:09 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/atan/atan.md
> +
```suggestion
```
You still need to remove the extra line break at the start of the metadata.

2023-03-22 11:19 UTC, SSwiniarski approved these changes
@OCollis aside from one more line break, this is ready for a second review.

2023-03-22 11:19 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/atan/atan.md
> +
```suggestion
```
Remove extra line break.

2023-03-23 23:17 UTC, caupolicandiaz requested changes
@OCollis Overall looks good. Just a couple of minor edits.

2023-03-23 23:17 UTC, caupolicandiaz commented on content/c-sharp/concepts/math-functions/terms/atan/atan.md
> +  - 'Learn c-sharp'
```suggestion
  - 'learn-c-sharp'
```

2023-03-23 23:17 UTC, caupolicandiaz commented on content/c-sharp/concepts/math-functions/terms/atan/atan.md
> +## Codebyte Example
Generally, for simple methods, one example is sufficient unless there is some valuable additional functionality demonstrated by a second example. Here I think we should remove one (either example can stay on its own).

2023-03-24 19:11 UTC, caupolicandiaz approved these changes
@OCollis All set. I did add a quick edit, the catalogContent item was still missing a dash.

2023-03-25 11:35 UTC, merged

2023-03-25 11:45 UTC, SSwiniarski commented
@OCollis congrats on the new entry. Live link is here: https://www.codecademy.com/resources/docs/c-sharp/math-functions/atan

You're currently listed as an anonymous contributor. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.

![image](https://user-images.githubusercontent.com/86081858/227715517-71b95627-a4aa-4b05-a16f-d04145d5f393.png)

To add your GitHub username to your Codecademy profile:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

![image](https://user-images.githubusercontent.com/86081858/227715551-f61db289-84e5-4252-8cd3-7a2a387ca2c1.png)

2.) Then log out and log back into Codecademy using your GitHub login:

![image](https://user-images.githubusercontent.com/86081858/227715567-cd840df4-3f44-4aea-85ff-54389cd56f0f.png)