C# Strings.Equals() entry added for review
Codecademy/docs pull request #1844
Opened 2023-03-18 18:32 UTC by alexwiehl

### Description

A C# entry has been created for the Strings.Equals() method. This is the first "term" entry for C# Strings, so I have created a new folder labeled "terms" under c-sharp/concepts/strings. Closes #1834.

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-18 18:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1844) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1844) before we can accept your contribution.<br/><hr/>**Alex Wiehl** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1844) it.</sub>

2023-03-21 21:16 UTC, caupolicandiaz requested changes
@alexwiehl Just some minor edits to align this entry with our current standards. Tag me when you've finished making changes. Thanks

2023-03-21 21:16 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/equals/equals.md
> +Title: 'String.Equals()'
```suggestion
Title: '.Equals()'
```

2023-03-21 21:16 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/equals/equals.md
> +Description: 'Determines whether two String objects have the same value or not.'
```suggestion
Description: 'Determines whether two string objects have the same value or not.'
```

2023-03-21 21:16 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/equals/equals.md
> +The **String.Equals()** method determines whether two String objects have the same value or not.
```suggestion
The **.Equals()** method determines whether two string objects have the same value or not.
```

2023-03-31 22:58 UTC, caupolicandiaz commented
@alexwiehl Just checking in on this entry, do you need any assistance with the edits?

2023-04-06 21:55 UTC, caupolicandiaz approved these changes
@alexwiehl I've gone ahead and made the changes I suggested.

2023-04-07 13:49 UTC, SSwiniarski commented
@alexwiehl, we will be unable to merge this until you add the `Alex Wiehl` e-mail that created this entry to your GitHub account.  The CLA doesn't recognize the second e-mail.

2023-04-07 13:53 UTC, SSwiniarski requested changes
@alexwiehl I had one comment to add the other syntax for `.Equals()` that you use in the example. Do that and fix the email problem with the CLA and we should be ready to merge.

2023-04-07 13:53 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/equals/equals.md
> +String.Equals(string1, string2)
You also need to mention the syntax `string1,Equals(string2)` that you use in the example.

2023-04-13 20:07 UTC, caupolicandiaz commented
@alexwiehl @SSwiniarski I've updated the syntax section. @SSwiniarski Any additional edits?

2023-04-14 16:09 UTC, SSwiniarski commented
@caupolicandiaz we just need @alexwiehl to fix the e-mail problem with the CLA.

2023-04-14 19:08 UTC, merged

2023-04-16 23:34 UTC, yangc95 commented
Nice 👍 @alexwiehl here's the live link: https://www.codecademy.com/resources/docs/c-sharp/strings/equals

> t looks as if you're anonymous. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.
> 
> 
> To add your GitHub username to your Codecademy profile:
> 
> 1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
> 
> ![https://user-images.githubusercontent.com/72277593/228601403-8b7dc0df-0623-4560-9c9f-078b0759133a.png](https://user-images.githubusercontent.com/72277593/228601403-8b7dc0df-0623-4560-9c9f-078b0759133a.png)
> 
> Make sure to set your visibility to “everyone”.
> 
> 2.) Then log out and log back into Codecademy using your GitHub login:
> 
> <img width="976" alt="githublogin" src="[https://user-images.githubusercontent.com/72277593/228601315-71d5d52c-846e-408e-87db-7f9e40e6b0f1.png](https://user-images.githubusercontent.com/72277593/228601315-71d5d52c-846e-408e-87db-7f9e40e6b0f1.png)">
> 
> If the steps above do not work, it may be due to an email or local configuration issue.
> 
> In addition, we may reach out in the future if any adjustments to these entries are required.
>
> If you wish to write about a topic you're more comfortable with, feel free to join the discussion at [Find a Starting Point: Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868)