Added markdown for ToLower() string method
Codecademy/docs pull request #1845
Opened 2023-03-19 16:25 UTC by Rahul-Yadav-Online

### Description

A C# entry has been created  for Strings.ToLower() method. This is the first "term" entry for C# Strings, so I have created a new folder labeled "terms" under c-sharp/concepts/strings. Closes #1842

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-19 16:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1845) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1845) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1845) it.</sub>

2023-03-20 15:32 UTC, SSwiniarski requested changes
@Rahul-Yadav-Online I did a first review and left some comments.

2023-03-20 15:32 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/tolower/tolower.md
> +Here, `originalString` is the string you want to convert to lowercase, and `lowerCaseString` is the new string that contains the lowercase characters.
```suggestion
Here, `originalString` is the string being converted to lowercase, and `lowerCaseString` is the new string that contains the lowercase characters.
```

2023-03-20 15:32 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/tolower/tolower.md
> +
```suggestion
```
remove extra line break

2023-03-20 15:32 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/tolower/tolower.md
> +In the following example, we create a new string `originalString` that contains the text *"HELLO WORLD"*. We then call the `ToLower()` method on this string and store the result in a new string varia
```suggestion
In the following example, a new string `originalString` is created that contains the text "HELLO WORLD". Then the `.ToLower()` method is called on this string and store the result in a new string variable `lowerCaseString`. Finally, the value of `lowerCaseString` is printed to the console, which outputs "hello world".
```

2023-03-20 15:32 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/tolower/tolower.md
> +In following runnable example, we create a new string `originalString` that contains the text *"THIS IS A TEST STRING"*. We then call the `ToLower()` method on this string and store the result in a n
```suggestion
In following runnable example, a new string `originalString` is created that contains the text "THIS IS A TEST STRING". Then the `.ToLower()` method is called on this string and the result is stored in a new string variable `lowerCaseString`. Finally, both the original and the lowercase strings are printed to the console.
```

2023-03-21 04:12 UTC, Rahul-Yadav-Online commented on content/c-sharp/concepts/strings/terms/tolower/tolower.md
> +
ok

2023-03-21 04:12 UTC, Rahul-Yadav-Online commented on content/c-sharp/concepts/strings/terms/tolower/tolower.md
> +
Okay

2023-03-21 04:15 UTC, Rahul-Yadav-Online commented on content/c-sharp/concepts/strings/terms/tolower/tolower.md
> +Here, `originalString` is the string you want to convert to lowercase, and `lowerCaseString` is the new string that contains the lowercase characters.
do i need to remove the and as well ?

2023-03-21 04:19 UTC, Rahul-Yadav-Online commented on content/c-sharp/concepts/strings/terms/tolower/tolower.md
> +In the following example, we create a new string `originalString` that contains the text *"HELLO WORLD"*. We then call the `ToLower()` method on this string and store the result in a new string varia
Okay will do

2023-03-21 04:22 UTC, Rahul-Yadav-Online commented on content/c-sharp/concepts/strings/terms/tolower/tolower.md
> +In following runnable example, we create a new string `originalString` that contains the text *"THIS IS A TEST STRING"*. We then call the `ToLower()` method on this string and store the result in a n
Got it, will change this one as well

2023-03-21 04:22 UTC, Rahul-Yadav-Online commented on content/c-sharp/concepts/strings/terms/tolower/tolower.md
> +Here, `originalString` is the string you want to convert to lowercase, and `lowerCaseString` is the new string that contains the lowercase characters.
okay

2023-03-21 16:12 UTC, SSwiniarski approved these changes
@Rahul-Yadav-Online Looks good for a second review.

2023-03-28 18:46 UTC, yangc95 approved these changes

2023-03-28 18:52 UTC, merged

2023-03-28 18:57 UTC, yangc95 commented
🙌 Congrats on this entry @Rahul-Yadav-Online here's the live link: https://www.codecademy.com/resources/docs/c-sharp/strings/tolower

![Screenshot 2023-03-28 at 2 55 44 PM](https://user-images.githubusercontent.com/72277593/228339450-a89ef8f0-36d8-4e5c-9dee-a636d71cf2e9.png)

> It looks as if you're anonymous. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.
>
> To add your GitHub username to your Codecademy profile:
>
> 1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
>
![githubusername.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/435cd0ba-5edc-4624-999e-b2c4b4fe7944/githubusername.png)
>
> 2.) Then log out and log back into Codecademy using your GitHub login:
>
![githublogin.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/3889044f-a20f-48b9-9cca-55fe713fe045/githublogin.png)
>
> If the steps above do not work, it may be due to an email or local configuration issue.
>
> In addition, we may reach out in the future if any adjustments to these entries are required.

cc: @SSwiniarski