Add markdown description for String.ToUpper() method
Codecademy/docs pull request #1853
Opened 2023-03-22 21:03 UTC by huythai855

### Description
I see the issue #1841 and want to make some contribution. I followed the instructions and here is my commit.
Please leave your comments if there are problems. Thank you so much!
 
### Type of Change
- Adding a new entry

### Checklist
- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-22 21:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1853) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1853) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1853) it.</sub>

2023-03-22 21:36 UTC, caupolicandiaz requested changes
@huythai855 I've completed my initial review. Please update the entry and tag me when you've finished making changes. Thanks

2023-03-22 21:36 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/toupper/toupper.md
> +Title: '.ToLower()'
```suggestion
Title: '.ToUpper()'
```

2023-03-22 21:36 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/toupper/toupper.md
> +Description: 'The ToUpper() method is used to convert all the characters in a given string to uppercase.'
```suggestion
Description: 'Returns a new string in all uppercase characters based on the passed string.'
```

2023-03-22 21:36 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/toupper/toupper.md
> +The **`ToUpper()`** method is a method in C# that takes a string and returns a copy of this string converted to uppercase. Numbers and symbols are not changed.
```suggestion
The **`.ToUpper()`** method is a method in C# that takes a string and returns a copy of this string converted to uppercase. Numbers and symbols within the string are not changed.
```

2023-03-22 21:36 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/toupper/toupper.md
> +The .ToUpper() return a new string whose letters are converted to uppercase.
```suggestion

```

2023-03-22 21:36 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/toupper/toupper.md
> +string.ToUpper()
```suggestion
some_string.ToUpper()
```

2023-03-22 21:36 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/toupper/toupper.md
> +```pseudo
```suggestion
```shell
```

2023-03-22 21:36 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/toupper/toupper.md
> +// This code demonstrates the use of the ToUpper() method in C#
```suggestion

```

2023-03-22 21:36 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/toupper/toupper.md
> +```cs
please include the code setup, the class and main calls, in the first example as well. It should be runnable as is.

2023-03-22 21:36 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/toupper/toupper.md
> +```
Add a space after the code block and after "Here is the output:"

2023-03-22 21:36 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/toupper/toupper.md
> +To convert `originalString`, which contains the text *"Hi! I'm Codecademy"*, to uppercase then store in a new string variable named `uppercaseString`:
```suggestion
The example below converts a given string to uppercase and stores this value in a new string variable named `uppercaseString`:
```

2023-03-23 13:14 UTC, huythai855 commented
Hi @caupolicandiaz. Thank you very much for your review.
I've just updated the entry. Please keep noticing me if something goes wrong.

2023-03-23 19:26 UTC, caupolicandiaz approved these changes
@huythai855 Looks good. I did add a couple of edits, there was some spacing issues in the metadata and an extra line break in the body. This is ready for another review.

2023-04-05 22:26 UTC, yangc95 commented on content/c-sharp/concepts/strings/terms/toupper/toupper.md
> +Description: 'Returns a new string in all uppercase characters based on the passed string.'
```suggestion
Description: 'Returns a new string with all uppercase characters.'
```

2023-04-05 22:27 UTC, yangc95 commented on content/c-sharp/concepts/strings/terms/toupper/toupper.md
> +The **`.ToUpper()`** method is a method in C# that takes a string and returns a copy of this string converted to uppercase. Numbers and symbols are not changed.
Rather than taking in a a thing, this method is called on the string. Let's rephrase here!

2023-04-05 22:29 UTC, yangc95 commented on content/c-sharp/concepts/strings/terms/toupper/toupper.md
> +In this following example, `originalString` is the string being converted to uppercase, and `uppercaseString` is the new string that contains the uppercase characters. We can see that the original st
```suggestion
In this following example, `originalString` is the string being converted to uppercase, and `uppercaseString` is the new string that contains the uppercased characters. The original string remains unchanged:
```

2023-04-05 22:29 UTC, yangc95 commented on content/c-sharp/concepts/strings/terms/toupper/toupper.md
> +
```suggestion
```

2023-04-05 22:30 UTC, yangc95 commented on content/c-sharp/concepts/strings/terms/toupper/toupper.md
> +## Example
Let's actually just keep the codebyte example here because the method is relatively straightforward. One example will suffice

2023-04-05 22:31 UTC, yangc95 reviewed
Hey @huythai855, thanks for your patience! Great concise term entry.

I left a few comments, after which please tag me. I believe after this edit, the term will be ready to merge.

2023-04-07 18:46 UTC, huythai855 commented
Hi @yangc95. Thanks for your second review.
I've just made some modifications. Can you take a look again?

2023-04-07 20:19 UTC, yangc95 approved these changes

2023-04-07 20:45 UTC, merged

2023-04-08 20:09 UTC, yangc95 commented
🥳 Congrats @huythai855, here's the live link: https://www.codecademy.com/resources/docs/c-sharp/strings/toupper

<img width="828" alt="Screenshot 2023-04-08 at 4 07 36 PM" src="https://user-images.githubusercontent.com/72277593/230740616-2e0c8aee-93de-425a-97d2-fe3b9cec9a2c.png">

> It looks as if you're anonymous. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.
> 
> 
> To add your GitHub username to your Codecademy profile:
> 
> 1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
> 
> ![https://user-images.githubusercontent.com/72277593/228601403-8b7dc0df-0623-4560-9c9f-078b0759133a.png](https://user-images.githubusercontent.com/72277593/228601403-8b7dc0df-0623-4560-9c9f-078b0759133a.png)
> 
> 2.) Then log out and log back into Codecademy using your GitHub login:
> 
> <img width="976" alt="githublogin" src="https://user-images.githubusercontent.com/72277593/230740663-7ab7f33a-49bf-443d-a5b8-2903d6ac53a4.png">
>
> If the steps above do not work, it may be due to an email or local configuration issue.
> 
> In addition, we may reach out in the future if any adjustments to these entries are required.
>

2023-04-08 20:27 UTC, huythai855 commented
@yangc95  I did 2 steps about several times but it doesn't work. And the entry contributor name is still `Anonymous`
Can you check again for me please?

2023-04-08 20:29 UTC, yangc95 commented
@huythai855 do your e-mails differ between GitHub and Codecademy?

2023-04-08 20:34 UTC, huythai855 commented
@yangc95 No, I have just check again. My Github Primary email is the same to the Codecademy one.

Besides, I have 2 more additional email linked with my github account. But I don't think it's the problem.

2023-04-12 02:21 UTC, huythai855 commented
@yangc95 yes, this is my full setting

![image](https://user-images.githubusercontent.com/51937716/231331136-2d8e6a50-1f17-4d2a-929c-989b215de3f7.png)

2023-04-17 14:40 UTC, yangc95 commented
@huythai855 Maybe it needed more time to render. Looks looks like everything is visible now 🙂