C# Strings.Replace() entry added for review
Codecademy/docs pull request #1856
Opened 2023-03-23 11:48 UTC by PetroHubenya

### Description

A C# entry has been created for the Strings.Replace() method. This is the first "term" entry for C# Strings, so I have created a new folder labeled "terms" under c-sharp/concepts/strings. Closes https://github.com/Codecademy/docs/issues/1840.

### Type of Change

- Adding a new entry.

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-23 11:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1856) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1856) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1856) it.</sub>

2023-03-23 16:00 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/replace/replace.md
> +Interested in helping build Docs? Read the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) or share your thoughts in this [feedback form](https://codecademy
Remove this last line. It is provided by Docs automatically.

2023-03-23 21:24 UTC, PetroHubenya commented
Dear @SSwiniarski, the [content/c-sharp/concepts/strings/terms/replace/replace.md](https://github.com/Codecademy/docs/pull/1856/commits/2a13056b85a273987038673f93b03b4ddde29c42) file is updated according to your comments.
Kindly ask you to review.

2023-03-24 17:32 UTC, SSwiniarski approved these changes
@PetroHubenya Looks good for a second review.

2023-03-24 19:50 UTC, caupolicandiaz requested changes
@PetroHubenya I've finished my initial review. Please update the entry and tag me when you've finished pushing changes. Thanks

2023-03-24 19:50 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/replace/replace.md
> +> **Note:** The `.Replace()` method does not modify the original `string`. It always produces a new string.
```suggestion
> **Note:** The `.Replace()` method does not modify the original `string`, it always produces a new string.
```

2023-03-24 19:50 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/replace/replace.md
> +> **Note:** If `oldChar` or `oldString` is not found in the original string, than the `.Replace()` method returns the string witout changes.
```suggestion
> **Note:** If `oldChar` or `oldString` is not found in the original string, than the method returns the string without changes.
```

2023-03-24 19:50 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/replace/replace.md
> +* All occurances of indicated character are replaced with another one.
```suggestion
* All occurrences of indicated character are replaced with another one.
```

2023-03-24 19:50 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/replace/replace.md
> +* All occurances of indicated string are replaced with another one.
```suggestion
* All occurrences of indicated string are replaced with another one.
```

2023-03-24 19:50 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/replace/replace.md
> +string oldString = "A-B-C-D-E-F-G-H-I";
both code examples should include a class and main call, it should be runnable as is, like a codebyte

2023-03-24 19:50 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/replace/replace.md
> +Console.WriteLine($"Wrong statement is: {wrongString}");
```suggestion
Console.WriteLine($"False statement: {wrongString}");
```

2023-03-24 19:50 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/replace/replace.md
> +Console.WriteLine($"Right statement is: {rightString}");
```suggestion
Console.WriteLine($"True statement: {rightString}");
```

2023-03-24 19:50 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/replace/replace.md
> +Wrong statement is: Earth is the fourth planet from the Sun.
```suggestion
False statement: Earth is the fourth planet from the Sun.
```

2023-03-24 19:50 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/replace/replace.md
> +Right statement is: Earth is the third planet from the Sun.
```suggestion
True statement: Earth is the third planet from the Sun.
```

2023-03-25 11:15 UTC, PetroHubenya commented
Dear @caupolicandiaz, the entry is updated according your comments. Kindly ask you review ones again.

2023-03-25 20:38 UTC, caupolicandiaz approved these changes
@PetroHubenya Looks good. I did add a couple of edits, one issue was the sequential notes or block quotes under the syntax section. This arrangement sets off MD028/no-blanks-blockquote error. I've added comments to avoid the error, but having one note that addresses all three concerns is probably a cleaner approach.

2023-03-26 11:43 UTC, merged

2023-03-26 13:28 UTC, SSwiniarski commented
@PetroHubenya congrats on the new entry! Live link is here:https://www.codecademy.com/resources/docs/c-sharp/strings/replace

You're currently listed as an anonymous contributor. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.

![image](https://user-images.githubusercontent.com/86081858/227778793-f6ed276e-4a62-44fb-95ca-64a991bf34bd.png)

To add your GitHub username to your Codecademy profile:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

![image](https://user-images.githubusercontent.com/86081858/227778844-d0e73f44-d1a8-4b63-87e6-c04f07bd9b0a.png)

2.) Then log out and log back into Codecademy using your GitHub login:

![image](https://user-images.githubusercontent.com/86081858/227778896-f66695ad-f59a-45d0-9d57-0234d4780551.png)

**Note:** Your email used for Codecademy will have to be listed in your GitHub profile for the login feature to properly work. If you use the same email for both GitHub and Codecademy already, then you're set.