Adding Links to Cybersecurity Topics
Codecademy/docs pull request #1865
Opened 2023-03-25 18:33 UTC by SSwiniarski

### Description

Adding some crosslinking to the new Cybersecurity entries.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-25 22:15 UTC, caupolicandiaz approved these changes
@SSwiniarski Overall looks good, just one comment.

2023-03-25 22:15 UTC, caupolicandiaz commented on content/cybersecurity/concepts/cyber-attack/cyber-attack.md
> +- Strong user authentication and authortization practices, such as strong passwords and [multi-factor authentication](https://www.codecademy.com/resources/docs/cybersecurity/multi-factor-authenticati
```suggestion
- Strong user authentication and authorization practices, such as strong passwords and [multi-factor authentication](https://www.codecademy.com/resources/docs/cybersecurity/multi-factor-authentication), should be utilized.
```

2023-04-01 15:00 UTC, KTom101 requested changes
@SSwiniarski I just added one request.

2023-04-01 15:00 UTC, KTom101 commented on content/cybersecurity/concepts/spear-phishing/spear-phishing.md
While we have this open, can the subheadings be fixed to be all title-cased? The casing is mixed in this entry.

2023-04-02 13:14 UTC, SSwiniarski commented on content/cybersecurity/concepts/spear-phishing/spear-phishing.md
done!

2023-04-02 13:15 UTC, SSwiniarski commented
@KTom101 I applied your suggestion.

2023-04-02 20:14 UTC, KTom101 approved these changes
@SSwiniarski 👍

2023-04-02 20:34 UTC, merged

2023-04-02 20:46 UTC, KTom101 commented
Live Links: [Blue Team](https://www.codecademy.com/resources/docs/cybersecurity/blue-team), [Cyber Attack](https://www.codecademy.com/resources/docs/cybersecurity/cyber-attack), [Cyber Resilience](https://www.codecademy.com/resources/docs/cybersecurity/cyber-resilience), [Data Exfiltration](https://www.codecademy.com/resources/docs/cybersecurity/data-exfiltration), [Hacking](https://www.codecademy.com/resources/docs/cybersecurity/hacking), [Red Team](https://www.codecademy.com/resources/docs/cybersecurity/red-team), [Risk Management](https://www.codecademy.com/resources/docs/cybersecurity/risk-management), [Security Testing](http://codecademy.com/resources/docs/cybersecurity/security-testing), [Spear Phishing](https://www.codecademy.com/resources/docs/cybersecurity/spear-phishing)