[Term Entry] Sdlc: agile
Codecademy/docs pull request #1879
Opened 2023-03-27 17:12 UTC by aherman91

### Description

Add term entry on Agile to SDLC Doc in General. 

### Type of Change

Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-27 20:18 UTC, caupolicandiaz requested changes
@aherman91 Looks good overall, just a few notes.

2023-03-27 20:18 UTC, caupolicandiaz commented on content/general/concepts/software-development-life-cycle/Terms/agile/agile.md
> +Description: 'Agile development is a software development methodology that emphasizes iteration, flexibility, and cross-team collaboration.'
```suggestion
Description: 'Agile is a software development methodology that emphasizes iteration, flexibility, and cross-team collaboration.'
```

2023-03-27 20:18 UTC, caupolicandiaz commented on content/general/concepts/software-development-life-cycle/Terms/agile/agile.md
> +**Agile Development** is a software development methodology that emphasizes iteration, flexibility and cross-team collaboration.
```suggestion
**Agile** is a software development methodology that emphasizes iteration, flexibility and cross-team collaboration. 
```

2023-03-28 17:16 UTC, aherman91 commented
Hey @caupolicandiaz thank you for the feedback! I have made the suggested changes.

2023-03-28 18:58 UTC, caupolicandiaz approved these changes
@aherman91 Looks good.

2023-03-28 21:36 UTC, HishamT approved these changes
LGTM!

2023-03-31 23:52 UTC, merged

2023-04-01 03:06 UTC, KTom101 commented
I noticed the file path is incorrect, the entry is not appearing on Codecademy. A new PR will need to be created to change `content/general/concepts/software-development-life-cycle/Terms/agile/agile.md` to `content/general/concepts/software-development-life-cycle/terms/agile/agile.md`

2023-04-01 20:20 UTC, caupolicandiaz commented
I'm going to add this to one of our link PRs

2023-04-03 16:27 UTC, yangc95 commented
Thanks @KTom101 for making note of this. I created a PR here which shouldn't alter authorship: https://github.com/Codecademy/docs/pull/1929

cc: @aherman91 @caupolicandiaz @HishamT