Add PHP switch case statement entry to docs
Codecademy/docs pull request #1887
Opened 2023-03-28 09:56 UTC by apostoliadel

### Description

I made a new directory in the docs/content/php/concepts/switch section and added a markdown file named "switch.md". Inside the file, I explained what the switch case is, how it works, and included an example to make it easy to understand. I tried to keep it simple and informative. Closes #1874 - [Concept Entry] PHP Switch

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-28 10:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1887) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1887) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1887) it.</sub>

2023-03-29 17:06 UTC, SSwiniarski requested changes
@apostoliadel I did a first review and left a couple of comments.

2023-03-29 17:06 UTC, SSwiniarski commented on content/php/concepts/switch/switch.md
> +A switch case statement in PHP executes different blocks of code based on a variable or an expression. It's a helpful alternative to multiple if-else statements, especially when there are many condit
```suggestion
A **switch case** statement in PHP executes different blocks of code based on a variable or an expression. It's a helpful alternative to multiple if-else statements, especially when there are many conditions to check. By grouping related conditions, switch case simplifies code and makes it easier to read. Moreover, it speeds up code execution by evaluating the expression only once.
```

2023-03-29 17:06 UTC, SSwiniarski commented on content/php/concepts/switch/switch.md
> +It's important to end each case block with a `break` statement, or the code will continue to the next case block.
```suggestion
> **Note:** It's important to end each case block with a `break` statement, or the code will continue to the next case block.
```

2023-03-31 06:40 UTC, apostoliadel commented
Thanks for the suggestions! I've updated the code and really appreciate your time and effort! Apologies for the default commit names, this is my first time using this feature.

2023-04-03 21:51 UTC, KTom101 requested changes
@apostoliadel I've completed a second review of this. Let me know if there are any questions.

2023-04-03 21:51 UTC, KTom101 commented on content/php/concepts/switch/switch.md
> +  - 'paths/front-end-engineer-career-path'
Let's keep this as two catalog content slugs instead of three.
```suggestion
```

2023-04-03 21:51 UTC, KTom101 commented on content/php/concepts/switch/switch.md
> +  - 'Conditionals'
This tag (Conditionals) will need to be added to the [tags.md](https://github.com/Codecademy/docs/blob/main/documentation/tags.md) file. You can include the edit in this PR.

2023-04-04 07:29 UTC, apostoliadel commented
Thank you so much for your feedback! I applied all of the changes you suggested and made several new commits. Please let me know if there's anything else I can improve. Thanks again!

2023-04-05 17:50 UTC, KTom101 approved these changes
@apostoliadel Looks good, I just added the language (pseudo) to the syntax code block [c9d4f32](https://github.com/Codecademy/docs/pull/1887/commits/c9d4f32fb702c7d750b3828e812de77f1dab5805).

2023-04-05 17:51 UTC, merged

2023-04-05 18:07 UTC, KTom101 commented
@apostoliadel Entry is live 🎉 https://www.codecademy.com/resources/docs/php/switch

Currently, you're listed as an anonymous contributor:

<img width="848" alt="Screenshot 2023-04-05 at 1 57 12 PM" src="https://user-images.githubusercontent.com/40783324/230164143-1a41492a-829d-4f51-8bb7-7a305ff9bd24.png">

If you want to remain anonymous, there is nothing more you need to do. If you wish to be listed as a contributor, make sure you've added your GitHub username to your Codecademy profile using the following steps:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

<img width="871" alt="YourGitHubName" src="https://user-images.githubusercontent.com/40783324/230164577-59f07cc3-8297-4828-be73-89205545b633.png">

2.) Then log out and log back into Codecademy using your GitHub login:

<img width="1273" alt="ReLogIn" src="https://user-images.githubusercontent.com/40783324/230164784-d8684c33-15d7-4b1b-a7e0-b96a5297cef3.png">

> **Note:** Your email used for Codecademy will have to be listed in your GitHub profile for the login feature to properly work. If you use the same email for both GitHub and Codecademy already, then you're set.

@yangc95 @SSwiniarski