Copy module
Codecademy/docs pull request #1902
Opened 2023-03-29 23:11 UTC by xenos92

### Description

Added description for pandas dataframe.copy() method.

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-29 23:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1902) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1902) before we can accept your contribution.<br/><hr/>**arash.shokri** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1902) it.</sub>

2023-03-30 21:24 UTC, caupolicandiaz requested changes
@xenos92 I've completed my initial review. Please update the entry and tag me when you've finished making changes. Thanks

2023-03-30 21:24 UTC, caupolicandiaz commented on content/pandas/concepts/dataframe/terms/copy/copy.md
> +Notice that .copy() method has a deep parameter that can dictate the behavior of the resulting dataframe. We can either make a shallow or a deep copy of pandas dataframe.
```suggestion
Note that the designation of the `deep` parameter can have impacts on the resulting copy as well as the original DataFrame.

```

2023-03-30 21:24 UTC, caupolicandiaz commented on content/pandas/concepts/dataframe/terms/copy/copy.md
> +1. In a shallow copy, the new object points to the same data as the original object, and any changes made to the copy will affect the original object. Changes made to the original dataframe will also
```suggestion
- In a shallow copy, the new object points to the same data as the original object, and any changes made to the copy will affect the original object. Changes made to the original dataframe will also be reflected in the shallow copy. By default, the `.copy()` method creates a deep copy. 
```

2023-03-30 21:24 UTC, caupolicandiaz commented on content/pandas/concepts/dataframe/terms/copy/copy.md
> +
```suggestion
```

2023-03-30 21:24 UTC, caupolicandiaz commented on content/pandas/concepts/dataframe/terms/copy/copy.md
> +2. In a deep copy, a new object is created with a completely new set of data that is identical to the original data. Changes made to the copied object will not affect the original object and vice ver
```suggestion
- In a deep copy, a new object is created with a completely new set of data that is identical to the original data. Changes made to the copied object will not affect the original object and vice versa, even if the original data is modified. 
```

2023-03-30 21:24 UTC, caupolicandiaz commented on content/pandas/concepts/dataframe/terms/copy/copy.md
> +```py
I would recommend that you remove the output comments. Follow the print statement on line 57 with the other two print statements and close the code block. Then have a line of text "The output of the code above will be:" and follow with a ```shell block that just contains the three dataframes.

2023-03-30 21:24 UTC, caupolicandiaz commented on content/pandas/concepts/dataframe/terms/copy/copy.md
> +# create a DataFrame
```suggestion
# Create a DataFrame
```

2023-03-30 21:24 UTC, caupolicandiaz commented on content/pandas/concepts/dataframe/terms/copy/copy.md
> +# create a DataFrame
always start comments with a capital

2023-03-31 19:43 UTC, caupolicandiaz commented on content/pandas/concepts/dataframe/terms/copy/copy.md
> +| Parameter Name | Data Type                | Usage                                                                                                                             |
Yes, please remove them.

2023-03-31 23:35 UTC, caupolicandiaz approved these changes
@xenos92 This is ready for another review.

2023-04-01 13:59 UTC, SSwiniarski requested changes
@xenos92 I did a review and only had one comment.

2023-04-01 13:59 UTC, SSwiniarski commented on content/pandas/concepts/dataframe/terms/copy/copy.md
> +- In a deep copy, a new object is created with a completely new set of data that is identical to the original data. Changes made to the copied object will not affect the original object and vice vers
```suggestion
- In a deep copy, a new object is created with a completely new set of data that is identical to the original data. Changes made to the copied object will not affect the original object and vice versa. 
```

2023-04-02 13:33 UTC, SSwiniarski approved these changes

2023-04-02 13:33 UTC, merged

2023-04-02 13:40 UTC, SSwiniarski commented
@xenos92 Congrats on the new entry. Live link is here: https://www.codecademy.com/resources/docs/pandas/dataframe/copy

You're currently listed as an anonymous contributor. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.

![image](https://user-images.githubusercontent.com/86081858/229356474-8e10f94f-928e-467d-ba04-091b1cd95d7c.png)

To add your GitHub username to your Codecademy profile:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

![image](https://user-images.githubusercontent.com/86081858/229356502-16c1ee39-25b1-4352-958f-98df70ae155a.png)

2.) Then log out and log back into Codecademy using your GitHub login:

![image](https://user-images.githubusercontent.com/86081858/229356534-0a62a05c-be69-46f6-8b81-05541cf99710.png)

Note: Your email used for Codecademy will have to be listed in your GitHub profile for the login feature to properly work. If you use the same email for both GitHub and Codecademy already, then you're set.

2023-04-04 16:10 UTC, SSwiniarski commented
@yangc95, @KTom101, @caupolicandiaz, any Idea why the entry is still anonymous?

2023-04-09 00:20 UTC, KTom101 commented
@xenos92 Did you also verify that you have the same email for Codecademy listed under your GitHub profile?

2023-04-10 20:08 UTC, yangc95 commented
@xenos92 on Codecademy, is your privacy set to this:

<img width="537" alt="Screenshot 2023-04-10 at 4 07 30 PM" src="https://user-images.githubusercontent.com/72277593/230988453-0485b387-eb93-45e5-920d-ddb4f0c29cfb.png">

2023-04-11 04:37 UTC, KTom101 commented
@xenos92 It is under your Codecademy profile, the same page you entered your GitHub username. Scroll down to the bottom and the privacy details will be there.

2023-04-14 23:17 UTC, KTom101 commented
@xenos92 It looks like you're listed now:

![image](https://user-images.githubusercontent.com/40783324/232169416-08e1ad00-38d2-4743-94b6-11b0d14da274.jpeg)