C_enums
Codecademy/docs pull request #1909
Opened 2023-03-31 03:29 UTC by RodMe27

### Description

This document is the first documentation of the keyword "enum" for the programming lenguage C.
Closes #1872

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-03-31 03:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1909) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1909) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1909) it.</sub>

2023-03-31 16:34 UTC, SSwiniarski reviewed
@RodMe27, I did a first review and left a few comments.

2023-03-31 16:34 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +# Enum
This entry is missing the required metadata. To understand what to put here, please read the [metadata section in the style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#metadata). The metadata should look like this:

```
---
Title: 'The Title'
Description: 'A brief description'
Subjects:
  - 'A subject name'
  - 'A second subject name'
  - 'An nth subject name'
Tags:
  - 'A tag'
  - 'A second tag'
  - 'An nth tag'
CatalogContent:
  - 'learn-example-course'
  - 'path/example-path'
---

Also, we do not have h1 headers to title Doc entries, the title in the metadata does this automatically.

2023-03-31 16:34 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +## Another Example
You don't need these two examples. The second example below illustrates the same thing. I'd remove these first two, and move that second example below so it's the first example.

2023-03-31 16:34 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +## Note
```suggestion
## Examples 
```

2023-03-31 16:34 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +### 1. Two enum names can have the same value. For instance, both ‘Running’ and ‘In_Progress’ have the same value of 1.
```suggestion
Two `enum` names can have the same value. For instance, both `Running` and `In_Progress` have the same value of 1.
```
These are not appropriate as headers.

2023-03-31 16:34 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +#### Output
```suggestion
This example results in the following output.
```

2023-03-31 16:34 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +### 2. If we do not explicitly assign values to enum MemberName, the compiler by default assigns values starting from 0. For instance, Sunday gets a value of 0, Monday gets 1, and so on.
```suggestion
If we do not explicitly assign values to `enum` `day`, the compiler by default assigns values starting from 0. For instance, `sunday` gets a value of 0, `monday` gets 1, and so on.
```

Can we also move this so it is the first example?

2023-03-31 16:34 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +#### Output
```suggestion
This example results in the following output:
```

2023-03-31 16:34 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +### 3. We can assign values to a particular name in any order. All unassigned names get value as the value of the previous name plus one.
```suggestion
We can assign values to a particular name in any order. All unassigned names get value as the value of the previous name plus one.
```

2023-03-31 16:34 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +#### Output
```suggestion
This example results in the following output:
```

2023-03-31 16:34 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +### 4.  All enum constants must be unique in their scope.
```suggestion
> **Note:**  All `enum` constants must be unique in their scope.
```

2023-03-31 17:54 UTC, RodMe27 commented
@SSwiniarski changes has been updated and push to the branch.

2023-04-01 13:44 UTC, SSwiniarski requested changes
@RodMe27 a few more comments.

2023-04-01 13:44 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +  - 'Variable Type'
```suggestion
  - 'Variable Types'
```

2023-04-01 13:44 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +  - 'Enums'
```suggestion
  - 'Enum'
```

2023-04-01 13:44 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +	memberName1 = <integral constant>,
```suggestion
  memberName1 = <integral constant>,
```

2023-04-01 13:44 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +	memberName2,
```suggestion
  memberName2,
```

2023-04-01 13:44 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +	memberName3,
```suggestion
  memberName3,
```

2023-04-01 13:44 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +	...
```suggestion
  ...
```

2023-04-01 13:44 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +	memberNameN
```suggestion
  memberNameN
```

2023-04-03 16:03 UTC, RodMe27 commented
@SSwiniarski New changes review committed.

2023-04-03 16:08 UTC, SSwiniarski requested changes
@RodMe27, last few comments.

2023-04-03 16:08 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +Description: 'Enum is used to assign custom names to integral constants'
```suggestion
Description: 'An enum is used to assign custom names to integral constants.'
```

2023-04-03 16:08 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +A **enum** (enumeration) is a user-defined data type in C. It is used to assign names to integral constants, the principal purpose of this names is to create a program that is easy to read and mainta
```suggestion
An **enum** (enumeration) is a user-defined data type in C. It is used to assign names to integral constants. The principal purpose of these names is to create a program that is easy to read and maintain. It is defined using the `enum` keyword.
```

2023-04-03 16:08 UTC, SSwiniarski commented on content/c/concepts/enums/enums.md
> +If we do not explicitly assign values to `enum` `day`, the compiler by default assigns values starting from 0. For instance, `sundays` gets a value of 0, `monday` gets 1, and so on.
```suggestion
If we do not explicitly assign values to `enum` `day`, the compiler by default assigns values starting from 0. For instance, `sunday` gets a value of 0, `monday` gets 1, and so on.
```

2023-04-03 16:14 UTC, RodMe27 commented
Changes committed, thanks for the comments @SSwiniarski

2023-04-03 16:18 UTC, SSwiniarski approved these changes
@RodMe27 Looks good for a second review.

2023-04-11 20:03 UTC, caupolicandiaz requested changes
@RodMe27 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-04-11 20:03 UTC, caupolicandiaz commented on content/c/concepts/enums/enums.md
> +An enum is made up of members where each `memberName` can have a defined integral constant (i.e. 0, 10, 2) or just the `memberName`.
```suggestion
An enum is made up of members where each `memberName` can have a defined integral constant (e.g. 0, 10, 2) or just the `memberName`.
```

2023-04-19 23:22 UTC, caupolicandiaz commented
@RodMe27 It's been over a week since I posted the review on this PR, do you need any assistance with the changes?

2023-05-12 16:21 UTC, SSwiniarski commented
@RodMe27 in the interest of getting this merged, I addressed @caupolicandiaz's comments myself. @caupolicandiaz, do we look good to merge this now?

2023-05-12 19:22 UTC, caupolicandiaz approved these changes
@RodMe27 @SSwiniarski Looks good to merge. I just made a couple minor edits.

2023-05-12 19:23 UTC, merged

2023-05-13 13:12 UTC, SSwiniarski commented
@RodMe27 Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/c/enums

![image](https://github.com/Codecademy/docs/assets/86081858/6d829ca2-bd9d-4986-b886-ff250fe4e489)