Create trim.md
Codecademy/docs pull request #1914
Opened 2023-04-01 07:38 UTC by Captain-Arnab

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-04-01 07:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1914) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1914) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1914) it.</sub>

2023-04-02 14:33 UTC, SSwiniarski requested changes
@Captain-Arnab I did a first review and left some comments. There may be more after you address these.

2023-04-02 14:33 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/trim/trim.md
> +Description: 'Strip whitespace (or other characters) from the beginning and end of a string' # Required; ideally under 150 characters and starts with a noun (used in search engine results and content
```suggestion
Description: 'Strips whitespace (or other characters) from the beginning and end of a string.' # Required; ideally under 150 characters and starts with a noun (used in search engine results and content previews)
```

2023-04-02 14:33 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/trim/trim.md
> +`trim()` returns a string with whitespace stripped from the beginning and end of string.
```suggestion
The **`trim()`** function returns a string with whitespace stripped from the beginning and end of string.
```

2023-04-02 14:33 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/trim/trim.md
> +## Codebyte Example (if applicable)
```suggestion
## Codebyte Example
```

2023-04-02 14:33 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/trim/trim.md
> +```
This block needs to start with ` ```codebyte/php `.
It also needs a sentence preceding it, describing what it does.

2023-04-02 14:33 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/trim/trim.md
> +## Pseudo Code:
```suggestion
## Syntax
```

2023-04-02 14:33 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/trim/trim.md
> +`trim(string $string, string $characters = " \n\r\t\v\x00"): string`
This should be in a ` ```pseudo ` code block, not single backticks.

2023-04-02 14:33 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/trim/trim.md
> +Parameters:
Rewrite this Parameters section by removing the line of dashes and organizing the parameters in a bulleted list like this:

- `string`: The string that will be trimmed.
- `characters`: Optionally, the stripped characters can also be specified using the characters parameter.

Also, rewrite to remove the use of the "you" pronoun.

2023-04-02 14:33 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/trim/trim.md
> +## Syntax
Remove this section.

2023-04-26 15:27 UTC, SSwiniarski commented
@Captain-Arnab It's been over two weeks, do you need assistance addressing these changes?

2023-04-30 12:22 UTC, Captain-Arnab commented
@SSwiniarski I have committed the changes. Please check those.

On Wed, Apr 26, 2023 at 8:57 PM SSwiniarski ***@***.***>
wrote:

> @Captain-Arnab <https://github.com/Captain-Arnab> It's been over two
> weeks, do you need assistance addressing these changes?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Codecademy/docs/pull/1914#issuecomment-1523616228>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVLRCTDBZ4P6IRD2WMWZ4LLXDE5GXANCNFSM6AAAAAAWPPAMR4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-30 13:39 UTC, SSwiniarski commented
@Captain-Arnab I don't see your changes. Did you make commits to the branch this PR is based on?

2023-05-12 16:23 UTC, SSwiniarski commented
@Captain-Arnab your changes never made it to this PR, do you need assistance?

2023-05-26 12:59 UTC, SSwiniarski commented
@Captain-Arnab It's been another two weeks, are you still working on this PR?

2023-05-27 15:28 UTC, SSwiniarski approved these changes
@Captain-Arnab because of the inactivity, I addressed the concerns myself so we can move on to a second review.

2023-08-02 23:28 UTC, yangc95 commented on content/php/concepts/string-functions/terms/trim/trim.md
> +  - Spaces `" "` \n\r\t\v\x00"
```suggestion
  - Spaces `" "`
```

2023-08-02 23:28 UTC, yangc95 approved these changes

2023-08-02 23:31 UTC, merged

2023-08-02 23:32 UTC, yangc95 commented
Thanks for your contribution @Captain-Arnab 👍

Live link: https://www.codecademy.com/resources/docs/php/string-functions/trim

cc: @SSwiniarski