Conditionals
Codecademy/docs pull request #1916
Opened 2023-04-01 12:41 UTC by VisnetAppel

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

I've accidently closed it on my side I believe. @yangc95 i've applied your feedback

2023-04-01 12:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1916) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1916) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: VisnetAppel<br/>:x: Vincent Meeuws<br/><hr/>**Vincent Meeuws** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1916) it.</sub>

2023-04-01 20:13 UTC, yangc95 commented
@VisnetAppel it looks like your GitHub and git configurations may not done under the e-mail:
<img width="623" alt="Screenshot 2023-04-01 at 4 09 31 PM" src="https://user-images.githubusercontent.com/72277593/229311989-35748727-7e61-4fb0-ba94-a3459fb7408a.png">

I'd recommend taking a look at these three resource to make sure git is set up properly.
https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address

In the meantime, I'll also be taking a look at this PR for the corrections that you made from PR [1759](https://github.com/Codecademy/docs/pull/1759). If I have further comments I'll tag you, otherwise I'll pass this on for a second review.

2023-04-15 23:09 UTC, yangc95 approved these changes
@VisnetAppel Did rewording on this entry, although if there is anything that you spot, feel free to adjust. 

Please look over the changes I made here and let me know if you have any questions.
https://github.com/Codecademy/docs/pull/1916/commits/1eaeee1617d9f9d2b76e2d864d459cafea83c182
https://github.com/Codecademy/docs/pull/1916/commits/80436455058258d1ec2fd0a5fc08fb3a3c21b813

Otherwise, looks good for a second review!

Making note here that this can benefit (future iterations) with `switch` statement and `for` loop. In addition, perhaps some operators can be mentioned (up for discussion).

2023-04-17 20:55 UTC, caupolicandiaz requested changes
@VisnetAppel I've added some additional edits. Please update the entry, and tag me when you've finished making changes. Thanks

2023-04-17 20:55 UTC, caupolicandiaz commented on content/c-sharp/concepts/conditionals/conditionals.md
> +  - 'learn-typescript'
```suggestion
  - 'learn-c-sharp'
```

2023-04-17 20:55 UTC, caupolicandiaz commented on content/c-sharp/concepts/conditionals/conditionals.md
> +The conditional operator `?:` also known as the ternary operator, checks a boolean output and returns one of two results depending wether the condition is true or false. The ternary operator can be r
```suggestion
The conditional operator `?:` also known as the ternary operator, checks a boolean output and returns one of two results depending on whether the condition is true or false. The ternary operator can be read in pseudocode as follows:
```

2023-04-17 20:55 UTC, caupolicandiaz commented on content/c-sharp/concepts/conditionals/conditionals.md
> +```cs
```suggestion
```pseudo
```

2023-04-17 20:55 UTC, caupolicandiaz commented on content/c-sharp/concepts/conditionals/conditionals.md
> +## `if` Statement
```suggestion
## If Statement
```

2023-04-17 20:55 UTC, caupolicandiaz commented on content/c-sharp/concepts/conditionals/conditionals.md
> +## `if` Statement
we generally don't use backticks in headers

2023-04-17 20:55 UTC, caupolicandiaz commented on content/c-sharp/concepts/conditionals/conditionals.md
> +### `else` Statements
```suggestion
### Else Statements
```

2023-04-17 20:55 UTC, caupolicandiaz commented on content/c-sharp/concepts/conditionals/conditionals.md
> +### `else if` Statements
```suggestion
### Else If Statements
```

2023-04-17 20:55 UTC, caupolicandiaz commented on content/c-sharp/concepts/conditionals/conditionals.md
> +In the example below, three variables (`var`) and assigned values. Then, an `if` statement checks for a condition; if it evaluates to true, then the variable of boolean type will change:
```suggestion
In the example below, three variables are declared and assigned values. Then, an `if` statement checks for a condition; if it evaluates to true, then the variable of boolean type will change:
```

2023-04-27 05:00 UTC, caupolicandiaz approved these changes
@VisnetAppel @yangc95 I've gone ahead and made the edits I had suggested in my review, so we can move this entry along. I think this is good to go.

2023-05-01 12:50 UTC, VisnetAppel commented
Thanks. sorry for the late replies.

Is there a way to remove Vincent Meeuws from the CLA? I can't get it
verified and have changed the name for uploads now so it shouldn't be added
again.

Is there something else needed from me?

Op do 27 apr 2023 om 07:00 schreef caupolicandiaz ***@***.***
>:

> ***@***.**** approved this pull request.
>
> @VisnetAppel <https://github.com/VisnetAppel> @yangc95
> <https://github.com/yangc95> I've gone ahead an made the edits I had
> suggested in my review, so we can move this entry along. I think this is
> good to go.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Codecademy/docs/pull/1916#pullrequestreview-1403180595>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2ITYGKOR5MW4K5OJOREWILXDH4OBANCNFSM6AAAAAAWPTQQJI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-03 13:01 UTC, merged

2023-05-03 13:35 UTC, SSwiniarski commented
@VisnetAppel congrats on your new entry. Live link here: https://www.codecademy.com/resources/docs/c-sharp/conditionals

@yangc95, @KTom101, @caupolicandiaz This is another one where the maintainers are being listed as the contributors. Do we know what's causing this?
  
![image](https://user-images.githubusercontent.com/86081858/235931490-66e22f80-5f93-427f-8f8a-13b5fd19cb83.png)

2023-05-10 15:12 UTC, yangc95 commented
@VisnetAppel judging from the CLA, it looks like more than one e-mail was used to push up changes (this could also be because GitHub defaulted to a private e-mail for you)

Make sure that your GitHub handle is correct on your Codecademy profile and that your visibility is set to everyone. Then log back in with the GitHub option and confirm that you were logged into your actual Codecademy account.

cc: @SSwiniarski