remove spaces
Codecademy/docs pull request #1925
Opened 2023-04-03 07:34 UTC by Pavan-04-08

### Description
acc to https://github.com/Codecademy/docs/pull/1526#issuecomment-1485551055

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-04-03 16:20 UTC, SSwiniarski approved these changes
@Pavan-04-08 looks good for a second review.

2023-04-09 05:00 UTC, KTom101 requested changes
@Pavan-04-08 There is one more change needed.

2023-04-09 06:07 UTC, Pavan-04-08 commented on content/go/concepts/functions/functions.md
hmm there is a new line after 30? @KTom101 
![image](https://user-images.githubusercontent.com/92514129/230757429-ad44db82-e984-4308-89d1-3c22fa1b0e60.png)

2023-04-09 06:09 UTC, Pavan-04-08 commented on content/go/concepts/functions/functions.md
if its refering to 29,30 line in between 29 and 30? 
to combine them i am not actually sure how to place that explaination into 1 line

2023-04-09 19:47 UTC, yangc95 commented on content/go/concepts/functions/functions.md
Yes, it looks like line 30 is now line 29.

In which case, can we add a line between 29+30? In addition, can we rephrase to say that parameters are passed-by-value or passed-by-copy, meaning the function receives...

Also when it says "To modify the parameter, pass a pointer," would you be able to expand on this for me? Do we mean the parameter should be of pointer type? Thanks for any info you can provide

2023-04-10 14:16 UTC, Pavan-04-08 commented on content/go/concepts/functions/functions.md
yeah it should be pointer type , like say

2023-04-10 14:17 UTC, Pavan-04-08 commented on content/go/concepts/functions/functions.md
```
func main() {
    changeMe := 10
    modify(&x)
    fmt.Println(changeMe) //prints smthng idk whatever modify changes it
}
```

this is kinda similar to any other lang ig not go only thing so i kept it simple

2023-04-10 18:11 UTC, KTom101 approved these changes
@Pavan-04-08 👍

2023-04-10 18:13 UTC, merged