Add Entry: PHP String Function term hex2bin() #1895
Codecademy/docs pull request #1932
Opened 2023-04-03 18:41 UTC by sriharshamajeti

### Description

Add entry for PHP string functions and new term for it, `hex2bin()`.

### Type of Change

- Adding a new entry

### Checklist

- [ x ] All writings are my own.
- [ x ] My entry follows the Codecademy Docs style guide.
- [ x ] My changes generate no new warnings.
- [ x ] I have performed a self-review of my own writing and code.
- [ x ] I have checked my entry and corrected any misspellings.
- [ x ] I have made corresponding changes to the documentation if needed.
- [ x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-04-03 18:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1932) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1932) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1932) it.</sub>

2023-04-04 16:47 UTC, SSwiniarski requested changes
@sriharshamajeti I did a first review and left a few comments, basically around formatting your "Note". In docs we format these with a blockquote and a bolded "Note:" on the same line, like this:

```
> **Note:** Text of note.
```

2023-04-04 16:47 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/hex2bin/hex2bin.md
> +**Note**:
```suggestion
```

2023-04-04 16:47 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/hex2bin/hex2bin.md
> +- This function does **NOT** convert a hexadecimal number to a binary number.
```suggestion
> **Note:** This function does **NOT** convert a hexadecimal number to a binary number.
```

2023-04-04 16:47 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/hex2bin/hex2bin.md
> +- The `hex2bin()` function is available only in PHP 5.4.0 and later versions.
```suggestion
The `hex2bin()` function is available only in PHP 5.4.0 and later versions.
```

2023-04-04 16:47 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/hex2bin/hex2bin.md
> +
```suggestion
```

2023-04-05 16:19 UTC, SSwiniarski approved these changes
@sriharshamajeti looks good for a second review.

2023-04-05 16:32 UTC, sriharshamajeti commented
Hi @SSwiniarski one of the tests is failing -> `format:verify` what is wrong with the PR, as the name suggests is there something I am missing in the format?

2023-04-06 18:07 UTC, sriharshamajeti commented
Thank you @SSwiniarski , will sure keep in mind.

2023-04-30 03:14 UTC, KTom101 requested changes
@sriharshamajeti I've added another review.

2023-04-30 03:14 UTC, KTom101 commented on content/php/concepts/string-functions/terms/hex2bin/hex2bin.md
> +The `hex_string` parameter represents the hexadecimal values to be converted.
```suggestion
The `hex_string` parameter represents the string of hexadecimal values to be converted.
```

2023-05-12 16:26 UTC, SSwiniarski commented
@sriharshamajeti In the interest of getting this merged, I implemented @KTom101's suggestions.

2023-05-12 16:27 UTC, SSwiniarski commented
@KTom101, are we ready to merge?

2023-05-12 23:48 UTC, KTom101 commented
@sriharshamajeti So you know for future entries, please make a new feature branch for every entry. We discourage working off your `main` branch. 

In regards to the tests, I ran `npm run format:all` to fix the checks.

2023-05-12 23:48 UTC, KTom101 approved these changes

2023-05-12 23:49 UTC, merged

2023-05-12 23:54 UTC, KTom101 commented
@sriharshamajeti Link is live: https://www.codecademy.com/resources/docs/php/string-functions/hex2bin

![image](https://github.com/Codecademy/docs/assets/40783324/8d5970c8-4967-45cb-abc8-56a5a25f29cc)

Cc @yangc95