ROSHAN ISSUE #1919
Codecademy/docs pull request #1938
Opened 2023-04-04 16:34 UTC by Roshanbhadauriya

Broken Links Audit: Entries 41-50. Solved

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-04-04 16:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1938) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1938) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1938) it.</sub>

2023-04-04 19:55 UTC, caupolicandiaz requested changes
@Roshanbhadauriya I've completed my review, there are just a few edits to be made. Please update the entry, and tag me when you've finished making changes.

2023-04-04 19:55 UTC, caupolicandiaz commented on content/uiux/concepts/wireframe/wireframe.md
> +Wireframes are like rough drafts that help determine a solution for the structure ([information architecture](https://www.codecademy.com/resources/docs/uiux/information-architecture) and [interaction
```suggestion
Wireframes are like rough drafts that help determine a solution for the structure ([information architecture](https://www.codecademy.com/resources/docs/uiux/information-architecture) and [interaction design](https://www.codecademy.com/resources/docs/uiux/ux-design)) and skeleton ([interface design](https://www.codecademy.com/resources/docs/uiux/ui-design), [navigation design](https://www.codecademy.com/resources/docs/uiux/navigation), information design) layers of the [Five Elements of UX Design](https://www.codecademy.com/resources/docs/uiux/five-elements-of-ux-design).
```

2023-04-04 19:55 UTC, caupolicandiaz commented on content/uiux/concepts/wireframe/wireframe.md
> +Wireframes are like rough drafts that help determine a solution for the structure ([information architecture](https://www.codecademy.com/resources/docs/uiux/information-architecture) and [interaction
we don't have a current resource for information-design, so I removed the link

2023-04-04 19:55 UTC, caupolicandiaz commented on content/uiux/concepts/design-software/design-software.md
> +**Design software** is useful when creating user interface (UI) and user experience (UX) deliverables such as [wireframes](https://www.codecademy.com/resources/docs/uiux/wireframe), interactive proto
```suggestion
**Design software** is useful when creating user interface (UI) and user experience (UX) deliverables such as [wireframes](https://www.codecademy.com/resources/docs/uiux/wireframe), interactive prototypes, [personas](https://www.codecademy.com/resources/docs/uiux/persona), [user workflows](https://www.codecademy.com/resources/docs/uiux/user-workflows), and [site maps](https://www.codecademy.com/resources/docs/uiux/site-map), to name a few.
```

2023-04-05 07:53 UTC, Roshanbhadauriya commented
@caupolicandiaz I have updated the changes that you suggest.

2023-04-05 19:37 UTC, caupolicandiaz approved these changes
@Roshanbhadauriya Looks good.

2023-04-06 05:05 UTC, Roshanbhadauriya commented
@caupolicandiaz Thank you for the opportunity, this is my contribution.

2023-04-15 23:17 UTC, yangc95 commented on content/uiux/concepts/qualitative-research/qualitative-research.md
> +- [UserZoom: UX research methods - a comprehensive guide](https://www.userzoom.com/ux-research/)
```suggestion
- [UserZoom: UX research methods - a comprehensive guide](https://www.userzoom.com/ux-research/methods/)
```

2023-04-15 23:18 UTC, yangc95 approved these changes

2023-04-16 02:27 UTC, merged

2023-04-16 16:51 UTC, yangc95 commented
Thanks @Roshanbhadauriya for your contribution!

Edits should appear here: UIUX: [Button](https://www.codecademy.com/resources/docs/uiux/button), [Design Software](https://www.codecademy.com/resources/docs/uiux/design-software), [Homepage](https://www.codecademy.com/resources/docs/uiux/homepage), [Image](https://www.codecademy.com/resources/docs/uiux/image), [Opacity](https://www.codecademy.com/resources/docs/uiux/opacity), [Qualitative Research](https://www.codecademy.com/resources/docs/uiux/qualitative-research), [Search Fields](https://www.codecademy.com/resources/docs/uiux/search-fields), [Sketching](https://www.codecademy.com/resources/docs/uiux/sketching), [Wireframe Elements](https://www.codecademy.com/resources/docs/uiux/wireframe-elements), [Wireframe](https://www.codecademy.com/resources/docs/uiux/wireframe)

@caupolicandiaz