added baselineOffset concept to SwiftUI viewmodifier terms
Codecademy/docs pull request #1940
Opened 2023-04-04 23:17 UTC by jfelix9

### Description

Closes [#1569](https://github.com/Codecademy/docs/issues/1569) . Added a the .baselineOffset() view modifier term under SwiftUI with an image.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-04-04 23:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1940) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1940) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1940) it.</sub>

2023-04-06 15:37 UTC, SSwiniarski requested changes
@jfelix9 I did a first review and had a couple of comments.

2023-04-06 15:37 UTC, SSwiniarski commented on content/swiftui/concepts/viewmodifier/terms/baselineOffset/baselineOffset.md
> +- `baselineOffset` specifies how many points the text is shifted up or down. The following options are possible:
This line and the following table is misleading, implying that 0,5,-5 are the only valid options. Simply say the parameter can be positive, negative or zero.

2023-04-13 01:27 UTC, jfelix9 commented
Hi @SSwiniarski I fixed the grammatical mistakes and replaced the misleading parts.

2023-04-13 16:13 UTC, SSwiniarski requested changes
@jfelix9 I had a couple more comments.

2023-04-13 16:13 UTC, SSwiniarski commented on content/swiftui/concepts/viewmodifier/terms/baselineOffset/baselineOffset.md
> +The **`.baselineOffset()`** modifier method moves text in a view [view](https://www.codecademy.com/resources/docs/swiftui/views) vertically relative to its baseline. The bounds of the text's parent v
```suggestion
The **`.baselineOffset()`** modifier method moves text in a view [view](https://www.codecademy.com/resources/docs/swiftui/views) vertically relative to its baseline. The bounds of the text's parent view expands to contain the modified text.
```
```suggestion
The **`.baselineOffset()`** modifier method moves text in a [view](https://www.codecademy.com/resources/docs/swiftui/views) vertically relative to its baseline. The bounds of the text's parent view expands to contain the modified text.
```

2023-04-13 16:13 UTC, SSwiniarski commented on content/swiftui/concepts/viewmodifier/terms/baselineOffset/baselineOffset.md
> +
```suggestion
```
remove line break between bullet points.

2023-04-13 22:46 UTC, jfelix9 commented
Hi @SSwiniarski , I've implemented the recommended changes, ready for review

2023-04-14 16:15 UTC, SSwiniarski approved these changes
@jfelix9 looks good for a second review.

2023-04-26 16:29 UTC, yangc95 commented on content/swiftui/concepts/viewmodifier/terms/baselineOffset/baselineOffset.md
> +    }
I nested this in a stack. Can you include the background color you used?

2023-04-27 02:31 UTC, jfelix9 commented
Hi @yangc95 I've added the color and padding to the stack to have it match the image

2023-05-01 19:26 UTC, yangc95 approved these changes

2023-05-01 19:27 UTC, merged

2023-05-01 20:34 UTC, yangc95 commented
🙌 Neat! @jfelix9 live link: https://www.codecademy.com/resources/docs/swiftui/viewmodifier/baselineOffset

<img width="806" alt="Screenshot 2023-05-01 at 4 32 44 PM" src="https://user-images.githubusercontent.com/72277593/235526212-e1d57624-d5e7-4068-ab20-902eb422170d.png">

cc: @SSwiniarski @KTom101