Term entry c sharp compare
Codecademy/docs pull request #1943
Opened 2023-04-05 10:08 UTC by cslylla

### Description

- Added new term for C# String methods: .Compare()
- Closes #1833 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-04-05 20:41 UTC, caupolicandiaz requested changes
@cslylla I've completed my initial review. Please update the entry and tag me when you've finished making changes. Thanks

2023-04-05 20:41 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/compare/compare.md
> +In the following runnable example, the `.Compare()` method determines the alphabetical order of the given `string1` and `string2`, while the letter casing is ignored. Finally, the `WriteLine()` metho
```suggestion
In the following runnable example, the `.Compare()` method determines the alphabetical order of `string1` and `string2`, while the letter casing is ignored. Finally, the `WriteLine()` method prints the returned integer to the console.
```

2023-04-05 20:41 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/compare/compare.md
> +- a negative `integer` if `string1` comes before `string2`
```suggestion
- `-1` if `string1` comes before `string2`
```

2023-04-05 20:41 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/compare/compare.md
> +- a positive `integer` if `string2` comes before `string1`
```suggestion
- `1` if `string2` comes before `string1`
```

2023-04-05 20:41 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/compare/compare.md
> +> **Note:** `ignoreCase` is an optional `boolean` type argument. By default, `false` or not specified, the `.Compare()` method is case-sensitive. Passing `true` as the third argument makes the`.Compa
```suggestion
> **Note:** `ignoreCase` is an optional `boolean` type argument. By default the `.Compare()` method is case-sensitive. Passing `true` as the third argument makes the `.Compare()` method case insensitive.
```

2023-04-05 20:41 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/compare/compare.md
> +The `.Compare()` method is called on the `String` class. It takes two `string` type arguments, `string1` and `string2`, to compare them alphabetically.
```suggestion
The `.Compare()` method is called on the `String` class. It takes two `string` type arguments, `string1` and `string2`,  and compares them alphabetically.
```

2023-04-05 20:41 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/compare/compare.md
> +String.Compare(string1, string2, `ignoreCase`);
```suggestion
String.Compare(string1, string2, ignoreCase);
```

2023-04-05 20:41 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/compare/compare.md
> +Description: 'Compares two specified strings in alphabetical order and returns an integer that represents their relative order.'
```suggestion
Description: 'Compares the alphabetical order of two strings and returns an integer that represents their relative ranking.'
```

2023-04-05 20:41 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/compare/compare.md
> +The **`.Compare()`** method is a string method that compares two specified [`strings`](https://www.codecademy.com/resources/docs/c-sharp/strings) in alphabetical order and returns an integer that rep
```suggestion
The **`.Compare()`** method is a string method that compares the alphabetical order of two specified [`strings`](https://www.codecademy.com/resources/docs/c-sharp/strings) and returns an integer that represents their relative ranking.
```

2023-04-06 08:02 UTC, cslylla commented
@caupolicandiaz I accepted the changes.

2023-04-06 19:41 UTC, caupolicandiaz approved these changes
@cslylla  All set!

2023-04-16 02:27 UTC, yangc95 approved these changes

2023-04-16 02:37 UTC, yangc95 commented on content/c-sharp/concepts/strings/terms/compare/compare.md
> +- `ignoreCase` is an optional `boolean` type argument. By default the `.Compare()` method is case-sensitive. Passing `true` as the third argument makes the `.Compare()` method case insensitive.
```suggestion
- `ignoreCase` is an optional `boolean` type argument. By default the `.Compare()` method is case-sensitive. Passing `true` as the third argument makes the `.Compare()` method case-insensitive.
```

2023-04-16 16:31 UTC, merged

2023-04-16 16:40 UTC, yangc95 commented
🙌 Always a pleasure reviewing your contributions ☺️  @cslylla live link: https://www.codecademy.com/resources/docs/c-sharp/strings/compare

cc: @caupolicandiaz