Add `scaledToFill` ViewModifier documentation and example
Codecademy/docs pull request #1946
Opened 2023-04-07 17:12 UTC by JaredDanielJones

### Description

This pull request adds documentation and an example for the `scaledToFill` ViewModifier in SwiftUI. The following changes have been made:

1. Created a new folder: `content/swiftui/concepts/viewmodifier/terms/scaledToFill`
2. Added the `scaledToFill.md` file in the new folder, which contains an explanation of the `scaledToFill` ViewModifier and its usage.
3. Included an example image: `media/swiftui-viewmodifier-scaledToFill.png` to demonstrate the effect of the `scaledToFill` ViewModifier.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-04-07 17:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1946) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1946) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1946) it.</sub>

2023-04-19 02:11 UTC, yangc95 approved these changes
@JaredDanielJones Awesome!

2023-04-21 16:33 UTC, SSwiniarski requested changes
@JaredDanielJones Good entry. I did a second review and only had one comment.

2023-04-21 16:33 UTC, SSwiniarski commented on content/swiftui/concepts/viewmodifier/terms/scaledToFill/scaledToFill.md
> +The image on the left shows the circle without the **`.scaledToFill()`** modifier applied. The image on the right shows the circle with the **`.scaledToFill()`** modifer applied.
```suggestion
The image on the left shows the circle without the `.scaledToFill()` modifier applied. The image on the right shows the circle with the `.scaledToFill()` modifier applied.
```

2023-05-01 16:14 UTC, SSwiniarski approved these changes
@JaredDanielJones Looks good.

2023-05-01 16:14 UTC, merged

2023-05-01 16:18 UTC, SSwiniarski commented
@JaredDanielJones congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/swiftui/viewmodifier/scaledToFill

You're currently listed as an anonymous contributor. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.

![image](https://user-images.githubusercontent.com/86081858/235486016-0962a427-7cfd-4c19-801a-3d650f297a69.png)

To add your GitHub username to your Codecademy profile:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

![image](https://user-images.githubusercontent.com/86081858/235486077-6f014dbf-6e8c-40f6-a0ee-5fda9c526b4a.png)

2.) Then log out and log back into Codecademy using your GitHub login:

![image](https://user-images.githubusercontent.com/86081858/235486154-6522304e-d597-4eda-bc38-383f083ec5a0.png)

**Note**: Your email used for Codecademy will have to be listed in your GitHub profile for the login feature to properly work. If you use the same email for both GitHub and Codecademy already, then you're set.