Added `Interfaces.md` in the kotlin folder
Codecademy/docs pull request #1948
Opened 2023-04-07 17:48 UTC by dakshdeepHERE

### Description

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

Fixes #1949

2023-04-07 18:46 UTC, SSwiniarski requested changes
@dakshdeepHERE I did a first review and left a couple of comments.

2023-04-07 18:46 UTC, SSwiniarski commented on content/kotlin/concepts/Interfaces/Interfaces.md
> +Description: 'Interface are like abstract class describing methods and variables that should exist in any class that implements the interface.'
```suggestion
Description: 'Interfaces are an abstract class describing methods and variables that should exist in any class that implements the interface.'
```

2023-04-07 18:46 UTC, SSwiniarski commented on content/kotlin/concepts/Interfaces/Interfaces.md
> +An **interface** is a type that defines a set of methods and properties that a class can implement. It provides a way to define a contract between the implementing class and the calling code. An inte
```suggestion
An **interface** is a type that defines a set of methods and properties that a class can implement. It provides a way to define a contract between the implementing class and the calling code. An interface can be thought of as a blueprint for a class, where the class must implement all the methods and properties defined in the interface.
```

2023-04-08 18:16 UTC, dakshdeepHERE commented
done @SSwiniarski

2023-04-08 18:59 UTC, SSwiniarski approved these changes
@dakshdeepHERE Looks good for a second review.

2023-04-18 22:45 UTC, merged

2023-04-18 22:46 UTC, yangc95 commented
🙌 @dakshdeepHERE live link: https://www.codecademy.com/resources/docs/kotlin/interfaces

cc: @KTom101 @SSwiniarski

2023-04-18 22:49 UTC, yangc95 commented
@dakshdeepHERE Actually, it looks like the folder and file names are capitalized instead of lower-cased. Can you open a new PR and adjust this? Thanks!

2023-04-19 09:00 UTC, dakshdeepHERE commented
@yangc95 I did small in start only if you check the commits but I checked the java folder there it was starting with "I" so K recommitted it.

2023-04-24 20:01 UTC, yangc95 commented
@dakshdeepHERE I don't see any commits on your feature branch. Would you be able to create a PR and we can go from there?

2023-04-26 16:40 UTC, dakshdeepHERE commented
@yangc95 yes I renamed the folder but see when I do git status there is no changes shown I dont know why
<img width="416" alt="image" src="https://user-images.githubusercontent.com/94860622/234644555-82d42a4e-81f0-4236-854e-01acf825bf15.png">
<img width="316" alt="image" src="https://user-images.githubusercontent.com/94860622/234644587-5b40936f-c9b7-47fb-8072-ad7b1ad5ce7f.png">
Why is that?

2023-04-26 16:45 UTC, dakshdeepHERE commented
see even the file name changes arent showing as changes 
<img width="345" alt="image" src="https://user-images.githubusercontent.com/94860622/234645233-f7cec154-a6a2-49ba-ac29-206e7c354ba6.png">
<img width="363" alt="image" src="https://user-images.githubusercontent.com/94860622/234645255-bc140709-3d9f-4d19-bd9c-abd0049eb33f.png">

2023-05-01 19:17 UTC, yangc95 commented
@dakshdeepHERE Change the file metadata from the title "Interface" to "Interfaces" and push up to create the PR. I can help from there with the renaming

2023-05-02 06:17 UTC, dakshdeepHERE commented
@yangc95 Oh okay! I got it will do it right now.

2023-05-09 14:04 UTC, yangc95 commented
Thanks @dakshdeepHERE ! [#2076](https://github.com/Codecademy/docs/pull/2076) is merged now and the entry should be live at the correct link: https://www.codecademy.com/resources/docs/kotlin/interfaces