Huythai855 csharp string last index of
Codecademy/docs pull request #1952
Opened 2023-04-08 08:21 UTC by huythai855

### Description
I've just added the markdown description for String.LastIndexOf() method.
Please leave your comments if there are problems. Closes #1839 

### Type of Change
- Adding a new entry

### Checklist
- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-04-08 17:49 UTC, SSwiniarski requested changes
@huythai855 I did a first review and left a few comments.

2023-04-08 17:49 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/tan/tan.md
It looks like you branched off of your prior PR's branch rather than branching fresh from the main branch. You'll need to remove this file from this branch or there will be a conflict between this PR and your prior one.

2023-04-08 17:49 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/lastindexof/lastindexof.md
> +Description: 'Find the last occurrence of a specified character or substring within a string'
```suggestion
Description: 'Finds the last occurrence of a specified character or substring within a string.'
```

2023-04-08 17:49 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/lastindexof/lastindexof.md
> +The method return `-1` if there's not such valid search results.
```suggestion
The method returns `-1` if there's no such match.
```

2023-04-08 17:49 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/lastindexof/lastindexof.md
> +An additional parameters may be supplied to define the criteria for the search.
```suggestion
Additional parameters may be supplied to define the criteria for the search.
```

2023-04-08 17:49 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/lastindexof/lastindexof.md
> +// Same as about but use additional startIndex. The search starts at the startIndex and proceeds backward toward the beginning of the string, using the stringComparison method.
```suggestion
// Same as above but use additional startIndex. The search starts at the startIndex and proceeds backward toward the beginning of the string, using the stringComparison method.
```

2023-04-08 17:49 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/lastindexof/lastindexof.md
> +// Same as about but use additional searching length. The search starts at the startIndex and proceeds backward toward the beginning of the string for a specified number of character positions, using
```suggestion
// Same as above but uses additional searching length. The search starts at the startIndex and proceeds backward toward the beginning of the string for a specified number of character positions, using the stringComparison method.
```

2023-04-08 17:49 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/lastindexof/lastindexof.md
> +String.LastIndexOf(substring, startIndex, lenth, stringComparison);
```suggestion
String.LastIndexOf(substring, startIndex, length, stringComparison);
```

2023-04-08 17:49 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/lastindexof/lastindexof.md
> +- `len` is an Int32 object.
```suggestion
- `length` is an Int32 object.
```

2023-04-08 17:49 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/lastindexof/lastindexof.md
> +In this example, the `String.LastIndexOf()` is use with `compareStr`, `startIndex` and  `strCmp` parameters to determine the zero-base index of the last occurrence of substring within the string. The
```suggestion
In this example, the `String.LastIndexOf()` is used with `compareStr`, `startIndex` and  `strCmp` parameters to determine the zero-base index of the last occurrence of substring within the string. The search starts at the startIndex and proceeds backward toward the beginning of the string, using the StringComparison method:
```

2023-04-12 03:39 UTC, huythai855 commented
@SSwiniarski I deleted redundant file and edit typos. Can you check it again, please?

2023-04-12 22:03 UTC, caupolicandiaz requested changes
@huythai855 I've completed my initial review. Please update the entry, and tag me when you're finished making changes. Thanks

2023-04-12 22:03 UTC, caupolicandiaz commented on content/c-sharp/concepts/strings/terms/lastindexof/lastindexof.md
> +        compareStr = "C";
```suggestion
        string compareStr = "C";
```

2023-04-13 07:24 UTC, huythai855 commented
@caupolicandiaz I finished editing the typos. Can you check it again?

2023-04-13 19:34 UTC, caupolicandiaz approved these changes
@huythai855 Looks good

2023-04-14 16:05 UTC, merged

2023-04-14 16:11 UTC, SSwiniarski commented
@huythai855 Congrats on the new entry. Live link here:https://www.codecademy.com/resources/docs/c-sharp/strings/lastindexof

![image](https://user-images.githubusercontent.com/86081858/232098650-bd127976-dcae-4b9e-84b0-619f3842912a.png)