Add Pandas sum codebyte
Codecademy/docs pull request #1971
Opened 2023-04-13 20:29 UTC by SamanthaZerman

Added a codebyte to the bottom on Pandas sum method. Please make sure my description makes sense.

### Description

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [ x] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-04-14 19:31 UTC, caupolicandiaz requested changes
@SamanthaZerman I just added a few comments. Let me know if you have any questions. Thanks

2023-04-14 19:31 UTC, caupolicandiaz commented on content/pandas/concepts/groupby/terms/sum/sum.md
> +## Syntax for Pandas .sum() Method
```suggestion
## Syntax 
```

2023-04-14 19:31 UTC, caupolicandiaz commented on content/pandas/concepts/groupby/terms/sum/sum.md
> +## Syntax for Pandas .sum() Method
We generally don't specify the method in the header

2023-04-14 19:31 UTC, caupolicandiaz commented on content/pandas/concepts/groupby/terms/sum/sum.md
> +### Try It Yourself
```suggestion
## Codebyte Example
```

2023-04-14 19:31 UTC, caupolicandiaz commented on content/pandas/concepts/groupby/terms/sum/sum.md
> +### Try It Yourself
I believe "try it yourself" is the tag line used on another site. We generally stick to "Codebyte Example"

2023-04-14 19:31 UTC, caupolicandiaz commented on content/pandas/concepts/groupby/terms/sum/sum.md
> +Use the Codebytes editor below to produce a new Series using Pandas .sum() method.
```suggestion
Use the Codebytes editor below to produce a new Series with the `.sum()` method.
```

2023-04-18 22:00 UTC, caupolicandiaz approved these changes
@SamanthaZerman LGTM

2023-04-20 16:03 UTC, SSwiniarski approved these changes
@SamanthaZerman Looks good to me.

2023-04-20 16:03 UTC, SSwiniarski commented on content/pandas/concepts/groupby/terms/sum/sum.md
> +## Syntax
```suggestion
## Syntax
```

2023-04-20 16:09 UTC, merged