Add /content/kotlin/concepts/operators/operators.md first version file
Codecademy/docs pull request #1974
Opened 2023-04-14 15:04 UTC by JuanGabrielTerrazasSarmiento

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-04-14 15:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1974) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1974) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1974) it.</sub>

2023-04-15 23:16 UTC, caupolicandiaz requested changes
@JuanGabrielTerrazasSarmiento I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-04-15 23:16 UTC, caupolicandiaz commented on content/kotlin/concepts/operators/operators.md
> +* '!=' (not equals to)
```suggestion
* '!=' (not equal)
```

2023-04-15 23:16 UTC, caupolicandiaz commented on content/kotlin/concepts/operators/operators.md
> +* '>=' ()greater than or equals to)
```suggestion
* '>=' (greater than or equal to)
```

2023-04-15 23:16 UTC, caupolicandiaz commented on content/kotlin/concepts/operators/operators.md
> +* '<=' (less than or equals to)
```suggestion
* '<=' (less than or equal to)
```

2023-04-15 23:16 UTC, caupolicandiaz commented on content/kotlin/concepts/operators/operators.md
> +Logical operators are used to combine two or mode conditions and determine the overall result. Kotlin supports the following logical operators:
```suggestion
Logical operators are used to combine two or more conditions and determine the overall result. Kotlin supports the following logical operators:
```

2023-04-15 23:16 UTC, caupolicandiaz commented on content/kotlin/concepts/operators/operators.md
> +* '-=' (substraction assignment)
```suggestion
* '-=' (subtraction assignment)
```

2023-04-15 23:16 UTC, caupolicandiaz commented on content/kotlin/concepts/operators/operators.md
> +* '%=' (module assignment)
```suggestion
* '%=' (modulus assignment)
```

2023-04-15 23:16 UTC, caupolicandiaz commented on content/kotlin/concepts/operators/operators.md
> +## Increment and decrement operators
```suggestion
## Increment and Decrement Operators
```

2023-04-15 23:16 UTC, caupolicandiaz commented on content/kotlin/concepts/operators/operators.md
> +println(b.inv()) // 0b0011
I believe this prints out integers

2023-04-21 19:18 UTC, caupolicandiaz commented
@JuanGabrielTerrazasSarmiento There hasn't been any action on this PR, do you need any assistance with the changes?

2023-04-29 13:15 UTC, caupolicandiaz approved these changes
@JuanGabrielTerrazasSarmiento I've gone ahead and made the changes I suggested in order to keep this entry moving.

2023-04-29 14:20 UTC, SSwiniarski requested changes
@JuanGabrielTerrazasSarmiento I've done a second review and left a few comments. 

One additional thing I'd like to see is a sentence about what each operator does as part of the bulleted lists. so they read something like this:

```
- `+` Addition: Adds the left argument to the right argument.
```

Also I'd like the lists edited as above, with the operator in single backticks, removing the parenthesis, and capitalizing the operator name.

2023-04-29 14:20 UTC, SSwiniarski commented on content/kotlin/concepts/operators/operators.md
> +## Understanding Kotlin Operators
We generally don't start with a header, so remove this one.

2023-04-29 14:20 UTC, SSwiniarski commented on content/kotlin/concepts/operators/operators.md
> +Comparison operators are used to compare two values and determine wheter they are equal, not equal, greater than, less than, greater than or equal to, or less than or equal to. Kotlin supports the fo
```suggestion
Comparison operators are used to compare two values and determine whether they are equal, not equal, greater than, less than, greater than or equal to, or less than or equal to. Kotlin supports the following comparison operators:
```

2023-04-29 14:20 UTC, SSwiniarski commented on content/kotlin/concepts/operators/operators.md
> +- '>=' ()greater than or equals to)
```suggestion
- '>=' (greater than or equals to)
```

2023-04-29 14:20 UTC, SSwiniarski commented on content/kotlin/concepts/operators/operators.md
> +## Assignment Operators
You're missing examples for the last two sections.

2023-04-29 14:20 UTC, SSwiniarski commented on content/kotlin/concepts/operators/operators.md
> +- 'inv' (bitwise complement)
`inv()` is a function, not an operator.

2023-05-05 11:58 UTC, caupolicandiaz commented
@JuanGabrielTerrazasSarmiento There hasn't been any updates on this entry in the past week, are you still working on this? Please advise if you need any assistance?

2023-05-07 08:00 UTC, caupolicandiaz commented
@SSwiniarski @JuanGabrielTerrazasSarmiento I've gone ahead and incorporated the edits from the second review.

2023-05-07 12:07 UTC, SSwiniarski approved these changes
@JuanGabrielTerrazasSarmiento Looks good to me.

2023-05-07 13:40 UTC, merged

2023-05-07 13:53 UTC, SSwiniarski commented
@JuanGabrielTerrazasSarmiento congrats on your new entry. Live link is here: https://www.codecademy.com/resources/docs/kotlin/operators

@yangc95, @KTom101, @caupolicandiaz, This is another one where the user isn't being credited with the entry.
  
![image](https://user-images.githubusercontent.com/86081858/236681696-d8ecc02f-259b-49d1-9fd7-b6cc91708931.png)

2023-05-09 20:46 UTC, yangc95 commented
@JuanGabrielTerrazasSarmiento I would still recommend following the recommended steps to ensure that:

1. Your e-mails are consistent with your Codecademy profile and GitHub (then log back in to Codecademy with the GitHub option)
2, Your Codecademy profile is visible to everyone in your privacy settings and has the correct reference to your GitHub username