AI Generative article
Codecademy/docs pull request #1995
Opened 2023-04-21 14:22 UTC by bpascazio

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-04-21 23:13 UTC, HishamT requested changes
Hey @bpascazio, thank you for your entry. I have reviewed it and it does appear to contain several problems.

1. Bold terms should be reserved for technical terms only.
2. There are a number of sentences that are unclear and should be rewritten. I have marked them.

Thank you again.

2023-04-21 23:13 UTC, HishamT commented on content/ai/concepts/generative-ai/generative-ai.md
> +Generative AI may open up entirely new ways we can create and consume content. For example media now is difficult and time consuming to create even just in one length and format. Generative AI may al
```suggestion
Generative AI may open up entirely new ways to create and consume content. For example, currently, any form of media is difficult and time-consuming to create. Generative AI may allow different versions of movies, stories, and short videos to be generated from the same source to allow new ways of media consumption.
```

2023-04-21 23:13 UTC, HishamT commented on content/ai/concepts/generative-ai/generative-ai.md
> +Generation of speech based on text with high fidelity style will allow creates to make content where they were limited by voice overlay before.
```suggestion
The generation of high-fidelity speech based on text will allow creators to make content when previously, they were limited by voice overlay.
```

2023-04-21 23:13 UTC, HishamT commented on content/ai/concepts/generative-ai/generative-ai.md
> +Code generation, while automating repetitive work may result in higher quality code and the focus on new creative user centric solutions.
```suggestion
Code generation, while automating repetitive work, may result in higher-quality code and allow engineers to focus on creative user-centric solutions.
```

2023-04-21 23:13 UTC, HishamT commented on content/ai/concepts/generative-ai/generative-ai.md
> +Movies and video creation once expensive and available through large studios and digital production groups can instead be created by individuals and bound only by their imagination.
```suggestion
Movies and video creation, once expensive and available only through large studios and digital production groups, can instead be created by individuals and bound only by their imagination.
```

2023-04-21 23:13 UTC, HishamT commented on content/ai/concepts/generative-ai/generative-ai.md
> +Generative AI may help people understand more how creative processes work in general and how to continually enhance the human process.
```suggestion
Generative AI can help people further understand how the creative process works in general and how to continually enhance the human process.
```

2023-04-21 23:13 UTC, HishamT commented on content/ai/concepts/generative-ai/generative-ai.md
> +Generative AI may help people understand more how creative processes work in general and how to continually enhance the human process.
"the human process" is unclear. Can a different example be used?

2023-04-28 12:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=1995) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1995) before we can accept your contribution.<br/>**17** out of **18** committers have signed the CLA.<br/><br/>:white_check_mark: bpascazio<br/>:white_check_mark: Cesarcas1958<br/>:white_check_mark: caupolicandiaz<br/>:white_check_mark: freshjah<br/>:white_check_mark: jrood<br/>:white_check_mark: astronomical3<br/>:white_check_mark: SamanthaZerman<br/>:white_check_mark: RaffyRod<br/>:white_check_mark: Toseef-Ahmad<br/>:white_check_mark: yangc95<br/>:white_check_mark: SSwiniarski<br/>:white_check_mark: KLadygina<br/>:white_check_mark: kobrius11<br/>:white_check_mark: yekyam<br/>:white_check_mark: Pavan-04-08<br/>:white_check_mark: DiogoBarros03<br/>:white_check_mark: JohnSteeleCG<br/>:x: codecademy-gh-api<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=1995) it.</sub>

2023-04-29 14:42 UTC, SSwiniarski commented
Closing this as it is replaced by [2043](https://github.com/Codecademy/docs/pull/2043).

2023-04-29 14:42 UTC, closed without merging