Initial commit
Codecademy/docs pull request #2000
Opened 2023-04-23 06:05 UTC by KennyCopp

### Description

I created a markdown file for the SQL ROW_NUMBER() window function as part of the portfolio project in the "Learn Git & GitHub" course

### Type of Change

- Adding a new entry

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-04-23 06:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2000) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2000) before we can accept your contribution.<br/><hr/>**KennyCopp** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2000) it.</sub>

2023-04-26 07:19 UTC, KTom101 requested changes
@KennyCopp I've added some changes to this entry as part of the 1st review. Please let me know if there are any questions, Thanks.

2023-04-26 07:19 UTC, KTom101 commented on content/sql/concepts/window-functions/terms/row_number/row-number.md
> +
Can we have a section here showing the results in a table like the others?


Chris|Blake|Manchester
Emily|Pugh|Manchester
Eric|Gustav|Louisville
Joseph|Chang|Raleigh
Mary|Greene|Raleigh

2023-04-26 07:19 UTC, KTom101 commented on content/sql/concepts/window-functions/terms/row_number/row-number.md
Rename the folder to match the file name "row-number" (replace the underscore `_` with a dash `-`)

2023-04-29 05:28 UTC, KennyCopp commented on content/sql/concepts/window-functions/terms/row_number/row-number.md
Thank you for your suggestions, I've updated the folder name and made the changes to row-number.md itself. I believe I've added the commit to the right place? Please let me know if there is anything else.

2023-04-29 06:02 UTC, KTom101 reviewed
@KennyCopp Just a few more spots that need spacing, but otherwise good.

2023-04-29 06:02 UTC, KTom101 commented on content/sql/concepts/window-functions/terms/row-number/row-number.md
> +* `PARTITION BY` is an optional parameter used to create partitions (groups of rows). If it is not used, `ROW_NUMBER()` will treat the result set as one partition. It is important to note that `ROW_N
```suggestion

* `PARTITION BY` is an optional parameter used to create partitions (groups of rows). If it is not used, `ROW_NUMBER()` will treat the result set as one partition. It is important to note that `ROW_NUMBER()` is applied to each partition separately; so the first row in a partition is assigned '1', the second row is assigned '2', and so on.
```

2023-04-30 01:19 UTC, KTom101 approved these changes
@KennyCopp I added the remaining line breaks/spacing here: [f767225](https://github.com/Codecademy/docs/pull/2000/commits/f767225888fa0b38b87bf05eb951a1ccae7a0b42). Please wait for a second review from another maintainer/collaborator.

2023-04-30 14:01 UTC, SSwiniarski approved these changes
@KennyCopp Looks good as is.

2023-05-13 13:19 UTC, SSwiniarski commented
@caupolicandiaz were you still going to review this or can we merge?

2023-05-13 13:35 UTC, caupolicandiaz commented
> @caupolicandiaz were you still going to review this or can we merge?

merge

2023-05-13 14:39 UTC, merged

2023-05-13 14:44 UTC, SSwiniarski commented
@KennyCopp Congrats on the new entry. Live link here:https://www.codecademy.com/resources/docs/sql/window-functions/row-number

![image](https://github.com/Codecademy/docs/assets/86081858/feff8a66-050d-4f3c-85b8-fb688d99bbb3)