added: startswith.md in csharp\concepts\strings\terms\startswith directory
Codecademy/docs pull request #2001
Opened 2023-04-23 07:58 UTC by kobrius11

docs/content/c-sharp/concepts/strings/terms/startswith/startswith.md

### Description

Added new term StartsWith() in c-sharp concept entry. i used endswith.md as a reference, i dont know c-sharp but i used examples from endswith.md and i checked them, they work as intended. If change doesn't get pulled it was a pleasant experience, nonetheless. 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [+] My entry follows the Codecademy Docs style guide.
- [+] My changes generate no new warnings.
- [+] I have performed a self-review of my own writing and code.
- [+] I have checked my entry and corrected any misspellings.
- [+] I have made corresponding changes to the documentation if needed.
- [+] I have confirmed my changes are not being pushed from my forked `main` branch.
- [+] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [+] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-04-23 07:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2001) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2001) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2001) it.</sub>

2023-04-23 13:48 UTC, SSwiniarski requested changes
@kobrius11 I did a first review and left a few comments.

2023-04-23 13:48 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/startswith/startswith.md
> +// Same as above but uses additional case-sensitive and culture-sensitive
```suggestion
// Same as above but uses additional case-sensitive and culture-sensitive criteria.
```

2023-04-23 13:48 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/startswith/startswith.md
> +// Determines whether the String instance's first character matches the specified character
```suggestion
// Determines whether the String instance's first character matches the specified character.
```

2023-04-23 13:48 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/startswith/startswith.md
> +// Determines whether the start of String instance matches the specified string
```suggestion
// Determines whether the start of String instance matches the specified string.
```

2023-04-23 13:48 UTC, SSwiniarski commented on content/c-sharp/concepts/strings/terms/startswith/startswith.md
> +// Same as above but uses an enumeration to determine the case- and culture-sensitive criteria
```suggestion
// Same as above but uses an enumeration to determine the case- and culture-sensitive criteria.
```

2023-04-27 04:39 UTC, caupolicandiaz approved these changes
@kobrius11 @SSwiniarski LGTM. I think this is good to merge.

2023-04-27 11:29 UTC, merged

2023-04-27 11:35 UTC, SSwiniarski commented
@kobrius11 congrats on the new entry. Live link can be found here: https://www.codecademy.com/resources/docs/c-sharp/strings/startswith

You're currently listed as an anonymous contributor. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.

![image](https://user-images.githubusercontent.com/86081858/234850070-863effe7-7201-4b07-9846-c3e5b682b506.png)

To add your GitHub username to your Codecademy profile:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

![image](https://user-images.githubusercontent.com/86081858/234850180-20a781d6-9f22-49e3-b8c7-40381ca58037.png)

2.) Then log out and log back into Codecademy using your GitHub login:

![image](https://user-images.githubusercontent.com/86081858/234850303-533f179e-6d0d-46b9-a53f-56cee664a00b.png)

**Note**: Your email used for Codecademy will have to be listed in your GitHub profile for the login feature to properly work. If you use the same email for both GitHub and Codecademy already, then you're set.