Added new entry on Software Engineering
Codecademy/docs pull request #2041
Opened 2023-04-27 21:53 UTC by YanisaHS

### Description

Added a new entry on Software Engineering to close #1822 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-04-29 05:30 UTC, caupolicandiaz requested changes
@YanisaHS I've added a few comments. Please update, and tag me when you've finished. Thanks

2023-04-29 05:30 UTC, caupolicandiaz commented on content/general/concepts/software-engineering/software-engineering.md
> +  - 'paths/back-end-engineer-career-path'
```suggestion
```

2023-04-29 05:30 UTC, caupolicandiaz commented on content/general/concepts/software-engineering/software-engineering.md
> +  - 'paths/back-end-engineer-career-path'
We limit the subject and content fields to two items, tags can contain as many as five

2023-04-29 05:30 UTC, caupolicandiaz commented on content/general/concepts/software-engineering/software-engineering.md
> +  - 'Mobile Development'
```suggestion
```

2023-04-29 05:30 UTC, caupolicandiaz commented on content/general/concepts/software-engineering/software-engineering.md
> +A [front-end](https://www.codecademy.com/resources/docs/general/front-end) engineer creates and manages the user-facing components of an application, such as a website. They typically work on web app
```suggestion
A [front-end](https://www.codecademy.com/resources/docs/general/front-end) engineer creates and manages the user-facing components of an application, such as a website. They typically work on web applications, although some front-end engineers work on desktop and mobile applications. Front-end engineers are familiar with programming languages such as JavaScript, [TypeScript](https://www.codecademy.com/resources/docs/typescript), [Ruby](https://www.codecademy.com/resources/docs/ruby), as well as mark-up languages [HTML](https://www.codecademy.com/resources/docs/html), and [CSS](https://www.codecademy.com/resources/docs/css). They also use web development tools and frameworks, such as [Angular](https://www.codecademy.com/resources/docs/open-source/angular), [React](https://www.codecademy.com/resources/docs/react), and [Bootstrap](https://www.codecademy.com/resources/docs/open-source/bootstrap).
```

2023-05-01 13:43 UTC, YanisaHS commented
@caupolicandiaz thank you for your feedback!! I've finished committing those changes 🥳

2023-05-01 16:16 UTC, caupolicandiaz approved these changes
@YanisaHS LGTM. This is ready for another review.

2023-05-12 22:34 UTC, KTom101 approved these changes
@YanisaHS I just added a couple of minor changes in commit [fd20d56](https://github.com/Codecademy/docs/pull/2041/commits/fd20d5647c4f7016a0f40e842ad5a35d1dbdc11f). Looks good to merge, thank you 👍

2023-05-12 22:34 UTC, merged

2023-05-12 22:37 UTC, KTom101 commented
@YanisaHS Entry is live: https://www.codecademy.com/resources/docs/general/software-engineering 🎉 Thanks for another solid contribution and your patience on this! 🎉

<img width="728" alt="Screenshot 2023-05-12 at 6 35 47 PM" src="https://github.com/Codecademy/docs/assets/40783324/f85e62a6-8273-41de-8400-1c3a2f3625aa">