Initial commit PHP implode documentation
Codecademy/docs pull request #2069
Opened 2023-05-01 16:44 UTC by freshjah

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-03 11:54 UTC, SSwiniarski approved these changes
@freshjah I did a first review and left a couple of comments.

2023-05-03 11:54 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/implode/implode.md
> +The following example show the use of `implode()` function with and without the use of the `separator`.
```suggestion
The following example shows the use of `implode()` function with and without the use of the `separator`.
```

2023-05-03 11:54 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/implode/implode.md
> +The example below uses the `implode()` function to create the sentence 'I love learning with Codecademy'. The separator is a single white space.
```suggestion
The example below uses the `implode()` function to create the sentence 'I love learning with Codecademy'. The separator is a single space.
```

2023-05-03 13:37 UTC, SSwiniarski approved these changes
@freshjah Looks good for a second review.

2023-05-13 20:44 UTC, KTom101 requested changes
@freshjah I've completed a second review of this entry.

2023-05-13 20:44 UTC, KTom101 commented on content/php/concepts/string-functions/terms/implode/implode.md
> +    echo("<br/>");
I'm noticing in the codebyte for [another php entry](https://www.codecademy.com/resources/docs/php/string-functions/explode) that the `<br>` are not being rendered correctly, let's change to the new line character for now: 
```suggestion
    echo("\r\n");
```

2023-05-13 20:44 UTC, KTom101 commented on content/php/concepts/string-functions/terms/implode/implode.md
> +    echo("<br/>");
```suggestion
    echo("\r\n");
```

2023-05-13 20:44 UTC, KTom101 commented on content/php/concepts/string-functions/terms/implode/implode.md
> +- `separator` - Optional string value. If omitted defaults to empty string.
```suggestion
- `separator` - Optional string value. If omitted, the default is an empty string.
```

2023-05-26 13:12 UTC, SSwiniarski commented
In the interest of getting this merged, I implemented @KTom101's suggestions.

2023-05-27 18:06 UTC, KTom101 approved these changes
LGTM

2023-05-27 18:07 UTC, merged

2023-05-27 18:16 UTC, KTom101 commented
@freshjah Link is live: https://www.codecademy.com/resources/docs/php/string-functions/implode

Currently, you're listed as an anonymous contributor:

<img width="370" alt="Screenshot 2023-05-27 at 2 12 34 PM" src="https://github.com/Codecademy/docs/assets/40783324/312d14ab-625b-4401-b808-8de3c243ca7a">

If you want to remain anonymous, there is nothing more you need to do. If you wish to be listed as a contributor, make sure you've added your GitHub username to your Codecademy profile using the following steps:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

<img width="871" alt="YourGitHubName" src="https://github.com/Codecademy/docs/assets/40783324/7be82a66-d9ef-4c3b-9334-d49f4540cb70">

2.) Then log out and log back into Codecademy using your GitHub login:

<img width="1273" alt="ReLogIn" src="https://github.com/Codecademy/docs/assets/40783324/f7d9c1c8-2eea-495c-9393-86d9762b899b">

> **Note:** Your email used for Codecademy will have to be listed in your GitHub profile for the login feature to properly work. If you use the same email for both GitHub and Codecademy already, then you're set.

cc: @yangc95 @SSwiniarski