[Concept Entry] ransomware
Codecademy/docs pull request #2075
Opened 2023-05-02 07:31 UTC by JohnSteeleCG

### Description

Created concept entry for Ransomware located at docs/content/cybersecurity/concepts/ransomware/ransomware.md
added brief description on ransomware and various countermeasures. Closes #2010 if merged.

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-02 16:53 UTC, SSwiniarski requested changes
@JohnSteeleCG, Looks good. I left a few comments. Other than the line-edit things, I want you to add a sentence or two about the "ransom" part of ransomware.

2023-05-02 16:53 UTC, SSwiniarski commented on content/cybersecurity/concepts/ransomware/ransomware.md
> +- Use up-to-date security software to protect devices. Outdated software might contain [Vulnerabilities](https://www.codecademy.com/resources/docs/cybersecurity/vulnerability) making it easy for the
```suggestion
- Use up-to-date security software to protect devices. Outdated software might contain [vulnerabilities](https://www.codecademy.com/resources/docs/cybersecurity/vulnerability) making it easy for the attacker to infect the device.
```

2023-05-02 16:53 UTC, SSwiniarski commented on content/cybersecurity/concepts/ransomware/ransomware.md
> +- Implement the use of [Multi-factor Authentication](https://www.codecademy.com/resources/docs/cybersecurity/multi-factor-authentication) to ensure that an attacker will not gain access to important
```suggestion
- Implement the use of [multi-factor authentication](https://www.codecademy.com/resources/docs/cybersecurity/multi-factor-authentication) to ensure that an attacker will not gain access to important accounts online by verifying an additional factor, such as a token, that the authentic user would only possess.
```

2023-05-02 16:53 UTC, SSwiniarski commented on content/cybersecurity/concepts/ransomware/ransomware.md
> +- Use secured networks when possible. Using unsecured networks will leave the device unprotected and increase the [risk](https://www.codecademy.com/resources/docs/cybersecurity/risk) of ransomware in
```suggestion
- Use secured networks when possible. Using unsecured networks will leave the device unprotected and increase the [risk](https://www.codecademy.com/resources/docs/cybersecurity/risk) of ransomware infecting the device. The use of a [virtual private network (VPN)](https://www.codecademy.com/resources/docs/cybersecurity/virtual-private-network) is recommended to secure and encrypt the connection to protect against malicious threats.
```

2023-05-02 16:53 UTC, SSwiniarski commented on content/cybersecurity/concepts/ransomware/ransomware.md
> +**Ransomware** is a [cyber attack](https://www.codecademy.com/resources/docs/cybersecurity/cyber-attack) that blocks and prevents a user from accessing important files or personal data that is locate
Add the fact that the bad actors will ask for money, usually cryptocurrency, in order to restore the compromised system.

2023-05-02 20:27 UTC, JohnSteeleCG commented
@SSwiniarski made the requested changes, let me know if it looks good.

2023-05-03 11:28 UTC, SSwiniarski approved these changes
@JohnSteeleCG Looks good for another review.

2023-05-04 12:46 UTC, merged

2023-05-04 12:58 UTC, SSwiniarski commented
@JohnSteeleCG congrats on the new entry. Live link is here:https://www.codecademy.com/resources/docs/cybersecurity/ransomware

![image](https://user-images.githubusercontent.com/86081858/236211615-2d9fedb4-35c2-454c-8ca9-2f00fd8b6cb8.png)