[Concept Entry] HTML Quotations #2065
Codecademy/docs pull request #2077
Opened 2023-05-02 14:33 UTC by Roshanbhadauriya

## What does this PR do?
fixes #2065 
### Description

Added new entry HTML Quotations.
Closes issue #2065

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-02 16:42 UTC, SSwiniarski requested changes
@Roshanbhadauriya I did a first review and left a few comments.

2023-05-02 16:42 UTC, SSwiniarski commented on content/html/concepts/quotations/quotations.md
> +Short quotations are used for brief, inline quotations that are a few words or less. To create a short quotation, you can use the `q` tag. Here's an example of how to use the `q` tag:
```suggestion
Short quotations are used for brief, inline quotations that are a few words or less. To create a short quotation, you can use the [`<q>` tag](https://www.codecademy.com/resources/docs/html/elements/q). Here's an example of how to use the `<q>` tag:
```

2023-05-02 16:42 UTC, SSwiniarski commented on content/html/concepts/quotations/quotations.md
> +<p>According to <q>Albert Einstein</q>, "Imagination is more important than knowledge."</p>
```suggestion
<p>According to Albert Einstein, <q>Imagination is more important than knowledge.</q></p>
```

2023-05-02 16:42 UTC, SSwiniarski commented on content/html/concepts/quotations/quotations.md
> +In this example, the text "The best way to predict your future is to create it" is enclosed in the `blockquote` tag to indicate that it's a quotation. The `footer` tag is used to specify the author o
```suggestion
In this example, the text "The best way to predict your future is to create it" is enclosed in the `<blockquote>` tag to indicate that it's a quotation. The `<footer>` tag is used to specify the author of the quote.
```

2023-05-03 05:28 UTC, Roshanbhadauriya commented on content/html/concepts/quotations/quotations.md
> +  - 'Quotations'
Okay! I get it now.

2023-05-26 14:34 UTC, caupolicandiaz commented on content/html/concepts/quotations/quotations.md
> +Short quotations are used for brief, inline quotations that are a few words or less. To create a short quotation, you can use the [`<q>` tag](https://www.codecademy.com/resources/docs/html/elements/q
```suggestion
Short quotations such as a short sentence or fragment should be set off with the [`<q>` tag](https://www.codecademy.com/resources/docs/html/elements/q). Here's an example of how to use the `<q>` tag:
```

2023-05-26 14:37 UTC, caupolicandiaz commented on content/html/concepts/quotations/quotations.md
> +Long quotations are used for quotations that are longer than a few words and typically require their own paragraph. To create a long quotation, you can use the `[<blockquote>](https://www.codecademy.
```suggestion
For longer quotations the `[<blockquote>](https://www.codecademy.com/resources/docs/html/elements/blockquote)` tag is used in lieu of `<q>`. Here's an example of how to use the `<blockquote>` tag:
```

2023-05-26 14:37 UTC, caupolicandiaz commented on content/html/concepts/quotations/quotations.md
> +```pseudo
```suggestion
```html
```

2023-05-26 14:38 UTC, caupolicandiaz commented on content/html/concepts/quotations/quotations.md
> +```pseudo
since this is a real example and not pseudocode we should use the html tag

2023-05-26 14:38 UTC, caupolicandiaz commented on content/html/concepts/quotations/quotations.md
> +```pseudo
```suggestion
```html
```

2023-05-26 14:39 UTC, caupolicandiaz commented on content/html/concepts/quotations/quotations.md
> +<p>"The best way to predict your future is to create it."</p>
I think it would be preferable to show something that's a bit longer. This quote is almost the same length as the previous example

2023-05-26 14:42 UTC, caupolicandiaz commented on content/html/concepts/quotations/quotations.md
> +In conclusion, HTML provides two types of quotation tags: short quotations and long quotations. Short quotations can be created using the `<q>` tag, while long quotations can be created using the `<b
```suggestion
In conclusion, HTML provides two types of quotation tags to address short quotations and long quotations. Short quotations can be created using the `<q>` tag, while long quotations can be created using the `<blockquote>` tag. By using these tags correctly, quotations can be added to web pages in the most explicit and accessible form possible.
```

2023-06-02 15:36 UTC, Roshanbhadauriya commented
@caupolicandiaz  done.

2023-06-03 08:47 UTC, caupolicandiaz requested changes
@Roshanbhadauriya A couple of additional comments.

2023-06-03 08:47 UTC, caupolicandiaz commented on content/html/concepts/quotations/quotations.md
> +  <p>"The greatest glory in living lies not in never falling, but in rising every time we fall. The way to get started is to quit talking and begin doing. Your time is limited, don't waste it living
```suggestion
  <p>"The greatest glory in living lies not in never falling, but in rising every time we fall. The way 
  to get started is to quit talking and begin doing. Your time is limited, don't waste it living someone 
  else's life. Don't be trapped by dogma, which is living the result of other people's thinking. Don't 
  let the noise of other's opinions drown your own inner voice. And most important, have the courage
  to follow your heart and intuition. They somehow already know what you truly want to become. 
  Everything else is secondary."</p> 
```

2023-06-03 08:47 UTC, caupolicandiaz commented on content/html/concepts/quotations/quotations.md
> +  <p>"The greatest glory in living lies not in never falling, but in rising every time we fall. The way to get started is to quit talking and begin doing. Your time is limited, don't waste it living
I think it's preferable to break the lines similar to what I've done above, so, that the quote is visible all at once, and users don't have to scroll to see what the text says.

Additionally, the footer with the author's name is missing.

2023-06-07 11:56 UTC, caupolicandiaz approved these changes
@Roshanbhadauriya @SSwiniarski LGTM

2023-06-07 12:00 UTC, merged

2023-06-07 14:02 UTC, SSwiniarski commented
@Roshanbhadauriya congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/html/quotations

![image](https://github.com/Codecademy/docs/assets/86081858/191737e7-ef91-43ad-b595-1e6ebb7a07c4)