Floor
Codecademy/docs pull request #2085
Opened 2023-05-04 12:44 UTC by leichtaustin

### Description

Adding floor() content for php section

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [ x] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-04 12:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2085) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2085) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2085) it.</sub>

2023-05-04 13:08 UTC, SSwiniarski requested changes
@leichtaustin I did a first review and left a few comments.

2023-05-04 21:08 UTC, leichtaustin commented
Resubmitted the changes to include the php code block around example.

2023-05-05 11:29 UTC, SSwiniarski requested changes
@leichtaustin A few more comments.

2023-05-05 11:29 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/floor/floor.md
> +## Example
```suggestion
## Example

```
Add line break.

2023-05-05 11:29 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/floor/floor.md
> +The **`floor()`** function returns a rounded number down to the nearest integer and if necessary, returns a result.
```suggestion
The **`floor()`** function returns a rounded number down to the nearest integer.
```

2023-05-05 11:29 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/floor/floor.md
> +Description: 'Returns a rounded number down to the nearest integer and if necessary, returns a result.'
```suggestion
Description: 'Returns a rounded number down to the nearest integer.'
```

2023-05-06 11:55 UTC, SSwiniarski approved these changes
@leichtaustin Looks good for a second review.

2023-05-26 17:11 UTC, yangc95 commented on content/php/concepts/math-functions/terms/floor/floor.md
> +The result returns a value type of float.
```suggestion
The result returns a value type of `float`.
```

2023-05-26 18:39 UTC, yangc95 commented on content/php/concepts/math-functions/terms/floor/floor.md
> +In this example, the result will be a float value of 3 as the function rounds down 3.4 to 3
```suggestion

In this example, the result will be a float value of 3 as the function rounds down 3.4 to 3
```

2023-05-26 18:43 UTC, merged

2023-05-26 18:45 UTC, yangc95 commented
🥳 @leichtaustin live link: https://www.codecademy.com/resources/docs/php/math-functions/floor

<img width="946" alt="Screenshot 2023-05-26 at 2 45 06 PM" src="https://github.com/Codecademy/docs/assets/72277593/c32157a4-db6a-47fb-806b-d4f03fde70f3">

It looks as if you're anonymous. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.
To add your GitHub username to your Codecademy profile:
1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

Make sure to set your visibility to “everyone”:


2.) Then log out and log back into Codecademy using your GitHub login:

If the steps above do not work, it may be due to an email or local configuration issue.
In addition, we may reach out in the future if any adjustments to these entries are required.


cc: @SSwiniarski