Term entry sdl bigbang
Codecademy/docs pull request #2117
Opened 2023-05-08 10:30 UTC by cslylla

### Description

- Added new term for General Concepts - SDLC Math Functions: Big Bang Model
- Closes #1804 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-12 11:20 UTC, SSwiniarski requested changes
@cslylla Strong entry, I only had a few comments. I have a question about the image. Is it your own work, or did you source it from somewhere?

2023-05-12 11:20 UTC, SSwiniarski commented on content/general/concepts/software-development-life-cycle/terms/big-bang/big-bang.md
> +- time,
```suggestion
- Time.
```

2023-05-12 11:20 UTC, SSwiniarski commented on content/general/concepts/software-development-life-cycle/terms/big-bang/big-bang.md
> +- effort and
```suggestion
- Effort.
```

2023-05-12 11:20 UTC, SSwiniarski commented on content/general/concepts/software-development-life-cycle/terms/big-bang/big-bang.md
> +- resources.
```suggestion
- Resources.
```

2023-05-12 11:41 UTC, cslylla commented
@SSwiniarski Thank you, I accepted the changes. I made the image with Figma. I used icons from [Material Design](https://fonts.google.com/icons) and [Icons8](https://icons8.com/). I tried to use the same colours that Codecademy uses.

2023-05-12 11:52 UTC, SSwiniarski approved these changes
@cslylla Looks good for a second review. Complements on the image.

2023-05-16 08:33 UTC, caupolicandiaz requested changes
@cslylla Looks good. Just a couple edits to match our new standards for this topic. Please tag me when you've finished making the changes. Thanks

2023-05-16 08:33 UTC, caupolicandiaz commented on content/general/concepts/software-development-life-cycle/terms/big-bang/big-bang.md
> +Title: 'Big Bang'
```suggestion
Title: 'Big Bang Model'
```

2023-05-16 08:33 UTC, caupolicandiaz commented on content/general/concepts/software-development-life-cycle/terms/big-bang/big-bang.md
> +Title: 'Big Bang'
We have decided to updated all of the SLDC terms to include model in the title and the file name per https://github.com/Codecademy/docs/pull/2177. Please update this entry to match.

@yangc95

2023-05-16 13:44 UTC, cslylla commented
@caupolicandiaz I updated the file and folder name to include "model" in it. I also made a minor change to the document: I changed  "model" to bold in the first sentence.

2023-05-16 16:01 UTC, caupolicandiaz approved these changes
@cslylla Looks good

2023-05-16 16:19 UTC, merged

2023-05-16 16:21 UTC, SSwiniarski commented
@cslylla Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/general/software-development-life-cycle/big-bang-model

![image](https://github.com/Codecademy/docs/assets/86081858/91f246a2-8c10-4eb4-a1bc-2f5afea2b347)