added entry for files in cpp docs
Codecademy/docs pull request #212
Opened 2021-08-31 17:19 UTC by bhagyamudgal

### Description

- Added entry for Cpp Files.

### Type of Change

- [x] Adding a new entry
- [ ] Editing an existing entry (fixing a typo, bug, issues, etc)
- [ ] Updating the documentation

### Checklist

- [x] My entry follows the Codecademy Docs style guide
- [x] I have performed a self-review of my own writing and code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have checked my entry and corrected any misspellings
- [x] All writings are my own

### Codecademy Username

If you want your Codecademy username be displayed in your entry (feature coming in October), make sure to have your Codecademy user profile linked to your GitHub:

1. Go to your Codecademy dashboard.
2. Click on your profile image in the top-right and then choose "Profile".
3. Then click "Edit Profile".
4. In the GitHub field, add your GitHub profile URL.

2021-08-31 19:45 UTC, sonnynomnom requested changes
Left some changes!

2021-08-31 19:45 UTC, sonnynomnom commented on content/cpp/concepts/files/files.md
> +Title: "Loops"
Files, not Loops

2021-08-31 19:45 UTC, sonnynomnom commented on content/cpp/concepts/files/files.md
> +To use the `fstream` library in C++ program, include both the standard `<iostream>` AND the `<fstream>` header files in C++ program:
Lowercase AND -> and.

2021-08-31 19:45 UTC, sonnynomnom commented on content/cpp/concepts/files/files.md
> +To use the `fstream` library in C++ program, include both the standard `<iostream>` AND the `<fstream>` header files in C++ program:
in the C++ program:

2021-08-31 19:45 UTC, sonnynomnom commented on content/cpp/concepts/files/files.md
> +1. `ofstream`: Creates and writes to files.
Let's use bullet points instead of numbers.

2021-09-01 05:06 UTC, sonnynomnom approved these changes
LGTM!

2021-09-01 05:06 UTC, merged

2021-09-01 05:18 UTC, sonnynomnom commented
Hi @bhagyamudgal,

I made some changes: https://github.com/Codecademy/docs/commit/ca4038ba9ba2832f2fcfd11bb3c7d7434d475dca

It was brought to my attention that the first sentence might not be yours. We are human so I understand, but please refrain from doing this in the future. Because this could potentially jeopardize all other 600 entries 🙏. I just fixed it though so we good.

2021-09-01 05:26 UTC, bhagyamudgal commented
@sonnynomnom Ok I will take care of this next time.