[Concept Entry] PHP Math Functions ceil() #2061
Codecademy/docs pull request #2120
Opened 2023-05-09 09:25 UTC by d1r0l

### Description

Added new term entry for PHP math function ceil()

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-11 16:42 UTC, SSwiniarski requested changes
@d1r0l I did a first review. Good entry! I just had one comment about expanding your example section.

2023-05-11 16:42 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/ceil/ceil.md
> +## Example
Generally we want a sentence describing what the example does, and output shown not in comments, but in a separate ` ```shell ` block afterwards (introduced by a sentence like, "This example results in the following output").

2023-05-12 19:29 UTC, d1r0l commented
@SSwiniarski Thanks for a review and a request! I fixed the Example block according to the recommendation so please review again.

2023-05-13 13:15 UTC, SSwiniarski requested changes
@d1r0l Still part of my last comment that needs to be addressed.

2023-05-13 13:15 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/ceil/ceil.md
> +## Example
Still would like to have a sentence introducing the example and what it does.

2023-05-13 16:31 UTC, SSwiniarski approved these changes
@d1r0l Looks good for review number two.

2023-05-13 16:33 UTC, d1r0l commented
@SSwiniarski Thank you! Sorry for misunderstanding first time.

2023-05-26 19:26 UTC, yangc95 commented on content/php/concepts/math-functions/terms/ceil/ceil.md
> +This example demonstrates the usage of ceil function with three different arguments and outputs results of each in a new line:
```suggestion
This example demonstrates the usage of the `ceil()` function with three different arguments, and outputs results of each on a new line:
```

2023-05-26 19:29 UTC, yangc95 commented on content/php/concepts/math-functions/terms/ceil/ceil.md
> +  echo ceil(6.01)."\n";
```suggestion
  echo ceil(9.4)."</br>";
  echo ceil(6.01)."</br>";
```

2023-05-26 19:30 UTC, yangc95 approved these changes

2023-05-26 19:32 UTC, merged

2023-05-26 19:35 UTC, yangc95 commented
Congrats 🥳 @d1r0l live link: https://www.codecademy.com/resources/docs/php/math-functions/ceil

<img width="838" alt="Screenshot 2023-05-26 at 3 35 09 PM" src="https://github.com/Codecademy/docs/assets/72277593/1a31807d-99f6-43e0-89de-6a76a8c1abec">

It looks as if you're anonymous. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.
To add your GitHub username to your Codecademy profile:
1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
![githubusername](https://github.com/Codecademy/docs/assets/72277593/4b8686cf-0600-4b7f-b8a8-642c319a6032)

Make sure to set your visibility to “everyone”:

<img width="537" alt="Screenshot 2023-04-10 at 4 07 30 PM" src="https://github.com/Codecademy/docs/assets/72277593/b657415d-f825-4011-808e-c2b84c471759">

2.) Then log out and log back into Codecademy using your GitHub login:
<img width="976" alt="githublogin" src="https://github.com/Codecademy/docs/assets/72277593/b4664a12-201c-419b-81d8-2f70786b4379">

If the steps above do not work, it may be due to an email or local configuration issue.
In addition, we may reach out in the future if any adjustments to these entries are required.


cc: @SSwiniarski