[Term Entry] PHP Math Functions sin()
Codecademy/docs pull request #2124
Opened 2023-05-10 15:06 UTC by jorgeprietoarranz

### Description

- Added the sin() term for PHP
- Closes Issue #2059 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-10 15:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2124) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2124) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2124) it.</sub>

2023-05-11 11:56 UTC, SSwiniarski requested changes
@jorgeprietoarranz I did a first review and left a couple of comments.

2023-05-11 11:56 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/sin/sin.md
> +  - 'paths/computer-science'
```suggestion
```
We generally limit CatalogContent to two entries.

2023-05-11 11:56 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/sin/sin.md
> +The **`sin()`** function returns the sine of a given angle in radians.
```suggestion
The **`sin()`** function returns the sine of a angle given in radians.
```
Original wording can read as if the result was given in radians.

2023-05-12 11:55 UTC, SSwiniarski approved these changes
@jorgeprietoarranz Other than one line edit, looks good for a second review.

2023-05-12 11:55 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/sin/sin.md
> +The **`sin()`** function returns the sine of a angle given in radians.
```suggestion
The **`sin()`** function returns the sine of an angle given in radians.
```

2023-05-13 22:17 UTC, KTom101 requested changes
@jorgeprietoarranz I've added a second review to this entry.

2023-05-17 09:33 UTC, jorgeprietoarranz commented
> @jorgeprietoarranz I've added a second review to this entry.

Thanks a lot for your suggestions!

2023-05-18 18:45 UTC, KTom101 approved these changes
@jorgeprietoarranz Added a minor change in the codebyte so we can have an example with a different output. I also ran `npm run format:all` to fix the tests failing. You can read more on that [here](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md#how-can-i-test-my-changes-before-submitting-a-pr).

2023-05-18 18:47 UTC, merged

2023-05-19 07:51 UTC, jorgeprietoarranz commented
I have just followed the steps, so my contribution should not appear as anonymous anymore.

Thanks a lot for the experience and hope see you around soon ^_^