Added a term entry for is-nan in PHP (#2087)
Codecademy/docs pull request #2126
Opened 2023-05-10 18:13 UTC by tipofey

### Description
Added a new term entry for **PHP** about `is_nan` function.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-10 18:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2126) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2126) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2126) it.</sub>

2023-05-10 19:34 UTC, yangc95 commented on content/php/concepts/math-functions/terms/is-nan/is-nan.md
> +Title: 'is-nan'
```suggestion
Title: 'is-nan()'
```

2023-05-10 19:35 UTC, yangc95 commented on content/php/concepts/math-functions/terms/is-nan/is-nan.md
> +Description: 'Finds whether a value is not a number.'
```suggestion
Description: 'Returns a boolean indicating if a value is not a number.'
```

2023-05-10 19:35 UTC, yangc95 commented on content/php/concepts/math-functions/terms/is-nan/is-nan.md
> +Title: 'is-nan'
```suggestion
Title: 'is-nan()'
```

2023-05-10 19:35 UTC, yangc95 commented on content/php/concepts/math-functions/terms/is-nan/is-nan.md
> +The **`is_nan`** function checks whether the argument is 'not a number'.
```suggestion
The **`is_nan()`** function checks whether the argument is not a number.
```

2023-05-10 19:36 UTC, yangc95 commented on content/php/concepts/math-functions/terms/is-nan/is-nan.md
> +Returns **true** if `n` is 'not a number', else **false**.
```suggestion
Returns `true` if `n` is 'not a number', else `false`.
```

2023-05-10 19:36 UTC, yangc95 commented on content/php/concepts/math-functions/terms/is-nan/is-nan.md
> +Using `is_nan()` to check whether `10` is 'not a number':
```suggestion
Using `is_nan()` to check whether `10` is not a number:
```

2023-05-10 19:36 UTC, yangc95 commented on content/php/concepts/math-functions/terms/is-nan/is-nan.md
> +?>
```suggestion
?>
```
```

2023-05-10 19:36 UTC, yangc95 commented on content/php/concepts/math-functions/terms/is-nan/is-nan.md
> +  - 'An nth tag'
```suggestion
```

2023-05-10 19:56 UTC, yangc95 commented on content/php/concepts/math-functions/terms/is-nan/is-nan.md
> +Returns **true** if `n` is 'not a number', else **false**.
It looks like when it's false, it returns nothing and returns 1 when true

2023-05-10 19:56 UTC, yangc95 commented on content/php/concepts/math-functions/terms/is-nan/is-nan.md
> +?>
Nothin should be echoed because it's false

2023-05-10 20:00 UTC, yangc95 reviewed
@tipofey nice succinct entry 👍 I left a few comments and suggestions. Please get to them when you have a chance!

2023-05-10 20:33 UTC, tipofey commented
Cheers @yangc95 ! Not sure it was the most efficient way, but I've created a new pull request based on your suggestions.

2023-05-11 17:14 UTC, yangc95 commented on content/php/concepts/math-functions/terms/is-nan/is-nan.md
> +echo "acos 1.01: ", is_nan(acos(1.01));
```suggestion
  echo "10:", is_nan(10), "\n";
  echo "sqrt of -1: ", is_nan(sqrt(-1));
```

2023-05-11 17:15 UTC, yangc95 commented on content/php/concepts/math-functions/terms/is-nan/is-nan.md
> +echo "acos 1.01: ", is_nan(acos(1.01));
I like this example, since sort of a negative number is undefined

2023-05-11 17:17 UTC, yangc95 commented
@tipofey I don't see a new pull request. It looks like you correctly made changes on this PR which is great.

I left one suggestion on this PR, after which I can approve and we can get a second and final reviewer on this 🙂 thanks!

2023-05-11 20:45 UTC, yangc95 commented on content/php/concepts/math-functions/terms/is-nan/is-nan.md
> +Title: 'is-nan()'
```suggestion
Title: 'is_nan()'
```

2023-05-11 20:46 UTC, yangc95 commented on content/php/concepts/math-functions/terms/is-nan/is-nan.md
> +
```suggestion
```

2023-05-11 20:47 UTC, yangc95 approved these changes
@tipofey With the exception of the two required suggestions I left in the metadata, this looks good for a second reviewer 👍

2023-05-14 02:19 UTC, KTom101 requested changes
@tipofey I took a look at this and have one change, thanks.

2023-05-15 20:32 UTC, tipofey commented
@KTom101 Thanks! Is there anything I need to do at this point?

2023-05-15 20:38 UTC, KTom101 approved these changes
@tipofey No more you have to do. I went ahead and ran `npm run format:all` since the tests were failing. You can read more about that [here](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md#how-can-i-test-my-changes-before-submitting-a-pr) for future entries.

I will be merging this in a minute.

2023-05-15 20:40 UTC, merged

2023-05-15 20:50 UTC, KTom101 commented
The link is live: https://www.codecademy.com/resources/docs/php/math-functions/is-nan

You're currently listed as anonymous:

<img width="723" alt="Screenshot 2023-05-15 at 4 47 23 PM" src="https://github.com/Codecademy/docs/assets/40783324/4f507ecb-f8b6-4d51-bca3-8e4fe761025d">

If you want to remain anonymous, there is nothing more you need to do. If you wish to be listed as a contributor, make sure you've added your GitHub username to your Codecademy profile using the following steps:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

<img width="871" alt="YourGitHubName" src="https://github.com/Codecademy/docs/assets/40783324/3761a3ce-3ae4-4fc6-a1a6-bdb3dc967128">

2.) Then log out and log back into Codecademy using your GitHub login:

<img width="1273" alt="ReLogIn" src="https://github.com/Codecademy/docs/assets/40783324/fc67d020-ab4c-4a96-b42d-fbb2396b7845">

> **Note:** Your email used for Codecademy will have to be listed in your GitHub profile for the login feature to properly work. If you use the same email for both GitHub and Codecademy already, then you're set.

@yangc95 @SSwiniarski