[Concept entry] AI Large Language Model
Codecademy/docs pull request #2131
Opened 2023-05-12 15:29 UTC by Hassan-fayez

Describe what a Large Language Model is.

### Description

-added a new concept to describ the AI LLM
Closes #2108 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-12 15:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2131) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2131) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2131) it.</sub>

2023-05-12 16:07 UTC, SSwiniarski requested changes
@Hassan-fayez I did a first review and left some comments. The most important is the missing metadata and updating the file name.

2023-05-12 16:07 UTC, SSwiniarski commented on content/ai /concepts/ai-models/models/ai-large-language-models/ai-large-language-modelsmd
> +A **Large Language Model (LLM)** is an artificial intelligence system that uses natural language processing (NLP) techniques to generate human-like text. LLMs are based on deep learning models that a
```suggestion
A **Large Language Model (LLM)** is an artificial intelligence system that uses natural language processing (NLP) techniques to generate human-like text. LLMs are based on deep learning models that are trained on massive amounts of text data, allowing them to generate complex language patterns.
```

2023-05-13 18:41 UTC, Hassan-fayez commented
hi @SSwiniarski :) 

thank you for your explanation, i realized that i pushed the wrong branch to the PR.
i have submitted a new  [PR](https://github.com/Codecademy/docs/pull/2165) with the correct metadata and path

2023-05-14 12:05 UTC, SSwiniarski commented
If you're submitting another PR for this, I am closing this one.

2023-05-14 12:05 UTC, closed without merging