added str-repeat.md in str-repeat folder in the string functions in php
Codecademy/docs pull request #2159
Opened 2023-05-12 21:24 UTC by MMMMMMMZ

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-12 21:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2159) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2159) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2159) it.</sub>

2023-05-13 13:59 UTC, SSwiniarski requested changes
@MMMMMMMZ I did a first review and left a few comments.

2023-05-13 13:59 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/str-repeat/str-repeat
> +Title: 'str_replace()'
```suggestion
Title: 'str_repeat()'
```

2023-05-13 13:59 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/str-repeat/str-repeat
> +Description: 'Returns a string with occurrences of a specified substring replaced by another string.'
```suggestion
Description: 'Returns a string with occurrences of a specified substring repeated a specified number of times.'
```

2023-05-13 13:59 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/str-repeat/str-repeat
> +---
Delete the repeated metadata.

2023-05-13 13:59 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/str-repeat/str-repeat
> +# str_repeat()
Delete this header. The metadata Title key will provide the title for the entry. Once you delete this and the repeated metadata, make sure there's only one blank line between the end of the metadata and the first line of the entry.

2023-05-13 13:59 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/str-repeat/str-repeat
> +The `str_repeat()` function repeats a string a specified number of times.
```suggestion
The `str_repeat()` function returns a string that repeats a substring a specified number of times.
```

2023-05-13 13:59 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/str-repeat/str-repeat
> +-  ```$string```  Specifies the string to repeat and it is required.
```suggestion
- `$string`:  Specifies the string to repeat and it is required.
```

2023-05-13 13:59 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/str-repeat/str-repeat
> +- ```$repeat``` Specifies the number of times the string will be repeated. Must be greater or equal to 0 and it is also required.
```suggestion
- `$repeat`: Specifies the number of times the string will be repeated. Must be greater or equal to 0 and it is also required.
```

2023-05-13 13:59 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/str-repeat/str-repeat
> +## Code Byte Example
```suggestion
## Codebyte Example
```

2023-05-13 13:59 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/str-repeat/str-repeat
> +This example provides a few demonstrations of `str_repeat()` operating on a string.
```suggestion
This example provides a few demonstrations of `str_repeat()` operating on a string.

```

2023-05-13 13:59 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/str-repeat/str-repeat
> +Notice How the third echo statment doesn't apear in the output do it being repeated zero times .
```suggestion

Notice how the third `echo` statement doesn't appear in the output due it being repeated zero times.
```

2023-05-14 12:21 UTC, SSwiniarski approved these changes
@MMMMMMMZ Aside from one extra space, looks good for a second review.

2023-05-14 12:21 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/str-repeat/str-repeat
> +- `$string`:  Specifies the string to repeat and it is required.
```suggestion
- `$string`: Specifies the string to repeat and it is required.
```

2023-05-14 12:30 UTC, MMMMMMMZ commented
ok, is it ready now for the second review?

2023-05-27 04:00 UTC, KTom101 requested changes
@MMMMMMMZ I've added a second review.

2023-05-27 04:00 UTC, KTom101 commented on content/php/concepts/string-functions/terms/str-repeat/str-repeat
> +echo (str_repeat("I-don't-apear",0). "\n");
```suggestion
echo (str_repeat("I-don't-appear ",0). "\n");
```

2023-05-27 04:00 UTC, KTom101 commented on content/php/concepts/string-functions/terms/str-repeat/str-repeat
> +Notice how the third `echo` statement doesn't appear in the output due it being repeated zero times.
Bump this line up to line 30 so the codebyte is the last thing on the page.
```suggestion
```

2023-05-27 04:00 UTC, KTom101 commented on content/php/concepts/string-functions/terms/str-repeat/str-repeat
> +
```suggestion

> **Note:** The third echo statement will not output to the console due to the second argument of `str_repeat` being set to `0`.

```

2023-05-27 04:00 UTC, KTom101 commented on content/php/concepts/string-functions/terms/str-repeat/str-repeat
> +echo (str_repeat("Cool",10). "\n");
```suggestion
echo (str_repeat("Cool ",10). "\n");
```

2023-05-27 04:00 UTC, KTom101 commented on content/php/concepts/string-functions/terms/str-repeat/str-repeat
> +echo (str_repeat("I-am-repeated",3)."\n");
```suggestion
echo (str_repeat("I-am-repeated ",3)."\n");
```

2023-05-27 15:40 UTC, SSwiniarski commented
@MMMMMMMZ I did a fix to the filename (it was missing the ".md") and ran an `npm format` so the linting checks would pass. This should be ready to merge once @KTom101 reviews again and approves your edits.

2023-05-30 16:15 UTC, merged

2023-05-30 16:24 UTC, KTom101 commented
@MMMMMMMZ Live link is here: https://www.codecademy.com/resources/docs/php/string-functions/str-repeat

Currently, you're listed as an anonymous contributor:

<img width="842" alt="Screenshot 2023-05-30 at 12 21 04 PM" src="https://github.com/Codecademy/docs/assets/40783324/022aa23c-d749-452b-b7ae-bb71f232f017">

If you want to remain anonymous, there is nothing more you need to do. If you wish to be listed as a contributor, make sure you've added your GitHub username to your Codecademy profile using the following steps:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

<img width="871" alt="YourGitHubName" src="https://github.com/Codecademy/docs/assets/40783324/b11ddb61-1de9-469f-9459-87b1f14338ad">

2.) Then log out and log back into Codecademy using your GitHub login:

<img width="1273" alt="ReLogIn" src="https://github.com/Codecademy/docs/assets/40783324/07821381-4ba5-447a-ac49-2f5c24396531">

> **Note:** Your email used for Codecademy will have to be listed in your GitHub profile for the login feature to properly work. If you use the same email for both GitHub and Codecademy already, then you're set.

cc @yangc95   @SSwiniarski