Oct
Codecademy/docs pull request #2168
Opened 2023-05-14 09:52 UTC by EngOmarAhmedIOS

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ Check ] All writings are my own.
- [ Check ] My entry follows the Codecademy Docs style guide.
- [ Check ] My changes generate no new warnings.
- [ Check ] I have performed a self-review of my own writing and code.
- [ Check ] I have checked my entry and corrected any misspellings.
- [ Check ] I have made corresponding changes to the documentation if needed.
- [ Check ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ Check ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ Check ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-14 09:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2168) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2168) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2168) it.</sub>

2023-05-14 12:13 UTC, EngOmarAhmedIOS commented
can you please review my work ?

2023-05-14 14:01 UTC, SSwiniarski requested changes
@EngOmarAhmedIOS I did a first review and left a few comments.

2023-05-14 14:01 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +```py
````suggestion
```shell
````

2023-05-14 14:01 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +```py
````suggestion
```shell
````

2023-05-14 14:24 UTC, EngOmarAhmedIOS commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +### Parameters
you want me to delete the parameters header

2023-05-14 14:26 UTC, EngOmarAhmedIOS commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +## Example 2
I don't get what is the change I should do, I don't see any difference

2023-05-14 15:31 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +## Example 2
@EngOmarAhmedIOS There's a line break after the header.

2023-05-14 15:31 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +### Parameters
Yes

2023-05-14 18:41 UTC, EngOmarAhmedIOS commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +  - 'Computer Science'
```suggestion
  - 'Computer Science'
  - 'Data Science' 
  - 'Code Foundations'
```

2023-05-14 18:45 UTC, EngOmarAhmedIOS commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +  - 'Numbers'
```suggestion
  - 'Numbers'
  - 'Data Types'
```

2023-05-14 18:48 UTC, EngOmarAhmedIOS commented
I corrected all the requested changes. please review the final file @SSwiniarski

2023-05-15 11:57 UTC, SSwiniarski requested changes
@EngOmarAhmedIOS I had a few more comments, all about removing extra line breaks in the entry.

2023-05-15 11:57 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +
```suggestion
```
Remove extra line break.

2023-05-15 11:57 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +
```suggestion
```
Remove extra line break.

2023-05-15 11:57 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +
```suggestion
```
Remove extra line break.

2023-05-15 11:57 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +
```suggestion
```
Remove extra line break.

2023-05-15 11:57 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +
```suggestion
```
Remove extra line break.

2023-05-15 16:18 UTC, SSwiniarski approved these changes
@EngOmarAhmedIOS Looks good for a second review.

2023-05-15 17:57 UTC, EngOmarAhmedIOS commented
Now I am officially contributor with CodeAcadmey Docs or Should I wait for a second review before celebrating this moment 😁 @SSwiniarski

2023-05-16 07:41 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +The **oct()** function takes an argument and returns an integer converted into an octal string.
```suggestion
The **`oct()`** function takes an integer and returns the corresponding octal string.

```

2023-05-16 07:42 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +Where `integer` is the value which is to be converted into an octal string.
```suggestion
Where `integer` is the value to be converted into an octal string.

```

2023-05-16 07:44 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +# Python oct() function example
```suggestion

```

2023-05-16 07:46 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +This example gets an octal value of a decimal number.
```suggestion
This example returns the octal string for the value `10`.

```

2023-05-16 07:48 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +# binary number
```suggestion
# Binary number  

```

2023-05-16 07:48 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +# hexadecimal number
```suggestion
# Hexadecimal number  

```

2023-05-16 07:50 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/oct/oct.md
> +In Python, binary and hexadecimal values are integer values. So, the `oct()` function can return octal conversion of binary and hexadecimal values as well.
```suggestion
In Python, binary and hexadecimal values are integer values. So, the `oct()` function can convert binary and hexadecimal values as well. 

```

2023-05-16 16:16 UTC, caupolicandiaz approved these changes
@EngOmarAhmedIOS @SSwiniarski Looks good. I just removed a couple of extra lines (there should never be multiple lines between content) and I decided to change the second example to a codebyte.

2023-05-16 16:19 UTC, EngOmarAhmedIOS commented
> @EngOmarAhmedIOS @SSwiniarski Looks good. I just removed a couple of extra lines (there should never be multiple lines between content) and I decided to change the second example to a codebyte.

@caupolicandiaz is there anything I should do now

2023-05-16 16:24 UTC, EngOmarAhmedIOS commented
Should I celebrate 🎉 this moment and consider my self as a contributor with Codeacadmey @caupolicandiaz 😁😁

2023-05-16 16:25 UTC, merged

2023-05-16 16:32 UTC, SSwiniarski commented
@EngOmarAhmedIOS Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/python/built-in-functions/oct

![image](https://github.com/Codecademy/docs/assets/86081858/d1ec63df-ecfb-49b4-a6c4-fd495241924a)