Swift spacer
Codecademy/docs pull request #2174
Opened 2023-05-15 11:43 UTC by jlewr

### Description

Added an entry for the Spacer view in SwiftUI, including syntax, examples and images.

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-15 11:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2174) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2174) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2174) it.</sub>

2023-05-19 16:46 UTC, SSwiniarski requested changes
@jlewr I did a first review and left a few comments, all of which are fairly minor. (Mostly the fact we only bold the fist instance of a term, and in the rest of the entry just highlight keywords with single backticks.)

2023-05-19 16:46 UTC, SSwiniarski commented on content/swiftui/concepts/views/terms/spacer/spacer.md
> +The **`Spacer`** is an adaptive view that expands as much as possible within a stack, such as a **`HStack`** or **`VStack`**.
```suggestion
The **`Spacer`** is an adaptive view that expands as much as possible within a stack, such as a `HStack` or `VStack`.
```

2023-05-19 16:46 UTC, SSwiniarski commented on content/swiftui/concepts/views/terms/spacer/spacer.md
> +
```suggestion
```
delete extra line break

2023-05-19 16:46 UTC, SSwiniarski commented on content/swiftui/concepts/views/terms/spacer/spacer.md
> +
```suggestion
```
delete extra line break

2023-05-19 16:57 UTC, jlewr commented
Thanks @SSwiniarski for reviewing! I think I've added all the changes. Let me know if anything else is required. :)

2023-05-20 13:22 UTC, SSwiniarski approved these changes
@jlewr Looks good for a second review.

2023-06-01 01:24 UTC, gracekishino commented
> Hey @gracekishino ! Would you be comfortable taking this entry on for a second review?

@yangc95 yes I'd love to try it!

2023-06-07 07:14 UTC, gracekishino commented
I took a look through and this looks like a great entry to me! 

@yangc95 The only comment I have is, do we usually not have the `body` view code in syntax blocks?

2023-06-23 11:35 UTC, merged

2023-06-23 11:50 UTC, yangc95 commented
@jlewr live link: https://www.codecademy.com/resources/docs/swiftui/views/spacer

<img width="817" alt="Screenshot 2023-06-23 at 7 41 13 AM" src="https://github.com/Codecademy/docs/assets/72277593/7d0e8054-e221-42d5-9494-87af02170fa8">

It looks as if you're anonymous. If you want to be credited, see [My contribution is live but I’m not being shown as a contributor, why is this?](https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036)

cc: @SSwiniarski