Codeacademy docs hex term creation
Codecademy/docs pull request #2180
Opened 2023-05-16 00:20 UTC by Maternowsky

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-16 00:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2180) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2180) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2180) it.</sub>

2023-05-16 07:37 UTC, caupolicandiaz requested changes
@Maternowsky I've finished my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-05-16 07:37 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/hex/hex.md
> +## Example 1
```suggestion
## Example

```

2023-05-16 07:37 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/hex/hex.md
> +#output: '0x1f'
```suggestion
n = hex(31)
print(n)
```

2023-05-16 07:37 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/hex/hex.md
> +```
```suggestion
```
This will result in the following output:

```shell
'0x1f'
```

2023-05-16 07:37 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/hex/hex.md
> +Print the hexidecimal converted values of the array `[1, 100, -200, 5834]`
```suggestion
The following example prints the hexadecimal values of the array `[1, 100, -200, 5834]`. 
```

2023-05-25 16:17 UTC, SSwiniarski requested changes
@Maternowsky I did a second review and had one comment.

2023-05-25 16:17 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/hex/hex.md
> +
Like to see one sentence describing the syntax explaining what `integer` is.

2023-05-26 15:20 UTC, SSwiniarski requested changes
@Maternowsky, Thanks, but you misunderstood my comment

2023-05-26 15:20 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/hex/hex.md
> +An **integer** is the number zero (0), a postive natural number (1, 2, 3, etc.) or a negative integer that includes a minus sign (-1, -2, -3, etc).
```suggestion
```
You misunderstand what I meant. I want a sentence explaining what the value `integer` is in the code `hex(integer)`. Something like:
```
The value `integer` is the value `hex()` will turn into a hexadecimal string.
```

It should also be after the ` ```pseudo ` code block.

2023-05-26 16:09 UTC, merged

2023-05-26 16:13 UTC, SSwiniarski commented
@Maternowsky Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/python/built-in-functions/hex

You're currently listed as an anonymous contributor. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.

![image](https://github.com/Codecademy/docs/assets/86081858/a7ec98f3-0702-4d96-bace-5aaee1b8fd6c)

To add your GitHub username to your Codecademy profile:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

![image](https://github.com/Codecademy/docs/assets/86081858/4de025f0-9125-4684-9ae2-5bcedc6ec223)

2.) Then log out and log back into Codecademy using your GitHub login:

![image](https://github.com/Codecademy/docs/assets/86081858/05f53f73-05e5-4962-bf2d-ef7505563eed)

**Note:** Your email used for Codecademy will have to be listed in your GitHub profile for the login feature to properly work. If you use the same email for both GitHub and Codecademy already, then you're set.