[Term entry] Python Built-in-Function: .Repr()
Codecademy/docs pull request #2183
Opened 2023-05-16 10:27 UTC by Mboatella25

### Description

- Added the .repr() function for Python.
- Closes Issue #2152 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-16 10:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2183) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2183) before we can accept your contribution.<br/><hr/>**Marie** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2183) it.</sub>

2023-05-16 11:17 UTC, SSwiniarski commented
@Mboatella25 yo seem to have committed this with an e-mail that isn't linked to your GitHub account. Please add the "Marie" email to your GitHub account and sign the [CLA](https://cla-assistant.io/Codecademy/docs?pullRequest=2183).

2023-05-16 11:22 UTC, SSwiniarski requested changes
@Mboatella25  I did a first review and left some comments, all about line breaks in your entry.

2023-05-16 11:22 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/repr/repr.md
> +---
```suggestion
---

```
Add a line break after metadata.

2023-05-16 11:22 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/repr/repr.md
> +
```suggestion
```
Remove extra line break

2023-05-16 11:22 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/repr/repr.md
> +
```suggestion
```
Remove extra line break.

2023-05-16 11:22 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/repr/repr.md
> +
```suggestion
```
Remove extra line break.

2023-05-16 11:22 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/repr/repr.md
> +
```suggestion
```
Remove extra line break

2023-05-16 11:22 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/repr/repr.md
> +
```suggestion
```
Remove extra line break

2023-05-16 11:22 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/repr/repr.md
> +var = Variable()
```suggestion

var = Variable()
```
Add line break.

2023-05-18 00:00 UTC, yangc95 commented on content/python/concepts/built-in-functions/terms/repr/repr.md
> +Title: '.repr()'
```suggestion
Title: 'repr()'
```

2023-05-18 00:01 UTC, yangc95 commented on content/python/concepts/built-in-functions/terms/repr/repr.md
> +Description: 'Returns a printable string describing the object.'
```suggestion
Description: 'Returns a printable string describing the object that is passed in.'
```

2023-05-18 00:02 UTC, yangc95 commented on content/python/concepts/built-in-functions/terms/repr/repr.md
> +A class can control what this function returns for its instances when called by defining a [`__repr__()`](https://www.codecademy.com/resources/docs/python/dunder-methods/repr) dunder method.
Either add a new line between these two or combine onto one line.

Also:

```suggestion
The **`repr()`** function returns a printable string describing the object that is passed in. It gives us the string representation passed implicitly to the `eval()` function.

A class can control what this function returns for its instances when called by defining a [`__repr__()`](https://www.codecademy.com/resources/docs/python/dunder-methods/repr) dunder method.
```

2023-05-18 00:02 UTC, yangc95 commented on content/python/concepts/built-in-functions/terms/repr/repr.md
> +- The first one returns the default value (a string with the name and address of the object, enclosed in angle brackets).
```suggestion
Here, two instances of `repr()` are called:

- The first one returns the default value (a string with the name and address of the object, enclosed in angle brackets).
```

2023-05-18 00:03 UTC, yangc95 commented on content/python/concepts/built-in-functions/terms/repr/repr.md
> +
```suggestion
print(repr(cte))
print(repr(var))
```

2023-05-18 00:04 UTC, yangc95 reviewed
@Mboatella25 Conducted a second review. Please tag me once you'd like me to take another look

2023-05-18 08:58 UTC, Mboatella25 commented
@yangc95 Fixed the issues of the second review.

2023-06-02 23:11 UTC, yangc95 approved these changes

2023-06-02 23:57 UTC, merged

2023-06-03 00:02 UTC, yangc95 commented
Thanks for this entry @Mboatella25 🙌 Feel free to make additional edits to this entry at any time.

<img width="880" alt="Screenshot 2023-06-02 at 8 00 33 PM" src="https://github.com/Codecademy/docs/assets/72277593/127ec0fa-fea4-40f4-aace-7877fd6ce961">

It looks as if you're anonymous. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.
To add your GitHub username to your Codecademy profile:
1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
![githubusername](https://github.com/Codecademy/docs/assets/72277593/4229f2bf-58f2-4ae2-90cc-9e644d53fe4f)

Make sure to set your visibility to “everyone”:
<img width="537" alt="Screenshot 2023-04-10 at 4 07 30 PM" src="https://github.com/Codecademy/docs/assets/72277593/5c4ae55a-6a95-4252-927a-243e6e449f3e">


2.) Then log out and log back into Codecademy using your GitHub login:
<img width="976" alt="githublogin" src="https://github.com/Codecademy/docs/assets/72277593/8669f6d2-0c6d-4cb4-8f0f-0523002a9805">

If the steps above do not work, it may be due to an email or local configuration issue.
In addition, we may reach out in the future if any adjustments to these entries are required.

cc: @SSwiniarski