built in function iter()
Codecademy/docs pull request #2196
Opened 2023-05-18 04:34 UTC by nikolaspoczekaj

### Description

Hey, thanks for assigning me. As my first contribution I worked on issue #2147.

### Type of Change

- Added iter.md

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-18 04:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2196) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2196) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2196) it.</sub>

2023-05-18 07:39 UTC, caupolicandiaz requested changes
@nikolaspoczekaj I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-05-18 07:39 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/iter/iter.md
> +  - 'Built-in Functions'
```suggestion
  - 'Functions'
```

2023-05-18 07:39 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/iter/iter.md
> +Here is an example of how you might use the `iter()` function:
```suggestion
The code below demonstrates the use of the `iter()` function:
```

2023-05-18 07:39 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/iter/iter.md
> +# create a list
```suggestion
# Create a list
```

2023-05-18 07:39 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/iter/iter.md
> +# get an iterator object
```suggestion
# Get an iterator object
```

2023-05-18 07:39 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/iter/iter.md
> +# iterate over the list using the iterator
```suggestion
# Iterate over the list using the iterator
```

2023-05-18 07:39 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/iter/iter.md
> +In the above code snippet, we first create a list of fruits. We then use the `iter()` function to get an iterator object for the list. Finally, we use the `next()` function to iterate over the items
```suggestion
In the code above a list is declared, and the `iter()` function is used to get an iterator object for the list. Finally, the `next()` function is used to step through the items in the list.
```

2023-05-18 07:39 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/iter/iter.md
> +In the above code snippet, we first create a list of fruits. We then use the `iter()` function to get an iterator object for the list. Finally, we use the `next()` function to iterate over the items
Generally, we try to avoid the use of first and second person pronouns in docs (I, you, we)

2023-05-18 07:39 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/iter/iter.md
> +In the following example, we are doing almost the same thing as in the previous example. However, we are using a `while True` loop to continue calling `next(fruit_iter)` until a `StopIteration` excep
```suggestion
In the following example, the code is iterating and printing the items in the `fruits` list as in the previous example. However, in this instance a `while` loop is used to continue calling `next(fruit_iter)` until a `StopIteration` exception is raised, indicating that there are no more items to iterate over.
```

2023-05-18 07:39 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/iter/iter.md
> +The `iter()` function has two main forms:
```suggestion
```

2023-05-18 07:53 UTC, nikolaspoczekaj commented
@caupolicandiaz 

Done! Thanks for the quick review:)

2023-05-18 08:38 UTC, caupolicandiaz approved these changes
@nikolaspoczekaj Looks good, this is ready for a second review.

2023-05-18 16:30 UTC, SSwiniarski requested changes
@nikolaspoczekaj Looks good, I only had one comment to address.

2023-05-18 16:30 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/iter/iter.md
> +The **`iter()`** function is a built-in Python function used to create an **iterator** object.
```suggestion
The **`iter()`** function is a built-in Python function used to create an `iterator` object.
```

2023-05-18 16:33 UTC, nikolaspoczekaj commented
@SSwiniarski 

Okay, done. Thanks for the review :)

2023-05-19 11:15 UTC, SSwiniarski approved these changes

2023-05-19 11:17 UTC, merged

2023-05-19 11:22 UTC, SSwiniarski commented
@nikolaspoczekaj Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/python/built-in-functions/iter

![image](https://github.com/Codecademy/docs/assets/86081858/8599317d-6639-45c5-ab8f-ad3e8f82f1b9)

2023-05-19 15:08 UTC, nikolaspoczekaj commented
Thanks @SSwiniarski !

I'm looking forward to contributing more.

2023-05-30 21:31 UTC, yangc95 commented
Hey @nikolaspoczekaj! Thanks again for this entry. Our team of maintainers noticed that there is an overlap of terms. It appears that the `iter()` functions existed in the Iterators concept and this entry needs to be moved.

Would you be able to create a new pull request for edits? You'll be removing this folder/file path and doing a bit more critical thinking work by incorporating what you have in this entry, with the existing [iter()](https://www.codecademy.com/resources/docs/python/iterators/iter) entry. Please let me know if you have any questions or concerns!

2023-05-31 13:52 UTC, nikolaspoczekaj commented
Hi @yangc95 , I'll take care of it :)

2023-05-31 15:46 UTC, SSwiniarski commented
@nikolaspoczekaj Yes, that's the idea.