[Edit] Go: Maps
Codecademy/docs pull request #2197
Opened 2023-05-18 15:29 UTC by caupolicandiaz

### Description

This PR makes several corrections and additions to the Go map entry including:
- Clarifying the declaration syntax which referred to `create` in lieu of `make` which is the syntax used in an example
- Modifying header capitalization
- Adding a section on removing items
- Truncating code examples that use the same map
- Changing the final example to be a codebyte to match the existing header

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-18 15:34 UTC, yangc95 commented on content/go/concepts/map/map.md
> +
```suggestion
```

```

2023-05-18 15:35 UTC, yangc95 commented on content/go/concepts/map/map.md
> +
Closing backticks needed

2023-05-18 15:36 UTC, yangc95 approved these changes
@caupolicandiaz two minor format suggestions. Looks great and you definitely improved clarity for this entry!

2023-05-18 16:21 UTC, SSwiniarski requested changes
@caupolicandiaz other than my two comments, looks good to go.

2023-05-18 16:21 UTC, SSwiniarski commented on content/go/concepts/map/map.md
> +
````suggestion
```

````

2023-05-18 16:21 UTC, SSwiniarski commented on content/go/concepts/map/map.md
> +````
````suggestion
```
````

2023-05-18 19:57 UTC, HishamT reviewed
Finished reviewing the entry. I noticed that the functions are written as `function()` as opposed to `.function()`. I believe the standard was to use the '.' in the function name.

2023-05-18 19:57 UTC, HishamT commented on content/go/concepts/map/map.md
> +A **map** is a built-in data structure that is used to store a collection of unordered key-value pairs. The pairs can be of the same type, or of mixed types. It is Go's implementation of a hash table
```suggestion
A **map** is a built-in data structure that is used to store a collection of unordered key-value pairs. The pairs can be of the same type or of mixed types. It is Go's implementation of a hash table, which allows for efficient access, insertion, and deletion.
```

2023-05-19 07:34 UTC, caupolicandiaz commented
> Finished reviewing the entry. I noticed that the functions are written as `function()` as opposed to `.function()`. I believe the standard was to use the '.' in the function name.

I believe we generally format this based on how the functions are implemented. Some functions are applied using "dot notation" and others like the built-in len() function in python are passed arguments, so we don't include a period.

2023-05-19 11:29 UTC, SSwiniarski approved these changes

2023-05-19 11:35 UTC, merged

2023-05-26 00:56 UTC, yangc95 commented
> > Finished reviewing the entry. I noticed that the functions are written as `function()` as opposed to `.function()`. I believe the standard was to use the '.' in the function name.
> 
> I believe we generally format the names based on how the functions are implemented. Some functions are applied using "dot notation" and others like the built-in len() function in python are passed arguments, so we don't include a period.

Sounds right! Functions are written without the dot, while methods are. This is dependent on the concept entry 🙂

2023-05-26 01:00 UTC, yangc95 commented
🎉  @caupolicandiaz edits will appear here: https://www.codecademy.com/resources/docs/go/map

cc: @HishamT @SSwiniarski