Term entry java script window clear interval
Codecademy/docs pull request #2233
Opened 2023-05-21 03:16 UTC by RaffyRod

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-21 03:18 UTC, RaffyRod commented
@KTom101  @yangc95  this one is ready too.

2023-05-21 15:33 UTC, SSwiniarski requested changes
@RaffyRod I did a first review and left a few comments.

2023-05-21 15:33 UTC, SSwiniarski commented on content/javascript/concepts/window-clearInterval/window-clearInterval.md
> +Description: 'cancels a timer previously stablished by setInterval()'
```suggestion
Description: 'Cancels a timer previously stablished by setInterval().'
```

2023-05-21 15:33 UTC, SSwiniarski commented on content/javascript/concepts/window-clearInterval/window-clearInterval.md
> +**`clearInterval`** is a window method used to shut down the loop-calling process of a **setInterval()** execution when this has been called and must be stopped or aborted it.
```suggestion
**`clearInterval()`** is a window method used to shut down the loop-calling process of a `setInterval()` execution when it must be stopped or aborted.
```

2023-05-21 15:33 UTC, SSwiniarski commented on content/javascript/concepts/window-clearInterval/window-clearInterval.md
> +Title: 'clearInterval'
```suggestion
Title: 'clearInterval()'
```

2023-05-21 15:33 UTC, SSwiniarski commented on content/javascript/concepts/window-clearInterval/window-clearInterval.md
> +**`clearInterval`** receives a parameter called intervalId which is returned from the previously created `setInterval()` timer.
```suggestion
`clearInterval()` receives a parameter called `intervalId` which is returned from the previously created `setInterval()` timer.
```

2023-05-21 15:33 UTC, SSwiniarski commented on content/javascript/concepts/window-clearInterval/window-clearInterval.md
> +The provided sample code contains some examples of how `clearInterval` is composed:
```suggestion
The below is an example of how `clearInterval()` is composed:
```

2023-05-21 15:33 UTC, SSwiniarski commented on content/javascript/concepts/window-clearInterval/window-clearInterval.md
> +
We need an introductory sentence describing what the example does. Also, it doesn't actually stop the timer, it just declares a function to do so.

2023-05-22 02:46 UTC, RaffyRod commented
@SSwiniarski added suggested changes.

2023-05-22 16:25 UTC, SSwiniarski requested changes
@RaffyRod I did another pass and left a few more comments.

2023-05-22 16:25 UTC, SSwiniarski commented on content/javascript/concepts/window-clearInterval/window-clearInterval.md
> +The following sample shows the usage of `clearInterval()` by canceling a previously added `setInterval()` to a function.
The example still never stops the timer. Edit it so it actually uses the function you created.

2023-05-22 18:08 UTC, RaffyRod commented
@SSwiniarski changes added.

2023-05-23 15:38 UTC, SSwiniarski requested changes
@RaffyRod Still need to update the example.

2023-05-23 15:38 UTC, SSwiniarski commented on content/javascript/concepts/window-clearInterval/window-clearInterval.md
> +
You're still never calling the function in this example, so the example never executes `clearInterval()`

2023-05-23 16:39 UTC, SSwiniarski approved these changes
@RaffyRod Looks good for a second review.

2023-05-26 14:14 UTC, caupolicandiaz requested changes
@RaffyRod I've added a couple of comments. Tag me when you've made the changes. Thanks

2023-05-26 17:13 UTC, RaffyRod commented
@caupolicandiaz  changes added.

2023-05-28 13:15 UTC, caupolicandiaz approved these changes
@RaffyRod @SSwiniarski Looks good to go.

2023-05-28 13:26 UTC, SSwiniarski commented
@RaffyRod, @caupolicandiaz We should wait for #2282 to merge, before merging this one.

2023-05-29 13:02 UTC, merged

2023-05-29 13:08 UTC, SSwiniarski commented
@RaffyRod Thanks for your patience waiting for this to merge, and congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/javascript/window/clearInterval

![image](https://github.com/Codecademy/docs/assets/86081858/7938004e-953b-444d-ad6f-97ac80550132)