sql-math-function-power
Codecademy/docs pull request #2239
Opened 2023-05-22 17:19 UTC by nikolaspoczekaj

### Description

This closes #2219 . Thanks for assigning me.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-23 10:13 UTC, caupolicandiaz requested changes
@nikolaspoczekaj Just completed my initial review and I only had a couple of comments. Please update and tag me when you've finished. Thanks

2023-05-23 10:13 UTC, caupolicandiaz commented on content/sql/concepts/math-functions/terms/power/power.md
> +Description: 'Calculates the power of a number.'
```suggestion
Description: 'Returns the value of a number raised to the power of another number.'
```

2023-05-23 10:27 UTC, nikolaspoczekaj commented
@caupolicandiaz Done :)

2023-05-23 15:56 UTC, caupolicandiaz approved these changes
@nikolaspoczekaj Looks good

2023-05-23 16:23 UTC, SSwiniarski approved these changes
@nikolaspoczekaj Looks good to merge.

2023-05-23 16:24 UTC, merged

2023-05-23 16:36 UTC, SSwiniarski commented
@nikolaspoczekaj, congrats on the new entry. Unfortunately it won't be visible on the site until we merge [2228](https://github.com/Codecademy/docs/pull/2228).

2023-05-25 19:29 UTC, yangc95 commented
🥳 @nikolaspoczekaj livelink: https://www.codecademy.com/resources/docs/sql/math-functions/power

<img width="962" alt="Screenshot 2023-05-25 at 3 28 59 PM" src="https://github.com/Codecademy/docs/assets/72277593/cc331365-5500-4ea6-8b8d-2e97a50b8ea3">