sql-math-function-abs
Codecademy/docs pull request #2240
Opened 2023-05-22 17:42 UTC by nikolaspoczekaj

### Description

This closes #2216 . Thanks for assigning me.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-22 17:44 UTC, yangc95 commented on content/sql/concepts/math-functions/terms/abs/abs.md
> +Description: 'Returns the absolute value of a given number'
```suggestion
Description: 'Returns the absolute value of a given number.'
```

2023-05-22 17:49 UTC, yangc95 commented on content/sql/concepts/math-functions/terms/abs/abs.md
> +That means, It effectively converts negative numbers to positive numbers, and leaves positive numbers unchanged.
```suggestion
The `ABS()` function in SQL returns the absolute value of a given number. That means, it effectively converts negative numbers to positive numbers, and leaves positive numbers unchanged.
```

2023-05-22 17:51 UTC, yangc95 commented on content/sql/concepts/math-functions/terms/abs/abs.md
> +In this example the following data is given:
```suggestion
In this example, the following data is given in a `transactions` table:
```

2023-05-22 17:54 UTC, yangc95 reviewed
Nice one @nikolaspoczekaj! Minor changes here.

Also, can you add a note about which flavors of SQL support this function? I found these: MySQL, PostgreSQL, Oracle and SQL Server but please confirm and add it in as a note.

2023-05-22 18:07 UTC, nikolaspoczekaj commented
Thanks @yangc95 . Commited the changes. What do you think ?

2023-05-22 18:15 UTC, yangc95 approved these changes
Looks good for a second review, just make sure to turn that note into a block quote

2023-05-22 18:15 UTC, yangc95 commented on content/sql/concepts/math-functions/terms/abs/abs.md
> +**Note:** `ABS()` is compatible with various SQL database systems such as MySQL, PostgreSQL, Oracle, and SQL Server.
turn this into a block quote

2023-05-22 18:15 UTC, yangc95 approved these changes
Looks good for a second review, just make sure to turn that note into a block quote

2023-05-22 18:23 UTC, nikolaspoczekaj commented
Done :) @yangc95

2023-05-23 09:57 UTC, caupolicandiaz requested changes
@nikolaspoczekaj Looks good, just left one comment.

2023-05-23 09:57 UTC, caupolicandiaz commented on content/sql/concepts/math-functions/terms/abs/abs.md
> +The `ABS()` function in SQL returns the absolute value of a given number. That means, it effectively converts negative numbers to positive numbers, and leaves positive numbers unchanged.
```suggestion
The **`ABS()`** function in SQL returns the absolute value of a given number. That means, it effectively converts negative numbers to positive numbers, and leaves positive numbers unchanged.
```

2023-05-23 10:03 UTC, nikolaspoczekaj commented
@caupolicandiaz thanks. change commited.

2023-05-23 15:54 UTC, caupolicandiaz approved these changes
@nikolaspoczekaj @yangc95 Looks good to me.

2023-05-29 13:35 UTC, merged

2023-05-29 13:45 UTC, SSwiniarski commented
@nikolaspoczekaj Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/sql/math-functions/abs

![image](https://github.com/Codecademy/docs/assets/86081858/4998fb6e-40e8-4a1b-8999-f9274e01b73e)