added cosine function
Codecademy/docs pull request #2244
Opened 2023-05-23 13:47 UTC by KushagraVarshney05

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-23 13:48 UTC, KushagraVarshney05 commented
@yoiang @SSwiniarski i have completed the cos function.....pls review it!!!

2023-05-23 15:53 UTC, SSwiniarski approved these changes
@KushagraVarshney05 The PR itself looks good, but there are two other points:

1. You need to sign the [CLA](https://cla-assistant.io/Codecademy/docs?pullRequest=2244).
2. You made this PR off your main branch, which is not best practice. Next time make a new branch off of main for your PR. This shouldn't cause any issues as long as you don't submit another PR before this one is merged.

2023-05-27 05:32 UTC, KushagraVarshney05 commented
@SSwiniarski @yoiang  I have made the required changes

2023-06-04 07:09 UTC, KushagraVarshney05 commented
> @KushagraVarshney05 The PR itself looks good, but there are two other points:
> 
> 1. You need to sign the [CLA](https://cla-assistant.io/Codecademy/docs?pullRequest=2244).
> 2. You made this PR off your main branch, which is not best practice. Next time make a new branch off of main for your PR. This shouldn't cause any issues as long as you don't submit another PR before this one is merged.

i have signed the CLA but my pr still has not merged

2023-06-04 11:52 UTC, SSwiniarski commented
> > @KushagraVarshney05 The PR itself looks good, but there are two other points:
> > 
> > 1. You need to sign the [CLA](https://cla-assistant.io/Codecademy/docs?pullRequest=2244).
> > 2. You made this PR off your main branch, which is not best practice. Next time make a new branch off of main for your PR. This shouldn't cause any issues as long as you don't submit another PR before this one is merged.
> 
> i have signed the CLA but my pr still has not merged

@KushagraVarshney05 Have patience. PRs require two reviews. After the next review and any issues are dealt with, then it can be merged.

2023-06-14 04:44 UTC, KTom101 requested changes
@KushagraVarshney05 I added on change

2023-06-14 04:44 UTC, KTom101 commented on content/php/concepts/math-functions/terms/cos/cos.md
> +Using `cos()` to return the tangent of the angle in radians:
```suggestion
Using `cos()` to return the cosine of the angle in radians:
```

2023-06-17 21:33 UTC, KTom101 approved these changes
@KushagraVarshney05 I went ahead and committed the change. This looks good to merge. 👍

2023-06-17 21:34 UTC, merged

2023-06-17 21:36 UTC, KTom101 commented
@KushagraVarshney05 Also, please note for the future do not use your `main` branch. It is highly discouraged. Make a new branch for every new entry.

2023-06-17 21:56 UTC, KTom101 commented
@KushagraVarshney05 Entry is live: https://www.codecademy.com/resources/docs/php/math-functions/cos 

You're currently listed as an unknown contributor:

<img width="788" alt="Screenshot 2023-06-17 at 5 52 26 PM" src="https://github.com/Codecademy/docs/assets/40783324/62b7bfa7-6f61-44b0-906c-fa2294a1ebc4">

If you wish to remain that way, there is nothing more you need to do. Otherwise, if you want your profile listed follow the steps linked [here](https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036
).