Edit javascript codebyte1
Codecademy/docs pull request #2245
Opened 2023-05-23 14:33 UTC by cslylla

### Description

- The following terms were updated:

  - JavaScript/Dates: .getDate(),
  - JavaScript/Dates: .getDay(),
  - JavaScript/Dates: .getHours(),

- The following changes were made:
  - Add codebyte example,
  - Fix typos,
  - Update term definitions to match other terms

- Closes: #2226 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-23 16:32 UTC, caupolicandiaz requested changes
@cslylla I've completed my initial review. Please update the entries, and tag me when you've finished making changes. Thanks

2023-05-23 16:32 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getDate/getDate.md
> +The example below is runnable, and first, it defines a variable `myDate` with a given new `Date`, then uses the `getDate()` method to store the day from that date into a variable called `payDay`. The
```suggestion
The example below is runnable, and assigns the variable `myDate` to a new given `Date`, then the result of the `.getDate()` method is stored in `payDay`. Finally, a `console.log` call prints this value to the screen:
```

2023-05-23 16:32 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getDate/getDate.md
>  ```js
```suggestion
```shell
```

2023-05-23 16:32 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getDay/getDay.md
>  ```js
```suggestion
```shell
```

2023-05-23 16:32 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getDate/getDate.md
> +The return value of `getDate()` is an integer number between `1` and `31` representing the day of a month.
```suggestion
The return value of `.getDate()` is an integer number between `1` and `31` representing the day of a month.
```

2023-05-23 16:32 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getDay/getDay.md
> +The return value of `getDay()` is an integer number between `0` and `6`:
```suggestion
The return value of `.getDay()` is an integer number between `0` and `6`:
```

2023-05-23 16:32 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getDay/getDay.md
> +The example below is runnable, and first, it defines a variable called `today` with a new `Date` of today's date, then uses the `getDay()` method to store the weekday from that date into a variable c
```suggestion
The example below is runnable, and first, it defines `today` with today's date, then the result of the `.getDay()` method is assigned to `weekDay`. Finally, a `console.log` call prints the value to the screen:
```

2023-05-23 16:32 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getHours/getHours.md
>  ```js
```suggestion
```shell
```

2023-05-23 16:32 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getHours/getHours.md
> +The return value of `getHours()` is an integer number between `0` and `23`, meaning the hour according to the local time.
```suggestion
The return value of `.getHours()` is an integer number between `0` and `23`, meaning the hour according to the local time.
```

2023-05-23 16:32 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getHours/getHours.md
> +The example below is runnable, and first, it defines a variable called `currentTime` with a new `Date` of today's date and time, then uses the `getHours()` method to store the hour from that date int
```suggestion
The example below is runnable, and first, it defines `currentTime` with today's date and time, then the result of the `.getHours()`method is saved in `currentHour`. Lastly, a `console.log` call prints the value to the screen:
```

2023-05-23 16:32 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getHours/getHours.md
> +console.log("The current hour of the day is: " + currentHour);
```suggestion
console.log("The current hour is: " + currentHour);
```

2023-05-23 16:32 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getDate/getDate.md
> +The example below is runnable, and first, it defines a variable `myDate` with a given new `Date`, then uses the `getDate()` method to store the day from that date into a variable called `payDay`. The
Generally, I think these example introductions should be minimal.

2023-05-23 16:33 UTC, caupolicandiaz requested changes
@cslylla I've completed my initial review. Please update the entries, and tag me when you've finished making changes. Thanks

2023-05-23 16:42 UTC, cslylla commented
@caupolicandiaz I approved the changes.

2023-05-24 11:28 UTC, caupolicandiaz approved these changes
@cslylla Looks good, this is ready for a second review.

2023-05-24 15:56 UTC, merged

2023-05-24 16:03 UTC, SSwiniarski commented
@yangc95, @KTom101, @caupolicandiaz, @HishamT-- Just noted that this seems to have overwritten the original authors for these entries.

2023-05-24 18:10 UTC, KTom101 commented
@SSwiniarski In previous entries when the original author was anonymous, the author of the edit is listed and the anonymous author thumbnail wouldn't appear anymore. But I'm not sure if this is what happened here, do we know if the previous authors were anonymous?

2023-05-25 18:59 UTC, yangc95 commented
@SSwiniarski @KTom101 The original author was @EugeneGohh and it looks like the entries written are anonymous. See: https://www.codecademy.com/resources/docs/javascript/dates/getMinutes which was also written by Eugene.

2023-05-25 19:52 UTC, KTom101 commented
Thanks @yangc95 ❤️