added asin.md
Codecademy/docs pull request #2247
Opened 2023-05-23 15:59 UTC by ChiragAgg5k

### Description

Added a new term entry for php about the asin() function in a new file in docs/content/php/concepts/math-functions/terms/asin/asin.md

Closes #2203

### Type of Change

- Adding a new entry

### Checklist

- [✅] All writings are my own.
- [✅] My entry follows the Codecademy Docs style guide.
- [✅] My changes generate no new warnings.
- [✅] I have performed a self-review of my own writing and code.
- [✅] I have checked my entry and corrected any misspellings.
- [✅] I have made corresponding changes to the documentation if needed.
- [✅] I have confirmed my changes are not being pushed from my forked `main` branch.
- [✅] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [✅] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

<!--

2023-05-23 16:21 UTC, SSwiniarski requested changes
@ChiragAgg5k I did a first review and left two comments. Otherwise this looks good.

2023-05-23 16:21 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/asin/asin.md
> +
```suggestion
```
Remove extra line break.

2023-05-23 16:21 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/asin/asin.md
> +The codebyte example below uses the `asin()` function to return the arc sine of the `2` and `-1`:
```suggestion
The codebyte example below uses the `asin()` function to return the arc sine of `2` and `-1`:
```

2023-05-23 16:26 UTC, ChiragAgg5k commented
Implemented the reviewed changes

2023-06-06 17:35 UTC, ChiragAgg5k commented
@SSwiniarski hey... is there any update regarding this pr?

2023-06-06 22:17 UTC, yangc95 commented
Thanks for your patience @ChiragAgg5k I can conduct the second review.

2023-06-06 22:21 UTC, yangc95 approved these changes

2023-06-06 22:25 UTC, merged

2023-06-06 22:38 UTC, yangc95 commented
🥳 @ChiragAgg5k live link: https://www.codecademy.com/resources/docs/php/math-functions/asin

<img width="734" alt="Screenshot 2023-06-05 at 7 25 21 PM" src="https://github.com/Codecademy/docs/assets/72277593/b6078f8d-8965-468e-97cf-8300fca48ca5">

It looks as if you're anonymous. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.
To add your GitHub username to your Codecademy profile:
1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
![githubusername](https://github.com/Codecademy/docs/assets/72277593/98fd730f-38aa-4c48-bca2-4ffb27a0dafa)

Make sure to set your visibility to “everyone”:

<img width="537" alt="Screenshot 2023-04-10 at 4 07 30 PM" src="https://github.com/Codecademy/docs/assets/72277593/93688ec1-1e64-4d80-9231-d6cb305392c9">

2.) Then log out and log back into Codecademy using your GitHub login:
<img width="976" alt="githublogin" src="https://github.com/Codecademy/docs/assets/72277593/4b173fbd-ffe8-4ffa-baf7-79e577a50eaf">

If the steps above do not work, it may be due to an email or local configuration issue.
In addition, we may reach out in the future if any adjustments to these entries are required.


cc: @SSwiniarski