Added R-conditionals
Codecademy/docs pull request #2249
Opened 2023-05-24 08:32 UTC by jdagz28

### Description
Added information on conditionals in R at docs/content/r/concepts/conditionals/conditionals.md.

### Type of Change
- Adding a new entry

### Checklist
- [✅] All writings are my own.
- [✅] My entry follows the Codecademy Docs style guide.
- [✅] My changes generate no new warnings.
- [✅] I have performed a self-review of my own writing and code.
- [✅] I have checked my entry and corrected any misspellings.
- [✅] I have made corresponding changes to the documentation if needed.
- [✅] I have confirmed my changes are not being pushed from my forked `main` branch.
- [✅] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [✅] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-24 08:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2249) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2249) before we can accept your contribution.<br/><hr/>**Joshua Dagoy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2249) it.</sub>

2023-05-25 05:05 UTC, caupolicandiaz requested changes
@jdagz28 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-05-25 05:05 UTC, caupolicandiaz commented on content/r/concepts/conditionals/conditionals.md
> +    Output: `x is less than y`
Usually we prefer using a separate shell block for displaying the output; however, with entries such as this, with many examples, we allow for commented outputs within the same block.

2023-05-25 05:05 UTC, caupolicandiaz commented on content/r/concepts/conditionals/conditionals.md
> +Logical operators in R allow you to combine or negate logical values. Here are the commonly used logical operators:
```suggestion
Logical operators in R allow can be used to combine or negate logical values. Here are the commonly used logical operators:
```

2023-05-25 05:05 UTC, caupolicandiaz commented on content/r/concepts/conditionals/conditionals.md
> +- `&&` (and): Returns `TRUE` if both the left and right operands are `TRUE`.
I think this section should also be consolidated in two parts as above. List all of the operators with their definitions and then the examples.

2023-05-25 05:05 UTC, caupolicandiaz commented on content/r/concepts/conditionals/conditionals.md
> +These are the basic conditional statements, comparison operators, and logical operators in R. They allow you to control the flow of your program, compare values, and make decisions based on specific
```suggestion
These are the basic conditional statements, comparison operators, and logical operators in R. They can be leveraged to control the flow of a program, compare values, and make decisions based on specific conditions.
```

2023-05-25 07:59 UTC, jdagz28 commented
Hi @caupolicandiaz, made the necessary changes. Please let me know if there are more changes to be made.

Thank you.

2023-05-25 11:19 UTC, caupolicandiaz requested changes
@jdagz28 I've added some additional comments. Tag me for another review when you've made the changes. Thanks

2023-05-25 11:19 UTC, caupolicandiaz commented on content/r/concepts/conditionals/conditionals.md
> +Title: 'R - Conditionals'
```suggestion
Title: 'Conditionals'
```

2023-05-25 11:19 UTC, caupolicandiaz commented on content/r/concepts/conditionals/conditionals.md
> +Description: 'A brief description on the usage of conditional statements, comparison and logic operators in R'
```suggestion
Description: 'Statements that return a boolean value that provide control flow in a program.'
```

2023-05-25 11:19 UTC, caupolicandiaz commented on content/r/concepts/conditionals/conditionals.md
> +  - 'Conditinal Statements'
```suggestion
  - 'Conditional Statements'
```

2023-05-25 11:19 UTC, caupolicandiaz commented on content/r/concepts/conditionals/conditionals.md
> +  - 'conditionals'
```suggestion
  - 'Conditionals'
```

2023-05-25 11:19 UTC, caupolicandiaz commented on content/r/concepts/conditionals/conditionals.md
> +  - 'comparison'
```suggestion
  - 'Comparison'
```

2023-05-25 11:19 UTC, caupolicandiaz commented on content/r/concepts/conditionals/conditionals.md
> +  - 'logic'
```suggestion
  - 'Logic'
```

2023-05-25 11:19 UTC, caupolicandiaz commented on content/r/concepts/conditionals/conditionals.md
> +
```suggestion
```

2023-05-25 11:19 UTC, caupolicandiaz commented on content/r/concepts/conditionals/conditionals.md
> +  ```R
```suggestion
```r
```

2023-05-25 16:26 UTC, SSwiniarski requested changes
@jdagz28 I did a review and left you a comment.

2023-05-25 16:26 UTC, SSwiniarski commented on content/r/concepts/conditionals/conditionals.md
> +Description: 'Statements that return a boolean value that provide control flow in a program'
```suggestion
Description: 'Conditional statements return a boolean value that provides control flow in a program.'
```

2023-05-25 18:18 UTC, jdagz28 commented
@SSwiniarski edited the description already.

2023-05-26 12:38 UTC, SSwiniarski commented
@jdagz28 It's up to you. We can merge without that e-mail signing the CLA, but it may have effects on you getting credit for your entry. If you don't mind an anonymous entry, we can go ahead with this PR. 

Otherwise, you can make a new PR (using your GitHub e-mail) with the edited entry in its current form. On that PR request a review from me and @caupolicandiaz and leave a comment on the new entry tagging both of us, letting us know we already reviewed it. Then you can close this one.

2023-05-26 13:23 UTC, jdagz28 commented
@SSwiniarski  I am okay with an anonymous entry for this pull request.  Please go ahead with the merge. Thank you very much.

2023-05-26 13:38 UTC, SSwiniarski approved these changes
@jdagz28 Okay, looks like we can merge!

2023-05-26 13:40 UTC, merged

2023-05-26 13:49 UTC, SSwiniarski commented
@jdagz28 congrats on the new entry! The live link is here: https://www.codecademy.com/resources/docs/r/conditionals

![image](https://github.com/Codecademy/docs/assets/86081858/30d1ccb5-6b11-4271-8f02-1a809d90a0ab)

As I said, this is anonymous. If you want credit on future entries, makes sure that you use your GitHub email is used to commit the PR, and that your GitHub account is connected to your Codecademy profile.