Sql-math-function-floor
Codecademy/docs pull request #2250
Opened 2023-05-24 10:40 UTC by nikolaspoczekaj

### Description

Thanks for assigning me. This closes #2218 . I used the example i removed from the math-functions concept entry. 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-24 12:21 UTC, caupolicandiaz requested changes
@nikolaspoczekaj Just a few comments. Tag me when you've finished making the edits.

2023-05-24 12:21 UTC, caupolicandiaz commented on content/sql/concepts/math-functions/terms/floor/floor.md
> +The SQL math function `FLOOR()` returns the largest integer that is less than or equal to a specified numeric value. It effectively rounds down a number to the nearest whole integer.
```suggestion
The SQL math function **`FLOOR()`** returns the largest integer that is less than or equal to a specified numeric value. It effectively rounds down a number to the nearest whole integer.
```

2023-05-24 12:21 UTC, caupolicandiaz commented on content/sql/concepts/math-functions/terms/floor/floor.md
> +The `FLOOR()` function can be used to calculate the largest integer that is less than or equal to a given value:
```suggestion
The `FLOOR()` function can be used to return the largest integer that is less than or equal to a given value:
```

2023-05-24 12:21 UTC, caupolicandiaz commented on content/sql/concepts/math-functions/terms/floor/floor.md
> +In this SQL statement, the `salary` values are floored for each employee to calculate the `floored_salary`. The [`AS`](https://www.codecademy.com/resources/docs/sql/commands/as) keyword is used to re
```suggestion
In this SQL statement, the `salary` values are floored for each employee to get the `floored_salary`. The [`AS`](https://www.codecademy.com/resources/docs/sql/commands/as) keyword is used to name the resulting column `floored_salary` in the output.
```

2023-05-24 18:16 UTC, caupolicandiaz approved these changes
@nikolaspoczekaj Looks good

2023-05-25 16:06 UTC, SSwiniarski requested changes
@nikolaspoczekaj  I did a review and only had one comment.

2023-05-25 16:06 UTC, SSwiniarski commented on content/sql/concepts/math-functions/terms/floor/floor.md
> +```
Like to see a sentence explanation of the syntax describing what `number` is.

2023-05-25 18:50 UTC, nikolaspoczekaj commented
Done. @SSwiniarski

2023-05-26 11:36 UTC, SSwiniarski approved these changes
@nikolaspoczekaj Looks good to merge!

2023-05-26 11:37 UTC, merged

2023-05-26 12:22 UTC, SSwiniarski commented
@nikolaspoczekaj Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/sql/math-functions/floor

![image](https://github.com/Codecademy/docs/assets/86081858/19f9847d-441e-47e2-ba76-987fa489347e)