[Concept Entry] JavaScript Window
Codecademy/docs pull request #2282
Opened 2023-05-26 15:49 UTC by SSwiniarski

### Description

Concept entry for JavaScript `window` object.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-27 02:17 UTC, KTom101 requested changes
@SSwiniarski I added some minor changes

2023-05-27 02:17 UTC, KTom101 commented on content/javascript/concepts/window/window.md
> +The `window` object is the global object of JavaScript when run within a browser and represents the browser window. It is supported by all browsers. It contains as members all global JavaScript objec
```suggestion
The **`window`** object is the global object of JavaScript when run within a browser and represents the browser window. All browsers support it. It contains as members all global JavaScript objects, functions, and variables. Such variables become properties of the `window` object, such functions become methods of the `window` object.
```

2023-05-27 02:17 UTC, KTom101 commented on content/javascript/concepts/window/window.md
> +> **Note:** If a browser window contains [`<iframe>`](https://www.codecademy.com/resources/docs/html/elements/iframe) tags, there will be one `window` object for the page containing the `<iframe>` ta
```suggestion
> **Note:** If a browser window contains [`<iframe>`](https://www.codecademy.com/resources/docs/html/elements/iframe) tags, there will be one `window` object for the page containing the `<iframe>` tags, and an additional `window` object for the page in each `<iframe>`.
```

2023-05-27 12:39 UTC, SSwiniarski commented
@KTom101, I updated with your suggestions.

2023-05-27 17:28 UTC, KTom101 approved these changes
I'll pass this on to a second review.

2023-05-29 11:32 UTC, caupolicandiaz approved these changes
@SSwiniarski @KTom101 LGTM

2023-05-29 12:59 UTC, merged

2023-05-29 23:27 UTC, yangc95 commented
🙌 @SSwiniarski live link: https://www.codecademy.com/resources/docs/javascript/window

<img width="789" alt="Screenshot 2023-05-29 at 7 26 34 PM" src="https://github.com/Codecademy/docs/assets/72277593/2c569930-0dbe-435b-9b51-4e292a515c8b">

cc: @KTom101