Entry on the BEAM Search algorithm
Codecademy/docs pull request #2283
Opened 2023-05-27 00:25 UTC by HishamT

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-27 02:26 UTC, KTom101 requested changes
@HishamT I've added very minor comments.

2023-06-01 18:10 UTC, HishamT commented on content/ai/concepts/search-algorithms/terms/beam-search/beam-search.md
> +  - 'Search Algorithms'
Done!

2023-06-02 00:05 UTC, KTom101 approved these changes
@HishamT This can go on to the next review. But the exclamation points for the linked images on lines 36-59 weren't supposed to be removed since they were images. To link an image, the syntax would be:
 `![name](https://raw.githubusercontent.com/Codecademy/docs/main/media/)`

Regular links to webpages would be `[text](link)` which doesn't have the exclamation point. So the only exclamation points that needed to be removed were the ones that were linking out other entries which thank you for doing 😄 Hope my exclamation makes sense!

2023-06-03 14:29 UTC, SSwiniarski requested changes
@HishamT I did a second review. My comments are just fixing the image markdown and adding a period.

2023-06-03 14:29 UTC, SSwiniarski commented on content/ai/concepts/search-algorithms/terms/beam-search/beam-search.md
> +[Example-graph](https://raw.githubusercontent.com/Codecademy/docs/main/media/BEAM-Search-example-graph.png)
```suggestion
![Example-graph](https://raw.githubusercontent.com/Codecademy/docs/main/media/BEAM-Search-example-graph.png)
```

2023-06-03 14:29 UTC, SSwiniarski commented on content/ai/concepts/search-algorithms/terms/beam-search/beam-search.md
> +[BEAM-Search-1](https://raw.githubusercontent.com/Codecademy/docs/main/media/BEAM-Search-Tree-1.png)
```suggestion
![BEAM-Search-1](https://raw.githubusercontent.com/Codecademy/docs/main/media/BEAM-Search-Tree-1.png)
```

2023-06-03 14:29 UTC, SSwiniarski commented on content/ai/concepts/search-algorithms/terms/beam-search/beam-search.md
> +[BEAM-Search-2](https://raw.githubusercontent.com/Codecademy/docs/main/media/BEAM-Search-Tree-2.png)
```suggestion
![BEAM-Search-2](https://raw.githubusercontent.com/Codecademy/docs/main/media/BEAM-Search-Tree-2.png)
```

2023-06-03 14:29 UTC, SSwiniarski commented on content/ai/concepts/search-algorithms/terms/beam-search/beam-search.md
> +[BEAM-Search-3](https://raw.githubusercontent.com/Codecademy/docs/main/media/BEAM-Search-Tree-3.png)
```suggestion
![BEAM-Search-3](https://raw.githubusercontent.com/Codecademy/docs/main/media/BEAM-Search-Tree-3.png)
```

2023-06-03 14:29 UTC, SSwiniarski commented on content/ai/concepts/search-algorithms/terms/beam-search/beam-search.md
> +[BEAM-Search-4](https://raw.githubusercontent.com/Codecademy/docs/main/media/BEAM-Search-Tree-4.png)
```suggestion
![BEAM-Search-4](https://raw.githubusercontent.com/Codecademy/docs/main/media/BEAM-Search-Tree-4.png)
```

2023-06-03 14:29 UTC, SSwiniarski commented on content/ai/concepts/search-algorithms/terms/beam-search/beam-search.md
> +[BEAM-Search-5](https://raw.githubusercontent.com/Codecademy/docs/main/media/BEAM-Search-Tree-5.png)
```suggestion
![BEAM-Search-5](https://raw.githubusercontent.com/Codecademy/docs/main/media/BEAM-Search-Tree-5.png)
```

2023-06-03 14:29 UTC, SSwiniarski commented on content/ai/concepts/search-algorithms/terms/beam-search/beam-search.md
> +[BEAM-Search-6](https://raw.githubusercontent.com/Codecademy/docs/main/media/BEAM-Search-Tree-6.png)
```suggestion
![BEAM-Search-6](https://raw.githubusercontent.com/Codecademy/docs/main/media/BEAM-Search-Tree-6.png)
```

2023-06-03 14:29 UTC, SSwiniarski commented on content/ai/concepts/search-algorithms/terms/beam-search/beam-search.md
> +[Final-path](https://raw.githubusercontent.com/Codecademy/docs/main/media/BEAM-Search-final-path.png)
```suggestion
![Final-path](https://raw.githubusercontent.com/Codecademy/docs/main/media/BEAM-Search-final-path.png)
```

2023-06-03 14:29 UTC, SSwiniarski commented on content/ai/concepts/search-algorithms/terms/beam-search/beam-search.md
> +Description: 'A graph searching algorithm that is a variant of breadth-first search'
```suggestion
Description: 'A graph searching algorithm that is a variant of breadth-first search.'
```

2023-06-05 15:36 UTC, SSwiniarski approved these changes
@HishamT Looks good to me. Shall we merge?

2023-06-05 16:35 UTC, HishamT commented
Sounds good! :)

2023-06-05 16:36 UTC, merged