Move comments to a new line for PowerShell concepts
Codecademy/docs pull request #2284
Opened 2023-05-27 00:36 UTC by Prince25

### Description
Since I was credited as "Anonymous" for contributing to PowerShell docs, @yangc95 [asked me](https://github.com/Codecademy/docs/pull/2185#issuecomment-1556279892) to move comments to a new line and push the changes to the main branch.

### Type of Change
- Updating the documentation

### Checklist
- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch -> got permission
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-27 13:05 UTC, SSwiniarski requested changes
@Prince25 I did a first review and left some comments. They're all about moving the comments from the command line examples. You can move the comments in the scripting samples, but in the command line it breaks the example. The good news is that all the files where this happens, there seems to be a scripting example, so fixing this wont break what you're trying to do.

2023-05-27 13:05 UTC, SSwiniarski commented on content/powershell/concepts/operators/operators.md
> -PS > $number += 6 # $number is now 10
Again, we can't really move the comments in the command line examples.

2023-05-27 13:05 UTC, SSwiniarski commented on content/powershell/concepts/operators/operators.md
> -PS > $num_1 -lt $num_2  # num_1 is not less than num_2
Again I'd undo the command line examples

2023-05-27 13:05 UTC, SSwiniarski commented on content/powershell/concepts/operators/operators.md
> -PS > $num_2++           # num_2 is now 4
See prior comments.

2023-05-27 13:05 UTC, SSwiniarski commented on content/powershell/concepts/operators/operators.md
> -PS > $num_1 /= 2        # num_1 is now 2
See prior comments.

2023-05-27 13:05 UTC, SSwiniarski commented on content/powershell/concepts/variables/variables.md
> -PS > [Int]$age = "twenty five" # Results in an error
Let's not move the comment for the command line examples.

2023-05-28 00:31 UTC, Prince25 commented
Thank you. I believe I reverted all of the command line examples but feel free to take another look.

2023-05-28 12:12 UTC, SSwiniarski approved these changes
@Prince25 Looks good!

2023-06-08 18:52 UTC, yangc95 approved these changes

2023-06-08 18:56 UTC, merged

2023-06-08 22:47 UTC, yangc95 commented
@Prince25 edits will appear here: powershell: [Arrays](https://www.codecademy.com/resources/docs/powershell/arrays), [Conditionals](https://www.codecademy.com/resources/docs/powershell/conditionals), [Objects](https://www.codecademy.com/resources/docs/powershell/objects), [Variables](https://www.codecademy.com/resources/docs/powershell/variables)

cc: @SSwiniarski