[Term Entry] Php Math Function: log10()
Codecademy/docs pull request #2287
Opened 2023-05-28 08:28 UTC by wejdan01

### Description

-Added the log10 Term for Php
-Closes issue #2271 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-28 08:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2287) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2287) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2287) it.</sub>

2023-05-28 13:22 UTC, SSwiniarski requested changes
@wejdan01 I did a first review and left a few comments.

2023-05-28 13:22 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/log10/log10.md
> +The **`log10()`** function returns the base-10 logarithm of a number.
```suggestion

The **`log10()`** function returns the base-10 logarithm of a number.
```
Add line break.

2023-05-28 13:22 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/log10/log10.md
> +## Parameters:
```suggestion

```

2023-05-28 13:22 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/log10/log10.md
> +The function accepts a single parameter $arg which refers to the number of whose the logarithm is to be calculated.
```suggestion
The function accepts a single parameter `$arg` which refers to the number of whose the logarithm is to be calculated.
```

2023-05-28 13:22 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/log10/log10.md
> +Using `log10()` to return the abase-10 logarithm of `100`:
```suggestion
Using `log10()` to return the base-10 logarithm of `100`:
```

2023-05-28 13:22 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/log10/log10.md
> +   echo "log10(" . $arg. ")=" . log10($arg) . "
```suggestion
   echo "log10(" . $arg . ")=" . log10($arg) . "
```

2023-05-29 08:24 UTC, wejdan01 commented
@SSwiniarski done

2023-05-29 12:57 UTC, SSwiniarski requested changes
@wejdan01 One more edit I wanted you to make.

2023-05-29 12:57 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/log10/log10.md
> +## Parameters
I wanted you to remove this Parameters header so the following sentence is part of the Syntax section.

2023-06-14 05:09 UTC, KTom101 requested changes
@wejdan01 I added a couple of changes to this.

2023-06-14 05:09 UTC, KTom101 commented on content/php/concepts/math-functions/terms/log10/log10.md
> +Using `log10()` to return the base-10 logarithm of `100`:
```suggestion
The following codebyte example uses the `log10()` function to return the base-10 logarithm of `100`, then it outputs the result using `[echo](https://www.codecademy.com/resources/docs/php/string-functions/echo)`:
```

2023-06-26 22:58 UTC, KTom101 approved these changes
@wejdan01 Since a good amount of time has passed, I've gone ahead and added the changes myself in commit [ef80478](https://github.com/Codecademy/docs/pull/2287/commits/ef80478b36c8b9035d6ca567cdf207ab21841a79) & [24e72fd](https://github.com/Codecademy/docs/pull/2287/commits/24e72fd8e25800fd0c45086df77ebda33a3a15b3).

2023-06-26 23:03 UTC, merged

2023-06-26 23:13 UTC, KTom101 commented
@wejdan01 Entry is here: https://www.codecademy.com/resources/docs/php/math-functions/log10

You're currently listed as anonymous:

<img width="775" alt="Screenshot 2023-06-26 at 7 12 07 PM" src="https://github.com/Codecademy/docs/assets/40783324/72b750dd-173e-4928-8b96-df2e24a1da93">

If you want to remain anonymous, there is nothing more you need to do. If you wish to be listed as a contributor, please follow the instructions linked [here](https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036).