Add files via upload
Codecademy/docs pull request #2289
Opened 2023-05-28 12:52 UTC by sulabh007

acos

### Description

-Adding a new entry:  acos() for PHP 
-Close Issues: #2204

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-28 12:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2289) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2289) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2289) it.</sub>

2023-05-28 13:40 UTC, SSwiniarski requested changes
@sulabh007 I did a first review and left a couple of comments. Just a reminder that you shouldn't be making PRs off your `main` branch. You should create a new branch off of each PR. As it is now, you can't submit another PR until this one is merged.

2023-05-28 13:40 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/acos/acos.md
> +Title: 'floor()'
```suggestion
Title: 'acos()'
```

2023-05-28 13:40 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/acos/acos.md
> +Description: 'Returns a rounded number down to the nearest integer.'
```suggestion
Description: 'Returns the angle whose cosine value is equal to the specified value.'

```

2023-05-28 13:40 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/acos/acos.md
> +
```suggestion
```
Remove extra line break.

2023-05-28 13:40 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/acos/acos.md
> +Where `number` is the number that should be Specifies in range -1 to 1.
```suggestion
Where `number` is the number that the function returns the arc cosine for. Should be specified in range -1 to 1.

```

2023-05-28 13:40 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/acos/acos.md
> +acos(0.64)
The example must be full PHP code. It needs the `<?php ... ?>` tags and something line an `echo()` function to do something with the result of the function.

2023-05-28 13:40 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/acos/acos.md
> +The result will be a float value of `0.87629806116834` as the function angle in `rad`.
```suggestion
The result will be a float value of `0.87629806116834`.
```

2023-05-28 13:40 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/acos/acos.md
> +// Output: 0.87629806116834
```suggestion
```
Remove the comment, as this is handled in the description.

2023-05-28 13:40 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/acos/acos.md
> +acos(-1) returns the value of Pi.
```suggestion
`acos(-1)` returns the value of Pi.

```

2023-05-31 15:21 UTC, sulabh007 commented
i have committed those changes

2023-06-03 14:17 UTC, SSwiniarski requested changes
@sulabh007 you missed one comment.

2023-06-03 14:17 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/acos/acos.md
> +acos(0.64)
You still need to add the `<?php ... ?>` tags to this example.

2023-06-09 14:36 UTC, sulabh007 commented
i have updated the example code

2023-06-09 16:14 UTC, SSwiniarski requested changes
@sulabh007 One more thing.

2023-06-09 16:14 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/acos/acos.md
> +acos(0.64)
```suggestion
  echo(acos(0.64));
```
So we do something with the result of the function.

2023-06-09 17:03 UTC, sulabh007 commented
changed it

2023-06-11 08:40 UTC, sulabh007 commented
> @sulabh007 Looks good for a second review.

how does that work

2023-06-11 12:30 UTC, SSwiniarski commented
> > @sulabh007 Looks good for a second review.
> 
> how does that work

One of the other maintainers will se the "ready for next review" tag and come and do a second review. We require two maintainer reviews before an entry is merged. Be patient, as there are a lot of PRs for them to go through.

2023-06-15 20:15 UTC, KTom101 approved these changes
@sulabh007 Since my changes were minor, I went ahead and applied them for you in commit [6b7c87a](https://github.com/Codecademy/docs/pull/2289/commits/6b7c87afb1e209b6d441a14e71eabbf2933695e2). 

Note for future entries, it is extremely discouraged to write off your `main` branch. Always make a separate branch when working on a feature. Thanks.

2023-06-15 20:16 UTC, merged

2023-06-16 01:47 UTC, KTom101 commented
@sulabh007 The entry is live here: https://www.codecademy.com/resources/docs/php/math-functions/acos and you're listed as a contributor: 

<img width="804" alt="Screenshot 2023-06-15 at 9 45 46 PM" src="https://github.com/Codecademy/docs/assets/40783324/1c09b45d-6175-4ec4-b31e-be011b446571">

Let me know if you notice something amiss.

cc @yangc95