php-function-cosh
Codecademy/docs pull request #2291
Opened 2023-05-29 14:29 UTC by nikolaspoczekaj

### Description

Thanks for assigning me. This closes #2207 .

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-29 16:41 UTC, SSwiniarski requested changes
@nikolaspoczekaj I did a first review and only had one comment.

2023-05-29 16:41 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/cosh/cosh.md
> +In this executable example of the function, the `$x` variable can be changed to print the `cosh()` of it
```suggestion
In this executable example of the function, the `$x` variable can be changed to print the `cosh()` of it:
```

2023-05-29 16:46 UTC, nikolaspoczekaj commented
@SSwiniarski Done, thanks :)

2023-05-29 16:52 UTC, SSwiniarski approved these changes
@nikolaspoczekaj Looks good for a second review.

2023-06-15 17:38 UTC, caupolicandiaz requested changes
@nikolaspoczekaj I've added a couple of comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-06-15 17:38 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/cosh/cosh.md
> +`number` - represents the input value for which the hyperbolic cosine will be returned.
```suggestion
`number`: Represents the input value for which the hyperbolic cosine will be returned.
```

2023-06-15 17:38 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/cosh/cosh.md
> +## Codebyte Example
We don't duplicate examples in docs. I would recommend deleting the codebyte unless there is some additional functionality that is worthwhile illustrating with a different example.

2023-06-21 06:43 UTC, nikolaspoczekaj commented
Thanks @caupolicandiaz . Finished making the changes.

2023-06-21 16:29 UTC, caupolicandiaz approved these changes
@nikolaspoczekaj @SSwiniarski  Looks good

2023-06-21 16:55 UTC, merged

2023-06-21 17:30 UTC, SSwiniarski commented
@nikolaspoczekaj Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/php/math-functions/cosh

![image](https://github.com/Codecademy/docs/assets/86081858/a1062f03-b8db-46fd-a546-4cd30be392c7)