added codebyte to unshift and valueOf method for arrays in javascript
Codecademy/docs pull request #2292
Opened 2023-05-29 15:14 UTC by yashladekar

### Description

#2278
This PR adds code bytes for unshift and valueOf  methods

This code examples demonstrate the use of the unshift and valueOf methods in JavaScript . The unshift example shows how to add elements to the beginning of an array, while the valueOf example shows how to 
return the array itself.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-29 16:48 UTC, SSwiniarski requested changes
@yashladekar I did a small edit and had one comment for you.

2023-05-29 16:48 UTC, SSwiniarski commented on content/javascript/concepts/arrays/terms/unshift/unshift.md
> +The code below adds `Lemon` and `Pineapple` to the beginning of the array `fruits` with the help of the unshift() method.
```suggestion
The code below adds `Lemon` and `Pineapple` to the beginning of the array `fruits` with the help of the `unshift()` method.
```

2023-05-29 19:19 UTC, SSwiniarski approved these changes
@yashladekar Looks good for second review.

2023-06-06 17:54 UTC, caupolicandiaz requested changes
@yashladekar I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-06-06 17:54 UTC, caupolicandiaz commented on content/javascript/concepts/arrays/terms/unshift/unshift.md
> +The code below adds `Lemon` and `Pineapple` to the beginning of the array `fruits` with the help of the `unshift()` method.
```suggestion
The code below adds `Lemon` and `Pineapple` to the beginning of the array `fruits` with the help of the `.unshift()` method.
```

2023-06-06 17:54 UTC, caupolicandiaz commented on content/javascript/concepts/arrays/terms/unshift/unshift.md
> +
remove the empty line at the top of the code block

2023-06-06 17:54 UTC, caupolicandiaz commented on content/javascript/concepts/arrays/terms/unshift/unshift.md
> +### Codebyte Example
```suggestion
## Codebyte Example
```

2023-06-11 10:54 UTC, yashladekar reviewed
The changes are done. Do let me know if there are any other changes I need to make.

2023-06-12 14:33 UTC, merged