Modified abs, acos, asin math functions
Codecademy/docs pull request #2294
Opened 2023-05-29 15:26 UTC by l2eza

modified:   content/cpp/concepts/math-functions/terms/abs/abs.md	
        modified:   content/cpp/concepts/math-functions/terms/acos/acos.md
	modified:   content/cpp/concepts/math-functions/terms/asin/asin.md

### Description

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-29 16:51 UTC, SSwiniarski approved these changes
@l2eza This looks good, passing it on to a second review.

2023-05-30 14:17 UTC, caupolicandiaz requested changes
@l2eza I've added a few comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-05-30 14:17 UTC, caupolicandiaz commented on content/cpp/concepts/math-functions/terms/asin/asin.md
> +In this example, the `std::asin()` function is applied to the variable `x`, which holds the value `0.5`. The `std::asin()` function returns the inverse sine (also known as arcsine) of the provided ar
```suggestion
In this example, the `std::asin()` function is applied to the variable `x`, which holds the value `0.5`. The `std::asin()` function returns the inverse sine (also known as arcsine) of the provided argument.
```

2023-06-18 14:37 UTC, SSwiniarski commented
@l2eza are you going to address @caupolicandiaz's comments, it's been three weeks. If we don't see any movement in the next couple of days we'll close this PR due to inactivity.

2023-06-23 19:53 UTC, SSwiniarski commented
Closing this PR due to inactivity.

2023-06-23 19:53 UTC, closed without merging