add .toString() and .valueOf() codebyte examples
Codecademy/docs pull request #2295
Opened 2023-05-29 18:59 UTC by andrzejkukuryk

### Description

Added codebyte examples to date .toString() and .valueOf() methods.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-29 18:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2295) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2295) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2295) it.</sub>

2023-05-29 19:28 UTC, SSwiniarski requested changes
@andrzejkukuryk This looks good except for one thing: Can we change the variable names in the examples so they don't refer to `currentDate`? We want to do this because the date used won't be current for anyone who reads this entry.

2023-05-29 19:55 UTC, andrzejkukuryk commented
> @andrzejkukuryk This looks good except for one thing: Can we change the variable names in the examples so they don't refer to `currentDate`? We want to do this because the date used won't be current for anyone who reads this entry.

It's done! Current name is "exampleDate".

2023-05-29 20:21 UTC, SSwiniarski requested changes
@andrzejkukuryk Looks good for a second review.

2023-05-30 11:45 UTC, caupolicandiaz requested changes
@andrzejkukuryk I've added a couple of comments. Please update the entry, and tag me when you've finished. Thanks

2023-05-30 11:45 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/toString/toString.md
> +The following example shows the work of `.toString()` method.
```suggestion
The following is runnable, and demonstrates the use of the `.toString()` method.
```

2023-05-30 11:45 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/valueOf/valueOf.md
> +## Codebyte Example
It appears that this entry already has a codebyte and was incorrectly added to this pr. Please revert these changes.

2023-05-30 19:33 UTC, andrzejkukuryk commented
@caupolicandiaz @SSwiniarski I guess it's ready to review.

2023-05-31 14:51 UTC, caupolicandiaz approved these changes
@andrzejkukuryk Looks good

2023-05-31 16:01 UTC, SSwiniarski approved these changes

2023-05-31 16:08 UTC, merged