Add metadata, description, examples
Codecademy/docs pull request #2305
Opened 2023-05-31 13:17 UTC by teona-pavliukova

### Description

A new term entry was created for [Python:NumPy](https://www.codecademy.com/resources/docs/numpy) **.amin()** function in a new file in `docs/content/numpy/concepts/built-in-functions/terms/min/amin.md`.  This entry closses issue #2094.

The entry have all the below requirements listed on the issue's page:
- Mention the equivalent ndarray.min() method.
- Have a syntax section illustrating the function with a ```pseudo code block.
- An example showing the function in use with a ```py code block.
- A runnable codebyte example in a  ```codebyte/python block.

An entry was created as part of a portfolio project for *Learn Git and GitHub* course.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-31 14:00 UTC, caupolicandiaz commented on content/numpy/concepts/built-in-functions/terms/min/amin.md
> +* If axis is a tuple, the result would be an array of dimension a.ndim - len(axis)
```suggestion
* If axis is an integer, the result would be an array of dimension `a.ndim - 1`.
* If axis is a tuple, the result would be an array of dimension `a.ndim - len(axis)`.
```

2023-05-31 23:14 UTC, teona-pavliukova commented on content/numpy/concepts/built-in-functions/terms/min/amin.md
> +
I couldn't fix this issue from a comment, so I deleted extra line in a separate commit ae99460.

2023-05-31 23:16 UTC, teona-pavliukova commented
@caupolicandiaz Thank you for your review, all issues were fixed.

2023-06-01 11:03 UTC, caupolicandiaz approved these changes
@teona-pavliukova Looks good. I just made a couple of small edits to remove extra lines in the last code block.

2023-06-01 11:50 UTC, SSwiniarski requested changes
@teona-pavliukova I did a review and had one comment.

2023-06-01 11:50 UTC, SSwiniarski commented on content/numpy/concepts/built-in-functions/terms/min/amin.md
> +The **`.amin()`** function returns the minimum of an array or minimum along an axis. The `a.min()` function is equivalent to `ndarray.min()`.
```suggestion
The **`.amin()`** function returns the minimum of an array or minimum along an axis. The `.amin()` function is equivalent to `ndarray.min()`.
```

2023-06-01 15:35 UTC, SSwiniarski approved these changes
@teona-pavliukova Looks good.

2023-06-01 16:23 UTC, merged

2023-06-01 16:26 UTC, SSwiniarski commented
@teona-pavliukova Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/numpy/built-in-functions/amin

![image](https://github.com/Codecademy/docs/assets/86081858/6cee547a-e4ed-4967-b228-222240ded990)