add-js-codebytes
Codecademy/docs pull request #2307
Opened 2023-05-31 15:14 UTC by nikolaspoczekaj

### Description

Thanks for assigning. This closes #2279 . 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-05-31 16:15 UTC, SSwiniarski approved these changes
@nikolaspoczekaj Looks good! Sending to second review.

2023-06-01 12:15 UTC, caupolicandiaz requested changes
@nikolaspoczekaj I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-06-01 12:15 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/now/now.md
> +```codebyte/javascript
In the new example please remove the extra empty lines at the top and bottom of the code block

2023-06-01 12:15 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/toLocaleDateString/toLocaleDateString.md
> +
As noted above, please remove the additional empty lines at the top and bottom of the code block

2023-06-02 13:08 UTC, caupolicandiaz approved these changes
@nikolaspoczekaj Looks good. I just made a couple of minor edits to the now.md entry.

2023-06-02 13:12 UTC, merged

2023-06-02 13:13 UTC, SSwiniarski commented
@nikolaspoczekaj Congrats on the new edits!

Live links here:
- https://www.codecademy.com/resources/docs/javascript/dates/now
- https://www.codecademy.com/resources/docs/javascript/dates/toLocaleDateString