move-iter-function
Codecademy/docs pull request #2312
Opened 2023-06-01 08:23 UTC by nikolaspoczekaj

### Description

This should close #2198 . I removed my entry from built-in-functions and merged it into the existing iterators/iter entry.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-01 16:38 UTC, SSwiniarski requested changes
@nikolaspoczekaj so far, so good. My one comment is to replace the sentinel example completely as it contains references to another site.

2023-06-01 16:38 UTC, SSwiniarski commented on content/python/concepts/iterators/terms/iter/iter.md
>  class codeNinjaCount:
The example as it was worked, but I think we'd like to replace it with a completely new example, as codeNinja refers to another site.

2023-06-02 07:45 UTC, nikolaspoczekaj commented
@SSwiniarski Done. I changed the example.

2023-06-02 11:43 UTC, SSwiniarski approved these changes
@nikolaspoczekaj looks good for review two.

2023-06-05 23:45 UTC, yangc95 approved these changes

2023-06-05 23:48 UTC, merged

2023-06-05 23:51 UTC, yangc95 commented
Thanks @nikolaspoczekaj! The edits should appear here: https://www.codecademy.com/resources/docs/python/iterators/iter

cc: @SSwiniarski @KTom101