Entered doc for AI Linear Function
Codecademy/docs pull request #2327
Opened 2023-06-03 03:30 UTC by Himasnhu-AT

### Description
closes #2055 

Included a file in `docs/content/ai/concepts/neural-networks/terms/linear-activation-function.md`. the reason for it being that I think the linear function is a simple but very powerful tool that you can use in _AI/ML_ to improve your model. As an aspiring AI Researcher, I thought, why not write it and improve my knowledge while contributing to this amazing community?

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-03 03:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2327) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2327) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2327) it.</sub>

2023-06-03 11:02 UTC, caupolicandiaz requested changes
@Himasnhu-AT I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-06-03 11:02 UTC, caupolicandiaz commented on content/ai/concepts/neural-networks/terms/linear-activation-function.md
> +> Note that this code assumes the presence of the NumPy library for array operations. Make sure you have NumPy installed or adjust the code accordingly if you're using a different numerical computing
```suggestion
> **Note:** This code assumes the availability of the NumPy library for array operations. Make sure you have NumPy installed or adjust the code accordingly if you're using a different numerical computing library.
```

2023-06-03 17:29 UTC, Himasnhu-AT commented
@caupolicandiaz Thank you for your review. I have resolved the issues. Regarding images, may I get direction on how should I update them and sent via this pull request

2023-06-11 07:54 UTC, caupolicandiaz requested changes
@Himasnhu-AT Apologies for the delay, but I wanted to take some time to reconsider the content of this entry. Overall, I believe this is a well rounded introduction to linear functions from a mathematical perspective. But, this entry is really just about linear functions within the context of activation functions for neural nets. So, the content should be focused on presenting a basic definition as well as how and why these functions are used in this role for neural nets. I'd like you to try and rewrite the body of the entry to fulfill the outline I've provided. 

Please let me know if you have any other questions about what's needed.

2023-06-26 06:11 UTC, Himasnhu-AT commented
@caupolicandiaz i have completed the changes. Let me know if I have to make any changes in it.

2023-07-04 19:37 UTC, caupolicandiaz commented
@Himasnhu-AT Unfortunately, I think this submission is still too general and unfocused for this assignment. I'm going to close this PR, but I hope you select another issue to work on. We look forward to helping you make a docs contribution.

2023-07-04 19:37 UTC, closed without merging