Fixes issue 2224
Codecademy/docs pull request #2329
Opened 2023-06-03 21:08 UTC by luis-morel

### Description

Adding Codebyte examples for the JavaScript array length property and map() method as requested on issue #2224. This PR closes issue #2224.

Files modified:

- content/javascript/concepts/arrays/terms/length/length.md
- content/javascript/concepts/arrays/terms/map/map.md

I am in the process of completing the Codecademy Front End Engineer path and process of contributing to the Codecademy docs was introduced as part of the "Learn Git and GitHub" course (see project task here: https://www.codecademy.com/courses/learn-git/kanban_projects/contributing-to-the-codecademy-docs-repository). I have already made one contribution and, in the spirit of learning and community, decided to do another.

### Type of Change

- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-04 13:08 UTC, SSwiniarski requested changes
@luis-morel I did a first review. The primary issue with this PR is that it pulled in additional changes from a prior branch. This is because you created a branch from an earlier branch rather than main. This can be fixed simply by undoing the extra changes in this branch. (It won't affect the earlier branch.)

2023-06-04 13:08 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/getMinutes/getMinutes.md
It looks like you branched off the branch for another PR, rather than from main. This pulled in extra changes. Please remove this change from this branch.

2023-06-04 13:08 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/getMonth/getMonth.md
It looks like you branched off the branch for another PR, rather than from main. This pulled in extra changes. Please remove this change from this branch.

2023-06-04 13:08 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/getSeconds/getSeconds.md
It looks like you branched off the branch for another PR, rather than from main. This pulled in extra changes. Please remove this change from this branch.

2023-06-04 13:08 UTC, SSwiniarski commented on content/javascript/concepts/arrays/terms/length/length.md
> +The example below defines a new array `groceries` and then lists, logs the 4 array items to the console. Next, to delete the last item in the array, its `length` property is set to 3. Finally, to con
```suggestion
The example below defines a new array `groceries` and then logs the four array items to the console. Next, to delete the last item in the array, its `length` property is set to 3. Finally, to confirm the last item has been removed, the updated array and the value of item 4 (`undefined`) are logged to the console.
```

2023-06-05 10:49 UTC, luis-morel commented on content/javascript/concepts/dates/terms/getMinutes/getMinutes.md
@SSwiniarski, I could have sworn I switched to main before creating the branch for this issue. Either way, I removed the updates to the files from the other issue, tried to add\commit the changes, and git rejected my commit due to the error noted below. 

Would deleting and recreating this branch, and then committing the changes from scratch resolve this issue? 

- issue-2224-fix -> issue-2224-fix (fetch first)
- error: failed to push some refs to 'github.com:luis-morel/cc-docs.git'. 
- hint: Updates were rejected because the remote contains work that you do not have locally. This is usually caused by another repository pushing to the same ref. You may want to first integrate the remote changes (e.g., 'git pull ...') before pushing again. See the 'Note about fast-forwards' in 'git push --help' for details.

2023-06-05 15:43 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/getMinutes/getMinutes.md
@luis-morel You can try a `git pull` like it suggests, or you can create a new branch and submit a new PR. Whatever's easier for you. If you do submit a new PR, make sure to incorporate the change and tag me letting me know I reviewed the content already.

2023-06-06 11:32 UTC, SSwiniarski commented
Closed because PR was resubmitted.

2023-06-06 11:32 UTC, closed without merging