Documentation about log() function for php
Codecademy/docs pull request #2332
Opened 2023-06-04 10:44 UTC by tanbirali

### Description

I have added new Term entry for PHP about the log() function. 

### Type of Change

- Adding a new entry for php about log() function
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-04 10:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2332) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2332) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2332) it.</sub>

2023-06-04 13:31 UTC, SSwiniarski requested changes
@tanbirali I did a first review and left a few comments.

2023-06-04 13:31 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/log/log.md
> +Description: 'Return the natural logarithm of different numbers.'
```suggestion
Description: 'Returns the natural logarithm of different numbers.'
```

2023-06-04 13:31 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/log/log.md
> +Where `number` is the number whose logartihm is to be calculated and `base` is optional parameter which signifies the logarithmic base to be used. By default `base` is 'e'.
```suggestion
Where `number` is the number whose logarithm is to be calculated and `base` is optional parameter which signifies the logarithmic base to be used. By default `base` is *e*.
```

2023-06-04 13:31 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/log/log.md
> +floor(1)
```suggestion
<?php
  echo(log(1));
?>
```

2023-06-04 13:31 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/log/log.md
> +  echo(floor(7));
```suggestion
  echo(log(7));
```

2023-06-04 13:39 UTC, tanbirali commented
@SSwiniarski thank you for reviewing my PR. I have committed the suggested changes do let me know if I need to do any other changes.

2023-06-04 14:17 UTC, SSwiniarski approved these changes
@tanbirali Looks good for a second review.

2023-06-16 08:51 UTC, caupolicandiaz requested changes
@tanbirali I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-06-16 08:51 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/log/log.md
> +Description: 'Returns the natural logarithm of different numbers.'
```suggestion
Description: 'Returns the natural logarithm of a value.'
```

2023-06-16 08:51 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/log/log.md
> +The **`log()`** function returns the natural logarithm of different numbers.
```suggestion
The **`log()`** function returns the natural logarithm of a value.
```

2023-06-16 08:51 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/log/log.md
> +The result returns a value type of `float`.
```suggestion
The value returned by the function is a `float` type.
```

2023-06-16 08:51 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/log/log.md
> +Where `number` is the number whose logarithm is to be calculated and `base` is optional parameter which signifies the logarithmic base to be used. By default `base` is *e*.
```suggestion
Where `number` is the number whose logarithm is to be calculated and `base` is an optional parameter which signifies the logarithmic base to be used. By default `base` is *e*.
```

2023-06-16 08:51 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/log/log.md
> +// Output: 0
```suggestion
```

2023-06-16 08:51 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/log/log.md
> +The result will be a float value of `0` as the logarithmic value of `1` is `0`.
```suggestion
This will result in the following output:
```

2023-06-16 08:51 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/log/log.md
> +
```shell
0
```

2023-06-17 06:46 UTC, caupolicandiaz approved these changes
@tanbirali @SSwiniarski This is all set to go. I just made a couple of small formatting edits such as adding a shell block for the output, etc.

2023-06-17 12:24 UTC, merged

2023-06-17 12:40 UTC, SSwiniarski commented
Congrats @tanbirali on the new entry! Live link here: https://www.codecademy.com/resources/docs/php/math-functions/log

![image](https://github.com/Codecademy/docs/assets/86081858/f81fa679-514b-4f49-82e0-64a3737fcbba)