Closes Issue #2224 2.0
Codecademy/docs pull request #2346
Opened 2023-06-06 10:56 UTC by luis-morel

### Description

Adding Codebytes for the JavaScript array length property and map() method as requested on issue #2224. This PR closes issue #2224.

Files modified:

- content/javascript/concepts/arrays/terms/length/length.md
- content/javascript/concepts/arrays/terms/map/map.md

I am working on the Codecademy Front End Engineer path and the process of contributing to the Codecademy docs was introduced as part of the "Learn Git and GitHub" course (see project task here: https://www.codecademy.com/courses/learn-git/kanban_projects/contributing-to-the-codecademy-docs-repository). I have already made one contribution and, in the spirit of learning and community, decided to do another.

### Type of Change

- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-06 11:00 UTC, luis-morel commented
Hi, @SSwiniarski. I created a new branch and PR to close issue #2224. You have reviewed the content already. Thanks!

2023-06-06 11:30 UTC, SSwiniarski approved these changes
@luis-morel Looks good for review two.

2023-06-06 18:22 UTC, caupolicandiaz commented on content/javascript/concepts/arrays/terms/length/length.md
> +console.log(`\nTotal grocery items: ${groceries.length}`); // 5
```suggestion
console.log(`\nTotal grocery items: ${groceries.length}`); 
```

2023-06-06 18:36 UTC, caupolicandiaz requested changes
@luis-morel I've added a few comments. Please update the entry, and tag me when you're done. Thanks

2023-06-06 18:36 UTC, caupolicandiaz commented on content/javascript/concepts/arrays/terms/length/length.md
> +console.log(`\nTotal grocery items: ${groceries.length}`); // 5
you can remove the commented output because it will show the appropriate values when the user runs the code

2023-06-06 18:36 UTC, caupolicandiaz commented on content/javascript/concepts/arrays/terms/length/length.md
> +console.log(`\nItem 4: ${groceries[3]}`); // undefined; last item deleted
```suggestion
console.log(`\nTotal grocery items: ${groceries.length}`); 
console.log(`\nItem 4: ${groceries[3]}`); 
```

2023-06-06 18:36 UTC, caupolicandiaz commented on content/javascript/concepts/arrays/terms/map/map.md
> +The example below defines a new array `teachers`. Next, the results of the `map()` method are stored in a new variable, array `courses`. Finally, the items of the `courses` array are logged to the co
```suggestion
The example below defines a new array `teachers`. Next, the results of the `.map()` method are stored in a new variable, array `courses`. Finally, the items of the `courses` array are logged to the console.
```

2023-06-08 00:56 UTC, luis-morel commented
> @luis-morel I've added a few comments. Please update the entry, and tag me when you're done. Thanks

@caupolicandiaz, I have pushed your recommendations. Thank you!

2023-06-08 12:11 UTC, merged

2023-06-08 12:21 UTC, SSwiniarski commented
@luis-morel congrats on the new edits.

Live links here:
- https://www.codecademy.com/resources/docs/javascript/arrays/length
- https://www.codecademy.com/resources/docs/javascript/arrays/map