[Concept Entry] Go Math Functions.
Codecademy/docs pull request #2408
Opened 2023-06-07 19:18 UTC by SSwiniarski

### Description

In the interest of filling out our Go entries, I created a Math Functions concept so we can start producing issues for Go math functions. I included one term so that the list wouldn't be empty when this is merged.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-08 02:54 UTC, KTom101 requested changes
@SSwiniarski Only a couple of changes from me.

2023-06-08 02:54 UTC, KTom101 commented on content/go/concepts/math-functions/terms/abs/abs.md
> +The following caluates the absolute value of `-255` and prints out the result:
```suggestion
The following calculates the absolute value of `-255` and prints out the result:
```

2023-06-08 02:54 UTC, KTom101 commented on content/go/concepts/math-functions/math-functions.md
> +Go supports many different math functions through the `math` package. You must import the `math` package before using these functions, as in the example below:
```suggestion
Go supports many different **math functions** through the `math` package. The `math` package must be imported before using these functions, as in the example below:
```

2023-06-08 11:40 UTC, SSwiniarski commented
@KTom101, I applied your changes.

2023-06-08 14:01 UTC, KTom101 approved these changes
@SSwiniarski I'll pass this on for a second review

2023-06-09 13:52 UTC, caupolicandiaz approved these changes
@SSwiniarski LGTM. My only comment is that perhaps we should use a different example on the landing page so that we don't have the exact copy in the entry for ABS

2023-06-09 16:15 UTC, merged

2023-06-09 21:24 UTC, yangc95 commented
@SSwiniarski live links: Go [Math Functions](https://www.codecademy.com/resources/docs/go/math-functions): [abs()](https://www.codecademy.com/resources/docs/go/math-functions/abs)

TY @caupolicandiaz @KTom101