[New Concept] AI Foundation Models
Codecademy/docs pull request #2410
Opened 2023-06-07 19:38 UTC by yangc95

### Description

As discussed here: https://github.com/Codecademy/docs/pull/2165#issuecomment-1569038020
- Create new concept "Foundation Models"

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-08 18:49 UTC, yangc95 commented
@Hassan-fayez Would you like to take a look at this entry as well (one if you're comfortable)? Please let me know otherwise. Foundation model is the term we decided to go with for this concept entry so it would be a good idea to change the file path for the term entry to the correct one. Thanks!

2023-06-10 21:38 UTC, HishamT requested changes
Hey @yangc95, can you add some examples of AI foundation models? :grinning: 

GPT, VAE, BERT, etc...

Thanks!

2023-06-14 14:06 UTC, yangc95 commented
@HishamT Added those examples!

2023-06-14 18:15 UTC, HishamT approved these changes
LGTM!

2023-06-15 17:19 UTC, HishamT approved these changes
LGTM!!

2023-06-16 00:46 UTC, yangc95 commented
@HishamT I added some additional info on foundation models based on this source: https://crfm.stanford.edu/assets/report.pdf#technology

2023-06-17 14:47 UTC, SSwiniarski requested changes
@yangc95 I did a second review and only had a few minor comments.

2023-06-17 14:47 UTC, SSwiniarski commented on content/ai/concepts/foundation-models/foundation-models.md
> +Pre-training models on data is vital in transfer learning, which deals with the application of knowledge learned from one task onto another task. As computer hardware increase in speed and memory, th
```suggestion
Pre-training models on data is vital in transfer learning, which deals with the application of knowledge learned from one task onto another task. As computer hardware increases in speed and memory, the amount of training data that is able to be processed increases as well, making foundation models possible.
```

2023-06-17 14:47 UTC, SSwiniarski commented on content/ai/concepts/foundation-models/foundation-models.md
> +- GPT (Generative Pre-trained Transformer)(https://www.codecademy.com/resources/docs/ai/chatgpt) is a model that was first introduced by OpenAI in 2018. It is trained on text and code, and powers [Ch
```suggestion
- GPT (Generative Pre-trained Transformer) is a model that was first introduced by OpenAI in 2018. It is trained on text and code, and powers [ChatGPT](https://www.codecademy.com/resources/docs/ai/chatgpt) which was released in November 2022.
```

2023-06-17 14:47 UTC, SSwiniarski commented on content/ai/concepts/foundation-models/foundation-models.md
> +**Foundation models** power AI systems that are trained on text, images, code, and other formats of data. These models pre-train on large amounts of unlabeled data from the internet. They can then be
```suggestion
**Foundation models** power AI systems that are trained on text, images, code, and other formats of data. These models pre-train on large amounts of unlabeled data from the internet. They can then be fine-tuned to perform various downstream tasks, like generating content(referred to as [generative AI (GenAI)](https://www.codecademy.com/resources/docs/ai/generative-ai)).
```

2023-06-29 18:12 UTC, yangc95 commented
Thanks @SSwiniarski added those suggestions!

Also @HishamT did you want to take another look after I added additional context.

2023-06-30 15:52 UTC, SSwiniarski approved these changes
@yangc95 Looks good!

2023-07-01 15:00 UTC, SSwiniarski commented
@HishamT are we good to merge this?

2023-07-06 14:54 UTC, merged