[Edit]Python: Regular Expressions
Codecademy/docs pull request #2413
Opened 2023-06-08 11:54 UTC by caupolicandiaz

### Description

This PR makes a number of corrections and enhancements including:
- Correcting missing capitalizations
- Bolding the first entry in several instances
- Codebyte examples incorrectly formatted as standard code blocks
- Adding a codebyte
- Other small formatting edits

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-08 12:19 UTC, SSwiniarski requested changes
@caupolicandiaz Looks good. I only had one suggestion to update a code comment.

2023-06-08 12:19 UTC, SSwiniarski commented on content/python/concepts/regex/terms/split/split.md
>  # A backslash indicates that the parentheses are part of the pattern
```suggestion
# A backslash indicates that the asterisks are part of the pattern
```

2023-06-08 12:35 UTC, caupolicandiaz commented
@SSwiniarski Good catch! I've made the edit.

2023-06-08 12:51 UTC, SSwiniarski approved these changes
@caupolicandiaz Looks good!

2023-07-02 22:40 UTC, KTom101 approved these changes
@caupolicandiaz LGTM 👍

2023-07-02 22:44 UTC, merged

2023-07-02 22:47 UTC, KTom101 commented
Links to edited files: [Regular Expressions](https://www.codecademy.com/resources/docs/python/regex), [re.findall](https://www.codecademy.com/resources/docs/python/regex/findall), [re.match](https://www.codecademy.com/resources/docs/python/regex/match), [re.search](https://www.codecademy.com/resources/docs/python/regex/search), [re.split()](https://www.codecademy.com/resources/docs/python/regex/split)