Create vars.md
Codecademy/docs pull request #2450
Opened 2023-06-09 16:22 UTC by SayalGorania

Created vars.md file and added content

### Description

Added vars.md file to describe the built-in vars function in Python. Closes issue #2389 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-09 16:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2450) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2450) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2450) it.</sub>

2023-06-09 17:03 UTC, SSwiniarski requested changes
@SayalGorania I did a first review and left a few comments.

2023-06-09 17:03 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/vars/vars.md
> +Use vars() to return the __dict__ attributes of the object 'Person'
```suggestion
The following example uses `vars()` to return the `__dict__` attributes of the object `Person`:
```

2023-06-09 17:03 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/vars/vars.md
> +	>>>{'__module__': '__main__', 'name': 'John', 'age': 36, 'country': 'norway', '__dict__': <attribute '__dict__' of 'Person' objects>, '__weakref__': <attribute '__weakref__' of 'Person' objects>, '_
```suggestion
```
That is not actual code or part of the codebyte. Remove it. Also add a line to output the value of `x` to the user.

2023-06-09 17:25 UTC, SayalGorania commented
@SSwiniarski  I have reviewed an tried to implement your comments and suggestions.

2023-06-10 12:07 UTC, SSwiniarski approved these changes
@SayalGorania looks good for a second review.

2023-06-10 12:07 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/vars/vars.md
> +## Example
```suggestion
## Codebyte Example
```

2023-06-10 16:09 UTC, caupolicandiaz requested changes
@SayalGorania I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-06-10 16:09 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/vars/vars.md
> +Description: 'Returns the __dict__ attirbute of an object.'
```suggestion
Description: 'Returns the __dict__ attribute of an object.'
```

2023-06-10 16:09 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/vars/vars.md
> +  - 'learn-python'
```suggestion
  - 'learn-python-3'
```

2023-06-10 16:09 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/vars/vars.md
> +**`vars()`** is a built-in python function that returns the `__dict__` attribute of an object. The `__dict__` attribute is a dictionary containing the object's changeable attributes.
```suggestion
**`vars()`** is a built-in Python function that returns the `__dict__` attribute of an object. The `__dict__` attribute is a dictionary containing the object's mutable attributes.
```

2023-06-10 16:09 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/vars/vars.md
> +Here, 'object' refers to an instance of a particular class.
```suggestion
Here, `object` refers to an instance of a particular class.
```

2023-06-10 16:09 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/vars/vars.md
> +	class Person:
the code should be shifted to the left

2023-06-10 22:39 UTC, SayalGorania commented
@caupolicandiaz I have reviewed your comments and tried to make the relevant changes.

2023-06-12 03:05 UTC, CBID2 approved these changes
Looks good to me! 😊

2023-06-21 19:39 UTC, caupolicandiaz approved these changes
@SayalGorania Looks good.

2023-06-22 12:00 UTC, merged

2023-06-22 15:35 UTC, SSwiniarski commented
@SayalGorania Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/python/built-in-functions/vars

![image](https://github.com/Codecademy/docs/assets/86081858/30c060cd-62d1-48b3-ac53-a8aa9be9cf84)

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.