[Term Entry] JavaScript Dates .getUTCDay() #2338
Codecademy/docs pull request #2456
Opened 2023-06-10 13:46 UTC by leonly-wd

### Description

-Added term entry for the method getUTCDay for JavaScript

### Type of Change

- Adding a new entry 

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-10 13:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2456) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2456) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2456) it.</sub>

2023-06-10 16:35 UTC, caupolicandiaz requested changes
@leonly-wd I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-06-10 16:35 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getUTCDay/getUTCDay.md
> +  - 'paths/front-end-developer-career-path'
```suggestion
  - 'paths/front-end-engineer-career-path'
```

2023-06-10 16:35 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getUTCDay/getUTCDay.md
> +The ** `getUTCDay()` ** method returns the day of the week in the specified date according to universal time, as an integer value from 0 - 6 where 0 represents Sunday, 1 for Monday and so on.
```suggestion
The **`getUTCDay()`** method returns the day of the week in the specified date according to universal time. The returned value is an integer from `0` to `6` where `0` represents Sunday, `1` for Monday and so on.
```

2023-06-10 16:35 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getUTCDay/getUTCDay.md
> +```javascript
```suggestion
```pseudo
```

2023-06-10 16:35 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getUTCDay/getUTCDay.md
> +getUTCday();
```suggestion
date_obj.getUTCday();
```

2023-06-10 16:35 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getUTCDay/getUTCDay.md
> +```
add a line break between the block and the sentence

2023-06-10 16:35 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getUTCDay/getUTCDay.md
> +The return value will give you a integer between 0 and 6:
```suggestion
The return value of the passed `Date` object will yield an integer between `0` and `6`:
```

2023-06-10 16:35 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getUTCDay/getUTCDay.md
> +The output will be 6.
```suggestion
The output will be:

```shell
6
```
```

2023-06-10 20:51 UTC, leonly-wd commented
@caupolicandiaz Hi I've made the changes as requested but I think I made a mistake by adding an extra commit. There should only be one commit the Update getUTCDay file commit.

2023-06-12 13:32 UTC, caupolicandiaz approved these changes
@leonly-wd I've gone ahead and made some edits that were outstanding and removed the duplicate file. Please review the changes carefully for future reference.

2023-06-13 08:36 UTC, leonly-wd commented
> @leonly-wd I've gone ahead and made some edits that were outstanding and removed the duplicate file. Please review the changes carefully for future reference.

Ok thank you

2023-06-14 16:09 UTC, merged

2023-06-14 16:17 UTC, SSwiniarski commented
@leonly-wd Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/javascript/dates/getUTCDay

You're currently listed as an anonymous contributor. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.

![image](https://github.com/Codecademy/docs/assets/86081858/b0540530-3050-47c8-aba9-0a2290037b95)

To add your GitHub username to your Codecademy profile:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

![image](https://github.com/Codecademy/docs/assets/86081858/f3a183f5-d75e-4e28-8766-761cdca3d946)

2.) Make sure to set your visibility to “everyone”:

![image](https://github.com/Codecademy/docs/assets/86081858/40f92196-c427-43ee-9763-0d7b4c2297b5)

3.) Then log out and log back into Codecademy using your GitHub login:
 
![image](https://github.com/Codecademy/docs/assets/86081858/79152e83-9478-4ba9-b056-0c4b56b086c7)

Note: Your email used for Codecademy will have to be listed in your GitHub profile for the login feature to properly work. If you 
use the same email for both GitHub and Codecademy already, then you're set.

In addition, we may reach out in the future if any adjustments to these entries are required.