Update all.md
Codecademy/docs pull request #2459
Opened 2023-06-10 17:43 UTC by shivangnayar-crypto

added new content (definitions, codeblocks, etc.)

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-10 17:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2459) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2459) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2459) it.</sub>

2023-06-11 01:49 UTC, shivangnayar-crypto commented
@SSwiniarski

2023-06-11 01:52 UTC, shivangnayar-crypto commented
I need help regarding how to pass those ci checks

2023-06-11 13:13 UTC, SSwiniarski commented
@shivangnayar-dev This PR doesn't address the issue you were assigned. The issue was to add codebyte entries to two terms. This only addresses the one term and does not add a codebyte, but just rewrites the existing example code. Do you want to revise this PR to address the issue, or do you want to be unassigned from the issue and have this PR reviewed on its own merits in its current state?

2023-06-11 13:37 UTC, shivangnayar-dev commented
i apologies , I will do it can you help me with providing more details like what actually you need.
please assign me this issue.
thanks

2023-06-11 19:41 UTC, SSwiniarski commented
@shivangnayar-dev what the issue is asking for is to add new Codebytes at the end of the two entries. Codebytes are examples of code that can be run by the reader of the entry. They should be different from the example given in the body of the entry, and should look something like this:

````
## Codebyte Example

A sentence describing what the codebyte does:

```codebyte/javascript
the example code to run goes here
```
````

You can look at the codebytes for other JavaScript entries, like [here.](https://github.com/Codecademy/docs/edit/main/content/javascript/concepts/arrays/terms/indexOf/indexOf.md)

The issue you claimed wants codebytes to be added to both these entries:
- https://www.codecademy.com/resources/docs/javascript/promise/all
- https://www.codecademy.com/resources/docs/javascript/promise/any

2023-06-12 00:40 UTC, CBID2 commented on content/javascript/concepts/promise/terms/all/all.md
> +When we use .all(), all the tasks start together, and .all() waits for all of them to finish. It gives us a Promise that contains the results of all the tasks.
[Proofreading/Nitpick] According to the [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#writing-entries), pronouns(e.g., I, we, us, our, they, you, he, she) can't be used. 
```suggestion
When using `.all()`, the tasks start together and wait for all of them to finish. `.all()` gives a Promise that contains the results of all the tasks.
```

2023-06-12 00:42 UTC, CBID2 commented on content/javascript/concepts/promise/terms/all/all.md
> +When we use .all(), all the tasks start together, and .all() waits for all of them to finish. It gives us a Promise that contains the results of all the tasks.
[Proofreading/Nitpick] These two lines share the same issue as line 5. Refer to [my feedback from there](https://github.com/Codecademy/docs/pull/2459/files#r1225974895) to help you.
```suggestion
The .all() method in JavaScript Promises helps us work with multiple tasks at once. It takes a group of tasks (Promises) and returns a new Promise.


When we use .all(), all the tasks start together, and .all() waits for all of them to finish. It gives us a Promise that contains the results of all the tasks.
```

2023-06-12 00:43 UTC, CBID2 commented on content/javascript/concepts/promise/terms/all/all.md
> +We use Promise.all() to execute these promises in parallel and wait for all of them to resolve. The .then() callback receives an array of resolved values in the same order as the input promises. We d
[Proofreading/Nipick] Refer to [my comment on line 5](https://github.com/Codecademy/docs/pull/2459/files#r1225974895). It shares the same issue as this line.  
```suggestion
In this example, we have three functions (fetchUserData(), fetchProductData(), and fetchOrderData()) that simulate API calls with a delay using setTimeout(). Each function returns a Promise that resolves with the respective data.

We use Promise.all() to execute these promises in parallel and wait for all of them to resolve. The .then() callback receives an array of resolved values in the same order as the input promises. We destructure the array to extract the user data, product data, and order data, and log them to the console.
```

2023-06-12 00:45 UTC, CBID2 requested changes
Hi, @shivangnayar-dev! :) I gave some proofreading suggestions for your entry. I hope they help! :)

2023-06-12 02:51 UTC, shivangnayar-dev commented
> Hi, @shivangnayar-dev! :) I gave some proofreading suggestions for your entry. I hope they help! :)

Thanks !!

2023-06-12 02:51 UTC, shivangnayar-dev commented
> @shivangnayar-dev what the issue is asking for is to add new codebytes at the end of the two entries. Codebytes are examples of code that can be run by the reader of the entry. They should be different from the example given in the body of the entry, and should look something like this:
> 
> ```
> ## Codebyte Example
> 
> A sentence describing what the codebyte does:
> 
> ```codebyte/javascript
> the example code to run goes here
> ```
> ```
> 
> You can look at the codebytes for other JavaScript entries, like [here.](https://github.com/Codecademy/docs/edit/main/content/javascript/concepts/arrays/terms/indexOf/indexOf.md)
> 
> The issue you claimed wants codebytes to be added to both these entries:
> 
> * https://www.codecademy.com/resources/docs/javascript/promise/all
> * https://www.codecademy.com/resources/docs/javascript/promise/any

Ok i will do that!
Thanks

2023-06-12 16:17 UTC, SSwiniarski commented
@shivangnayar-dev are you going to update this PR to add codebytes, or do you want to just submit it as-is?

2023-06-13 02:43 UTC, shivangnayar-dev commented
> @shivangnayar-dev are you going to update this PR to add codebytes, or do you want to just submit it as-is?

Yes, i will add codebytes

2023-06-13 04:37 UTC, shivangnayar-dev commented
> > @shivangnayar-dev are you going to update this PR to add codebytes, or do you want to just submit it as-is?
>

2023-06-13 04:39 UTC, shivangnayar-dev commented
> > > @shivangnayar-dev are you going to update this PR to add codebytes, or do you want to just submit it as-is?



> @shivangnayar-dev are you going to update this PR to add codebytes, or do you want to just submit it as-is?

for now you can submit it as the codebyte has been created for .all() but for .any() is remaining

2023-06-13 04:44 UTC, shivangnayar-dev commented
> @shivangnayar-dev are you going to update this PR to add codebytes, or do you want to just submit it as-is?

you can submit it as codebyte is created for .all()

2023-06-13 11:34 UTC, SSwiniarski commented
> > @shivangnayar-dev are you going to update this PR to add codebytes, or do you want to just submit it as-is?
> 
> you can submit it as codebyte is created for .all()

@shivangnayar-dev in order to address the issue you also need to add a codebyte for .any() in this PR.

2023-06-23 18:41 UTC, SSwiniarski commented
@shivangnayar-dev I am unassigning you from the original issue and reviewing this PR as-is without codebytes.

2023-06-23 18:59 UTC, SSwiniarski requested changes
@shivangnayar-dev I reviewed your entry and had several comments.

2023-06-23 18:59 UTC, SSwiniarski commented on content/javascript/concepts/promise/terms/all/all.md
> +Description: "The .all() method in JavaScript Promises helps us work with multiple tasks at once. It takes a group of tasks (Promises) and returns a new Promise.
```suggestion
Description: 'Takes a group of tasks (Promises) and returns a new Promise.'
```
Descriptions in the metadata are not multi-line.

2023-06-23 18:59 UTC, SSwiniarski commented on content/javascript/concepts/promise/terms/all/all.md
> +
```suggestion
```
Delete blank line.

2023-06-23 18:59 UTC, SSwiniarski commented on content/javascript/concepts/promise/terms/all/all.md
> +When using `.all()`, the tasks start together and wait for all of them to finish. `.all()` gives a Promise that contains the results of all the tasks.
```suggestion
```
Delete line

2023-06-23 18:59 UTC, SSwiniarski commented on content/javascript/concepts/promise/terms/all/all.md
> +The .all() method in JavaScript Promises helps us work with multiple tasks at once. It takes a group of tasks (Promises) and returns a new Promise.
```suggestion
The **`.all()`** method in JavaScript Promises helps in working with multiple tasks at once. It takes a group of tasks (Promises) and returns a new Promise.
```
No first- or second- person pronouns.

2023-06-23 18:59 UTC, SSwiniarski commented on content/javascript/concepts/promise/terms/all/all.md
> +
```suggestion
```
Delete blank line

2023-06-23 18:59 UTC, SSwiniarski commented on content/javascript/concepts/promise/terms/all/all.md
> +When we use .all(), all the tasks start together, and .all() waits for all of them to finish. It gives us a Promise that contains the results of all the tasks.
```suggestion
When using `.all()`, all the tasks start together, and `.all()` waits for all of them to finish. It returns a Promise that contains the results of all the tasks.
```
No first- or second-person pronouns in Docs.

2023-06-23 18:59 UTC, SSwiniarski commented on content/javascript/concepts/promise/terms/all/all.md
> +## Explanation
```suggestion
```
Remove the header.

2023-06-23 18:59 UTC, SSwiniarski commented on content/javascript/concepts/promise/terms/all/all.md
> +
```suggestion
```
Delete blank line.

2023-06-23 18:59 UTC, SSwiniarski commented on content/javascript/concepts/promise/terms/all/all.md
> +In this example, we have three functions (fetchUserData(), fetchProductData(), and fetchOrderData()) that simulate API calls with a delay using setTimeout(). Each function returns a Promise that reso
```suggestion
In this example, there are three functions (`fetchUserData()`, `fetchProductData()`, and `fetchOrderData()`) that simulate API calls with a delay using `setTimeout()`. Each function returns a Promise that resolves with the respective data.
```
No first- or second- person pronouns in Docs.

2023-06-23 18:59 UTC, SSwiniarski commented on content/javascript/concepts/promise/terms/all/all.md
> +We use Promise.all() to execute these promises in parallel and wait for all of them to resolve. The .then() callback receives an array of resolved values in the same order as the input promises. We d
```suggestion
`Promise.all()` executes these promises in parallel and waits for all of them to resolve. The `.then()` callback receives an array of resolved values in the same order as the input promises. The example destructures the array to extract the user data, product data, and order data, and log them to the console.
```
No first- or second-person pronouns in Docs.

2023-07-29 13:50 UTC, SSwiniarski approved these changes
@shivangnayar-dev In the interest of moving this along, I committed all my suggestions so it can go on to a second review.

2023-08-05 04:07 UTC, KTom101 commented
@SSwiniarski Taking a closer look at this PR. I noticed the Promise: [.all()](https://www.codecademy.com/resources/docs/javascript/promise/all) entry already has a codebyte. However, it looks like that update was made after this PR was made. So merging these changes will outdate the changes already made.

This can not be merged as is but if there are edits that we would like to include in the version we have now then I think this would need to be reopened. Let me know what you think on this.

cc @yangc95

2023-08-05 13:31 UTC, SSwiniarski commented
@KTom101 do we just want to close this?

2023-08-07 13:47 UTC, CBID2 commented
> @KTom101 do we just want to close this?

I think it would be best

2023-08-08 01:59 UTC, KTom101 commented
I'm going ahead and closing this out since the original entry has been edited with the change mentioned in the issue. 

@shivangnayar-dev Feel free to work on another [issue](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee) but please make sure you understand what is being asked for first.

2023-08-08 01:59 UTC, KTom101 commented
I'm going ahead and closing this out since the original entry has been edited with the change mentioned in the issue.

@shivangnayar-dev Feel free to work on another [issue](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee) but please make sure you understand what is being asked for first.

2023-08-08 01:59 UTC, closed without merging