Created a new entry for numpy.aMax
Codecademy/docs pull request #2463
Opened 2023-06-11 04:54 UTC by mark-nettleton

### Description

Added new entry for numpy function AMax

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-11 04:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2463) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2463) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2463) it.</sub>

2023-06-11 13:45 UTC, SSwiniarski requested changes
@mark-nettleton Looks good, only a few minor comments on first review.

2023-06-11 13:45 UTC, SSwiniarski commented on content/numpy/concepts/built-in-functions/terms/amax/amax.md
> +- If axis is None, the result would be a scalar value.
```suggestion
- If `axis` is None, the result would be a scalar value.

```

2023-06-11 13:45 UTC, SSwiniarski commented on content/numpy/concepts/built-in-functions/terms/amax/amax.md
> +- If axis is an integer, the result would be an array of dimension `a.ndim - 1`.
```suggestion
- If `axis` is an integer, the result would be an array of dimension `a.ndim - 1`.

```

2023-06-11 13:45 UTC, SSwiniarski commented on content/numpy/concepts/built-in-functions/terms/amax/amax.md
> +- If axis is a tuple, the result would be an array of dimension `a.ndim - len(axis)`.
```suggestion
- If `axis` is a tuple, the result would be an array of dimension `a.ndim - len(axis)`.

```

2023-06-11 13:45 UTC, SSwiniarski commented on content/numpy/concepts/built-in-functions/terms/amax/amax.md
> +[10,12,14,16]
```suggestion
[10 12 14 16]
```

2023-06-12 01:45 UTC, mark-nettleton commented
@SSwiniarski thanks for the suggestions. All committed. 
I'm still learning github...how do I update my local aMax branch with the changes made with these 4 commits? Do I need to wait until you've merged the branch in to main and then sync with my version of the repo?

2023-06-12 16:13 UTC, SSwiniarski approved these changes
@mark-nettleton Looks good for a second review.

2023-06-13 00:47 UTC, mark-nettleton commented
> > @SSwiniarski thanks for the suggestions. All committed. I'm still learning github...how do I update my local aMax branch with the changes made with these 4 commits? Do I need to wait until you've merged the branch in to main and then sync with my version of the repo?
> 
> @mark-nettleton you should be able to do a `git pull` from the remote version of your branch.

@SSwiniarski I get the error: "Your configuration specifies to merge with the ref 'refs/heads/amax'
from the remote, but no such ref was fetched."
Have tried deleting the local branch and recereating from remote repo but same error exists (although it has now updated the code file now). Why is that error occuring?

2023-06-13 11:25 UTC, SSwiniarski commented
@KTom101, @yangc95, @caupolicandiaz any idea on @mark-nettleton's issue?

2023-06-14 14:58 UTC, caupolicandiaz requested changes
@mark-nettleton I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-06-14 14:58 UTC, caupolicandiaz commented on content/numpy/concepts/built-in-functions/terms/amax/amax.md
> +Description: 'Returns the maximum of an array or maximum along an axis.'
```suggestion
Description: 'Returns the maximum of a given array or maximum along an axis.'

```

2023-06-14 14:58 UTC, caupolicandiaz commented on content/numpy/concepts/built-in-functions/terms/amax/amax.md
> +The **`.amax()`** function returns the maximum value of an array or maximum along an axis. The `.amax()` function is equivalent to the NumPy method `ndarray.max()`.
```suggestion
The **`.amax()`** function returns the maximum value of a given array or the maximum along an axis. The `.amax()` function is equivalent to the NumPy method `ndarray.max()`.

```

2023-06-14 14:58 UTC, caupolicandiaz commented on content/numpy/concepts/built-in-functions/terms/amax/amax.md
> +Returns:
add an empty line after Returns:

2023-06-14 14:58 UTC, caupolicandiaz commented on content/numpy/concepts/built-in-functions/terms/amax/amax.md
> +The maximum element in the array `a`.
```suggestion

```

2023-06-14 14:58 UTC, caupolicandiaz commented on content/numpy/concepts/built-in-functions/terms/amax/amax.md
> +- If `axis` is None, the result would be a scalar value.
remove the empty lines between these items

2023-06-14 14:58 UTC, caupolicandiaz commented on content/numpy/concepts/built-in-functions/terms/amax/amax.md
> +The following example creates an array and then uses a few `.amin()` operations to return the minimum.
```suggestion
The following example creates an array and applies several `.amin()` operations, and returns each result to console.

```

2023-06-14 14:58 UTC, caupolicandiaz commented on content/numpy/concepts/built-in-functions/terms/amax/amax.md
> +The following example creates a 2-dimensional array each containing 8 random integers (between 1 and 20). First, it prints the array, then performs four `.amax()` operations with different arguments
```suggestion
The following example creates a 2-dimensional array composed of random integers (between 1 and 20). The code prints the array, and then prints the result of four `.amax()` operations that use different arguments.

```

2023-06-18 23:37 UTC, mark-nettleton commented
@caupolicandiaz I've approved your suggestions where I can. However I can't make any further amendments to the code (removing and addign blank lines) due to my issue:
_Your configuration specifies to merge with the ref 'refs/heads/amax'
from the remote, but no such ref was fetched._

2023-06-19 20:53 UTC, caupolicandiaz approved these changes
@mark-nettleton I've gone ahead and made the edits. For future reference, there should never be multiple lines between elements in an entry.

2023-06-19 20:55 UTC, merged

2023-06-20 11:55 UTC, SSwiniarski commented
@mark-nettleton Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/numpy/built-in-functions/amax

![image](https://github.com/Codecademy/docs/assets/86081858/ef11f9b1-7de3-4ae2-9f1e-528049ad88d9)

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.