Python Built-in-function : .dir()
Codecademy/docs pull request #2470
Opened 2023-06-12 11:28 UTC by VasilisCbt17gr

### Description

- Added the dir() bult-in-function for Python
- Closes Issue #2137 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-12 15:25 UTC, CBID2 approved these changes
Looks good to me! 😊👍🏾

2023-06-13 10:40 UTC, VasilisCbt17gr commented
@CBID2  Could you check it please?

2023-06-13 11:47 UTC, SSwiniarski commented
@VasilisCbt17gr You already have an outstanding PR on this issue that's currently being reviewed, [#2303](https://github.com/Codecademy/docs/pull/2303). Why are you submitting another one?

2023-06-13 17:20 UTC, VasilisCbt17gr commented
@SSwiniarski  I'm training on gitlab and i couldn't complete  issue #2303 . So, i did the procedure from scratch ,reviewed each video carefully and submitted it again.

2023-06-13 17:24 UTC, VasilisCbt17gr commented
@cbid2 I did every check using yarn successfully. But there is still a sign "Required" and a message " 1 workflow awaiting approval ".
What should i do to proceed? Thank you.

2023-06-13 17:56 UTC, VasilisCbt17gr commented
@CBID2  So, have i wait or make some changes?

2023-06-13 21:43 UTC, CBID2 commented
> @CBID2 So, have i wait or make some changes?

You'd have to wait for the maintainers, the people I tagged, @VasilisCbt17gr. Also, don't forget to update your branch.

2023-06-14 11:54 UTC, SSwiniarski requested changes
@VasilisCbt17gr I did a first review. Most important is your PR touches two files aside from the entry. We cannot merge with those changes. So you need to undo those changes or submit a new PR without them.

2023-06-16 10:03 UTC, VasilisCbt17gr commented
@SSwiniarski  Could you review the changes?

2023-06-16 15:16 UTC, SSwiniarski requested changes
@VasilisCbt17gr You haven't addressed three of my comments. Most important are the changes to the two system files in this PR **this PR cannot be merged with those changes**. You need to undo those changes in this PR, or create a fresh branch off of main for a new PR that contains just your entry.

2023-06-17 12:19 UTC, SSwiniarski commented on yarn.lock
@VasilisCbt17gr The easiest way to fix this at this point is for you to make a fresh branch off of main, copy your entry there, and create a fresh PR. The yarn.lock and package.json files should not be touched in the PR, and these are heavily modified. We can't merge with those changes.

2023-06-19 06:54 UTC, VasilisCbt17gr commented
@SSwiniarski  Could you check issue #2528 ? Thank you.

2023-06-19 16:27 UTC, SSwiniarski commented
Closing because a new PR was created for this issue.

2023-06-22 15:33 UTC, closed without merging