[feat] Create emojis.md
Codecademy/docs pull request #2475
Opened 2023-06-13 04:52 UTC by CBID2

### Description

I have added a new entry to the Markdown section. In other words, this pull request closes issue #2474 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-13 05:17 UTC, CBID2 commented
Hi @KTom101! :) I'm ready for your review! 😄

2023-06-14 15:59 UTC, SSwiniarski requested changes
@CBID2 I did a first review and only had a couple of comments.

2023-06-14 15:59 UTC, SSwiniarski commented on .vscode/settings.json
Need to remove this file.

2023-06-14 15:59 UTC, SSwiniarski commented on content/markdown/concepts/emojis/emojis.md
> +When using Markdown, you can just copy and paste emojis straight from sources like [Emojipedia](https://emojipedia.org/):
```suggestion
When using Markdown, emojis can be copied and pasted straight from sources like [Emojipedia](https://emojipedia.org/):
```
No first- or second-person pronouns.

2023-06-14 16:09 UTC, CBID2 commented
> @CBID2 I did a first review and only had a couple of comments.

Just committed your suggestions @SSwiniarski! :)

2023-06-14 16:32 UTC, SSwiniarski approved these changes
@CBID2 It looks good for a second review. (I deleted the extra file.)

2023-06-14 16:34 UTC, CBID2 commented
> @CBID2 It looks good for a second review. (I deleted the extra file.)

Thanks @SSwiniarski! :) The only issue I have is the "Push/ci format:verify" test. It keeps failing for some reason.

2023-06-22 15:59 UTC, SSwiniarski commented
> > @CBID2 It looks good for a second review. (I deleted the extra file.)
> 
> Thanks @SSwiniarski! :) The only issue I have is the "Push/ci format:verify" test. It keeps failing for some reason.

@CBID2 I did an `npm run format` on the file and it fixed the issue.

2023-06-22 16:00 UTC, CBID2 commented
> > > @CBID2 It looks good for a second review. (I deleted the extra file.)
> 
> > 
> 
> > Thanks @SSwiniarski! :) The only issue I have is the "Push/ci format:verify" test. It keeps failing for some reason.
> 
> 
> 
> @CBID2 I did an `npm run format` on the file and it fixed the issue.

Thanks

2023-06-24 19:19 UTC, KTom101 requested changes
@CBID2 Just a few minor changes from me.

2023-06-24 19:19 UTC, KTom101 commented on content/markdown/concepts/emojis/emojis.md
> +Another method that is used are shortcodes, emojis being described through words. These vary from application to application, so it's important to refer to their Markdown style guide to ensure that t
```suggestion
Another method used are shortcodes, emojis being described through words. These vary from application to application, so it's important to refer to their Markdown style guide to ensure that the emojis are described accordingly.
```

2023-06-24 19:19 UTC, KTom101 commented on content/markdown/concepts/emojis/emojis.md
> +In the paragraph below, the shortcode is conveyed in accordance to [GitHub's standards](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/
```suggestion
In the paragraph below, the shortcode is conveyed in accordance with [GitHub's standards](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#using-emoji):
```

2023-06-24 19:23 UTC, CBID2 commented on content/markdown/concepts/emojis/emojis.md
> +Another method that is used are shortcodes, emojis being described through words. These vary from application to application, so it's important to refer to their Markdown style guide to ensure that t
Done

2023-06-24 19:32 UTC, KTom101 approved these changes
@CBID2 Looks good 👍

2023-06-24 19:37 UTC, merged

2023-06-24 19:49 UTC, KTom101 commented
@CBID2 It's live here: https://www.codecademy.com/resources/docs/markdown/emojis

I'm noticing that perhaps we should have made the title say "Emojis" with a capital "E" and "s" at the end. Are you able to open a PR to change the title in the metadata?

2023-06-24 20:21 UTC, CBID2 commented
> @CBID2 It's live here: https://www.codecademy.com/resources/docs/markdown/emojis
> 
> 
> 
> I'm noticing that perhaps we should have made the title say "Emojis" with a capital "E" and "s" at the end. Are you able to open a PR to change the title in the metadata?

Sure I'll do it later

2023-06-24 20:22 UTC, KTom101 commented
> > @CBID2 It's live here: https://www.codecademy.com/resources/docs/markdown/emojis
> > I'm noticing that perhaps we should have made the title say "Emojis" with a capital "E" and "s" at the end. Are you able to open a PR to change the title in the metadata?
> 
> Sure I'll do it later

Great, thanks!

2023-06-24 20:23 UTC, CBID2 commented
> > > @CBID2 It's live here: https://www.codecademy.com/resources/docs/markdown/emojis
> 
> > > I'm noticing that perhaps we should have made the title say "Emojis" with a capital "E" and "s" at the end. Are you able to open a PR to change the title in the metadata?
> 
> > 
> 
> > Sure I'll do it later
> 
> 
> 
> Great, thanks!

Can you review this one?

2023-06-25 02:17 UTC, CBID2 commented
> > > @CBID2 It's live here: https://www.codecademy.com/resources/docs/markdown/emojis
> > > I'm noticing that perhaps we should have made the title say "Emojis" with a capital "E" and "s" at the end. Are you able to open a PR to change the title in the metadata?
> > 
> > 
> > Sure I'll do it later
> 
> Great, thanks!

Made the change @KTom101! :) It's #2587