sql-function-cos
Codecademy/docs pull request #2476
Opened 2023-06-13 08:56 UTC by nikolaspoczekaj

### Description

Thanks for assigning. This closes #2262 .

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-13 13:07 UTC, caupolicandiaz requested changes
@nikolaspoczekaj I just added a few comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-06-13 13:07 UTC, caupolicandiaz commented on content/sql/concepts/math-functions/terms/cos/cos.md
> +The SQL function **`COS()`** calculates the cosine of a given angle, expressed in radians. It returns the ratio of the adjacent side of a right triangle to its hypotenuse, representing the cosine val
```suggestion
The SQL function **`COS()`** calculates the cosine of a given angle, expressed in radians.
```

2023-06-15 05:58 UTC, nikolaspoczekaj commented
@caupolicandiaz thanks for the review! I'm done with the changes.

2023-06-15 06:05 UTC, nikolaspoczekaj commented
cant really tell why the format verify is failing...

2023-06-15 12:44 UTC, merged