[Term Entry] JavaScript Dates .getUTCMonth() #2426
Codecademy/docs pull request #2477
Opened 2023-06-13 09:49 UTC by Iampetrus

### Description

- Added .getUTCMonth() method for Javascript
- Closes #2426
- 
### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-13 09:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2477) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2477) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2477) it.</sub>

2023-06-13 12:50 UTC, caupolicandiaz requested changes
@Iampetrus Please update the entry, and tag me when you've finished making changes. Thanks

2023-06-13 12:50 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getUTCMonth/getUTCMonth.md
> +Title:
Please review another entry or template and update the metadata to match. There are several edits that are required:

- all of the content must be within single quotes
- the title and description should not begin on a separate line
- catalogcontent should include two items

2023-06-13 12:50 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getUTCMonth/getUTCMonth.md
> +‘Method of date instances that returns the month date according to universal time, as a zero-based value (where zero indicates the first month of the year).'
```suggestion
'Returns the month of the passed date according to universal time, as a zero-based value.' 
```

2023-06-13 12:50 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getUTCMonth/getUTCMonth.md
> +get methods retrieve the date components based on the user’s local timezone settings. For increased control over the dates and times, you can use the **`.getUTCMonth()`** method, which are exactly th
```suggestion
Get methods are used to retrieve date components based on the user’s local timezone settings. The **`.getUTCMonth()`** method returns the month of the date passed, similar to `.getMonth()`. However, `.getUTCMonth()` calculates the time based on the UTC (Coordinated Universal Time) standard.
```

2023-06-13 12:50 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getUTCMonth/getUTCMonth.md
> +## Syntax
add a line break after the header

2023-06-13 12:50 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getUTCMonth/getUTCMonth.md
> +```
```suggestion
```pseudo
```

2023-06-13 12:50 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getUTCMonth/getUTCMonth.md
> +```
add a line below the syntax

2023-06-13 12:50 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getUTCMonth/getUTCMonth.md
> +Example above assigns the month portion of the current `Date` to the variable `month`.
update this line to explain the function, the return value, etc in more detail.

2023-06-13 12:50 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getUTCMonth/getUTCMonth.md
> +## Example
add an empty line after the header

2023-06-13 12:50 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/getUTCMonth/getUTCMonth.md
> +// expected output December: 11
delete the comments and use a shell block instead

2023-06-15 12:03 UTC, caupolicandiaz approved these changes
@Iampetrus This all set for another review. I just made a couple of small edits mostly to correct spacing.

2023-06-15 12:59 UTC, SSwiniarski approved these changes
@Iampetrus I did a few punctuation edits on the metadata, otherwise it looks good to me.

2023-06-15 13:11 UTC, merged