php-function-strtolower
Codecademy/docs pull request #2485
Opened 2023-06-15 06:30 UTC by nikolaspoczekaj

### Description

Thanks for assigning me. This closes #2435 .

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-15 16:35 UTC, SSwiniarski requested changes
@nikolaspoczekaj Looks good, only one comment.

2023-06-15 16:35 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/strtolower/strtolower.md
> +The **`strtolower()`** method in PHP converts a string to lowercase. It takes a string as input and returns a new string with all the characters converted to lowercase.
```suggestion
The **`strtolower()`** function in PHP converts a string to lowercase. It takes a string as input and returns a new string with all the characters converted to lowercase.
```

2023-06-21 06:24 UTC, nikolaspoczekaj commented
@SSwiniarski Done with the changes !

2023-06-21 19:23 UTC, caupolicandiaz approved these changes
@nikolaspoczekaj @SSwiniarski LGTM

2023-06-22 11:55 UTC, merged

2023-06-22 15:29 UTC, SSwiniarski commented
@nikolaspoczekaj Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/php/string-functions/strtolower

![image](https://github.com/Codecademy/docs/assets/86081858/e8b65993-3148-4772-b28e-c91f1badfa82)