[Term Entry] PHP Math Functions exp() #2269
Codecademy/docs pull request #2493
Opened 2023-06-15 16:55 UTC by MMMMMMMZ

### Description

addresses issue #2269

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-15 17:08 UTC, SSwiniarski requested changes
@MMMMMMMZ I did a first review and left a number of comments. Many of them just removing excess blank lines.

2023-06-15 17:08 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/exp/exp.md
> +Description: 'Returns E raised to the power of x (E^x^).'
```suggestion
Description: 'Returns e raised to the power of x.'
```

2023-06-15 17:08 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/exp/exp.md
> +
```suggestion
```
Remove blank line

2023-06-15 17:08 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/exp/exp.md
> +
```suggestion
```
Remove blank line

2023-06-15 17:08 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/exp/exp.md
> +
```suggestion
```
Remove blank line

2023-06-15 17:08 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/exp/exp.md
> +The `exp()` function Returns E raised to the power of x (E^x^).
```suggestion
The **`exp()`** function Returns _e_ raised to the power of x.
```

2023-06-15 17:08 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/exp/exp.md
> +- `$x`: specifies the exponent that E will be raised to.
```suggestion
- `$x`: specifies the exponent that _e_ will be raised to.
```

2023-06-15 17:08 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/exp/exp.md
> +
```suggestion
```
Remove blank line

2023-06-21 22:27 UTC, MMMMMMMZ commented
I added/removed everything you told me to

2023-06-22 15:39 UTC, SSwiniarski approved these changes
@MMMMMMMZ I made one minor edit. Now it looks good for a second review.

2023-06-22 20:17 UTC, caupolicandiaz approved these changes
@MMMMMMMZ @SSwiniarski Looks good to merge.

2023-06-23 16:22 UTC, merged

2023-06-23 16:36 UTC, SSwiniarski commented
@MMMMMMMZ Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/php/math-functions/exp

![image](https://github.com/Codecademy/docs/assets/86081858/175d3cad-0f8b-4895-8cc9-60b2dbdfe286)

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.