added an entry for getUTCSeconds term
Codecademy/docs pull request #2494
Opened 2023-06-15 22:58 UTC by rickc73

### Description

- added an entry for getUTCSeconds
- Created getUTCSeconds.md
- Completed this task as part of the Git & GitHub course on CodeCademy
### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-15 22:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2494) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2494) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2494) it.</sub>

2023-06-16 02:38 UTC, KTom101 requested changes
@rickc73 I've added a few changes to this entry.

2023-06-16 02:38 UTC, KTom101 commented on content/javascript/concepts/dates/terms/getUTCSeconds/getUTCSeconds.md
> +The getUTCSeconds() method returns the seconds (ranging from 0 to 59) of a specific date according to UTC (Coordinated Universal Time).
```suggestion
The **`getUTCSeconds()`** method returns the seconds (ranging from 0 to 59) of a specific date according to UTC (Coordinated Universal Time).
```

2023-06-16 02:38 UTC, KTom101 commented on content/javascript/concepts/dates/terms/getUTCSeconds/getUTCSeconds.md
> +
Only need one line break here.
```suggestion
```

2023-06-16 02:38 UTC, KTom101 commented on content/javascript/concepts/dates/terms/getUTCSeconds/getUTCSeconds.md
> +Consider the following example that uses the `.getUTCSeconds()` method to get the seconds of `2023-06-06T10:30:04` and logs the result to the console:
```suggestion
The following example uses the `.getUTCSeconds()` method to get the seconds of `2023-06-06T10:30:04` and logs the result to the console:
```

2023-06-16 02:38 UTC, KTom101 commented on content/javascript/concepts/dates/terms/getUTCSeconds/getUTCSeconds.md
> +The example below demonstrates the use of `.getUTCSeconds()` to print the current time in seconds to the console:
Let's add a line break and make this a codebyte example.
```suggestion

## Codebyte Example

The codebyte example below uses the `.getUTCSeconds()` method to get the current time in seconds and logs it to the console:
```

2023-06-16 02:38 UTC, KTom101 commented on content/javascript/concepts/dates/terms/getUTCSeconds/getUTCSeconds.md
> +```js
```suggestion
```codebyte/javascript
```

2023-06-16 02:38 UTC, KTom101 commented on content/javascript/concepts/dates/terms/getUTCSeconds/getUTCSeconds.md
> +console.log(today_seconds) //ouput: current second of todays UTC time
```suggestion
console.log(today_seconds); 
```

2023-06-16 12:26 UTC, rickc73 reviewed
happy with the suggestions, i have applied them

2023-06-16 14:35 UTC, KTom101 approved these changes
@rickc73 I noticed one more extra line break. Otherwise, it looks good for the next review, thanks! 😃

2023-06-16 14:35 UTC, KTom101 commented on content/javascript/concepts/dates/terms/getUTCSeconds/getUTCSeconds.md
> +
```suggestion
```

2023-06-17 13:56 UTC, SSwiniarski approved these changes
@rickc73 Looks good to me!

2023-06-17 14:05 UTC, merged

2023-06-17 14:13 UTC, SSwiniarski commented
Congrats @rickc73 on the new entry. Live link here: https://www.codecademy.com/resources/docs/javascript/dates/getUTCSeconds

![image](https://github.com/Codecademy/docs/assets/86081858/edfd0b2d-20d2-4948-8c0a-98bf0be71bc8)

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.