Create sinh.md
Codecademy/docs pull request #2515
Opened 2023-06-17 02:03 UTC by Alisha-0704

### Description

Adding a term entry for sinh in PHP.

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-17 02:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2515) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2515) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2515) it.</sub>

2023-06-17 12:17 UTC, caupolicandiaz requested changes
@Alisha-0704 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-06-17 12:17 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/sin/sinh.md
> +  - 'Hyperbolic Functions'
Hyperbolic Functions is not a current tag on our list. Please delete the tag, or add it to the tags.md document.

2023-06-17 12:17 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/sin/sinh.md
> +
delete empty line 16. We never have more than one empty line between sections

2023-06-17 12:17 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/sin/sinh.md
> +The **`sinh()`**function is used to calculate the hyperbolic sine of a given number.
```suggestion
The **`sinh()`** function is used to calculate the hyperbolic sine of a given number.
```

2023-06-17 12:17 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/sin/sinh.md
> +Use `sinh()` to calculate the hyperbolic sine of `2.5`:
```suggestion
The example below illustrates a basic implementation of the function:
```

2023-06-17 12:17 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/sin/sinh.md
> +  echo sinh(2.5);  // Output: 6.0502033806203
```suggestion
  echo sinh(2.5);  
```

2023-06-17 12:17 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/sin/sinh.md
> +  echo sinh(2.5);  // Output: 6.0502033806203
We don't use the comment in this instance because we have the output below.

2023-06-17 12:17 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/sin/sinh.md
> +```
```suggestion
```

2023-06-17 12:17 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/sin/sinh.md
> +<?php
remove the comment, the code is runnable and the output doesn't need to be included here

2023-06-17 12:17 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/sin/sinh.md
> +In this example, the `sinh()` function is called with the number `-3` as the parameter. The output will be `-10.01787492741`, which is the hyperbolic sine of `-3`.
```suggestion
```

2023-06-17 12:17 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/sin/sinh.md
> +**Note:** The `sinh()` function is the inverse of the `asinh()` function.
```suggestion
> **Note:** The `sinh()` function is the inverse of the `asinh()` function.
```

2023-06-18 01:42 UTC, Alisha-0704 commented
@caupolicandiaz I've made the changes. Please review. Thanks.

2023-06-19 21:26 UTC, caupolicandiaz approved these changes
@Alisha-0704 This is ready for a second review. FYI I updated the location of the file. I noticed this was saved with the sin entry, instead of on its own in a sinh folder.

2023-06-20 16:23 UTC, SSwiniarski approved these changes
@Alisha-0704 I did a minor formatting edit, otherwise it looks good to merge.

2023-06-20 16:28 UTC, merged

2023-06-20 16:36 UTC, SSwiniarski commented
@Alisha-0704 Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/php/math-functions/sinh

![image](https://github.com/Codecademy/docs/assets/86081858/a9c96834-8ff5-443f-8308-46b5d3aea769)

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.