[CLOSES] 2429 [Term Entry] JavaScript Dates .setFullYear()
Codecademy/docs pull request #2516
Opened 2023-06-17 05:10 UTC by Yashi11

### Description
A new term entry for JavaScript [Dates](https://www.codecademy.com/resources/docs/javascript/dates) about the .setFullYear() method in a new file in docs/content/javascript/concepts/dates/terms/setFullYear/setFullYear.md with  an introductory paragraph about what the method is and does , an example showing the method in use and others as per the requirement.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-17 12:04 UTC, caupolicandiaz requested changes
@Yashi11 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-06-17 12:04 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/setFullYear/setFullYear.md
> +Description: 'Changes the year, month, and/or day of month  according to local time.'
```suggestion
Description: 'Changes the year, month, and/or day according to local time.'
```

2023-06-17 17:44 UTC, Yashi11 commented on content/javascript/concepts/dates/terms/setFullYear/setFullYear.md
> +Sun Aug 14 1887 18:21:27 GMT+0521 (India Standard Time)
This is the output that I have received after running the required code only i.e. the exact code mentioned above the shell output, still I will re-check it once and update accordingly.

2023-06-18 04:21 UTC, Yashi11 commented
@caupolicandiaz Done with the required changes 👍

2023-06-19 21:15 UTC, caupolicandiaz approved these changes
@Yashi11 This is ready for a second review.

2023-06-20 16:19 UTC, SSwiniarski requested changes
@Yashi11 I did a second review and had a few comments.

2023-06-29 15:14 UTC, Yashi11 commented
Done with the required changes.

2023-06-29 16:08 UTC, SSwiniarski approved these changes
@Yashi11 Looks good for a second review.

2023-06-29 16:13 UTC, merged