added setTime.md
Codecademy/docs pull request #2517
Opened 2023-06-17 08:04 UTC by ShivangRawat30

### Description

Added setTime at `docs/content/javascript/concepts/dates/terms/setTime/setTime.md`
Closes #2501

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-17 08:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2517) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2517) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2517) it.</sub>

2023-06-17 12:58 UTC, SSwiniarski requested changes
@ShivangRawat30 I did a fist review and had a couple of comments.

2023-06-17 12:58 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setTIme/setTIme.md
> +The **`.setTime()`** method returns a number, representing the number of milliseconds between the date object and midnight January 1 1970.
```suggestion
The **`.setTime()`** method sets date and time by adding or subtracting a specified number of milliseconds to/from midnight January 1, 1970.
```
The intro sentence and description should be in sync.

2023-06-17 12:58 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setTIme/setTIme.md
> +This results in the following output:
Note this output will be localized, set in the user's time zone.

2023-06-17 13:34 UTC, SSwiniarski approved these changes
@ShivangRawat30 Looks ready for a second review.

2023-06-17 15:24 UTC, SSwiniarski commented
@ShivangRawat30, we've gone through a review so we're going to keep this PR, but you are **not** supposed to submit a PR for an issue you have not been assigned. There was someone already waiting to contribute to this issue. Do **not** do this again, we have assignments to prevent this situation, where two people are working on the same issue.

2023-06-20 18:21 UTC, caupolicandiaz approved these changes
@ShivangRawat30 @SSwiniarski This is all set to merge. I just made a couple of minor edits, including renaming the file and folder which were set as setTIme in lieu of setTime.

2023-06-21 11:26 UTC, merged

2023-06-21 11:39 UTC, SSwiniarski commented
@ShivangRawat30 Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/javascript/dates/setTime

![image](https://github.com/Codecademy/docs/assets/86081858/2e2e9780-cfdc-4d07-812e-d96a5b9e14bc)

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.