Complete term entry for ACOS SQL function
Codecademy/docs pull request #2523
Opened 2023-06-17 20:51 UTC by jubalclary

### Description

I have wrote a term entry for the ACOS function in SQL for the issue "[Term Entry] SQL Math Functions ACOS #2265".

The file path to my changes is docs/content/sql/concepts/math-functions/terms/acos/acos.md

I *heavily* relied on the doc page for the COS function: https://github.com/Codecademy/docs/blob/main/content/sql/concepts/math-functions/terms/cos/cos.md

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-17 20:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2523) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2523) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2523) it.</sub>

2023-06-18 02:17 UTC, dakshdeepHERE requested changes
A change from my side.

2023-06-18 02:17 UTC, dakshdeepHERE commented on content/sql/concepts/math-functions/terms/acos/acos.md
> +```sql
```suggestion
```pseudo 
```
With syntax always use pseudo.

2023-06-18 13:00 UTC, SSwiniarski requested changes
@jubalclary I did a first review and left a few comments.

2023-06-18 18:42 UTC, jubalclary commented
Thanks for the feedback, I just committed some changes

2023-06-19 15:35 UTC, SSwiniarski approved these changes
@jubalclary I made a small typo change, now it looks good for a second review.

2023-06-20 20:29 UTC, caupolicandiaz approved these changes
@jubalclary @SSwiniarski Looks good to merge. I just made a couple of minor edits.

2023-06-21 11:28 UTC, merged

2023-06-21 11:41 UTC, SSwiniarski commented
@jubalclary Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/sql/math-functions/acos

![image](https://github.com/Codecademy/docs/assets/86081858/802355e1-222c-47ab-a83f-dccdb856de01)

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.