added setSeconds
Codecademy/docs pull request #2524
Opened 2023-06-18 10:39 UTC by ShivangRawat30

### Description
added setSeconds.md at `docs/content/javascript/concepts/dates/terms/setSeconds/setSeconds.md`
solves #2500

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-18 13:06 UTC, SSwiniarski reviewed
@ShivangRawat30 I did a first review and left a couple of comments. Tag me when you've addressed them.

2023-06-18 13:06 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setSeconds/setSeconds.md
> +Description: 'Set the seconds component of a date object to a specified value'
```suggestion
Description: 'Sets the seconds component of a date object to a specified value.'
```

2023-06-18 13:06 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setSeconds/setSeconds.md
> +The **`.setSeconds()`** method takes an integer value as its parameter, representing the new value for the seconds.
```suggestion
The **`.setSeconds()`** method sets the seconds component of a date object to a specified value. It takes an integer value as its parameter, representing the new value for the seconds.
```

2023-06-18 13:06 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setSeconds/setSeconds.md
> +The returned value from `.setSeconds()` modifies the original date object by setting the seconds to the specified value.
```suggestion
The returned value from `.setSeconds()` modifies the original date object, `myDate`, by setting the seconds to `secondsValue`.
```

2023-06-18 13:06 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setSeconds/setSeconds.md
> +```js
Can we use a static datetime value so the output will be consistent whenever we run this code?

2023-06-19 16:41 UTC, SSwiniarski approved these changes
@ShivangRawat30 Looks good for a second review.

2023-06-20 20:42 UTC, caupolicandiaz requested changes
@ShivangRawat30 I've added several comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-06-20 20:42 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/setSeconds/setSeconds.md
> +The **`.setSeconds()`** method sets the seconds component of a date object to a specified value. It takes an integer value as its parameter, representing the new value for the seconds.
```suggestion
The **`.setSeconds()`** method sets the seconds component of a `Date` object to a specified value. It takes an integer value as its parameter, representing the new value for the seconds.
```

2023-06-20 20:42 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/setSeconds/setSeconds.md
> +The returned value from `.setSeconds()` modifies the original date object, `myDate`, by setting the seconds to `secondsValue`.
```suggestion
The returned value from `.setSeconds()` modifies the original `Date` object, `myDate`, by setting the seconds to `secondsValue`.
```

2023-06-20 20:42 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/setSeconds/setSeconds.md
> +In the example below, the `myDate` variable takes the provided Time and then the `.setSeconds()` method is applied to return a modified time.
```suggestion
In the example below, the `myDate` variable is declared and then the `.setSeconds()` method is applied to return a modified time.
```

2023-06-20 20:42 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/setSeconds/setSeconds.md
> +const myDate = new Date(August 29, 2022 23:15:30);
```suggestion
const myDate = new Date('August 29, 2022 23:15:30');
```

2023-06-20 20:42 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/setSeconds/setSeconds.md
> +console.log(myDate);
```suggestion
console.log(myDate.toString());
```

2023-06-21 13:48 UTC, ShivangRawat30 commented
@caupolicandiaz I've implemented the suggested changes.

2023-06-21 17:33 UTC, caupolicandiaz approved these changes
@ShivangRawat30 Looks good

2023-06-21 17:36 UTC, merged

2023-06-22 11:45 UTC, SSwiniarski commented
@ShivangRawat30 Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/javascript/dates/setSeconds

![image](https://github.com/Codecademy/docs/assets/86081858/0481f017-3c89-421b-b953-b83bf660d810)

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.