[Concept Entry]: Added bindec in the terms folder of math-function
Codecademy/docs pull request #2526
Opened 2023-06-18 14:45 UTC by dakshdeepHERE

### Description

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

Fixes#2504

2023-06-18 15:36 UTC, SSwiniarski requested changes
@dakshdeepHERE I did a first review and left a few comments.

2023-06-18 15:36 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/bindec/bindec.md
> +The `bindec()` function in PHP is used to convert a binary string representation to its decimal equivalent. It takes a binary string as input and returns the corresponding decimal value.
```suggestion
The **`bindec()`** function in PHP is used to convert a binary string representation to its decimal equivalent. It takes a binary string as input and returns the corresponding decimal value.
```

2023-06-18 15:36 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/bindec/bindec.md
> +Here's an explanation of the `bindec()` function along with syntax:
We don't need this sentence. Let's remove it.

2023-06-18 15:36 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/bindec/bindec.md
> +- **Parameters**:
Let's remove the `**Parameters**` and `**Return Value**` and just have the two bullet points.

2023-06-18 15:36 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/bindec/bindec.md
> +## Example 2
We don't need a second example, let's remove it.

2023-06-18 15:36 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/bindec/bindec.md
> +It's important to note that if the binary string contains characters other than `0` and `1`, or if it's an empty string, the `bindec()` function will return `0`. Additionally, if the binary string is
```suggestion
> **Note:** If the binary string contains characters other than `0` and `1`, or if it's an empty string, the `bindec()` function will return `0`. Additionally, if the binary string is too large to fit into an integer (defined by the system, usually 32 or 64 bits) the function may return an incorrect result due to integer overflow.
```

2023-06-18 15:36 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/bindec/bindec.md
> +## Additional details
Most of these are redundant with the information you've given in the above note. We can remove this.

2023-06-18 15:42 UTC, dakshdeepHERE commented
@SSwiniarski all the changes are done can you check it once if there's anything else needed.

2023-06-19 15:31 UTC, SSwiniarski approved these changes
@dakshdeepHERE Looks good for a second review.

2023-06-20 20:50 UTC, caupolicandiaz approved these changes
@dakshdeepHERE @SSwiniarski LGTM

2023-06-21 04:31 UTC, dakshdeepHERE commented
Thank you @caupolicandiaz

2023-06-21 15:52 UTC, merged