Term entry sql log10
Codecademy/docs pull request #2529
Opened 2023-06-19 09:53 UTC by cslylla

### Description

- Added a new term for SQL: Math Functions - log10
-Closes #2260 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-20 00:11 UTC, CBID2 commented on content/sql/concepts/math-functions/terms/log10/log10.md
> +This example results in the following output:
[Proofreading]
```suggestion
The above example results in the following output:
```

2023-06-20 00:12 UTC, CBID2 requested changes
Hi @cslylla! :) I just gave a proofreading recommendation for your entry, so check that out to learn how to improve it. Other than that, you're off to a great start! :)

2023-06-20 20:56 UTC, caupolicandiaz requested changes
@cslylla I've added a couple of comments. Please update the entry, and tag me when you've made the changes. Thanks

2023-06-20 20:56 UTC, caupolicandiaz commented on content/sql/concepts/math-functions/terms/log10/log10.md
> +- a `float` type number greater than `0`, or
```suggestion
- A `float` type number greater than `0`.
```

2023-06-20 20:56 UTC, caupolicandiaz commented on content/sql/concepts/math-functions/terms/log10/log10.md
> +- an expression resulting in a `float` type number (e.g. `EXP(10)` or `10*10`).
```suggestion
- An expression resulting in a `float` type number (e.g. `EXP(10)` or `10*10`).
```

2023-06-22 10:15 UTC, cslylla commented
> Hi @cslylla! :) I just gave a proofreading recommendation for your entry, so check that out to learn how to improve it. Other than that, you're off to a great start! :)

Hi @CBID2, thanks for the feedback! I have just approved the suggested change! 😊

2023-06-22 10:16 UTC, cslylla commented
@caupolicandiaz I approved the changes; thank you!

2023-06-22 11:54 UTC, CBID2 approved these changes
LGTM

2023-06-22 16:18 UTC, caupolicandiaz approved these changes
@cslylla Looks good

2023-07-01 15:02 UTC, SSwiniarski approved these changes
@cslylla Looks good to merge.

2023-07-01 15:07 UTC, merged

2023-07-01 15:12 UTC, SSwiniarski commented
@cslylla Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/sql/math-functions/log10

![image](https://github.com/Codecademy/docs/assets/86081858/16501066-312d-493c-90f6-c8788dde1195)