#2406 javascript map has size codebytes
Codecademy/docs pull request #2532
Opened 2023-06-19 19:18 UTC by carlos-ds

### Description

Added Codebyte examples to the following term entries for Map in Javascript: `size` and `has`.
Closes #2406.

### Type of Change

Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-19 19:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2532) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2532) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2532) it.</sub>

2023-06-20 17:15 UTC, caupolicandiaz requested changes
@carlos-ds Just added a few comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-06-20 17:15 UTC, caupolicandiaz commented on content/javascript/concepts/map/terms/has/has.md
> +```js
```suggestion
```codebyte/js
```

2023-06-20 17:15 UTC, caupolicandiaz commented on content/javascript/concepts/map/terms/size/size.md
> +The following example maps names to the age of the corresponding person. The value of the `size` property changes after deleting a key-value pair.
```suggestion
The following example uses the `size` property to confirm the number of elements in a map after deleting a key-value pair.
```

2023-06-20 17:15 UTC, caupolicandiaz commented on content/javascript/concepts/map/terms/size/size.md
> +```js
```suggestion
```codebyte/js
```

2023-06-22 18:19 UTC, carlos-ds commented
Hi @caupolicandiaz, thanks for reviewing! I've applied the suggested changes. If there's anything else, let me know.

2023-06-22 20:10 UTC, caupolicandiaz approved these changes
@carlos-ds Looks good. This is ready for a second review.

2023-06-26 17:02 UTC, merged

2023-06-26 17:03 UTC, SSwiniarski commented
@carlos-ds Congrats on the new edits!

Live links:
- https://www.codecademy.com/resources/docs/javascript/map/size
- https://www.codecademy.com/resources/docs/javascript/map/has