[Term Entry] Go Math Functions: .Tan()
Codecademy/docs pull request #2535
Opened 2023-06-21 09:36 UTC by 4hbab

### Description

- Added the Math.Tan() term for go
- Closes issue #2442 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-21 09:55 UTC, 4hbab commented
Hi. I had some problems with the merging as i first didn't pull the cos.md file from the main branch.

2023-06-21 15:08 UTC, dakshdeepHERE commented
@4hbab can you link the issue this is fixing? Also if you don't want the other file to appear in this PR then simply copy it and delete the file from the branch or reset the commits and stash the other file. Make sure to copy the file then make a separate branch for it and add the file in that branch to push it separately.

2023-06-21 16:39 UTC, SSwiniarski requested changes
@4hbab I dis a first review and had a couple of comments. The main one of which is you need to delete the `cos.md` file from this PR.

2023-06-21 16:39 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/cos/cos.md
Please remove this file from this PR.

2023-06-21 16:39 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/tan/tan.md
> +The **`Tan()`** function returns the tangent of the given angle (in radians). The `math` library must be imported in order to use this function.
```suggestion
The **`Tan()`** function returns the tangent of an angle given in radians. The `math` library must be imported in order to use this function.
```

2023-06-21 16:39 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/tan/tan.md
> +
```suggestion
```
Remove blank line

2023-06-22 16:01 UTC, SSwiniarski commented
@4hbab I see you updated the tan.md file, but you haven't removed the cos.md file.

2023-06-22 16:03 UTC, 4hbab commented
I'm sorry. I'm relatively new to PRs and could tell me how I could remove the cos.md file please?

2023-06-22 16:50 UTC, SSwiniarski commented
@4hbab if you're working locally, simply delete the file from your repo and commit the change. If you're doing it on GitHub, just navigate to the file, then click on the three dots to the right of the filename. The last option on the list will be "Delete File".

2023-06-22 18:26 UTC, 4hbab commented
Thank you. @SSwiniarski I updated the PR and made changes the pass the automated tests.

2023-06-23 16:16 UTC, SSwiniarski approved these changes
@4hbab Looks good for a second review.

2023-06-27 17:30 UTC, caupolicandiaz approved these changes
@4hbab @SSwiniarski LGTM

2023-06-28 12:08 UTC, merged

2023-06-28 12:18 UTC, SSwiniarski commented
@4hbab Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/go/math-functions/tan

![image](https://github.com/Codecademy/docs/assets/86081858/d994a2a7-cee8-4fb7-a95e-5b7c2f1c93d5)