[Term Entry] Swift Array Term Entry: .Filter()
Codecademy/docs pull request #2543
Opened 2023-06-22 22:36 UTC by MandyDoree

### Description

- Added the Filter() term entry for Swift
- Closes Issue #2446 

### Type of Change

- Adding a new entry
- 
### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-22 22:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2543) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2543) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2543) it.</sub>

2023-06-23 17:01 UTC, SSwiniarski approved these changes
@MandyDoree Looks good to me as-is. But I wonder why you didn't use the tag you added to the `tags.md` file in your entry.

2023-06-23 21:09 UTC, caupolicandiaz requested changes
@MandyDoree I've added my suggestions. Please update the entry, and tag me when you've finished making changes. Thanks

2023-06-23 21:09 UTC, caupolicandiaz commented on content/swift/concepts/arrays/terms/filter/filter.md
> +//return all elements that start with an "A"
```suggestion
// Return all elements that start with an "A"
```

2023-06-23 21:09 UTC, caupolicandiaz commented on content/swift/concepts/arrays/terms/filter/filter.md
> +In the example above, the `.filter()` method is searching through the `names` array. All items that meet the condition of starting with `A` will be returned.
```suggestion
In the example above, the `.filter()` method is used to search through the `names` array. All items that meet the condition of starting with `A` will be returned.
```

2023-06-23 21:09 UTC, caupolicandiaz commented on content/swift/concepts/arrays/terms/filter/filter.md
> +In the example above, the `.filter()` method is searching through the `names` array. All items that meet the condition of starting with `A` will be returned.
I think it 's preferable to have this sentence above the code block on line 26

2023-06-26 19:14 UTC, MandyDoree commented
@caupolicandiaz changes can be found in #2595. I had some issues creating the request (this is my first time), so I might have made some errors here and there that causes things to not go the way I planned it. Please let me know if anything looks wrong from your side.

I couldn't assign the issue to you, so I tagged you in it.

2023-06-26 21:26 UTC, caupolicandiaz commented
@MandyDoree Why did you start a new PR? Did you have a problem making changes on this branch?

2023-06-26 21:57 UTC, MandyDoree commented
@caupolicandiaz I know how to make a new PR, but I had issues figuring out how to make changes on the current branch. Those changes mainly being I could not check if I were doing it right. So I decided to go for the solution I was most certain of. And I changed the branch name to comply with the check list.

2023-06-27 11:52 UTC, SSwiniarski commented
@MandyDoree, Closing this because of a new PR.

2023-06-27 11:52 UTC, closed without merging