[Concept Entry] Swift Errors
Codecademy/docs pull request #2544
Opened 2023-06-23 02:08 UTC by raschuh

### Description

- Added a concept entry for Swift Errors
- Closes Issue #2212 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-23 02:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2544) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2544) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2544) it.</sub>

2023-06-30 00:25 UTC, KTom101 requested changes
@raschuh I've added some changes to this.

2023-07-03 22:48 UTC, raschuh commented
@KTom101, I have directly applied your suggestions. Sorry for the multiple commits as this is my first PR.

2023-07-10 18:05 UTC, KTom101 approved these changes
@raschuh I've added a small change and ran the command `npm run format:all` to fix [the failing checks](https://www.codecademy.com/resources/docs/contribution-guide/getting-set-up-on-your-computer#:~:text=continuous%20integration%20(CI)%20workflows). This looks good otherwise 👍

2023-07-10 18:06 UTC, merged