Add str starts with
Codecademy/docs pull request #2572
Opened 2023-06-23 15:43 UTC by jopbdavid

### Description

Added new entry @  docs/content/php/concepts/string-functions/terms/str-starts-with/str-starts-with.md (Note the path uses dashes, not underscores.) - for [PHP] about the str_starts_with() function.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-23 17:08 UTC, SSwiniarski requested changes
@jopbdavid I did a first review and only had a couple of comments.

2023-06-23 17:08 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/str-starts-with/str-starts-with.md
> +Description: 'Performs a case-sensitive search to check if a string starts with a certain substring:'
```suggestion
Description: 'Performs a case-sensitive search to check if a string starts with a certain substring.'
```

2023-06-23 17:08 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/str-starts-with/str-starts-with.md
> +The `$stringstartswith` function returns true if the `$str` starts with the `$substr` or false otherwise.
```suggestion
The `str_starts_with()` function returns true if the `$str` starts with the `$substr` or false otherwise.
```

2023-06-23 20:14 UTC, jopbdavid commented on content/php/concepts/string-functions/terms/str-starts-with/str-starts-with.md
> +The `$stringstartswith` function returns true if the `$str` starts with the `$substr` or false otherwise.
nice one, didn't catch that one

2023-06-24 12:40 UTC, SSwiniarski approved these changes
@jopbdavid Looks good for a second review.

2023-06-27 20:16 UTC, caupolicandiaz approved these changes
@jopbdavid @SSwiniarski I made a few small changes. Looks good to go

2023-06-28 12:25 UTC, merged

2023-06-28 12:31 UTC, SSwiniarski commented
@jopbdavid Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/php/string-functions/str-starts-with

![image](https://github.com/Codecademy/docs/assets/86081858/6ca3b5f7-f73b-4826-8fe2-883a99cb48af)