feat: add information about good first issues
Codecademy/docs pull request #2575
Opened 2023-06-23 23:30 UTC by CBID2

### Description

- I added information about good first issues to the [GitHub Entry](https://www.codecademy.com/resources/docs/general/github). 
- Closes #2527 
### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-24 14:56 UTC, SSwiniarski requested changes
@CBID2 I did a first review and left a line-editing eomment.

2023-06-24 14:56 UTC, SSwiniarski commented on content/general/concepts/github/github.md
> +[Good First Issue](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels) is a label open source maintainers used on GitHub to categorize issues that are intende
```suggestion
["Good First Issue"](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels) is a label open source maintainers used on GitHub to categorize issues that are intended for people who have either never made an open source contribution before or are new to their project. It also signifies to maintainers that extra assistance is needed when reviewing a new contributor's pull request, whether it's introducing the contributing guidelines or providing in-line comments on lines of code that need revision. "Good First Issue" is also a list of repositories that contain beginner-level issues in the [topics section of GitHub](https://github.com/topics/good-first-issue).
```

2023-06-24 14:57 UTC, CBID2 commented
> @CBID2 I did a first review and left a line-editing eomment.

Changes made @SSwiniarski! :)

2023-06-24 15:34 UTC, SSwiniarski approved these changes
@CBID2 I did one more slight edit and it looks good for a second review.

2023-06-24 15:35 UTC, CBID2 commented
> @CBID2 I did one more slight edit and it looks good for a second review.

Great @SSwiniarski. Can you review the one I did on URL Slugs?

2023-07-16 21:41 UTC, KTom101 requested changes
@CBID2 Added feedback.

2023-07-16 21:42 UTC, CBID2 commented
> @CBID2 Added feedback.

Done @KTom101.

2023-07-16 21:59 UTC, KTom101 approved these changes
@CBID2 Thank you 👍

2023-07-16 21:59 UTC, merged

2023-07-16 22:01 UTC, KTom101 commented
@CBID2 Changes are live: https://www.codecademy.com/resources/docs/general/github 🎉

cc @yangc95

2023-07-16 22:05 UTC, CBID2 commented
> @CBID2 Changes are live: https://www.codecademy.com/resources/docs/general/github 🎉
> 
> 
> 
> cc @yangc95 

Thanks @KTom101! :) Now I just need an approval rating on PR #2720

2023-07-16 22:11 UTC, KTom101 commented
@CBID2 Looks like @yangc95 is already on it 🔥 Thanks for your patience on these approvals!

2023-07-16 22:18 UTC, CBID2 commented
> @CBID2 Looks like @yangc95 is already on it 🔥 Thanks for your patience on these approvals!

You're welcome @KTom101. I was hoping you'd merge it though

2023-07-16 22:25 UTC, KTom101 commented
@CBID2 Sorry! @yangc95 may have changes already pending on their end. Please give it some more time 🙂

2023-07-16 22:31 UTC, CBID2 commented
> @CBID2 Sorry! @yangc95 may have changes already pending on their end. Please give it some more time 🙂

Ohh ok