Update count.md
Codecademy/docs pull request #2577
Opened 2023-06-24 04:07 UTC by isradin93

1) Fixed Python List.count() method Syntax.
2) Example 2 has TypeError; Replaced with new Example.

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-24 15:46 UTC, SSwiniarski requested changes
@isradin93, I did a first review and had one comment. We generally prefer output from examples in a separate block.

2023-06-24 15:46 UTC, SSwiniarski commented on content/python/concepts/lists/terms/count/count.md
> +# 51 occurred 1 time in the list.
````suggestion
```

This results in the following output:

```shell
77 occurred 2 times in the list. 
99 occurred 3 times in the list. 
51 occurred 1 time in the list.
````

2023-07-08 19:34 UTC, SSwiniarski approved these changes
@isradin93 in the interest of getting this moving after a few weeks I implemented my suggestion and I'm passing this off to a second review.

2023-07-17 17:52 UTC, KTom101 requested changes
@isradin93 I added a second review. Let me know if you have questions about making the changes!

2023-08-08 12:48 UTC, KTom101 commented
@isradin93 Closing this due to unresponsiveness, a new PR was made to fix the error.

2023-08-08 12:48 UTC, closed without merging