[Term Entry] PHP String Function: str_pad()
Codecademy/docs pull request #2578
Opened 2023-06-24 05:30 UTC by phuongtrieu97coder

### Description

- Added the str_pad() term for PHP
- Closes issue #2434 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-24 05:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2578) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2578) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2578) it.</sub>

2023-06-24 18:15 UTC, KTom101 requested changes
@phuongtrieu97coder I've done a first review and added some changes to this.

2023-06-29 02:35 UTC, KTom101 approved these changes
@phuongtrieu97coder Thanks for making the changes. All you have to do is wait for another reviewer for a 2nd review.

2023-06-29 16:47 UTC, SSwiniarski requested changes
@phuongtrieu97coder I did a second review and left a few comments.

2023-06-29 16:47 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/str-pad/str-pad.md
> +The `str_pad()` function has four required parameters:
```suggestion
The `str_pad()` function has two required parameters and two optional parameters:
```

2023-06-30 16:07 UTC, SSwiniarski approved these changes
@phuongtrieu97coder I did one more edit. Looks ready to merge.

2023-06-30 16:14 UTC, merged

2023-06-30 16:23 UTC, SSwiniarski commented
@phuongtrieu97coder Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/php/string-functions/str-pad

![image](https://github.com/Codecademy/docs/assets/86081858/80025cda-4a15-456e-b837-68f9ec7b28fd)