ASIN() in sql
Codecademy/docs pull request #2582
Opened 2023-06-24 12:07 UTC by arisdelacruz

### Description

**I drafted, for review,  a write-up on the _ASIN()_ function in _SQL_ when I was granted the permission to do it. Motivation emanates from the Codecademy lesson that I am currently taking on Github and its operations.**

### Type of Change

- Adding a new entry

### Checklist

- [ / ] All writings are my own.
- [ / ] My entry follows the Codecademy Docs style guide.
- [ / ] My changes generate no new warnings.
- [ / ] I have performed a self-review of my own writing and code.
- [ / ] I have checked my entry and corrected any misspellings.
- [ / ] I have made corresponding changes to the documentation if needed.
- [ / ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ / ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ / ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-24 12:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2582) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2582) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2582) it.</sub>

2023-06-24 17:57 UTC, SSwiniarski requested changes
@arisdelacruz I did a first review and left a few comments.

2023-06-24 17:57 UTC, SSwiniarski commented on content/sql/concepts/math-functions/terms/asin/asin.md
> +The **`ASIN()`** function in SQL is a mathematical function that returns the sine of an angle.
```suggestion
The **`ASIN()`** function in SQL is a mathematical function that returns the  inverse sine of a number.  
```

2023-06-24 17:57 UTC, SSwiniarski commented on content/sql/concepts/math-functions/terms/asin/asin.md
> +```
````suggestion
```pseudo
ASIN(number)
```
````
SELECT is not part of the syntax, and we generally place syntax blocks in a ` ```pseudo ` block.

2023-06-24 17:57 UTC, SSwiniarski commented on content/sql/concepts/math-functions/terms/asin/asin.md
> +The specified number must be between -1 to 1, otherwise this function returns NULL.
```suggestion
The specified number must be between -1 to 1, otherwise this function returns `NULL`.
```

2023-06-24 17:57 UTC, SSwiniarski commented on content/sql/concepts/math-functions/terms/asin/asin.md
> +The `ASIN()` function is used to calculate the arcsine as the output_number:
```suggestion
The `ASIN()` function is used to calculate the arcsine as `output_number`:
```

2023-06-24 17:57 UTC, SSwiniarski commented on content/sql/concepts/math-functions/terms/asin/asin.md
> +
```suggestion
```
Delete this line as it is somewhat redundant with the note.

2023-06-24 23:05 UTC, arisdelacruz commented
> @arisdelacruz I did a first review and left a few comments.

@SSwiniarski big thanks

2023-06-25 14:07 UTC, SSwiniarski approved these changes
@arisdelacruz  I did two minor edits and it looks good for a second review.

2023-06-26 02:57 UTC, arisdelacruz commented
> @arisdelacruz I did two minor edits and it looks good for a second review.

@SSwiniarski big thanks again

Sorry, is there anything that I need to do from my end

pls advise, thanks

2023-06-26 23:58 UTC, arisdelacruz commented
Noted this.

Big thanks

2023-06-27 19:58 UTC, caupolicandiaz approved these changes
@arisdelacruz @SSwiniarski I made a couple of minor edits. Looks good to merge.

2023-06-28 00:44 UTC, arisdelacruz commented
> @arisdelacruz @SSwiniarski I made a couple of minor edits. Looks good to merge.

@SSwiniarski @caupolicandiaz big thanks, guys

2023-06-28 12:35 UTC, merged