Go math ceil
Codecademy/docs pull request #2590
Opened 2023-06-25 20:53 UTC by Nessvah

### Description

Closes issue #2438

I have created a new entry about the Go Ceil math function on a new folder and a new file called ceil.md on the go math functions directory.

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-26 00:50 UTC, CBID2 commented on content/go/concepts/math-functions/terms/ceil/ceil.md
> +- When passing `Ceil(±0)` the returned value will be exactly the same as the argument.
[Typo]
```suggestion
- When passing `Ceil(±Inf)`, the returned value will be the same as the argument.
- When passing `Ceil(Nan)`, the returned value will be also `Nan`.
- When passing `Ceil(±0)`, the returned value will be exactly the same as the argument.
```

2023-06-26 00:53 UTC, CBID2 requested changes
Hi @Nessvah! :) I pointed out some typos that could be improved. Other than that, you're off to a good start! :)

2023-06-27 08:22 UTC, Nessvah commented
> Hi @Nessvah! :) I pointed out some typos that could be improved. Other than that, you're off to a good start! :)

Thank you! I'll be working on it asap.

2023-06-27 15:54 UTC, SSwiniarski requested changes
@Nessvah I did a first review and left a few comments.

2023-06-27 15:54 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/ceil/ceil.md
> +The `Cei()` function receives a value of type `float64` and returns a single value of the same type. This returned value is the argument rounded to the nearest integer.
```suggestion
The `Cei()` function receives a value of type `float64` and returns a single value of the same type. This returned value is the next highest integer equal to or greater than the argument.
```

2023-06-27 15:54 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/ceil/ceil.md
> +```golang
````suggestion
```codebyte/golang
````

2023-06-27 15:54 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/ceil/ceil.md
> +Below is a simple example where the result will be the score, rounded up to the nearest integer.
```suggestion
Below is a simple example where the result will be the score, rounded up to the next highest integer.
```

2023-06-27 15:54 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/ceil/ceil.md
> +Description: 'Returns the rounded up value of a given decimal number.'
```suggestion
Description: 'Returns a given decimal number rounded up to the next highest integer.'
```

2023-06-27 15:54 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/ceil/ceil.md
> +The **Ceil()** function returns the rounded up value of a given decimal number.
```suggestion
The **Ceil()** function returns a given decimal number rounded up to the next highest integer.
```

2023-06-30 15:21 UTC, Nessvah commented
@SSwiniarski Hi! I applied the suggested changes. Let me know if there is anything else that I can improve on this.

2023-06-30 16:25 UTC, SSwiniarski approved these changes
@Nessvah Looks good for a second maintainer review.

2023-07-03 22:17 UTC, caupolicandiaz requested changes
@Nessvah I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-03 22:17 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/ceil/ceil.md
> +The **Ceil()** function returns a given decimal number rounded up to the next highest integer.
```suggestion
The **`Ceil()`** function returns a given decimal number rounded up to the next highest integer.
```

2023-07-03 22:17 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/ceil/ceil.md
> +The `Cei()` function receives a value of type `float64` and returns a single value of the same type. This returned value is the next highest integer equal to or greater than the argument.
```suggestion
The `Ceil()` function receives a value of type `float64` and returns a single value of the same type. This returned value is the next highest integer equal to or greater than the argument.
```

2023-07-03 22:17 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/ceil/ceil.md
> +Below is a simple example where the result will be the score, rounded up to the next highest integer.
```suggestion
```

2023-07-03 22:17 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/ceil/ceil.md
> +    "math"
```suggestion
    "math"  // Required
```

2023-07-03 22:17 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/ceil/ceil.md
> +
There should be a line such as "The output is as follows:" and a shell block with the output

2023-07-09 20:10 UTC, Nessvah commented
@caupolicandiaz hi! Sorry, I took too long to reply. The changes are already in place but since I was busy this past week with a presentation, I forgot to push it!  I'll be doing it later today!

2023-07-10 16:18 UTC, caupolicandiaz approved these changes
@Nessvah Looks good to go.

2023-07-10 16:20 UTC, merged

2023-07-11 15:43 UTC, SSwiniarski commented
@Nessvah Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/go/math-functions/ceil

![image](https://github.com/Codecademy/docs/assets/86081858/005a66eb-a990-4015-9790-0c04df4a4e4a)