Python format() built-in-function entry
Codecademy/docs pull request #2592
Opened 2023-06-26 16:37 UTC by David-OC17

### Description

This pull request is for the integration of a new entry for the Python built-in format() function. This is for the built-in format() function, not the string .format().

### Type of Change

- Adding a new entry

### Linked issue
Closes #2525

2023-06-26 17:06 UTC, dakshdeepHERE requested changes
Few changes from my side

2023-06-26 17:28 UTC, dakshdeepHERE requested changes

2023-06-26 17:28 UTC, dakshdeepHERE commented on content/python/concepts/built-in-functions/terms/format/format.md
> +
```suggestion

```python
pi = 3.14159
formatted = format(pi, '.2f')
print(formatted)
```

```

2023-06-26 17:28 UTC, dakshdeepHERE commented on content/python/concepts/built-in-functions/terms/format/format.md
> +
```suggestion
Output for above code is:

```shell
3.14
```

```

2023-06-26 17:28 UTC, dakshdeepHERE commented on content/python/concepts/built-in-functions/terms/format/format.md
> +
```suggestion

```python
value = 42
formatted = format(value, 'b')  # Format value as binary
print(formatted)
```

```

2023-06-26 17:28 UTC, dakshdeepHERE commented on content/python/concepts/built-in-functions/terms/format/format.md
> +101010
```suggestion
Output for the above code is:
```shell
101010
```

```

2023-06-26 17:29 UTC, dakshdeepHERE commented
@David-OC17 Try to use tags with each code snippets. Please read [guide](https://www.codecademy.com/resources/docs/contribution-guide).

2023-07-01 21:53 UTC, David-OC17 commented
I just committed the changes requested by @dakshdeepHERE

2023-07-03 16:05 UTC, dakshdeepHERE commented
> I just committed the changes requested by @dakshdeepHERE

Awsm tag the maintainers now for further reviews. :)

2023-07-03 16:09 UTC, dakshdeepHERE requested changes
Few more changes @David-OC17

2023-07-03 16:09 UTC, dakshdeepHERE commented on content/python/concepts/built-in-functions/terms/format/format.md
> +## Codebyte Example (if applicable)
```suggestion
## Codebyte Example
```

2023-07-03 16:09 UTC, dakshdeepHERE commented on content/python/concepts/built-in-functions/terms/format/format.md
> +```python
```suggestion
```codebyte/python
```

2023-07-03 16:09 UTC, dakshdeepHERE commented on content/python/concepts/built-in-functions/terms/format/format.md
> +```
```suggestion
```
no need to attach output section for codebyte

2023-07-03 16:09 UTC, dakshdeepHERE commented on content/python/concepts/built-in-functions/terms/format/format.md
> +formatted = format(value, 'b')  # Format value as binary
```suggestion
formatted = format(value, 'b')  
```
no comments in codebytes

2023-07-03 16:09 UTC, dakshdeepHERE commented on content/python/concepts/built-in-functions/terms/format/format.md
> +
```suggestion

format(value, format_specification)

```

please write syntax snippet like this:
<img width="311" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/a0b27b3e-6d36-4b8c-81c7-85717abe468c">

2023-08-16 14:39 UTC, SSwiniarski requested changes
@David-OC17 In the interest of moving this along, I implemented the last of @dakshdeepHERE's suggestions and did a first maintainer review.

2023-08-16 14:39 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/format/format.md
> +Description: The format() function in Python is a built-in function that is used to format different types of objects into strings.
```suggestion
Description: 'Used to format different types of objects into strings.'
```

2023-08-16 14:39 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/format/format.md
> +  - 'An nth subject name'
```suggestion
Subjects:
  - 'Computer Science'
```

2023-08-16 14:39 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/format/format.md
> +  - 'learn-git-&-github'
```suggestion
CatalogContent:
- 'learn-python-3'
- 'paths/computer-science'
```

2023-08-16 14:39 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/format/format.md
> +The **format()** function returns a string from an input value, formatted to the specified specifications.
```suggestion
The **format()** function returns a string from an input value, formatted to the provided specifications.
```

2023-08-16 14:39 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/format/format.md
> +
```suggestion
Need a sentence explaining the syntax and an explanation of at least some format specifications.
```

2023-08-16 14:39 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/format/format.md
> +
```suggestion
```
Remove trailing blank line.

2023-09-10 18:26 UTC, SSwiniarski approved these changes
@David-OC17 I did the updates myself to move this along. I'm now sending it for a second review.

2023-09-11 21:13 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/format/format.md
> +The **format()** function returns a string from an input value, formatted to the provided specifications.
```suggestion
The **`format()`** function returns a string from an input value, formatted to the provided specifications.
```

2023-09-11 21:13 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/format/format.md
> +| b         | Binary format.                         |
```suggestion
| `b`         | Binary format                         |
```

2023-09-13 16:18 UTC, SSwiniarski commented
@caupolicandiaz I went ahead and implemented your suggestions. Do we look good to merge?

2023-09-13 17:06 UTC, caupolicandiaz approved these changes
@David-OC17 @SSwiniarski LGTM

2023-09-13 18:15 UTC, David-OC17 commented
Looks good to merge. Just started merge of main-->this branch, in order to be up-to-date, and later merge the these changes back to main.

2023-09-14 11:02 UTC, merged