[Term Entry] PHP Math Functions rad2deg()
Codecademy/docs pull request #2596
Opened 2023-06-26 23:42 UTC by alexflightlessbird

### Description

Closes Issue: #2274 
Created rad2deg folder in PHP terms and added rad2deg.md 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-26 23:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2596) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2596) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2596) it.</sub>

2023-06-27 13:55 UTC, dakshdeepHERE requested changes
Few changes from my side

2023-06-27 13:55 UTC, dakshdeepHERE commented on content/php/concepts/math-functions/terms/rad2deg/rad2deg.md
> +## Example
```suggestion
## Example

```

2023-06-27 13:55 UTC, dakshdeepHERE commented on content/php/concepts/math-functions/terms/rad2deg/rad2deg.md
> +## Codebyte Example
```suggestion
## Codebyte Example

```

2023-06-27 13:55 UTC, dakshdeepHERE commented on content/php/concepts/math-functions/terms/rad2deg/rad2deg.md
> +This example results in the following output:
```suggestion
This example results in the following output:

```

2023-06-27 13:55 UTC, dakshdeepHERE commented on content/php/concepts/math-functions/terms/rad2deg/rad2deg.md
> +The value returned by the function is a `float` type and is the equivalent of `number` in degrees.
```suggestion
Where `number` is the radian value to convert to degrees. The value returned by the function is a `float` type and is the equivalent of `number` in degrees.
```

2023-06-27 19:23 UTC, alexflightlessbird commented
@SSwiniarski comments have been reviewed and applied!

2023-06-28 12:22 UTC, SSwiniarski approved these changes
@alexflightlessbird I made one small edit and now it looks good for a second review.

2023-06-28 19:16 UTC, caupolicandiaz approved these changes
@alexflightlessbird @SSwiniarski Looks good to merge

2023-06-29 12:17 UTC, merged