New entry for docs repository "setUTCFullYear"
Codecademy/docs pull request #2606
Opened 2023-06-28 01:29 UTC by Beto-Garcia

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-28 01:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2606) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2606) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2606) it.</sub>

2023-06-28 08:09 UTC, dakshdeepHERE requested changes
Some changes from my side @Beto-Garcia :)

2023-06-28 08:09 UTC, dakshdeepHERE commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +```
```suggestion
```pseudo 
```

2023-06-28 08:09 UTC, dakshdeepHERE commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +# Date.prototype.setUTCFullYear()
```suggestion
## Date.prototype.setUTCFullYear()
```

2023-06-28 08:09 UTC, dakshdeepHERE commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +### Parameters
```suggestion
## Parameters
```

2023-06-28 08:09 UTC, dakshdeepHERE commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +### Return value
```suggestion
## Return value
```

2023-06-28 08:09 UTC, dakshdeepHERE commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +### Description
```suggestion
## Description
```

2023-06-28 08:09 UTC, dakshdeepHERE commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +### Examples
```suggestion
## Examples
```

2023-06-28 08:09 UTC, dakshdeepHERE commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +If a parameter you specify is outside of the expected range, `setUTCFullYear()` attempts to update the other parameters and the date information in the *`Date`* object accordingly. For example, if yo
```suggestion
If the `monthValue` and `dateValue` parameters are not specified, the values returned from the *`getUTCMonth()`* and *`getUTCDate()`* methods are used.

If a parameter specified is outside of the expected range, `setUTCFullYear()` attempts to update the other parameters and the date information in the *`Date`* object accordingly. For example, if 15 is specified for `monthValue`, the year is incremented by 1 (`yearValue + 1`), and 3 is used for the month.
```
We don't use pronouns in docs contributions

2023-06-28 08:09 UTC, dakshdeepHERE commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +```
```suggestion
```shell
```

2023-06-28 08:09 UTC, dakshdeepHERE commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +Using `setUTCFullYear()`
```suggestion
Using `setUTCFullYear()`:
```

2023-06-28 08:09 UTC, dakshdeepHERE commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +Description: 'setUTCFullYear() method of Date instances'
```suggestion
Description: 'Used to set the year value of a Date object in UTC (Coordinated Universal Time)'
```
Description should be small and descriptive explanation of what the function will does.

2023-06-29 16:31 UTC, SSwiniarski commented
@Beto-Garcia tag me once you address @dakshdeepHERE's comments and I will do a first maintainer review.

2023-08-10 16:22 UTC, SSwiniarski requested changes
@Beto-Garcia I committed all of @dakshdeepHERE's comments to get this moving. I did a first maintainer review and left a few comments.

2023-08-10 16:22 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +  - 'docs/content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md'
```suggestion
Tags:
  - 'Date'
  - 'Methods'
CatalogContent:
  - 'introduction-to-javascript'
  - 'paths/front-end-engineer-career-path'
```

2023-08-10 16:22 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +
```suggestion
```
No leading header, the title in the metadata provides that.

2023-08-10 16:22 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +The **`setUTCFullYear()`** method of `Date` instances changes the year for this date according to universal time.
```suggestion
The **`setUTCFullYear()`** method of `Date` instances changes the year for the date according to UTC (Coordinated Universal Time).
```

2023-08-10 16:22 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +Description: 'Used to set the year value of a Date object in UTC (Coordinated Universal Time)'
```suggestion
Description: 'Used to set the year value of a Date object in UTC (Coordinated Universal Time).'
```

2023-08-10 16:22 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +## Parameters
```suggestion
Parameters:
```

2023-08-10 16:22 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +- An integer between 1 and 31 representing the day of the month. If you specify dateValue, you must also specify monthValue.
```suggestion
- `yearValue`: An integer representing the year. For example, 1995.
- `monthValue`: (Optional) An integer representing the month: 0 for January, 1 for February, and so on.
- `dateValue`: (Optional) An integer between 1 and 31 representing the day of the month. If `dateValue` is specified, `monthValue` must also be specified.
```
No first- or second-person pronouns in Docs.

2023-08-10 16:22 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +If a parameter specified is outside of the expected range, `setUTCFullYear()` attempts to update the other parameters and the date information in the *`Date`* object accordingly. For example, if 15 i
```suggestion
If the `monthValue` and `dateValue` parameters are not specified, the values returned from the `getUTCMonth()` and `getUTCDate()` methods are used.

> **Note:** If a parameter specified is outside of the expected range, `setUTCFullYear()` attempts to update the other parameters and the date information in the `Date` object accordingly. For example, if 15 is specified for `monthValue`, the year is incremented by 1 (`yearValue + 1`), and 3 is used for the month.
```

2023-08-10 16:22 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setUTCFullYear/setUTCFullYear.md
> +```
````suggestion

## Example

Using `setUTCFullYear()`:

```shell
const theBigDay = new Date('2023-03-01');
theBigDay.setUTCFullYear(1997);
console.log(theBigDay);
```

This code will output the following:

```shell
1997-03-01T00:00:00.000Z
```
````

2023-08-31 16:33 UTC, SSwiniarski approved these changes
@Beto-Garcia In the interest of getting this moving, I implemented all my suggestions so this is ready for a second review.

2023-08-31 17:00 UTC, caupolicandiaz approved these changes
@Beto-Garcia @SSwiniarski Just made a few formatting edits. Looks good to merge

2023-09-01 11:02 UTC, merged