Edit variable names and literals
Codecademy/docs pull request #261
Opened 2021-09-29 03:26 UTC by yangc95

### Description

### Type of Change

- [ ] Adding a new entry
- [x] Editing an existing entry (fixing a typo, bug, issues, etc)
- [ ] Updating the documentation

### Checklist

- [x] My entry follows the Codecademy Docs style guide
- [ ] I have performed a self-review of my own writing and code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have checked my entry and corrected any misspellings
- [x] I have confirmed my changes are not being pushed from my forked `main` branch
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making
- [ ] All writings are my own

2021-10-01 03:01 UTC, EugeneGohh approved these changes
LGTM.

2021-10-02 03:21 UTC, Dusch4593 approved these changes
LGTM!

2021-10-04 21:11 UTC, sonnynomnom requested changes

2021-10-04 21:11 UTC, sonnynomnom commented on content/javascript/concepts/arrays/terms/valueOf/valueOf.md
> +Returns the value of all the elements of the original array.
The `Description` metadata can start with the verb. 

For these though, let's do:

The `.valueOf()` method returns the value of all the elements of the original array.

2021-10-04 21:11 UTC, sonnynomnom commented on content/javascript/concepts/arrays/terms/valueOf/valueOf.md
> +**Note:** This method will not change the original array. However, if the original array or the variable which holds it (via the `valueOf` method) is manipulated, the value of the array will change a
(using the `.valueOf()` method)

2021-10-04 21:11 UTC, sonnynomnom commented on package.json
> +    "@codecademy/eslint-config": "^3.1.0",
This file shouldn't be changed, right?

2021-10-04 21:27 UTC, yangc95 commented on package.json
> +    "@codecademy/eslint-config": "^3.1.0",
removed (along with the yarn file)!

2021-10-04 21:35 UTC, sonnynomnom approved these changes

2021-10-04 21:35 UTC, merged

2021-10-04 21:36 UTC, sonnynomnom commented
merged!

2021-10-04 21:37 UTC, sonnynomnom commented
Made two tiny changes: 

https://github.com/Codecademy/docs/commit/aa57adcda872e6599656860dc1558a728fa6d526