[Term Entry] Swift Arrays .randomElement() #2561
Codecademy/docs pull request #2610
Opened 2023-06-29 02:32 UTC by bruce0221

### Description

Create a term entry for Swfit Arrays `.randomElement()`, which is issue #2561 .

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-29 02:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2610) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2610) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2610) it.</sub>

2023-06-29 16:13 UTC, caupolicandiaz requested changes
@bruce0221 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-06-29 16:13 UTC, caupolicandiaz commented on content/swift/concepts/arrays/terms/randomElement/randomElement.md
> +Description: 'Returns a random element from of arrary.'
```suggestion
Description: 'Returns a random element from an array.'
```

2023-06-29 16:13 UTC, caupolicandiaz commented on content/swift/concepts/arrays/terms/randomElement/randomElement.md
> +The ** `.randomElement()` method will randomly return an element from an  array. If the array is empty, it will return nil.
```suggestion
The ** `.randomElement()`** method will randomly return an element from an array. If the array is empty, it will return `nil`.
```

2023-06-29 16:13 UTC, caupolicandiaz commented on content/swift/concepts/arrays/terms/randomElement/randomElement.md
> +
```suggestion
```

2023-06-29 16:13 UTC, caupolicandiaz commented on content/swift/concepts/arrays/terms/randomElement/randomElement.md
> +
Generally we try to include a sentence or two after the syntax block explaining the parameters, or functionality of the method, etc

2023-06-29 16:13 UTC, caupolicandiaz commented on content/swift/concepts/arrays/terms/randomElement/randomElement.md
> +The output will be:
```suggestion
The output will be similar to:
```

2023-07-01 02:29 UTC, bruce0221 commented
@caupolicandiaz , the entry is revised.

2023-07-01 20:29 UTC, caupolicandiaz approved these changes
@bruce0221 I've gone ahead and made a few small edits. This is ready for a second review.

2023-07-02 02:21 UTC, bruce0221 commented
@caupolicandiaz  thank you. 
I need to wait for the second reviewer's approval, then I can merge the new branch into main branch, correct ?

2023-07-03 19:43 UTC, caupolicandiaz commented
> @caupolicandiaz thank you.
> I need to wait for the second reviewer's approval, then I can merge the new branch into main branch, correct ?

Merging is done by the maintainers. The only work left, potentially, is addressing any comments in a second review.

2023-07-08 16:11 UTC, SSwiniarski approved these changes
@bruce0221 looks good to merge.

2023-07-08 16:13 UTC, merged

2023-07-08 16:19 UTC, SSwiniarski commented
@bruce0221 Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/swift/arrays/randomElement

![image](https://github.com/Codecademy/docs/assets/86081858/04b15b65-fb91-41ab-8117-f0bf821d1c84)

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.