[CLOSES] Issue#2431 Term Entry: JavaScript Dates .setMilliseconds()
Codecademy/docs pull request #2615
Opened 2023-06-29 18:43 UTC by Yashi11

### Description

A new term entry for JavaScript [Dates](https://www.codecademy.com/resources/docs/javascript/dates) about the .setMilliseconds() method in a new file in docs/content/javascript/concepts/dates/terms/setMilliseconds/setMilliseconds.md with an introductory paragraph about what the method is and does , an example showing the method in use and others as per the requirement.

### Type of Change
- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-06-30 05:47 UTC, dakshdeepHERE requested changes
few changes from my side

2023-06-30 05:47 UTC, dakshdeepHERE commented on content/javascript/concepts/dates/terms/setMilliseconds/setMilliseconds.md
> +To set the millisecond value of given date to 421 :
```suggestion
To set the millisecond value of given date to 421:
```

2023-06-30 05:47 UTC, dakshdeepHERE commented on content/javascript/concepts/dates/terms/setMilliseconds/setMilliseconds.md
> +The example below is runnable, and first, it defines `eventDate` with given date and time, then the millisecond value of `eventDate` is changed to 112 milliseconds in future. Lastly, a `console.log`
```suggestion
The example below is runnable and demonstrates how to define `eventDate` with a given date and time. It then modifies the millisecond value of `eventDate` to be 112 milliseconds in the future. Finally, a `console.log` call prints the updated value of `eventDate` to the screen:
```

2023-06-30 17:50 UTC, SSwiniarski commented
@Yashi11 tag me when you've addressed @dakshdeepHERE's suggestions and I will do a first maintainer review.

2023-07-04 07:56 UTC, Yashi11 commented
> @Yashi11 tag me when you've addressed @dakshdeepHERE's suggestions and I will do a first maintainer review.

@SSwiniarski done with the requested changes 👍

2023-07-04 13:10 UTC, SSwiniarski requested changes
@Yashi11 I did a review and had two comments.

2023-07-04 13:10 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setMilliseconds/setMilliseconds.md
> +Above code changes millisecond of `dateObject` to n, which is an integer between 1 and 999.
```suggestion
Above code changes millisecond of `dateObject` to `n`, which is an integer between 1 and 999.
```

2023-07-04 13:10 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setMilliseconds/setMilliseconds.md
> +## Codebyte Example
This codebyte is exactly the same as the example. Can we rewrite it so it's different, at least by using the current date.

2023-08-10 17:31 UTC, caupolicandiaz approved these changes
@Yashi11 @SSwiniarski Just pushed a few minor edits. Looks good to merge

2023-08-11 11:25 UTC, merged