Adding Selection-Sort.md in Algorithm folder
Codecademy/docs pull request #2635
Opened 2023-06-30 17:14 UTC by dakshdeepHERE

### Description

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

Fixes #2616

2023-06-30 17:15 UTC, dakshdeepHERE commented
I've first time made a graphical representation if there's any changes required in that picture I can change it.

2023-07-04 03:48 UTC, KTom101 requested changes
@dakshdeepHERE I've left a few comments for you.

2023-07-04 07:07 UTC, dakshdeepHERE commented on content/general/concepts/algorithm/terms/selection-sort/selection-sort.jpg
Hey please suggest a background colour and the font name I could use. 


> with the word "start" above the box?

Sure

2023-07-04 17:28 UTC, dakshdeepHERE commented on content/general/concepts/algorithm/terms/selection-sort/selection-sort.jpg
@KTom101

2023-07-05 09:57 UTC, dakshdeepHERE commented
@KTom101 Check now please

2023-07-05 17:01 UTC, dakshdeepHERE commented
I've added a new picture and removed the older one @KTom101

2023-07-05 17:54 UTC, KTom101 approved these changes
@dakshdeepHERE I'll pass this on to a second review.

2023-07-05 18:01 UTC, dakshdeepHERE commented
@KTom101 thanks

2023-07-10 15:32 UTC, dakshdeepHERE commented
@SSwiniarski @yangc95 @HishamT @caupolicandiaz can anyone do the second review for this entry please.

2023-07-11 23:18 UTC, caupolicandiaz requested changes
@dakshdeepHERE I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-11 23:18 UTC, caupolicandiaz commented on content/general/concepts/algorithm/terms/selection-sort/selection-sort.md
> +![Selection Sort](SelectionSort.png)
You need to move the image to the folder below and use this address in the parentheses

https://raw.githubusercontent.com/Codecademy/docs/main/media/SelectionSort.png

2023-07-11 23:18 UTC, caupolicandiaz commented on content/general/concepts/algorithm/terms/selection-sort/selection-sort.md
> +A brief explanation of `Selection Sort`:
```suggestion
A brief explanation of the selection sort algorithm:
```

2023-07-11 23:18 UTC, caupolicandiaz commented on content/general/concepts/algorithm/terms/selection-sort/selection-sort.md
> +- It swaps the selected element with the first unsorted element: Once the minimum (or maximum) element is identified, selection sort swaps it with the first element of the unsorted subarray. This act
```suggestion
- It swaps the selected element with the first unsorted element: Once the minimum (or maximum) element is identified, selection sort swaps it with the first element of the unsorted subarray. This action effectively expands the sorted subarray by one element and reduces the unsorted subarray by one.
```

2023-07-11 23:18 UTC, caupolicandiaz commented on content/general/concepts/algorithm/terms/selection-sort/selection-sort.md
> +
It would be helpful to also include the big O time complexity of the algorithm

2023-07-11 23:18 UTC, caupolicandiaz commented on content/general/concepts/algorithm/terms/selection-sort/selection-sort.md
> +The `selectionSort` method in the code takes an integer `array` as input and performs the selection sort algorithm on it. It initializes a variable `n` with the length of the array. The outer loop it
```suggestion
The `selectionSort` function in the code takes an integer `array` as input and initializes a variable `n` with the length of the array. The outer loop iterates through the elements from the first to the second-to-last element of the array, representing the boundary of the unsorted subarray.
```

2023-07-12 20:03 UTC, caupolicandiaz approved these changes
@dakshdeepHERE @KTom101 I just made a couple of formatting edits, otherwise looks good to go.

2023-07-13 16:01 UTC, merged