[Term Entry] Go string function contains
Codecademy/docs pull request #2637
Opened 2023-07-01 11:31 UTC by Manikanta528

### Description

Addressing issue #2631 

### Type of Change

- Adding a new entry Go string function contains

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-01 13:50 UTC, SSwiniarski requested changes
@Manikanta528 I did a first review and had one comment.

2023-07-01 13:50 UTC, SSwiniarski commented on content/go/concepts/strings/terms/contains/contains.md
> +Where `str` is the original string and `sub_str` is the substring that we wanted to check against the original string.
```suggestion
Where `str` is the original string and `sub_str` is the substring to check against the original string.
```
Avoid first- and second-person pronouns.

2023-07-01 14:15 UTC, Manikanta528 commented
@SSwiniarski updated the requested changes

2023-07-01 14:24 UTC, SSwiniarski approved these changes
@Manikanta528 looks good for a second review.

2023-07-03 22:31 UTC, caupolicandiaz approved these changes
@Manikanta528 @SSwiniarski I just made a couple of minor edits. Looks good to merge

2023-07-04 12:43 UTC, merged

2023-07-04 12:58 UTC, SSwiniarski commented
@Manikanta528 congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/go/strings/contains

![image](https://github.com/Codecademy/docs/assets/86081858/39f938e4-fc1b-489d-a4c2-24382337abfd)