[Term Entry] PHP Arrays array_pop()_07/02/2023_9::PM
Codecademy/docs pull request #2653
Opened 2023-07-03 04:31 UTC by phuongtrieu97coder

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-05 21:35 UTC, caupolicandiaz requested changes
@phuongtrieu97coder I've added a few comments. Please update the entry, and tag me when you've finished making the changes. Thanks

2023-07-05 21:35 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-pop/array-pop.md
> +Description: 'Removes the last element of an array, and returns the new number of element values in the array. If the specified array is empty, null will be returned.'
```suggestion
Description: 'Removes the last element of an array.'
```

2023-07-05 21:35 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-pop/array-pop.md
> +  - 'Web Development'
```suggestion
```

2023-07-05 21:35 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-pop/array-pop.md
> +  - 'Web Development'
we limit subjects to two items

2023-07-05 21:35 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-pop/array-pop.md
> +The following example uses the `array_pop()` function to remove `"Mexico"` element value from the indexed array `$countries`:
```suggestion
The following example uses the `array_pop()` function to remove `"Mexico"` from the array `$countries`:
```

2023-07-06 16:27 UTC, caupolicandiaz approved these changes
@phuongtrieu97coder I made a couple of additional edits. This is ready for a second review.

2023-07-08 15:57 UTC, SSwiniarski approved these changes
@phuongtrieu97coder Looks good to merge.

2023-07-08 15:59 UTC, merged

2023-07-08 16:01 UTC, SSwiniarski commented
@phuongtrieu97coder Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/php/arrays/array-pop

![image](https://github.com/Codecademy/docs/assets/86081858/ca3ee1cf-9a82-47c8-a9f1-eec4d1786a76)