Str ends with
Codecademy/docs pull request #2657
Opened 2023-07-03 22:21 UTC by MMMMMMMZ

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-03 22:30 UTC, MMMMMMMZ commented
ok I fixed some problems with the checks and removed some weird spacing

2023-07-04 07:09 UTC, dakshdeepHERE requested changes
Few changes and also don't comments in codebyte

2023-07-04 07:09 UTC, dakshdeepHERE commented on content/php/concepts/string-functions/terms/str-ends-with/str-ends-with.md
> +    echo "NiceJob Ends with Bob\n"; // doesn't print
```suggestion
    echo "NiceJob Ends with Bob\n"; 
```

2023-07-04 07:09 UTC, dakshdeepHERE commented on content/php/concepts/string-functions/terms/str-ends-with/str-ends-with.md
> +    echo "All Strings end with empty String\n"; // does print due to the reason in note 1
```suggestion
    echo "All Strings end with empty String\n"; 
```

2023-07-04 07:09 UTC, dakshdeepHERE commented on content/php/concepts/string-functions/terms/str-ends-with/str-ends-with.md
> +    echo "str_ends_with() doesn't care about Case\n"; // doesn't print due to the reason in note 2
```suggestion
    echo "str_ends_with() doesn't care about Case\n"; 
```

2023-07-05 22:16 UTC, caupolicandiaz requested changes
@MMMMMMMZ I've completed my initial review. Please update the entry, and tag me when you've finished making the changes. Thanks

2023-07-05 22:16 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/str-ends-with/str-ends-with.md
> +  - 'Web Development'
```suggestion
```

2023-07-05 22:16 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/str-ends-with/str-ends-with.md
> +The **`str_ends_with()`** function Checks if a **`string`** ends with a given **`substring`**
```suggestion
The **`str_ends_with()`** function checks if a string ends with a given substring.
```

2023-07-05 22:16 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/str-ends-with/str-ends-with.md
> +The **`str_ends_with()`** function has two required parameters:
```suggestion
The `str_ends_with()` function has two required parameters:
```

2023-07-05 22:16 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/str-ends-with/str-ends-with.md
> +The **`str_ends_with()`** function has two required parameters:
boldface is only used for the first instance of the function/concept/etc

2023-07-05 22:16 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/str-ends-with/str-ends-with.md
> +- **`$string`**: Specifies the **`string`** to check if it ends with the **`$substring`**.
remove the boldface formatting from the other terms in this entry

2023-07-05 22:16 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/str-ends-with/str-ends-with.md
> +The following example uses the **`str_ends_with()`** function to check if the `"fiddlesticks"` ends with `"sticks"` and then prints to the console `" fiddlesticks end with sticks "`:
```suggestion
The following example uses the **`str_ends_with()`** function to check if the `"fiddlesticks"` ends with `"sticks"` and then prints to the console:
```

2023-07-05 22:16 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/str-ends-with/str-ends-with.md
> +
remove empty lines in the code block

2023-07-05 22:16 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/str-ends-with/str-ends-with.md
> +```shell
same as above

2023-07-05 22:57 UTC, MMMMMMMZ commented
@caupolicandiaz I finished the Requested Changes and Tagged you as you wished.

2023-07-07 16:45 UTC, SSwiniarski approved these changes
@MMMMMMMZ Looks good to merge.

2023-07-07 16:47 UTC, merged

2023-07-07 16:59 UTC, SSwiniarski commented
@MMMMMMMZ Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/php/string-functions/str-ends-with

![image](https://github.com/Codecademy/docs/assets/86081858/a30c6cc7-f517-4b2b-b2aa-961fef613296)