[Term Entry] Go String Function: Replace()
Codecademy/docs pull request #2661
Opened 2023-07-04 07:47 UTC by frhadjmli

### Description

- add `strings.Replace()`  term for Go
- closes issue #2632 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-04 07:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2661) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2661) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2661) it.</sub>

2023-07-04 13:16 UTC, SSwiniarski commented
@frhadjmli before review I wanted to let you know there was an error in the issue path. The file should be located in `docs/content/go/concepts/strings/terms/replace/replace.md`. Sorry for the confusion.

2023-07-04 14:27 UTC, frhadjmli commented
@SSwiniarski I correct the file location, and it's ready for your review.

2023-07-04 21:56 UTC, SSwiniarski commented
@frhadjmli, too much of this article is copied from [this site](https://www.educative.io/answers/how-to-use-stringsreplace-in-golang). 

We take plagiarism seriously for Codecademy Docs and for Codecademy content in general because a single case of plagiarism could jeopardize the credibility of all other 650+ entries as well as our greater catalog.
Here's the Codecademy Docs [Code of Conduct](https://github.com/yangc95/docs/blob/main/.github/CODE_OF_CONDUCT.md) on GitHub.
Since this is your first occurrence, I am issuing a warning.
We truly appreciate your help with your contribution so far and we don't want to lose you temporarily or permanently. But as we attempt to build the best coding documentation on the web, it's a long-term game and we want to focus on quality, not quantity!
We hope you understand why we are taking this very seriously.

I note that this was partially rewritten, but in order for this to be reviewed, you need to rewrite _all_ the parts of this entry that are copied from the other site.

2023-07-05 08:06 UTC, frhadjmli commented
@SSwiniarski  I made a series of changes in the file, please review it and if you have any points or find any issues, mark them in the "files changed" tab so that I can work more precisely.

2023-07-05 16:53 UTC, SSwiniarski commented
@frhadjmli so far so good. You still need to edit the description in the metadata.

2023-07-06 07:54 UTC, frhadjmli commented
@SSwiniarski I edit the description in the metadata.

2023-07-06 16:12 UTC, SSwiniarski requested changes
@frhadjmli I did a first review and left some comments.

2023-07-06 16:12 UTC, SSwiniarski commented on content/go/concepts/strings/terms/replace/replace.md
> +Description: 'replaces all or number of occurrences of a specified substring within a given string with another substring. It returns a new string with the replacements made.'
```suggestion
Description: 'Replaces all or a number of occurrences of a specified substring within a given string with another substring.' 
```

2023-07-06 16:12 UTC, SSwiniarski commented on content/go/concepts/strings/terms/replace/replace.md
> +The **strings.Replace()** replaces all or number of occurrences of a specified substring within a given string with another substring. It returns a new string with the replacements made.
```suggestion
The **`strings.Replace()`** replaces all or a number of occurrences of a specified substring within a given string with another substring. It returns a new string with the replacements made.
```

2023-07-06 16:12 UTC, SSwiniarski commented on content/go/concepts/strings/terms/replace/replace.md
> +If the 'old str' is empty, it corresponds to the beginning of the 'provided str'. It returns up to k+1 replacements after each UTF-8 sequence, resulting in a k-rune string. If n is a negative integer
```suggestion
If the `old` string is empty, it corresponds to the beginning of the `provided` string. It returns up to k+1 replacements after each UTF-8 sequence, resulting in a k-rune string. If `n` is a negative integer, there is no limit to the number of substitutions that can be made.
```

2023-07-06 16:12 UTC, SSwiniarski commented on content/go/concepts/strings/terms/replace/replace.md
> +- `n`: the count of replacements made for the old string
```suggestion
- `provided`: The original string.
- `old`: The string that will be replaced.
- `new`: The string that replaces the `old` string.
- `n`: The count of replacements made of the `old` string.
```

2023-07-06 16:12 UTC, SSwiniarski commented on content/go/concepts/strings/terms/replace/replace.md
> +## Codebyte Example (if applicable)
```suggestion
## Codebyte Example 
```

2023-07-06 19:01 UTC, frhadjmli commented
@SSwiniarski I made the requested changes.

2023-07-07 12:13 UTC, SSwiniarski approved these changes
@frhadjmli Looks good for a second review.

2023-07-07 19:52 UTC, caupolicandiaz approved these changes
@frhadjmli @SSwiniarski I just made a few small edits. Looks good to go

2023-07-08 12:44 UTC, merged

2023-07-08 13:57 UTC, SSwiniarski commented
@frhadjmli Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/go/strings/replace

![image](https://github.com/Codecademy/docs/assets/86081858/928d9cab-6a20-46ff-b3fc-fba5b37e253f)

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.