[Entry] SASS - New term page for sass concept
Codecademy/docs pull request #2662
Opened 2023-07-04 08:33 UTC by lloan

### Description

New term page for SASS concept, to go under the CSS term page. 

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-04 08:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2662) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2662) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2662) it.</sub>

2023-07-05 22:04 UTC, caupolicandiaz requested changes
@lloan I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-05 22:04 UTC, caupolicandiaz commented on content/css/concepts/sass/sass.md
> +SASS allows you to define reusable variables, making it easy to store and reuse values throughout your stylesheets.
we avoid the use of first and second person pronouns ( I, you, we) in docs. Please review and revise the other instances in this entry as above.

2023-07-05 22:04 UTC, caupolicandiaz commented on content/css/concepts/sass/sass.md
> +Operators in SASS are symbols that perform mathematical operations on values. They include arithmetic operators (+, -, *, /), comparison operators (==, !=, >, <), and logical operators (and, or, not)
```suggestion
Operators in SASS are symbols that perform mathematical operations on values. They include arithmetic operators ( `+, -, *, / `), comparison operators (`==, !=, >, <`), and logical operators (`and, or, not`). They enable dynamic calculations and conditional logic within SASS stylesheets.
```

2023-07-18 17:20 UTC, caupolicandiaz approved these changes
@lloan Looks good. I made a couple of minor tweaks, but overall this is in good shape. I'm passing this on for a second review.

2023-07-22 03:30 UTC, KTom101 requested changes
@lloan Only a few minor changes from me.

2023-07-28 01:24 UTC, KTom101 approved these changes

2023-07-28 01:24 UTC, merged

2023-07-28 03:13 UTC, KTom101 commented
@lloan Thank you for your contribution 🎉 Link is live here: https://www.codecademy.com/resources/docs/css/sass

<img width="775" alt="Screenshot 2023-07-27 at 11 12 37 PM" src="https://github.com/Codecademy/docs/assets/40783324/969befd5-5b83-45ea-9eb6-0160cca1332b">