RE: [Edit] C++ Add Codebytes #2156
Codecademy/docs pull request #2666
Opened 2023-07-04 22:35 UTC by xGavi

### Description

Hey!
I have updated cos.md, ceil.md and cbrt.md to include a Codebyte example. I have also slightly altered the wording on the previously given examples to better reflect the content of the page. This should close issue #2156.
Regarding this being my first contribution, I came across this repo through the Learn Git & GitHub course on Codecademy, and did this contribution as part of one of its projects.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-04 22:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2666) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2666) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2666) it.</sub>

2023-07-05 10:00 UTC, dakshdeepHERE commented on content/cpp/concepts/math-functions/terms/cos/cos.md
> +  // Output: The cosine of 2.5 radians is -0.801
```suggestion
```

2023-07-05 11:41 UTC, xGavi commented
> Few changes

Fixed!

2023-07-07 16:10 UTC, SSwiniarski requested changes
@xGavi I did a first maintainer review. The main issue is that the codebytes are all copied from the prior examples with just a number being changed. The codebytes should have different code than the prior examples in the entry.

2023-07-07 16:10 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/cbrt/cbrt.md
> +The following example is runnable and returns the cube root of `8` with the `cbrt()` function:
Can we make this codbyte a little more different than the prior example?

2023-07-07 16:10 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/ceil/ceil.md
> +## Codebyte Example
Can we make the codebyte example a little more different than the prior example.

2023-07-07 16:10 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/cos/cos.md
> +## Codebyte Example
Can we make the codebyte a little more different than the prior example?

2023-07-07 18:41 UTC, xGavi commented
@SSwiniarski all examples were changed!

2023-07-08 12:33 UTC, SSwiniarski approved these changes
@xGavi looks good for a second review.

2023-07-19 23:46 UTC, KTom101 requested changes
@xGavi I've added some changes to this mainly with transferring the output into `shell` blocks since the outputs are slightly lengthy to be kept in in-line comments. When transferring to `shell` blocks, please place a sentence before each `shell` saying something like "The example outputs the following:" or "The following is the output:". You can see an example of this in the [acosh entry](https://www.codecademy.com/resources/docs/cpp/math-functions/acosh) in the Example section.

2023-07-31 23:45 UTC, KTom101 approved these changes
@xGavi I've made a few more minor changes directly and ran the command `npm run format:all` in terminal to fix the failed [ci checks](https://www.codecademy.com/resources/docs/contribution-guide/getting-set-up-on-your-computer#:~:text=continuous%20integration%20(CI)%20workflows). Looks good to go 👍

2023-07-31 23:46 UTC, merged

2023-07-31 23:57 UTC, KTom101 commented
@xGavi Edits are live: [cbrt()](https://www.codecademy.com/resources/docs/cpp/math-functions/cbrt), [ceil()](https://www.codecademy.com/resources/docs/cpp/math-functions/ceil), [cos()](https://www.codecademy.com/resources/docs/cpp/math-functions/cos)

<img width="803" alt="Screenshot 2023-07-31 at 7 52 34 PM" src="https://github.com/Codecademy/docs/assets/40783324/da06db46-cca2-4e6a-bb71-78a57e2fcd50">