Go entry project
Codecademy/docs pull request #2667
Opened 2023-07-05 01:30 UTC by tokyohmachine

### Description

 I created a new pull request with the updated file path and changes. Now, I'm waiting for the repository maintainers to review and hopefully accept my new contributions.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-05 20:52 UTC, caupolicandiaz approved these changes
@tokyohmachine I've gone ahead and made some changes that were missing from the previous review. I also removed the php edits from the other PR. Please review the changes for future reference. I'm going to pass this along for a second review.

2023-07-06 04:46 UTC, CBID2 requested changes
Looks great @tokyohmachine. Just found a typo.

2023-07-06 04:46 UTC, CBID2 commented on content/go/concepts/strings/terms/join/join.md
> +In the code below several strings are concatenated into a single string, separated by spaces, using the `Join()` function.
[Typo]
```suggestion
In the code below, several strings are concatenated into a single string, separated by spaces, using the `Join()` function.
```

2023-07-06 16:38 UTC, SSwiniarski approved these changes
@tokyohmachine I committed @CBID2's suggestion because otherwise this looks good to merge.

2023-07-06 16:46 UTC, merged

2023-07-06 16:54 UTC, SSwiniarski commented
@tokyohmachine congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/go/strings/join

![image](https://github.com/Codecademy/docs/assets/86081858/2abd9f94-145a-4320-a8b3-1ccd337d6c6d)