[Term Entry] Go String Functions Trim()
Codecademy/docs pull request #2669
Opened 2023-07-05 07:30 UTC by 4hbab

### Description

- Added strings.Trim() term for go
- Closes Issue #2633 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-05 19:27 UTC, caupolicandiaz requested changes
@4hbab I've added a few comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-05 19:27 UTC, caupolicandiaz commented on content/go/concepts/strings/terms/trim/trim.md
> +Description: 'Removes leading and trailing specified characters from a string.'
```suggestion
Description: 'Removes leading and trailing characters from a string based on the given input.'
```

2023-07-05 19:27 UTC, caupolicandiaz commented on content/go/concepts/strings/terms/trim/trim.md
> +The **`Trim()`** function removes leading and trailing specified characters from a string. The `strings` library must be imported in order to use this function.
```suggestion
The **`Trim()`** function removes leading and trailing characters from a string based on the given input. The `strings` library must be imported in order to use this function.
```

2023-07-05 19:27 UTC, caupolicandiaz commented on content/go/concepts/strings/terms/trim/trim.md
> +Where `str` is the input string from which the leading and trailing characters are to be removed, `cutset` is a string containing the characters to be removed, and `trimmed` is the resulting string a
I would suggest reformatting this as a list-
- `str`: The input string from which the leading and trailing characters are to be removed.
- etc

2023-07-05 19:27 UTC, caupolicandiaz commented on content/go/concepts/strings/terms/trim/trim.md
> +The following runnable example shows the usage of the `Trim()` function to remove specific characters from a string:
```suggestion
The following runnable example uses the `Trim()` function to remove specific characters from a string:
```

2023-07-08 05:09 UTC, 4hbab commented
@caupolicandiaz I've made the suggested changes

2023-07-08 15:24 UTC, caupolicandiaz approved these changes
@4hbab Looks good. I'm passing this on to a second review.

2023-07-08 15:52 UTC, SSwiniarski approved these changes
@4hbab Looks good to merge.

2023-07-08 15:53 UTC, merged

2023-07-08 15:59 UTC, SSwiniarski commented
@4hbab Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/go/strings/trim

![image](https://github.com/Codecademy/docs/assets/86081858/250b6030-50f9-4fe4-bd4d-3fb9a1537ef1)