New cpp codebytes
Codecademy/docs pull request #2670
Opened 2023-07-05 10:20 UTC by Luke943

### Description

- Codebyte examples have been added for three C++ functions: abs, acos, asin.
- Closes #2155

### Type of Change

- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-05 10:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2670) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2670) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2670) it.</sub>

2023-07-05 15:14 UTC, yangc95 commented on content/cpp/concepts/math-functions/terms/acos/acos.md
> +#include <cmath>
may want to include std here and for other examples so we don't have to keep repeating std

2023-07-05 15:16 UTC, yangc95 requested changes
Hey @Luke943, just one main comment here for all three codebytes

2023-07-05 16:25 UTC, Luke943 commented
Thanks @yangc95, I've made the change to the files.

2023-07-12 03:34 UTC, yangc95 approved these changes
@Luke943 perf placement! Thanks for making those changes, looks good for another quick review

2023-07-13 21:06 UTC, caupolicandiaz approved these changes
@Luke943 @yangc95 LGTM

2023-07-14 07:46 UTC, Luke943 commented
Great! Thanks both @yangc95 @caupolicandiaz

2023-07-20 17:05 UTC, merged