Edit entries php examples3
Codecademy/docs pull request #2671
Opened 2023-07-05 12:12 UTC by cslylla

### Description

- I updated the following terms:
  - PHP String functions: explode(),
  - PHP String functions: strtolower(),
  - PHP String functions: substr(),
  
- I made the following changes:
  - Add Example section,
  - Fix typos.

- Closes: #2640 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-05 14:46 UTC, yangc95 commented on content/php/concepts/string-functions/terms/explode/explode.md
> +The **`explode()`** function takes a `string` and splits it on a given delimiter `string`. It returns an `array` of the substrings produced.
```suggestion
The **`explode()`** function takes a string and splits it on a given delimiter string. It returns an array of the substrings produced.
```

Thanks for bolding! The string and array though aren't referring to a code snippet or actual String/Array objects so it doesn't need to be in backticks.

2023-07-06 16:06 UTC, cslylla commented
@yangc95 Thanks for the explanation. I removed the backticks from the strtolower.md and substr.md files as well.

2023-07-12 03:37 UTC, yangc95 approved these changes
@cslylla Thanks for your thorough self-review! Looks good for a second review 🙂

2023-07-16 17:30 UTC, SSwiniarski requested changes
@cslylla I did a review and only had one comment about a missing word in the Potter quote.

2023-07-16 17:30 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/strtolower/strtolower.md
> +  echo (strtolower( "I Solemnly Swear That I Am To No Good"));
```suggestion
  echo (strtolower( "I Solemnly Swear That I Am Up To No Good"));
```

2023-07-16 17:30 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/strtolower/strtolower.md
> +i solemnly swear that i am to no good
```suggestion
i solemnly swear that i am up to no good
```

2023-07-17 16:36 UTC, merged