[Term Entry] JavaScript Dates .setHours()
Codecademy/docs pull request #2673
Opened 2023-07-05 16:12 UTC by eskuode

### Description

I have made an introductory paragraph about .setHours method, what it is and what it does. Also, I made  a section about parameters used in this method. And finally, I have provided an example showing the method in use.

- 

### Type of Change

- Adding a new entry

### Checklist

- [ x] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-05 16:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2673) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2673) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2673) it.</sub>

2023-07-05 17:24 UTC, dakshdeepHERE requested changes
Few changes from my side. Also please remove that other new_file.html file from this PR.

2023-07-05 17:24 UTC, dakshdeepHERE commented on content/javascript/concepts/dates/terms/setHours/setHours.md
> +In the example below, the `myDate` variable takes the provided date and then the `.setHours()` method is applied to return a date with set hours, minutes and seconds.
```suggestion
In the example below, the `myDate` variable takes the provided date and applies the `.setHours()` method to set the hours, minutes, and seconds of the date:
```

2023-07-05 17:24 UTC, dakshdeepHERE commented on content/javascript/concepts/dates/terms/setHours/setHours.md
> +- ##### Optional. 0 to 999 representing the milliseconds. You must also specify `minutesValue` and `secondsValue`.
```suggestion
**`hoursValue:`** 
- Required. 0 to 23 representing the hours.
**`minutesValue:`**
- Optional. 0 to 59 representing the minutes.
**`secondsValue:`**
- Optional. 0 to 59 representing the seconds. You must also specify `minutesValue`.
**`millisecondsValue:`**
- Optional. 0 to 999 representing the milliseconds. You must also specify `minutesValue` and `secondsValue`.
```

2023-07-05 22:30 UTC, caupolicandiaz requested changes
@eskuode I've completed a maintainers review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-05 22:30 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/setHours/setHours.md
> +The `.setHours()` method changes the hours, minutes, seconds and millisecons for this date according to local time.
```suggestion
```

2023-07-05 22:30 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/setHours/setHours.md
> +## Parameters
`.setHours()` takes the following parameters:

2023-07-05 22:30 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/setHours/setHours.md
> +- Required. 0 to 23 representing the hours.
```suggestion
- `hoursValue:` (Required) Takes values from `0` to `23` representing the hours.
```

2023-07-05 22:30 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/setHours/setHours.md
> +- Required. 0 to 23 representing the hours.
update the other parameters as above

2023-07-05 22:30 UTC, caupolicandiaz commented on content/javascript/concepts/dates/terms/setHours/setHours.md
> +The `.setHours()` method changes the hours, minutes, seconds and millisecons for this date according to local time.
```suggestion
The `.setHours()` method changes the hours, minutes, seconds and milliseconds for a given date according to local time.
```

2023-07-10 16:34 UTC, caupolicandiaz commented
@eskuode Are you still working on these changes? It looks as though some updates are still missing.

2023-07-10 20:11 UTC, eskuode commented
@caupolicandiaz hi, yes i am still working on it

2023-07-10 20:30 UTC, eskuode commented
@caupolicandiaz I will let you know in couple days how it's going, just messed up something on my local repo.

2023-07-12 11:37 UTC, eskuode commented
@caupolicandiaz I have finished with updates.

2023-07-12 17:31 UTC, caupolicandiaz approved these changes
@eskuode Overall, looks good. I did push a couple of minor edits. I'm passing this on to a second review.

2023-07-15 14:56 UTC, SSwiniarski requested changes
@eskuode I did a second review and had one comment to address.

2023-07-15 14:56 UTC, SSwiniarski commented on content/javascript/concepts/dates/terms/setHours/setHours.md
> +- `millisecondsValue:`(Optional) takes values from `0` to `999` representing the milliseconds. You must also specify `minutesValue` and `secondsValue`.
```suggestion
- `hoursValue`: (Required) takes values from `0` to `23` representing the hours.
- `minutesValue`: (Optional) takes values from `0` to `59` representing the minutes.
- `secondsValue`: (Optional) takes values from `0` to `59` representing the seconds. Must also specify `minutesValue`.
- `millisecondsValue`: (Optional) takes values from `0` to `999` representing the milliseconds. Must also specify `minutesValue` and `secondsValue`.
```
Some minor formatting things and removing second person pronoun.

2023-07-16 14:00 UTC, eskuode commented
@SSwiniarski Thanks, I accepted the updates.

2023-07-16 15:50 UTC, SSwiniarski approved these changes
@eskuode Looks good.

2023-07-16 16:08 UTC, merged

2023-07-16 16:16 UTC, SSwiniarski commented
@eskuode congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/javascript/dates/setHours

![image](https://github.com/Codecademy/docs/assets/86081858/442ec332-790b-49ec-b5c7-2848ad59b7e1)

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.