[New Entry] PHP Array term array_combine()
Codecademy/docs pull request #2675
Opened 2023-07-05 20:10 UTC by brandon-kong

### Description

- Added PHP Entry
- Closes issue #2555 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-05 20:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2675) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2675) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2675) it.</sub>

2023-07-07 08:52 UTC, dakshdeepHERE requested changes
One change from my side

2023-07-07 08:52 UTC, dakshdeepHERE commented on content/php/concepts/arrays/terms/array-combine/array-combine.md
> +Description: 'The array_combine() function returns an array by using the elements of one "keys" array as keys and the elements of another "values" array as the corresponding values.'
```suggestion
Description: 'Returns a new array by combining two arrays, where one array represents keys and the other array represents values.'
```
Let's keep this short and descriptive we can explain it more down below

2023-07-07 16:19 UTC, SSwiniarski requested changes
@brandon-kong I did a first maintainer review with a few comments to address in addition to @dakshdeepHERE's comment. You also modified the `yarn.lock` file, which shouldn't have happened. I'll try and fix that for you.

2023-07-07 16:19 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-combine/array-combine.md
> +The `array_combine()` returns an array by using the elements of one "keys" array as keys and the elements of another "values" array as the corresponding values.
```suggestion
The **`array_combine()`** returns an array by using the elements of one "keys" array as keys and the elements of another "values" array as the corresponding values.
```

2023-07-07 16:19 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-combine/array-combine.md
> +
Have a sentence before the example block summarizing what it does.

2023-07-07 16:19 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-combine/array-combine.md
> +Additionally, if there are multiple keys in the `keys` array, the last value that corresponds to the last occurrence of the key will prevail.
Swap this line with the header on line 51.

2023-07-07 16:19 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-combine/array-combine.md
> +
Have a sentence introducing the codebyte and summarizing what it's doing.

2023-07-07 16:24 UTC, SSwiniarski commented
@brandon-kong I fixed the edits to the `yarn.lock` file.

2023-07-08 12:37 UTC, SSwiniarski requested changes
@brandon-kong one more comment.

2023-07-08 12:37 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-combine/array-combine.md
> +In this example, we will create an array with the keys `one`, `two`, `three`, and `four` and the values `1`, `2`, `3`, and `4`, respectively.
```suggestion
In this example, an array is created with the keys `one`, `two`, `three`, and `four` and the values `1`, `2`, `3`, and `4`, respectively.
```
We avoid first- and second-person pronouns in Docs.

2023-07-08 18:02 UTC, SSwiniarski approved these changes
@brandon-kong Looks good for a second review.

2023-07-10 20:03 UTC, caupolicandiaz requested changes
@brandon-kong I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-10 20:03 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-combine/array-combine.md
> +  print_r($colorHex);
```suggestion
  $colors = array("red", "green", "blue");
  $food = array("apple", "broccoli", "blueberry");
  $colorAndFood = array_combine($colors, $food);
  print_r($colorAndFood);
```

2023-07-10 20:24 UTC, brandon-kong commented
@caupolicandiaz Thanks for your initial review. I have went ahead and made changes according to your suggestions. Thanks in advance.

2023-07-11 16:51 UTC, caupolicandiaz approved these changes
@brandon-kong @SSwiniarski Looks good to merge

2023-07-12 13:19 UTC, merged