[Concept Entry] SwiftUI Layouts
Codecademy/docs pull request #2699
Opened 2023-07-08 13:40 UTC by gracekishino

Add new concept entry for SwiftUI layouts.

### Description

Added new folder `layouts` inside `content/swiftui/concepts/`.
Added new entry file `content/swiftui/concepts/layouts/layouts.md` for SwiftUI Layouts.

Closes #2102

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-08 15:29 UTC, SSwiniarski requested changes
@gracekishino I did a first review and only had a couple of comments.

2023-07-08 15:29 UTC, SSwiniarski commented on content/swiftui/concepts/layouts/layouts.md
> +**`Layout`** is a `protocol` in [SwiftUI](https://www.codecademy.com/resources/docs/swiftui) used to create layouts for user interfaces. Layouts specify how to arrange the [views](https://www.codecad
```suggestion
**`Layout`** is a `protocol` in SwiftUI used to create layouts for user interfaces. Layouts specify how to arrange the [views](https://www.codecademy.com/resources/docs/swiftui/views) they contain. It's possible to create custom and conditional layouts. There are also built-in layouts that can be used when creating conditional layouts.
```
We generally don't link to parent entries. Docs navigation provides those automatically.

2023-07-08 15:29 UTC, SSwiniarski commented on media/swiftui-conditional-layout.gif
If this is supposed to animate, I am not seeing the animation.

2023-07-09 01:26 UTC, gracekishino commented on media/swiftui-conditional-layout.gif
@SSwiniarski the gif wasn't looping so now replaced it with a looping one. Hope you can see it OK now!

2023-07-09 13:40 UTC, SSwiniarski approved these changes
@gracekishino Looks good for a second review.

2023-08-03 20:48 UTC, yangc95 approved these changes
@gracekishino wow! This is excellent

2023-08-03 20:49 UTC, merged

2023-08-03 20:50 UTC, yangc95 commented
🥳 Outstanding @gracekishino live link: https://www.codecademy.com/resources/docs/swiftui/layouts
<img width="684" alt="Screenshot 2023-08-03 at 4 50 37 PM" src="https://github.com/Codecademy/docs/assets/72277593/3941263f-687f-48fb-a25e-ee9d984d1860">

cc: @SSwiniarski

2023-08-04 08:46 UTC, gracekishino commented
@yangc95 @SSwiniarski Thanks so much! This one did take me quite a while to research and understand so learned loads from it :)