Supply chain attack
Codecademy/docs pull request #2702
Opened 2023-07-08 18:23 UTC by SUSHIBUN

### Description

Closes #2692 For the issue: [Term Entry] Cybersecurity Cyber-Attack Supply Chain Attack, added and edited a new file supply-chain-attack.md in 'content/cybersecurity/concepts/cyber-attack/terms/supply-chain-attack/'

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-08 18:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2702) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2702) before we can accept your contribution.<br/><hr/>**Steve Li** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2702) it.</sub>

2023-07-08 18:37 UTC, SUSHIBUN commented
Thanks for the help! I solved the problem and made a PR.

2023-07-08 18:58 UTC, SSwiniarski requested changes
@SUSHIBUN I did a first review and left a few comments.

2023-07-08 18:58 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-attack/terms/supply-chain-attack/supply-chain-attack.md
> +Description: 'A supply chain attack targets an organizations software or hardware supply chain, compromising it to gain unauthorized access or control over the organizations systems.'
```suggestion
Description: 'A supply chain attack targets the software or hardware supply chain of an organization, compromising it to gain unauthorized access or control over the systems of the organization.'
```
Rewrote so there's no apostropheless possessives.

2023-07-08 18:58 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-attack/terms/supply-chain-attack/supply-chain-attack.md
> +**Supply chain attack** is a cyber attack that targets an organization's software or hardware supply chain, aiming to gain unauthorized access or control over the target organization's systems by inj
```suggestion
A **supply chain attack** is a cyber attack that targets an organization's software or hardware supply chain, aiming to gain unauthorized access or control over the target organization's systems by injecting malicious code or tampering with components within the supply chain.
```

2023-07-08 18:58 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-attack/terms/supply-chain-attack/supply-chain-attack.md
> +## Harmful Reasons
```suggestion
## Risks
```

2023-07-08 18:58 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-attack/terms/supply-chain-attack/supply-chain-attack.md
> +- Reputational and financial damage: Organizations that fall victim to supply chain attacks can suffer significant reputational damage, loss of customer trust, and financial losses. Recovering from s
```suggestion
- Trust and reliance: Organizations often trust their suppliers, vendors, and partners within the supply chain, assuming that the software or hardware components they provide are secure and free from malicious elements. As a result, when compromised components are introduced into the supply chain, they can easily infiltrate the target organization's systems without raising suspicion.
- Widespread impact: Supply chain attacks can have a cascading effect, impacting multiple organizations and potentially thousands or millions of users. By compromising a trusted vendor or supplier, attackers can gain access to numerous downstream organizations that rely on their products or services, amplifying the scope and impact of the attack.
- Difficulty in detection: Since the malicious components are embedded within legitimate software or hardware, they can evade traditional security measures, such as antivirus software or network firewalls. This makes it challenging to detect and mitigate the attack before it infiltrates the target organization's systems.
- Persistence and stealth: Supply chain attacks often aim to establish persistent access or backdoors within the target organization's systems, allowing attackers to maintain control over an extended period. These backdoors can be difficult to detect and remove, providing attackers with ongoing unauthorized access and the ability to steal sensitive data or launch further attacks.
- Complexity and sophistication: Supply chain attacks require careful planning, technical expertise, and knowledge of the target organization's supply chain relationships. Attackers may exploit vulnerabilities at different stages of the supply chain, including development, distribution, or even physical tampering. The level of sophistication involved makes these attacks more challenging to defend against.
- Reputational and financial damage: Organizations that fall victim to supply chain attacks can suffer significant reputational damage, loss of customer trust, and financial losses. Recovering from such attacks often involves substantial costs for incident response, remediation, legal actions, and rebuilding trust with customers and partners.
```
Eliminate blank lines between bullet points.

2023-07-08 18:58 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-attack/terms/supply-chain-attack/supply-chain-attack.md
> +## Protecting Methods
```suggestion
## Means of Protection
```

2023-07-08 18:58 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-attack/terms/supply-chain-attack/supply-chain-attack.md
> +Organizations can enhance their protection against supply chain attacks by the steps below:
```suggestion
Organizations can enhance their protection against supply chain attacks via the steps below:
```

2023-07-08 18:58 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-attack/terms/supply-chain-attack/supply-chain-attack.md
> +9.Stay compliant: Stay updated with relevant regulations and implement necessary controls to protect data and privacy.
```suggestion
1. Choose trusted vendors and partners: Conduct thorough evaluations of vendors and suppliers to ensure they have strong security practices and a good reputation.
2. Secure software and hardware: Implement measures to verify the integrity of components throughout the supply chain, such as using digital signatures or checksums.
3. Monitor and detect: Deploy monitoring systems to identify suspicious activities within the supply chain and leverage threat intelligence to detect potential attacks.
4. Establish security agreements: Establish clear security requirements in contracts with suppliers and vendors, including incident response protocols.
5. Educate employees: Train employees to recognize and report suspicious activities and foster a culture of security awareness.
6. Plan for incidents: Develop an incident response plan specific to supply chain attacks and regularly test and update it.
7. Assess and audit: Conduct regular security assessments and audits to identify vulnerabilities and areas for improvement.
8. Collaborate and share information: Engage in information sharing and industry collaborations to stay informed about emerging threats.
9. Stay compliant: Stay updated with relevant regulations and implement necessary controls to protect data and privacy.
```
No blank lines between bullet points.

2023-07-08 19:21 UTC, SSwiniarski approved these changes
@SUSHIBUN Looks good for a second review.

2023-07-11 19:44 UTC, caupolicandiaz requested changes
@SUSHIBUN I've added a few comments. Please update the entry, and tag me when you've finished making the changes. Thanks

2023-07-11 19:44 UTC, caupolicandiaz commented on content/cybersecurity/concepts/cyber-attack/terms/supply-chain-attack/supply-chain-attack.md
> +Description: 'A supply chain attack targets the software or hardware supply chain of an organization, compromising it to gain unauthorized access or control over the systems of the organization.'
```suggestion
Description: 'A supply chain attack targets the software or hardware supply chain of an organization in order to access or gain control over their systems.'
```

2023-07-11 19:44 UTC, caupolicandiaz commented on content/cybersecurity/concepts/cyber-attack/terms/supply-chain-attack/supply-chain-attack.md
> +A **supply chain attack** is a cyber attack that targets an organization's software or hardware supply chain, aiming to gain unauthorized access or control over the target organization's systems by i
```suggestion
A **supply chain attack** is a cyber attack that targets an organization's software or hardware supply chain. The aim is to gain unauthorized access or control over the target organization's systems by injecting malicious code or tampering with components within the supply chain.
```

2023-07-11 19:44 UTC, caupolicandiaz commented on content/cybersecurity/concepts/cyber-attack/terms/supply-chain-attack/supply-chain-attack.md
> +  - 'Cybersecurity'
```suggestion
  - 'Cybersecurity'
  - 'Infrastructure'
```

2023-07-13 15:46 UTC, SUSHIBUN commented
@caupolicandiaz Thanks for the comments, I have finished the change.

2023-07-13 17:30 UTC, caupolicandiaz approved these changes
@SUSHIBUN @SSwiniarski This looks good to merge.

2023-07-14 11:46 UTC, merged