[Term Entry] Java Date Method: .after()
Codecademy/docs pull request #2703
Opened 2023-07-08 21:02 UTC by frhadjmli

### Description

- Added the Date.after() term for Java
- closes issue #2685 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-09 04:53 UTC, dakshdeepHERE requested changes
A change from my side

2023-07-09 04:53 UTC, dakshdeepHERE commented on content/java/concepts/date/terms/after/after.md
> +The **`Date.after()`** method Checks if the first date occurs after the second date. It returns a boolean value.
```suggestion
The **`Date.after()`** method checks whether the first date occurs after the second date and returns a boolean value.
```

2023-07-09 14:25 UTC, SSwiniarski requested changes
@frhadjmli I did a first maintainer review and left a couple of comments.

2023-07-09 14:25 UTC, SSwiniarski commented on content/java/concepts/date/terms/after/after.md
> +Description: 'Checks if the first date occurs after the second date.'
```suggestion
Description: 'Checks if a date occurs after a specified date.'
```

2023-07-09 14:25 UTC, SSwiniarski commented on content/java/concepts/date/terms/after/after.md
> +The **`Date.after()`** method checks whether the first date occurs after the second date and returns a boolean value.
```suggestion
The **`Date.after()`** method checks whether a date occurs after a specified date and returns a boolean value.
```

2023-07-09 16:27 UTC, frhadjmli commented
@SSwiniarski I made the changes as requested.

2023-07-09 16:30 UTC, SSwiniarski approved these changes
@frhadjmli Looks good for a second review.

2023-07-10 20:33 UTC, caupolicandiaz approved these changes
@frhadjmli @SSwiniarski LGTM

2023-07-11 16:07 UTC, merged

2023-07-11 16:12 UTC, SSwiniarski commented
@frhadjmli Congrats on the new entry! Live link here:https://www.codecademy.com/resources/docs/java/date/after

![image](https://github.com/Codecademy/docs/assets/86081858/d4e7a097-708a-4c94-bd86-6750bfeeafcc)