Feature recurrent neural networks
Codecademy/docs pull request #2704
Opened 2023-07-08 21:53 UTC by apropos0

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-08 22:14 UTC, apropos0 commented
#2017

2023-07-08 23:29 UTC, bananagrenade commented on content/ai/concepts/neural-networks/terms/recurrent-neural-networks/recurrent-neural-networks.md
> +Description: 'Recurrent Neural Network is a type of neural network distinguished by its use of the outputs from previous layers as inputs in the current layer'
Description: 'Recurrent Neural Network is a type of neural network distinguished by storing and re-using outputs from previous layers as additional inputs in the current layer'

2023-07-08 23:36 UTC, bananagrenade commented on content/ai/concepts/neural-networks/terms/recurrent-neural-networks/recurrent-neural-networks.md
> +RNNs apply best in cases where "memory" or "state" is important, this can be sequential or time-based data, where the output is a predictable value in the sequence.
RNNs apply best in cases where the sequence of data is important to the predicted output. In sequential or time-based data sets, RNNs can persist previous outputs as "memories" or "states", and use that to predict the output in the sequence.

2023-07-08 23:47 UTC, bananagrenade commented on content/ai/concepts/neural-networks/terms/recurrent-neural-networks/recurrent-neural-networks.md
> +To conceptually train an RNN, a vector-encoded input is passed from the dataset to the network, and the network computes its output using initially random weights and biases (unlike other neural netw
To train a RNN, a vector-encoded input is passed from the dataset (_a vector-encoded dataset is passed as an input to the network ?_ might be misunderstanding this part) to a network that is initialized with random weights and biases. However, unlike other neural networks, a RNN keeps the same weight and biases throughout all of its layers when computing the output value(s).

2023-07-08 23:50 UTC, bananagrenade commented on content/ai/concepts/neural-networks/terms/recurrent-neural-networks/recurrent-neural-networks.md
> +When the output is computed, it is fed forward to the next layer, which uses the previous result as well as the current input from the dataset to form its output. This process is continued through th
Think you should drop in a sentence or two describing the outputs being stored / persisted for re-use in a loop (?). Then the mention of "previous" result might make more sense

2023-07-08 23:56 UTC, bananagrenade commented on content/ai/concepts/neural-networks/terms/recurrent-neural-networks/recurrent-neural-networks.md
> +Using a loss function, we compare the expected and actual results to find the error. The error is backpropagated through time (BPTT) to update the weights and biases and thus train the network until
A loss function is used to compare the expected result(s) and actual result(s) to find the error rate of the prediction. The error is then backpropagated through time (BPTT) to so the network can update its weights and biases in each layer. Repeating this process thus trains the network until the expected result is produced.

2023-07-08 23:56 UTC, bananagrenade commented on content/ai/concepts/neural-networks/terms/recurrent-neural-networks/recurrent-neural-networks.md
> +A standard issue when training a typical RNN is the vanishing gradient problem. When attempting to backpropagate and update the weights, we see that inputs used earlier in the layer have a smaller im
A common issue when training a RNN...

2023-07-09 15:58 UTC, SSwiniarski requested changes
@apropos0 I did a first maintainer review and left a few comments.

2023-07-09 15:58 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/recurrent-neural-networks/recurrent-neural-networks.md
> +Description: 'Recurrent Neural Network is a type of neural network distinguished by storing and re-using the output from previous steps as an additional input in the current step'
```suggestion
Description: 'Recurrent Neural Networks are a type of neural network distinguished by storing and re-using the output from previous steps as an additional input in the current step'
```

2023-07-09 15:58 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/recurrent-neural-networks/recurrent-neural-networks.md
> +## What Is A Recurrent Neural Network (RNN)?
```suggestion
```
Remove this header. In docs we don't use headers above the first paragraph. The paragraph comes right after the title.

2023-07-09 15:58 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/recurrent-neural-networks/recurrent-neural-networks.md
> +**Recurrent Neural Network** (RNN) is a type of neural network distinguished by storing and re-using the outputs from previous steps as additional inputs in the current step. RNNs processes sequentia
```suggestion
A **Recurrent Neural Network** (RNN) is a type of neural network distinguished by storing and re-using the outputs from previous steps as additional inputs in the current step. RNNs process sequential data in groups of "timesteps" which represent a slice of the sequence.  These timesteps could represent words from a sentence or frames from an audio clip. The network uses the output from previous timesteps which are stored in a "hidden state" or "hidden variable" to compute the output for the current timestep.
```

2023-07-09 15:58 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/recurrent-neural-networks/recurrent-neural-networks.md
> +The training data is split into time-based sequences, they are then vector-encoded and passed into the RNN as inputs. The RNN is initialized with random weights and biases which remain the same throu
```suggestion
The training data is split into time-based sequences. They are then vector-encoded and passed into the RNN as inputs. The RNN is initialized with random weights and biases which remain the same through all timesteps. The network iterates over the sequence to compute the output or hidden state for each timestep.
```

2023-07-09 15:58 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/recurrent-neural-networks/recurrent-neural-networks.md
> +The current hidden state is computed by passing the input for the current time-step, the previous hidden state and the weights and biases for the sequence into a layer with an activation function of
```suggestion
The current hidden state is computed by passing the input for the current time-step, the previous hidden state, and the weights and biases for the sequence into a layer with an activation function of choice. The hidden state is then returned as an output and passed to the next timestep. The process is repeated through the rest of the timesteps. Depending on the task, the final output can either be returned as a single vector or can be a combination of output vectors returned in each timestep. For the first timestep the previous hidden state can be initialized as a zero vector, its size will depend on the intended output size.
```

2023-07-09 15:58 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/recurrent-neural-networks/recurrent-neural-networks.md
> +- One input to one output: Image classification.
```suggestion
- Many inputs to many outputs: Speech Recognition, Language Translation, Language modeling.
- Many inputs to one output: Stock prediction, weather prediction, Sentiment analysis.
- One input to many output: Image captioning, Music Generation.
- One input to one output: Image classification.
```
Remove blank lines between items in a bulleted list.

2023-07-10 01:02 UTC, apropos0 commented
Thanks @SSwiniarski , applied suggestions

2023-07-28 22:25 UTC, HishamT reviewed
Hey @apropos0, thank you for your entry to Codecademy Docs. I have reviewed the entry and left some comments.

2023-07-28 22:25 UTC, HishamT commented on content/ai/concepts/neural-networks/terms/recurrent-neural-networks/recurrent-neural-networks.md
> +A **Recurrent Neural Network** (RNN) is a type of neural network distinguished by storing and re-using the outputs from previous steps as additional inputs in the current step. RNNs process sequentia
```suggestion
A **Recurrent Neural Network** (RNN) is a type of neural network that stores and re-uses the outputs from previous steps as additional inputs in the current step. RNNs process sequential data in groups of *timesteps* which represent a segment of the sequence. These timesteps could represent words from a sentence or frames from an audio clip. The network uses the output from previous timesteps which are stored in a "hidden state" or "hidden variable" to compute the output for the current timestep.
```

2023-07-28 22:25 UTC, HishamT commented on content/ai/concepts/neural-networks/terms/recurrent-neural-networks/recurrent-neural-networks.md
> +The current hidden state is computed by passing the input for the current time-step, the previous hidden state, and the weights and biases for the sequence into a layer with an activation function of
```suggestion
The current hidden state is computed by passing the input for the current time-step, the previous hidden state, and the weights and biases for the sequence into a layer with an activation function of choice. The hidden state is then returned as an output and passed to the next timestep. The process is repeated through the rest of the timesteps. Depending on the task, the final output can either be returned as a single vector or can be a combination of output vectors returned in each timestep. For the first timestep, the previous hidden state can be initialized as a zero vector of size dependent on the intended output size.
```

2023-07-28 22:25 UTC, HishamT commented on content/ai/concepts/neural-networks/terms/recurrent-neural-networks/recurrent-neural-networks.md
> +A loss function is used to compare the expected result and actual result returned by the model. Using the loss calculated, the loss gradient for each timestep is computed using backpropagation throug
Capitalize Backpropagation Through Time

2023-07-30 15:46 UTC, apropos0 commented
@HishamT Thanks for the review. Applied suggestions. Used _timesteps_ instead, prettier had an issue with the *timesteps* format

2023-08-07 19:05 UTC, merged

2023-08-08 11:13 UTC, SSwiniarski commented
@apropos0 Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/ai/neural-networks/recurrent-neural-networks

![image](https://github.com/Codecademy/docs/assets/86081858/32b79113-a4ae-4722-9f82-1868e133e4da)