Storage length
Codecademy/docs pull request #2705
Opened 2023-07-09 02:38 UTC by Rcshort123

### Description

Created the beginning of the length.md by creating the path folders to the file. I have done an introduction of the method and the syntax for string and array. As this is the first contribution I wanted to make a pull request to double-check that I am going about this the right way before I get too far into it. plus small requests are better from what I learned on Codecademy so far. thank you

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x ] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-09 02:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2705) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2705) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2705) it.</sub>

2023-07-09 04:50 UTC, dakshdeepHERE requested changes
I have some comments for you

2023-07-09 04:50 UTC, dakshdeepHERE commented on content/javascript/concepts/storage/terms/length.md
> +# .length()
```suggestion
```
Add the table here like this:
<img width="898" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/dd0f7b19-30e6-4d25-bcb6-94113b007b63">
```
---
Title: 'Selection-Sort Algorithm'
Description: 'Returns a sorted array'
Subjects:
  - 'Computer Science'
Tags:
  - 'Algorithms'
  - 'Arithmetic'
CatalogContent:
  - 'learn-java'
  - 'paths/computer-science'
---
```
You have to change the names and description according to the entry

2023-07-09 04:50 UTC, dakshdeepHERE commented on content/javascript/concepts/storage/terms/length.md
> +///returns 3;
```suggestion
```

2023-07-09 04:50 UTC, dakshdeepHERE commented on content/javascript/concepts/storage/terms/length.md
> +length is called on a string through the following syntax and will output the number of characters of the string.
```suggestion
length is called on a string through the following syntax and will output the number of characters of the string. 

```

2023-07-09 04:50 UTC, dakshdeepHERE commented on content/javascript/concepts/storage/terms/length.md
> +```
```suggestion
```shell
```

2023-07-09 04:50 UTC, dakshdeepHERE commented on content/javascript/concepts/storage/terms/length.md
> +```
```suggestion
```

```

2023-07-09 04:50 UTC, dakshdeepHERE commented on content/javascript/concepts/storage/terms/length.md
> +Remember arrays are 0 Indexed but .length will count the 0 as 1 in it's count.
Why not remove all this and add this code block in the above syntax itself. After that create a example section for the code blocks

2023-07-09 06:07 UTC, Rcshort123 commented
thank you @dakshdeepHERE for the comments I'll get working on them and make another request when I have it more fleshed out. =)

2023-07-09 06:25 UTC, dakshdeepHERE commented
> thank you @dakshdeepHERE for the comments I'll get working on them and make another request when I have it more fleshed out. =)

Sure good luck with the changes.

2023-07-09 13:46 UTC, SSwiniarski commented
> thank you @dakshdeepHERE for the comments I'll get working on them and make another request when I have it more fleshed out. =)

@Rcshort123 You don't need to make another PR, we can see all the changes in this PR. Also yo need to sign the [CLA](https://cla-assistant.io/Codecademy/docs?pullRequest=2705) both as @Rcshort123 and @shortryan91. Also, @shortryan91 will be the GitHub user that will recieve credit for this entry, since that's the user that submitted the PR.

2023-07-09 13:58 UTC, SSwiniarski commented
@Rcshort123 looking at this we have two problems:

1. You have no metadata at the start of your entry. You can learn how to add the metadata from the style guide [here](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#metadata).
2.  Second, this entry is not about the correct property. The array and string `length` properties have their own entries. What we want here is the `Storage.length` property. That is, the `length` property of the `Storage` object. You need to rewrite this to cover that property.

Tag me when you've addressed these issues and I'll do a first maintainer review.

2023-07-09 21:59 UTC, closed without merging

2023-07-10 15:48 UTC, SSwiniarski commented
@Rcshort123 are you going to submit another PR or do you want to be unassigned from this issue?

2023-07-11 00:09 UTC, Rcshort123 commented
@SSwiniarski Yes I will submit another request, as you mentioned I pull requested with the wrong account, and I would like to have it credited to the right account, and its good practice for me to make sure. I'll be sure to @ you in the new request thanks for all the help so far =)