[Term Entry] Go Math Functions Round()
Codecademy/docs pull request #2706
Opened 2023-07-09 08:54 UTC by 4hbab

- Added math.Round() term for go
- Closes Issue #2560 

### Description

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-09 15:37 UTC, SSwiniarski requested changes
@4hbab I did a first review and left a couple of comments.

2023-07-09 15:37 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/round/round.md
> +The **`Round()`** function in Go is used to round a given number to the nearest integer. This function is part of the `math` package and can be imported to use in your Go programs.
```suggestion
The **`Round()`** function in Go is used to round a given number to the nearest integer. This function is part of the `math` package which needs to be imported to use in Go programs.
```

2023-07-09 15:37 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/round/round.md
> +- `x`: is the number to be rounded
```suggestion
- `x`: is the number to be rounded.
```

2023-07-10 07:42 UTC, 4hbab commented
@SSwiniarski I've made the changes

2023-07-10 15:57 UTC, SSwiniarski approved these changes
@4hbab looks good for a second review.

2023-07-10 19:14 UTC, caupolicandiaz approved these changes
@4hbab @SSwiniarski Looks good to merge

2023-07-11 15:52 UTC, merged

2023-07-11 16:04 UTC, SSwiniarski commented
@4hbab Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/go/math-functions/round

![image](https://github.com/Codecademy/docs/assets/86081858/10139dd0-6f97-44a5-9423-c3d8a77d238e)