[Term Entry] JavaScript Storage .getItem(key) - close #2694
Codecademy/docs pull request #2715
Opened 2023-07-10 08:42 UTC by SimonaPiz

### Description
close #2694

This was my first entry for Codecademy docs

- I created a new folder 'storage/terms/getItem' in 'content/javascript/concepts/'
- Inside it I created new file 'getItem.md' with the required content
  - [x] Title
  - [x] Description
  - [x] Subjects
  - [x] Tags
  - [x] CatalogContent
  - [x] Syntax
  - [x] Codebyte Example
- I added a new `Storage` tag  in '/documentation/tags.md'

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-10 08:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2715) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2715) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2715) it.</sub>

2023-07-10 15:29 UTC, dakshdeepHERE commented on content/javascript/concepts/storage/terms/getItem/getItem.md
> +```javascript
```suggestion
```pseudo
```
use pseudo tags for syntax

2023-07-10 15:29 UTC, dakshdeepHERE commented on content/javascript/concepts/storage/terms/getItem/getItem.md
> +```javascript
```suggestion
or

```pseudo
```

2023-07-10 21:44 UTC, caupolicandiaz requested changes
@SimonaPiz I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-10 21:44 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/getItem/getItem.md
> +  - 'Objects'
```suggestion
```

2023-07-10 21:44 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/getItem/getItem.md
> +  - 'Objects'
we limit tags to 5 items

2023-07-10 21:44 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/getItem/getItem.md
> +  - 'user-authentication-authorization-express'
```suggestion
```

2023-07-10 21:44 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/getItem/getItem.md
> +  - 'user-authentication-authorization-express'
catalog content should only contain two items

2023-07-10 21:44 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/getItem/getItem.md
> +  - 'paths/securing-express-applications'
```suggestion
  - 'introduction-to-javascript'
```

2023-07-10 21:44 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/getItem/getItem.md
> +  - 'paths/back-end-engineer-career-path'
```suggestion
  - 'paths/front-end-engineer-career-path'
```

2023-07-10 21:44 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/getItem/getItem.md
> +The **.getItem()** method takes the key of the data item as an argument and returns the value of the data if it is in the `Storage` object, otherwise it returns `null`.
```suggestion
The **`.getItem()`** method takes a key as an argument and returns the associated value. If the key is not present in the `Storage` object, it returns `null`.
```

2023-07-10 21:44 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/getItem/getItem.md
> +Description: 'Returns the value of the key of the data item passed as an argument or null if it does not exist, from the storage object'
```suggestion
Description: 'Returns the value of the key on the given data item.'
```

2023-07-10 21:44 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/getItem/getItem.md
> +## Codebyte Example
```suggestion
## Example
```

2023-07-10 21:44 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/getItem/getItem.md
> +## Codebyte Example
this function is not currently supported by Codecademy's compiler. Please reframe this example as a "standard" example with an output in a ```shell block

2023-07-10 21:44 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/getItem/getItem.md
> +> You could also use `Storage.length` to test whether the storage object is empty or not.
```suggestion
> **Note:** The `Storage.length` property can be used to test whether the storage object is empty or not.
```

2023-07-10 21:44 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/getItem/getItem.md
> +```pseudo
the two formats can be consolidated into one block

2023-07-11 07:43 UTC, SimonaPiz commented
@caupolicandiaz 
Thanks for the review and recommendations. I have made the requested changes.

2023-07-11 20:17 UTC, caupolicandiaz requested changes
@SimonaPiz I've added additional comments. Please review and revise.

2023-07-11 20:17 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/getItem/getItem.md
> +```codebyte/javascript
There are still changes missing here. The block is still set as a codebyte and the code should be revised to be a more complete example that could be conceivably used as is, something like:
localStorage.setItem("Seuss", "Green Eggs and Ham")
console.log(localStorage.getItem("Seuss")

And the output should be in a separate ```shell block

2023-07-11 21:15 UTC, caupolicandiaz approved these changes
@SimonaPiz I've made some small edits to your revisions, please review for future reference. I'm passing this on for a second review.

2023-07-15 14:52 UTC, SSwiniarski requested changes
@SimonaPiz I did a review and had one comment. (We avoid first- and second-person pronouns in Docs.)

2023-07-15 14:52 UTC, SSwiniarski commented on content/javascript/concepts/storage/terms/getItem/getItem.md
> +The `keyName` parameter is required and it's a string containing the name of the key you want to retrieve the value of.
```suggestion
The `keyName` parameter is required and it's a string containing the name of the key to retrieve the value of.
```

2023-07-16 13:08 UTC, SSwiniarski approved these changes
@SimonaPiz Looks good to merge once we have a storage concept merged.

2023-08-02 15:59 UTC, merged