[Term Entry]: PHP strtoupper()
Codecademy/docs pull request #2718
Opened 2023-07-10 17:04 UTC by Jess-G95

### Description

Added a new entry for the PHP function strtoupper(). The entry is in a new file in docs/content/php/concepts/string-functions/terms/strtoupper/strtoupper.md.

Closes #2436 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-10 21:07 UTC, caupolicandiaz requested changes
@Jess-G95 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-10 21:07 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/strtoupper/strtoupper.md
> +## Codebyte
```suggestion
## Example
```

2023-07-10 21:07 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/strtoupper/strtoupper.md
> +## Codebyte
generally we include one or more standard examples (depending on the entry) and zero or more codebytes (these are not always part of an entry)

2023-07-10 21:07 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/strtoupper/strtoupper.md
> +The following code is runnable to show how `strtoupper()` alters the string.
```suggestion
The following code demonstrates the use of `strtoupper()` to alter a string.
```

2023-07-10 21:07 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/strtoupper/strtoupper.md
> +```codebyte/php
```suggestion
```php
```

2023-07-10 21:07 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/strtoupper/strtoupper.md
> +```
include a ```shell block with the output preceded by a sentence such as: "The code results in the following:"

2023-07-11 10:58 UTC, Jess-G95 commented
@caupolicandiaz thanks, I have addressed your comments and made the changes.

2023-07-12 19:24 UTC, SSwiniarski approved these changes
@Jess-G95 Looks good to go.

2023-07-12 19:25 UTC, merged

2023-07-12 19:33 UTC, SSwiniarski commented
@Jess-G95 Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/php/string-functions/strtoupper

![image](https://github.com/Codecademy/docs/assets/86081858/0952d743-c3e9-4b68-8baa-e1ddd89b7ae2)