[Term Entry] JavaScript Array.prototype.some() #2658
Codecademy/docs pull request #2722
Opened 2023-07-11 05:15 UTC by Elimodo

explanation and example on how to use the .some() method in javascript

### Description

### Type of Change

- Adding a new entry

### Checklist

- [yes ] All writings are my own.
- [yes ] My entry follows the Codecademy Docs style guide.
- [yes ] My changes generate no new warnings.
- [ yes] I have performed a self-review of my own writing and code.
- [yes ] I have checked my entry and corrected any misspellings.
- [yes ] I have made corresponding changes to the documentation if needed.
- [yes ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ yes] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ yes] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-11 05:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2722) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2722) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2722) it.</sub>

2023-07-11 22:03 UTC, caupolicandiaz requested changes
@Elimodo I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-11 22:03 UTC, caupolicandiaz commented on javascript-array-prototype-some().md
> +Check whether any value in an array is over 5
```suggestion
## Example

The example below checks whether any value in an array is over 5:
```

2023-07-11 22:03 UTC, caupolicandiaz commented on javascript-array-prototype-some().md
> + ```codebyte/javascript
```suggestion
 ```javascript
```

2023-07-11 22:03 UTC, caupolicandiaz commented on javascript-array-prototype-some().md
> + ```codebyte/javascript
it would be more explicit if the code actually prints something to the console

2023-07-11 22:03 UTC, caupolicandiaz commented on javascript-array-prototype-some().md
> +### Output
```suggestion

This result in the following output:

```shell
// add the appropriate output here
```

2023-07-12 14:27 UTC, SSwiniarski commented
@Elimodo, @caupolicandiaz We may have to close this PR, as there is already an entry for this: https://www.codecademy.com/resources/docs/javascript/arrays/some

I think the issue must have been posted by mistake.

2023-07-12 16:56 UTC, closed without merging