[Term Entry] PHP Arrays array_fill()
Codecademy/docs pull request #2723
Opened 2023-07-11 08:23 UTC by EspressoCat

### Description

- Added array_fill() term for PHP
- Closes issue #2556 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-11 21:45 UTC, caupolicandiaz requested changes
@EspressoCat I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-11 21:45 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-fill/array-fill.md
> +Description: 'This function fills an array with values and returns a filled array.'
```suggestion
Description: 'Fills an array with values and returns a filled array.'
```

2023-07-11 21:45 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-fill/array-fill.md
> +  - 'Web Development'
```suggestion
```

2023-07-11 21:45 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-fill/array-fill.md
> +  - 'Web Development'
subjects should only contain two items

2023-07-11 21:45 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-fill/array-fill.md
> +- `$start_index`: This parameter specifies the first `index` of the returned array.
```suggestion
- `$start_index`: This parameter specifies the first index of the returned array.
```

2023-07-11 21:45 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-fill/array-fill.md
> +- `$number_elements`: This parameter refers to the `number` of elements to insert into the array.
```suggestion
- `$number_elements`: This parameter refers to the number of elements to insert into the array.
```

2023-07-11 21:45 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-fill/array-fill.md
> +- `$values`: Specifies the `value` to be used to fill the array.
```suggestion
- `$values`: Specifies the values to be used to fill the array.
```

2023-07-11 21:45 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-fill/array-fill.md
> +- `$start_index`: This parameter specifies the first `index` of the returned array.
generally elements that are being referenced in a code block such as a variable name or function should use backticks. Generic terms for elements do not have to be formatted.

2023-07-11 21:45 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-fill/array-fill.md
> +
remove empty lines in the code block

2023-07-12 04:51 UTC, EspressoCat commented
Thanks for the feedback @caupolicandiaz I made the requested changes.

2023-07-12 16:44 UTC, caupolicandiaz approved these changes
@EspressoCat Looks good. I'm passing this on for a second review.

2023-07-12 18:13 UTC, SSwiniarski approved these changes
@EspressoCat I made one minor edit and it looks ok to merge.

2023-07-12 18:14 UTC, merged

2023-07-12 18:19 UTC, SSwiniarski commented
@EspressoCat Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/php/arrays/array-fill

![image](https://github.com/Codecademy/docs/assets/86081858/0c520c79-e9a5-48fe-b2f5-1929dc95dbf2)

2023-07-12 18:30 UTC, EspressoCat commented
Thank you for taking the time to check the code @SSwiniarski ;)