Created atan2() reference function for php
Codecademy/docs pull request #2724
Opened 2023-07-11 10:15 UTC by arisdelacruz

### Description

This is an attempt to create the ATAN2() reference function for php. Motivation comes from the aspiration to eventually become a regular contributor to codecademy docs.

### Type of Change

- Adding a new entry

### Checklist

- [ /] All writings are my own.
- [ /] My entry follows the Codecademy Docs style guide.
- [ /] My changes generate no new warnings.
- [ /] I have performed a self-review of my own writing and code.
- [ /] I have checked my entry and corrected any misspellings.
- [ /] I have made corresponding changes to the documentation if needed.
- [ /] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ /] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ /] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-11 21:35 UTC, caupolicandiaz requested changes
@arisdelacruz I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-11 21:35 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/atan2/atan2.md
> +Description: 'The atan2() function returns the arc tangent of y/x, in radians.'
```suggestion
Description: 'Returns the arc tangent of y/x, in radians.'
```

2023-07-11 21:35 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/atan2/atan2.md
> +The `atan2()` function has two (2) parameters. It returns the arc tangent of y/x, in radians. Where x and y are the coordinates of a point (x,y). Both specify a positive or negative number.
```suggestion
The `atan2()` function has two (2) parameters. It returns the arc tangent of *y/x*, in radians. Where `x` and `y` are the coordinates of a point (x, y). Both specify a positive or negative number.
```

2023-07-11 21:35 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/atan2/atan2.md
> +The **`atan2()`** function returns the arc tangent of y/x, in radians.
```suggestion
The **`atan2()`** function returns the arc tangent of *y/x*, in radians.
```

2023-07-11 21:35 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/atan2/atan2.md
> +## Codebyte Example
```suggestion
## Example
```

2023-07-11 21:35 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/atan2/atan2.md
> +```codebyte/php
```suggestion
```php
```

2023-07-11 21:35 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/atan2/atan2.md
> +The output is -0.89605538457134
```suggestion
This results in the following output:

```shell
 -0.89605538457134
 ```

```

2023-07-12 05:29 UTC, arisdelacruz commented
@caupolicandiaz 

done

thanks

2023-07-12 16:37 UTC, caupolicandiaz approved these changes
@arisdelacruz Looks good. I'm passing this on to a second review.

2023-07-12 18:05 UTC, SSwiniarski approved these changes
@arisdelacruz Looks good to go.

2023-07-12 18:09 UTC, merged

2023-07-12 18:17 UTC, SSwiniarski commented
@arisdelacruz Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/php/math-functions/atan2

![image](https://github.com/Codecademy/docs/assets/86081858/fc2fa9d4-fcc1-4607-89a3-3484c2375db6)