[Term Entry] PHP Date function date_sub()
Codecademy/docs pull request #2730
Opened 2023-07-12 18:15 UTC by EspressoCat

### Description

Added date_sub() term for PHP
Closes issue #2553 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR

2023-07-12 21:38 UTC, caupolicandiaz requested changes
@EspressoCat I've completed my initial review. Please update the entry, and tag me when you've finished making the changes. Thanks

2023-07-12 21:38 UTC, caupolicandiaz commented on content/php/concepts/date-functions/terms/date-sub/date-sub.md
> +- `$object`: This parameter specifies the DateTime object returned by date_create().
```suggestion
- `$object`: This parameter specifies the `DateTime` object returned by `date_create()`.
```

2023-07-12 21:38 UTC, caupolicandiaz commented on content/php/concepts/date-functions/terms/date-sub/date-sub.md
> +- `$interval`: This parameter specifies the DateInterval object which we want to subtract.
```suggestion
- `$interval`: This parameter specifies the `DateInterval` object to be subtracted.
```

2023-07-12 21:38 UTC, caupolicandiaz commented on content/php/concepts/date-functions/terms/date-sub/date-sub.md
> +- `$interval`: This parameter specifies the DateInterval object which we want to subtract.
we avoid the use of first and second person pronouns (I, you, we) in docs

2023-07-12 21:38 UTC, caupolicandiaz commented on content/php/concepts/date-functions/terms/date-sub/date-sub.md
> +The `date_sub()` function returns a DateTime object after subtracting the interval.
```suggestion
The `date_sub()` function returns a `DateTime` object after subtracting the interval.
```

2023-07-12 21:38 UTC, caupolicandiaz commented on content/php/concepts/date-functions/terms/date-sub/date-sub.md
> +The following example uses the `date_sub()` function to subtract 30 days from the 3 March, 2023:
```suggestion
The following example uses the `date_sub()` function to subtract 30 days from the passed date:
```

2023-07-12 21:38 UTC, caupolicandiaz commented on content/php/concepts/date-functions/terms/date-sub/date-sub.md
> +- `$object`: This parameter specifies the DateTime object returned by date_create().
generally we use backticks on specific terms, functions, symbols specific to the code shown or language. If it's a generic term such as arrays or classes I would omit the backticks.

2023-07-13 05:02 UTC, EspressoCat commented
Thanks for the feedback @caupolicandiaz I made the requested changes.

2023-07-13 17:01 UTC, caupolicandiaz approved these changes
@EspressoCat I just reverted the changes on array-fill, they shouldn't be part of this PR. Looks good for a second review.

2023-07-15 14:43 UTC, SSwiniarski approved these changes
@EspressoCat Looks good to me.

2023-07-15 14:45 UTC, merged

2023-07-15 14:58 UTC, SSwiniarski commented
@EspressoCat Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/php/date-functions/date-sub

![image](https://github.com/Codecademy/docs/assets/86081858/39622855-1a94-4669-9293-8f07048325e9)