Crom my contribution
Codecademy/docs pull request #2731
Opened 2023-07-12 22:59 UTC by csrordzhn

### Description

Addiing a new term entry for trojan under the malware section, #2688 
### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-12 22:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2731) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2731) before we can accept your contribution.<br/><hr/>**Cesar Ordonez** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2731) it.</sub>

2023-07-13 09:28 UTC, dakshdeepHERE requested changes
I change from my side and I have one more comment to make in overall entry

2023-07-13 09:28 UTC, dakshdeepHERE commented on content/cybersecurity/concepts/malware/terms/trojan/trojan.md
> +Description: 'A trojan is a type of malware that downloads onto a computer disguised as a legitimate program.'
```suggestion
Description: 'A type of malicious software that appears harmless but secretly carries out harmful actions on a computer system'
```

2023-07-13 09:31 UTC, dakshdeepHERE commented
Your entry is very similar and matches word to word from these websites [**1**](https://www.fortinet.com/resources/cyberglossary/trojan-horse-virus#:~:text=Trojans%20can%20also%20attack%20and,using%20it%20to%20launch%20cyberattacks.) [**2**](https://www.fortinet.com/resources/cyberglossary/trojan-horse-virus) 
<img width="1517" alt="Screenshot 2023-07-13 at 2 55 47 PM" src="https://github.com/Codecademy/docs/assets/94860622/2457acb3-cdbd-4384-aea0-609e6b22debb">
<img width="1603" alt="Screenshot 2023-07-13 at 2 57 05 PM" src="https://github.com/Codecademy/docs/assets/94860622/85c92c09-c77f-4d9a-b52a-d31bca35f855">
You can try to rephrase the content so it doesn't flag it as plagiarised content to fix this issue 🙂.

2023-07-13 16:06 UTC, SSwiniarski commented
As @dakshdeepHERE mentioned, this PR entry is copied from [here](https://www.fortinet.com/resources/cyberglossary/trojan-horse-virus).
We take plagiarism seriously for Codecademy Docs and for Codecademy content in general because a single case of plagiarism could jeopardize the credibility of all other 650+ entries as well as our greater catalog.
Here's the Codecademy Docs [Code of Conduct](https://github.com/yangc95/docs/blob/main/.github/CODE_OF_CONDUCT.md) on GitHub.
Since this is your first occurrence, I am issuing a warning.
We truly appreciate your help with your contribution so far and we don't want to lose you temporarily or permanently. But as we attempt to build the best coding documentation on the web, it's a long-term game and we want to focus on quality, not quantity!
We hope you understand why we are taking this very seriously.

Needless to say this entry cannot be considered until it is rewritten.

2023-07-17 16:08 UTC, csrordzhn commented
Got it. I apologize for this and thanks for the warning. I will work on this issue this week.

2023-08-10 16:35 UTC, SSwiniarski commented
@csrordzhn Because of the inactivity on this I am closing this PR.

2023-08-10 16:35 UTC, closed without merging