Add removeItem term entry
Codecademy/docs pull request #2737
Opened 2023-07-13 14:22 UTC by braanj

### Description

### Type of Change

Add the removeItem term entry to javascript.

- Adding a new entry

### Checklist

- [ x] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-13 14:38 UTC, braanj commented
@SSwiniarski Hello, plz review my PR

2023-07-13 19:22 UTC, caupolicandiaz requested changes
@braanj I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-13 19:22 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/removeItem/removeItem.md
> +Title: 'removeItem()'
```suggestion
Title: '.removeItem()'
```

2023-07-13 19:22 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/removeItem/removeItem.md
> +When called, the `removeItem()` method takes a single parameter, which is the key of the item to be removed. It searches for the key in the storage and, if found, removes the associated key-value pai
```suggestion
When called, the `.removeItem()` method takes a single parameter, `keyName`, which is the key of the item to be removed. The function removes the associated key-value pair from storage, if found. If the key does not exist, the method does nothing and the storage remains unchanged.
```

2023-07-13 19:22 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/removeItem/removeItem.md
> +When called, the `removeItem()` method takes a single parameter, which is the key of the item to be removed. It searches for the key in the storage and, if found, removes the associated key-value pai
I'd recommend putting the description after the syntax block

2023-07-13 19:22 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/removeItem/removeItem.md
> +The following code demonstrates the application of `removeItem()` on the localeStorage:
```suggestion
The following code demonstrates the application of `.removeItem()` to modify `localStorage`:
```

2023-07-13 19:22 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/removeItem/removeItem.md
> +In the example above, a key-value pair (`username`, `JohnDoe`) is added to the localeStorage using `setItem()`, and removed using `removeItem()`.
```suggestion
In the example above, a key-value pair (`username`, `JohnDoe`) is added to the `localStorage` using `.setItem()`, and removed using `.removeItem()`.
```

2023-07-13 19:22 UTC, caupolicandiaz commented on content/javascript/concepts/storage/terms/removeItem/removeItem.md
> +Similarly, you can do the same for the session storage:
```suggestion
The same can be done with the session storage:
```

2023-07-14 10:00 UTC, braanj commented
@caupolicandiaz Thanks for the review. Changes made!

2023-07-14 17:10 UTC, caupolicandiaz approved these changes
@braanj This is ready for a second review.

2023-07-15 14:05 UTC, SSwiniarski approved these changes
@braanj this looks goo to merge once the "Storage" entry is added.

2023-07-17 11:26 UTC, braanj commented
@SSwiniarski Thanks for the review

2023-08-02 15:55 UTC, merged

2023-08-02 16:06 UTC, SSwiniarski commented
@braanj Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/javascript/storage/removeItem

![image](https://github.com/Codecademy/docs/assets/86081858/803a6bc2-3ea7-4051-9c79-cb639dd649e4)