Add switch concept entry
Codecademy/docs pull request #2739
Opened 2023-07-13 16:02 UTC by braanj

### Description

Add a concept entry: switch()

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-13 20:12 UTC, caupolicandiaz requested changes
@braanj I've added my comments. Please update the entry, and tag me when you've finished making the changes. Thanks

2023-07-13 20:12 UTC, caupolicandiaz commented on content/r/concepts/switch/switch.md
> +In this case, if the value of month does not match any of the specified cases, the default case "Unknown month" is returned and assigned to the variable season.
```suggestion
In this scenario, if the value of month does not match any of the specified cases, the default case `"Unknown month"` is returned and assigned to the variable `season`.
```

2023-07-13 20:12 UTC, caupolicandiaz commented on content/r/concepts/switch/switch.md
> +In this case, if the value of month does not match any of the specified cases, the default case "Unknown month" is returned and assigned to the variable season.
looks like in this case it returns null in lieu of the default.

2023-07-14 11:08 UTC, braanj commented on content/r/concepts/switch/switch.md
> +```pseudo
Done!

2023-07-14 11:09 UTC, braanj commented
@caupolicandiaz  Changes made!

2023-07-14 17:07 UTC, caupolicandiaz approved these changes
@braanj Looks good. This is ready for a second review.

2023-08-24 20:28 UTC, merged