Add vim modes subsection to commandline/vim.md doc
Codecademy/docs pull request #2740
Opened 2023-07-13 23:24 UTC by hakanergul

### Description

Vim modes (`command`, `insert` and `visual`) are added to `content/command-line/concepts/vim/vim.md` file. I just add a brief description for these modes. 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x ] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-13 23:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2740) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2740) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2740) it.</sub>

2023-07-15 13:59 UTC, SSwiniarski requested changes
@hakanergul I did a review and had one comment, mostly about formatting.

2023-07-15 13:59 UTC, SSwiniarski commented on content/command-line/concepts/vim/vim.md
> ++ `VISUAL MODE` : *Highlight, select and edit text*
```suggestion
- `COMMAND MODE` : Execute commands like undo, redo, find, replace, quit, etc.
- `INSERT MODE` : Type and edit text.
- `VISUAL MODE` : Highlight, select and edit text.
```

2023-07-15 17:38 UTC, hakanergul commented
@SSwiniarski thank you. I committed the changes👍

2023-07-16 13:05 UTC, SSwiniarski approved these changes
@hakanergul I made one small change and it looks ready for a second review.

2023-07-17 22:19 UTC, caupolicandiaz approved these changes
@hakanergul @SSwiniarski LGTM. Just made some minor edits, mostly on the existing text describing the features of vim.

2023-07-18 11:04 UTC, merged

2023-07-18 11:05 UTC, SSwiniarski commented
@hakanergul congrats on the new edit,

Live link: https://www.codecademy.com/resources/docs/command-line/vim