New term entry for PHP about the strpos() function
Codecademy/docs pull request #2748
Opened 2023-07-14 13:49 UTC by Judis07

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-14 13:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2748) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2748) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Judis07<br/>:x: Arvind M<br/><hr/>**Arvind M** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2748) it.</sub>

2023-07-14 17:38 UTC, caupolicandiaz commented
@Judis07 This entry was recently completed by another contributor. Please look for another issue to work on. Thanks
https://github.com/Codecademy/docs/pull/2618

2023-07-14 17:57 UTC, Judis07 commented
Hi, please correct if I am wrong. I think #2618 is for another method called stripos() while this issue is for strpos()? While both method are very much similar but one is case sensitive and the other one case insensitive. Thanks

2023-07-14 19:12 UTC, caupolicandiaz commented
> Hi, please correct if I am wrong. I think #2618 is for another method called stripos() while this issue is for strpos()? While both method are very much similar but one is case sensitive and the other one case insensitive. Thanks

My mistake.

2023-07-14 20:38 UTC, caupolicandiaz requested changes
@Judis07 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-14 20:38 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/strops/strops.md
> +  - 'Web Development'
```suggestion
```

2023-07-14 20:38 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/strops/strops.md
> +  - 'Web Development'
only two items are permitted under subjects

2023-07-14 20:38 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/strops/strops.md
> +---
Please review our standards and update the metadata, and spacing formatting.

2023-07-14 20:38 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/strops/strops.md
> +Description: 'Returns the position of the first occurrence of a string inside another string. It is a case-sensitive function'
```suggestion
Description: 'Performs a case-sensitive search for the first occurrence of a substring in a given string.'
```

2023-07-14 20:38 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/strops/strops.md
> +## Codebyte
This is essentially the same example. Codebytes should not duplicate other examples within the entry. Please revise the example or delete it.

2023-07-15 06:16 UTC, Judis07 commented
Hello @caupolicandiaz, I have made the changes you suggested. Please review them. 
Thanks

2023-07-17 16:02 UTC, Judis07 commented
@caupolicandiaz please let me know if you need any new changes from my end

2023-07-17 19:36 UTC, caupolicandiaz approved these changes
@Judis07 Overall, this looks good. There were changes to the metadata that were still missing, which I added (please review for future reference). I also made some edits to the example. This is ready for a second review.

2023-07-19 13:51 UTC, Judis07 commented
@caupolicandiaz Do let me know if anything needs to be done from my end. Thanks

2023-07-19 17:05 UTC, caupolicandiaz commented
> @caupolicandiaz Do let me know if anything needs to be done from my end. Thanks

The next step is for another maintainer to review this entry. If they have any suggestions you will need to make additional edits to complete this submission.

2023-07-20 16:14 UTC, SSwiniarski approved these changes
@Judis07 Looks good.

2023-07-20 16:17 UTC, merged

2023-07-20 16:21 UTC, SSwiniarski commented
@Judis07 Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/php/string-functions/strops

![image](https://github.com/Codecademy/docs/assets/86081858/cf6231ae-e55b-447c-8281-c146bf5deecd)

2023-07-20 16:24 UTC, SSwiniarski commented
@Judis07 I've noticed there is a typo in the filename. Can you submit a new PR that changes the path from `content/php/concepts/string-functions/terms/strops/strops.md` to `content/php/concepts/string-functions/terms/strpos/strpos.md`

2023-07-20 16:33 UTC, Judis07 commented
@SSwiniarski sure, I will submit a new PR with this fix.