add ruby-text element entry
Codecademy/docs pull request #2769
Opened 2023-07-16 16:07 UTC by gs-Hani

### Description

Added a new entry "The Ruby Text element".

### Type of Change

- Adding a new entry

### Checklist

- [ x] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-16 16:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2769) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2769) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2769) it.</sub>

2023-07-16 16:45 UTC, SSwiniarski requested changes
@gs-Hani I did a first review and left a couple of comments.

2023-07-16 16:45 UTC, SSwiniarski commented on content/html/concepts/semantic-html/terms/ruby-text/ruby-text.md
> +Title: '<ruby-text>'
```suggestion
Title: '<rt>'
```

2023-07-16 16:45 UTC, SSwiniarski commented on content/html/concepts/semantic-html/terms/ruby-text/ruby-text.md
> +The **`<rt>`** semantic HTML element represents the [ruby](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby) text component of a ruby annotation, this provides pronunciation, translatio
```suggestion
The **`<rt>`** semantic HTML element represents the ruby text component of a ruby annotation, this provides pronunciation, translation, or transliteration information for East Asian typography. The `<rt>` element must be contained within a `<ruby>` element at all times.
```
We generally discourage linking to outside documentation.

2023-07-17 16:23 UTC, SSwiniarski approved these changes
@gs-Hani looks good for a second review.

2023-07-17 21:39 UTC, caupolicandiaz requested changes
@gs-Hani I've completed my review. Please update, and tag me when you've finished the changes. Thanks.

2023-07-17 21:39 UTC, caupolicandiaz commented on content/html/concepts/semantic-html/terms/ruby-text/ruby-text.md
> +Title: '<rt>'
Looks like this path is incorrect. The folder and filename should use the tag, "rt". So, it should be:
.../terms/rt/rt.md

2023-07-17 21:39 UTC, caupolicandiaz commented on content/html/concepts/semantic-html/terms/ruby-text/ruby-text.md
> +Description: 'Used to provide pronunciation, translation, or transliteration information for East Asian typography.'
This description is a very close to a verbatim copy of the Mozilla documentation. I would suggest rephrasing this to differentiate it further. Also the example used below is the same as in the Mozilla version. All docs content must be original. Please revise with an example you have developed.

2023-07-18 07:33 UTC, gs-Hani commented
entry updated based on feedback @caupolicandiaz

2023-07-18 16:58 UTC, caupolicandiaz approved these changes
@gs-Hani @SSwiniarski This is good to merge. I did make some additional edits to further differentiate this entry. In the future I would recommend writing the entry on your own, in your own words. And after completing your draft you might want to look at other references to see if you're missing any information or need to make some other corrections.

2023-07-19 06:08 UTC, gs-Hani commented
thank you for the advice @caupolicandiaz, I enjoyed this project, I was asked to share where did I hear about the docs, it is part of the Git course on Codecademy.
Is there anything else left for me to do?

2023-07-19 16:18 UTC, merged

2023-07-19 16:33 UTC, SSwiniarski commented
@gs-Hani Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/html/semantic-html/rt

![image](https://github.com/Codecademy/docs/assets/86081858/fdfd9358-7f9c-40a2-9190-4dc1398ef5d6)

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.

2023-07-25 20:16 UTC, yangc95 commented on content/html/concepts/semantic-html/terms/rt/rt.md
> +```pseudo
@gs-Hani I think you meant to make this an html block rather than a pseudo block

Feel free to open an enhancement or edit PR