fmod.md for PHP
Codecademy/docs pull request #2772
Opened 2023-07-17 03:48 UTC by arisdelacruz

### Description

This is my attempt to create a reference for the fmod() function in PHP. Motivation stems from the sustained momentum of contributing to docs and sticking with the primary goal of helping others.

### Type of Change

- Adding a new entry

### Checklist

- [ /] All writings are my own.
- [ /] My entry follows the Codecademy Docs style guide.
- [ /] My changes generate no new warnings.
- [ /] I have performed a self-review of my own writing and code.
- [ /] I have checked my entry and corrected any misspellings.
- [ /] I have made corresponding changes to the documentation if needed.
- [ /] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ /] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ /] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-17 20:52 UTC, caupolicandiaz requested changes
@arisdelacruz Just a few minor edits. Please update, and tag me when complete.

2023-07-17 20:52 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/fmod/fmod.md
> +The **`fmod()`** function returns the remainder (Modulo) of x/y. It stands for Floating Modulo and calculates the Modulo of any division which may contain a `float` as both dividend and divisor.
```suggestion
The **`fmod()`** function returns the remainder (modulo) of *x/y*. The name stands for "floating modulo" and the function calculates the modulo of any division which may contain a `float` as both dividend and divisor.
```

2023-07-18 01:27 UTC, arisdelacruz commented
@caupolicandiaz 

just completed

thanks, buddy

2023-07-18 16:35 UTC, caupolicandiaz approved these changes
@arisdelacruz Looks good. I'm passing this on to a second review.

2023-07-20 16:05 UTC, SSwiniarski approved these changes
@arisdelacruz Looks good.

2023-07-20 16:10 UTC, merged

2023-07-20 16:16 UTC, SSwiniarski commented
@arisdelacruz Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/php/math-functions/fmod

![image](https://github.com/Codecademy/docs/assets/86081858/64ac16ae-1f5c-44d7-a1ff-bc6a71dd8bd6)