2775 fix typo
Codecademy/docs pull request #2776
Opened 2023-07-17 09:07 UTC by droffilc1

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-18 15:59 UTC, SSwiniarski requested changes
@droffilc1 only one comment. Remove the extra file from the prior PR.

2023-07-18 15:59 UTC, SSwiniarski commented on content/html/concepts/semantic-html/terms/ruby/ruby.md
Remove this file from this PR.

2023-07-18 16:19 UTC, droffilc1 commented on content/html/concepts/semantic-html/terms/ruby/ruby.md
Okay.

2023-07-19 16:07 UTC, SSwiniarski approved these changes
@droffilc1 Looks good. Sending it for review two.

2023-07-20 17:31 UTC, caupolicandiaz approved these changes
@droffilc1 @SSwiniarski LGTM

2023-07-20 17:33 UTC, merged