Array.prototype.at() method added
Codecademy/docs pull request #2777
Opened 2023-07-17 10:19 UTC by sumitdethe27

### Description
Issue: #2660 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-17 21:15 UTC, caupolicandiaz requested changes
@sumitdethe27 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-17 21:15 UTC, caupolicandiaz commented on content/javascript/concepts/arrays/terms/at/at.md
> +Description: 'Return the element at a specified index in an array.'
```suggestion
Description: 'Returns the element at a specified index in an array.'
```

2023-07-17 21:15 UTC, caupolicandiaz commented on content/javascript/concepts/arrays/terms/at/at.md
> +The **`.at()`** method in JavaScript is used to return the element at a specified index in an array. The index can be either positive or negative, and negative indices count from the end of the array
```suggestion
The **`.at()`** method in JavaScript is used to return the element at a specified index in an array. The index can be either positive or negative (negative indices count from the end of the array).
```

2023-07-17 21:15 UTC, caupolicandiaz commented on content/javascript/concepts/arrays/terms/at/at.md
> +```js
```suggestion
```pseudo
```

2023-07-17 21:15 UTC, caupolicandiaz commented on content/javascript/concepts/arrays/terms/at/at.md
> +- `index`:The element at the specified `index` is the one intended to be returned.
```suggestion
- `index`: The index value of the element to be returned.
```

2023-07-17 21:15 UTC, caupolicandiaz commented on content/javascript/concepts/arrays/terms/at/at.md
> +## Example 1
```suggestion
## Example 
```

2023-07-17 21:15 UTC, caupolicandiaz commented on content/javascript/concepts/arrays/terms/at/at.md
> +
There should be an introductory sentence here such as:
The following code demonstrates a basic implementation of `.at()`:

2023-07-17 21:15 UTC, caupolicandiaz commented on content/javascript/concepts/arrays/terms/at/at.md
> +## Codebyte Example
The Codecademy infrastructure does not currently support this function, so the codebyte will result in an error. Please delete this example

2023-07-25 14:37 UTC, sumitdethe27 commented
@caupolicandiaz i have made changes

2023-07-25 17:31 UTC, caupolicandiaz approved these changes
@sumitdethe27 Just made one small edit regarding the example intro. Looks good for a second review.

2023-07-30 15:25 UTC, SSwiniarski approved these changes
@sumitdethe27 Looks good.

2023-07-30 15:26 UTC, merged

2023-07-30 15:35 UTC, SSwiniarski commented
@sumitdethe27 Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/javascript/arrays/at

![image](https://github.com/Codecademy/docs/assets/86081858/f4664823-cd08-4033-ba2b-fd76e5d256f7)