proof by strong induction term entry
Codecademy/docs pull request #2780
Opened 2023-07-17 19:46 UTC by sreeharsha-rav

### Description

Created a term entry for proof by strong induction.

### Type of Change

- Added description about proof by strong induction
- Described steps for performing proof by strong induction
- Illustrated an example for proof by strong induction
- Included a Python codebyte to implement given example

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-17 19:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2780) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2780) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2780) it.</sub>

2023-07-27 02:44 UTC, sreeharsha-rav commented
@KTom101 I made the pull request, is there anything to be done on my side?

2023-08-10 16:01 UTC, SSwiniarski requested changes
@sreeharsha-rav Sorry for the delay. I did a first review and left a few comments.

2023-08-10 16:01 UTC, SSwiniarski commented on content/discrete-math/concepts/proofs/terms/proof-by-strong-induction/proof-by-strong-induction.md
> +```
```suggestion
```
I don't think the codebyte is adding anything to this entry.

2023-08-10 18:19 UTC, sreeharsha-rav commented
@SSwiniarski I committed the requested changes, thanks for your review.

2023-08-11 11:29 UTC, SSwiniarski approved these changes
@sreeharsha-rav looks good for a second review.

2023-08-21 23:39 UTC, KTom101 requested changes
@sreeharsha-rav I added some changes to this entry.

2023-08-21 23:39 UTC, KTom101 commented on content/discrete-math/concepts/proofs/terms/proof-by-strong-induction/proof-by-strong-induction.md
> +```
```suggestion
```plaintext
```

2023-08-21 23:39 UTC, KTom101 commented on content/discrete-math/concepts/proofs/terms/proof-by-strong-induction/proof-by-strong-induction.md
> +```
```suggestion
```plaintext
```

2023-08-21 23:39 UTC, KTom101 commented on content/discrete-math/concepts/proofs/terms/proof-by-strong-induction/proof-by-strong-induction.md
> +```
```suggestion
```plaintext
```

2023-08-21 23:39 UTC, KTom101 commented on content/discrete-math/concepts/proofs/terms/proof-by-strong-induction/proof-by-strong-induction.md
> +                       = k + 1  [Substitute from x = k, we know that 2(k-1) - (k-2) = k]
```suggestion
                       = k + 1  [Substituting from x = k, which states that 2(k-1) - (k-2) = k]
```

2023-08-21 23:39 UTC, KTom101 commented on content/discrete-math/concepts/proofs/terms/proof-by-strong-induction/proof-by-strong-induction.md
> +Then at x = k+1, we need to prove that 2((k+1)-1) - ((k+1)-2) = k+1
avoid using the pronoun "we"
```suggestion
Then at x = k+1, prove that 2((k+1)-1) - ((k+1)-2) = k+1
```

2023-08-23 14:40 UTC, sreeharsha-rav commented
@KTom101 I committed the requested changes. Thanks for your review.

2023-08-23 19:12 UTC, KTom101 approved these changes
@sreeharsha-rav Looks good, I just ran `npm run format:all` to fix the failed [checks](https://www.codecademy.com/resources/docs/contribution-guide/getting-set-up-on-your-computer#:~:text=There%20are%20continuous%20integration%20(CI)%20workflows).

2023-08-23 19:14 UTC, merged