Create [Term Entry] SQL Math Functions EXP
Codecademy/docs pull request #2781
Opened 2023-07-18 01:22 UTC by andyguo0228

### Description

- Added SQL math function for `EXP()`
- Closes issue #2258 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-18 01:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2781) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2781) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2781) it.</sub>

2023-07-18 16:31 UTC, SSwiniarski requested changes
@andyguo0228 I did a first review and left a few comments.

2023-07-18 16:31 UTC, SSwiniarski commented on content/sql/concepts/math-functions/terms/exp/exp.md
> +**`EXP()`** is a mathematical function in SQL that returns the value of **e** raised to the power of a given `number`. Where **e** is the base of natural logarithms, a mathematical constant equal to
```suggestion
**`EXP()`** is a mathematical function in SQL that returns the value of _e_ raised to the power of a given number. Where _e_ is the base of natural logarithms, a mathematical constant equal to approximately 2.71828.
```

2023-07-18 16:31 UTC, SSwiniarski commented on content/sql/concepts/math-functions/terms/exp/exp.md
> +```sql
This should be a ` ```pseudo ` code block, and should show the function outside any `SELECT` statements, `SELECT` is not a part of the syntax of `EXP()`

Also follow the code block with a sentence describing what `number` is in the example.

2023-07-18 16:31 UTC, SSwiniarski commented on content/sql/concepts/math-functions/terms/exp/exp.md
> +The `EXP()` function is used to return the value of e raised to the power of the `num` column:
```suggestion
The `EXP()` function is used to return the value of _e_ raised to the power of the `num` column:
```

2023-07-19 01:37 UTC, andyguo0228 commented
@SSwiniarski I applied the recommended changes.

2023-07-19 16:30 UTC, SSwiniarski approved these changes

2023-07-19 20:51 UTC, caupolicandiaz requested changes
@andyguo0228 Just one comment. Please update the entry, and tag me when you've made the changes. Thanks

2023-07-19 20:51 UTC, caupolicandiaz commented on content/sql/concepts/math-functions/terms/exp/exp.md
> +**`EXP()`** is a mathematical function in SQL that returns the value of _e_ raised to the power of a given number. Where _e_ is the base of natural logarithms, a mathematical constant equal to approx
```suggestion
**`EXP()`** is a mathematical function in SQL that returns the value of _e_ raised to the power of a given number. Where _e_ is a mathematical constant equal to approximately 2.71828, which is the base used in the determination of natural logarithms.
```

2023-07-20 17:16 UTC, caupolicandiaz approved these changes
@andyguo0228 @SSwiniarski LGTM

2023-07-21 11:51 UTC, merged

2023-07-21 12:00 UTC, SSwiniarski commented
@andyguo0228 Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/sql/math-functions/exp

![image](https://github.com/Codecademy/docs/assets/86081858/57d07274-281d-4a08-86d5-a88dffe06ce9)

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.