[Term Entry] PHP Math Functions base_convert()
Codecademy/docs pull request #2782
Opened 2023-07-18 12:29 UTC by EspressoCat

### Description

Added base_convert() term for PHP
Closes issue #2503 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-18 16:35 UTC, SSwiniarski requested changes
@EspressoCat I did a first review and only had one comment to clarify the syntax.

2023-07-26 12:14 UTC, EspressoCat commented
hey @codecademy-docs 👋🏻 

Let me know if requested changes are ok. Thanks!

2023-07-26 22:08 UTC, caupolicandiaz requested changes
@EspressoCat I've added a few comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-26 22:08 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/base-convert/base-convert.md
> +The **`base_convert()`** converts a number from one number base to another.
```suggestion
The **`base_convert()`** function converts a number from one base system to another.
```

2023-07-26 22:08 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/base-convert/base-convert.md
> +base_convert(string $number, int $frombase, int $tobase): string
```suggestion
base_convert($number, $fromBase, $toBase)
```

2023-07-26 22:08 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/base-convert/base-convert.md
> +- `$frombase`: Specifies the original base of number.
```suggestion
- `$fromBase`: Specifies the original base of `$number` as an integer.
```

2023-07-26 22:08 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/base-convert/base-convert.md
> +- `$tobase`: Specifies the base to convert to.
```suggestion
- `$tobase`: Specifies the base to convert to as an integer.
```

2023-07-27 12:21 UTC, EspressoCat commented
Thanks for the comments @caupolicandiaz . 

Made requested changes to the entry.

2023-07-27 16:32 UTC, merged

2023-07-27 16:39 UTC, SSwiniarski commented
@EspressoCat Congrats on the new entry! Live link here:https://www.codecademy.com/resources/docs/php/math-functions/base-convert

![image](https://github.com/Codecademy/docs/assets/86081858/90a3cd30-bb8f-484f-8d64-6dc1e66361aa)