[Term Entry] Cybersecurity Malware Rootkit
Codecademy/docs pull request #2788
Opened 2023-07-19 17:30 UTC by frhadjmli

### Description

- Add Rootkit term for cybersecurity
- closes issue #2690 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-22 14:38 UTC, SSwiniarski requested changes
@frhadjmli I did a first review and left a few comments.

2023-07-22 14:38 UTC, SSwiniarski commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +Description: 'Rootkit is a type of malware and a program, or a collection of software tools, covertly grants cybercriminals the ability to gain remote access on a targeted computer or system.'
```suggestion
Description: 'A Rootkit is a program, or a collection of software tools, that covertly grants cybercriminals the ability to gain remote access on a targeted computer or system.'
```

2023-07-22 14:38 UTC, SSwiniarski commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +**Rootkit** is a type of [malware](https://www.codecademy.com/resources/docs/cybersecurity/malware) and a program, or a collection of software tools, covertly grants cybercriminals the ability to gai
```suggestion
A **Rootkit** is a program, or a collection of software tools, that covertly grants cybercriminals the ability to gain remote access on a targeted computer or system. The term "rootkit" originates from [Unix](https://www.codecademy.com/resources/docs/general/unix)-based operating systems, such as [Linux](https://www.codecademy.com/resources/docs/open-source/linux), where the most privileged account is referred to as "root". The applications that provide unauthorized access to the device at the root or admin level are referred to as the "kit".
```

2023-07-22 14:38 UTC, SSwiniarski commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +Rootkits attempt to prevent malware from being detected by disabling endpoint antimalware and antivirus software. While the majority of rootkits impact the software and operating system, certain root
```suggestion
Rootkits attempt to prevent malware from being detected by disabling endpoint antimalware and antivirus software. While the majority of rootkits impact the software and operating system, certain rootkits can also infiltrate a computer's hardware and firmware.
```
We avoid first- and second-person pronouns in Docs.

2023-07-22 14:38 UTC, SSwiniarski commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +There are different types of rootkits, and they fall into different categories based on what they do and how long they stay on your system. The ones listed here are the most well-known, but there are
```suggestion
There are different types of rootkits, and they fall into different categories based on what they do and how long they stay on a system. The ones listed here are the most well-known, but there are even more types out there.
```

2023-07-22 14:38 UTC, SSwiniarski commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +| Memory rootkit      | Memory rootkits conceal themselves within the computer's Random Access Memory (RAM)<br>and exploit system resources to execute malicious activities unnoticed in the background
```suggestion
- Kernel mode rootkit: Designed to manipulate critical and system files of operating systems and can inject malicious code into the operating system's kernel data structure.                                                                                                                                                                                      - User mode rootkit:  Also known by the name "application rootkit", it replaces standard computer files with rootkit files and may even change the way standard programs work.                                                                                                                                                                                           - Firmware rootkit: Can affect a router or BIOS.                                                                                                                                                                                                                                                                                  - Bootloader rootkit: Also known as "bootkits," they replace the legitimate bootloader with a corrupted version, compromising the computer's loading process.                                                                                                                                                                                                    - Memory rootkit: Conceals itself within the computer's Random Access Memory (RAM) and exploits system resources to execute malicious activities unnoticed in the background. Since memory rootkits only reside in the computer's RAM and do not inject malicious code permanently, they disappear as soon as the system is rebooted. 
```
This works better as a bulleted list rather than a table.

2023-07-22 14:38 UTC, SSwiniarski commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +- Unexpected System Modifications.
```suggestion
- Difficulty in Detection.
- Unclear Network Activity.
- Unusual System Behavior.
- Slow Performance.
- Disabled Security Software.
- Unexpected System Modifications.
```

2023-07-22 14:38 UTC, SSwiniarski commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +## Rootkit Preventions
```suggestion
## Rootkit Prevention
```

2023-07-22 14:38 UTC, SSwiniarski commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +Similar precautions can be taken to prevent the rootkit from infiltrating the system. A few of these measures include:
```suggestion
Precautions can be taken to prevent the rootkit from infiltrating the system. A few of these measures include:
```

2023-07-22 14:38 UTC, SSwiniarski commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +- Don't install unknown software form unreliable sources.
```suggestion
- Keep The system and software updated.
- Run security scans regularly.
- Don't click on suspicious links.
- Don't install unknown software form unreliable sources.
```

2023-07-22 18:07 UTC, frhadjmli commented
@SSwiniarski I made the changes as requested.

2023-07-23 13:33 UTC, SSwiniarski approved these changes
@frhadjmli This looks good for a second review.

2023-07-28 23:19 UTC, CBID2 commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +
[Proofreading] I think using the word "below" instead of "here" would help developers gain a better understanding of where to find the list of rootkits. 
```suggestion
There are different types of rootkits, and they fall into different categories based on what they do and how long they stay on a system. The ones listed below are the most well-known, but there are even more types out there.

```

2023-07-28 23:23 UTC, CBID2 commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +- Memory rootkit: Conceals itself within the computer's Random Access Memory (RAM) and exploits system resources to execute malicious activities unnoticed in the background. Since memory rootkits onl
[nitpick/question] What are some well-known rootkits? I think naming and adding a link to software in each bullet point would help spring cybersecurity professionals have some idea of what tools they'd use in their line of work. 
```suggestion
- Kernel mode rootkit: Designed to manipulate critical and system files of operating systems and can inject malicious code into the operating system's kernel data structure.
- User mode rootkit: Also known by the name "application rootkit", it replaces standard computer files with rootkit files and may even change the way standard programs work.
- Firmware rootkit: Can affect a router or BIOS.
- Bootloader rootkit: Also known as "bootkits," they replace the legitimate bootloader with a corrupted version, compromising the computer's loading process.
- Memory rootkit: Conceals itself within the computer's Random Access Memory (RAM) and exploits system resources to execute malicious activities unnoticed in the background. Since memory rootkits only reside in the computer's RAM and do not inject malicious code permanently, they disappear as soon as the system is rebooted.
```

2023-07-28 23:24 UTC, CBID2 requested changes
Hi @frhadjmli! :) I pointed out a proofreading error and some suggestions in my inline comments. In the future, consider running your descriptions through Grammarly or Spellcheck and doing some research on your entry before making a pull request. Other than that, you're off to a great start! :) 
Note: I'm not a maintainer. Just a contributor who is eager to help other contributors.

2023-07-29 18:08 UTC, frhadjmli commented
Hello @CBID2, Thank you for your suggestions and tips. I have already checked it with the free version of Grammarly.

2023-07-29 18:11 UTC, frhadjmli commented
@SSwiniarski It has been a week since the first review, and I am still waiting for the second review.

2023-07-29 19:48 UTC, SSwiniarski commented
@frhadjmli have patience, there are only four maintainers working though a high volume of submissions.

2023-08-08 13:27 UTC, KTom101 requested changes
@frhadjmli Added some changes to this

2023-08-08 13:27 UTC, KTom101 commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +A **Rootkit** is a program, or a collection of software tools, that covertly grants cybercriminals the ability to gain remote access on a targeted computer or system. The term "rootkit" originates fr
```suggestion
A **Rootkit** is a program, or a collection of software tools, that covertly grants cybercriminals the ability to gain remote access to a targeted computer or system. The term "rootkit" originates from [Unix](https://www.codecademy.com/resources/docs/general/unix)-based operating systems, such as [Linux](https://www.codecademy.com/resources/docs/open-source/linux), where the most privileged account is referred to as "root". The applications that provide unauthorized access to the device at the root or admin level are referred to as the "kit".
```

2023-08-08 13:27 UTC, KTom101 commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +Rootkits have great power in hiding and can hide in files, registry settings, or processes and steal user information. A rootkit opens a backdoor on victims' systems to introduce malicious software,
```suggestion
Rootkits have significant power in hiding and can conceal themselves within files, registry settings, or processes to steal user information. A rootkit opens a backdoor on victims' systems to introduce malicious software, including [viruses](https://www.codecademy.com/resources/docs/cybersecurity/malware/virus), [ransomware](https://www.codecademy.com/resources/docs/cybersecurity/malware/ransomware), keyloggers, or other malware, as well as systems that can exploit active security networks.
```

2023-08-08 13:27 UTC, KTom101 commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +Rootkits attempt to prevent malware from being detected by disabling endpoint antimalware and antivirus software. While the majority of rootkits impact the software and operating system, certain root
```suggestion
Rootkits attempt to prevent malware from being detected by disabling endpoint antimalware and antivirus software. While most rootkits impact software and operating systems, certain rootkits can also infiltrate a computer's hardware and firmware.
```

2023-08-08 13:27 UTC, KTom101 commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +There are different types of rootkits, and they fall into different categories based on what they do and how long they stay on a system. The ones listed here are the most well-known, but there are ev
```suggestion
Different types of rootkits fall into various categories based on their actions and duration on a system. The following are the most well-known types, but there are more variations:
```

2023-08-08 13:27 UTC, KTom101 commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +- Kernel mode rootkit: Designed to manipulate critical and system files of operating systems and can inject malicious code into the operating system's kernel data structure.
```suggestion
- Kernel mode rootkit: Designed to manipulate critical system files, it can inject malicious code into the operating system's kernel data structure.
```

2023-08-08 13:27 UTC, KTom101 commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +- User mode rootkit: Also known by the name "application rootkit", it replaces standard computer files with rootkit files and may even change the way standard programs work.
```suggestion
- User mode rootkit: Also known as an "application rootkit", it replaces standard computer files with rootkit files and may alter the way standard programs work.
```

2023-08-08 13:27 UTC, KTom101 commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +- Keep The system and software updated.
```suggestion
- Keep the system and software updated.
```

2023-08-08 13:27 UTC, KTom101 commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +- Don't click on suspicious links.
```suggestion
- Avoid clicking on suspicious links.
```

2023-08-08 13:27 UTC, KTom101 commented on content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md
> +- Don't install unknown software form unreliable sources.
```suggestion
- Refrain from installing unknown software from unreliable sources.
```

2023-08-08 19:38 UTC, frhadjmli commented
@KTom101 I made the changes as requested.

2023-08-11 18:59 UTC, KTom101 approved these changes

2023-08-11 19:09 UTC, merged