New term entry for cross site scripting
Codecademy/docs pull request #2794
Opened 2023-07-20 17:53 UTC by ariana124

### Description

- Created a new cybersecurity term entry for Cross-Site Scripting (XSS)

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-20 17:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2794) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2794) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2794) it.</sub>

2023-07-22 13:59 UTC, SSwiniarski requested changes
@ariana124 Looks good, just some spacing related comments.

2023-07-22 13:59 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-attack/terms/cross-site-scripting/cross-site-scripting.md
> +3. Document Object Model (DOM) Based XSS: With DOM-based XSS, the attacker attempts to exploit the victim's web browser by attacking the DOM, usually through the URL. This attack is also known as cli
```suggestion
There are three common types of cross-site scripting attacks:

1. Stored/Persistent XSS: The attacker attempts to get data provided from injected scripts placed in the victim's web browser, or the website's web server or database.
2. Reflected/Non-Persistent XSS: The attacker attempts to have the user click on a malicious link, masqueraded as a legitimate link, from the website's error message, search result, or phishing email.
3. Document Object Model (DOM) Based XSS: With DOM-based XSS, the attacker attempts to exploit the victim's web browser by attacking the DOM, usually through the URL. This attack is also known as client-side XSS.
```
Adjust spacing. Should be a blank line before bulleted list and no blank lines between items.

2023-07-22 13:59 UTC, SSwiniarski commented on content/cybersecurity/concepts/cyber-attack/terms/cross-site-scripting/cross-site-scripting.md
> +- Hijack the victim's session cookies.
```suggestion
With successful XSS attacks, the attacker can:

- Hijack the victim's session cookies.
```

2023-08-22 04:38 UTC, KTom101 requested changes
@ariana124 I added a few changes

2023-08-22 04:38 UTC, KTom101 commented on content/cybersecurity/concepts/cyber-attack/terms/cross-site-scripting/cross-site-scripting.md
> +1. Stored/Persistent XSS: The attacker attempts to get data provided from injected scripts placed in the victim's web browser, or the website's web server or database.
Let's make this a little bit more clear
```suggestion
1. Stored/Persistent XSS: The attacker attempts to inject malicious scripts into a web server or database. These scripts are then delivered to victims when they access specific pages on the website.
```

2023-08-22 04:38 UTC, KTom101 commented on content/cybersecurity/concepts/cyber-attack/terms/cross-site-scripting/cross-site-scripting.md
> +3. Document Object Model (DOM) Based XSS: With DOM-based XSS, the attacker attempts to exploit the victim's web browser by attacking the DOM, usually through the URL. This attack is also known as cli
```suggestion
3. Document Object Model (DOM) Based XSS: Involves manipulating the Document Object Model (DOM) of a web page to execute malicious scripts in the victim's browser. This can occur through various user interactions and events, not limited to the URL alone. This attack is also known as client-side XSS.
```

2023-08-22 04:38 UTC, KTom101 commented on content/cybersecurity/concepts/cyber-attack/terms/cross-site-scripting/cross-site-scripting.md
> +XSS is particularly harmful because the victim is the user, not the web browser. This attack exploits the trust that exists between the user's web browser and the web server. The malicious code is in
```suggestion
XSS is particularly harmful because its primary target is the user, not the web browser. This attack exploits the trust that exists between the user's web browser and the web server. The malicious code is injected into the web page that's delivered from the web server to the user.
```

2023-09-24 19:50 UTC, SSwiniarski commented
@KTom101, in the interest of getting this moving after a month, I implemented your suggestions. How does it look now?

2023-10-06 22:14 UTC, KTom101 approved these changes
@SSwiniarski Thank you.

2023-10-06 22:15 UTC, merged