Creation of Asinh for php
Codecademy/docs pull request #2843
Opened 2023-07-23 03:25 UTC by arisdelacruz

### Description

This is my attempt to create reference of the asinh function for php. Motivation still stems from the enthusiasm to contribute more to docs and help others.

### Type of Change

- Adding a new entry

### Checklist

- [ /] All writings are my own.
- [ /] My entry follows the Codecademy Docs style guide.
- [ /] My changes generate no new warnings.
- [ /] I have performed a self-review of my own writing and code.
- [ /] I have checked my entry and corrected any misspellings.
- [ /] I have made corresponding changes to the documentation if needed.
- [ /] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ /] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ /] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-23 15:40 UTC, SSwiniarski requested changes
@arisdelacruz I did a first review and left some comments. Most important is you need to remove the fmod.md file from this PR.

2023-07-23 15:40 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/fmod/fmod.md
You need to remove this file from this PR.

2023-07-23 15:40 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/asinh/asinh.md
> +The `asinh()` function takes only one parameter, `value`. The value of this parameter must be in `radians`.
```suggestion
The `asinh()` function takes only one parameter, `value`.
```

2023-07-24 09:26 UTC, arisdelacruz commented on content/php/concepts/math-functions/terms/fmod/fmod.md
duly noted with thanks

2023-07-24 09:30 UTC, arisdelacruz commented on content/php/concepts/math-functions/terms/fmod/fmod.md
just wonderin though

do i need to submit another PR

thanks

2023-07-24 11:21 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/fmod/fmod.md
You shouldn't have to, this should resolve the conflict.

2023-07-26 01:28 UTC, arisdelacruz commented
@SSwiniarski

I hope i got the message right. No needed move from my end as of the moment.

Thanks

2023-07-26 09:43 UTC, arisdelacruz commented
i tried to resolve the branch conflict

so, i hope i did the right thing

thanks

2023-07-26 15:34 UTC, SSwiniarski approved these changes
@arisdelacruz Looks good for a second review.

2023-07-26 21:51 UTC, caupolicandiaz approved these changes
@arisdelacruz @SSwiniarski I just pushed some minor edits. Looks good to merge

2023-07-27 16:18 UTC, merged

2023-07-27 16:26 UTC, SSwiniarski commented
@arisdelacruz Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/php/math-functions/asinh

![image](https://github.com/Codecademy/docs/assets/86081858/50c6eb5f-9cf3-4ae1-8630-cc4430af7a7c)