[New Term Entry] Adding compareTo() to Java date terms
Codecademy/docs pull request #2848
Opened 2023-07-24 10:11 UTC by ChiragAgg5k

### Description

Adds a new term entry for compareTo() - a Date object comparison method - to the Java dates section. Closes #2836 .

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-24 16:22 UTC, SSwiniarski requested changes
@ChiragAgg5k I did a first review and only had a couple of comments.

2023-07-24 16:47 UTC, ChiragAgg5k commented
Made the changes as requested 👍🏻

2023-07-25 16:04 UTC, SSwiniarski approved these changes
@ChiragAgg5k Looks good for a second review.

2023-07-25 19:57 UTC, caupolicandiaz requested changes
@ChiragAgg5k I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-25 19:57 UTC, caupolicandiaz commented on content/java/concepts/date/terms/compareTo/compareTo.md
> +The **`Date.compareTo()`** method compares one Date object with another and returns an integer value accordingly.
```suggestion
The **`Date.compareTo()`** method compares one `Date` object with another and returns an integer value accordingly.
```

2023-07-25 19:57 UTC, caupolicandiaz commented on content/java/concepts/date/terms/compareTo/compareTo.md
> +It returns
```suggestion
It returns:
```

2023-07-25 19:57 UTC, caupolicandiaz commented on content/java/concepts/date/terms/compareTo/compareTo.md
> +- the value `0` if the argument Date is equal to this Date.
```suggestion
- The value `0` if `argumentDate` is equal to `thisDate`.
```

2023-07-25 19:57 UTC, caupolicandiaz commented on content/java/concepts/date/terms/compareTo/compareTo.md
> +- the value `0` if the argument Date is equal to this Date.
Update the other bullet points with the formatting shown above

2023-07-25 19:57 UTC, caupolicandiaz commented on content/java/concepts/date/terms/compareTo/compareTo.md
> +The function throws a single exception that is [NullPointerException](https://www.codecademy.com/resources/docs/java/errors/nullpointerexception) if the argumentDate is null.
```suggestion
The function throws a single exception, a [NullPointerException](https://www.codecademy.com/resources/docs/java/errors/nullpointerexception), if `argumentDate` is null.
```

2023-07-26 03:45 UTC, ChiragAgg5k commented
@caupolicandiaz entry updated

2023-07-26 03:54 UTC, ChiragAgg5k commented
Really sorry about the consecutive commits. Next time I will make sure to read more properly before pushing

2023-07-26 03:57 UTC, ChiragAgg5k commented
Apologies for the consecutive commits. Next time I will try to read more carefully before pushing. Thanks

2023-07-26 17:12 UTC, caupolicandiaz approved these changes
@ChiragAgg5k @SSwiniarski LGTM

2023-07-27 16:13 UTC, merged

2023-07-27 16:25 UTC, SSwiniarski commented
@ChiragAgg5k Congrats on your new entry! Live link here: https://www.codecademy.com/resources/docs/java/date/compareTo

![image](https://github.com/Codecademy/docs/assets/86081858/08306aac-51e8-426c-9bef-87138aa6d034)

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.