[Term Entry] PHP Math Functions acosh()
Codecademy/docs pull request #2856
Opened 2023-07-25 19:34 UTC by LewisMK

### Description

[Term Entry] PHP Math Functions acosh(). Closes #2396

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-25 20:19 UTC, caupolicandiaz requested changes
@LewisMK I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-25 20:19 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/acosh/acosh.md
> +Description: 'Returns a floating point number of the inverse hyperbolic cosine value of the argument which is passed as a radian.'
```suggestion
Description: 'Returns the inverse hyperbolic cosine value of the given argument.'
```

2023-07-25 20:19 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/acosh/acosh.md
> +The built-in math function **`acosh()`** determines the `inverse hyperbolic cosine` of a number, i.e the value whose hyperbolic cosine is the input number. The input number must be in radians, and th
```suggestion
The built-in math function **`acosh()`** determines the inverse hyperbolic cosine of a number, in other words the value whose hyperbolic cosine is the input number. The input number must be in radians, and the output is a floating point number.
```

2023-07-25 20:19 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/acosh/acosh.md
> +$result = acosh(number);
```suggestion
$result = acosh($number);
```

2023-07-25 20:19 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/acosh/acosh.md
> +Where `number` is the number that the function returns the inverse hyperbolic cosine for.
```suggestion
Where `$number` is the value in radians that the inverse hyperbolic cosine will be based on.
```

2023-07-25 20:19 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/acosh/acosh.md
> +The result will be a float value of `2.9932228461264`.
```suggestion
This will result in the following output:

```shell
2.9932228461264

```

2023-07-25 20:19 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/acosh/acosh.md
> +The `acosh()` function returns the inverse hyperbolic cosine of the given number as a float value in radians.
```suggestion
The following code is runnable and demonstrates the use of `acosh()`.
```

2023-07-25 20:19 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/acosh/acosh.md
> +  echo(acosh(10) . "<br>");
```suggestion
  echo(acosh(-10) . " Radians\n");
```

2023-07-25 20:19 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/acosh/acosh.md
> +  echo(acosh(5));
```suggestion
  echo(acosh(5)) . " Radians";
```

2023-07-26 07:15 UTC, LewisMK commented
@caupolicandiaz I have updated the necessary changes.

2023-07-26 17:18 UTC, caupolicandiaz approved these changes
@LewisMK I made a few small edits to the examples. This is ready for a second review.

2023-07-28 16:18 UTC, SSwiniarski requested changes
@LewisMK I did a second review and had two comments.

2023-07-28 16:18 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/acosh/acosh.md
> +The built-in math function **`acosh()`** determines the inverse hyperbolic cosine of a number, in other words the value whose hyperbolic cosine is the input number. The input number must be in radian
```suggestion
The built-in math function **`acosh()`** determines the inverse hyperbolic cosine of a number, in other words the value whose hyperbolic cosine is the input number. The output is a floating point number in radians.
```
The angle is the output of the function, not the input.

2023-07-28 16:18 UTC, SSwiniarski commented on content/php/concepts/math-functions/terms/acosh/acosh.md
> +Where `$number` is the value in radians that the inverse hyperbolic cosine will be based on.
```suggestion
Where `$number` is the value that the inverse hyperbolic cosine will be based on.
```
The result is ni radians, not the argument.

2023-07-28 16:47 UTC, LewisMK commented
@SSwiniarski  thanks, comments have been committed.

2023-07-29 13:19 UTC, SSwiniarski approved these changes
@LewisMK looks good.

2023-07-29 13:23 UTC, merged

2023-07-29 13:39 UTC, SSwiniarski commented
@LewisMK Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/php/math-functions/acosh

![image](https://github.com/Codecademy/docs/assets/86081858/87e6defd-4ae3-4aa6-8c2d-bd05095e64a6)

2023-07-29 15:08 UTC, LewisMK commented
@SSwiniarski thanks a lot.