Created clone.md for Java Date clone method
Codecademy/docs pull request #2860
Opened 2023-07-26 07:37 UTC by Rayatk

### Description

- Added `Date.clone()` term entry for Java
- Addressed issue #2835

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-26 07:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2860) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2860) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2860) it.</sub>

2023-07-26 21:37 UTC, caupolicandiaz requested changes
@Rayatk I've added my initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-26 21:37 UTC, caupolicandiaz commented on content/java/concepts/date/terms/clone/clone.md
> +The **`Date.clone()`** method returns a copy or duplicate of a specified Date object.
```suggestion
The **`Date.clone()`** method returns a copy or duplicate of a specified `Date` object.
```

2023-07-26 21:37 UTC, caupolicandiaz commented on content/java/concepts/date/terms/clone/clone.md
> +It returns a copy or duplicate of the `currentDate` when the method is called without an argument. However, if an argument is passed on to the method,
```suggestion
It returns a copy or duplicate of the `currentDate`, and the returned value is an `Object`, not a `Date`.  
```

2023-07-26 21:37 UTC, caupolicandiaz commented on content/java/concepts/date/terms/clone/clone.md
> +The output will be:
```suggestion
The output will be similar to:
```

2023-07-26 21:37 UTC, caupolicandiaz commented on content/java/concepts/date/terms/clone/clone.md
> +The following example shows the implementation of `Date.clone()`:
```suggestion
The following example shows an implementation of `Date.clone()`:
```

2023-07-27 02:32 UTC, Rayatk commented
@caupolicandiaz I have finished making changes as suggested.

2023-07-27 02:37 UTC, Rayatk commented
> @Rayatk I've added my initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

@caupolicandiaz I have finished making changes as suggested.

2023-07-29 20:35 UTC, SSwiniarski requested changes
@Rayatk I did a second review and only had one comment.

2023-07-29 20:35 UTC, SSwiniarski commented on content/java/concepts/date/terms/clone/clone.md
> +The `Date.clone()` does not take any parameters.
```suggestion
The `Date.clone()` method  does not take any parameters.
```

2023-07-31 01:43 UTC, Rayatk commented
@SSwiniarski I did the changes.

2023-07-31 15:55 UTC, SSwiniarski approved these changes
@Rayatk looks good.

2023-07-31 16:04 UTC, merged

2023-07-31 16:22 UTC, SSwiniarski commented
@Rayatk Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/java/date/clone

![image](https://github.com/Codecademy/docs/assets/86081858/6a99f153-f333-433d-8143-042384d82d45)

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.