add codebyte for Reversed applied on tuple
Codecademy/docs pull request #2863
Opened 2023-07-26 12:18 UTC by DelphCL

### Description

### Type of Change

- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-29 15:21 UTC, SSwiniarski commented
@DelphCL This only addresses half the issue yo were assigned. You need to include a codebyte for `https://www.codecademy.com/resources/docs/python/built-in-functions/sorted` in with this PR. Tag me once that's accomplished and I'll do a first review.

2023-07-29 15:27 UTC, DelphCL commented
> 



> @DelphCL This only addresses half the issue you were assigned. You need to include a codebyte for `https://www.codecademy.com/resources/docs/python/built-in-functions/sorted` in with this PR. Tag me once that's accomplished and I'll do a first review.

@SSwiniarski , the codebyte for the sorted function was added in a previous PR:"add example 6 to Python Built in Functions - sorted() #2845", which was already approved and merged a few days ago. 

Not sure what I have done wrong here, please let me know if any further correction or action is required, 

Many thanks 

Kind regards

DelphCL

2023-07-29 19:50 UTC, SSwiniarski commented
@DelphCL This is why we prefer to have only one PR per issue. It leads to confusion like this. I removed the tag and will review this.

2023-07-29 19:53 UTC, SSwiniarski requested changes
@DelphCL I did a first review and left some comments.

2023-07-29 19:53 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/reversed/reversed.md
> +Takes in an iteratable object, such as a list, string, or a tuple and returns a reversed iterator object.
```suggestion
The **`reversed()`** function takes in an iteratable object, such as a list, string, or a tuple and returns a reversed iterator object.
```

2023-07-29 19:53 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/reversed/reversed.md
> +Tuples are iterable objects too hence `reversed()` can be used on tuples as well.
```suggestion
Tuples are iterable objects too, hence `reversed()` can be used on tuples as well. 
```

2023-07-31 15:15 UTC, DelphCL commented
> 

@SSwiniarski, many thanks, I have accepted the changes you suggested and committed them. Many thanks.

2023-07-31 16:34 UTC, SSwiniarski approved these changes
@DelphCL Looks good for a second review.

2023-08-02 16:13 UTC, DelphCL commented
@SSwiniarski, is there any action left for me to do ? many thanks DelphCL

2023-08-21 21:51 UTC, caupolicandiaz approved these changes
@DelphCL @SSwiniarski Just made a couple of typo edits. Looks good to merge

2023-08-22 12:28 UTC, merged