Add deprecation notes
Codecademy/docs pull request #2867
Opened 2023-07-26 18:58 UTC by yangc95

### Description

 Replace paragraph formatting for note formatting when mentioning deprecated features.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-26 22:23 UTC, KTom101 requested changes
@yangc95 Added some minor changes.

2023-07-27 17:43 UTC, yangc95 commented on content/general/concepts/ssl/ssl.md
>  SSL uses a cryptographic mechanism featuring a public and private key to encrypt data communicating over internet networks. SSL uses a protocol known as a 'handshake' to determine the authenticity of
```suggestion
SSL uses a cryptographic mechanism featuring a public and private key to encrypt data communicating over internet networks. SSL uses a protocol known as a 'handshake' to determine the authenticity of a server. The main advantage of SSL is the confidence it gives to users that a server has been authenticated by a trusted Certificate Authority (CA). Valid SSL certs can only be issued by accredited Certificate Authorities which have rigid standards for issuing them.
```

2023-07-27 17:43 UTC, yangc95 commented on content/general/concepts/ssl/ssl.md
> +**SSL** stands for **Secure Socket Layer**, and is a cryptographic protocol for securing computer networks.
```suggestion
**Secure Socket Layer (SSL)** is a cryptographic protocol for securing computer networks.
```

2023-07-27 17:44 UTC, yangc95 commented on content/general/concepts/ssl/ssl.md
> +> **Note**: SSL was deprecated in 1999 and renamed TLS by the [Internet Engineering Task Force](https://www.ietf.org). TLS is essentially an improved version of SSL (it is SSL 3.1) and features a num
```suggestion
> **Note**: SSL was deprecated in 1999 and renamed Transport Layer Security (TLS) by the [Internet Engineering Task Force](https://www.ietf.org). TLS is essentially an improved version of SSL (it is SSL 3.1) and features a number of improvements that address security concerns that were discovered in the initial and prior implementations of SSL.
```

2023-07-27 17:45 UTC, yangc95 commented on content/general/concepts/ssl/ssl.md
>  SSL uses a cryptographic mechanism featuring a public and private key to encrypt data communicating over internet networks. SSL uses a protocol known as a 'handshake' to determine the authenticity of
good idea!

2023-07-28 19:23 UTC, KTom101 approved these changes
@yangc95 LGTM

2023-07-29 14:58 UTC, SSwiniarski approved these changes
@yangc95 I had one little comment, otherwise it looks good to merge.

2023-07-29 14:58 UTC, SSwiniarski commented on content/html/concepts/elements/terms/font/font.md
> +> **Note** This is now deprecated. Some [CSS](https://www.codecademy.com/resources/docs/css) properties like the [`font`](https://www.codecademy.com/resources/docs/css/typography/font) property shoul
```suggestion
> **Note** This is now deprecated. [CSS](https://www.codecademy.com/resources/docs/css) properties like the [`font`](https://www.codecademy.com/resources/docs/css/typography/font) property should be used instead.
```

2023-07-31 16:36 UTC, merged