[Term Entry] PHP Arrays range()
Codecademy/docs pull request #2870
Opened 2023-07-27 17:55 UTC by EspressoCat

### Description

- Added range() term for PHP
- Closes issue #2754 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-28 17:31 UTC, caupolicandiaz requested changes
@EspressoCat I've added my initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-07-28 17:31 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/range/range.md
> +Description: 'Returns an array of elements from low to high.'
```suggestion
Description: 'Returns an array that contains a series of elements based on the parameters given.'
```

2023-07-28 17:31 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/range/range.md
> +The **`range()`** function generates an array containing a sequence of elements. It allows you to define a starting point, an endpoint, and an optional step value to determine the increment between e
```suggestion
The **`range()`** function generates an array containing a sequence of elements. The function allows for the specification of a starting point, an endpoint, and an optional step value to determine the increment between elements.
```

2023-07-28 17:31 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/range/range.md
> +The `range()` function returns an array of elements from `$start` to `$end`, inclusive.
```suggestion
The `range()` function returns an array of elements from `$start` to `$end`, and is inclusive (the `$end` value will be the final element in the array).
```

2023-07-28 17:31 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/range/range.md
> +// printing elements of array
```suggestion
// Printing elements of the array
```

2023-07-31 07:49 UTC, EspressoCat commented
Thanks for the comments @caupolicandiaz
made requested changes.

2023-07-31 17:09 UTC, caupolicandiaz approved these changes
@EspressoCat This is ready for a second review.

2023-08-03 19:51 UTC, EspressoCat commented
hey @codecademy-docs 👋🏻

Let me know if addition changes are required. Thanks!

2023-08-03 20:36 UTC, caupolicandiaz commented
> hey @codecademy-docs 👋🏻
> 
> Let me know if addition changes are required. Thanks!

We appreciate your eagerness and interest, however, please be patient. Another maintainer will conduct a review when they can.

2023-08-06 15:32 UTC, SSwiniarski approved these changes
@EspressoCat Looks good.

2023-08-06 15:35 UTC, merged

2023-08-06 15:45 UTC, SSwiniarski commented
@EspressoCat Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/php/arrays/range

![image](https://github.com/Codecademy/docs/assets/86081858/6cba22b1-8a5d-429c-a7a3-1a17a359bf7e)