[Term Entry] PHP Arrays rsort() #2824
Codecademy/docs pull request #2890
Opened 2023-07-28 18:22 UTC by a-g-test

### Description

- Added the rsort.md term for PHP
- Closes issue #2824

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-29 14:01 UTC, SSwiniarski requested changes
@a-g-test I did a first review and left a few comments.

2023-07-29 14:01 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/rsort/rsort.md
> +
```suggestion
## Codebyte Example

```

2023-08-02 13:30 UTC, a-g-test commented on content/php/concepts/arrays/terms/rsort/rsort.md
> +- `arrayToSort`: An array - required parameter, specifies the array to sort in rsort.
This has been updated

2023-08-02 13:30 UTC, a-g-test commented on content/php/concepts/arrays/terms/rsort/rsort.md
> +###### Sorting type flags
This has been updated

2023-08-02 13:30 UTC, a-g-test commented on content/php/concepts/arrays/terms/rsort/rsort.md
> +
This has been updated

2023-08-02 13:31 UTC, a-g-test commented on content/php/concepts/arrays/terms/rsort/rsort.md
> +3 = Cherries
This has been updated

2023-08-03 16:20 UTC, SSwiniarski approved these changes
@a-g-test Looks good for a second review.

2023-08-07 20:44 UTC, caupolicandiaz approved these changes
@a-g-test @SSwiniarski I made a few small edits, but otherwise in good shape. Looks good to merge

2023-08-08 11:16 UTC, merged

2023-08-08 11:21 UTC, SSwiniarski commented
@a-g-test Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/php/arrays/rsort

![image](https://github.com/Codecademy/docs/assets/86081858/2b06af80-1979-49f5-936c-71c1c180becb)

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.