Python add codebytes
Codecademy/docs pull request #2893
Opened 2023-07-30 12:04 UTC by Jonnie-Dev

### Description
Closes #2889 

Added new codebyte examples for python - regex match, split and search

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-30 12:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2893) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2893) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2893) it.</sub>

2023-07-30 14:56 UTC, SSwiniarski requested changes
@Jonnie-Dev I've done a first review and have just one comment.

2023-07-30 14:56 UTC, SSwiniarski commented on content/python/concepts/regex/terms/match/match.md
While it was probably an oversight that the issue mentioned an entry with a codebyte already, I think your codebyte is better than the existing one. So, instead of adding the new codebyte, can you just replace the existing codebyte with yours? We generally only have one codebyte per entry.

2023-07-30 15:31 UTC, Jonnie-Dev commented on content/python/concepts/regex/terms/match/match.md
ooh ooh, will do that now. Thank you

2023-07-30 15:42 UTC, SSwiniarski approved these changes
@Jonnie-Dev aside from one minor change, looks good for a second review.

2023-07-30 15:42 UTC, SSwiniarski commented on content/python/concepts/regex/terms/match/match.md
> +## Codebyte Examples
```suggestion
## Codebyte Example
```

2023-08-01 16:53 UTC, caupolicandiaz approved these changes
@Jonnie-Dev @SSwiniarski Overall, looks good. I think the "match" and "search" codebytes, are more complete examples than what was existing. The "split" example had errors and I don't think it was an improvement over the original, so I reverted those changes. Looks good to merge.

2023-08-01 16:55 UTC, Jonnie-Dev commented
> @Jonnie-Dev @SSwiniarski Overall, looks good. I think the "match" and "search" codebytes, are more complete examples than what was existing. The "split" example had errors and I don't think it was an improvement over the original, so I reverted those changes. Looks good to merge.

Thank you for this, the typos were an oversight on my end.

2023-08-02 11:07 UTC, merged

2023-08-02 11:15 UTC, SSwiniarski commented
@Jonnie-Dev Congrats on the new edit!

Live links:
- https://www.codecademy.com/resources/docs/python/regex/match
- https://www.codecademy.com/resources/docs/python/regex/search

2023-08-03 16:16 UTC, SSwiniarski commented
If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.