New python file codebytes
Codecademy/docs pull request #2895
Opened 2023-07-30 15:02 UTC by Luke943

### Description

Closes #2819 .

Codebytes have been added for three Python file methods: close, readline and remove.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-07-31 19:53 UTC, caupolicandiaz requested changes
@Luke943 I've added my comments. Please update the entries, and tag me when you've finished making changes. Thanks

2023-07-31 19:53 UTC, caupolicandiaz commented on content/python/concepts/files/terms/close/close.md
> +The example below opens a file called **example_file.txt** and then closes it using `.close()`. The `.closed` attribute is used to show whether the file is open or closed.
```suggestion
The example below opens a file called `example_file.txt` and then closes it using `.close()`. The `.closed` attribute is used to show whether the file is open or closed.
```

2023-07-31 19:53 UTC, caupolicandiaz commented on content/python/concepts/files/terms/close/close.md
> +f = open("example_file.txt", "r+")
```suggestion
filename = "example.txt"
f = open(filename, "w")

```

2023-07-31 19:53 UTC, caupolicandiaz commented on content/python/concepts/files/terms/readline/readline.md
> +The example below first creates a file called **sample_text.txt** and writes multiple lines of text to the file. It then calls `.readline()` twice to extract the two lines of content.
```suggestion
The example below first creates a file called `sample_text.txt` and writes multiple lines of text to the file. It then calls `.readline()` twice to extract the two lines of content.
```

2023-07-31 19:53 UTC, caupolicandiaz commented on content/python/concepts/files/terms/remove/remove.md
> +The example below creates a file called **example.txt** and then deletes it using the `.remove()` method. The `.isfile()` method is used to show at which stage the file is found.
```suggestion
The example below creates a file called `example.txt` and then deletes it using the `.remove()` method. The `.isfile()` method is used to show at which stage the file is found.
```

2023-08-01 09:45 UTC, Luke943 commented
Thanks for the feedback @caupolicandiaz . I've made the changes you suggested to the files.

The Example sections of these files also use the markdown format **filename.txt** instead of `filename.txt`. Should they be changed as well?

2023-08-06 15:27 UTC, SSwiniarski approved these changes
@Luke943 Looks good.

2023-08-06 15:28 UTC, merged