Python - Add codebytes for math.pow and math.sin
Codecademy/docs pull request #2902
Opened 2023-08-01 07:39 UTC by AapoSoukkio

### Description

- Added Codebytes to the listed entries.
   https://www.codecademy.com/resources/docs/python/math-module/math-pow
   https://www.codecademy.com/resources/docs/python/math-module/math-sin
- Closes Issue  [#2886](https://github.com/Codecademy/docs/issues/2886)

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-01 07:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2902) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2902) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2902) it.</sub>

2023-08-01 20:25 UTC, caupolicandiaz requested changes
@AapoSoukkio I've completed my initial review. Please update the entries, and tag me when you've finished making changes. Thanks

2023-08-01 20:25 UTC, caupolicandiaz commented on content/python/concepts/math-module/terms/math-sin/math-sin.md
> +Return the sine of different numbers
```suggestion
The following code is runnable and returns the sine of different values:
```

2023-08-01 20:25 UTC, caupolicandiaz commented on content/python/concepts/math-module/terms/math-pow/math-pow.md
> +Return the value of 4 raised to the power of 3
```suggestion
The following code is runnable and demonstrates the use of `math.pow()`:
```

2023-08-01 20:25 UTC, caupolicandiaz commented on content/python/concepts/math-module/terms/math-pow/math-pow.md
> +print(math.pow(4, 3))
```suggestion
print(math.pow(2, 0.0))
print(math.pow(1.0, 2))
```

2023-08-01 20:25 UTC, caupolicandiaz commented on content/python/concepts/math-module/terms/math-pow/math-pow.md
> +print(math.pow(4, 3))
I updated this example to illustrate one of the special cases in order to differentiate it more from the other examples

2023-08-02 07:19 UTC, AapoSoukkio commented
@caupolicandiaz Thank you for your review. The entries has been updated as requested now.

2023-08-02 18:58 UTC, caupolicandiaz approved these changes
@AapoSoukkio Looks good. I'm passing this on for a second review.

2023-08-06 14:58 UTC, SSwiniarski approved these changes
@AapoSoukkio Looks good.

2023-08-06 15:12 UTC, merged

2023-08-06 15:18 UTC, SSwiniarski commented
@AapoSoukkio Congrats on the new edits!

Live links:
- https://www.codecademy.com/resources/docs/python/math-module/math-pow
- https://www.codecademy.com/resources/docs/python/math-module/math-sin