Example02
Codecademy/docs pull request #2909
Opened 2023-08-02 09:32 UTC by mfa34

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-02 09:32 UTC, mfa34 commented
@SSwiniarski

2023-08-03 16:56 UTC, SSwiniarski requested changes
@mfa34 I did a first review and left a few comments.

2023-08-03 16:56 UTC, SSwiniarski commented on content/go/concepts/generics/generics.md
> +Description: 'Generics is a programming feature that allows you to write versatile and reusable code that operates on different data types.'
```suggestion
Description: 'Generics are a programming feature that allows the programmer to write versatile and reusable code that operates on different data types.'
```

2023-08-03 16:56 UTC, SSwiniarski commented on content/go/concepts/generics/generics.md
> +**`Generics`** is a powerful feature introduced in Go 1.18 that empowers developers to write versatile and reusable code that operates on different data types. Generics provide a new level of express
```suggestion
**Generics** are a powerful feature introduced in Go 1.18 that empowers developers to write versatile and reusable code that operates on different data types. Generics provide a new level of expressiveness and flexibility to the language, allowing the creation of functions, methods, and data structures that work seamlessly across a range of types.
```

2023-08-03 16:56 UTC, SSwiniarski commented on content/go/concepts/generics/generics.md
> +## Type Constraints
```suggestion
## Type Constraints

```

2023-08-03 16:56 UTC, SSwiniarski commented on content/go/concepts/generics/generics.md
> +Type constraints enable you to specify requirements for the types used with generics. Common constraints include:
```suggestion
Type constraints enable the specification of requirements for the types used with generics. Common constraints include:
```

2023-08-03 16:56 UTC, SSwiniarski commented on content/go/concepts/generics/generics.md
> +## Benefits of Generics
```suggestion
## Benefits of Generics

```

2023-08-03 16:56 UTC, SSwiniarski commented on content/go/concepts/generics/generics.md
> +- `Modularity`: Generics promote modular design by enabling the creation of generic components that can be adapted to various contexts.
```suggestion
- Code Reusability: Generics allows the creation of functions and data structures that can work with multiple types, reducing the need for duplicated code.
- Type Safety: Compile-time type checking ensures that generic code is type-safe and minimizes runtime errors.
- Modularity: Generics promote modular design by enabling the creation of generic components that can be adapted to various contexts.
```

2023-08-03 16:56 UTC, SSwiniarski commented on content/go/concepts/generics/generics.md
> +-  Proper documentation and clear naming of type parameters are essential for code readability.
```suggestion
## Limitation and Considerations

- Generics are currently limited to functions and methods. They cannot be used with structs or interfaces.
- Generics in Go 1.18 have some differences compared to generics in other programming languages.
-  Proper documentation and clear naming of type parameters are essential for code readability.
```

2023-08-03 16:56 UTC, SSwiniarski commented on content/go/concepts/generics/generics.md
> +In Go **`generics`**, are defined using type parameters within function and method declarations. The syntax for declaring a generic function is as follows:
```suggestion
In Go, generics are defined using type parameters within function and method declarations. The syntax for declaring a generic function is as follows:
```

2023-08-03 16:56 UTC, SSwiniarski commented on content/go/concepts/generics/generics.md
> +- `T`: Represents the type parameter that can be replaced with actual types when using the function.
```suggestion

- `T`: Represents the type parameter that can be replaced with actual types when using the function.
```

2023-08-03 16:56 UTC, SSwiniarski commented on content/go/concepts/generics/generics.md
> +## Example
```suggestion
## Example

```
We like to see an introductory sentence to an example summarizing what it does.

2023-08-03 16:56 UTC, SSwiniarski commented on content/go/concepts/generics/generics.md
> +``` shell
````suggestion
```

This example results in the following output:

``` shell
````

2023-08-03 16:56 UTC, SSwiniarski commented on content/go/concepts/generics/generics.md
> +  For comprehensive details and usage examples, refer to the official [Go generics design draft](https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md).
```suggestion
```

We generally don't link out to other documentation in Docs.

2023-08-03 18:17 UTC, mfa34 commented
@SSwiniarski i checked, i updated  accordingly your suggestions, Sir.

2023-08-04 11:16 UTC, SSwiniarski approved these changes
@mfa34 I made a few more changes and it looks good for a second review.

2023-09-08 16:33 UTC, yangc95 commented on content/go/concepts/generics/generics.md
> +```go
```suggestion
```pseudo
```

2023-09-08 16:33 UTC, yangc95 approved these changes
@mfa34 nice! Looks gtg

2023-09-08 16:38 UTC, merged