Closes #2570 Added and edited Codebytes
Codecademy/docs pull request #2911
Opened 2023-08-02 10:45 UTC by alexawolajagit

### Description

Codebytes were edited and added in the compile.md and complex.md files.

### Type of Change

- Added a new example codebyte to compile.md. The new example shows another use of the compile function, by making use of a single expression.
- Edited an existing example in compile.md to include use of a function in the code block.
- Edited an existing example in complex.md to include a different string to convert into a complex number and the output of the function
- Updated the documentation in both complex.md and compile.md to reflect the changes made in both documents.

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-02 10:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2911) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2911) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2911) it.</sub>

2023-08-03 20:21 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/compile/compile.md
> +## Example 1
```suggestion
## Example
```

2023-08-03 20:23 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/compile/compile.md
> +```py
```suggestion
```codebyte/python
```

2023-08-03 20:25 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/compile/compile.md
> +```
remove these lines. The output will be visible when the user runs the code

2023-08-03 20:30 UTC, caupolicandiaz commented on content/python/concepts/built-in-functions/terms/complex/complex.md
> +## Example
These edits are just modifying the existing example. This example can stay as-is and you need to add a new example, ideally an example that is different from the existing (demonstrates some other functionality, a special case, etc) as a codebyte.

2023-08-04 10:09 UTC, alexawolajagit commented
@caupolicandiaz I have made the revisions as you requested, I hope they are acceptable. I am still fairly new to this process, please advise if i need to do anything my side for the workflow changes to be approved.
Thanks

2023-08-04 20:57 UTC, caupolicandiaz approved these changes
@alexawolajagit Overall, looks good. I just added some additional minor edits. This is ready for a second review.

2023-08-06 14:34 UTC, SSwiniarski requested changes
@alexawolajagit I did a second review and added a couple more edits.

2023-08-06 14:34 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/complex/complex.md
>  Converts a given string into a complex number.
```suggestion
The **`complex()`** function converts a given string, or pair of numbers, into a complex number.
```

2023-08-06 14:34 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/complex/complex.md
>  complex(real, imaginary)
```suggestion
result1 = complex(real, imaginary)
result2 = complex(string)
```

2023-08-06 14:34 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/complex/complex.md
```suggestion

- `real` is the real part of a complex number.
- `imaginary` is the imaginary part of a complex number.
- `string` is the string representation of a complex number.

```

2023-08-07 09:58 UTC, alexawolajagit commented
Thanks @SSwiniarski, I have made the edits as requested.

2023-08-07 15:55 UTC, SSwiniarski approved these changes
@alexawolajagit Looks good to merge.

2023-08-07 15:56 UTC, merged