add lua mathematical library entry
Codecademy/docs pull request #2923
Opened 2023-08-02 19:02 UTC by navea330

### Description

This PR adds a Lua mathematical library entry. This is part of the AoT Internship Lua project.

### Type of Change

- Adding a new entry

### Checklist

- [X ] All writings are my own.
- [ X] My entry follows the Codecademy Docs style guide.
- [X ] My changes generate no new warnings.
- [ X] I have performed a self-review of my own writing and code.
- [X ] I have checked my entry and corrected any misspellings.
- [X ] I have made corresponding changes to the documentation if needed.
- [ X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-02 19:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2923) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2923) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2923) it.</sub>

2023-08-04 19:24 UTC, lucwhite requested changes
Great work! Just a couple small changes

2023-08-04 19:24 UTC, lucwhite commented on content/lua/concepts/mathematical-library/mathematical-library.md
> +#### `math.max(x, ..)`
These should likely be terms but thats out of scope for the internship. Make note of this in the handoff doc

2023-08-04 19:24 UTC, lucwhite commented on content/lua/concepts/mathematical-library/mathematical-library.md
> +  - 'learn-lua'
```suggestion
  - 'learn-lua'
  - 'paths/computer-science'
```

2023-08-04 19:24 UTC, lucwhite commented on content/lua/concepts/mathematical-library/mathematical-library.md
> +To see a full list of math functions, visit [the Lua documentation page](https://www.lua.org/manual/5.1/manual.html#5.6).
```suggestion
To see a full list of math functions, visit the [Lua documentation page](https://www.lua.org/manual/5.1/manual.html#5.6).
```

2023-08-08 18:04 UTC, navea330 commented on content/lua/concepts/mathematical-library/mathematical-library.md
> +Description: "Lua's Mathematical Library holds built-in functions relating to math." # Required; ideally under 150 characters and starts with a noun (used in search engine results and content preview
```suggestion
Description: "Lua's Mathematical Library holds built-in functions relating to math" # Required; ideally under 150 characters and starts with a noun (used in search engine results and content previews)
```

2023-08-08 18:07 UTC, navea330 commented on content/lua/concepts/mathematical-library/mathematical-library.md
> +## Math Functions
```suggestion
## Math Functions

```

2023-08-15 01:41 UTC, yangc95 approved these changes
@navea330 Great base for building on top of! The functions you listed out will make great future terms 👍

2023-08-15 02:02 UTC, merged