Swiftui shape
Codecademy/docs pull request #2930
Opened 2023-08-03 02:10 UTC by kevveth

### Description

Created a new concept for SwiftUI covering the Shapes protocol. I am studying Swift and have been wanting to contribute to open-source projects, thus, I found this issue to be a good project.

Closes #2680 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-05 14:32 UTC, SSwiniarski requested changes
@kevveth I did a first review and left a few comments.

2023-08-05 14:32 UTC, SSwiniarski commented on .vscode/settings.json
You need to remove this file from the PR.

2023-08-05 14:32 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +Description: "Methods for implementing built-in and custom shapes in a SwiftUI view."
```suggestion
Description: "The Shape protocol is used for implementing built-in and custom shapes in a SwiftUI view."
```
While we generally omit the title in terms, we generally don't in concepts.

2023-08-05 14:32 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +<br>
```suggestion
```
Omit HTML. A simple blank line will suffice.

2023-08-05 14:32 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +- The function should return a `Path` object that describes the shape contained inside a rectangular frame of reference.
```suggestion

- The function should return a `Path` object that describes the shape contained inside a rectangular frame of reference.
```

2023-08-05 14:32 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +## Example: Custom Triangle Shape
```suggestion
## Example: Custom Triangle Shape

```

2023-08-05 14:32 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +Since there is no Triangle shape built-in, a custom one can be made using path operations.
```suggestion
Since there is no triangle shape built-in, a custom one can be made using path operations.
```

2023-08-05 14:32 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +<br>
```suggestion
```

2023-08-05 14:32 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +### Displaying the Custom Shape
```suggestion
### Displaying the Custom Shape

```

2023-08-05 14:32 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +![SwiftUI Shapes](https://raw.githubusercontent.com/Codecademy/docs/main/media/swiftui-shapes-triangle.jpeg The code displays a yellow triangle on a blue background)
```suggestion

This code results in the following output:

![SwiftUI Shapes](https://raw.githubusercontent.com/Codecademy/docs/main/media/swiftui-shapes-triangle.jpeg The code displays a yellow triangle on a blue background)
```

2023-08-08 11:35 UTC, SSwiniarski requested changes
@kevveth I made some more comments, mostly about deleting some garbage that made its way into the entry.

2023-08-08 11:35 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +<<<<<<< HEAD
```suggestion

```

2023-08-08 11:35 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +=======
```suggestion

Since there is no Triangle shape built-in, a custom one can be made using path operations.
```

2023-08-08 11:35 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +>>>>>>> a7f91915addc7e1fd9a5ae1bcb3a6d8d4db83343
```suggestion
```

2023-08-08 11:35 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +<br>
```suggestion
```

2023-08-08 11:35 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +
```suggestion
```

2023-08-08 11:35 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +>>>>>>> a7f91915addc7e1fd9a5ae1bcb3a6d8d4db83343
```suggestion
```

2023-08-08 11:35 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +=======
```suggestion
```

2023-08-08 11:35 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +>>>>>>> a7f91915addc7e1fd9a5ae1bcb3a6d8d4db83343
```suggestion

```

2023-08-08 11:35 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +<<<<<<< HEAD
Delete

2023-08-08 11:36 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +=======
Delete "======"

2023-08-08 11:36 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +>>>>>>> a7f91915addc7e1fd9a5ae1bcb3a6d8d4db83343
Delete

2023-08-08 11:36 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +<br>
Delete

2023-08-08 11:36 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +
Delete

2023-08-08 11:36 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +>>>>>>> a7f91915addc7e1fd9a5ae1bcb3a6d8d4db83343
Delete

2023-08-08 11:36 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +=======
Delete

2023-08-08 11:36 UTC, SSwiniarski commented on content/swiftui/concepts/shapes/shapes.md
> +>>>>>>> a7f91915addc7e1fd9a5ae1bcb3a6d8d4db83343
Delete

2023-08-09 01:07 UTC, kevveth commented
@SSwiniarski I see where I made the mistake, thank you for the help fixing things up. I went ahead and committed your suggestions. Please, let me know if there's anything else I can do.

2023-08-09 16:17 UTC, SSwiniarski approved these changes
@kevveth I made some changes to remove duplicated lines and this is now ready for a second review.

2023-08-28 18:26 UTC, yangc95 approved these changes
LGTM, liking the custom shape example ^^

2023-08-28 18:39 UTC, merged