Edit entries python codebyte
Codecademy/docs pull request #2935
Opened 2023-08-03 13:00 UTC by cslylla

### Description

- Updated the following entries:
  - Python Math functions: .ceil(),
  - Python Math functions: .cos(),
  - Python Math functions: .log(),
 
- With the following changes:
  - Add Codebyte section,
  - Fix typos.

- Closes: #2885 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-03 20:19 UTC, caupolicandiaz requested changes
@cslylla I've completed my initial review. Please update the entries, and tag me when you've finished making changes. Thanks

2023-08-03 20:19 UTC, caupolicandiaz commented on content/python/concepts/math-module/terms/math-ceil/math-ceil.md
>  ## Example 1
```suggestion
## Example 
```

2023-08-03 20:19 UTC, caupolicandiaz commented on content/python/concepts/math-module/terms/math-ceil/math-ceil.md
>  ## Example 1
I would also suggest removing one of the existing examples from these entries. These are all generally pretty basic methods and there isn't a lot gained by showing essentially the same functionality multiple times.

2023-08-03 20:19 UTC, caupolicandiaz commented on content/python/concepts/math-module/terms/math-cos/math-cos.md
>  ```py
```suggestion
```pseudo
```

2023-08-03 20:19 UTC, caupolicandiaz commented on content/python/concepts/math-module/terms/math-cos/math-cos.md
>  ```py
update all entries accordingly

2023-08-04 10:01 UTC, cslylla commented
@caupolicandiaz Thank you for the comments. I updated all files accordingly. I checked the style guide, and all the other files in the math function folder are incorrect (in issue #2888, #2887, #2886):
- Syntaxy should be `pseudo` (not `py`)
- Example should be `py` (not `python`)
- Codebyte (if there) should be `codebyte/python` (not `codebyte/py`)

I also noticed that the `.ceil()` function from this issue is also included in issue #2888.

2023-08-04 20:38 UTC, caupolicandiaz approved these changes
@cslylla Thanks for going through and reviewing the other terms and highlighting the duplicated issue. This looks good, ready for a second review.

2023-08-06 14:25 UTC, SSwiniarski requested changes
@cslylla I did a second review and left some edits which were mostly updates to the original entries to make them conform more to current practice.

2023-08-06 14:25 UTC, SSwiniarski commented on content/python/concepts/math-module/terms/math-cos/math-cos.md
> +Returns the cosine of an angle.
```suggestion
The **`math.cos()`** function returns the cosine of an angle.
```

2023-08-06 14:25 UTC, SSwiniarski commented on content/python/concepts/math-module/terms/math-cos/math-cos.md
> +The **`math.cos()`** function returns a numeric value between -1 and 1, which represents the cosine of the value `n`.
```suggestion
The `math.cos()` function returns a numeric value between -1 and 1, which represents the cosine of the value `n`.
```

2023-08-06 14:25 UTC, SSwiniarski commented on content/python/concepts/math-module/terms/math-log/math-log.md
> +Returns the natural logarithm of a number or the logarithm of a number to the given base.
```suggestion
The **`math.log()`** function returns the natural logarithm of a number or the logarithm of a number to the given base.
```

2023-08-06 14:25 UTC, SSwiniarski commented on content/python/concepts/math-module/terms/math-log/math-log.md
> +The **`math.log()`** function takes the following parameters:
```suggestion
The `math.log()` function takes the following parameters:
```

2023-08-06 14:25 UTC, SSwiniarski commented on content/python/concepts/math-module/terms/math-log/math-log.md
> +Use `math.log()` to return the natural log of `12` (base `e`):
```suggestion
Use `math.log()` to return the natural log of `12` (base _e_):
```

2023-08-07 15:20 UTC, SSwiniarski approved these changes
@cslylla Looks good to merge.

2023-08-07 15:24 UTC, merged