[Term Entry] PHP Math Functions: .atanh()
Codecademy/docs pull request #2940
Opened 2023-08-03 21:59 UTC by Dijok243

### Description

-Added the Math.atanh() term for PHP
-Closes issue #2398 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-03 21:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2940) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2940) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2940) it.</sub>

2023-08-04 22:00 UTC, caupolicandiaz requested changes
@Dijok243 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-08-08 01:22 UTC, Dijok243 commented
@caupolicandiaz I have made the changes requested, please check and tell me if there are more to do

2023-08-08 19:48 UTC, caupolicandiaz approved these changes
@Dijok243 I've made some additional edits that I missed in my initial review. Forwarding this along for a second review.

2023-08-09 16:34 UTC, merged