[Concept Entry]: AI Stochastic Gradient Descent
Codecademy/docs pull request #2941
Opened 2023-08-04 09:59 UTC by hitesh-gitdev

### Description

- Created concept entry for Stochastic Gradient Descent AI search algorithm.
- Closes issue - #2135 

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-11 16:15 UTC, SSwiniarski requested changes
@hitesh-gitdev I did a first review and left one comment.

2023-08-11 16:15 UTC, SSwiniarski commented on content/ai/concepts/search-algorithms/terms/stochastic-gradient-descent/stochastic-gradient-descent.md
> +5. **Repeat**: Steps 2 to 4 are repeated for a specified number of epochs or until a convergence criterion is met.
```suggestion
1. **Shuffle Data**: Training data is randomly shuffled before each epoch to introduce randomness and prevent biases in updates.
2. **Mini-Batch Selection**: A small subset (mini-batch) of data points is randomly selected from the shuffled training dataset.
3. **Compute Gradient**: The gradient of the cost function is computed using the selected mini-batch of data points. The gradient represents the direction of steepest descent, guiding the algorithm towards the minimum.
4. **Update Parameters**: Based on the calculated gradient, the model's parameters are updated. The learning rate determines the step size of these updates and controls the convergence speed of the algorithm.
5. **Repeat**: Steps 2 to 4 are repeated for a specified number of epochs or until a convergence criterion is met.
```

2023-08-12 16:34 UTC, SSwiniarski approved these changes
@hitesh-gitdev Sending this on to a second review.

2023-08-21 16:33 UTC, hitesh-gitdev commented
@SSwiniarski how may I expedite the second review?

2023-09-21 21:46 UTC, KTom101 requested changes
@hitesh-gitdev I've added a few changes mainly structural. Let me know if you have any questions

2023-09-21 21:46 UTC, KTom101 commented on content/ai/concepts/search-algorithms/terms/stochastic-gradient-descent/stochastic-gradient-descent.md
> +## Pseudocode for Stochastic Gradient Descent
remove this header
```suggestion
```

2023-09-21 21:46 UTC, KTom101 commented on content/ai/concepts/search-algorithms/terms/stochastic-gradient-descent/stochastic-gradient-descent.md
> +## Uses in Machine Learning
Move this section (Uses in Machine Learning) to before the section on (## Advantages of Stochastic Gradient Descent)

2023-10-05 06:47 UTC, hitesh-gitdev commented
@SSwiniarski @KTom101 I have addressed the comments from the 2nd PR review.

2023-10-06 22:26 UTC, KTom101 approved these changes
@hitesh-gitdev I made a couple more minor changes directly. This looks good to merge, thank you 🎉

2023-10-06 22:27 UTC, merged