Array-chunk.md has been added and is up for review
Codecademy/docs pull request #2945
Opened 2023-08-04 19:10 UTC by MellowZippy1

### Description

Adds a term entry of PHP Arrays array_chunk(). I have done this due to the Git & GitHub course on Codecademy. I'm doing this course because the Computer Science career path advised me to.
Closes #2875 

### Type of Change

- Adding a new entry

### Checklist

- [ x ] All writings are my own.
- [ x ] My entry follows the Codecademy Docs style guide.
- [ x ] My changes generate no new warnings.
- [ x ] I have performed a self-review of my own writing and code.
- [  x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-04 19:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2945) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2945) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: MellowZippy<br/>:x: MellowZippy1<br/><hr/>**MellowZippy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2945) it.</sub>

2023-08-04 19:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2945) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2945) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: MellowZippy<br/>:x: MellowZippy1<br/><hr/>**MellowZippy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2945) it.</sub>

2023-08-05 17:07 UTC, SSwiniarski commented
@MellowZippy1 You need to sign the [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2945). You also need to make sure both emails you're using for this PR are attached to your GitHub account.

2023-08-05 17:11 UTC, SSwiniarski requested changes
@MellowZippy1 I did a first review and left a few comments.

2023-08-05 17:11 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-chunk/array-chunk.md
> +The `array_chunk()` function has two required parameter and one optional parameter.
```suggestion
The `array_chunk()` function has two required parameters and one optional parameter.
```

2023-08-05 17:11 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-chunk/array-chunk.md
> +The `array_chunk()` function returns a multidimensional array, with each dimension containing **length** elements.
```suggestion
The `array_chunk()` function returns a multidimensional array, with each dimension containing `$length` elements.
```

2023-08-05 17:11 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-chunk/array-chunk.md
> +- `$preserve_keys`: When set to **true** keys will be preserved. The default is **false** which will reindex each chunk.
```suggestion
- `$preserve_keys`: When set to `true` keys will be preserved. The default is `false` which will reindex each chunk.
```

2023-08-05 17:11 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-chunk/array-chunk.md
> +> **Note:** The last chunk may contain less than **length** elements. Due to $preserve_keys being set to **true** the indexes in the chunks do not reindex.
```suggestion
> **Note:** The last chunk may contain less than `$length` elements. Due to `$preserve_keys` being set to `true` the indexes in the chunks do not reindex.
```

2023-08-05 17:11 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-chunk/array-chunk.md
> +> **Note:** The example used a `foreach` loop to cycle through the elements with each chunk. `implode()` is used to join the names of students in each chunk to create a readable format for output.
```suggestion
> **Note:** The example uses a `foreach` loop to cycle through the elements with each chunk. `implode()` is used to join the names of students in each chunk to create a readable format for output.
```

2023-09-24 19:57 UTC, SSwiniarski commented
@MellowZippy1 In the interest of moving this along, I committed my suggestions so this can go on to a second review.

2023-09-24 19:57 UTC, SSwiniarski approved these changes

2023-09-26 19:37 UTC, caupolicandiaz requested changes
@MellowZippy1 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-26 19:37 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-chunk/array-chunk.md
> +Desciprtion: 'Splits an array into chunks'
```suggestion
Description: 'Splits an array into a number of specified chunks.'
```

2023-09-26 19:37 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-chunk/array-chunk.md
> +Desciprtion: 'Splits an array into chunks'
the spacing within the metadata section looks incorrect. Please look at one of the templates or an existing doc for reference

2023-09-26 19:37 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-chunk/array-chunk.md
> +array_chunk(array $array, int $length, bool $preserve_keys = false)
```suggestion
array_chunk($array, $length, $preserve_keys)
```

2023-09-26 19:37 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-chunk/array-chunk.md
> +- `$length`: Specifies that amount of elements in a chunk.
```suggestion
- `$length`: An integer that specifies that amount of elements in a chunk.
```

2023-09-26 19:37 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-chunk/array-chunk.md
> +> **Note:** The last chunk may contain less than `$length` elements. Due to `$preserve_keys` being set to `true` the indexes in the chunks do not reindex.
```suggestion
> **Note:** The last chunk may contain less than `$length` elements.
```

2023-09-26 19:37 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-chunk/array-chunk.md
> +The following example uses the `array_chunk()` function to split an array of students into chunks of 5.
```suggestion
The following example uses the `array_chunk()` function to split an array of students into chunks of 5. Additionally, the `$preserve_keys` parameter is set as `true`, which maintains the existing indexes.
```

2023-09-26 19:37 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-chunk/array-chunk.md
> +> **Note:** The example uses a `foreach` loop to cycle through the elements with each chunk. `implode()` is used to join the names of students in each chunk to create a readable format for output.
```suggestion
> **Note:** The example uses a `foreach` loop to cycle through the elements with each chunk, and `implode()` is used to join the names of students in each chunk to create a readable format.
```

2023-10-09 19:07 UTC, caupolicandiaz approved these changes
@MellowZippy1 @SSwiniarski Since there hasn't been any activity on this entry, I've gone ahead and committed the suggestions I proposed. This is ready to merge

2023-10-10 16:20 UTC, merged