make the changes in PI file
Codecademy/docs pull request #2948
Opened 2023-08-05 12:31 UTC by tlokare

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-05 12:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=2948) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=2948) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=2948) it.</sub>

2023-08-05 17:01 UTC, SSwiniarski requested changes
@tlokare I did a first review and left a few comments.

2023-08-05 17:01 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/DIPU PI/PI.md
The entry is missing an example section showing Java code with `Math.PI` in use.

2023-09-04 14:36 UTC, SSwiniarski commented
@tlokare It's been a while. Are you still working on this entry? Do you need assistance implementing any of the suggestions above?

2023-09-14 21:23 UTC, caupolicandiaz commented
@tlokare @SSwiniarski I've gone ahead and made the updates. Let me know if further edits are needed.

2023-09-15 11:03 UTC, SSwiniarski approved these changes
@caupolicandiaz, @tlokare Looks good.

2023-09-22 12:09 UTC, yangc95 commented on content/java/concepts/math-methods/terms/pi/pi.md
> +    double circle_area = Math.PI * (circle_radius * circle_radius)
```suggestion
    double circle_area = Math.PI * (circle_radius * circle_radius);
```

2023-10-13 19:19 UTC, yangc95 commented
@tlokare After further eval, I won't be moving forward with a second review. We're trying to keep the terms table within the scope of math methods specifically.

Your idea here will be considered for a future issue to mention math constants that are available here! Thanks so much for your understanding and for creating this PR initially :)

2023-10-13 19:19 UTC, closed without merging

2023-10-13 21:34 UTC, yangc95 commented
@tlokare I've created an issue for this change here: https://github.com/Codecademy/docs/issues/3601

Feel free to grab it if no one has claimed it. Thank you!