[Term Entry] PHP Arrays shuffle()
Codecademy/docs pull request #2950
Opened 2023-08-05 22:31 UTC by MMMMMMMZ

### Description

Added The PHP Array function shuffle() which resolves #2822 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-06 14:02 UTC, SSwiniarski requested changes
@MMMMMMMZ I did a first review and left a couple of comments.

2023-08-06 14:02 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/shuffle/shuffle.md
> +- `$array`: Specifies the array to randomize Its elements.
```suggestion
- `$array`: Specifies the array to randomize.
```

2023-08-06 14:02 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/shuffle/shuffle.md
> +> **Note:** The Numbers Might Be arranged differently.
```suggestion
> **Note:** The numbers might be arranged differently.
```

2023-08-07 14:52 UTC, SSwiniarski approved these changes
@MMMMMMMZ Looks good for a second review.

2023-08-07 21:45 UTC, caupolicandiaz approved these changes
@MMMMMMMZ @SSwiniarski Overall in solid shape, I just pushed a few minor edits. Looks good to merge

2023-08-08 11:20 UTC, merged

2023-08-08 11:24 UTC, SSwiniarski commented
@MMMMMMMZ Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/php/arrays/shuffle

![image](https://github.com/Codecademy/docs/assets/86081858/77d143c6-6786-4df6-af77-7a83181b861f)