New entry for PHP array_count_values function
Codecademy/docs pull request #2951
Opened 2023-08-06 12:57 UTC by Judis07

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-06 14:17 UTC, SSwiniarski requested changes
@Judis07 I did a first review and left a couple of comments, basically about building out the syntax section.

2023-08-06 14:17 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-count-values/array-count-values.md
> +array_count_values($array)
```suggestion
$result = array_count_values($array)
```

2023-08-06 14:17 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-count-values/array-count-values.md
> +
```suggestion

- `$array` is the array whose values are being counted.
- `$result` is the resultant array with counts.

```

2023-08-07 02:45 UTC, Judis07 commented
@SSwiniarski suggested changes are now done. Please review.

2023-08-07 21:32 UTC, caupolicandiaz approved these changes
@Judis07 @SSwiniarski Just made some minor edits to the example intros. Looks good to merge

2023-08-08 11:18 UTC, merged

2023-08-08 11:23 UTC, SSwiniarski commented
@Judis07 Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/php/arrays/array-count-values

![image](https://github.com/Codecademy/docs/assets/86081858/550e2387-1f22-4dd1-a7cb-7319ecdce587)