Python add codebytes
Codecademy/docs pull request #2983
Opened 2023-08-07 16:28 UTC by karthikmurali60

### Description

- Added Codebytes examples for three Python file methods: math.ceil, PyTorch and tqdm.
- Closes Issue https://github.com/Codecademy/docs/issues/2888

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-07 16:29 UTC, karthikmurali60 commented
@SSwiniarski @caupolicandiaz I have recreated the PR. I have omitted adding codebytes for pytorch since it was mentioned that it is not supported yet. Please review the PR when you get a chance !

2023-08-10 00:54 UTC, karthikmurali60 commented
@SSwiniarski @caupolicandiaz kind reminder to review this PR

2023-08-13 01:57 UTC, KTom101 commented
@SSwiniarski @caupolicandiaz I see you were already reviewing this in the previous PR so I will let you continue on.

2023-08-13 14:12 UTC, SSwiniarski requested changes
@karthikmurali60 I just had a couple of comments.

2023-08-13 14:12 UTC, SSwiniarski commented on content/python/concepts/math-module/terms/math-ceil/math-ceil.md
> +
We usually have a sentence introducing the codebyte.

2023-08-13 14:12 UTC, SSwiniarski commented on content/python/concepts/modules/terms/tqdm/tqdm.md
> +
We usually have a sentence introducing the codebyte.

2023-08-13 14:14 UTC, SSwiniarski commented
@caupolicandiaz, I ran the tqdm codebyte in the codebyte editor, and while it did run, it didn't produce the output you'd expect in a real environment. Do we still want to include it?

2023-08-15 15:52 UTC, SSwiniarski commented
@karthikmurali60 Would you mind removing the tqdm codebyte from this PR?

2023-08-17 05:36 UTC, karthikmurali60 commented
@SSwiniarski I have addressed your review comments and also removed the tqdm codebyte from this PR. Please review when you get a chance. Thanks

2023-08-17 16:38 UTC, SSwiniarski approved these changes
@karthikmurali60 Looks good.

2023-08-17 16:43 UTC, merged