[Edit] Python Added Codebyte in .lower()
Codecademy/docs pull request #2987
Opened 2023-08-08 16:43 UTC by ChiragAgg5k

### Description

Edited lower.md to add a codebyte. Closes  #2981 .

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-08 21:55 UTC, caupolicandiaz requested changes
@ChiragAgg5k I've added a couple comments. Please update, and tag me when you've finished making changes. Thanks

2023-08-08 21:55 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/lower/lower.md
> +user_favorite_color = input("What is your favorite color? : ")
the input() function isn't supported by the Codecademy compiler so this example will throw an error. Please revise the example. Additionally, note that docs code uses 2 spaces, not tabs. The use of tabs will return file errors.

2023-08-09 03:24 UTC, ChiragAgg5k commented
@caupolicandiaz I have made the changes.

2023-08-13 07:19 UTC, ChiragAgg5k commented
Hey @caupolicandiaz hope you are not too busy. Just mentioning you again in case this pr slipped past you.

2023-08-15 16:52 UTC, SSwiniarski approved these changes
@ChiragAgg5k Looks good.

2023-08-15 16:53 UTC, merged