feat: adding entry about mdx
Codecademy/docs pull request #2993
Opened 2023-08-09 02:37 UTC by CBID2

### Description
This PR adds a new file called `mdx.md`, which explains the concept of MDX.
Closes #2872 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-09 02:52 UTC, CBID2 commented
Hi @KTom101! :) I'm ready for a review! :)

2023-08-12 01:23 UTC, KTom101 requested changes
@CBID2 I added a few changes

2023-08-12 01:23 UTC, KTom101 commented on content/markdown/concepts/mdx/mdx.md
> +```mdx
```suggestion
```pseudo
```

2023-08-12 01:23 UTC, KTom101 commented on content/markdown/concepts/mdx/mdx.md
> +export default MyMDX;
Don't forget to close the block (```)

2023-08-12 01:23 UTC, KTom101 commented on content/markdown/concepts/mdx/mdx.md
> +md
```suggestion
```md
```

2023-08-12 01:23 UTC, KTom101 commented on content/markdown/concepts/mdx/mdx.md
> +**MDX** is an extension to Markdown that allows developers to include JSX and import components like interactive charts and alerts to Markdown documents that contain long content more engaging.
```suggestion
**MDX** is an extension to Markdown that allows developers to include JSX and import components like interactive charts and alerts to Markdown documents that contain lengthy content more engaging.
```

2023-08-12 01:26 UTC, CBID2 commented
> @CBID2 I added a few changes 

Done @KTom101

2023-08-12 01:53 UTC, KTom101 approved these changes
@CBID2 Just one more change but this is ready for a 2nd round of review.

2023-08-12 01:53 UTC, KTom101 commented on content/markdown/concepts/mdx/mdx.md
> +```
```suggestion
```

```

2023-08-12 18:38 UTC, SSwiniarski requested changes
@CBID2 I did a review and had one comment.

2023-08-12 18:38 UTC, SSwiniarski commented on content/markdown/concepts/mdx/mdx.md
> +**MDX** is an extension to Markdown that allows developers to include JSX and import components like interactive charts and alerts to Markdown documents that contain lengthy content more engaging.
```suggestion
**MDX** is an extension to Markdown that allows developers to include JSX and import components like interactive charts and alerts to make Markdown documents that contain lengthy content more engaging.
```

2023-08-12 19:06 UTC, CBID2 commented
> @CBID2 I did a review and had one comment.

Done @SSwiniarski

2023-08-13 13:26 UTC, SSwiniarski approved these changes
@CBID2 Looks good.

2023-08-13 13:44 UTC, merged