[New Term entry] added getDisplayNames.md
Codecademy/docs pull request #2995
Opened 2023-08-09 18:09 UTC by ChiragAgg5k

### Description

Added java term entry for getDisplayNames() method of the Calendar class. Closes #2980 .

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-09 20:17 UTC, caupolicandiaz requested changes
@ChiragAgg5k I've added my initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-08-09 20:17 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getDisplayNames/getDisplayNames.md
> +The `.getDisplayNames()` method of the `Calendar` class returns a map containing all string representations of Calendar field values in the given style and locale and the corresponding field values.
```suggestion
The `.getDisplayNames()` method of the `Calendar` class returns a map containing the string representations of the field values in the given style and locale.
```

2023-08-09 20:17 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getDisplayNames/getDisplayNames.md
> +Throws [NullPointerException](https://www.codecademy.com/resources/docs/java/errors/nullpointerexception) if `locale` is `null`.
```suggestion
The function will throw a [`NullPointerException`](https://www.codecademy.com/resources/docs/java/errors/nullpointerexception) if `locale` is `null`.
```

2023-08-09 20:17 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getDisplayNames/getDisplayNames.md
> +The following example, `.getDisplayNames()` method returns a map containing all days of the week in short form for the US locale. The days are paired with integer values representing the index of the
```suggestion
In the following example, `.getDisplayNames()` method returns a map containing all the days of the week in short form for the US locale. The days are paired with integer values representing the index of the day in the week (Sunday is 1, Monday is 2, etc.)
```

2023-08-10 05:12 UTC, ChiragAgg5k commented
@caupolicandiaz I have made the changes.

2023-08-11 16:39 UTC, SSwiniarski approved these changes
@ChiragAgg5k Looks good!

2023-08-11 16:40 UTC, merged