Concept Entry Javascript Accessors
Codecademy/docs pull request #3013
Opened 2023-08-14 08:09 UTC by Judis07

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-15 12:23 UTC, droffilc1 commented on content/javascript/concepts/accessors/accessors.md
> +  - 'Methods'
To enhance the clarity of your code, consider adding more tags. For instance, including tags like 'Objects' and 'Classes' would help make the purpose and structure of your code even more apparent

2023-08-15 12:23 UTC, droffilc1 commented on content/javascript/concepts/accessors/accessors.md
> +In JavaScript, object properties can be accessed using accessor known as getters. The `get` keyword is used to define a getter method for establishing custom behavior when accessing the values of obj
A JavaScript object property can be accessed using accessors known as getters. The `get` keyword is used to define a getter method for establishing custom behavior when accessing the values of object properties.

2023-08-15 12:31 UTC, droffilc1 requested changes
@Judis07 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-08-16 12:55 UTC, SSwiniarski commented
@Judis07 after you're finished with the user review above, tag me and I'll do a first maintainer review.

2023-08-21 21:03 UTC, caupolicandiaz requested changes
@Judis07 I've added several comments. Please review carefully, and update the entry. Tag me when you've finished making changes. Thanks

2023-08-21 21:03 UTC, caupolicandiaz commented on content/javascript/concepts/accessors/accessors.md
> +In JavaScript, object properties can be accessed using accessor known as getters. The `get` keyword is used to define a getter method for establishing custom behavior when accessing the values of obj
```suggestion
In JavaScript, object properties can be obtained using **accessors**.  Properties are established and retrieved with methods known as "getters" and "setters". 

The `get` keyword is used to define a getter method for establishing a custom behavior when accessing the values of object properties, while the `set` keyword is used to create a setter method that determines the behavior when assigning values to those properties.
```

2023-08-21 21:03 UTC, caupolicandiaz commented on content/javascript/concepts/accessors/accessors.md
> +The following example defines a `User` class with a constructor and a getter method. It demonstrates how to encapsulate and access the GitHub profile information of a user using accessor methods.
I would suggest using a generic/fictional user and not your GitHub user profile

2023-08-23 13:56 UTC, Judis07 commented
@caupolicandiaz I have made all suggested changes that were mentioned. Please review again. Thanks

2023-08-23 13:59 UTC, Judis07 commented on content/javascript/concepts/accessors/accessors.md
> +Description: "Provides access to an object's properties by using the dot notation or the bracket notation."
This was never my intention. I had no idea that my description matches with MDN, it was purely a coincident. However, i have corrected this and will be more careful about such things. Thanks for the heads up.

2023-08-23 17:08 UTC, caupolicandiaz requested changes
@Judis07 A couple of additional edits. Please update. Thanks

2023-08-23 17:08 UTC, caupolicandiaz commented on content/javascript/concepts/accessors/accessors.md
> +Description: "Offers access to an object's properties through either dot notation or bracket notation."
```suggestion
Description: 'Offers access to the properties of an object through either dot notation or bracket notation.'
```

2023-08-23 17:08 UTC, caupolicandiaz commented on content/javascript/concepts/accessors/accessors.md
> +Description: "Offers access to an object's properties through either dot notation or bracket notation."
metadata must only use single quotes and there is no punctuation permitted within the description

2023-08-25 13:27 UTC, Judis07 commented
@caupolicandiaz changes are done please review.

2023-08-26 11:42 UTC, SSwiniarski commented
@Judis07 can you update this with main so we can merge?

2023-08-26 13:41 UTC, Judis07 commented
@SSwiniarski update with main.

2023-08-26 17:11 UTC, merged