Term Entry Java Calendar Complete
Codecademy/docs pull request #3017
Opened 2023-08-15 14:48 UTC by codeolly

### Description

A Markdown file (complete.md) created to briefly explain the complete() method of the Calendar class in Java.
The document has a short explanation, then the syntax and an example.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-15 14:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3017) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3017) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3017) it.</sub>

2023-08-15 19:45 UTC, caupolicandiaz requested changes
@codeolly I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-08-15 19:45 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/complete/complete.md
> +protected void complete()
```suggestion
someCalendar.complete()
```

2023-08-15 19:45 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/complete/complete.md
> +Title: 'complete()'
```suggestion
Title: '.complete()'
```

2023-08-15 19:45 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/complete/complete.md
> +> **Note:** If the time value has not been calculated from the calender field values, the computeTime() method is called. Then to calculate all calendar field values, the computeFields() method is ca
```suggestion
> **Note:** If the time value has not been calculated from the calender field values, the `.computeTime()` method is called. Then to calculate all calendar field values, the `.computeFields()` method is called.
```

2023-08-15 19:45 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/complete/complete.md
> +The example below demonstrates the use of the complete() method.
```suggestion
The example below demonstrates the use of the `.complete()` method.
```

2023-08-15 19:45 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/complete/complete.md
> +      Main cal = new Main();
```suggestion
      CalendarCompleteExample cal = new CalendarCompleteExample();
```

2023-08-15 19:45 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/complete/complete.md
> +   public static void main(String[] args) {
all examples should use spaces(2) instead of tabs

2023-08-16 12:20 UTC, codeolly commented
@caupolicandiaz thank you for the suggestions, all revisions have been made and commited again.

2023-08-16 16:59 UTC, caupolicandiaz approved these changes
@codeolly Looks good, this is ready for a second review.

2023-08-21 16:51 UTC, SSwiniarski approved these changes
@codeolly Looks good!

2023-08-21 17:06 UTC, merged