add 'what-is-an-object'
Codecademy/docs pull request #302
Opened 2021-10-05 04:44 UTC by pavankalyan-codes

2021-10-05 04:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=302) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=302) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=302) it.</sub>

2021-10-05 05:23 UTC, sonnynomnom commented
This one requires two reviews from the three of us @Dusch4593 @yangc95.

2021-10-05 06:43 UTC, sonnynomnom requested changes
Made some changes. Please make the changes before it goes through review #2 from another maintainer.

Also, I wonder if you can add some history about Objects. When and why it was invented. And how it's used in programs today (OOP).

2021-10-05 06:43 UTC, sonnynomnom commented on content/general/concepts/what-is-an-object/what-is-an-object.md
> +Description: 'An Object is an instance of a class. It is created when we instantiate the class. Object contains the properties and functionalities. When an Object is created memory will be allocated
Let's shorten the Description in the metadata:

```
Description: 'An object is an instance of a class. It has the properties and behaviors of its class.'
```

2021-10-05 06:43 UTC, sonnynomnom commented on content/general/concepts/what-is-an-object/what-is-an-object.md
> +CatalogContent:
Let's only have 2 items here. So let's do:

```
CatalogContent:
  - 'learn-c-plus-plus'
  - 'paths/computer-science'
  ```

2021-10-05 06:43 UTC, sonnynomnom commented on content/general/concepts/what-is-an-object/what-is-an-object.md
> +An Object is an instance of a class. It is created when we instantiate the class. Object contains the properties and functionalities. When an Object is created memory will be allocated for it.
lowercase object:

An object is an instance of a class. It is created when we instantiate the class. 

An object contains the properties and functionalities of its class. When an object is created, memory will be allocated for it.

2021-10-05 06:43 UTC, sonnynomnom commented on content/general/concepts/what-is-an-object/what-is-an-object.md
> +class Employee{
Use triple tick java

```java
// Creating the Employee class
class Employee {
  int id;
  String firstName;
  String lastName;
  char middleInitial;
  float years;
}

// Creating five different objects from the Employee class
Employee tina = new Employee();
Employee louise = new Employee();
Employee linda = new Employee();
Employee bob = new Employee();
Employee gene = new Employee();
```

2021-10-05 06:43 UTC, sonnynomnom commented on content/general/concepts/what-is-an-object/what-is-an-object.md
> +In the above example we created an object for the class ***Employee***. In Java we create an object using the **new** keyword. The **new** keyword tells the compiler to create a new instance of a cla
In the above example, we created five different objects from the class `Employee`.

2021-10-05 07:01 UTC, yangc95 commented
Great first entry; make sure to stick to the [PR template](https://github.com/Codecademy/docs/blob/main/.github/PULL_REQUEST_TEMPLATE.md) when submitting a PR!

Looking forward to reviewing your entry ^^

2021-10-06 05:40 UTC, yangc95 approved these changes

2021-10-06 07:27 UTC, sonnynomnom commented
Hi @pavankalyan-codes, make sure to go through these checkboxes again:

<img width="647" alt="Screen Shot 2021-10-06 at 3 26 54 AM" src="https://user-images.githubusercontent.com/4999022/136158610-fda6a306-ffd0-4c63-96b0-ece7983cc427.png">

2021-10-06 16:21 UTC, sonnynomnom approved these changes

2021-10-06 16:23 UTC, merged

2021-10-06 17:43 UTC, pavankalyan-codes commented
> Congrats @pavankalyan-codes! Just merged and live:
> 
> https://www.codecademy.com/resources/docs/general/what-is-an-object
> 
> We might need to revisit this again to add some historical context for objects and OOP.

Thanks @sonnynomnom :)  Learnt a lot while making this contribution. Will try to make a couple of more contributions.