[Term Entry] added .before() for Calendar class of Java
Codecademy/docs pull request #3022
Opened 2023-08-16 13:51 UTC by ChiragAgg5k

### Description

Added new term entry for .before() method of Calendar class in Java. closes #2966 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-16 14:13 UTC, SSwiniarski requested changes
@ChiragAgg5k I did a first review and had a couple of comments.

2023-08-17 05:41 UTC, ChiragAgg5k commented
@SSwiniarski made the requested changes.

2023-08-17 16:43 UTC, SSwiniarski approved these changes
@ChiragAgg5k Looks good for a second review.

2023-08-18 20:48 UTC, caupolicandiaz requested changes
@ChiragAgg5k I've just added a few comments. Please update, and tag me when you've finished making changes. Thanks

2023-08-18 20:48 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/before/before.md
> +The **`.before()`** method of the `Calendar` class is used to check if the time given by one Calendar instance is before the time given by another Calendar instance.
```suggestion
The **`.before()`** method of the `Calendar` class is used to check if one `Calendar` instance is before another.
```

2023-08-18 20:48 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/before/before.md
> +> **Note:** The `.before` method returns `false` if the two `Calendar` instances represent the same time.
```suggestion
> **Note:** The `.before()` method returns `false` if the two `Calendar` instances represent the same time.
```

2023-08-18 20:48 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/before/before.md
> +Description: 'Checks if time given by one Calendar instance is before the time given by another Calendar instance.'
```suggestion
Description: 'Returns a boolean based on the whether one Calendar instance is before the other given instance.'
```

2023-08-18 20:48 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/before/before.md
> +In the example below, two `Calendar` instances are created. The first represents the current date and time, the second represents the current date and time plus two hours. The `.before` method is use
```suggestion
In the example below, two `Calendar` instances are created. The first represents the current date and time, the second represents the current date and time plus two hours. The `.before()` method is used to check if the `myCalendar` object is before the `otherCalendar` object. The method is also used to check if the `myCalendar` object is before itself.
```

2023-08-19 05:50 UTC, ChiragAgg5k commented
@caupolicandiaz i am done with the changes.

2023-08-19 19:30 UTC, caupolicandiaz approved these changes
@ChiragAgg5k @SSwiniarski LGTM

2023-08-20 11:57 UTC, merged