Added a markdown file containing information on the getAvailableLocal…
Codecademy/docs pull request #3024
Opened 2023-08-16 16:24 UTC by ReprogramAkash

### Description

This PR contains a markdown file that contains information on the getAvailableLocales method of the calendar class.

### Type of Change

- Updating the documentation

2023-08-16 16:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3024) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3024) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3024) it.</sub>

2023-08-16 19:56 UTC, caupolicandiaz requested changes
@ReprogramAkash I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Also edit the PR description to include the checklist, as required. Thanks

2023-08-16 19:56 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getAvailableLocales/getAvailableLocales.md
> +Description: 'Returns an array of all locales available in java runtime environment.'
```suggestion
Description: 'Returns an array of all locales available in the Java runtime environment.'
```

2023-08-16 19:56 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getAvailableLocales/getAvailableLocales.md
> +The `.getAvailableLocales()` method of the `Calendar` class is used to return an array of all locales. getAvailableLocals() method is a static method.
```suggestion
The **`.getAvailableLocales()`** method of the `Calendar` class is used to return an array of all locales. In other words, an array of all locales for which there are `Calendar` instances.
```

2023-08-16 19:56 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getAvailableLocales/getAvailableLocales.md
> +
```suggestion
Locale.getAvailableLocales()  
```

2023-08-16 19:56 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getAvailableLocales/getAvailableLocales.md
> +       // an object of local class called strlocal(array) is created
```suggestion
       // An object of local class called strlocal(array) is created   
```

2023-08-16 19:56 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getAvailableLocales/getAvailableLocales.md
> +       // an object of local class called strlocal(array) is created
Comments should begin with a capital and all indentations should use 2 spaces not tabs

2023-08-16 19:56 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getAvailableLocales/getAvailableLocales.md
> +This will output the following:
```suggestion
This will output a result similar to the following:
```

2023-09-26 22:05 UTC, caupolicandiaz commented
@ReprogramAkash This entry hasn't been any activity on this entry. Are you still available to complete this edit?

2023-09-29 10:35 UTC, ReprogramAkash commented
> @ReprogramAkash There hasn't been any activity on this entry. Are you still available to complete this edit?

Hi, yes, I will update the PR with the requested changes shortly. Thanks!

2023-10-21 21:44 UTC, caupolicandiaz commented
@ReprogramAkash I'm closing this due to lack of progress.

2023-10-21 21:44 UTC, closed without merging