Python dates
Codecademy/docs pull request #303
Opened 2021-10-05 05:53 UTC by ramanic

### Description
I have added new entry dates for python topic.

### Type of Change

- Adding a new entry

### Checklist

- [ x] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

2021-10-05 05:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=303) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=303) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=303) it.</sub>

2021-10-05 06:27 UTC, sonnynomnom requested changes
Some very minor tweaks to start. Please make the changes so we can move on to review #2!

2021-10-05 06:27 UTC, sonnynomnom commented on content/python/concepts/dates/dates.md
> +
Delete extra newline.

2021-10-05 06:27 UTC, sonnynomnom commented on content/python/concepts/dates/dates.md
> +
Delete extra newline.

2021-10-05 06:27 UTC, sonnynomnom commented on content/python/concepts/dates/dates.md
> +
Delete extra newline.

2021-10-05 06:27 UTC, sonnynomnom commented on content/python/concepts/dates/dates.md
> +
Delete extra newline.

2021-10-05 06:27 UTC, sonnynomnom commented on content/python/concepts/dates/dates.md
> +Description: 'Python does not have any data types for date and time but we can work with date and time in python using "datetime" module. It comes built in with python so we do not have to install it
```
Description: 'The built-in Python module called datetime is used to create and modify dates and times.'
```

2021-10-05 06:27 UTC, sonnynomnom commented on content/python/concepts/dates/dates.md
> +Python doesn't have a data type for datetime but there is built in module called [datetime](https://docs.python.org/3/library/datetime.html) that can be used to create and modify datetime objects.
There's a built-in module called [datetime](https://docs.python.org/3/library/datetime.html) that can be used to create and modify `datetime` objects.

2021-10-05 06:27 UTC, sonnynomnom commented on content/python/concepts/dates/dates.md
> +The result will be the current date and time as below :
Delete extra space before the `:`

2021-10-05 06:27 UTC, sonnynomnom commented on content/python/concepts/dates/dates.md
> +
Delete extra line.

2021-10-05 06:27 UTC, sonnynomnom commented on content/python/concepts/dates/dates.md
> +
Delete extra line.

2021-10-05 06:27 UTC, sonnynomnom commented on content/python/concepts/dates/dates.md
> +#get current datetime
```
# Get current datetime
```

2021-10-05 06:27 UTC, sonnynomnom commented on content/python/concepts/dates/dates.md
> +#get current datetime
```
# Get current datetime
```

2021-10-05 06:59 UTC, ramanic commented
Please check, I have made the changes.

2021-10-05 07:15 UTC, sonnynomnom commented
@yangc95 @Dusch4593 

I made a quick pass. One of you should give it a more thorough review tomorrow!

2021-10-05 20:04 UTC, caupolicandiaz commented on content/python/concepts/dates/dates.md
> +The module comes built in with python so installation is not required but we need to import it at top of Python file as below:
```suggestion
The module comes built-in with Python so installation is not required, but we do need to import it at top of a Python file as below:
```

2021-10-05 20:09 UTC, caupolicandiaz commented on content/python/concepts/dates/dates.md
> +
```suggestion
```

2021-10-05 20:15 UTC, caupolicandiaz commented on content/python/concepts/dates/dates.md
> +It contains year,month,day,hour,minute,second and microsecond.
```suggestion
It contains the year, month, day, hour, minute, second and microsecond.
```

2021-10-05 20:16 UTC, caupolicandiaz commented on content/python/concepts/dates/dates.md
> +`datetime` module have three main available types i.e `date` , `time` and `datetime`.
```suggestion
The `datetime` module has three main available types: `date` , `time` and `datetime`.
```

2021-10-05 20:18 UTC, caupolicandiaz commented on content/python/concepts/dates/dates.md
> +# Create datetime object with year=2021, month=10, day=5,hour=10,minute=5 and second=31
```suggestion
# Creates datetime object with year=2021, month=10, day=5, hour=10, minute=5 and second=31
```

2021-10-05 20:22 UTC, caupolicandiaz commented on content/python/concepts/dates/dates.md
> +Further more we also have a timedelta type which is used to represent time difference.
```suggestion
Furthermore, we also have a timedelta type which is used to represent time difference.
```

2021-10-05 20:29 UTC, caupolicandiaz commented on content/python/concepts/dates/dates.md
> +## Operations on datetime object
```suggestion
## Operations on a datetime Object
```

2021-10-05 20:33 UTC, caupolicandiaz commented on content/python/concepts/dates/dates.md
> +For example `.datetime.now()` method will return the current date and time.
```suggestion
A basic example is employing the `.datetime.now()` method to return the current date and time:
```

2021-10-05 20:39 UTC, caupolicandiaz commented on content/python/concepts/dates/dates.md
> +All arguments are optional and have default value of 0.
```suggestion
Note that all of the arguments are optional and have default value of 0.
```

2021-10-05 20:39 UTC, caupolicandiaz commented on content/python/concepts/dates/dates.md
> +We can perform different operation on a datetime object.
```suggestion
We can perform different operations on a datetime object.
```

2021-10-05 20:41 UTC, caupolicandiaz commented on content/python/concepts/dates/dates.md
> +# Displays date 2 months from current date.
```suggestion
# Displays date 2 months from current date
```

2021-10-05 20:43 UTC, caupolicandiaz commented on content/python/concepts/dates/dates.md
> +Date and time difference can be calculated using difference operation in `datetime` module.
```suggestion
Date and time difference can be calculated using the difference or subtraction operator on `datetime` objects.
```

2021-10-05 20:47 UTC, caupolicandiaz commented on content/python/concepts/dates/dates.md
> +#Get current datetime
```suggestion
#Get current datetime
```

2021-10-05 21:08 UTC, caupolicandiaz requested changes
I've made some suggested changes for readability and consistency, but overall many of the edits are spacing and punctuation.

2021-10-06 03:10 UTC, ramanic commented
@caupolicandiaz Thanks, I have committed the chages.

2021-10-06 03:35 UTC, sonnynomnom reviewed
Some final changes!

2021-10-06 06:46 UTC, merged

2021-10-06 06:57 UTC, sonnynomnom commented
Merged! Congrats!

I made some more changes here btw: https://github.com/Codecademy/docs/blob/main/content/python/concepts/dates/dates.md

cc @caupolicandiaz @ramanic

2021-10-06 15:28 UTC, ramanic commented
Cool thanks :), will love to contribute more.