added first draft SingleValueEncodingContainer doc
Codecademy/docs pull request #3033
Opened 2023-08-19 00:11 UTC by turtelneck

### Description

I created the first draft of a document about the SingleValueEncodingContainer protocol, including a brief description and example. Not sure if the example is a bit overlong, my idea was to create simple, self-contained code.

### Type of Change

N/A

### Checklist

- [ x ] All writings are my own.
- [ x ] My entry follows the Codecademy Docs style guide.
- [ x ] My changes generate no new warnings.
- [ x ] I have performed a self-review of my own writing and code.
- [ x ] I have checked my entry and corrected any misspellings.
- [ x ] I have made corresponding changes to the documentation if needed.
- [ x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-19 00:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3033) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3033) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3033) it.</sub>

2023-08-20 14:30 UTC, SSwiniarski requested changes
@turtelneck I did a first review and left a few comments.

2023-08-20 14:30 UTC, SSwiniarski commented on content/swift/concepts/protocols/SingleValueEncodingContainer.md
> +Title: 'SingleValueEncodingContainer Protocols'
```suggestion
Title: 'SingleValueEncodingContainer'
```

2023-08-20 14:30 UTC, SSwiniarski commented on content/swift/concepts/protocols/SingleValueEncodingContainer.md
> +The values you can encode will depend on the chosen encoding format (JSON, plist, etc.).
```suggestion
The values that can be encoded will depend on the chosen encoding format (JSON, plist, etc.).
```

2023-08-20 14:30 UTC, SSwiniarski commented on content/swift/concepts/protocols/SingleValueEncodingContainer.md
> +```
We typically have a sentence explaining the syntax.

2023-08-20 14:30 UTC, SSwiniarski commented on content/swift/concepts/protocols/SingleValueEncodingContainer.md
> +
You need a introductory sentence summarizing the example.

2023-08-20 14:30 UTC, SSwiniarski commented on content/swift/concepts/protocols/SingleValueEncodingContainer.md
> +```
You need a ` ```shell` block following the example showing the output, like this:

````
This example results in the following output:

```shell
The example's output
```
````

2023-08-20 14:30 UTC, SSwiniarski commented on content/swift/concepts/protocols/SingleValueEncodingContainer.md
> +Official Swift Documentation: https://developer.apple.com/documentation/swift/singlevalueencodingcontainer
```suggestion
```

We don't like to link to off-site documentation in Docs.

2023-09-27 22:11 UTC, caupolicandiaz commented
@turtelneck It has been several weeks and there hasn't been any updates to this entry. Are you still available to finish this?

2023-10-18 22:02 UTC, caupolicandiaz commented
@turtelneck @SSwiniarski I'm closing this due to inactivity

2023-10-18 22:02 UTC, closed without merging