AI Linear Activation Function (Issue #2700)
Codecademy/docs pull request #3036
Opened 2023-08-19 11:45 UTC by shanmukha-m-k

AI Linear Activation Function (Issue #2700)

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [*] All writings are my own.
- [*] My entry follows the Codecademy Docs style guide.
- [*] My changes generate no new warnings.
- [*] I have performed a self-review of my own writing and code.
- [*] I have checked my entry and corrected any misspellings.
- [*] I have made corresponding changes to the documentation if needed.
- [*] I have confirmed my changes are not being pushed from my forked `main` branch.
- [*] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [*] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-20 14:19 UTC, SSwiniarski requested changes
@shanmukha-m-k I did a first review and left a few comments.

2023-08-20 14:19 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/linear-activation-function/linear-activation-function.md
> +Description: 'The linear activation function also known as identity function, where the activation is proportional to the input.'
```suggestion
Description: 'The linear activation function, also known as the identity function, is where the activation is proportional to the input.'
```

2023-08-20 14:19 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/linear-activation-function/linear-activation-function.md
> +The **linear activation function** is also known as **straight-line function** where the activation is proportional to the input.The function doesn't do anything to the weighted sum of the input, it
```suggestion
The **linear activation function**, also known as the identity function, is where the activation is proportional to the input. The function doesn't do anything to the weighted sum of the input, it simply spits out the value it was given.
```

2023-08-20 14:19 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/linear-activation-function/linear-activation-function.md
> +chosen by the user.
There's no variable "a" in the above equation.

2023-08-20 14:19 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/linear-activation-function/linear-activation-function.md
> +The problem with this activation is that it cannot be defined in a specific range. Applying this function in all the nodes makes the activation function work like linear regression.
```suggestion
The problem with this activation function is that it cannot be defined for a specific range. Applying this function in all the nodes makes the activation function work like linear regression.
```

2023-08-20 15:31 UTC, shanmukha-m-k commented
i have commited suggested changes plz review once

2023-08-21 11:20 UTC, SSwiniarski approved these changes
@shanmukha-m-k Looks good for a second review.

2023-08-24 15:29 UTC, HishamT requested changes
Hey @shanmukha-m-k, I have reviewed your entry and left you some comments. 

One major issue I noticed is that some of text and a picture were taken from another article on the web. As this can be seen as plagiarism, you will have to rewrite those parts. Remember, that all writing submitted must be original! We do not allow plagiarized content on Codecademy. Thank you!

2023-08-29 12:57 UTC, shanmukha-m-k commented
@HishamT Thanks for your suggestion sir  . I committed suggested changes please review once

2023-09-05 17:37 UTC, HishamT requested changes
Hey @shanmukha-m-k, I have reviewed your entry and left you some comments.

2023-09-05 17:37 UTC, HishamT commented on content/ai/concepts/neural-networks/terms/linear-activation-function/linear-activation-function.md
> +The **linear activation function**, also known as the identity function, is one of the most straight-forward activation function,where the output of linear activation function is exactly same as inpu
```suggestion
The **linear activation function**, also known as the identity function, is a straight-forward activation functions where the output is exactly same as the input.
```

2023-09-05 17:37 UTC, HishamT commented on content/ai/concepts/neural-networks/terms/linear-activation-function/linear-activation-function.md
> +![linear Activation Function Equation](https://raw.githubusercontent.com/Codecademy/docs/main/media/linear-equation.png)
This link yields a 404 error

2023-09-05 17:37 UTC, HishamT commented on content/ai/concepts/neural-networks/terms/linear-activation-function/linear-activation-function.md
> +In general , linear activation function simply add weighted sum with bias and pass it as output.
This statement contains some grammatical errors and is unclear. Can you reword it?

2023-09-05 17:37 UTC, HishamT commented on content/ai/concepts/neural-networks/terms/linear-activation-function/linear-activation-function.md
> +Using linear activation functions would not able to the model to learn complex non-linear relationships between input's and output's.
This statement needs to be reworded.

2023-09-06 10:59 UTC, shanmukha-m-k commented
@SSwiniarski @HishamT  Hi sir , I have committed suggested changes please review once

2023-09-12 11:28 UTC, SSwiniarski commented
@HishamT Are we good to merge?

2023-09-12 14:20 UTC, HishamT approved these changes
LGTM

2023-09-12 14:37 UTC, merged