[Term Entry] Go Math Functions Hypot()
Codecademy/docs pull request #3037
Opened 2023-08-19 16:45 UTC by MarkTunstall

### Description

-Added the Hypot() term for Go
-Closes issue #2831 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-19 20:10 UTC, caupolicandiaz requested changes
@MarkTunstall I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-08-19 20:10 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/hypot/hypot.md
> +- If '0' is passed as both arguments, the result is '0'.
```suggestion
- If `0` is passed as both arguments, the result is `0`. If one of the arguments is `0` the result is equal to the other argument.
```

2023-08-19 20:10 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/hypot/hypot.md
> +- If either argument is negative, the result is positive.
```suggestion
- If either argument is negative, or both, the result is positive.
```

2023-08-19 20:10 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/hypot/hypot.md
> +- If both arguments are negative, the result is positive.
```suggestion
- If either argument is positive infinity (`+Inf`), the result will be positive infinity.
```

2023-08-19 20:10 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/hypot/hypot.md
> +- If either argument is passed as '0', the result is the other argument.
```suggestion
- If either argument passed is `NaN`, the result will be `NaN`.
```

2023-08-19 20:10 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/hypot/hypot.md
> +    fmt.Printf("Hypot of -1.5 and -1.5 = %f\n", math.Sqrt((-1.5 * -1.5)+(-1.5 * -1.5)))
```suggestion
    fmt.Printf("Hypot of 3 and 4 = %f\n", math.Hypot(3 , 4))
    fmt.Printf("Hypot of -1.5 and -1.5 = %f\n", math.Hypot(-1.5,-1.5))
```

2023-08-19 20:10 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/hypot/hypot.md
> +package main
The code should be indented with 2 spaces, tabs are not used in docs

2023-08-19 20:10 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/hypot/hypot.md
> +```codebyte/golang
make the same corrections here as in the block above

2023-08-19 20:10 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/hypot/hypot.md
> +The runnable example of the 'Hypot()' function of the cases where '0' or a negative number is at least one of the arguments.
```suggestion
The runnable example of the `Hypot()` function of the cases where `0` or a negative number is at least one of the arguments. 
```

2023-08-20 18:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3037) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3037) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3037) it.</sub>

2023-08-20 19:06 UTC, MarkTunstall commented on content/go/concepts/math-functions/terms/hypot/hypot.md
> +```
result = math.Hypot(x, y)

```

2023-08-20 19:10 UTC, MarkTunstall commented on content/go/concepts/math-functions/terms/hypot/hypot.md
> +```
thanks @caupolicandiaz, just added spacing in now.

2023-08-20 20:13 UTC, MarkTunstall commented
@caupolicandiaz I have commited the changes you suggested.

2023-08-21 16:56 UTC, caupolicandiaz requested changes
@MarkTunstall I've added a few additional comments. Please update, and tag me when you're finished. Thanks

2023-08-21 16:56 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/hypot/hypot.md
> +  - 'Arithmatic'
```suggestion
  - 'Arithmetic'
```

2023-08-21 16:56 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/hypot/hypot.md
> +hypotenuse = $`\sqrt{(x * x) + (y * y)}`$
The inline formatting isn't supported in docs. The formula should be inside a code block with the latex call ```tex

2023-08-21 16:56 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/hypot/hypot.md
> +```go
The entire code block should be shifted left and the indentations should use 2 spaces, tabs are not used in docs

2023-08-21 16:56 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/hypot/hypot.md
> +  Hypotenuse of 3 and 4 = 5.000000
remove the spaces at the start of these lines

2023-08-21 16:56 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/hypot/hypot.md
> +```codebyte/golang
same edits as the code block above

2023-08-21 17:52 UTC, MarkTunstall commented
@caupolicandiaz I've updated the markdown file with your suggestions.

2023-08-21 19:07 UTC, caupolicandiaz approved these changes
@MarkTunstall There were a couple of edits that were not completed accurately. I went ahead and made them directly. Please note that the changes to the example code for future reference. This is ready for a second review.

2023-08-22 14:14 UTC, merged