feat: add entry about IT
Codecademy/docs pull request #3052
Opened 2023-08-22 19:26 UTC by CBID2

### Description
This PR adds a new file, "information-technology.md", which provides an overview of Information Technology (IT) and gives people an idea of other sectors in the tech industry that they can pursue. 
Closes #3029

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-22 19:30 UTC, CBID2 commented
Hey @SSwiniarski! :) I'm ready for a review

2023-08-23 17:26 UTC, SSwiniarski commented on content/information-technology/information-technology.md
I have two main thoughts looking at this entry:

1. This should be a concept under the General topic, not a topic in its own right.
2. It should be longer and go into more depth. At least have a full paragraph or two.

2023-08-23 18:00 UTC, CBID2 commented
> @CBID2 I have a couple of overall comments I'd like to see addressed, then I may have other comments later.

Hi @SSwiniarski. I used this approach after being inspired by the Cybersecurity entry. I plan on adding a section of terms at the end.

2023-09-09 19:45 UTC, CBID2 commented
> > @CBID2 I have a couple of overall comments I'd like to see addressed, then I may have other comments later.
> 
> Hi @SSwiniarski. I used this approach after being inspired by the Cybersecurity entry. I plan on adding a section of terms at the end.

@yangc95, what do you think?

2023-09-19 02:07 UTC, CBID2 commented on content/information-technology/information-technology.md
Hi @SSwiniarski! :) I thought about what you said and decided to put it as a General topic. I also made some additions to the entry. Check them out and let me know what you think.

2023-09-20 03:18 UTC, CBID2 commented
@SSwiniarski, I'm ready for a review! :)

2023-09-20 11:35 UTC, SSwiniarski requested changes
@CBID2 I did a review and left a few comments. One thing that's important, you need to update the metadata now that it's no longer a topic.

2023-09-20 11:35 UTC, SSwiniarski commented on content/general/information-technology/information-technology.md
> +---
You still need to format the Metadata as a term entry, it's still laid out as a topic.

2023-09-20 11:35 UTC, SSwiniarski commented on content/general/information-technology/information-technology.md
> +<link rel="cannonical" href="https://www.codecademy.com/courses/introduction-to-it/articles/it-overview"/>
Don't use HTML in the Markdown.

2023-09-20 11:35 UTC, SSwiniarski commented on content/general/information-technology/information-technology.md
> +**Information Technology**, also known as IT, is the use of digital technological tools to store and turn data into useful information. Since we live in a technology-driven world, IT plays a major ro
Can we rewrite this without using "we" or "our"?

2023-09-20 11:35 UTC, SSwiniarski commented on content/general/information-technology/information-technology.md
> +These are the common roles in the IT industry:
```suggestion
These are some common roles in the IT industry:
```

2023-09-20 11:35 UTC, SSwiniarski commented on content/general/information-technology/information-technology.md
> +- Network Engineers: Designs,plans, and implements network infrastructures ranging from local area networks(LANs), wide area networks(WANs), and intranets for businesses and organizations. Also analy
```suggestion
- Network Engineers: Designs, plans, and implements network infrastructures ranging from local area networks(LANs), wide area networks(WANs), and intranets for businesses and organizations. Also analyzes network traffic and discusses suggestions how to optimize it to fulfill the organization/business' needs.
```

2023-09-20 11:35 UTC, SSwiniarski commented on content/general/information-technology/information-technology.md
> +- Desktop Support Personnel: Typically provides tech support(e.g.,restoring and backing up data to mobile devices) to customers via computer or phone.
```suggestion
- Desktop Support Personnel: Typically provides tech support (e.g. restoring and backing up data to mobile devices) to customers via computer or phone.
```
Can we include more than one example, they do more than restoring/backing up data.

2023-09-20 11:35 UTC, SSwiniarski commented on content/general/information-technology/information-technology.md
> +Some IT roles require applicants to become certified. Common types of certifications include:
No Microsoft certifications? Should include at lest the most popular one or two.

2023-09-21 03:56 UTC, CBID2 commented
I made the necessary changes @SSwiniarski

2023-09-21 16:19 UTC, CBID2 commented on content/general/information-technology/information-technology.md
> +  - 'Information Technology'
The documentation mentioned that I can add a new one @SSwiniarski.

2023-09-21 16:20 UTC, CBID2 commented on content/general/information-technology/information-technology.md
> +  - 'information technology'
The documentation mentions that I can add a new one @SSwiniarski.

2023-09-22 11:19 UTC, SSwiniarski commented on content/general/information-technology/information-technology.md
> +  - 'Information Technology'
> The documentation mentioned that I can add a new one @SSwiniarski.

@CBID2 Then you need to add the term to the subjects file in this PR.

2023-09-22 11:20 UTC, SSwiniarski commented on content/general/information-technology/information-technology.md
> +  - 'information technology'
> The [documentation](https://github.com/Codecademy/docs/blob/main/documentation/tags.md) mentions that I can add a new one @SSwiniarski

Then you need to add the term to the Tags file in this PR. (And capitalize it.)

2023-09-22 23:41 UTC, CBID2 commented
Made the changes @SSwiniarski

2023-09-23 15:30 UTC, SSwiniarski approved these changes
@CBID2 Looks good for a second review.

2023-10-07 21:30 UTC, KTom101 requested changes
@CBID2 I've added some changes!

2023-10-07 21:30 UTC, KTom101 commented on content/general/information-technology/information-technology.md
> +- Desktop Support Personnel: Typically provides tech support (e.g. restoring and backing up data to mobile devices) to customers via computer or phone.
```suggestion
- Desktop Support Personnel: Typically provides tech support (e.g. restoring and backing up data to mobile devices) to customers via computer or phone. Handles a range of technical issues, including hardware and software problems.
```

2023-10-07 21:30 UTC, KTom101 commented on content/general/information-technology/information-technology.md
> +**Information Technology**, also known as IT, is the use of digital technological tools to store and turn data into useful information. Due to living in a technology-driven world, IT plays a major ro
I think we should broaden the definition a little bit more. Feel free to change the wording. 
```suggestion
**Information Technology**, also known as IT, is the use of digital tools and technologies to store, process, obtain, transmit, and manage useful information. IT encompasses a spectrum of tasks, including designing, implementing, and maintaining systems, networks, databases, and applications. Due to living in a technology-driven world, IT plays a major role in people's lives whether it's fixing a cracked screen on a phone, doing a data transfer from an old computer to another one, or repairing a PC's hardware.
```

2023-10-07 21:34 UTC, CBID2 commented
> @CBID2 I've added some changes!

@KTom101, I made the changes! :)

2023-10-07 21:51 UTC, KTom101 approved these changes
@CBID2 Looks Good

2023-10-07 21:56 UTC, KTom101 commented
@CBID2 There is one additional change needed so the check passes. The file path needs to be changed so it's located in the general concepts folder.

2023-10-07 22:01 UTC, CBID2 commented
> @CBID2 There is one additional change needed so the check passes. The file path needs to be changed so it's located in the general concepts folder.

Hi @KTom101! :) I'm confused on what to change. The IT folder is in the General concepts one.

2023-10-07 22:06 UTC, KTom101 commented
@CBID2 The current path is `content/general/information-technology/information-technology.md` which is causing one of the checks to fail. 

It needs to be `content/general/concepts/information-technology/information-technology.md` adding in the "concepts" folder which is where all the other entries are located.

2023-10-07 22:08 UTC, CBID2 commented
> @CBID2 The current path is `content/general/information-technology/information-technology.md` which is causing one of the checks to fail. 
> 
> It needs to be `content/general/concepts/information-technology/information-technology.md` adding in the "concepts" folder which is where all the other entries are located. 

Ok, I think I got it @KTom101. :)

2023-10-07 22:10 UTC, KTom101 commented
> > @CBID2 The current path is `content/general/information-technology/information-technology.md` which is causing one of the checks to fail. 
> > 
> > It needs to be `content/general/concepts/information-technology/information-technology.md` adding in the "concepts" folder which is where all the other entries are located. 
> 
> Ok, I think I got it @KTom101. :)

Let me know if you have any trouble! I could always make the change on my end.

2023-10-07 22:13 UTC, CBID2 commented
> > > @CBID2 The current path is `content/general/information-technology/information-technology.md` which is causing one of the checks to fail. 
> > > 
> > > It needs to be `content/general/concepts/information-technology/information-technology.md` adding in the "concepts" folder which is where all the other entries are located. 
> > 
> > Ok, I think I got it @KTom101. :)
> 
> Let me know if you have any trouble! I could always make the change on my end. 

Things are fine @KTom101. The checks have passed! :)

2023-10-07 22:22 UTC, KTom101 commented
Great!

2023-10-07 22:22 UTC, merged