[Term Entry] PHP Array Method: array_splice()
Codecademy/docs pull request #3056
Opened 2023-08-23 21:00 UTC by bccarruth927

### Description

- Add the term entry for the array_splice method in PHP
- Closes issue #3049 

### Type of Change

- Adding a new entry

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-23 21:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3056) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3056) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3056) it.</sub>

2023-08-23 21:38 UTC, caupolicandiaz requested changes
@bccarruth927 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-08-23 21:38 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-splice/array-splice.md
> +Description: 'Removes a set of elements from an array and replaces them with a new set of elements'
```suggestion
Description: 'Removes a set of elements from an array and replaces them with a new set of elements.'
```

2023-08-23 21:38 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-splice/array-splice.md
> +The **`array_splice()`** method takes an array as it's input value and replaces elements within the array with new elements. The developer can specify within the method the index value
```suggestion
The **`array_splice()`** method takes an array as it's input value and replaces elements within the array with new elements. The developer can specify within the method the starting index value for the replacement values, and the length of the values to be replaced.
```

2023-08-23 21:38 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-splice/array-splice.md
> +the replacement values begin as well as the length of index values to be replaced in the original array.
```suggestion
```

2023-08-23 21:38 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-splice/array-splice.md
> +  index value. 1 = second value of the `array`. If a negative number is provided the replacement will start at that number from the last index value. -3 = third value from last of the `array`.
```suggestion
  - `$input_array`: The original array that will recieve the new elements.
  - `$starting_index`: The index value that specifies where the replacement elements will start within the `$input_array`. 
  
 > **Note:** Positive and negative index values are valid arguments for the `$starting_index`. A negative number  counts from the last index value in the array (i.e. -3 equals third value from last).
```

2023-08-23 21:38 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-splice/array-splice.md
> +  **Optional Parameters**
this header should not be indented

2023-08-23 21:38 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-splice/array-splice.md
> +    - `$replacement_length`: Is the length of values to be replaced within the `$input_array`. 2 = two values will be replaced within `$input_array` starting at `$starting_index`.
```suggestion
    - `$replacement_length`: The length of values to be replaced within the `$input_array`. 
```

2023-08-23 21:38 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-splice/array-splice.md
> +    - `$replacement_values`: Is an array that contains the new values that will be 'spliced' into the `$input_array`.
```suggestion
    - `$replacement_values`: An array that contains the new values that will be 'spliced' into the `$input_array`.
```

2023-08-23 21:38 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-splice/array-splice.md
> +      - **Note** If there is only one replacement value a `string` can be used in place of an `array`.
```suggestion
> **Note:** If there is only one replacement value a `string` can be used in place of an `array`.
```

2023-08-23 21:38 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-splice/array-splice.md
> +This runnable codebyte example demonstrates a before (the array in it's original state) and after (the array after alteration by array_splice()) of an array.
```suggestion
This runnable codebyte example demonstrates an alteration using `array_splice()`.
```

2023-08-25 23:04 UTC, bccarruth927 commented
@caupolicandiaz I apologize for the delay in updating the PR. I have made a second commit with the recommended changes provided and am awaiting a secondary review.

2023-08-28 17:31 UTC, caupolicandiaz approved these changes
@bccarruth927 Looks good. This is ready for another review.

2023-08-29 15:49 UTC, SSwiniarski requested changes
@bccarruth927 I did a review and left a few comments.

2023-08-29 15:49 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-splice/array-splice.md
> +  > **Note:** If there is only one replacement value a `string` can be used in place of an `array`.
```suggestion
> **Note:** If there is only one replacement value a `string` can be used in place of an `array`.
```

2023-08-29 20:44 UTC, bccarruth927 commented
@SSwiniarski I have made the adjustments based on your suggestions. Ready for another review.

2023-08-30 11:10 UTC, SSwiniarski approved these changes
@bccarruth927 Looks good.

2023-08-30 11:17 UTC, merged