[Term Entry] PHP Arrays array_column()
Codecademy/docs pull request #3057
Opened 2023-08-24 11:34 UTC by wierci

### Description

- Add the term entry for the array_splice method in PHP
- Closes issue #2876 

### Type of Change

- Adding a new entry

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-24 11:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3057) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3057) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3057) it.</sub>

2023-08-24 17:23 UTC, caupolicandiaz requested changes
@wierci I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-08-24 17:23 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-column/array-column.md
> +In this example, the first names from an array are returned.
```suggestion
In this example, the `first_name` keys are returned using the `array_column()` method.
```

2023-08-24 17:23 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-column/array-column.md
> +Additionally, the returened values can be indexed by the "id" column:
```suggestion
Additionally, the returned values can be indexed by the `id` column:
```

2023-08-24 17:23 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-column/array-column.md
> +);
I think we don't need to duplicate this part and we can just show the method with the new arguments

2023-08-24 17:23 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-column/array-column.md
> +  [2] => Lois
this looks like it's missing the ids

2023-08-24 17:23 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-column/array-column.md
> +The following codebyte example declares a `$colorFabric`. It then returns all fabric types in a new array called `$fabrics`.
```suggestion
The following codebyte example is runnable and utilizes the `array_column()` method.
```

2023-08-24 17:23 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-column/array-column.md
> +  array('color' => 'beige', 'fabric' => 'linen'))
```suggestion
  array('color' => 'beige', 'fabric' => 'linen')
```

2023-08-25 11:58 UTC, wierci commented
@caupolicandiaz I've updated the entry and finished making changes.

2023-08-26 18:07 UTC, SSwiniarski approved these changes
@wierci Looks good.

2023-08-26 18:11 UTC, merged