[Term Entry] PHP Arrays array_uniqe()
Codecademy/docs pull request #3059
Opened 2023-08-24 14:23 UTC by ChiragAgg5k

### Description

- Added the term entry for array_uniqe() method in PHP.
- Closes #3050 .

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-24 17:09 UTC, caupolicandiaz requested changes
@ChiragAgg5k I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-08-24 17:09 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-unique/array-unique.md
> +Description: 'Used to remove duplicate values from an array.'
```suggestion
Description: 'Returns an array without duplicate values.'
```

2023-08-24 17:09 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array-unique/array-unique.md
> +The **`array_unique()`** function removes duplicate values from an array.
```suggestion
The **`array_unique()`** function returns a new array with any duplicate values removed.
```

2023-08-24 17:28 UTC, ChiragAgg5k commented
@caupolicandiaz i have made the changes

2023-08-25 16:37 UTC, caupolicandiaz approved these changes
@ChiragAgg5k Looks good. This is ready for a second review

2023-08-26 17:31 UTC, SSwiniarski approved these changes
@ChiragAgg5k Looks good.

2023-08-26 17:33 UTC, merged