[Edit]Add Codebytes Content/c sharp/concepts/math functions/terms/sqrt/sqrt.md
Codecademy/docs pull request #3085
Opened 2023-08-27 15:14 UTC by bimbolaolawale

### Description

Edited an existing term entry on math.sqrt and math.tanh functions for c-sharp
closes issue number #2982 
### Type of Change

- 
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x ] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-27 15:17 UTC, bimbolaolawale commented
@SSwiniarski Please check this out.Thanks

2023-08-28 11:34 UTC, SSwiniarski commented
@bimbolaolawale I think you need to look at the source of other entries to see what a codebyte is supposed to look like. These aren't codebytes. They're code grafted on to existing examples. That's not what's being asked for. You need to add something like the following to the end of the entries:

````
## Codebyte Example

Sentence summarizing what the codebyte is doing.

```codebyte/csharp

Code for the codebyte

```
````

Once you correct this, tag me and I'll do a first review.

2023-08-29 20:33 UTC, bimbolaolawale commented
@SSwiniarski Thanks for your patience with me and guidance. Please check out the correction and advise on what to do next. Thanks.

2023-08-30 11:08 UTC, SSwiniarski requested changes
@bimbolaolawale I left a few more comments for you.

2023-08-30 11:08 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/sqrt/sqrt.md
> +
````suggestion
```

````

2023-08-30 11:08 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +  ```codebyte/csharp
```suggestion
```codebyte/csharp
```

2023-08-30 11:08 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +}using System;
```suggestion
using System;
```

2023-08-30 11:08 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +
```suggestion
```

2023-08-30 11:08 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +  is positive it returns 1.
```suggestion
  This codebyte demonstrates the `Math.tanh()` function:
```

2023-08-30 11:08 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/sqrt/sqrt.md
> +The code below demonstrates that  when an argument ('x') is negative the method would return Nan with the use of `Math.sqrt()` function.
```suggestion
The code below demonstrates that  when an argument ('x') is negative the `.sqrt()` method would return `NaN`:
```

2023-08-30 11:08 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/sqrt/sqrt.md
> +
```suggestion
```codebyte/csharp
using System;

namespace MysquareRoot {
  public class Example {
    public static void Main()
      {
        double x = -81;
        Console.Write(Math.Sqrt(x));
      }
    }
  }
```

2023-08-30 11:08 UTC, SSwiniarski commented on content/c-sharp/concepts/math-functions/terms/tanh/tanh.md
> +  }
```suggestion
public class program
{
  public static void Main(string[] args)
  {
    double num1 = 60.0, num2 = 0.0, num3 = 1.0;
    double tanhvalue = Math.Tanh(num1);
    Console.WriteLine("The tanh of num1 = " + tanhvalue);

    tanhvalue = Math.Tanh(num2);
    Console.WriteLine("The tanh of num2 = " + tanhvalue);

    tanhvalue = Math.Tanh(num3);
    Console.WriteLine("The tanh of num3 = " + tanhvalue);
  }
}
```

2023-08-30 11:33 UTC, SSwiniarski commented
@bimbolaolawale Please just edit this branch rather than creating new PRs.

2023-09-01 08:31 UTC, bimbolaolawale commented
@SSwiniarski Hello, Please check out the update. Thanks

2023-09-01 11:18 UTC, SSwiniarski approved these changes
@bimbolaolawale I deleted the extra docs folder and now this is ready for a second review.

2023-09-01 12:47 UTC, bimbolaolawale commented
Thank you so much for your support 


Sent from Yahoo Mail for iPhone


On Friday, September 1, 2023, 12:18 pm, SSwiniarski ***@***.***> wrote:




@SSwiniarski approved this pull request.

@bimbolaolawale I deleted the extra docs folder and now this is ready for a second review.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-09-01 21:57 UTC, caupolicandiaz approved these changes
@bimbolaolawale @SSwiniarski I noticed that the sqrt entry already had a codebyte. The new codebyte didn't really improve on what was there, so I reverted the changes. Looks good to merge

2023-09-01 22:06 UTC, merged