[Concept Entry] C# Interfaces
Codecademy/docs pull request #3090
Opened 2023-08-27 16:49 UTC by manviii27

### Description

 Added a new concept in C# `Interfaces` . File Location: `docs/content/c-sharp/concepts/interfaces/interfaces.md`

### Type of Change

- Adding a new entry

### Checklist

- [ ✓] All writings are my own.
- [ ✓] My entry follows the Codecademy Docs style guide.
- [ ✓] My changes generate no new warnings.
- [ ✓] I have performed a self-review of my own writing and code.
- [ ✓] I have checked my entry and corrected any misspellings.
- [ ✓] I have made corresponding changes to the documentation if needed.
- [ ✓] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ✓] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ✓] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-31 15:50 UTC, SSwiniarski requested changes
@manviii27 I did a first review and only had a couple of comments.

2023-08-31 15:50 UTC, SSwiniarski commented on content/c-sharp/concepts/interfaces/interfaces.md
> +To create an interface in C#, you use the `interface` keyword. The syntax for defining an interface in C# is:
```suggestion
An interface in C# is created using the `interface` keyword. The syntax for defining an interface in C# is:
```
No first- or second-person pronouns in Docs.

2023-08-31 15:50 UTC, SSwiniarski commented on content/c-sharp/concepts/interfaces/interfaces.md
> +The following examples show various comment styles:
```suggestion
The following example shows implementation of an interface:

```

2023-09-04 08:43 UTC, manviii27 commented
@SSwiniarski I've made the changes, please check. Thank you.

2023-09-04 14:18 UTC, SSwiniarski approved these changes
@manviii27 this is ready for a second review.

2023-09-09 21:49 UTC, caupolicandiaz approved these changes
@manviii27 @SSwiniarski Just made a couple minor edits. Looks good to merge

2023-09-10 11:53 UTC, merged