Java get time in millis
Codecademy/docs pull request #3123
Opened 2023-08-29 17:36 UTC by bcaro1221

### Description

This pull request is addressing the following [issue](https://github.com/Codecademy/docs/issues/3097). This is adding documentation for the Java method .getTimeInMillis() off of the Calendar class, which returns the calendar date and time represented in milliseconds. Closes #3097

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-29 17:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3123) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3123) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3123) it.</sub>

2023-08-29 18:22 UTC, bcaro1221 commented
@codecademy-docs is there a specific way I am to add reviewers? Also if the merge is blocked would I need to refetch the original repository?

2023-08-29 19:35 UTC, caupolicandiaz commented
> @codecademy-docs is there a specific way I am to add reviewers? Also if the merge is blocked would I need to refetch the original repository?

The only work you are responsible for is updating the entry to address the review comments. All the other tasks are done by maintainers.

2023-08-29 20:20 UTC, caupolicandiaz requested changes
@bcaro1221 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-08-29 20:20 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getTimeInMillis/getTimeInMillis.md
> +	- 'Code Foundations'
the indentations within the metadata section is incorrect. Please review one of our templates for reference.

2023-08-29 20:20 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getTimeInMillis/getTimeInMillis.md
> +The **`.getTimeInMillis()`** method of the `Calendar` class returns the time represented by a calendar object in the form of milliseconds.
```suggestion
The **`.getTimeInMillis()`** method of the `Calendar` class returns the time represented by a `Calendar` object in the form of milliseconds.
```

2023-08-29 20:20 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getTimeInMillis/getTimeInMillis.md
> +
There should be some additional information here, such as what is the expected return value

2023-08-29 20:20 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getTimeInMillis/getTimeInMillis.md
> +This example code creates a calendar object, records the current time, sets and records the time back to 12:00 AM the same day, and then prints the difference.
```suggestion
This example code creates a `Calendar` object, records the current time, sets a new time, and then prints the difference.
```

2023-08-29 20:20 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getTimeInMillis/getTimeInMillis.md
> +```java
the code should use 2 spaces for indentations not tabs

2023-08-29 20:20 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getTimeInMillis/getTimeInMillis.md
> +The output of the code above is the time passed in milliseconds today from 12:00 AM.
The output should be in a ```shell block

And there should be a sentence before the block such as "The output of the code will be similar to:"

2023-08-29 23:01 UTC, bcaro1221 commented
Hi I'm having trouble with my stack of local commits at the moment and definitely would like some guidance before I push my newest commit with the suggested changes. So I tried to commit the changes and push them but then I got a message saying: 
```shell
error: failed to push some refs to 'https://github.com/bcaro1221/codecademy_docs.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
```

So I tried pulling and got the following message:

```shell
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
```

I tried looking this up and doing the recommended steps but the only thing that worked in regards to pulling was when I ran `git rebase`. But it looks like `git rebase` created a commit titled `Merge branch 'main' into JavaGetTimeInMillis` which looks like it merged master in to my newer commit. I was wondering if I should roll it back/if you all had any advice on what to do here (what the correct procedure is for fetching the origin updates after my pull request is already created?) or if this was the correct. @codecademy-docs @caupolicandiaz

2023-08-30 16:46 UTC, caupolicandiaz approved these changes
@bcaro1221 It can be difficult to diagnose the errors without more information. I went ahead and made the remaining edit directly. The branch is fine as is stands right now. This is ready now for a second review.

2023-08-30 18:51 UTC, bcaro1221 commented
Sgtm. Can I leave a feature request on the git lesson that asks to contribute to this open source resource? Specifically, in regards to this issue. Though I'm new to git I've had fair share of experience in the code review process, and I know that code review can sometimes take more than a day given people's schedules. Was wondering if y'all could add text specifically describing what to do after you get feedback on a pull request and there are new changes in the source/origin which need to be pulled in to your branch in order to make your changes? Thanks! @codecademy-docs @caupolicandiaz

2023-08-30 19:16 UTC, caupolicandiaz commented
> Sgtm. Can I leave a feature request on the git lesson that asks to contribute to this open source resource? Specifically, in regards to this issue. Though I'm new to git I've had fair share of experience in the code review process, and I know that code review can sometimes take more than a day given people's schedules. Was wondering if y'all could add text specifically describing what to do after you get feedback on a pull request and there are new changes in the source/origin which need to be pulled in to your branch in order to make your changes? Thanks! @codecademy-docs @caupolicandiaz

I would recommend reviewing our contribution resources such as -
https://www.codecademy.com/resources/docs/contribution-guide/creating-a-pull-request-and-revisions

2023-08-31 16:11 UTC, SSwiniarski approved these changes
@bcaro1221 Looks good to me.

2023-08-31 16:13 UTC, merged