[Term Entry] PHP Math Functions round()
Codecademy/docs pull request #3124
Opened 2023-08-29 18:56 UTC by LewisMK

### Description

Closes #2395 

### Type of Change

- Adding a new entry

### Checklist

- [*] All writings are my own.
- [*] My entry follows the Codecademy Docs style guide.
- [*] My changes generate no new warnings.
- [*] I have performed a self-review of my own writing and code.
- [*] I have checked my entry and corrected any misspellings.
- [*] I have made corresponding changes to the documentation if needed.
- [*] I have confirmed my changes are not being pushed from my forked `main` branch.
- [*] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [*] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-29 19:57 UTC, caupolicandiaz requested changes
@LewisMK I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-08-29 19:57 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/round/round.md
> +Description: 'Round a number to the nearest whole number or to specified decimal numbers.'
```suggestion
Description: 'Returns the nearest whole number to the passed value, or the value rounded to the specified decimal precision.'
```

2023-08-29 19:57 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/round/round.md
> +The **`round()`** converts an integer or a float to the nearest whole number or to specified decimal numbers.
```suggestion
The **`round()`** returns an integer or a float to the nearest whole number or to the specified decimal precision.
```

2023-08-29 19:57 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/round/round.md
> +$roundedNumber = round($number);
```suggestion
$roundedNumber = round($number, $decimals, $roundMode);
```

2023-08-29 19:57 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/round/round.md
> +$roundedNumber = round($number);
I recommend having one syntax block with all the parameters. And address each parameter below.

2023-08-29 19:57 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/round/round.md
> +$originalNumber = 3.1415927;
```suggestion
$piConstant = pi();
```

2023-08-29 19:57 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/round/round.md
> +$roundedNumber = round($originalNumber, 3);
```suggestion
$roundedNumber = round($piConstant, 3);
```

2023-08-29 19:57 UTC, caupolicandiaz commented on content/php/concepts/math-functions/terms/round/round.md
> +echo "Rounded Number: $roundedNumber";
```suggestion
echo "Original Number: $piConstant\n";
echo "Rounded Number: $roundedNumber";
```

2023-09-09 22:06 UTC, caupolicandiaz approved these changes
@LewisMK I made a couple of direct edits to the syntax section. This is ready for a second review.

2023-09-09 23:14 UTC, LewisMK commented
I am truly sorry  @caupolicandiaz for not competing the PHP roundmode. I was held up trying to do some projects for a SOC-Analyst entry role. I am sorry for my tardiness.  I will avail myself better in soon time to come.

2023-09-09 23:17 UTC, LewisMK commented
If you want me to complete it, I can manage and I will dedicate one day to finish immediately. Your suggestions helped me to learn about multiple PHP round modes that I never knew.

2023-09-10 00:07 UTC, LewisMK commented
I am qualified and ready to take on SOC  analyst work...I know how to analyze malicious docs and traffic...If you have space for me to learn more for volunteer, I am willing. Thanks.

2023-09-10 15:21 UTC, SSwiniarski approved these changes
@LewisMK Looks good.

2023-09-10 15:23 UTC, merged