[Term Entry] Go Strings `ToLower()`
Codecademy/docs pull request #3127
Opened 2023-08-30 08:00 UTC by manviii27

### Description

 Added term entry for Go String function `ToLower()` . File Location: `docs/content/go/concepts/string-functions/terms/tolower/tolower.md`

### Type of Change

- Adding a new entry

### Checklist

- [✓ ] All writings are my own.
- [✓ ] My entry follows the Codecademy Docs style guide.
- [ ✓] My changes generate no new warnings.
- [ ✓] I have performed a self-review of my own writing and code.
- [ ✓] I have checked my entry and corrected any misspellings.
- [ ✓] I have made corresponding changes to the documentation if needed.
- [ ✓] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ✓] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ✓] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-30 11:37 UTC, SSwiniarski approved these changes
@manviii27 I made one small edit and this is good for a second review.

2023-08-30 17:08 UTC, caupolicandiaz requested changes
@manviii27 Just added one comment. Please update, and tag me when you've made the changes. Thanks

2023-09-04 08:50 UTC, manviii27 commented on content/go/concepts/strings/terms/tolower/tolower.md
> +```go
@caupolicandiaz I've made the changes, please review. Thank you

2023-09-05 18:06 UTC, caupolicandiaz approved these changes
@manviii27 @SSwiniarski LGTM

2023-09-05 18:09 UTC, merged