[Term Entry] Lua Tables `freeze()`
Codecademy/docs pull request #3129
Opened 2023-08-30 19:08 UTC by ShatilKhan

### Description

Added term entry for Lua Table function `freeze()` . 
File Location: `content\lua\concepts\tables\terms\freeze\freeze.md`. Closes #3119 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-30 19:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3129) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3129) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3129) it.</sub>

2023-08-30 20:07 UTC, caupolicandiaz requested changes
@ShatilKhan I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-08-30 20:07 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/freeze/freeze.md
> +Now if you run:
```suggestion

The variable `frozen_table`  is instantiated with the `freeze()` method to make the contents read-only.

Now, if an element is added:
```

2023-08-30 20:07 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/freeze/freeze.md
> +The error is caused because because the `freeze()` method has made the table `read-only` and we cannot modify its contents.
```suggestion
The error is thrown because the `freeze()` method has made the table read-only, so the contents cannot be modified.
```

2023-08-30 20:07 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/freeze/freeze.md
> +frozen_table[1] = "🍔" -- This will throw an error
Instead of commenting the output there should be a ```shell block with the error

2023-08-31 00:11 UTC, ShatilKhan commented
Thanks for reviewing, I'll let you know after I've made the uodates.

2023-09-01 05:40 UTC, ShatilKhan commented
I've updated all the requested changes. Please let me know if everything is ok.

2023-09-01 20:18 UTC, caupolicandiaz approved these changes
@ShatilKhan @lucwhite I've gone ahead and incorporated the changes I suggested.

2023-09-01 20:27 UTC, merged