Acos.md for Golang
Codecademy/docs pull request #3130
Opened 2023-08-31 13:15 UTC by arisdelacruz

### Description

This is an attempt to create acos() reference for Golang

### Type of Change

- Adding a new entry

### Checklist

- [ / ] All writings are my own.
- [ / ] My entry follows the Codecademy Docs style guide.
- [ / ] My changes generate no new warnings.
- [ / ] I have performed a self-review of my own writing and code.
- [ / ] I have checked my entry and corrected any misspellings.
- [ / ] I have made corresponding changes to the documentation if needed.
- [ / ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ / ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ / ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-08-31 15:58 UTC, SSwiniarski requested changes
@arisdelacruz I did a first review and left a couple of comments.

2023-08-31 15:58 UTC, SSwiniarski commented on content/discrete-math/concepts/enumeration/enumeration.md
It looks like yo made a branch off of a prior branch rather than off of main. This extra file needs to be removed from this PR.

2023-08-31 15:58 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/acos/acos.md
> +## Notes on the Parameter(s)
```suggestion
Notes on the Parameter:
```

2023-08-31 15:58 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/acos/acos.md
> +- If the parameter is either less than 0 or greater than 0, it returns `NaN` - as in this equation: `Acos(x) = NaN if x < -1 or x > 1`
```suggestion
- `x` is the value whose arccosine value is to be found.
- The range must be between `-1` and `1`.
- If the parameter is either less than -1 or greater than 1, it returns `NaN`.
```

2023-08-31 15:58 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/acos/acos.md
> +func Acos (x float64) float64
```suggestion
result := math.Acos(x) 
```
We generally show the syntax of the function in use rather than showing the function signature.

2023-09-01 01:36 UTC, arisdelacruz commented on content/discrete-math/concepts/enumeration/enumeration.md
yeah

just did a wrong commit and push with a late realization

note with thanks

2023-09-01 11:07 UTC, SSwiniarski approved these changes
@arisdelacruz Looks good for a second review.

2023-09-01 21:44 UTC, caupolicandiaz approved these changes
@arisdelacruz @SSwiniarski Just made a couple of minor edits. This is good to merge

2023-09-01 22:03 UTC, merged