[Term Entry] Java calendar getTime()
Codecademy/docs pull request #3134
Opened 2023-09-02 13:23 UTC by ChiragAgg5k

### Description

Added entry for getTime() method of Java Calendar class. Closes #3096 .

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-02 15:34 UTC, SSwiniarski requested changes
@ChiragAgg5k I did a review and only had one comment.

2023-09-02 15:34 UTC, SSwiniarski commented on content/java/concepts/calendar/terms/getTime/getTime.md
> +The **`.getTime()`** method of the `Calendar` class returns a `Date` object that represents time value of the `Calendar` class's object.
```suggestion
The **`.getTime()`** method of the `Calendar` class returns a [`Date`](https://www.codecademy.com/resources/docs/java/date) object that represents time value of the `Calendar` class's object.
```

2023-09-03 11:51 UTC, SSwiniarski approved these changes
@ChiragAgg5k Looks good for a second review.

2023-09-05 20:54 UTC, caupolicandiaz approved these changes
@ChiragAgg5k @SSwiniarski Just made a few small edits directly. Looks good to merge

2023-09-06 11:16 UTC, merged