Created toupper.md
Codecademy/docs pull request #3137
Opened 2023-09-02 22:02 UTC by jayghp

content\go\concepts\strings\terms\toupper\toupper.md

### Description

Created the file and path:

toupper.md
content\go\concepts\strings\terms\toupper\toupper.md

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-02 22:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3137) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3137) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3137) it.</sub>

2023-09-03 12:42 UTC, SSwiniarski requested changes
@jayghp I did a first review and left a few comments.

2023-09-03 12:42 UTC, SSwiniarski commented on content/go/concepts/strings/terms/toupper/toupper.md
> +func ToUpper(str string) string
```suggestion
result = strings.ToUpper(str) 
```
We generall want the syntax to show the function in use, not just a signature.

2023-09-03 12:42 UTC, SSwiniarski commented on content/go/concepts/strings/terms/toupper/toupper.md
> +```
```suggestion
```
We don't need to show output for a codebyte.

2023-09-03 12:42 UTC, SSwiniarski commented on content/go/concepts/strings/terms/toupper/toupper.md
> +This can also be acomplshied using the ToTitle() function.
This second example is pretty much the same as the codebyte. We can get rid of it and just leave the codebyte.

2023-09-14 16:07 UTC, jayghp commented
All changes have been addressed

2023-09-14 16:28 UTC, SSwiniarski requested changes
@jayghp Some more comments.

2023-09-14 16:28 UTC, SSwiniarski commented on content/go/concepts/strings/terms/toupper/toupper.md
> +The function accepts the given string as argument and returns the final string converting it to uppercase.
```suggestion
The function accepts the given string, `str`, as its argument and returns the final string, `result`, converting lowercase characters to uppercase.
```

2023-09-14 16:28 UTC, SSwiniarski commented on content/go/concepts/strings/terms/toupper/toupper.md
> +> **Note:** This only works with thte standardized alphabet characters.
```suggestion
> **Note:** This only works with the standardized alphabet characters.
```

2023-09-14 16:28 UTC, SSwiniarski commented on content/go/concepts/strings/terms/toupper/toupper.md
> +The **`toupper()`** function is used to convert lowercase alphabet to uppercase in a given string.
```suggestion
The **`ToUpper()`** function is used to convert lowercase alphabet to uppercase in a given string.
```

2023-09-14 16:28 UTC, SSwiniarski commented on content/go/concepts/strings/terms/toupper/toupper.md
> +Title: 'toupper()'
```suggestion
Title: 'ToUpper()'
```

2023-09-14 16:41 UTC, jayghp commented
New changes commited

2023-09-15 10:51 UTC, SSwiniarski approved these changes
@jayghp Looks good for a second review.

2023-09-16 20:28 UTC, caupolicandiaz requested changes
@jayghp I've added my initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-16 20:28 UTC, caupolicandiaz commented on content/go/concepts/strings/terms/toupper/toupper.md
> +Description: 'Returns a lowercase string converted to uppercase.'
```suggestion
Description: 'Returns a string in all uppercase.'
```

2023-09-16 20:28 UTC, caupolicandiaz commented on content/go/concepts/strings/terms/toupper/toupper.md
> +The **`ToUpper()`** function is used to convert lowercase alphabet to uppercase in a given string.
```suggestion
The **`ToUpper()`** function is used to convert lowercase characters to uppercase in a given string.
```

2023-09-16 20:28 UTC, caupolicandiaz commented on content/go/concepts/strings/terms/toupper/toupper.md
> +> **Note:** This only works with the standardized alphabet characters.
```suggestion
> **Note:** This function only works with the standard characters of the alphabet.
```

2023-09-16 20:28 UTC, caupolicandiaz commented on content/go/concepts/strings/terms/toupper/toupper.md
> +In the example below, the whole string "Codecademy" is converted to uppercase.
```suggestion
In the example below, `"Codecademy"` is converted to all uppercase.
```

2023-09-16 20:28 UTC, caupolicandiaz commented on content/go/concepts/strings/terms/toupper/toupper.md
> +
```suggestion
```

2023-09-16 20:28 UTC, caupolicandiaz commented on content/go/concepts/strings/terms/toupper/toupper.md
> +   "unicode"
```suggestion
   "strings"
```

2023-09-16 20:28 UTC, caupolicandiaz commented on content/go/concepts/strings/terms/toupper/toupper.md
> +   var output string = ToUpper(input)
```suggestion
   var output string = strings.ToUpper(input)
```

2023-09-24 10:52 UTC, jayghp commented
> @caupolicandiaz Sorry for the delay. I have committed the changes.

2023-09-25 17:43 UTC, caupolicandiaz approved these changes
@jayghp @SSwiniarski Looks good to merge

2023-09-27 16:36 UTC, merged