Create create.md
Codecademy/docs pull request #3142
Opened 2023-09-04 09:34 UTC by Brag2gr8

### Description

Added term entry for Lua Table function create() .
File Location: content\lua\concepts\tables\terms\create\create.md. Closes https://github.com/Codecademy/docs/issues/3116

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-04 09:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3142) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3142) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3142) it.</sub>

2023-09-04 13:47 UTC, SSwiniarski commented
@Brag2gr8 just a reminder to please sign the [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3142).

2023-09-04 13:55 UTC, SSwiniarski requested changes
@Brag2gr8 I did a first review and left a few comments.

2023-09-04 13:55 UTC, SSwiniarski commented on content/lua/concepts/tables/terms/create/create.md
> +The `create` function is used to generate a new table with a specified value repeated a certain number of times. This function is helpful when you need to initialize a table with a repetitive pattern
Instead of repeating the intro sentence, please describe the syntax example, explaining what `value` and `amount` are.

2023-09-04 13:55 UTC, SSwiniarski commented on content/lua/concepts/tables/terms/create/create.md
> +```lua
Can we have the example print out the values in the table so the following ` ```shell` block can actually be output from the example.

2023-09-04 13:55 UTC, SSwiniarski commented on content/lua/concepts/tables/terms/create/create.md
> +```shell
We prefer this to be output from the example code. Can you revise the example so an output block would make sense?

2023-09-04 13:55 UTC, SSwiniarski commented on content/lua/concepts/tables/terms/create/create.md
> +The **.create()** function in Lua Tables generates a new table with a specified value repeated a given number of times.
```suggestion
The **`.create()`** function generates a new table with a specified value repeated a given number of times.
```

2023-09-04 16:14 UTC, Brag2gr8 commented
@SSwiniarski  I implemented the suggested changes. please do another review

2023-09-04 16:17 UTC, SSwiniarski requested changes
@Brag2gr8  Two more comments.

2023-09-04 16:17 UTC, SSwiniarski commented on content/lua/concepts/tables/terms/create/create.md
> +**amount** : This parameter specifies how many times you want to repeat the **value** in the table.
```suggestion
- `value` : This parameter represents the value to populate the table with.
- `amount` : This parameter specifies how many times to repeat the `value` in the table.
```
We avoid first- and second-person pronouns in Docs.

2023-09-04 16:17 UTC, SSwiniarski commented on content/lua/concepts/tables/terms/create/create.md
> +After executing this code, the newTable will contain the following elements:
```suggestion

After executing this code, it will produce the following output:
```

2023-09-04 16:21 UTC, Brag2gr8 commented
understood! 
done committing

2023-09-05 00:21 UTC, Brag2gr8 commented
Alright that's great to hear..

2023-09-10 03:23 UTC, KTom101 requested changes
@Brag2gr8 I've added several changes. For future entries, please make sure you have run your code to ensure it works as expected. Let me know when you're done making the changes or if you have any questions.

2023-09-10 03:23 UTC, KTom101 commented on content/lua/concepts/tables/terms/create/create.md
> +
Let's add a note here explaining what happens when `value` is nill or is not given

```suggestion

> **Note:** When `value` is omitted or `nil`, the table will be returned empty but will have preallocated space for the `amount` specified. Preallocation is done on the array portion of the table, making `table.create` counter-productive on dictionaries.

```

2023-09-10 03:23 UTC, KTom101 commented on content/lua/concepts/tables/terms/create/create.md
> +description: 'Returns a new table with the provided value repeated the provided amount of times.'
```suggestion
Description: 'Returns a new table with a specified value repeated a given number of times.'
```

2023-09-10 03:23 UTC, KTom101 commented on content/lua/concepts/tables/terms/create/create.md
> +title: 'create()'
```suggestion
Title: '.create()'
```

2023-09-10 03:23 UTC, KTom101 commented on content/lua/concepts/tables/terms/create/create.md
> + - 'paths/computer-science'
```suggestion
  - 'paths/computer-science'
```

2023-09-10 03:25 UTC, KTom101 commented on content/lua/concepts/tables/terms/create/create.md
> +```lua
```suggestion
```pseudo
```

2023-09-10 22:43 UTC, Brag2gr8 commented on content/lua/concepts/tables/terms/create/create.md
> +table.create(value, amount)
🫠🫠

2023-09-10 22:56 UTC, Brag2gr8 commented
@KTom101  I'm done with the changes. I also changed "amount" to "size" to avoid the confusion

2023-09-14 22:27 UTC, KTom101 approved these changes
@Brag2gr8 This looks good. I made a minor change and ran `npm format:all` to fix the failed [check](https://www.codecademy.com/resources/docs/contribution-guide/getting-set-up-on-your-computer#:~:text=There%20are%20continuous%20integration%20(CI)%20workflows).

This looks good to go. Since this term was made for Luau (instead of Lua), we've decided this is best to be put under the Luau Table concept which is currently being created. There is nothing more you have to do, once the Table entry is up we will merge this in. Thank you for your patience 😄

cc @SSwiniarski

2023-09-15 00:14 UTC, Brag2gr8 commented
@KTom101 😂

2023-10-06 22:36 UTC, KTom101 commented
I moved the file to go under [Luau Tables](https://www.codecademy.com/resources/docs/luau/tables) and will now merge this.

2023-10-06 22:37 UTC, merged