[Term Entry] Lua Strings upper()
Codecademy/docs pull request #3144
Opened 2023-09-04 16:03 UTC by rhysfirkins

### Description

 - Added the string.upper() term for Lua
 - Issue #3106 

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-04 16:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3144) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3144) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3144) it.</sub>

2023-09-04 16:23 UTC, SSwiniarski requested changes
@rhysfirkins I did a first review and left a few comments.

2023-09-04 16:23 UTC, SSwiniarski commented on content/lua/concepts/strings/terms/upper/upper.md
> +  - 'learn-lua'
```suggestion
  - 'learn-lua'
  - 'paths/computer-science'
```

2023-09-04 16:23 UTC, SSwiniarski commented on content/lua/concepts/strings/terms/upper/upper.md
> +This code would display the following output:
```suggestion

This code would display the following output:
```

2023-09-04 17:30 UTC, SSwiniarski requested changes
@rhysfirkins One more comment.

2023-09-04 17:30 UTC, SSwiniarski commented on content/lua/concepts/strings/terms/upper/upper.md
> +```lua
````suggestion
```shell
````

2023-09-04 20:11 UTC, SSwiniarski approved these changes
@rhysfirkins Looks good for a second review.

2023-09-05 21:05 UTC, caupolicandiaz approved these changes
@rhysfirkins @SSwiniarski Made some of the missing changes and a couple of additional edits. Looks good to merge

2023-09-06 11:18 UTC, merged