docs browser: Add entry for string.byte function
Codecademy/docs pull request #3147
Opened 2023-09-04 19:18 UTC by gibran-padilla

### Description

New term entry for the string.byte() function of lua programming language.
Includes a breve description, syntax explanation and examples.

### Type of Change

New entry to docs browser

### Checklist

- [✓ ] All writings are my own.
- [ ✓] My entry follows the Codecademy Docs style guide.
- [✓ ] My changes generate no new warnings.
- [✓ ] I have performed a self-review of my own writing and code.
- [✓ ] I have checked my entry and corrected any misspellings.
- [✓ ] I have made corresponding changes to the documentation if needed.
- [✓ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ✓] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [✓ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-04 19:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3147) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3147) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3147) it.</sub>

2023-09-06 17:46 UTC, caupolicandiaz requested changes
@gibran-padilla I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-06 17:46 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/byte/byte.md
> +
```suggestion
 - 'Game Development'
```

2023-09-06 17:46 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/byte/byte.md
> +  - 'learn-example-course'
```suggestion
  - 'learn-lua'
```

2023-09-06 17:46 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/byte/byte.md
> +  - 'paths/example-path'
```suggestion
  - 'paths/computer-science'
```

2023-09-06 17:46 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/byte/byte.md
> +**String.byte()** function takes a character or a string as an argument and returns an ASCII (decimal) equivalent internal numeric representation.
```suggestion
The **`string.byte()`** function takes a character or a string as an argument and returns an ASCII (decimal) equivalent internal numeric representation.
```

2023-09-06 17:46 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/byte/byte.md
> +The Function string.byte(s, n) can take two arguments, where s parameter is a character or string and n is the index of the string passed as an argument. Passing only one argument will set n to defau
```suggestion
```pseudo
string.byte(s, n)
```

The function can take two arguments, where the `s` parameter is a character or string and `n` is the index of the string passed as an argument. Passing only one argument will set `n` to `1`.
```

2023-09-06 17:46 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/byte/byte.md
> +## Arguments
```suggestion
## Example 1
```

2023-09-06 17:46 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/byte/byte.md
> +The function first argument can take a string or digit  but a symbol will throw an error.
```suggestion
The example below demonstrates the use of the `.byte()` method.
```

2023-09-06 17:46 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/byte/byte.md
> +print(string.byte('a')) -- Prints: 97
typically the output is shown in a separate ```shell block

2023-09-06 17:46 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/byte/byte.md
> +Adding a second argument separated by acomma.
```suggestion
## Example 2

The following code demonstrates the use of this function with a second argument.
```

2023-09-06 20:58 UTC, gibran-padilla commented
@caupolicandiaz Thank you very much for the review. 

I made the changes suggested, so I would be happy if you can check the new entry.

Regards.

2023-09-07 18:02 UTC, caupolicandiaz approved these changes
@gibran-padilla Some of the edits were not implemented correctly, so I went ahead and made them directly. Please review the changes for future reference. This is ready for a second review.

2023-09-07 18:42 UTC, gibran-padilla commented
@caupolicandiaz I appreciate your comments, 
I will try to improve the mistake made this time.

Regrads.

2023-09-10 15:12 UTC, SSwiniarski approved these changes
@gibran-padilla I made one small edit and it looks ready to merge.

2023-09-10 15:14 UTC, merged