Adding a new PHP array
Codecademy/docs pull request #3149
Opened 2023-09-04 22:20 UTC by JayRKyd

### Description

The array_values() function takes in an array and returns a new array in numerical order. It effectively removes keys from the array and re-indexes it, starting from zero. The reason for creating this doc is to help beginners understand PHP functions properly.

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-05 16:52 UTC, SSwiniarski requested changes
@JayRKyd I did a first review and left a few comments.

2023-09-05 16:52 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-values/array-values.md
> +The **`array_values()`** function allows you to return all the values from an array in numerical order.
```suggestion
The **`array_values()`** function returns all the values from an array in numerical order.
```

2023-09-05 16:52 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-values/array-values.md
> +```
````suggestion
## Example

The example shown below creates an array called `$vehicle` with three key-value pairs. It then uses the `array_values()` function to extract and print the array's values resulting in an indexed array.

```php
````

2023-09-05 16:52 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-values/array-values.md
> +```
````suggestion
```pseudo
````

2023-09-05 16:52 UTC, SSwiniarski commented on content/php/concepts/arrays/terms/array-values/array-values.md
> +```shell
````suggestion
```

This example shows the values "BMW", "gold" and "X5" printed to the console:

```shell
````

2023-10-02 20:06 UTC, caupolicandiaz commented
@JayRKyd It has been several weeks with no activity on this entry. Are you still available to edit this?

2023-10-05 22:17 UTC, caupolicandiaz reviewed
@JayRKyd @SSwiniarski For the sake of moving this along I've gone ahead and incorporated all of the edits.

2023-10-06 11:38 UTC, SSwiniarski approved these changes
@JayRKyd, @caupolicandiaz Looks good.

2023-10-06 17:56 UTC, caupolicandiaz approved these changes
@JayRKyd @SSwiniarski This is good to merge

2023-10-07 14:40 UTC, merged