Lua strings reverse
Codecademy/docs pull request #3156
Opened 2023-09-05 20:43 UTC by Brag2gr8

### Description

Added term entry for Lua Strings function reverse() .
File Location: content\lua\concepts\strings\terms\reverse\reverse.md. Closes #3112 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-05 21:13 UTC, caupolicandiaz requested changes
@Brag2gr8 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-05 21:13 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/reverse/reverse.md
> +Description: ' rearranges a provided string in reverse order'
```suggestion
Description: 'Returns a provided string in reverse order.'
```

2023-09-05 21:13 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/reverse/reverse.md
> +The **`originalString`** is the string to be reversed.
```suggestion
The `originalString` is the string to be reversed.
```

2023-09-05 21:13 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/reverse/reverse.md
> +The **`originalString`** is the string to be reversed.
bold is only applied to the first instance of the method or concept in the entry

2023-09-05 21:13 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/reverse/reverse.md
> +
remove empty line

2023-09-05 21:13 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/reverse/reverse.md
> +Consider the following example:
```suggestion
The code below demonstrates a basic implementation of the `.reverse()` method:
```

2023-09-05 21:13 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/reverse/reverse.md
> +Expected output:
```suggestion
This will return the following output:
```

2023-09-05 21:13 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/reverse/reverse.md
> +"!dlroW ,olleH"
```suggestion
!dlroW ,olleH
```

2023-09-05 21:21 UTC, Brag2gr8 reviewed
update code with all reviews

2023-09-06 08:00 UTC, Brag2gr8 commented
@caupolicandiaz completed

2023-09-06 17:11 UTC, caupolicandiaz approved these changes
@Brag2gr8 Looks good. This is ready for a second review.

2023-09-08 16:46 UTC, SSwiniarski approved these changes
@Brag2gr8 Looks good!

2023-09-08 16:54 UTC, merged