added Java Calendar isLenient() method
Codecademy/docs pull request #3182
Opened 2023-09-07 05:09 UTC by ATREAY

### Description

added Java Calendar isLenient() method

### Type of Change

- Adding a new entry

### Checklist

- [v] All writings are my own.
- [v] My entry follows the Codecademy Docs style guide.
- [v] My changes generate no new warnings.
- [v] I have performed a self-review of my own writing and code.
- [v] I have checked my entry and corrected any misspellings.
- [v  I have made corresponding changes to the documentation if needed.
- [v] I have confirmed my changes are not being pushed from my forked `main` branch.
- [v] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [v] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-07 05:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3182) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3182) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3182) it.</sub>

2023-09-07 21:03 UTC, caupolicandiaz requested changes
@ATREAY I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-07 21:03 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/isLenient/isLenient.md
> +
remove empty line 30

2023-09-07 21:03 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/isLenient/isLenient.md
> +public class CalendarIsLenientExample {
the code should use 2 spaces for indentations not tabs

2023-09-07 21:03 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/isLenient/isLenient.md
> +```
add and empty line between the shell block and the example 2 header

2023-09-07 21:03 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/isLenient/isLenient.md
> +public class CalendarIsLenientExample{
update the indentations

2023-09-08 03:18 UTC, ATREAY commented
Hey @caupolicandiaz,
I have implemented the necessary modifications. Please go through it.

2023-09-08 17:32 UTC, caupolicandiaz approved these changes
@ATREAY Looks good. This is ready for a second review

2023-09-10 15:06 UTC, SSwiniarski approved these changes
@ATREAY I made a few edits, fixing the modification of the `yarn.lock` and `package.json` files. Now it looks good to merge.

2023-09-10 15:08 UTC, SSwiniarski commented
@ATREAY also, for future reference, it is not recommended that you submit PRs from your main branch. It is better to create a separate branch off of main for each PR.

2023-09-10 15:08 UTC, merged

2023-09-11 04:28 UTC, ATREAY commented
I appreciate your guidance, @SSwiniarski. 
I will diligently incorporate all the recommendations you have provided into my future Pull Requests (PRs).