Lua strings format()
Codecademy/docs pull request #3183
Opened 2023-09-07 10:54 UTC by Brag2gr8

### Description

Added term entry for Lua String function format() .
File Location: content\lua\concepts\strings\terms\format\format.md. Closes #3109

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-07 21:16 UTC, caupolicandiaz requested changes
@Brag2gr8 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-07 21:16 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/format/format.md
> +The **`.format()`** is used to create formatted strings by replacing placeholders in a format string with specified values.
```suggestion
The **`.format()`** method is used to create formatted strings by replacing placeholders with specified values.
```

2023-09-07 21:16 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/format/format.md
> +`%.nf`: Specify the number of decimal places (e.g., %.2f for two decimal places).
```suggestion
`%.nf`: Designates the number of decimal places (e.g. `%.2f` for two decimal places).
```

2023-09-07 21:16 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/format/format.md
> +Here are some examples of how to use `string.format()` :
```suggestion
The following example demonstrates an implementation of `string.format()` :
```

2023-09-07 21:16 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/format/format.md
> +Here are some examples of how to use `string.format()` :
move this line after the example 1 header

2023-09-07 21:16 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/format/format.md
> +In this example, the string.format() function is used to create a formatted string by replacing `%s`, `%.1f` and `%d` placeholders with the values of name, age and height, respectively. The resulting
```suggestion
```

2023-09-07 21:16 UTC, caupolicandiaz commented on content/lua/concepts/strings/terms/format/format.md
> +## Example 2
```suggestion
## Example 2

The following example demonstrates the use of `string.format()` with a hexadecimal value.

```

2023-09-07 22:32 UTC, Brag2gr8 commented
@caupolicandiaz done with the changes

2023-09-08 17:07 UTC, caupolicandiaz approved these changes
@Brag2gr8 This is ready for a second review.

2023-09-09 15:33 UTC, SSwiniarski approved these changes
@Brag2gr8 Looks good.

2023-09-09 15:35 UTC, merged