Array shift
Codecademy/docs pull request #3184
Opened 2023-09-07 13:53 UTC by eusackis

### Description

Wrote a beginner's entry for the array_shift() function in php as a part of my 'Learn Git & Github' course.

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-07 13:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3184) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3184) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3184) it.</sub>

2023-09-07 21:38 UTC, caupolicandiaz requested changes
@eusackis I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-07 21:38 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array_shift/array-shift.md
> +Description: 'Shifts/pops an element off the beginning of an array.'
```suggestion
Description: 'Pops an element off the beginning of an array.'
```

2023-09-07 21:38 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array_shift/array-shift.md
> +The **`array_shift()`** shifts/pops the first value of the array off and returns it, shortening the array by one element and shifting each element down. Numerical keys will be reset to start counting
```suggestion
The **`array_shift()`** pops the first value of the array off and returns it, shortening the array by one element and shifting each element down. Numerical keys will be reset to start counting from `0`, whereas the remaining literal keys will not be affected.
```

2023-09-07 21:38 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array_shift/array-shift.md
> +array_shift(array &$array)
```suggestion
array_shift($array)
```

2023-09-07 21:38 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array_shift/array-shift.md
> +In the code snippet below `array_shift()` is used twice. First time it takes the one element with a numerical key, second time with a literal key. After that the `$num_array` is printed out. Notice t
```suggestion
In the code snippet below `array_shift()` is used twice. The first time it pops the one element with a numerical key, the second time an element with a literal key. After that the `$num_array` is printed out. Notice that the string `"600"` is still a numerical key, so it is reset to `0`.
```

2023-09-07 21:38 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array_shift/array-shift.md
> +    print_r($counting_rhyme) //Prints: the modified array
```suggestion
    echo $removed . "\n";
    print_r($counting_rhyme)
```

2023-09-07 21:38 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array_shift/array-shift.md
> +    print_r($counting_rhyme) //Prints: the modified array
the comments are unnecessary because the output is included below. Also update the indentations to use 2 spaces not tabs

2023-09-07 21:38 UTC, caupolicandiaz commented on content/php/concepts/arrays/terms/array_shift/array-shift.md
> +    [0] => Meeny
update to use 2 spaces

2023-09-08 21:49 UTC, caupolicandiaz approved these changes
@eusackis This is ready for a second review

2023-09-09 15:29 UTC, SSwiniarski approved these changes
@eusackis Looks good.

2023-09-09 15:31 UTC, merged