[Term Entry] Java Calendar internalGet() (#3102)
Codecademy/docs pull request #3192
Opened 2023-09-08 14:26 UTC by LeoMiguelB

### Description

This PR includes an entry to the Calendar class for the internalGet method. It includes an example and a description. The path for this new entry is `content/java/concepts/calendar/terms/internalGet/internalGet.md.`

Closes #3102 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [✔️] All writings are my own.
- [ ✔️] My entry follows the Codecademy Docs style guide.
- [✔️ ] My changes generate no new warnings.
- [✔️ ] I have performed a self-review of my own writing and code.
- [✔️ ] I have checked my entry and corrected any misspellings.
- [ ✔️] I have made corresponding changes to the documentation if needed.
- [✔️ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [✔️ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [✔️ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-08 14:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3192) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3192) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3192) it.</sub>

2023-09-08 22:38 UTC, caupolicandiaz requested changes
@LeoMiguelB I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-08 22:38 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/internalGet/internalGet.md
> +Description: 'Returns the value of a given field'
```suggestion
Description: 'Returns the value of a given field.'
```

2023-09-08 22:38 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/internalGet/internalGet.md
> +The **`.internalGet()`** method is a protected method used to retrieve the value of a field from a Calendar instance. In other words it takes a field as input and returns its corresponding value. Thi
```suggestion
The **`.internalGet()`** method is a protected method used to retrieve the value of a field from a `Calendar` instance. In other words, it takes a field as input and returns its corresponding value. This method is generally used within the `Calendar` class or its sub classes.
```

2023-09-08 22:38 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/internalGet/internalGet.md
> +protected final int internalGet(int field)
```suggestion
myCalendar.internalGet(int field)
```

2023-09-08 22:38 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/internalGet/internalGet.md
> +
There should be a note here after the syntax regarding the parameters taken, return value, or any other valuable information

2023-09-08 22:38 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/internalGet/internalGet.md
> +In this example, the `InternalGetExample` class inherits the `GregorianCalendar` class which is a concrete subclass of the Calendar class. The code first instantiates a new object of type `InternalGe
```suggestion
In this example, the `InternalGetExample` class inherits the `GregorianCalendar` class. The code first instantiates a new object of type `InternalGetExample` with the current date which uses the Gregorian calendar system.
```

2023-09-08 22:38 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/internalGet/internalGet.md
> +## Example 1
```suggestion
## Example 
```

2023-09-08 22:38 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/internalGet/internalGet.md
> +import java.util.GregorianCalendar;
update the code to use 2 spaces for indentation instead of tabs

2023-09-08 23:38 UTC, LeoMiguelB commented
@caupolicandiaz, I followed your suggestions and corrected my entry.

2023-09-09 20:35 UTC, caupolicandiaz approved these changes
@LeoMiguelB I made a couple of additional edits directly. This is ready for a second review

2023-09-10 14:55 UTC, SSwiniarski approved these changes
@LeoMiguelB Looks good.

2023-09-10 14:57 UTC, merged