[Term Entry] setMinimalDaysInFirstWeek()
Codecademy/docs pull request #3193
Opened 2023-09-08 17:45 UTC by roberanegussie

### Description

I have added a new term entry for the calendar class by creating a new file setMinimalDaysInFirstWeek used to set the minimal required days in first week of the year. This is my first time contributing to this repo so took time to make sure I did it well. 
### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-08 17:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3193) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3193) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3193) it.</sub>

2023-09-08 22:02 UTC, caupolicandiaz requested changes
@roberanegussie I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-08 22:02 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/setMinimalDaysInFirstWeek/setMinimalDaysInFirstWeek.md
> +In the following example, `.setMinimalDaysInFirstWeek()` is used to set the minimal days in required in first week of the year. This example will set the minimal days required in the first week of th
```suggestion
In the following example, `.setMinimalDaysInFirstWeek()` is used to set the minimal days required in the first week of the year. 
```

2023-09-08 22:02 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/setMinimalDaysInFirstWeek/setMinimalDaysInFirstWeek.md
> +The output of the above code will be set the minimal days required in first week of the year as 2 days:
```suggestion
The output of the above code will be:
```

2023-09-09 08:03 UTC, roberanegussie commented
@caupolicandiaz  I have updated the PR based on the required suggestions please review.

2023-09-09 20:43 UTC, caupolicandiaz approved these changes
@roberanegussie Looks good, this is ready for a second review.

2023-09-10 14:51 UTC, SSwiniarski approved these changes
@roberanegussie Looks good.

2023-09-10 14:53 UTC, merged