[Term Entry] Swift Protocols Decodable #2958
Codecademy/docs pull request #3198
Opened 2023-09-09 05:05 UTC by sdwinston

### Description

-Added Decodable Protocol term entry for Swift
-Closes Issue #2958

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-09 05:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3198) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3198) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3198) it.</sub>

2023-09-09 14:28 UTC, SSwiniarski requested changes
@sdwinston I did a first review and left a few comments. Also note you still need to sign the [CLA](https://cla-assistant.io/Codecademy/docs?pullRequest=3198).

2023-09-09 14:28 UTC, SSwiniarski commented on content/swift/concepts/protocols/terms/decodable/decodable.md
> +`Decodable` is a type in Swift that can convert itself into a structure that conforms to the **`Decodable protocol`**. The `Decodable protocol` is used to easily decode JSON or similar data formats l
```suggestion
`Decodable` is a type in Swift that can convert itself into a structure that conforms to the **`Decodable`** protocol. The `Decodable` protocol is used to easily decode JSON or similar data formats like XML. The required initializer is `init(from: Decoder)` which creates a new instance by decoding from the given decoder. The `Decodable` protocol is often used with the `JSONDecoder` class. `Decodable` should be used when there's only a need to read data. 
```

2023-09-09 14:28 UTC, SSwiniarski commented on content/swift/concepts/protocols/terms/decodable/decodable.md
> +Create a structure to represent the data to decode, followed by `Decodable` using the standard syntax of a Swift protocol.
```suggestion
## Syntax

Create a structure to represent the data to decode, followed by `Decodable` using the standard syntax of a Swift protocol.   
```

2023-09-09 14:28 UTC, SSwiniarski commented on content/swift/concepts/protocols/terms/decodable/decodable.md
> +In the example below, a structure called User is created and the `Decodable` protocol is used with `JSONDecoder` to convert JSON stored as a data object.
```suggestion

In the example below, a structure called User is created and the `Decodable` protocol is used with `JSONDecoder` to convert stored JSON into a data object.
```

2023-09-09 14:28 UTC, SSwiniarski commented on content/swift/concepts/protocols/terms/decodable/decodable.md
> +
````suggestion
```
````
Remove extra blank lines.

2023-09-25 13:46 UTC, SSwiniarski approved these changes
@sdwinston This looks good for a second review.

2023-09-25 22:20 UTC, caupolicandiaz requested changes
@sdwinston I've added a few additional comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-25 22:20 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/decodable/decodable.md
> +  - 'Computer Science'
```suggestion
```

2023-09-25 22:20 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/decodable/decodable.md
> +  - 'Computer Science'
we limit subjects to one or two items

2023-09-25 22:20 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/decodable/decodable.md
> +`Decodable` is a type in Swift that can convert itself into a structure that conforms to the **`Decodable`** protocol. The `Decodable` protocol is used to easily decode JSON or similar data formats l
```suggestion
The **`Decodable`** protocol is used to easily decode JSON or similar data formats like XML. The required initializer is `init(from: Decoder)` which creates a new instance by decoding from the given decoder. The `Decodable` protocol is often used with the `JSONDecoder` class. `Decodable` should be used when there's only a need to read data, when reading and writing are required the `Codable` protocol should be implemented.
```

2023-09-25 22:20 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/decodable/decodable.md
> +In the example below, a structure called User is created and the `Decodable` protocol is used with `JSONDecoder` to convert stored JSON into a data object.
```suggestion
In the example below, a `User` struct is defined and the `Decodable` protocol is used with `JSONDecoder` to convert stored JSON into a data object.
```

2023-09-25 22:20 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/decodable/decodable.md
> +print(user.name) // Prints "Charlotte Lucas"
```suggestion
import Foundation
struct User: Decodable {
   var name: String
   var age: Int
   var location: String
 }

 let userJson = """
 {
   "name": "Charlotte Lucas",
   "age": 27,
   "location": "England"
 }
 """
 
 let userData = Data(userJson.utf8)

 let decoder = JSONDecoder()
 let user = try decoder.decode(User.self, from: userData)
 print(user.name)
```

2023-09-25 22:20 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/decodable/decodable.md
> +print(user.name) // Prints "Charlotte Lucas"
we usually use a ```shell block for the output

2023-10-03 11:37 UTC, sdwinston commented
@caupolicandiaz I've updated the entry with the changes

2023-10-03 17:47 UTC, caupolicandiaz approved these changes
@sdwinston @SSwiniarski LGTM

2023-10-03 19:45 UTC, merged