Edit html favicon media
Codecademy/docs pull request #3199
Opened 2023-09-09 05:11 UTC by karellehofler

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-09 05:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3199) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3199) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3199) it.</sub>

2023-09-09 14:39 UTC, SSwiniarski requested changes
@karellehofler I did a first review and have a few suggestions about your image.

2023-09-09 14:39 UTC, SSwiniarski commented on media/favicon-codecademy.png
Three suggestions for this image:

1) Have the arrow and the circle lines be the same weight.
2) Have the word "favicon" be in a larger font.
3) Have the arrow pointing from the lower right (rather than the lower left) so it's emerging from the left side of the word "favicon"

![image](https://github.com/Codecademy/docs/assets/86081858/b4b1e432-6286-4c82-9ea4-2ad816cbdb78)

2023-09-13 11:00 UTC, SSwiniarski approved these changes
@karellehofler Looks good for a second review.

2023-09-14 19:09 UTC, caupolicandiaz approved these changes
@karellehofler @SSwiniarski LGTM

2023-09-15 11:01 UTC, merged