Go term cosh
Codecademy/docs pull request #3200
Opened 2023-09-09 09:54 UTC by abu-hasib

### Description
- This PR adds information about Go Math Cosh function. It closes #3082.
- Ran formating and ran all tests.

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-09 14:43 UTC, SSwiniarski requested changes
@abu-hasib I did a first review and left a few comments.

2023-09-09 14:43 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/cosh/cosh.md
> +Where `CoshX` is the hyperbolic cosine value of `x`, it is of type _float64_. It always return the hyperbolic consine value except some special cases:
```suggestion
Where `CoshX` is the hyperbolic cosine value of `x`, it is of type _float64_. It always returns the hyperbolic cosine value except for some special cases:
```

2023-09-09 14:43 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/cosh/cosh.md
> +The following Golang Program calculates the hyperbolic cosine of `x` and prints out the result:
```suggestion
The following Golang program calculates the hyperbolic cosine of `x` and prints out the result:
```

2023-09-09 14:43 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/cosh/cosh.md
> +The following example shows how the `Cosh()` function handles float64 arguments including _special cases_ arguments.
```suggestion
The following example shows how the `Cosh()` function handles float64 arguments including special cases.
```

2023-09-09 15:44 UTC, abu-hasib commented
@SSwiniarski I have gone through the review and resolved the comments.

2023-09-10 11:48 UTC, SSwiniarski approved these changes
@abu-hasib Looks good for a second review.

2023-09-11 20:25 UTC, caupolicandiaz requested changes
@abu-hasib I've added a few additional comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-11 20:25 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/cosh/cosh.md
> +Where `CoshX` is the hyperbolic cosine value of `x`, it is of type _float64_. It always returns the hyperbolic cosine value except for some special cases:
```suggestion
Where `CoshX` is the hyperbolic cosine value of `x`, it is of type `float64`. It always returns the hyperbolic cosine value except for some special cases:
```

2023-09-11 20:25 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/cosh/cosh.md
> +- CoshX of `Cosh(NaN)` is `NaN`
```suggestion
- `Cosh(±0)` is `1`
- `Cosh(±Inf)` is `+Inf`
- `Cosh(NaN)` is `NaN`
```

2023-09-11 20:25 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/cosh/cosh.md
> +```codebyte/golang
2 of 3 of these results are duplicates from the previous example. Codebytes should not duplicate previous work. Ideally it should demonstrate some new functionality, information, etc. I would suggest updating the values or deleting the example.

2023-09-14 13:25 UTC, abu-hasib commented
@caupolicandiaz resolved the comments

2023-09-14 16:36 UTC, caupolicandiaz approved these changes
@abu-hasib @SSwiniarski Looks good to merge

2023-09-16 12:07 UTC, merged