Get week year method
Codecademy/docs pull request #3202
Opened 2023-09-10 06:27 UTC by Ameya02

### Description
- Added the calender.getWeekYear() method for Java
- Closes issue #3100 

### Type of Change

- Adding a new entry
### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-10 06:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3202) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3202) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3202) it.</sub>

2023-09-10 13:39 UTC, SSwiniarski requested changes
@Ameya02 I did one edit to fix the changes to the `yarn.lock` file. Then on review I found a few things to address.

2023-09-10 13:39 UTC, SSwiniarski commented on content/java/concepts/calendar/terms/getWeekYear/getWeekYear.md
> +Description: 'Returns the week year'
```suggestion
Description: 'Returns the week year.'
```

2023-09-10 13:39 UTC, SSwiniarski commented on content/java/concepts/calendar/terms/getWeekYear/getWeekYear.md
> +The **`.getWeekYear()`** method of the `Calendar` class returns the time represented by a `Calendar` object in the form of week year.
```suggestion
The **`.getWeekYear()`** method of the `Calendar` class returns the time represented by a `Calendar` object in the form of the week year.
```

2023-09-10 13:39 UTC, SSwiniarski commented on content/java/concepts/calendar/terms/getWeekYear/getWeekYear.md
> +This example code shows the basic use of the getWeekYear() method
```suggestion
This example code shows the basic use of the `getWeekYear()` method:
```

2023-09-10 15:41 UTC, SSwiniarski approved these changes
@Ameya02 Looks good for a second review.

2023-09-11 18:02 UTC, caupolicandiaz approved these changes
@Ameya02 @SSwiniarski Just made a couple of minor edits, looks good to merge

2023-09-12 11:38 UTC, merged