Creation of atan.md for Golang
Codecademy/docs pull request #3212
Opened 2023-09-10 15:09 UTC by arisdelacruz

### Description

This is my attempt to create the resource for the Atan() function in Golang.

### Type of Change

- Adding a new entry

### Checklist

- [ / ] All writings are my own.
- [ / ] My entry follows the Codecademy Docs style guide.
- [ / ] My changes generate no new warnings.
- [ / ] I have performed a self-review of my own writing and code.
- [ / ] I have checked my entry and corrected any misspellings.
- [ / ] I have made corresponding changes to the documentation if needed.
- [ / ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ / ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ / ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-10 16:05 UTC, SSwiniarski requested changes
@arisdelacruz I did a first review and left a couple of comments.

2023-09-10 16:05 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/atan/atan.md
> +The **`Atan()`** function returns the arctangent of a value given in radians.
```suggestion
The **`Atan()`** function returns the arctangent, in radians, of a given value.
```

2023-09-10 16:05 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/atan/atan.md
> +- The range must be between between -π/2 to π/2 radians.
```suggestion
- The `result` will be between between -π/2 to π/2 radians.
```

2023-09-10 16:05 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/atan/atan.md
> +- If the parameter is either less than -π/2 or greater than π/2 it returns NaN.
```suggestion
- If the parameter is `NaN` it returns `NaN`.
```

2023-09-11 00:04 UTC, arisdelacruz commented
@SSwiniarski 

thanks

2023-09-11 11:48 UTC, SSwiniarski requested changes
@arisdelacruz Looks good for a second review.

2023-09-11 11:48 UTC, SSwiniarski approved these changes

2023-09-11 20:06 UTC, caupolicandiaz requested changes
@arisdelacruz Just a couple of small additional edits. Please update, and tag me when you've completed the changes. Thanks

2023-09-11 20:06 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/atan/atan.md
> +Notes on the parameter:
```suggestion
Notes on `.Atan()`:
```

2023-09-11 20:06 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/atan/atan.md
> +- If the parameter is `NaN` it returns `NaN`.
```suggestion
- If the argument is `NaN` it returns `NaN`.
```

2023-09-13 12:16 UTC, arisdelacruz commented
@caupolicandiaz 

done

thanks

2023-09-14 11:00 UTC, merged