Added Java Calendar getWeeksInWeekYear() function
Codecademy/docs pull request #3233
Opened 2023-09-11 16:21 UTC by ATREAY

### Description

This pull request pertains to issue #3099(Java Calendar getWeeksInWeekYear())

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-11 19:11 UTC, caupolicandiaz approved these changes
@ATREAY I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-11 19:11 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getWeeksInWeekYear/getWeeksInWeekYear.md
> +Description: 'Returns the total number of weeks in a week year in the integer form.'
```suggestion
Description: 'Returns the total number of weeks in a week year.'
```

2023-09-11 19:11 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getWeeksInWeekYear/getWeeksInWeekYear.md
> +The **`.getWeeksInWeekYear()`** method of the `Calendar` class returns the integer `number of weeks` in `week year`.
```suggestion
The **`.getWeeksInWeekYear()`** method of the `Calendar` class returns an integer representing the number of weeks in a *week year*.
```

2023-09-11 19:11 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getWeeksInWeekYear/getWeeksInWeekYear.md
> +> **Note:** The concept of a `week-based year` is important in some calendar systems, especially when dealing with fiscal years or other non-standard year definitions. The number of weeks in a week-b
```suggestion
> **Note:** The concept of a *week-based year* is important in some calendar systems, especially when dealing with fiscal years or other non-standard year definitions. The number of weeks in a week-based year can vary depending on factors such as the starting day of the week and whether the year contains partial weeks at the beginning or end.
```

2023-09-11 19:11 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getWeeksInWeekYear/getWeeksInWeekYear.md
> +    System.out.println("Weeks in week year :"  + cal.getWeeksInWeekYear());
```suggestion
    System.out.println("Weeks in week year: "  + cal.getWeeksInWeekYear());
```

2023-09-11 19:11 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getWeeksInWeekYear/getWeeksInWeekYear.md
> +    System.out.println("Changed Time:"+cal.getTime());
```suggestion
    System.out.println("Changed Time: "+cal.getTime());
```

2023-09-11 19:11 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getWeeksInWeekYear/getWeeksInWeekYear.md
> +    System.out.println("Weeks in week year :"  + cal.getWeeksInWeekYear());
```suggestion
    System.out.println("Weeks in week year: "  + cal.getWeeksInWeekYear());
```

2023-09-12 04:25 UTC, ATREAY commented
Hello @caupolicandiaz, 
I have implemented the necessary modifications. I kindly request that you review them.

2023-09-12 16:57 UTC, caupolicandiaz approved these changes
@ATREAY Looks good, this is ready for a second review.

2023-09-14 16:40 UTC, SSwiniarski requested changes
@ATREAY I did a second review and left a few comments.

2023-09-14 16:40 UTC, SSwiniarski commented on content/java/concepts/calendar/terms/getWeeksInWeekYear/getWeeksInWeekYear.md
> +> **Note:** The concept of a _week-based year_ is important in some calendar systems, especially when dealing with fiscal years or other non-standard year definitions. The number of weeks in a week-b
```suggestion
> **Note:** The concept of a **week-based year** is important in some calendar systems, especially when dealing with fiscal years or other non-standard year definitions. The number of weeks in a week-based year can vary depending on factors such as the starting day of the week and whether the year contains partial weeks at the beginning or end.
```

2023-09-15 09:54 UTC, ATREAY commented on content/java/concepts/calendar/terms/isLenient/isLenient.md
Hey @SSwiniarski, I've deleted the isLenient.md file. Could you take a look at it?

2023-09-16 12:12 UTC, SSwiniarski approved these changes
@ATREAY Looks good for a second review.

2023-09-16 12:14 UTC, merged