Issue3165  Term Entry: set lenient method
Codecademy/docs pull request #3234
Opened 2023-09-11 22:35 UTC by ChiduAnush

### Description

New Term Entry for ava Calendar setLenient(). Closes #3165 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-11 22:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3234) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3234) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3234) it.</sub>

2023-09-12 16:39 UTC, caupolicandiaz requested changes
@ChiduAnush I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-12 16:39 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/setLenient/setLenient.md
> +The `**.setLenient()**` method of the `calender` class is used to set the lineacy of the interpretation of date and time. i.e., it is used to specify whether the internpretation of date and time shou
```suggestion
The **`.setLenient()`** method of the `Calendar` class is used to set the leniency of the interpretation of date and time. In other words, it is used to specify whether the interpretation should be strict or not. 
```

2023-09-12 16:39 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/setLenient/setLenient.md
> +The method takes one boolean value as a parameter.
```suggestion
```

2023-09-12 16:39 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/setLenient/setLenient.md
> +calender.setLenient(boolean lenient)
```suggestion
calender.setLenient(bool_flag)
```

2023-09-12 16:39 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/setLenient/setLenient.md
> +Parameter: set `lenient` as false for more strict interpretation, that is, leniency is turned off. Set true for leniency to be turned on.
```suggestion

This method has only one parameter, `bool_flag`, which should be set as `false` for a strict interpretation, that is, leniency is turned off. And set to `true` for leniency to be turned on.
```

2023-09-12 16:39 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/setLenient/setLenient.md
> +> **Note:** You can use the `.isLenient()` method to check if given calender instance is lenient or not.
```suggestion
> **Note:** The `.isLenient()` method can be used to check if a given calendar is lenient or not.
```

2023-09-12 16:39 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/setLenient/setLenient.md
> +This example shows what happens when you dont use .setLeient() method.
```suggestion
This example demonstrates a use case for the  `.setLenient()` method.
```

2023-09-13 18:28 UTC, ChiduAnush commented
I did the recommended changes and did the git add and commit.
then I ran the `git push origin <my-branch-name>` command.

before that, I merged my branch and the Codecademy:main in my fork.

hopefully I did the right thing.
please check of the changes are now okay. thank you so much for your time

@caupolicandiaz

2023-09-13 19:34 UTC, ChiduAnush commented
okay, as I was a little doubtful of the commits, 
I did the following commands, 
`git fetch upstream`
`git rebase upstream/main`
`git push -f origin <my branch name>`

I think it worked.
Please let me know if the changes are reflected properly.
@caupolicandiaz thank you again.

2023-09-13 21:07 UTC, caupolicandiaz approved these changes
@ChiduAnush I've made some additional edits directly. This is ready for a second review.

2023-09-14 01:48 UTC, ChiduAnush commented
Thank you

2023-09-14 13:29 UTC, ChiduAnush commented
I updated the branch using git fetch, rebase and push.
@caupolicandiaz should I see updating everyday or should I leave it?

2023-09-14 16:38 UTC, caupolicandiaz commented
> I updated the branch using git fetch, rebase and push.
> @caupolicandiaz should I see updating everyday or should I leave it?

You don't have to worry about constantly updating. You can leave it as is.

2023-09-14 16:46 UTC, SSwiniarski approved these changes
@ChiduAnush Looks good to me.

2023-09-14 17:10 UTC, ChiduAnush commented
great, thank you so much.
I can see that 2/6 checks have not passed.

what is this about? do I need to make any changes?
what are the next steps?

2023-09-14 17:25 UTC, merged

2023-09-14 17:31 UTC, ChiduAnush commented
okay I can see the merged and closed purple notification. is my work done then? thank you too muchhh.
Can I see the changes on the website now?