added gitMinimum.md
Codecademy/docs pull request #3235
Opened 2023-09-12 05:21 UTC by ChiragAgg5k

### Description

Added term entry for java calendar's getMinimum method. Closes #3095 .

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-12 16:21 UTC, caupolicandiaz requested changes
@ChiragAgg5k I've added my initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-12 16:21 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getMinimum/getMinimum.md
> +The `.getMinimum()` method of the `Calendar` class returns the minimum value for the given calendar field of this `Calendar` class's instance.
```suggestion
The **`.getMinimum()`** method of the `Calendar` class returns the minimum value for the given calendar field.
```

2023-09-12 16:21 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getMinimum/getMinimum.md
> +Description: 'Returns the minimum value for the given calendar field of this Calendar instance.'
```suggestion
Description: 'Returns the minimum value for the given calendar field.'
```

2023-09-12 16:21 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getMinimum/getMinimum.md
> +
there should be a short sentence describing `field`

2023-09-12 16:21 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/getMinimum/getMinimum.md
> +```java
update the indentation in the code to use 2 spaces, not tabs

2023-09-13 16:59 UTC, caupolicandiaz approved these changes
@ChiragAgg5k LGTM. This is ready for a second review.

2023-09-17 20:56 UTC, SSwiniarski approved these changes
@ChiragAgg5k looks good.

2023-09-17 20:57 UTC, merged