[Edit] Edits to proof-by-strong-induction.md
Codecademy/docs pull request #3237
Opened 2023-09-12 06:17 UTC by noahpgordon

### Description

Edited file proof-by-strong-induction.md

-Corrected basic misunderstanding of the relationship between strong and weak induction (both can have multiple base cases, contra previous entry).
-Clarified example proof.
-Added explanation of the logic of strong induction.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-24 18:39 UTC, SSwiniarski approved these changes
@noahpgordon Looks good to me. I'm sending for a second review.

2023-10-10 01:18 UTC, noahpgordon commented
@yangc95 I made some changes to the recent edits. The most significant were that I changed the description so that it reflects the difference between strong induction and regular induction, and I eliminated the reference to recursion, as it was somewhat inaccurate. (Recursion is not used to prove the inductive step in a strong induction, although there are clear similarities between the logic of induction as a whole and the technique of recursion.)

2023-11-30 19:53 UTC, dakshdeepHERE requested changes

2023-11-30 19:53 UTC, dakshdeepHERE commented on content/discrete-math/concepts/proofs/terms/proof-by-strong-induction/proof-by-strong-induction.md
> +2. Inductive Step: Prove that if _n_ and all elements prior to n have the relevant property, then _n + 1_ has that property.
```suggestion
1. `Base Step`: Prove that the first element or elements in the series have some property.
2. `Inductive Step`: Prove that if _n_ and all elements before n have the relevant property, then _n + 1_ has that property.
```

2023-12-11 16:48 UTC, dakshdeepHERE approved these changes
This looks good for merging 🚀

2023-12-11 17:49 UTC, merged