Create number-format.md, closes #3219
Codecademy/docs pull request #3240
Opened 2023-09-12 20:14 UTC by reganmarie

- Created number-format.md on filepath docs/content/php/concepts/string-functions/terms/number-format/number-format.md
- Added Title, Description, Subjects, Tags, and Catalog Content
- Added description, syntax, example, and codebyte example
- Ran through 3 online plagiarism checkers to ensure 100% unique wording and description, passed with 100%
- Followed content and style guidelines -Checked for spelling and grammar errors

### Description

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-12 21:23 UTC, caupolicandiaz requested changes
@reganmarie I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-12 21:23 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/number-format/number-format.md
> +Description: 'Formats a number with grouped thousands'
```suggestion
Description: 'Returns a given value formatted with grouped thousands.'
```

2023-09-12 21:23 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/number-format/number-format.md
> +  - 'Web Development'
```suggestion
```

2023-09-12 21:23 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/number-format/number-format.md
> +  - 'Web Development'
there should only be two items under subjects

2023-09-12 21:23 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/number-format/number-format.md
> +- `decimal_point`: Optional argument that specifies the decimal separator and should be given in string format.
```suggestion
- `decimal_point`: Optional parameter that specifies the decimal separator and should be given as a string.
```

2023-09-12 21:23 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/number-format/number-format.md
> +- `separator`: Optional argument that specifies the thousands separator and should be given in string format.
```suggestion
- `separator`: Optional parameter that specifies the thousands separator and should be given as a string.
```

2023-09-12 21:23 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/number-format/number-format.md
> +This is the output for the above example:
```suggestion
This will result in the following output:
```

2023-09-12 21:23 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/number-format/number-format.md
> +  echo number_format("500000");
```suggestion
  echo number_format("500000"), "\n";
```

2023-09-12 21:23 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/number-format/number-format.md
> +The following codebyte example can be run and calls the `number_format()` method two times. The second call uses the optional `decimals`, `decimal_point`, and `separator` arguments.
```suggestion
The following codebyte example can be run and calls the `number_format()` method two times. The second call uses the optional `decimals`, `decimal_point`, and `separator` parameters.
```

2023-09-12 22:05 UTC, reganmarie commented
@caupolicandiaz I didn't want to spam your inbox by responding to each individual revision, so these are the changes I made in the latest commit!
- Changed Description to 'Returns a given value formatted with grouped thousands.'
- Removed a subject so there are only two
- Changed argument to parameter in syntax
- Changed "given in string format" to "given as a string" in both instances that wording was used in Syntax block
- Changed output wording to "this will result in the following output" in example section
- Added new line to Codebyte example
- Changed 'arguments' to 'parameters' in Codebyte explanation

2023-09-13 16:54 UTC, caupolicandiaz approved these changes
@reganmarie This is ready for a second review.

2023-09-13 17:04 UTC, reganmarie commented
Thank you @caupolicandiaz 😊

2023-09-17 20:54 UTC, SSwiniarski approved these changes
@reganmarie Looks good.

2023-09-17 20:55 UTC, merged