[Edit] HTML Add Media: Links #3231
Codecademy/docs pull request #3246
Opened 2023-09-13 09:21 UTC by maxx-l

### Description

Added a section about the title attribute in links.md 

### Type of Change

- Updating the documentation

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-13 09:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3246) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3246) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3246) it.</sub>

2023-09-14 11:49 UTC, SSwiniarski requested changes
@maxx-l I did a first review and left two comments.

2023-09-14 11:49 UTC, SSwiniarski commented on content/html/concepts/links/links.md
> +
Can we have an image of a cursor hovering over the link with the pop-up text?  The issue specifically wanted images.

2023-09-14 11:49 UTC, SSwiniarski commented on content/html/concepts/links/links.md
> +<a href="https://www.codecademy.com/resources/docs" title="Go to codecademy documentation">Visit our Tutorial</a>
```suggestion
<a href="https://www.codecademy.com/resources/docs" title="Go to Codecademy Docs">Learn about code.</a>
```

2023-09-14 14:16 UTC, maxx-l commented
Hi @SSwiniarski ,

Thanks for the review. I added your first comment to this commit.
I am trying to add a gif but I am struggling to display it on my side.  
I used this markdown  found [here ](https://www.codecademy.com/resources/docs/contribution-guide/writing-your-doc)
`![Example](https://raw.githubusercontent.com/Codecademy/docs/main/media/<links-title-attribute>.<gif>)`

any suggestion?
Cheers

2023-10-16 23:41 UTC, caupolicandiaz commented
@maxx-l There hasn't been any any activity on this PR, are you still available to complete this?

2023-10-21 12:17 UTC, closed without merging