Create remainder.md
Codecademy/docs pull request #3249
Opened 2023-09-13 18:26 UTC by reganmarie

### Description

- Created number-format.md on filepath docs/content/go/concepts/math-functions/terms/remainder/remainder.md
- Added Title, Description, Subjects, Tags, and Catalog Content
- Added description, syntax, example, and codebyte example
- Ran through 3 online plagiarism checkers to ensure 100% unique wording and description, passed with 100%
- Followed content and style guidelines -Checked for spelling and grammar errors

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-13 20:36 UTC, caupolicandiaz requested changes
@reganmarie I've completed my initial review. Please update the entry, and tag me when you've finished making the changes. Thanks

2023-09-13 20:36 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/remainder/remainder.md
> +Description: 'Returns the remainder of two given values.'
```suggestion
Description: 'Returns the remainder of the division of two given values.'
```

2023-09-13 20:36 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/remainder/remainder.md
> +The **`Remainder()`** function returns the remainder of two given values. The remainder may be a whole number or the IEEE 754 floating-point.
```suggestion
The **`Remainder()`** function returns the remainder of the division of two given values. The remainder may be a whole number, or a floating-point.
```

2023-09-13 20:36 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/remainder/remainder.md
> +- math.Remainder(±Inf, num2) returns NaN
```suggestion
- If `num1` equals `+-Inf` the function will return `NaN`, if num2 equals `+-Inf` the function returns `num1`
```

2023-09-13 20:36 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/remainder/remainder.md
> +- math.Remainder(NaN, num2) returns NaN
```suggestion
- If either argument is `NaN` the function will return `NaN`
```

2023-09-13 20:36 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/remainder/remainder.md
> +- math.Remainder(num1, 0) returns NaN
```suggestion
- If `num2` equals `0` the function will return `NaN`
```

2023-09-13 20:36 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/remainder/remainder.md
> +- math.Remainder(num1, NaN) returns NaN
```suggestion
```

2023-09-13 20:36 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/remainder/remainder.md
> +  result2 := math.Remainder(±Inf, 2)
```suggestion
  result2 := math.Remainder(math.Inf(1), 2)
```

2023-09-13 20:36 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/remainder/remainder.md
> +  fmt.Printf("Result 2: %.1f\n", result_2)
```suggestion
  fmt.Printf("Result 1: %.1f\n", result1)
  fmt.Printf("Result 2: %.1f\n", result2)
```

2023-09-14 00:13 UTC, reganmarie commented
@caupolicandiaz Updated and committed every revision, listed here! 
- Line 3, change Description to 'Returns the remainder of the division of two given values.'
- Line 15 change to The **`Remainder()`** function returns the remainder of the division of two given values. The remainder may be a whole number, or a floating-point.
- Take out lines 25-29 and replace with combined rules for special cases
- Change Codebyte example in line 70 to result2 := math.Remainder(math.Inf(1), 2)
- Change Codebyte print statements to result1, result2

2023-09-14 16:39 UTC, reganmarie commented
Thank you @caupolicandiaz! 😊

2023-09-16 13:39 UTC, SSwiniarski approved these changes
@reganmarie I did a small edit and it looks good to merge.

2023-09-16 13:41 UTC, merged