Write an entry for move()
Codecademy/docs pull request #3252
Opened 2023-09-14 23:35 UTC by E-Aghbari

### Description

Codecademy assigned this issue for me to experience on how is it to be a contributor; thus, this is my first contribution into a repository on Github. Therefore, I have created a term entry for the `.move()` function in the `move` folder within the `table` folder. A metadata about the function has been written at the very top of the document with brief description of it I also explained the parameters of the function and what type of data type that is passed for each argument. Using an example, I showcased how the function work using two different tables.

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [✓ ] All writings are my own.
- [✓ ] My entry follows the Codecademy Docs style guide.
- [✓ ] My changes generate no new warnings.
- [✓ ] I have performed a self-review of my own writing and code.
- [ ✓] I have checked my entry and corrected any misspellings.
- [✓ ] I have made corresponding changes to the documentation if needed.
- [✓ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [✓ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [✓ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-14 23:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3252) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3252) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3252) it.</sub>

2023-09-16 03:46 UTC, KTom101 requested changes
@E-Aghbari I've added some changes to this entry.

2023-09-16 03:46 UTC, KTom101 commented on content/lua/concepts/tables/terms/move/move.md
> +The above code will result in:
```suggestion
The above code will result in:

```

2023-09-16 09:08 UTC, E-Aghbari commented on content/lua/concepts/tables/terms/move/move.md
> +```
Wouldn't that result make the whole entry a block of code since ``` at bottom removed?

2023-09-23 18:21 UTC, KTom101 approved these changes
@E-Aghbari Please wait for a second review.

2023-09-23 21:46 UTC, caupolicandiaz requested changes
@E-Aghbari I've added my comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-23 21:46 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/move/move.md
> +`t` means _to_ (First index within `a2`).
```suggestion
- `.move()` function expects five arguments where `a1` is the source table and `a2` is the destination table.
- `f` means _from_ (First index within `a1`).
- `e` means _end_ (Last index within `a1`).
- `t` means _to_ (First index within `a2`).
```

2023-09-23 21:46 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/move/move.md
> +local Table2 = {}
```suggestion
local Table1 = {"🍎", "🍌", "🍇", "🍓", "🍉" }

local Table2 = {"🍎", "🍌"}
```

2023-09-23 21:46 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/move/move.md
> +table.move(Table1, 1, #Table1, #Table2 + 1, Table2)
```suggestion
table.move(Table1, 1, #Table1, 3, Table2)
```

2023-09-23 21:46 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/move/move.md
> +local Table2 = {}
I think the operation might be more obvious if the move is happening to a table that has some elements

2023-09-23 21:46 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/move/move.md
> +print(table.concat(Table2))
```suggestion
print(table.unpack(Table2))
```

2023-09-23 21:46 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/move/move.md
> +In this example, the elements in `Table1` have been copied to `Table2` using the `.move()` function. Starting from index 1 in `Table1` until the end and then copying them in sequence to `Table2` star
```suggestion
In this example, the elements in `Table1` have been copied to `Table2` using the `.move()` function. Starting from index 1 in `Table1` until the end and then copying them in sequence to `Table2` starting from index 3.
```

2023-09-23 21:46 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/move/move.md
> +🍎🍌🍇🍓🍉
```suggestion
🍎 🍌 🍎 🍌 🍇 🍓 🍉
```

2023-09-23 21:46 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/move/move.md
> +> **Note:** In Lua, indices start from 1; thus, the fourth argument is `#Table2 + 1` where `#Table2` is the length of the table. Therefore, `0 + 1` is the starting index of `Table2`.
```suggestion
> **Note:** In Lua, indices start from 1; thus, the next available index in `Table2` is index 3.
```

2023-10-02 19:56 UTC, E-Aghbari commented
I have finished updating the entry, please have a look. Thank you. @caupolicandiaz

2023-10-02 21:01 UTC, caupolicandiaz approved these changes
@E-Aghbari @KTom101 LGTM

2023-10-02 21:13 UTC, E-Aghbari commented
@caupolicandiaz Why does the CLA shows that i have not signed yet when I already have?
Thanks.

2023-10-02 21:29 UTC, E-Aghbari commented
@caupolicandiaz It seems that I commited with different username Ebrahim Al Aghbari for some reason and the CLA refuses to carry on unless its signed but I dont know how to remove that commit. Is it possible to remove that commit and them commit again with same user?

2023-10-02 22:39 UTC, caupolicandiaz commented
> @caupolicandiaz It seems that I commited with different username Ebrahim Al Aghbari for some reason and the CLA refuses to carry on unless its signed but I dont know how to remove that commit. Is it possible to remove that commit and them commit again with same user?

I'm not sure that's something we can reverse. I think we might have to push through the commit with the error. @KTom101 @yangc95 @SSwiniarski Am I missing an alternative option to resolving this CLA issue?

2023-10-03 15:38 UTC, SSwiniarski commented
> > @caupolicandiaz It seems that I commited with different username Ebrahim Al Aghbari for some reason and the CLA refuses to carry on unless its signed but I dont know how to remove that commit. Is it possible to remove that commit and them commit again with same user?
> 
> I'm not sure that's something we can reverse. I think we might have to push through the commit with the error. @KTom101 @yangc95 @SSwiniarski Am I missing an alternative option to resolving this CLA issue?

@caupolicandiaz We can merge with the error. We've done so with similar issues.

2023-10-03 15:39 UTC, merged

2023-10-03 17:04 UTC, E-Aghbari commented
@SSwiniarski Thank you for merging my branch into the main. However, my name is does not appear and shows as Anonymous Contributor, though I linked my github account to my codecademy account. Is there a way to fix that to show up my name?