My entry about the CodingKey protocol
Codecademy/docs pull request #3262
Opened 2023-09-18 12:49 UTC by LVC1D

### Description (Closes #2961)

I have submitted a **Term Entry** about the `CodingKey` protocol that works in conjunction with the `Decodable` and `Encodable` protocols.

Those protocols are for the Swift objects to conform to when we want to map the key of the JSON's objects and the Swift objects' properties.

The workflow for this entry is as follows:

+ I have provided two basic pseudo-codebases for the Decodable and the Encodable scenarios
+ Then, I have proceeded with showcasing the application of the CodingKey protocol in the enumerator defined inside both the examples' structs
+ Below each example, I have shown what would the expected result be logged in the terminal upon running the examples codes

*My small concern here is with the understanding of the last checkmark point about "linking any issues that are relevant to this PR". I have written to which issue number I am referring as mentioned in the parentheses.*

### Type of Change

- Adding a new entry **codingkey/codingkey.md** into the following path: *content/swift/concepts/protocols*

### Checklist

- [V] All writings are my own.
- [V] My entry follows the Codecademy Docs style guide.
- [V] My changes generate no new warnings.
- [V] I have performed a self-review of my own writing and code.
- [V] I have checked my entry and corrected any misspellings.
- [V] I have made corresponding changes to the documentation if needed.
- [V] I have confirmed my changes are not being pushed from my forked `main` branch.
- [V] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [V] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-21 21:53 UTC, caupolicandiaz requested changes
@LVC1D I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +```shell
```suggestion
```

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +Description: 'Enables the mapping of JSON's keys to different Swift's struct / class properties.'
```suggestion
Description: 'Enables the mapping of keys from JSON to a given Swift struct or class property.'
```

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +Description: 'Enables the mapping of JSON's keys to different Swift's struct / class properties.'
descriptions cannot contain punctuation like apostrophes

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +> **Note:** JSON and Swift have different naming conventions (JSON uses *snake_case* for its key identifiers, while Swift uses *camelCase* for its property identifiers)
There should be an empty line after the note

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +## Syntax
There should be am empty line after the syntax header

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +This protocol will work when a Swift object conforms to either an `Decodable` or `Encodable` protocol.
I don't believe there needs to be a separate example but `Decodable` and `Encodable` are each just half of the `Codable` protocol which isn't mentioned

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +The above demonstrates the usage of an enumerator 'CodingKeys', its cases of which refer to the JSON's object keys. It also specifies:
```suggestion
The code above demonstrates the usage of an enumerator `CodingKeys`, its cases of which refer to the JSON's object keys. It also specifies:
```

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +1. the raw value type of the keys (it's a String because all JSON keys are of a String type only),
```suggestion
1. The raw value type of the keys (it's a `String` because all JSON keys are of a `String` type only).
```

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +2. the `CodingKey` protocol to which the enumerator has to conform in order to map the JSON keys with the Swift object's properties
```suggestion
2. The `CodingKey` protocol to which the enumerator has to conform in order to map the JSON keys with the Swift object's properties.
```

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +The example below will decode a JSON object array of famous musicians into a Swift model using the enumerator that conforms to the `CodingKey` protocol, and
```suggestion
The example below will decode a JSON object array of famous musicians into a Swift model using the enumerator that conforms to the `CodingKey` protocol, and list the name and active years for each musician using a `.forEach` function.
```

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +list each musician's names and active years using a `.forEach` function
```suggestion
```

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +```swift
code indentations should use 2 spaces not tabs

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +> **Note:** *Notice how we managed to use the newly-created `yearsActive` property in the Swift model when JSON's key was written as `years_active`.*
```suggestion
> **Note:** Notice the use of the newly-created `yearsActive` property in the Swift model when JSON's key is written as `years_active`.
```

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +> **Note:** *Notice how we managed to use the newly-created `yearsActive` property in the Swift model when JSON's key was written as `years_active`.*
docs content avoids the use of first and second person personal pronouns (I , you, we)

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +> Note that we only used a trailing closure in the invoked functon to simplify the code.
```suggestion
> **Note:** A trailing closure in the invoked function is used only to simplify the code.
```

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +Following the workflow of [encoding](https://www.codecademy.com/resources/docs/swift/protocols/encodable) the Swift model into a JSON data structure, let's create an
```suggestion
Following the workflow of [encoding](https://www.codecademy.com/resources/docs/swift/protocols/encodable) the Swift model into a JSON data structure, the following example will display the `Exercises` struct parsed into JSON.
```

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +example of displaying the **Exercises** struct parsed into JSON.
```suggestion
```

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +import Foundation
update the indentations and comments should begin with a capital
// Create the CodingKyes enum to define the JSON keys

2023-09-21 21:53 UTC, caupolicandiaz commented on content/swift/concepts/protocols/terms/codingkey/codingkey.md
> +The output in the terminal will produce the following:
add an empty line before the shell block

2023-09-22 19:59 UTC, LVC1D commented
@caupolicandiaz Hi again! I've refactored the entry by showcasing one cohesive example that conforms to the `Coddle` protocol. In addition, I took into account all other suggestions of yours, that included fixing the indentations, phrasings etc.

Let me know if this version looks better now. Thank you.

2023-09-25 21:50 UTC, caupolicandiaz approved these changes
@LVC1D This is ready for a second review

2023-10-09 11:57 UTC, LVC1D commented
@caupolicandiaz Hi! Are there any updates on this PR, please?

2023-10-09 17:24 UTC, caupolicandiaz commented
> @caupolicandiaz Hi! Are there any updates on this PR, please?

Please be patient. There are many PRs and few maintainers.

2023-10-26 16:11 UTC, SSwiniarski approved these changes
@LVC1D Dis some minor edits. Looks good now.

2023-10-26 16:18 UTC, merged