Go term copysign
Codecademy/docs pull request #3299
Opened 2023-09-20 14:29 UTC by abu-hasib

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-20 19:36 UTC, caupolicandiaz requested changes
@abu-hasib I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-20 19:36 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/copysign/copysign.md
> +Description: 'Returns a value with the magnitude of a parameter and a sign of another parameter'
```suggestion
Description: 'Returns a value with the magnitude and sign of the given arguments.'
```

2023-09-20 19:36 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/copysign/copysign.md
> +The **`Copysign()`** of the `math` package is an inbuilt function that takes two parameters and returns a value containing magnitude of the first parameter and a sign of the second parameter.
```suggestion
The **`Copysign()`** of the `math` package is an inbuilt function that returns a value based on the magnitude of the first argument and the sign of the second argument.
```

2023-09-20 19:36 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/copysign/copysign.md
> +Where `CpSgnXY` is the value of the magnitude of `x` and the sign of `y`, it is of type `float64`.
```suggestion
Where `CpSgnXY` is the value, of type `float64`, composed of the magnitude of `x` and the sign of `y`.
```

2023-09-20 19:36 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/copysign/copysign.md
> +The following Golang program calculates the magnitude of `x` and the sign of `y` and prints out the result:
```suggestion
The following code demonstrates the basic implementations of `.Copysign()`:
```

2023-09-20 19:36 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/copysign/copysign.md
> +The following example shows how the `Copysign()` function handles float64 arguments.
```suggestion
The following example shows how the `Copysign()` function handles various arguments.
```

2023-09-23 22:42 UTC, abu-hasib commented
@caupolicandiaz

2023-09-25 17:40 UTC, caupolicandiaz approved these changes
@abu-hasib This is ready for a second review

2023-10-03 16:03 UTC, SSwiniarski approved these changes
@abu-hasib Looks good.

2023-10-03 16:03 UTC, SSwiniarski commented on content/go/concepts/math-functions/terms/cosh/cosh.md
It looks as if you created a branch off of another PR branch rather than main. You'll need to delete this extra file to avoid a conflict when merging.

2023-10-03 16:08 UTC, merged