Docs
Codecademy/docs pull request #3304
Opened 2023-09-21 05:52 UTC by ATREAY

### Description

This Pull Request is associated with Issue #3279(Python Strings .isidentifier()).

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-21 16:28 UTC, SSwiniarski requested changes
@ATREAY I had a couple of comments.

2023-09-21 16:28 UTC, SSwiniarski commented on content/python/concepts/strings/terms/isidentifier/isidentifier.md
> +## Example1
```suggestion
## Example
```

2023-09-22 05:01 UTC, ATREAY commented
Hello @SSwiniarski, I have implemented the necessary modifications. 
I kindly request that you review them.

2023-09-22 16:30 UTC, SSwiniarski approved these changes
@ATREAY Looks good for a second review.

2023-09-22 17:04 UTC, caupolicandiaz requested changes
@ATREAY I've added my comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-22 17:04 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/isidentifier/isidentifier.md
> +Use `.isidentifier()` to check if a string is a valid Python identifier:
```suggestion
In the code below `.isidentifier()` to check if a string is a valid Python identifier:
```

2023-09-22 17:04 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/isidentifier/isidentifier.md
> +Use `.isidentifier()` to check if `my_string` is a valid Python identifier:
```suggestion
The following code is runnable and uses `.isidentifier()` to check if `my_string` is a valid Python identifier:
```

2023-09-22 17:04 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/isidentifier/isidentifier.md
> +```py
```suggestion
```pseudo
```

2023-09-23 03:28 UTC, ATREAY commented
Hello @caupolicandiaz, I have made the required changes.
I kindly request that you review them.

2023-09-23 21:02 UTC, caupolicandiaz approved these changes
@ATREAY Looks good

2023-09-23 21:04 UTC, merged