- Added image for tr preview ,- Fixed iframe video to be able to play in readme file
Codecademy/docs pull request #3306
Opened 2023-09-21 06:37 UTC by Moddinu

- Added image for tr preview 
- Fixed iframe video to be able to play in readme file

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-21 06:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3306) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3306) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3306) it.</sub>

2023-11-06 17:44 UTC, SSwiniarski commented
@Moddinu if we do not see movement on this PR in a couple of days we'll have to close this PR and unassign the issue.

2023-11-07 06:43 UTC, Moddinu commented
I already pushed my code so you can close it once merged.

On Mon, Nov 6, 2023 at 6:44 PM SSwiniarski ***@***.***> wrote:

> @Moddinu <https://github.com/Moddinu> if we do not see movement on this
> PR in a couple of days we'll have to close this PR and unassign the issue.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Codecademy/docs/pull/3306#issuecomment-1795676614>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABILHAVUDRSQXQQJVJ4XGATYDEOYNAVCNFSM6AAAAAA5BAKUACVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJVGY3TMNRRGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-09 06:48 UTC, Moddinu commented on content/html/concepts/tables/tables.md
> +![source="https://www.w3schools.com/html/html_tables.asp"](https://raw.githubusercontent.com/Codecademy/docs/main/media/html-tables-tr.png)
Done

2023-11-09 06:50 UTC, Moddinu commented on content/html/concepts/tables/tables.md
> -<iframe width="560" height="315" src="https://www.youtube.com/embed/VjiD2EyJHIQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
Done reverted iframe back

2023-11-12 14:48 UTC, SSwiniarski requested changes
@Moddinu There are still several problems with this that need to be addressed.

2023-11-12 14:48 UTC, SSwiniarski commented on content/html/concepts/tables/tables.md
> +![image](https://github.com/Moddinu/docs/assets/5288834/b30bf57d-f69c-4fb3-8e3c-97943cf49ab5)---
```suggestion
```
This is in the metadata, this is wrong.

2023-11-12 14:48 UTC, SSwiniarski commented on content/html/concepts/tables/tables.md
> +![image](https://github.com/Moddinu/docs/assets/5288834/1a865d50-a767-4736-8cc4-ff4d68e57615)
This image is in the wrong place. it needs to be uploaded to the `/media` folder and use the url:`https://raw.githubusercontent.com/Codecademy/docs/main/media/`

2023-11-12 14:48 UTC, SSwiniarski commented on content/html/concepts/tables/tables.md
> +![image](https://github.com/Moddinu/docs/assets/5288834/2b15a2d2-d047-4426-a3bb-f04cfb137278)
This image is in the wrong place. it needs to be uploaded to the `/media` folder and use the url:`https://raw.githubusercontent.com/Codecademy/docs/main/media/`

2023-11-12 14:48 UTC, SSwiniarski commented on content/html/concepts/tables/tables.md
> +![source="https://www.w3schools.com/html/html_tables.asp"](https://raw.githubusercontent.com/Codecademy/docs/main/media/html-tables-tr.png)
You cannot use images from other websites, that's plagiarism an not allowed. You also put the url in the ALT text of the markdown and the actual image URL is pointing at the poor image you've uploaded to the media folder. Please remove that image.

2023-11-22 13:01 UTC, SSwiniarski commented
@Moddinu are you still working on this? If we do not hear from you in another week we're going to close the PR and unassign the issue.

2023-11-22 13:03 UTC, Moddinu commented
Please close the issue and unassign as did not find time to work on it.
Thank you learned alot

On Wed, Nov 22, 2023 at 2:01 PM SSwiniarski ***@***.***>
wrote:

> @Moddinu <https://github.com/Moddinu> are you still working on this? If
> we do not hear from you in another week we're going to close the PR and
> unassign the issue.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Codecademy/docs/pull/3306#issuecomment-1822730205>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABILHAWHMJ4HDWYINMNKHODYFXZSBAVCNFSM6AAAAAA5BAKUACVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRSG4ZTAMRQGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-22 16:44 UTC, SSwiniarski commented
Closed at author request.

2023-11-22 16:44 UTC, closed without merging