[Term Entry] Lua Tables getn()
Codecademy/docs pull request #3311
Opened 2023-09-22 20:54 UTC by badday182

### Description

- Added Table.Getn() term for Lua
- Closes issue #3168 #
### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-22 20:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3311) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3311) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3311) it.</sub>

2023-09-27 20:01 UTC, caupolicandiaz requested changes
@badday182 I've added a couple of initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-27 20:01 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/getn/getn.md
> +---
Please update the spacing in the entry. There should never be multiple empty lines between content, and there should always be one empty line after a header or code block

2023-09-28 08:13 UTC, badday182 commented
@caupolicandiaz  Thank you for your feedback, I finished making changes:
- updated the path and the entry to Luau
- updated the spacing in the entry

2023-09-28 17:57 UTC, caupolicandiaz requested changes
@badday182 I've added some additional comments.

2023-09-28 17:57 UTC, caupolicandiaz commented on content/luau/concepts/tables/terms/getn/getn.md
> +**This function has been deprecated and is not recommended for use in new code; use #t instead.**
```suggestion
> **Note:** This function has been deprecated. It is recommended that new projects use `#t` instead.
```

2023-09-28 17:57 UTC, caupolicandiaz commented on content/luau/concepts/tables/terms/getn/getn.md
> +**This function has been deprecated and is not recommended for use in new code; use #t instead.**
move this after the description/summary

2023-09-28 17:57 UTC, caupolicandiaz commented on content/luau/concepts/tables/terms/getn/getn.md
> +```luau
```suggestion
```lua
```

2023-09-28 17:57 UTC, caupolicandiaz commented on content/luau/concepts/tables/terms/getn/getn.md
> +```lua
```suggestion
```shell
```

2023-09-28 17:57 UTC, caupolicandiaz commented on content/luau/concepts/tables/terms/getn/getn.md
> +```
```suggestion
```shell
```

2023-09-28 17:57 UTC, caupolicandiaz commented on content/luau/concepts/tables/terms/getn/getn.md
> +```
```suggestion
```shell
```

2023-09-28 17:57 UTC, caupolicandiaz commented on content/luau/concepts/tables/terms/getn/getn.md
> +print(count) -- Prints 4
this output should also be in a separate ```shell block

2023-09-28 17:57 UTC, caupolicandiaz commented on content/luau/concepts/tables/terms/getn/getn.md
> +## Example 4
There should be an empty line after the example header

2023-09-29 07:03 UTC, badday182 commented
@caupolicandiaz i've finished making changes:
- moved "Note:" to the end of description/summary
- chenged "luau" to "lua"
- chenged/added ```shell block

2023-09-29 19:39 UTC, badday182 commented
@caupolicandiaz i've made several corrections:
- changed and moved note about deprecated function to the end of description/summary
- luau block changed to lua block
- used shell block where it's correct

2023-09-29 20:14 UTC, caupolicandiaz requested changes
@badday182 There are a number of additional edits that got mixed in with this PR. There should only be one file here, please revert the other changes. You should be able to use the following syntax-
git checkout main -- filepath

2023-10-03 22:38 UTC, caupolicandiaz approved these changes
@badday182 This is ready for a second review.  However, there continue to be a pair of files that should not be part of this PR

2023-10-05 12:16 UTC, badday182 commented
@caupolicandiaz 
- no empty line after the example header
- valid filenames other directories

2023-10-05 12:35 UTC, badday182 commented
@caupolicandiaz 
- no empty line after the example header
- valid filenames other directories

2023-10-05 19:17 UTC, caupolicandiaz approved these changes
@badday182 This is ready for a second review.

2023-10-12 04:33 UTC, KTom101 requested changes
@badday182 I added changes

2023-10-12 04:33 UTC, KTom101 commented on content/luau/concepts/tables/terms/getn/getn.md
> +The **`.getn()`** function in Luau returns the number of elements in a table by iterating over the table and counting the elements, while ignoring any nil elements. This function is a handy tool for
The note is supposed to go here with a blockquote (change added below 👇 )
```suggestion
The **`.getn()`** function in Luau returns the number of elements in a table by iterating over the table and counting the elements, while ignoring any nil elements. This function is a handy tool for various table-related tasks, including checking the table's length, allocating memory for a table, and determining if a table is empty.

> **Note:** This function has been deprecated. Applying the `.getn()` function will result in an error. Use `#t` instead.
```

2023-10-13 08:11 UTC, badday182 commented
@KTom101 Thank you for your response, I've added your comments into description

2023-10-19 16:29 UTC, KTom101 approved these changes

2023-10-19 20:22 UTC, caupolicandiaz commented
@badday182 This entry is currently failing our formatting test and can't be merged until it is resolved. Often, we take responsibility for running the formatter to update entries. However, we don't have access to your remote. Contributors are asked to use the **Allow edits from maintainers** option. Please update your access settings or run the formatter on your own. Thanks

2023-10-20 06:33 UTC, badday182 commented
@caupolicandiaz I've given maintainers access to editing

2023-10-20 21:11 UTC, KTom101 commented
@badday182 Thank you. I was able to format the failing [checks](https://www.codecademy.com/resources/docs/contribution-guide/getting-set-up-on-your-computer#:~:text=There%20are%20continuous%20integration%20(CI)%20workflows) using `npm run format:all`. I will go ahead and merge this.

2023-10-20 21:12 UTC, merged