Complete isfrozen function term entry
Codecademy/docs pull request #3317
Opened 2023-09-24 10:48 UTC by 0umkbe

### Description

Adding new entry regarding the `.isfrozen()` function in Luau language.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-24 10:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3317) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3317) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3317) it.</sub>

2023-09-24 15:11 UTC, SSwiniarski requested changes
@0umkbe I did a first review and left a few comments.

2023-09-24 15:11 UTC, SSwiniarski commented on content/luau/concepts/tables/terms/isfrozen/isfrozen.md
> +In this example, we first create a table called myTable. Then, we use the isfrozen() function to check if it's in read-only mode. Depending on the result, we print a message indicating whether the ta
```suggestion
In this example, a table called `myTable` is created. Then, the `isfrozen()` function is used to check if it's in read-only mode. Depending on the result, a message is printed indicating whether the table is frozen (read-only) or not.
```
After these edits, let's move this before the example code block.

2023-09-24 15:11 UTC, SSwiniarski commented on content/luau/concepts/tables/terms/isfrozen/isfrozen.md
> +## Codebyte Example
```suggestion
## Example
```
This isn't a codebyte. Codebytes are special code blocks that the reader can execute. It's only supported for some languages, and Luau isn't one of them.

2023-09-24 15:11 UTC, SSwiniarski commented on content/luau/concepts/tables/terms/isfrozen/isfrozen.md
> +local frozenStatus = myTable:IsFrozen()
```suggestion
local frozenStatus = table.isfrozen(myTable)
```

2023-09-24 17:33 UTC, SSwiniarski requested changes
@0umkbe a couple more comments.

2023-09-24 17:33 UTC, SSwiniarski commented on content/luau/concepts/tables/terms/isfrozen/isfrozen.md
> +Title: '.isfrozen'
```suggestion
Title: 'isfrozen()'
```

2023-09-24 17:33 UTC, SSwiniarski commented on content/luau/concepts/tables/terms/isfrozen/isfrozen.md
> +
```suggestion
```
Remove blank line at start of entry.

2023-09-24 18:33 UTC, SSwiniarski approved these changes
@0umkbe looks good for a second review.

2023-09-26 20:41 UTC, caupolicandiaz requested changes
@0umkbe I've added some additional comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-26 20:41 UTC, caupolicandiaz commented on content/luau/concepts/tables/terms/isfrozen/isfrozen.md
> +The 'isfrozen()' function returns a boolean value, true if the table is in read-only mode and false if it's not.
```suggestion
The `isfrozen()` function returns a boolean value, `true` if the table is in read-only mode and `false` if it's not.
```

2023-09-26 20:41 UTC, caupolicandiaz commented on content/luau/concepts/tables/terms/isfrozen/isfrozen.md
> +```luau
```suggestion
```lua
```

2023-09-26 20:41 UTC, caupolicandiaz commented on content/luau/concepts/tables/terms/isfrozen/isfrozen.md
> +```luau
I don't believe luau is supported by markdown code blocks, but Lua can be used to show the syntax highlighting

2023-09-26 20:41 UTC, caupolicandiaz commented on content/luau/concepts/tables/terms/isfrozen/isfrozen.md
> +In this example, a table called `myTable` is created. Then, the `isfrozen()` function is used to check if it's in read-only mode. Depending on the result, a message is printed indicating whether the
```suggestion
In this example, a table called `myTable` is created. Then, the `isfrozen()` function is used to check if it's in read-only mode.

2023-09-26 20:41 UTC, caupolicandiaz commented on content/luau/concepts/tables/terms/isfrozen/isfrozen.md
> +In this example, a table called `myTable` is created. Then, the `isfrozen()` function is used to check if it's in read-only mode. Depending on the result, a message is printed indicating whether the
This is generally set before the example. And an output ```shell block is used to highlight the result

2023-09-26 21:46 UTC, 0umkbe commented
@caupolicandiaz Thanks for the feedback, please check now!

2023-09-27 17:09 UTC, caupolicandiaz approved these changes
@0umkbe @SSwiniarski There were some missing edits that I just made directly. This is good to merge

2023-09-28 18:12 UTC, SSwiniarski commented
@caupolicandiaz @0umkbe we'll need to wait for the table entry for Luau is complete to merge this.

2023-09-28 18:19 UTC, 0umkbe commented
@SSwiniarski Sure, looking forward to it!

2023-10-05 23:02 UTC, merged