Issue #3204 Luau Comments
Codecademy/docs pull request #3320
Opened 2023-09-24 21:15 UTC by AnastasiaCortes

### Description
Adding a new entry regarding Luau comments

### Type of Change

- Adding a new entry

### Checklist

 -[x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-24 21:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3320) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3320) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3320) it.</sub>

2023-09-25 14:42 UTC, SSwiniarski requested changes
@AnastasiaCortes I did a first review and left a couple of comments.

2023-09-26 20:55 UTC, caupolicandiaz requested changes
@AnastasiaCortes I've completed my initial review. Please update the entry, and tag me when you've finished making changes.

2023-09-26 20:55 UTC, caupolicandiaz commented on content/luau/concepts/comments/comments.md
> +Description: 'Comments in Luau are used to add explanatory or descriptive notes within the code. They are ignored by the interpreter and do not affect the execution of the program.'
```suggestion
Description: 'Comments are used to add explanatory or descriptive notes within a script or program.'
```

2023-09-26 20:55 UTC, caupolicandiaz commented on content/luau/concepts/comments/comments.md
> +A **comment**  is text that the Luau parser ignores at runtime. They are useful for documenting code, leaving reminders for future modifications, or temporarily disabling code without removing it.
```suggestion
A **comment** is text that the Luau parser ignores at runtime. They are useful for documenting code, leaving reminders for future modifications, or temporarily disabling code without removing it.
```

2023-09-26 20:55 UTC, caupolicandiaz commented on content/luau/concepts/comments/comments.md
> +type Point = { x: number, y :number }
```suggestion
type Point = { x: number, y: number }
```

2023-09-26 20:55 UTC, caupolicandiaz commented on content/luau/concepts/comments/comments.md
> +In Luau, multi-line or block comments are created using double hyphens and double brackets `--[[ ]]`. The compiler does not read any text in between. Multi-line comments commonly used at the top of f
```suggestion
In Luau, multi-line or block comments are created using double hyphens and double brackets `--[[ ]]`. The compiler does not read any text in between. Multi-line comments are commonly used at the top of files to describe the purpose of a library or module, before functions to describe their intent, and in many other cases.
```

2023-09-26 23:07 UTC, AnastasiaCortes commented
@caupolicandiaz finished with the changes.

2023-09-27 19:46 UTC, caupolicandiaz approved these changes
@AnastasiaCortes @SSwiniarski Looks good to merge

2023-09-28 18:27 UTC, merged