[Term Entry] Python String Function: format_map()
Codecademy/docs pull request #3323
Opened 2023-09-24 23:22 UTC by phuongtrieu97coder

### Description

-Added the .format_map() term for Python
-Closes issue #3273 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-25 19:37 UTC, caupolicandiaz requested changes
@phuongtrieu97coder I've added my initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-25 19:37 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/format-map/format-map.md
> +Description: 'Returns a dictionary key’s value.'
```suggestion
Description: 'Returns the values from a given dictionary.'
```

2023-09-25 19:37 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/format-map/format-map.md
> +Description: 'Returns a dictionary key’s value.'
apostrophes are not permitted in the metadata

2023-09-25 19:37 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/format-map/format-map.md
> +  - 'paths/data-science'
```suggestion
```

2023-09-25 19:37 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/format-map/format-map.md
> +  - 'paths/data-science'
there should only be 2 items under catalog content

2023-09-25 19:37 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/format-map/format-map.md
> +The `.format_map()` string method takes a single parameter which is the input dictionary and returns key's values.
```suggestion
The **`.format_map()`** string method takes a single parameter which is the input dictionary and returns the key's values.
```

2023-09-25 19:37 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/format-map/format-map.md
> +```py
```suggestion
```pseudo
```

2023-09-25 19:37 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/format-map/format-map.md
> +`d` is a variable in which the input dictionary is stored.
```suggestion
`d` is the dictionary to be addressed.
```

2023-09-25 19:37 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/format-map/format-map.md
> +The example below uses `.format_map()` takes in a variable `a` which stores a dictionary and returns the value of the key `x` and `y`:
```suggestion
The example below uses `.format_map()` to return the values stored in `x` and `y`:
```

2023-09-25 19:37 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/format-map/format-map.md
> +# input stored in variable a.
```suggestion
# Input stored in variable a.
```

2023-09-25 19:37 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/format-map/format-map.md
> +
```suggestion
The following code is runnable and demonstrates the use of `.format_map()`:
```

2023-09-26 03:39 UTC, phuongtrieu97coder commented
@caupolicandiaz I've completed my review and finished making changes.

2023-09-26 17:21 UTC, caupolicandiaz approved these changes
@phuongtrieu97coder I just made a couple of spacing edits directly. This is ready for a second review.

2023-10-19 16:24 UTC, SSwiniarski approved these changes
@phuongtrieu97coder @caupolicandiaz Looks good.

2023-10-19 16:25 UTC, merged