Add new term entry for the Python string method .center()
Codecademy/docs pull request #3327
Opened 2023-09-25 15:37 UTC by Rclarkeweb

### Description

Add new term entry for Python string method .center()

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-25 15:57 UTC, Rclarkeweb commented
Hi, I'm not sure why my checks keep failing. I have checked the style guides. Any advice would be much appreciated!

2023-09-25 20:15 UTC, caupolicandiaz requested changes
@Rclarkeweb I've added my initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-25 20:15 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/center/center.md
> +Description: 'Returns a new string with added specified padding. It's default is whitespace.'
```suggestion
Description: 'Returns a new string with the specified padding.'
```

2023-09-25 20:15 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/center/center.md
> +The `length` parameter is required and must be an integar. This will be the length of new string.
```suggestion
The `length` parameter is required and must be an integer. This will be the length of new string.
```

2023-09-25 20:15 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/center/center.md
> +new_str = str.center(10, '+')
it may be better to se the length to 11 in this case so that there are an equivalent number of `+` on either side of the word

2023-09-25 20:15 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/center/center.md
> +The **`.center()`** string method returns a new string that has been amended with added padding. The default padding is whitespace, but any character may be used, including numbers or symbols.
```suggestion
The **`.center()`** string method returns a new string that has been amended with padding. The padding is allocated evenly to both sides of the string, depending on the overall length specified. The default padding is whitespace, but any character may be used, including numbers or symbols.
```

2023-09-26 14:36 UTC, Rclarkeweb commented
Hi @caupolicandiaz I'm not sure why this Pull Request check is failing on the 'format:verify', it is fine on my other PR (.isalpha()). Any ideas on how to fix it? Thanks!

2023-09-26 17:32 UTC, caupolicandiaz approved these changes
@Rclarkeweb This is ready for a second review

2023-10-26 16:14 UTC, SSwiniarski approved these changes
@Rclarkeweb Looks good.

2023-10-26 16:21 UTC, merged