[Term Entry] Lua tables concat()
Codecademy/docs pull request #3345
Opened 2023-09-27 01:26 UTC by phil-haywood

### Description

-Added the tables concat() term for Lua
-Closes issue #3115 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-27 01:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3345) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3345) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3345) it.</sub>

2023-09-27 21:37 UTC, caupolicandiaz requested changes
@phil-haywood I've added my initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-27 21:37 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/concat/concat.md
> +## Introduction
entries do not begin with headers, delete both

2023-09-27 21:37 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/concat/concat.md
> +The `concat()` function is used to join the values of a table into a single string, separated by a specified separator. This function is particularly useful when you need to convert a table into a fo
```suggestion
The **`concat()`** function is used to join the values of a table into a single string, separated by a specified separator. This function is particularly useful when you need to convert a table into a formatted string representation. It allows you to customize the separator between values and optionally specify a range of indices to concatenate. 

```

2023-09-27 21:37 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/concat/concat.md
> +## Syntax
add an empty line after the header

2023-09-27 21:37 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/concat/concat.md
> +```lua
```suggestion
```pseudo

```

2023-09-27 21:37 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/concat/concat.md
> +In this example, we have a table `fruits` containing four elements. We use `table.concat()` to join the elements from index 2 to 3 (inclusive) with a comma and space as the separator. The resulting s
```suggestion
In this example, the table `fruits` contains four elements. `table.concat()` is used to join the elements from index 2 to 3 (inclusive) with a comma and space as the separator. The resulting string is then printed.

```

2023-09-29 00:47 UTC, phil-haywood commented
@caupolicandiaz I think I have everything updated. Let me know if there is anything else. Thanks

2023-09-29 20:06 UTC, caupolicandiaz requested changes
@phil-haywood I added a few additional comments that I had overlooked in my initial review.

2023-09-29 20:06 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/concat/concat.md
> +The **`concat()`** function is used to join the values of a table into a single string, separated by a specified separator. This function is particularly useful when you need to convert a table into
```suggestion
The **`concat()`** function is used to join the values of a table into a single string, separated by a specified separator. This function is particularly valuable when a table needs to be converted into a formatted string representation. The method allows for the use of a custom separator between values and the option to specify a range of indices to concatenate.
```

2023-09-29 20:06 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/concat/concat.md
> +The **`concat()`** function is used to join the values of a table into a single string, separated by a specified separator. This function is particularly useful when you need to convert a table into
docs avoids the use of first and second person pronouns (I, you, we)

2023-09-29 20:06 UTC, caupolicandiaz commented on content/lua/concepts/tables/terms/concat/concat.md
> +```
there should be descriptions for the parameters below the syntax block

2023-10-01 17:59 UTC, phil-haywood commented
@caupolicandiaz I believe I have it now. 😊

2023-10-02 17:51 UTC, caupolicandiaz approved these changes
@phil-haywood I made a couple of direct changes to the parameter section. This is ready for a second review.

2023-10-02 21:38 UTC, phil-haywood commented
@caupolicandiaz thank you

2023-10-21 02:08 UTC, KTom101 requested changes
@phil-haywood I added a few changes to this. You will also have to remove the `yarn.lock` file.

2023-10-21 02:08 UTC, KTom101 commented on content/lua/concepts/tables/terms/concat/concat.md
> +The code will return the following output:
```suggestion
The output is the following:
```

2023-10-24 21:58 UTC, caupolicandiaz commented
@phil-haywood @KTom101 For the sake of moving this along I've gone ahead and made the changes to the entry

2023-10-24 23:37 UTC, phil-haywood commented
@caupolicandiaz  @KTom101 OK, thanks.

2023-10-26 21:06 UTC, KTom101 approved these changes

2023-10-26 21:08 UTC, merged