[Editted] SQL Commands:ORDER BY
Codecademy/docs pull request #3347
Opened 2023-09-27 17:25 UTC by kevuschka

### Description

Closes issue #3346

The PR belongs to the issue #3346
I added some more lines to the existing SQL order-by.md.
My addings include some lines to mention the possibility to ORDER BY (or sort) multiple columns, if they exist in that SQL table.

I am learning with the "Learn Git & Github" course from Codecademy, that's where my motivation comes from.
### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the 
"Description" above).

2023-09-27 17:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3347) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3347) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3347) it.</sub>

2023-09-28 20:13 UTC, SSwiniarski requested changes
@kevuschka I did a first review and left a few comments.

2023-09-28 20:13 UTC, SSwiniarski commented on content/sql/concepts/commands/terms/order-by/order-by.md
> +> _by seperating with a comma_
```suggestion

It's also possible to `ORDER BY` multiple columns by separating them with a comma.

```

2023-09-28 20:13 UTC, SSwiniarski commented on content/sql/concepts/commands/terms/order-by/order-by.md
> +-  assuming **_column_name_1_** and **_column_name_2_** exist in **table_name**
```suggestion

This assumes `column_name_1` and `column_name_2` exist in `table_name`.
```

2023-09-28 20:13 UTC, SSwiniarski commented on content/sql/concepts/commands/terms/order-by/order-by.md
> +
```suggestion
```
Remove blank line.

2023-10-04 11:22 UTC, kevuschka commented
@SSwiniarski I commited your suggestions directly here on github

2023-10-04 11:38 UTC, SSwiniarski approved these changes
@kevuschka Looks good for a second review.

2023-10-05 21:19 UTC, caupolicandiaz approved these changes
@kevuschka @SSwiniarski LGTM

2023-10-06 11:36 UTC, merged