[Term Entry] rfind
Codecademy/docs pull request #3353
Opened 2023-09-28 12:31 UTC by roberanegussie

### Description
I  have added a new tern entry for the string class in python which checks the last occurrence of a substring in index value from a string provided and if the substring is not found it return -1.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-09-28 19:39 UTC, caupolicandiaz requested changes
@roberanegussie I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-09-28 19:39 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rfind/rfind.md
> +Description: 'Finds the starting index of the last occurrence of a specified substring if it is found in an original string and if the substring is not present the method returns -1.'
```suggestion
Description: 'Finds the last occurrence of a specified substring and returns the starting index.'
```

2023-09-28 19:39 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rfind/rfind.md
> +**`.rfind()`** searches an entire string from the `0th` index to the `last` index or searches a part of the string from the `ith` index to `jth` index, where `i < j` and returns the `last` index wher
```suggestion
**`.rfind()`** searches a given string for a substring starting from index `0`,  or alternatively, from the *ith* index to *jth* index (where *i < j*). The method returns the starting index of the last occurrence of the substring.
```

2023-09-28 19:39 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rfind/rfind.md
> +
remove empty line

2023-09-28 19:39 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rfind/rfind.md
> +This method is called on a string `mystr` and returns the last index where the substring `value` is found at by searching the original string `mystr` from the `start` index to the `end` index and if
```suggestion
This method is called on a string `mystr` and returns the last index where the substring `value` is found at by searching the original string `mystr` from the `start` index to the `end` index, and if the substring is not found it returns `-1`.
```

2023-09-28 19:39 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rfind/rfind.md
> +In the following example, `.rfind()` is used to find out if the substring values are found in the original string `mystr`.
```suggestion
In the following example, `.rfind()` is used to search for several substring values in the original string `mystr`.
```

2023-09-28 19:39 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rfind/rfind.md
> +  - 'String'
```suggestion
  - 'Strings'
```

2023-09-29 08:13 UTC, roberanegussie commented
@caupolicandiaz I've made the requested changes please check.

2023-09-29 20:23 UTC, caupolicandiaz approved these changes
@roberanegussie This is ready for a second review.

2023-10-04 06:19 UTC, roberanegussie commented
@caupolicandiaz please merge my PR.

2023-10-04 17:30 UTC, caupolicandiaz commented
> @caupolicandiaz please merge my PR.

This entry will be merged after a second review is completed.

2023-10-06 16:26 UTC, merged