[Term Entry] Python String .rindex() function
Codecademy/docs pull request #3357
Opened 2023-09-30 14:50 UTC by deenovita

### Description

- Created a new term entry Python strings .rindex() function.
- Close issue #3332 

### Type of Change

- Adding a new entry.

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-02 18:12 UTC, caupolicandiaz requested changes
@deenovita I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-10-02 18:12 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rindex/rindex.md
> +  - 'paths/example-path'
```suggestion
  - 'learn-python-3'
  - 'paths/computer-science'
```

2023-10-02 18:12 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rindex/rindex.md
> +**`.rindex()`** is used to locate the highest index of the substring within a string variable. ValueError will raise when the substring cannot be found.
```suggestion
**`.rindex()`** is used to locate the highest index of the substring within a string variable. A `ValueError` will be raised when the substring cannot be found.
```

2023-10-02 18:12 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rindex/rindex.md
> +The syntax of this function can be shown below :
```suggestion
The syntax of the function takes the following formats:
```

2023-10-02 18:12 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rindex/rindex.md
> +
there should be a brief summary explaining each parameter

2023-10-02 18:12 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rindex/rindex.md
> +The following examples implement `.rindex()` and will return the index location of substring :
```suggestion
The following examples implement `.rindex()` and will return the index location of substring:
```

2023-10-02 18:12 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rindex/rindex.md
> +The index of substring m is found on indices 0 and 4. Therefore, index 4 will be returned.
```suggestion
This will result in the following output:

```shell
4
6
```

2023-10-02 18:12 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rindex/rindex.md
> +The index of substring m is found on indices 0 and 4. Therefore, index 4 will be returned.
use a shell block to show the results and delete the output in the comments

2023-10-02 18:12 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rindex/rindex.md
> +This example is runnable and demonstrate instance where `.rindex()` will locate the substring between the certain indices :
```suggestion
This example is runnable and demonstrates an instance where `.rindex()` will locate the substring between the given indices :
```

2023-10-03 09:41 UTC, deenovita commented
@caupolicandiaz I have updated the entry as suggested. Let me know if there is another thing I need to improve. Thank you

2023-10-03 17:40 UTC, caupolicandiaz approved these changes
@deenovita This is ready for a second review.

2023-10-04 11:47 UTC, deenovita commented
> @deenovita This is ready for a second review.

Thank you!

2023-10-06 16:14 UTC, SSwiniarski approved these changes
@deenovita, @caupolicandiaz Looks good to me.

2023-10-06 16:17 UTC, merged

2023-10-06 16:23 UTC, deenovita commented
> @deenovita, @caupolicandiaz Looks good to me.

Thank you!