[Concept Entry] Luau: iterators.md
Codecademy/docs pull request #3418
Opened 2023-10-03 07:14 UTC by noahpgordon

### Description

Added concept **iterators** to Luau. Closes #3208 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-03 20:06 UTC, caupolicandiaz requested changes
@noahpgordon I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-10-03 20:06 UTC, caupolicandiaz commented on content/luau/concepts/iterators/iterators.md
> +Note that the order in which the elements of the table are looped through is not guaranteed when using `pairs()`.
```suggestion
> **Note:** The order in which the elements of the table are looped through is not guaranteed when using `pairs()`.
```

2023-10-03 20:06 UTC, caupolicandiaz commented on content/luau/concepts/iterators/iterators.md
> +Compare the behavior of `ipairs()` when used on an identical table as in the previous example:
```suggestion
Compare the behavior of `ipairs()` when used on the same table as above:
```

2023-10-03 20:06 UTC, caupolicandiaz commented on content/luau/concepts/iterators/iterators.md
> +	print(i)
be sure to use 2 spaces for code indentations not tabs

2023-10-04 01:01 UTC, noahpgordon commented
@caupolicandiaz I've incorporated these edits.

2023-10-04 17:22 UTC, caupolicandiaz approved these changes
@noahpgordon This is ready for a second review.

2023-10-06 16:07 UTC, SSwiniarski approved these changes
@noahpgordon, @caupolicandiaz Looks good to me.

2023-10-06 16:12 UTC, merged