Create atan2 entry for golang
Codecademy/docs pull request #3419
Opened 2023-10-03 08:50 UTC by arisdelacruz

### Description

This is my attempt to create an entry for the atan2 function for golang. Hoping to help others on this. Thanks

### Type of Change

- Adding a new entry

### Checklist

- [ / ] All writings are my own.
- [ / ] My entry follows the Codecademy Docs style guide.
- [ / ] My changes generate no new warnings.
- [ / ] I have performed a self-review of my own writing and code.
- [ / ] I have checked my entry and corrected any misspellings.
- [ / ] I have made corresponding changes to the documentation if needed.
- [ / ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ / ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ / ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-03 19:31 UTC, caupolicandiaz requested changes
@arisdelacruz I've added my initial comments. Please update the entry, and tag me when you have finished making changes. Thanks

2023-10-03 19:31 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/atan2/atan2.md
> +The **`Atan2()`** function returns the arctangent value of the x/y value.
```suggestion
The **`Atan2()`** function returns the arctangent value of the *y/x* value.
```

2023-10-03 19:31 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/atan2/atan2.md
> +- The ratio of the two arguments `(y/x)` is used to calculate the value of the arc tangent.
```suggestion
- The ratio of the two arguments `(y/x)` is used to calculate the value of the arctangent.
```

2023-10-03 19:31 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/atan2/atan2.md
> +## Special Cases
```suggestion
### Special Cases
```

2023-10-03 19:31 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/atan2/atan2.md
> +- Atan2(NaN, x) = NaN
```suggestion
`NAN`:
- *Atan2(y, NaN) = NaN*
- *Atan2(NaN, x) = NaN*
```

2023-10-03 19:31 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/atan2/atan2.md
> +- Atan2(NaN, x) = NaN
Update the others as above

2023-10-03 19:31 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/atan2/atan2.md
> +import  "math"
```suggestion
import (
  "fmt"
  "math"
  )
```

2023-10-03 19:31 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/atan2/atan2.md
> +import  "math"
make sure indentations in the code use 2 spaces not tabs

2023-10-04 05:45 UTC, arisdelacruz commented
@caupolicandiaz 

done, buddy

thanks

2023-10-04 17:29 UTC, caupolicandiaz approved these changes
@arisdelacruz This is ready for a second review.

2023-10-06 15:47 UTC, SSwiniarski approved these changes
@arisdelacruz, @caupolicandiaz Looks good to me.

2023-10-06 16:02 UTC, merged