Update functions.md
Codecademy/docs pull request #3421
Opened 2023-10-03 13:02 UTC by bcsamrudh

Closes #3399 

### Description
Added notes about Function Overloading

### Type of Change

- Updating the documentation

### Checklist

- [x] All writings are my own. 
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings. 
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch. 
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number>" in the "Description" above).

2023-10-03 18:33 UTC, SSwiniarski requested changes
@bcsamrudh I did a first review and left a few comments.

2023-10-03 18:33 UTC, SSwiniarski commented on content/cpp/concepts/functions/functions.md
> +The ability to create <strong>multiple functions</strong> with the <strong>same name</strong> but <strong>different parameters</strong> is called function overloading in C++. It provides a way to <st
```suggestion
The ability to create multiple functions with the same name but different parameters is called function [overloading](https://www.codecademy.com/resources/docs/cpp/overloading) in C++. It provides a way to reuse the same function name in different contexts by accepting different data types and numbers of arguments.
```
This is a Markdown document, please don't use HTML in it.

2023-10-03 18:33 UTC, SSwiniarski commented on content/cpp/concepts/functions/functions.md
> +  cout<<"Output,when add function is called with integer parameters: "<<a+b <<"\n";
```suggestion
  cout << "Output,when add function is called with integer parameters: " << a+b << "\n";
```

2023-10-03 18:33 UTC, SSwiniarski commented on content/cpp/concepts/functions/functions.md
> +  cout <<"Output,when add function is called with string parameters: " <<a+b <<"\n";
```suggestion
  cout << "Output,when add function is called with string parameters: " << a+b << "\n";
```

2023-10-03 18:33 UTC, SSwiniarski commented on content/cpp/concepts/functions/functions.md
> +[Read More about Overloading](https://www.codecademy.com/resources/docs/cpp/overloading)
```suggestion
```
Remove this last line. I moved the link to the first paragraph.

2023-10-04 11:29 UTC, SSwiniarski approved these changes
@bcsamrudh Looks good for a second review.

2023-10-04 20:41 UTC, caupolicandiaz requested changes
@bcsamrudh I've added a few additional comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-10-04 20:41 UTC, caupolicandiaz commented on content/cpp/concepts/functions/functions.md
> +
remove extra empty line

2023-10-04 20:41 UTC, caupolicandiaz commented on content/cpp/concepts/functions/functions.md
> +This will Output:
```suggestion
This will output:
```

2023-10-04 20:41 UTC, caupolicandiaz commented on content/cpp/concepts/functions/functions.md
> +```
```suggestion
```shell
```

2023-10-04 20:41 UTC, caupolicandiaz commented on content/cpp/concepts/functions/functions.md
> +  cout << "Output,when add function is called with integer parameters: " << a+b << "\n";
```suggestion
  cout << "Output, when add function is called with integer parameters: " << a+b << "\n";
```

2023-10-04 20:41 UTC, caupolicandiaz commented on content/cpp/concepts/functions/functions.md
> +  cout << "Output,when add function is called with string parameters: " << a+b << "\n";
```suggestion
  cout << "Output, when add function is called with string parameters: " << a+b << "\n";
```

2023-10-05 01:33 UTC, bcsamrudh commented
@caupolicandiaz Just updated the file as per your suggestion.

2023-10-05 18:57 UTC, caupolicandiaz approved these changes
@bcsamrudh @SSwiniarski LGTM

2023-10-06 11:45 UTC, merged