Add documentation for Lua .asin() method
Codecademy/docs pull request #3423
Opened 2023-10-03 14:17 UTC by Manmit124

### Description

In this pull request, I have created a new documentation entry for the Lua .asin() method. The documentation includes information about the method's syntax, description, parameters, and an example of usage. This addition aims to improve the comprehensibility of the Lua mathematical library documentation and provide users with clear guidance on using the .asin() method effectively in Lua programming.

Please make sure to provide a summary that accurately reflects the purpose and scope of your pull request. This helps reviewers and maintainers quickly understand the nature of your contribution.
### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-03 14:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3423) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3423) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3423) it.</sub>

2023-10-03 19:17 UTC, caupolicandiaz requested changes
@Manmit124 I've made my initial comments. Please update the entry, and tag me when you've finished making changes.

Also, be sure to wait that you are assigned an issue by a maintainer before submitting a PR. Thanks

2023-10-03 19:17 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +title: Lua .asin() Method
the metadata section is incorrect. Please reference a template or one of our existing entries to see the correct formatting and elements
https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md?plain=1

2023-10-03 19:17 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +### Description
```suggestion
```

2023-10-03 19:17 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +### Description
the first content in the body should be the text of the description, we do not use a header at the top

2023-10-03 19:17 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +The `.asin()` method in Lua returns the arcsine (inverse sine) of `x`. The arcsine of `x` is the angle whose sine is `x`. The result is given in radians and is within the range of [-π/2, π/2].
```suggestion
The **`.asin()`** method in Lua returns the arcsine (inverse sine) of `x`. The arcsine of `x` is the angle whose sine is `x`. The result is given in radians and is within the range of *-π/2 : π/2*.
```

2023-10-03 19:17 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +## Syntax
the syntax section should be after the description

2023-10-03 19:17 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +````lua
```suggestion
```pseudo
```

2023-10-03 19:17 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +### Parameters
```suggestion
```

2023-10-03 19:17 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +### Returns
```suggestion
```

2023-10-03 19:17 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +
There should be a brief introduction to the example here

2023-10-03 19:17 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +````
should be only 3 backticks ```

2023-10-04 16:48 UTC, Manmit124 commented
@caupolicandiaz i updated  my code check it 
and sry i'm  beginner

2023-10-05 04:45 UTC, Manmit124 commented
thanks for metadata 
can you suggest to me which entry is missing

2023-10-05 19:13 UTC, caupolicandiaz commented
> thanks for metadata
> can you suggest to me which entry is missing

Almost the entire entry is missing. Please review the link below and compare to your entry. And add the missing areas.

https://github.com/Codecademy/docs/pull/3150/files

2023-10-24 22:01 UTC, caupolicandiaz commented
@Manmit124 I'm closing this due to lack of progress

2023-10-24 22:01 UTC, closed without merging