Python strings .rstrip(), Closes #3363
Codecademy/docs pull request #3429
Opened 2023-10-03 20:24 UTC by reganmarie

### Description

- Closes issue #3363 
- Created rstrip.md on filepath docs/content/python/concepts/strings/terms/rstrip/rstrip.md
- Added Title, Description, Subjects, Tags, and Catalog Content
Added description, syntax, example, and codebyte example
- Ran through 3 online plagiarism checkers to ensure 100% unique wording and description, passed with 100%
- Followed content and style guidelines
-Checked for spelling and grammar errors
- Read for clarity and readability

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-03 20:47 UTC, caupolicandiaz requested changes
@reganmarie I've added my initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-10-03 20:47 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rstrip/rstrip.md
> +The second call specifies the characters to remove from the end of the string.
```suggestion
In the following example, the `.rstrip()` method is called twice. The first call does not specify characters to remove, so whitespace is removed. And the second call specifies the characters `"se"` to be removed from the end of the string.
```

2023-10-03 20:47 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rstrip/rstrip.md
> +
there should be an introductory sentence here

2023-10-03 20:47 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/rstrip/rstrip.md
> +``
```suggestion
```

2023-10-04 00:37 UTC, reganmarie commented
@caupolicandiaz Updated with the suggested changes! 
- Condensed the example introduction in line 28 to the suggested change.
- Added an introductory sentence to the Codebyte example:
In the following example, the `.rstrip()` method is called twice. The first call does not specify characters to remove, so whitespace is removed. The second call specifies the characters `"sca"` to be removed from the end of the string.

2023-10-04 17:09 UTC, caupolicandiaz approved these changes
@reganmarie This is ready for a second review.

2023-10-04 17:20 UTC, reganmarie commented
Thank you @caupolicandiaz! 😊

2023-10-07 15:35 UTC, yangc95 approved these changes

2023-10-07 15:41 UTC, merged