Update syntax for second parameter in split() method
Codecademy/docs pull request #3441
Opened 2023-10-04 19:40 UTC by christina-ml

### Description

Closes #3402 

This edit is for the Python Strings: [Split](https://www.codecademy.com/resources/docs/python/strings/split) method located under the file path docs/content/python/concepts/strings/terms/split/split.md

Edit the syntax section to clarify that the second parameter in the split() method is the maximum number of splits. Also include the default when a number isn't given.

My changes:
- Edit syntax section to clarify that the second parameter in the split() method is the maximum number of splits
- Rename second parameter from `number_of_items` to `maxsplit` for clarification as to what this parameter does. It is not a count for the number of items, instead it sets a maximum number of times the string can be split.
- Explain what the default value is if second parameter is not specified, or if the second parameter has a value of `-1`

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-04 19:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3441) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3441) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3441) it.</sub>

2023-10-04 20:56 UTC, caupolicandiaz requested changes
@christina-ml Just a couple of edits. Please update the entry, and tag me when you've finished the changes. Thanks

2023-10-04 20:56 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/split/split.md
> +- A maximum `maxsplit` specifying at most the number of splits that can occur, and the remainder of the string is returned as the final element of the list.
```suggestion
- The value `maxsplit` specifies the total number of splits that can occur, and the remainder of the string is returned as the final element of the list. The default value is `-1`, which means an unlimited number of splits.
```

2023-10-04 20:56 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/split/split.md
> +If the `maxsplit` parameter is not specified, or has a value of `-1`, the default value is `-1`. This means there is no maximum limit to the number of splits, and all possible splits are made.
```suggestion
```

2023-10-04 21:18 UTC, christina-ml commented
@caupolicandiaz I updated the entry with the suggested changes.

2023-10-05 18:56 UTC, caupolicandiaz approved these changes
@christina-ml This is ready for a second review.

2023-10-06 15:38 UTC, SSwiniarski approved these changes
@christina-ml, @caupolicandiaz looks good to me.

2023-10-06 15:43 UTC, merged