Docs
Codecademy/docs pull request #3446
Opened 2023-10-05 06:52 UTC by ATREAY

### Description

implemented the Lua Coroutines .close() function which pertains to the issue #3378(Lua Coroutines .close()).

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-05 16:40 UTC, SSwiniarski requested changes
@ATREAY I did a first review and had one comment.

2023-10-05 16:40 UTC, SSwiniarski commented on content/lua/concepts/coroutines/terms/close/close.md
> +In this example, we use the `.close()` function to terminate a running coroutine.
```suggestion
This example uses the `.close()` function to terminate a running coroutine.
```
We avoid first- and second-person pronouns in Docs.

2023-10-05 16:50 UTC, ATREAY commented
Hey @SSwiniarski, I have made the requested changes.

2023-10-05 16:57 UTC, SSwiniarski approved these changes
@ATREAY Looks good for a second review.

2023-10-05 19:50 UTC, caupolicandiaz requested changes
@ATREAY I've added my comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-10-05 19:50 UTC, caupolicandiaz commented on content/lua/concepts/coroutines/terms/close/close.md
> +The `.close()` function in Lua's coroutine module is employed to gracefully terminate a coroutine and release its associated resources.
```suggestion
The **`close()`** function in Lua's coroutine module is employed to gracefully terminate a coroutine and release its associated resources.
```

2023-10-05 19:50 UTC, caupolicandiaz commented on content/lua/concepts/coroutines/terms/close/close.md
> +It yields a boolean value, signifying `true` if the coroutine has been successfully closed; otherwise, it returns `false`.
```suggestion
It yields a boolean value, `true`, if the coroutine has been successfully closed, otherwise it returns `false`.
```

2023-10-05 19:50 UTC, caupolicandiaz commented on content/lua/concepts/coroutines/terms/close/close.md
> +Title: '.close()'
```suggestion
Title: 'close()'
```

2023-10-05 19:50 UTC, caupolicandiaz commented on content/lua/concepts/coroutines/terms/close/close.md
> +- Always check the return values of `coroutine.close()` to handle potential errors gracefully.
```suggestion
- Always check the return values of `coroutine.close()` to handle potential errors appropriately.
```

2023-10-05 19:50 UTC, caupolicandiaz commented on content/lua/concepts/coroutines/terms/close/close.md
> +This example uses the `.close()` function to terminate a running coroutine.
```suggestion
This example uses the `close()` function to terminate a running coroutine.
```

2023-10-05 19:50 UTC, caupolicandiaz commented on content/lua/concepts/coroutines/terms/close/close.md
> +In the codebyte example below we create a coroutine using `coroutine.create()`, start it with `coroutine.resume()`, and then close it with `coroutine.close()`.
```suggestion
This example is runnable and creates a coroutine using `coroutine.create()`, starts it with `coroutine.resume()`, and then closes it with `coroutine.close()`.
```

2023-10-06 03:53 UTC, ATREAY commented
hey @caupolicandiaz, I've made the necessary updates. Could you please take a look when you have a moment?

2023-10-06 19:54 UTC, caupolicandiaz approved these changes
@ATREAY @SSwiniarski I just switched the codebyte to a standard example because Lua isn't currently supported by the Codecademy compiler. Looks good to merge

2023-10-07 14:54 UTC, merged