Add .zfill() Method Entry in 'Terms' Section (#3367)
Codecademy/docs pull request #3447
Opened 2023-10-05 10:58 UTC by KimFarida

### Description
Added a new entry for the '.zfill()' method in the 'Terms' section. Created a new markdown file named 'zfill.md' under the zfill folder with usage examples and explanations for the method.
This change closes issue #3367.

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR

2023-10-05 10:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3447) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3447) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3447) it.</sub>

2023-10-05 16:50 UTC, SSwiniarski requested changes
@KimFarida I did a first review and left a few comments.

2023-10-05 16:50 UTC, SSwiniarski commented on content/python/concepts/strings/terms/zfill/zfill.md
> +Description: 'Takes an int and returns a copy of the string with a number of zeros preppended as a suffix , i.e "no. of zeros" + string.'
```suggestion
Description: 'Takes an int and returns a copy of the string with a number of zeros prepended as a prefix, i.e "no. of zeros" + string.'
```

2023-10-05 16:50 UTC, SSwiniarski commented on content/python/concepts/strings/terms/zfill/zfill.md
> +If no argument is passed into the method. A type error is thrown
```suggestion
> **Note:** The `.zfill()` method does not change the string it is used on.
```
We don't need the line about the error, just note above that the parameter is required.

2023-10-05 16:50 UTC, SSwiniarski commented on content/python/concepts/strings/terms/zfill/zfill.md
> +```
````suggestion
## Syntax

```pseudo
result = string.zfill(arg)
```
````
Also add a sentence after the code block explaining what `result` and `arg` are.

2023-10-05 16:50 UTC, SSwiniarski commented on content/python/concepts/strings/terms/zfill/zfill.md
> +The following example shows how `.zfill()` returns a copy of that string with leading zeros.
```suggestion
## Example 1

The following example shows how `.zfill()` returns a copy of that string with leading zeros: 
```

2023-10-05 16:50 UTC, SSwiniarski commented on content/python/concepts/strings/terms/zfill/zfill.md
> +The following example shows how `.zfill()` method helps ensure a specific length for a string, adding zeros to the beginning if the string is shorter than the desired length.
```suggestion
## Codebyte Example

The following example shows how `.zfill()` method helps ensure a specific length for a string, adding zeros to the beginning if the string is shorter than the desired length.
```

2023-10-05 16:50 UTC, SSwiniarski commented on content/python/concepts/strings/terms/zfill/zfill.md
> +## Example
This section is really not necessary. All functions with required parameters will throw an error if the parameter is missing. It isn't something specific to `.zfill()`

2023-10-08 08:21 UTC, Spikke88 approved these changes

2023-10-24 22:04 UTC, caupolicandiaz commented
@KimFarida There hasn't been any activity on this entry, are you still available to finish this submission?

2023-10-25 08:47 UTC, KimFarida commented
> @KimFarida There hasn't been any activity on this entry, are you still available to finish this submission?

Yes I am, sorry it took so long. 
had a few personal I had to handle so wasn't available for a while. I'm okay now
I'll put in the submission before the week ends

2023-10-26 17:09 UTC, KimFarida commented
> @KimFarida There hasn't been any activity on this entry, are you still available to finish this submission?

I have made the required changes

2023-11-06 17:52 UTC, SSwiniarski approved these changes
@KimFarida looks good for a second review. (Sorry for the delay)

2023-11-06 20:03 UTC, caupolicandiaz requested changes
@KimFarida I've added my comments. Please update the entry, and tag me when the changes are complete. Thanks

2023-11-06 20:03 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/zfill/zfill.md
> +# parameter is less than/ equal to string length, output will be the same string.
```suggestion
# If the argument is less than/equal to string length, output will be the same string.
```

2023-11-06 20:03 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/zfill/zfill.md
> +It creates a new string with leading zeros based on the specified integer argument, represented by `arg`. The modified string is stored in the variable `result`.
```suggestion
It creates a new string with leading zeros based on the specified integer argument, represented by `total_length`. The modified string is stored in the variable `result`.
```

2023-11-06 20:03 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/zfill/zfill.md
> +```
There should be an empty line after the code block

2023-11-06 20:03 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/zfill/zfill.md
> +
```suggestion
```

2023-11-19 22:04 UTC, caupolicandiaz approved these changes
@KimFarida @SSwiniarski I've gone ahead and incorporated the edits I suggested.

2023-11-19 22:05 UTC, merged