Issue 3409 animation fill mode add media
Codecademy/docs pull request #3448
Opened 2023-10-05 15:28 UTC by DustyDogCodex

### Description

Closes issue #3409 

Added gifs showcasing animation-fill-mode: forwards and animation-fill-mode: backwards to media folder.
Updated animation-fill-mode.md with these gifs.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-05 15:29 UTC, DustyDogCodex commented
hi @KTom101 !

Hope you are doing well! I have added gifs showcasing the appropriate animations and updated the animation-fill-mode.md file with those gifs as well. Please let me know if I need to change anything here.

Thanks!

2023-10-05 16:55 UTC, SSwiniarski requested changes
@DustyDogCodex I did a first review and only had one comment.

2023-10-05 16:55 UTC, SSwiniarski commented on content/css/concepts/animations/terms/animation-fill-mode/animation-fill-mode.md
Looks good, but you need to update the links as specified in the [file hosting section of the style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#file-hosting). This is so the images will show when the page is published to the Docs site.

2023-10-05 18:51 UTC, DustyDogCodex commented
Hi @SSwiniarski !

Hope you are having a good day of coding today! I have made your recommended changes to the gif links. They should now be in line with the style guide. Please review them when you have a moment and let me know if this PR needs anymore changes.

Thanks!

2023-10-06 11:27 UTC, SSwiniarski approved these changes
@DustyDogCodex Looks good for a second review.

2023-10-25 21:56 UTC, caupolicandiaz approved these changes
@DustyDogCodex @SSwiniarski LGTM

2023-10-25 21:58 UTC, merged