[Term Entry] Lua Math .ceil()
Codecademy/docs pull request #3449
Opened 2023-10-05 19:08 UTC by Fejiro001

### Description

- Added the Math.ceil() term for Lua
- Closes Issue #3389 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-05 19:27 UTC, caupolicandiaz requested changes
@Fejiro001 I've completed my initial review. Please update the entry, and tag me when you've finished making edits. Thanks

2023-10-05 19:27 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/ceil/ceil.md
> +The **`.ceil()`** function in Lua's Math library rounds up a given number to the smallest integer that is greater than or equal to th given number. The given number can be a positive or negative numb
```suggestion
The **`.ceil()`** function in Lua's math library rounds up a given number to the smallest integer that is greater than or equal to the passed value. The given number can be a positive or negative number.
```

2023-10-05 19:27 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/ceil/ceil.md
> +```lua
```suggestion
```pseudo
```

2023-10-05 19:27 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/ceil/ceil.md
> +- `x`: A number that is round up to the smallest integer.
```suggestion
- `x`: The number to be rounded.
```

2023-10-05 19:27 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/ceil/ceil.md
> +
There should be a line here like -
"This will result in the following output:"

2023-10-05 19:27 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/ceil/ceil.md
> +In the example above, `math.ceil()` is used to round `num1` (14.4) up to the smallest integer, resulting in `15`. Similarly, `math.ceil()` is used to round `num2` (-22.5) up to the smallest integer,
```suggestion
In this example, `math.ceil()` is used to round a pair of values.
```

2023-10-05 19:27 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/ceil/ceil.md
> +In the example above, `math.ceil()` is used to round `num1` (14.4) up to the smallest integer, resulting in `15`. Similarly, `math.ceil()` is used to round `num2` (-22.5) up to the smallest integer,
move this sentence above the Lua code block

2023-10-05 19:36 UTC, Fejiro001 commented
@caupolicandiaz Ok, thank you. I will make the changes now

2023-10-05 19:48 UTC, Fejiro001 commented
@caupolicandiaz I have finished making the edits

2023-10-06 19:29 UTC, caupolicandiaz approved these changes
@Fejiro001 This is ready for a second review.

2023-10-06 20:51 UTC, Fejiro001 commented
@caupolicandiaz  Ok. I just updated my branch since it was behind on commits

2023-10-07 04:42 UTC, Fejiro001 commented
@caupolicandiaz can I start on the other issue I have been assigned to, or should I wait for this to be merged

2023-10-07 19:07 UTC, caupolicandiaz commented
> @caupolicandiaz can I start on the other issue I have been assigned to, or should I wait for this to be merged

Yes, you can work on your other assignments just make sure to keep your work separate. The other PR should not include changes from this entry, and this PR should not include changes from new efforts.

2023-10-07 20:15 UTC, Fejiro001 commented
> > @caupolicandiaz can I start on the other issue I have been assigned to, or should I wait for this to be merged
> 
> Yes, you can work on your other assignments just make sure to keep your work separate. The other PR should not include changes from this entry, and this PR should not include changes from new efforts.

Ok thank you

2023-10-15 18:42 UTC, Fejiro001 commented
@SSwiniarski is my pull request ok for merging?

2023-10-15 19:03 UTC, SSwiniarski commented on content/lua/concepts/mathematical-library/terms/ceil/ceil.md
> +Description: 'Returns the smallest integer greater than or equal to x.'
```suggestion
Description: 'Returns the smallest integer greater than or equal to a given value.'
```

2023-10-15 19:15 UTC, Fejiro001 commented
@SSwiniarski ok will implement it now

2023-10-15 19:19 UTC, SSwiniarski approved these changes
@Fejiro001 Looks good.

2023-10-15 19:22 UTC, merged