Add semantic html content
Codecademy/docs pull request #3450
Opened 2023-10-05 21:59 UTC by narcissus123

### Description

- Added new content, codes and images to the semantic html document (docs/content/html/concepts/semantic-html/semantic-html.md).
- Closes #<issue #3286>

### Type of Change

- Editing an existing entry (fixing a type, bug, issues, etc.) 

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-05 21:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3450) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3450) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3450) it.</sub>

2023-10-07 15:30 UTC, SSwiniarski requested changes
@narcissus123 I did a first review and while I admire your enthusiasm, you've gone far beyond the issue, and have written a full-blown tutorial. Doc's isn't the place for tutorials like this. The entries are meant to be short overviews of the topic that are easily digestible. In addition, the CSS segments aren't germane to the subject of the entry. To accept this, the images (what the issue was asking for) should relate to semantic HTML, and the rest of this needs to be boiled down to a few paragraphs (three or four at most.) 

Also note we avoid first- and second-person pronouns in Docs.

2023-10-08 04:05 UTC, narcissus123 commented
@ SSwiniarski thank you, I will work on the semantic HTML document and ensure it follows the guidelines you mentioned.

2023-10-09 04:13 UTC, heena-patel31 commented
hi @SSwiniarski  Can I please make these changes?

2023-10-09 11:13 UTC, SSwiniarski commented
@heena-patel31, this is @narcissus123's PR, it's their job to edit it. You only make edits to your own PR.

2023-10-10 14:46 UTC, narcissus123 commented
Hi @SSwiniarski, please review the latest changes I've made based on your feedback.

2023-10-10 16:42 UTC, SSwiniarski commented
@narcissus123 The PR is better, but I am going to remove the issue link and unassign you from the issue as this does not actually address the original issue (adding media to the Semantic HTML entry). We'll be reviewing this PR on its own without regard to the original issue.

2023-10-10 16:48 UTC, SSwiniarski requested changes
@narcissus123 I went through your edits and left a few comments.

2023-10-10 16:48 UTC, SSwiniarski commented on content/html/concepts/semantic-html/semantic-html.md
> +## Semantic HTML Best Practices: Mastering the Art
```suggestion
## Semantic HTML Best Practices
```

2023-10-10 16:48 UTC, SSwiniarski commented on content/html/concepts/semantic-html/semantic-html.md
> +- Use Semantics for Meaning: Choose semantic HTML Tags wisely: It is important to choose tags that accurately convey the content's meaning and purpose. Avoid common mistakes like using `<article>` an
```suggestion
Use Semantics for Meaning: Choose semantic HTML Tags wisely. It is important to choose tags that accurately convey the content's meaning and purpose. Avoid common mistakes like using `<article>` and `<section>` tags interchangeably. In the following example, using `<article>` for each subsection correctly represents self-contained content (news articles), while `<section>` encapsulates the broader category 'Technology News,' aligning with their intended semantic purposes.
```

2023-10-10 16:48 UTC, SSwiniarski commented on content/html/concepts/semantic-html/semantic-html.md
> +## Drawbacks of Using Semantic HTML: Navigating Challenges
```suggestion
## Drawbacks of Using Semantic HTML
```

2023-10-11 01:53 UTC, narcissus123 commented
Thank you, [SSwiniarski](https://github.com/SSwiniarski), for your review and valuable feedback. I have carefully made all the changes you suggested. Additionally, I've introduced two images to enhance the document under the "Semantic Tags" and "Use Semantics for Meaning" sections. If you have any further suggestions or if these additions are not in line with what you were looking for, please let me know, and I'll make the necessary adjustments.

2023-10-11 15:46 UTC, SSwiniarski requested changes
@narcissus123 Some more comments. I reassigned the issue as this PR now addresses it.

2023-10-11 15:46 UTC, SSwiniarski commented on content/html/concepts/semantic-html/semantic-html.md
> +![Semantic Tags](https://raw.githubusercontent.com/Codecademy/docs/main/media/<semantic-tags>.<png>)
```suggestion
![Semantic Tags](https://raw.githubusercontent.com/Codecademy/docs/main/media/semantic-tags.png)
```
Ad a sentence before this image describing what it shows.

2023-10-11 15:46 UTC, SSwiniarski commented on content/html/concepts/semantic-html/semantic-html.md
> +Use Semantics for Meaning: Choose semantic HTML Tags wisely: It is important to choose tags that accurately convey the content's meaning and purpose. Avoid common mistakes like using `<article>` and
```suggestion
Use Semantics for Meaning: Choose semantic HTML Tags wisely. It is important to choose tags that accurately convey the content's meaning and purpose. Avoid common mistakes like using `<article>` and `<section>` tags interchangeably. In the following example, using `<article>` for each subsection correctly represents self-contained content (news articles), while `<section>` encapsulates the broader category 'Technology News,' aligning with their intended semantic purposes.
```

2023-10-11 15:46 UTC, SSwiniarski commented on content/html/concepts/semantic-html/semantic-html.md
> +Proper Nesting: Structure with intent. Proper nesting is a fundamental aspect of semantic HTML. So, it is crucial to structure content logically to reflect hierarchical relationships between semantic
```suggestion
Proper Nesting: Proper nesting is a fundamental aspect of semantic HTML. So, it is crucial to structure content logically to reflect hierarchical relationships between semantic elements. For instance, avoid the common mistake of placing the `<aside>` element directly within the main content; `<aside>` is intended to be positioned to the side, separate from the primary content.
```

2023-10-11 15:46 UTC, SSwiniarski commented on content/html/concepts/semantic-html/semantic-html.md
> +![Semantic Tag Visualization for Technology News](https://raw.githubusercontent.com/Codecademy/docs/main/media/<use-semantics-for-meaning>.<png>)
```suggestion
![Semantic Tag Visualization for Technology News](https://raw.githubusercontent.com/Codecademy/docs/main/media/use-semantics-for-meaning.png)
```

2023-10-12 23:36 UTC, narcissus123 commented
Hi [@SSwiniarski](https://github.com/SSwiniarski), Thank you for your feedback and for reassigning the issue to this pull request. I've made the changes based on your suggestions. Please let me know if there are any further adjustments needed.

2023-10-13 11:54 UTC, SSwiniarski reviewed
@narcissus123 looks good for a second review.

2023-10-13 15:22 UTC, narcissus123 commented
[@SSwiniarski](https://github.com/SSwiniarski), I removed the trailing space at line 52 to remove the error message provided in the "ci (lint:md)" check. But I am not sure how I can remove the other one.

2023-10-13 19:51 UTC, caupolicandiaz requested changes
@narcissus123 I've added a few comments. Please update the entry, and tag me when you've finished making the changes. Thanks

2023-10-13 19:51 UTC, caupolicandiaz commented on content/html/concepts/semantic-html/semantic-html.md
> +Testing and validating for browser compatibility is essential in web development to ensure a consistent user experience. Stick to well-supported modern semantic HTML tags, checking their compatibilit
```suggestion
Testing and validating for browser compatibility is essential in web development to ensure a consistent user experience. It is best practice to employ well-supported modern semantic HTML tags, and confirming their compatibility using resources like [Can I use](https://caniuse.com/). Additionally, validation tools like the [W3C Markup Validation Service](https://validator.w3.org/) are valuable for maintaining code quality, identifying errors, and ensuring compliance with web standards. These practices can aid in supporting compatibility across various browsers and devices.
```

2023-10-13 19:51 UTC, caupolicandiaz commented on content/html/concepts/semantic-html/semantic-html.md
> +Use Semantics for Meaning: Choose semantic HTML Tags wisely. It is important to choose tags that accurately convey the content's meaning and purpose. Avoid common mistakes like using `<article>` and
```suggestion
It is important to choose tags that accurately convey the content's meaning and purpose. Avoid common mistakes like using `<article>` and `<section>` tags interchangeably. In the following example, using `<article>` for each subsection correctly represents self-contained content (news articles), while `<section>` encapsulates the broader category 'Technology News,' aligning with their intended semantic purposes.
```

2023-10-13 19:51 UTC, caupolicandiaz commented on content/html/concepts/semantic-html/semantic-html.md
> +Proper Nesting: Proper nesting is a fundamental aspect of semantic HTML. So, it is crucial to structure content logically to reflect hierarchical relationships between semantic elements. For instance
```suggestion
Proper nesting is a fundamental aspect of semantic HTML. So, it is crucial to structure content logically to reflect hierarchical relationships between semantic elements. For instance, avoid the common mistake of placing the `<aside>` element directly within the main content. The `<aside>` tag is intended for content that is to be positioned to the side, or flanking, separate from the primary content.
```

2023-10-13 20:40 UTC, narcissus123 commented
Hi [@caupolicandiaz](https://github.com/caupolicandiaz), I updated the entry. Please let me know if there are any further adjustments needed. Thank you.

2023-10-14 19:42 UTC, caupolicandiaz approved these changes
@narcissus123 @SSwiniarski This is ready to merge

2023-10-15 15:17 UTC, SSwiniarski approved these changes

2023-10-15 15:18 UTC, merged