Branch 1
Codecademy/docs pull request #3454
Opened 2023-10-06 16:44 UTC by bharathgaddam1712

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-06 16:46 UTC, bharathgaddam1712 commented
![Screenshot 2023-10-06 220516](https://github.com/Codecademy/docs/assets/134089638/b03b8c1a-a4b5-4c16-bea0-798b2c6fb0f4)

2023-10-06 16:55 UTC, bharathgaddam1712 commented
![image](https://github.com/Codecademy/docs/assets/134089638/b783ef14-460a-4bda-aed6-4230f9b00ce2)

2023-10-06 16:56 UTC, bharathgaddam1712 commented
All have checked and verified all the checklists.

2023-10-06 19:12 UTC, bharathgaddam1712 commented
please add hactoberfest tag

2023-10-07 15:17 UTC, SSwiniarski requested changes
@bharathgaddam1712 This looks good except for the file copied from a prior PR.

2023-10-07 15:17 UTC, SSwiniarski commented on content/rust/concepts/structs/structs.md
You appear to have created this branch off of a prior PR. You should remove this file from this PR to avoid a conflict.

2023-10-07 15:34 UTC, bharathgaddam1712 commented
Created a new PR from the branch named : rust_structs-1

2023-10-07 15:40 UTC, bharathgaddam1712 commented
Updated branch-1 . Please review it now.

2023-10-08 15:51 UTC, SSwiniarski approved these changes
@bharathgaddam1712 Looks good for a second review.

2023-10-09 21:08 UTC, caupolicandiaz approved these changes
@bharathgaddam1712 @SSwiniarski I just made a few direct edits to update some of the formatting and punctuation. Looks good to merge

2023-10-10 16:34 UTC, merged