[Term Entry] Lua Math .fmod()
Codecademy/docs pull request #3459
Opened 2023-10-07 10:03 UTC by noahpgordon

### Description

Add term **fmod.md** to Lua Math. Closes #3394 .

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-07 19:55 UTC, caupolicandiaz requested changes
@noahpgordon I've added my initial comments. Please update the entry, and tag me when you've completed the changes. Thanks

2023-10-07 19:55 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/fmod/fmod.md
> +Title: '.fmod()'
```suggestion
Title: 'fmod()'
```

2023-10-07 19:55 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/fmod/fmod.md
> +Description: 'Returns the remainder of the quotient of two parameters.'
```suggestion
Description: 'Returns the remainder of the quotient of two arguments.'
```

2023-10-07 19:55 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/fmod/fmod.md
> +The method **`.fmod()`** takes two numbers as parameters and returns the remainder of the first number divided by the second number.
```suggestion
The method **`fmod()`** takes two numbers and returns the remainder of the first number divided by the second number.
```

2023-10-07 19:55 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/fmod/fmod.md
> +The syntax of `.fmod()` is as follows:
```suggestion
The syntax of `fmod()` is as follows:
```

2023-10-07 19:55 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/fmod/fmod.md
> +Where `num1` names the number to be divided by `num2`.
```suggestion
Where `num1` is the value to be divided by `num2`.
```

2023-10-07 19:55 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/fmod/fmod.md
> +The following examples illustrate the behavior of `.fmod()`:
```suggestion
The following examples illustrate the behavior of `fmod()`:
```

2023-10-09 03:39 UTC, noahpgordon commented
@caupolicandiaz I've made the above edits.

2023-10-09 17:21 UTC, caupolicandiaz approved these changes
@noahpgordon This is ready for a second review.

2023-10-26 16:28 UTC, SSwiniarski approved these changes
@noahpgordon Looks good.

2023-10-26 16:34 UTC, merged