Add Lua and fix typos
Codecademy/docs pull request #3460
Opened 2023-10-07 10:59 UTC by cslylla

### Description

- Update documentation/style-guide.md file to include Lua as a supported language and fix typos.
- Closes #3453 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-08 16:22 UTC, SSwiniarski requested changes
@cslylla I did a first review and left some comments.

2023-10-08 16:22 UTC, SSwiniarski commented on documentation/style-guide.md
> +- Do not include a title header automatically provided by the metadata.
```suggestion
- Do not include a title header. It is automatically provided by the metadata.
```

2023-10-08 16:22 UTC, SSwiniarski commented on documentation/style-guide.md
> +- Images' `src` attribute should be linked to the URL: "https://raw.githubusercontent.com/Codecademy/docs/main/media/" followed by the image name.
```suggestion
- Images should be linked to the URL: "https://raw.githubusercontent.com/Codecademy/docs/main/media/" followed by the image name.
```
These are Markdown files, not HTML.

2023-10-09 11:28 UTC, SSwiniarski approved these changes
@cslylla Looks good for a second review.

2023-10-09 16:36 UTC, yangc95 approved these changes

2023-10-09 16:38 UTC, merged