Concept entry luau string
Codecademy/docs pull request #3464
Opened 2023-10-07 18:08 UTC by cslylla

### Description

- Added new concept to Luau: Strings
- Closes: #3210 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-07 22:07 UTC, caupolicandiaz requested changes
@cslylla I've added my comments. Please update the entry, and tag me when you've finished making changes.

2023-10-07 22:07 UTC, caupolicandiaz commented on content/luau/concepts/strings/strings.md
> +print(capitalized)
```suggestion
print(string.upper(name))
```

2023-10-08 10:59 UTC, cslylla commented
@caupolicandiaz I updated the entry.

2023-10-09 17:15 UTC, caupolicandiaz approved these changes
@cslylla Looks good. This is ready for a second review

2023-10-27 01:50 UTC, KTom101 approved these changes
@cslylla Looks good to merge as is. Thanks for your patience.

2023-10-27 01:50 UTC, merged