[Edit] Add notes about overloading for C++ Classes
Codecademy/docs pull request #3476
Opened 2023-10-09 08:55 UTC by krushnarout

### Description

Added notes about overloading and one example

Closes #3398 

### Type of Change

- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-09 19:36 UTC, caupolicandiaz requested changes
@krushnarout Just added a couple of comments. Please update the entry, and tag me when you've completed the changes. Thanks

2023-10-09 19:36 UTC, caupolicandiaz commented on content/cpp/concepts/classes/classes.md
> +The method of creating operators that work differently with custom data types is called operator [overloading](https://www.codecademy.com/resources/docs/cpp/overloading) in C++. This enables the user
```suggestion
Redefining operators to work differently with custom data types is called operator [overloading](https://www.codecademy.com/resources/docs/cpp/overloading) in C++. This enables the user to use these operators with objects of their own classes.
```

2023-10-09 19:36 UTC, caupolicandiaz commented on content/cpp/concepts/classes/classes.md
> +```cpp
update code to use 2 spaces for indentation instead of tabs

2023-10-10 10:19 UTC, krushnarout commented
@caupolicandiaz I updated the notes with the suggested changes. Please review and let me know if any further changes are needed. Thanks!

2023-10-11 17:12 UTC, caupolicandiaz approved these changes
@krushnarout This is ready for a second review.

2023-10-20 21:37 UTC, KTom101 approved these changes
@krushnarout I added one change directly here: [3fe31cd](https://github.com/Codecademy/docs/pull/3476/commits/3fe31cd89edbe819353ae1fe28c89c4913af2575). Looks good to merge. 👍

2023-10-20 21:39 UTC, merged

2023-10-21 02:30 UTC, krushnarout commented
@KTom101 Thank you