[Edit] HTML Add Media: style #3336
Codecademy/docs pull request #3477
Opened 2023-10-09 08:55 UTC by kkkeevvvin

### Description

In the `style` page, it only mention that it's better using external CSS style sheet. But, I think it also important to mention how-to.

### Type of Change

- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-09 08:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3477) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3477) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3477) it.</sub>

2023-10-09 15:59 UTC, SSwiniarski commented
@kkkeevvvin you titled this PR as if it was dealing with an existing issue, but it doesn't actually have anything to do with that issue, so I changed the name to avoid further confusion.

2023-10-09 16:01 UTC, SSwiniarski requested changes
@kkkeevvvin I did a first review and left a comment.

2023-10-09 16:01 UTC, SSwiniarski commented on content/html/concepts/attributes/terms/style/style.md
> +> The method for using external CSS style sheet can be seen at [`<link>`](https://www.codecademy.com/resources/docs/html/elements/link).
```suggestion
> The method for using an external CSS style sheet can be seen at [`<link>`](https://www.codecademy.com/resources/docs/html/elements/link).
```

2023-10-24 20:04 UTC, caupolicandiaz approved these changes
@kkkeevvvin @SSwiniarski Just updated the language in the note to condense it a bit

2023-10-24 20:05 UTC, merged