[Term Entry] Go Math Functions RoundToEven() #3223
Codecademy/docs pull request #3480
Opened 2023-10-09 22:11 UTC by alinasir85

### Description

- Added the RoundToEven term for Go
- Closes Issue #3223 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-09 22:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3480) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3480) before we can accept your contribution.<br/><hr/>**Ali** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3480) it.</sub>

2023-10-09 22:37 UTC, caupolicandiaz requested changes
@alinasir85 I've added my initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-10-09 22:37 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/roundtoeven/roundtoeven.md
> +In this Go code example, we have a simple program that rounds a float value to the nearest even integer, using the `RoundToEven()` function from the `math` package.
```suggestion
This Go code example demonstrates a basic implementations of the `RoundToEven()` function.
```

2023-10-09 22:37 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/roundtoeven/roundtoeven.md
> +fmt.Printf("Rounded %v to the nearest even integer: %v\n", x, rounded)
```suggestion
fmt.Printf("%v rounded to the nearest even integer yields: %v\n", x, rounded)
```

2023-10-09 22:37 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/roundtoeven/roundtoeven.md
> +Rounded 3.5 to the nearest even integer: 4
update to match edits above

2023-10-09 22:37 UTC, caupolicandiaz commented on content/go/concepts/math-functions/terms/roundtoeven/roundtoeven.md
> +
remove the empty lines at the top and bottom of the code block

2023-10-09 22:39 UTC, caupolicandiaz commented
@alinasir85 In the future please wait that a maintainer assigns the issue to you before submitting a PR

2023-10-09 22:49 UTC, alinasir85 commented
> @alinasir85 In the future please wait that a maintainer assigns the issue to you before submitting a PR

ok got it

2023-10-09 22:50 UTC, alinasir85 commented
> @alinasir85 I've added my initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

@caupolicandiaz , suggested changes pushed

2023-10-11 16:49 UTC, SSwiniarski approved these changes
@alinasir85 @caupolicandiaz Looks good.

2023-10-11 16:51 UTC, merged