Closes [Term Entry] PHP String Functions chr() #3220
Codecademy/docs pull request #3481
Opened 2023-10-09 22:19 UTC by alinasir85

### Description

- Added chr() term entry for php
- Closes issue #3220

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-09 22:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3481) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3481) before we can accept your contribution.<br/><hr/>**Ali** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3481) it.</sub>

2023-10-09 22:50 UTC, caupolicandiaz requested changes
@alinasir85 I've added several comments. Please update the entry, and tag me when you've made the changes. Thanks

2023-10-09 22:50 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/chr/chr.md
> +It accepts an ASCII value as a parameter and returns a string representing a character from the specified ASCII value.
```suggestion
It accepts an ASCII value as the argument and returns a string representing the associated character.
```

2023-10-09 22:50 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/chr/chr.md
> +- Hex values are defined by a leading 0x.
```suggestion
- Octal values are defined by a leading `0`.
- Hex values are defined by a leading `0x`.
```

2023-10-09 22:50 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/chr/chr.md
> +The example below demonstrate the `chr()` function when different ASCII are passed but their equivalent character is same:
```suggestion
The example below demonstrate the `chr()` function when different ASCII values are passed but their equivalent character is same:
```

2023-10-09 22:56 UTC, alinasir85 commented
> @alinasir85 I've added several comments. Please update the entry, and tag me when you've made the changes. Thanks

@caupolicandiaz, suggested changes pushed

2023-10-10 17:30 UTC, caupolicandiaz approved these changes
@alinasir85 This is ready for a second review

2023-10-11 16:40 UTC, SSwiniarski approved these changes
@alinasir85 @caupolicandiaz Looks good.

2023-10-11 16:47 UTC, merged