[Term Entry] Add Lua Coroutines .wrap()
Codecademy/docs pull request #3538
Opened 2023-10-10 15:23 UTC by krushnarout

### Description

Added new term entry on new term entry on the .wrap() method for Lua Coroutines.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-10 19:20 UTC, caupolicandiaz requested changes
@krushnarout I've completed my initial review. Please update the entry, and tag me when you've made the changes. Thanks

2023-10-10 19:20 UTC, caupolicandiaz commented on content/lua/concepts/coroutines/terms/wrap/wrap.md
> +  - 'Coroutines'
I don't believe coroutines is currently part of our tags list. Please make the addition to the list or remove it here

2023-10-10 19:20 UTC, caupolicandiaz commented on content/lua/concepts/coroutines/terms/wrap/wrap.md
> +  - 'Lua Programming'
```suggestion
  - 'Game Development'
```

2023-10-10 19:20 UTC, caupolicandiaz commented on content/lua/concepts/coroutines/terms/wrap/wrap.md
> +- The `wrap()` is a function in Lua that creates a coroutine and returns a function that, when called, resumes the coroutine.
```suggestion
- `wrap()` is a function in Lua that creates a coroutine and returns a function that, when called, resumes the coroutine. 
```

2023-10-10 19:20 UTC, caupolicandiaz commented on content/lua/concepts/coroutines/terms/wrap/wrap.md
> +This example utilizes the wrap() function to execute a wrapped coroutine, printing a specific message.
```suggestion
This example utilizes the `wrap()` function to execute a wrapped coroutine, printing a specific message.
```

2023-10-11 05:32 UTC, krushnarout commented
@caupolicandiaz I updated the entry with the suggested changes. Please review and let me know if any further changes are needed. Thanks!

2023-10-11 20:32 UTC, caupolicandiaz approved these changes
@krushnarout This is ready for a second review.

2023-10-17 16:52 UTC, SSwiniarski approved these changes
@krushnarout I did a minor edit to remove a pronoun. Now it looks good to go.

2023-10-17 16:54 UTC, merged

2023-10-18 01:16 UTC, krushnarout commented
@SSwiniarski Thank you