Add new term on the yield
Codecademy/docs pull request #3541
Opened 2023-10-10 17:15 UTC by krushnarout

### Description

Added new term entry on new term entry on the .yield() method for Lua Coroutines.

Closes #3384 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-10 18:00 UTC, caupolicandiaz requested changes
@krushnarout I've added my initial comments. Please update the entry, and tag me when you've completed the changes. Thanks

2023-10-10 18:06 UTC, krushnarout commented on content/lua/concepts/coroutines/terms/yield/yield.md
> +
@caupolicandiaz I think this should be on 44 line. Can you check again?

2023-10-10 18:08 UTC, krushnarout commented on content/lua/concepts/coroutines/terms/yield/yield.md
> +
I believe this should be placed on line 44. Can you double-check?

2023-10-10 18:09 UTC, krushnarout commented on content/lua/concepts/coroutines/terms/yield/yield.md
> +
@caupolicandiaz I believe this should be placed on line 44. Can you double-check?

2023-10-10 18:31 UTC, krushnarout commented
@caupolicandiaz I updated the entry with the suggested changes. Please review and let me know if any further changes are needed. Thanks!

2023-10-11 17:15 UTC, caupolicandiaz approved these changes
@krushnarout This is ready for a second review.

2023-10-18 17:07 UTC, SSwiniarski approved these changes
@krushnarout Looks good to me

2023-10-18 17:09 UTC, merged

2023-10-19 09:51 UTC, krushnarout commented
@SSwiniarski Thank you