[Concept Entry] Luau: Arrays #3203
Codecademy/docs pull request #3546
Opened 2023-10-10 19:34 UTC by alinasir85

### Description

- Added concept entry of luau arrays
- Closes issue #3203

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-10 22:01 UTC, caupolicandiaz requested changes
@alinasir85 Please review the comments carefully, and update the entry accordingly.

2023-10-10 22:52 UTC, alinasir85 commented on content/luau/concepts/arrays/arrays.md
> +Arrays can hold any type of data, can be accessed and modified using the common indexing syntax (`[]`), and can be cleared through the assignment of `nil`.
I followed the examples from the same repo's Lua because Luau arrays are also same. I have changed all examples

2023-10-10 22:54 UTC, alinasir85 commented
> @alinasir85 Please review the comments carefully, and update the entry accordingly.

@caupolicandiaz changes pushed

2023-10-11 18:06 UTC, caupolicandiaz approved these changes
@alinasir85 I made some direct edits to update the phrasing (we avoid the use of first and second person pronouns - I, you, we - in docs). This is ready for a second review.

2023-10-14 16:46 UTC, SSwiniarski requested changes
@alinasir85 I've done a review and left a few comments. Most have to do with pronoun use (we don't use first- or second-person pronouns in Docs) and with the use of curly quotes in code blocks (straight quotes should be used).

2023-10-14 16:46 UTC, SSwiniarski commented on content/luau/concepts/arrays/arrays.md
> +Luau allows for the creation of arrays using curly braces `{}`. Unlike some programming languages that start array indexing from `0`, in Luau, the convention is to begin with index `1`. By default, t
```suggestion
Luau allows for the creation of arrays using curly braces `{}`. Unlike some programming languages that start array indexing from `0`, in Luau, by default, the first element in an array is designated as index `1`. However, Luau provides the flexibility to create arrays with custom indices as needed.
```

2023-10-14 16:46 UTC, SSwiniarski commented on content/luau/concepts/arrays/arrays.md
> +In this array, elements are indexed from 1 to 3. To print `b`, you need to reference it by its assigned index, which is 2.
```suggestion
In this array, elements are indexed from 1 to 3. To print `b`, reference it by its assigned index, which is 2.
```
We avoid first and second-person pronouns in Docs.

2023-10-14 16:46 UTC, SSwiniarski commented on content/luau/concepts/arrays/arrays.md
> +```
````suggestion
```lua
dictionary = {
    ["A"] = "Apple",
    ["B"] = "Banana",
    ["C"] = "Cat"
}

print(dictionary["C"]) -- "Cat"
```
````
Regular straight quotes should be used in code.

2023-10-14 16:46 UTC, SSwiniarski commented on content/luau/concepts/arrays/arrays.md
> +    [3] = “c”
```suggestion
    [1] = "a",
    [2] = "b",
    [3] = "c"
```
Straight quotes should be used in code.

2023-10-14 16:46 UTC, SSwiniarski commented on content/luau/concepts/arrays/arrays.md
> +It's important to note that in Lua (and Luau), when you access a dictionary or array using an index or key, Luau returns the associated value, not the index or key itself.
```suggestion
It's important to note that in Lua (and Luau), when accessing a dictionary or array using an index or key, Luau returns the associated value, not the index or key itself.
```
No first- or second-person pronouns.

2023-10-14 16:46 UTC, SSwiniarski commented on content/luau/concepts/arrays/arrays.md
> +You can reassign values in Luau arrays by specifying the index and providing a new value, as shown below:
```suggestion
Values can be reassigned in Luau arrays by specifying the index and providing a new value, as shown below:
```

2023-10-14 16:46 UTC, SSwiniarski commented on content/luau/concepts/arrays/arrays.md
> +a[2] = “c” -- Now the object at index is 2 is c instead of b
```suggestion
a[2] = "c" -- Now the object at index is 2 is c instead of b
```
Straight quotes

2023-10-14 16:46 UTC, SSwiniarski commented on content/luau/concepts/arrays/arrays.md
> +To remove an element, you can simply reassign the index to `nil`.
```suggestion
To remove an element, simply reassign the index to `nil`.
```

2023-10-14 16:46 UTC, SSwiniarski commented on content/luau/concepts/arrays/arrays.md
> +Frequently, you'll want to determine the length or size of an array. In Luau, you can use the `#` symbol before an array to retrieve its length.
```suggestion
Frequently, it's necessary to determine the length or size of an array. In Luau, use the `#` symbol before an array to retrieve its length.
```

2023-10-14 16:46 UTC, SSwiniarski commented on content/luau/concepts/arrays/arrays.md
> +You can add elements to the end of an array using the `table.insert()` function:
```suggestion
Elements can be added to the end of an array using the `table.insert()` function:
```

2023-10-14 16:46 UTC, SSwiniarski commented on content/luau/concepts/arrays/arrays.md
> +To remove an element from an array, you can use the `table.remove()` function:
```suggestion
To remove an element from an array, use the `table.remove()` function:
```

2023-10-14 16:46 UTC, SSwiniarski commented on content/luau/concepts/arrays/arrays.md
> +Luau supports multi-dimensional arrays, which are arrays of arrays. You can create them like this:
```suggestion
Luau supports multi-dimensional arrays, which are arrays of arrays. They can be created like this:
```

2023-10-14 16:46 UTC, SSwiniarski commented on content/luau/concepts/arrays/arrays.md
> +Accessing elements in a multi-dimensional array requires using nested square brackets:
```suggestion
Accessing elements in a multi-dimensional array requires using multiple sets of square brackets:
```

2023-10-27 17:26 UTC, caupolicandiaz commented
@alinasir85 There hasn't been any activity on this entry, are you still available to complete these edits?

2023-10-27 19:34 UTC, alinasir85 commented
@caupolicandiaz Review changes done

2023-10-28 12:00 UTC, SSwiniarski approved these changes
@alinasir85 I did one minor change. Now it looks good to go.

2023-10-28 12:02 UTC, merged