added a new term entry on the .atan() method for Lua: Math
Codecademy/docs pull request #3554
Opened 2023-10-11 13:53 UTC by Fejiro001

### Description

- Added the Math.atan() term for Lua
- Closes Issue #3388 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-11 22:53 UTC, caupolicandiaz requested changes
@Fejiro001 I've added my comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-10-11 22:53 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/atan/atan.md
> +The **`atan()`** function in Lua's math library evaluates the arctangent (inverse tangent) of a given number. The arctangent is the angle in radians (this is the answer returned) whose tangent is equ
```suggestion
The **`atan()`** function in Lua's math library evaluates the arctangent (inverse tangent) of a given number. The arctangent is the angle in radians (the answer returned) whose tangent is equal to the given value.
```

2023-10-11 22:53 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/atan/atan.md
> +print("The Arctangent of", x, "is", answer)
```suggestion
local output = string.format("The arctangent of %.2f is approximately %.4f", x, answer)
print(output)
```

2023-10-11 22:53 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/atan/atan.md
> +This will result in the following output below. The answer is approximately 0.785 radians or 45 degrees.
```suggestion
This will result in the following output below. 
```

2023-10-11 22:53 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/atan/atan.md
> +The Arctangent of 1	is 0.78539816339745
update to match edits above

2023-10-12 17:58 UTC, caupolicandiaz approved these changes
@Fejiro001 Looks good, this is ready for a second review.

2023-10-14 16:18 UTC, SSwiniarski approved these changes
@Fejiro001, @caupolicandiaz Looks good.

2023-10-14 16:21 UTC, merged