Kotlin floor() method implementation
Codecademy/docs pull request #3555
Opened 2023-10-11 13:57 UTC by tanbirali

### Description
A new term entry for Kotlin Floor method.
Close #3524 

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-11 23:20 UTC, caupolicandiaz requested changes
@tanbirali I've added my initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-10-11 23:20 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/floor/floor.md
> +Description: 'The `floor()` method in Kotlin is used to round a floating-point to a nearest lowest integer value'
```suggestion
Description: 'Returns the nearest integer that is lower than or equal to the value passed.'
```

2023-10-11 23:20 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/floor/floor.md
> +The **`floor()`** function returns a rounded number down to the nearest integer.
```suggestion
The **`floor()`** function takes a value and returns the nearest integer that is lower than or equal to the value given.
```

2023-10-11 23:20 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/floor/floor.md
> +Math.floor(x:Double)
```suggestion
import kotlin.math.*
floor(x)
```

2023-10-11 23:20 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/floor/floor.md
> +Where `x` is the number to be rounded down to the nearest integer.
```suggestion
Where `x` is the number of type double to be rounded down to the nearest integer.
```

2023-10-11 23:20 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/floor/floor.md
> +println(Math.floor(3.4))
```suggestion
import kotlin.math.*
println(floor(3.4))
```

2023-10-11 23:20 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/floor/floor.md
> +Math.floor(x:Double)
I believe `Math` calls the java library

2023-10-11 23:20 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/floor/floor.md
> +## Codebyte Example
kotlin is not currently supported by the Codecademy compiler so I would suggest removing this example

2023-10-12 07:55 UTC, tanbirali commented
@caupolicandiaz I have commited the requested changes and also removed the codebyte example, do let me know if I have to make any more changes.

2023-10-12 17:56 UTC, caupolicandiaz approved these changes
@tanbirali Just added a couple of direct edits to update the example. This is ready for a second review.

2023-10-14 16:23 UTC, SSwiniarski approved these changes
@tanbirali, @caupolicandiaz Looks good.

2023-10-14 16:25 UTC, merged