Add image to CSS Typography word-spacing
Codecademy/docs pull request #3562
Opened 2023-10-11 23:05 UTC by yangc95

### Description

Adding new media to CSS term, fixed some typos

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-11 23:16 UTC, caupolicandiaz approved these changes
@yangc95 This looks good.

2023-10-11 23:28 UTC, caupolicandiaz requested changes
@yangc95 I've added a couple of edits. Please update, and tag me when you've finished with the changes. Thanks

2023-10-11 23:28 UTC, caupolicandiaz commented on content/css/concepts/typography/terms/word-spacing/word-spacing.md
> +**`word-spacing`** sets space between words.
```suggestion
The **`word-spacing`** attribute is used to set the size of spaces between words.
```

2023-10-11 23:28 UTC, caupolicandiaz commented on content/css/concepts/typography/terms/word-spacing/word-spacing.md
> +> **Note:** For word spacing, using `em` values are recommended because the spacing can be set based on the size of the font.
```suggestion
> **Note:** For word spacing, using `em` values are recommended because the spacing can be set to match the size of the font.
```

2023-10-11 23:32 UTC, caupolicandiaz approved these changes
@yangc95 Looks good!

2023-10-13 16:15 UTC, SSwiniarski approved these changes
@yangc95 looks good.

2023-10-13 16:22 UTC, SSwiniarski commented
@yangc95 you'll need to resolve the failed checks before merging.

2023-10-13 21:36 UTC, merged