Lua modf
Codecademy/docs pull request #3564
Opened 2023-10-12 08:55 UTC by SusheelThapa

### Description

- Closed issue #3500 
- Created documentation for the `math.modf()` function in Lua.
- Included details on usage, syntax, and examples.
- Motivation: To assist users in understanding the functionality of `math.modf()` in Lua.
- Context: Aligning the documentation with existing math function documentation in Lua.

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-12 08:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3564) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3564) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3564) it.</sub>

2023-10-12 19:29 UTC, caupolicandiaz requested changes
@SusheelThapa I've completed my initial review. Please update the entry, and tag me when you've finished making changes thanks.

2023-10-12 19:29 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/modf/modf.md
> +Description: 'Used to extract the integral and fractional parts of a given number'
```suggestion
Description: 'Used to extract the integral and fractional parts of a given number.'
```

2023-10-12 19:29 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/modf/modf.md
> +The **`math.modf()`** function is a part of the Lua `math` library and is used to split a given number into **its integral and fractional parts**. It rounds the number down to the nearest integer and
```suggestion
The **`math.modf()`** function is a part of the Lua `math` library and is used to split a given number into *its integral and fractional parts*. It rounds the number down to the nearest integer and returns both the integer part and the fractional part as separate values.
```

2023-10-12 19:29 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/modf/modf.md
> +> **Note:** `math.modf()`rounds the number down and always returns a value equal to or less than the given number. If you need to round numbers in either direction, consider using `math.round()`.
```suggestion
> **Note:** `math.modf()` rounds the number down and always returns a value equal to or less than the given number. 
```

2023-10-12 19:29 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/modf/modf.md
> +> **Note:** `math.modf()`rounds the number down and always returns a value equal to or less than the given number. If you need to round numbers in either direction, consider using `math.round()`.
I believe that math.round is only available in luau

2023-10-12 19:29 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/modf/modf.md
> +print("Integer part: " .. integerPart)       -- Output: Integer part: 5
generally we use ```shell blocks for showing the output.

2023-10-13 05:25 UTC, SusheelThapa commented
@caupolicandiaz Can you please review, I have updated as per your suggestion?

2023-10-13 16:48 UTC, caupolicandiaz approved these changes
@SusheelThapa This is ready for a second review.

2023-10-14 16:01 UTC, SSwiniarski requested changes
@SusheelThapa I did a review and left a couple of comments.

2023-10-14 16:01 UTC, SSwiniarski commented on content/lua/concepts/mathematical-library/terms/modf/modf.md
> +
````suggestion
integerPart, fractionalPart = math.modf(number)
```

`math.modf()` returns the integral part of `number` in `integerPart` and the fractional part in `fractionalPart`.

````

Prefer the explanatory text outside the code block.

2023-10-14 16:01 UTC, SSwiniarski commented on content/lua/concepts/mathematical-library/terms/modf/modf.md
> +For negative numbers, `math.modf()` returns the closest integer less than or equal to the given value:
```suggestion
For negative numbers, `math.modf()` returns the closest integer greater than or equal to the given value:
```
-3.0 is greater than -3.3

2023-10-15 02:19 UTC, SusheelThapa commented
@SSwiniarski I have updated based in you suggestions. Can you review it?

2023-10-15 15:29 UTC, SSwiniarski approved these changes
@SusheelThapa Looks good.

2023-10-15 15:30 UTC, merged