[Term Entry] Java Calendar setFirstDayOfWeek()
Codecademy/docs pull request #3584
Opened 2023-10-12 18:51 UTC by alanabarned2

### Description

- Added the Calendar.setFirstDayOfWeek() term to Java
- Closes Issue #3164 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-12 18:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3584) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3584) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3584) it.</sub>

2023-10-12 21:54 UTC, caupolicandiaz requested changes
@alanabarned2 I've added my initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-10-12 21:54 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/setFirstDayOfWeek/setFirstDayOfWeek.md
> +calendar.setFirstDayOfWeek(int day_val)
```suggestion
calendar.setFirstDayOfWeek(day_val)
```

2023-10-12 21:54 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/setFirstDayOfWeek/setFirstDayOfWeek.md
> +    int newFirstDay = cal.setFirstDayOfWeek(Calendar.SATURDAY);
```suggestion
    cal.setFirstDayOfWeek(Calendar.SATURDAY);
    int newFirstDay = cal.getFirstDayOfWeek();
```

2023-10-12 21:54 UTC, caupolicandiaz commented on content/java/concepts/calendar/terms/setFirstDayOfWeek/setFirstDayOfWeek.md
> +    System.out.println("First day of the week: " + first_day);
```suggestion
    System.out.println("First day of the week: " + firstDay);
```

2023-10-18 19:49 UTC, caupolicandiaz approved these changes
@alanabarned2 This is ready for a second review.

2023-10-27 19:42 UTC, KTom101 approved these changes
@alanabarned2 I'm going to keep everything as is. Looks good.

2023-10-27 19:43 UTC, merged