feat(git): add new entry(rebase) in git subdirectory
Codecademy/docs pull request #3585
Opened 2023-10-12 19:43 UTC by adeyinkaezra123

### Description
Add new [Concept Entry] Git Rebase. Fixes #3490 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-13 16:01 UTC, SSwiniarski requested changes
@adeyinkaezra123 I did a first review and left a few comments.

2023-10-13 16:01 UTC, SSwiniarski commented on content/git/concepts/rebase/rebase.md
> +8. Clean up (optional): Once you're sure the rebase is successful, you can delete the old branch if needed with `git branch -d <old-branch-name>`.
```suggestion
1. Make sure the working directory is clean: Commit or stash any changes in the current branch to ensure there are no uncommitted modifications.
2. Checkout the branch to rebase: Use `git checkout <branch-name>` to switch to the branch to rebase.
3. Fetch the latest changes: Run `git fetch` to capture the latest changes from the remote repository.
4. Start the rebase: Start a rebase in either the regular or interactive modes
5. Resolve conflicts (if any): Git will pause the rebase if there are conflicts. Use git status to identify the files with conflicts and resolve them manually. After resolving conflicts, use `git add <file>` and `git rebase --continue` to continue the rebase.
6. Complete the rebase: After resolving conflicts (if any), the rebase will continue automatically or when `git rebase --continue` is used.
7. Push the rebased branch: When working on a shared branch, it's essential to push the rebased branch with `git push` to update the remote branch.
8. Clean up (optional): Once the rebase is successful, the old branch can be deleted if needed with `git branch -d <old-branch-name>`.
```
There shouldn't be blank lines between elements of a bulleted list.

2023-10-13 18:53 UTC, adeyinkaezra123 commented
@SSwiniarski Incorporated all suggestions

2023-10-14 12:09 UTC, SSwiniarski approved these changes
@adeyinkaezra123 I fixed one typo. Looks good for a second review.

2023-10-25 22:54 UTC, caupolicandiaz approved these changes
@adeyinkaezra123 @SSwiniarski LGTM

2023-10-25 22:56 UTC, merged