Added: [Term Entry] Kotlin Math .atan2()
Codecademy/docs pull request #3591
Opened 2023-10-13 03:24 UTC by rahul0x00

### Description

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-13 04:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3591) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3591) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3591) it.</sub>

2023-10-13 15:53 UTC, SSwiniarski requested changes
@rahul0x00 I did a first review and only had one comment.

2023-10-13 15:53 UTC, SSwiniarski commented on content/kotlin/concepts/math-methods/terms/atan2/atan2.md
> +`The angle between the positive x-axis and the point (3.0, 4.0) is 0.93 radians.`
````suggestion
In this example, the .atan2() method calculates the angle, and the result will output:

```shell
The angle between the positive x-axis and the point (3.0, 4.0) is 0.93 radians.
```
````
This is our preferred method of displaying example output.

2023-10-14 12:01 UTC, SSwiniarski approved these changes
@rahul0x00 I make a couple of minor edits and this looks good for a second review.

2023-10-14 22:01 UTC, caupolicandiaz requested changes
@rahul0x00 I've added my comments. Please update the entry, and tag me when you've completed the changes. Thanks

2023-10-14 22:01 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/atan2/atan2.md
> +```
update code indentations to use 2 spaces not tabs

2023-10-14 22:01 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/atan2/atan2.md
> +In this example, the .atan2() method calculates the angle, and the result will output:
```suggestion
The code above will result in the following output:
```

2023-10-15 03:27 UTC, rahul0x00 commented
@caupolicandiaz 
Hi, i've made the suggested changes

2023-10-16 17:02 UTC, caupolicandiaz approved these changes
@rahul0x00 @SSwiniarski LGTM

2023-10-17 11:37 UTC, merged