[Entry] Subject: Adding Deep Learning Algorithm- Long Short-Term Memory Network
Codecademy/docs pull request #3594
Opened 2023-10-13 07:00 UTC by ARCHITABHATTAD

### Description
Added a new concept entry for the Deep Learning Algorithms.
The entry will go in a new file in docs/content/ai/concepts/neural-networks/terms/long-short-term-memory/long-short-term-memory.md

closes issue #3563 

### Type of Change
- Adding a new entry

### Checklist
- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-13 07:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3594) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3594) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3594) it.</sub>

2023-10-13 15:41 UTC, SSwiniarski requested changes
@ARCHITABHATTAD I did a first review and left a few comments.

2023-10-13 15:41 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/Long Short-Term Memory Networks/long-short-term-memory-network.md
> +
We're missing an introductory paragraph summarizing what Long Short-Term Memory Networks are. It should not have a header and be like the description above, if not longer.

2023-10-13 15:41 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/Long Short-Term Memory Networks/long-short-term-memory-network.md
> +- Backpropagation Through Time (BPTT): LSTMs, like other RNNs, use BPTT for training. BPTT is an extension of backpropagation that is used to update the network’s weights by taking into account the s
```suggestion
## Key Features of LSTM Networks

- Long-Term Dependencies: LSTMs are capable of learning long-term dependencies in data. Traditional RNNs struggle with this due to the vanishing gradient problem, where gradients diminish exponentially as they are backpropagated through time. LSTMs use a gating mechanism to mitigate this problem.
- Gating Mechanisms: LSTMs have three main components: the input gate, the forget gate, and the output gate. These gates regulate the flow of information into and out of the cell state, allowing LSTMs to selectively remember or forget information.
- Cell State: LSTMs have a cell state that runs through the entire sequence, acting as a memory of the network. The cell state can carry information across long distances, making LSTMs effective for learning long-term patterns.
- Flexibility: LSTMs can be adapted for various types of data, including sequences of different lengths and dimensions. They are widely used in natural language processing, speech recognition, and time-series analysis.
- Backpropagation Through Time (BPTT): LSTMs, like other RNNs, use BPTT for training. BPTT is an extension of backpropagation that is used to update the network’s weights by taking into account the sequential nature of the data.
```
There should be blank lines before and after headers, and should not be blank lines between elements of a bulleted list.

2023-10-13 15:41 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/Long Short-Term Memory Networks/long-short-term-memory-network.md
> +## What is LSTM?
This should be the first section (before "Key Features of LSTM Networks")

2023-10-13 15:41 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/Long Short-Term Memory Networks/long-short-term-memory-network.md
> +
```suggestion
1. **Forget Gate:** Determines what information from the cell state should be discarded or kept.
2. **Input Gate:** Updates the cell state with new information.
3. **Cell State:** Maintains the long-term memory of the network.
4. **Output Gate:** Produces the output based on the cell state.
```

2023-10-13 15:41 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/Long Short-Term Memory Networks/long-short-term-memory-network.md
> +
```suggestion
- Memory Storage: The worker has a good memory (cell state) and a notebook (hidden state) to keep track of tasks.
- Forget Old Information: Before adding new items to the assembly line, the worker checks the notebook and decides what old information is not needed anymore (forget gate). This helps in clearing unnecessary clutter.
- Add New Information: When new items arrive, the worker decides what's important and adds it to the notebook (input gate and candidate cell state). This is like writing down new tasks in the notebook.
- Update Memory: The worker updates their memory by combining the old remembered tasks (adjusted for what was forgotten) with the new tasks (update cell state). This ensures that important past tasks are not entirely lost.
- Decide Output: Finally, the worker looks at their notebook, chooses what to share with the boss, and tells the boss about the most important ongoing tasks (output gate).
```

2023-10-13 15:44 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/Long Short-Term Memory Networks/long-short-term-memory-network.md
You should also change the location of this file from `Long Short-Term Memory Networks/long-short-term-memory-network.md` to `long-short-term-memory-networks/long-short-term-memory-networks.md

2023-10-13 15:45 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/Long Short-Term Memory Networks/long-short-term-memory-network.md
You should also change the location of this file from `Long Short-Term Memory Networks/long-short-term-memory-network.md` to `long-short-term-memory-networks/long-short-term-memory-networks.md

2023-10-13 17:56 UTC, ARCHITABHATTAD commented
@SSwiniarski Thankyou for guiding me...I have made the required changes....can you please check and let me know if any other changes are required.

2023-10-14 12:05 UTC, SSwiniarski requested changes
@ARCHITABHATTAD Some more comments.

2023-10-14 12:05 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/long-short-term-memory-networks/long-short-term-memory-networks.md
> +
```suggestion

```
No header for introduction.

2023-10-14 12:05 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/long-short-term-memory-networks/long-short-term-memory-networks.md
> +   Produces the output based on the cell state.
```suggestion
1. **Forget Gate:** Determines what information from the cell state should be discarded or kept.
2. **Input Gate:** Updates the cell state with new information.
3. **Cell State:** Maintains the long-term memory of the network.
4. **Output Gate:** Produces the output based on the cell state.
```

2023-10-14 12:05 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/long-short-term-memory-networks/long-short-term-memory-networks.md
> +## Key Features of LSTM Networks
```suggestion
## Key Features of LSTM Networks

```
Need a blank line after header.

2023-10-14 12:05 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/long-short-term-memory-networks/long-short-term-memory-networks.md
> +
```suggestion
```
Remove one blank line (no more than one in a row.)

2023-10-14 14:10 UTC, SSwiniarski requested changes
@ARCHITABHATTAD One more comment.

2023-10-14 14:10 UTC, SSwiniarski commented on content/ai/concepts/neural-networks/terms/long-short-term-memory-networks/long-short-term-memory-networks.md
> +## What is LSTM
```suggestion
```
We do not use headers before the introduction.

2023-10-14 14:43 UTC, SSwiniarski approved these changes
@ARCHITABHATTAD Looks good for a second review.

2023-10-31 22:17 UTC, caupolicandiaz approved these changes
@ARCHITABHATTAD @SSwiniarski LGTM

2023-10-31 22:17 UTC, merged