Update greedy-best-first-search.md
Codecademy/docs pull request #3595
Opened 2023-10-13 09:16 UTC by Sahilkumar19

Fixes #3565 

Description
This PR updating and adding new feature in the Greedy Best First Search algorithm which are the important one and every folks out there should know them.
closes #3565 

Type of Change
-Adding a new entry
-Editing an existing entry (fixing a typo, bug, issues, etc)
-Updating the documentation

Checklist
- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-13 09:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3595) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3595) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3595) it.</sub>

2023-10-13 15:06 UTC, yangc95 commented on content/ai/concepts/search-algorithms/terms/greedy-best-first-search/greedy-best-first-search.md
> +**Greedy best-first search** is an informed search algorithm where the evaluation function is strictly equal to the heuristic function, disregarding the edge weights in a weighted graph(because we ca
Can we keep the original wording but expand on certain terms like "heuristic function" in a concise manner? The change is quite wordy and doesn't necessarily present any new information.

2023-10-13 15:19 UTC, yangc95 commented on content/ai/concepts/search-algorithms/terms/greedy-best-first-search/greedy-best-first-search.md
> +**Greedy best-first search** is an informed search algorithm where the evaluation function is strictly equal to the heuristic function, disregarding the edge weights in a weighted graph(because we ca
```suggestion
**Greedy best-first search** is an informed search algorithm where the evaluation function is strictly based on the heuristic function, regardless of edge weights in a weighted graph. It selects the next node to traverse based on the lowest value obtained from a heuristic function, denoted as _h(x)_. The primary objective is to find the quickest path to the target node.
```

2023-10-13 15:20 UTC, yangc95 requested changes
@Sahilkumar19 I appreciate your input in refining the text. It's great to collaborate and improve the content. However, to maintain clarity and conciseness, we should aim for meaningful edits.

Feel free to continue making suggestions, and let's work together to enhance the text while keeping it clear and informative.

2023-10-14 13:10 UTC, Sahilkumar19 commented
> @Sahilkumar19 I appreciate your input in refining the text. It's great to collaborate and improve the content. However, to maintain clarity and conciseness, we should aim for meaningful edits.
> 
> Feel free to continue making suggestions, and let's work together to enhance the text while keeping it clear and informative.

Right, thanks for pointing it out that we should aim for meaningful edits.

2023-10-14 13:13 UTC, Sahilkumar19 commented
Can I close this PR? as I have already made one PR for the same issue.

2023-10-15 17:17 UTC, yangc95 commented
> Can I close this PR? as I have already made one PR for the same issue.

Sure! I can go ahead and close this PR.

2023-10-15 17:17 UTC, closed without merging