Update a-star-search.md
Codecademy/docs pull request #3597
Opened 2023-10-13 13:12 UTC by Sahilkumar19

Description
Fixes #3596 
This PR enhancing the clarity and readability in the topic of A* search algorithm.Added some important properties like optimality and colpleteness.
closes #3596 

Type of changes
- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

2023-10-13 13:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3597) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3597) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3597) it.</sub>

2023-10-13 13:13 UTC, Sahilkumar19 reviewed
Reviewed the changes.

2023-10-13 15:22 UTC, SSwiniarski requested changes
@Sahilkumar19 I did a first review and left a few comments.

2023-10-13 15:22 UTC, SSwiniarski commented on content/ai/concepts/search-algorithms/terms/a-star-search/a-star-search.md
> +**A\* Search** is an informed [best-first search algorithm](https://www.codecademy.com/resources/docs/ai/search-algorithms/best-first-search) It evaluates the nodes by combining **g(n)** the exact co
```suggestion
**A\* Search** is an informed [best-first search algorithm](https://www.codecademy.com/resources/docs/ai/search-algorithms/best-first-search) It evaluates the nodes by combining **g(n)** the exact cost to reach the node n from the starting point, and **h(n)** the (heuristic) approximate cost to get from 'n' to the goal.
```

2023-10-13 15:22 UTC, SSwiniarski commented on content/ai/concepts/search-algorithms/terms/a-star-search/a-star-search.md
> +**f(n)** = Estimated cost of the cheapest solution from the starting point to the goal state through the goal state.
```suggestion
- **f(n)** = **h(n)** + **g(n)**
- **g(n)** = The exact cost to reach node n from the starting node.
- **h(n)** = The heuristic cost of the cheapest path from node n to the goal.
- **f(n)** = Estimated cost of the cheapest solution from the starting point to the goal through n.
```

2023-10-13 15:22 UTC, SSwiniarski commented on content/ai/concepts/search-algorithms/terms/a-star-search/a-star-search.md
> +Provided that heuristic function should satisfy certain conditions A* search is both complete and optimal given that **h(n)** should be admissible heuristic means that it should never overestimate th
```suggestion
A* search is both complete and optimal given that **h(n)** should be **admissible**, meaning that it should never overestimate the cost to reach the goal, and **h(n)** must be **consistent**, i.e., it satisfies the triangle inequality.
```

2023-10-13 15:22 UTC, SSwiniarski commented on content/ai/concepts/search-algorithms/terms/a-star-search/a-star-search.md
>  For the algorithm to generate the correct result, the evaluation function must be **admissible**, meaning that it never overestimates the cost to arrive at the goal node.
```suggestion
```
This line is now redundant.

2023-10-14 14:14 UTC, SSwiniarski requested changes
@Sahilkumar19 one more comment.

2023-10-14 14:14 UTC, SSwiniarski commented on content/ai/concepts/search-algorithms/terms/a-star-search/a-star-search.md
> +**f(n)** = Estimated cost of the cheapest solution from the starting point to the goal through n.
```suggestion
- **f(n)** = **h(n)** + **g(n)**
- **g(n)** = The exact cost to reach node n from the starting node.
- **h(n)** = The heuristic cost of the cheapest path from node n to the goal.
- **f(n)** = Estimated cost of the cheapest solution from the starting point to the goal through n.
```
This needs to be a bulleted list.

2023-10-14 15:55 UTC, Sahilkumar19 commented on content/ai/concepts/search-algorithms/terms/a-star-search/a-star-search.md
> +**f(n)** = Estimated cost of the cheapest solution from the starting point to the goal through n.
I have made the suggested changes.

2023-10-14 16:16 UTC, SSwiniarski approved these changes
@Sahilkumar19 Looks good for a second review.

2023-10-19 16:46 UTC, SSwiniarski commented
> > @Sahilkumar19 Looks good for a second review.
> 
> Who will review it for the second time (just asking)

@Sahilkumar19 one of the other maintainers. It's not set exactly which one, that depends on everyone's workload.

2023-11-02 19:54 UTC, caupolicandiaz commented
@Sahilkumar19 Apologies for the delay moving forward with this PR. We've reconsidered these edits and decided not to incorporate them. We hope you can find another issue or concept to work on and contribute to docs. Thanks

2023-11-02 19:54 UTC, closed without merging