[Term Entry] Lua Math .sin()
Codecademy/docs pull request #3599
Opened 2023-10-13 21:18 UTC by Fejiro001

### Description

- Added the Math.sin() term for Lua
- Closes Issue #3505 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-14 13:17 UTC, SSwiniarski requested changes
@Fejiro001 I did a first review and had two minor comments.

2023-10-14 13:17 UTC, SSwiniarski commented on content/lua/concepts/mathematical-library/terms/sin/sin.md
> +Description: 'Returns the sine of an angle in radians.'
```suggestion
Description: 'Returns the sine of an angle given in radians.'
```

2023-10-14 13:17 UTC, SSwiniarski commented on content/lua/concepts/mathematical-library/terms/sin/sin.md
> +The **`sin()`** function in Lua's math library calculates the sine of a given angle in radians. The result is the ratio of the length the side opposite the given angle to the length of the hypotenuse
```suggestion
The **`sin()`** function in Lua's math library calculates the sine of an angle given in radians. The result is the ratio of the length the side opposite the given angle to the length of the hypotenuse in a right-angled triangle.
```

2023-10-14 20:33 UTC, Fejiro001 commented
@SSwiniarski ok thank you.

2023-10-15 15:28 UTC, SSwiniarski commented
@Fejiro001 have you made the changes? I don't see them yet.

2023-10-15 18:41 UTC, Fejiro001 commented
@SSwiniarski I have made the changes now

2023-10-15 19:06 UTC, SSwiniarski approved these changes
@Fejiro001 Looks good for a second review.

2023-10-16 20:02 UTC, caupolicandiaz approved these changes
@Fejiro001 @SSwiniarski Just made some minor language edits. Looks good to merge

2023-10-17 11:59 UTC, merged

2023-10-17 14:22 UTC, Fejiro001 commented
Thank you @SSwiniarski and @caupolicandiaz