[Term Entry] Kotlin `hypot()` method
Codecademy/docs pull request #3604
Opened 2023-10-14 03:10 UTC by manviii27

### Description

A new term entry for Kotlin `.hypot()` method.
Closes #3525 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-14 13:51 UTC, SSwiniarski requested changes
@manviii27 I did a first review and left comments. The most important is you need to change the codebyte section because codebytes does not support Kotlin right now.

2023-10-14 13:51 UTC, SSwiniarski commented on content/kotlin/concepts/math-methods/terms/hypot/hypot.md
> +- y: Another number whose hypotenuse is to be calculated.
```suggestion
- `y`: The other number whose hypotenuse is to be calculated.

```

2023-10-14 13:51 UTC, SSwiniarski commented on content/kotlin/concepts/math-methods/terms/hypot/hypot.md
> +- x: One of the two numbers whose hypotenuse is to be calculated.
```suggestion
- `x`: One of the two numbers whose hypotenuse is to be calculated.

```

2023-10-14 13:51 UTC, SSwiniarski commented on content/kotlin/concepts/math-methods/terms/hypot/hypot.md
> +## Codebyte Example
This either needs to be changed to a regular example or removed, the codebytes engine does not support Kotlin at this time.

2023-10-15 11:49 UTC, manviii27 commented
@SSwiniarski I've made the changes, please review!

2023-10-15 15:50 UTC, SSwiniarski approved these changes
@manviii27 looks good for a second review.

2023-10-16 17:39 UTC, caupolicandiaz approved these changes
@manviii27 @SSwiniarski Just made a couple of direct edits to update some formatting . Looks good to merge

2023-10-17 11:48 UTC, merged