[Term Entry] Kotlin `.ln()` method
Codecademy/docs pull request #3605
Opened 2023-10-14 03:15 UTC by manviii27

### Description

A new term entry for Kotlin `.hypot()` method.
Close #3526 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-14 13:55 UTC, SSwiniarski requested changes
@manviii27 I did a first review and left comments. Most important is the codebyte must be changed or removed because codebytes does not support Kotlin.

2023-10-14 13:55 UTC, SSwiniarski commented on content/kotlin/concepts/math-methods/terms/ln/ln.md
> +The `.ln()` method returns a value of type `double`, the logarithm of `n` to `e`. The following are the special cases:
```suggestion
The `.ln()` method returns a value of type `double`, the logarithm of `n` to _e_. The following are the special cases:

```

2023-10-14 13:55 UTC, SSwiniarski commented on content/kotlin/concepts/math-methods/terms/ln/ln.md
> +## Codebyte Example
Codebytes does not support Kotlin so this needs to be changed to a regular example or removed.

2023-10-15 11:47 UTC, manviii27 commented
@SSwiniarski I've made the changes, please review!

2023-10-15 15:48 UTC, SSwiniarski reviewed
@manviii27 looks good for a second review.

2023-10-15 15:49 UTC, SSwiniarski approved these changes

2023-10-16 17:48 UTC, caupolicandiaz requested changes
@manviii27 I just added a few additional minor edits. Please update, and tag me when you've completed the changes. Thanks

2023-10-16 17:48 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/ln/ln.md
> +The **`.log()`** method in Kotlin's `math` class is used to calculate the natural logarithm of a number.
```suggestion
The **`ln()`** method in Kotlin's `math` class is used to calculate the natural logarithm of a number.

```

2023-10-16 17:48 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/ln/ln.md
> +- n: The number of type `double` for which the logarithm is to be calculated.
```suggestion
- `n`: The number of type `double` for which the logarithm is to be calculated.

```

2023-10-16 17:48 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/ln/ln.md
> +The `.ln()` method returns a value of type `double`, the logarithm of `n` to _e_. The following are the special cases:
```suggestion
The `ln()` method returns a value of type `double`, the logarithm of `n` to _e_. The following values represent special cases:

```

2023-10-16 17:48 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/ln/ln.md
> +This example shows how to use the `.ln()` method to calculate the natural logarithm of `6`:
```suggestion
This example shows how to use the `ln()` method to calculate the natural logarithm of `6`:

```

2023-10-17 05:39 UTC, manviii27 commented
@caupolicandiaz I've made the changes, please review.

2023-10-17 17:36 UTC, caupolicandiaz approved these changes
@manviii27 This is ready for a second review

2023-10-18 12:46 UTC, merged