[Term Entry] Kotlin `.log()` method
Codecademy/docs pull request #3606
Opened 2023-10-14 04:04 UTC by manviii27

### Description

A new term entry for Kotlin `.log()` method.
Close #3527 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-14 14:18 UTC, SSwiniarski requested changes
@manviii27 I did a first review and left a few comments. Most important is the codebyte needs to be changed or removed because codebytes doesn't support Kotlin.

2023-10-14 14:18 UTC, SSwiniarski commented on content/kotlin/concepts/math-methods/terms/log/log.md
> +Description: 'Calculates the logarithm of a number with respect to base.'
```suggestion
Description: 'Calculates the logarithm of a number with respect to a base value.'

```

2023-10-14 14:18 UTC, SSwiniarski commented on content/kotlin/concepts/math-methods/terms/log/log.md
> +The **`.log()`** method in Kotlin's `math` class is used to calculate the logarithm of a number with respect to base.
```suggestion
The **`.log()`** method in Kotlin's `math` class is used to calculate the logarithm of a number with respect to a base value.

```

2023-10-14 14:18 UTC, SSwiniarski commented on content/kotlin/concepts/math-methods/terms/log/log.md
> +## Codebyte Example
This needs to be changed to a regular example or removed as codebytes doesn't support Kotlin at this time.

2023-10-15 11:45 UTC, manviii27 commented
@SSwiniarski I've made the changes, please review!

2023-10-15 15:47 UTC, SSwiniarski approved these changes
@manviii27 looks good for a second review.

2023-10-16 17:54 UTC, caupolicandiaz requested changes
@manviii27 I've added my comments. Please update the entry, and tag me when you've made the changes. Thanks

2023-10-16 17:54 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/log/log.md
> +The **`.log()`** method in Kotlin's `math` class is used to calculate the logarithm of a number with respect to a base value.
```suggestion
The **`log()`** method in Kotlin's `math` class is used to calculate the logarithm of a number with respect to a base value.

```

2023-10-16 17:54 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/log/log.md
> +- n: The number of type `double` for which the logarithm is to be calculated.
```suggestion
- `n`: The number of type `double` for which the logarithm is to be calculated.

```

2023-10-16 17:54 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/log/log.md
> +- base: The number of type `double` that specifies the logarithm base.
```suggestion
- `base`: The number of type `double` that specifies the logarithm base.

```

2023-10-16 17:54 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/log/log.md
> +The `.log()` method returns a value of type `double`, the logarithm of `n` to `base`. The following are the special cases:
```suggestion
The `log()` method returns a value of type `double`, the logarithm of `n` to `base`. The following values represent special cases:

```

2023-10-16 17:54 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/log/log.md
> +This example shows how to use the `.log()` method to calculate the logarithm of `12` with base `2`:
```suggestion
This example shows how to use the `log()` method to calculate the logarithm of `12` with base `2`:

```

2023-10-17 05:46 UTC, manviii27 commented
@caupolicandiaz I've made the changes, please review.

2023-10-17 17:43 UTC, caupolicandiaz approved these changes
@manviii27 @SSwiniarski This is ready to merge

2023-10-18 12:47 UTC, merged