Update cpp.md
Codecademy/docs pull request #3608
Opened 2023-10-14 09:06 UTC by nikcode9

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-14 09:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3608) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3608) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3608) it.</sub>

2023-10-14 14:39 UTC, SSwiniarski requested changes
@nikcode9 Looks like a good addition. I did a first review and made some comments about the formatting and updating the language.

2023-10-14 14:39 UTC, SSwiniarski commented on content/cpp/cpp.md
> +There are a lot of versions of the C++ programming language. These versions of the language are implementations of compilers based on specifications constructed by the ISO C++ community, the communit
```suggestion

There are many of versions of the C++ programming language. These versions of the language are implementations of compilers based on specifications constructed by the ISO C++ community, the community that oversees the development of the language. The following are versions of the language:
```
Needs a blank line between this and the preceding paragraph.

2023-10-14 14:39 UTC, SSwiniarski commented on content/cpp/cpp.md
> +C++17 is the fifth edition.
```suggestion
- C++98 (ISO/IEC 14882:1998) is the first edition.
- C++03 (ISO/IEC 14882:2003) is the second edition.
- C++11 is the third edition.
- C++14 is the fourth edition.
- C++17 is the fifth edition.

```
Needs to be a bulleted list and have a blank line following it.

2023-10-14 14:39 UTC, SSwiniarski commented on content/cpp/cpp.md
> +All of these versions have a lot of differences, mainly additions to the standard library and expansion of APIs. These standards also have differences in APIs due to deperaction.
```suggestion
These versions have many of differences, mainly additions to the standard library and expansion of APIs. These standards also have differences in APIs due to depreciation.
```

2023-10-15 15:52 UTC, SSwiniarski commented
> @codecademy-docs please merge it.

@nikcode9 you need to make the changes above so I can approve it, then another maintainer has to review it. It's not going to be merged without any changes.

2023-10-15 16:02 UTC, nikcode9 reviewed
updated the file.

2023-10-15 16:03 UTC, nikcode9 commented
@SSwiniarski  updated it,please check.

2023-10-15 18:59 UTC, SSwiniarski approved these changes
@nikcode9 I did some minor edits for line spacing. Now it looks good for a second review.

2023-10-15 19:11 UTC, nikcode9 reviewed
updated

2023-10-28 04:29 UTC, KTom101 approved these changes
@nikcode9 This looks good as is.

2023-10-28 04:34 UTC, merged