HTML Add Media: style #3556
Codecademy/docs pull request #3609
Opened 2023-10-14 09:47 UTC by kitttrick

### Description

- Added an output header
- Added an image to demonstrate an example of the code
- Closes Issue #3336 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-14 14:49 UTC, SSwiniarski requested changes
@kitttrick I've done a first review and left some comments.

2023-10-14 14:49 UTC, SSwiniarski commented on media/style-attribute-example.PNG
This does not look like the example style. Can we do full size on a white background?

2023-10-14 14:49 UTC, SSwiniarski commented on content/html/concepts/attributes/terms/style/style.md
> +## Output
```suggestion
```
We do not need a header for the output

2023-10-14 14:49 UTC, SSwiniarski commented on media/style-attribute-example.PNG
Also, can we have ".png" in lower case?

2023-10-17 14:41 UTC, kitttrick reviewed
I believe I've now made all requested changes

2023-10-17 16:22 UTC, SSwiniarski requested changes
@kitttrick some more comments

2023-10-17 16:22 UTC, SSwiniarski commented on media/style-attribute-example.PNG
we need to get rid of this file

2023-10-17 16:22 UTC, SSwiniarski commented on content/html/concepts/attributes/terms/style/style.md
> +![Style Attribute Example](https://raw.githubusercontent.com/Codecademy/docs/main/media/media/style-attribute-example.PNG)
```suggestion
![Style Attribute Example](https://raw.githubusercontent.com/Codecademy/docs/main/media/media/style-attribute-example.png)
```

2023-10-17 16:22 UTC, SSwiniarski commented on media/style-attribute-example.png
Can we zoom in on this so the text is legible.

2023-11-06 17:48 UTC, SSwiniarski commented
@kitttrick You still need to remove that file and make the image text legible. If there's no movement on this PR in a few days, we'll have to close it and unassign the issue.

2023-11-13 12:44 UTC, SSwiniarski commented
Closing because PR was resubmitted.

2023-11-13 12:44 UTC, closed without merging