docs: Add Kotlin math term atan
Codecademy/docs pull request #3610
Opened 2023-10-14 11:09 UTC by gonmmarques

### Description
A new term entry for Kotlin .atan) method.
Closes https://github.com/Codecademy/docs/issues/3516

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-14 11:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3610) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3610) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3610) it.</sub>

2023-10-14 15:03 UTC, SSwiniarski requested changes
@gonmmarques I did a first review and left a few comments.

2023-10-14 15:03 UTC, SSwiniarski commented on content/kotlin/concepts/math-methods/terms/atan/atan.md
> +- x: One of the two numbers whose hypotenuse is to be calculated.
```suggestion
- `x`: The number for which the arc tangent is to be calculated.
```

2023-10-14 15:03 UTC, SSwiniarski commented on content/kotlin/concepts/math-methods/terms/atan/atan.md
> +- atan(NaN) is NaN
```suggestion
- `atan(NaN)` is NaN
```

2023-10-14 15:03 UTC, SSwiniarski commented on content/kotlin/concepts/math-methods/terms/atan/atan.md
> +
```suggestion
```
Remove extra blank line.

2023-10-15 15:46 UTC, SSwiniarski approved these changes
@gonmmarques looks good for a second review.

2023-10-16 17:59 UTC, caupolicandiaz requested changes
@gonmmarques I've added my comments. Please update the entry, and tag me when you've finished making the changes. Thanks

2023-10-16 17:59 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/atan/atan.md
> +The **`.atan()`** method in Kotlin's `math` class is used to calculate the arc tangent of a value. It returns the value of the angle in the range from -PI/2 to PI/2 radians.
```suggestion
The **`atan()`** method in Kotlin's `math` class is used to calculate the arc tangent of a value. It returns the value of the angle in the range from *-PI/2* to *PI/2* radians.
```

2023-10-16 17:59 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/atan/atan.md
> +The `.atan()` method returns a value of type `double` or `float` depending also on the type of the input respectively. There is a special case of:
```suggestion
The `atan()` method returns a value of type `double` or `float` depending also on the type of the input respectively. If the argument passed is `NaN`, the method will return `NaN`.
```

2023-10-16 17:59 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/atan/atan.md
> +- `atan(NaN)` is NaN
```suggestion
```

2023-10-16 17:59 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/atan/atan.md
> +This example shows how to use the `.atan()` method to calculate the arc tangent of `90.0`:
```suggestion
This example shows how to use the `atan()` method to calculate the arc tangent of `90.0`:
```

2023-10-16 17:59 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/atan/atan.md
> +    println(arctan(90.0))
```suggestion
    println(atan(90.0))
```

2023-10-16 19:08 UTC, gonmmarques commented
> @gonmmarques I've added my comments. Please update the entry, and tag me when you've finished making the changes. Thanks

Thank you for your feedback :)

2023-10-18 19:29 UTC, caupolicandiaz approved these changes
@gonmmarques @SSwiniarski LGTM

2023-10-18 20:10 UTC, gonmmarques commented
> @gonmmarques @SSwiniarski LGTM

Any to-dos missing from my side?

2023-10-19 11:17 UTC, merged