[Concept Entry] Rust Conditionals
Codecademy/docs pull request #3611
Opened 2023-10-14 12:16 UTC by Captainnik53

added concept entry for conditionals in Rust

### Description

Added concept of Conditional statements in Rust documentation along with appropriate syntax and code snippets.

### Type of Change

- Adding a new entry

### Checklist

- [✅ ] All writings are my own.
- [✅  ] My entry follows the Codecademy Docs style guide.
- [ ✅ ] My changes generate no new warnings.
- [ ✅ ] I have performed a self-review of my own writing and code.
- [ ✅ ] I have checked my entry and corrected any misspellings.
- [✅  ] I have made corresponding changes to the documentation if needed.
- [✅  ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [✅  ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ✅ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-14 12:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3611) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3611) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3611) it.</sub>

2023-10-14 15:09 UTC, SSwiniarski requested changes
@Captainnik53 I did a first review and left you a few comments.

2023-10-14 15:09 UTC, SSwiniarski commented on content/rust/concepts/conditionals/conditionals.md
> +**Conditional** statements in Rust allow the control of flow in program based on certain conditions. Rust provides support for Conditional statements that include `if`, `else if` and `else` statement
```suggestion
**Conditional** statements in Rust allow the control of flow in program based on certain conditions. Rust provides support for Conditional statements that include `if`, `else if` and `else` statements. Unlike many programming languages, the condition is not surrounded by parenthesis.
```

2023-10-14 15:09 UTC, SSwiniarski commented on content/rust/concepts/conditionals/conditionals.md
> +Example of `else if` statement:
Move this to after the "Example" header.

2023-10-14 15:09 UTC, SSwiniarski commented on content/rust/concepts/conditionals/conditionals.md
> +  println!("This line will be executed.");
```suggestion
  println!("The number is 20 or less.");
```

2023-10-14 15:26 UTC, Captainnik53 commented
> @Captainnik53 I did a first review and left you a few comments.

Have resolved all issues

2023-10-14 15:26 UTC, Captainnik53 commented on content/rust/concepts/conditionals/conditionals.md
> +  println!("This line will be executed.");
Done

2023-10-14 16:14 UTC, SSwiniarski approved these changes
@Captainnik53 i DID ONE MINOR EDIT AND IT LOOKS LIKE WE'RE READY FOR A SECOND REVIEW.

2023-10-14 22:16 UTC, caupolicandiaz requested changes
@Captainnik53 I've added a few additional comments. Please update the entry, and tag me when you've finished making the changes. Thanks

2023-10-14 22:16 UTC, caupolicandiaz commented on content/rust/concepts/conditionals/conditionals.md
> +  - 'learn/rust-for-programmers'
```suggestion
  - 'rust-for-programmers'
  - 'paths/computer-science'
```

2023-10-14 22:16 UTC, caupolicandiaz commented on content/rust/concepts/conditionals/conditionals.md
> +**Conditional** statements in Rust allow the control of flow in program based on certain conditions. Rust provides support for Conditional statements that include `if`, `else if` and `else` statement
```suggestion
**Conditional** statements in Rust allow the control of flow in program based on certain conditions. Rust provides support for conditional statements that include `if`, `else if` and `else` statements. Unlike many programming languages, the condition is not enclosed by parentheses.
```

2023-10-14 22:16 UTC, caupolicandiaz commented on content/rust/concepts/conditionals/conditionals.md
> +Example of `else if` statement:
```suggestion
Example of an `else if` statement:
```

2023-10-14 22:16 UTC, caupolicandiaz commented on content/rust/concepts/conditionals/conditionals.md
> +Example of `else` statement:
```suggestion
Example of an `else` statement:
```

2023-10-15 05:04 UTC, Captainnik53 commented
> @Captainnik53 I've added a few additional comments. Please update the entry, and tag me when you've finished making the changes. Thanks

@caupolicandiaz Have done changes as per your comments.

2023-10-16 17:09 UTC, caupolicandiaz approved these changes
@Captainnik53 @SSwiniarski LGTM

2023-10-17 11:42 UTC, merged