Addresses #3533 | added image example for background-clip
Codecademy/docs pull request #3612
Opened 2023-10-14 15:44 UTC by arun-sagar-s-a

Add media example for background-clip

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-14 15:47 UTC, arun-sagar-s-a commented
@yoiang

2023-10-14 22:32 UTC, caupolicandiaz requested changes
@arun-sagar-s-a I've added my initial review. Please update the entry, and tag me when you've made the changes. Thanks

2023-10-14 22:32 UTC, caupolicandiaz commented on content/css/concepts/background/terms/background-clip/background-clip.md
> +![Rendered background-clip tag](https://raw.githubusercontent.com/Codecademy/docs/main/media/rendered-background-clip.png)
It looks like the image does not exactly match the properties of the examples. The image below uses a double border, but the examples specify a single dashed line. Also the numbers do not match the examples, content-box should be number 1. Please update the image to match

2023-10-15 13:20 UTC, arun-sagar-s-a commented
@caupolicandiaz  Done. Let me know if there's any other changes needed. I made slight changes to make it easy to look at and understand.

2023-10-17 02:39 UTC, arun-sagar-s-a commented
@yoiang Can I get a second review please.

2023-10-17 16:42 UTC, SSwiniarski approved these changes
@arun-sagar-s-a Looks good to me.

2023-10-17 16:44 UTC, merged