Added [Term Entry] Kotlin Math .acos()
Codecademy/docs pull request #3613
Opened 2023-10-14 17:36 UTC by rahul0x00

### Description
Added a new term entry for Kotlin .acos() method
Closes #3512 

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-14 17:44 UTC, rahul0x00 commented on content/kotlin/concepts/math-methods/terms/acos/acos.md
> +Description: 'Calculates the arccosine or reverse cosine of a value, returning the angle in radians.'
should i also include inverse cosine?

Description: 'Calculates the arccosine or reverse cosine or inverse cosine of a value, returning the angle in radians.'

2023-10-14 20:05 UTC, caupolicandiaz requested changes
@rahul0x00 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-10-14 20:05 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/acos/acos.md
> +val angle = Math.acos(value)
```suggestion
import kotlin.math.*
val angle = acos(value)
```

2023-10-14 20:05 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/acos/acos.md
> +in the range [-1, 1].
```suggestion
`value`: The given value to be used in the arccosine calculation. The value should be in the range `-1` to `1`.
```

2023-10-14 20:05 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/acos/acos.md
> +radians. The result is in the range [0, PI].
```suggestion
The `.acos()` method returns a value of type `double` representing the angle in radians. The result will be in the range `0` to `PI`.
```

2023-10-14 20:05 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/acos/acos.md
> +a value:
```suggestion
This example shows how to use the `acos()` method to calculate the arccosine of a value:
```

2023-10-14 20:05 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/acos/acos.md
> +    val angle = Math.acos(value)
```suggestion
    val angle = acos(value)
```

2023-10-14 20:05 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/acos/acos.md
> +1.0471975511965979 rad
this output doesn't match the print statement

2023-10-15 03:33 UTC, rahul0x00 commented
@caupolicandiaz 
Hi, i made the suggested changes

2023-10-16 17:06 UTC, caupolicandiaz approved these changes
@rahul0x00 This is ready for a second review

2023-10-17 11:40 UTC, SSwiniarski approved these changes
@rahul0x00 @caupolicandiaz Looks good.

2023-10-17 11:40 UTC, merged