Docs: Added Kotlin Math cbrt function
Codecademy/docs pull request #3618
Opened 2023-10-16 05:57 UTC by VividhPandey003

### Description

Closes #3519 

### Type of Change

- Updating the documentation

### Checklist

- [+] All writings are my own.
- [+] My entry follows the Codecademy Docs style guide.
- [+] My changes generate no new warnings.
- [+] I have performed a self-review of my own writing and code.
- [+] I have checked my entry and corrected any misspellings.
- [+] I have made corresponding changes to the documentation if needed.
- [+] I have confirmed my changes are not being pushed from my forked `main` branch.
- [+] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [+] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-16 05:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3618) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3618) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3618) it.</sub>

2023-10-16 19:45 UTC, caupolicandiaz requested changes
@VividhPandey003 I've added my initial comments. Please update the entry, and tag me when you've finished making the changes. Thanks

2023-10-16 19:45 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/cbrt/cbrt.md
> +The **`Math.cbrt()`** method returns the cube root of the argument.
```suggestion

The **`math.cbrt()`** method returns the cube root of the given argument.
```

2023-10-16 19:45 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/cbrt/cbrt.md
> +Math.cbrt(n)
```suggestion
cbrt(n)
```

2023-10-16 19:45 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/cbrt/cbrt.md
> +Math.cbrt(n)
there should also be a brief sentence explaining `n`

2023-10-16 19:45 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/cbrt/cbrt.md
> +The following example uses `Math.cbrt()` to return the cube roots of `-6.5`, `2`, and `-340.8`:
```suggestion

The following example uses `cbrt()` to return the cube roots of `-6.5`, `2`, and `-340.8`:
```

2023-10-16 19:45 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/cbrt/cbrt.md
> +The following example uses `Math.cbrt()` to return the cube roots of `-6.5`, `2`, and `-340.8`:
there should always be an empty line after a header

2023-10-16 19:45 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/cbrt/cbrt.md
> +Title: '.cbrt()'
```suggestion
Title: 'cbrt()'
```

2023-10-17 04:18 UTC, VividhPandey003 commented
@caupolicandiaz I have made the required changes. Could you please review it once.
Thanks

2023-10-17 17:10 UTC, caupolicandiaz approved these changes
@VividhPandey003 I just made a couple of additional direct edits. This is ready for a second review.

2023-10-18 16:59 UTC, SSwiniarski approved these changes
@VividhPandey003 @caupolicandiaz Looks good.

2023-10-18 17:00 UTC, merged