Kotlin asinh
Codecademy/docs pull request #3622
Opened 2023-10-16 11:09 UTC by Anudhyan

### Description
-First pull request for Hacktoberfest
-Worked for the first time with Codecademy
-Help by Ezra
-Nervous
### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-16 11:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3622) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3622) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3622) it.</sub>

2023-10-16 16:29 UTC, Anudhyan commented
@SSwiniarski sir please check my pull request and kindly approve it

2023-10-16 16:59 UTC, SSwiniarski requested changes
@Anudhyan I did a first review and had a couple of comments.

2023-10-16 16:59 UTC, SSwiniarski commented on content/kotlin/concepts/math-methods/terms/asinh/asinh.md
> +Description: 'Returns the inverse hyperbolic sine of a numeric argument'
```suggestion
Description: 'Returns the inverse hyperbolic sine of a numeric argument.'
```

2023-10-16 16:59 UTC, SSwiniarski commented on content/kotlin/concepts/math-methods/terms/asinh/asinh.md
> +
```suggestion
```
Delete extra blank line.

2023-10-16 16:59 UTC, SSwiniarski commented on content/kotlin/concepts/math-methods/terms/asinh/asinh.md
> +In this example below we are trying to find the value of inverse hyperbolic sine of 1.0
```suggestion
The example below is finding the value of the inverse hyperbolic sine of 1.0
```

2023-10-16 18:28 UTC, Anudhyan commented on content/kotlin/concepts/math-methods/terms/asinh/asinh.md
> +
Kindly check. I have fixed it, sir !

2023-10-17 11:14 UTC, Anudhyan commented
@SSwiniarski sir please check it soon and approve my first ever pull request !

2023-10-17 12:01 UTC, SSwiniarski approved these changes
@Anudhyan Passing this on to a second review.

2023-10-17 12:05 UTC, Anudhyan commented
> @Anudhyan Passing this on to a second review.

Then what will I have to do sir , in the mean time?

2023-10-17 16:16 UTC, SSwiniarski commented
> > @Anudhyan Passing this on to a second review.
> 
> Then what will I have to do in the mean time ,sir? @SSwiniarski

@Anudhyan you don't have to do anything unless the second review comes up with more changes.

2023-10-17 20:00 UTC, caupolicandiaz approved these changes
@Anudhyan @SSwiniarski Just made a few small direct edits. This is good to merge

2023-10-18 12:56 UTC, merged