[Term Entry] Python Strings `.maketrans()` method
Codecademy/docs pull request #3623
Opened 2023-10-16 12:05 UTC by manviii27

### Description

A new term entry for Python Strings `.maketrans()` method.
Close #3330 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-16 20:41 UTC, caupolicandiaz requested changes
@manviii27 I've added my comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-10-16 20:41 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/maketrans/maketrans.md
> +Title: '.maketrans()'
```suggestion
Title: 'maketrans()'

```

2023-10-16 20:41 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/maketrans/maketrans.md
> +Description: 'Used to construct the transition table.'
```suggestion
Description: 'Returns a transition table based on the given strings.'

```

2023-10-16 20:41 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/maketrans/maketrans.md
> +The **`.maketrans()`** method is used for creating a translation table that can be used to perform character replacements or translations in strings. This method is particularly useful when you want
```suggestion
The **`maketrans()`** method is used for creating a translation table that can be used to perform character replacements or translations in strings. This method is particularly useful when there is a need to replace specific characters or substrings with other characters, or to remove certain characters from a string.

```

2023-10-16 20:41 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/maketrans/maketrans.md
> +The `.maketrans()` method returns a translation table, which can then be used with the `.translate()` method to perform the actual translations or replacements in a string.
```suggestion
The `maketrans()` method returns a translation table, which can then be used with the `translate()` method to perform the actual translations or replacements in a string.

```

2023-10-16 20:41 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/maketrans/maketrans.md
> +This example shows the use of `.maketrans()` mathod to replace characters in a string.
```suggestion
This example shows the use of `maketrans()` method to replace characters in a string.

```

2023-10-16 20:41 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/maketrans/maketrans.md
> +The following code is runnable and uses the `.maketrans()` method.
```suggestion
The following code is runnable and uses the `maketrans()` method.

```

2023-10-16 20:41 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/maketrans/maketrans.md
> +trans_table = str.maketrans('aeiou', '12345', 'l')
This is the same example as above. We do not include duplicates within and entry, ideally every example should be demonstrating some new functionality of the method. Please revise the example or delete it

2023-10-17 05:36 UTC, manviii27 commented
@caupolicandiaz I've made the changes, please review.

2023-10-17 17:34 UTC, caupolicandiaz approved these changes
@manviii27 This is ready for a second review

2023-10-18 16:56 UTC, SSwiniarski approved these changes
@manviii27 @caupolicandiaz Looks good.

2023-10-18 16:58 UTC, merged