[Term Entry] CSS Animation Timing Function
Codecademy/docs pull request #3656
Opened 2023-10-17 09:52 UTC by Arv4ix

### Description

-Added the Animation-Timing-Function to CSS Animations.
-Closes issue #[Edit] CSS [Edit] CSS Animations: animation-timing-function #3529 

### Type of Change

- Adding a new entry
- Adding a new image

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-18 16:46 UTC, SSwiniarski requested changes
@Arv4ix I did a first review and made a few comments. Most important is you need to add images that illustrate the animations in the example.

2023-10-18 16:46 UTC, SSwiniarski commented on content/css/concepts/animations/terms/animation-timing-function/animation-timing-function.md
> +  - 'paths/git-and-github'
```suggestion
  - 'learn-css'
  - 'paths/front-end-engineer-career-path'
  - 'paths/full-stack-engineer-career-path'
```
This change makes no sense as this isn't a GitHub topic

2023-10-18 16:46 UTC, SSwiniarski commented on content/css/concepts/animations/terms/animation-timing-function/animation-timing-function.md
> +**Note**
```suggestion

```

2023-10-18 16:46 UTC, SSwiniarski commented on media/css-animation-function-1.png
This isn't used because the html is rendered as code. What media we need is .gif animations of the animation examples given that can be added to the entry. To do this follow the Markdown syntax for adding images, and follow the instructions about file hosting in the style guide [here](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#file-hosting).

So, remove this image and add two GIFs that illustrate the animation examples.

2023-10-27 16:02 UTC, SSwiniarski commented
@Arv4ix you haven't uploaded the .gifs to the media folder, and you need to delete the original message. Also, your image links must conform to the instructions in the style guide [here](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#file-hosting).

2023-11-19 23:54 UTC, caupolicandiaz commented
@Arv4ix It's been several weeks and there hasn't been any activity on this. Are you still available to complete this entry?

2023-11-26 18:32 UTC, closed without merging