[Term Entry] Lua Math .abs()
Codecademy/docs pull request #3671
Opened 2023-10-18 18:44 UTC by parthrc

### Description

Added the math.abs() term for Lua
Closes issue #3385 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-18 18:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3671) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3671) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3671) it.</sub>

2023-10-18 19:57 UTC, caupolicandiaz requested changes
@parthrc I've added my comments. Please update the entry, and tag me when you've finished making the changes. Thanks

2023-10-18 19:57 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/abs/abs.md
> +Description: 'Converts given number to absolute value'
```suggestion
Description: 'Returns the absolute value of a given number.'
```

2023-10-18 19:57 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/abs/abs.md
> +The **`abs()`** function in Lua's math library converts a number  to its absolute value.
```suggestion
The **`abs()`** function in Lua's math library returns the absolute value of a given number.
```

2023-10-18 19:57 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/abs/abs.md
> +- `number`: The number.
```suggestion
- `number`: The number to be addressed.
```

2023-10-18 19:57 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/abs/abs.md
> +In this example, `math.abs()` converts -5 to 5.
```suggestion
This example demonstrates a basic implementation of `math.abs()`.
```

2023-10-18 19:57 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/abs/abs.md
> +In this example, `math.abs()` converts -5 to 5.
Including the output here is redundant

2023-10-19 04:40 UTC, parthrc commented
Hey @caupolicandiaz done with changes.

2023-10-19 16:54 UTC, caupolicandiaz approved these changes
@parthrc This is ready for a second review

2023-10-23 16:37 UTC, SSwiniarski approved these changes
@parthrc Looks good.

2023-10-23 16:50 UTC, merged