Create encode.md for Python Strings .encode()
Codecademy/docs pull request #3675
Opened 2023-10-18 22:54 UTC by reganmarie

### Description

- Closes #3272 
- Created encode.md on docs/content/python/concepts/strings/terms/encode/encode.md
- Added Title, Description, Subjects, Tags, and Catalog Content
- Added description, syntax, example, and codebyte example
- Ran through 3 online plagiarism checkers to ensure 100% unique wording and description, passed with 100%
- Followed content and style guidelines -Checked for spelling and grammar errors
- Read over initial draft to correct for clarity and readability

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-19 19:23 UTC, caupolicandiaz requested changes
@reganmarie I've completed my initial review. Please update the entry, and tag me when you've finished making the changes. Thanks

2023-10-19 19:23 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/encode/encode.md
> +In the following example, the `.encode()` method is called twice. The first call does not specify the optional parameters, so the string is encoded in UTF-8 and will throw a `UnicodeDecodeError` if t
```suggestion
In the following example, the `.encode()` method is called twice. The first call does not specify the optional parameters, so the string is encoded in UTF-8 and will throw a `UnicodeDecodeError` if there is failure. The second call specifies that the string will be encoded using `ascii` and that errors will be handled using `xmlcharrefreplace`.
```

2023-10-19 19:23 UTC, caupolicandiaz commented on content/python/concepts/strings/terms/encode/encode.md
> +print("ASCII example:", ascii_example)
```suggestion
print("UTF-16 example:", utf_16_example)
```

2023-10-19 19:36 UTC, reganmarie commented
@caupolicandiaz Made the following requested changes! 
- Changed line 29 to the `\uNNNN` characters
- Changed line 30 to the `\N{...}` characters
- Changed line 34 to ascii rather than ASCII
- Changed line 66 to ("UTF-16 example:", utf_16_example)

2023-10-20 18:04 UTC, caupolicandiaz approved these changes
@reganmarie This is ready for a second review.

2023-10-20 18:12 UTC, reganmarie commented
Thank you @caupolicandiaz! 😊

2023-10-23 16:15 UTC, SSwiniarski approved these changes
@reganmarie Fixed one typo and it looks good to merge.

2023-10-23 16:17 UTC, merged

2023-10-23 16:55 UTC, reganmarie commented
Thank you @SSwiniarski! 😊