[Term Entry] Kotlin Math .sqrt()
Codecademy/docs pull request #3676
Opened 2023-10-19 09:56 UTC by rahul0x00

### Description

Closes #3631 
Added new Term Entry for Kotlin Math.sqrt()

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-19 19:41 UTC, caupolicandiaz requested changes
@rahul0x00 I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

2023-10-19 19:41 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sqrt/sqrt.md
> +Title: 'Math.sqrt()'
```suggestion
Title: 'sqrt()'
```

2023-10-19 19:41 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sqrt/sqrt.md
> +  - 'Programming'
```suggestion
  - 'Code Foundations'
```

2023-10-19 19:41 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sqrt/sqrt.md
> +The **`Math.sqrt()`** method in Kotlin's `Math` class is used to calculate the square root of a given number.
```suggestion
The **`math.sqrt()`** method in Kotlin's `math` class is used to calculate the square root of a given number.
```

2023-10-19 19:41 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sqrt/sqrt.md
> +val squareRoot = Math.sqrt(number)
```suggestion
import kotlin.math.sqrt
val squareRoot = sqrt(number)
```

2023-10-19 19:41 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sqrt/sqrt.md
> +- `number`: The number for which you want to calculate the square root. It should be a non-negative value (zero or a positive number).
```suggestion
- `number`: The number for which you want to calculate the square root. It should be a non-negative value (zero or a positive number) of type `Double` or `Float`.
```

2023-10-19 19:41 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sqrt/sqrt.md
> +The `Math.sqrt()` method returns a value of type `Double` representing the square root of the input number. The result is a non-negative value or NaN if the input is negative.
```suggestion
The method returns a number, of the same type given, representing the square root. The result is a non-negative value or `NaN` if the input is negative.
```

2023-10-19 19:41 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sqrt/sqrt.md
> +This example shows how to use the `Math.sqrt()` method to calculate the square root of a number:
```suggestion
This example shows how to use the `sqrt()` method to calculate the square root of a number:
```

2023-10-19 19:41 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sqrt/sqrt.md
> +```kotlin
```suggestion
```kotlin
import kotlin.math.sqrt
```

2023-10-19 19:41 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sqrt/sqrt.md
> +    val squareRoot = Math.sqrt(number)
```suggestion
    val squareRoot = sqrt(number)
```

2023-10-20 02:20 UTC, rahul0x00 commented
@caupolicandiaz updated the entry

2023-10-20 06:50 UTC, aman79lb commented
brother , how to pass checks and why my pull request is not getting reviewed , it is named " Create lambda.md " in the pull requests.

2023-10-20 06:57 UTC, rahul0x00 commented
> brother , how to pass checks and why my pull request is not getting reviewed , it is named " Create lambda.md " in the pull requests.

Because you've put your PR in draft

2023-10-20 17:34 UTC, caupolicandiaz approved these changes
@rahul0x00 This is ready for a second review.

2023-10-23 16:09 UTC, SSwiniarski approved these changes
@rahul0x00 Made one change to remove an instance of "you" and this looks good to go.

2023-10-23 16:10 UTC, merged