[Term Entry] Kotlin Math .sinh()
Codecademy/docs pull request #3677
Opened 2023-10-19 10:10 UTC by rahul0x00

### Description

Added Term Entry for Kotlin Math.sinh()
Closes #3630 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-19 19:55 UTC, caupolicandiaz requested changes
@rahul0x00 I've added my comments. Please update, and tag me for another review.

2023-10-19 19:55 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sinh/sinh.md
> +Title: 'Math.sinh()'
```suggestion
Title: 'sinh()'
```

2023-10-19 19:55 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sinh/sinh.md
> +  - 'Programming'
```suggestion
  - 'Code Foundations'
```

2023-10-19 19:55 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sinh/sinh.md
> +  - 'Programming'
There should only be items from our subjects.md listed here (2 item max)

2023-10-19 19:55 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sinh/sinh.md
> +The **`Math.sinh()`** method in Kotlin's `Math` class is used to calculate the hyperbolic sine of a given number.
```suggestion
The **`math.sinh()`** method in Kotlin's `math` class is used to calculate the hyperbolic sine of a given number.
```

2023-10-19 19:55 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sinh/sinh.md
> +val hyperbolicSine = Math.sinh(number)
```suggestion
import kotlin.math.sinh
val hyperbolicSine = sinh(number)
```

2023-10-19 19:55 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sinh/sinh.md
> +- `number`: The number for which you want to calculate the hyperbolic sine.
```suggestion
- `number`: The number, of type `Double` or `Float`, to be used in the calculation of the hyperbolic sine.
```

2023-10-19 19:55 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sinh/sinh.md
> +The `Math.sinh()` method returns a value of type `Double` representing the hyperbolic sine of the input number.
```suggestion
```

2023-10-19 19:55 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sinh/sinh.md
> +This example shows how to use the `Math.sinh()` method to calculate the hyperbolic sine of a number:
```suggestion
This example shows how to use the `sinh()` method to calculate the hyperbolic sine of a number:
```

2023-10-19 19:55 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sinh/sinh.md
> +```kotlin
```suggestion
```kotlin
import kotlin.math.sinh
```

2023-10-19 19:55 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sinh/sinh.md
> +    val hyperbolicSine = Math.sinh(number)
```suggestion
    val hyperbolicSine = sinh(number)
```

2023-10-20 02:22 UTC, rahul0x00 commented
@caupolicandiaz updated the entry

2023-10-20 17:46 UTC, caupolicandiaz approved these changes
@rahul0x00 This is ready for a second review.

2023-10-23 16:03 UTC, SSwiniarski approved these changes
@rahul0x00 I made one minor spacing edit. Now it looks good to go.

2023-10-23 16:05 UTC, merged