[Term Entry] Kotlin Math .sin()
Codecademy/docs pull request #3678
Opened 2023-10-19 10:22 UTC by rahul0x00

### Description
Added Entry for Kotlin Math.sin() 
Closes #3629 

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-19 19:59 UTC, caupolicandiaz requested changes
@rahul0x00 Please update, and tag when complete. Thanks

2023-10-19 19:59 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sin/sin.md
> +Title: 'Math.sin()'
```suggestion
Title: 'sin()'
```

2023-10-19 19:59 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/sin/sin.md
> +Title: 'Math.sin()'
This entry has many of the same issues as the other math submissions you've completed. Please look at the previously reviewed entries and make the required updates.

2023-10-20 02:23 UTC, rahul0x00 commented
@caupolicandiaz updated the entry

2023-10-20 17:50 UTC, caupolicandiaz commented
> @caupolicandiaz updated the entry

This is not complete. Almost all the same edits made in the other kotlin math entries you made are applicable here. I did not individually highlight them, but you should be able to compare and make the changes.

2023-10-22 13:39 UTC, rahul0x00 commented
@caupolicandiaz Hi, can you review the changes?

2023-10-23 18:18 UTC, caupolicandiaz approved these changes
@rahul0x00 I made a few additional direct edits. This is ready for a second review.

2023-10-27 16:33 UTC, SSwiniarski approved these changes
@rahul0x00 Looks good.

2023-10-27 16:35 UTC, merged