Term entry atanh.md
Codecademy/docs pull request #3696
Opened 2023-10-21 06:18 UTC by Kadif-Ravik

### Description

Term entry for kotlin.math.atanh()

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-21 06:21 UTC, Kadif-Ravik commented
uhg

2023-10-21 21:34 UTC, caupolicandiaz requested changes
@Kadif-Ravik I've added my comments. Please update the entry, and tag me when you've finished making the changes. Thanks

2023-10-21 21:34 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/atanh/atanh.md
> +Description: 'Calculates the inverse hyperbolic tangent of a value'
```suggestion
Description: 'Calculates the inverse hyperbolic tangent of a value.'
```

2023-10-21 21:34 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/atanh/atanh.md
> +## Syntax:
```suggestion
## Syntax
```

2023-10-21 21:34 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/atanh/atanh.md
> +val y = Math.atanh(x)
```suggestion
val y = math.atanh(x)
```

2023-10-21 21:34 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/atanh/atanh.md
> +- `x`: A number between `-1.0` and `1.0`, of datatype `Double` or `Float`.
```suggestion
- `x`: A number between `-1.0` and `1.0`, of type `Double` or `Float`.
```

2023-10-21 21:34 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/atanh/atanh.md
> +The `math.atanh(x)` method returns the value `y` such that `tanh(y) == x`
```suggestion
The following code is a basic implementation of `math.atanh()`.
```

2023-10-21 21:34 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/atanh/atanh.md
> +## Example:
```suggestion
## Example
```

2023-10-21 21:34 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/atanh/atanh.md
> +```
These lines should come after the syntax section and before the example. And generally we do not use a code block for the special cases

2023-10-21 21:34 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/atanh/atanh.md
> +  println('$y')
```suggestion
  println(y)
```

2023-10-22 21:48 UTC, Kadif-Ravik commented
@caupolicandiaz I think i got it.

2023-10-23 16:12 UTC, Kadif-Ravik commented
@caupolicandiaz

2023-10-23 19:50 UTC, caupolicandiaz approved these changes
@Kadif-Ravik I made a few additional direct edits. Looks good for a second review

2023-10-23 19:52 UTC, Kadif-Ravik commented
@caupolicandiaz dunno how I overlooked the special cases. thanks

2023-10-25 17:16 UTC, Kadif-Ravik commented
@caupolicandiaz @SSwiniarski

2023-10-25 17:18 UTC, SSwiniarski approved these changes
@Kadif-Ravik Looks good.

2023-10-25 17:20 UTC, merged