[Term Entry] Kotlin Math .exp()
Codecademy/docs pull request #3698
Opened 2023-10-21 16:20 UTC by vaisrinivasan

### Description

I created the exp.md in Kotlin > concepts > math-methods > terms directory.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-21 18:20 UTC, vaisrinivasan commented
Hi. Need some help with the markdown part (The initial one). 
`---
Title: 'sqrt()'
Description: 'Calculates the square root of a given number.'
Subjects:
  - 'Code Foundations'
  - 'Computer Science'
Tags:
  - 'Math'
  - 'Functions'
    CatalogContent:
  - 'learn-kotlin'
  - 'paths/computer-science'
---`
Whichever solution I try, it doesn't come as a table like given in the template and hence the test is failing.

2023-10-21 21:17 UTC, caupolicandiaz requested changes
@vaisrinivasan I've completed my initial review. Please update the entry, and tag me when you've made the changes. Thanks

2023-10-21 21:17 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/exp/exp.md
> +Description: 'Calculates the Euler's number e raised to the power of the value of a given number.'
```suggestion
Description: 'Returns e raised to the power of a given number.'
```

2023-10-21 21:17 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/exp/exp.md
> +The **`exp()`** method in Kotlin's `math` class is used to calculate the Euler's number e raised to the power of the value of the given number.
```suggestion
The **`exp()`** method in Kotlin's `math` class is used to calculate Euler's number *e* raised to the power of a given number.
```

2023-10-21 21:17 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/exp/exp.md
> +- `number`: The number for which you want to calculate the Euler's number e raised to the power. It should be of type `Double` or `Float`.
```suggestion
- `number`: A number of type `Double` or `Float`. The method returns a number, of the same type given.
```

2023-10-21 21:17 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/exp/exp.md
> +The method returns a number, of the same type given.
```suggestion
```

2023-10-21 21:17 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/exp/exp.md
> +This example shows how to use the `exp()` method to calculate the Euler's number e raised to the power of the value of the given number.
```suggestion
This example demonstrates a basic implementation of the `exp()` method.
```

2023-10-21 21:17 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/exp/exp.md
> +    println("The Euler's number e raised to the power of $number is $ePowNumber.")
```suggestion
    println("Euler's number e raised to the power of $number is $ePowNumber.")
```

2023-10-21 21:17 UTC, caupolicandiaz commented on content/kotlin/concepts/math-methods/terms/exp/exp.md
> +The Euler's number e raised to the power of 3.0 is 20.085536923187668.
```suggestion
Euler's number e raised to the power of 3.0 is 20.085536923187668.
```

2023-10-22 07:53 UTC, vaisrinivasan commented
@caupolicandiaz : I've addressed the review comments and all the checks are passing. Please re-review.
I haven't done the below checks as the review is already happening in this PR. Let me know if I've to push from a branch named after the changes I'm making and I'll be happy to accommodate the same.

 I have confirmed my changes are not being pushed from my forked main branch.
 I have confirmed that I'm pushing from a new branch named after the changes I'm making.

2023-10-23 18:11 UTC, caupolicandiaz approved these changes
@vaisrinivasan This is ready for a second review.

2023-10-26 08:34 UTC, vaisrinivasan commented
Hi. Can I get a second review for this? Thanks.

2023-10-26 17:39 UTC, caupolicandiaz commented
> Hi. Can I get a second review for this? Thanks.

Please be patient, there are many PRs and few maintainers

2023-10-27 15:48 UTC, SSwiniarski approved these changes
@vaisrinivasan Looks good.

2023-10-27 15:50 UTC, merged