[Concept Entry] C# Classes
Codecademy/docs pull request #3700
Opened 2023-10-22 02:32 UTC by narcissus123

### Description

- Added classes concept for C# and an image for the partial classes subsection.
- Closes Issue #2758

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-22 13:40 UTC, SSwiniarski requested changes
@narcissus123 I did a first review and left a couple of comments.

2023-10-22 13:40 UTC, SSwiniarski commented on content/c-sharp/concepts/classes/classes.md
> +To declare a class in C#, you use the `class` keyword, followed by the class name. Class names should follow C# naming conventions (typically using PascalCase). The class definition is enclosed withi
```suggestion
To declare a class in C#, use the `class` keyword, followed by the class name. Class names should follow C# naming conventions (typically using PascalCase). The class definition is enclosed within curly braces {}.
```

2023-10-22 13:40 UTC, SSwiniarski commented on content/c-sharp/concepts/classes/classes.md
> +```cs
Have a sentence introducing this code block and explaining its relationship to the image.

2023-10-25 14:19 UTC, narcissus123 commented
@SSwiniarski, thank you for your initial review. I have applied the changes. If you have any additional feedback or require further adjustments, please let me know.

2023-10-25 16:09 UTC, SSwiniarski approved these changes
@narcissus123 Looks good for a second review.

2023-10-30 18:39 UTC, narcissus123 commented
@SSwiniarski, may I ask how long it takes for my pull request to go through a second review? I'm really looking forward to getting my entry in for Hacktoberfest.

2023-10-30 23:11 UTC, caupolicandiaz approved these changes
@narcissus123 @SSwiniarski Overall, looks good. Just made a few minor language and formatting edits. This is ready to merge

2023-10-31 11:35 UTC, merged

2023-10-31 12:10 UTC, narcissus123 commented
@SSwiniarski @caupolicandiaz Thank you so much for reviewing and accepting my pull request.