Update machine-learning.md
Codecademy/docs pull request #3703
Opened 2023-10-22 05:59 UTC by Pratikdate

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [# ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-22 05:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3703) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3703) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3703) it.</sub>

2023-10-22 06:04 UTC, Pratikdate commented
Please add hactoberfest-accepted lable

2023-10-22 13:45 UTC, SSwiniarski requested changes
@Pratikdate I did a first review and left a few comments.

2023-10-22 13:45 UTC, SSwiniarski commented on content/ai/concepts/machine-learning/machine-learning.md
> +
```suggestion
```
Remove blank line

2023-10-22 13:45 UTC, SSwiniarski commented on content/ai/concepts/machine-learning/machine-learning.md
> +Based on the evaluation results, you might fine-tune the model's hyperparameters or adjust the model architecture to improve its performance.There are several methods to fine-tune models.
```suggestion
Based on the evaluation results, the model's user might fine-tune the model's hyperparameters or adjust the model architecture to improve its performance. There are several methods to fine-tune models.
```
We avoid first- and second-person pronouns in Docs.

2023-10-22 13:45 UTC, SSwiniarski commented on content/ai/concepts/machine-learning/machine-learning.md
> +  - Hyperparameter Tuning:Hyperparameters are configuration settings for a machine learning model that are not learned during training but are set before training begins. These settings can significa
```suggestion
  - Hyperparameter Tuning: Hyperparameters are configuration settings for a machine learning model that are not learned during training but are set before training begins. These settings can significantly impact a model's performance.
```

2023-10-22 13:45 UTC, SSwiniarski commented on content/ai/concepts/machine-learning/machine-learning.md
> +  - Model Architecture Adjustments:There are several methods to accurately adjust the Architecture of ML algorithms.There are some technique such as Feature Engineering,Model Selection,Ensemble Metho
```suggestion
  - Model Architecture Adjustments: There are several methods to accurately adjust the Architecture of ML algorithms. There are techniques such as Feature Engineering, Model Selection, and Ensemble Methods .
```

2023-10-22 13:45 UTC, SSwiniarski commented on content/ai/concepts/machine-learning/machine-learning.md
> +
```suggestion
```
Remove blank line.

2023-10-22 14:37 UTC, SSwiniarski approved these changes
@Pratikdate Looks good for a second review.

2023-10-31 05:07 UTC, KTom101 approved these changes
@Pratikdate I added some minor changes directly, there were a couple of things in the original content I cleaned up. I also ran `npm run format:all` to fix the failed [checks](https://www.codecademy.com/resources/docs/contribution-guide/getting-set-up-on-your-computer#:~:text=There%20are%20continuous%20integration%20(CI)%20workflows).

2023-10-31 05:07 UTC, merged