add: Fork concept under git category
Codecademy/docs pull request #3705
Opened 2023-10-22 11:19 UTC by singodiyashubham87

### Description
Closes #3650 

I have added "Fork" as a new entry under the git category

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-22 11:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3705) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3705) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3705) it.</sub>

2023-10-22 13:53 UTC, SSwiniarski requested changes
@singodiyashubham87 I did a first review and left a few comments. Maybe most important is you're missing a description of forking from the command line. This is an entry on Git, the command line tool, not GitHub. Please add that information to this entry.

2023-10-22 13:53 UTC, SSwiniarski commented on content/git/concepts/fork/fork.md
> +**Fork** is making a duplicate of an existing repository. This "fork" becomes a separate undertaking that you are in charge of. Collaboration, experimentation, and contributions to open-source code a
```suggestion
A **fork** is making a duplicate of an existing repository. This "fork" becomes a separate undertaking that the user is in charge of. Collaboration, experimentation, and contributions to open-source code are made possible by forking. It enables developers worldwide to collaborate, make changes, and contribute to projects while retaining the integrity of the source code. It is a secure approach to modify and test code without changing the original.
```
We avoid first- and second-person pronouns in docs.

2023-10-22 13:53 UTC, SSwiniarski commented on content/git/concepts/fork/fork.md
> +### Step 1
Instead of headers, use a bulleted list, and remove the second-person pronouns ("you")

2023-10-22 13:53 UTC, SSwiniarski commented on content/git/concepts/fork/fork.md
> +![Repo page with Fork button](https://i.imgur.com/000HPJD.png)
If you want to put an image here, follow the instructions on hosting media in the style guide [here](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#file-hosting).

2023-10-22 13:53 UTC, SSwiniarski commented on content/git/concepts/fork/fork.md
> +This will create a new copy of the original "Codecademy/docs" repository into your account on which you can work.
```suggestion
This will create a new copy of the original "Codecademy/docs" repository.
```

2023-10-26 04:26 UTC, singodiyashubham87 commented
@SSwiniarski Kindly validate  and merge my PR.

2023-10-26 16:50 UTC, SSwiniarski commented
@singodiyashubham87 you still need to address my comments about adding details about using fork on the command line. This is an entry on Git, the command line tool, not GitHub. Please add that information to this entry.

2023-10-27 06:00 UTC, singodiyashubham87 commented
@SSwiniarski I've added the steps to fork using terminal

2023-10-27 11:58 UTC, SSwiniarski requested changes
@singodiyashubham87 I have a few more comments.

2023-10-27 11:58 UTC, SSwiniarski commented on content/git/concepts/fork/fork.md
> +First the user login to his/her GitHub account using the command
```suggestion
First the user must login to his/her GitHub account using the command:
```

2023-10-27 11:58 UTC, SSwiniarski commented on content/git/concepts/fork/fork.md
> +After successful login, the user can fork the repository using the command
```suggestion
After successful login, the user can fork the repository using the command:
```

2023-10-27 11:58 UTC, SSwiniarski commented on media/fork.png
You should remove this image since you no longer use it.

2023-10-27 11:58 UTC, SSwiniarski commented on content/git/concepts/fork/fork.md
> +## Steps to Fork a Repository
You should note that the fork command is provided by a separate command line tool than Git.

2023-10-27 13:51 UTC, singodiyashubham87 commented
@SSwiniarski Done!

2023-10-27 15:44 UTC, SSwiniarski approved these changes
@singodiyashubham87 Looks good for a second review.

2023-10-27 22:17 UTC, caupolicandiaz requested changes
@singodiyashubham87 I've added my initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-10-27 22:17 UTC, caupolicandiaz commented on content/git/concepts/fork/fork.md
> +Description: 'Making a duplicate of a repository to work on separately is known as forking.'
```suggestion
Description: 'A duplicate of a repository that resides within the independent directories of a contributor.'
```

2023-10-27 22:17 UTC, caupolicandiaz commented on content/git/concepts/fork/fork.md
> +  - 'Web Development'
```suggestion
```

2023-10-27 22:17 UTC, caupolicandiaz commented on content/git/concepts/fork/fork.md
> +  - 'Web Development'
subjects should only contain 2 items

2023-10-27 22:17 UTC, caupolicandiaz commented on content/git/concepts/fork/fork.md
> +  - 'learn-git'
```suggestion
  - 'learn-git'
  - 'learn-the-command-line'
```

2023-10-27 22:17 UTC, caupolicandiaz commented on content/git/concepts/fork/fork.md
> +A **fork** is making a duplicate of an existing repository. This "fork" becomes a separate undertaking that the user is in charge of. Collaboration, experimentation, and contributions to open-source
```suggestion
A **fork** is a duplicate of an existing repository. This "fork" is an independent entity that allows a contributor to interact with the original repository. Collaboration, experimentation, and contributions to open-source code are made possible by forking. It enables developers worldwide to collaborate, make changes, and contribute to projects while retaining the integrity of the source code. It is a secure approach to modify and test code without making changes directly to the original.
```

2023-10-27 22:17 UTC, caupolicandiaz commented on content/git/concepts/fork/fork.md
> +
It may be helpful for those less familiar with Git/version control to mention where to acquire a link for a given repo

2023-10-30 14:32 UTC, singodiyashubham87 commented
@caupolicandiaz @SSwiniarski Kindly merge the PR.

2023-10-30 17:45 UTC, caupolicandiaz commented
@singodiyashubham87 The PR can't be merged until the CLA is signed

2023-10-30 17:46 UTC, singodiyashubham87 commented
@caupolicandiaz But I've already signed the CLA.

2023-10-30 17:48 UTC, singodiyashubham87 commented
@caupolicandiaz See 
![image](https://github.com/Codecademy/docs/assets/93720428/1f555e5e-002e-4b44-8f2d-cd2953d65e73)

2023-10-30 18:01 UTC, merged

2023-10-30 18:02 UTC, caupolicandiaz commented
> @caupolicandiaz See
> ![image](https://user-images.githubusercontent.com/93720428/279149751-1f555e5e-002e-4b44-8f2d-cd2953d65e73.png)

my mistake