Edited the syntax and examples for border-left.md
Codecademy/docs pull request #3710
Opened 2023-10-22 14:00 UTC by SanchitMahajan236

### Description

Closes #3641 
I edited border-left.md as per the issue assigned to me. I added more description of the syntax and make the "note:" line a blockquote as per the style guide, and also an additional example reflecting how border-right does not require 3 parameters and will assign default values.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-22 14:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3710) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3710) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3710) it.</sub>

2023-10-22 14:11 UTC, SSwiniarski requested changes
@SanchitMahajan236 I did a first review and you need to upload the images and change the links in line with our You need to follow the instructions for file hosting as described in the style guide [here](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md)..

2023-10-22 14:11 UTC, SSwiniarski commented on content/css/concepts/borders/terms/border-left/border-left.md
> +![Example 1](https://github.com/SanchitMahajan236/Codeacademy_docs/assets/116559051/2fe25faa-9e11-4095-a0e7-cb71ce6a7a39)
You need to follow the instructions for file hosting as described in the style guide [here](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md).

2023-10-22 14:11 UTC, SSwiniarski commented on content/css/concepts/borders/terms/border-left/border-left.md
> +![Example 2](https://github.com/SanchitMahajan236/Codeacademy_docs/assets/116559051/fcd95df2-78c2-4f57-9ca1-7b42334110cb)
You need to follow the instructions for file hosting as described in the style guide [here](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md).

2023-10-22 14:11 UTC, SSwiniarski commented on content/css/concepts/borders/terms/border-left/border-left.md
> +![Example 3](https://github.com/SanchitMahajan236/Codeacademy_docs/assets/116559051/9f4a99e3-9ecc-45f0-bb64-153c3fa9a611)
You need to follow the instructions for file hosting as described in the style guide [here](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md).

2023-10-23 11:41 UTC, SSwiniarski approved these changes
@SanchitMahajan236 Looks good for a second review.

2023-10-23 20:33 UTC, caupolicandiaz approved these changes
@SanchitMahajan236 @SSwiniarski LGTM

2023-10-23 20:35 UTC, caupolicandiaz commented
@SanchitMahajan236 The CLA needs to be updated

2023-10-24 04:54 UTC, SanchitMahajan236 commented
> @SanchitMahajan236 The CLA needs to be updated

@caupolicandiaz Done

2023-10-24 12:04 UTC, merged