Added the new term entry binascii module in python
Codecademy/docs pull request #3749
Opened 2023-10-24 03:41 UTC by Atharva1723

ruby9940067347

### Description

### Type of Change
Added a new term entry regarding the inbuilt binascii module in Python

### Checklist

- [✔ ] All writings are my own.
- [ ✔] My entry follows the Codecademy Docs style guide.
- [✔ ] My changes generate no new warnings.
- [✔ ] I have performed a self-review of my own writing and code.
- [✔ ] I have checked my entry and corrected any misspellings.
- [✔ ] I have made corresponding changes to the documentation if needed.
- [✔ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ✔] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [✔ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-24 15:49 UTC, SSwiniarski requested changes
@Atharva1723 I did a first review and left some comments.

2023-10-24 15:49 UTC, SSwiniarski commented on content/python/concepts/binascii-module/binascii-module.md
> +Description: 'The Python `binascii` module is a built-in module that provides essential functions for working with binary data and performing binary-to-text encoding and decoding. It is a valuable re
```suggestion
Description: 'The binascii module is a built-in module that provides essential functions for working with binary data and performing binary-to-text encoding and decoding.'
```

2023-10-24 15:49 UTC, SSwiniarski commented on content/python/concepts/binascii-module/binascii-module.md
> +The **`binascii`** module contains a number of methods to convert between binary and various ASCII-encoded binary representations. Normally, you will not use these functions directly but use wrapper
```suggestion
The **`binascii`** module contains a number of methods to convert between binary and various ASCII-encoded binary representations. . It is a valuable resource when dealing with binary data in various contexts, such as network protocols and file handling. Normally, the programmer will not use these functions directly but use wrapper modules like `uu` or `base64` instead. The `binascii` module contains low-level functions written in C for greater speed that are used by the higher-level modules. The Python binascii module is a valuable tool when working with binary data and encoding it into different text formats or decoding text representations back into binary data.
```

2023-10-25 11:38 UTC, SSwiniarski approved these changes
@Atharva1723 made one typo edit and this looks good for a second review.

2023-10-25 12:40 UTC, Atharva1723 commented
@KTom101 @caupolicandiaz can you please review and suggest any changes to be made

2023-10-25 20:31 UTC, caupolicandiaz approved these changes
@Atharva1723 @SSwiniarski Just made a couple of additions directly. LGTM

2023-10-25 20:33 UTC, merged