Create filterNot.md #3726
Codecademy/docs pull request #3753
Opened 2023-10-24 17:04 UTC by AlstrupJacob

### Description

Closes issue 'Kotlin Strings .filterNot() #3726'

### Type of Change

created filterNot.md. entry in directory docs/content/kotlin/concepts/strings/terms/filterNot

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-24 17:52 UTC, AlstrupJacob commented
should pass now

2023-10-24 18:08 UTC, caupolicandiaz requested changes
@AlstrupJacob I've added my comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-10-24 18:08 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/filterNot/filterNot.md
> +`String`: The collection of elements to be filtered. can be any iterable dtype.
The documentation shows that this available for Strings and CharSequence

2023-10-24 18:08 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/filterNot/filterNot.md
> +`Predicate`: The collection of elements to be filtered out.
```suggestion
`predicate`: The collection of elements to be filtered out.
```

2023-10-24 18:08 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/filterNot/filterNot.md
> +The `.filterNot(predicate)` method returns the collection it was called on, with any values present in `predicate` filtered out
```suggestion
```

2023-10-24 18:08 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/filterNot/filterNot.md
> +```kotlin
```suggestion
```kotlin
fun main {
```

2023-10-24 18:08 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/filterNot/filterNot.md
> +val filteredMap2 = originalMap.filterNot { it.key == 'c'
```suggestion
val filteredMap2 = originalMap.filterNot { it.key == "c" }
```

2023-10-24 18:08 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/filterNot/filterNot.md
> +}
```suggestion

```

2023-10-24 18:08 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/filterNot/filterNot.md
> +println(filteredMap2) // {a=1, b=2}
```suggestion
println(filteredMap2) 
}
```

2023-10-24 18:08 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/filterNot/filterNot.md
> +println(filteredMap) // {b=2, c=3}
```suggestion
println(filteredMap)
```

2023-10-24 18:08 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/filterNot/filterNot.md
> +println(filteredMap) // {b=2, c=3}
the lines of the body should be indented 2 spaces

2023-10-24 18:08 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/filterNot/filterNot.md
> +In the above example .filterNot() is first used to filter out any pairs in the map with a value less than 2, leaving {b=2, c=3}, then used to filter out any pairs with the key 'c', leaving
```suggestion
The example demonstrates the use of `.filterNot()` to remove any pairs in the map with a value less than `2`, and then used to filter out any pairs with the key `"c:`.
```

2023-10-24 18:08 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/filterNot/filterNot.md
> +In the above example .filterNot() is first used to filter out any pairs in the map with a value less than 2, leaving {b=2, c=3}, then used to filter out any pairs with the key 'c', leaving
This should come after the example header and before the code block

2023-10-24 18:08 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/filterNot/filterNot.md
> +In the above example .filterNot() is first used to filter out any pairs in the map with a value less than 2, leaving {b=2, c=3}, then used to filter out any pairs with the key 'c', leaving
The output should be in a ```shell block

2023-10-24 18:28 UTC, AlstrupJacob commented
@caupolicandiaz done

2023-10-24 19:22 UTC, AlstrupJacob commented
@caupolicandiaz sorry for the bit of confusion this is my first contrib, all changes complete now

2023-10-25 19:52 UTC, caupolicandiaz approved these changes
@AlstrupJacob Just made a couple of direct edits to update the spacing. This is ready for a second review.

2023-10-28 15:02 UTC, SSwiniarski approved these changes
@AlstrupJacob Looks good.

2023-10-28 15:08 UTC, merged