Create padStart.md
Codecademy/docs pull request #3756
Opened 2023-10-25 02:23 UTC by AlstrupJacob

### Description

created padStart.md. resolves issue #3729

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-25 17:02 UTC, dakshdeepHERE requested changes
Few changes from my side.

2023-10-25 17:02 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/padStart/padStart.md
> +The **`.padStart()`** method will pad the start of the sequence with the desired fill character to the specified length, returning the new character seuqence.
```suggestion
The **`.padStart()`** method will pad the start of the sequence with the desired fill character to the specified length, returning the new character sequence. **`.padStart()`** is also used for left padding. 
```

2023-10-25 17:54 UTC, AlstrupJacob commented
@dakshdeepHERE done

2023-10-25 18:16 UTC, dakshdeepHERE commented
<img width="1341" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/126a3f0c-7d48-466a-bac4-dae846555bea">
@AlstrupJacob where are the requested changes applied? The syntax is still the same.

2023-10-25 18:20 UTC, AlstrupJacob commented
> <img alt="image" width="1341" src="https://user-images.githubusercontent.com/94860622/278107912-126a3f0c-7d48-466a-bac4-dae846555bea.png"> @AlstrupJacob where are the requested changes applied? The syntax is still the same.

very strange, are they there now?

2023-10-25 18:20 UTC, dakshdeepHERE commented
> > <img alt="image" width="1341" src="https://user-images.githubusercontent.com/94860622/278107912-126a3f0c-7d48-466a-bac4-dae846555bea.png"> @AlstrupJacob where are the requested changes applied? The syntax is still the same.
> 
> very strange, are they there now?

Let me check. If they are not there I will tell you how to commit these changes easily.

2023-10-25 18:24 UTC, dakshdeepHERE requested changes

2023-10-25 18:24 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/padStart/padStart.md
> +## Examples
```suggestion
## Example
```
One change left.

2023-10-25 18:25 UTC, AlstrupJacob commented
done sorry again

2023-10-25 18:25 UTC, dakshdeepHERE commented
@AlstrupJacob commit this last change and I will do the overall review and move to 2nd review part.

2023-10-25 18:27 UTC, dakshdeepHERE commented
> done sorry again

It's okay. :)

2023-10-25 20:11 UTC, dakshdeepHERE requested changes

2023-10-25 20:20 UTC, dakshdeepHERE requested changes
Last two changes

2023-10-25 20:20 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/padStart/padStart.md
> +`padChar`: Character to be used as padding, defaults to ' '.
```suggestion
- `length`: The amount of padding to be added, in number of characters.
- `padChar`: Character to be used as padding, defaults to ' '.
```

2023-10-25 20:20 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/padStart/padStart.md
> +  }
```suggestion
fun main() {
  val str = "codecademydocs"

  val str2 = str.padStart(14)
  println(str2)

  val str3 = str.padStart(18, '-')
  println(str3)
}
```
The print the below output you'll have to do these changes. The length of the string is 14. If you use 3 and 4 the string will be printed. No padding will be there.

2023-10-25 20:20 UTC, dakshdeepHERE commented
@AlstrupJacob Last 2 changes, then we will move for 2nd review.

2023-10-25 22:14 UTC, AlstrupJacob commented
> @AlstrupJacob Last 2 changes, then we will move for 2nd review.

done

2023-10-27 17:59 UTC, dakshdeepHERE approved these changes

2023-10-27 20:05 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/padStart/padStart.md
> +Description: 'Pads the start of a character sequence with a string of the specified character and length.'
```suggestion
Description: 'Pads the start of a string with a specified character.' 
```

2023-10-27 20:10 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/padStart/padStart.md
> +String.padStart(length: Int, padChar: String): String
```suggestion
String.padStart(length, padChar)
```

2023-10-27 20:12 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/padStart/padStart.md
> +-`length`: The amount of padding to be added, in number of characters.
```suggestion
-`length`: An integer that represents the total length of the string returned (with padding).
```

2023-10-27 20:14 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/padStart/padStart.md
> +-`padChar`: Character to be used as padding, defaults to ' '.
```suggestion
-`padChar`: The character to be used (enclosed by `''`) as padding, defaults to whitespace.
```

2023-10-27 20:16 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/padStart/padStart.md
> +
```suggestion

- 'String': The string to be modified.
```

2023-10-27 20:16 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/padStart/padStart.md
> +The example demonstrates the use of `.padStart()` to pad a string.
```suggestion
The example below demonstrates the use of `.padStart()` to pad a string.
```

2023-10-27 20:16 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/padStart/padStart.md
> +  val str3 = str.padStart(18, "-")
```suggestion
  val str3 = str.padStart(18, '-')
```

2023-10-27 20:50 UTC, AlstrupJacob commented
@caupolicandiaz done

2023-10-27 21:24 UTC, caupolicandiaz approved these changes
@AlstrupJacob Looks good

2023-10-27 21:24 UTC, merged