Create endsWith.md
Codecademy/docs pull request #3757
Opened 2023-10-25 02:33 UTC by AlstrupJacob

### Description

created endsWith.md. resolves issue #3724

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-25 05:31 UTC, dakshdeepHERE requested changes
I have requested few changes. Commit then changes and add the requested things so we can move forward to the second review round.

2023-10-25 05:31 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/endsWIth/endsWith.md
> +The **`.endsWith()`** method will compare the end of the sequence with the given suffix, returning a boolean value representing wether they are the same or not.
```suggestion
The **`.endsWith()`** method compares the end of the sequence with the given suffix and returns a boolean value indicating whether they are the same or not.
```

2023-10-25 05:31 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/endsWIth/endsWith.md
> +
```suggestion
```
No need for space here

2023-10-25 05:31 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/endsWIth/endsWith.md
> +`suffix`: a sequence of length `n`, to be compared with the last `n` elements of `String`.
After this please explain `ignoreCase` too.

2023-10-25 05:31 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/endsWIth/endsWith.md
> +## Example
```suggestion
## Example

```
Add a space after the heading

2023-10-25 05:31 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/endsWIth/endsWith.md
> +String.endsWith(suffix)
```suggestion
String.endsWith(suffix: String, ignoreCase: Boolean = false): Boolean
```
Mention the `ignoreCase` parameter. By default, it stays `false`, which means this function is case-sensitive. However, if we want it to be case-insensitive, we can set `ignoreCase` to `true`.

2023-10-25 06:19 UTC, dakshdeepHERE requested changes
I have overall comment too which is about your path of `endsWith.md`. Right now it is `content/kotlin/concepts/strings/endsWIth/endsWith.md` but it should be `content/kotlin/concepts/strings/terms/endsWIth/endsWith.md`. Please fix this too.

2023-10-25 16:48 UTC, dakshdeepHERE requested changes
Have two more changes request from my side. Please commit these changes.

2023-10-25 16:48 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/endsWIth/endsWith.md
> +## Example
```suggestion
## Example

```
Add a space here

2023-10-25 16:48 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/endsWIth/endsWith.md
> +`suffix`: a sequence of length `n`, to be compared with the last `n` elements of `String`.
Add info about `ignoreCase` here please after `suffix`.

2023-10-25 16:48 UTC, dakshdeepHERE commented
@AlstrupJacob have last 2 changes request. Commit them and we will move to 2nd review.

2023-10-25 17:50 UTC, AlstrupJacob commented
> @AlstrupJacob have last 2 changes request. Commit them and we will move to 2nd review.

done

2023-10-25 20:02 UTC, dakshdeepHERE requested changes

2023-10-25 20:02 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/endsWIth/endsWith.md
> +
```suggestion
```

2023-10-25 20:10 UTC, dakshdeepHERE requested changes
One last comment from my side. There were some syntax issues with your code example.

2023-10-25 20:10 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/endsWIth/endsWith.md
> +  }
```suggestion
fun main() {
  val str = "JohnAppleseed@Hotmail.com"
  val sfx1 = "@gmail.com"
  val sfx2 = "@hotmail.com"

  val endsWithSfx1 = str.endsWith(sfx1)
  println(endsWithSfx1)

  val endsWithSfx2 = str.endsWith(sfx2, true)
  println(endsWithSfx2)
}
```
Please fix this issue with the code block

2023-10-26 05:45 UTC, dakshdeepHERE commented
@AlstrupJacob Looks good for second review.

2023-10-26 17:55 UTC, caupolicandiaz requested changes
@AlstrupJacob I've added my comments. Please update the entry, and tag me when you've finished the changes. Thanks

2023-10-26 17:55 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/endsWIth/endsWith.md
> +Title: '.endsWith()'
The path has an error. The folder name is "endsWIth" but it should be "endsWith"

2023-10-26 17:55 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/endsWIth/endsWith.md
> +Description: 'Returns a boolean value representing wether the sequence ends with the specified suffix.'
```suggestion
Description: 'Returns a boolean value representing whether the sequence ends with the specified suffix.' 

```

2023-10-26 17:55 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/endsWIth/endsWith.md
> +  - 'String'
```suggestion
  - 'Strings'

```

2023-10-26 17:55 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/endsWIth/endsWith.md
> +  - 'Kotlin'
```suggestion
```

2023-10-26 17:55 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/endsWIth/endsWith.md
> +The **`.endsWith()`** method compares the end of the sequence with the given suffix and returns a boolean value indicating wether they are the same or not.
```suggestion
The **`.endsWith()`** method compares the end of the sequence with the given suffix and returns a boolean value indicating whether they are the same or not.

```

2023-10-26 17:55 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/endsWIth/endsWith.md
> +String.endsWith(suffix: String, ignoreCase: Boolean = False): Boolean
```suggestion
String.endsWith(suffix, ignoreCase)

```

2023-10-26 17:55 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/endsWIth/endsWith.md
> +String.endsWith(suffix: String, ignoreCase: Boolean = False): Boolean
generally, data types are detailed with the parameter info below

2023-10-26 17:55 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/endsWIth/endsWith.md
> +- `suffix`: a sequence of length `n`, to be compared with the last `n` elements of `String`.
```suggestion
- `suffix`: A sequence of length `n`, to be compared with the last `n` elements of `String`.

```

2023-10-26 17:55 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/endsWIth/endsWith.md
> +- `ignoreCase`: boolean value dictating whether function is to be case insensitive. Defaults to false.
```suggestion
- `ignoreCase`: A boolean value dictating whether function is to be case insensitive. Defaults to `false`.

```

2023-10-26 17:55 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/endsWIth/endsWith.md
> +  val endsWithSfx1 = str.endsWith (sfx1)
```suggestion
  val endsWithSfx1 = str.endsWith(sfx1)

```

2023-10-26 18:00 UTC, AlstrupJacob commented
@caupolicandiaz  done

2023-10-27 17:57 UTC, dakshdeepHERE approved these changes

2023-10-27 19:23 UTC, caupolicandiaz approved these changes
@AlstrupJacob Looks good, this is ready to merge

2023-10-27 19:25 UTC, merged