[Term Entry] Kotlin Strings .removePrefix()
Codecademy/docs pull request #3758
Opened 2023-10-25 03:36 UTC by nobunagaaa

### Description

Add Term Entry for Kotlin: Strings .removePrefix()
Closes #3733 
### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-25 03:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3758) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3758) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3758) it.</sub>

2023-10-25 04:52 UTC, dakshdeepHERE requested changes
Hello, I have requested some changes. Waiting for you to apply them. Also you can try adding a working codebyte of the `removePrefix()` in the end of this entry?
<img width="1119" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/fa6e303e-24d5-4934-a1ec-63e65ed3150b">
Like this 👆🏻(Use Kotlin in place of Javascript). Looking forward to see what interesting codebyte you add.

2023-10-25 04:52 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/removePrefix/removePrefix.md
> +import kotlin.text.*
```suggestion
```
We don't have to explicitly import 'kotlin.text.*' to utilize the `removePrefix()` function in Kotlin. This function is included in the Kotlin standard library and is readily accessible for use in Kotlin code without any extra imports.

2023-10-25 04:52 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/removePrefix/removePrefix.md
> +`originalString`: The original string from which you want to remove the prefix.
```suggestion
`originalString`: The original string from which the prefix will be removed.
```
Refrain from using pronouns.

2023-10-25 04:52 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/removePrefix/removePrefix.md
> +`prefix`: The prefix you want to remove from the original string.
```suggestion
`prefix`: The prefix which will be removed from the original string.
```
Same as above, refrain from using pronouns.

2023-10-25 04:52 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/removePrefix/removePrefix.md
> +import kotlin.text.*
```suggestion
```
We don't have to explicitly import 'kotlin.text.*' to utilize the `removePrefix()` function in Kotlin. This function is included in the Kotlin standard library and is readily accessible for use in Kotlin code without any extra imports.

2023-10-25 04:52 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/removePrefix/removePrefix.md
> +
```suggestion
```

2023-10-25 04:52 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/removePrefix/removePrefix.md
> +The `removePrefix()` method returns a new `string` with the specified prefix removed if it exists. If the original string does not start with the specified prefix, the method returns the original str
```suggestion
```
Why don't we remove this part from here and place it with the definition of the function above. To be specific in the 16th line.

2023-10-25 04:52 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/removePrefix/removePrefix.md
> +val modifiedString = originalString.removePrefix(prefix)
```suggestion
val modifiedString = originalString.removePrefix(prefixToRemove)
```

2023-10-25 11:48 UTC, nobunagaaa commented
@dakshdeepHERE resolved the comments

2023-10-25 16:42 UTC, dakshdeepHERE commented
@nobunagaaa Looks good for the second review. 🚀

2023-10-25 19:23 UTC, caupolicandiaz requested changes
@nobunagaaa I've added a few additional comments. Please update the entry, and tag me when you've made the changes. Thanks

2023-10-25 19:23 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/removePrefix/removePrefix.md
> +  - 'Software Development'
```suggestion
  - 'Computer Science'
  - 'Code Foundations'
```

2023-10-25 19:23 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/removePrefix/removePrefix.md
> +  - 'paths/software-development'
```suggestion
  - 'paths/computer-science'
```

2023-10-25 19:23 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/removePrefix/removePrefix.md
> +In this example, the `removePrefix()` method is used to remove the "Hello" prefix from the original string. The result will be printed as:
```suggestion
The result will be printed as:
```

2023-10-25 19:23 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/removePrefix/removePrefix.md
> +```
kotlin is not currently supported by Codecademy, so this will not run. Please remove this example

2023-10-26 03:34 UTC, nobunagaaa commented
@caupolicandiaz Hi, i've made the suggested changes

2023-10-26 17:35 UTC, caupolicandiaz approved these changes
@nobunagaaa This is all set. The one element that is outstanding is the CLA. Please update

2023-10-26 17:55 UTC, nobunagaaa commented
@caupolicandiaz signed the cla

2023-10-27 06:56 UTC, dakshdeepHERE commented
Hey @nobunagaaa you missed one of change request.

2023-10-27 07:02 UTC, dakshdeepHERE submitted a review, later dismissed
You missed this one last thing

2023-10-27 07:38 UTC, nobunagaaa commented
> You missed this one last thing

Sorry about that, commited the suggestion

2023-10-27 07:48 UTC, dakshdeepHERE commented
@nobunagaaa no issues. This looks good to me @caupolicandiaz.

2023-10-27 16:18 UTC, merged