Create asin.md
Codecademy/docs pull request #3761
Opened 2023-10-25 10:34 UTC by HKABIG

created asin.md in accordance to the guidelines provided

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-25 10:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3761) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3761) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3761) it.</sub>

2023-10-25 20:14 UTC, avdhoottt requested changes
@HKABIG Firstly, creating a PR on the main branch is discouraged, Consider using a new branch. I've mentioned some changes, please correct them.

2023-10-25 20:14 UTC, avdhoottt commented on content/kotlin/concepts/math-methods/terms/asin/asin.md
> +The function accepts one mandatory parameter `x`. It should be a numeric value in the range between `-1` and `1` (inclusive). The argument can be of `Double`, `Float`, or `Long` datatype.
```suggestion
The function accepts one mandatory parameter `x`. It should be a numeric value in the range between `-1` and `1` (inclusive). The argument can be of `Double`, and `Float` datatype.
```
Long is a numeric data type, it doesn't make as much sense to use it as an argument for the asin() function.

2023-10-25 20:14 UTC, avdhoottt commented on content/kotlin/concepts/math-methods/terms/asin/asin.md
> +The function returns the arcsine of the argument, which represents an angle in radians. The return value will be of the same type as the argument.
```suggestion
It returns the arcsine of the argument, which represents an angle in radians. The return value will be of the same type as the argument.
```

2023-10-25 20:14 UTC, avdhoottt commented on content/kotlin/concepts/math-methods/terms/asin/asin.md
> +The example below demonstrates how to use the method to return the arcsine of `0.5`.
```suggestion
The example below demonstrates how to use the asin() method to return the arcsine of `0.5`.
```

2023-10-29 05:53 UTC, HKABIG commented
@avdhoottt applied the requested changes please review

2023-10-29 12:14 UTC, avdhoottt approved these changes
Ready for the next round of Review

2023-10-29 12:20 UTC, SSwiniarski approved these changes
@HKABIG Looks good.

2023-10-29 12:23 UTC, merged