[Term Entry] Kotlin Strings .removeRange()
Codecademy/docs pull request #3763
Opened 2023-10-25 14:21 UTC by 0xrahul6

### Description

Added Term Entry for Strings .removeRange()
Closes #3734 
### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-27 13:11 UTC, avdhoottt requested changes
@0xrahul6 Hey, Please make the changes that I've mentioned.

2023-10-27 13:11 UTC, avdhoottt commented on content/kotlin/concepts/strings/terms/removeRange/removeRange.md
> +The **`removeRange()`** method in Kotlin is used to remove a specified range of characters from a string.The removeRange() method returns a new `string` with the specified range of characters removed
```suggestion
The **`removeRange()`** method in Kotlin is used to remove a specified range of characters from a string. It returns a new string with the specified range of characters removed.
```

2023-10-28 12:40 UTC, avdhoottt reviewed
PR is ready for the next round of Review.

2023-10-28 13:11 UTC, avdhoottt approved these changes

2023-10-28 14:57 UTC, SSwiniarski approved these changes
@0xrahul6 I did one minor edit and it looks good to merge.

2023-10-28 14:58 UTC, merged