[Term Entry] Kotlin Strings .removeSuffix()
Codecademy/docs pull request #3764
Opened 2023-10-25 14:38 UTC by 0xrahul6

### Description

Term Entry for Kotlin: Strings .removeSuffix()

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-25 14:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3764) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3764) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3764) it.</sub>

2023-10-25 19:07 UTC, dakshdeepHERE requested changes
Have few changes from my side. Please commit the changes.

2023-10-25 19:07 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/removeSuffix/removeSuffix.md
> +}
```suggestion
fun main() {
    val originalString = "Codecademy.com"
    val suffix = ".com"

    val modifiedString = originalString.removeSuffix(suffix)
    println("Modified String: $modifiedString")
}
```

2023-10-25 19:45 UTC, dakshdeepHERE requested changes

2023-10-25 19:45 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/removeSuffix/removeSuffix.md
> +```
```suggestion
```
Please remove the codebyte. kotlin is not currently supported by Codecademy, so this will not run.

2023-10-26 03:36 UTC, 0xrahul6 commented
@dakshdeepHERE Hi, I've made the changes

2023-10-26 05:39 UTC, dakshdeepHERE commented
@0xrahul6 looks good for second review.

2023-10-26 19:06 UTC, caupolicandiaz requested changes
@0xrahul6 I've added my comments. Please update the entry, and tag me when the changes are complete. Thanks

2023-10-26 19:06 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/removeSuffix/removeSuffix.md
> +Title: 'removeSuffix()'
```suggestion
Title: '.removeSuffix()'
```

2023-10-26 19:06 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/removeSuffix/removeSuffix.md
> +The **`removeSuffix()`** method in Kotlin is used to remove a specified suffix from a string if it is present.The `removeSuffix()` method returns a new `string` with the specified suffix removed if i
```suggestion
The **`.removeSuffix()`** method in Kotlin is used to remove a specified suffix from a string if it is present. The `.removeSuffix()` method returns a new string with the specified suffix removed if it exists. If the original string does not end with the specified suffix, the method returns the original string unchanged.
```

2023-10-26 19:06 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/removeSuffix/removeSuffix.md
> +fun String.removeSuffix(suffix: CharSequence): String
```suggestion
String.removeSuffix(suffix)
```

2023-10-26 19:06 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/removeSuffix/removeSuffix.md
> +This example shows how to use the `removeSuffix()` method to remove a suffix from a Kotlin string:
```suggestion
This example shows how to use the `.removeSuffix()` method to remove a suffix from a Kotlin string:
```

2023-10-26 19:06 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/removeSuffix/removeSuffix.md
> +    val modifiedString = originalString.removeSuffix(suffixToRemove)
```suggestion
    val modifiedString = originalString.removeSuffix(suffix)
```

2023-10-26 19:06 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/removeSuffix/removeSuffix.md
> +    val modifiedString = originalString.removeSuffix(suffixToRemove)
update the indentations in the code block to use 2 spaces instead of tabs

2023-10-26 19:06 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/removeSuffix/removeSuffix.md
> +In this example, `removeSuffix()` method is used to remove the ".jpg" suffix from the original string. The result will be printed as:
```suggestion
The result will be printed as:
```

2023-10-27 07:35 UTC, 0xrahul6 commented
@caupolicandiaz committed the changes

2023-10-27 16:52 UTC, caupolicandiaz approved these changes
@0xrahul6 This looks good

2023-10-27 17:54 UTC, dakshdeepHERE approved these changes

2023-10-27 18:58 UTC, merged