Add .asin() method to Lua documentation
Codecademy/docs pull request #3766
Opened 2023-10-25 16:16 UTC by laisvigas

### Description

Closes #3387

The document provides information about Lua's math.asin() function, explaining its usage and practical applications, and I have created a new entry for this topic in the documentation.

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-29 13:28 UTC, dakshdeepHERE requested changes
Some changes from my side. Will look through it again once you commit these.

2023-10-29 13:28 UTC, dakshdeepHERE commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +> **Note**: Mastering the intricacies of `math.asin()` is crucial for anyone in the programming field. Although specific tasks might be accomplished through libraries and frameworks, a solid understa
```suggestion
> **Note**: Understanding the inner workings of `math.asin()` is essential for anyone in the programming field. While specific tasks can often be achieved using libraries and frameworks, a solid grasp of this function's functionality is fundamental. This knowledge not only helps in solving immediate problems but also empowers programmers to create new applications and innovate within their respective domains.
```

2023-10-29 13:28 UTC, dakshdeepHERE commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +-- Fixed values
```suggestion
```

2023-10-29 13:28 UTC, dakshdeepHERE commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +-- Calculating launch angle using simplified formula
```suggestion
```

2023-10-30 09:28 UTC, laisvigas commented
@dakshdeepHERE Done.

2023-10-30 18:26 UTC, dakshdeepHERE commented
@laisvigas LGTM🚀

2023-10-30 18:26 UTC, dakshdeepHERE approved these changes

2023-10-30 20:59 UTC, caupolicandiaz requested changes
@laisvigas I've added my comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-10-30 20:59 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +> **Note**: Understanding the inner workings of `math.asin()` is essential for anyone in the programming field. While specific tasks can often be achieved using libraries and frameworks, a solid gras
```suggestion
```

2023-10-30 20:59 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +> **Note**: Understanding the inner workings of `math.asin()` is essential for anyone in the programming field. While specific tasks can often be achieved using libraries and frameworks, a solid gras
This note is not really bringing attention to a specific aspect of the functionality, or a caveat to be aware of. It's more of a general recommendation how understanding the implementation can have broader benefits in understanding other programming problems.

2023-10-30 20:59 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +- Where `x` is a number between - 1 and 1, representing a sine value for finding the corresponding angle in radians. If no argument is passed, the program will raise an error.
```suggestion
- Where `x` is a number between `-1` and `1`, representing a sine value for finding the corresponding angle in radians. If no argument is passed, the program will raise an error.
```

2023-10-30 20:59 UTC, caupolicandiaz commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
> +## Example 2
This example doesn't seem quite right. Generally, projectile problems (whether time of flight, max height, etc) all include a gravitational component (g), which is not present here. I would suggest deleting the example for the sake of simplification

2023-11-02 11:41 UTC, laisvigas commented
@caupolicandiaz Done.

2023-11-03 22:16 UTC, caupolicandiaz approved these changes
@laisvigas This looks good

2023-11-03 22:18 UTC, merged