Added new entry regionMatches() in Kotlin
Codecademy/docs pull request #3769
Opened 2023-10-25 17:33 UTC by Atharva1723

Resolves #3732
My Username:
ruby9940067347

### Type of Change
Added new term entry regionMatches() in Kotlin 

### Checklist

- [✔ ] All writings are my own.
- [✔ ] My entry follows the Codecademy Docs style guide.
- [ ✔] My changes generate no new warnings.
- [ ✔] I have performed a self-review of my own writing and code.
- [ ✔] I have checked my entry and corrected any misspellings.
- [✔ ] I have made corresponding changes to the documentation if needed.
- [✔ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ✔] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [✔ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-26 14:45 UTC, avdhoottt requested changes
@Atharva1723  I have mentioned some changed, please correct them.

2023-10-26 14:45 UTC, avdhoottt commented on content/kotlin/concepts/regionMatches/regionMatches.md
> +Title: 'regionMatches()'
```suggestion
Title: '.regionMatches()'
```

2023-10-26 14:45 UTC, avdhoottt commented on content/kotlin/concepts/regionMatches/regionMatches.md
> +- length - the length of the substring to compare.
These lines contain Plagiarism, please remove it.

2023-10-26 14:45 UTC, avdhoottt commented on content/kotlin/concepts/regionMatches/regionMatches.md
> +**regionMatches()** for string checks if a specified region within a Kotlin String matches the content of another string.
```suggestion
**.regionMatches()** for char sequence checks if a specified region within a Kotlin char sequence matches the content of another char sequence. It also checks if a specified region within a Kotlin String matches the content of another string.
```

2023-10-26 14:45 UTC, avdhoottt commented on content/kotlin/concepts/regionMatches/regionMatches.md
> +- length - the length of the substring to compare.
Use H2 headings to divide the content for CharSequence and String.

2023-10-26 14:45 UTC, avdhoottt commented on content/kotlin/concepts/regionMatches/regionMatches.md
> +- length - the length of the substring to compare.
Contains Plagiarism.

2023-10-26 14:45 UTC, avdhoottt commented on content/kotlin/concepts/regionMatches/regionMatches.md
> +The following example uses the `regionMatches()`for char sequence to check if a specified region within a Kotlin char sequence matches the content of another char sequence. The result is then printed
```suggestion
The following example uses the `.regionMatches()` for the char sequence. The result is then printed:
```
The line was repeated many times.

2023-10-26 14:45 UTC, avdhoottt commented on content/kotlin/concepts/regionMatches/regionMatches.md
> +}
```suggestion
fun main() {
    val charSeq1: CharSequence = "Hello, CodeAcademy Members"
    val charSeq2: CharSequence = "code"

    val result = charSeq1.regionMatches(
        thisOffset = 7,
        other = charSeq2,
        otherOffset = 0,
        length = 4,
        ignoreCase = true
    )

    if (result) {
        println("The specified region in charSeq1 matches the content of charSeq2.")
    } else {
        println("The specified region in charSeq1 does not match the content of charSeq2.")
    }
}
```
The string "code" has a length of 4.

2023-10-26 14:45 UTC, avdhoottt commented on content/kotlin/concepts/regionMatches/regionMatches.md
> +The following example uses the `regionMatches()`for string to check if a specified region within a Kotlin string matches the content of another string. The result is then printed:
```suggestion
The following example uses the `.regionMatches()` for string. The result is then printed:
```

2023-10-26 16:47 UTC, Atharva1723 commented
@avdhoottt I have made necessary changes

2023-10-26 16:55 UTC, avdhoottt requested changes
@Atharva1723 I have suggested some content addition, please add it to the content.

2023-10-26 16:55 UTC, avdhoottt commented on content/kotlin/concepts/regionMatches/regionMatches.md
> +): Boolean
Explain the parameters of .regionMatches() without any Plagiarism. Add it below this syntax.

2023-10-27 12:52 UTC, avdhoottt requested changes
@Atharva1723 Make these changed and rest of the content is fine but the path of this entry is wrong. Check the [issue](https://github.com/Codecademy/docs/issues/3732) and the this entry to this path - docs/content/kotlin/concepts/strings/terms/regionMatches/regionMatches.md

2023-10-27 12:52 UTC, avdhoottt commented on content/kotlin/concepts/regionMatches/regionMatches.md
> +- length - the length of the substring to be compared.
```suggestion
Parameters:

- thisOffset - the starting position in this string for the substring to be compared.
- other - the string to which a substring is compared.
- otherOffset - the starting position in the other string for the substring to be compared.
- length - the length of the substring to be compared.
```

2023-10-27 12:52 UTC, avdhoottt commented on content/kotlin/concepts/regionMatches/regionMatches.md
> +- length: This specifies the length of the substring under comparison.
```suggestion
- thisOffset: This is the starting position within the current character sequence for the substring being compared.
- other: This represents the string against which a substring comparison is carried out.
- otherOffset: This indicates the starting position within the other character sequence for the substring being compared.
- length: This specifies the length of the substring under comparison.
```

2023-10-27 13:02 UTC, Atharva1723 reviewed
All Changes Done

2023-10-27 16:10 UTC, SSwiniarski requested changes
@Atharva1723 I did a second review and had a few comments.

2023-10-27 16:10 UTC, SSwiniarski commented on content/kotlin/concepts/strings/terms/regionMatches/regionMatches.md
> +- length: This specifies the length of the substring under comparison.
```suggestion
- `thisOffset`: This is the starting position within the current character sequence for the substring being compared.
- `other`: This represents the string against which a substring comparison is carried out.
- `otherOffset`: This indicates the starting position within the other character sequence for the substring being compared.
- `length`: This specifies the length of the substring under comparison.
```

2023-10-27 16:10 UTC, SSwiniarski commented on content/kotlin/concepts/strings/terms/regionMatches/regionMatches.md
> +- length - the length of the substring to be compared.
```suggestion
- `thisOffset`: The starting position in this string for the substring to be compared.
- `other`: The string to which a substring is compared.
- `otherOffset`: The starting position in the other string for the substring to be compared.
- `length`: The length of the substring to be compared.
```

2023-10-28 11:49 UTC, SSwiniarski approved these changes
@Atharva1723 Looks good. @avdhoottt can you approve this so we can merge.

2023-10-28 12:38 UTC, avdhoottt approved these changes
@SSwiniarski Yes, we can merge this PR.

2023-10-28 14:37 UTC, merged