Added: Kotlin Math abs function✨
Codecademy/docs pull request #3770
Opened 2023-10-25 18:07 UTC by VividhPandey003

### Description

Added Kotlin Math abs function documentation 

Closes #3511 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-25 19:28 UTC, dakshdeepHERE requested changes
I have requested few changes. Please commit them from your side. 🚀

2023-10-25 19:28 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/abs/abs.md
> +In this example, we import the abs function from the `kotlin.math` library and use it to calculate the absolute values of various numeric expressions. The results are then printed to the console.
```suggestion
In this example, the **`abs`** function is imported from the `kotlin.math` library and employed to calculate the absolute values of different numeric expressions. The results are subsequently printed to the console. 
```
Refrain from using pronouns

2023-10-25 19:28 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/abs/abs.md
> +The output of this code will be:
```suggestion
The output of this code will be:

```
adding a line after this

2023-10-25 19:28 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/abs/abs.md
> +The .abs() method is particularly useful when you need to ensure that a value is treated as positive, regardless of its original sign.
```suggestion
The **`.abs()`** method is notably useful when ensuring that a value is treated as positive, irrespective of its original sign.
```
Refrain from using pronouns.

2023-10-25 19:28 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/abs/abs.md
> +### Example
```suggestion
## Example 
```

2023-10-25 19:28 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/abs/abs.md
> +
```suggestion
```

2023-10-25 19:28 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/abs/abs.md
> +### Syntax
```suggestion
## Syntax
```

2023-10-25 19:28 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/abs/abs.md
> +The .abs() method is particularly useful when you need to ensure that a value is treated as positive, regardless of its original sign.
You can add a working codebyte after this. Try to keep the code different from above example.

2023-10-25 19:29 UTC, dakshdeepHERE requested changes

2023-10-25 19:29 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/abs/abs.md
> +The method takes the numeric expression n as its argument and returns the absolute value, ensuring that the result is always a non-negative value.
```suggestion
`n`: A numeric expression (e.g., `Int`, `Long`, `Double`, `Float`, etc.) for which you want to calculate the absolute value.

The method takes the numeric expression n as its argument and returns the absolute value, ensuring that the result is always a non-negative value.
```
```suggestion
`n`: A numeric expression (e.g., `Int`, `Long`, `Double`, `Float`, etc.) for which you want to calculate the absolute value.

The method takes the numeric expression n as its argument and returns the absolute value, ensuring that the result is always a non-negative value.
```
```suggestion
`n`: A numeric expression (e.g., `Int`, `Long`, `Double`, `Float`, etc.) for which you want to calculate the absolute value. The method takes the numeric expression n as its argument and returns the absolute value, ensuring that the result is always a non-negative value.
```
There is no need to leave space here.

2023-10-27 16:02 UTC, VividhPandey003 commented
@dakshdeepHERE Committed the suggested changes. Would you please review them once.

2023-10-27 16:50 UTC, dakshdeepHERE requested changes
Thank you for the commit here are few more. Commit these so we can move forward to 2nd review. :)

2023-10-27 16:50 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/abs/abs.md
> +The **`.abs()`** method is notably useful when ensuring that a value is treated as positive, irrespective of its original sign.
```suggestion
> **Note**: The `.abs()` method is notably useful when ensuring that a value is treated as positive, irrespective of its original sign.
```

2023-10-27 16:50 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/abs/abs.md
> +In this example, the **`abs`** function is imported from the `kotlin.math` library and employed to calculate the absolute values of different numeric expressions. The results are subsequently printed
```suggestion
In this example, the `abs` function is imported from the `kotlin.math` library and employed to calculate the absolute values of different numeric expressions. The results are subsequently printed to the console. 
```

2023-10-27 16:50 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/abs/abs.md
> +The `.abs()` method in Kotlin's Math library is used to calculate the absolute value of a numeric expression. The absolute value is the non-negative value of a number, effectively removing its negati
```suggestion
The **`.abs()`** method in Kotlin's Math library is used to calculate the absolute value of a numeric expression. The absolute value is the non-negative value of a number, effectively removing its negative sign, if present.
```

2023-10-27 16:50 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/abs/abs.md
> +  - 'Computer Science'
```suggestion
  - 'Computer Science'
  - 'Code Foundations'
```

2023-10-27 16:50 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/abs/abs.md
> +}
```suggestion
import kotlin.math.abs

fun main() {
  val x = -6.5
  val y = 2
  val z = -340.8

  val absoluteX = abs(x)
  val absoluteY = abs(y)
  val absoluteZ = abs(z)
  println("Absolute value of x: $absoluteX")
  println("Absolute value of y: $absoluteY")
  println("Absolute value of z: $absoluteZ")
}
```

2023-10-27 17:49 UTC, VividhPandey003 commented
> Thank you for the commit here are few more. Commit these so we can move forward to 2nd review. :)

Done

2023-10-27 17:49 UTC, dakshdeepHERE commented
@VividhPandey003 LGTM 🚀

2023-10-27 17:55 UTC, dakshdeepHERE approved these changes

2023-10-27 19:40 UTC, caupolicandiaz approved these changes
@VividhPandey003 I made some direct edits to update the formatting. Looks good to merge

2023-10-27 19:42 UTC, merged