Update css background size documentation with images
Codecademy/docs pull request #3771
Opened 2023-10-25 18:35 UTC by laisvigas

### Description

Closes #3637

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-25 18:39 UTC, laisvigas commented
Hi, @SSwiniarski I wanted to inform you that I've addressed the issues encountered in the last pull request, and I've created a new one. I kindly request that you or someone from the team to review the changes and, if everything is satisfactory, proceed with the merge. Thank you!

2023-10-26 12:09 UTC, SSwiniarski requested changes
@laisvigas You need to address the extra file in this PR.

2023-10-26 12:46 UTC, laisvigas commented on content/lua/concepts/mathematical-library/terms/asin/asin.md
Done.

2023-10-26 16:56 UTC, SSwiniarski approved these changes
@laisvigas looks good for another review.

2023-10-26 19:50 UTC, caupolicandiaz approved these changes
@laisvigas @SSwiniarski LGTM

2023-10-26 19:52 UTC, merged