[Edit] update to blur.md added image eample
Codecademy/docs pull request #3772
Opened 2023-10-25 19:05 UTC by DanWSDev

### Description
Added new png image to show the example

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-27 22:31 UTC, caupolicandiaz requested changes
@DanWSDev Just one edit. Please update, and tag me when complete. Thanks.

2023-10-27 22:31 UTC, caupolicandiaz commented on content/css/concepts/filter-functions/terms/blur/blur.md
> +![css-filterfunctions-blur-example](https://github.com/DanWSDev/docs/blob/patch-3/media/css-filterfunctions-blur-example.png)
the image should be in the docs/media folder and the link should use the following path -
https://raw.githubusercontent.com/Codecademy/docs/main/media/css-filterfunctions-blur-example.png

2023-10-27 23:31 UTC, DanWSDev commented
> @DanWSDev Just one edit. Please update, and tag me when complete. Thanks.

@caupolicandiaz Thank you for pointing this out silly mistake on my part it is updated now.

2023-10-28 19:43 UTC, caupolicandiaz approved these changes
@DanWSDev Looks good, this is ready for a second review

2023-10-29 12:26 UTC, SSwiniarski approved these changes
@DanWSDev Looks good.

2023-10-29 12:27 UTC, merged