[Edit] CSS display flex example image addition
Codecademy/docs pull request #3774
Opened 2023-10-25 21:43 UTC by Khalid-debugg

### Description

Edited display.md

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-26 14:40 UTC, ishg-153 requested changes
@Khalid-debugg I have suggested a few changes. Please make those.
Also, make sure to sign the CLA.

2023-10-26 14:40 UTC, ishg-153 commented on content/css/concepts/display/display.md
> +
Add in a sentence that leads the above code block to this output. Something like this:
"This does [XYZ] and results in:"

2023-10-26 14:40 UTC, ishg-153 commented on content/css/concepts/display/display.md
> +![css-display-flex-example](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-display-flex-example.jpg)
```suggestion
![CSS display flex example](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-display-flex-example.jpg)
```
Inside the square brackets is the alt text for the image. It should be a short phrase relating to the image, like so:

2023-10-26 19:39 UTC, caupolicandiaz approved these changes
@Khalid-debugg For the sake of expediency I updated the image for a higher resolution copy. Looks good to merge

2023-10-26 20:18 UTC, ishg-153 commented
> @Khalid-debugg @ishg-153 For the sake of expediency I updated the image for a higher resolution copy. Looks good to merge

Hey, there seems to be a small grammatical error in the sentence above the image, can we correct that?

2023-10-26 20:42 UTC, caupolicandiaz commented
> > @Khalid-debugg @ishg-153 For the sake of expediency I updated the image for a higher resolution copy. Looks good to merge
> 
> Hey, there seems to be a small grammatical error in the sentence above the image, can we correct that?

Feel free to add it.

2023-10-27 14:48 UTC, ishg-153 commented
> > > @Khalid-debugg @ishg-153 For the sake of expediency I updated the image for a higher resolution copy. Looks good to merge
> > 
> > 
> > Hey, there seems to be a small grammatical error in the sentence above the image, can we correct that?
> 
> Feel free to add it.

@Khalid-debugg made the necessary change, it's ready to merge.

2023-10-27 14:53 UTC, Khalid-debugg commented
> > > > @Khalid-debugg @ishg-153 For the sake of expediency I updated the image for a higher resolution copy. Looks good to merge
> > > 
> > > 
> > > Hey, there seems to be a small grammatical error in the sentence above the image, can we correct that?
> > 
> > 
> > Feel free to add it.
> 
> @Khalid-debugg made the necessary change, it's ready to merge.

sorry but I can't see a grammatical mistake, I even used an external software and I can't figure it out, can you point it out?

2023-10-27 15:02 UTC, ishg-153 approved these changes
Good to go

2023-10-27 17:22 UTC, merged