[Edit] clear.md added PNG example
Codecademy/docs pull request #3775
Opened 2023-10-26 03:14 UTC by DanWSDev

### Description
Created and added a PNG image for the code example.

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-26 18:50 UTC, DanWSDev commented
> @DanWSDev the image `css-display-clear-eaxmple.png` that you've added, doesn't need the title attribute that reads "Moves the img element below the h1 element" given to the image. Please remo


> @DanWSDev the image `css-display-clear-eaxmple.png` that you've added, doesn't need the title attribute that reads "Moves the img element below the h1 element" given to the image. Please remove it.

@ishg-153 Updated the image to remove the text

2023-10-28 02:43 UTC, ishg-153 approved these changes
Looks good for a second review.

2023-10-28 14:53 UTC, SSwiniarski requested changes
@DanWSDev I did a second review and had a couple of comments.

2023-10-28 14:53 UTC, SSwiniarski commented on content/css/concepts/display/terms/clear/clear.md
> +![css-display-clear-example](https://github.com/DanWSDev/docs/blob/patch-4/media/css-display-clear-example.png)
You need to use the URL as specified in the style guide [here](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#file-hosting).

2023-10-28 14:53 UTC, SSwiniarski commented on content/css/concepts/display/terms/clear/clear.md
> +
Add a sentence introducing the image and explaining it is an example of the above CSS.

2023-10-29 11:47 UTC, SSwiniarski approved these changes
@DanWSDev looks good.

2023-10-29 11:48 UTC, merged