Add lua deg function to documentation
Codecademy/docs pull request #3778
Opened 2023-10-26 11:19 UTC by laisvigas

### Description

Closes #3391

The documentation provides comprehensive information about Lua's math.deg() function, explaining how it converts angles from radians to degrees. It covers the function's purpose, syntax, usage, and includes an illustrative example, ensuring a clear understanding of its implementation in Lua programming.

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-26 16:26 UTC, laisvigas commented
I realized there were some unintended files included in the initial submission. However, I have resolved these issues, and I believe the pull request is now in good shape. Please take a moment to go through the changes and provide any feedback or suggestions.

2023-10-26 16:29 UTC, laisvigas commented
I realized there were some unintended files included in the initial submission. However, I have resolved these issues, and I believe the pull request is now in good shape. Please take a moment to go through the changes and provide any feedback or suggestions.

2023-10-27 08:00 UTC, dakshdeepHERE requested changes
Few changes from my side. Otherwise this looks good

2023-10-27 08:00 UTC, dakshdeepHERE commented on content/lua/concepts/mathematical-library/terms/deg/deg.md
> +Title: ‘deg()’
```suggestion
Title: ‘.deg()’
```

2023-10-27 08:00 UTC, dakshdeepHERE commented on content/lua/concepts/mathematical-library/terms/deg/deg.md
> +> **Note**: It's important to be cautious of rounding errors when converting between degrees and radians due to computer's floating-point representation, especially for small or large angles.
```suggestion
> **Note**: It's important to be cautious of rounding errors when converting between degrees and radians due to computer's floating-point representation, especially for small or large angles. Rounding errors occur when converting between degrees and radians due to the inherent limitations of computer representation of numbers.
```

2023-10-27 08:00 UTC, dakshdeepHERE commented on content/lua/concepts/mathematical-library/terms/deg/deg.md
> +print("Angle of the right triangle in degrees: " .. angleInDegrees)
```suggestion
local angleInRadians = math.pi / 4

local angleInDegrees = math.deg(angleInRadians)

print("Angle of the right triangle in degrees: " .. angleInDegrees)
```

2023-10-27 08:06 UTC, dakshdeepHERE commented
Few changes from my side @laisvigas.

2023-10-27 11:42 UTC, laisvigas commented
> @laisvigas the other files and the commit came here can be due to two issue:
> 
> * this branch `add-lua-deg-function-to-documentation` is a sub branch/child branch of some other branch. To confirm it run this locally in CLI
> 
> ```shell
> git log --oneline --graph --decorate --all --simplify-by-decoration
> ```
> 
>  * Or you committed those commit on your main branch. So basically those commit will appear everywhere in all other branches that you will create from now on. If this is the case then I will recommend rebasing the branch.

@dakshdeepHERE Thank you for your guidance. GIT and GitHub are still relatively new concepts for me. Thanks to Hacktoberfest, I've been diving deep into the world of version control and collaboration, and I'm learning a lot in the process. I used the command you suggested: `git log --oneline --graph --decorate --all --simplify-by-decoration`, and here's what I found:

<img width="750" alt="Screenshot 2023-10-27 at 12 20 52" src="https://github.com/Codecademy/docs/assets/119849251/51d74ef9-191a-4aa6-ae6d-daeac733f1cb">

If there are any specific actions you'd like me to take based on this information, please let me know. Otherwise, should I wait for the second review before making any additional changes?

2023-10-28 15:44 UTC, dakshdeepHERE approved these changes

2023-10-28 15:54 UTC, dakshdeepHERE commented
Based on the Git log you provided, it appears that the branch `add-lua-deg-function-to-documentation` (HEAD) has a commit history that shows it was branched off from `origin/add-lua-deg-function-to-documentation`. This is evident from the branching pattern in the Git log, where there's a merge commit from `origin/add-lua-deg-function-to-documentation` into your current branch.

The line in your Git log indicates this branching:

```
* 23cc9ec9 (HEAD - add-lua-deg-function-to-documentation, origin/add-lua-deg-function-to-documentati on) Add Lua math.deg() function to the documentation and exclude wrong files
| * 6f3f7de6 (origin/add-asin-method-to-Lua-documentation) Merge branch 'main' into add-asin-method-t o-Lua-documentation
```

In this log, you can see that `23cc9ec9` (your current branch) is a child branch of `origin/add-lua-deg-function-to-documentation`. The merge commit `6f3f7de6` indicates that changes from `origin/add-asin-method-to-Lua-documentation` were merged into your branch.

So, based on this information, your branch `add-lua-deg-function-to-documentation` is indeed a sub-branch of `origin/add-lua-deg-function-to-documentation`.

2023-10-28 15:55 UTC, dakshdeepHERE commented
Also the entry looks good for 2nd review.

2023-10-28 21:59 UTC, caupolicandiaz approved these changes
@laisvigas Just made a few direct edits to correct some formatting and simplify.

2023-10-28 22:00 UTC, merged