adds git stash
Codecademy/docs pull request #3782
Opened 2023-10-26 12:03 UTC by Vidip-Ghosh

### Description

Closes #3708 

I've added the use of `git stash` command. This command is used when we have changes in the current branch and want to switch to different branch. So we stash the changes and switch to different branch. We run `git stash apply` to get the changes back. 

### Type of Change

- Adding a new entry
 Editing an existing entry (fixing a typo, bug, issues, etc)
 Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-26 12:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3782) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3782) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3782) it.</sub>

2023-10-26 17:16 UTC, avdhoottt requested changes
@Vidip-Ghosh Firstly, delete the yarn.lock file as there is no need to push it. I have also mentioned some changes, please make those.

2023-10-26 17:16 UTC, avdhoottt commented on content/git/concepts/stash/stash.md
> +Description: 'The changes made to the current working file are temporarily stored using the git stash command, which makes it simple to switch to a different branch and work on different features wit
```suggestion
Description: 'The changes made to the current working file are temporarily stored using the git stash command, which makes it simple to switch to a different branch and work on different features without losing modifications.
```

2023-10-26 17:16 UTC, avdhoottt commented on content/git/concepts/stash/stash.md
> +Title: 'stash'
```suggestion
Title: 'Stash'
```

2023-10-26 17:16 UTC, avdhoottt commented on content/git/concepts/stash/stash.md
> +  - 'paths/computer-science'
```suggestion
Tags: 
  - 'Git'
  - 'Version Control'
  - 'GitHub'
CatalogContent: 
  - 'learn-git'
  - 'paths/computer-science'
```

2023-10-26 17:16 UTC, avdhoottt commented on content/git/concepts/stash/stash.md
> +
```suggestion
The **`git stash`** temporarily stores the changes made in the current working file to the hidden directory called .git/refs/stash and we can use **`git stash apply`** to restore the changes done.

```

2023-10-26 17:16 UTC, avdhoottt commented on content/git/concepts/stash/stash.md
> +```
Add the complete output from the command line, this is incomplete.

2023-10-27 11:31 UTC, Vidip-Ghosh commented
Why is it giving me conflicts? 
I try to integrate my changes but main branch shows something different.

2023-10-27 11:46 UTC, SSwiniarski commented
@Vidip-Ghosh you accidently duplicated an earlier issue that someone had worked on and was merged. Apologies, your issue shouldn't have been accepted as it was a duplicate. We'll have to close this PR and the associated issue.

2023-10-27 11:46 UTC, closed without merging