Hkabig patch 2
Codecademy/docs pull request #3799
Opened 2023-10-29 17:40 UTC by HKABIG

created asin.md in accordance to the guidelines provided

### Description

created docs/content/kotlin/concepts/math-methods/terms/acosh/acosh.md entry for https://github.com/Codecademy/docs/issues/3513

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-29 17:41 UTC, HKABIG commented
@SSwiniarski please review this changes

2023-10-30 07:06 UTC, dakshdeepHERE requested changes
Few changes from my side for now. Please commit it so we can move forward.

2023-10-30 07:06 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/acosh/acosh.md
> +It returns the hyperbolic arccosine of the argument, which represents a real number.
```suggestion
The function accepts one mandatory parameter `x`, which should be a numeric value greater than or equal to `1`. The argument can be of `Double` and `Float` datatype. 

> **Note**: It returns the hyperbolic arccosine of the argument, which represents a real number.
```
We can take float datatype also. [ref](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.math/acosh.html)

2023-10-30 07:06 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/acosh/acosh.md
> +    println(result)
```suggestion
import kotlin.math.acosh
fun main() {
    val x = 2.0
    val result = acosh(x)

    println(result)
```
No need for code comments here

2023-10-30 07:06 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/acosh/acosh.md
> +Description: 'Returns the hyperbolic arccosine of a numeric argument.'
```suggestion
Description: 'Returns the inverse hyperbolic cosine of a numeric argument.'
```

2023-10-30 07:15 UTC, HKABIG commented
@dakshdeepHERE I have commited your suggestions

2023-10-30 07:40 UTC, dakshdeepHERE commented
@HKABIG That was quick 😄, let me look through the entry again. 🚀

2023-10-30 07:49 UTC, dakshdeepHERE commented
@HKABIG LGTM for 2nd review. Thanks for commits.🚀

2023-10-30 07:49 UTC, dakshdeepHERE approved these changes

2023-10-30 11:50 UTC, SSwiniarski approved these changes
@HKABIG I did some minor edits and now it looks good to merge.

2023-10-30 11:51 UTC, merged