[Concept Entry] SwiftUI Tables
Codecademy/docs pull request #3800
Opened 2023-10-30 02:20 UTC by arirays

### Description

-Added SwiftUI Tables concept entry
- Closes issue #2105

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x ] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x]Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-30 08:53 UTC, dakshdeepHERE requested changes
Here are some initial changes commit these so we can move forward in the review process. 🚀

2023-10-30 08:53 UTC, dakshdeepHERE commented on content/swiftui/concepts/tables/tables.md
> +
```suggestion
```
No need to give 2 white space here

2023-10-30 08:53 UTC, dakshdeepHERE commented on content/swiftui/concepts/tables/tables.md
> +**Table** in SwiftUI is a structure that allows us to create and display collections of data in columns and rows. Many datasets have a tabular structure and can be efficiently presented in a table fo
```suggestion
**`Table`** in SwiftUI is a container that enables the creation and presentation of data collections in a tabular format, organized into columns and rows. It is a valuable tool for displaying datasets that have a structured, grid-like layout. When the number of rows exceeds the available vertical space, the `Table` component will automatically enable vertical scrolling to ensure all data is accessible. Moreover, on macOS, horizontal scrolling becomes available when the number of columns exceeds the width of the view.
```

2023-10-30 08:53 UTC, dakshdeepHERE commented on content/swiftui/concepts/tables/tables.md
> +### Example
```suggestion
## Example

`Table` is an excellent choice for presenting data in a concise, organized manner. In the example below, to create a straightforward three-column table from an array of `Singer`, the data model needs to conform to `Identifiable`.

```
Let's remove the above heading and add it below the example heading only. Also refrain from using pronouns.

2023-10-30 08:53 UTC, dakshdeepHERE commented on content/swiftui/concepts/tables/tables.md
> +To make the columns of a `Table` sortable we need to make an array of KeyPathComparator objects with the default sorting inside.  Additionally, provide a binding to an array of sort comparators to wa
```suggestion
To enable sorting of `Table` columns, an array of `KeyPathComparator` objects should be created with default sorting inside. Additionally, a binding to an array of sort comparators needs to be provided to track changes in the sorting order. The table itself does not perform data sorting itself. To activate sorting, monitoring changes can be achieved using the `.onChange(of:perform:)` modifier and then sorting the data within the closure.
```

2023-10-30 08:53 UTC, dakshdeepHERE commented on content/swiftui/concepts/tables/tables.md
> +Here's an example of how to add sorting to the previous code:
```suggestion

Here's an example of how to add sorting to the previous code:
```

2023-10-30 08:53 UTC, dakshdeepHERE commented on content/swiftui/concepts/tables/tables.md
> + Here's an example of how to use multi-select functionality into the previous example:
```suggestion
To improve table interactivity, enabling users to select one or more rows can be achieved. To do this, binding to an optional identifier of the item should be provided to the `Table`. For creating a table that permits multiple selections, a binding to a Set of IDs can be established. Here's an example of how to incorporate multi-select functionality into the previous example:
```

2023-10-30 08:53 UTC, dakshdeepHERE commented on content/swiftui/concepts/tables/tables.md
> + // @State private var selection: Singer.ID? allows one row selection
```suggestion
```

2023-10-30 08:53 UTC, dakshdeepHERE commented on content/swiftui/concepts/tables/tables.md
> +## Customizing a Table style
```suggestion

## Customizing a Table style
```
Add a line before starting a new heading

2023-10-30 08:53 UTC, dakshdeepHERE commented on content/swiftui/concepts/tables/tables.md
> +    // Table columns
```suggestion
```

2023-10-30 08:53 UTC, dakshdeepHERE commented on content/swiftui/concepts/tables/tables.md
> +You can set a specific width for a table column:
```suggestion
Defining a precise width for a table column can be accomplished as follows:
```

2023-10-30 19:28 UTC, arirays commented
Hi @SSwiniarski I created a PR for issue #3800. Could you please review it? Thank you.

2023-10-31 05:37 UTC, dakshdeepHERE requested changes
Few more changes.

2023-10-31 05:37 UTC, dakshdeepHERE commented on content/swiftui/concepts/tables/tables.md
> +}
```suggestion
struct ContentView: View {
  @State private var people = [
      Singer(name: "Taylor", lastName: "Swift", ranking: 95),
      Singer(name: "Olivia", lastName: "Rodrigo", ranking: 80),
      Singer(name: "Billie", lastName: "Eilish", ranking: 70),
      Singer(name: "Katy", lastName: "Perry", ranking: 75)
  ]
  
  @State private var sortOrder = [KeyPathComparator(\Singer.name)]
  
  var body: some View {
      Table(people, sortOrder: $sortOrder) {
          TableColumn("Name", value: \.name)
          TableColumn("Last Name", value: \.lastName)
          TableColumn("Ranking") {
              people in
              Text(String(people.ranking))
          }
      }
      .onChange(of: sortOrder) { newOrder in
          people.sort(using: newOrder)
      }
  }
}
```

2023-10-31 05:37 UTC, dakshdeepHERE commented on content/swiftui/concepts/tables/tables.md
> + }
```suggestion
 @State private var selection = Set<Singer.ID>()

var body: some View {
  Table(people, selection: $selection, sortOrder: $sortOrder) {...}
}
```

2023-11-01 18:40 UTC, dakshdeepHERE commented
Hello @arirays, can commit the changes so we can move forward to 2nd review?

2023-11-02 05:42 UTC, dakshdeepHERE commented
@arirays Looks good for 2nd review. 🚀

2023-11-03 22:51 UTC, caupolicandiaz requested changes
@arirays I've added my initial comments. Please update the entry, and tag me when you've finished making changes. Thanks

2023-11-03 22:51 UTC, caupolicandiaz commented on content/swiftui/concepts/tables/tables.md
> +**`Table`** in SwiftUI is a container that enables the creation and presentation of data collections in a tabular format, organized into columns and rows. It is a valuable tool for displaying dataset
```suggestion
A **`Table`** in SwiftUI is a container that enables the creation and presentation of data collections in a tabular format: values organized into columns and rows. It is a valuable tool for displaying datasets that have a structured, grid-like layout. When the number of rows exceeds the available vertical space, the `Table` component will automatically enable vertical scrolling to ensure all data is accessible. Moreover, on macOS, horizontal scrolling becomes available when the number of columns exceeds the width of the view.
```

2023-11-03 22:51 UTC, caupolicandiaz commented on content/swiftui/concepts/tables/tables.md
> +
Before any examples there should be a syntax section to demonstrate how the structure is implemented generically with pseudo code. For example - 
https://www.codecademy.com/resources/docs/swiftui/views/button

2023-11-03 22:51 UTC, caupolicandiaz commented on content/swiftui/concepts/tables/tables.md
> +### Adding sorting to a table
```suggestion
### Adding Sorting to a Table
```

2023-11-03 22:51 UTC, caupolicandiaz commented on content/swiftui/concepts/tables/tables.md
> +### Adding selection to a table
```suggestion
### Adding Selection to a Table
```

2023-11-03 22:51 UTC, caupolicandiaz commented on content/swiftui/concepts/tables/tables.md
> +### Customizing a Table style
```suggestion
### Customizing a Table Style
```

2023-11-03 22:51 UTC, caupolicandiaz commented on content/swiftui/concepts/tables/tables.md
> +### Setting a fixed width for the table column
```suggestion
### Setting a Fixed Width for a Table Column
```

2023-11-03 22:51 UTC, caupolicandiaz commented on content/swiftui/concepts/tables/tables.md
> +One of the easiest methods to change a table's appearance is by using the `.tableStyle(_:)` modifier. This modifier requires one argument, a TableStyle, which defines the style to use for the table.
```suggestion
One of the easiest methods to change a table's appearance is by using the `.tableStyle(_:)` modifier. This modifier requires just one argument, a predefined table style. SwiftUI provides several options, such as `InsetTableStyle` and, on macOS, `BorderedTableStyle`. The default style is `AutomaticTableStyle`, which is available on all platforms that support `Table`.
```

2023-11-05 14:08 UTC, SSwiniarski requested changes
@arirays There are edits you made to the documentation you need to revert in order for this to merge.

2023-11-05 14:08 UTC, SSwiniarski commented on documentation/concept-entry-template.md
@arirays In order to merge this you need to undo the changes to this file. Easiest would be to replace it with a copy of the `content-entry-template.md` from your main branch.

2023-11-05 21:20 UTC, arirays commented on documentation/concept-entry-template.md
k, @SSwiniarski can I use git reset [commit ID]?

2023-11-05 21:50 UTC, arirays commented on documentation/concept-entry-template.md
I did git revert [commit ID]

2023-11-06 12:31 UTC, SSwiniarski commented on documentation/concept-entry-template.md
@arirays this is still a problem. Did you try my suggested fix?

2023-11-06 21:40 UTC, arirays commented on documentation/concept-entry-template.md
Yes I reverted my concept-entry-template.md by copying it from the main branch.

2023-11-07 18:12 UTC, caupolicandiaz approved these changes
@arirays I made a few direct edits. The filepath for the image was incorrect. All images are stored in an existing folder named media. I updated the path and relocated the file, and updated some of the formatting in the entry. This is ready to merge

2023-11-07 18:30 UTC, dakshdeepHERE approved these changes

2023-11-08 12:26 UTC, SSwiniarski approved these changes

2023-11-08 12:27 UTC, merged

2023-11-19 05:17 UTC, arirays commented
Hi @SSwiniarski and @caupolicandiaz after checking out my Codecademy profile I noticed that my contributions are anonymous....Is it possible to add my profile afterwards? I'd appreciate your help or advice, thank you so much!

2023-11-19 06:58 UTC, dakshdeepHERE commented
@arirays have you linked your Github account to your Codecademy account? Also, make your Codecademy account public. Don't worry it will update automatically.

2023-11-21 04:54 UTC, arirays commented
yes I linked my account to Codecademy account and it is public. Thank you for the reply, hopefully it'll update soon 👍