[Term Entry] Kotlin String Function: .drop()
Codecademy/docs pull request #3822
Opened 2023-10-30 21:00 UTC by MarkDGraham

### Description

- Added the String.drop() term for Kotlin.
- Closes issue #3722 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-30 21:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3822) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3822) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3822) it.</sub>

2023-10-31 06:56 UTC, ishg-153 requested changes
@MarkDGraham This looks great!
You do need to remove the `yarn.lock` file. If you're having trouble with that, let me know.

2023-11-03 21:05 UTC, MarkDGraham commented
I tried to remove the yarn.lock using git rm but now a new branch is existing causing my branch to be ahead by 4 commits. Can you help @ishg-153?

2023-11-04 17:06 UTC, ishg-153 commented
> I tried to remove the yarn.lock using git rm but now a new branch is existing causing my branch to be ahead by 4 commits. Can you help @ishg-153?

I see. The best way would be to revert back to the commit before you had tried to remove the `yarn.lock` file. Then you will need to `git rm --cached yarn.lock`. This will make sure that the `yarn.lock` file is removed from the git repository but stays in your file system.

If you are still not able to do it yourself, I can take care of it for you. No need to fret.

2023-11-04 17:23 UTC, MarkDGraham commented
@ishg-153 yarn.lock has been removed and should be good to go.

2023-11-04 17:29 UTC, ishg-153 approved these changes
This looks good for a second review.

2023-11-04 20:34 UTC, caupolicandiaz requested changes
@MarkDGraham I've added my comments. Please update the entry, and tag me when the changes are complete. Thanks

2023-11-04 20:34 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/drop/drop.md
> +Description: 'Returns a list containing all elements excluding 0th to nth elements.'
```suggestion
Description: 'Returns a string where the characters have been removed from the start to the nth index given.'
```

2023-11-04 20:34 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/drop/drop.md
> +The **`.drop()`** method removes all elements from the original or 0th index element to the nth index element.
```suggestion
The **`.drop()`** method removes characters from the start (0th index) of a given string to the nth index element.
```

2023-11-04 20:34 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/drop/drop.md
> +String.drop(nth-element)
```suggestion
String.drop(nth-index)
```

2023-11-04 20:34 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/drop/drop.md
> +- `nth-element`: The index of the fartherest element to be removed from the front.
```suggestion
- `nth-index`: The method will remove characters up to this value.
```

2023-11-04 20:34 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/drop/drop.md
> +- `String`: The sequence of chars to be removed from and replaced.
```suggestion
- `String`: The string to be modified. The method will return a new string with the specified values missing.
```

2023-11-04 20:34 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/drop/drop.md
> +The example demonstrates the use of `.drop()` to remove elements from the beginning of the string.
```suggestion
The example demonstrates the use of `.drop()` to remove characters from the beginning of the string.
```

2023-11-04 20:34 UTC, caupolicandiaz commented on content/kotlin/concepts/strings/terms/drop/drop.md
> +  println(str2)
```suggestion
  println(str.drop(8))   // Drops 'This is '
  println(str2.drop(6)) // Drops 'I'm a '
```

2023-11-05 09:44 UTC, MarkDGraham commented
@caupolicandiaz I have made the changes following your comments and addressed them accordingly. I believe it should be ready now.

2023-11-06 19:36 UTC, merged