Kotlin tan
Codecademy/docs pull request #3823
Opened 2023-10-30 21:35 UTC by Anudhyan

### Description

- Created a new term entry for tan() in Kotlin Programming language

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-30 21:57 UTC, Anudhyan commented
@SSwiniarski sir it is failing one check

2023-10-31 05:43 UTC, dakshdeepHERE requested changes
Few changes from my side

2023-10-31 05:43 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/tan/tan.md
> +The example below demonstrates how to use the tan() function in Kotlin calculates the tangent of the angle `45` degrees in radians.
```suggestion
The example below demonstrates how to use the `tan()` function in Kotlin to calculate the tangent of the angle `45` degrees in radians.

```

2023-10-31 05:43 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/tan/tan.md
> +}
```suggestion
import kotlin.math.*
fun main() {
  val angleInRadians = Math.toRadians(45.0)
  val tangent = tan(angleInRadians)

  println(tangent)
}
```

2023-10-31 05:43 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/tan/tan.md
> +The function returns a `Double` value, which is the tangent of the angle.
```suggestion
- The function accepts one mandatory parameter `x`. They all take an angle in radians as `Double` or `Float` as a parameter.
- The function returns a `Double` value, which is the tangent of the angle.
```

2023-10-31 05:49 UTC, dakshdeepHERE commented
@Anudhyan Don't worry about the checks

2023-10-31 07:43 UTC, Anudhyan commented
> @Anudhyan Don't worry about the checks

Hello @dakshdeepHERE I have applied the changes . Please check now and accept the pull request by adding the hacktoberfest tag as it was originally there

2023-10-31 09:40 UTC, dakshdeepHERE commented
@Anudhyan Done, This LGTM for 2nd review. 🚀

2023-10-31 09:41 UTC, dakshdeepHERE approved these changes

2023-10-31 10:40 UTC, Anudhyan commented
> Reference i
@dakshdeepHERE please tag Someone who can review it asap and merge the pull request

2023-10-31 10:47 UTC, dakshdeepHERE commented
@Anudhyan Please have patience our other maintainers live in different time zones. So next reviews can take time. Don't worry.

2023-10-31 10:51 UTC, Anudhyan commented
> @Anudhyan Please have patience our other maintainers live in different time zones. So next reviews can take time. Don't worry.

I do understand this but hacktoberfest ends today so I am a bit nervous & anxious

2023-10-31 11:05 UTC, Anudhyan commented
@caupolicandiaz @SSwiniarski sir kindly check this

2023-10-31 11:45 UTC, SSwiniarski approved these changes
@Anudhyan Looks good.

2023-10-31 11:51 UTC, merged

2023-10-31 11:51 UTC, Anudhyan commented
> @Anudhyan Looks good.

Thanks sir for the motivation . I feel so confident now !