Create daysUntil.md
Codecademy/docs pull request #3827
Opened 2023-10-31 14:08 UTC by AlstrupJacob

also edit tags documentation to included required tags

### Description

created daysUntil.md  in docs/content/kotlin/concepts/datetime/terms/daysUntil and edited tags documentation to include required tags

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-31 18:42 UTC, dakshdeepHERE requested changes
Few changes from my side

2023-10-31 18:42 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/daysUntil/daysUntil.md
> +The **`.daysUntil()`** method returns an Int of whole days between two instants. if the number is too large to fit in an Int datatype, the method will return Int.MAX_VALUE or Int.MIN_VALUE depending
```suggestion
The **`.daysUntil()`** method calculates the number of whole days between two instants and returns the result as an `Int`. If the number of days is too large to fit within the bounds of the `Int` datatype, the method will return `Int.MAX_VALUE` if the result is positive or `Int.MIN_VALUE` if the result is negative.
```

2023-10-31 18:42 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/daysUntil/daysUntil.md
> +Instant.daysUntil(Instant)
```suggestion
fun Instant.daysUntil(other: Instant, timeZone: TimeZone): Int
```

2023-10-31 18:42 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/daysUntil/daysUntil.md
> +-`Instant`: A moment in time.
```suggestion
-`Instant`: A moment in time.
- `TimeZone`: This parameter is of type `TimeZone`. It indicates that the calculation should consider the time zone when determining the number of days between the two `Instant` objects.
```

2023-10-31 18:49 UTC, dakshdeepHERE requested changes

2023-10-31 18:49 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/daysUntil/daysUntil.md
> +The example demonstrates the use of `.daysUntil()` to calculate the number of days between two Instants.
```suggestion
The example demonstrates the use of `.daysUntil()` to calculate the number of days between two `Instants`.
```

2023-10-31 19:32 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/daysUntil/daysUntil.md
> +  println(t3)
Can you show me a screenshot of where this is working and give the output as mentioned below?

2023-10-31 19:33 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/daysUntil/daysUntil.md
> +  println(t3)
I think we need to use `ChronoUnit` class to make it work.

2023-10-31 19:33 UTC, dakshdeepHERE commented
@AlstrupJacob please read my recent comment and try to fix it so we can move forward to 2nd review.

2023-10-31 22:33 UTC, AlstrupJacob commented
> @AlstrupJacob please read my recent comment and try to fix it so we can move forward to 2nd review.

I think it works now, I'm having trouble importing the libraries required

2023-11-01 06:50 UTC, dakshdeepHERE commented
> > @AlstrupJacob please read my recent comment and try to fix it so we can move forward to 2nd review.
> 
> I think it works now, I'm having trouble importing the libraries required

I can't see it reflected here on git. Have you pushed the commits?

2023-11-01 19:33 UTC, AlstrupJacob commented
> > > @AlstrupJacob please read my recent comment and try to fix it so we can move forward to 2nd review.
> > 
> > 
> > I think it works now, I'm having trouble importing the libraries required
> 
> I can't see it reflected here on git. Have you pushed the commits?

yes push 47ae83d

2023-11-04 09:04 UTC, dakshdeepHERE requested changes
Last change

2023-11-04 09:04 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/daysUntil/daysUntil.md
> +}
```suggestion
import java.time.Instant
import java.time.Duration

fun Instant.daysUntil(other: Instant): Long {
// Calculate the duration between 'this' Instant and 'other' Instant
    val duration = Duration.between(this, other)
    
// Convert the duration to days and return the result 
    return duration.toDays()
}

fun main() {
    val t1 = Instant.parse("2008-09-29T12:00:00Z")
    val t2 = t1.plus(Duration.ofHours(125))

    val t3 = t2.daysUntil(t1)
    println(t3)
}
```
There are two big problems here:
- `DateTimeUnit.HOURS` is not a valid enum value in Kotlin or the standard Java library. You should use `Duration.ofHours(125)` to add `125` hours to `t1.`
- The `daysUntil` function does not exist in the standard Kotlin or Java libraries for Instant objects. You need to create a custom extension function for Instant to calculate the days between two Instant timestamps, as I showed in the previous response.
I have added the fixed code please commit it.

2023-11-04 09:04 UTC, dakshdeepHERE commented
@AlstrupJacob feel free to ask anything. I have last commit request from my side.

2023-11-05 04:23 UTC, dakshdeepHERE commented
@AlstrupJacob Looks good for second review.

2023-11-05 04:23 UTC, dakshdeepHERE approved these changes

2023-11-13 13:32 UTC, ishg-153 approved these changes
This looks good to merge.

2023-11-13 17:59 UTC, dakshdeepHERE commented
@ishg-153 I'm merging this as you passed it in the second review. Thanks for the review. 🚀🛠️

2023-11-13 19:02 UTC, merged