Remove prefix fixes
Codecademy/docs pull request #3829
Opened 2023-10-31 18:01 UTC by IvanT98

### Description

The Kotlin [removePrefix](https://www.codecademy.com/resources/docs/kotlin/strings/removePrefix) method term entry needed to be updated to match the overall style of the other term entries for Kotlin Strings.

The following was done:
- Added the missing dot to the mentions of the removePrefix method in the description and example (```removePrefix``` should be ```.removePrefix```).
- Simplified syntax code snippet from ```val modifiedString = originalString.removePrefix(prefixToRemove)``` to ```String.removeSuffix(suffix)```.
- Updated variables names in the syntax section to match the new snippet.
- Updated example code snippet to use the same originalString variable value ("HelloWorld.jpg") as the [removeSuffix](https://www.codecademy.com/resources/docs/kotlin/strings/removeSuffix) method term entry page. The example code snippet was also be updated to reflect the change to the originalString variable.
- Removed empty line between suffix and modifiedString variables in the example code snippet and add an empty line after the modifiedString variable to honor [Kotlin style guide](https://developer.android.com/kotlin/style-guide#vertical).
- Updated entry description to add 'Kotlin' before 'string'.

Closes #3820.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-10-31 18:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3829) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3829) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3829) it.</sub>

2023-10-31 18:25 UTC, avdhoottt requested changes

2023-10-31 18:25 UTC, avdhoottt commented on content/kotlin/concepts/strings/terms/removePrefix/removePrefix.md
> +The **`.removePrefix()`** method in Kotlin is used to remove a specified prefix from a string if it is present. The `.removePrefix()` method returns a new string with the specified prefix removed if
```suggestion
The **`.removePrefix()`** method in Kotlin is used to remove a specified prefix from a string if it is present. It returns a new string with the specified prefix removed if it exists. If the original string does not start with the specified prefix, the method returns the original string unchanged.
```
The function name seems repetitive.

2023-10-31 18:26 UTC, avdhoottt approved these changes
PR is Ready for the Second Review.

2023-10-31 18:47 UTC, IvanT98 commented on content/kotlin/concepts/strings/terms/removePrefix/removePrefix.md
> +The **`.removePrefix()`** method in Kotlin is used to remove a specified prefix from a string if it is present. The `.removePrefix()` method returns a new string with the specified prefix removed if
Good suggestion. Added

2023-10-31 19:32 UTC, IvanT98 commented
Pushed new commit to remove space from new line in the example code snippet that was causing the format:verify step to fail

2023-11-01 13:54 UTC, SSwiniarski approved these changes
@IvanT98 Looks good.

2023-11-01 13:56 UTC, merged