[Term Entry] Kotlin Strings .padEnd()
Codecademy/docs pull request #3833
Opened 2023-10-31 22:07 UTC by Fejiro001

### Description

- Added the .padEnd() method for Kotlin Strings
- Closes Issue #3728  

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-01 04:58 UTC, dakshdeepHERE requested changes
2 changes from my side

2023-11-01 04:58 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/padEnd/padEnd.md
> +// string is returned when its length is greater than the specified string
```suggestion
```
No need for comment here

2023-11-01 04:58 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/padEnd/padEnd.md
> +  - 'Methods'
```suggestion
  - 'Methods'
  - 'Kotlin'
```

2023-11-01 16:31 UTC, dakshdeepHERE commented
Hey @Fejiro001 👋, this looks good for 2nd review. 🚀

2023-11-02 16:21 UTC, SSwiniarski requested changes
@Fejiro001 I did a second review and left a few comments.

2023-11-03 11:41 UTC, SSwiniarski approved these changes
@Fejiro001 Did one minor edit and this is ready to merge.

2023-11-03 11:41 UTC, merged