[Term Entry] Kotlin Strings .prependIndent()
Codecademy/docs pull request #3834
Opened 2023-10-31 23:12 UTC by Fejiro001

### Description

- Added the .prependIndent() method for Kotlin Strings
- Closes Issue #3731   

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-01 05:03 UTC, dakshdeepHERE requested changes
Nice entry 😊 Here are few requested changes from my side

2023-11-01 05:03 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/prependIndent/prependIndent.md
> +The **`.prependIndent()`** method in Kotlin is used to add indentation to a string. It is useful for formatting text, especially when we need to align or indent lines within a string.
```suggestion
The **`.prependIndent()`** method in Kotlin is used to add indentation to a `string`. It is useful for formatting text, especially when we need to align or indent lines within a `string`.
```

2023-11-01 05:03 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/prependIndent/prependIndent.md
> +    // Adds three spaces of indentation to the beginning of the string
```suggestion
```
Let's remove it from here and add this in the intro of this code sample

2023-11-01 05:03 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/prependIndent/prependIndent.md
> +This example shows how to use the `.prependIndent()` method to add indents to a string:
```suggestion
This example shows how to use the `.prependIndent()` method to add three spaces of indentation to the beginning of the `string`:
```

2023-11-01 05:03 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/prependIndent/prependIndent.md
> +The code will return the following output:
```suggestion
The above code will return the following output:
```

2023-11-01 16:27 UTC, dakshdeepHERE commented
@Fejiro001 This look good for 2nd review.

2023-11-01 16:27 UTC, dakshdeepHERE approved these changes

2023-11-02 15:53 UTC, SSwiniarski approved these changes
@Fejiro001 I made a slight edit ro remove first person pronouns, now it looks good to merge.

2023-11-02 15:58 UTC, merged