[Term Entry] Swift Protocols Decoder #2960
Codecademy/docs pull request #3837
Opened 2023-11-01 19:43 UTC by marjoriekohn

### Description

Created decoder.md for Swift > concepts > protocols > terms directory.
Closes #2960 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-02 06:33 UTC, avdhoottt requested changes
@marjoriekohn I've suggested some changes, please make them.

2023-11-02 06:33 UTC, avdhoottt commented on content/swift/concepts/protocols/terms/decoder/decoder.md
> +  - 'Swift'
```suggestion
```
please choose the appropriate tags from the official [documentation](https://github.com/Codecademy/docs/blob/main/documentation/tags.md). Swift is not listed in it.

2023-11-02 06:33 UTC, avdhoottt commented on content/swift/concepts/protocols/terms/decoder/decoder.md
> +  - 'learn-swift'
```suggestion
- 'learn-swift'
- 'paths/build-ios-apps-with-swiftui'
```
Two CatlogContent slugs should be there, first for a free course and second for a pro course. You can find the CatalogContent [here](https://github.com/Codecademy/docs/blob/main/documentation/catalog-content.md).

2023-11-02 06:33 UTC, avdhoottt commented on content/swift/concepts/protocols/terms/decoder/decoder.md
> +- JSON data gets transformed into the `SomeStruct` Swift type via the `decode(_:from:)` method.
```suggestion
- The `Decodable` protocol signifies that `SomeStruct` can be decoded from an external format.
- If needed, the `init(from:)` initializer is used to provide custom decoding logic.
- The `JSONDecoder` class decodes JSON data into a Swift type that conforms to the `Decodable` protocol.
- JSON data gets transformed into the `SomeStruct` Swift type via the `decode(_:from:)` method.
```
Explain the itemData parameter too.

2023-11-02 06:33 UTC, avdhoottt commented on content/swift/concepts/protocols/terms/decoder/decoder.md
> +In the following example, a JSON representation of a book is translated into a `Book` instance which conforms to the `Decodable` protocol.
```suggestion
In the following example, a JSON representation of a book is translated into a `Book` instance.
```
The sentence is repeated many times which is not good for readability.

2023-11-08 11:25 UTC, avdhoottt commented on content/swift/concepts/protocols/terms/decoder/decoder.md
> +```pseudo
```suggestion
```swift
```
The example should be in a code block.

2023-11-08 11:28 UTC, avdhoottt approved these changes
PR is ready for the second review.

2023-11-14 15:50 UTC, ishg-153 requested changes
@marjoriekohn There's one small change you need to make.

2023-11-14 15:50 UTC, ishg-153 commented on content/swift/concepts/protocols/terms/decoder/decoder.md
> +Description: 'A Swift protocol that converts external data into Swift types.'
```suggestion
Description: 'Converts external data into Swift types.'
```

2023-11-14 18:14 UTC, ishg-153 approved these changes
@marjoriekohn Great! Ready to merge.

2023-11-14 19:09 UTC, merged