Create minus.md
Codecademy/docs pull request #3839
Opened 2023-11-01 20:28 UTC by AlstrupJacob

Create minus.md, solves #3812 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-02 07:25 UTC, avdhoottt requested changes
@AlstrupJacob Please make these changes.

2023-11-02 07:25 UTC, avdhoottt commented on content/kotlin/concepts/datetime/terms/minus/minus.md
> +}
This code example is not able to compile, Make sure the code executes properly.

2023-11-02 20:02 UTC, avdhoottt commented
@AlstrupJacob Don't commit the tags.md file as it is not a part of this entry.

2023-11-05 21:13 UTC, AlstrupJacob commented
I cannot figure out why it wont pass, however the code example now compiles.

2023-11-06 12:59 UTC, SSwiniarski commented
@KTom101 @caupolicandiaz again this is referring back to the Java libraries, not the `kotlinx.datetime` library. What is is we're looking for in the Kotlin/datetime concept?

2023-11-07 16:47 UTC, SSwiniarski approved these changes
@AlstrupJacob looks good.

2023-11-17 22:27 UTC, caupolicandiaz commented
@avdhoottt @SSwiniarski I noticed that this entry overlooked much of the functionality of this method. So I updated the syntax description and example to better account for the options available. Please briefly review again to ensure no errors are present, since I've made significant edits.

2023-11-17 22:44 UTC, AlstrupJacob commented
> @avdhoottt @SSwiniarski I noticed that this entry overlooked much of the functionality of this method. So I updated the syntax description and example to better account for the options available. Please briefly review again to ensure no errors are present, since I've made significant edits.

I wrote the documentation for the kotlinx version in the first place, but was told that was incorrect and to write it for the standard java time library instead.

2023-11-17 22:45 UTC, AlstrupJacob commented
> > @avdhoottt @SSwiniarski I noticed that this entry overlooked much of the functionality of this method. So I updated the syntax description and example to better account for the options available. Please briefly review again to ensure no errors are present, since I've made significant edits.
> 
> I wrote the documentation for the kotlinx version in the first place, but was told that was incorrect and to write it for the standard java time library instead.

very confused as to which version of the minus function this documentation is supposedconcern

2023-11-17 22:46 UTC, AlstrupJacob commented
whoops

2023-11-17 22:49 UTC, caupolicandiaz commented
> > @avdhoottt @SSwiniarski I noticed that this entry overlooked much of the functionality of this method. So I updated the syntax description and example to better account for the options available. Please briefly review again to ensure no errors are present, since I've made significant edits.
> 
> I wrote the documentation for the kotlinx version in the first place, but was told that was incorrect and to write it for the standard java time library instead.

Apologies for the miscommunication. There was some confusion internally regarding these entries.

2023-11-18 01:27 UTC, AlstrupJacob commented
> > > @avdhoottt @SSwiniarski I noticed that this entry overlooked much of the functionality of this method. So I updated the syntax description and example to better account for the options available. Please briefly review again to ensure no errors are present, since I've made significant edits.
> > 
> > 
> > I wrote the documentation for the kotlinx version in the first place, but was told that was incorrect and to write it for the standard java time library instead.
> 
> Apologies for the miscommunication. There was some confusion internally regarding these entries.

no worries just thought i would elaborate the current state of the pr

2023-11-26 18:37 UTC, merged