[Term Entry] Kotlin Datetime .Month() #3813
Codecademy/docs pull request #3843
Opened 2023-11-02 10:21 UTC by philipphdt

### Description

- Added the Month() method for Kotlin
- Closes Issue #3813 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-02 10:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3843) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3843) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3843) it.</sub>

2023-11-02 11:09 UTC, dakshdeepHERE requested changes
I have request few changes please commit them so we can move forward to 2nd review.

2023-11-02 11:09 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/Month/Month.md
> +Title: 'month'
```suggestion
Title: '.Month'
```

2023-11-02 11:09 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/Month/Month.md
> +The **.Month()** method in Kotlin is used to retrieve the month from a given date object. This method is essential when working with date and time in Kotlin, allowing developers to extract and manipu
```suggestion
The **`.Month()`** method in Kotlin is used to retrieve the month from a given date object. This method is essential when working with `date` and `time` in Kotlin, allowing developers to extract and manipulate the month component of a date. It's particularly useful in scenarios where the month needs to be displayed, compared, or used in calculations. In Kotlin's date-time API, the month is typically represented as an integer, where `1` corresponds to `January` and `12` to `December`.
```

2023-11-02 11:09 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/Month/Month.md
> +- **month**: This is an integer representing the month extracted from the date object. Typically, in Kotlin, months are represented as integers ranging from 1 (January) to 12 (December).
```suggestion
- *date*: An instance of a date object from which you want to extract the month.
- *month*: This is an integer representing the month extracted from the date object. Typically, in Kotlin, months are represented as integers ranging from 1 (January) to 12 (December).
```

2023-11-02 11:09 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/Month/Month.md
> +}
```suggestion
import java.time.LocalDate

fun main() {
    val currentDate = LocalDate.now() 
    val month = currentDate.monthValue

    println("The current month is: $month")
}
```

2023-11-02 11:09 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/Month/Month.md
> +**Note**: Kotlin's standard library doesn't directly provide a `.Month()` method. Instead, the standard way to get the month from a date in Kotlin is by using Java's `java.time.LocalDate` and its `mo
```suggestion
> **Note**: Kotlin's standard library doesn't directly provide a `.Month()` method. Instead, the standard way to get the month from a date in Kotlin is by using Java's `java.time.LocalDate` and its monthValue` property as shown in the example. Adjustments might be needed based on the specific libraries and versions in use.
```

2023-11-02 11:14 UTC, dakshdeepHERE requested changes

2023-11-02 11:14 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/Month/Month.md
> +  - 'DateTime'
```suggestion
  - 'Date'
```
Date time doesn't exist in the tags.md file

2023-11-02 11:14 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/Month/Month.md
> +  - 'learn-kotlin'
```suggestion
  - 'learn-kotlin'
  - 'paths/computer-science'
```

2023-11-02 15:22 UTC, philipphdt commented
@dakshdeepHERE Hi, thanks for your inputs! I hope everything looks good now.

2023-11-04 08:32 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/Month/Month.md
> +In this example, `LocalDate.now()` is used to get the current date. The `.monthValue` property (which serves a similar purpose to a `.Month()` method) of the `LocalDate` object is then called to retr
Remove this sentence from here and move it above the example code snippet as an introductory sentence. Also, remove the last output part and add the output in its own block. Like this:
```shell
then your output

2023-11-04 08:32 UTC, dakshdeepHERE reviewed
I have comment from my side please work on it too

2023-11-04 08:33 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/Month/Month.md
> +In this example, `LocalDate.now()` is used to get the current date. The `.monthValue` property (which serves a similar purpose to a `.Month()` method) of the `LocalDate` object is then called to retr
<img width="114" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/ab094437-20ac-4719-affe-36b5f2d5c044">
This is how to make output block 👆🏻

2023-11-04 10:37 UTC, philipphdt commented
@dakshdeepHERE Hi, I just added your inputs.

2023-11-05 19:43 UTC, dakshdeepHERE approved these changes
Looks good for 2nd review

2023-11-06 12:46 UTC, SSwiniarski requested changes
@philipphdt I did a second review and left some comments.

2023-11-06 12:46 UTC, SSwiniarski commented on content/kotlin/concepts/datetime/terms/Month/Month.md
> +Tags:\
```suggestion
Tags:
```

2023-11-06 12:46 UTC, SSwiniarski commented on content/kotlin/concepts/datetime/terms/Month/Month.md
> +
```suggestion
```
Remove extra blank line.

2023-11-06 12:46 UTC, SSwiniarski commented on content/kotlin/concepts/datetime/terms/Month/Month.md
> +Assuming the current date is November 1, 2023, the output will be:
```suggestion

Assuming the current date is November 1, 2023, the output will be:
```
Blank line between code block and next paragraph.

2023-11-06 12:49 UTC, SSwiniarski commented
@KTom101, @caupolicandiaz There seems to be a mismatch here. Most of the Kotlin datetime terms seem to refer to the `kotlinx.datetime` library. This doesn't. How do we want to deal with this?

2023-11-07 16:51 UTC, KTom101 commented
@SSwiniarski @philipphdt  I'm ok with keeping this. However, it would be a good idea to move the blockquote note at the bottom to before the syntax section. That way it's toward the top and the reader is aware of this before continuing on.

2023-11-19 21:54 UTC, caupolicandiaz commented
@SSwiniarski I've made some outstanding edits to the metadata and updated elements of the body to better align this content with the other entries for this library.

2023-11-20 12:20 UTC, SSwiniarski approved these changes

2023-11-20 12:22 UTC, merged