[Topic]D3.js: Base Pages
Codecademy/docs pull request #3849
Opened 2023-11-03 21:03 UTC by caupolicandiaz

### Description

The edited files included are intended to initialize the D3 library topic in docs. It includes, the topic landing page as well as two concept pages that may serve as starting points for other concept and term entries to be developed.

### Type of Change

- Adding a new entry

### Checklist

- [/ ] All writings are my own.
- [/ ] My entry follows the Codecademy Docs style guide.
- [/ ] My changes generate no new warnings.
- [/ ] I have performed a self-review of my own writing and code.
- [/ ] I have checked my entry and corrected any misspellings.
- [/ ] I have made corresponding changes to the documentation if needed.
- [/ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [/ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [/ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-05 19:38 UTC, dakshdeepHERE requested changes
Hey @caupolicandiaz, I have few changes from my side. Also, I'm eager to see your comment on some of my suggestions.

2023-11-05 19:38 UTC, dakshdeepHERE commented on content/d3/concepts/anatomy/anatomy.md
> +In broad strokes, a chart definition will often take the following form.
```suggestion
In broad strokes, a chart definition will often take the following form:
```

2023-11-05 19:38 UTC, dakshdeepHERE commented on content/d3/concepts/selection/selection.md
> +For this example, the data will be consist of 50 points generated with the aid of the JavaScript `Math.random()` method. The set is constructed as follows.
```suggestion
For this example, the data will consist of 50 points generated with the aid of the JavaScript `Math.random()` method. The set is constructed as follows:
```

2023-11-05 19:38 UTC, dakshdeepHERE commented on content/d3/concepts/selection/selection.md
> +A scatterplot is one of the simplest charts, it is a representation of data in 2-D space where each element is located based on an associated x-y coordinate value. Generally, each element is marked w
```suggestion
A `scatterplot` is one of the simplest charts, it is a representation of data in 2-D space where each element is located based on an associated x-y coordinate value. Generally, each element is marked with a point, circle, or some other shape.
```

2023-11-05 19:38 UTC, dakshdeepHERE commented on content/d3/concepts/selection/selection.md
> +
```suggestion
```
We don't give a white space before the bullet points and its desc, right?

2023-11-05 19:38 UTC, dakshdeepHERE commented on content/d3/concepts/selection/selection.md
> +Selection is the assignment and manipulation of elements in the construction of a chart. In D3 there are a range of methods that are used to add and filter elements in order to allocate specific data
```suggestion
**`Selection`** is the assignment and manipulation of elements in the construction of a chart. In D3 there are a range of methods that are used to add and filter elements in order to allocate specific data and apply modifications. The most widely used among these are the `.select()`, `.selectAll()` and `.append()` methods.
```
The first occurrence of the entry method should be in bold, Right?

2023-11-05 19:38 UTC, dakshdeepHERE commented on content/d3/concepts/anatomy/anatomy.md
> +The anatomy or structure of a D3 chart is built through the use of a range of methods to manipulate data and aesthetic parameters applied to an SVG object. A chart can be seen as meta-function, withi
```suggestion
The **`anatomy`** or structure of a D3 chart is built through the use of a range of methods to manipulate data and aesthetic parameters applied to an SVG object. A chart can be seen as a meta-function, within it are objects and methods that generate the various components of a chart (e.g., paths, axes, labels, etc.) and at the end of it the result, or return, is an SVG that is the sum of all these intermediate operations.
```

2023-11-06 20:43 UTC, caupolicandiaz commented
@dakshdeepHERE Thanks for the review, I've added the changes.

2023-11-06 21:16 UTC, dakshdeepHERE approved these changes

2023-11-12 15:47 UTC, SSwiniarski approved these changes
@caupolicandiaz Looks good.

2023-11-12 15:49 UTC, merged