[Term Entry] Kotlin datetime function: .DateTimePeriod()
Codecademy/docs pull request #3851
Opened 2023-11-04 02:53 UTC by andersooi

### Description

- Added the datetime.DateTimePeriod() term for Kotlin
- Closes issue #3809 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-04 02:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3851) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3851) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3851) it.</sub>

2023-11-04 18:29 UTC, avdhoottt requested changes
@andersooi Please make these changes and only commit DateTimePeriod.md file, don't commit the rest of the two files.

2023-11-04 18:29 UTC, avdhoottt commented on content/kotlin/concepts/datetime/terms/DateTimePeriod/DateTimePeriod.md
> +Description: 'Returns a DateTimePeriod object or a DatePeriod object (if all arguments are set to zero) to indicate the time difference between two dates.'
```suggestion
Description: 'Returns a DateTimePeriod object to indicate the time difference between two dates.'
```

2023-11-04 18:29 UTC, avdhoottt commented on content/kotlin/concepts/datetime/terms/DateTimePeriod/DateTimePeriod.md
> +The **`DateTimePeriod`** function helps to make a new `DateTimePeriod` object that tells you how much time has passed between two dates (even up to nanoseconds). If nothing is passed into the functio
```suggestion
The **`.DateTimePeriod`** function helps to make a new `DateTimePeriod` object that tells you how much time has passed between two dates (even up to nanoseconds). If nothing is passed into the function, it returns a `DatePeriod` object by default. You can use this function to set how many years, months, days, hours, minutes, seconds, and even nanoseconds are between two dates.
```

2023-11-04 18:29 UTC, avdhoottt commented on content/kotlin/concepts/datetime/terms/DateTimePeriod/DateTimePeriod.md
> +): DateTimePeriod
The syntax contains plagiarism, please try to remove it.

2023-11-04 18:29 UTC, avdhoottt commented on content/kotlin/concepts/datetime/terms/DateTimePeriod/DateTimePeriod.md
> +The following example shows how to use the **`DateTimePeriod`** function to add two weeks to a given date.
```suggestion
The following example shows how to use the **`.DateTimePeriod`** function to add two weeks to a given date.
```

2023-11-04 18:29 UTC, avdhoottt commented on content/kotlin/concepts/datetime/terms/DateTimePeriod/DateTimePeriod.md
> +}
```suggestion
import kotlinx.datetime.DateTimePeriod
fun main() {
  //Create an Instant for 2023-12-25 12:00 UTC zone from an ISO 8601 String
  val currDate = "2023-12-25T12:00:00.00+00:00".toInstant()

  // Create a new DateTimePeriod for 2 weeks
  val twoWeeks = DateTimePeriod(days = 14)

  // add 2 weeks to the current date
  val newDate = currDate.plus(twoWeeks, TimeZone.UTC)

  println(newDate)
}
```
The program is giving errors, please add all the necessary import statements.

2023-11-04 18:29 UTC, avdhoottt commented on content/kotlin/concepts/datetime/terms/DateTimePeriod/DateTimePeriod.md
> +The output will be similar to the following:
```suggestion
The output is as follows:
```

2023-11-04 18:29 UTC, avdhoottt commented on content/kotlin/concepts/datetime/terms/DateTimePeriod/DateTimePeriod.md
> +Note that the function will throw an `IllegalArgumentException` if any of the inputs overflows a Long.
Add it as a Note, take reference from this [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md).

2023-11-05 09:15 UTC, andersooi commented
Hi @avdhoottt thanks for the comments. After I make the changes to the DateTimePeriod.md file, do I just add the file to the staging area, commit and push? Or do I need to uncommit the other 2 files first before doing that (apologies as I am still learning how to use GitHub)?

2023-11-06 08:40 UTC, avdhoottt commented
@andersooi Delete the files from the branch, Once files are deleted commit the change and push the branch.

2023-11-06 18:54 UTC, avdhoottt commented
@andersooi Don't just delete them directly from Github, remove them, commit the change, and then push the branch.

2023-11-07 00:57 UTC, andersooi commented
Thanks @avdhoottt. I am currently in the `docs` working directory.

So I ran the following:
`git rm --cached package.json` and `git rm --cached yarn.lock`, but was met with the error that it did not match any files.

I was thinking of resetting git to the commit SHA of my first commit (the one that I committed all 3 files), run the same commands again, commit and then push.

Just wanted to check if this is alright or if I should be using another workaround.

2023-11-08 17:30 UTC, avdhoottt commented
@andersooi can you revert back to the commit where you have not committed those files? or you can create a new Pull Request but remember to commit the necessary file only.

2023-11-13 15:24 UTC, andersooi commented
Hi @avdhoottt I shall create a new pull request instead and commit the necessary file only. Will close this pull request.

2023-11-13 15:24 UTC, closed without merging