made the description more descriptive and added few additional syntax…
Codecademy/docs pull request #3853
Opened 2023-11-04 13:24 UTC by WernerGomindes

… examples

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-04 13:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3853) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3853) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3853) it.</sub>

2023-11-04 16:00 UTC, dakshdeepHERE commented on content/css/concepts/colors/terms/rgb/rgb.md
> +The `rgb()` function in CSS defines a color by specifying its components using three comma-separated values. The first value represents the red component, the second value represents the green compon
we avoid first- and second-person pronouns in Docs. So remove use of `you` `we` etc

2023-11-04 16:01 UTC, dakshdeepHERE requested changes
Looks good overall but have one comment for you to work on.

2023-11-08 13:43 UTC, dakshdeepHERE commented
@WernerGomindes can you commit the changes so we can move forward?

2023-11-26 18:42 UTC, SSwiniarski commented
@WernerGomindes It's been several weeks and you haven't addressed the comments, or signed the [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3853). If we don't see progress in another week we'll need to close this PR as abandoned.

2023-12-10 15:19 UTC, SSwiniarski commented
Closing this PR as abandoned.

2023-12-10 15:19 UTC, closed without merging