[Concept Entry] Rust loops #
Codecademy/docs pull request #3856
Opened 2023-11-05 14:47 UTC by moha230

### Description
- added concept entry rust loops
- added a folder loops
- added a file loops.md
- Closes issue #3374

### Type of Change
- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-05 14:49 UTC, moha230 commented
Hello @SSwiniarski I have done the entry . Thank you

2023-11-05 15:29 UTC, moha230 commented
hello @SSwiniarski  i have an issue in the [Concept Entry] Rust loops #3374 #3856 I don't know why its like this please help

2023-11-05 19:17 UTC, dakshdeepHERE requested changes
I have few comments work on them. Once you commit these I will do another check.

2023-11-05 19:17 UTC, dakshdeepHERE commented on content/rust/concepts/loops/loops.md
> +A `loop` is a control structure that allows you to execute a block of code repeatedly. Loops are used to perform tasks that need to be done multiple times, such as iterating through a list of items,
```suggestion
A **`loop`** is a control structure that enables the repetitive execution of a block of code. `Loops` are employed for tasks that require multiple iterations, such as iterating through a list of items, performing calculations, or waiting for a specific condition to be met. There are typically three main types: `for`, `while`, and `loop`.
```
we don't prefer to use pronouns. Refrain form using them.

2023-11-05 19:17 UTC, dakshdeepHERE commented on content/rust/concepts/loops/loops.md
> +  - 'Computer Science'
```suggestion
  - 'Computer Science'
  - 'Code Foundations'
```

2023-11-05 19:17 UTC, dakshdeepHERE commented on content/rust/concepts/loops/loops.md
> +
```suggestion
## Syntax

```
We always add syntax heading then we add the example heading. We can make the different kinds of loops as sub headings.

2023-11-05 19:17 UTC, dakshdeepHERE commented on content/rust/concepts/loops/loops.md
> +## for loops
```suggestion
### For loop
```

2023-11-05 19:17 UTC, dakshdeepHERE commented on content/rust/concepts/loops/loops.md
> +The `for` loop is used to iterate over collections or ranges.It automatically iterates through elements and executes a block of code for each item in the collection or range.It's commonly used for it
```suggestion
The `for loop` is used to iterate over collections or ranges. It automatically iterates through elements and executes a code block for each item in the pool or scope. It's commonly used for iterating over `arrays`, `vectors`, and other iterable data structures.
```

2023-11-05 19:17 UTC, dakshdeepHERE commented on content/rust/concepts/loops/loops.md
> +## while loops
```suggestion
### While loop
```

2023-11-05 19:17 UTC, dakshdeepHERE commented on content/rust/concepts/loops/loops.md
> +## loop loops
```suggestion
### Loop 
```

2023-11-05 19:22 UTC, dakshdeepHERE requested changes

2023-11-05 19:22 UTC, dakshdeepHERE commented on content/rust/concepts/loops/loops.md
> +This example demonstrates a `while` loop that iterates from `5` to `10` as the counter variable starts from `5`.The second example shows a `for` loop that iterates over an array that containe numbers
```suggestion
This example demonstrates a `while loop` that iterates from `5` to `10` as the counter variable starts from `5`. The second example shows a `for` loop that iterates over an `array` that contains numbers `1` to `5`.
```

2023-11-05 19:22 UTC, dakshdeepHERE commented on content/rust/concepts/loops/loops.md
> +The `loop` keyword creates an infinite loop that continues executing the code block indefinitely until it's explicitly interrupted using the break statement.It's useful when you need to perform a tas
```suggestion
The `loop` keyword creates an infinite loop that continues executing the code block indefinitely until it's explicitly interrupted using the break statement. It's useful when you need to perform a task until a certain condition is met within the loop.
```

2023-11-05 19:22 UTC, dakshdeepHERE commented on content/rust/concepts/loops/loops.md
> +The `while` loop repeatedly executes a block of code as long as a specified condition remains true.It checks the condition before entering the loop, and if the condition is initially false, the loop
```suggestion
The `while loop` repeatedly executes a block of code as long as a specified condition remains true. It checks the condition before entering the loop, and if the condition is initially `false`, the loop won't run. `While loops` are useful when you don't know in advance how many iterations are needed.
```

2023-11-06 15:54 UTC, moha230 commented
Hello @dakshdeepHERE its done . Thank you

2023-11-06 19:14 UTC, dakshdeepHERE approved these changes
Did some small changes. Overall look good for 2nd review.

2023-11-09 18:03 UTC, caupolicandiaz requested changes
@moha230 I've added my initial comments. Please update the entry, and tag me when you've made the changes. Thanks

2023-11-09 18:03 UTC, caupolicandiaz commented on content/rust/concepts/loops/loops.md
> +This example demonstrates a `while loop` that iterates from `5` to `10` as the counter variable starts from `5`. The second example shows a `for` loop that iterates over an `array` that contains numb
```suggestion
This example demonstrates a `while loop` that iterates through each integer from `5` to `10`. The second example uses a `for` loop to iterate over an array that contains the integers in the range `1` to `5`.
```

2023-11-09 18:03 UTC, caupolicandiaz commented on content/rust/concepts/loops/loops.md
> +  - 'Learn-rust'
```suggestion
  - 'rust-for-programmers'
```

2023-11-11 05:00 UTC, moha230 commented on content/rust/concepts/loops/loops.md
> +### Loop
Hello @caupolicandiaz If the sub heading on line 42 changes to infinite loop should we also change the intro at line 14 ? . Suggested change :A **loop** is a control structure that enables the repetitive execution of a block of code. Loops are employed for tasks that require multiple iterations, such as iterating through a list of items, performing calculations, or waiting for a specific condition to be met. There are typically three main types: `for`, `while` and  infinite `loop`. Thank you

2023-11-11 05:12 UTC, moha230 commented
Hello @caupolicandiaz all done . Thank you

2023-11-13 22:09 UTC, merged