UIUX Update
Codecademy/docs pull request #3857
Opened 2023-11-05 15:05 UTC by SSwiniarski

### Description

This was one of my requests on the last mass UIUX update, I deferred it so we could merge. This is breaking down the overlong "bias in user research" entry into the concept and a number of terms.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-09 15:33 UTC, ishg-153 requested changes
Hey @SSwiniarski. I have suggested some changes, please let me know if I misunderstood anything.

For the framing effect entry, can sub it for cognitive bias instead? Since the framing effect stems from Cognitive bias.

2023-11-09 15:33 UTC, ishg-153 commented on content/uiux/concepts/bias-in-user-research/terms/interview-bias/interview-bias.md
> +**Interview bias** refers to bias due to a participant's perception of the interviewer. This may be due to a user's own biased perception of an interviewer's ethnicity, age, gender, or physical appea
I think this entry is supposed to be for Interviewer Bias.

2023-11-12 15:29 UTC, SSwiniarski commented
> Hey @SSwiniarski. I have suggested some changes, please let me know if I misunderstood anything.
> 
> For the framing effect entry, can we sub it for cognitive bias instead? Since the framing effect stems from Cognitive bias.

@ishg-153  I'd rather cognitive bias be done in it's own PR. Other than that, I addressed your comments.

2023-11-16 16:33 UTC, dakshdeepHERE requested changes

2023-11-17 12:49 UTC, SSwiniarski commented
@dakshdeepHERE, committed your suggestions.

2023-11-17 18:46 UTC, dakshdeepHERE approved these changes
Looks good

2023-11-18 15:37 UTC, merged