added about useRef() topic hook in react
Codecademy/docs pull request #3858
Opened 2023-11-05 16:19 UTC by kaushal1717

### Description

### Type of Change

- Adding a new entry
 
I have added useRef() hook topic In the docs as mentioned in #3791 

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-05 16:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3858) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3858) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3858) it.</sub>

2023-11-07 10:33 UTC, vaibhavmani810 requested changes
Hi @kaushal1717 , I am done with the first round of review, suggested some changes, please do the needful and we will go one more round before the Second Review.

2023-11-07 10:33 UTC, vaibhavmani810 commented on content/react/concepts/hooks/terms/useRef/useRef.md
> +Here is how you can use this hook :
```suggestion
This hook can be utilized as follows:
```

2023-11-07 10:33 UTC, vaibhavmani810 commented on content/react/concepts/hooks/terms/useRef/useRef.md
> +If no `initialValue` is provided, `myRef.current` will be undefined by default.
```suggestion
If no `initialValue` is provided, `myRef.current` will be null by default.
```

2023-11-07 10:33 UTC, vaibhavmani810 commented on content/react/concepts/hooks/terms/useRef/useRef.md
> +  );
Please add an explanation of the code.

2023-11-07 14:56 UTC, vaibhavmani810 commented on content/react/concepts/hooks/terms/useRef/useRef.md
> +  );
Hey @kaushal1717,you forgot to add explanation of the example.

2023-11-08 06:43 UTC, kaushal1717 commented
Done all the changes you suggested please review it and tell if I have to change anything again @vaibhavmani810

2023-11-08 06:56 UTC, vaibhavmani810 approved these changes

2023-11-08 17:17 UTC, SSwiniarski requested changes
@kaushal1717 I did a second review and left a few comments.

2023-11-08 17:17 UTC, SSwiniarski commented on content/react/concepts/hooks/terms/useRef/useRef.md
> +Title: 'useState()'
```suggestion
Title: 'useRef()'
```

2023-11-08 17:17 UTC, SSwiniarski commented on content/react/concepts/hooks/terms/useRef/useRef.md
> +Description: 'Create mutable references to elements or values, allowing access to them without causing re-renders.'
```suggestion
Description: 'Creates mutable references to elements or values, allowing access to them without causing re-renders.'
```

2023-11-08 17:17 UTC, SSwiniarski commented on content/react/concepts/hooks/terms/useRef/useRef.md
> +In the `useRef()` hook, the `initialValue` is an optional parameter that you can provide when creating a new ref object.
```suggestion
In the `useRef()` hook, the `initialValue` is an optional parameter that can be provided when creating a new ref object.
```
We avoid first- and second-person pronouns in Docs.

2023-11-08 17:17 UTC, SSwiniarski commented on content/react/concepts/hooks/terms/useRef/useRef.md
> +`initialValue` allows you to initialization of the `.current` property of the ref object with an initial value.
```suggestion
`initialValue` allows the initialization of the `.current` property of the ref object with an initial value.
```

2023-11-08 17:17 UTC, SSwiniarski commented on content/react/concepts/hooks/terms/useRef/useRef.md
> +In this example, the `useRef()` hook is used to store the previous value of the count state, allowing you to display the current and previous count values without triggering re-renders.
```suggestion
In this example, the `useRef()` hook is used to store the previous value of the count state, allowing the display of the current and previous count values without triggering re-renders.
```

2023-11-08 17:17 UTC, SSwiniarski commented on content/react/concepts/hooks/terms/useRef/useRef.md
> +There is no need to re-render the component just to track the previous value; we only need to update the value without causing a re-render. So we use `useRef()` hook
```suggestion
There is no need to re-render the component just to track the previous value; it's only necessary to update the value without causing a re-render. So the `useRef()` hook is used.
```

2023-11-09 10:58 UTC, kaushal1717 commented
I have made suggested changes you can review them @SSwiniarski

2023-11-12 15:32 UTC, SSwiniarski approved these changes
@kaushal1717 Looks good.

2023-11-12 16:31 UTC, merged