[Term Entry] for Kotlin date time API: .plus()
Codecademy/docs pull request #3862
Opened 2023-11-05 21:32 UTC by telfort92

### Description

- Added the datetime.plus() term for kotlin
- Closes Issue #3818 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-05 21:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3862) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3862) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3862) it.</sub>

2023-11-06 08:53 UTC, avdhoottt requested changes
@telfort92 This entry does not follow the style guide. Please read this [documentation](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) and format your content according to it.

2023-11-06 08:53 UTC, avdhoottt commented on content/kotlin/concepts/datetime/terms/plus/plus.md
> +Title: 'Plus() method'
```suggestion
Title: '.plus()' 
```

2023-11-07 01:27 UTC, telfort92 commented
ok I will make the necessary changes

2023-11-07 17:54 UTC, avdhoottt commented
@telfort92 You have used the syntax and examples of the .plus method that refers to the Java libraries. Please replace this with the correct syntax/examples from the kotlix.datetime library.

2023-11-08 02:16 UTC, closed without merging