[Term Entry] Kotlin Math .cos()
Codecademy/docs pull request #3864
Opened 2023-11-06 19:25 UTC by yangvianno

### Description

Added new term entry on the .cos() method for Kotlin: Math

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-06 19:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3864) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3864) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3864) it.</sub>

2023-11-07 13:03 UTC, dakshdeepHERE requested changes
Few comments for now

2023-11-07 13:03 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/cosin/cosin.md
> +in radians.
```suggestion
The **`math.cos()`** method in Kotlin's `math` class is used to calculate the cosine of an angle in radians.
```

2023-11-07 13:03 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/cosin/cosin.md
> +import kotlin.math.cos
```suggestion
```
no need to mention the lib here

2023-11-07 13:03 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/cosin/cosin.md
> +- `angle`: The angle in radians for which you want to calculate the cosine.
```suggestion
- `angle`: The angle in radians for which you want to calculate the `cosine`.
```

2023-11-07 13:03 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/cosin/cosin.md
> +an angle.
```suggestion
The example below demonstrates how to use `math.cos()` method to calculate the cosine of an angle:
```

2023-11-07 13:07 UTC, dakshdeepHERE requested changes

2023-11-07 13:07 UTC, dakshdeepHERE commented on content/kotlin/concepts/math-methods/terms/cosin/cosin.md
> +input angle.
```suggestion
- The `math.cos()` method returns a value of type Double representing the cosine of the input angle.
```

2023-11-08 17:01 UTC, SSwiniarski approved these changes
@yangvianno I fixed the name of the .md file and made a small change to eliminate a second-person pronoun. Now it looks good. @dakshdeepHERE can you approve this so we can merge.

2023-11-12 20:24 UTC, dakshdeepHERE approved these changes

2023-11-12 20:24 UTC, dakshdeepHERE commented
Done @SSwiniarski

2023-11-13 12:32 UTC, merged