[term entry]- kotlin offsetAt
Codecademy/docs pull request #3892
Opened 2023-11-07 11:59 UTC by vrun1208

### Description

closes #3815 
Added a new term entry for kotlin dateTime .offsetAt() method

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-07 17:22 UTC, Atharva1723 approved these changes
LGTM 👍

2023-11-08 16:52 UTC, vrun1208 commented
Hi @ishg-153, how can I be the maintainer of this repo?

2023-11-08 19:25 UTC, vaibhavmani810 reviewed
Hi @vrun1208 Looks Fine! , Sending it for second review.

2023-11-12 20:53 UTC, dakshdeepHERE requested changes
Here are some requested changes from my side.

2023-11-12 20:53 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/offsetAt/offsetAt.md
> +- `utcOffset`: An offset from UTC (Coordinated Universal Time).
```suggestion
- `UtcOffset`: An offset from UTC (Coordinated Universal Time).
```

2023-11-12 20:53 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/offsetAt/offsetAt.md
> +Output:
```suggestion
The above example will result in the following output:
```

2023-11-12 20:53 UTC, dakshdeepHERE commented on content/kotlin/concepts/datetime/terms/offsetAt/offsetAt.md
> +
```suggestion
```

2023-11-14 06:46 UTC, vrun1208 commented
> Here are some requested changes from my side.

@dakshdeepHERE, I commit the changes as you suggested!

2023-11-14 06:48 UTC, dakshdeepHERE approved these changes
Looks good to merge

2023-11-14 06:49 UTC, merged