[Edit] HTML Add Media: Headings
Codecademy/docs pull request #3894
Opened 2023-11-07 18:05 UTC by OhWilko

### Description

Added content to headings.md covering the topic of changing heading sizes.
closes issue #3229 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-07 18:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3894) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3894) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3894) it.</sub>

2023-11-08 13:40 UTC, dakshdeepHERE requested changes
One change from my side

2023-11-08 13:40 UTC, dakshdeepHERE commented on content/html/concepts/headings/headings.md
> +default size does not fill the available space correctly.
```suggestion
HTML Headings have default sizes but these can be changed using the CSS style attribute. Using the font-size property you can customize how big or small headings will appear on the webpage. This is useful if the default size does not fill the available space correctly. 
```

2023-11-08 20:51 UTC, dakshdeepHERE approved these changes
LGTM 🚀

2023-11-09 17:25 UTC, SSwiniarski approved these changes
@OhWilko I made a few changes, and now it's ready to merge.

2023-11-09 17:30 UTC, merged