Create decoct.md for PHP Math Functions
Codecademy/docs pull request #3903
Opened 2023-11-08 21:12 UTC by reganmarie

### Description

- Closes #2623 
- Created decoct.md on docs/content/php/concepts/math-functions/terms/decoct/decoct.md
- Added Title, Description, Subjects, Tags, and Catalog Content
- Added description, syntax, example, and codebyte example
- Ran through 3 online plagiarism checkers to ensure 100% unique wording and description: passed with 100%
- Followed content and style guidelines -Checked for spelling and grammar errors
- Corrected for clarity and readability

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-09 09:53 UTC, dakshdeepHERE requested changes
Few changes from my side. Otherwise looks good.

2023-11-09 09:53 UTC, dakshdeepHERE commented on content/php/concepts/math-functions/terms/decoct/decoct.md
> +Title: 'decoct()'
```suggestion
Title: '.decoct()'
```

2023-11-09 09:53 UTC, dakshdeepHERE commented on content/php/concepts/math-functions/terms/decoct/decoct.md
> +For 32-bit platforms, 4294967295 is the largest number that can be computed. For 64-bit platforms, 9223372036854775807 is the largest number that can be computed.
```suggestion
The **`.decoct()`** function takes a given decimal number and returns a `string` version of the corresponding octal value. An octal value is from the base-8 numerical system, which only uses eight digits: zero through seven. For 32-bit platforms, 4294967295 is the largest number that can be computed. For 64-bit platforms, 9223372036854775807 is the largest number that can be computed.
```

2023-11-09 09:53 UTC, dakshdeepHERE commented on content/php/concepts/math-functions/terms/decoct/decoct.md
> +This example uses the `decoct` function to convert a decimal to its octal value.
```suggestion
This example uses the `.decoct()` function to convert a decimal to its octal value.
```

2023-11-09 20:25 UTC, reganmarie commented
@dakshdeepHERE Made the suggested changes! 
- Updated `decoct()` to `.decoct()` in line 2, line 27, and line 43 to update per edit and for consistency
- Changed lines 15-19 to enclose string in `` and to take up one line versus being spaced out

2023-11-10 07:32 UTC, dakshdeepHERE approved these changes
@reganmarie this looks good for second review. 🚀

2023-11-10 18:40 UTC, reganmarie commented
Thank you @dakshdeepHERE and @KTom101! 😊

2023-11-10 23:14 UTC, caupolicandiaz approved these changes
@reganmarie @dakshdeepHERE LGTM

2023-11-10 23:15 UTC, merged