Kotlin partition
Codecademy/docs pull request #3904
Opened 2023-11-10 06:08 UTC by noahpgordon

### Description

Added **partition.md** within Kotlin Strings. Closes #3730 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-10 07:05 UTC, dakshdeepHERE requested changes
I have few comments for you @noahpgordon. 🚀

2023-11-10 07:05 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/partition/partition.md
> +Where `xString` supplies the string to be partitioned by the predicate `xPredicate`.
```suggestion
- **xString:** This supplies the string to be partitioned by the predicate.
```

2023-11-10 07:05 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/partition/partition.md
> +
explain here what is `xPradicate like you did for the `xString` above

2023-11-10 07:05 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/partition/partition.md
> +This outputs:
```suggestion
The above example results in the following output:
```

2023-11-10 19:02 UTC, KTom101 commented on content/kotlin/concepts/strings/terms/partition/partition.md
> +The following example uses the character method `.isUpperCase()` to partition a string into uppercase letter characters and other characters:
```suggestion
The following example uses `.partition()` and the character method `.isUpperCase()` to partition a string into uppercase letter characters and other characters:
```

2023-11-11 00:56 UTC, noahpgordon commented
@dakshdeepHERE @KTom101 I've made relevant edits.

2023-11-12 20:27 UTC, dakshdeepHERE approved these changes
Looks good for second review

2023-11-13 17:43 UTC, merged