[Term Entry] Lua Math .log()
Codecademy/docs pull request #3911
Opened 2023-11-11 20:40 UTC by Fejiro001

### Description

- Added the .log() method for Lua Math
- Closes Issue #3494    

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-12 17:47 UTC, dakshdeepHERE requested changes
I have requested few changes for you @Fejiro001 🚀

2023-11-12 17:47 UTC, dakshdeepHERE commented on content/lua/concepts/mathematical-library/terms/log/log.md
> +Title: 'log()'
```suggestion
Title: '.log()'
```

2023-11-12 17:47 UTC, dakshdeepHERE commented on content/lua/concepts/mathematical-library/terms/log/log.md
> +Description: 'Calculates the natural logarithm of a number.'
```suggestion
Description: 'Calculates the natural logarithmic value of a number.'
```

2023-11-12 17:47 UTC, dakshdeepHERE commented on content/lua/concepts/mathematical-library/terms/log/log.md
> +The **`log()`** function in Lua's math library calculates the natural logarithm of a given number. The natural logarithm is to the base `e`, where `e` is Euler's number, an irrational constant approx
```suggestion
The **`.log()`** function in Lua's math library calculates the natural logarithm of a given number. The natural logarithm is to the base `e`, where `e` is Euler's number, an irrational constant approximately equal to `2.71828`.
```

2023-11-12 17:47 UTC, dakshdeepHERE commented on content/lua/concepts/mathematical-library/terms/log/log.md
> +In this example, `math.log()` calculates the natural logarithm of 20.
```suggestion
In this example, `math.log()` calculates the natural logarithmic value of `20`:
```

2023-11-12 17:47 UTC, dakshdeepHERE commented on content/lua/concepts/mathematical-library/terms/log/log.md
> +The result of the above example is shown below.
```suggestion
The above example will result in the following output:
```

2023-11-12 20:23 UTC, dakshdeepHERE commented
Hey @Fejiro001, Thank you for contributing this entry. This looks good for second review.

2023-11-12 20:23 UTC, dakshdeepHERE approved these changes

2023-11-13 17:41 UTC, avdhoottt commented on content/lua/concepts/mathematical-library/terms/log/log.md
> +print(output)
```suggestion
local num = 20
local result = math.log(num)
local output = string.format("The natural Logarithm of %.0f: %.4f", num, result)
print(output)
```
Remove the extra line from the code.

2023-11-13 17:42 UTC, avdhoottt approved these changes
Looks good to merge!!

2023-11-13 18:00 UTC, merged