Add images to to rbg.md
Codecademy/docs pull request #3918
Opened 2023-11-13 18:06 UTC by troytomasch

### Description
Issue: #3737 
Added images to illustrate the examples

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-13 18:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3918) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3918) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3918) it.</sub>

2023-11-13 18:34 UTC, dakshdeepHERE reviewed
I have an overall comment for you to work on. The image you use needs to replace `an` with `a`. That's it overall it looks good to me.

2023-11-13 19:51 UTC, troytomasch commented
> I have an overall comment for you to work on. The image you use needs to replace `an` with `a`. That's it overall it looks good to me.

@dakshdeepHERE Thanks for the feedback. You bring up an interesting point and in my research I have seen it both ways. Some of the articles I saw it written out with a 'an' were https://www.semrush.com/blog/h1-tag/ and https://ahrefs.com/blog/h1-tag/. However, on Codeacademy there is an 'a' before an h2 tag in this article: https://www.codecademy.com/article/glossary-html. I think either gets the point across and I can definitely change it if you feel strongly about it.

2023-11-13 20:10 UTC, dakshdeepHERE commented
Hey @troytomasch 👋, you're totally right. If we dig deep into grammar then one might think we use `an` with vowels only but when it comes to using `an` it depends on the pronunciation too. For `h` we kind of pronoun it like `aich` so `an` is right to use it. I suggested you change it because of the other entries present in Codecademy they seem to use `a`.  I just want the entries to be consistent. Let's change it for now and wait for the second review maintainer to come and check the change. I'm amazed you did the checks from your side too. Thanks for contributing this entry. 🚀

2023-11-13 20:30 UTC, troytomasch commented
@dakshdeepHERE I agree that maintaining consistency should be the priority. I'll make that change. Thanks for the feedback!

2023-11-14 18:49 UTC, dakshdeepHERE commented
@troytomasch Thanks for the changes. This looks good for a second review.

2023-11-14 18:49 UTC, dakshdeepHERE approved these changes

2023-11-14 21:16 UTC, caupolicandiaz requested changes
@troytomasch I've added my comments. Please update the entry, and tag me when you've made the changes. Thanks

2023-11-14 21:16 UTC, caupolicandiaz commented on content/css/concepts/colors/terms/rgb/rgb.md
> +![rgb-example-1](https://github.com/troytomasch/docs/blob/css-rgb-images/media/css-rgb-example1.png)
```suggestion
![RGB White Font Example](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-rgb-example1.png)
```

2023-11-14 21:16 UTC, caupolicandiaz commented on content/css/concepts/colors/terms/rgb/rgb.md
> +![rgb-example-1](https://github.com/troytomasch/docs/blob/css-rgb-images/media/css-rgb-example1.png)
The files are in the wrong location. Please relocate the files to the filepath noted above

2023-11-14 21:16 UTC, caupolicandiaz commented on content/css/concepts/colors/terms/rgb/rgb.md
>    color: rgb(230, 230, 250);
This color is very light and is difficult to see. I would recommend changing the color and the image to something like rgb(124, 124, 242)

2023-11-14 22:25 UTC, troytomasch commented
@caupolicandiaz Made the changes you requested. Currently the images show as not found however as they have not been added. Is this the expected behavior?

2023-11-14 22:45 UTC, caupolicandiaz commented
> @caupolicandiaz Made the changes you requested. Currently the images show as not found however as they have not been added. Is this the expected behavior?

Yes, the images will not show in the preview.

2023-11-14 22:50 UTC, caupolicandiaz approved these changes
@troytomasch This is ready to merge

2023-11-14 22:51 UTC, merged