[Term Entry] Lua Tables find() #3117
Codecademy/docs pull request #3924
Opened 2023-11-14 22:50 UTC by moha230

### Description

- added concept entry loa table find()
- added a folder  find
- added a file find.md
- Closes issue  #3117 

### Type of Change

- Adding a term  entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [  ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-17 15:13 UTC, vaibhavmani810 submitted a review, later dismissed
Hi @moha230 , There is no built in function find() in lua language correct it accordingly also later on you did everything like custom function only but naming of your custom function is"table.find()" which is confusing , seems like inbuilt function is getting called.
Please modify these things.
After modification we will review it again.

2023-11-17 15:13 UTC, vaibhavmani810 commented on content/lua/concepts/tables/terms/find/find.md
> +The **find()** is a built in function that searches for a specific value in an a table and returns its index if found or `nil` if the value is not present in the table.
Find() is not a built in functions in genric lua , Please refer the documentation of the Lua.

2023-11-17 15:13 UTC, vaibhavmani810 commented on content/lua/concepts/tables/terms/find/find.md
> +The **find()** is a built in function that searches for a specific value in an a table and returns its index if found or `nil` if the value is not present in the table.
You are supposed to write the custom function find()

2023-11-23 23:38 UTC, moha230 commented
Hello @vaibhavmani810 done

2023-11-26 20:02 UTC, SSwiniarski commented
@vaibhavmani810, @moha230 This issue should have been for the Luau `table.find()` method. We shouldn't be creating custom functions for Docs, as that's not what it's for. Can we revise this PR accordingly?

2023-11-26 22:32 UTC, moha230 commented
@SSwiniarski ok will fix it Thank you

2023-11-28 05:03 UTC, moha230 commented
@vaibhavmani810 its done . Thank you

2023-11-28 17:14 UTC, SSwiniarski requested changes
@moha230 I went ahead and did my own review and highlighted a few things. One of which is the file location. This was incorrectly labeled as a Lua function in the original issue when it should have been Luau. So it needs to be moved to the `luau` directory here: `content/luau/concepts/tables/terms/find/find.md`

2023-11-28 17:14 UTC, SSwiniarski commented on content/lua/concepts/tables/terms/find/find.md
Can we change the location from `content/lua/concepts/tables/terms/find/find.md` to `content/luau/concepts/tables/terms/find/find.md`

2023-11-28 17:14 UTC, SSwiniarski commented on content/lua/concepts/tables/terms/find/find.md
> +The **find()** function is used to search for a specific value in a table and returns its index if found.The function returns `nil` if the value is not present in the table.
```suggestion
The **find()** function is used to search for a specific value in a table and returns its index if found. The function returns `nil` if the value is not present in the table.
```

2023-11-28 17:14 UTC, SSwiniarski commented on content/lua/concepts/tables/terms/find/find.md
> +
There should be a sentence after the syntax block explaining what `myTable` and `value` are.

2023-11-28 17:14 UTC, SSwiniarski commented on content/lua/concepts/tables/terms/find/find.md
> +
There should be an introductory sentence summarizing what the example is doing.

2023-11-28 17:14 UTC, SSwiniarski commented on content/lua/concepts/tables/terms/find/find.md
> +```lua
````suggestion
```pseudo
````

2023-11-29 20:36 UTC, moha230 commented
@SSwiniarski  done Thank you

2023-11-29 20:50 UTC, SSwiniarski approved these changes
@moha230 I made a few minor changes, and now it looks good to me.

2023-11-29 20:51 UTC, SSwiniarski commented
@vaibhavmani810 can you look this over and see if you approve merging this?

2023-12-19 17:28 UTC, SSwiniarski commented
@vaibhavmani810 this PR needs your approval before we can merge it.

2023-12-30 12:51 UTC, merged