Animation delay examples
Codecademy/docs pull request #3933
Opened 2023-11-16 21:25 UTC by Kadif-Ravik

### Description

Examples of the animation delay property

### Type of Change

- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-16 21:33 UTC, Kadif-Ravik commented
@SSwiniarski

2023-11-17 03:46 UTC, dakshdeepHERE requested changes
Have 2 comments for you

2023-11-17 03:46 UTC, dakshdeepHERE commented on content/css/concepts/animations/terms/animation-delay/animation-delay.md
> +![Examples 1 animations(https://raw.githubusercontent.com/Codecademy/docs/main/media/animation-delay-example1.gif)
```suggestion
![Example 1 animation](https://raw.githubusercontent.com/Codecademy/docs/main/media/animation-delay-example1.gif)
```

2023-11-17 03:46 UTC, dakshdeepHERE commented on content/css/concepts/animations/terms/animation-delay/animation-delay.md
> +![Examples 2 animations(https://raw.githubusercontent.com/Codecademy/docs/main/media/animation-delay-example2.gif)
```suggestion
![Example 2 animation](https://raw.githubusercontent.com/Codecademy/docs/main/media/animation-delay-example2.gif)
```

2023-12-11 16:46 UTC, dakshdeepHERE requested changes
Have one last request for you to work on @Kadif-Ravik

2023-12-11 16:46 UTC, dakshdeepHERE commented on content/css/concepts/animations/terms/animation-delay/animation-delay.md
> +![Example 2 animation](https://raw.githubusercontent.com/Codecademy/docs/main/media/animation-delay-example2.gif)
@Kadif-Ravik can be specific in the tags what the animation will do. Like Animations example with delay of 2 seconds.

2023-12-11 17:49 UTC, dakshdeepHERE commented on content/css/concepts/animations/terms/animation-delay/animation-delay.md
> +![Example 2, after the first animation delay second animation for 6000 milliseconds](https://raw.githubusercontent.com/Codecademy/docs/main/media/animation-delay-example2.gif)
```suggestion
![Example 2, after the first animation delay the second animation for 6000 milliseconds](https://raw.githubusercontent.com/Codecademy/docs/main/media/animation-delay-example2.gif)
```

2023-12-12 16:16 UTC, dakshdeepHERE approved these changes

2023-12-12 16:17 UTC, dakshdeepHERE commented
Looks good for second review @Kadif-Ravik 🚀

2023-12-14 13:09 UTC, SSwiniarski approved these changes
@Kadif-Ravik Looks good!

2023-12-14 13:10 UTC, merged