CSS [Edit] CSS animation-direction
Codecademy/docs pull request #3934
Opened 2023-11-16 23:58 UTC by Kadif-Ravik

### Description

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-17 08:56 UTC, dakshdeepHERE reviewed
I only have one question for you @Kadif-Ravik. Let me know what you think of it.

2023-11-17 08:56 UTC, dakshdeepHERE commented on content/css/concepts/animations/terms/animation-direction/animation-direction.md
> +![Example 2 animation](https://raw.githubusercontent.com/Codecademy/docs/main/media/animation-direction-example2.gif)
Can we give better names to these tags? As if this gif doesn't load then this text will show.

2023-11-21 22:31 UTC, dakshdeepHERE approved these changes
Looks good for second review

2023-11-28 08:02 UTC, ishg-153 requested changes
@Kadif-Ravik I've suggested minor changes in the `alt-text` (text in square brackets) of the output images. Please make those.

2023-11-28 08:02 UTC, ishg-153 commented on content/css/concepts/animations/terms/animation-direction/animation-direction.md
> +![Animation of example 1 with animation direction as reverse](https://raw.githubusercontent.com/Codecademy/docs/main/media/animation-direction-example1.gif)
```suggestion
![Animation with reverse animation-direction](https://raw.githubusercontent.com/Codecademy/docs/main/media/animation-direction-example1.gif)
```

2023-11-28 08:02 UTC, ishg-153 commented on content/css/concepts/animations/terms/animation-direction/animation-direction.md
> +![Animation of example 2 with animation direction as alternate and altrernate-reverse](https://raw.githubusercontent.com/Codecademy/docs/main/media/animation-direction-example2.gif)
```suggestion
![Animation with animation-direction as alternate and altrernate-reverse](https://raw.githubusercontent.com/Codecademy/docs/main/media/animation-direction-example2.gif)
```

2023-11-29 12:55 UTC, ishg-153 approved these changes
@Kadif-Ravik This is ready to merge.

2023-11-29 12:59 UTC, merged