[Concept Entry] Swift Ranges
Codecademy/docs pull request #3935
Opened 2023-11-17 09:10 UTC by gracekishino

### Description

Add an entry for Swift Ranges.

Added new folder `ranges` inside `content/swift/concepts/`.
Added new entry file `content/swift/concepts/ranges/ranges.md`.

Closes #3487 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-18 18:02 UTC, dakshdeepHERE requested changes
Few comments from my side for you @gracekishino to address. Then we will move to second review. :)

2023-11-19 04:03 UTC, gracekishino commented on content/swift/concepts/ranges/ranges.md
> +let newRange = lower..<upper
I changed the text to include this.

2023-11-19 04:15 UTC, gracekishino commented on content/swift/concepts/ranges/ranges.md
> +`ClosedRange` instances are declared using the `...` operator. They contain values from a lower bound up to and **including** an upper bound.
I added in more detail for half-open and closed ranges in a few places.

2023-11-19 04:18 UTC, gracekishino commented
@dakshdeepHERE thanks for the review! I committed your suggestions and also added in more information about "half-open range" and "closed ranges" in a few more places.

2023-11-21 22:28 UTC, dakshdeepHERE requested changes
Thanks for the commits @gracekishino, I have two more comments for you to work on.

2023-11-21 22:28 UTC, dakshdeepHERE commented on content/swift/concepts/ranges/ranges.md
> +**Ranges** are used to create an interval of values. There are two kinds of range [structures](https://www.codecademy.com/resources/docs/swift/structures), `Range` for creating half-open ranges and `
```suggestion
**Ranges** are used to create an interval of values. There are two kinds of range [structures](https://www.codecademy.com/resources/docs/swift/structures), `Range` for creating `half-open` ranges and `ClosedRange` for creating closed ranges.
```

2023-11-21 22:28 UTC, dakshdeepHERE commented on content/swift/concepts/ranges/ranges.md
> +The example below uses **for-in loops** with a half-open range and then a closed range to print some emoji trees:
```suggestion
The example below uses `for-in loops` with a `half-open` range and then a `closed range` to print some emoji trees:
```

2023-11-22 05:17 UTC, gracekishino commented
@dakshdeepHERE thanks for the new comments! Though I think "half-open range" and "closed range" are clearer without the formatting, is there a reason they need to have it? Also if we add the formatting to "for-in loops" then does it also need to be added to "switch", "array", etc.?

2023-11-22 20:19 UTC, dakshdeepHERE commented
@gracekishino I formated the `half-open` because `ClosedRange` was formatted in the desc para. It was suggested just to be consistent. Also yes we use the backticks when we are referring to elements as they appear in code (properties, methods, functions, commands, expressions, etc.).

2023-11-25 10:32 UTC, gracekishino commented
@dakshdeepHERE thanks for the clarification! 
In Swift the structure for half-open ranges is called `Range` and the structure for closed ranges is called `ClosedRange` so that's why I formatted them with backticks and didn't format the descriptive words before them. I pushed a new commit with backticks around the `for-in` loop command. 
Do you think it's OK like this?

2023-11-27 12:57 UTC, dakshdeepHERE commented
Oh, I see @gracekishino, that makes sense. Let me go through the entry again. I think this is ready for a second review. Again an amazing entry 🚀

2023-11-27 13:00 UTC, dakshdeepHERE approved these changes
This is ready for second review @gracekishino. I added a tag from my side.🚀

2023-11-27 17:04 UTC, SSwiniarski approved these changes
@gracekishino This looks good to me.

2023-11-27 17:25 UTC, merged

2023-11-28 05:53 UTC, gracekishino commented
@dakshdeepHERE and @SSwiniarski thanks so much for reviewing! 🙏

2023-11-28 08:06 UTC, dakshdeepHERE commented
No worries @gracekishino 🫡 Amazing entry 🚀