[Edit] Small edit to fix syntax errors in rdf.md
Codecademy/docs pull request #3945
Opened 2023-11-20 06:02 UTC by noahpgordon

### Description

Fixed some mistakes in the syntax of the example of Turtle within **rdf.md**. Also deleted a sentence that I decided was misleading.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-20 19:52 UTC, dakshdeepHERE requested changes
One comment otherwise LGTM. 🚀

2023-11-20 19:52 UTC, dakshdeepHERE commented on content/general/concepts/semantic-technologies/terms/rdf/rdf.md
> +- _Blank node_: Blank nodes do not specify anything in particular. They allow for statements that say that something stands in a given relationship without identifying what that thing is.
```suggestion
- _Blank node_: Does not specify anything in particular. Allows statements stating that something stands in a given relationship without identifying what that thing is.
```

2023-11-20 23:15 UTC, noahpgordon commented
@dakshdeepHERE I edited the description of blank nodes.

2023-11-21 22:19 UTC, dakshdeepHERE approved these changes
Looks good for second review

2023-11-22 12:45 UTC, SSwiniarski approved these changes
@noahpgordon Looks good

2023-11-22 12:47 UTC, merged