[TERM] : Added new term entry in python for ljust method in strings
Codecademy/docs pull request #3946
Opened 2023-11-20 10:19 UTC by Atharva1723

Resolves #3284

### Description
Added a new term entry for the ljust() method. The description provides an explanation of the method, detailing its functionality in left-aligning a string with a specified fill character (defaulting to space).

### Type of Change

Documentation Update

- Adding a new entry
- Updating the documentation

### Checklist

- [ ✔] All writings are my own.
- [ ✔ ] My entry follows the Codecademy Docs style guide.
- [ ✔ ] My changes generate no new warnings.
- [ ✔] I have performed a self-review of my own writing and code.
- [ ✔] I have checked my entry and corrected any misspellings.
- [ ✔ ] I have made corresponding changes to the documentation if needed.
- [ ✔ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ✔ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ✔] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-20 14:49 UTC, ishg-153 requested changes
>Make sure to read all the comments and suggestions carefully.

@Atharva1723 I have added my comments; please address them.

2023-11-20 14:49 UTC, ishg-153 commented on content/python/concepts/strings/terms/ljust/ljust.md
> +string.ljust(length,fillchar)
```suggestion
string.ljust(length, fillchar)
```

2023-11-20 14:49 UTC, ishg-153 commented on content/python/concepts/strings/terms/ljust/ljust.md
> +The `.ljust()` method is used to left align the string with the width specified. If the specified width is more than the length of the string, then the remaining part of the string is filled with `fi
```suggestion
- `length`:
- `fillchar`:
```
Explain both these variables that were used in syntax.

2023-11-20 14:49 UTC, ishg-153 commented on content/python/concepts/strings/terms/ljust/ljust.md
> +
```suggestion
exampleString = 'User, Welcome to docs'
exampleString = exampleString.ljust(22, '!')
print(exampleString)
```
Removed a blank line.

2023-11-20 14:49 UTC, ishg-153 commented on content/python/concepts/strings/terms/ljust/ljust.md
> +
```suggestion
Hello Contributors!!
```
Removed a blank line.

2023-11-20 14:49 UTC, ishg-153 commented on content/python/concepts/strings/terms/ljust/ljust.md
> +```
```suggestion
```python
text = 'Hello Contributors'
left_aligned_text = text.ljust(20, '!')
print(left_aligned_text)
```
```
Removed a blank line.

2023-11-20 14:49 UTC, ishg-153 commented on content/python/concepts/strings/terms/ljust/ljust.md
> +The default fillchar is a blank space. The original string is retrieved if the width is less than or equal to the given string length.
```suggestion
The default `fillchar` is a blank space. The original string is retrieved if the length is less than or equal to the given string's length.
```
Also, move this above the "Example" header.

2023-11-20 14:49 UTC, ishg-153 commented on content/python/concepts/strings/terms/ljust/ljust.md
> +The **`.ljust()`** method left-aligns a string with a specified fill character
Please add the following points:
- is a method for strings
- returns a left0aligned string of the length given
Feel free to cover other relevant information.

2023-11-20 14:49 UTC, ishg-153 commented on content/python/concepts/strings/terms/ljust/ljust.md
> +> **Note:** `.ljust()` returns a new string and does not modify the original string and only one specific character can be mentioned to fill the remaining part of the string with fillchar.
```suggestion
> **Note:** `.ljust()` returns a new string and does not modify the original string. Only one specific character can be mentioned to fill the remaining part of the string with fillchar.
```

2023-11-20 15:44 UTC, Atharva1723 commented
@ishg-153 I have commited your suggestions and also added some from my side

2023-11-21 14:10 UTC, ishg-153 requested changes
@Atharva1723 I have suggested one change. Please make that. Everything else looks good.

2023-11-21 14:10 UTC, ishg-153 commented on content/python/concepts/strings/terms/ljust/ljust.md
> +The method **`.ljust()`** adds padding of a specified length to the right of a given string. The user can specify a character to use as the padding. The number of padding characters added is equal to
```suggestion
The method **`.ljust()`** left aligns a string for the given length of characters. If the length of the string is less than the parameter given, then padding is added to the right of a given string. The user can specify a character to use as the padding. The number of padding characters added is the length of the string provided subtracted from the length specified in the method call.
```

2023-11-23 12:52 UTC, ishg-153 approved these changes
@Atharva1723 This looks ready for a second review.

2023-11-24 14:21 UTC, avdhoottt requested changes
Nice Work @Atharva1723, I have suggested some minor changes, make them and I'll merge it.

2023-11-24 14:21 UTC, avdhoottt commented on content/python/concepts/strings/terms/ljust/ljust.md
> +> **Note:** `.ljust()` returns a new string and does not modify the original string. Only one specific character can be mentioned to fill the remaining part of the string with fillchar.
```suggestion
> **Note:** `.ljust()` returns a new string and does not modify the original string. Only one specific character can be mentioned to fill the remaining part of the string with the parameter `fillchar`.
```
Some readers might get confused if they directly read the sentence. I think it'll be a good practice to mention that it is a parameter.

2023-11-24 14:21 UTC, avdhoottt commented on content/python/concepts/strings/terms/ljust/ljust.md
> +The default `fillchar` is a blank space. The original string is retrieved if the length is less than or equal to the given string's length.
```suggestion
The default value for the parameter `fillchar` is a blank space. The original string is retrieved if the length is less than or equal to the given string's length.
```
Same suggestion for this, mentioning that it is a parameter will be helpful to the reader.

2023-11-24 14:21 UTC, avdhoottt commented on content/python/concepts/strings/terms/ljust/ljust.md
> +- `fillchar`: A character to fill the missing space (to the right of the string). Default is " " (space).
```suggestion
- `fillchar`: A character to fill the missing space (to the right of the string). The default value is " " (space).
```

2023-11-26 06:50 UTC, avdhoottt approved these changes
Ready to get merged!

2023-11-26 06:59 UTC, merged