Decode from string
Codecademy/docs pull request #3948
Opened 2023-11-20 15:03 UTC by christopher-spencer

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-21 17:03 UTC, avdhoottt requested changes
@christopher-spencer Great that you have added the entry in the serialization folder. I have suggested a small change for you to make and the last thing, I think you have mistakenly committed some other file too, please remove that from the PR. :)

2023-11-21 17:03 UTC, avdhoottt commented on content/kotlin/concepts/serialization/terms/decodeFromString/decodeFromString.md
> +}
```suggestion
import kotlinx.serialization.*
import kotlinx.serialization.json.Json

@Serializable
data class Person(val name: String, val age: Int)

fun main() {
  val jsonString = """
  {
    "name": "Johnny",
    "age": 30
  }
  """
  // Deserialize the JSON string into a Person object using decodeFromString()
  val person = Json.decodeFromString<Person>(jsonString)
  println(person)
}
```
I think the json class needs to be added separately, its not working in my machine without it. let me know if it's the same for you.

2023-11-23 17:28 UTC, avdhoottt approved these changes
Looks Good :)

2023-11-27 19:05 UTC, dakshdeepHERE requested changes
For now work on these 2 changes @christopher-spencer. I might have more suggestions.

2023-11-27 19:05 UTC, dakshdeepHERE commented on content/kotlin/concepts/serialization/terms/decodeFromString/decodeFromString.md
> +This will print the following output:
```suggestion
The above example will result in the following output:
```

2023-11-29 18:17 UTC, dakshdeepHERE approved these changes
Looks good for second review @christopher-spencer.

2023-12-07 18:15 UTC, dakshdeepHERE approved these changes

2023-12-07 18:46 UTC, merged