Gani encode to hex string
Codecademy/docs pull request #3971
Opened 2023-11-21 13:11 UTC by rusliabdulgani

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-21 13:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3971) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3971) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: rusliabdulgani<br/>:x: fullertonhealthapp<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3971) it.</sub>

2023-11-21 13:14 UTC, rusliabdulgani commented
i just did normal pull request, but why the account of fullertonhealthapp still included in my pull request commiters? i confuse now, how to resolve it? 
so i cannot passed the signed CLA

2023-11-21 13:40 UTC, ishg-153 commented
> i just did normal pull request, but why the account of fullertonhealthapp still included in my pull request commiters? i confuse now, how to resolve it? so i cannot passed the signed CLA

It's because you made a PR from the same branch. You can delete that branch and close this PR. Make a new branch and add your file from the correct account, and then you can open a new PR.

Make sure you have that file locally saved before doing this.

2023-11-21 22:10 UTC, dakshdeepHERE commented
@rusliabdulgani Keep the file which is on this path `docs/content/kotlin/concepts/serializarion/terms/encodeToHexString/encodeToHexString.md`. Remove the other one from this PR.

2023-11-21 22:16 UTC, dakshdeepHERE requested changes
Initial review changes and remove the other file from this PR.

2023-11-21 22:16 UTC, dakshdeepHERE commented on content/kotlin/concepts/serialization/terms/encodeToHexString/encodeToHexString.md
> +This method is part of the kotlinx.serialization library, which provides a comprehensive framework for serialization and deserialization of data in various formats.
```suggestion
The **`.encodeToHexString()`** is a method used to serialize and encode a given value to a hexadecimal string representation.   This method is part of the `kotlinx.serialization` library, which provides a comprehensive framework for serialization and deserialization of data in various formats.
```

2023-11-21 22:16 UTC, dakshdeepHERE commented on content/kotlin/concepts/serialization/terms/encodeToHexString/encodeToHexString.md
> +The **`.encodeToHexString()`** method takes a value as input and performs the following steps:
```suggestion
The `.encodeToHexString()` method takes a value as input and performs the following steps:
```

2023-11-21 22:16 UTC, dakshdeepHERE commented on content/kotlin/concepts/serialization/terms/encodeToHexString/encodeToHexString.md
> +  2. Encoding: It converts the byte array into a hexadecimal string representation.
```suggestion
- `Serialization`: It serializes the given value into a byte array using the appropriate serializer.
- `Encoding`: It converts the byte array into a hexadecimal string representation.
```

2023-11-21 22:16 UTC, dakshdeepHERE commented on content/kotlin/concepts/serialization/terms/encodeToHexString/encodeToHexString.md
> +## Syntax
```suggestion
## Syntax

```

2023-11-21 22:16 UTC, dakshdeepHERE commented on content/kotlin/concepts/serialization/terms/encodeToHexString/encodeToHexString.md
> +
```suggestion
- `serializer`: An instance of SerializationStrategy that defines how the data should be serialized.
- `value`: The object or data to be serialized to a hex string.

```

2023-11-21 22:16 UTC, dakshdeepHERE commented on content/kotlin/concepts/serialization/terms/encodeToHexString/encodeToHexString.md
> +Here is an example of how to use **`encodeToString()`** to serialize data into a hex string:
```suggestion
Here is an example of how to use `encodeToString()` to serialize data into a hex string:
```

2023-11-21 22:16 UTC, dakshdeepHERE commented on content/kotlin/concepts/serialization/terms/encodeToHexString/encodeToHexString.md
> +    // Cetak data objek User dalam format hexadecimal
What is `objek` `cetak` here?

2023-11-21 22:16 UTC, dakshdeepHERE commented on content/kotlin/concepts/serialization/terms/encodeToHexString/encodeToHexString.md
> +This will print following output:
```suggestion
The above example will print the following output:
```

2023-11-21 22:16 UTC, dakshdeepHERE commented on content/kotlin/concepts/serialization/terms/encodeToHexString/encodeToHexString.md
> +
```suggestion
```

2023-11-23 18:55 UTC, dakshdeepHERE commented
@rusliabdulgani check once what email you are using locally in your CLI. Run this command once:
`gh auth status` check if it's the same mail you are trying to sign CLA with. If it is then delete the current file go to main branch create a new branch commit the file there and create a new PR.

2024-01-01 09:37 UTC, dakshdeepHERE commented
@rusliabdulgani hello what is status for this PR? Are still willing to work on this issue?

2024-01-05 17:10 UTC, closed without merging

2024-01-05 17:10 UTC, dakshdeepHERE commented
Because the author is responding to the commit changes I'm closing this PR and the issue will be assigned to someone else.