[Term Entry] CSS Filter Function: Opacity() Example 2
Codecademy/docs pull request #3973
Opened 2023-11-22 05:20 UTC by giliopoulosaz

### Description

- Added a image/media .png for opacity()
- Closes issue #3969 

### Type of Change

- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-22 05:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3973) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3973) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3973) it.</sub>

2023-11-22 10:55 UTC, dakshdeepHERE reviewed
I have one comment for you @giliopoulosaz

2023-11-22 10:55 UTC, dakshdeepHERE commented on content/css/concepts/filter-functions/terms/opacity/opacity.md
> +![css-filterfunction-opacity-example2](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-filterfunction-opacity-example2.png)
@giliopoulosaz in the generated issue you were instructed to add media of the current example. No need to create a new example and add media for it.

2023-11-23 03:44 UTC, giliopoulosaz commented
@dakshdeepHERE updated the file, removed Example 2 and just added media to the existing example.

2023-11-25 04:50 UTC, dakshdeepHERE approved these changes
Looks good to me @giliopoulosaz

2023-11-25 09:36 UTC, ishg-153 requested changes
@giliopoulosaz I've suggested some changes. Please read all of them and then start making the changes.

2023-11-25 09:36 UTC, ishg-153 commented on content/css/concepts/filter-functions/terms/opacity/opacity.md
> +![css-filterfunction-opacity-example](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-filterfunction-opacity-example.png)
Add a more descriptive `alt-text` (text inside the square brackets).

It should give information about the image.

2023-11-25 09:36 UTC, ishg-153 commented on content/css/concepts/filter-functions/terms/opacity/opacity.md
> +![css-filterfunction-opacity-example](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-filterfunction-opacity-example.png)
From your output remove the text below the images reading `Image with opacity filter` and `Image without opacity filter`.

```suggestion
![css-filterfunction-opacity-example](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-filterfunction-opacity-example.png)

[add the description here]
```
Then add a sentence below the output that states which image is which.

2023-11-25 09:36 UTC, ishg-153 commented on content/css/concepts/filter-functions/terms/opacity/opacity.md
> +![css-filterfunction-opacity-example](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-filterfunction-opacity-example.png)
For the output itself, other entries show the original image first followed by the image with filter to the right. For the sake of uniformity, please reorder those images.

2023-11-25 18:54 UTC, giliopoulosaz commented
@ishg-153 made the changes you requested.

2023-11-26 07:05 UTC, ishg-153 approved these changes
@giliopoulosaz This looks ready to merge.

2023-11-26 07:07 UTC, merged