html-attribute-id-addmedia
Codecademy/docs pull request #3974
Opened 2023-11-22 08:14 UTC by ROOHITH

### Description

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-22 08:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3974) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3974) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3974) it.</sub>

2023-11-22 20:23 UTC, dakshdeepHERE requested changes
Change the image description that you are using in `[]`. Make them a bit descriptive about the image. As if the images/gif failed to load then this text will show there instead.

2023-11-23 05:11 UTC, ROOHITH commented
I have made the changes that were requested.

2023-11-23 19:54 UTC, dakshdeepHERE approved these changes
@ROOHITH looks good for second 2nd review

2023-11-24 14:09 UTC, ishg-153 requested changes
@ROOHITH I have suggested changes in the `alt-text`. Please make those.

2023-11-24 14:09 UTC, ishg-153 commented on content/html/concepts/attributes/terms/id/id.md
> +![Screenshot that shows an example of a unique id attribute.](https://raw.githubusercontent.com/Codecademy/docs/main/media/html-attribute-id-example-img1.png)
```suggestion
![Use of unique id attribute with inline CSS](https://raw.githubusercontent.com/Codecademy/docs/main/media/html-attribute-id-example-img1.png)
```

2023-11-24 14:09 UTC, ishg-153 commented on content/html/concepts/attributes/terms/id/id.md
> +![Shows how navigating a section on the same page and another page uses a unique id attribute.](https://raw.githubusercontent.com/Codecademy/docs/main/media/html-attribute-id-example2-gif.gif)
```suggestion
![Use of a unique id attribute for navigation on the same and other pages in the website](https://raw.githubusercontent.com/Codecademy/docs/main/media/html-attribute-id-example2-gif.gif)
```

2023-11-24 14:09 UTC, ishg-153 commented on content/html/concepts/attributes/terms/id/id.md
> +![CSS styling using id selector.](https://raw.githubusercontent.com/Codecademy/docs/main/media/html-attribute-id-exampl3.png)
```suggestion
![CSS styling using id selector](https://raw.githubusercontent.com/Codecademy/docs/main/media/html-attribute-id-exampl3.png)
```

2023-11-24 14:09 UTC, ishg-153 commented on content/html/concepts/attributes/terms/id/id.md
> +![The javascript uses the id attribute to style the html element.](https://raw.githubusercontent.com/Codecademy/docs/main/media/html-attribute-id-example4.png)
```suggestion
![Use of id attributes to style HTML elements in JavaScript](https://raw.githubusercontent.com/Codecademy/docs/main/media/html-attribute-id-example4.png)
```

2023-11-24 14:32 UTC, ishg-153 approved these changes
@ROOHITH Great! This is ready to merge.

2023-11-24 14:33 UTC, merged