[Term Entry] UI/UX Focus group
Codecademy/docs pull request #3975
Opened 2023-11-24 14:35 UTC by ShatilKhan

### Description

Closes #3889 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-25 04:43 UTC, dakshdeepHERE requested changes
For now work on these comments @ShatilKhan.

2023-11-25 04:43 UTC, dakshdeepHERE commented on content/uiux/focus-group/focus-group.md
> +
```suggestion
```
No need for this header

2023-11-25 04:43 UTC, dakshdeepHERE commented on content/uiux/focus-group/focus-group.md
> +  - 'User Interface Design'
This is wrong choose subjects only from this [file](https://github.com/Codecademy/docs/blob/main/documentation/subjects.md)

2023-11-25 04:43 UTC, dakshdeepHERE commented on content/uiux/focus-group/focus-group.md
> +  - 'User Research'
```suggestion
  - 'UI'
```

2023-11-25 04:43 UTC, dakshdeepHERE commented on content/uiux/focus-group/focus-group.md
> +  - 'Design Thinking'
```suggestion
  - 'UX'
```

2023-11-25 04:43 UTC, dakshdeepHERE commented on content/uiux/focus-group/focus-group.md
> +
```suggestion
```

2023-11-25 04:43 UTC, dakshdeepHERE commented on content/uiux/focus-group/focus-group.md
> +- **Validate Design Decisions:** Validate design decisions through user opinions and preferences.
```suggestion
- **Understand User Perspectives:** Gain a deeper understanding of how users interact with a product or service.

- **Collect Feedback:** Obtain direct feedback on design elements, usability, and overall user experience.

- **Identify Pain Points:** Identify pain points and challenges users may face during interaction.

- **Generate Ideas:** Stimulate creative thinking and generate new design ideas.

- **Validate Design Decisions:** Validate design decisions through user opinions and preferences.
```
Let's be consistent with the spacing throughout the entry

2023-11-25 04:43 UTC, dakshdeepHERE commented on content/uiux/focus-group/focus-group.md
> +A typical UI/UX focus group involves:
```suggestion
A typical **UI/UX focus group** involves:
```

2023-11-25 04:43 UTC, dakshdeepHERE commented on content/uiux/focus-group/focus-group.md
> +5. **Post-Session Analysis:** Analyze the collected data to derive actionable insights for design improvements.
```suggestion
- **Selection of Participants:** Carefully select a diverse group of participants representing the target user demographic.
  
- **Preparation of Materials:** Prepare prototypes, wireframes, or design concepts for participants to evaluate.

- **Facilitation:** A skilled facilitator guides the discussion, encouraging participants to express their thoughts, opinions, and concerns.

- **Observation:** Designers and stakeholders observe the session, taking notes on participant reactions and comments.

- **Post-Session Analysis:** Analyze the collected data to derive actionable insights for design improvements.
```

2023-11-30 18:10 UTC, dakshdeepHERE commented
@ShatilKhan can you commit the changes? It's been over a week now.

2023-12-12 16:51 UTC, dakshdeepHERE commented
Hey @ShatilKhan, can you please work on the comments above please so we can move forward with the PR? We will wait another week and then close with PR moving forward with someone else working on this PR.

2023-12-12 17:07 UTC, ShatilKhan commented
Yeah sorry for the delay, I'll work on them right away

On Tue, Dec 12, 2023, 10:51 PM Daksha Deep ***@***.***> wrote:

> Hey @ShatilKhan <https://github.com/ShatilKhan>, can you please work on
> the comments above please so we can move forward with the PR? We will wait
> another week and then close with PR moving forward with someone else
> working on this PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Codecademy/docs/pull/3975#issuecomment-1852425871>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMQQD6HR4WB6QEMPQ25S2S3YJCDQFAVCNFSM6AAAAAA7ZHAMU6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJSGQZDKOBXGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-15 18:01 UTC, dakshdeepHERE commented
@ShatilKhan I'm looking forward to the changes.

2023-12-15 18:32 UTC, ShatilKhan reviewed
Done with the proposed changes

2023-12-17 16:44 UTC, dakshdeepHERE approved these changes
Looks good for second review @ShatilKhan :)

2023-12-20 17:26 UTC, ishg-153 commented on content/uiux/focus-group/focus-group.md
> +- **Post-Session Analysis:** Analyze the collected data to derive actionable insights for design improvements.
Move the structure before the purpose.

2023-12-20 17:37 UTC, ishg-153 commented on content/uiux/focus-group/focus-group.md
> +5. **Closing Remarks:** Thank participants, provide incentives if applicable, and communicate next steps in the design process.
The example seems very similar to `## Structure`. Try to explain what focus group interactions would be like through it.

2023-12-20 17:37 UTC, ishg-153 commented on content/uiux/focus-group/focus-group.md
> +UI/UX focus groups play a crucial role in creating user-centered designs. By understanding user perspectives and incorporating direct feedback, designers can refine and optimize products to meet the
This seems unnecessary and isn't accurate either. Please remove this.

2024-01-03 17:18 UTC, ishg-153 commented
@ShatilKhan You've made one of the suggested changes. Can you address the remaining changes as well?

2024-01-18 18:19 UTC, ishg-153 approved these changes
@ShatilKhan I went ahead and removed the example from the entry and renamed the subheadings. This is now ready to merge.

I apologize for the delay on my part.

2024-01-18 18:36 UTC, merged