[Edit] CSS [Edit] CSS Borders: border-color
Codecademy/docs pull request #3977
Opened 2023-11-25 23:53 UTC by yeipkwa

### Description

- Added css-border-color-example1.png and css-border-color-example2.png images media directory
- Added links to example images to border-color.md file.
- Closes Issue #3640 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-25 23:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3977) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3977) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3977) it.</sub>

2023-11-26 06:50 UTC, ishg-153 requested changes
@yeipkwa The output images look great! I have requested 2 changes regarding `alt-text`. Please make those.

2023-11-26 06:50 UTC, ishg-153 commented on content/css/concepts/borders/terms/border-color/border-color.md
> +![css-border-color-example1](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-border-color-example1.png)
Add more descriptive `alt-text` (text inside the square brackets).

It should be information about the output image.

2023-11-26 06:50 UTC, ishg-153 commented on content/css/concepts/borders/terms/border-color/border-color.md
> +![css-border-color-example2](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-border-color-example2.png)
Same here, make the `alt-text` more descriptive.

2023-11-29 01:06 UTC, yeipkwa reviewed
Hi, I added more descriptive alt texts to the images. Let me know if there's anything else I need to change. Thanks!

2023-11-29 12:52 UTC, ishg-153 approved these changes
@yeipkwa Great! This looks ready for a second review.

2023-11-29 14:59 UTC, SSwiniarski approved these changes
@yeipkwa Looks good.

2023-11-29 15:03 UTC, merged