[term entry]: d3-scaling range
Codecademy/docs pull request #3981
Opened 2023-11-26 19:21 UTC by vrun1208

### Description

closes #3887 
Added new term entry - d3 Scaling .range()

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-27 18:53 UTC, dakshdeepHERE approved these changes
Looks good for second review. 🚀

2023-11-29 06:09 UTC, avdhoottt requested changes
@vrun1208 Great entry, I have suggested some minor changes, please make them.

2023-11-29 06:09 UTC, avdhoottt commented on content/d3/concepts/scaling/terms/range/range.md
> +- **.range():** The second step in defining a scale, the arguments `minOutput` and `maxOutput` are used to specify the set of values returned by the scale.
```suggestion
- `.scaleType()`: The selected scale method (e.g., `.scaleLinear()`- a continuous linear scale).
- `.domain()`: Requires the `minValue` and `maxValue` arguments to set the accepted range.
- `.range()`: The second step in defining a scale, the arguments `minOutput` and `maxOutput` are used to specify the set of values returned by the scale.
```
Use backticks to indicate methods or reserved keywords. Change the last line as it contains plagiarism (Line of `.range()`)

2023-11-29 06:09 UTC, avdhoottt commented on content/d3/concepts/scaling/terms/range/range.md
> +The above example will give the following output:
```suggestion
The above example will give the following output:
```
Change the line a little bit as it contains some plagiarism.

2023-11-29 10:28 UTC, vrun1208 commented on content/d3/concepts/scaling/terms/range/range.md
> +The **`.range()`** method is used to define the output range of a scale. The range represents the output values produced by the scale when mapped from the `domain`. The syntax for the `.range()` meth
Yes! I wrote that one. how to link this?

2023-11-29 10:31 UTC, dakshdeepHERE commented on content/d3/concepts/scaling/terms/range/range.md
> +The **`.range()`** method is used to define the output range of a scale. The range represents the output values produced by the scale when mapped from the `domain`. The syntax for the `.range()` meth
use the markdown style to link it like [this](https://www.codecademy.com/resources/docs/d3/scaling/domain)
<img width="545" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/e9c257c1-d619-492b-9005-087c6c5d33f6">

2023-11-29 10:32 UTC, vrun1208 commented on content/d3/concepts/scaling/terms/range/range.md
> +The **`.range()`** method is used to define the output range of a scale. The range represents the output values produced by the scale when mapped from the `domain`. The syntax for the `.range()` meth
okay got it 👍

2023-11-30 18:14 UTC, avdhoottt approved these changes
Ready to merge!!

2023-11-30 18:17 UTC, merged