[term entry]: d3 styling .attr()
Codecademy/docs pull request #3983
Opened 2023-11-27 13:47 UTC by vrun1208

### Description

closes #3961 
Added new term entry - d3 styling .attr()

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-29 05:37 UTC, avdhoottt requested changes
@vrun1208 Hey, Some changes from my side!! I might suggest some more changes later.

2023-11-29 05:37 UTC, avdhoottt commented on content/d3/concepts/styling/terms/attr/attr.md
> +The `.attr()` function takes two parameters, first is the name of attribute and second is the corresponding value or a callback function.
Explain the parameters separately using a bullet list.

2023-11-29 05:37 UTC, avdhoottt commented on content/d3/concepts/styling/terms/attr/attr.md
> +
Add a line describing the example.

2023-11-29 19:38 UTC, vrun1208 commented
@avdhoottt , I made the changes as you suggested

2023-12-01 17:00 UTC, avdhoottt commented on content/d3/concepts/styling/terms/attr/attr.md
> +The example given below demonstrates the arguement as a callback function. It is used to dynamically compute attribute value based on the data given. Here function is used to calculate parameter of c
```suggestion
The example given below demonstrates the argument as a callback function. It is used to dynamically compute attribute value based on the data given. Here the function is used to calculate the parameter of the circle. The callback function is passed the current data and returns the attribute value.
```

2023-12-01 17:07 UTC, avdhoottt commented on content/d3/concepts/styling/terms/attr/attr.md
> +The example given below demonstrates the argument as a callback function. It is used to dynamically compute attribute value based on the data given. Here the function is used to calculate the paramet
```suggestion
The following example shows how to use the argument as a callback function. Based on the provided data, it is used to compute attribute values dynamically. Here, the circle's parameter is calculated using the function. 
```

2023-12-01 17:07 UTC, avdhoottt approved these changes
Ready for the second review.

2023-12-07 08:13 UTC, vrun1208 commented on content/d3/concepts/styling/terms/attr/attr.md
> +
Can we use image in output as there is no written output for that

2023-12-07 08:20 UTC, dakshdeepHERE commented on content/d3/concepts/styling/terms/attr/attr.md
> +
You sure can just remember to put the gif or png in the media folder

2023-12-27 17:23 UTC, dakshdeepHERE commented on content/d3/concepts/styling/terms/attr/attr.md
> +
@vrun1208 can I get any update on the media addition?

2023-12-29 18:18 UTC, vrun1208 commented on content/d3/concepts/styling/terms/attr/attr.md
> +
@dakshdeepHERE media added 👍, check out the latest commit

2023-12-31 09:20 UTC, dakshdeepHERE approved these changes
LGTM 🚀 Thanks for the commits @vrun1208 :)

2023-12-31 09:21 UTC, merged