[EDIT] CSS Background: background-color - Add media to show output
Codecademy/docs pull request #3986
Opened 2023-11-28 10:49 UTC by myiphokodo

### Description

- Added images to show output of each code block
- Provided alt text for images
- Closes issue #3534

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-28 10:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3986) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3986) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3986) it.</sub>

2023-11-28 11:22 UTC, dakshdeepHERE approved these changes
Looks good to me

2023-11-29 11:45 UTC, ishg-153 requested changes
@myiphokodo I suggested minor changes for the `alt-text`.

Also, remove the text below `h1` that reads "The background is set to aquamarine for contrast." from both the output images.

2023-11-29 11:45 UTC, ishg-153 commented on content/css/concepts/background/terms/background-color/background-color.md
> +![Image showing h1 element with green background over an aquamarine background](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-background-color-example-1.png)
```suggestion
![Shows h1 element with green background over an aquamarine background](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-background-color-example-1.png)
```

2023-11-29 11:45 UTC, ishg-153 commented on content/css/concepts/background/terms/background-color/background-color.md
> +![Image showing h1 element with transparent background over an aquamarine background](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-background-color-example-2.png)
```suggestion
![Shows h1 element with transparent background over an aquamarine background](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-background-color-example-2.png)
```

2023-11-29 14:44 UTC, myiphokodo commented
Hello @ishg-153, I've made the suggested edits. Please let me know if there is anything else I should do :)

2023-11-29 19:04 UTC, ishg-153 approved these changes
@myiphokodo I just changed your output images to higher quality ones to expedite the process. This is ready to merge.

2023-11-29 19:43 UTC, merged