Kotlin decode from byte array
Codecademy/docs pull request #3990
Opened 2023-11-29 09:38 UTC by Fejiro001

### Description

- Added the .decodeFromByteArray() method for Kotlin Serialization
- Closes Issue #3869 

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-29 10:39 UTC, dakshdeepHERE commented
@Fejiro001 remove the identical file from the datetime folder please. We need it only in the serialisation folder

2023-11-29 10:42 UTC, dakshdeepHERE requested changes
Some initial comments for you to work on @Fejiro001. 🚀

2023-11-29 10:42 UTC, dakshdeepHERE commented on content/kotlin/concepts/serialization/terms/decodeFromByteArray/decodeFromByteArray.md
> +The **`.decodeFromByteArray()`** method is a part of the `kotlinx.serialization` library and is used to deserialize/decode (convert) byte array into a Kotlin object. Commonly used when data in byte a
```suggestion
The **`.decodeFromByteArray()`** method is a part of the **kotlinx.serialization** library and is used to deserialize/decode (convert) byte array into a Kotlin object. Commonly used when data in byte array format is transmitted and needs to be reverted back into a Kotlin object. 
```

2023-11-29 10:42 UTC, dakshdeepHERE commented on content/kotlin/concepts/serialization/terms/decodeFromByteArray/decodeFromByteArray.md
> +- `ByteArray`: the byte array containing the binary representation of the serialized object
```suggestion
- `<T>`: The type of the object to be deserialized
- `BinaryFormat`: An interface in `kotlinx.serialization` library that provides methods for serializing and deserializing Kotlin objects in binary formats
- `ByteArray`: The byte array containing the binary representation of the serialized object
```

2023-11-29 10:42 UTC, dakshdeepHERE commented on content/kotlin/concepts/serialization/terms/decodeFromByteArray/decodeFromByteArray.md
> +The following example demonstrates how to use `.decodeFromByteArray`.
```suggestion
The following example demonstrates how to use `.decodeFromByteArray`:
```

2023-11-29 10:42 UTC, dakshdeepHERE commented on content/kotlin/concepts/serialization/terms/decodeFromByteArray/decodeFromByteArray.md
> +}
```suggestion
import kotlinx.serialization.*

@Serializable
data class Person(val name: String, val age: Int)

fun main() {
  val person = Person("Alice", 25)
  val personToByteArray = ProtoBuf.encodeToByteArray(person)
  val deserializedPerson = ProtoBuf.decodeFromByteArray(personToByteArray)
  println("Original Person: $person")
  println("Deserialized Person: $deserializedPerson")
}
```

2023-12-05 17:33 UTC, dakshdeepHERE approved these changes
This looks good for second review @Fejiro001 🚀

2023-12-08 17:19 UTC, SSwiniarski requested changes
@Fejiro001 I left a few comments. Also, please make sure that your code is runnable as written. There are currently unresolved references in it.

2023-12-08 17:19 UTC, SSwiniarski commented on content/kotlin/concepts/serialization/terms/decodeFromByteArray/decodeFromByteArray.md
> +  val personToByteArray = ProtoBuf.encodeToByteArray(person)
What are these ProtoBuf references? They aren't declared anywhere.

2023-12-27 17:01 UTC, SSwiniarski approved these changes
@Fejiro001 looks good.

2023-12-27 17:07 UTC, merged