Create dataround.md for D3
Codecademy/docs pull request #3991
Opened 2023-11-29 20:36 UTC by qwertyhands

### Description

Create Codecademy Docs term entry on the .data() method for D3.

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-11-29 20:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=3991) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3991) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3991) it.</sub>

2023-11-30 21:32 UTC, qwertyhands commented
@ishg-153 I believe this was an issue which I took up, but apologies I didn't state the issue number. I've made the requested changes (hopefully satisfactorily). Thanks

2023-12-01 06:28 UTC, ishg-153 commented
@qwertyhands I apologize for the mix-up. I couldn't find the corresponding issue earlier, thanks for bringing that to my attention. I will go ahead and review the entry.

2023-12-01 06:45 UTC, ishg-153 commented
I'm sorry to do this again but could you move it back under the `selection` directory terms? So this would be the new file path:
`content/d3/concepts/selection/terms/data/data.md`

Thank you in advance for understanding.

2023-12-03 15:08 UTC, qwertyhands commented
@ishg-153 I've changed the file name as requested

2023-12-04 07:00 UTC, ishg-153 requested changes
@qwertyhands I have suggested changes. Please address them and let me know when you are done.

2023-12-04 22:06 UTC, qwertyhands commented on content/d3/concepts/selection/terms/data/data.md
> +</html>
Hopefully, my other updates are OK. But I'm afraid I can't seem to get the output to show for this. I copied and pasted the above new example code to Notepad, added the line console.log(), and saved it as an html file, which I opened to then inspect, hoping I'd get the output screenshot from this. But there seem to be errors. Please help me with this if you can. Or we can leave it if you think that's best - I chose this issue as it was beginner friendly, but I'm very inexperienced with JavaScript yet alone D3.

2023-12-06 14:34 UTC, ishg-153 approved these changes
@qwertyhands This looks good to go.

2023-12-06 14:35 UTC, ishg-153 commented
@caupolicandiaz Do you have any more suggestions for this entry? 
After your review can I move straight to merging this?

2023-12-06 14:36 UTC, ishg-153 commented
Merging this entry.

2023-12-06 14:36 UTC, merged