Term entry] UI and ux design UI ux (ideation) user pain points
Codecademy/docs pull request #4006
Opened 2023-12-01 23:54 UTC by Kadif-Ravik

### Description

Term entry for UI and UX, user pain points

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-04 21:38 UTC, Kadif-Ravik commented
@dakshdeepHERE

2023-12-05 15:24 UTC, dakshdeepHERE requested changes
Have few requests for you to work on @Kadif-Ravik 🚀

2023-12-05 15:24 UTC, dakshdeepHERE commented on content/uiux/user-pain-points/user-pain-points.md
> +**User pain points** are areas of difficulty or frustration a user encounters when using a website or program that make the experience undesirable. User pain points can be minor inconveinences to maj
```suggestion
**User pain points** are areas of difficulty or frustration a user encounters when using a website or program that make the experience undesirable. User pain points can be minor inconveniences to major issues preventing users from accessing the product or service entirely. Identifying and resolving these issues is a crucial part of web development and should be considered throughout any project. Pain points are commonly described in three levels with four types at each level
```

2023-12-05 15:24 UTC, dakshdeepHERE commented on content/uiux/user-pain-points/user-pain-points.md
> + - Relationship: users lifetime experience with a product or brand
```suggestion
- `Interaction`: User's interaction with product or support
- `Journey`: The steps it takes a user to complete a task
- `Relationship`: User's lifetime experience with a product or brand 
```

2023-12-05 15:24 UTC, dakshdeepHERE commented on content/uiux/user-pain-points/user-pain-points.md
> + - Support: relates to how organizations respond to user questions
```suggestion
- `Financial`: relates to paywalls and subscription services that lock a user out.
- `Product`: relates to the performance, quality, and usability issues while using a product
- `Process`: relates to the steps required to complete a task
- `Support`: relates to how organizations respond to user questions
```

2023-12-05 15:24 UTC, dakshdeepHERE commented on content/uiux/user-pain-points/user-pain-points.md
> +In the example below there are many elements of the web page that are sure to cause frustration for any user. A user might find it difficult to differentiate between what is an item for sale and what
```suggestion
In the example below there are many elements of the web page that are sure to cause frustration for any user. A user might find it difficult to differentiate between what is an item for sale and what is an advertisement. There are also many accessibility issues and following [Accessibility Best Practices](https://www.w3.org/WAI/tips/designing/Accessibility) will aid in solving many common issues.
```

2023-12-11 16:47 UTC, dakshdeepHERE approved these changes
Looks good for second review @Kadif-Ravik 🚀

2023-12-20 17:13 UTC, ishg-153 requested changes
@Kadif-Ravik I have suggested changes. Please make those.

2023-12-20 17:13 UTC, ishg-153 commented on content/uiux/user-pain-points/user-pain-points.md
> +**User pain points** are areas of difficulty or frustration a user encounters when using a website or program that make the experience undesirable. User pain points can be minor inconveinences to maj
```suggestion
**User Pain Points** are areas of difficulty or frustration for a user when using a product that makes the experience undesirable. These can be minor inconveniences or issues preventing users from accessing the product or service entirely.  User Pain Points can also be difficulties users face with their daily tasks. Such problems are identified at the beginning of the product development process, to build user-centric solutions. They can be identified through User Research within the User Experience (UX) design process.

User Pain Points within existing applications are commonly described in three levels with four types at each level given below.
```

2023-12-20 17:13 UTC, ishg-153 commented on content/uiux/user-pain-points/user-pain-points.md
> +![Example of a crowded website layout](https://raw.githubusercontent.com/Codecademy/docs/main/media/user-pain-points-example.png)
This example seems a little vague. Can you use a simpler example to explain a user pain point? It isn't necessary to use an image. 

If you have trouble with this, let me know.

2024-01-03 18:01 UTC, ishg-153 commented
@Kadif-Ravik It's been two weeks are you done making all the suggested changes?

2024-01-17 07:59 UTC, ishg-153 approved these changes
Merging this

2024-01-17 08:00 UTC, merged