On a seperated branch, created octdec file, then revise my entry
Codecademy/docs pull request #4033
Opened 2023-12-04 21:00 UTC by viktoriaseprenyi

### Description

- Created a new PHP entry
- It was necessary to be assigned to an issue because of my Git-Github portfolio project
- Close #3994

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-04 21:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4033) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4033) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4033) it.</sub>

2023-12-05 07:24 UTC, ishg-153 commented
@viktoriaseprenyi While I get started with reviewing this entry, please sign the CLA as prompted above.

2023-12-06 19:17 UTC, ishg-153 requested changes
@viktoriaseprenyi I have suggested some changes for you to address. Ping me once you are done.

2023-12-06 19:17 UTC, ishg-153 commented on content/php/concepts/math-functions/terms/octdec/octdec.md
> +Shortly, it means converting an octal number to a decimal number. In PHP, **octdec()** function is a built-in function that calculates the decimal equivalent of an octal number.
```suggestion
The **octdec()** function is a built-in function that calculates the decimal equivalent of an octal number. It accepts the octal number as the only argument.
```

2023-12-06 19:17 UTC, ishg-153 commented on content/php/concepts/math-functions/terms/octdec/octdec.md
> +octdec($value);
```suggestion
octdec(value);
```

2023-12-06 19:17 UTC, ishg-153 commented on content/php/concepts/math-functions/terms/octdec/octdec.md
> +It accepts a single parameter as an argument, which has to be a string representing the octal number to convert to a decimal number. It will be ignored if you try to pass an invalid character as an a
```suggestion
- `value`: It's an octal number, given as a parameter to the function, in the string format. If an invalid character is passed, it is ignored.
```

2023-12-06 19:17 UTC, ishg-153 commented on content/php/concepts/math-functions/terms/octdec/octdec.md
> +1043
```suggestion
53
24
```
Try running the example code block and cross-check. I got this output.

2023-12-06 19:17 UTC, ishg-153 commented on content/php/concepts/math-functions/terms/octdec/octdec.md
> +Run your code and try converting decimal numbers from octal numbers.
```suggestion
Run the code below to get a better idea of how the `octdec()` function works:
```

2023-12-07 20:31 UTC, viktoriaseprenyi commented
@ishg-153 I am done!  Thanks for your suggestions!

2023-12-08 15:12 UTC, ishg-153 approved these changes
@viktoriaseprenyi This looks good for a second review.

2023-12-08 21:47 UTC, viktoriaseprenyi commented
Thank you! Is there anything that I can do? :)

2023-12-10 16:07 UTC, avdhoottt requested changes
@viktoriaseprenyi Hey, Great Work!! Please make these changes and ping me when you are done!

2023-12-10 16:07 UTC, avdhoottt commented on content/php/concepts/math-functions/terms/octdec/octdec.md
> +- `value`: It's an octal number given as a parameter to the function in string format. If an invalid character is passed, it is ignored.
```suggestion
- `value`: An octal number given as a parameter to the function in string format. If an invalid character is passed, it is ignored.
```

2023-12-10 16:07 UTC, avdhoottt commented on content/php/concepts/math-functions/terms/octdec/octdec.md
> + echo octdec("3098");
```suggestion
echo octdec("65") . "<br>";
echo octdec("3098") . "<br>";
```
To print the output like below, you'll need `<br>` tags so the next statement will print on a new line.

2023-12-10 19:56 UTC, viktoriaseprenyi commented
Hello @avdhoottt. I am done with your suggested changes. :)

2023-12-11 17:38 UTC, avdhoottt approved these changes
Ready to get merged!!

2023-12-12 16:30 UTC, merged