Topic content term
Codecademy/docs pull request #4040
Opened 2023-12-07 10:54 UTC by thomasvlachos

### Description

Created term-entry for .delay() in specified path as mentioned in description.

### Type of Change

- Adding a new entry

### Checklist

- [ X] All writings are my own.
- [ X] My entry follows the Codecademy Docs style guide.
- [X ] My changes generate no new warnings.
- [ X] I have performed a self-review of my own writing and code.
- [X ] I have checked my entry and corrected any misspellings.
- [X ] I have made corresponding changes to the documentation if needed.
- [ X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-07 10:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4040) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4040) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4040) it.</sub>

2023-12-09 14:44 UTC, avdhoottt requested changes
Great Entry!! I have suggested some changes, please make them. Remove the extra line spaces from the end of the content.

2023-12-09 14:44 UTC, avdhoottt commented on content/d3/concepts/interactivity/terms/delay/delay.md
> +Description: 'It introduces a waiting period before executing subsequent actions.'
```suggestion
Description: 'Sets a waiting period before executing subsequent actions.' 
```

2023-12-09 14:44 UTC, avdhoottt commented on content/d3/concepts/interactivity/terms/delay/delay.md
> +The `.delay()` method is used in the context of transitions and sets the delay before the transition starts.
Add this line in the method introduction part.

2023-12-09 14:44 UTC, avdhoottt commented on content/d3/concepts/interactivity/terms/delay/delay.md
> +![delay-3sec](https://github.com/thomasvlachos/docs/assets/32740965/b2e96749-638d-4903-8d95-3687c5236b36)
Read the [documentation](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#file-hosting) to add the media files properly and do it accordingly.

2023-12-09 18:16 UTC, thomasvlachos reviewed
I'm not sure if this is the way to add media file. Inform me if i did something wrong to check it again. Thanks!

2023-12-10 16:38 UTC, avdhoottt requested changes
@thomasvlachos I have suggested a minor change and the rest of the content is good. You've added the image properly, Thanks for doing it.

2023-12-10 16:38 UTC, avdhoottt commented on content/d3/concepts/interactivity/terms/delay/delay.md
> +The example will result in the following output:
Give a line space after the code block.

2023-12-11 17:35 UTC, avdhoottt approved these changes
Good for the second review.

2023-12-12 16:37 UTC, dakshdeepHERE approved these changes
This looks good to merge 🚀

2023-12-12 16:43 UTC, merged