Javascript object Methods .defineProperties()
Codecademy/docs pull request #4041
Opened 2023-12-07 11:34 UTC by Brag2gr8

### Description

Added new entry for Javascript Object Methods defineProperties()
Entry Location: content/javascript/concepts/objects/terms/defineProperties/defineProperties.md. closes #4025

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-07 14:54 UTC, ishg-153 requested changes
@Brag2gr8 This is a great entry overall. I have left suggestions, please address those. Let me know when you are done.

2023-12-07 14:54 UTC, ishg-153 commented on content/javascript/concepts/objects/terms/defineProperties/defineProperties.md
> +The `Object.defineProperties()` is used to define new or modify existing properties directly on an object or to add multiple properties to an object at once. This method is often used for property de
```suggestion
The **`.defineProperties()`** method is used to define new or modify existing properties directly on an object or to add multiple properties to an object at once. This method is often used for property descriptors and fine-grained control over object properties.
```

2023-12-07 14:54 UTC, ishg-153 commented on content/javascript/concepts/objects/terms/defineProperties/defineProperties.md
> +- `descriptors`: An object where each key represents a property name, and the corresponding value is the property descriptor.
```suggestion
- `descriptors`: An object where each key represents a property name, and the corresponding value is the property descriptor.

[optional keys of descriptors]
```
`descriptors` has optional keys `value` and `writable` that you've used in the example below. Write about these keys in points. There are also keys `get` and `set` if I'm not wrong.

2023-12-07 14:54 UTC, ishg-153 commented on content/javascript/concepts/objects/terms/defineProperties/defineProperties.md
> +The `value` attribute is the value of the property and the `writable` attribute determines whether the property can be modified.
```suggestion
```
This sentence won't be necessary as we are adding that in the syntax section now.

2023-12-07 15:37 UTC, Brag2gr8 commented
@ishg-153 I just updated the changes

2023-12-27 17:14 UTC, dakshdeepHERE commented
I did some minor changes and this LGTM 🚀

2023-12-27 17:21 UTC, dakshdeepHERE commented
@Brag2gr8 can you change the current Branch name a bit? Because of the branch name ending with `-` I'm not able to push the changes I made for the yarn checks here. Make sure you keep the branch name simple and it doesn't end with `()` or `-`.

2023-12-27 17:55 UTC, closed without merging