[Term Entry] D3 Interactivity .duration()
Codecademy/docs pull request #4046
Opened 2023-12-09 11:05 UTC by andersooi

### Description

- Added the D3 Interactivity .duration() function
- Closes #4016 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-09 14:14 UTC, avdhoottt requested changes
@andersooi Great Entry!! I have suggested some minor changes, please make them.

2023-12-09 14:14 UTC, avdhoottt commented on content/d3/concepts/interactivity/terms/duration/duration.md
> +```
There's no need to add the HTML code, you can add the JavaScript part only where the method is used (Code under the Script tag).

2023-12-09 14:14 UTC, avdhoottt commented on content/d3/concepts/interactivity/terms/duration/duration.md
> +The **`.duration()`** method sets the duration for transitions. This is crucial for creating animated visualizations, allowing developers to control how long an animation takes to move from a startin
```suggestion
The **`.duration()`** method sets the duration for transitions. This method is crucial for creating animated visualizations as it allows developers to control how long an animation takes to move from a starting to an ending state. It accepts a single argument representing the time in milliseconds for the transition.
```

2023-12-10 16:32 UTC, avdhoottt approved these changes
Good to go for the second review.

2023-12-11 17:57 UTC, ishg-153 requested changes
@andersooi I have suggested a few changes. Please make those and let me know when you are done.

2023-12-11 17:57 UTC, ishg-153 commented on content/d3/concepts/interactivity/terms/duration/duration.md
> +The **`.duration()`** method sets the duration for transitions. This method is crucial for creating animated visualizations as it allows developers to control how long an animation takes to move from
```suggestion
The **`.duration()`** method sets the time for which a transition lasts. This method is crucial for creating animated visualizations as it allows developers to control the length of an animation. It accepts a single argument representing the duration in milliseconds for the transition.
```

2023-12-11 17:57 UTC, ishg-153 commented on content/d3/concepts/interactivity/terms/duration/duration.md
> +transition().duration(milliseconds)
```suggestion
transition().duration(t)
```

2023-12-11 17:57 UTC, ishg-153 commented on content/d3/concepts/interactivity/terms/duration/duration.md
> +This method requires a transition selection object and `miliseconds` as an argument. If `milliseconds` is not provided, D3 defaults to using a 250ms duration for the transition.
```suggestion
- `t`: It is the duration of the animation and the only argument taken by the `.duration()` method. If not specified, the default duration value is set to 250ms for the transition.
```

2023-12-14 14:23 UTC, andersooi commented
Hi @ishg-153 I have made the necessary changes; bumping this just in case the review request didn't go through

2023-12-19 14:52 UTC, ishg-153 approved these changes
@andersooi Great! This looks ready to merge.

2023-12-19 14:55 UTC, merged