Created concept entry for SwiftUI Notifications
Codecademy/docs pull request #4052
Opened 2023-12-11 00:52 UTC by arirays

### Description
- Added SwiftUI Notifications concept entry
- Closes issue #2682

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-11 07:50 UTC, dakshdeepHERE requested changes
Have few comments for you to work on @arirays 🚀

2023-12-11 07:50 UTC, dakshdeepHERE commented on content/swiftui/concepts/notifications/notifications.md
> +Description: 'Notifications in SwiftUI send notifications to the user's device either from a server or create them directly within an app.'
```suggestion
Description: 'It is used to send notifications to the user's device either from a server or create them directly within an app.' 
```

2023-12-11 07:50 UTC, dakshdeepHERE commented on content/swiftui/concepts/notifications/notifications.md
> +**Notifications** in SwiftUI are presented with two options types to keep users informed and engaged: Local notifications and Remote(push) notifications. Local notifications differ from remote (push)
```suggestion
**Notifications** in SwiftUI are presented with two option types to keep users informed and engaged: **Local notifications** and **Remote(push) notifications**. **Local notifications** differ from remote (push) notifications in that they don't depend on a server to deliver messages to users' devices. While **remote (push) notifications** use Apple's Push Notification Service (APNS) for message delivery, local notifications are self-contained within the app. 
```

2023-12-11 07:50 UTC, dakshdeepHERE commented on content/swiftui/concepts/notifications/notifications.md
> +Implementation in SwiftUI: Implementing local notifications in SwiftUI involves using the UNUserNotificationCenter to manage notification content, request permission, and schedule the notification de
```suggestion
- `Definition`: Local notifications are created and scheduled within the app itself, without any need for an external server. They are ideal for reminders, calendar events, or any other notifications that are triggered by the app based on user actions or predefined schedules.

- `Scheduling`: The developer sets up the timing and content of these notifications. They can be scheduled to appear at a specific time or in response to a particular event within the app.

- `User permissions`: Though less intrusive than remote notifications, local notifications still require user permission. The app must request and obtain permission to send notifications to the user.

- `Customization`: Local notifications can be customized with various options such as sound, alerts, or badges. They can also be configured to trigger certain actions when interacted with.

- `Implementation in SwiftUI`: Implementing local notifications in SwiftUI involves using the UNUserNotificationCenter to manage notification content, request permission, and schedule the notification delivery.
```

2023-12-11 07:50 UTC, dakshdeepHERE commented on content/swiftui/concepts/notifications/notifications.md
> +
```suggestion
func scheduleTimeBasedNotification() {
  // 1. Request permission to display alerts and play sounds.
  UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .sound]) { granted, error in
    if granted {
        print("Permission granted")
    } else if let error = error {
        print(error.localizedDescription)
    }
}

  // 2. Create the content for the notification
  let content = UNMutableNotificationContent()
  content.title = "Reminder"
  content.body = "Don't forget to check the app!"
  content.sound = UNNotificationSound.default

  // 3. Set up a trigger for the notification
  // For example, 10 seconds from now
  let trigger = UNTimeIntervalNotificationTrigger(timeInterval: (10), repeats: false)

  // 4. Create the request
  let request = UNNotificationRequest(identifier: UUID().uuidString, content: content, trigger: trigger)

  // 5. Add the request to the notification center
  UNUserNotificationCenter.current().add(request) { error in
    if let error = error {
        print(error.localizedDescription)
    } else {
        print("Notification scheduled")
    }
  }
}
```

2023-12-11 07:50 UTC, dakshdeepHERE commented on content/swiftui/concepts/notifications/notifications.md
> +
```suggestion
```

2023-12-11 07:50 UTC, dakshdeepHERE commented on content/swiftui/concepts/notifications/notifications.md
> +![SwiftUI Remote Push Notifications](../../../../media/swiftui-remote-push-notification.png)
```suggestion
![SwiftUI Remote Push Notifications](https://raw.githubusercontent.com/Codecademy/docs/main/media/swiftui-remote-push-notification.png)
```

2023-12-11 07:50 UTC, dakshdeepHERE commented on content/swiftui/concepts/notifications/notifications.md
> +
```suggestion
class AppDelegate: NSObject, UIApplicationDelegate {

  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .badge, .sound]) { granted, error in
        if granted {
            DispatchQueue.main.async {
                UIApplication.shared.registerForRemoteNotifications()
            }
        }
    }
    return true
}

func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    // Convert token to string and send to your server
    let tokenString = deviceToken.map { String(format: "%02.2hhx", $0) }.joined()
    print("Device push notification token: \(tokenString)")
    // Here you would typically send the token to your server
}

  func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
      print("Failed to register for remote notifications: \(error)")
  }
}
```

2023-12-13 07:22 UTC, dakshdeepHERE requested changes
I have one last question for you @arirays

2023-12-13 07:22 UTC, dakshdeepHERE commented on content/swiftui/concepts/notifications/notifications.md
> +
Is there a possibility for you to add an image example for this notification type here?

2023-12-21 14:57 UTC, dakshdeepHERE requested changes
Please check my last comments

2023-12-21 14:57 UTC, dakshdeepHERE commented on content/swiftui/concepts/notifications/notifications.md
> +![Simulator Screenshot - iPhone 15 Pro - 2023-12-20 at 16 41 31](https://github.com/arirays/docs/assets/51388551/ded8763a-245f-4ea3-af16-d680b7d0bec4)
can you add this image in the media and make this link like this:
https://raw.githubusercontent.com/Codecademy/docs/main/media/background-position-example-1.png

2023-12-21 14:57 UTC, dakshdeepHERE commented on content/swiftui/concepts/notifications/notifications.md
> +![Simulator Screenshot - iPhone 15 Pro - 2023-12-02 at 11 50 11](https://github.com/arirays/docs/assets/51388551/edad365a-7d4c-4299-945b-c2781a243744)
same here check the above comment please

2023-12-24 09:10 UTC, dakshdeepHERE approved these changes
Thank you @arirays for working on the comments. This looks good for second review 🚀

2024-01-09 07:28 UTC, arirays commented
Hi Steven @SSwiniarski, could you please review my PR?
And I have a question about my previous contributions, I see my entries posted at Codecademy, but as an anonymous contributor. I followed all contributions guidelines, but unfortunately my profile isn't visible. Is it possible to change it?
I'd really appreciate it if you could help me. Thank you!

2024-01-09 17:06 UTC, dakshdeepHERE commented
@arirays I'll let @SSwiniarski know. Also, you'll have to make your Codecademy profile public and link it with this Github email. Once linking the github is done with Codecademy account once log it out and then login using Github account. Then you can see your account on the entries. Make sure the mails are same for github.

2024-01-10 16:59 UTC, SSwiniarski commented
@dakshdeepHERE any idea on the failing check? I can't seem to get rid of it.

2024-01-10 17:32 UTC, dakshdeepHERE commented
@SSwiniarski Done, I think there was some issue with the npm and yarn update. After updating it got fixed for me.

2024-01-10 17:35 UTC, merged