[Term Entry] D3 Interactivity .ease() added
Codecademy/docs pull request #4054
Opened 2023-12-11 11:50 UTC by antriksh-9

### Description
I was assigned this [issue](https://github.com/Codecademy/docs/issues/4018).
Created Codecademy Docs term entry on the .ease() method for D3.
Closes #4018.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-12 18:44 UTC, ishg-153 requested changes
@antriksh-9 I have suggested this one change for now. Please make it, I'll let you know if there's more.

2023-12-12 18:44 UTC, ishg-153 commented on content/d3/concepts/interactivity/terms/ease/ease.md
> +The **`.ease()`** method is specific to the D3.js library, which is primarily used for data visualization on the web. It allows you to control the timing and pacing of transitions in animations.
```suggestion
The **`.ease()`** method is specific to the D3.js library, this is primarily used to add an easing effect to a transition. It allows to control the timing and pacing of transitions in animations.
```

2023-12-13 06:14 UTC, antriksh-9 commented
Hey @ishg-153 I have made the proposed changes.

2023-12-19 15:14 UTC, ishg-153 requested changes
@antriksh-9 I have suggested one more change, please make it.

2023-12-19 15:14 UTC, ishg-153 commented on content/d3/concepts/interactivity/terms/ease/ease.md
> +- `easingFunction`: It is the easing function.
You should mention the different types of easing functions below this.

2023-12-19 17:02 UTC, antriksh-9 commented
Hey @ishg-153 I have made the necessary changes.

2023-12-26 15:23 UTC, ishg-153 approved these changes
@antriksh-9 Great! Ready for a second review!

2023-12-28 17:06 UTC, avdhoottt requested changes
@antriksh-9 Great work! Some minor changes from my side.

2023-12-28 17:06 UTC, avdhoottt commented on content/d3/concepts/interactivity/terms/ease/ease.md
> +
Add a line describing that the following is the output of the given code.

2023-12-28 17:06 UTC, avdhoottt commented on content/d3/concepts/interactivity/terms/ease/ease.md
> +Here's a simple HTML structure with D3.js code to create the transition animation:
```suggestion
Consider an HTML document with an SVG element containing a circle with the specified ID `myCircle`. Here's a simple HTML structure with D3.js code to create the transition animation:

```

2023-12-28 17:17 UTC, antriksh-9 commented
Hey @avdhoottt I have made the necessary changes.

2024-01-02 13:40 UTC, avdhoottt approved these changes
Ready to get merged.

2024-01-02 13:47 UTC, merged