[Term Entry] Kotlin Strings .lowercase()
Codecademy/docs pull request #4059
Opened 2023-12-11 20:56 UTC by Fejiro001

### Description

- Added the .lowercase() method for Kotlin Strings
- Closes Issue #3980    

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-12 16:30 UTC, dakshdeepHERE requested changes
I have few comments from my side for you to work on @Fejiro001 🚀

2023-12-12 16:30 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/lowercase/lowercase.md
> +Description: 'Compares two strings lexicographically.'
```suggestion
Description: 'It is used to convert a string to lowercase'
```

2023-12-12 16:30 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/lowercase/lowercase.md
> +String.lowercase(): String
```suggestion
String.lowercase()
```
I don't think we have to mention the return type it's very obvious.

2023-12-12 16:30 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/lowercase/lowercase.md
> +}
```suggestion
fun main() {
  val originalString = "Hello, World!"
  val newString = originalString.lowercase()
  println("Original String: $originalString")
  println("Lowercased String: $newString")
}
```

2023-12-12 16:30 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/lowercase/lowercase.md
> +The code will return the following output:
```suggestion
The above code will return the following output:
```

2023-12-12 16:30 UTC, dakshdeepHERE commented on content/kotlin/concepts/strings/terms/lowercase/lowercase.md
> +Lowercase: hello, world!
```suggestion
Original String: Hello, World!
Lowercased String: hello, world!
```

2024-01-03 14:57 UTC, dakshdeepHERE approved these changes
Hey @Fejiro001, thank you for committing the changes. This looks good to me, let's move it to the second review.

2024-01-04 14:37 UTC, avdhoottt requested changes
@Fejiro001 Mentioned a few changes, please make them.

2024-01-04 14:37 UTC, avdhoottt commented on content/kotlin/concepts/strings/terms/lowercase/lowercase.md
> +Description: 'It used to convert a string to lowercase.'
```suggestion
Description: 'Converts a string to lowercase.'
```

2024-01-04 14:37 UTC, avdhoottt commented on content/kotlin/concepts/strings/terms/lowercase/lowercase.md
> +The **`.lowercase()`** method in Kotlin is changes all characters in a string to lowercase. It does not modify the original string, rather it returns a new transformed string. This is useful when cas
```suggestion
The **`.lowercase()`** method in Kotlin changes all characters in a string to lowercase. It does not modify the original string, rather it returns a new transformed string. This is useful when case-sensitive operations are performed.
```

2024-01-04 14:37 UTC, avdhoottt commented on content/kotlin/concepts/strings/terms/lowercase/lowercase.md
> +This example shows how to use the `.lowercase()` method on a string:
```suggestion
The following example shows how to use the `.lowercase()` method on a string:
```

2024-01-11 11:04 UTC, avdhoottt commented
@Fejiro001 It's been a week since I suggested the changes. Are you working on this PR?

2024-01-14 18:54 UTC, avdhoottt approved these changes
Looks good to get merged!!

2024-01-14 18:54 UTC, merged