[Term Entry] JavaScript Object Function: Object.isSealed()
Codecademy/docs pull request #4084
Opened 2023-12-13 18:55 UTC by phuongtrieu97coder

### Description

-Added the Object.isSealed() term for JavaScript
-Closes Issue #4069 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-15 18:02 UTC, avdhoottt requested changes
@phuongtrieu97coder Nice Work! I might have some more changes later, make these changes for now.

2023-12-15 18:02 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/isSealed/isSealed.md
> +This will return the following output:
```suggestion
The above code will return the following output:
```

2023-12-16 17:06 UTC, phuongtrieu97coder commented
@avdhoottt I've finished my review with all the changes. Please proceed to further review.

2023-12-18 12:16 UTC, avdhoottt requested changes
Looks good!! PR is ready for the second review.

2023-12-18 15:14 UTC, dakshdeepHERE approved these changes
Did some minor checks and this looks good for merge. 🚀

2023-12-19 14:10 UTC, avdhoottt approved these changes
Good to merge.

2023-12-19 15:34 UTC, merged