[Term Entry] JavaScript Object Function: Object.getPrototypeOf()
Codecademy/docs pull request #4085
Opened 2023-12-13 19:54 UTC by phuongtrieu97coder

### Description

-Added the Object.getPrototypeOf() term for JavaScript
-Closes Issue #4063 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-14 17:22 UTC, avdhoottt requested changes
@phuongtrieu97coder Nice Work!! I have mentioned some changes, please make them. Ping me when you are done with the changes.

2023-12-14 18:18 UTC, phuongtrieu97coder commented
@avdhoottt I've finished my review with all my changes. Please proceed to your next review.

2023-12-15 18:04 UTC, avdhoottt approved these changes
PR is ready for the second review.

2023-12-16 08:22 UTC, dakshdeepHERE requested changes
Few changes from my side

2023-12-16 08:22 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/getPrototypeOf/getPrototypeOf.md
> +Title: 'Object.getPrototypeOf()'
```suggestion
Title: '.getPrototypeOf()'
```

2023-12-16 08:22 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/getPrototypeOf/getPrototypeOf.md
> +Description: 'Returns the prototype value of the specified object.'
```suggestion
Description: 'Returns the prototype value of the specified object'
```

2023-12-16 08:22 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/getPrototypeOf/getPrototypeOf.md
> +The **`Object.getPrototypeOf()`** method is a static method that returns the prototype (the value of the internal [[Prototype]] property) of the specified object.
```suggestion
The **`.getPrototypeOf()`** method is a static method that returns the prototype (the value of the internal [[Prototype]] property) of the specified object.
```

2023-12-16 17:00 UTC, phuongtrieu97coder commented
@dakshdeepHERE  I've finished my review with all my changes. Please proceed to your next review.

2023-12-17 06:38 UTC, dakshdeepHERE approved these changes
@phuongtrieu97coder looks good to merge 🚀

2023-12-17 16:41 UTC, merged