[Term Entry] JavaScript Object Function: Object.getOwnPropertySymbols()
Codecademy/docs pull request #4088
Opened 2023-12-13 21:00 UTC by phuongtrieu97coder

### Description

-Added Object.getOwnPropertySymbols() term for JavaScript
-Closes Issue #4062 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-14 09:25 UTC, dakshdeepHERE requested changes
I have requested few changes from my side for you @phuongtrieu97coder :)

2023-12-14 09:25 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/getOwnPropertySymbols/getOwnPropertySymbols.md
> +The **`Object.getOwnPropertySymbols()`** method is a static method that returns an array of all symbol property found directly upon a given object. If the object has no own symbol properties initiall
```suggestion
The **`.getOwnPropertySymbols()`** method is a static method that returns an array of all symbol properties found directly upon a given object. If the object initially has no symbol properties, `.getOwnPropertySymbols()` returns an empty array.
```
We bold the first occurrence only

2023-12-14 09:25 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/getOwnPropertySymbols/getOwnPropertySymbols.md
> +> **Note:** **`Object.getOwnPropertySymbols()`** method itself does not contain the symbol properties of an object and only the string properties.
```suggestion
> **Note:** `Object.getOwnPropertySymbols()` method itself does not contain the symbol properties of an object and only the string properties.
```

2023-12-14 09:25 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/getOwnPropertySymbols/getOwnPropertySymbols.md
> +
```suggestion

## Examples

```

2023-12-14 09:25 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/getOwnPropertySymbols/getOwnPropertySymbols.md
> +
give a small description here of what the reader can expect from the coming code snippet like you did above

2023-12-14 09:25 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/getOwnPropertySymbols/getOwnPropertySymbols.md
> +This will return the following output:
```suggestion
The above example will return the following output:
```

2023-12-14 09:25 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/getOwnPropertySymbols/getOwnPropertySymbols.md
> +This will return the following output:
```suggestion
The above example will return the following output:
```

2023-12-14 20:23 UTC, phuongtrieu97coder commented
@dakshdeepHERE I've finished my review with all the changes. Please proceed to your next review.

2023-12-15 17:44 UTC, dakshdeepHERE requested changes
Few last changes for you to do @phuongtrieu97coder :)

2023-12-15 17:44 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/getOwnPropertySymbols/getOwnPropertySymbols.md
> +Title: 'Object.getOwnPropertySymbols()'
```suggestion
Title: '.getOwnPropertySymbols()'
```

2023-12-15 17:44 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/getOwnPropertySymbols/getOwnPropertySymbols.md
> +> **Note:** `Object.getOwnPropertySymbols()` method itself does not contain the symbol properties of an object and only the string properties.
```suggestion
> **Note:** `.getOwnPropertySymbols()` method itself does not contain the symbol properties of an object and only the string properties.
```

2023-12-15 17:44 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/getOwnPropertySymbols/getOwnPropertySymbols.md
> +
```suggestion
```

2023-12-16 17:09 UTC, phuongtrieu97coder commented
@dakshdeepHERE  I've finished my review with all the changes. Please proceed to further review.

2023-12-17 16:42 UTC, dakshdeepHERE approved these changes
Looks good for second review @phuongtrieu97coder :)

2023-12-22 16:12 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/getOwnPropertySymbols/getOwnPropertySymbols.md
> +In the following code, `Symbol()` and `Symbol.for()` will add symbol properties to the `Electronic_Devices` object. Next, the program will output the `Electronic_Devices` object into the console. The
```suggestion
In the following code, `Symbol()` and `Symbol.for()` will add symbol properties to the `Electronic_Devices` object. Next, the program will output the `Electronic_Devices` object into the console, and the `objectSymbols` variable that is assigned to `Object.getOwnPropertySymbols(object_name)` will be used to return the length of an array of all symbol properties that have been found, the array itself, and the first element in the array:
```

2023-12-22 16:15 UTC, avdhoottt approved these changes
Looks good to merge!

2023-12-22 16:24 UTC, merged