Add term: Javascript Objects: .isFrozen()
Codecademy/docs pull request #4089
Opened 2023-12-13 21:18 UTC by Jamesllllllllll

### Description

Add term entry for **Javascript Objects: `isFrozen()`**

**NOTE:** I'm not sure if I should be providing any explanation for what **frozen** is in this entry. I started learning about **configurability** and **writability** on the properties, and it seemed like it should belong in its own entry. I welcome any input on this!

Closes #4068 

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-14 09:21 UTC, dakshdeepHERE requested changes
Only one change

2023-12-14 09:21 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/isFrozen/isFrozen.md
> +The output would be:
```suggestion
The above example will give the following output:
```

2023-12-15 17:54 UTC, dakshdeepHERE approved these changes
Looks good for second review 🚀

2023-12-16 14:09 UTC, avdhoottt requested changes
@Jamesllllllllll I have mentioned two changes, please make these changes and ping me when you are done.

2023-12-16 14:09 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/isFrozen/isFrozen.md
> +The **`.isFrozen()`** static method returns `true` if the given object is _frozen_, and `false` if it is not.
```suggestion
The **`.isFrozen()`** static method returns `true` if the given object is frozen, and `false` if it is not.
```
Could you write when the object is frozen (Conditions), and add the line in the above statement?

2023-12-16 14:09 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/isFrozen/isFrozen.md
> +
Add the description for the `newObject` parameter in one line below the syntax.

2023-12-16 14:48 UTC, Jamesllllllllll commented
Thanks, @avdhoottt - let me know if I correctly resolved your suggestions.

2023-12-18 11:43 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/isFrozen/isFrozen.md
> +`newObj` is the object to be checked for its frozen state.
```suggestion
- `newObj`: It is the object to be checked for its frozen state.
```

2023-12-18 11:44 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/isFrozen/isFrozen.md
> +
```suggestion
```

2023-12-18 11:44 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/isFrozen/isFrozen.md
> +
```suggestion
```

2023-12-18 11:46 UTC, avdhoottt requested changes
Hey @Jamesllllllllll, The parameter description is fine but you have not mentioned 'what are the conditions in which we call that the object is frozen'. Please add that in the introduction paragraph or as a note below it.

2023-12-18 13:15 UTC, Jamesllllllllll commented
> Hey @Jamesllllllllll, The parameter description is fine but you have not mentioned 'what are the conditions in which we call that the object is frozen'. Please add that in the introduction paragraph or as a note below it.

Thanks, I added a description of the conditions of a frozen object. I also **bolded** the first instance of the word frozen per the Docs Style Guide.

2023-12-19 14:08 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/isFrozen/isFrozen.md
> +The **`.isFrozen()`** static method returns `true` when the given object is _frozen_, and `false` if it is not. An object is considered frozen when you cannot add new properties to it, cannot change
```suggestion
The **`.isFrozen()`** static method returns `true` when the given object is frozen, and `false` if it is not. An object is considered frozen when you cannot add new properties to it, cannot change the existing properties, and cannot delete the existing properties. For example, you can freeze an with the `Object.freeze()` static method.
```

2023-12-19 14:09 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/isFrozen/isFrozen.md
> +Checking if an object is frozen.
```suggestion
The following example checks if an object is frozen.
```

2023-12-19 14:09 UTC, avdhoottt approved these changes
Looks good to be merged.

2023-12-19 14:12 UTC, merged