add D3 Scaling.scaleLinear()
Codecademy/docs pull request #4090
Opened 2023-12-13 22:29 UTC by aciffone23

### Description
Closes #3884 
* Added `Scaling.scaleLinear() term entry`, `docs/content/d3/concepts/scaling/terms/scaleLinear/scaleLinear.md`. 
* Was motivated to make a contribution from the Learn Git & GitHub coursework. 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-13 22:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4090) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4090) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4090) it.</sub>

2023-12-14 09:19 UTC, dakshdeepHERE requested changes
Few changes from my side for you @aciffone23

2023-12-14 09:19 UTC, dakshdeepHERE commented on content/d3/concepts/scaling/terms/scaleLinear/scaleLinear.md
> +  - 'paths/computer-science'
```suggestion
  - 'paths/data-science'
```

2023-12-14 09:19 UTC, dakshdeepHERE commented on content/d3/concepts/scaling/terms/scaleLinear/scaleLinear.md
> +In the example given below the `scale` will map values within the specified domain to the corresponding range given. The `scale` is set to have a domain from `0` to `100` and range from `0` to `500`.
```suggestion
In the example given below the `scale` will map values within the specified domain to the corresponding range given. The `scale` is set to have a domain from `0` to `100` and range from `0` to `500`. When the values are mapped from the domain passed to the scale, the range produces the output accordingly:
```

2023-12-14 15:39 UTC, aciffone23 commented
> Few changes from my side for you @aciffone23

Thank you, committed the changes.

2023-12-15 17:53 UTC, dakshdeepHERE approved these changes
Looks good for second review 🚀

2023-12-16 14:01 UTC, avdhoottt requested changes
@aciffone23 Just a minor change from my side.

2023-12-18 11:42 UTC, avdhoottt approved these changes
Ready to merge.

2023-12-18 12:15 UTC, merged