add getOwnPropertyDescription file
Codecademy/docs pull request #4092
Opened 2023-12-14 15:34 UTC by Brag2gr8

### Description

Added getOwnPropertyDescription for Javascript Object terms. closes #4060 

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-14 17:55 UTC, avdhoottt requested changes
@Brag2gr8 Nice Work! Here are some changes from my side, please make them. I might have some more changes in the future.

2023-12-14 17:55 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/getOwnPropertyDescriptors/getOwnPropertyDescriptors.md
> +Title: '.getOwnPropertyDescriptors'
```suggestion
Title: 'Object.getOwnPropertyDescriptors()'
```
Use this format whenever you write the name of the method.

2023-12-14 17:55 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/getOwnPropertyDescriptors/getOwnPropertyDescriptors.md
> +Description: 'returns all own property descriptors of a given object'
```suggestion
Description: 'Returns all own property descriptors of a given object.'
```

2023-12-14 17:55 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/getOwnPropertyDescriptors/getOwnPropertyDescriptors.md
> +The **`Object.getOwnPropertyDescriptors()`** method returns all own property descriptors of a given object. It is useful for extracting property descriptors, including configurable, enumerable, value
```suggestion
The **`Object.getOwnPropertyDescriptors()`** method returns all own property descriptors of a given object. It is useful for extracting property descriptors, including configurable, enumerable, value, and writable properties, allowing manipulation of these property attributes from an object.
```

2023-12-14 17:55 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/getOwnPropertyDescriptors/getOwnPropertyDescriptors.md
> +`obj` is the given obeject.
```suggestion
- `obj`: It is the given object.
```

2023-12-14 17:55 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/getOwnPropertyDescriptors/getOwnPropertyDescriptors.md
> +## Examples
Remove this heading and add the rest of the two (`Example 1` & `Example 2`) headings as h2.

2023-12-14 17:55 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/getOwnPropertyDescriptors/getOwnPropertyDescriptors.md
> +In this example, Object.getOwnPropertyDescriptors() returns an object where each key is a property name, and the corresponding value is the property descriptor for that property.
```suggestion
In this example, `Object.getOwnPropertyDescriptors()` returns an object where each key is a property name, and the corresponding value is the property descriptor for that property.
```

2023-12-14 17:55 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/getOwnPropertyDescriptors/getOwnPropertyDescriptors.md
> +
```suggestion
```

2023-12-15 10:22 UTC, Brag2gr8 commented
@avdhoottt I'm done implementing the proposed changes

2023-12-15 17:47 UTC, avdhoottt approved these changes
Good to go for the second review.

2023-12-15 18:17 UTC, dakshdeepHERE approved these changes
This looks good to merge 🚀

2023-12-15 18:20 UTC, merged