[Concept Entry] Rust Threads
Codecademy/docs pull request #4093
Opened 2023-12-15 09:45 UTC by andersooi

### Description

- Added new concept entry for Rust Threads
- Added new tag: Threads
- Closes #3879 

### Type of Change

- Adding a new entry
- Updating the documentation (Tags)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-15 17:32 UTC, dakshdeepHERE requested changes
I have few comments otherwise this looks good 👍🏻

2023-12-15 17:32 UTC, dakshdeepHERE commented on content/rust/concepts/threads/threads.md
> +Description: ‘Threads allow parts of a program to run concurrently.’
```suggestion
Description: ‘Threads allow parts of a program to run concurrently’
```

2023-12-15 17:32 UTC, dakshdeepHERE commented on content/rust/concepts/threads/threads.md
> +}
```suggestion
fn main() {
  thread::spawn(|| {
    for i in 1..10 {
        println!("Spawned thread {}", i);
        thread::sleep(Duration::from_millis(3));
      }
  });

  for i in 1..4 {
    println!("Main thread {}", i);
    thread::sleep(Duration::from_millis(1));
  }
}
```

2023-12-15 17:32 UTC, dakshdeepHERE commented on content/rust/concepts/threads/threads.md
> +The output is as follows:
```suggestion
The above example will give the following output:
```

2023-12-15 17:32 UTC, dakshdeepHERE commented on content/rust/concepts/threads/threads.md
> +Consider the following example without using the `move` keyword:
```suggestion
Passing in the `move` keyword into the `thread::spawn()` function enables the safe transfer of ownership of a variable from one thread to another. Consider the following example without using the `move` keyword:
```

2023-12-15 17:32 UTC, dakshdeepHERE commented on content/rust/concepts/threads/threads.md
> +}
```suggestion
use std::thread;

fn main() {
  let greeting = String::from("hello");
  let handle = thread::spawn(|| {
    println!("{}", greeting);
  });

  handle.join().unwrap();
}
```

2023-12-15 17:32 UTC, dakshdeepHERE commented on content/rust/concepts/threads/threads.md
> +To solve this issue, pass in the `move` keyword as shown in the example below:
```suggestion
Rust will attempt to borrow `greeting` into the spawned thread, but it cannot guarantee how long the spawned thread will run for. Rust’s borrowing rules do not allow a thread to outlive the data it is borrowing potentially. To solve this issue, pass in the `move` keyword as shown in the example below:
```

2023-12-15 17:32 UTC, dakshdeepHERE commented on content/rust/concepts/threads/threads.md
> +}
```suggestion
use std::thread;

fn main() {
  let greeting = String::from("hello");
  let handle = thread::spawn(move || {
    println!("{}", greeting);
  });

  handle.join().unwrap();
}
```

2023-12-15 17:32 UTC, dakshdeepHERE commented on content/rust/concepts/threads/threads.md
> +The output is as follows:
```suggestion
The above example will give the following output:
```

2023-12-16 05:40 UTC, dakshdeepHERE approved these changes
Looks good for second review 🚀

2023-12-19 13:01 UTC, avdhoottt requested changes
@andersooi I left one change, please check them out.

2023-12-19 13:01 UTC, avdhoottt commented on content/rust/concepts/threads/threads.md
> +  - 'paths/computer-science'
Add these slugs instead of this - 
```
- 'rust-for-programmers'
- 'paths/computer-science'
```

2023-12-20 15:57 UTC, merged