4070 object keys
Codecademy/docs pull request #4094
Opened 2023-12-15 16:41 UTC by droffilc1

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-15 17:37 UTC, dakshdeepHERE requested changes
I have requested few changes from you side.

2023-12-15 17:37 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/keys/keys.md
> +Title: 'Object.keys()'
```suggestion
Title: '.keys()'
```

2023-12-15 17:37 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/keys/keys.md
> +and only for enumerable properties.
```suggestion
The `.keys()` static method extracts keys from an object and returns them as an array. `.keys()` only returns the keys for the object's property and only for enumerable properties.
```

2023-12-15 17:37 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/keys/keys.md
> +- `obj` - An object.
```suggestion
```

2023-12-15 17:37 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/keys/keys.md
> +Here's a simple example:
Instead of this give a basic desc of what the reader can expect from the coming code snippet

2023-12-15 17:37 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/keys/keys.md
> +### Output:
```suggestion

The above example will give the following output:
```

2023-12-15 17:37 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/keys/keys.md
> +```pseudo
instead of pseudo use the shell tag for output blocks

2023-12-16 08:19 UTC, dakshdeepHERE commented
Looks good for second review @droffilc1 🚀

2023-12-16 08:19 UTC, dakshdeepHERE approved these changes

2023-12-22 16:29 UTC, avdhoottt requested changes
@droffilc1 I have mentioned some minor changes, please make them.

2023-12-22 16:29 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/keys/keys.md
> +The `.keys()` static method extracts keys from an object and returns them as an array. `.keys()` only returns the keys for the object's property and only for enumerable properties.
```suggestion
The `.keys()` static method extracts keys from an object and returns them as an array. It only returns the keys for the object's property and only for enumerable properties.
```

2023-12-22 16:29 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/keys/keys.md
> +>**Note:** The order of the keys in the resulting array is not guaranteed to be the same as the order in which they were defined in the object.
```suggestion
> **Note:** The order of the keys in the resulting array is not guaranteed to be the same as the order in which they were defined in the object.
```

2023-12-22 16:29 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/keys/keys.md
> +
Write a description for the `obj` parameter below the syntax block.

2023-12-22 16:29 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/keys/keys.md
> +Here's a simple example that extracts keys from an object and returns them as an array:
```suggestion
Here's a simple example that extracts keys from an object and returns them as an array:

```
Remember to give a line space before and after a code block.

2023-12-27 14:26 UTC, avdhoottt commented on content/javascript/concepts/objects/terms/keys/keys.md
> +`obj`: An object
```suggestion
- `obj`: An object from which the keys are extracted.
```

2023-12-27 14:27 UTC, avdhoottt approved these changes
Looks good to get merged.

2023-12-27 14:33 UTC, merged