[ Term Entry ] .defineProperty() for Javascript
Codecademy/docs pull request #4100
Opened 2023-12-18 17:13 UTC by alimalim77

### Description

Added the definition, syntax and example for .defineProperty().

### Type of Change

- Closes Issue: https://github.com/Codecademy/docs/issues/4026
- Adding a new entry
-  Created an example and added the same

### Checklist

- [✓ ] All writings are my own.
- [ ✓] My entry follows the Codecademy Docs style guide.
- [ ✓] My changes generate no new warnings.
- [ ✓] I have performed a self-review of my own writing and code.
- [ ✓] I have checked my entry and corrected any misspellings.
- [ ✓] I have made corresponding changes to the documentation if needed.
- [ ✓] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ✓] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ✓] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-19 09:02 UTC, dakshdeepHERE requested changes
I have some comments for you to work on @alimalim77

2023-12-19 09:02 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/definedProperty/defineProperty.md
> +Description: 'defines a property of an object either by creating or modifying.'
```suggestion
Description: 'Defines a property of an object either by creating or modifying.'
```

2023-12-19 09:02 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/definedProperty/defineProperty.md
> +The `.defineProperty()` method defines a property on an object, either creating a new property or modifying an existing one. The method returns the modified object with the specified property.
```suggestion
The **`.defineProperty()`** method defines a property on an object, either creating a new property or modifying an existing one. The method returns the modified object with the specified property.
```

2023-12-19 09:02 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/definedProperty/defineProperty.md
> +Object.defineProperty(obj, prop, descriptor)
give bullet points below this explaining what are prop, obj and descriptor

2023-12-19 09:02 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/definedProperty/defineProperty.md
> +In the example below, a `name` property is defined using the .defineProperty() method. Then, to check the value of property, by printing it to the console:
```suggestion
In the example below, a `name` property is defined using the `.defineProperty()` method. Then, to check the value of the property, by printing it to the console:
```

2023-12-19 09:02 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/definedProperty/defineProperty.md
> +console.log("Name:", person.name); // Output: John
```suggestion
console.log("Name:", person.name);
```

2023-12-19 09:02 UTC, dakshdeepHERE commented on content/javascript/concepts/objects/terms/definedProperty/defineProperty.md
> +// Define a property 'name' on the 'person' object with a descriptor
```suggestion
```

2023-12-20 18:23 UTC, alimalim77 commented on content/javascript/concepts/objects/terms/definedProperty/defineProperty.md
> +Description: 'defines a property of an object either by creating or modifying.'
Resolved.

2023-12-20 18:28 UTC, alimalim77 commented
I have made the suggested changes @dakshdeepHERE . Please let me know if there is room for any more changes. Thanks!

2023-12-21 15:00 UTC, dakshdeepHERE approved these changes
Thank you for the commits @alimalim77. This looks good for second review.

2023-12-28 13:34 UTC, avdhoottt approved these changes
Looks good to get merged.

2023-12-28 13:58 UTC, merged