Add sort() entry to Java ArrayList
Codecademy/docs pull request #4108
Opened 2023-12-21 12:10 UTC by Brag2gr8

### Description

- Added the Calendar .isSet() term for Java
- Closing issue #4102 

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-21 17:50 UTC, dakshdeepHERE requested changes
I have some comments for you.

2023-12-21 17:50 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/sort/sort.md
> +Description: 'Used to sort arrays of primitive types and objects'
```suggestion
Description: 'Used to sort arrays of primitive types and objects.'
```

2023-12-21 17:50 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/sort/sort.md
> +## Example 1
```suggestion
## Examples

### Example 1
```

2023-12-21 17:50 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/sort/sort.md
> +
```suggestion

Here's a basic syntax of how to use the `.sort()` method:

```

2023-12-21 17:50 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/sort/sort.md
> +In this case, strings implement the `Comparable` interface, so they can be sorted directly using `Arrays.sort()`.
```suggestion
In this case, strings implement the `Comparable` interface, so they can be sorted directly using `Arrays.sort()`:
```

2023-12-21 17:50 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/sort/sort.md
> +}
```suggestion
import java.util.Arrays;

public class Main {
  public static void main(String[] args) {
    int[] numbers = {5, 2, 8, 1, 3};

    // Sorting the array in ascending order
    Arrays.sort(numbers);
    
    System.out.println("Sorted Array: " + Arrays.toString(numbers));
  }
}
```

2023-12-21 17:50 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/sort/sort.md
> +The output should look like this:
```suggestion
The above example will give the following output:
```

2023-12-21 17:50 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/sort/sort.md
> +
have a small introductory sentence here too like you did above

2023-12-21 17:50 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/sort/sort.md
> +}
```suggestion
import java.util.Arrays;

public class Main {
  public static void main(String[] args) {
    String[] names = {"Alice", "Bob", "Charlie", "David"};

    // Sorting the array of strings in ascending order
    Arrays.sort(names);
    
    System.out.println("Sorted Array by Length: " + Arrays.toString(names));
  }
}
```

2023-12-21 17:50 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/sort/sort.md
> +The output should look like this:
```suggestion
The above example will give the following output:
```

2023-12-21 17:50 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/sort/sort.md
> +> **Note:** If you need a custom sorting order, you can use the Comparator interface. Here's an example sorting strings by their length:
We dont allow the use third person and pronouns in our docs contributions. Please refactor this sentence. Dont use words like He she you us ours etc in entries please.

2023-12-22 13:52 UTC, Brag2gr8 commented
@dakshdeepHERE I've added the changes. please check it out

2023-12-23 16:08 UTC, dakshdeepHERE approved these changes
@Brag2gr8 I did some minor changes from my side. This looks good for second review. 🚀

2023-12-27 17:55 UTC, closed without merging