[]: added Java ArrayList: .trimToSize()
Codecademy/docs pull request #4111
Opened 2023-12-22 07:32 UTC by ATREAY

### Description

This pull request introduces a new term, `trimToSize()`, within the Java ArrayList section.
fixes: #4106

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-23 16:05 UTC, dakshdeepHERE requested changes
Few changes from my side for you @ATREAY 🚀

2023-12-23 16:05 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/trimToSize/trimToSize.md
> +  - 'Data Types'
```suggestion
  - 'Data Types'
  - 'Methods'
```

2023-12-23 16:05 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/trimToSize/trimToSize.md
> +The following example creates an `ArrayList`, uses [`.add()`](https://www.codecademy.com/resources/docs/java/array-list/add) to append elements to it, and then trims its capacity to match its size us
```suggestion
The following example creates an `ArrayList`, uses [`.add()`](https://www.codecademy.com/resources/docs/java/array-list/add) method to append elements to it, and then trims its capacity to match its size using `.trimToSize()`:
```

2023-12-23 16:05 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/trimToSize/trimToSize.md
> +}
```suggestion
import java.util.ArrayList;

public class Main {
  public static void main(String[] args) {
    // Create an ArrayList of Strings with an initial capacity
    ArrayList<String> list = new ArrayList<>(10);

    // Add some elements to the list
    list.add("Apple");
    list.add("Banana");
    list.add("Orange");

    // Trim the capacity to match the size
    list.trimToSize();
    
    System.out.println("Trimmed Capacity: " + list.size());
  }
}
```

2023-12-24 08:33 UTC, ATREAY commented
Hey @dakshdeepHERE, I have made the required changes, please go through it when you have a moment.

2023-12-24 09:06 UTC, dakshdeepHERE approved these changes
Looks good for second review 🚀

2023-12-27 14:07 UTC, avdhoottt requested changes
@ATREAY I have suggested a small change, please make it.

2023-12-27 14:07 UTC, avdhoottt commented on content/java/concepts/array-list/terms/trimToSize/trimToSize.md
> +The **`.trimToSize()`** method of the `ArrayList` class adjusts the capacity of the list to be the same as its size.
Hyperlink the `ArrayList` with [this](https://www.codecademy.com/resources/docs/java/array-list) docs url.

2023-12-27 14:19 UTC, ATREAY commented
Hey @avdhoottt, I have made the suggested changes, please go through it when you have a moment.

2023-12-30 14:10 UTC, avdhoottt approved these changes
Looks good to get merged.

2023-12-30 14:11 UTC, merged