feat: add entry for mergetool
Codecademy/docs pull request #4112
Opened 2023-12-23 04:25 UTC by CBID2

### Description
This PR adds an entry about the `mergetool` command in the Git section. I decided to create it because it would help developers and other tech professionals solve merge conflicts, a common encounter when working with code. 

### Type of Change

- Adding a new entry

### Issues
Closes #4096 

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-25 07:19 UTC, dakshdeepHERE requested changes
I am suggesting a few changes for you to work on @CBID2.

2023-12-25 07:19 UTC, dakshdeepHERE commented on content/git/concepts/mergetool/mergetool.md
> +Description: 'The mergetool command is used to activate a tool used to solve merge conflicts that occur in a branch'
```suggestion
Description: 'The mergetool command is used to activate a tool used to solve merge conflicts that occur in a branch.' 
```

2023-12-25 07:19 UTC, dakshdeepHERE commented on content/git/concepts/mergetool/mergetool.md
> +Below is an example on how to use `git mergetool`. The developer runs the command and the merge conflict appears.
```suggestion
Below is an example on how to use `git mergetool`. The developer runs the command and the merge conflict appears:
```

2023-12-25 07:19 UTC, dakshdeepHERE commented on content/git/concepts/mergetool/mergetool.md
> +-`====`: Divides the developer's changes from the changes in the other branch, followed by `>>>>>>> UPDATING-THE-STYLE-GUIDE`
```suggestion
- `<<<<<<< HEAD`: where the developer's changes appear.  
- `====`: Divides the developer's changes from the changes in the other branch, followed by `>>>>>>> UPDATING-THE-STYLE-GUIDE`
```

2023-12-25 07:19 UTC, dakshdeepHERE commented on content/git/concepts/mergetool/mergetool.md
> +- [Sublime Merge](https://www.sublimemerge.com/): Tool comes in a paid and free version. It is deemed to have a great user interface and intuitively easy to use.
```suggestion
- [**Kaleidoscope**](https://kaleidoscope.app/): Developers often use this to resolve merge conflicts due to its use of different highlighted colors and powerful features ranging from a Convert to Merge command, text filters that remove unimportant data, and a debugger.
- [**Visual Studio Code**](https://code.visualstudio.com/docs/sourcecontrol/overview#_3way-merge-editor): This Integrated Development Environment (IDE) has a built-in 3-way merge editor, which displays the incoming changes to the file and provides a button that enables the changes to be accepted into the file. This allows developers to edit files and resolve conflicts easily.
- [**Sublime Merge**](https://www.sublimemerge.com/): Tool comes in a paid and free version. It is deemed to have a great user interface and is intuitively easy to use.
```

2023-12-25 07:22 UTC, CBID2 commented
Made the changes @dakshdeepHERE! :)

2023-12-25 08:03 UTC, dakshdeepHERE approved these changes
LGTM 🚀

2023-12-27 17:34 UTC, SSwiniarski approved these changes
@CBID2 Looks good to me.

2023-12-27 17:44 UTC, merged