[Term Entry] Kotlin Datetime .asTimeZone()
Codecademy/docs pull request #4118
Opened 2023-12-27 06:01 UTC by Kadif-Ravik

### Description

Term entry for Kotlin datetime, .asTimeZone()

Closes #3805

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-27 14:02 UTC, avdhoottt requested changes
@Kadif-Ravik Here are a few changes from my side, I might suggest some more changes in the future.

2023-12-27 14:02 UTC, avdhoottt commented on content/kotlin/concepts/datetime/terms/asTimeZone/asTimeZone.md
> +In the following example a`TimeZone` object, `timeZone` with the ID `America/ Los_Angeles` is created. The `.asTimeZone()` function converts the `TimeZone` object to a string  representation of the t
```suggestion
In the following example a `TimeZone` object, `timeZone` with the ID `America/ Los_Angeles` is created. The `.asTimeZone()` function converts the `TimeZone` object to a string representation of the time zone.
```

2023-12-27 14:02 UTC, avdhoottt commented on content/kotlin/concepts/datetime/terms/asTimeZone/asTimeZone.md
> +
```suggestion
-08:00
```
Add the proper and accurate output.

2023-12-27 15:44 UTC, Kadif-Ravik commented
@avdhoottt I'm having trouble with the main function.

2023-12-29 17:32 UTC, avdhoottt requested changes
@Kadif-Ravik I have looked into the code and have updated the code as per my knowledge. Please have a look at it and make the suggested changes.

2023-12-29 17:32 UTC, avdhoottt commented on content/kotlin/concepts/datetime/terms/asTimeZone/asTimeZone.md
> +Title: '.asTimeZone'
```suggestion
Title: '.asTimeZone()'
```

2023-12-29 17:32 UTC, avdhoottt commented on content/kotlin/concepts/datetime/terms/asTimeZone/asTimeZone.md
> +}
```suggestion
import kotlinx.datetime.*

fun main() {
  // Create a UTCOffset object with an offset of +5 hours, 30 minutes
  val utcOffset = UtcOffset(5, 30)
  val fixedOffsetTimeZone: FixedOffsetTimeZone = utcOffset.asTimeZone()
  println("$fixedOffsetTimeZone") 
}
```
I've provided a code in Kotlin, please have a look at it. I think the `.asTimeZone()` method only works on UTC offset, so I've created one and called the method on it.

2023-12-29 17:32 UTC, avdhoottt commented on content/kotlin/concepts/datetime/terms/asTimeZone/asTimeZone.md
> +-08:00
```suggestion
+05:30
```
Updated the output as per the code.

2023-12-29 17:32 UTC, avdhoottt commented on content/kotlin/concepts/datetime/terms/asTimeZone/asTimeZone.md
> +In the following example a `TimeZone` object, `timeZone` with the ID `America/ Los_Angeles` is created. The `.asTimeZone()` function converts the `TimeZone` object to a string representation of the t
Please review the code and change the description accordingly.

2024-01-07 17:17 UTC, avdhoottt commented
@Kadif-Ravik Are you still working on this PR? Please make the suggested changes.

2024-01-20 06:18 UTC, ishg-153 commented
@avdhoottt You should consider closing this PR and opening up the corresponding issue so that someone else can work on it.

2024-05-15 07:24 UTC, ishg-153 commented
Closing this PR and opening up its corresponding issue.

@Kadif-Ravik @avdhoottt

2024-05-15 07:25 UTC, closed without merging