Term entry] java array list .sort
Codecademy/docs pull request #4121
Opened 2023-12-27 18:05 UTC by Brag2gr8

### Description

- Added the Calendar .sort() term for Java
- Closing issue #4102 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-29 14:40 UTC, dakshdeepHERE requested changes
I have requested few changes from my side.

2023-12-29 14:40 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/sort/sort.md
> +In this example, the `Arrays.sort(numbers)` method is used to sort the array of integers in ascending order. The result is then printed using `Arrays.toString()`.
```suggestion
In this example, the `Arrays.sort(numbers)` method is used to sort the array of integers in ascending order. The result is then printed using `Arrays.toString()`:
```

2023-12-29 14:40 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/sort/sort.md
> +> **Note:** For an array of objects, you can use a custom comparator or ensure that the objects in the array implement the `Comparable` interface. Here's an example with strings.
Avoid using first- and second-person pronouns (e.g. "I", "we", "you") if possible.

2023-12-29 14:40 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/sort/sort.md
> +In this Example, strings implement the `Comparable` interface, so they can be sorted directly using Arrays.sort().
```suggestion
In this example, strings implement the `Comparable` interface, so they can be sorted directly using `Arrays.sort()`:
```

2023-12-29 14:40 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/sort/sort.md
> +In this example, `Comparator.comparing(String::length)` is used to sort the array of strings based on their length.
```suggestion
In this example, `Comparator.comparing(String::length)` is used to sort the array of strings based on their length:
```

2023-12-29 14:40 UTC, dakshdeepHERE commented on content/java/concepts/array-list/terms/sort/sort.md
> +
```suggestion

The above example will give the following output:

```

2023-12-30 00:35 UTC, Brag2gr8 commented
@dakshdeepHERE done commiting the changes

2023-12-31 09:19 UTC, dakshdeepHERE approved these changes
LGTM 🚀

2023-12-31 13:57 UTC, avdhoottt requested changes
@Brag2gr8 Few changes from my side.

2023-12-31 13:57 UTC, avdhoottt commented on content/java/concepts/array-list/terms/sort/sort.md
> +Arrays.sort(array);
As you've added in the introduction of the method, there can be an optional parameter `Comparator`. Please add it to the syntax and write a one-line description below the syntax block.

2023-12-31 13:57 UTC, avdhoottt commented on content/java/concepts/array-list/terms/sort/sort.md
> +
```suggestion
```

2023-12-31 13:57 UTC, avdhoottt commented on content/java/concepts/array-list/terms/sort/sort.md
> +
```suggestion
```

2023-12-31 13:57 UTC, avdhoottt commented on content/java/concepts/array-list/terms/sort/sort.md
> +> **Note:** For a custom sorting order, the `Comparator` interface can be used. Here's an example sorting strings by their length.
```suggestion
> **Note:** For a custom sorting order, the `Comparator` interface can be used. Here's an example of sorting strings by their length.
```

2024-01-04 08:40 UTC, Brag2gr8 commented
@avdhoottt done with the changes

2024-01-05 14:23 UTC, avdhoottt commented on content/java/concepts/array-list/terms/sort/sort.md
> +> **Note:** For an array of objects, a custom comparator can be used or the objects in the array should implement the `Comparable` interface. Here's an example with strings.
```suggestion
> **Note:** For an array of objects, a custom comparator can be used or the objects in the array should implement the `Comparable` interface.
```

2024-01-05 14:24 UTC, avdhoottt approved these changes
Let's get this merged.

2024-01-05 14:37 UTC, merged