Create toArray.md
Codecademy/docs pull request #4122
Opened 2023-12-27 18:28 UTC by Brag2gr8

### Description

Added new entry for Javascript Object Methods defineProperties()
Entry Location: content/javascript/concepts/objects/terms/toArray/toArray.md. closes #4105

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-30 15:48 UTC, Sriparno08 reviewed
Hey @Brag2gr8, thanks for contributing to Codecademy!

I have listed all the modifications that you need to make in your article below:

2023-12-30 15:48 UTC, Sriparno08 commented on content/java/concepts/array-list/terms/toArray/toArray.md
> +  - 'Data Types'
Add `'Elements'` inside the `Tags` section:

```suggestion
Tags:
  - 'Arrays'
  - 'Data Types'
  - 'Elements'
```

2023-12-30 22:27 UTC, Brag2gr8 commented
@Sriparno08 I just finished comiting the changes

2023-12-31 04:45 UTC, Sriparno08 commented
Good job, @Brag2gr8 👍

This looks good for a second review.

2023-12-31 14:08 UTC, avdhoottt requested changes
@Brag2gr8 Suggested some minor changes, please make them.

2023-12-31 14:08 UTC, avdhoottt commented on content/java/concepts/array-list/terms/toArray/toArray.md
> +
```suggestion
```

2023-12-31 14:08 UTC, avdhoottt commented on content/java/concepts/array-list/terms/toArray/toArray.md
> +
```suggestion
```

2023-12-31 14:08 UTC, avdhoottt commented on content/java/concepts/array-list/terms/toArray/toArray.md
> +The output should look like this:
```suggestion
The output should result in the following output:
```

2023-12-31 14:08 UTC, avdhoottt commented on content/java/concepts/array-list/terms/toArray/toArray.md
> +The output should look like this:
```suggestion
The output should result in the following output:
```

2024-01-04 08:27 UTC, Brag2gr8 commented
@avdhoottt I'm done making the suggested changes

2024-01-05 14:19 UTC, merged