[Term Entry] D3 Selection .append() added
Codecademy/docs pull request #4124
Opened 2023-12-28 18:43 UTC by antriksh-9

### Description

I was assigned this [issue](https://github.com/Codecademy/docs/issues/3958).
Created Codecademy Docs term entry on the .append() method for D3 Selection.
Closes #3958.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-29 07:27 UTC, avdhoottt requested changes
@antriksh-9 I might have some more changes in the future. For now, make the mentioned changes.

2023-12-29 07:27 UTC, avdhoottt commented on content/d3/concepts/selection/terms/append/append.md
> +selection.append(name);
```suggestion
selection.append(type);

```
The `type` word would describe the parameter correctly.

2023-12-29 07:27 UTC, avdhoottt commented on content/d3/concepts/selection/terms/append/append.md
> +- `name`: This parameter takes a string that defines the type of the element.
```suggestion
- `type`: This parameter takes a string that defines the type of the element.

```

2023-12-29 07:27 UTC, avdhoottt commented on content/d3/concepts/selection/terms/append/append.md
> +The **`selection.append()`** function is used to append a new element to the `HTML` tag name as given in the parameters to the end of the element. If the type that is given is a function then it must
```suggestion
The **`.append()`** function is used to append a new element to the `HTML` tag name as given in the parameters to the end of the element. If the type that is given is a function then it must be evaluated for each element that is in the selection.

```
This line contains some plagiarism, please change it.

2023-12-29 17:33 UTC, avdhoottt commented on content/d3/concepts/selection/terms/append/append.md
> +of the newly appended paragraph.
```suggestion
In this example, D3.js selects the `<body>` element and appends a new `<p>` (paragraph) element to it. The `.text()` method is then used to set the text content of the newly appended paragraph.

```

2023-12-29 17:34 UTC, avdhoottt approved these changes
Looks good for the second review.

2024-01-03 06:56 UTC, dakshdeepHERE approved these changes
Did some minor changes and this LGTM 🚀

2024-01-03 07:00 UTC, merged