[Term Entry] D3 Interactivity .transition() added
Codecademy/docs pull request #4129
Opened 2023-12-30 10:45 UTC by antriksh-9

### Description

I was assigned this [issue](https://github.com/Codecademy/docs/issues/4032).
Created Codecademy Docs term entry on the .transition() method for D3.
Closes #4032.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2023-12-30 10:53 UTC, dakshdeepHERE requested changes
Only one change from my side

2023-12-30 10:53 UTC, dakshdeepHERE commented on content/d3/concepts/interactivity/terms/transition/transition.md
> +It allows to smoothly update the appearance of elements making visualizations more interactive and engaging.
```suggestion
In D3.js, the **`.transition()`** method is used to create a smooth transition between different states of a selection. Transitions provide a way to animate changes in the DOM elements over time. It allows to smoothly update the appearance of elements making visualizations more interactive and engaging.
```

2023-12-30 10:56 UTC, antriksh-9 commented
Hey @dakshdeepHERE I have made the changes.

2023-12-31 09:16 UTC, dakshdeepHERE approved these changes
Looks good for second review.

2024-01-02 13:36 UTC, avdhoottt approved these changes
Looks good to get merged.

2024-01-02 13:44 UTC, merged