[Term Entry] D3 Styling .html()
Codecademy/docs pull request #4133
Opened 2023-12-31 15:41 UTC by andersooi

### Description

- created new term entry for D3 styling html function
- closes #3964 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-01-01 09:11 UTC, dakshdeepHERE approved these changes
Did some minor changes and this looks good for second review.

2024-01-03 17:45 UTC, avdhoottt requested changes
@andersooi Mentioned a few minor changes, please make them.

2024-01-03 17:45 UTC, avdhoottt commented on content/d3/concepts/styling/terms/html/html.md
> +In the example given below, `.select(".test)` method will select the HTML element with classname `test` and the `html.(<b>Updated test line</b>)` will change the element's inner HTML from `Test line`
```suggestion
In the example given below, `.select('.test')` method will select the HTML element with classname `test` and the `html.(<b>Updated test line</b>)` will change the element's inner HTML from `Test line` to `<b>Updated test line</b>`. Calling the `.html()` function again without any arguments will return the inner HTML of the first (non-null) element in the selection:
```

2024-01-03 17:45 UTC, avdhoottt commented on content/d3/concepts/styling/terms/html/html.md
> +```HTML
```suggestion
```html
```

2024-01-05 14:20 UTC, avdhoottt commented on content/d3/concepts/styling/terms/html/html.md
> +Description: 'This method is used to set or get the inner HTML of the selected elements.'
```suggestion
Description: 'Used to set or get the inner HTML of the selected elements.'
```

2024-01-05 14:20 UTC, avdhoottt approved these changes
@andersooi Looks good to get merged.

2024-01-05 14:22 UTC, merged