Adding Example 3, in case of complex string including other characters
Codecademy/docs pull request #4159
Opened 2024-01-02 15:36 UTC by dcldavid

…haracters.

### Description

Added Example 3 to the `toLowerCase()` method featuring how the method can be used in more complex string use cases.
Closes #4153 

### Type of Change

- Updating the documentation

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR

2024-01-02 15:37 UTC, dcldavid commented
First ever pull request! Apologies in advance for errors!

2024-01-02 15:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4159) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4159) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4159) it.</sub>

2024-01-03 06:42 UTC, dakshdeepHERE requested changes
I have requested few changes from my side for you @dcldavid 🚀

2024-01-03 06:42 UTC, dakshdeepHERE commented on content/javascript/concepts/strings/terms/toLowerCase/toLowerCase.md
> +## Example 3
```suggestion
## Codebyte Example
```

2024-01-03 06:42 UTC, dakshdeepHERE commented on content/javascript/concepts/strings/terms/toLowerCase/toLowerCase.md
> +// Output: what a complex string !1@2#3
```suggestion
```
No need to show the output here as a comment the readers can compile the code and get the output as usual.

2024-01-03 06:42 UTC, dakshdeepHERE commented on content/javascript/concepts/strings/terms/toLowerCase/toLowerCase.md
> +The `.toLowerCase()` method will convert upper case alphabet characters to lower case in a string with other character types such as digits and special characters.
```suggestion
Here `.toLowerCase()` method will convert upper-case alphabet characters to lower-case in a string with other character types such as digits and special characters:
```

2024-01-03 14:25 UTC, dcldavid commented
Thanks @dakshdeepHERE I have committed all of the changes.

2024-01-03 14:55 UTC, dakshdeepHERE approved these changes
LGTM 🚀

2024-01-09 18:59 UTC, ishg-153 approved these changes
@dcldavid I made a small change but everything else looks good. Ready to merge!

2024-01-09 19:15 UTC, merged