Adding Codebyte for getUTCHours
Codecademy/docs pull request #4161
Opened 2024-01-02 22:19 UTC by bpicoCode

### Description
- Adding Codebyte for .getUTCHours() entry
- Closes issue #4150  

### Type of Change
- Editing an existing entry (fixing a typo, bug, issues, etc)
- 
### Checklist

- [ x] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-01-02 22:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4161) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4161) before we can accept your contribution.<br/><hr/>**Benjamin Picone** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4161) it.</sub>

2024-01-03 14:41 UTC, avdhoottt requested changes
@bpicoCode Please make the mentioned changes.

2024-01-03 14:41 UTC, avdhoottt commented on content/javascript/concepts/dates/terms/getUTCHours/getUTCHours.md
> +In the following example, variables `estDate` and `pstDate` are defined to store a new `Date` object in Eastern Time and Pacific Time respectively. The method `.getUTCHours()` is then used to print t
Give space before and after the code byte.

2024-01-03 14:41 UTC, avdhoottt commented on content/javascript/concepts/dates/terms/getUTCHours/getUTCHours.md
> +### Codebyte Example
```suggestion
## Codebyte Example
```
It should be a H2 subheading.

2024-01-03 14:41 UTC, avdhoottt commented on content/javascript/concepts/dates/terms/getUTCHours/getUTCHours.md
> +In the following example, variables `estDate` and `pstDate` are defined to store a new `Date` object in Eastern Time and Pacific Time respectively. The method `.getUTCHours()` is then used to print t
```suggestion
In the following example, variables `estDate` and `pstDate` are defined to store a new `Date` object in Eastern Time and Pacific Time respectively. The method `.getUTCHours()` is then used to print the hours of the dates according to universal time. You can just run this example in the Codebyte to test the results. 
```

2024-01-04 04:46 UTC, bpicoCode commented
I made the changes as requested. Let me know if there is anything else I need to do. Thank you!

2024-01-04 14:29 UTC, avdhoottt commented on content/javascript/concepts/dates/terms/getUTCHours/getUTCHours.md
> +In the following example, variables `estDate` and `pstDate` are defined to store a new `Date` object in Eastern Time and Pacific Time respectively. The method `.getUTCHours()` is then used to print t
```suggestion
In the following example, variables `estDate` and `pstDate` are defined to store a new `Date` object in Eastern Time and Pacific Time respectively. The method `.getUTCHours()` is then used to print the hours of the dates according to universal time. You can just run this example in the Codebyte to test the results. 

```

2024-01-04 14:30 UTC, avdhoottt approved these changes
It's ready for the second review. @bpicoCode Please sign our CLA as it is mandatory for authors.

2024-01-04 18:17 UTC, dakshdeepHERE approved these changes
LGTM for merge 🚀

2024-01-04 18:20 UTC, dakshdeepHERE commented
@bpicoCode can you please sign the CLA assistant so we can merge this PR?

2024-01-04 18:55 UTC, bpicoCode commented
> @bpicoCode can you please sign the CLA assistant so we can merge this PR?
I signed the CLA but my initial commit came from my local repo which wasn't linked to a Github user. See that 'Benjamin Picone' hasn't signed yet but bpicoCode (also me) has signed. I can't change that initial commit. Maybe we should delete that commit so that 'Benjamin Picone' no longer shows up?

2024-01-04 20:27 UTC, bpicoCode commented
@dakshdeepHERE Alternatively we could create a new pull request and link this one. I configured my Githib

> > @bpicoCode can you please sign the CLA assistant so we can merge this PR?
> > I signed the CLA but my initial commit came from my local repo which wasn't linked to a Github user. See that 'Benjamin Picone' hasn't signed yet but bpicoCode (also me) has signed. I can't change that initial commit. Maybe we should delete that commit so that 'Benjamin Picone' no longer shows up?

Alternatively we could create a new pull request with all the review changes.

2024-01-07 14:59 UTC, dakshdeepHERE commented
@bpicoCode please go on

2024-01-16 18:15 UTC, dakshdeepHERE commented
This PR is getting closed as the new one is opened by the Author.

2024-01-16 18:15 UTC, closed without merging