[Term Entry] D3 Selection .join() added
Codecademy/docs pull request #4168
Opened 2024-01-04 07:19 UTC by antriksh-9

### Description

I was assigned this [issue](https://github.com/Codecademy/docs/issues/3957).
Created Codecademy Docs term entry on the .join() method for D3.
CLoses #3957.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-01-04 14:24 UTC, avdhoottt requested changes
Excellent Work @antriksh-9, I reviewed the content and mentioned some changes, please make them.

2024-01-04 14:24 UTC, avdhoottt commented on content/d3/concepts/selection/terms/join/join.md
> +  exitFunction
```suggestion
  enter,
  update,
  exit

```
Better to keep it as simple as possible.

2024-01-04 14:24 UTC, avdhoottt commented on content/d3/concepts/selection/terms/join/join.md
> +- `exitFunction`: Function specifying how to handle elements that no longer have corresponding data.
```suggestion
- `enter`:  Function specifying how to create new elements for entering data.
- `update`: Function specifying how to update properties of existing elements based on data.
- `exit`: Function specifying how to handle elements that no longer have corresponding data.

```

2024-01-04 14:24 UTC, avdhoottt commented on content/d3/concepts/selection/terms/join/join.md
> +In this example, if there are fewer `p` elements than data points, new `p` elements are created (enter selection). If there are an equal number, existing elements are updated (update selection). If t
```suggestion
In this example, if there are fewer `p` elements than data points, new `p` elements are created (`enter` selection). If there is an equal number, existing elements are updated (`update` selection). If there are more elements than data points, excess elements are removed (`exit` selection).

```

2024-01-04 14:30 UTC, antriksh-9 commented
Hey @avdhoottt I have made the changes.

2024-01-07 17:15 UTC, avdhoottt approved these changes
Looks good for the second review, Thanks for the changes.

2024-07-30 17:24 UTC, avdhoottt approved these changes
LGTM!

2024-07-30 17:26 UTC, merged