[Edit] Arrays: Added codebyte for .toSorted()
Codecademy/docs pull request #4169
Opened 2024-01-04 09:58 UTC by andersooi

### Description

- Added a codebyte for Javascript Array's toSorted() method
- Closes #4137

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-01-04 16:46 UTC, avdhoottt requested changes
@andersooi Thanks for the contribution. For your Information the .toSorted() method only works with Node.js Version 20 or above and our compiler doesn't support that. If we execute this code in the codebyte it gives an error. I discussed it with the internal team and decided to make your contributed code a regular example. Please make the suggested change.

2024-01-05 02:53 UTC, andersooi commented
Hi @avdhoottt noted on the compatibility issue. The original entry already has an example section from the original contributor. Should I park the codebyte example (code + expected output) under that section instead?

2024-01-05 13:30 UTC, avdhoottt commented
Edit the other example's heading as `Example 1`, `Example 2`, and then mark yours accordingly.

2024-01-07 17:11 UTC, avdhoottt commented on content/javascript/concepts/arrays/terms/toSorted/toSorted.md
> +The following example demonstrates the use of an arrow function in the `toSorted()` method:
```suggestion
The following example demonstrates the use of an arrow function in the `.toSorted()` method:
```

2024-01-07 17:12 UTC, avdhoottt approved these changes
Looks good to me!! Thanks for the changes.

2024-01-10 08:56 UTC, andersooi commented
@ishg-153 do let me know if there are any changes that need to be made!

2024-01-10 18:38 UTC, ishg-153 approved these changes
Hey @andersooi! Your example looks great! I have suggested minor changes. If we follow the `term-entry-template` there should just be one `## Example` sub-heading, so I have asked you to undo that.

2024-01-10 18:38 UTC, ishg-153 commented on content/javascript/concepts/arrays/terms/toSorted/toSorted.md
> +## Example 1
```suggestion
## Example
```

2024-01-10 18:38 UTC, ishg-153 commented on content/javascript/concepts/arrays/terms/toSorted/toSorted.md
> +## Example 2
```suggestion
```

2024-01-10 18:39 UTC, ishg-153 requested changes
The above changes are requested. (Accidentally approved beforehand)

2024-01-17 07:30 UTC, merged