[Term Entry] PHP Array Functions: array_pad()
Codecademy/docs pull request #4178
Opened 2024-01-05 06:28 UTC by andersooi

### Description

- Added new term entry for PHP's Array Functions: array_pad()
- Closes #4000 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-01-05 07:42 UTC, dakshdeepHERE requested changes
Few changes from my side for you @andersooi 🚀

2024-01-05 07:42 UTC, dakshdeepHERE commented on content/php/concepts/arrays/terms/array-pad/array-pad.md
> +The **`array_pad()`** method is used to pad an array to a specified length with a value. If the specified length is positve, the array is padded to the right with the value until the array's size equ
```suggestion
The **`array_pad()`** method pads an array to a specified length with a value. If the specified length is positive, the array is padded to the right with the value until the array's size equals to the specified length. Conversely, if the specified length is negative, the array is padded to the left with the value until the array's size equals the absolute value of the specified length. The array will not be padded if the size of the array is more than the absolute value of the specified length.
```

2024-01-05 07:42 UTC, dakshdeepHERE commented on content/php/concepts/arrays/terms/array-pad/array-pad.md
> +- `$value`: The value to be padded to `array` if its size is less than absolute value of `$length`.
```suggestion
- `$array`: Specifies the input `array`.
- `$length`: The new size of `array`.
- `$value`: The value to be padded to `array` if its size is less than the absolute value of `$length`.
```

2024-01-05 07:42 UTC, dakshdeepHERE commented on content/php/concepts/arrays/terms/array-pad/array-pad.md
> +The `array_pad()` function returns the padded array according to the specified length with the intended value.
```suggestion
>> **Note:** The `array_pad()` function returns the padded array according to the specified length with the intended value.
```
Lets keep this as Note

2024-01-05 07:42 UTC, dakshdeepHERE commented on content/php/concepts/arrays/terms/array-pad/array-pad.md
> +The example will result in the following output:
```suggestion
The example above will result in the following output:
```

2024-01-06 13:55 UTC, dakshdeepHERE approved these changes
This looks good for second review 🚀

2024-01-08 15:35 UTC, avdhoottt commented on content/php/concepts/arrays/terms/array-pad/array-pad.md
> +The **`array_pad()`** method pads an array to a specified length with a value. If the specified length is positive, the array is padded to the right with the value until the array's size equals to th
```suggestion
The **`array_pad()`** method pads an array to a specified length with a value. If the specified length is positive, the array is padded to the right with the value until the array's size equals the specified length. Conversely, if the specified length is negative, the array is padded to the left with the value until the array's size equals the absolute value of the specified length. The array will not be padded if the size of the array is more than the absolute value of the specified length.
```

2024-01-08 15:38 UTC, avdhoottt approved these changes
Looks good to get merged!!

2024-01-08 15:40 UTC, merged