Resolve 4150 commit issue
Codecademy/docs pull request #4210
Opened 2024-01-10 19:28 UTC by bpicoCode

### Description
- Resolving Commit Issue (hopefully)

### Type of Change
- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-01-10 19:29 UTC, bpicoCode commented
@daksh10110 Let me know how this looks.

2024-01-16 18:17 UTC, dakshdeepHERE approved these changes
This looks good @bpicoCode 🚀

2024-01-17 06:53 UTC, ishg-153 requested changes
@bpicoCode One small change from my end and then it's ready to go.

2024-01-17 06:53 UTC, ishg-153 commented on content/javascript/concepts/dates/terms/getUTCHours/getUTCHours.md
> +In the following example, variables `estDate` and `pstDate` are defined to store a new `Date` object in Eastern Time and Pacific Time respectively. The method `.getUTCHours()` is then used to print t
```suggestion
In the following example, variables `estDate` and `pstDate` are defined to store a new `Date` object in Eastern Time and Pacific Time respectively. The method `.getUTCHours()` is then used to print the hours of the dates according to universal time. Run the example in the Codebyte below to test the results:
```
We avoid the use of personal pronouns in entries.

2024-01-17 19:00 UTC, bpicoCode commented
> @bpicoCode One small change from my end and then it's ready to go.

Made the change!

2024-01-18 18:13 UTC, merged