Uxui competitive analysis
Codecademy/docs pull request #4211
Opened 2024-01-11 09:02 UTC by christaton

### Description

Creating docs entry for 'Competitive Analysis' in the Codecademy UI/UX content section. Includes an overview of the concept and the basic process.

Closes #3888 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-01-11 09:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4211) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4211) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4211) it.</sub>

2024-01-21 07:46 UTC, ishg-153 requested changes
@christaton This is a great entry.

I noticed you have used personal pronouns like `you` all throughout the entry. You need to rephrase the sentences to remove any personal pronouns as we refrain from using them in entries. Please let me know once you are done making this change.

2024-01-21 12:48 UTC, christaton commented
@ishg-153 Thank you for the feedback. I have updated and committed the changes, and re-requested review.

2024-01-23 17:38 UTC, ishg-153 requested changes
@christaton I've suggested a couple of more changes. Please make those and ping me once done.

2024-01-23 17:38 UTC, ishg-153 commented on content/uiux/concepts/competitive-analysis/competitive-analysis.md
> +Integrate successful elements from competitors' interfaces while addressing their shortcomings to create a unique and improved user experience for the audience.
```suggestion
Successful elements from competitors' interfaces can be integrated into the product while addressing their shortcomings to create a unique and improved user experience for the audience.
```

2024-01-23 17:38 UTC, ishg-153 commented on content/uiux/concepts/competitive-analysis/competitive-analysis.md
> +In the field of UX/UI design, **Competitive Analysis** is a crucial process for evaluating and benchmarking a digital product against competitors. By examining the user experience, [visual design](ht
```suggestion
In UI/UX design, **Competitive Analysis** is a crucial process for evaluating and benchmarking a digital product against competitors. By examining the user experience, [visual design](https://www.codecademy.com/resources/docs/uiux/visual-design), interaction elements, content strategy, and technological implementations of rival platforms, valuable insights are gained to inform and enhance design decisions.
```

2024-01-23 17:38 UTC, ishg-153 commented on content/uiux/concepts/competitive-analysis/competitive-analysis.md
> +Understanding the competitive landscape helps to align with industry standards, identify user expectations, and foster innovation. This strategic analysis ensures that the digital interface not only
```suggestion
Understanding the competitive landscape helps to align with industry standards, identify user expectations, and foster innovation. This strategic analysis ensures that the digital interface meets user needs.
```

2024-01-23 21:13 UTC, christaton reviewed
Thanks for the feedback @ishg-153. Changes accepted and implemented.

2024-01-24 18:53 UTC, ishg-153 approved these changes
@christaton Great! This looks ready for a second review.

2024-01-24 19:20 UTC, Helfese approved these changes

2024-01-26 13:03 UTC, ishg-153 commented
Hey @Helfese. Only the maintainers (people with the collaborator tag) review and approve requests. I request you to not request or approve changes.

2024-01-29 11:53 UTC, dakshdeepHERE approved these changes
LGTM for merge 🚀

2024-01-29 11:54 UTC, merged