Create boolean-logic.md
Codecademy/docs pull request #4225
Opened 2024-01-17 03:10 UTC by noahpgordon

### Description

Added **boolean-logic.md** within Java. Closes #4175 

(I'm unsure if classes within Java Codebytes must have specific names to work. Please advise.)

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-01-17 16:34 UTC, dakshdeepHERE requested changes
I have requested few changes @noahpgordon 🚀

2024-01-17 16:34 UTC, dakshdeepHERE commented on content/java/concepts/boolean-logic/boolean-logic.md
> +**Boolean logic** describes the ways in which boolean values can be combined and manipulated. Java implements boolean logic through a set of [operators](https://www.codecademy.com/resources/docs/java
```suggestion
**Boolean logic** describes how boolean values can be combined and manipulated. Java implements boolean logic through a set of [operators](https://www.codecademy.com/resources/docs/java/operators) and [methods](https://www.codecademy.com/resources/docs/java/methods).
```

2024-01-17 16:34 UTC, dakshdeepHERE commented on content/java/concepts/boolean-logic/boolean-logic.md
> +### Codebyte Example
Lets make this is a simple example section. As our online compiler doesn't support java.

2024-01-19 02:49 UTC, noahpgordon commented
@dakshdeepHERE Implemented.

2024-01-19 15:04 UTC, dakshdeepHERE approved these changes
LGTM 🚀

2024-01-19 17:34 UTC, avdhoottt commented on content/java/concepts/boolean-logic/boolean-logic.md
> +  - 'Computer Science'
```suggestion
  - 'Computer Science'
  - 'Code Foundations'
```

2024-01-19 17:37 UTC, avdhoottt reviewed
Looks to get merged!!

2024-01-19 17:37 UTC, avdhoottt approved these changes

2024-01-19 17:42 UTC, merged