Css bottom fixed
Codecademy/docs pull request #4228
Opened 2024-01-17 11:09 UTC by Aukse1976

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-01-18 14:07 UTC, dakshdeepHERE requested changes
Some changes and can you explain why you have added other two images if you are not using them in the entry?

2024-01-18 14:07 UTC, dakshdeepHERE commented on content/css/concepts/position/terms/bottom/bottom.md
> +![Shows use CSS bottom attribute with element position set to absolute](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-absolute-bottom.png)
```suggestion
![Shows the use of CSS bottom attribute with element position set to absolute](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-absolute-bottom.png)
```

2024-01-18 14:07 UTC, dakshdeepHERE commented on content/css/concepts/position/terms/bottom/bottom.md
> +![Shows use CSS bottom attribute with element position set to relative](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-relative-bottom.png)
```suggestion
![Shows the use of CSS bottom attribute with element position set to relative](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-relative-bottom.png)
```

2024-01-19 16:56 UTC, Aukse1976 commented on content/css/concepts/position/terms/bottom/bottom.md
> +![Shows use CSS bottom attribute with element position set to relative](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-relative-bottom.png)
Thanks :) Changes made

2024-01-19 16:59 UTC, dakshdeepHERE commented
@Aukse1976 remove the other two identical images. Only keep the ones you are using the entry.

2024-01-19 17:04 UTC, Aukse1976 commented
> Some changes and can you explain why you have added other two images if you are not using them in the entry?

Two pairs of images are similar, but  file names are different.   I’ve only attached two with file names i thought are more 
suitable. And deleated those unused filed from 'media' folder.

2024-01-19 17:17 UTC, dakshdeepHERE commented
I'm saying deleted these two files `media/css-bottom-position-relative.png` and `media/css-bottom-position-absolute.png`. As it is just redundant keep it there if they are not getting used anywhere.

2024-01-19 18:54 UTC, Aukse1976 commented
> I'm saying delete these two files `media/css-bottom-position-relative.png` and `media/css-bottom-position-absolute.png`. As it is just redundant keep it there if they are not getting used anywhere.

aukse@DESKTOP-AK0M9HI MINGW64 /c/projects/docs/media (css-bottom-fixed)
$ git commit -m "Deleated files: css-bottom-position-absolute.png and css-bottom-position-relative"
fatal: Unable to create 'C:/projects/docs/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

2024-01-19 20:40 UTC, Aukse1976 commented
> I'm saying delete these two files `media/css-bottom-position-relative.png` and `media/css-bottom-position-absolute.png`. As it is just redundant keep it there if they are not getting used anywhere.

Please review  all changes are made in new branch "css-bottom" :) #4257 I hope it will help

2024-01-22 11:08 UTC, closed without merging