Data types: Adding codebyte for data-type.md
Codecademy/docs pull request #4258
Opened 2024-01-19 20:55 UTC by kamlesh-ops

### Description

- Added new sections for Number, BigInt, String, Boolean, Null, Undefined and Objects.
- closes issue #4134 

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-01-19 20:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4258) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4258) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4258) it.</sub>

2024-01-20 14:21 UTC, avdhoottt requested changes
Hey @kamlesh-ops, you've done excellent work but you have to add code bytes under ` ```codebyte/javascript`. You have added the codes as the normal examples.

2024-01-20 14:24 UTC, kamlesh-ops commented
@avdhoottt I see. My bad. I will make another PR in few hours after rectifying.

2024-01-20 14:45 UTC, avdhoottt commented
@kamlesh-ops You don't need to create another PR, you can just update this one. You have used ` ```js` instead of ` ```codebyte/javascript`. Just make these changes.

2024-01-20 14:47 UTC, avdhoottt commented
We use `shell` block for the output.

2024-01-20 14:49 UTC, kamlesh-ops commented
Sure got it

2024-01-20 14:51 UTC, avdhoottt commented
Another thing @kamlesh-ops, have you by any chance removed or updated the existing ` ```js` codes?

2024-01-20 18:12 UTC, kamlesh-ops commented
No I didn't modify anything, just replaced the ```js label. Are there any more issues??

2024-01-20 18:16 UTC, avdhoottt commented
@kamlesh-ops Nope, you shouldn't have done that. You must create a new code byte at the end of the existing content. Make the entry as it was and add the code byte as instructed. You can refer to our [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md),

2024-01-21 02:31 UTC, kamlesh-ops commented
@avdhoottt Sir I have made some changes. Actually, I had restructured the existing code and explanations, so I have just added the new changed section under the previous section, you may find two sections for string, for example, the new modified one and the old one. 
Pl verify and let me know. 
Thanks.

2024-01-28 17:43 UTC, avdhoottt requested changes
Hey @kamlesh-ops, I appreciate your work but I need to tell you that there is a fixed structure for each entry as follows - 
- Heading
- One line description
- Normal Code block
- Output of the above code block
- Then the code byte.

Please follow these. Then it would help if you made these - 
- You have added 2 String headings.
- You don't need to add concepts like string interpolation, etc in this entry as this entry should only give a basic overview of the data types.
- You have two boolean headings, keep only one.
- The same goes for Null and Undefined headings.

I suggest keeping the previous codes (those were written before you made this PR) and then adding the codebytes only below the old content. You can edit the old content too but try to keep it as simple as possible. It's better to keep one codebyte for one heading if possible.

Thanks.

2024-01-28 18:04 UTC, kamlesh-ops commented
@avdhoottt I get the idea. Actually this is my first PR, so maybe that's why the mistake. I will resolve the problem and get back.

2024-01-29 18:18 UTC, kamlesh-ops commented
@avdhoottt I hope I have made the changes as you had instructed.

2024-01-31 15:45 UTC, avdhoottt commented on content/javascript/concepts/data-types/data-types.md
> +In JavaScript, numbers are always stored as double-precision floating point numbers.
```suggestion

In JavaScript, numbers are always stored as double-precision floating point numbers.
```

2024-01-31 15:48 UTC, avdhoottt commented on content/javascript/concepts/data-types/data-types.md
> +The integer precision for the `Number` type is `15 digits`. You can see for yourself.
```suggestion
The integer precision for the `Number` type is `15 digits`. The following example is runnable: 
```

2024-01-31 15:48 UTC, avdhoottt commented on content/javascript/concepts/data-types/data-types.md
> +console.log(value); // returns true
```suggestion
let value = Boolean('Harry'); 
console.log(value);
```

2024-01-31 15:50 UTC, avdhoottt approved these changes
Excellent work @kamlesh-ops 🚀, it's good to go for the second review.

2024-01-31 16:44 UTC, kamlesh-ops commented
@avdhoottt great to know! Thanks:)

2024-02-12 15:08 UTC, ishg-153 requested changes
@kamlesh-ops I've requested a few changes please make those.

2024-02-12 15:08 UTC, ishg-153 commented on content/javascript/concepts/data-types/data-types.md
> +To find the length of the string, the built-in `length` property is used.
```suggestion
To find the length of the string, the built-in `length` property is used. Run the following example to get a better idea:
```

2024-02-12 15:08 UTC, ishg-153 commented on content/javascript/concepts/data-types/data-types.md
> +To convert a non-boolean value into a boolean, the `Boolean` function or double not `!!` is used.
```suggestion
To convert a non-boolean value into a boolean, the `Boolean` function or double not `!!` is used. Run the following code block to see how `Boolean()` works:
```

2024-02-12 15:08 UTC, ishg-153 commented on content/javascript/concepts/data-types/data-types.md
> +Alternately, an empty `object` can be initialised and then the properties added to the object.
```suggestion
Alternately, an empty `object` can be initialized and the properties added to the object. Run the code below to see it in action:
```

2024-02-13 04:10 UTC, kamlesh-ops commented
@ishg-153 made the changes as requested.

2024-02-13 17:42 UTC, ishg-153 approved these changes
@kamlesh-ops looks good to merge to me.

2024-02-13 17:54 UTC, merged