feat: Add Issue section to PR template
Codecademy/docs pull request #4259
Opened 2024-01-19 21:14 UTC by CBID2

### Description
This PR adds a `Issue` section with commented instructions on how contributors should link the issue numbers that their contribution addresses. By adding this section, contributors know how to create effective PRs.  

### Type of Change

- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-01-19 21:23 UTC, CBID2 commented on .github/PULL_REQUEST_TEMPLATE.md
> +# Description
```suggestion
### Description
```

2024-01-19 21:23 UTC, CBID2 commented on .github/PULL_REQUEST_TEMPLATE.md
> +## Issue Solved
```suggestion
### Issue Solved
```

2024-01-19 21:28 UTC, CBID2 commented
Hi @KTom101! :) I'm ready for your review! :)

2024-01-21 07:31 UTC, ishg-153 commented
Hey @CBID2! Will this edit include instructions in the comments as mentioned in the description?

2024-01-21 07:53 UTC, CBID2 commented
> Hey @CBID2! Will this edit include instructions in the comments as mentioned in the description?

Yes @ishg-153

2024-01-21 09:16 UTC, ishg-153 commented
> Yes @ishg-153

Are you yet to add that, because I can't see that change? I see your edit to the last checklist item.

2024-01-21 17:23 UTC, CBID2 commented
> > Yes @ishg-153
> 
> 
> 
> @CBID2 Are you yet to add that, because I can't see that change? I see your edit to the last checklist item.

Hi @ishg-153. I added them.

2024-01-23 17:24 UTC, ishg-153 requested changes
@CBID2 I've suggested one change, please make it.

2024-01-23 17:24 UTC, ishg-153 commented on .github/PULL_REQUEST_TEMPLATE.md
> +Relates to #issue number(e.g., #123)
```suggestion
Please use the following format(s) to link the issue numbers that your contribution addresses: 
Closes #issue-number (where `issue-number` corresponds to the PRs' respective issue)
```

2024-01-23 17:25 UTC, CBID2 commented
> @CBID2 I've suggested one change, please make it.

Done @ishg-153

2024-01-23 17:47 UTC, ishg-153 approved these changes
@CBID2 This looks good to me. Ready for a second review!

2024-01-26 17:56 UTC, avdhoottt approved these changes
LGTM 🚀

2024-01-26 18:06 UTC, merged