Added hyperlinks to state and props + Arrow function definition
Codecademy/docs pull request #426
Opened 2021-11-15 20:13 UTC by Emiliano-Russo

### Description

components file was edited

state and props now have hyperlinks to their own page
props argument added to function component
arrow function + explanation added

### Type of Change

- Adding a new entry: yes added arrow function
- Updating the documentation: yes, no props argument on function

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

2021-11-15 20:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=426) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=426) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=426) it.</sub>

2021-11-15 22:32 UTC, Dusch4593 commented
Hi, @Emiliano-Russo! Thanks for helping us out with this entry; we truly appreciate it! I'll take a look at the changes you recently pushed and leave some comments and/or suggestions for you to resolve afterwards. Look out for those within the next 24 hours 😄

2021-11-15 22:56 UTC, Dusch4593 commented on content/react/concepts/components/components.md
> +- [props](https://www.codecademy.com/resources/docs/react/props) : Data that can be shared from parent component to child component
```suggestion
- A [`state` object](https://www.codecademy.com/resources/docs/react/state) that contains component data that is expected to change over time. 
- A [`props` object](https://www.codecademy.com/resources/docs/react/props) with data that can be passed down from parent component to child component.
```

Let's keep the back-ticks around "state" and "props" and treat these list items as complete sentences.

2021-11-15 22:58 UTC, Dusch4593 commented on content/react/concepts/components/components.md
>  In React, components make up the UI of the application. Components are pieces of code that are reuseable and independent. Each component comes with 1 or 2 of the following things:
```suggestion
In React, components make up the UI of the application. Components are pieces of code that are reusable and independent. Each component comes with one or both of the following:
```

2021-11-15 22:59 UTC, Dusch4593 commented on content/react/concepts/components/components.md
> +## Arrow function
```suggestion

## Arrow Function

```

Let's use "Title Case" for the headers and don't forget to surround them with an empty line. 😃

2021-11-15 23:03 UTC, Dusch4593 commented on content/react/concepts/components/components.md
> + ES6 version of JavaScript
Can we turn into a complete sentence ending with a period? Maybe we could also include a hyperlink to the Docs entry for arrow functions? 

https://www.codecademy.com/resources/docs/javascript/arrow-functions

2021-11-15 23:05 UTC, Dusch4593 requested changes
@Emiliano-Russo I've finished my review! 😃 Feel free to take a look at my comments/suggestions and tag me once you're finished. If you have any questions along the way, we're here to help! 👍

2021-11-16 02:31 UTC, Dusch4593 approved these changes
Hi, @Emiliano-Russo thanks for the changes! I'm going to approve this and make a quick change to the latter part of the file. Should we conduct one more review, @sonnynomnom?

2021-11-16 02:35 UTC, Dusch4593 commented
@Emiliano-Russo 

I made some edits in the following:

The meta `Description` tag:

- The `Description` meta tag near the top should (ideally) be 150 characters or less as this makes the web page for the entry more SEO-friendly.

The "Array Functions" section:

Technically, ESx isn't a "version of JavaScript". ECMAScript is the official name of the syntax specification most JS programmers use today. 

Also, let's avoid using 1st- and 2nd-person pronouns. Docs should have an inviting yet manual-like voice.

Thank you again for your work on this. I truly appreciate your help with this entry. 😃

2021-11-19 07:29 UTC, lukeecart approved these changes

2021-11-22 19:36 UTC, sonnynomnom commented
merging!

2021-11-22 19:37 UTC, merged

2021-11-30 21:49 UTC, sonnynomnom commented
Added two small changes: https://github.com/Codecademy/docs/commit/862dcb4678829eef332822fc06d274ad5d7cf92f

@Emiliano-Russo @Dusch4593 

Mostly just cus this looks funky:

![Screen Shot 2021-11-30 at 4 46 39 PM](https://user-images.githubusercontent.com/4999022/144133458-692825c9-acbd-417b-ac1b-b56aad13ed49.png)

2021-11-30 21:49 UTC, sonnynomnom commented
But anyway your entry is live!