[Term Entry] Variables: Add new term entry for variables
Codecademy/docs pull request #4260
Opened 2024-01-21 08:28 UTC by imfabra

### Description
Closes: #4237 

Added a new term entry for Dart variables in the path docs/content/dart/concepts/variables/variables.md. This includes a description of the term, syntax section, and an example explaining how variables work in Dart.

### Type of Change
- Adding a new entry

### Checklist
- [ ] Checked for typos and formatting issues
- [ ] Verified that the new entry follows documentation guidelines
- [ ] Linked the PR to the related issue (#4237)
- [ ] Assigned the PR to the appropriate reviewer

Please review the changes to ensure accuracy and completeness in the new term entry for Dart variables. Thank you!

2024-01-21 08:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4260) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4260) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4260) it.</sub>

2024-01-23 18:08 UTC, ishg-153 requested changes
@imfabra I noticed that through out the entry you have used [personal pronouns like you, we, etc. Please restructure the particular sentences to remove these personal pronouns as we don't use them in entries.

I have also suggested a couple of more changes, please let me know when you are done making them.

2024-01-23 18:08 UTC, ishg-153 commented on content/dart/concepts/variables/variables.md
> +In Dart, **variables** are storage blocks that contain modifiable information during the execution of a program. They are essential for software development, as they allow storing, manipulating, and
```suggestion
In Dart, **variables** are storage blocks that contain modifiable information during the execution of a program. They are essential for storing, manipulating, and referencing data.
```

2024-01-23 18:08 UTC, ishg-153 commented on content/dart/concepts/variables/variables.md
> +```
This doesn't feel necessary in this context, please remove it.

2024-02-06 17:37 UTC, ishg-153 commented
@imfabra It's been 2 weeks. Are you still working on the suggested changes?

2024-02-08 00:24 UTC, imfabra commented
Hello @ishg-153 ,
Yes, I'm still working on the suggestions. I'll be finishing up in the next few hours.

2024-02-24 18:01 UTC, ishg-153 commented
@imfabra Due to lack of response from your end I am closing this PR and unassigning the corresponding issue.

2024-02-24 18:03 UTC, closed without merging