[Concept Entry] Rust Data Types #3373
Codecademy/docs pull request #4263
Opened 2024-01-22 17:06 UTC by moha230

### Description

- added concept entry rust data-types
- added a folder data-types 
- added a file data-types.md
- Closes issue  #3373 

### Type of Change

- Adding concept entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [  ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR

2024-01-22 17:13 UTC, moha230 commented
Hello @ishg-153  and @dakshdeepHERE its done

2024-01-23 12:45 UTC, dakshdeepHERE requested changes
For now I have few comments for you to work on

2024-01-23 12:45 UTC, dakshdeepHERE commented on content/rust/concepts/data-types/data-types.md
> +## Primitive types || scala types
```suggestion
## Primitive and Scala types
```

2024-01-23 12:45 UTC, dakshdeepHERE commented on content/rust/concepts/data-types/data-types.md
> +A boolean is a data type representing one of two values: `true` or `false`. Booleans have a size of one byte and they are specified using the `bool` keyword with explicit type annotation:
give a funtion returning bool value example

2024-01-23 12:45 UTC, dakshdeepHERE commented on content/rust/concepts/data-types/data-types.md
> +## Tuples
```suggestion
### Tuples
```

2024-01-23 12:45 UTC, dakshdeepHERE commented on content/rust/concepts/data-types/data-types.md
> +## Arrays
```suggestion
### Arrays
```

2024-01-23 12:46 UTC, dakshdeepHERE commented
Also really well done on fixing the commit issue @moha230

2024-01-23 17:08 UTC, ishg-153 commented
@dakshdeepHERE let me know when this is ready for a second review.

2024-01-23 23:23 UTC, moha230 commented
its done @dakshdeepHERE

2024-01-29 17:12 UTC, moha230 commented
hello @ishg-153 its done

2024-02-14 08:59 UTC, moha230 commented
Hello @dakshdeepHERE i have done the changes is it possible to inform @ishg-153 thank you in advance.

2024-03-12 18:16 UTC, avdhoottt commented on content/rust/concepts/data-types/data-types.md
> +## Primitive and Scala types
```suggestion
## Primitive and Scalar types
```

2024-03-12 18:17 UTC, avdhoottt commented on content/rust/concepts/data-types/data-types.md
> +Scala types represent a single value.
```suggestion
Scalar types represent a single value.
```

2024-03-12 18:18 UTC, avdhoottt commented on content/rust/concepts/data-types/data-types.md
> +An integer in Rust is a number without a fractional component. The signed integer starts with an `i` followed by the bit number and the unsigned integer starts with `u` followed by the bit number. Th
```suggestion
An integer in Rust is a number without a fractional component. The signed integer starts with an `i` followed by the bit number and the unsigned integer starts with `u` followed by the bit number. The built-in integer types in Rust include `8bit`, `16bit`, `32bit`, `64bit`, and `128bit`:
```

2024-03-12 18:19 UTC, avdhoottt commented on content/rust/concepts/data-types/data-types.md
> +A floating-point represents numbers with decimal points. The built-in floating-point types are `f32` and `f64` which are 32 bits and 64 bits in size respectively. The default size is `f64` and all fl
```suggestion
A floating point represents numbers with decimal points. The built-in floating-point types are `f32` and `f64` which are 32 bits and 64 bits in size respectively. The default size is `f64` and all floating points are signed:
```

2024-03-12 18:21 UTC, avdhoottt commented on content/rust/concepts/data-types/data-types.md
> +
Can you add the output of the above code here?

2024-03-12 18:22 UTC, avdhoottt commented on content/rust/concepts/data-types/data-types.md
> +A tuple is a collection of values of different types. Tuples are constructed using parentheses `()` and each has a value with type signature. Tuples are used by functions to return multiple values as
```suggestion
A tuple is a collection of values of different types. Tuples are constructed using parentheses `()` and each has a value with the type signature. Tuples are used by functions to return multiple values as tuples can hold any number of values:
```

2024-03-12 18:23 UTC, avdhoottt commented on content/rust/concepts/data-types/data-types.md
> +}
```suggestion
fn main() {
    // Array
    let numbers: [i32; 5] = [11, 82, 12, 88, 90];

    // Accessing array elements
    let first_number = numbers[0];
    let second_number = numbers[1];

    // Printing tuple and array elements
    println!("Person: {} is {} years old. Adult: {}", name, age, is_adult);
    println!("Array: [{}, {}]", first_number, second_number);
}
```

2024-03-12 18:24 UTC, avdhoottt commented on content/rust/concepts/data-types/data-types.md
> +```
Add the output of the code.

2024-03-12 18:24 UTC, avdhoottt requested changes
Hey @moha230, can you make the suggested changes here?

2024-03-12 18:42 UTC, moha230 commented
@avdhoottt yes I make the changes as soon as possible thank you .

2024-03-13 08:30 UTC, moha230 commented on content/rust/concepts/data-types/data-types.md
> +## Primitive and Scala types
yes i i was wrong its scalar not scala

2024-03-13 08:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4263) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4263) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: moha230<br/>:x: AF7626<br/><hr/>**AF7626** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4263) it.</sub>

2024-03-13 08:51 UTC, moha230 commented
@avdhoottt its done Thank you

2024-03-18 09:29 UTC, avdhoottt approved these changes
LGTM!!

2024-05-15 07:18 UTC, ishg-153 commented
@AF7626 Please sign the CLA.
@moha230 if this a spare email or account you have please sign CLA with that account

2024-06-10 14:10 UTC, ishg-153 commented
@moha230 This PR is being closed due to a lack of activity.

2024-06-10 14:10 UTC, closed without merging