[Term Entry] Dart Iterable: New Concept Entry Iterable.md
Codecademy/docs pull request #4269
Opened 2024-01-24 09:57 UTC by AlessioAltomonte

### Description

- Added the Iterable term file for Dart 
- Closes issue #4245 
- 
### Type of Change

- Adding a new entry

### Checklist

- [x ] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-01-24 09:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4269) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4269) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4269) it.</sub>

2024-01-31 12:56 UTC, Sriparno08 reviewed
Hey @AlessioAltomonte, thanks for contributing to Codecademy!

I've listed all the modifications that you need to make in your entry below:

2024-01-31 12:56 UTC, Sriparno08 commented on content/dart/concepts/iterable/iterable.md
> +## Example
Let's remove the 'Syntax'  section as it's not needed:

```suggestion
## Example
```

2024-01-31 12:56 UTC, Sriparno08 commented on content/dart/concepts/iterable/iterable.md
> +    Dart uses the Iterable<E> abstract class to represent iterable objects.
Let's limit this entry to a single example as it's enough for demonstrating the concept. Plus, let's remove the 'Summary' section as it's not needed.

Also, let's replace the whole with the following:

````suggestion
Here is the output for the above code:

```shell
12
23
34
45
56
```
````

2024-01-31 12:56 UTC, Sriparno08 commented on content/dart/concepts/iterable/iterable.md
> +Code language: Dart (dart)
````suggestion
```dart
void main() {
  Iterable<int> iter = [12, 23, 34, 45, 56];
  for (var num in iter) {
    print(num);
  }
}
```
````

2024-02-06 15:10 UTC, Sriparno08 commented
Hey @AlessioAltomonte, please make the required changes so that we can review them and move on to the second round of review.

2024-02-10 06:06 UTC, Sriparno08 approved these changes
This looks good for a second review 👍

2024-02-24 17:47 UTC, ishg-153 requested changes
@AlessioAltomonte I have suggested changes please make those. Let me know once done.

2024-02-24 17:47 UTC, ishg-153 commented on content/dart/concepts/iterable/iterable.md
> +An iterable object consists of an iterator getter, which returns an iterator object. The returned iterator is then used by the iterable object for element traversal. Each time the iterator getter is
```suggestion
An iterable object consists of an iterator getter, which returns elements from the iterable object. The iterator is used for element traversal. Each time the iterator getter is accessed, a new iterator is returned by the iterable object. This means that more than one iterator can be returned by the same iterable object.
```

2024-03-10 13:49 UTC, ishg-153 commented
@AlessioAltomonte It's been 2 weeks. Are you still working on the changes?

2024-03-15 11:37 UTC, ishg-153 approved these changes
Went ahead and made the changes.
This is ready to merge.

2024-03-15 11:38 UTC, merged