Adding new term entry for Hick's law to UI/UX
Codecademy/docs pull request #4270
Opened 2024-01-24 15:09 UTC by alopezgurria

### Description

This PR adds a new term entry for Hick's law in the UI/UX section as well as 2 new images in the media directory to illustrate Hick's law formula and examples.

Closes #4023 issue

### Type of Change

- Adding a new entry
- Adding new images to media

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-01-24 15:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4270) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4270) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4270) it.</sub>

2024-01-30 18:14 UTC, ishg-153 requested changes
@alopezgurria This is a great entry. I have suggested some minor changes please make those. 

Did you create the images yourself? They look amazing! Just in the formula image check if it's possible to add the '2' in subscript.

2024-01-30 18:14 UTC, ishg-153 commented on content/uiux/concepts/hicks-law/hicks-law.md
> +![Describe image](https://raw.githubusercontent.com/Codecademy/docs/main/media/hickslaw-formula.png)
Instead of "Describe image" actually write a description for the image
For example: Formula for Hicks Law

2024-01-30 18:14 UTC, ishg-153 commented on content/uiux/concepts/hicks-law/hicks-law.md
> +## Implications in UX design:
```suggestion
## Implications of Hick's Law:
```

2024-01-30 18:14 UTC, ishg-153 commented on content/uiux/concepts/hicks-law/hicks-law.md
> +![Describe image](https://raw.githubusercontent.com/Codecademy/docs/main/media/hickslaw-examples.png)
Similarly here as well, add a description of the image.

2024-01-30 18:14 UTC, ishg-153 commented on content/uiux/concepts/hicks-law/hicks-law.md
> +Hick’s Law states that increasing the number of choices will increase the decision time logarithmically and is written as follows: RT = a + b log<sub>2</sub>(n)
```suggestion
Hick’s Law states that increasing the number of choices will increase the decision time logarithmically and is represented as follows: 
RT = a + b log<sub>2</sub>(n)
```

2024-01-31 09:15 UTC, alopezgurria commented
@ishg-153 Thank you so much for your feedback. Yes, I did make all the images myself. I will proceed to make the changes you recommend right now.

2024-01-31 11:01 UTC, alopezgurria commented
@ishg-153 I just made the changes, looking forward to your feedback

2024-02-06 17:39 UTC, ishg-153 approved these changes
@alopezgurria Great Work! This is ready for a second review.

I apologize for the delayed response.

2024-03-22 14:43 UTC, Sriparno08 approved these changes
Looks good 👍

2024-03-22 14:44 UTC, merged