Added constructors.md
Codecademy/docs pull request #4289
Opened 2024-01-28 19:23 UTC by vjurcutiu

### Description

Added the constructors.md file, which covers the concept of constructors in Dart.

### Issue Solved

Closes #4247

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

<!--
Having trouble with the PR checker? Here are some common issues and resolutions:

- verify_formatting is failing
  - run `yarn format path/to/markdown/file.md` or `yarn format:all` and commit the results
- verify_lint is failing
  - same as above
  - if verify_lint is still failing, running `yarn lint` locally should let you know what needs to be changed by hand
- test is failing
  - ensure any new markdown files have a `Title` and `Description` defined in their metadata
  - ensure any new markdown files only contain alphanumerics and dashes in their file names and have the same name as their parent directory
  - if that looks ok, running `yarn test` locally should let you know what the issue is
→

2024-01-28 19:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4289) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4289) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4289) it.</sub>

2024-01-29 11:51 UTC, dakshdeepHERE requested changes
Nice entry, for now I have few comments for you to work on @vjurcutiu

2024-01-29 11:51 UTC, dakshdeepHERE commented on dart/concepts/constructors/constructors.md
> +- Factory constructors
```suggestion
In Dart, there are six constructor types:

- `Default constructors`
- `Generative constructors`
- `Named constructors`
- `Redirecting constructors`
- `Constant constructors`
- `Factory constructors`
```

2024-01-29 11:51 UTC, dakshdeepHERE commented on dart/concepts/constructors/constructors.md
> +Super parameters will forward parameters to the declared superclass constructor. They help avoid having to manually pass each parameter in the super invocation of a constructor.
```suggestion
To better deal with constructor parameters and superclasses, Dart offers two main tools: superparameters and the initializer list. Superparameters will forward parameters to the declared superclass constructor. They help avoid having to manually pass each parameter in the super invocation of a constructor:
```

2024-02-02 22:17 UTC, Helfese approved these changes

2024-02-27 18:04 UTC, ishg-153 approved these changes
@vjurcutiu Great Entry! Looks ready to merge.

2024-02-27 18:06 UTC, merged