First iteration of Dart math-methods entry
Codecademy/docs pull request #4317
Opened 2024-01-29 22:29 UTC by dalling123

### Description

- Added entry for Dart math methods.

### Issue Solved

- Closes Issue #4243 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-01-29 22:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4317) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4317) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4317) it.</sub>

2024-01-30 14:28 UTC, avdhoottt requested changes
An overall comment for you. Try to add more content to it, for example, you can add a table that includes the methods and their short description (Don't go too much in deep as I said there will be separate entries)

2024-01-30 14:28 UTC, avdhoottt commented on content/dart/concepts/math-methods/math-methods.md
> +```
Remove this section as there will be separate term entries for these methods.

2024-02-07 16:59 UTC, avdhoottt commented
@dalling123 Are you still working on this PR?

2024-02-09 10:59 UTC, dalling123 commented
Hi Avdhoot,

Yes I am! Just on holiday this week - I can complete next week if thats
okay! Best,

Dylan

On Wed, 7 Feb 2024, 17:59 Avdhoot, ***@***.***> wrote:

> @dalling123 <https://github.com/dalling123> Are you still working on this
> PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Codecademy/docs/pull/4317#issuecomment-1932485747>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2AFIVMZJFBXRDTOHAIJ4CLYSOXGVAVCNFSM6AAAAABCQHAH7OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMZSGQ4DKNZUG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-15 17:03 UTC, avdhoottt commented
@dalling123 are you available to make the changes now?

2024-02-29 16:10 UTC, avdhoottt approved these changes
Looks good for the second review.

2024-03-07 18:12 UTC, dalling123 commented
Hello @avdhoottt and @ishg-153,
What next steps are needed here?

2024-03-08 19:02 UTC, ishg-153 reviewed
@dalling123 Great Work! Ready to merge!

2024-03-08 19:03 UTC, ishg-153 approved these changes

2024-03-08 19:16 UTC, merged