[Edit]: Python math-module term entries
Codecademy/docs pull request #4318
Opened 2024-01-30 15:46 UTC by ishg-153

### Description
Added separate shell blocks for examples in all the existing term entries.

### Issue Solved

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-02-07 17:20 UTC, ishg-153 commented
Hey @dakshdeepHERE Are you done reviewing this?

2024-02-07 17:21 UTC, dakshdeepHERE commented
Hey @ishg-153, yep I will review it today.

2024-02-13 18:07 UTC, dakshdeepHERE requested changes
Few changes from my side overall looks perfect.

2024-02-19 17:49 UTC, ishg-153 commented on content/python/concepts/math-module/terms/math-sqrt/math-sqrt.md
> +The above code give the following output:
```suggestion
The above code gives the following output:
```

2024-02-19 17:49 UTC, ishg-153 commented on content/python/concepts/math-module/terms/math-sqrt/math-sqrt.md
> +The above code give the following output:
```suggestion
The above code gives the following output:
```

2024-02-19 17:49 UTC, ishg-153 commented on content/python/concepts/math-module/terms/math-tan/math-tan.md
> +The above code give the following output:
```suggestion
The above code gives the following output:
```

2024-02-19 17:49 UTC, ishg-153 commented on content/python/concepts/math-module/terms/math-tan/math-tan.md
> +The above code give the following output:
```suggestion
The above code gives the following output:
```

2024-02-19 17:52 UTC, ishg-153 commented
@dakshdeepHERE Sorry for the delay on my part, made the change everywhere!

2024-03-17 14:46 UTC, Sriparno08 approved these changes
Looks good 👍

2024-03-17 14:48 UTC, merged