Task#3997
Codecademy/docs pull request #4319
Opened 2024-01-30 16:25 UTC by kpoultney

### Description

I have created a folder under content > javascript > concepts > dates > terms named toLocaleString. In this folder, I have created a file named toLocaleString.md detailing the term entry of the .toLocaleString() method. I used Mozilla MDN docs as a reference guide for my entry. This contribution was done as a project (Contributing to the Codecademy Docs Repository) for the Codecademy course Learn Git and GitHub.

### Issue Solved

Closes #3997 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-01-30 16:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4319) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4319) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4319) it.</sub>

2024-01-30 22:46 UTC, Helfese approved these changes

2024-02-12 15:25 UTC, ishg-153 requested changes
@kpoultney I've suggested a couple of changes. Please make those and let me know once done.

I apologize for my delayed response.

2024-02-12 15:25 UTC, ishg-153 commented on content/javascript/concepts/dates/terms/toLocaleString/toLocaleString.md
> +// 11/22/1963, 12:30:00 PM
Under each of the `console.log` you have given the output in comments. Please remove that.

2024-02-12 15:25 UTC, ishg-153 commented on content/javascript/concepts/dates/terms/toLocaleString/toLocaleString.md
> +
```suggestion

The above code block gives the following output:

```shell
11/22/1963, 5:30:00 PM
1963. 11. 22. 오후 5:30:00
11/22/1963, 5:30:00 PM


```

2024-02-12 15:25 UTC, ishg-153 commented on content/javascript/concepts/dates/terms/toLocaleString/toLocaleString.md
> +The parameters `locale` and `options` can be used. `Locale` is represented by a language subtag and a region subtag (i.e. `en-US`). `Options` is an object defining the format for `weekday`, `year`, `
```suggestion
The parameters `locale` and `options` can be used. `Locale` is represented by a language subtag and a region subtag (i.e. `en-US`). `Options` is an object defining the format for `weekday`, `year`, `month`, `day`, `dayPeriod`, `hour`, `minute`, `second`, and `fractionalSecondDigits`. If undefined, the default setting is "numeric".
```

2024-02-13 17:36 UTC, ishg-153 requested changes
@kpoultney I'm marking previous suggestions as unresolved, please take a look and make the necessary changes. Make sure you push your changes to `Task#3997` branch. No need to create a new PR, we will keep working on this same one.

2024-02-14 17:13 UTC, ishg-153 requested changes
@kpoultney You still need to address on suggestion marking that as unresolved, please make it.

2024-02-15 16:25 UTC, ishg-153 requested changes
@kpoultney The change you are referring to is not reflecting as complete hence I am marking it as unresolved. Please take a look and make the suggested change and push it.

2024-02-23 17:04 UTC, closed without merging

2024-02-23 17:41 UTC, ishg-153 commented
@kpoultney I think you accidentally closed this repository because you deleted your fork of the Codecademy docs repo. Are you still willing to work on this issue?

2024-02-23 19:39 UTC, kpoultney commented
No