New term entry list.clear
Codecademy/docs pull request #4333
Opened 2024-02-04 15:02 UTC by Vino-Siva

### Description

New term entry for Dart - List.clear method

### Issue Solved

Closes #4294 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-02-05 14:40 UTC, avdhoottt requested changes
Hey @Vino-Siva, excellent entry. I've suggested some changes, please make them.

2024-02-05 14:40 UTC, avdhoottt commented on content/dart/concepts/list/terms/clear/clear.md
> +Title: 'Clear Method (List)'
```suggestion
Title: 'clear()'
```

2024-02-05 14:40 UTC, avdhoottt commented on content/dart/concepts/list/terms/clear/clear.md
> +## Implementation
```suggestion
## Syntax
```
This heading must be called Syntax.

2024-02-05 14:40 UTC, avdhoottt commented on content/dart/concepts/list/terms/clear/clear.md
> +void clear();
```suggestion
listName.clear();
```
The syntax should be as minimal as possible and the users should understand it easily.

2024-02-05 14:40 UTC, avdhoottt commented on content/dart/concepts/list/terms/clear/clear.md
> +This method does not take any parameters.
```suggestion
```
We don't need this section.

2024-02-05 14:40 UTC, avdhoottt commented on content/dart/concepts/list/terms/clear/clear.md
> +This method does not return any value.
This section is not required too but you can add this line in the introductory paragraph.

2024-02-05 14:40 UTC, avdhoottt commented on content/dart/concepts/list/terms/clear/clear.md
> +## Usage and Examples
```suggestion
## Example
```

2024-02-05 14:40 UTC, avdhoottt commented on content/dart/concepts/list/terms/clear/clear.md
> +The Output is:
```suggestion
The Output of the above code is:
```

2024-02-05 14:40 UTC, avdhoottt commented on content/dart/concepts/list/terms/clear/clear.md
> +>* If the list is a fixed list, calling clear() will throw an error.
```suggestion
>* The `clear()` method modifies the original list and does not create a new list.
>* After calling `clear()`, the list will have a length of 0.
>* If the list is already empty, calling `clear()` has no effect.
>* If the list is a fixed list, calling `clear()` will throw an error.
```

2024-02-05 14:40 UTC, avdhoottt commented on content/dart/concepts/list/terms/clear/clear.md
> +Uncaught Error: Unsupported operation: clear
```suggestion
[1, 1, 1]
3
[]
0
[3, 3, 3]
Uncaught Error: Unsupported operation: clear
```
The output was slightly incorrect, I've edited it.

2024-02-05 16:23 UTC, Vino-Siva commented
> Hey @Vino-Siva, excellent entry. I've suggested some changes, please make them.

Thanks 😄 ... Made the changes you have suggested.

2024-02-06 15:52 UTC, avdhoottt commented on content/dart/concepts/list/terms/clear/clear.md
> +The Output of the above code is:
```suggestion
The output of the above code is:
```

2024-02-06 15:53 UTC, avdhoottt commented on content/dart/concepts/list/terms/clear/clear.md
> +Description: 'Removes all objects from the list; the length of the list becomes zero.'
```suggestion
Description: 'Removes all objects from the list and the length of the list becomes zero.'
```

2024-02-06 15:53 UTC, avdhoottt commented on content/dart/concepts/list/terms/clear/clear.md
> +This method does not return any value.
```suggestion
The **`clear()`** method in Dart is used to remove all elements from a List, leaving an empty list in its place. This method is handy when you need to reset or clear the contents of a List, making it ready for new data. This method does not return any value.
```

2024-02-06 15:54 UTC, avdhoottt approved these changes
Great!! Look good for the second review.

2024-02-15 14:43 UTC, Sriparno08 approved these changes
Looks good 👍

2024-02-15 14:44 UTC, merged