add Python Math.floor()
Codecademy/docs pull request #4350
Opened 2024-02-06 02:40 UTC by evankart

### Description

Added a new term entry on the math.floor() function for [Python- Math Module](https://www.codecademy.com/resources/docs/python/math-module)

### Issue Solved

Closes #4347

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x ] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-02-06 02:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4350) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4350) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4350) it.</sub>

2024-02-07 17:22 UTC, ishg-153 requested changes
@evankart Very nice and crisp entry. I have suggested a couple of changes. Please make those and let me know once done.

2024-02-07 17:22 UTC, ishg-153 commented on content/python/concepts/math-module/terms/math-floor/math-floor.md
> +# Output: 9
```suggestion
import math

print(math.floor(4.2))

print(math.floor(9.7))
```
We want to get the users to run the codeblock and find the output themselves so no need to give the output.

2024-02-08 21:41 UTC, Helfese approved these changes

2024-02-09 21:30 UTC, helfese approved these changes

2024-02-12 15:17 UTC, ishg-153 requested changes
@evankart one last change, everything else looks good.

2024-02-12 15:17 UTC, ishg-153 commented on content/python/concepts/math-module/terms/math-floor/math-floor.md
> +134
Please add closing triple brackets
` ``` `
after these two lines

2024-02-12 21:47 UTC, evankart commented on content/python/concepts/math-module/terms/math-floor/math-floor.md
> +134
thanks @ishg-153, added now

2024-02-14 17:19 UTC, ishg-153 approved these changes
@evankart Looks good for a second review!

2024-02-29 16:13 UTC, avdhoottt commented on content/python/concepts/math-module/terms/math-floor/math-floor.md
> +Use `math.floor()` to return the floor of `134.2`:
```suggestion
Here's an example of `math.floor()` to return the floor of `134.2`:
```

2024-02-29 16:13 UTC, avdhoottt commented on content/python/concepts/math-module/terms/math-floor/math-floor.md
> +The **`math.floor()`** function takes in a value and returns its floor, the smallest integer greater than or equal to that value.
```suggestion
The `math.floor()` function takes in a value and returns its floor, the smallest integer greater than or equal to that value.
```

2024-02-29 16:14 UTC, avdhoottt commented on content/python/concepts/math-module/terms/math-floor/math-floor.md
> +Takes in a numeric data type and rounds the value down to the nearest integer.
```suggestion
The **`math.floor()`** function takes in a numeric data type and rounds the value down to the nearest integer.
```

2024-02-29 16:14 UTC, avdhoottt approved these changes
LGTM!!

2024-02-29 16:16 UTC, merged