Initial removeWhere.md for dart
Codecademy/docs pull request #4358
Opened 2024-02-09 04:19 UTC by lordgabriel98

### Description
Added documentation for .removeWhere() method for lists in Dart programming language. Also created the directory for list under Dart/concepts and other folders that were mentioned in the issue.

### Issue Solved

 Dart List .removeWhere() #4315

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-02-09 04:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4358) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4358) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4358) it.</sub>

2024-02-09 14:33 UTC, avdhoottt commented
Hey @lordgabriel98, the entry is not following the term entry guidelines. Please go through the [term-entry-template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md) and then improvise your content to meet the content guidelines.

2024-02-15 23:11 UTC, lordgabriel98 commented
@avdhoottt apologies for the delay. 

Updated removeWhere.md to better suit term-entry-template.

2024-02-22 07:26 UTC, lordgabriel98 commented
@avdhoottt please review this merge request asap. Thank you.

2024-02-29 16:06 UTC, avdhoottt requested changes
Hey @lordgabriel98, sorry for the delay. Please make the suggested changes.

2024-02-29 16:06 UTC, avdhoottt commented on content/dart/concepts/list/terms/removeWhere/removeWhere.md
> +```pseudo
Give one line space before and after a heading/code block/meta data.

2024-02-29 16:06 UTC, avdhoottt commented on content/dart/concepts/list/terms/removeWhere/removeWhere.md
> +The **.removeWhere()** method removes elements from a list, based on a given condition that is provided as an argument.
```suggestion

The **.removeWhere()** method removes elements from a list, based on a given condition that is provided as an argument.
```

2024-02-29 16:06 UTC, avdhoottt commented on content/dart/concepts/list/terms/removeWhere/removeWhere.md
> +
Describe the parameter function `test` below the syntax block.

2024-02-29 16:06 UTC, avdhoottt commented on content/dart/concepts/list/terms/removeWhere/removeWhere.md
> +
Add the description of the example in one line below the `Example` heading.

2024-02-29 16:06 UTC, avdhoottt commented on content/dart/concepts/list/terms/removeWhere/removeWhere.md
> +
Close the code block with closing ticks and add the output inside a ` ```shell `.

2024-03-01 04:49 UTC, lordgabriel98 commented
@avdhoottt thank for the review. Please review updates that I have made.

2024-03-05 08:42 UTC, avdhoottt commented on content/dart/concepts/list/terms/removeWhere/removeWhere.md
> +The .removeWhere() method takes in a `bool` function as an argument, referred to as the `test` parameter, which defines the condition for removal. Values in the list are removed if they satisfy this
```suggestion
- `test`: This function defines the condition for removal. Values in the list are removed if they satisfy this condition, meaning if the `test` function evaluates to `true` for those values.
```

2024-03-06 00:09 UTC, lordgabriel98 commented
@avdhoottt have made final changes to removeWhere.md.

2024-03-07 16:10 UTC, avdhoottt commented on content/dart/concepts/list/terms/removeWhere/removeWhere.md
> +- `test`: This function defines the condition for removal. Values in the list are removed if they satisfy this condition, meaning if the `test` function evaluates to `true` for those values
```suggestion
- `test`: This function defines the condition for removal. Values in the list are removed if they satisfy this condition, meaning if the `test` function evaluates to `true` for those values.
```

2024-03-07 16:10 UTC, avdhoottt commented on content/dart/concepts/list/terms/removeWhere/removeWhere.md
> +The above code will produce the following output:
```suggestion
The above code will return the following output:
```

2024-03-07 16:22 UTC, avdhoottt commented on content/dart/concepts/list/terms/removeWhere/removeWhere.md
> +
```suggestion
```

2024-03-07 16:25 UTC, avdhoottt approved these changes
Looks good for the second review!! Thanks.

2024-03-10 12:19 UTC, ishg-153 commented on content/dart/concepts/list/terms/removeWhere/removeWhere.md
> +void removeWhere(bool Function(E element) test)
```suggestion
void removeWhere(bool Function(E element))
```

2024-03-10 12:20 UTC, ishg-153 commented on content/dart/concepts/list/terms/removeWhere/removeWhere.md
> +- `test`: This function defines the condition for removal. Values in the list are removed if they satisfy this condition, meaning if the `test` function evaluates to `true` for those values.
```suggestion
- `Function(E element)`: It defines the condition for removal. If the function evaluates to `true` for a value in the list, then the value is removed from the list.
```

2024-03-11 00:39 UTC, lordgabriel98 commented
@ishg-153 I have made modifications as suggested. Thanks

2024-03-15 11:44 UTC, ishg-153 approved these changes
@lordgabriel98 Looks good to merge!

2024-03-15 12:50 UTC, lordgabriel98 commented
@ishg-153 roger that. Merging removewhere branch into main

2024-03-15 14:14 UTC, merged