[Edit] Git: Pull Requests - Add Note
Codecademy/docs pull request #4382
Opened 2024-02-14 21:03 UTC by liye0

### Description

- Added note under Method 1: Fork explaining exactly when a fork is needed.

### Issue Solved

- Closes Issue #4377 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-02-15 17:33 UTC, ishg-153 requested changes
@liye0 I've suggested one small change.

2024-02-15 17:33 UTC, ishg-153 commented on content/git/concepts/pull-requests/pull-requests.md
> +> **Note**: Forking a repository is needed when the user lacks write access to the original repository or when the user wants to make changes without affecting the original repository.
```suggestion
> **Note**: Forking a repository is needed when the user lacks write access to the original repository or wants to make changes without affecting the original repository.
```

2024-02-22 21:45 UTC, helfese approved these changes

2024-02-22 23:11 UTC, liye0 commented
@ishg-153 Could you please review the change

2024-02-24 18:22 UTC, ishg-153 approved these changes
@liye0 Looks good for a second review!

2024-02-25 17:29 UTC, avdhoottt approved these changes
LGTM!!

2024-02-26 17:51 UTC, ishg-153 commented
@avdhoottt merging this!

2024-02-26 17:51 UTC, merged