added length.md documentation
Codecademy/docs pull request #4384
Opened 2024-02-14 23:48 UTC by aaron-ross-sanchez

### Description

In this pull request, I added directories and a length.md file as shown below:
content/dart/concepts/map/terms/length/length.md

I followed the term-entry-template to add information about the length property in dart.

### Issue Solved

The issue is complete to my knowledge. If there is anything you would like changed, please let me know and I am happy to fix it!

### Type of Change

- Adding a new entry
- Updating the documentation (the only file that was edited was the file that was created: length.md)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-02-14 23:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4384) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4384) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4384) it.</sub>

2024-02-15 16:57 UTC, avdhoottt requested changes
Nice entry @aaron-ross-sanchez. I have suggested some changes, please make them.

2024-02-15 16:57 UTC, avdhoottt commented on content/dart/concepts/map/terms/length/length.md
> +```
The entire code block should be executable as it is. You need to wrap this code inside the main function.

2024-02-15 16:57 UTC, avdhoottt commented on content/dart/concepts/map/terms/length/length.md
> +}
The print statement is not there so there would be no output. Please add the print statement so it'll be a valid code and output block.

2024-02-15 16:57 UTC, avdhoottt commented on content/dart/concepts/map/terms/length/length.md
> +}
Same goes for this code block.

2024-02-15 16:57 UTC, avdhoottt commented on content/dart/concepts/map/terms/length/length.md
> +Title: 'length'
```suggestion
Title: '.length()'
```

2024-02-15 16:57 UTC, avdhoottt commented on content/dart/concepts/map/terms/length/length.md
> +In Dart, the **`.length`** property is a utility for determining the number of key-value pairs contained within a Map instance. It enables developers to efficiently manage and manipulate data structu
```suggestion
In Dart, the **`.length()`** property is a utility for determining the number of key-value pairs contained within a Map instance. It enables developers to efficiently manage and manipulate data structures by providing a quick and reliable means of accessing the size of a Map.
```

2024-02-15 16:57 UTC, avdhoottt commented on content/dart/concepts/map/terms/length/length.md
> +- `print();`: A built-in function that outputs data to the console.
```suggestion
```
No need for this description.

2024-02-15 16:57 UTC, avdhoottt commented on content/dart/concepts/map/terms/length/length.md
> +print(<Map-variable>.length);
```suggestion
Map-variable.length
```

2024-02-15 16:57 UTC, avdhoottt commented on content/dart/concepts/map/terms/length/length.md
> +- `<Map-variable>`: Represents a variable that holds a Map object.
```suggestion
- `Map-variable`: Represents a variable that holds a Map object.
```

2024-02-15 19:17 UTC, aaron-ross-sanchez commented
I made all of the suggested changes, please let me know what else needs to be adjusted! Thank you!

2024-02-16 15:09 UTC, avdhoottt approved these changes
Look good for the second review!!

2024-02-27 15:14 UTC, Sriparno08 approved these changes
Looks good 👍

2024-02-27 15:15 UTC, merged