add for-each to loops
Codecademy/docs pull request #4393
Opened 2024-02-15 21:14 UTC by connorpark24

### Description

I have added an explanation for for-each loops in C++ to iterate over a given container. I have provided both an explanation and brief example of the topic. The syntax for a traditional for loop can be confusing/overwhelming to beginners, so providing the syntax for the for-each loop may contribute to a better understanding of the concept of a loop in C++.

### Issue Solved

### Type of Change

- Updating the documentation

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-02-15 21:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4393) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4393) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4393) it.</sub>

2024-02-16 21:15 UTC, helfese approved these changes

2024-02-26 17:46 UTC, ishg-153 requested changes
@connorpark24 Please read the comments carefully and make all the suggested changes. Let me know once done.

2024-02-26 21:13 UTC, connorpark24 commented on content/cpp/concepts/loops/loops.md
> +}
Just updated the docs! Let me know if I need to change anything. This is my first time submitting a PR on a project so I am open to any feedback.

2024-02-29 17:05 UTC, ishg-153 requested changes
@connorpark24 Resuggested the one change you missed from the last review.

2024-02-29 17:05 UTC, ishg-153 commented on content/cpp/concepts/loops/loops.md
> +}
You need to copy and paste the entire code in your file that gives you the following output that you've now added.

2024-03-10 13:06 UTC, ishg-153 commented
@connorpark24 It's been over a week are you still working on this PR.

2024-03-15 23:41 UTC, closed without merging