[Term Entry] Dart List.asMap()
Codecademy/docs pull request #4400
Opened 2024-02-20 01:18 UTC by dancikmad

### Description

- Created a new term entry under Dart List **.asMap()** method

### Issue Solved

- Closes #4298 

### Type of Change

- Adding a new entry

### Checklist

- [x ] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-02-20 01:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4400) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4400) before we can accept your contribution.<br/><hr/>**Daniel Crigan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4400) it.</sub>

2024-02-21 17:06 UTC, avdhoottt requested changes
@dancikmad I have suggested some changes, can you make them?

2024-02-21 17:06 UTC, avdhoottt commented on content/dart/concepts/list/terms/asMap/asMap.md
> +- this method does not take any arguments.
```suggestion
```
No need for this statement.

2024-02-21 17:06 UTC, avdhoottt commented on content/dart/concepts/list/terms/asMap/asMap.md
> +Description: 'Returns a new **`Map`** view of a **`List`** where keys are the indices and values are elements'
```suggestion
Description: 'Returns an unmodifiable Map view of a List where keys are the indices and values are elements.'
```

2024-02-21 17:06 UTC, avdhoottt commented on content/dart/concepts/list/terms/asMap/asMap.md
> +With this approach, the list undergoes converstion into a map. The resulting map remains immutable.
Add this as a note that the resulting map remains immutable.

2024-02-21 17:06 UTC, avdhoottt commented on content/dart/concepts/list/terms/asMap/asMap.md
> +In Dart, the **`.asMap()`** method is used to obtain a new **`Map`** view of a **`List`**, where the keys are the indices of the list and the values are the elements at those indices. This method is
```suggestion
In Dart, the **`.asMap()`** method is used to obtain a new `Map` view of a `List`, where the keys are the indices of the list and the values are the elements at those indices. This method is particularly useful when you need to work with list elements in a map-line manner, accessing them by their indices.
```

2024-02-21 17:10 UTC, dancikmad commented
Hi, @avdhoottt thank you for pointing out. I will start working on these changes.

2024-02-21 20:28 UTC, dancikmad commented
@avdhoottt hi, i made changes after you review suggestions. let me know if it is all good now :)

2024-02-24 15:35 UTC, avdhoottt commented on content/dart/concepts/list/terms/asMap/asMap.md
> +> The resulting map remains immutable.
```suggestion
> **Note:** The resulting map remains immutable.
```

2024-02-24 15:36 UTC, avdhoottt approved these changes
Looks good for the second review.

2024-03-06 06:25 UTC, merged