[Term Entry] Dart List .addAll()
Codecademy/docs pull request #4401
Opened 2024-02-20 07:05 UTC by manviii27

### Description

- Created a new term entry under Dart List .addAll() method

### Issue Solved

- Closes #4300 

### Type of Change

- Adding a new entry

### Checklist

- [✓] All writings are my own.
- [✓] My entry follows the Codecademy Docs style guide.
- [✓] My changes generate no new warnings.
- [✓] I have performed a self-review of my own writing and code.
- [✓] I have checked my entry and corrected any misspellings.
- [✓] I have made corresponding changes to the documentation if needed.
- [✓] I have confirmed my changes are not being pushed from my forked `main` branch.
- [✓] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [✓] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-02-21 13:55 UTC, avdhoottt requested changes
Hey, @manviii27, Excellent entry. Please make the following changes.

2024-02-21 13:55 UTC, avdhoottt commented on content/dart/concepts/list/terms/addAll/addAll.md
> +
Describe the list1 and list2 parameters just below the syntax block. It should be in this format - 
```
- `paramter`: it's description.
```

2024-02-21 13:55 UTC, avdhoottt commented on content/dart/concepts/list/terms/addAll/addAll.md
> +The **`.addAll()`** method in Dart which allows you to append multiple elements from one list to another list. This method is useful when you want to combine the contents of multiple lists into a sin
```suggestion
The **`.addAll()`** method in Dart allows you to append multiple elements from one list to another. This method is useful when you want to combine the contents of multiple lists into a single list. This method does not create a new list but rather modifies the original list.

```

2024-02-21 13:55 UTC, avdhoottt commented on content/dart/concepts/list/terms/addAll/addAll.md
> +The `.addAll()` method only works on a growable list. If the list is a fixed-length list, then it throws an `Unsupported operation` error and retains all objects in the list.
You can add this sentence as a note here and replace it with the actual description of the code.

2024-02-21 13:55 UTC, avdhoottt commented on content/dart/concepts/list/terms/addAll/addAll.md
> +Description: 'Adds multiple objects from a list.'
```suggestion
Description: 'Adds multiple elements from a list.'

```

2024-03-01 10:30 UTC, manviii27 commented
@avdhoottt I've made the changes, please review

2024-03-03 17:27 UTC, avdhoottt commented on content/dart/concepts/list/terms/addAll/addAll.md
> +The **`.addAll()`** method in Dart allows you to append multiple elements from one list to another. This method is useful when you want to combine the contents of multiple lists into a single list. T
```suggestion
The **`.addAll()`** method in Dart allows appending multiple elements from one list to another. This method is useful to combine the contents of multiple lists into a single list. This method does not create a new list but rather modifies the original list.

```

2024-03-03 17:27 UTC, avdhoottt commented on content/dart/concepts/list/terms/addAll/addAll.md
> +**Note** - The `.addAll()` method only works on a growable list. If the list is a fixed-length list, it throws an `Unsupported operation` error and retains all objects.
```suggestion
> **Note** - The `.addAll()` method only works on a growable list. If the list is a fixed-length list, it throws an `Unsupported operation` error and retains all objects.

```

2024-03-03 17:28 UTC, avdhoottt commented on content/dart/concepts/list/terms/addAll/addAll.md
> +This code demonstrates the usage of the `addAll()` method in Dart. It appends different lists to existing lists. The first example appends a list `[4, 5, 6]` to an existing list `nums`. The second ex
```suggestion
This code demonstrates the usage of the `.addAll()` method in Dart. It appends different lists to existing lists. The first example appends a list `[4, 5, 6]` to an existing list `nums`. The second example combines the lists `otherNumbers` and `extraNumbers` and appends them to the `numbers` list. The third example appends a list `additionalElements` to a fixed length list `nonGrowableList`.

```

2024-03-03 17:28 UTC, avdhoottt approved these changes
Thanks for making the changes. PR is ready for the second review.

2024-03-12 13:56 UTC, Sriparno08 approved these changes
Looks good 👍

2024-03-12 13:57 UTC, merged