[concept entry] Dart map putIfAbsent function
Codecademy/docs pull request #4405
Opened 2024-02-21 00:11 UTC by sambunyan

Sam_p_Bunyan

### Description
-  I have added the document putifabsent.md in docs/content/dart/concepts/map/terms//putifabsent/putifabsent.md.

### Issue Solved
- Closes issue number #4373 
 
### Type of Change

- Adding a new entry

### Checklist

- [X ] All writings are my own.
- [X ] My entry follows the Codecademy Docs style guide.
- [ X] My changes generate no new warnings.
- [X ] I have performed a self-review of my own writing and code.
- [X ] I have checked my entry and corrected any misspellings.
- [X ] I have made corresponding changes to the documentation if needed.
- [X ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-02-21 00:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4405) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4405) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4405) it.</sub>

2024-02-21 23:28 UTC, helfese approved these changes

2024-02-24 15:48 UTC, avdhoottt requested changes
Hey @sambunyan, you have committed two files and only `content/dart/concepts/map/terms/putifabsent/putifabsent.md` this is valid. Please delete the other file so that I can then review it and suggest the changes.

2024-02-24 20:48 UTC, sambunyan commented
hello @avdhoottt, I have deleted the extra depository and the files within from my merging branch, only content/dart/concepts/map/terms/putifabsent/putifabsent.md is present now.

2024-02-25 17:19 UTC, avdhoottt requested changes
Hey Author, I have suggested some changes, can you make those?

2024-02-25 17:19 UTC, avdhoottt commented on content/dart/concepts/map/terms/putifabsent/putifabsent.md
> +Description: '.putifabsent() is used to insert a key-value pair into a map if the key is not already present. '
```suggestion
Description: 'Inserts a key-value pair into a map if the key is not already present.'
```

2024-02-25 17:19 UTC, avdhoottt commented on content/dart/concepts/map/terms/putifabsent/putifabsent.md
> +Title: '.putifabsent()'
```suggestion
Title: '.putIfAbsent()'
```

2024-02-25 17:19 UTC, avdhoottt commented on content/dart/concepts/map/terms/putifabsent/putifabsent.md
> +The .putifabsent() method in Dart is used to insert a key-value pair into a map if the key is not already present. If the key is already present, it does nothing and returns the existing value associ
```suggestion
The **`.putifabsent()`** method in Dart is used to insert a key-value pair into a map if the key is not already present. If the key is already present, it does nothing and returns the existing value associated with the key.
```

2024-02-25 17:19 UTC, avdhoottt commented on content/dart/concepts/map/terms/putifabsent/putifabsent.md
> +- `ifabsent`: A function that returns the value to be associated with the key if it is not already present in the map.
```suggestion
- `key`: The key to check for or add to the map.
- `ifAbsent`: A function that returns the value associated with the key if it is not already in the map.
```

2024-02-25 17:19 UTC, avdhoottt commented on content/dart/concepts/map/terms/putifabsent/putifabsent.md
> +
```suggestion
void main() {
  var map = {'key1': 1, 'key2': 2};
  // 'key3' is not present, so the value 3 will be provided by the ifAbsent function
  map.putIfAbsent('key3', () => 3); // {'key1': 1, 'key2': 2, 'key3': 3}
  // 'key1' is present, so the ifAbsent function is not invoked
  map.putIfAbsent('key1', () => 5); // Notice the output stays the same {'key1': 1, 'key2': 2, 'key3': 3}
  print(map); // output {'key1': 1, 'key2': 2, 'key3': 3}
}
```
The code had a missing bracket and the method must be called by its exact name as it is case-sensitive.

2024-02-25 17:19 UTC, avdhoottt commented on content/dart/concepts/map/terms/putifabsent/putifabsent.md
> +{'key1': 1, 'key2': 2, 'key3': 3}
```suggestion
{key1: 1, key2: 2, key3: 3}
```

2024-02-25 17:19 UTC, avdhoottt commented on content/dart/concepts/map/terms/putifabsent/putifabsent.md
> +```
```suggestion
```shell
```
The output block should be inside ` ```shell`.

2024-02-29 10:41 UTC, sambunyan commented
hello @avdhoottt I have made the suggested changes.

2024-03-02 16:52 UTC, avdhoottt approved these changes
PR is ready for the second review.

2024-03-15 11:31 UTC, ishg-153 requested changes
@sambunyan I have suggested some changes. Please make those and ping me once done.

2024-03-15 11:31 UTC, ishg-153 commented on content/dart/concepts/map/terms/putifabsent/putifabsent.md
> +In this example, the key 'key3' is not present in the map, so the ifAbsent function () => 3 is invoked to provide the value 3. The key 'key1' and 'key2' are present so the ifAbsent function is not in
```suggestion
In this example, the key `key3` is not present in the map, so the `ifAbsent()` function `() => 3` is invoked to provide the value 3. The keys `key1` and `key2` are present so the `ifAbsent()` function is not invoked and the existing values are returned.
```

2024-03-15 11:31 UTC, ishg-153 commented on content/dart/concepts/map/terms/putifabsent/putifabsent.md
> +}
```suggestion
void main() {
  var map = {'key1': 1, 'key2': 2};
  // 'key3' is not present, so the value 3 will be provided by the ifAbsent function
  map.putIfAbsent('key3', () => 3); // {'key1': 1, 'key2': 2, 'key3': 3}
  // 'key1' is present, so the ifAbsent function is not invoked
  print(map.putIfAbsent('key1', () => 5)); // Notice the output is the existing value associated with key1
  print(map); // output {'key1': 1, 'key2': 2, 'key3': 3}
}
```

It makes sense to show how the method returns the existing value of the key.

2024-03-15 11:31 UTC, ishg-153 commented on content/dart/concepts/map/terms/putifabsent/putifabsent.md
> +{key1: 1, key2: 2, key3: 3}
```suggestion
1
{key1: 1, key2: 2, key3: 3}
```

2024-03-15 11:56 UTC, sambunyan commented
@ishg-153 I have applied the suggested changes

2024-03-15 14:37 UTC, ishg-153 approved these changes
@sambunyan Great work! Ready to merge.

2024-03-15 17:38 UTC, merged