Java hashmap contains values entry
Codecademy/docs pull request #4411
Opened 2024-02-25 19:29 UTC by itskarelleh

### Description

A new entry for Java's HashMap method containsValue()

### Issue Solved 

Closes #4181 
### Type of Change

- Adding a new entry

### Checklist

- [ x ] All writings are my own.
- [ x ] My entry follows the Codecademy Docs style guide.
- [ x ] My changes generate no new warnings.
- [ x ] I have performed a self-review of my own writing and code.
- [ x ] I have checked my entry and corrected any misspellings.
- [ x ] I have made corresponding changes to the documentation if needed.
- [ x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-03-03 22:30 UTC, helfese approved these changes

2024-03-06 15:27 UTC, ishg-153 requested changes
@itskarelleh I have suggested some changes. Please read carefully and make all of the changes.

Let me know once done.

2024-03-06 15:27 UTC, ishg-153 commented on content/java/concepts/map/terms/containsValue/containsValue.md
> +The map method **containsValue()** is used to determine whether a map contains a given value. It returns a boolean value. The boolean value will return true if the map has one or more keys that map t
```suggestion
The **`.containsValue()`** method determines whether a map contains the given value. The method returns the boolean value `true` if the map has one or more keys that map to the given value and `false` if the map does not contain the given value.
```

2024-03-06 15:27 UTC, ishg-153 commented on content/java/concepts/map/terms/containsValue/containsValue.md
> +}
```suggestion
import java.util.HashMap;

public class FlowerInventory{
  public static void main(String[] args) {

    HashMap<String, Integer> inventory = new HashMap<String, Integer>();
    inventory.put("Roses", 10);
    inventory.put("Lillies", 5);
    inventory.put("Tulips", 1);

    System.out.println("Flowers that have a quantity of 10 is present? - " + inventory.containsValue(10));
    System.out.println("Flowers that have a quantity of 3 is present? - " + inventory.containsValue(0));
  }
}
```
Solved the error this code was throwing. Please remember to run you code as we want the code to be actually working.

2024-03-06 15:27 UTC, ishg-153 commented on content/java/concepts/map/terms/containsValue/containsValue.md
> +
```suggestion

The example below creates a hashmap for flowers, where the string represents its name and the integer represents the quantity. Then the integer is used with `.contiansValue()` as given below:

```

2024-03-06 15:27 UTC, ishg-153 commented on content/java/concepts/map/terms/containsValue/containsValue.md
> +```
After this add this:
The about of the above code block is:

Followed by the output inside of ` ```shell ``` ` block.
The output I received on running the working code is as follows:
Flowers that have a quantity of 10 is present? - true
Flowers that have a quantity of 3 is present? - false

2024-03-14 13:33 UTC, Sriparno08 approved these changes
Looks good 👍

2024-03-14 13:34 UTC, merged