[Term Entry] Dart Maps .remove()
Codecademy/docs pull request #4420
Opened 2024-02-27 00:11 UTC by dancikmad

### Description

- Added the List.remove() method for Dart

### Issue Solved

- Closes issue #4374 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-02-27 15:09 UTC, avdhoottt requested changes
Hey @dancikmad, I noticed that you have mentioned `list.remove()` method in the content, please change it to `map.remove()`. Ping me when you are done with it.

2024-02-27 15:09 UTC, avdhoottt commented on content/dart/concepts/map/terms/remove/remove.md
> +In Dart, the **`.remove()`** method is used to remove the first occurence of a specified value from the list. This method is useful when a particular element from a list has to be removed without kno
This entry is for Map concept so you need to write the content in reference to Maps. You have mentioned lists everywhere in the content, please replace it.

2024-02-27 15:28 UTC, dancikmad commented
@avdhoottt Hi, yeah I know. My mistake ... I realised this morning after I went through the doc again.
Will work on it today and replace and push the change. 
Thank you mate

2024-03-06 14:03 UTC, avdhoottt commented
Hey @dancikmad Are you working on this PR?

2024-03-06 14:06 UTC, dancikmad commented
@avdhoottt Yes, I have redone it, I will push the change later this evening. Sorry for the delay, been busy with a side project this week.

2024-03-10 18:10 UTC, avdhoottt commented
Hey @dancikmad, I think you have mistakenly committed `package.json` and `yarn.lock`. Please can you delete them from this PR?

2024-03-13 17:26 UTC, avdhoottt requested changes
Hey @dancikmad, please make these final changes!!

2024-03-13 17:26 UTC, avdhoottt commented on content/dart/concepts/map/terms/remove/remove.md
> +- `key`: The key of the entry to be removed from the map.
This line contains plagiarism, please change it.

2024-03-13 17:26 UTC, avdhoottt commented on content/dart/concepts/map/terms/remove/remove.md
> +}
```suggestion
void main() {
  Map<String, int> myMap = {'a': 1, 'b': 2, 'c': 3};
  print('Original Map: $myMap');
  // Removing an entry from the map
  myMap.remove('c');
  print('Map after removing entry with key "c": $myMap');
}
```
Code has some typos.

2024-03-13 17:26 UTC, avdhoottt commented on content/dart/concepts/map/terms/remove/remove.md
> +With this approach, the `.remove()` method removes the entry with the key `'c'` from the map and prints the updated map.
```suggestion
With this approach, the `.remove()` method removes the entry with the key `c` from the map and prints the updated map.
```

2024-03-13 17:26 UTC, avdhoottt commented on content/dart/concepts/map/terms/remove/remove.md
> +> **Note** If the specified key is not found in the map, the method returns `null`, and the map remains unchanged.
```suggestion
> **Note** If the specified key is not found in the map, it returns `null`, and the map remains unchanged.
```

2024-05-13 18:09 UTC, avdhoottt approved these changes
Looks good for the second review!!

2024-05-14 14:19 UTC, Sriparno08 approved these changes
Looks good! 👍

2024-05-14 14:20 UTC, merged