[Edit] C++: Methods
Codecademy/docs pull request #4423
Opened 2024-02-28 06:55 UTC by KTom101

### Description

A few errors were found in the C++: Methods code snippets. Fixing so it can run as-is.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-02-28 18:38 UTC, avdhoottt requested changes
Hey @KTom101, just a small change. Please can you look at it?

2024-02-28 18:38 UTC, avdhoottt commented on content/cpp/concepts/methods/methods.md
> +};
This is giving `Segmentation fault`. It's not fine, right?

2024-03-13 14:34 UTC, avdhoottt requested changes
I'll check up this PR.

2024-03-13 14:34 UTC, avdhoottt approved these changes
demo

2024-03-18 09:18 UTC, avdhoottt commented on content/cpp/concepts/methods/methods.md
> +    string set_name(string newName) {
```suggestion
    void set_name(string newName) {
```
`set_name` is not returning anything so we should keep it as it is.

2024-03-18 09:18 UTC, avdhoottt approved these changes
Looks good for the second review!!

2024-03-20 14:23 UTC, Sriparno08 approved these changes
Looks good 👍

2024-03-20 14:24 UTC, merged