Added descriptions and examples for font-style.
Codecademy/docs pull request #4429
Opened 2024-02-29 17:16 UTC by SarahCarlock

### Description

Added a description and method example for font-styles' normal, italic, oblique, inherit, and initial. Provided two images showing font-style used in an HTML document and it's output. 

### Issue Solved

- Closes issue #4416 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-02-29 17:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4429) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4429) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4429) it.</sub>

2024-03-01 15:20 UTC, ishg-153 requested changes
@SarahCarlock I have suggested changes. Please make them and let me know once done.

2024-03-01 15:20 UTC, ishg-153 commented on content/css/concepts/typography/terms/font-style/font-style.md
> +![font-styles visual examples.](https://github.com/SarahCarlock/codecademyDocs/assets/112113100/fcb3817f-86ac-47f5-a44e-386da8ad439a)
For this do the following things
- Move this to the end of the entry after all the examples.
- Change the link to this format: `https://raw.githubusercontent.com/Codecademy/docs/main/media/` followed by the image name. For this, you'll have to add your image to the media folder on this branch.

2024-03-01 15:20 UTC, ishg-153 commented on content/css/concepts/typography/terms/font-style/font-style.md
> +## Examples
```suggestion
## Example
```

2024-03-01 15:20 UTC, ishg-153 commented on content/css/concepts/typography/terms/font-style/font-style.md
> +### `normal`: text will be in it's basic design. This is the default style in Cascading Style Sheets (CSS).
```suggestion
`normal`: text will be in it's basic design. This is the default style in Cascading Style Sheets (CSS).
```

2024-03-01 15:20 UTC, ishg-153 commented on content/css/concepts/typography/terms/font-style/font-style.md
> +### `italic`: _text will be tilted, some characters will be replaced with a specialized tilted character (e.g. "a" to "ɑ" in the font Calibri)._
```suggestion
`italic`: text will be tilted, some characters will be replaced with a specialized tilted character (e.g. "a" to "ɑ" in the font Calibri).
```

2024-03-01 15:20 UTC, ishg-153 commented on content/css/concepts/typography/terms/font-style/font-style.md
> +### `oblique`: gives text a minor slant to the font without changing any characters. It is less supported and may not always be available.
```suggestion
`oblique`: gives text a minor slant to the font without changing any characters. It is less supported and may not always be available.
```

2024-03-01 15:20 UTC, ishg-153 commented on content/css/concepts/typography/terms/font-style/font-style.md
> +### `inherit`: text will take on the style used by the parent element.
```suggestion
`inherit`: text will take on the style used by the parent element.
```

2024-03-01 15:20 UTC, ishg-153 commented on content/css/concepts/typography/terms/font-style/font-style.md
> +### `initial`: sets the text font-style to it's default style, similar to `normal`.
```suggestion
`initial`: sets the text font-style to it's default style, similar to `normal`.
```

2024-03-01 16:19 UTC, SarahCarlock commented on content/css/concepts/typography/terms/font-style/font-style.md
> +![font-styles in html.](https://github.com/SarahCarlock/codecademyDocs/assets/112113100/4dce07d9-bd71-447c-94c6-d8468d66e150)
Removed

2024-03-04 16:27 UTC, SarahCarlock commented
@ishg-153 I've completed the changes requested.

2024-03-10 12:33 UTC, ishg-153 commented on content/css/concepts/typography/terms/font-style/font-style.md
> +![font-styles visual examples.](https://github.com/SarahCarlock/codecademyDocs/assets/112113100/fcb3817f-86ac-47f5-a44e-386da8ad439a)
Yep!

2024-03-10 12:41 UTC, ishg-153 approved these changes
@SarahCarlock I made some changes from my side. This is ready for second review!

2024-03-10 18:00 UTC, avdhoottt commented on content/css/concepts/typography/terms/font-style/font-style.md
> +`normal`: text will be in it's basic design. This is the default style in Cascading Style Sheets (CSS).
```suggestion
`normal`: The text will be in its basic design. This is the default style in Cascading Style Sheets (CSS).
```

2024-03-10 18:00 UTC, avdhoottt commented on content/css/concepts/typography/terms/font-style/font-style.md
> +`italic`: text will be tilted, and some characters will be replaced with a specialized tilted character (e.g. "a" to "ɑ" in the font Calibri).
```suggestion
`italic`: text will be tilted, and some characters will be replaced with a specialized tilted character (e.g. "a" to "ɑ" in the font `Calibri`).
```

2024-03-10 18:01 UTC, avdhoottt commented on content/css/concepts/typography/terms/font-style/font-style.md
> +`oblique`: gives text a minor slant to the font without changing any characters. It is less supported and may not always be available.
```suggestion
`oblique`: It gives text a minor slant to the font without changing any characters. It is less supported and may not always be available.
```

2024-03-10 18:01 UTC, avdhoottt commented on content/css/concepts/typography/terms/font-style/font-style.md
> +`normal`: text will be in it's basic design. This is the default style in Cascading Style Sheets (CSS).
```suggestion
`normal`: The text will be in it's basic design. This is the default style in Cascading Style Sheets (CSS).
```

2024-03-10 18:02 UTC, avdhoottt commented on content/css/concepts/typography/terms/font-style/font-style.md
> +`initial`: set the text `font-style` to its default style, similar to `normal`.
```suggestion
`inherit`: text will take on the style used by the parent element.

```css
p {
  font-style: inherit;
}
```

`initial`: Sets the text `font-style` to its default style, similar to `normal`.
```

2024-03-10 18:03 UTC, avdhoottt commented on content/css/concepts/typography/terms/font-style/font-style.md
> +`initial`: set the text `font-style` to its default style, similar to `normal`.
```suggestion
`initial`: Sets the text `font-style` to its default style, similar to `normal`.
```

2024-03-10 18:04 UTC, avdhoottt commented on content/css/concepts/typography/terms/font-style/font-style.md
> +`inherit`: text will take on the style used by the parent element.
```suggestion
`inherit`: The text will take on the style used by the parent element.
```

2024-03-10 18:04 UTC, avdhoottt approved these changes
LGTM!! Nice entry!!

2024-03-10 18:08 UTC, merged