EDIT: CSS overflow-y
Codecademy/docs pull request #4440
Opened 2024-03-05 03:52 UTC by Jamesllllllllll

### Description

I added an image that reflects the three examples given in the article. I also made one small grammatical correction.

### Issue Solved

Closes #4414 

### Type of Change

- Editing an existing entry (add image)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-03-05 17:29 UTC, avdhoottt approved these changes
Nice image!! Looks good for the second review.

2024-03-05 18:00 UTC, helfese approved these changes

2024-03-08 18:38 UTC, ishg-153 requested changes
@Jamesllllllllll One small change. Everything else looks good!

2024-03-08 18:38 UTC, ishg-153 commented on content/css/concepts/overflow/terms/overflow-y/overflow-y.md
> +Provide a scrollbar only if overflow contents exist.
```suggestion
Provide a scrollbar only if overflow content exists.
```
This sentence makes more sense to me.

2024-03-10 12:25 UTC, ishg-153 approved these changes
@Jamesllllllllll Good to merge!!

2024-03-10 12:31 UTC, merged