[Term Entry] Dart Queue .clear() #4457
Codecademy/docs pull request #4464
Opened 2024-03-14 16:25 UTC by NixDi

### Description

- Added a clear.md file. 
- Added content related to Dart Queue .clear() method.
- Closes issue #4457 

### Issue Solved

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-03-14 16:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4464) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4464) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4464) it.</sub>

2024-04-01 06:30 UTC, ishg-153 requested changes
@NixDi I have suggested some changes. Please make those and let me know once done.

2024-04-01 06:30 UTC, ishg-153 commented on content/dart/concepts/queue/terms/clear/clear.md
> +In [`Dart`](<[url](https://www.codecademy.com/resources/docs/dart)>), the **`.clear()`** method in [`Queue`](<[url](https://www.codecademy.com/resources/docs/dart/queue)>) removes all elements in the
```suggestion

In Dart, the **`.clear()`** method in Queue removes all elements in the queue. The size of the queue becomes zero.
```
It doesn't make sense to add those links as it is clear that this entry is under dart topic and queue concept.

2024-04-01 06:30 UTC, ishg-153 commented on content/dart/concepts/queue/terms/clear/clear.md
> +- removes all elements in the queue;
Remove this as it is redundant.

2024-04-01 06:30 UTC, ishg-153 commented on content/dart/concepts/queue/terms/clear/clear.md
> +- the method doesn't take any arguments.
Instead of writing this as points make it into a sentence.

2024-04-11 10:51 UTC, NixDi commented
@ishg-153 Thanks for your reply. I have made the changes as requested, please check.

2024-06-04 06:34 UTC, ishg-153 approved these changes
@NixDi I apologize for the delayed response. This entry is ready for a second review!

2024-06-09 09:12 UTC, letsbuildanything approved these changes
Looks good to be merged! 🚀

2024-06-09 09:15 UTC, merged