[Term Entry]Dart Queue .contains()
Codecademy/docs pull request #4470
Opened 2024-03-18 20:15 UTC by VeraLK

### Description

-Added contains.md file on the topic "Dart Queue .contains()"
-Fixed spelling mistakes spotted in contains.md file

### Issue Solved

### Type of Change

- Adding a new entry
- Editing my entry (fixing a typo)

### Checklist

- [ x] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-03-18 20:18 UTC, VeraLK commented
@avdhoottt sorry for the first try. I don't know where I made the mistake so it was empty but now I think I managed :) Thank you for your patience with me as it is for my first time to contribute :)

2024-03-23 14:28 UTC, avdhoottt commented on content/dart/concepts/queue/terms/contains/contains.md
> +The Dart **.contains()** method in the 'Queue' class is used to check if a specified element is present in the queue.
```suggestion
The **`.contains()`** method in Dart checks if a specified element is present in the given queue. 
```

2024-03-23 14:28 UTC, avdhoottt commented on content/dart/concepts/queue/terms/contains/contains.md
> +## Sintax:
```suggestion
## Syntax
```
Typo here.

2024-03-23 14:34 UTC, avdhoottt requested changes
Hey @VeraLK, I have suggested some changes, please make them.

2024-03-23 14:34 UTC, avdhoottt commented on content/dart/concepts/queue/terms/contains/contains.md
> +The syntax for this method is as follows:
```suggestion
```
We don't need this line so better to remove it.

2024-03-23 14:34 UTC, avdhoottt commented on content/dart/concepts/queue/terms/contains/contains.md
> +- `element`: The element is the object that needs to be checked in the queue.
```suggestion

- `element`: It is the object that needs to be checked in the queue.
```
Give one line space before and after a heading/codeblock.

2024-03-23 14:34 UTC, avdhoottt commented on content/dart/concepts/queue/terms/contains/contains.md
> +## Example-1:
```suggestion
## Example 1
```

2024-03-23 14:34 UTC, avdhoottt commented on content/dart/concepts/queue/terms/contains/contains.md
> +print(queue.contains(3)); // Output will be true
```suggestion
import 'dart:collection';

void main() {
  var queue = Queue();
  queue.addAll([1, 2, 3, 4, 5]);
  print(queue.contains(3)); 
}
```
You need to import the collection library and wrap the code inside the main function.

2024-03-23 14:34 UTC, avdhoottt commented on content/dart/concepts/queue/terms/contains/contains.md
> +This method returns `true` if the element is found in the queue, otherwise it returns `false`.
```suggestion

This method returns `true` if the element is found in the queue, otherwise it returns `false`.
```
Add the output block here too.

2024-03-23 14:34 UTC, avdhoottt commented on content/dart/concepts/queue/terms/contains/contains.md
> +## Example-2:
```suggestion
## Example 2
```

2024-03-23 14:34 UTC, avdhoottt commented on content/dart/concepts/queue/terms/contains/contains.md
> +print(names.contains('Bob')); // Output will be true
```suggestion
import 'dart:collection';

void main() {
  var names = Queue<String>();
  names.addAll(['Alice', 'Bob', 'Charlie', 'David']);
  print(names.contains('Bob')); 
}
```

2024-03-23 14:34 UTC, avdhoottt commented on content/dart/concepts/queue/terms/contains/contains.md
> +
Add the output block.

2024-03-23 14:34 UTC, avdhoottt commented on content/dart/concepts/queue/terms/contains/contains.md
> +
Remove these unnecessary spaces from the content.

2024-03-23 15:35 UTC, VeraLK commented
Hey @avdhoottt I've tried to make the suggested changes. Can you review it again as I wasn't sure how exactly to do it so please check it :)

2024-05-05 17:00 UTC, avdhoottt commented on content/dart/concepts/queue/terms/contains/contains.md
> +The output of the above is:
```suggestion
The output of the above code is:
```

2024-05-06 14:52 UTC, avdhoottt approved these changes
LGTM!!

2024-05-06 14:56 UTC, avdhoottt commented on content/dart/concepts/queue/terms/contains/contains.md
> +  -'paths/computer-science'
```suggestion
Title: '.contains()'
Description: 'Checks if a specified element is present in the queue.'
Subjects: 
  - 'Code foundations'
  - 'Computer science'
Tags: 
  - 'Dart'
  - 'Concepts'
  - 'Queue'
CatalogContent: 
  - 'learn-dart'
  - 'paths/computer-science'
```

2024-05-06 15:00 UTC, merged