[Term Entry] Python: NumPy built-in-functions Matrix Trace #4480
Codecademy/docs pull request #4493
Opened 2024-03-26 00:21 UTC by adrianna-yixin

Create .trace() term for numpy built-in-function

### Description

- Added the numpy.trace() term for Python
- Closes Issue #4480 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-03-26 00:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4493) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4493) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4493) it.</sub>

2024-03-26 18:14 UTC, mohitO12-dev commented on content/numpy/concepts/built-in-functions/terms/trace/trace.md
> +Title: '.trace()'
Instead of  ".trace()" we can use "numpy.trace()" to indicate the exact meaning of NumPy's trace functions used.

2024-03-26 18:57 UTC, mohitO12-dev requested changes

2024-03-26 18:57 UTC, mohitO12-dev commented on content/numpy/concepts/built-in-functions/terms/trace/trace.md
> +Title: '.trace()'
Instead of  ".trace()" we can use "numpy.trace()" to indicate the exact many of NumPy's trace functions used.

2024-03-26 18:57 UTC, mohitO12-dev commented on content/numpy/concepts/built-in-functions/terms/trace/trace.md
> +Tags:
- 'Arrays'
  - 'AI'
  - 'Machine Learning'
  - 'Math'
  - 'NumPy'
We can utilize AI tagging as well, as it, along with machine learning, aids in predicting various mathematical analyses of graph matrices in artificial intelligence.

2024-03-26 18:57 UTC, mohitO12-dev commented on content/numpy/concepts/built-in-functions/terms/trace/trace.md
> +np.trace(matrix, offset=1, dtype=float, out=result_array)
```suggestion
result_array[0] = np.trace(matrix, offset=1, dtype=float)

```

2024-03-26 18:57 UTC, mohitO12-dev commented on content/numpy/concepts/built-in-functions/terms/trace/trace.md
> +np.trace(matrix, offset=1, dtype=float, out=result_array)
The np.trace() function is not being used correctly.

The correct way to calculate the trace with specified parameters and store the result in an output array, would be to assign the result of np.trace() to result_array respectively.

2024-03-26 18:57 UTC, mohitO12-dev commented on content/numpy/concepts/built-in-functions/terms/trace/trace.md
> +```
The codebyte example results in the following output:
```shell
Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace with offset 1: 8
```

The code calculates the trace of a 3x3 matrix with an offset of 1, storing the result in an output array and printing the matrix along with the trace.

2024-03-26 18:57 UTC, mohitO12-dev commented on content/numpy/concepts/built-in-functions/terms/trace/trace.md
> +```
The above output is generated by codebyte.

2024-03-27 17:17 UTC, adrianna-yixin commented
Hi @mohitO12-dev, I've resolved the four requested changes, please have a look and I look forward to your further review.

2024-03-27 17:27 UTC, adrianna-yixin commented on content/numpy/concepts/built-in-functions/terms/trace/trace.md
> +Title: 'numpy.trace()'
Hi @dakshdeepHERE , I did not include "numpy" at first, but @mohitO12-dev requested this change. So... now I'm sure whether I should keep it or not.

2024-03-27 17:30 UTC, adrianna-yixin commented on content/numpy/concepts/built-in-functions/terms/trace/trace.md
> +The above output is generated by codebyte.
Hi, @dakshdeepHERE, again this is requested by @mohitO12-dev. Should I just delete this output block, then?

2024-03-27 17:44 UTC, adrianna-yixin commented
Hi @dakshdeepHERE, I've resolved the changes you requested, please have a look.

2024-03-27 17:54 UTC, mohitO12-dev approved these changes

2024-03-27 17:54 UTC, mohitO12-dev commented on content/numpy/concepts/built-in-functions/terms/trace/trace.md
> +Title: 'numpy.trace()'
@adrianna-yixin you can remove this, please.
```suggestion
Title: '.trace()'
```

2024-03-27 17:54 UTC, mohitO12-dev commented on content/numpy/concepts/built-in-functions/terms/trace/trace.md
> +
@adrianna-yixin  please add some introductory sentence.

2024-03-27 17:54 UTC, mohitO12-dev commented on content/numpy/concepts/built-in-functions/terms/trace/trace.md
> +The above output is generated by codebyte.
@adrianna-yixin  yeah please delete.

2024-03-27 17:55 UTC, mohitO12-dev approved these changes

2024-03-27 17:56 UTC, mohitO12-dev approved these changes

2024-03-27 17:56 UTC, mohitO12-dev approved these changes

2024-03-27 17:57 UTC, mohitO12-dev approved these changes

2024-03-27 17:58 UTC, mohitO12-dev approved these changes

2024-03-27 17:58 UTC, mohitO12-dev approved these changes

2024-03-27 17:58 UTC, mohitO12-dev approved these changes

2024-03-27 17:59 UTC, mohitO12-dev approved these changes

2024-03-27 18:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4493) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4493) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: adrianna-yixin<br/>:x: mohitO12-dev<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4493) it.</sub>

2024-03-29 15:49 UTC, adrianna-yixin commented
Hi @mohitO12-dev, would you please sign the Contributor License Agreement so this thread can be accepted? Or is there anything that I still need to work on? Please update me whenever thank you :)

2024-04-02 15:53 UTC, adrianna-yixin commented
Hi @dakshdeepHERE, I noticed that Push / ci (format:verify) (pull_request) failed. Is there anything I could do about it? Or I leave it as it is?

2024-04-24 14:04 UTC, mohitO12-dev approved these changes
Approved.

2024-04-24 14:06 UTC, mohitO12-dev approved these changes
Approved changes

2024-07-02 18:57 UTC, ishg-153 commented
@dakshdeepHERE is this ready to merge?

2024-08-12 20:21 UTC, closed without merging