[Term Entry] Python: NumPy built-in-functions Variance
Codecademy/docs pull request #4496
Opened 2024-03-27 02:29 UTC by luca1iu

### Description

- Added the NumPy built-in-functions numpy.var() term
- Closed Issue #4476 

### Issue Solved

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-03-27 02:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4496) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4496) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4496) it.</sub>

2024-04-02 13:38 UTC, Sriparno08 reviewed
Hey @luca1iu, thanks for contributing to Codecademy!

I've listed all the modifications that you need to make in your entry below:

2024-04-02 13:38 UTC, Sriparno08 commented on content/numpy/concepts/built-in-functions/terms/variance/variance.md
> +The `.var()` function compute the variance of the given data (array elements) along the specified axis(if any). This value represents the average of the squared differences from the mean and provides
```suggestion
The `.var()` [function](https://www.codecademy.com/resources/docs/numpy/built-in-functions) computes the variance of the elements of an array along the specified axis (if any). This value represents the average of the squared differences from the mean and provides a measure of how spread out the elements are in the array.
```

2024-04-02 13:38 UTC, Sriparno08 commented on content/numpy/concepts/built-in-functions/terms/variance/variance.md
> +Where `array` is the input array for which the variance needs to be calculated. `axis (optional)` specifies the axis along which the variance is calculated. If `axis` is not provided, the variance is
```suggestion
- `array`: The array for which the variance is to be calculated.
- `axis`: An optional parameter that specifies the axis along which the variance is to be calculated.

If `axis` is not provided, the variance is calculated for the entire array. If `axis` is specified, then the variance is calculated along that axis. For a 2D array, if `axis=0`, the variance is calculated column-wise and if `axis=1`, the variance is calculated row-wise.
```

2024-04-02 13:38 UTC, Sriparno08 commented on content/numpy/concepts/built-in-functions/terms/variance/variance.md
> +The example below creates a 2D array and calculates the overall variance, column-wise variance, and row-wise variance.
```suggestion
The below example creates a 2D array and calculates the overall variance, column-wise variance, and row-wise variance of the array using the `.var()` function:
```

2024-04-02 13:38 UTC, Sriparno08 commented on content/numpy/concepts/built-in-functions/terms/variance/variance.md
> +# the variance of the entire array
```suggestion
# Calculating the overall variance
```

2024-04-02 13:38 UTC, Sriparno08 commented on content/numpy/concepts/built-in-functions/terms/variance/variance.md
> +# the variance along axis=0 (column-wise)
```suggestion
# Calculating the column-wise variance (axis=0)
```

2024-04-02 13:38 UTC, Sriparno08 commented on content/numpy/concepts/built-in-functions/terms/variance/variance.md
> +# the variance along axis=1 (row-wise)
```suggestion
# Calculating the row-wise variance (axis=1)
```

2024-04-02 15:24 UTC, Sriparno08 approved these changes
Good job, @luca1iu!

This looks good for a second review 👍

2024-04-22 13:14 UTC, letsbuildanything requested changes
@luca1iu 
I've listed below some changes. Please make them as soon as possible.

2024-04-22 13:14 UTC, letsbuildanything commented on content/numpy/concepts/built-in-functions/terms/variance/variance.md
> +The below example creates a 2D array and calculates the overall variance, column-wise variance, and row-wise variance of the array using the `.var()` function:
```suggestion
The following example creates a 2D array and calculates the overall variance (variance of the flattened array), column-wise variance, and row-wise variance of the array using the `.var()` function:
```

2024-04-22 13:14 UTC, letsbuildanything commented on content/numpy/concepts/built-in-functions/terms/variance/variance.md
> +print(variance_axis_1)
```suggestion
import numpy as np

# Creating a 2D array
array_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

# Calculating the overall variance
overall_variance = np.var(array_2d)
print(overall_variance)

# Calculating the column-wise variance (axis=0)
column_variance = np.var(array_2d, axis=0)
print(column_variance)

# Calculating the row-wise variance (axis=1)
row_variance = np.var(array_2d, axis=1)
print(row_variance)
```

2024-04-23 08:24 UTC, letsbuildanything approved these changes
LGTM! 🚀

2024-04-23 08:28 UTC, merged