Concept entry dart loops. Adresses issue #4249
Codecademy/docs pull request #4499
Opened 2024-03-29 09:01 UTC by kamlesh-ops

### Description

### Issue Solved

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-03-29 09:11 UTC, kamlesh-ops commented
Hello there.
I was unaware that this issue was assigned and I got busy in other tasks. I deeply regret the inconvenience.
I have made the pr. Please give it a review and ping me if there are any issues.

2024-04-02 17:33 UTC, letsbuildanything requested changes
@kamlesh-ops I've listed below some changes. Please make them ASAP.
Also, When referring to elements as they appear in code (properties, methods, functions, commands, expressions, etc.), use backticks i.e. `for` instead of double quotes("for").

2024-04-02 17:33 UTC, letsbuildanything commented on content/dart/concepts/loops/loops.md
> +The for-each loop iterates over all elements in some container/collectible and passes the elements to some specific function.
```suggestion
The forEach loop iterates over all elements in a container or collection and invokes a specified function for each element.
```

2024-04-02 17:33 UTC, letsbuildanything commented on content/dart/concepts/loops/loops.md
> +#### Syntax
```suggestion
### Syntax
```

2024-04-02 17:33 UTC, letsbuildanything commented on content/dart/concepts/loops/loops.md
> +#### Example
```suggestion
### Example
```

2024-04-02 17:33 UTC, letsbuildanything commented on content/dart/concepts/loops/loops.md
> +The while loop executes a block of code until the given condition is false. It is more beneficial when we don't know the number of executions.
Using pronouns is not allowed. Remove 'we' and refine the definition.

2024-04-02 17:33 UTC, letsbuildanything commented on content/dart/concepts/loops/loops.md
> +#### Syntax
```suggestion
### Syntax
```

2024-04-02 17:33 UTC, letsbuildanything commented on content/dart/concepts/loops/loops.md
> +## do...while Loop
```suggestion
## do-while Loop
```

2024-04-02 17:33 UTC, letsbuildanything commented on content/dart/concepts/loops/loops.md
> +The do…while loop is similar to the while loop but only difference is that it executes the loop statement and then check the given condition. Hence the block of code inside the loop gets executed atl
```suggestion
The do-while loop is similar to the `while` loop, with the key difference being that it executes the loop statement before checking the given condition. Therefore, the block of code inside the loop is guaranteed to execute at least once
```

2024-04-02 17:33 UTC, letsbuildanything commented on content/dart/concepts/loops/loops.md
> +#### Syntax
```suggestion
### Syntax
```

2024-04-02 17:33 UTC, letsbuildanything commented on content/dart/concepts/loops/loops.md
> +#### Example
```suggestion
### Example
```

2024-04-02 17:33 UTC, letsbuildanything commented on content/dart/concepts/loops/loops.md
> +  nums.forEach((var num)=> print(num));
Using parameter name 'num' raise an issue. rename it!

2024-05-13 16:57 UTC, letsbuildanything commented
@kamlesh-ops It's been more than a month since the request was made. Please proceed with implementing all the suggested modifications.
Thank you!

2024-05-14 15:03 UTC, kamlesh-ops commented
@letsbuildanything I am extremely sorry for the delay. I have made the changes. Please review. 
Thank you!

2024-05-16 05:05 UTC, letsbuildanything approved these changes
@kamlesh-ops Thank you for making the changes. It seems ready for the next review!

2024-05-18 17:07 UTC, mohitO12-dev approved these changes
Approved

2024-05-18 17:08 UTC, merged