Determinant.md Pull Request first revision
Codecademy/docs pull request #4505
Opened 2024-04-01 16:27 UTC by boffskbob

Created numpy determinant markdown file and folder, completed first revision of determinant.md

### Description

### Issue Solved

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-04-01 16:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4505) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4505) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4505) it.</sub>

2024-04-02 12:26 UTC, letsbuildanything requested changes
@boffskbob I've suggested a few changes. Please make them.
Please remove any trailling spaces after punctuation. Otherwise, You did a great job!

2024-04-02 12:26 UTC, letsbuildanything commented on content/numpy/concepts/built-in-functions/terms/determinant/determinant.md
> + - `array` : The numpy array_like object to compute the determinant for
```suggestion
- `array` : The numpy array-like object for which the determinant is computed.
```

2024-04-02 12:26 UTC, letsbuildanything commented on content/numpy/concepts/built-in-functions/terms/determinant/determinant.md
> +The following example creates multiple numpy arrays then computes and returns the respective determinants.
```suggestion
The following examples demonstrate the use of `.det()` method:
```

2024-04-02 12:26 UTC, letsbuildanything commented on content/numpy/concepts/built-in-functions/terms/determinant/determinant.md
> +print(det_c)
```suggestion
mat_2x2 = np.array([[1, 2], [3, 4]])
det_mat_2x2 = np.linalg.det(mat_2x2)
print("Determinant of 2 x 2 matrix:", det_mat_2x2)  # prints output approx. -2.0

mat_3x3 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
det_mat_3x3 = np.linalg.det(mat_3x3)
print("Determinant of 3 x 3 matrix:", det_mat_3x3) # prints output approx. 1.0
```

2024-04-02 12:26 UTC, letsbuildanything commented on content/numpy/concepts/built-in-functions/terms/determinant/determinant.md
> +1.0
```suggestion
Determinant of 2 x 2 matrix: -2.0000000000000004
Determinant of 3 x 3 matrix: 0.9999999999999964
```

2024-04-02 12:26 UTC, letsbuildanything commented on content/numpy/concepts/built-in-functions/terms/determinant/determinant.md
> +```
Please add one codebyte example here.

2024-04-08 00:38 UTC, boffskbob commented
@letsbuildanything revisions have been made!

2024-04-10 18:24 UTC, letsbuildanything approved these changes

2024-04-12 15:55 UTC, Sriparno08 approved these changes
Looks good 👍

2024-04-12 15:56 UTC, merged