[Concept Entry] Python Deque Deque #4452
Codecademy/docs pull request #4511
Opened 2024-04-07 17:10 UTC by Aquacoder345

### Description

- Added the Concept Entry Python Deque

### Issue Solved

- Closes #4452 

### Type of Change

- Adding a new entry

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-04-07 17:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4511) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4511) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4511) it.</sub>

2024-04-10 11:36 UTC, letsbuildanything requested changes
@Aquacoder345 I've requested some changes below. Please make them ASAP.

2024-04-10 11:36 UTC, letsbuildanything commented on content/python/concepts/deque/deque.md
> +The pop() and popleft() methods remove items from the corresponding ends. The rotate() method moves elements from one end to the other, effectively rotating the deque.
```suggestion
```

2024-04-10 11:36 UTC, letsbuildanything commented on content/python/concepts/deque/deque.md
> +The pop() and popleft() methods remove items from the corresponding ends. The rotate() method moves elements from one end to the other, effectively rotating the deque.
The description of these methods is not required here. In the future, they will be added as term entries.

2024-04-10 11:36 UTC, letsbuildanything commented on content/python/concepts/deque/deque.md
> +## Using deque
```suggestion
## Example
```

2024-04-10 11:36 UTC, letsbuildanything commented on content/python/concepts/deque/deque.md
> +The back() method pops from the history and pushes onto the forward stack, while the forward() method does the opposite.
Below are the following changes or suggestion to be made here:
- explain use of `deque` object with easy to understand and beginner-friendly code. for example, using simple array of numbers or objects.
- Write Concrete code. for example in your case, you haven't mentioned `import` statement. (`from collections import deque`)
- Write all the runnable code inside triple backticks (```).
- For output, use ` ```shell` not ` ```Popping`. To learn more about this, you can visit [Style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md)

2024-04-10 12:07 UTC, letsbuildanything requested changes

2024-04-10 12:07 UTC, letsbuildanything commented on content/python/concepts/deque/deque.md
> +- Queues: To implement a queue, you would use the append() method to enqueue items at the back and the popleft() method to dequeue items from the front.
- use backticks i.e. \`append()\`,  for methods, properties, variables, etc. 
- Avoid using pronouns like `you`, `we`, etc
- Lastly, make all the necessary changes you deem appropriate here.

2024-04-23 06:44 UTC, letsbuildanything commented
@Aquacoder345 
you've committed changes to the `package.json` and `yarn.lock` files. Please remove these changes.

2024-04-23 19:14 UTC, Aquacoder345 commented
@letsbuildanything I believe I found and delete the changes made to the package.json. To my knowledge I did not make any manual changes to the yarn.lock file, are you able to assist me with finding what changes I made to yarn.lock.

2024-05-26 10:30 UTC, letsbuildanything commented
Hey @Aquacoder345,
I’ve reverted the changes in the `yarn.lock` file. Could you please update your contribution file to ensure it aligns with Codecademy's contribution guidelines? Additionally, make sure to review and follow our [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md).

Thank you!

2024-05-27 15:30 UTC, Aquacoder345 commented
Thank you @letsbuildanything. I will get this resolved as soon as i possible can.

2024-06-04 05:45 UTC, letsbuildanything commented
@Aquacoder345 It's been a week since the request was made. Please make the necessary changes as soon as possible.
Thank you!

2024-06-04 15:12 UTC, Aquacoder345 commented
@letsbuildanything I am in the process of moving and will get these changes made. apology in getting these changes completed.

2024-06-10 16:21 UTC, letsbuildanything commented
@Aquacoder345, please ensure you close an existing PR before opening a new one for the same issue. 
since you've opened a similar new [PR#4759](https://github.com/Codecademy/docs/pull/4759), I am closing this PR.

2024-06-10 16:21 UTC, closed without merging