[Term Entry] Python:NumPy built-in-functions .median()
Codecademy/docs pull request #4516
Opened 2024-04-15 16:06 UTC by HalfEatenApple

### Description

- Added the numpy.median() term for NumPy
- Closes issue #4472 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-04-15 16:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4516) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4516) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4516) it.</sub>

2024-04-16 08:21 UTC, mamtawardhani requested changes
@HalfEatenApple The entry was nicely written!

However, there were some minor changes required, I have made some suggestions and comments wherever the changes are required, please make those changes at your earliest convenience.

2024-04-16 08:21 UTC, mamtawardhani commented on content/numpy/concepts/built-in-functions/terms/median/median.md
> +The following example creates a 2-dimensional array composed of random integers (between 1 and 20). Then uses `.median()` to calculate the median, with various values of the `axis` parameter.
```suggestion
The following example creates a 2-dimensional array of random integers (between 1 and 20) and calculates the median using `.median()`, demonstrating different uses of the `axis` parameter.
```

2024-04-17 06:47 UTC, mamtawardhani approved these changes

2024-04-17 15:46 UTC, Sriparno08 reviewed
Hey @HalfEatenApple, I've listed all the modifications from my side that you need to make in your entry below:

2024-04-17 15:46 UTC, Sriparno08 commented on content/numpy/concepts/built-in-functions/terms/median/median.md
> +- `keepdims`: (Default = False) A boolean; if `True` will keep reduced axes in the result as dimensions with size one.
````suggestion
```pseudo
numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)
```

- `a`: The array of elements to calculate the median from.
- `axis`: The axis or axes along which to calculate the median. By default, it considers the array to be flattened (works on all axes). `axis=0` works along the column and `axis=1` works along the row.
- `out`: A different array to place the result. It must have the same shape as the expected result.
- `overwrite_input`: A parameter which, if `True`, allows memory usage of the array for calculations.
- `keepdims`: A parameter which, if `True`, keeps reduced axes in the result as dimensions with size one.

> **Note:** The `a` parameter is the only required parameter for this function. All other parameters are optional.
````

2024-04-17 15:46 UTC, Sriparno08 commented on content/numpy/concepts/built-in-functions/terms/median/median.md
> +The following example creates an array then applies a few `.median()` operations, and returns each result to the console.
```suggestion
The following example creates an array, then applies a few `.median()` operations, and returns each result to the console:
```

2024-04-17 15:46 UTC, Sriparno08 commented on content/numpy/concepts/built-in-functions/terms/median/median.md
> +#computes the median along the horizontal axis (row) of the array
```suggestion
# Computes the median of the entire array

print(np.median(a, axis=0))
# Computes the median along the vertical axis (column) of the array

print(np.median(a, axis=1))
# Computes the median along the horizontal axis (row) of the array
```

2024-04-17 15:46 UTC, Sriparno08 commented on content/numpy/concepts/built-in-functions/terms/median/median.md
> +The following example creates a 2-dimensional array of random integers (between 1 and 20) and calculates the median using `.median()`, demonstrating different uses of the `axis` parameter.
```suggestion
The following example creates a 2-dimensional array of random integers (between 1 and 20) and calculates the median using `.median()`, demonstrating different uses of the `axis` parameter:
```

2024-04-17 15:46 UTC, Sriparno08 commented on content/numpy/concepts/built-in-functions/terms/median/median.md
> +print("The median along the horizontal axis (axis = 1) with keepdims = True is:")
```suggestion
print("The median along the vertical axis (axis=0) is:")
print(np.median(randarr, axis=0))

print("The median along the horizontal axis (axis=1) is:")
print(np.median(randarr, axis=1))

print("The median along the horizontal axis (axis=1) with 'keepdims=True' is:")
```

2024-05-01 13:55 UTC, Sriparno08 approved these changes
Looks good 👍

2024-05-01 13:56 UTC, merged