Created the structure and content for Dart Strings length method
Codecademy/docs pull request #4539
Opened 2024-04-16 16:29 UTC by PaulNica

### Description

- Added a new entry length.md file on the topic "Dart String .length()"
- Closes issue https://github.com/Codecademy/docs/issues/4376

### Issue Solved

- Adding a new entry

### Checklist

- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-04-16 16:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4539) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4539) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4539) it.</sub>

2024-04-17 10:57 UTC, letsbuildanything requested changes
@PaulNica, Thanks for your great work on this file! 
I've listed some changes below. Could you please review and make them?

2024-04-17 10:57 UTC, letsbuildanything commented on content/dart/concepts/strings/terms/length/length.md
> +Here is an example of how to use `length` in Dart:
```suggestion
The following example demonstrates the use of `.length` property:
```

2024-04-17 10:57 UTC, letsbuildanything commented on content/dart/concepts/strings/terms/length/length.md
> +}
```suggestion
void main() {
  String firstString = "I love Codecademy";
  String secondString = "I love Codecademy😍";

  int lengthOfFirstString = firstString.length;
  int lengthOfSecondString = secondString.length;

  print(lengthOfFirstString);
  print(lengthOfSecondString);
}
```

2024-04-17 10:57 UTC, letsbuildanything commented on content/dart/concepts/strings/terms/length/length.md
> +17
```suggestion
17
19
```

2024-04-17 10:57 UTC, letsbuildanything commented on content/dart/concepts/strings/terms/length/length.md
> +
```suggestion

> **Note:** The emoji `😍` takes 2 UTF-16 units.

```

2024-04-17 10:57 UTC, letsbuildanything commented on content/dart/concepts/strings/terms/length/length.md
> +
```suggestion
```

2024-04-17 10:57 UTC, letsbuildanything commented on content/dart/concepts/strings/terms/length/length.md
> +## Example
```suggestion
## Examples
```

2024-04-17 10:57 UTC, letsbuildanything commented on content/dart/concepts/strings/terms/length/length.md
> +The `length` of an empty string will always be zero:
```suggestion
The following example computes the length of an empty string:
```

2024-04-17 10:57 UTC, letsbuildanything commented on content/dart/concepts/strings/terms/length/length.md
> +```
Add here an output block of the above code.

2024-04-17 10:57 UTC, letsbuildanything commented on content/dart/concepts/strings/terms/length/length.md
> +   print(len); // Output: 0
```suggestion
   String emptyString = "";
   int lengthOfEmptyString = emptyString.length;
   print(lengthOfEmptyString);
```

2024-04-17 12:33 UTC, PaulNica reviewed
Hi @letsbuildanything,

I have made the requested changes. As this is my first-ever contribution I am not sure what the correct way to proceed with the review, so if I did anything wrong or I should've done something different, any feedback would greatly help.

2024-04-17 13:24 UTC, letsbuildanything commented
@PaulNica Please commit all the suggestion and add output(```shell) block for the last example as suggested.

2024-04-17 13:49 UTC, letsbuildanything approved these changes
@PaulNica you did a great job! 
It seems ready for next review.

2024-04-19 16:11 UTC, Sriparno08 approved these changes
Looks good! 👍

2024-04-19 16:12 UTC, merged