Create comments.md under postgresql
Codecademy/docs pull request #4540
Opened 2024-04-16 17:49 UTC by thiennguyen93

### Description

### Issue Solved

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [ x I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-04-16 18:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4540) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4540) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4540) it.</sub>

2024-04-16 18:17 UTC, thiennguyen93 commented
CLA has been signed. However, license/cla is still pending

2024-04-18 10:04 UTC, letsbuildanything commented
@thiennguyen93, it appears that you've submitted this PR using two accounts. Therefore, please sign this CLA with both of your accounts, or alternatively, close this and resubmit a new PR using only a single account.

2024-04-18 16:11 UTC, thiennguyen93 commented
Everything is good know

2024-04-18 16:14 UTC, thiennguyen93 commented
@letsbuildanything Please help me review this one

2024-04-24 12:25 UTC, letsbuildanything requested changes
@thiennguyen93, Thank you for contributing to the Codecademy docs!
I've requested below few changes. Please make them as soon as possible.

2024-04-24 12:25 UTC, letsbuildanything commented on content/postgresql/concepts/comments/comments.md
> +**Comments** are text placed inside code that is not executed. They are intended as documentation or explanation of the code they are a part of.
```suggestion
In PostgreSQL, **comments** are annotations added to SQL code to provide information about the code without affecting its execution. They are primarily used for documentation purposes and enhancing code readability. Comments in PostgreSQL can be single-line or multi-line and are initiated with -- for single-line comments and /* */ for multi-line comments.
```

2024-04-24 12:25 UTC, letsbuildanything commented on content/postgresql/concepts/comments/comments.md
> +- Single-line comments start with `--` and end at the end of the line.
```suggestion
Single-line comment:
```

2024-04-24 12:25 UTC, letsbuildanything commented on content/postgresql/concepts/comments/comments.md
> +- Multi-line comments start with `/*` and end with `*/`.
```suggestion
Multi-line comment:
```

2024-04-24 12:25 UTC, letsbuildanything commented on content/postgresql/concepts/comments/comments.md
> +Here's an example of how you can use comments in PostgreSQL:
Avoid using first and second-person pronouns, i.e. "you", "I", and "we".

2024-04-24 12:25 UTC, letsbuildanything commented on content/postgresql/concepts/comments/comments.md
> +```
Here, you should utilize single-line or multi-line comments to explain the given code. Remove these `single-line` or `multi-line` keyword comments and add the necessary comments.

2024-04-24 12:25 UTC, letsbuildanything commented on content/postgresql/concepts/comments/comments.md
> +In the above example, comments are used to describe what the following SQL statement does. The PostgreSQL compiler will ignore these comments when executing the SQL code.
Use a `Note` to inform the reader of points of potential confusion or to warn of potential pitfalls.
ex: `> **Note:** Note Text.`

2024-05-10 15:44 UTC, thiennguyen93 commented
@letsbuildanything Thank you for your code reviews. I have made some changes to fix all.
Thank again.

2024-05-13 16:49 UTC, letsbuildanything approved these changes
@thiennguyen93 
It seems ready for the next review.

2024-05-14 07:04 UTC, mamtawardhani approved these changes
@thiennguyen93 Thank you for contributing to Codecademy Docs!

The entry looks good to me.

2024-05-14 07:07 UTC, merged