Added PostgreSQL Constants Concept
Codecademy/docs pull request #4543
Opened 2024-04-18 18:26 UTC by Dan-Tyas

### Description

 Added a folder named "PostgreSQL" with a file named "Constants" into the Codecademy/Docs Folder. I have also made an edit to the tags.md file and added the tag "Constants".

### Issue Solved

#4533 - [Concept Entry] PostgreSQL constants 

### Type of Change

- Adding a new entry
- Editing an existing entry
- Updating the documentation

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-04-18 18:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4543) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4543) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4543) it.</sub>

2024-04-24 15:14 UTC, raditya1117 requested changes
This is a good first attempt. Although the content needs restructuring, the foundations have been done well. Thank you, @Dan-Tyas , for this contribution. Could you please check the review comments and make changes accordingly so that we can move ahead?

2024-06-18 19:48 UTC, ishg-153 commented
@Dan-Tyas Please make the suggested changes.

**Note:** If you don't respond with the changes within a week, this PR will be closed and its corresponding issue will be unassigned from you.

2024-09-21 07:18 UTC, Sriparno08 commented
Closing this PR since the author is inactive.

2024-09-21 07:18 UTC, closed without merging