Create insert
Codecademy/docs pull request #4550
Opened 2024-04-20 18:46 UTC by MartinLBeacham

### Description

Add insert.md as a New Term for Existing Concept Entry.

### Issue Solved

Closes [#4521](https://github.com/Codecademy/docs/issues/4521).

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-04-20 18:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4550) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4550) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4550) it.</sub>

2024-04-22 10:22 UTC, mamtawardhani requested changes
Hey @MartinLBeacham 

Thank you for your contribution at Codecademy!
The entry was nicely written!

I've mentioned a few comments and suggestions for this entry, could you please review them and make the required changes at your earliest convenience? 
Thanks!

2024-04-22 10:22 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/insert/insert.md
> +```
Please add the printed statement "Further Updated Test Results:" at the start of the code.

2024-04-22 10:22 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/insert/insert.md
> +## Codebyte Example (if applicable)
```suggestion
## Codebyte Example
```

2024-04-22 10:22 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/insert/insert.md
> +```
```suggestion
```shell
```

2024-04-22 10:22 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/insert/insert.md
> +```
```suggestion
```py
```

2024-04-22 10:22 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/insert/insert.md
> +```
```suggestion
```py
```

2024-04-22 10:22 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/insert/insert.md
> +```
```suggestion
```shell
```

2024-04-22 10:22 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/insert/insert.md
> +```
```suggestion
```py
```

2024-04-22 10:22 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/insert/insert.md
> +```
```suggestion
```shell
```

2024-04-22 10:22 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/insert/insert.md
> +Feel free to play around with Doric's `testResults` DataFrame and add your own column.  Some suggestions include: test date(s), each person's class (such as 'Rogue' or 'Barbarian'), or known associat
```suggestion
The following example demonstrates the use of the .insert() method in pandas to add a new column named 'alignment' to a DataFrame, representing alignment information for test results.```

2024-04-22 10:22 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/insert/insert.md
> +```codebyte/js
```suggestion
```codebyte/python
```

2024-04-22 10:22 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/insert/insert.md
> +In the following examples, the `.insert()` method is used with different parameters on the testResults DataFrame:
```suggestion
In the following example, the `.insert()` method is used with different parameters on the testResults DataFrame:
```

2024-04-22 13:17 UTC, MartinLBeacham commented
Thank you so much @mamtawardhani !

I've committed your edits and incorporated your comments into an updated commit.

Please let me know if you have any further comments or questions.

2024-04-22 14:10 UTC, mamtawardhani requested changes
Hey @MartinLBeacham 

Just one more suggestion added, please modify the same.
Thanks!

2024-04-27 06:11 UTC, Sriparno08 approved these changes
Looks good 👍

2024-04-27 06:12 UTC, merged