[Topic Entry]: TensorFlow (created topic and added entry)
Codecademy/docs pull request #4574
Opened 2024-04-24 16:57 UTC by ishg-153

### Description

### Issue Solved

### Type of Change

- Creating new topic for TensorFlow
- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-04-29 09:59 UTC, Sriparno08 approved these changes
@ishg-153 Looks good for a second review 👍

2024-04-29 13:16 UTC, letsbuildanything requested changes
@ishg-153, requested a minor changes.

2024-04-29 13:16 UTC, letsbuildanything commented on content/tensorflow/tensorflow.md
> +**TensorFlow** is a free and [open-source](https://www.codecademy.com/resources/docs/open-source) library for [artificial intelligence](https://www.codecademy.com/resources/docs/ai) and machine learn
```suggestion
**TensorFlow**, a free and [open-source](https://www.codecademy.com/resources/docs/open-source) library for [artificial intelligence](https://www.codecademy.com/resources/docs/ai) and machine learning, was developed by Google Brain team. It is mainly used with [Python](https://www.codecademy.com/resources/docs/python) but also supports other programming languages such as [C++](https://www.codecademy.com/resources/docs/cpp). It provides an extensive collection of functions or APIs that can be used to build deep neural networks and deep learning models. To begin using TensorFlow, one can install the library by following the steps on the [TensorFlow](https://www.tensorflow.org/install) website.
```

2024-04-29 16:50 UTC, ishg-153 commented
Done @letsbuildanything!

2024-04-30 04:30 UTC, letsbuildanything approved these changes
LGTM! 🚀

2024-04-30 04:32 UTC, merged