Term entry dart to int()
Codecademy/docs pull request #4578
Opened 2024-04-25 22:58 UTC by VivianVanilla

### Description

I simply added a term entry for the `.toInt()` method by adding a new file located .../type-conversion/**toInt**/**toInt.md**. I added an example of how to use the method and followed the style guide and general procedure to the best of my ability. I did this for the Codecademy portfolio assignment in the 'Learn Git and Github' and had more fun than I expected!   

### Issue Solved

Closes Issue #4570 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-04-25 22:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4578) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4578) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4578) it.</sub>

2024-04-26 07:07 UTC, mamtawardhani requested changes
Hey @VivianVanilla! Thank you for contributing to Codecademy Docs!

The entry is well written! I've provided a few suggestions, could you please review and modify those at your earliest convenience?

Thank you!

2024-04-26 07:07 UTC, mamtawardhani commented on content/dart/concepts/type-conversion/toInt/toInt.md
> +  print(myNumber);
```suggestion
void main() {
  var myNumber = 10.4;
  var result = myNumber.toInt();
  print(result);
}
```

2024-04-26 07:07 UTC, mamtawardhani commented on content/dart/concepts/type-conversion/toInt/toInt.md
> +- `number`: Chosen numeric value that needs to be converted into an integer value.
```suggestion
- `number`: It is the chosen numeric value that needs to be converted into an integer value.
```

2024-04-26 07:07 UTC, mamtawardhani commented on content/dart/concepts/type-conversion/toInt/toInt.md
> +In the following example, the `.toInt()` method is used to turn `myNumber` into an integer value.
```suggestion
In the following example, the `.toInt()` method is used to convert `myNumber` into an integer value.
```

2024-04-26 16:35 UTC, VivianVanilla commented
Thank you so much for the suggestions and help @mamtawardhani ! I believe I've addressed all your concerns :).

2024-04-27 05:46 UTC, mamtawardhani approved these changes
Good for second review

2024-04-29 15:14 UTC, VivianVanilla commented
@letsbuildanything Updated the path!

2024-04-30 06:40 UTC, letsbuildanything approved these changes
LGTM! 🚀

2024-04-30 06:42 UTC, merged