[Term Entry] Java ArrayList .removeAll()
Codecademy/docs pull request #4581
Opened 2024-04-26 15:45 UTC by bpicoCode

### Description

- Adding a new term entry for ArrayList .removeAll() method

### Issue Solved

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-04-26 15:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4581) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4581) before we can accept your contribution.<br/><hr/>**Ben Picone** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4581) it.</sub>

2024-04-27 12:16 UTC, mamtawardhani requested changes
Hey @bpicoCode!
Thank you for contributing to Codecademy Docs! The entry is well written!

I've suggested a few changes, could you please review and modify them at your earliest convenience? 
Thank you!

2024-04-27 12:16 UTC, mamtawardhani commented on content/java/concepts/array-list/terms/removeAll/removeAll.md
> +In the example below, two `ArrayList` instance `fallMonths` and `monthsToRemove` are created and can hold `String`-type elements. Next, elements are added with [the `.add()` method](https://www.codec
```suggestion
In the example below, two `ArrayList` instances, `fallMonths` and `monthsToRemove`, are created to hold `String`-type elements. Elements are added to the `fallMonths` using the [`.add()`] method (https://www.codecademy.com/resources/docs/java/array-list/add). Then, `monthsToRemove` is utilized to remove the months - August and September from `fallMonths` using `.removeAll()`. Finally, all elements are removed from `fallMonths` by invoking `.removeAll()` with a reference to itself.
```

2024-04-27 12:16 UTC, mamtawardhani commented on content/java/concepts/array-list/terms/removeAll/removeAll.md
> +    System.out.println(fallMonths);
```suggestion
    System.out.println("After removing specified months: " + fallMonths);```

2024-04-27 12:16 UTC, mamtawardhani commented on content/java/concepts/array-list/terms/removeAll/removeAll.md
> +    System.out.println(fallMonths);
```suggestion
System.out.println("After removing all elements: " + fallMonths);```

2024-04-27 12:16 UTC, mamtawardhani commented on content/java/concepts/array-list/terms/removeAll/removeAll.md
> +The `.removeAll()` method is used for removing multiple elements from instances of the `ArrayList` class.
```suggestion
The **`.removeAll()`** method is used for removing multiple elements from instances of the `ArrayList` class.
```

2024-04-30 00:12 UTC, bpicoCode commented
@mamtawardhani Suggestions committed!

2024-04-30 06:18 UTC, mamtawardhani requested changes
Hey @bpicoCode, just one change is required, please review and modify it!
Thanks!

2024-04-30 06:18 UTC, mamtawardhani commented on content/java/concepts/array-list/terms/removeAll/removeAll.md
> +In the example below, two `ArrayList` instances, `fallMonths` and `monthsToRemove`, are created to hold `String`-type elements. Elements are added to the `fallMonths` using the [`.add()`] method (htt
```suggestion
In the example below, two `ArrayList` instances, `fallMonths` and `monthsToRemove`, are created to hold `String`-type elements. Elements are added to the `fallMonths` using the [`.add()`]
(https://www.codecademy.com/resources/docs/java/array-list/add) method. Then, `monthsToRemove` is utilized to remove the months - August and September from `fallMonths` using `.removeAll()`. Finally, all elements are removed from `fallMonths` by invoking `.removeAll()` with a reference to itself.
```

2024-05-01 05:35 UTC, mamtawardhani approved these changes
Good for the second review

2024-05-03 17:20 UTC, avdhoottt requested changes
Hey @bpicoCode, I suggested some changes, please make them.

2024-05-03 17:20 UTC, avdhoottt commented on content/java/concepts/array-list/terms/removeAll/removeAll.md
> +A collection of elements, specified by `Collection c`, can be removed from an `ArrayList` instance using the `.removeAll()` method:
Remove this line and add the description of the parameters `ArrayList2` and `ArrayList1` below the syntax in this format - 
```
- `parameterName`: Parameter description.
- `parameterName`: Parameter description.
```

2024-05-03 17:20 UTC, avdhoottt commented on content/java/concepts/array-list/terms/removeAll/removeAll.md
> +arrayListInstance.removeAll(Collection c);
```suggestion
ArrayList1.removeAll(ArrayList2);
```
Simply the syntax as much as possible.

2024-05-03 17:20 UTC, avdhoottt commented on content/java/concepts/array-list/terms/removeAll/removeAll.md
> +}
```suggestion
import java.util.ArrayList;

public class RemoveFallMonths{
  public static void main(String[] args) {

    ArrayList<String> fallMonths = new ArrayList<String>();

    fallMonths.add("August");
    fallMonths.add("September");
    fallMonths.add("October");
    fallMonths.add("November");
    fallMonths.add("December");

    ArrayList<String> monthsToRemove = new ArrayList<String>();

    monthsToRemove.add("August");
    monthsToRemove.add("December");

    // Remove August and December from fallMonths using monthsToRemove
    fallMonths.removeAll(monthsToRemove);

    System.out.println("After removing specified months: " + fallMonths);

    // Remove all elements from fallMonths
    fallMonths.removeAll(fallMonths);

System.out.println("After removing all elements: " + fallMonths);
  }
}
```
The code had some errors, but I fixed them.

2024-05-03 17:20 UTC, avdhoottt commented on content/java/concepts/array-list/terms/removeAll/removeAll.md
> +[]
```suggestion
After removing specified months: [September, October, November]
After removing all elements: []
```
This is the complete output.

2024-05-03 17:20 UTC, avdhoottt commented on content/java/concepts/array-list/terms/removeAll/removeAll.md
> +The `RemoveFallMonths` output should look like this:
```suggestion
The output of the above code should look like this:
```

2024-05-16 17:20 UTC, avdhoottt commented
Hey @bpicoCode, it's been two weeks since I suggested the changes, are you still working on this PR?

2024-05-21 15:49 UTC, avdhoottt commented on content/java/concepts/array-list/terms/removeAll/removeAll.md
> +In the example below, two `ArrayList` instances, `fallMonths` and `monthsToRemove`, are created to hold `String`-type elements. Elements are added to the `fallMonths` using the [`.add()`]
```suggestion
In the example below, two `ArrayList` instances, `fallMonths` and `monthsToRemove`, are created to hold `String` type elements. Elements are added to the `fallMonths` using the [`.add()`]
```

2024-05-21 15:49 UTC, avdhoottt approved these changes
LGTM!!

2024-05-21 16:37 UTC, merged