[Term Entry] Dart Type Conversion .tryParse() #4572
Codecademy/docs pull request #4586
Opened 2024-04-29 15:12 UTC by lou-pastorino

### Description

 - Added the tryParse() term for Dart. 
 - Mardown file entry is under: docs/tree/term-tryParse/content/dart/concepts/type-conversion 

### Issue Solved

- Closes issue #4572

### Type of Change

- Adding a new entry

### Checklist

- [x ] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-04-29 15:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4586) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4586) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4586) it.</sub>

2024-04-30 08:27 UTC, mamtawardhani commented
Hey @lou-pastorino! Please update the path to `docs/content/dart/concepts/type-conversion/terms/tryParse/tryParse.md`

2024-04-30 09:29 UTC, mamtawardhani requested changes
Hey @lou-pastorino!
Thanks for contributing to the Codecademy docs! 

I've suggested a few changes, please review and modify them at your earliest convenience.
Thank you!

2024-04-30 09:29 UTC, mamtawardhani commented on content/dart/concepts/type-conversion/terms/tryParse/tryParse.md
> +2. dataType is the data type that one wishes to convert stringValue to.
```suggestion
- `stringToParse` - Represents the `string` to be converted into the desired data type.
- `dataType` - Represents the data type to be converted to stringValue.
```

2024-04-30 09:29 UTC, mamtawardhani commented on content/dart/concepts/type-conversion/terms/tryParse/tryParse.md
> +dataType.tryParse(stringValue)
```suggestion
dataType.tryParse(stringToParse)
```

2024-04-30 09:29 UTC, mamtawardhani commented on content/dart/concepts/type-conversion/terms/tryParse/tryParse.md
> +```
The ## Codebyte is not needed, please place this codebyte under ## Example along with its output. Remove the:
value = num.tryParse('5'); // 5
2. value = num.tryParse('five'); // null

and ## Codebyte example tag

2024-04-30 09:29 UTC, mamtawardhani commented on content/dart/concepts/type-conversion/terms/tryParse/tryParse.md
> +
```suggestion
```

2024-04-30 11:23 UTC, mamtawardhani requested changes
Hey @lou-pastorino!

Can you please implement the one suggestion given? Thanks!

2024-04-30 11:23 UTC, mamtawardhani commented on content/dart/concepts/type-conversion/terms/tryParse/tryParse.md
> +- `dataType` - Represents the data type to be converted to stringValue.
```suggestion
- `stringToParse` - Represents the `string` to be converted into the desired data type.
- `dataType` -  Represents the data type used to parse `stringToParse`.
```

2024-04-30 11:29 UTC, lou-pastorino commented
@mamtawardhani Hey! The final suggestion has been implemented. 
Thanks

2024-04-30 11:34 UTC, mamtawardhani commented
Hey @lou-pastorino! Thank you for implementing the suggestions!

Lastly, could you please update the path to `docs/content/dart/concepts/type-conversion/terms/tryParse/tryParse.md`

2024-04-30 11:59 UTC, lou-pastorino commented
> Hey @lou-pastorino! Thank you for implementing the suggestions!
> 
> Lastly, could you please update the path to `docs/content/dart/concepts/type-conversion/terms/tryParse/tryParse.md`

Hi @mamtawardhani 

Apologies, I must be getting confused somewhere. On my side it looks like the file path is as you have described above. Do I need to create a new pull request to merge the updated branch with my main branch to update the file path? 
Apologies for the confusion!

2024-04-30 17:52 UTC, mamtawardhani approved these changes
Good to go for the second review.

@lou-pastorino Thanks for making the changes!

2024-05-01 13:10 UTC, merged