[Term Entry] Dart Type Conversion .parse()
Codecademy/docs pull request #4596
Opened 2024-04-29 20:28 UTC by Mhidayah19

### Description

- Added Dart Type Conversion .parse()
- Closes issue #4571

### Issue Solved

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-04-29 20:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4596) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4596) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4596) it.</sub>

2024-04-30 13:04 UTC, Sriparno08 reviewed
Hey @Mhidayah19, thanks for contributing to Codecademy!

I've listed all the modifications that you need to make in your entry below:

2024-05-01 13:50 UTC, Sriparno08 approved these changes
Looks good for a second review 👍

2024-05-03 11:32 UTC, letsbuildanything requested changes
@Mhidayah19 
I've requested below some changes. Please take a moment to address them. If you have any concerns or reasons to reject specific suggestions, feel free to discuss them.

2024-05-03 11:32 UTC, letsbuildanything commented on content/dart/concepts/type-conversion/terms/parse/parse.md
> +int.parse(string)
```suggestion
dataType.parse(string)
```

2024-05-20 14:23 UTC, letsbuildanything commented
@Mhidayah19  It's been more than two weeks since the request was made. Please proceed with implementing all the suggested modifications.
Thank you!

2024-06-04 03:43 UTC, letsbuildanything approved these changes
Ready to be Merged! 🚀

2024-06-04 03:44 UTC, merged