Create index and columns
Codecademy/docs pull request #4597
Opened 2024-04-29 23:21 UTC by 0-Brandon

### Description
Added entries for the .index and .columns attributes of DataFrames. 
### Issue Solved

Closes #4518
Closes #4519

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-04-30 14:46 UTC, letsbuildanything requested changes
@0-Brandon 
Thank you for contributing to Codecademy Docs!
I've requested below some changes. Please make them.

2024-04-30 14:46 UTC, letsbuildanything commented on content/pandas/concepts/dataframe/terms/index/index.md
> +The **`.index`** attribute represents the row labels (index) of the DataFrame. It is an Index object and can be used to view or assign new values to the row labels.
```suggestion
The **`.index`** attribute represents the row labels (index) of the DataFrame. It returns an Index object and can be used to view or assign new values to the row labels.
```

2024-04-30 14:46 UTC, letsbuildanything commented on content/pandas/concepts/dataframe/terms/index/index.md
> +Dataframe.index
```suggestion
pandas.DataFrame.index
```

2024-04-30 14:46 UTC, letsbuildanything commented on content/pandas/concepts/dataframe/terms/index/index.md
> +In the following example, the `.index` attribute is used to modify the row labels of the `monthlyCost` DataFrame:
```suggestion
In the following example, the `.index` attribute is used to view and modify the row labels of the `monthlyCost` DataFrame:
```

2024-04-30 14:46 UTC, letsbuildanything commented on content/pandas/concepts/dataframe/terms/index/index.md
> +print(monthlyCost)
```suggestion
import pandas as pd

# Creating the DataFrame representing monthly cost of 4 items

data = {'April': [88, 92, 79, 85],
'May': [94, 77, 90, 78],
'June': [89, 80, 95, 81]}

monthlyCost = pd.DataFrame(data)

# Print the DataFrame
print(f'{monthlyCost} \n')

# modify the row labels
monthlyCost.index = ['bread', 'milk', 'apples', 'onions']

# print the modified monthlyCost Dataframe
print(f'{monthlyCost} \n')

# print the row label or index of monthlyCost DataFrame
print(monthlyCost.index)
```

2024-04-30 14:46 UTC, letsbuildanything commented on content/pandas/concepts/dataframe/terms/index/index.md
> +3    85       78       81
```suggestion
  April  May  June
0     88   94    89
1     92   77    80
2     79   90    95
3     85   78    81 

        April  May  June
bread      88   94    89
milk       92   77    80
apples     79   90    95
onions     85   78    81 

Index(['bread', 'milk', 'apples', 'onions'], dtype='object')
```

2024-04-30 14:46 UTC, letsbuildanything commented on content/pandas/concepts/dataframe/terms/index/index.md
> +
```suggestion
```

2024-04-30 14:46 UTC, letsbuildanything commented on content/pandas/concepts/dataframe/terms/index/index.md
> +Codebyte Example
```suggestion
## Codebyte Example

```

2024-04-30 14:46 UTC, letsbuildanything commented on content/pandas/concepts/dataframe/terms/index/index.md
> +The following Codebyte demonstrates how to view and update a DataFrame using the `.index` attribute:
```suggestion
The following Codebyte Example demonstrates how to view and update a DataFrame using the `.index` attribute:
```

2024-04-30 14:46 UTC, letsbuildanything commented on content/pandas/concepts/dataframe/terms/index/index.md
> +df.index = ['r1', 'r2']
```suggestion
# updating the row label
df.index = ['r1', 'r2']
```

2024-05-05 18:16 UTC, letsbuildanything approved these changes
Ready for second round of review!

2024-05-06 11:11 UTC, Sriparno08 commented
Hey @0-Brandon, please open a new PR for the `.index` entry as we only want one logical change in a PR. In case of this PR, make a new commit removing the `.index` entry and leaving the `.columns` entry as it is.

2024-05-09 18:22 UTC, avdhoottt requested changes
Hey @0-Brandon, I've suggested a minor change. Please make it and let me know when you are done.

2024-05-09 18:22 UTC, avdhoottt commented on content/pandas/concepts/dataframe/terms/columns/columns.md
> +The **`.columns`** attribute represents the column labels of the DataFrame. It returns an Index object and can be used to view or assign new values to the column labels.
```suggestion
The **`.columns`** attribute represents the column labels of the DataFrame. It returns an `Index` object and can be used to view or assign new values to the column labels.
```

2024-05-09 18:22 UTC, avdhoottt commented on content/pandas/concepts/dataframe/terms/index/index.md
> +The **`.index`** attribute represents the row labels (index) of the DataFrame. It returns an Index object and can be used to view or assign new values to the row labels.
```suggestion
The **`.index`** attribute represents the row labels (index) of the DataFrame. It returns an `Index` object and can be used to view or assign new values to the row labels.
```

2024-05-12 18:13 UTC, avdhoottt approved these changes
LGTM!!

2024-05-12 18:15 UTC, merged