Add .create_gantt entry, associated media and new tags doc
Codecademy/docs pull request #4604
Opened 2024-05-03 22:21 UTC by rgo444

### Description

Added a new term entry for Plotly: **.create_gantt()**, along with an associated media image of the plot output. I also updated the tags document to include a new tag: Plotly :round_pushpin:

### Issue Solved

Closes #4563

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-03 22:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4604) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4604) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4604) it.</sub>

2024-05-04 09:32 UTC, mamtawardhani requested changes
Hey @rgo444! Thanks for contributing at Codecademy!

Please do the following:
(1) Sign the CLA
(2) Could you please rename the file to `create_gantt.md`, instead of `create-gantt.md`
(3) Please remove the `tags.md` file from this branch.
(4) I've mentioned some suggestions for the entry, could you please review and modify them at your earliest convenience?

Thank you!

2024-05-07 01:08 UTC, rgo444 commented on content/plotly/concepts/figure_factory/terms/create_gantt/create-gantt.md
> +---
Hi @mamtawardhani !

I have completed the requested changes, hope I managed to update the pull request correctly :dizzy_face:

Thank you!

2024-05-07 06:38 UTC, mamtawardhani requested changes
Hey @rgo444! I've suggested some changes in the entry, could you please review those and modify them at your earliest convenience? 
Also, you can remove the older `create-gantt.md` file from this branch, keep only the new `create_gantt.md` file.

Thanks!

2024-05-07 06:38 UTC, mamtawardhani commented on content/plotly/concepts/figure_factory/terms/create_gantt/create_gantt.md
> +"The syntax for the .create_gantt() method in Plotly is customizable. Below is a general structure of it: "
```suggestion
The syntax for the .create_gantt() method in Plotly is customizable. Below is a general structure of it: 
```

2024-05-07 06:38 UTC, mamtawardhani commented on content/plotly/concepts/figure_factory/terms/create_gantt/create_gantt.md
> +`.create_gantt` takes the following arguments:
```suggestion
The `.create_gantt()` method takes the following arguments:
```

2024-05-07 06:38 UTC, mamtawardhani commented on content/plotly/concepts/figure_factory/terms/create_gantt/create_gantt.md
> +- `title`: Sets the title of the chart.
```suggestion
- `df`: Required input data, either a `data frame` or a list, serving as the foundation for the Gantt chart's content.
- `colors`: Specifies the color scheme used in the chart, allowing customization through options like a Plotly scale name, a `list` of colors, a `dictionary` mapping values to colors, or a `tuple` defining the color range.
- `index_col`: Identifies the column header to be used as the indexing column in the Gantt chart, aiding in the organization of tasks or data points along the `y-axis`.
- `show_colorbar`: A `boolean` parameter determining the visibility of the color bar in the Gantt chart.
- `reverse_colors`: A `boolean` parameter enabling the reversal of selected colors in the chart.
- `title`: Sets a descriptive title for the Gantt chart.
```

2024-05-07 06:38 UTC, mamtawardhani commented on content/plotly/concepts/figure_factory/terms/create_gantt/create_gantt.md
> +**Note:** The ellipsis (...) indicates that there can be additional optional arguments beyond those listed here.
```suggestion
> **Note:** The ellipsis (...) indicates that there can be additional optional arguments beyond those listed here.
```

2024-05-07 06:38 UTC, mamtawardhani commented on content/plotly/concepts/figure_factory/terms/create_gantt/create_gantt.md
> +**Output:**
```suggestion

The code above produces the following output:
```

2024-05-13 08:05 UTC, mamtawardhani commented
Hey @rgo444! 
Here's a suggestion, I see that you have added a lot of files for this PR. Could you close this PR and create a new one with the suggestions you modified? That will be easy actually.

And sorry for the inconvenience caused, please make sure the path is `docs/content/plotly/concepts/figure-factory/terms/create-gantt/create-gantt.md`, so the `create-gantt/create-gantt.md` folder and file name should be fine.

Thank you!

2024-05-15 18:53 UTC, mamtawardhani commented
Yes @rgo444, it would be `create-gantt.md`.
Just make sure you apply the suggestions that I had given! Thanks! :)

2024-05-19 22:10 UTC, closed without merging

2024-05-19 22:30 UTC, rgo444 commented
Done deal @mamtawardhani! Have an excellent weekstart!