Python plotly bar
Codecademy/docs pull request #4607
Opened 2024-05-05 11:25 UTC by M-MacNeill

### Description

Term Entry and example output for Plotly .bar() method. Created docs/content/plotly/concepts/express/terms/bar/bar.md and docs\media\plotly-bar-example.png.

### Issue Solved

Closes #4557

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-05 11:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4607) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4607) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4607) it.</sub>

2024-05-06 10:23 UTC, Sriparno08 commented on content/plotly/concepts/express/terms/bar/bar.md
> +---
```suggestion
---
Title: '.bar()'
Description: 'Generates a chart representing categorical data with vertical bars.'
Subjects:
  - 'Computer Science'
  - 'Data Science'
Tags:
  - 'Data'
  - 'Graphs'
  - 'Libraries'
  - 'Methods'
CatalogContent:
  - 'learn-python-3'
  - 'paths/computer-science'
---
```

2024-05-06 10:31 UTC, Sriparno08 commented on content/plotly/concepts/express/terms/bar/bar.md
> +The **`.bar()`** method in Plotly is part of the Plotly Express high-level interface to Plotly. It generates charts representing categorical data with vertical bars.
```suggestion
In Plotly, the **`.bar()`** method is part of the high-level interface named `plotly.express`. It generates charts representing categorical data with vertical bars. 
```

2024-05-06 10:38 UTC, Sriparno08 commented on content/plotly/concepts/express/terms/bar/bar.md
> +- height: Integer designating the chart height in pixels.
````suggestion
```pseudo
plotly.express.bar(x, y, labels, title, width, height, ...)
```

- x: A string, integer, series, or array-like object designating the x-axis data.
- y: A string, integer, series, or array-like object designating the y-axis data.
- labels: A dictionary with string keys and string values designating column names and labels for axis titles, hovers, and legend entries.
- title: A string designating the chart title.
- width: An integer designating the chart width in pixels.
- height: An integer designating the chart height in pixels.
````

2024-05-06 10:39 UTC, Sriparno08 commented on content/plotly/concepts/express/terms/bar/bar.md
> +Below is an example demonstrating how to use the `.bar()` method to create a simple bar chart visualizing the values of items in categories a, b, c and d:
```suggestion
Below is an example demonstrating how to use the `.bar()` method to create a simple bar chart visualizing the values of items in categories `a`, `b`, `c`, and `d`:
```

2024-05-06 10:40 UTC, Sriparno08 commented on content/plotly/concepts/express/terms/bar/bar.md
> +```python
```suggestion
```py
```

2024-05-06 10:41 UTC, Sriparno08 commented on content/plotly/concepts/express/terms/bar/bar.md
> +Output:
```suggestion
The above code produces the following output:
```

2024-05-06 10:43 UTC, Sriparno08 commented on content/plotly/concepts/express/terms/bar/bar.md
> +![Output of ploltly.express.bar() method example](https://raw.githubusercontent.com/Codecademy/docs/main/media/plotly-bar-example.png)
```suggestion
![Output for the above example](https://raw.githubusercontent.com/Codecademy/docs/main/media/plotly-bar-example.png)
```

2024-05-07 06:12 UTC, M-MacNeill commented
Thanks for the suggested changes @Sriparno08. I have now applied them.

2024-05-07 07:23 UTC, Sriparno08 approved these changes
Looks good for a second review! 👍

2024-05-10 06:28 UTC, mamtawardhani requested changes
Hey @M-MacNeill! Thanks for contributing to Codecademy Docs!

I've suggested a few changes, could you please review and modify them at your earliest convenience?
Thank you!

2024-05-11 08:59 UTC, M-MacNeill commented
@mamtawardhani, Thank you for the additional suggestions. I have now made them too.

2024-05-14 06:22 UTC, mamtawardhani approved these changes
Thank you for making the required changes @M-MacNeill!

The entry looks good to me 👍
Will merge it to the main branch soon!

2024-05-21 17:01 UTC, merged