[Term Entry] Dart Type Conversion .toDouble()
Codecademy/docs pull request #4630
Opened 2024-05-07 10:45 UTC by alvaro347

### Description

- Added the toDouble() method for dart

### Issue Solved

Closes #4569 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-07 10:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4630) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4630) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4630) it.</sub>

2024-05-08 09:16 UTC, mamtawardhani commented
Hey @alvaro347! Please sign the CLA. Thanks!

2024-05-09 09:28 UTC, alvaro347 commented
@mamtawardhani I just signed the CLA, thank you.

2024-05-11 06:42 UTC, mamtawardhani requested changes
Hey @alvaro347! Thank you for Contributing to Codecademy Docs! The entry was nicely written.

I've suggested some changes in the entry, could you please review and modify them at your earliest convenience? Feel free to discuss if you have any concerns.
Thank you!

2024-05-11 06:42 UTC, mamtawardhani commented on content/dart/concepts/type-conversion/terms/toDouble/toDouble.md
> +---
```suggestion
---
Title: '.toDouble()'
Description: 'Returns the double representation of the number's value'
Subjects:
  - 'Code Foundations'
  - 'Computer Science'
  - 'Mobile Development'
Tags:
  - 'Dart'
  - 'Data Types'
  - 'Methods'
  - 'Numbers'
CatalogContent:
  - 'learn-dart'
  - 'paths/computer-science'
---
```

2024-05-11 06:42 UTC, mamtawardhani commented on content/dart/concepts/type-conversion/terms/toDouble/toDouble.md
> +In Dart, **`.toDouble()`** is a method used to convert numeric [data types](https://www.codecademy.com/resources/docs/dart/data-types), such as `int`, into its double-precision floating-point represe
```suggestion
In Dart, **`.toDouble()`** is a method used to convert numeric [data types](https://www.codecademy.com/resources/docs/dart/data-types), such as `int`, to their double-precision floating-point representation.
```

2024-05-11 06:42 UTC, mamtawardhani commented on content/dart/concepts/type-conversion/terms/toDouble/toDouble.md
> +```
```suggestion
```

> **Note:** The output `3.0` is a double. This can be confirmed by checking `value.runtimeType`.
```

2024-05-11 06:42 UTC, mamtawardhani commented on content/dart/concepts/type-conversion/terms/toDouble/toDouble.md
> +
```suggestion
## Example

The following example demonstrates how the `.toDouble()` method is used to convert a number to double:

```

2024-05-11 06:42 UTC, mamtawardhani commented on content/dart/concepts/type-conversion/terms/toDouble/toDouble.md
> +The above code returns the following output:
```suggestion
The above code produces the following output:
```

2024-05-12 20:47 UTC, alvaro347 commented
Hello @mamtawardhani, thank you for the revision and the suggestions. I updated the file and commit the changes. Do you mind checking it out?

2024-05-13 06:06 UTC, mamtawardhani approved these changes
Thank you for making the changes @alvaro347! 
Looks good for the second review.

2024-05-20 12:50 UTC, letsbuildanything approved these changes
Ready to merge! 🚀

2024-05-20 12:53 UTC, merged