[Term Entry] Python pillow .resize()
Codecademy/docs pull request #4635
Opened 2024-05-09 13:44 UTC by Elgittos

### Description

- Added new term entry on the '.resize()' method for the Pillow library in Python.
- Added the pillow folder and all it's subfolders in the content folder docs/content/pillow/concepts/image/terms/resize/resize.md, aswell as the resize.md file. 

### Issue Solved

- Closes Issue #4628 

### Type of Change

- Adding a new entry

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-09 13:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4635) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4635) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4635) it.</sub>

2024-05-11 07:17 UTC, mamtawardhani requested changes
Hey @Elgittos! Thank you for contributing to the Codecademy Docs! The entry was nicely written.

I've suggested some changes for this entry, could you please review and modify those at your earliest convenience? Feel free to discuss if you have any concerns!
Thank you!

2024-05-11 07:17 UTC, mamtawardhani commented on content/pillow/concepts/image/terms/resize/resize.md
> +```
Just one example is to be added, the other two can be removed.

2024-05-11 07:17 UTC, mamtawardhani commented on content/pillow/concepts/image/terms/resize/resize.md
> +`.resize()` takes pixels as arguments directly in the first parameter.
```suggestion
The following example demonstrates the use of  the `.resize()` method to change the size of the image:
```

2024-05-11 07:17 UTC, mamtawardhani commented on content/pillow/concepts/image/terms/resize/resize.md
> +```
For this example, make use of an image to also show the resized image in the output. Keep the Image used and the Output image under the "Media" folder in the docs.

2024-05-11 07:17 UTC, mamtawardhani commented on content/pillow/concepts/image/terms/resize/resize.md
> +Returns an **image** **object**.
For the parameters description, please use the following format:

- `size`: Parameter description
- `resample`: Parameter description
- `box`: Parameter description
- `reducing_gap`: Parameter description

You can avoid giving the details of the resample filters for this entry. Only the parameters description should be given.

2024-05-11 07:17 UTC, mamtawardhani commented on content/pillow/concepts/image/terms/resize/resize.md
> +img_resized = img.resized((1000, 1000))
```suggestion
img_resized = img.resize((1000, 1000))
```

2024-05-15 00:17 UTC, Elgittos commented
Hi thanks. I've made the changes. Hope it helped 👍

2024-05-15 06:48 UTC, mamtawardhani requested changes
Hey @Elgittos! I guess you missed some changes requested earlier, I've mentioned those again. Also, please make sure to describe the parameters in the suggested format and not the table format. Feel free to discuss if you have any concerns.

Thank you!

2024-05-15 06:48 UTC, mamtawardhani commented on content/pillow/concepts/image/terms/resize/resize.md
> +Description: 'The .resize() method is part of the Image class in the Pillow library (PIL Fork) in Python, and it is used to change the size of an image.'
```suggestion
Description: 'Changes the size of an image to a specified size.'
```

2024-05-15 06:48 UTC, mamtawardhani commented on content/pillow/concepts/image/terms/resize/resize.md
> +  - 'Web Development'
```suggestion
  - 'Computer Science'
  - 'Data Science'
  - 'Web Design'
  - 'Web Development'
```

2024-05-15 06:48 UTC, mamtawardhani commented on content/pillow/concepts/image/terms/resize/resize.md
> +Returns an **image** **object**.
For the parameters description, do not add a table, please use the following format:

- size: Parameter description
- resample: Parameter description
- box: Parameter description
- reducing_gap: Parameter description

2024-05-25 19:16 UTC, Elgittos commented
Hi. I corrected the entry. I hope I didn't miss anything 😄

2024-05-27 06:05 UTC, mamtawardhani approved these changes
Hello @Elgittos, thanks for making the required changes!

Looks good for a second review 😄

2024-05-27 10:53 UTC, mohitO12-dev approved these changes
ALL SORT OF FORMAT ISSUE IS SOLVED. after discussion with @mamtawardhani

2024-05-27 10:55 UTC, merged