[Concept Entry] Postgresql window-functions #4591
Codecademy/docs pull request #4638
Opened 2024-05-11 13:23 UTC by Johnnie-kay

### Description

- Created a new concept entry for Postgresql window functions.
- Closes issue #4591 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-11 13:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4638) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4638) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4638) it.</sub>

2024-05-12 19:38 UTC, SaviDahegaonkar requested changes
Hello Author,  I have suggested a few changes in the file and corrected some minor mistakes accordingly. Please have a look at it and please let me know.
Thanks!

2024-05-12 19:38 UTC, SaviDahegaonkar commented on content/postgresql/concepts/window-functions/window-functions.md
> +From the above _staff_ table, to rank the employees using the `Rank()` function, we select the id, salary, and address columns from the _staff_ table, and then use the `RANK()` window function to ass
```suggestion
From the above `_staff_ table`, to rank the employees using the `Rank()` function, we select the `id`, `salary`, and `address` columns from the `_staff_ ` table, and then use the `RANK()` window function to assign a rank to each row based on the ` _salary_ ` column within each partition defined by the `_address_ ` column.
```

2024-05-12 19:38 UTC, SaviDahegaonkar commented on content/postgresql/concepts/window-functions/window-functions.md
> +`SELECT id, salary, address, Rank() OVER (PARTITION BY address ORDER BY salary DESC) FROM staff;`
```suggestion

SELECT id, salary, address, Rank() OVER (PARTITION BY address ORDER BY salary DESC) FROM staff;
```
This is not a syntax as we are using it to print something. Write the code in the code block (```sql). Check the [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) for the reference.

2024-05-12 19:38 UTC, SaviDahegaonkar commented on content/postgresql/concepts/window-functions/window-functions.md
> +- The statement ends with `FROM staff`, signifying that it operates on the staff table.
```suggestion
Breaking down the syntax:
- The clause `SELECT`, selects the id, salary, and address columns from the staff table.
- The `Rank() OVER` part computes the row number of each row.
- The `(PARTITION BY address ORDER BY salary DESC)` clause actively defines how the window function partitions the data.
- The statement ends with `FROM staff`, signifying that it operates on the `_staff _` table.
```

2024-05-12 19:38 UTC, SaviDahegaonkar commented on content/postgresql/concepts/window-functions/window-functions.md
> +| 06 |  2500  | Dubai   |  1   |
```suggestion
## Output

| `id` | `salary`| `address` | `rank` | 
|--- | -----  | -----   | ---- |
| 01 |  5500  | Tokyo   |  1   |
| 04 |  3500  | Tokyo   |  2 |
| 08 |  2000  | Tokyo   |  3 |
| 07 |  4500  | Mumbai | 1 |
| 03 |  2500  | Mumbai | 2 |
| 02 |  5000  | Beijing | 1 |
| 05 |  4000  | Paris    | 1 |
| 06 |  2500  | Dubai | 1 |
```
Add a line like this after the subheading `## Output`: 
`This is the output of the above query:`

2024-05-12 19:38 UTC, SaviDahegaonkar commented on content/postgresql/concepts/window-functions/window-functions.md
> +In PostgreSQL, the `row_number` window function plays a useful role by defining the row number of a column. Let's use the _staff_ table to assign a row number to each row based on the `salary` column
```suggestion
In PostgreSQL, the `row_number` window function plays a useful role by defining the row number of a column. Let's use the `_staff_ table` to assign a row number to each row based on the `salary` column, within each group of rows that have the same `address`, ordering the rows by `salary` in descending order within each group.
```
Just added backticks.

2024-05-12 19:38 UTC, SaviDahegaonkar commented on content/postgresql/concepts/window-functions/window-functions.md
> +`SELECT id, salary, address, row_number() OVER (PARTITION BY address ORDER BY salary DESC) FROM staff`
```suggestion

SELECT id, salary, address, row_number() OVER (PARTITION BY address ORDER BY salary DESC) FROM staff
```
Please implement the changes here as I told you in the previous comment.

2024-05-12 19:38 UTC, SaviDahegaonkar commented on content/postgresql/concepts/window-functions/window-functions.md
> +- The statement ends with `FROM staff`, signifying that it operates on the staff table.
``` suggestion
Breaking down the syntax:
- The clause `SELECT`, selects the `id`, `salary`, and `address` columns from the `_staff_` table.
- The `Row_number() OVER` part computes the row number of each row.
- The `(PARTITION BY address ORDER BY salary DESC)` clause actively defines how the window function partitions the data.
 - `PARTITION BY address` partitions the rows into groups based on values in the `address` column.
 - `ORDER BY salary DESC` allows the rows to be ordered by `salary` in descending order within each partition.
- The statement ends with `FROM staff`, signifying that it operates on the `_staff_` table.
```

2024-05-12 19:38 UTC, SaviDahegaonkar commented on content/postgresql/concepts/window-functions/window-functions.md
> +| 06 |  2500  | Dubai   |  1   |
```suggestion
## Output

| `id` | `salary` | `address` | `row_number` | 
|--- | -----  | -----   | ---- |
| 01 | 5500 | Tokyo |  1  |
| 04 | 3500 | Tokyo   |  2   |
| 08 | 2000 | Tokyo   |  3   |
| 07 | 4500 | Mumbai | 1  |
| 03 | 2500 | Mumbai | 2 |
| 02 |  5000  | Beijing | 1 |
| 05 |  4000  | Paris   | 1 |
| 06 |  2500  | Dubai | 1 |
```
Write a line saying `This is the output of the above query:` before the output.

2024-05-14 11:10 UTC, Johnnie-kay commented
Hello @SaviDahegaonkar, all corrections and suggestions have been attended to.

2024-05-15 20:54 UTC, SaviDahegaonkar commented
> Hello @SaviDahegaonkar, all corrections and suggestions have been attended to. 

Yes I will look into it.
Thank you.

2024-05-19 08:22 UTC, Johnnie-kay reviewed
I have reviewed the window-functions.md file and made all corrections

2024-05-19 09:48 UTC, mohitO12-dev approved these changes

2024-05-21 05:15 UTC, SaviDahegaonkar approved these changes

2024-05-21 11:11 UTC, merged