Pull request for Julia variables
Codecademy/docs pull request #4667
Opened 2024-05-18 00:21 UTC by msaf9

### Description

Pull request for Julia variables.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-18 06:46 UTC, mamtawardhani commented
Hey @msaf9! I don't see an issue raised for this particular PR. Could you please link the issue here for which you have submitted this PR?

2024-05-18 16:55 UTC, msaf9 commented
Hello @mamtawardhani, it's a typo that I have checked the `Issues Solved` section on the Checklist. This is a new entry.

2024-05-20 11:08 UTC, mamtawardhani requested changes
Hey @msaf9 thank you for contributing to the Codecademy Docs! The entry was well written! 

I've added a few suggestions and requested changes there, could you please review and modify those at your earliest convenience?
(Also, the `Constants` and `Scoping` can be another term entry, so I've asked to remove them from this. :) )
Thank you! 😄

2024-05-20 11:08 UTC, mamtawardhani commented on content/general/concepts/julia/terms/variables/variables.md
> +```
```suggestion
## Syntax
```pseudo
variable_name = value
```

- `variable_name`: This is the chosen name for the variable, following Julia's naming rules and conventions.
- `value`: Represents the data or value assigned to the variable, which can be of various types supported by Julia.
```

2024-05-20 11:08 UTC, mamtawardhani commented on content/general/concepts/julia/terms/variables/variables.md
> +```
These points are not needed for this term entry, rather have an `## Example` block to showcase an example of variable(s) declaration in Julia and print it, show this output using the ```shell block.
Also add a `## Codebyte Example` block at the end to show another example (this should not have an output block).

For adding the above point above the variable nomenclature in Julia, use the `Note` format as follows:
> **Note:** Give some information about variable nomenclature in Julia

2024-05-21 04:25 UTC, msaf9 commented
Hello @mamtawardhani, I have resolved all review comments. Please let me know if there is anything that I should address.

2024-05-21 07:49 UTC, mamtawardhani approved these changes
Looks good for a second review 👍

2024-05-21 20:05 UTC, msaf9 commented
Now the branch is upto date, could someone please merge it.

2024-05-29 05:49 UTC, Sriparno08 approved these changes
Looks good, @msaf9! 👍

2024-05-29 05:49 UTC, merged