[Edit] HTML Add Media: Links
Codecademy/docs pull request #4674
Opened 2024-05-20 13:42 UTC by htnweb

### Description

- Added images to links.md
- Added subsequent media to content/media

### Issue Solved

- Closes Issue #3231 

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-20 13:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4674) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4674) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4674) it.</sub>

2024-05-23 19:56 UTC, cigar-galaxy82 commented
Hey @htnweb 

Thank you for contributing to Codecademy Docs!

I've suggested a few changes modify them at your convenience

Thank you!

2024-05-23 21:03 UTC, htnweb commented
Hi @cigar-galaxy82  thank you for the suggestions,

I am away on holiday until next Friday, I can hopefully complete when I am back.

From looking at your suggestions I should have the media link/path on a separate line, and also in a different location ?

Thanks for your help.

2024-05-28 11:15 UTC, shukriarahimitech commented
@htnweb, I am interested in this issue.

2024-05-28 11:16 UTC, shukriarahimitech commented
@htnweb I am interested in this issue.

2024-06-03 10:06 UTC, htnweb commented
Hi @cigar-galaxy82 I have uploaded the images and changed the file paths in links.md

Thanks

2024-06-19 05:26 UTC, letsbuildanything commented
@cigar-galaxy82 Please approve this.

2024-06-19 05:47 UTC, cigar-galaxy82 approved these changes

2024-06-19 07:58 UTC, letsbuildanything requested changes
@htnweb 
I've listed below some changes. Please take a moment to address them. If you have any concerns or reasons to reject specific suggestions, feel free to discuss them.
1. Ensure that the images are screenshots of the outputs generated by the given HTML code in the browser, and place them below or after the given HTML code.

2. please upload all the required images to the [/media folder](https://github.com/Codecademy/docs/tree/main/media).

3. Please remove all the unnecessary images and replace them with appropriate ones.

2024-06-19 07:58 UTC, letsbuildanything commented on content/html/concepts/links/links.md
> +## Hyperlinks ![Hyperlink image](https://raw.githubusercontent.com/Codecademy/docs/main/media/hyperlink.png)
```suggestion
## Hyperlinks
```

2024-06-19 07:58 UTC, letsbuildanything commented on content/html/concepts/links/links.md
> +## Hyperlinks ![Hyperlink image](https://raw.githubusercontent.com/Codecademy/docs/main/media/hyperlink.png)
@htnweb Please remove all the image links added next to headings like this.

2024-06-26 14:27 UTC, ishg-153 commented
@htnweb It's been a week since @letsbuildanything suggested changes. Are you still working on them?

2024-06-26 20:04 UTC, htnweb commented
Hi , I've been a bit busy on another project. I will try and complete this on Friday.

Kind regards

2024-06-28 11:27 UTC, htnweb commented
@letsbuildanything  Hi, I think I have done the changes you suggested although I am unsure on if the file path's are correct.

Thanks

2024-06-30 14:33 UTC, ishg-153 commented
@letsbuildanything please look through this PR and approve changes.

2024-07-08 15:00 UTC, letsbuildanything commented
Hi @htnweb,
Please use this entry: https://github.com/Codecademy/docs/blob/main/content/html/concepts/lists/lists.md as a reference on what and how to include media or screenshots in this entry. 
- The output image should be the screenshot of the HTML code output. 
-  Images should not be added in-line with the paragraph.
- No images seem to be appropriate here. So please remove all of them.

If you have any questions or need further clarification, feel free to ask.

2024-07-16 09:25 UTC, htnweb commented
Hi @letsbuildanything I have added a screenshot of the html output, and removed the wrong media.

Thanks

2024-08-14 15:37 UTC, letsbuildanything approved these changes
LGTM! 🚀

2024-08-14 15:46 UTC, merged

2024-08-18 13:55 UTC, htnweb commented
Thanks for everyone's suggestions on this issue, was good fun. I will now delete the branch.