[Term Entry] Pillow fromarray
Codecademy/docs pull request #4684
Opened 2024-05-21 02:24 UTC by deenovita

### Description

I have added a new term entry for the .fromarray function from Pillow Library

### Issue Solved

Ask to close #4624 issue

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-22 10:20 UTC, SaviDahegaonkar requested changes
Hello Author,
I have reviewed the given file, and made some changes, You can have a look at it and let me know.
Thanks,
Savi

2024-05-22 10:20 UTC, SaviDahegaonkar commented on content/pillow/concepts/image/terms/fromarray/fromarray.md
> +
```suggestion
from PIL import Image
import numpy as np

# Defined an array 3 by 3 with 200 as all the pixel values
obj_array = np.full((3, 3), 200)

# Create an image from the array as our `obj_array` is stored in an  numbered array form.
new_imageA = Image.fromarray(obj_array, mode="CMYK")

# Show the pixel value by the coordinate
print(new_imageA.getpixel((0,0)))

```
imported the numpy library from python

2024-05-22 10:20 UTC, SaviDahegaonkar commented on content/pillow/concepts/image/terms/fromarray/fromarray.md
> +The result proves that the pixel in coordinate (0,0) has stored as `CMYK` combination colors with the values shows below.
```suggestion
The result proves that the pixel at coordinate (0,0) is stored as `CMYK` combination colors with the values shown below.
```

2024-05-22 10:20 UTC, SaviDahegaonkar commented on content/pillow/concepts/image/terms/fromarray/fromarray.md
> +The following Codebyte example demonstrates how to create a new image from array and stored it in `RGB` color format.
```suggestion
The following Codebyte example demonstrates how to create a new image from the array and store it in an `RGB` color format.
```
I have corrected the sentence dramatically. Keep in note to always keep the sentence as readable as possible.

2024-05-22 10:20 UTC, SaviDahegaonkar commented on content/pillow/concepts/image/terms/fromarray/fromarray.md
> +print(new_imageB.getpixel((0,0)))
```suggestion
``` pseudo
import numpy as np
from PIL import Image

# Defined an array 3 by 3 with 200 as all the pixel values
obj_array = np.full((3, 3, 3), 200)

# Create an image from the array
new_imageB = Image.fromarray(obj_array, mode="RGB")

# Show the pixel value by the coordinate
print(new_imageB.getpixel((0,0)))
```
```
I have added one more channel for RGB image representation as the array should have three channels per pixel.

2024-05-24 11:56 UTC, deenovita commented
Thank you @SaviDahegaonkar, I have made some changes as requested

2024-05-24 18:40 UTC, SaviDahegaonkar requested changes
Hello @deenovita ,
There is a mistake you have committed this year.lock file, this file needs to be uncommitted by you, please look at the changes and let me know.
Thanks




<body>
<!--StartFragment--><br class="Apple-interchange-newline"><table cellpadding="0" role="presentation" class="cf gJ" style="border-collapse: collapse; margin-top: 0px; width: auto; -webkit-font-smoothing: antialiased; font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: 0.875rem; letter-spacing: normal; display: block;"><tbody style="display: block;"><tr style="display: flex;"><td class="gF gK" style="margin: 0px; text-align: left; white-space: nowrap; padding: 0px; vertical-align: top; width: auto; line-height: 20px; display: block; max-height: 20px; color: rgb(119, 119, 119); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span translate="no" email="notifications@github.com" data-hovercard-id="notifications@github.com" name="Dewi Novita Sari" class="gD bco" role="gridcell" tabindex="-1" data-hovercard-owner-id="21" style="color: rgb(31, 31, 31); font-size: 0.875rem; font-weight: bold; white-space: nowrap; display: inline; vertical-align: top; padding-right: 3px; -webkit-font-smoothing: antialiased; font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; letter-spacing: normal; line-height: 20px;"><span style="position: relative; vertical-align: top;">Dewi Novita Sari</span></span><span class="cfXrwd"></span></td><br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>

2024-05-27 18:12 UTC, SaviDahegaonkar approved these changes
Hello Author, 
I am approving this file and this ready for second review now.

2024-05-28 10:25 UTC, deenovita commented
@SaviDahegaonkar Thank you!

2024-05-30 16:01 UTC, mamtawardhani commented
Hey @ishg-153 please do ask the author to add an output image for the entry. Thanks! 😄

2024-05-31 09:03 UTC, ishg-153 commented
@mamtawardhani Thank you so much for pointing that out!

2024-05-31 12:00 UTC, ishg-153 requested changes
@deenovita I have suggested some changes for you to work on. Please make those and let me know once you are done.

If you need any additional help please to ask.

2024-06-03 04:12 UTC, deenovita commented
@ishg-153  I have made the requested changes. Please let me know if there are any other changes I need to make. Thank you!

2024-06-04 06:19 UTC, ishg-153 approved these changes
@deenovita Great! This entry is now good to merge. 

I have also made some minor changes from my end.

2024-06-04 06:22 UTC, ishg-153 commented
@deenovita Note that I won't be merging this right away, as we are waiting for another PR to be merged before moving forward with this one. 

Please don't delete this PRs' corresponding branch till it's merged. There's no other change required from your end.

2024-06-04 07:52 UTC, deenovita commented
@ishg-153 Sure, thank you so much!

2024-06-08 17:56 UTC, ishg-153 commented
Merging

2024-06-08 17:56 UTC, merged