PostgreSQL constraints
Codecademy/docs pull request #4693
Opened 2024-05-23 12:39 UTC by LGVjr2

### Description

- Added the PostgreSQL Constraints.md
- described the main concept
- can you pls add the Tag 'Constraints'

### Issue Solved

-Closes #4646 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-23 12:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4693) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4693) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4693) it.</sub>

2024-05-23 18:12 UTC, SaviDahegaonkar requested changes
Hello Author, 
I made some changes in this file and suggested some changes, please have a look at [Codecademy docs](https://github.com/Codecademy/docs). Looking forward for your response.

Thanks

2024-05-23 18:12 UTC, SaviDahegaonkar commented on content/postgresql/concepts/constraints/constraints.md
> +  - 'paths/computer-science'
```suggestion
CatalogContent:
  - 'getting-started-off-platform-for-data-science'
  - 'paths/design-databases-with-postgresql'
  - 'paths/computer-science'
```
The paths which are present here in the CatalogContent section must be taken  from the Catalog-content.md file

2024-05-23 18:12 UTC, SaviDahegaonkar commented on content/postgresql/concepts/constraints/constraints.md
> +  );
CREATE TABLE students (
  student_id SERIAL PRIMARY KEY,
  age INT,
  --Is age between 18 and 45?
  CONSTRAINT age_test CHECK (age BETWEEN 18 AND 45)
  );

2024-06-07 13:06 UTC, LGVjr2 commented
@SaviDahegaonkar changes done. Pls review again.

2024-06-07 18:16 UTC, SaviDahegaonkar approved these changes

2024-06-17 17:09 UTC, Sriparno08 approved these changes
Looks good, @LGVjr2! 👍

2024-06-17 17:09 UTC, merged