[Topic Entry] Python: Pillow
Codecademy/docs pull request #4694
Opened 2024-05-23 16:35 UTC by mamtawardhani

### Description

Added a topic entry for the Pillow Library in Python.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [xx] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-23 18:46 UTC, Sriparno08 approved these changes
Looks good for a second review, @mamtawardhani! 👍

2024-05-23 19:45 UTC, letsbuildanything requested changes
@mamtawardhani suggested and made some changes. Please take a moment to review them.
Thank you.

2024-05-23 19:45 UTC, letsbuildanything commented on content/pillow/pillow.md
> +```py
```suggestion
```shell
```

2024-05-24 04:57 UTC, mamtawardhani commented
@letsbuildanything I've made the required changes! 💯

2024-05-24 06:03 UTC, letsbuildanything approved these changes
Ready to Merge! 🚀

2024-05-24 06:08 UTC, merged