Postgresql aggregate expressions
Codecademy/docs pull request #4695
Opened 2024-05-24 15:38 UTC by Johnnie-kay

### Description
Created a new concept entry for Postgresql aggregate-expressions.

### Issue Solved
Closes #4590 [Concept Entry] Postgresql aggregate-expressions

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-30 10:28 UTC, Johnnie-kay commented
Hello @Sriparno08, please review this PR. some chcks are still failling and i dont know how to correct it. Let us close this issue so i can get assigned to other issues.

2024-05-30 15:01 UTC, Sriparno08 commented
Hey @Johnnie-kay, your PR will be reviewed soon. In terms of the checks, the reviewers will handle them. So, don't worry about that.

2024-06-03 16:35 UTC, Sriparno08 requested changes
Hey @Johnnie-kay, thanks for contributing to Codecademy Docs!

I've listed all the modifications that you need to make in your entry below:

2024-06-03 16:35 UTC, Sriparno08 commented on content/postgresql/concepts/aggregate-functions/aggregate-functions.md
> +- `GROUP BY Customer` clause groups the results by the `Customer` column.
```suggestion
The `GROUP BY` clause groups the set of results, including the total amount spent by each customer, by the `Customer` column.
```

2024-06-03 16:35 UTC, Sriparno08 commented on content/postgresql/concepts/aggregate-functions/aggregate-functions.md
> +This is the out put of the above query:
```suggestion
Here is the output of the above query:
```

2024-06-03 16:35 UTC, Sriparno08 commented on content/postgresql/concepts/aggregate-functions/aggregate-functions.md
> +The `GROUP BY` clause in Postgresql is used to arrange identical data into groups. This clause is often combined with aggregate functions to perform operations on each group of data. Essentially, `GR
```suggestion
### GROUP BY

The `GROUP BY` clause in PostgreSQL is used to arrange identical data into groups. This clause is often combined with aggregate functions to perform operations on each group of data. Essentially, `GROUP BY` summarizes data by grouping rows that have the same values in the specified columns.
```

2024-06-05 07:54 UTC, closed without merging

2024-06-05 08:07 UTC, Johnnie-kay commented
Hello @Sriparno08, I had to deleted this branch to create another one... The name of the branch was creating a confusion for me. sorry for the inconviniences. I created another branch named 'aggregate-functions' for this issue.

2024-06-05 08:10 UTC, Johnnie-kay commented
All the changes and corrections has been applied to the new branch as well. Please review it again.

2024-06-05 08:10 UTC, Johnnie-kay commented
I think I found a wayb out of this confusion.

2024-06-05 10:09 UTC, Sriparno08 commented
Okay 👍