Postgresql collation expressions
Codecademy/docs pull request #4696
Opened 2024-05-24 16:09 UTC by Johnnie-kay

### Description
Created a new concept entry for Postgresql collation-expressions.

### Issue Solved
Closes #4651 [Concept Entry] Postgresql collation-expressions

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-30 10:25 UTC, Johnnie-kay commented
Hello @cigar-galaxy82, please review this PR so i can make corrections on it to close this issue and get assigned on another one.

2024-05-31 12:15 UTC, cigar-galaxy82 commented
Sure @Johnnie-kay I will complete this by today

2024-06-01 10:33 UTC, cigar-galaxy82 requested changes
Hi @Johnnie-kay 

I've suggested a few changes.  Also, make sure the Metadata is written properly

2024-06-01 10:33 UTC, cigar-galaxy82 commented on content/postgresql/concepts/collation-expressions/collation-expressions.md
> +| Width sensitive | `_WS` | Differentiates full width and half width characters present, if `_WS` wasn't mentioned then it is width-insensitive and hence full and half width characters will be consid
Use ### Example when showing code for each type collation

2024-06-01 10:36 UTC, cigar-galaxy82 commented
Hi @Johnnie-kay 

Thank you for contributing to Codecademy Docs!

I've suggested a few changes please modify. Also, make sure Metadata is  written correctly

Thank you!

2024-06-05 07:18 UTC, Johnnie-kay commented
Hello @cigar-galaxy82, good morninng. I have made all the marked out corrections and adjustments on this issue.

2024-06-12 19:35 UTC, Johnnie-kay commented
Hello @letsbuildanything, the asTimeZone entry file has been deleted.

2024-06-20 12:40 UTC, Johnnie-kay commented
Hello @letsbuildanything please review this PR.

2024-06-25 12:10 UTC, Johnnie-kay commented
Hello @cigar-galaxy82 is there anything else to do on this issue. please review and close this PR.

2024-06-25 14:06 UTC, cigar-galaxy82 approved these changes

2024-06-25 14:07 UTC, cigar-galaxy82 commented
hi @Johnnie-kay review from my side is done soon someone will do the second review, and then we will merge it

2024-07-01 16:07 UTC, Sriparno08 approved these changes
Looks good, @Johnnie-kay! 👍

2024-07-01 16:08 UTC, merged