[Term Entry] Javascript Method : .parseFloat()
Codecademy/docs pull request #4700
Opened 2024-05-26 07:34 UTC by filming

### Description

- Added the Number.parseFloat() term for Javascript

### Issue Solved
- Closes #4673 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-29 07:28 UTC, mamtawardhani requested changes
Hello @filming! Thank you for contributing to the Codecademy Docs! The entry is well written!

I've suggested a few changes in the entry, could you please review the suggestions given and modify the required parts at your earliest convenience? 
Thanks! 😄

2024-05-29 07:28 UTC, mamtawardhani commented on content/javascript/concepts/number-methods/terms/parseFloat/parseFloat.md
> +- `value` (required): The value to parse, which is [coerced to a string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#string_coercion). Leading whitespaces
```suggestion
- `value`: Refers to the input string that the function converts into a floating-point number.
```

2024-05-29 07:28 UTC, mamtawardhani commented on content/javascript/concepts/number-methods/terms/parseFloat/parseFloat.md
> +## Examples
```suggestion
## Example
```

2024-05-29 07:28 UTC, mamtawardhani commented on content/javascript/concepts/number-methods/terms/parseFloat/parseFloat.md
> +Converting a value to a floating point number:
```suggestion
The example below denotes the use of the `parseFloat` method to convert a value to a floating point number:
```

2024-05-29 07:28 UTC, mamtawardhani commented on content/javascript/concepts/number-methods/terms/parseFloat/parseFloat.md
> +
Please use a ```shell block to show the output and remove the comments from the code above.

2024-05-29 07:28 UTC, mamtawardhani commented on content/javascript/concepts/number-methods/terms/parseFloat/parseFloat.md
> +# Before executing the code, what do you believe the result will be?
```suggestion
```

2024-05-31 05:24 UTC, filming commented
@mamtawardhani I have made all of the suggested/requested changes to the branch. Please feel free to let me know if there's anything else that could be updated after another review.

2024-05-31 06:35 UTC, mamtawardhani approved these changes
Thank you for making the required changes @filming! 😃 

Looks good for a second review!

2024-05-31 17:59 UTC, letsbuildanything approved these changes
Ready to be Merged! 🚀

2024-05-31 18:01 UTC, merged