[Term Entry] Pillow library method: .Transpose()
Codecademy/docs pull request #4703
Opened 2024-05-27 09:54 UTC by DevIggor

### Description

-Added the .Transpose() term for Pillow
-Closes Issue #4625 
### Issue Solved

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-27 09:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4703) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4703) before we can accept your contribution.<br/><hr/>**DevIggor** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4703) it.</sub>

2024-05-29 16:54 UTC, DevIggor commented
@cigar-galaxy82 Hey 👋 I have already signed the CLA and my email is also linked in my account and my bash command line but I still get the message from the CLA Assistant. Is there anything wrong my contribution?

2024-05-31 06:40 UTC, cigar-galaxy82 commented
Hi @DevIggor  don't worry about the CLA sometimes our CLAassistant behaves unpredictably

2024-06-03 17:53 UTC, mamtawardhani commented
Hey @DevIggor, it seems like when you raised this PR, you were signed out of your GitHub account, I suppose. 
You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

Could you please fill this out?

2024-06-03 23:31 UTC, DevIggor commented
Hey @mamtawardhani 👋 Just rechecked my email and my github account, it's all setted up and my Email is also verified and linked to my account, I sign in and out just to make sure there's nothing wrong on my side

2024-06-04 03:26 UTC, cigar-galaxy82 requested changes
Hi, I have suggested a few changes please modify them

2024-06-04 03:26 UTC, cigar-galaxy82 commented on content/pillow/concepts/image/terms/transpose/transpose.md
> +```
I think it would be good if you could add a before and after image to show what kind of output one can expect after running this code

2024-06-04 03:26 UTC, cigar-galaxy82 commented on content/pillow/concepts/image/terms/transpose/transpose.md
> +  - 'paths/computer-science'
Also, add these two in CatalogContent
  - 'paths/data-science'
  - 'paths/data-science-foundations'

2024-06-04 03:26 UTC, cigar-galaxy82 commented on content/pillow/concepts/image/terms/transpose/transpose.md
> +The **.transpose()** method is used to flip or rotate an image in 90 degree steps.
```suggestion
The **.transpose()** method is used to flip or rotate an image in 90-degree steps.
```

2024-06-04 03:26 UTC, cigar-galaxy82 commented on content/pillow/concepts/image/terms/transpose/transpose.md
> +method – Possible values of method are
```suggestion
# Where possible values of the method are
```

2024-06-04 03:26 UTC, cigar-galaxy82 commented on content/pillow/concepts/image/terms/transpose/transpose.md
> +  - 'Libraries'
Add Pillow in the tags

2024-06-04 03:28 UTC, cigar-galaxy82 commented
Hey @DevIggor 

Thank you for contributing to Codecademy Docs! The entry is well written!

I've suggested a few changes please modify them

Thank you!

2024-06-04 09:25 UTC, DevIggor commented
> Hey @DevIggor
> 
> Thank you for contributing to Codecademy Docs! The entry is well written!
> 
> I've suggested a few changes please modify them
> 
> Thank you!

changes made, thank you for the feedback!. 

Btw CLAassistant's still not approvingm me 😔

2024-06-05 06:02 UTC, letsbuildanything commented
Hey @DevIggor,
It's important to resolve the CLAssistant warning before merging this PR. Please carefully follow the instructions provided by CLAassistant.
Thank you!

2024-06-05 06:28 UTC, mamtawardhani commented
@letsbuildanything I guess @DevIggor did the required steps, however it still doesn't work for him. Should he raise another PR and close this one, for quick closing of this issue? What do you suggest?

2024-06-05 08:11 UTC, letsbuildanything commented
Hey @DevIggor, I've noticed that you're using two different accounts::
1: Author: DevIggor <DevIggor.010110@gmail.com>
2: Author: Igor Junio <dev.iggor010110@gmail.com>

And, for this commit [Create term entry for transpose method in pillow](https://github.com/Codecademy/docs/pull/4703/commits/dcb2c29f1acb6062a600c73aecd3450b66a7131f), you've used the account linked with first email address(Author: DevIggor <DevIggor.010110@gmail.com>). Please ensure that you've signed the CLA using both the account.

2024-06-05 08:13 UTC, DevIggor commented
> Hey @DevIggor, I've noticed that you're using two different accounts:: 1: Author: DevIggor [DevIggor.010110@gmail.com](mailto:DevIggor.010110@gmail.com) 2: Author: Igor Junio [dev.iggor010110@gmail.com](mailto:dev.iggor010110@gmail.com)
> 
> And, for this commit [Create term entry for transpose method in pillow](https://github.com/Codecademy/docs/pull/4703/commits/dcb2c29f1acb6062a600c73aecd3450b66a7131f), you've used the account linked with first email address(Author: DevIggor [DevIggor.010110@gmail.com](mailto:DevIggor.010110@gmail.com)). Please ensure that you've signed the CLA using both the account.

Will do that now, thank you :)

2024-06-05 08:14 UTC, letsbuildanything commented
@mamtawardhani Let's wait for @DevIggor's response first to confirm if the issue persists. We can decide the next steps based on his feedback.

2024-06-05 09:16 UTC, letsbuildanything commented
@DevIggor Thank you for your cooperation!
Could you please check if your Git account is configured for this PR in your local terminal by using the following commands:
- `git config user.email`
- `git config user.name`
If these are not configured, please set them using the commands below:
`git config --global user.email <your_correct_email@example.com>`
`git config --global user.name <your_correct_username>`

2024-06-05 09:33 UTC, letsbuildanything commented
@DevIggor Now, If your Git account is configured with the same email, please try committing some minor changes to your file and pushing it to see if this resolves the issue.

If the problem persists, I recommend closing this PR and submitting a new one with all the necessary changes. Be sure to request a review from @cigar-galaxy82 on your new PR.

Thank you!

2024-06-05 16:52 UTC, DevIggor commented
> @DevIggor Now, If your Git account is configured with the same email, please try committing some minor changes to your file and pushing it to see if this resolves the issue.
> 
> If the problem persists, I recommend closing this PR and submitting a new one with all the necessary changes. Be sure to request a review from @cigar-galaxy82 on your new PR.
> 
> Thank you!

Minor changes made. Awaiting for review, In case this doesn't work I'll close this PR and will be submitting a new one.

2024-06-05 18:01 UTC, letsbuildanything commented
@DevIggor 
Please close this PR and resubmit a new one. Apologies for any inconvenience this may cause.

2024-06-06 08:12 UTC, closed without merging