[Term Entry] Javascript Method: .parseInt()
Codecademy/docs pull request #4729
Opened 2024-05-28 16:07 UTC by andersooi

### Description

- Added new term entry for Javascript `parseInt()` method

### Issue Solved

Closes #4672 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-05-30 17:25 UTC, letsbuildanything requested changes
@andersooi Thank you for contributing to Codecademy Docs!
I've requested some changes. Please take a moment to address them. If you have any concerns or reasons to reject specific suggestions, feel free to discuss them.

2024-05-30 17:25 UTC, letsbuildanything commented on content/javascript/concepts/number-methods/terms/parseInt/parseInt.md
> +Description: 'Parses a string argument and returns an integer of the specified radix (base).'
```suggestion
Description: 'Converts a string into an integer.'
```

2024-05-30 17:25 UTC, letsbuildanything commented on content/javascript/concepts/number-methods/terms/parseInt/parseInt.md
> +parseInt(myString, radix);
```suggestion
parseInt(string, radix);
```

2024-05-30 17:25 UTC, letsbuildanything commented on content/javascript/concepts/number-methods/terms/parseInt/parseInt.md
> +- `radix` (optional): An integer between 2 and 36 inclusive, representing the base of the numeral system to be used.
```suggestion
- `string`: The string to be parsed. Leading whitespace in the string is ignored.
- `radix` (optional): An integer between 2 and 36 that represents the base of the numeral system to be used. If not provided, the `radix` defaults to 10, except when the string starts with "0x" or "0X" (indicating a hexadecimal number).
```

2024-05-30 17:25 UTC, letsbuildanything commented on content/javascript/concepts/number-methods/terms/parseInt/parseInt.md
> +// z = 127 (hexadecimal 7F is 127 in decimal)
@andersooi 
print the output of `x`, `y` and `z` using `console.log()` here. Also, Add the output below this code block using ```shell

2024-05-30 17:25 UTC, letsbuildanything commented on content/javascript/concepts/number-methods/terms/parseInt/parseInt.md
> +parseInt('*123'); // NaN, first character of string must be a numeric digit
print the output using `console.log()` and add ouput block using ```shell below this. If possible, include this example in the above code block

2024-05-30 17:25 UTC, letsbuildanything commented on content/javascript/concepts/number-methods/terms/parseInt/parseInt.md
> +> **Note:** The above examples are non-exhaustive.
use clear and beginner-friendly terms. Please replace 'non-exhaustive' with a more easy-to-understand term.

2024-05-30 17:25 UTC, letsbuildanything commented on content/javascript/concepts/number-methods/terms/parseInt/parseInt.md
> +console.log(parseInt('abc123'));
If possible, please add comments to this code block.

2024-05-31 04:12 UTC, andersooi commented
@letsbuildanything I have made the changes based on your comments. Do let me know if there any additional changes that I should make

2024-05-31 09:28 UTC, letsbuildanything approved these changes
@andersooi Thank you for making the changes. It's now ready for the second round of review!

2024-05-31 13:06 UTC, mamtawardhani approved these changes
Hey @andersooi! Thank you for your contribution, the entry looks nice and is ready to get merged 😄

2024-05-31 13:48 UTC, merged