.symmetric_difference_update() issue number #4168
Codecademy/docs pull request #4733
Opened 2024-05-29 14:57 UTC by Ewa-Krysiak

### Description

-added the .symmetric_difference_update() method for python
-Closes issue number #4168

### Issue Solved

-Closes issue number #4168

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-29 14:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4733) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4733) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4733) it.</sub>

2024-05-31 15:03 UTC, letsbuildanything requested changes
@Ewa-Krysiak Thank you for contributing to the Codecademy Docs!
I've requested some changes. Please take a moment to address them. If you have any concerns or reasons to reject specific suggestions, feel free to discuss them.

2024-05-31 15:03 UTC, letsbuildanything commented on content/python/concepts/sets/terms/symmetric-difference-update/symmetric-difference-update.md
> +print(sweet_drawer_1)
```suggestion
sweet_drawer_1 = set(['lollipops', 'cheescake', 'gummy bears', 'chocolate', 'lemon bars'])
sweet_drawer_2 = set(['waffles', 'brownie', 'gummy bears', 'jelly beans', 'chocolate'])

sweet_drawer_1 ^= sweet_drawer_2

print(sweet_drawer_1)
```

2024-06-03 04:42 UTC, letsbuildanything approved these changes
@Ewa-Krysiak Thank you for making the changes!
It looks good for the second round of review.

2024-06-03 09:33 UTC, mamtawardhani approved these changes
Thank you for your contribution to the Codecademy Docs @Ewa-Krysiak!

The entry is ready to be merged! 😄

2024-06-03 09:33 UTC, merged