[Term Entry] JavaScript Strings .substr() #4726
Codecademy/docs pull request #4737
Opened 2024-05-31 05:28 UTC by charanelgile

### Description

Create substr.md, a new term entry for JavaScript .substr() String Method

### Issue Solved

Closes #4726

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-31 05:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4737) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4737) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4737) it.</sub>

2024-06-01 03:11 UTC, cigar-galaxy82 commented on content/javascript/concepts/strings/terms/substr/substr.md
> +
For this case where starting index is negative show a similar example like Example 1 and Example 2 and then combine all of them in the codebyte example

2024-06-01 03:11 UTC, cigar-galaxy82 commented on content/javascript/concepts/strings/terms/substr/substr.md
> +The `.substr()` method in JavaScript extracts a portion of a string, starting from a specified index position up to a given number of characters. The index count begins with zero.
```suggestion
The **`.substr()`** method in JavaScript extracts a portion of a string, starting from a specified index position up to a given number of characters. The index count begins with zero.
```

2024-06-01 03:11 UTC, cigar-galaxy82 commented on content/javascript/concepts/strings/terms/substr/substr.md
> +The `.substr()` method does not change the original string. Also, it can extract from the end of the string when provided with a negative starting index position.
First, mention that it can extract from the end of the string then mention that it does not change the original string

2024-06-01 03:12 UTC, cigar-galaxy82 commented
Hey @charanelgile 

Thank you for contributing to Codecademy Docs!

I've suggested a few changes please modify

Thank you!

2024-06-02 13:07 UTC, charanelgile commented
Hello @cigar-galaxy82.
Thank you for your suggestions. Just letting you know that I've already pushed my modifications based on them. 
Appreciate it.

2024-06-07 11:40 UTC, cigar-galaxy82 commented
hi @charanelgile there is still one change required can you please complete that so it is ready for next review

2024-06-10 01:04 UTC, charanelgile commented
Hello @cigar-galaxy82 , all suggested changes have been addressed / completed.
Please review. Thank you.

2024-06-10 13:17 UTC, mamtawardhani commented
@cigar-galaxy82 kindly approve the PR

2024-06-10 13:20 UTC, cigar-galaxy82 approved these changes

2024-06-11 06:53 UTC, mamtawardhani requested changes
Hey @charanelgile, thanks for contributing to the Codecademy Docs! The entry was well written.

I have suggested come changes for this entry, could you please review and modify those at your earliest convenience? Thank you! 😃

2024-06-11 06:53 UTC, mamtawardhani commented on content/javascript/concepts/strings/terms/substr/substr.md
> +---
```suggestion
---
Title: '.substr()'
Description: 'Extracts a portion of a string starting from a specified position extending up to a specified number of characters.'
Subjects:
  - 'Computer Science'
  - 'Web Development'
Tags:
  - 'Methods'
  - 'Strings'
CatalogContent:
  - 'introduction-to-javascript'
  - 'paths/front-end-engineer-career-path'
---
```

2024-06-11 06:53 UTC, mamtawardhani commented on content/javascript/concepts/strings/terms/substr/substr.md
> +The **`.substr()`** method in JavaScript extracts a portion of a string, starting from a specified index position up to a given number of characters. The index count begins with zero.
```suggestion
The **`.substr()`** method in JavaScript extracts a portion of a string, starting from a specified index position and extending for a specified number of characters. Indexing begins at zero.
```

2024-06-11 06:53 UTC, mamtawardhani commented on content/javascript/concepts/strings/terms/substr/substr.md
> +string.substr(startingIndex, length);
```suggestion
string.substr(start, length);
```

2024-06-11 06:53 UTC, mamtawardhani commented on content/javascript/concepts/strings/terms/substr/substr.md
> +- `length`: (optional) is the number of characters to extract.
```suggestion
- `start`: The index position in the string where extraction begins. If negative, it counts from the end of the string 
- `length`: The number of characters to extract. It is an optional parameter. If omitted, the extraction continues to the end of the string.
```

2024-06-11 06:53 UTC, mamtawardhani commented on content/javascript/concepts/strings/terms/substr/substr.md
> +
```suggestion
```

2024-06-11 06:53 UTC, mamtawardhani commented on content/javascript/concepts/strings/terms/substr/substr.md
> +```
Let's have all the 3 examples with different test cases in one, as follows:

## Example
```js
// Extracting a portion of a string with a specified length

var sentence1 = "The Intro to JavaScript is fun to learn."
console.log(sentence1.substr(4, 19));

// Extracting a portion of a string without a specified length
var sentence2 = "The Intro to JavaScript is fun to learn"
console.log(sentence2.substr(4));
```

Add all the 3 use cases (examples) in one block, you can use comments `//` to explain the use case in the code. 
For displaying the output, use the ```shell``` block after the ##Example block.

2024-06-11 06:53 UTC, mamtawardhani commented on content/javascript/concepts/strings/terms/substr/substr.md
> +Important Note: The `.substr()` method does not change the original string.
This line can be added at the end, after the code byte example in the format:

> Note: The `.substr()` method does not change the original string.

2024-06-13 17:22 UTC, mamtawardhani commented
Hey @charanelgile, could you please make the required changes at your earliest convenience, so that we can merge this PR?

2024-06-13 17:23 UTC, mamtawardhani commented on content/javascript/concepts/strings/terms/substr/substr.md
> +
Added this in the description of the parameter itself

2024-06-13 17:23 UTC, mamtawardhani commented on content/javascript/concepts/strings/terms/substr/substr.md
> +---
the subjects and tags have to be in alphabetical order.

2024-06-14 01:49 UTC, charanelgile commented
Hi there @mamtawardhani 
I pushed the latest changes based on your suggestions. Please check / review. 
Thank you.

2024-06-14 06:17 UTC, mamtawardhani approved these changes
The entry looks good for merging! 

Good job @charanelgile! 😄

2024-06-14 06:20 UTC, merged