Completed term entry for JS .padStart()
Codecademy/docs pull request #4739
Opened 2024-05-31 14:23 UTC by nbarnhouse

### Description

Completed term entry for JavaScript String term .padStart(). 

### Issue Solved

Closes #issue-number 4727

### Type of Change

- Adding a new entry

### Checklist

- [ x] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-05-31 14:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4739) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4739) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4739) it.</sub>

2024-06-01 06:19 UTC, mamtawardhani requested changes
Hey @nbarnhouse! Thank you for your contribution to Codecademy Docs! The entry was nicely written!

I've suggested a few changes for the entry and added some comments for the ##Example section, could you please review and modify those at your earliest convenience? Feel free to discuss any concerns.
Thank you! 😄

2024-06-01 06:19 UTC, mamtawardhani commented on content/javascript/concepts/strings/terms/padStart/padStart.md
> +---
```suggestion
---
Title: '.padStart()'
Description: 'Returns a new string of a specified length with the original string padded from the start with a given string.'
Subjects:
  - 'Computer Science'
  - 'Web Development'
Tags:
  - 'Methods'
  - 'Strings'
CatalogContent:
  - 'introduction-to-javascript'
  - 'paths/front-end-engineer-career-path'
---
```

2024-06-01 06:19 UTC, mamtawardhani commented on content/javascript/concepts/strings/terms/padStart/padStart.md
> +Takes an original string and returns a second string to the front in order to change the original string to a specified length.
```suggestion
In JavaScript, the **`.padStart()`** method returns a new string of a specified length, with the original string padded at the beginning with a given string (repeated if necessary) until the desired length is reached.
```

2024-06-01 06:19 UTC, mamtawardhani commented on content/javascript/concepts/strings/terms/padStart/padStart.md
> +originalString.padStart(targetLength, padString);
```suggestion
string.padStart(targetLength, padString);
```

2024-06-01 06:19 UTC, mamtawardhani commented on content/javascript/concepts/strings/terms/padStart/padStart.md
> +- `padString`, (optional) character or string value to pad the original string.
```suggestion
- `string`: The original string to be padded.
- `targetLength`: The desired length of the resulting string after padding.
- `padString`: The string to pad the original string with. If not provided, it defaults to a space (' ').
```

2024-06-01 06:19 UTC, mamtawardhani commented on content/javascript/concepts/strings/terms/padStart/padStart.md
> +```
I would suggest putting all these use cases in one example, you can have multiple `console.log` showcasing multiple outputs.
After this bloc, use the ```shell``` block to show the output, avoid writing the output comments in the code itself. You can have comments in the code to explain the particular padding.

2024-06-01 06:19 UTC, mamtawardhani commented on content/javascript/concepts/strings/terms/padStart/padStart.md
> +The following is runnable, and demonstrates the use of the `.padStart()` method:
```suggestion
The following example demonstrates the use of the `.padStart()` method:
```

2024-06-02 14:23 UTC, nbarnhouse reviewed
please let me know if there is anything else I need to adjust @mamtawardhani.

2024-06-03 05:43 UTC, mamtawardhani approved these changes
Thank you for making the required changes @nbarnhouse!

This looks good for a second review! 😃

2024-06-04 18:34 UTC, letsbuildanything approved these changes
Ready to be Merged! 🚀

2024-06-04 18:36 UTC, merged