[Term Entry] Python:NumPy Math Methods round
Codecademy/docs pull request #4743
Opened 2024-06-03 00:04 UTC by WillJeffries

### Description

-Added the numpy.round() method for python. 
-Closes issue #4708 

### Issue Solved

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-03 00:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4743) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4743) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4743) it.</sub>

2024-06-09 13:31 UTC, cigar-galaxy82 requested changes
Hi, I have suggested a few please modify

2024-06-09 13:31 UTC, cigar-galaxy82 commented on content/numpy/concepts/math-methods/terms/round/round.md
> +```
Give a line break between the Output and shell

2024-06-09 13:31 UTC, cigar-galaxy82 commented on content/numpy/concepts/math-methods/terms/round/round.md
> +```
Give a line break between the Output and shell

2024-06-09 13:31 UTC, cigar-galaxy82 commented on content/numpy/concepts/math-methods/terms/round/round.md
> +Output:
```suggestion
Output:
```

2024-06-09 13:31 UTC, cigar-galaxy82 commented on content/numpy/concepts/math-methods/terms/round/round.md
> +Output:
```suggestion
Output:
```

2024-06-09 13:31 UTC, cigar-galaxy82 commented on content/numpy/concepts/math-methods/terms/round/round.md
> +`np.round()` will round to the nearest even number. When exactly halfway between two numbers.
```suggestion
`np.round()` will round to the nearest even number. When exactly halfway between two numbers.
```

2024-06-09 13:31 UTC, cigar-galaxy82 commented on content/numpy/concepts/math-methods/terms/round/round.md
> +  - 'Arrays'
```suggestion
  - 'Arrays'
```

2024-06-09 13:31 UTC, cigar-galaxy82 commented on content/numpy/concepts/math-methods/terms/round/round.md
> +## Example 1
```suggestion
## Example 1
```

2024-06-09 13:31 UTC, cigar-galaxy82 commented on content/numpy/concepts/math-methods/terms/round/round.md
> +## Example 4
```suggestion
## Example 4
```

2024-06-09 13:32 UTC, cigar-galaxy82 commented
Hi @WillJeffries 

Thank you for contributing to Codecademy, I have suggested few changes please modify

2024-06-15 10:42 UTC, cigar-galaxy82 approved these changes

2024-06-15 13:39 UTC, mamtawardhani requested changes
Hey @WillJeffries! The entry was nicely written!

I've suggested a few changes for the entry, could you please review and modify those at your earliest convenience? Feel free to dicuss any concerns, thank you! 😄

2024-06-15 13:39 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/round/round.md
> +**`.round()`** is a function from the NumPy Python library. It rounds a number or an array of numbers to a specified number of decimal places.
```suggestion
In the NumPy library, the **`.round()`** method rounds a number or an array of numbers to a specified number of decimal places.
```

2024-06-15 13:39 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/round/round.md
> +**`.round()`** is a function from the NumPy Python library. It rounds a number or an array of numbers to a specified number of decimal places.
reframed the sentence to start with "In"

2024-06-15 13:39 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/round/round.md
> +numpy.round(array/number, decimal place, out)
```suggestion
numpy.round(array, decimals=0, out=None)
```

2024-06-15 13:39 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/round/round.md
> +- `out` is an optional output array which the result will feed into.
```suggestion
- `array`: Represents either a single number or an array of numbers. Each element, whether a float or integer, will be rounded.
- `decimal`: Optional parameter that specifies the number of decimal places to which the numbers or elements in the array will be rounded. The default value is 0, and it accepts both positive and negative integers.
- `out`: Optional parameter that allows specifying an output array where the rounded results will be stored. If not provided, a new array will be created to store the rounded values.
```

2024-06-15 13:39 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/round/round.md
> +> **Note:** Numpy is commonly imported as `import numpy as np`. This allows us to refer to `numpy` as `np`.
```suggestion
```

2024-06-15 13:39 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/round/round.md
> +> **Note:** Numpy is commonly imported as `import numpy as np`. This allows us to refer to `numpy` as `np`.
This note is not needed, it can be removed since it is covered in the concept entry of numpy

2024-06-15 13:39 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/round/round.md
> +> **Note:** `numpy.round()` will return an array without commas separating the elements. To see the output with commas use [`.repr()`](https://github.com/Codecademy/docs/blob/main/content/python/conc
This can be added in the introductory paragraph itself which is above the syntax

2024-06-15 13:39 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/round/round.md
> +> **Note:** `numpy.round()` will round to the nearest even number when exactly halfway between two numbers.
This also can be added in the introductory paragraph itself which is above the syntax

2024-06-15 13:39 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/round/round.md
> +## Example 1
We can have all the example use cases under one ##Example block only, which will be accompanied by one ```shell ``` block. Use comments to explain the codes (use cases)

2024-06-15 13:39 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/round/round.md
> +```
At the end, please add a ##Codebyte Example, it need not have a ```shell``` block after it

2024-06-18 15:18 UTC, mamtawardhani approved these changes
Thank you for making the required changes @WillJeffries! 😃 

The entry is ready to be merged! 🚀

2024-06-18 15:25 UTC, merged