Add Concepts: Keywords
Codecademy/docs pull request #4747
Opened 2024-06-04 07:02 UTC by Danielmnm1

### Description

- Added Concepts
- Added Keywords
- Added keywords.md describing the most important keywords in mysql and adding examples.

### Issue Solved

- Closes issue #4679 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-11 19:19 UTC, letsbuildanything requested changes
@Danielmnm1 
I've requested some changes. Please take a moment to address them. If you have any concerns or reasons to reject specific suggestions, feel free to discuss them.
Also, Please refer to [style-guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md). It is a general guide to entry standards, which will help reduce the number of potential edits that will further need to be made to your PR.

2024-06-11 19:19 UTC, letsbuildanything commented on content/mysql/concepts/keywords/keywords.md
> +### Example
@Danielmnm1, 
Please add two separate sections: ##Syntax and ##Example.
In the Example section, include a table with a small number of rows and columns. like:

``` sql
CREATE TABLE products (
    name VARCHAR(50),
    price DECIMAL(10, 2),
    quantity_in_stock INT
);

INSERT INTO products (name, price, quantity_in_stock) VALUES
('Product A', 19.99, 10),
('Product B', 5.99, 20),
('Product C', 49.99, 5);
```

2024-06-22 05:24 UTC, Danielmnm1 commented
I fixed the branch issue, please let me know your comments. Thank you.

2024-06-22 05:58 UTC, ishg-153 commented
@letsbuildanything Please check if your required changes are reflected.

2024-07-04 09:18 UTC, letsbuildanything requested changes
@Danielmnm1 I've requested some more changes. Please take a moment to address them. If you have any concerns or reasons to reject specific suggestions, feel free to discuss them.

2024-07-04 09:18 UTC, letsbuildanything commented on content/mysql/concepts/keywords/keywords.md
> +```
I suggest combining the use cases of different keywords into one comprehensive example. Like this:

> ## Example
> 
> The following example demonstrates the use of several MySQL keywords:
> 
> ```SQL
> -- Create a new table
> CREATE TABLE employees (
>     id INT AUTO_INCREMENT PRIMARY KEY,
>     first_name VARCHAR(50),
>     last_name VARCHAR(50),
>     position VARCHAR(100),
>     salary DECIMAL(10, 2),
>     hire_date DATE
> );
> 
> -- Insert a new employee
> INSERT INTO employees (first_name, last_name, position, salary, hire_date)
> VALUES ('John', 'Doe', 'Software Engineer', 75000.00, '2024-05-25');
> 
> -- Select specific employees
> SELECT first_name, last_name
> FROM employees
> WHERE position = 'Software Engineer';

```

- Feel free to edit and improve as needed.  
- Wherever possible, Please add the output section.

2024-07-17 09:10 UTC, letsbuildanything approved these changes
Hey @Danielmnm1,
Due to inactivity, I've proceeded by incorporating the requested changes.
It's ready for the second round of review.

2024-07-18 15:31 UTC, Sriparno08 approved these changes
Looks good, @Danielmnm1! 👍

2024-07-18 15:32 UTC, merged