Postgresql aggregate functions
Codecademy/docs pull request #4749
Opened 2024-06-05 07:58 UTC by Johnnie-kay

### Description

### Issue Solved

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-05 10:50 UTC, Johnnie-kay commented
Hello @Sriparno08 please review this pull request. Thanks

2024-06-11 19:55 UTC, cigar-galaxy82 requested changes

2024-06-11 19:55 UTC, cigar-galaxy82 commented on content/postgresql/concepts/aggregate-functions/aggregate-functions.md
> +In PostgreSQL, **aggregate functions** perform calculations across multiple rows of data and return a single result. These functions execute operations including counting, adding, finding the average
```suggestion
In PostgreSQL, **aggregate functions** perform calculations on a data set and return a single result. These functions include counting, adding, finding the average, and searching the maximum or minimum value(s) using the `SELECT` statement and the `GROUP BY` clause.
```

2024-06-11 19:55 UTC, cigar-galaxy82 commented on content/postgresql/concepts/aggregate-functions/aggregate-functions.md
> +- `AVG()`: Computes the average (or arithmetic mean) of all the input values.
```suggestion
- `AVG()`: Computes the average of all the input values.
```

2024-06-11 19:55 UTC, cigar-galaxy82 commented on content/postgresql/concepts/aggregate-functions/aggregate-functions.md
> +```
Give a line break after line 40 and line 43

2024-06-11 19:55 UTC, cigar-galaxy82 commented on content/postgresql/concepts/aggregate-functions/aggregate-functions.md
> +```
Give a line break after line 46 and line 49

2024-06-11 19:55 UTC, cigar-galaxy82 commented on content/postgresql/concepts/aggregate-functions/aggregate-functions.md
> +```
Give a line break after line 52 and line 55

2024-06-11 19:55 UTC, cigar-galaxy82 commented on content/postgresql/concepts/aggregate-functions/aggregate-functions.md
> +```
Give a line break after line 58 and line 61

2024-06-11 19:55 UTC, cigar-galaxy82 commented on content/postgresql/concepts/aggregate-functions/aggregate-functions.md
> +```
Give a line break after line 64 and line 67

2024-06-11 19:55 UTC, cigar-galaxy82 commented on content/postgresql/concepts/aggregate-functions/aggregate-functions.md
> +```
Give a line break after line 79

2024-06-11 19:55 UTC, cigar-galaxy82 commented on content/postgresql/concepts/aggregate-functions/aggregate-functions.md
> +### GROUP BY
Give a line break after line 70

2024-06-11 19:55 UTC, cigar-galaxy82 commented on content/postgresql/concepts/aggregate-functions/aggregate-functions.md
> +In PostgreSQL, **aggregate functions** perform calculations across multiple rows of data and return a single result. These functions execute operations including counting, adding, finding the average
Since it's not compulsory to use `GROUP BY` with Aggregate Functions mention that in practice we use `GROUP BY`

2024-06-11 19:55 UTC, cigar-galaxy82 commented on content/postgresql/concepts/aggregate-functions/aggregate-functions.md
> +This is the out put of the above query:
```suggestion
This is the output of the above query:
```

2024-06-11 19:58 UTC, cigar-galaxy82 commented
Hi @Johnnie-kay

Thank you for contributing to Codecademy docs.

I have suggested a few changes please modify.

2024-06-12 20:45 UTC, Johnnie-kay commented
Hello @cigar-galaxy82, all corrections and modifications has been attened to.

2024-06-15 10:33 UTC, cigar-galaxy82 approved these changes

2024-06-20 12:30 UTC, Johnnie-kay commented
Hello @Sriparno08 and @cigar-galaxy82 please review this PR again so we can close this issue and have time to work on other contributions

2024-06-20 12:43 UTC, cigar-galaxy82 approved these changes

2024-06-20 14:14 UTC, Sriparno08 approved these changes
Looks good, @Johnnie-kay! 👍

2024-06-20 14:16 UTC, merged