Pillow image module
Codecademy/docs pull request #4754
Opened 2024-06-06 13:06 UTC by MattiasBaldi

### Description

Created a concept entry for the image module in python pillow. Explained how to import it and what it can be used for using: https://pillow.readthedocs.io/en/stable/reference/Image.html

### Issue Solved

[Concept Entry] Python pillow - image module https://github.com/Codecademy/docs/issues/4621

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-06 13:09 UTC, mamtawardhani commented
Perfect @MattiasBaldi! See, you did it 😁 
Will review it in a couple of hours and add some suggestions, just review and modify those by today if possible.
Thanks!

2024-06-06 15:58 UTC, mamtawardhani requested changes
Hey @MattiasBaldi, thank you for contributing to the Codecademy Docs! The entry is nicely written!

I've just suggested the meta-data at the start, please commit that suggestion, and also, could you just change the file name, because the required bath is `docs/content/pillow/concepts/image/image.md`, but you have named the file as `imagemodule.md`. 
Could you please do the above two tasks at your earliest convenience? 
Thank you! 😄

2024-06-06 15:58 UTC, mamtawardhani commented on content/pillow/concepts/image/imagemodule.md
> +In Python, the Pillow library is an advanced image processing tool designed to simplify the manipulation and editing of images by providing a wide range of easy-to-use functions for tasks such as ope
```suggestion
---
Title: 'Image'
Description: 'The Image module in Pillow is used for image processing tasks in Python, offering functionalities like opening, editing, and saving images in different formats, as well as applying filters, resizing, and accessing pixel data.'
Subjects:
  - 'Computer Science'
  - 'Data Science'
  - 'Data Visualization'
Tags:
  - 'Images'
  - 'Modules'
  - 'Pilow'
CatalogContent:
  - 'learn-python-3'
  - 'paths/computer-science'
  - 'paths/data-science'
  - 'paths/data-science-foundations'
---

The **Image** module in Pillow, a popular Python library for image processing, provides a comprehensive suite of tools for opening, creating, manipulating, and saving images in various formats. It allows users to perform a wide range of operations such as resizing, cropping, rotating, and flipping images. Additionally, the module supports converting images between different modes (e.g., RGB to grayscale) and accessing or modifying individual pixels, making it a powerful and versatile tool for handling image data in Python applications.
```

2024-06-06 15:58 UTC, mamtawardhani commented on content/pillow/concepts/image/imagemodule.md
> +```
```suggestion
```

This statement imports the Image module specifically from the Pillow library, which is a fork of the Python Imaging Library (PIL).
```

2024-06-07 05:54 UTC, mamtawardhani approved these changes
@MattiasBaldi Thank you so much for making the required changes! 😄 

Looks good for a second review!

2024-06-07 08:37 UTC, Sriparno08 approved these changes
Looks good! 👍

2024-06-07 08:38 UTC, merged