solved the issue Python:NumPy Math Methods exp #4721
Codecademy/docs pull request #4755
Opened 2024-06-06 14:14 UTC by AlinaStepanov

### Description

Added new file exp.md with explanation of `exp` function, example  and code.

### Issue Solved

Closes #4721

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new-branch after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-06 17:27 UTC, mamtawardhani requested changes
Hey @AlinaStepanov! Thank you for contributing to the Codecademy Docs! The entry was well written! 😄 

I've suggested a few changes for this entry, could you please review and modify those at your earliest convenience? Thank you! 😃

2024-06-06 17:27 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/exp/exp.md
> +# `exp`
```suggestion
---
Title: '.exp()'
Description: 'Computes the exponential of all elements in the input array'
Subjects:
  - 'Computer Science'
  - 'Data Science'
Tags:
  - 'Arrays'
  - 'Functions'
  - 'NumPy'
CatalogContent:
  - 'learn-python-3'
  - 'paths/data-science'
---
```

2024-06-06 17:27 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/exp/exp.md
> +
```suggestion
```

2024-06-06 17:27 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/exp/exp.md
> +The `exp` function in NumPy is used to calculate the exponential of all elements in the input array. This function is a part of the NumPy library, which is widely used for numerical computing in Pyth
```suggestion
The **`.exp`** function in NumPy calculates the exponential of all elements in the input array. As a part of the NumPy library, which is widely used for numerical computing in Python, this function is particularly useful in scientific computations where exponential functions are common.
```

2024-06-06 17:27 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/exp/exp.md
> +numpy.exp(arr)
```suggestion
numpy.exp(arr, out = None, where = True, casting = ‘same_kind’, order = ‘K’, dtype = None)
```

2024-06-06 17:27 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/exp/exp.md
> +- `arr`: Input array. The elements of the array can be any real numbers.
Please also add the description of the other parameters as well.

2024-06-06 17:27 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/exp/exp.md
> +The `exp` function computes the exponential of each element in the input array `arr`. The exponential function, \(\exp(x)\), returns \(e^x\), where \(e\) is Euler's number (approximately 2.71828).
```suggestion
>**Note:** The `.exp()` function computes the exponential of each element in the input array array. The exponential function, `.exp(𝑥)`, returns `e^x` , where `𝑒` is Euler's number, approximately 2.71828. 
```

2024-06-06 17:27 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/exp/exp.md
> +Here is an example demonstrating the use of the `exp` method:
```suggestion
Here is an example demonstrating the use of the `.exp()` function:
```

2024-06-06 17:27 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/exp/exp.md
> +### Output
```suggestion
The code above produces the following output:
```

2024-06-06 17:27 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/exp/exp.md
> +# Calculate the exponential of each element in the array
```suggestion
# Compute the exponential of each element in the array
```

2024-06-06 17:27 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/exp/exp.md
> +## Python Codebyte
```suggestion
## Codebyte Example
```

2024-06-06 17:27 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/exp/exp.md
> +```python
```suggestion
```pseudo
```

2024-06-06 17:27 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/exp/exp.md
> +```python
```suggestion
```py
```

2024-06-06 17:27 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/exp/exp.md
> +```python
```suggestion
```codebyte/python
```

2024-06-06 17:27 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/exp/exp.md
> +print("Exponential of input array:", result)
Please change the codebyte example, the example and codebyte example can't be the same. Use a different code (or values) for the codebyte example.

2024-06-06 17:27 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/exp/exp.md
> +By following these steps, you can easily use the `exp` function in NumPy to perform exponential calculations on arrays.
```suggestion
```

2024-06-07 05:17 UTC, mamtawardhani approved these changes
@AlinaStepanov Thank you for making the changes! Looks good for a second review! 😄

2024-06-13 16:21 UTC, Sriparno08 approved these changes
Looks good, @AlinaStepanov! 👍

2024-06-13 16:22 UTC, merged