[Term Entry] Python:NumPy Math Methods sin
Codecademy/docs pull request #4760
Opened 2024-06-10 09:32 UTC by andersooi

### Description

- Added new term entry for Python:NumPy Math Methods `sin`

### Issue Solved

Closes #4714  

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-06-10 16:31 UTC, letsbuildanything commented
@andersooi, please delete the `.at()` entry file, as you already have a separate PR for it.

2024-06-21 18:03 UTC, letsbuildanything requested changes
@andersooi Thank you for contributing to the Codecademy Docs!
I've requested some changes. Please take a moment to address them. If you have any concerns or reasons to reject specific suggestions, feel free to discuss them.

2024-06-21 18:03 UTC, letsbuildanything commented on content/numpy/concepts/math-methods/terms/sin/sin.md
> +np.sin(array, where=array >= np.pi/2, out=result)
```suggestion
np.sin(array)
```

2024-06-23 16:48 UTC, letsbuildanything approved these changes
@andersooi Thank you for making the changes.
Ready for the Second round of Review!

2024-06-24 08:46 UTC, mamtawardhani requested changes
Hey @andersooi, thank you for contributing to docs! 

I've suggested a few changes, could you please review and modify them at your earliest convenience? Thank you! 😄

2024-06-25 15:55 UTC, mamtawardhani approved these changes
Thank you for contributing to docs @andersooi! 😄 

The entry is ready to be merged! 🚀

2024-06-25 15:57 UTC, merged