[Term Entry] Dart Type Conversion .toStringAsPrecision()
Codecademy/docs pull request #4762
Opened 2024-06-11 13:46 UTC by tomasbaublys

### Description

- Added Dart Type Conversion .toStringAsPrecision()
- Closes Issue ##4567

### Issue Solved

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-18 08:28 UTC, cigar-galaxy82 requested changes
Hi, I have suggested a few changes

2024-06-18 08:28 UTC, cigar-galaxy82 commented on content/dart/concepts/type-conversion/terms/toStringAsPrecision/toStringAsPrecision.md
> +Description: 'Converts this number to a double and returns a string representation of that value.'
```suggestion
Description: 'Converts a number to a double and returns a string representation with the given precision significant digits.'
```

2024-06-18 08:28 UTC, cigar-galaxy82 commented on content/dart/concepts/type-conversion/terms/toStringAsPrecision/toStringAsPrecision.md
> +```
The reason for this in the code block the code should run just by copying and pasting it

2024-06-18 08:28 UTC, cigar-galaxy82 commented on content/dart/concepts/type-conversion/terms/toStringAsPrecision/toStringAsPrecision.md
> +The following examples illustrates how the `.toStringAsPrecision()` method is utilized to convert this number to a double and returns a string representation of that value:
```suggestion
The following examples illustrate how the `.toStringAsPrecision()` method is utilized to convert this number to a double and returns a string representation of that value:
```

2024-06-18 08:28 UTC, cigar-galaxy82 commented on content/dart/concepts/type-conversion/terms/toStringAsPrecision/toStringAsPrecision.md
> +In Dart, **`.toStringAsPrecision()`** is an abstract method used to convert this number to a `double`. This method returns a string representation of that value with exactly precision significant dig
```suggestion
In Dart, **`.toStringAsPrecision()`** is an abstract method used to convert this number to a `double`. This method returns a string representation of that value with exact precision significant digits.
```

2024-06-18 08:28 UTC, cigar-galaxy82 commented on content/dart/concepts/type-conversion/terms/toStringAsPrecision/toStringAsPrecision.md
> +1234567.toStringAsPrecision(9);
```suggestion
void main() {
  String a1 = 1.toStringAsPrecision(2);
  print("Output = " + a1);
  String a2 = 1e15.toStringAsPrecision(3);
  print("Output = " + a2);
  String a3 = 1234567.toStringAsPrecision(9);
  print("Output = " + a3);
}
```

2024-06-18 08:29 UTC, cigar-galaxy82 commented
Hi @tomasbaublys 

Thank you for contributing to Codecademy docs, the entry is well written I have suggested a few changes please modify

2024-06-20 11:53 UTC, mamtawardhani commented
Hey @tomasbaublys! Could you please make the required changes at your earliest convenience?

2024-06-20 18:08 UTC, tomasbaublys commented
> Hey @tomasbaublys! Could you please make the required changes at your earliest convenience?

@mamtawardhani I already comited required changes

2024-06-27 02:20 UTC, cigar-galaxy82 approved these changes

2024-06-27 09:54 UTC, mamtawardhani approved these changes
Thank you for the contribution @tomasbaublys!  😃 
The entry is ready to be merged! 🚀

2024-06-27 10:01 UTC, merged