Solving #4558
Codecademy/docs pull request #4765
Opened 2024-06-12 07:45 UTC by KarinaNi

### Description
 I documented plotly scatter() 

### Issue Solved
Solved #4558 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x ] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-12 07:47 UTC, mamtawardhani commented
Hey @KarinaNi, finally the PR is here 😁
However, as I can see, there are 16 files here, could you please remove the other files and keep only the scatter.md and the output images please?

2024-06-12 07:48 UTC, mamtawardhani commented
I would also suggest you to rename the feature branch, instead of main name it something else to avoid any confusion.

2024-06-12 07:57 UTC, KarinaNi commented
okay, so I will rename my main branch. I don't know how to remove the files, from the PR.

2024-06-12 08:18 UTC, mamtawardhani commented
While staging I suppose only add the required files.

2024-06-12 09:02 UTC, KarinaNi commented
how about now? @mamtawardhani

2024-06-12 10:37 UTC, mamtawardhani commented
> how about now? @mamtawardhani

Perfect! Will review it now, if any changes needed, I'll ask you. Thanks 😄

2024-06-12 11:08 UTC, mamtawardhani requested changes
Hey @KarinaNi two things to take care here:
(1) Please create a feature-branch using the `git checkout branch_name` and shift this entry on a feature branch and then continue. Refer to the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) for that, specificaaly the "getting setup on your computer" point.
(2) I've suggested a few changes, please review and modify those at your earliest convenience 😄 
Thank you!

2024-06-12 11:08 UTC, mamtawardhani commented on content/plotly/concepts/express/terms/scatter/scatter.md
> +Output:
```suggestion
The code above produces the following output:
```

2024-06-12 11:08 UTC, mamtawardhani commented on content/plotly/concepts/express/terms/scatter/scatter.md
> +fig = px.scatter(x, y, color=color, symbol=symbol, title = "Scatter Plot with Colors and Symbols")
```suggestion
fig = px.scatter(x=x, y=y, color=color, symbol=symbol, title = "Scatter Plot with Colors and Symbols")
```

2024-06-12 11:13 UTC, mamtawardhani commented
@KarinaNi I would suggest you first make the requested changes in this PR, then do the following steps to ensure that you create a new feature branch and also your content is transferred to it:

1. Create a new feature branch from your main branch:
git checkout -b feature-branch-name

2. Push the new branch to the (forked) remote repository:
git push origin feature-branch-name

3. Open your PR and change the base branch to the new feature branch:
- Go to the Pull Requests page in your repository on GitHub.
- Open the PR you created.
- Click the "Edit" button next to the PR title.
- Change the base branch from main to feature-branch-name.
- Save the changes.

4. Switch back to the main branch and reset it to the state before the PR changes:
git checkout main
git reset --hard origin/main

5. Ensure the main branch is clean and force push to update the remote main branch:
git push origin main --force

6. Continue working on your feature branch and push any further changes:
git checkout feature-branch-name
# Make your changes
git add .
git commit -m "Your commit message"
git push origin feature-branch-name

2024-06-14 06:19 UTC, mamtawardhani commented on content/plotly/concepts/express/terms/scatter/scatter.md
> +The scatter function **scatter()** in the Plotly library that creates a scatter plot to visualize the relationship between variables using markers on the Cartesian plane.
reframed it to sound better

2024-06-14 06:19 UTC, mamtawardhani commented on content/plotly/concepts/express/terms/scatter/scatter.md
> +
this will be helpful for the syntax since we are not adding all the parameters

2024-06-14 06:39 UTC, KarinaNi commented on content/plotly/concepts/express/terms/scatter/scatter.md
> +
can i commit suggestion? or make the changes myself and then commit it?

2024-06-14 07:05 UTC, KarinaNi commented
Rest of the changes need to be done with the new branch and the instructions above. And my forked repo is [24 commits ahead of](https://github.com/KarinaNi/docs/compare/Codecademy%3Adocs%3Amain...main), [6 commits behind](https://github.com/KarinaNi/docs/compare/main...Codecademy%3Adocs%3Amain) Codecademy/docs:main. so I don't know if making changes and pushing there in a different branch would achieve changes here

2024-06-14 07:10 UTC, mamtawardhani commented
> Rest of the changes need to be done with the new branch and the instructions above. And my forked repo is [24 commits ahead of](https://github.com/KarinaNi/docs/compare/Codecademy%3Adocs%3Amain...main), [6 commits behind](https://github.com/KarinaNi/docs/compare/main...Codecademy%3Adocs%3Amain) Codecademy/docs:main. so I don't know if making changes and pushing there in a different branch would achieve changes here. I will try to do it today.

Would you like to raise a new PR then? If yes, just make sure you follow the suggestions I've provided here. Let me know if you make a new PR 😄

2024-06-15 08:43 UTC, mamtawardhani commented
> > Rest of the changes need to be done with the new branch and the instructions above. And my forked repo is [24 commits ahead of](https://github.com/KarinaNi/docs/compare/Codecademy%3Adocs%3Amain...main), [6 commits behind](https://github.com/KarinaNi/docs/compare/main...Codecademy%3Adocs%3Amain) Codecademy/docs:main. so I don't know if making changes and pushing there in a different branch would achieve changes here. I will try to do it today.
> 
> Would you like to raise a new PR then? If yes, make sure you follow the suggestions I've provided here. Let me know if you make a new PR 😄

@KarinaNi please let me know about this.

2024-06-15 10:36 UTC, KarinaNi commented
Hi, I am a bit lost. If i make the suggested changes in this PR, even if my branch is 6 commits behind. would it still reflect the changes here?

2024-06-15 10:52 UTC, KarinaNi commented
I made some changes @mamtawardhani could you see if those made it here

2024-06-15 11:20 UTC, mamtawardhani commented
> I made some changes @mamtawardhani could you see if those made it here

The changes are visible 😃
But the issue is with the branch, you have committed the changes from the main branch, you need to create a feature branch for a PR, so could you do that? I have shared the steps above.

2024-06-15 12:25 UTC, mamtawardhani commented
Hey @KarinaNi

the issue is with the branch, you have committed the changes from the main branch, you need to create a feature branch for a PR, so could you do that? I have shared the steps above.

2024-06-17 06:20 UTC, mamtawardhani commented
Hey @KarinaNi, I would suggest you create another PR and close this one, since you are not able to shift the content to a feature branch. 
Just make sure that in the new PR, you have the content on the feature branch 😃

2024-06-19 07:12 UTC, mamtawardhani commented
Hey @KarinaNi!

Closing this PR since it is on the main branch.
Requesting you to please create a new PR, make sure you create a feature branch in that, and then edit the file on that feature branch. Refer to [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). 
Once you create a new PR, please let me know. Thanks! 😃

2024-06-19 07:12 UTC, closed without merging