Add files via upload
Codecademy/docs pull request #4768
Opened 2024-06-12 18:22 UTC by Jfri3ss

### Description

### Issue Solved

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-12 18:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4768) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4768) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4768) it.</sub>

2024-06-12 18:24 UTC, Jfri3ss commented
I am still learning here. 

I am making this comment for the CodeCademy Docs; I created a NumPy cos document.

2024-06-12 19:11 UTC, Jfri3ss commented
@mamtawardhani I was assigned an issue with this commit but I forgot to link it. My mistake.

2024-06-12 19:13 UTC, Jfri3ss reviewed
Removed text from bottom of the file.

2024-06-13 17:00 UTC, mamtawardhani commented
Hey @Jfri3ss you'll have to change the path of the file, the path needed is: `docs/content/numpy/concepts/math-methods/terms/cos/cos.md.` Please modify it as soon as possible, thanks! 😃

2024-06-14 05:53 UTC, mamtawardhani commented
Hey @Jfri3ss, let me know once you correct the path, I'll start the review 😄

2024-06-14 13:28 UTC, Jfri3ss commented
@mamtawardhani I changed the path two differnt ways. Perhapse accept the last update to the file path. You can discared the frist one.

Still learning as always, thanks for helping me learn!

2024-06-14 14:31 UTC, mamtawardhani commented
That is great! Will review it in a few hours @Jfri3ss. Thank you for your efforts 😃

2024-06-15 12:23 UTC, mamtawardhani requested changes
Hey @Jfri3ss! Thank you for contributing to the codecademy docs! The entry is well written!

I've suggested a few changes for the entry, could you please review and modify those at your earliest convenience? Feel free to dicuss any concerns, thank you! 😄

2024-06-15 12:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/cos/cos.md
> +---
```suggestion
---
Title: '.cos()'
Description: 'Computes the cosine of each element in an array or a single value.'
Subjects:
  - 'Computer Science'
  - 'Data Science'
Tags:
  - 'Arrays'
  - 'NumPy'
CatalogContent:
  - 'learn-python-3'
  - 'paths/computer-science'
---
```

2024-06-15 12:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/cos/cos.md
> +---
The description could be modified as given above, and just add two relatable tags for any PR

2024-06-15 12:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/cos/cos.md
> +In NumPy, the **cos** function computes the cosine of each element in an array. This trigonometric function is essential for various mathematical computations, especially in physics, engineering, com
```suggestion
In NumPy, the **`.cos()`** function computes the cosine of each element in an array. This trigonometric function is essential for various mathematical computations, especially in physics, engineering, computer graphics, signal processing, and more.
```

2024-06-15 12:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/cos/cos.md
> +In NumPy, the **cos** function computes the cosine of each element in an array. This trigonometric function is essential for various mathematical computations, especially in physics, engineering, com
In a PR, whenever you introduce the term that you have written a PR for, make sure it is in **bold**, and if its a term like this one make sure it is in backticks(` `) and bold, like: **`.cos()`**

2024-06-15 12:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/cos/cos.md
> +The generic syntax for the NumPy math methods is as follows:
```suggestion
```

2024-06-15 12:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/cos/cos.md
> +The generic syntax for the NumPy math methods is as follows:
This line can be removed since we already have a heading for this.

2024-06-15 12:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/cos/cos.md
> +numpy.cos(argument)
This is not the correct syntax, please re-check this once, the correct syntax is:
`numpy.cos(array, out = None, dtype = None)`

2024-06-15 12:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/cos/cos.md
> +- `argument`: The array of angles (in radians) on which the cos function is applied to compute the cosine values.
Please describe the correct parameters based on the correct syntax, example:
- `array`: describe this parameter
- `out`: describe this parameter
- `where`: describe this parameter

2024-06-15 12:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/cos/cos.md
> +The output of the above code is shown below:
```suggestion
The above code generates the output as below:
```

2024-06-15 12:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/cos/cos.md
> +The output of the above code is shown below:
The sentence earlier was plagiarised.

2024-06-15 12:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/cos/cos.md
> +- Inverse Tangent `numpy.arctan()`: Computes the inverse tangent of each element in the array.
These can be removed since this is only a term entry for the `.cos()` function

2024-06-15 12:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/cos/cos.md
> +The below example shows the `np.cos()` method in use:
```suggestion
The below example shows the `.cos()` function in use:
```

2024-06-18 15:55 UTC, mamtawardhani approved these changes
Thank you for making the changes @Jfri3ss! The entry looks good for a second round of review. 😃

2024-06-19 14:12 UTC, Jfri3ss commented on content/numpy/concepts/math-methods/terms/cos/cos.md
> +
@ishg-153  Perfect great update, I created another pull request with the updated changes and requested to merge.

2024-06-19 14:22 UTC, ishg-153 commented
@Jfri3ss I don't see a new PR. Also please do not create a new PR. You can just make the updates on this same branch of your fork `py-math-functions-cos` and commit and push the changes.

2024-06-19 14:34 UTC, Jfri3ss commented
> @Jfri3ss I don't see a new PR. Also please do not create a new PR. You can just make the updates on this same branch of your fork `py-math-functions-cos` and commit and push the changes.

Gotcha still learning the process. Thank you.

2024-06-19 14:37 UTC, Jfri3ss reviewed
Added corrected descriptions based on the updated sudo syntax, updated the header and added a line before the second code example on line 53.

2024-06-19 14:49 UTC, ishg-153 approved these changes
@Jfri3ss Great! This PR is now ready to merge.

2024-06-19 19:01 UTC, Jfri3ss reviewed
Finished Edits

2024-06-20 09:55 UTC, merged