Py pillow image filter
Codecademy/docs pull request #4774
Opened 2024-06-14 15:10 UTC by cbjazzguitar

### Description

- added the image filter() method for python
- Closes issue #4722
### Issue Solved

### Type of Change

- Adding a new entry

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-14 15:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4774) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4774) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4774) it.</sub>

2024-06-14 18:35 UTC, mamtawardhani commented
@cbjazzguitar please sign the CLA from the above comment. Thanks! 😁

2024-06-15 11:37 UTC, mamtawardhani requested changes
Hey @cbjazzguitar, the entry seems to be half done, there's no content in it. Could you please add the required content? Thank you!

2024-06-15 14:13 UTC, cbjazzguitar commented
￼

> On Jun 15, 2024, at 7:38 AM, Mamta Wardhani ***@***.***> wrote:
> 
> 
> @mamtawardhani requested changes on this pull request.
> 
> Hey @cbjazzguitar <https://github.com/cbjazzguitar>, the entry seems to be half done, there's no content in it. Could you please add the required content? Thank you!
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/Codecademy/docs/pull/4774#pullrequestreview-2120355627>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/BIXOONTS6AYSJ5SNFRH573LZHQRRVAVCNFSM6AAAAABJKRD3FSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMRQGM2TKNRSG4>.
> You are receiving this because you were mentioned.
>

2024-06-18 17:25 UTC, closed without merging