[Term Entry] Java ArrayList .listiterator() #4341
Codecademy/docs pull request #4776
Opened 2024-06-14 20:11 UTC by selenahuang017

### Description

Adds an additional term entry for Java ArrayList listiterator under the file path content/java/concepts/array-list/terms/listiterator/listiterator.md

### Issue Solved

Addresses: [Term Entry] Java ArrayList .listiterator() #4341 [https://github.com/Codecademy/docs/issues/4341](url)

### Type of Change

- Adding a new entry

### Checklist

- [ x] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-14 20:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4776) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4776) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4776) it.</sub>

2024-06-15 06:46 UTC, letsbuildanything commented
@selenahuang017 @selena-huang
Please sign the CLA using both accounts. We can begin the review process once this is completed.

2024-06-17 01:31 UTC, selenahuang017 commented
I've signed them :)

2024-06-21 15:40 UTC, selenahuang017 commented
@letsbuildanything @mamtawardhani just checking on the status of this, is there anything else I need to do?

2024-06-21 20:09 UTC, letsbuildanything requested changes
@selenahuang017 Thank you for contributing to the Codecademy Docs!
I've requested some changes. Please take a moment to address them. If you have any concerns or reasons to reject specific suggestions, feel free to discuss them.

2024-06-21 20:09 UTC, letsbuildanything commented on content/java/concepts/array-list/terms/listiterator/listiterator.md
> +    ListIterator<String> it = arrayList.listiterator(2);
```suggestion
    ListIterator<String> it = arrayList.listIterator(2);
```

2024-06-21 20:09 UTC, letsbuildanything commented on content/java/concepts/array-list/terms/listiterator/listiterator.md
> +    while (it.hasNext) {
```suggestion
    while (it.hasNext()) {
```

2024-06-21 20:09 UTC, letsbuildanything commented on content/java/concepts/array-list/terms/listiterator/listiterator.md
> +    System.out.println("Arraylist size:" + arraylist.size());
```suggestion
    System.out.println("ArrayList size: " + arrayList.size());
```

2024-06-21 20:09 UTC, letsbuildanything commented on content/java/concepts/array-list/terms/listiterator/listiterator.md
> +        ListIterator<String> it = arrayList.listiterator(5);
```suggestion
        ListIterator<String> it = arrayList.listIterator(5);
```

2024-06-21 20:09 UTC, letsbuildanything commented on content/java/concepts/array-list/terms/listiterator/listiterator.md
> +Exception thrown : java.lang.IndexOutOfBoundsException: Index: 5
```suggestion
ArrayList size: 4
Exception: java.lang.IndexOutOfBoundsException: Index: 5, Size: 4
```

2024-06-22 16:53 UTC, selenahuang017 reviewed
Updating java listiterator term as per feedback.
Edit: oops I didn't realize this was just a comment, I have updated the commit

2024-06-23 06:33 UTC, letsbuildanything approved these changes
@selenahuang017 Thank you for making the changes.
Ready for the second round of review!

2024-06-28 19:24 UTC, selenahuang017 commented
just checking in here, it looks like it needs maintainer approval @mamtawardhani , is there anyone I should reach out to?

2024-06-29 03:52 UTC, mamtawardhani commented
> just checking in here, it looks like it needs maintainer approval @mamtawardhani , is there anyone I should reach out to?

Hey @selenahuang017, this entry is in a second round of review, it will be done ASAP, don't worry.

2024-07-02 18:08 UTC, ishg-153 requested changes
@selenahuang017 Great entry! Please make this one change. Let me know once you are done.

2024-07-02 18:08 UTC, ishg-153 commented on content/java/concepts/array-list/terms/listiterator/listiterator.md
> +Description: 'Returns a ListIterator over the elements in ArrayList.'
```suggestion
Description: 'Iterates over the elements in an ArrayList in both directions.'
```

2024-07-08 11:09 UTC, mamtawardhani commented
@ishg-153 seems like the changes are done, you can check and merge this

2024-07-11 09:57 UTC, ishg-153 approved these changes
@selenahuang017 Great! This is ready to merge.

2024-07-11 10:00 UTC, merged