Completed [Term Entry] Python:NumPy Math Methods degrees
Codecademy/docs pull request #4784
Opened 2024-06-17 16:58 UTC by nbarnhouse

### Description

Completed Term Entry for Python Numpy.degrees().

### Issue Solved

Closes issue [#4720](https://github.com/Codecademy/docs/issues/4720)

### Type of Change

- Adding a new entry

### Checklist

- [ x ] All writings are my own.
- [ x ] My entry follows the Codecademy Docs style guide.
- [ x ] My changes generate no new warnings.
- [ x ] I have performed a self-review of my own writing and code.
- [ x ] I have checked my entry and corrected any misspellings.
- [ x ] I have made corresponding changes to the documentation if needed.
- [ x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-17 17:37 UTC, nbarnhouse commented
Hi @mamtawardhani I have fixed the error I found. I am still not passing 2 checks. I am available this afternoon and evening to correct as required.

2024-06-17 18:21 UTC, mamtawardhani commented
> Hi @mamtawardhani I have fixed the error I found. I am still not passing 2 checks. I am available this afternoon and evening to correct as required.

Hey @nbarnhouse thanks for the submission, and don't worry, we'll fix those from our side. Will tag you if there is any change needed in the entry. Thanks! 😊

2024-06-19 08:23 UTC, mamtawardhani requested changes
Hey @nbarnhouse, thank you for your contribution to the Codecademy Docs! The entry is well written! 😃 

I've suggested a few changes, could you review and modify those at your earliest convenience? Feel free to dicuss any concerns. Thank you! 😄

2024-06-19 08:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/degrees/degrees.md
> +numpy.degrees([x, x, x])
```suggestion
numpy.degrees(x, out=None, where=True)
```

2024-06-19 08:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/degrees/degrees.md
> +numpy.degrees([x, x, x])
This is the syntax of the `.degrees()` method. Including the parameters that are used very often

2024-06-19 08:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/degrees/degrees.md
> +- `x`: The number or array of numbers in radians that must be converted.
Please also describe the other parameters based on the above new syntax: `x`, `out` and `where`

2024-06-19 08:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/degrees/degrees.md
> +The output of the above code is shown below:
```suggestion
Below is the output generated by the code snippet:
```

2024-06-19 08:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/degrees/degrees.md
> +The output of the above code is shown below:
reframed it since it was giving plagiarism issue

2024-06-19 08:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/degrees/degrees.md
> +
```suggestion
```

2024-06-19 08:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/degrees/degrees.md
> +
Let's have only 1 line space after every heading or new topic

2024-06-19 08:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/degrees/degrees.md
> +
```suggestion
```

2024-06-19 08:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/degrees/degrees.md
> +
only 1 line space is needed

2024-06-19 08:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/degrees/degrees.md
> +The output of the above code is shown below:
```suggestion
The output generated by the code snippet is as follows:
```

2024-06-19 08:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/degrees/degrees.md
> +The output of the above code is shown below:
reframed it due to plagiarism issues

2024-06-19 08:23 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/degrees/degrees.md
> +In this codebyte example, the `.degree()` method converts
```suggestion
Run the following code to understand how the `.degrees()` function works:
```

2024-06-20 12:52 UTC, nbarnhouse commented
Hi @mamtawardhani all done with updates.

2024-06-20 14:14 UTC, mamtawardhani approved these changes
Thank you for making the required changes @nbarnhouse! 😄 

The entry is ready for a second round of the review 🚀

2024-06-27 20:56 UTC, letsbuildanything approved these changes
This looks good to be Merged! 🚀

2024-06-29 09:05 UTC, merged