Completed concept entry for Postgresql operator-invocations #4764
Codecademy/docs pull request #4785
Opened 2024-06-17 17:23 UTC by nbarnhouse

### Description

Completed concept entry for Postgresql operator-invocations

### Issue Solved

[Closes Issue #4649](https://github.com/Codecademy/docs/issues/4649)
Closes #4649 

### Type of Change

- Adding a new entry

### Checklist

- [x ] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-17 17:41 UTC, nbarnhouse commented
Submitted this to fix error in https://github.com/Codecademy/docs/pull/4764. ++ @cigar-galaxy82

2024-06-27 03:32 UTC, cigar-galaxy82 requested changes
Hi, I have suggested a few changes please modify

2024-06-27 03:32 UTC, cigar-galaxy82 commented on content/postgresql/concepts/operator-invocations/operator-invocations.md
> +  - 'paths/data-science-foundations'
```suggestion
  - 'learn-sql'
  - 'paths/data-science-foundations'
  - 'paths/analyze-data-with-sql'
  - 'paths/design-databases-with-postgresql'
```

2024-06-27 03:32 UTC, cigar-galaxy82 commented on content/postgresql/concepts/operator-invocations/operator-invocations.md
> +WHERE NOT column1 = 'SOUTH';
```suggestion
// AND
SELECT * FROM table_name
WHERE column1 >= 10 AND  column1 <= 1000;

// OR
SELECT * FROM table_name
WHERE column1 = 'North' OR 'WEST';

// NOT
SELECT * FROM table_name
WHERE NOT column1 = 'SOUTH';
```

2024-06-27 03:32 UTC, cigar-galaxy82 commented on content/postgresql/concepts/operator-invocations/operator-invocations.md
> +WHERE column1 < 1000;
```suggestion
// Equal to
SELECT * FROM table_name
WHERE column1 = 'North';

// Not Equal to
SELECT * FROM table_name
WHERE column1 != column2;

// Greater than
SELECT * FROM table_name
WHERE column1 > 10;

// Less than
SELECT * FROM table_name
WHERE column1 < 1000;
```

2024-06-27 03:32 UTC, cigar-galaxy82 commented on content/postgresql/concepts/operator-invocations/operator-invocations.md
> +WHERE gender = 'female' AND age >= 4;
```suggestion
SELECT * FROM animals WHERE gender = 'female' AND age >= 4;
```

2024-06-27 03:32 UTC, cigar-galaxy82 commented on content/postgresql/concepts/operator-invocations/operator-invocations.md
> +WHERE NOT species = 'lion';
```suggestion
SELECT * FROM animals WHERE NOT species = 'lion';
```

2024-06-27 03:33 UTC, cigar-galaxy82 commented
Hi @nbarnhouse 

Thank you for contributing to Codecademy docs. I have suggested a few changes please modify

2024-06-27 17:18 UTC, nbarnhouse commented
Thank you @cigar-galaxy82. I have made updates based on your comments.

2024-07-02 09:14 UTC, cigar-galaxy82 approved these changes

2024-07-03 10:40 UTC, Sriparno08 approved these changes
Looks good, @nbarnhouse! 👍

2024-07-03 10:41 UTC, merged