[Term Entry] Go: Pointers Go
Codecademy/docs pull request #4794
Opened 2024-06-19 19:07 UTC by Mayer-04

### Description

I have created the pointers topic in the Go programming language. Essential feature that allows you to work directly with the memory of a program.

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-02 18:21 UTC, ishg-153 requested changes
@Mayer-04 Nice entry! I have suggested some changes, please make those. Let me know once you are done.

2024-07-02 18:21 UTC, ishg-153 commented on content/go/concepts/pointers/pointers.md
> +
Please remove this as this is not necessary.

2024-07-02 18:21 UTC, ishg-153 commented on content/go/concepts/pointers/pointers.md
> +### Practical Example
```suggestion
## Example
```

2024-07-02 18:21 UTC, ishg-153 commented on content/go/concepts/pointers/pointers.md
> +
For the above code block please write its output as follows:
The output for the above code is:
(triple backticks)shell
[the received output]
(close the triple backticks)

2024-07-02 18:21 UTC, ishg-153 commented on content/go/concepts/pointers/pointers.md
> +
Do the same for this and all the other code blocks with outputs.

2024-07-04 13:42 UTC, Mayer-04 commented
Hello, I made the respective changes to the article, I am aware of anything else.

2024-07-19 20:39 UTC, ishg-153 approved these changes
@Mayer-04 Ready for second review!

2024-07-27 11:33 UTC, Sriparno08 approved these changes
Looks good, @Mayer-04! 👍

2024-07-27 11:35 UTC, merged