Dart Methods (New Pull Request)
Codecademy/docs pull request #4796
Opened 2024-06-20 01:32 UTC by brandk94

### Description

- Created a new sub-directory called 'methods' for the existing directory:   'content/dart/concepts'
- Created and edited a new file called 'methods.md' for the directory:    'content/dart/concepts/methods'

### Issue Solved

Closes #4252 

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-05 23:04 UTC, brandk94 commented
Hi @cigar-galaxy82 and @ishg-153. I looked at the results of the commit push test and saw that the "ci (format:verify)" and "ci (test)" workflows failed.  I looked to see what caused the failure, and for the "ci (test)" workflow, it turns out there was a spelling error with the "CatalogContent" metadata in the Dart methods.md file that I made.  The word "Catalog" in "CatalogContent" was misspelled "Catelog", but now I fixed it to "Catalog".  If there any more errors with this, please let me know. Thank you.

2024-07-11 10:18 UTC, ishg-153 commented
@cigar-galaxy82 Please are you working on reviewing this PR?

2024-08-18 14:22 UTC, cigar-galaxy82 commented
Change the structure of the of the entry as mentioned below

Syntax section
Return Value section
Parameters section

Then have a types of methods section, in this mention all the types shown below

Instance Method 
Static Method
Short-Hand Method

2024-08-18 20:02 UTC, cigar-galaxy82 requested changes

2024-08-18 20:02 UTC, cigar-galaxy82 commented on content/dart/concepts/methods/methods.md
> +```dart
```suggestion
```pseudo
```

2024-08-18 20:03 UTC, cigar-galaxy82 commented
Hi @brandk94 thank you for contributing to Codecademy docs, I have suggested changes please modify. Also please look at the structure of the entry is have suggested

2024-08-20 20:46 UTC, brandk94 commented
Hi @cigar-galaxy82. I made significant changes to my Dart methods.md file in accordance with the suggested changes you requested, and some other changes to make the file context look nice and consistent. Please let me know what you think and if any further changes need to be made. Thank you.

2024-09-13 17:26 UTC, cigar-galaxy82 approved these changes

2024-09-24 15:28 UTC, Sriparno08 approved these changes
Looks good, @brandk94!

2024-09-24 15:29 UTC, merged