[Edit] CSS Typography: text-align #4418
Codecademy/docs pull request #4803
Opened 2024-06-20 15:45 UTC by andres3204

…le 1 in content/css/concepts/typography/terms/text-align/text-align.md

### Description

- Added a paragraph explanatory picture for the functionality of text-align in the text-align.md file.
- Added text-align-paragraph-example.png to the media folder.

### Issue Solved

- Closes #4418 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-20 15:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4803) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4803) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4803) it.</sub>

2024-06-24 08:05 UTC, mamtawardhani requested changes
Hey @andres3204! Thank you for contributing to the Codecademy docs! 😃 

I've suggested a couple of changes, could you please review and modify those at your earliest convenience? Thank you! 😄

2024-06-24 13:03 UTC, mamtawardhani approved these changes
Thank you for making the changes @andres3204! 😃 

The entry looks good for a second round of review! 🚀

2024-06-25 15:57 UTC, Sriparno08 approved these changes
Looks good! 👍

2024-06-25 15:59 UTC, merged