Update props.md
Codecademy/docs pull request #4804
Opened 2024-06-20 15:56 UTC by roryyeung

Switched from class to function based components.

### Description

Switched from class to function based react components, in accordance with current course.

### Issue Solved

Solves issue 4788

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [X ] All writings are my own.
- [X ] My entry follows the Codecademy Docs style guide.
- [ X] My changes generate no new warnings.
- [X ] I have performed a self-review of my own writing and code.
- [ X] I have checked my entry and corrected any misspellings.
- [X ] I have made corresponding changes to the documentation if needed.
- [X ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-20 15:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4804) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4804) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4804) it.</sub>

2024-06-21 07:18 UTC, ishg-153 requested changes
@roryyeung I understand the change you have suggested. But since using class-based components isn't deprecated, instead of editing the existing example, you can add a new example where function-based components are used.

2024-10-01 13:35 UTC, mamtawardhani commented
@cigar-galaxy82 it's been 3 weeks, can you review this on priority and send it further?

2024-10-18 15:46 UTC, cigar-galaxy82 commented
Closing as the author has been inactive

2024-10-18 15:46 UTC, closed without merging