[Concept Entry] MySQL user-defined variables
Codecademy/docs pull request #4811
Opened 2024-06-21 09:45 UTC by andersooi

### Description

- Added new concept entry for MySQL User-Defined Variables

### Issue Solved

Closes #4680 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-06-28 16:41 UTC, Sriparno08 requested changes
Hey @andersooi, thanks for contributing to Codecademy!

I've listed all the modifications that you need to make in your entry below:

2024-06-28 16:41 UTC, Sriparno08 commented on content/mysql/concepts/user-defined-variables/user-defined-variables.md
> +```
Modifications:

- Let's change the first code block a bit for uniqueness
- Let's convert the comments of the second and third code block into sentences and insert them before the respective code blocks for a better structure

````suggestion
The following example demonstrates the use of a user-defined variable in MySQL:

```sql
-- Create a table named 'stocks_table'
CREATE TABLE stocks_table (
        name VARCHAR(30),
        price DECIMAL(8, 2)
);
```

Then, some stocks are inserted into the table:

```sql
INSERT INTO stocks_table (name, price)
VALUES
('Alphabet', 589.45),
('Apple', 398.23),
('Nvidia', 1237.78),
('Tesla', 1089.25);
```

Next, a user-defined variable is declared to store the total number of stocks and then used to retrieve the stored result:

```sql
SET @total_products = (SELECT COUNT(*) FROM stocks_table);
SELECT @total_products;
```
````

2024-06-28 16:41 UTC, Sriparno08 commented on content/mysql/concepts/user-defined-variables/user-defined-variables.md
> +The output of the SELECT statement will be:
Let's use single backticks (``` `...` ```) for 'SELECT':

```suggestion
The output of the `SELECT` statement will be:
```

2024-07-01 05:57 UTC, Sriparno08 approved these changes
Looks good for a second review, @andersooi! 👍

2024-07-08 06:38 UTC, ishg-153 requested changes
@andersooi Great entry! Please make this one small change. And then we can move forward to merging this PR.

2024-07-08 06:38 UTC, ishg-153 commented on content/mysql/concepts/user-defined-variables/user-defined-variables.md
> +In MySQL, **user-defined variables** can be used to store a value in a specific statement and later retrieve it in another statement. These variables can be useful for storing intermediate results, p
```suggestion
In MySQL, **user-defined variables** can be used to store a value in a specific statement and later retrieve it in another statement. These variables can be useful for storing intermediate results, passing data between statements, and enhancing the functionality of MySQL queries. They are also session-specific, meaning their values can only be used within the current session and will not be available in future sessions or stored in the database.
```

2024-07-19 20:41 UTC, ishg-153 approved these changes
@andersooi Ready to merge!

2024-07-19 20:42 UTC, merged