[Term Entry] Java ArrayList .clear()
Codecademy/docs pull request #4813
Opened 2024-06-21 12:03 UTC by elifmo9

### Description

- Added the .clear method for Java ArrayList
- closes issue #4335 

### Issue Solved

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-21 12:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4813) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4813) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4813) it.</sub>

2024-06-22 12:41 UTC, mamtawardhani requested changes
Hey @elifmo9! Thank you for contributing to the Codecademy Docs! The entry is nicely written! 😄 

I've suggested a few changes, could you please review and modify them at your earliest convenience? Feel free to discuss any concerns, thank you! 😃

2024-06-22 12:41 UTC, mamtawardhani commented on content/java/concepts/array-list/terms/clear/clear.md
> +---
```suggestion
---
Title: '.clear()'
Description: 'Removes all elements from an ArrayList.' 
Subjects:
  - 'Code Foundations'
  - 'Computer Science'
Tags:
  - 'Arrays'
  - 'Methods'
  - 'Java'
CatalogContent:
  - 'learn-java'
  - 'paths/computer-science'
---
```

2024-06-22 12:41 UTC, mamtawardhani commented on content/java/concepts/array-list/terms/clear/clear.md
> +---
Added the appropriate tags from the documents

2024-06-22 12:41 UTC, mamtawardhani commented on content/java/concepts/array-list/terms/clear/clear.md
> +The **`.clear()`** method removes all elements from an [`ArrayList`](https://www.codecademy.com/resources/docs/java/array-list) in Java.
```suggestion
The **`.clear()`** method in Java removes all elements from the [`ArrayList`](https://www.codecademy.com/resources/docs/java/array-list)

```

2024-06-22 12:41 UTC, mamtawardhani commented on content/java/concepts/array-list/terms/clear/clear.md
> +The **`.clear()`** method removes all elements from an [`ArrayList`](https://www.codecademy.com/resources/docs/java/array-list) in Java.
Reframed this due to plagiarism issues

2024-06-22 12:41 UTC, mamtawardhani commented on content/java/concepts/array-list/terms/clear/clear.md
> +All elements of an instance of `ArrayList` can be cleared by passing the `.clear()` method. After invoking this method, the list will be empty, but the `ArrayList` instance remains with its current c
This particular line can be added in the introductory paragraph itself. You can remove it from here and add it in the above paragraph.

2024-06-22 12:41 UTC, mamtawardhani commented on content/java/concepts/array-list/terms/clear/clear.md
> +arrayListInstance.clear();
```suggestion
myArrayList.clear();
```

2024-06-22 12:41 UTC, mamtawardhani commented on content/java/concepts/array-list/terms/clear/clear.md
> +```
Below this example, could you please also add the output using the ```shell ``` block?

2024-06-26 08:43 UTC, elifmo9 commented
Hi @mamtawardhani ! Thank you for your feedback. I will work on these now and let you know when I have completed them! :)

2024-06-26 13:13 UTC, elifmo9 commented
Hi @mamtawardhani I have pushed the suggested changes to my branch. Does this automatically sync to the pull request or will I need to do  anything additional for this?

2024-06-26 14:56 UTC, mamtawardhani approved these changes
Thank you for the contribution @elifmo9 😃 

The entry looks good for a second round of review 🚀

2024-06-27 10:52 UTC, Sriparno08 approved these changes
Looks good! 👍

2024-06-27 10:53 UTC, merged