Completed [Term Entry] Python Sets: .copy() #4799
Codecademy/docs pull request #4817
Opened 2024-06-22 12:25 UTC by nbarnhouse

### Description

Added .copy() method information to Python sets

### Issue Solved

Closes #issue-number [#4799](https://github.com/Codecademy/docs/issues/4799)

### Type of Change

- Adding a new entry

### Checklist

- [ x ] All writings are my own.
- [ x ] My entry follows the Codecademy Docs style guide.
- [ x ] My changes generate no new warnings.
- [ x ] I have performed a self-review of my own writing and code.
- [ x ] I have checked my entry and corrected any misspellings.
- [ x ] I have made corresponding changes to the documentation if needed.
- [ x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-27 08:34 UTC, Sriparno08 requested changes
Hey @nbarnhouse, thanks for contributing to Codecademy!

I've listed all the modifications that you need to make in your entry below:

2024-06-27 08:34 UTC, Sriparno08 commented on content/python/concepts/sets/terms/copy/copy.md
> +This example creates a shallow copy of a simple set.
Let's change the introduction for the example:

```suggestion
The following example demonstrates the usage of the `.copy()` method:
```

2024-06-27 08:34 UTC, Sriparno08 commented on content/python/concepts/sets/terms/copy/copy.md
> +This would output the result:
Let's change the introduction for the output:

```suggestion
The above code produces the following output:
```

2024-06-27 08:34 UTC, Sriparno08 commented on content/python/concepts/sets/terms/copy/copy.md
> +{'First', 'Second', 'Third', 'Fourth'}
Let's only include the output:

```suggestion
{'First', 'Second', 'Third'}
{'First', 'Second', 'Third', 'Fourth'}
```

2024-06-27 08:34 UTC, Sriparno08 commented on content/python/concepts/sets/terms/copy/copy.md
> +Note: Unlike lists, a set element has no order or index. The ouput of this result is shown in order, but the result can be different.
Modifications:

- Let's use the '>' symbol to indicate a 'Note'
- Let's link 'lists' to its doc entry
- Let's change the text a bit

```suggestion
> Note: Unlike [lists](https://www.codecademy.com/resources/docs/python/lists), a set element has no order or index. Hence, though the elements in the output are shown in order, they can be placed differently in other cases.
```

2024-06-27 08:34 UTC, Sriparno08 commented on content/python/concepts/sets/terms/copy/copy.md
> +Run the following code to understand how the **`.copy()`** method works:
Let's change the introduction for the codebyte example:

```suggestion
The following codebyte example demonstrates the usage of the `.copy()` method:
```

2024-06-27 17:16 UTC, nbarnhouse commented
Thank you @Sriparno08. I've made updates based on your comments.

2024-06-28 06:25 UTC, Sriparno08 approved these changes
Looks good for a second review! 👍

2024-06-28 11:29 UTC, mamtawardhani approved these changes
Thank you for the contribution @nbarnhouse! 😃 

The entry is ready to be merged! 🚀

2024-06-28 11:31 UTC, merged