[Concept Entry] MySQL: Indexing
Codecademy/docs pull request #4832
Opened 2024-06-24 15:55 UTC by Munaelekwa

### Description

Added an indexing.md file under Mysql. Wrote about indexes in Mysql, with examples.

### Issue Solved
Closes issue #4678 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-24 15:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4832) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4832) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4832) it.</sub>

2024-06-26 08:51 UTC, Munaelekwa commented
Hi @mamtawardhani , my PR is ready for review :)

2024-06-30 04:06 UTC, cigar-galaxy82 requested changes
Hi, I have suggested a few changes please modify

2024-06-30 04:06 UTC, cigar-galaxy82 commented on content/mysql/concepts/indexing/indexing.md
> +```
after this example show the output

2024-06-30 04:07 UTC, cigar-galaxy82 commented
Hi @Munaelekwa 

Thank you for contributing to Codecademy docs. The entry is very well written, I have suggested a few changes please modify.

2024-07-03 05:58 UTC, Munaelekwa commented
Hi @cigar-galaxy82 , i have modified the file to reflect the changes you suggested, kindly review, thanks.

2024-07-04 02:16 UTC, cigar-galaxy82 commented
Hi @Munaelekwa I see you have made the suggested changes but can you please change the heading in the first suggested also

2024-07-05 07:45 UTC, Munaelekwa commented
> Hi @Munaelekwa I see you have made the suggested changes but can you please change the heading in the first suggested also

Please can you be more specific on the line of the heading

2024-07-09 18:06 UTC, Munaelekwa commented
> Hi @Munaelekwa I see you have made the suggested changes but can you please change the heading in the first suggested also

Hi @cigar-galaxy82 , I'm yet to get clarity on the further changes you requested

2024-07-10 09:28 UTC, cigar-galaxy82 commented
Hi @Munaelekwa I mean where you mentioned types of indexes change the heading most used indexes since there are more indexes possible that can be used

2024-07-10 12:16 UTC, Munaelekwa commented
Hi @cigar-galaxy82 , I have modified the heading and just made it a sentence. I hope it looks better

2024-07-10 12:17 UTC, Munaelekwa commented
Hi @cigar-galaxy82 , I have modified the heading and just made it a sentence. I hope it looks better

2024-07-10 12:22 UTC, cigar-galaxy82 approved these changes

2024-07-25 17:00 UTC, avdhoottt requested changes
Hey @Munaelekwa, I've reviewed the entry and left some suggestions. Please make them and ping me whenever you are done. Thanks!!

2024-07-27 17:33 UTC, Munaelekwa commented
Hi @avdhoottt , I have committed the changes you suggested

2024-08-06 09:22 UTC, avdhoottt approved these changes
LGTM

2024-08-06 09:35 UTC, avdhoottt commented on content/mysql/concepts/indexing/indexing.md
> +**Expected Output**
```suggestion
Expected Output:
```

2024-08-06 09:37 UTC, merged