[Term Entry] Python:NumPy ndarray .tolist()
Codecademy/docs pull request #4837
Opened 2024-06-25 19:25 UTC by jmargitic

### Description

Hi!
I've added an entry for .tolist() for the ndarray content terms folder. It refers to issue: [Term Entry] Python:NumPy ndarray .tolist() #4828

### Issue Solved

Please use the following format(s) to link the issue numbers that your contribution addresses:
Closes #4828

### Type of Change

X Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

Hi! I believe I'm ready to submit my first pull request, however I have a few doubts with regards to the checklist.

With regards to point 1
_All writings are my own_

I've used resources from:
- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tolist.html
- ChatGPT (for editing the md content)

How can I properly cite this?

2024-06-25 19:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4837) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4837) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4837) it.</sub>

2024-06-26 11:11 UTC, mamtawardhani requested changes
Hey @jmargitic, thank you contributing to Codecademy Docs! The entry is well written! 😃 

I've suggested a few changes, could you review and modify those at your earliest convenience? Feel free to discuss any concerns, thank you! 😄

2024-06-26 11:11 UTC, mamtawardhani commented on content/numpy/concepts/ndarray/terms/tolist/tolist.md
> +type(arr_list[0])
```suggestion
#Checking Output
print(arr_list)

# Checking Output's type 
print(type(arr_list[0]))
```

2024-06-26 11:11 UTC, mamtawardhani commented on content/numpy/concepts/ndarray/terms/tolist/tolist.md
> +type(arr_list[0])
used the `print` statement for the output

2024-06-26 11:11 UTC, mamtawardhani commented on content/numpy/concepts/ndarray/terms/tolist/tolist.md
> +type(arr_tolist[0])
```suggestion
#Checking Output
print(arr_tolist)

# Checking Output's type 
print(type(arr_tolist[0]))
```

2024-06-26 11:11 UTC, mamtawardhani commented on content/numpy/concepts/ndarray/terms/tolist/tolist.md
> +type(arr_tolist[0])
used the print statement for the output

2024-06-26 11:11 UTC, mamtawardhani commented on content/numpy/concepts/ndarray/terms/tolist/tolist.md
> +```
This code can be added inside the ##Codebyte Example block

2024-06-26 11:11 UTC, mamtawardhani commented on content/numpy/concepts/ndarray/terms/tolist/tolist.md
> +### 2D Array
```suggestion
## Codebyte Example
```

2024-06-26 11:11 UTC, mamtawardhani commented on content/numpy/concepts/ndarray/terms/tolist/tolist.md
> +For a 2D array, `.tolist()` applies recursively:
```suggestion
Run the following code to understand the working of the `.tolist()` method for converting a 2D NumPy array to a Python list:
```

2024-06-26 11:11 UTC, mamtawardhani commented on content/numpy/concepts/ndarray/terms/tolist/tolist.md
> +``` python
```suggestion
```codebyte/python
```

2024-06-26 11:11 UTC, mamtawardhani commented on content/numpy/concepts/ndarray/terms/tolist/tolist.md
> +```
```suggestion
```

2024-06-26 11:11 UTC, mamtawardhani commented on content/numpy/concepts/ndarray/terms/tolist/tolist.md
> +```
Codebyte blocks don't have output section

2024-06-26 11:11 UTC, mamtawardhani commented on content/numpy/concepts/ndarray/terms/tolist/tolist.md
> +
```suggestion
```

2024-06-26 13:06 UTC, jmargitic commented
Hi! 
This is ready to be reviewed again!
Thank you!

2024-06-26 15:20 UTC, mamtawardhani approved these changes
Thank you for making the changes and for your contribution @jmargitic! 😃 

The entry looks nice for a second round of review 🚀

2024-06-29 11:32 UTC, Sriparno08 approved these changes
Looks good, @jmargitic! 👍

2024-06-29 11:33 UTC, merged