{Term Entry] Python:NumPy Math Methods power
Codecademy/docs pull request #4838
Opened 2024-06-25 20:21 UTC by cigar-galaxy82

### Description

Added new term entry for Python:NumPy Math Methods `power`

### Issue Solved

Closes [#4773](https://github.com/Codecademy/docs/pull/4773)

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-26 10:14 UTC, mamtawardhani requested changes
Thank you for contributing to Docs @cigar-galaxy82, the entry was well written! 😃 

I've suggested a few changes, could you please review and modify those at your earliest convenience? Feel free to discuss any concerns, thank you! 😄

2024-06-26 10:14 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/power/power.md
> +- `out`: An optional parameter that allows us to store the output array. If not provided, a new array will be created.
```suggestion
- `out`: An optional parameter that allows us to store the output array. If not specified, a new array will be allocated for the result.
```

2024-06-26 10:14 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/power/power.md
> +- `out`: An optional parameter that allows us to store the output array. If not provided, a new array will be created.
reframed it due to plagiarism issues for the second half of the sentence

2024-06-26 10:14 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/power/power.md
> +In this codebyte example, the `.power()` computes the power of the given elements in the in the `array1` as base with elements in `array2` as exponent for corresnpoding elements in `array1`:
```suggestion
In this codebyte example, `.power()` method computes the power where each element in `array1` serves as the base raised to the power of the corresponding element in `array2`:
```

2024-06-26 10:14 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/power/power.md
> +In this codebyte example, the `.power()` computes the power of the given elements in the in the `array1` as base with elements in `array2` as exponent for corresnpoding elements in `array1`:
corrected the spelling mistakes and sentence formation

2024-06-26 10:14 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/power/power.md
> +numpy.round(array1, array2, out=None, where=True)
1. the entry is for the `numpy.power()` method, the syntax was having `.round()`
2. Let's stick to the official NumPy doc for the parameters: https://numpy.org/doc/stable/reference/generated/numpy.power.html

2024-06-26 10:14 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/power/power.md
> +- `array2`: A number or an array of numbers which will be used as exponent for elements in `array1`.
```suggestion
- `x1`: A number or an array of numbers used as the base.
- `x2`: A number or an array of numbers used as the exponent for elements in `x1`.
```

2024-06-27 10:04 UTC, mamtawardhani commented
@cigar-galaxy82 please make the required changes, so this can be merged. Thank you 😃

2024-06-27 12:42 UTC, cigar-galaxy82 commented
Hi @mamtawardhani all the recommended changes are added

2024-06-27 15:19 UTC, mamtawardhani approved these changes
Great entry @cigar-galaxy82 😃 

Ready to be merged! 🚀

2024-06-27 15:21 UTC, merged