[Term Entry] C: Linked List
Codecademy/docs pull request #4853
Opened 2024-06-29 12:40 UTC by cigar-galaxy82

### Description

Add a new entry on `Linked List` in `C`. For this entry, I have only given the basics of a Linked list and in future, I will create a new entry for different kinds of Linked list

### Issue Solved

[#3701](https://github.com/Codecademy/docs/issues/3701)

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-06-30 16:57 UTC, letsbuildanything requested changes
@cigar-galaxy82 I've requested some changes. Please take a moment to address them.
Also,
1. Please add a simple example.
2. In the `singular-linked-list image`, I think the last node should point to the NULL.
Thank you.

2024-06-30 16:57 UTC, letsbuildanything commented on content/c/concepts/linked-list/linked-list.md
> +A **`linked list`** is a type of linear data structure in which elements are not sequentially stored but are randomly spread in memory consisting of small units called `node`. These units connect and
```suggestion
A **linked list** is a type of linear data structure in which elements are not stored sequentially but are dynamically allocated in memory, consisting of small units called nodes. These units connect and point to other nodes to create a linked list.
```

2024-06-30 16:57 UTC, letsbuildanything commented on content/c/concepts/linked-list/linked-list.md
> +A **`linked list`** is a type of linear data structure in which elements are not sequentially stored but are randomly spread in memory consisting of small units called `node`. These units connect and
Removed the last line, because you've already discussed it in the below structure of a node.

2024-06-30 16:57 UTC, letsbuildanything commented on content/c/concepts/linked-list/linked-list.md
> +The structure of a node is shown in the below image.
```suggestion
The structure of a node is illustrated below:
```

2024-06-30 16:57 UTC, letsbuildanything commented on content/c/concepts/linked-list/linked-list.md
> +So the node consist of two parts:
```suggestion
Each node in a linked list has two parts:
```

2024-06-30 16:57 UTC, letsbuildanything commented on content/c/concepts/linked-list/linked-list.md
> +- `data`: The data that will be stored, this can be of any data type present in `C`.
```suggestion
- `data`: It stores the value, which can be of any data type.
```

2024-06-30 16:57 UTC, letsbuildanything commented on content/c/concepts/linked-list/linked-list.md
> +- `next`: This is a `pointer` that is used to store the address of a different node.
```suggestion
- `next`: A pointer that stores the memory address of the next node in the sequence.
```

2024-06-30 16:57 UTC, letsbuildanything commented on content/c/concepts/linked-list/linked-list.md
> +When nodes are connected to each other a linked list is formed like shown below.
```suggestion
When nodes are connected to one other, a linked list is formed, as shown below:
```

2024-06-30 16:57 UTC, letsbuildanything commented on content/c/concepts/linked-list/linked-list.md
> +So the linked consist to parts:
```suggestion
A linked list consists of two key components:
```

2024-06-30 16:57 UTC, letsbuildanything commented on content/c/concepts/linked-list/linked-list.md
> +- `tail`: The last node of the linked list.
```suggestion
- `Head`: The first node in the linked list.
- `Tail`: The last node in the linked list, which points to `NULL` in a singly linked list.
```

2024-07-06 15:19 UTC, cigar-galaxy82 commented
Hi @letsbuildanything I have made all the suggested changes

2024-07-08 14:30 UTC, letsbuildanything commented
> @cigar-galaxy82 I've requested some changes. Please take a moment to address them. Also,
> 
> 1. Please add a simple example.
> 2. In the `singular-linked-list image`, I think the last node should point to the NULL.
>    Thank you.

hi @cigar-galaxy82, The above two changes still need to be made.

2024-07-21 19:54 UTC, cigar-galaxy82 commented
Hi @letsbuildanything I have made the changes.

2024-09-17 10:07 UTC, mamtawardhani approved these changes
Thank you for contributing to Docs @cigar-galaxy82 😄 

The entry is ready to be merged! 🚀

2024-09-17 10:09 UTC, merged