add .md file/entry for Pandas dataframe tail
Codecademy/docs pull request #4855
Opened 2024-07-01 01:35 UTC by sethaferd

### Description

Added .md file/entry for Pandas dataframe tail.

### Issue Solved

Closes #4523 

### Type of Change

- Adding a new entry

### Checklist

- [ x ] All writings are my own.
- [ x ] My entry follows the Codecademy Docs style guide.
- [ x ] My changes generate no new warnings.
- [ x ] I have performed a self-review of my own writing and code.
- [ x ] I have checked my entry and corrected any misspellings.
- [ x ] I have made corresponding changes to the documentation if needed.
- [ x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-01 01:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4855) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4855) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4855) it.</sub>

2024-07-01 11:57 UTC, mamtawardhani commented
Hey @sethaferd, seems like the path of entry is incorrect as the `tail.md` file should be inside a folder named `tail`, could you please update that? This is how your final path should look like: `docs/content/pandas/concepts/dataframe/terms/tail/tail.md`.

Let me know once you update it 😃

2024-07-02 06:31 UTC, mamtawardhani requested changes
Hey @sethaferd, thank you for contributing to the Codecademy Docs, the entry is nicely written!

I've requested some minor changes, could you please review and modify them at your earliest convenience? Thank you! 😃

2024-07-02 06:31 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/tail/tail.md
> +Title: '.copy()'
```suggestion
Title: '.tail()'
```

2024-07-02 06:31 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/tail/tail.md
> +Title: '.copy()'
The entry is about the `.tail()` method, seems like a silly mistake 🥹

2024-07-02 06:31 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/tail/tail.md
> +In Pandas, **`.tail()`** is a method that returns the last n rows of a DataFrame. By default, it returns the last 5 rows, but the number of rows can be adjusted by passing an integer argument to the
```suggestion
In Pandas, **`.tail()`** is a method that returns the last `n` rows of a [DataFrame](https://www.codecademy.com/resources/docs/pandas/dataframe). By default, it returns the last 5 rows, but the number of rows can be adjusted by passing an integer argument to the method.
```

2024-07-02 06:31 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/tail/tail.md
> +df_tail = df.tail(n=5)
```suggestion
DataFrame.tail(n=5)
```

2024-07-02 06:31 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/tail/tail.md
> +The parameter `n` specifies the number of rows to return. The default value is `n=5`.
Describing the parameters should be done in the following format:

- `DataFrame`: The Pandas data structure on which the method is called.
- `n`: Number of rows to return from the end of the DataFrame. The default value is 5.

(You can modify the framing of the sentences, this is just for example)

2024-07-02 06:31 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/tail/tail.md
> +By using the `.tail()` method, the end of a DataFrame can be previewed, which can be useful for inspecting the most recent data in a dataset.
```suggestion
By using the `.tail()` method, the end of a DataFrame can be previewed, which is useful for inspecting the most recent data in a dataset.
```

2024-07-02 06:31 UTC, mamtawardhani commented on content/pandas/concepts/dataframe/terms/tail/tail.md
> +By using the `.tail()` method, the end of a DataFrame can be previewed, which can be useful for inspecting the most recent data in a dataset.
At the end, please also add a running codebyte example using the ##Codebyte Example block, please note that the codebyte example is not accompanied by an output block.

2024-07-02 07:44 UTC, mamtawardhani approved these changes
Thank you for the contribution @sethaferd! 😃 

The entry looks good for a second review 🚀

2024-07-08 14:24 UTC, Sriparno08 approved these changes
Looks good, @sethaferd! 👍

2024-07-08 14:25 UTC, merged