[Concept Entry] PyTorch nn
Codecademy/docs pull request #4857
Opened 2024-07-01 10:10 UTC by andersooi

### Description

- Added new concept entry for PyTorch nn

### Issue Solved

Closes #4826  

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-07-19 20:56 UTC, ishg-153 requested changes
@andersooi Please make these changes

2024-07-19 20:56 UTC, ishg-153 commented on content/pytorch/concepts/nn/nn.md
> +The **`nn module`** in PyTorch provides the foundation to build and train neural network models. It contains various layers, activation functions, loss functions and optimisation algorithms that enab
```suggestion
The **`nn module`** in PyTorch provides the foundation to build and train neural network models. It contains various layers, activation functions, loss functions, and optimization algorithms that enable the creation of complex deep-learning models. The `nn module` is highly customizable, enabling developers to construct neural network architectures.
```
Do not use personal pronouns

2024-07-19 20:56 UTC, ishg-153 commented on content/pytorch/concepts/nn/nn.md
> +## Codebyte Example
You can remove this section as codecademy workspace is not compatible with pytorch yet, so this codebyte won't run.

2024-08-23 16:47 UTC, avdhoottt commented on content/pytorch/concepts/nn/nn.md
> +The **`nn module`** in PyTorch provides the foundation to build and train neural network models. It contains various layers, activation functions, loss functions, and optimization algorithms that ena
```suggestion
The `**torch.nn**` module in PyTorch provides the foundation for building and training neural network models. It includes a wide range of pre-built layers, activation functions, loss functions, and other components necessary for creating complex deep-learning models. The `torch.nn` module is highly flexible and customizable, allowing developers to design and implement neural network architectures tailored to specific tasks.
```

2024-08-23 16:48 UTC, avdhoottt commented on content/pytorch/concepts/nn/nn.md
> +  # Define other methods where necessary
```suggestion
import torch.nn as nn

# Define a neural network model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        # Define layers, activations, and other components here
        # For example: self.layer1 = nn.Linear(in_features, out_features)

    def forward(self, x):
        # Implement the forward pass of the model
        # For example: x = self.layer1(x)
        return x  # Replace 'x' with the final output after applying all layers

    # Define other methods if necessary
```

2024-08-23 16:53 UTC, avdhoottt commented on content/pytorch/concepts/nn/nn.md
> +The following example demonstrates how to define a simple neural network model using the `nn.Module`:
```suggestion
The following example demonstrates how to define a simple neural network model using the `nn.Module` with two fully connected layers, apply a ReLU activation function to the first layer's output, and create an instance of the model:
```

2024-08-23 16:53 UTC, avdhoottt approved these changes
LGTM!!

2024-08-24 12:22 UTC, mamtawardhani approved these changes
Hey @andersooi thank you for contributing to Codecademy Docs! 😄 

The entry is ready to be merged! 🚀

2024-08-24 12:22 UTC, mamtawardhani commented on content/pytorch/concepts/nn/nn.md
> +  - 'paths/data-science'
```suggestion
  - 'intro-to-py-torch-and-neural-networks'
  - 'py-torch-for-classification'
```

2024-08-26 06:35 UTC, merged