Add Not-equal-to entry in SQL docs #4850
Codecademy/docs pull request #4873
Opened 2024-07-02 02:14 UTC by sethaferd

### Description

This PR adds documentation for the "Not Equal To" operator in SQL, including a description, syntax, and examples. 
_refer to: docs\content\sql\concepts\operators\terms\not-equal-to\not-equal-to.md_

### Issue Solved

Closes: SQL Not equal to operator #4850

### Type of Change

Adding a new entry

### Checklist

- [ x ] All writings are my own.
- [ x ] My entry follows the Codecademy Docs style guide.
- [ x ] My changes generate no new warnings.
- [ x ] I have performed a self-review of my own writing and code.
- [ x ] I have checked my entry and corrected any misspellings.
- [ x ] I have made corresponding changes to the documentation if needed.
- [ x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-26 15:04 UTC, cigar-galaxy82 requested changes

2024-07-26 15:06 UTC, cigar-galaxy82 commented
Hi @sethaferd thank you for contributing to Codecademy docs, the entry is well written. I have suggested a few changes please modify.

2024-08-23 17:12 UTC, avdhoottt commented on content/sql/concepts/operators/terms/not-equal-to/not-equal-to.md
> +The given query will select all employees who are not in the 'Sales' department using the `<>` operator.
```suggestion
The given query will select all employees who are not in the `Sales` department using the `NOT EQUAL TO`  operator.
```

2024-08-23 17:12 UTC, avdhoottt approved these changes
LGTM!

2024-08-23 18:07 UTC, cigar-galaxy82 approved these changes

2024-08-26 14:45 UTC, merged