[Edit] CSS [Edit] CSS: Filter Functions sepia #4869
Codecademy/docs pull request #4880
Opened 2024-07-05 21:19 UTC by JEllis1313

### Description

-Added a output image comparing the original image in the example already given in the entry to its sepia filter version.
### Issue Solved

  
-Closes Issue #4869 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [ x] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-05 21:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4880) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4880) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4880) it.</sub>

2024-07-08 07:21 UTC, ishg-153 requested changes
@JEllis1313 You seem to have created a new entry. Please ensure that you are making changes to the existing entry at `content/css/concepts/filter-functions/terms/sepia/sepia.md`. Also, you need to delete the `CSS-filter_Functions-Sepia` submodule that you have added to this repo.

Then make the following changes.

2024-07-08 07:21 UTC, ishg-153 commented on docs/content/css/concepts/filter-functions/terms/sepia/sepia.md
> +```
It is not necessary to add this as there is one example code given above. You just need to add output image for it.

2024-07-08 07:21 UTC, ishg-153 commented on docs/content/css/concepts/filter-functions/terms/sepia/sepia.md
> +![Sepia Filtered Image](images/sepia-image.jpg)
You haven't added these images to the media folder. Please follow the directions here:
https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#file-hosting

2024-09-11 09:14 UTC, mamtawardhani commented
Hey @JEllis1313 are you still working on this? Note: If you do not revert back within 3 days this PR will be closed

2024-09-21 07:21 UTC, Sriparno08 commented
Closing this PR since the author is inactive.

2024-09-21 07:21 UTC, closed without merging