[Term Entry] Python:NumPy Math Methods log #4709
Codecademy/docs pull request #4882
Opened 2024-07-07 12:11 UTC by unicorns404

### Description

- Added the log term math method for python NumPy
- Closes issue #4709 

### Issue Solved

### Type of Change
- Added new entry

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-07 12:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4882) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4882) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4882) it.</sub>

2024-07-07 12:20 UTC, unicorns404 commented on content/numpy/concepts/math-methods/terms/log/log.md
> +In this codebyte example, the `.log10()` method only computes the natural logarithm of positive elements in the array:
Change to '.log10()' to '.log()'

2024-07-07 12:21 UTC, unicorns404 commented on content/numpy/concepts/math-methods/terms/log/log.md
> +> **Note:** Running the above code will result in a `RuntimeWarning` due to attempting to calculate the logarithm of a negative number, which is not a valid operation.
Remove

2024-07-08 08:39 UTC, mamtawardhani requested changes
Thank you for contributing to the Codecademy Docs @unicorns404 😃 

I've left a comment and suggested come changes for this entry, could you please review and modify those at your earliest convenience? Feel free to dicuss any concerns, thank you! 😄

2024-07-08 08:39 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/log/log.md
> +  - If not provided, the logarithm is computed for all elements.
This is directly plagiarised from: https://www.codecademy.com/resources/docs/numpy/math-methods/log10

Could you please reframe the sentences to solve this issue?

2024-07-08 08:39 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/log/log.md
> +> **Note:** Running the above code will result in a `RuntimeWarning` due to attempting to calculate the logarithm of a negative number, which is not a valid operation.
```suggestion
```

2024-07-08 08:39 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/log/log.md
> +In this codebyte example, the `.log10()` method only computes the natural logarithm of positive elements in the array:
```suggestion
In this codebyte example, the `.log()` method only computes the natural logarithm of positive elements in the array:
```

2024-07-10 06:15 UTC, mamtawardhani approved these changes
Thank you for the contribution @unicorns404 😄 

The entry looks good for a second round of review.

2024-07-14 10:38 UTC, letsbuildanything approved these changes
LGTM! 🚀

2024-07-15 14:46 UTC, merged