[Term Entry] Python Math Module comb() #4348
Codecademy/docs pull request #4885
Opened 2024-07-07 15:43 UTC by aSagCoder

### Description

- Added the math.com() function for Python math-module. 
- Can be located here - content/python/concepts/math-module/terms/math-comb/math-comb.md

### Issue Solved

- Closes #4348 

### Type of Change

- Adding a new entry
- ~Editing an existing entry (fixing a typo, bug, issues, etc)~
- ~Updating the documentation~

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-07 15:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4885) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4885) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4885) it.</sub>

2024-07-09 11:14 UTC, mamtawardhani requested changes
Thank you for your Contribution to the Codecademy Docs @aSagCoder, the entry is nicely written! 😃 

I've suggested a few changes, could you please review and modify them at your earliest convenience? Thank you! 😄

2024-07-09 11:14 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-comb/math-comb.md
> +where:
```suggestion
```

2024-07-09 11:14 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-comb/math-comb.md
> +    n, k - non-negative integers
```suggestion
- `n`: A non-negative integer that represents the total number of items.
- `k`: A non-negative integer that represents the number of items to choose.
```

2024-07-09 11:14 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-comb/math-comb.md
> +    n, k - non-negative integers
Elaborated both the parameters in the required format:
- `parameter1`: its description
- `parameter2`: its description

2024-07-09 11:14 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-comb/math-comb.md
> +  The result returned is a non-negative integer value that represents the number of ways in which we can make k number of choices out of n number of items without any repetition or order.
```suggestion
The result returned is a non-negative integer representing the number of ways to choose `k` items from `n` items without regard to order or repetition
```

2024-07-09 11:14 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-comb/math-comb.md
> +  The result returned is a non-negative integer value that represents the number of ways in which we can make k number of choices out of n number of items without any repetition or order.
Avoid using "you", "we" and other pronouns

2024-07-09 11:14 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-comb/math-comb.md
> +We use 'math.comb(n,k)' to find the number of unordered choices made to choose 'k' items from 'n' items.
```suggestion
The following example shows the use of `.comb()` function:
```

2024-07-09 11:14 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-comb/math-comb.md
> +We use 'math.comb(n,k)' to find the number of unordered choices made to choose 'k' items from 'n' items.
Since we've already said the "choose k items from n items" a few times above.

2024-07-09 11:14 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-comb/math-comb.md
> +Run the example given below that uses 'math.comb()' in order to find out in how many ways can someone choose 'k' number of flowers from 'n' number of flowers.
```suggestion
Run the example given below that uses `comb()` in order to find out in how many ways can someone choose `k` number of flowers from `n` number of flowers. 
```

2024-07-09 15:20 UTC, aSagCoder commented
Thank you for the review, @mamtawardhani ! Since this is my first time contributing in a technical writing oriented repo, these insights and suggestions are very helpful. I will try to make the necessary changes as soon as possible.

2024-07-13 18:33 UTC, aSagCoder reviewed
@mamtawardhani Hi there, I have reviewed and added the suggestions you made! Thank you for reviewing my PR and I hope everything looks good to go now.

2024-07-14 06:44 UTC, mamtawardhani approved these changes
Thank you for your contribution @aSagCoder 😃 

The entry is ready for a second round of review! 🚀

2024-07-23 14:13 UTC, Sriparno08 approved these changes
Looks good, @aSagCoder! 👍

For your next contributions, please create and make changes on a new branch (not the main branch) and then open a PR from it.

2024-07-23 14:13 UTC, merged