Create str.md
Codecademy/docs pull request #489
Opened 2021-12-26 13:41 UTC by SSwiniarski

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

2021-12-28 16:04 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/str/str.md
> +```codebyte/python
Let's only have one (1) codebyte snippet per entry (preferably towards the bottom).

2021-12-28 16:06 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/str/str.md
> +Use `str()` to change the datatype of a `float` value `314.0` into a string:
```suggestion
The `str()` function can change the datatype of a `float` value, `314.0`, into a string:
```

For entries, let's use a voice that is more manual-like ("This is ...") as opposed to instruction/tutorial-like ("Do this ...").

2021-12-28 16:13 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/str/str.md
> +Use `str()` to change the datatype of an `int` value `314` into a string:
```suggestion
`str()` can also wrap around other type conversions, like in the example below:
```

2021-12-28 16:14 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/str/str.md
> +print(int(314))
```suggestion
print(int(3.14))
```

2021-12-28 16:15 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/str/str.md
> +Takes in a value that can be converted into a string, and returns a copy of the value in the `string` datatype.
```suggestion
Takes in a value that can be converted into a string, and returns a copy of the value in the `string` datatype. If nothing is passed into `str()`, then an empty string is returned.
```

2021-12-28 16:17 UTC, Dusch4593 requested changes
@SSwiniarski All finished with my review! 😃 Tag me when you've finished looking over my comments/suggestions.

2021-12-30 19:13 UTC, SSwiniarski commented
@Dusch4593, I've updated the PR with your suggestions.

2021-12-30 20:44 UTC, Dusch4593 approved these changes
LGTM! Onward to review 2️⃣

2021-12-31 22:52 UTC, yangc95 commented on content/python/concepts/built-in-functions/terms/str/str.md
> +str()
```suggestion
str(object)
```

2021-12-31 22:59 UTC, yangc95 commented on content/python/concepts/built-in-functions/terms/str/str.md
> +The `str()` function can change the datatype of a `float` value, `314.0`, into a string:
```suggestion
The `str()` function changes the datatype of a `float` value, `314.0`, into a string:
```

2021-12-31 23:04 UTC, yangc95 reviewed
@SSwiniarski review 2️⃣ complete, some comments and suggestions

2021-12-31 23:04 UTC, yangc95 commented on content/python/concepts/built-in-functions/terms/str/str.md
> +The `str()` function can also wrap around other type conversions. How could that be done in the example below?
```suggestion
The `str()` function can also wrap around other type conversions.
```

Not sure if these examples are supposed to play out like problems for users to solve, or just demonstrations as we would expect from the documentation. I prefer the latter.

2021-12-31 23:04 UTC, yangc95 commented on content/python/concepts/built-in-functions/terms/str/str.md
> +print(int(3.14))
```suggestion
print(str(int(3.14)))
```

2022-01-01 15:04 UTC, SSwiniarski commented
@yangc95, I applied your changes.

2022-01-01 21:08 UTC, yangc95 approved these changes

2022-01-01 21:18 UTC, merged

2022-01-01 22:32 UTC, yangc95 commented
@SSwiniarski Woohoo, it's live here:

https://www.codecademy.com/resources/docs/python/built-in-functions/str

cc: @Dusch4593