Add codebyte examples for hoisted variables and functions
Codecademy/docs pull request #4898
Opened 2024-07-08 23:44 UTC by barns

### Description

Added codebyte examples to each of the subsections of the Hoisting doc. Each codebyte has been tested and demonstrates the concept covered in that subsection.

### Issue Solved

Closes #4866 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [X] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-08 23:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4898) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4898) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4898) it.</sub>

2024-07-16 10:12 UTC, avdhoottt requested changes
Hey @barns, I've reviewed the entry and suggested some changes, Can you make those? Thanks!

2024-07-16 10:12 UTC, avdhoottt commented on content/javascript/concepts/hoisting/hoisting.md
> +var name;
```suggestion
console.log(`My name is ${name} and I am logging a hoisted variable!`);
var name;
```

2024-07-16 10:12 UTC, avdhoottt commented on content/javascript/concepts/hoisting/hoisting.md
> +This is a very simple example of how a function declaration can be hoisted. Try changing the function declaration to a function expression to see how that affects the output.
```suggestion

This is an example of how a function declaration can be hoisted. Try changing the function declaration to a function expression to see how that affects the output.
```

2024-07-16 10:12 UTC, avdhoottt commented on content/javascript/concepts/hoisting/hoisting.md
> +This is a simple example of hoisting with a `let` variable declaration. Try running it and notice that no error is thrown. What about if you move the declaration to after the `console.log` statement?
```suggestion
This is an example of hoisting with a `let` variable declaration. Try running it and notice that no error is thrown.
```

2024-07-20 11:50 UTC, barns commented
Hi @avdhoottt - apologies for the delay but I've made those changes now

2024-07-20 16:16 UTC, avdhoottt approved these changes
Ready for the second review!!

2024-07-29 15:28 UTC, Sriparno08 approved these changes
Looks good, @barns! 👍

2024-07-29 15:28 UTC, merged