[Term Entry] Adding SQL operator greater than
Codecademy/docs pull request #4906
Opened 2024-07-09 20:13 UTC by selenahuang017

Description
Adding SQL greater than operator to SQL concepts under docs/content/sql/concepts/operators/terms/greater-than/greater-than.md.

Issue Solved
Addresses issue: https://github.com/Codecademy/docs/issues/4884 

Type of Change
Adding a new entry
Checklist
[x ] All writings are my own.
[x ] My entry follows the Codecademy Docs style guide.
[x ] My changes generate no new warnings.
[x ] I have performed a self-review of my own writing and code.
[x ] I have checked my entry and corrected any misspellings.
[x ] I have made corresponding changes to the documentation if needed.
[x ] I have confirmed my changes are not being pushed from my forked main branch.
[x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
[x ] I have linked any issues that are relevant to this PR in the Issues Solved section.

2024-07-22 17:59 UTC, SaviDahegaonkar approved these changes
Hello @selenahuang017,
Your file is completely correct and follows all the style-guide guidelines, hence it is approved.

Thanks.

2024-07-22 17:59 UTC, SaviDahegaonkar commented on content/sql/concepts/operators/terms/greater-than/greater-than.md
> +WHERE order_date >= "2020-01-01";
``` suggestion
SELECT *
FROM coffee
WHERE order_date >= '2020-01-01';
```
In SQL single quotes are very widely accepted and recommended for proper understanding and to ensure compatibility across different database systems.

2024-07-23 17:04 UTC, selenahuang017 commented
@SaviDahegaonkar Hi! I have updated the branch with the edits and linted the file, so it is ready to merge! Thank you.

2024-07-30 17:14 UTC, avdhoottt requested changes
Excellent entry! Hey @selenahuang017, I have suggested some changes, please make them. Thanks!!

2024-07-30 17:49 UTC, selenahuang017 commented
Hi! I'm not sure why the format would fail when the link passed, and the run doesn't give any information on what is wrong. Can someone please check on this and let me know?

2024-08-04 14:42 UTC, avdhoottt commented
> Hi! I'm not sure why the format would fail when the link passed, and the run doesn't give any information on what is wrong. Can someone please check on this and let me know?

I'll fix the format test. Thank you for contributing!!

2024-08-06 09:22 UTC, avdhoottt approved these changes
LGTM!

2024-08-06 09:35 UTC, merged