Create data-types.md
Codecademy/docs pull request #4908
Opened 2024-07-10 18:43 UTC by Alexa86

data types md file

### Description
PR is linked to MySQL data-types #4675 issue assigned to me and it is an .md file describing usage, syntax and examples of various MySQL data types.

### Issue Solved

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-27 00:38 UTC, cigar-galaxy82 requested changes

2024-07-27 00:38 UTC, cigar-galaxy82 commented on content/mysql/concepts/data-types/data-types.md
> +VALUES (UNHEX('AABBCCDDEEFF00112233445566778899AABBCCDDEEFF00112233445566778899...'));
keep the above code with the above code in a code block

2024-07-27 00:39 UTC, cigar-galaxy82 commented
Hi, @A1cX thank you for contributing to Codecademy docs, the entry is well written. I have suggested a few changes please modify

2024-08-01 13:39 UTC, A1cX commented on content/mysql/concepts/data-types/data-types.md
> +- ‘VARCHAR’: is used for storing variable-length strings with a maximum size specified and it gives flexibility in cases when user input to a database are needed.
note added, and VARBINARY, TINYBLOB and TINYTEXT

2024-08-01 14:16 UTC, A1cX commented on content/mysql/concepts/data-types/data-types.md
> +Numeric, date and time data types used in above scenario makes it possible to have recorded information stored in the database like for example:
here I am not sure the table is formatted right, something doesn't look well

2024-09-01 13:08 UTC, A1cX commented
file corrected

2024-09-09 23:25 UTC, cigar-galaxy82 approved these changes

2024-09-10 13:33 UTC, A1cX commented
Hello, should I resolve something in this request? Thank you

2024-09-10 13:55 UTC, cigar-galaxy82 commented
@A1cX there will be a next review after which the entry will be merged

2024-09-11 06:04 UTC, Sriparno08 approved these changes
Looks good, @A1cX!

2024-09-11 06:05 UTC, merged

2024-09-11 15:27 UTC, A1cX commented
@cigar-galaxy82  & @cigar-galaxy82  thank you guys for help with this one