Plotly concepts express terms histogram
Codecademy/docs pull request #4911
Opened 2024-07-11 09:39 UTC by romanwilk

### Description

Created new documentation, introducing information about histogram term in Plotly library for Python.

### Issue Solved

### Type of Change
- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-11 09:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4911) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4911) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4911) it.</sub>

2024-08-22 15:11 UTC, avdhoottt requested changes
Hey @romanwilk, I've suggested some changes, please make them. Thanks!!

2024-08-22 15:11 UTC, avdhoottt commented on content/plotly/concepts/express/terms/histogram/histogram.md
> +  - 'paths/data-science-foundations'
Keep only 2 slugs:
- A free course
- A Pro course/Path

2024-08-22 15:11 UTC, avdhoottt commented on content/plotly/concepts/express/terms/histogram/histogram.md
> +In Plotly, the **`.histogram()`** method as a part of the `plotly.express` interface, is used to make a graphical representation of data as an accumulated bar chart where, each stocked data is counte
```suggestion
In Plotly, the `**.histogram()**` method in the `plotly.express` module is used to create a graphical representation of data as a bar chart that shows the distribution of a dataset. The bars represent the count of data points within specified ranges (bins). This method also allows for aggregation functions like sum, average, and count, which can be applied to visualize data on categorical, date, or linear axes. 

The elements of the histogram graph are:
```

2024-08-22 15:11 UTC, avdhoottt commented on content/plotly/concepts/express/terms/histogram/histogram.md
> +plotly.express.histogram(data_frame=None, x=None, y=None, color=None, pattern_shape=None, facet_row=None, facet_col=None, facet_col_wrap=0, facet_row_spacing=None, facet_col_spacing=None, hover_name=
```suggestion
plotly.express.histogram(
    data_frame,    # Your DataFrame containing the data
    x,             # Column name for the x-axis (required)
    y=None,        # Optional column name for the y-axis
    color=None,    # Optional column name for color grouping
    facet_row=None,# Optional column name to split data into rows
    facet_col=None,# Optional column name to split data into columns
    hover_data=None,# Optional list of column names for hover info
    marginal=None, # Optional to add marginal plots (e.g., 'rug', 'box')
    opacity=None,  # Optional opacity for bars
    orientation=None,# 'v' or 'h' for vertical or horizontal bars
    barmode='relative', # Bar stacking mode: 'relative', 'overlay', etc.
    title=None,    # Optional title for the plot
    template=None, # Optional Plotly template (e.g., 'plotly_dark')
    width=None,    # Optional plot width
    height=None    # Optional plot height
)
```

2024-08-22 15:11 UTC, avdhoottt commented on content/plotly/concepts/express/terms/histogram/histogram.md
> +fig.show()
```suggestion
# Importing plotly.express as px
import plotly.express as px

# Loading a built-in data frame
df = px.data.tips()

# Creating the histogram with "total_bill" as the x variable and integer 20 as nbins
fig = px.histogram(df, x="total_bill", nbins=20)

# Showing the histogram plot
fig.show()
```

2024-09-04 14:05 UTC, avdhoottt commented on content/plotly/concepts/express/terms/histogram/histogram.md
> +  - 'paths/data-science-foundations'
```suggestion
  - 'learn-python-3'
  - 'paths/computer-science'
```

2024-09-05 14:12 UTC, Sriparno08 approved these changes
Looks good, @romanwilk!

2024-09-05 14:13 UTC, merged