[Topic Entry] Sklearn:Support-Vector-Machines
Codecademy/docs pull request #4918
Opened 2024-07-12 20:08 UTC by liamjdavis

### Description

Added a new topic for Support Vector Machines with Sklearn, as well as adding 'supervised learning' and 'unsupervised learning' to tags.

### Issue Solved

#4860 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-12 20:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4918) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4918) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4918) it.</sub>

2024-07-26 18:03 UTC, avdhoottt requested changes
Hey @liamjdavis, Excellent entry! I've suggested some changes, please make them. Thanks!!

2024-07-26 18:03 UTC, avdhoottt commented on content/sklearn/concepts/support-vector-machines/support-vector-machines.md
> +
Write a line here describing the code.

2024-07-26 18:03 UTC, avdhoottt commented on content/sklearn/concepts/support-vector-machines/support-vector-machines.md
> +- For highly complex data, experiment with different kernels and C values using techniques like grid search.
```suggestion
- For linearly separable data, use the `linear` kernel.
- For moderately complex, non-linear data, consider `rbf` or a low-degree `poly` kernel with a moderate C value.
- For highly complex data, experiment with different kernels and C values using techniques like grid search.
```

2024-07-26 18:03 UTC, avdhoottt commented on content/sklearn/concepts/support-vector-machines/support-vector-machines.md
> +## Example
Move the example section after the `Syntax` subheading. The example section should contain a code block and its output.

2024-07-28 18:08 UTC, liamjdavis commented
@avdhoottt I've edited the entry with your suggestions. Please take another look as soon as you can. Thank you.

2024-08-06 09:18 UTC, avdhoottt approved these changes
LGTM!!

2024-08-07 06:24 UTC, Sriparno08 approved these changes
Looks good, @liamjdavis! 👍

2024-08-07 06:25 UTC, merged