Create thematic-analysis.md
Codecademy/docs pull request #4919
Opened 2024-07-13 02:23 UTC by sturrdlefish

### Description

A term entry on thematic analysis has been created at docs/content/uiux/concepts/qualitative-research/thematic-analysis/thematic-analysis.md.

### Issue Solved

Closes #4903 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-13 02:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4919) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4919) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4919) it.</sub>

2024-07-26 16:59 UTC, SaviDahegaonkar approved these changes
Hey @sturrdlefish ,
I looked at your file, and I find it absolutely correct, so I hereby approve it for the first review.

2024-07-26 16:59 UTC, SaviDahegaonkar commented on content/uiux/concepts/qualitative-research/thematic-analysis/thematic-analysis.md
> +Once the data has been categorized, themes can be determined within the created codes. A theme is a core idea that is obtained through observing similar concepts within a code, indicating something a
```suggestion
## Themes
Once the data has been categorized, themes can be determined within the created codes. A theme is a core idea that is obtained through observing similar concepts within a code, indicating something about user needs or preferences, and providing meaningful insights.
```

2024-07-30 11:00 UTC, mamtawardhani requested changes
Hey @sturrdlefish thank you for your contribution, the entry is nicely written! 😃 

I've suggested a few changes, could you please review and modify them at your earliest convenience? Thank you! 😄

2024-07-30 17:41 UTC, sturrdlefish commented on content/uiux/concepts/qualitative-research/thematic-analysis/thematic-analysis.md
> +**Thematic analysis** is done by examining qualitative data (e.g. results from user interviews or feedback forms) and identifying patterns within it, categorizing it using **codes** and using those c
Added! All changes have now been completed

2024-08-02 10:41 UTC, mamtawardhani approved these changes
Thank you for your contribution @sturrdlefish. The entry looks good to be merged 😄 🎊

2024-08-02 13:11 UTC, mamtawardhani commented
Hey @sturrdlefish, we'll need a small change from your side. The current path is wrong, please change it to:
`docs/content/uiux/concepts/qualitative-research/terms/thematic-analysis/thematic-analysis.md`
You are missing the terms folder. Please do this at your earliest. Thank you! 😃

2024-08-02 19:13 UTC, sturrdlefish commented
@mamtawardhani Fixed! :)

2024-08-03 07:04 UTC, merged