new entry java deque
Codecademy/docs pull request #4924
Opened 2024-07-15 13:06 UTC by zottima

### Description

New concept entry for Java: Deque

### Issue Solved

#4451

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-15 13:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4924) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4924) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4924) it.</sub>

2024-07-18 21:30 UTC, avdhoottt requested changes
Hey Author, I've suggested some changes, please make them. Thanks!!

2024-07-18 21:30 UTC, avdhoottt commented on content/java/concepts/deque/deque.md
> +- `.getFirst()`: Returns, without removal, the first item of the `Deque`.
```suggestion
- `.getFirst()`: Returns, without removal, the first item of the `Deque`. It throws an exception if the Deque is empty.
```

2024-07-30 13:11 UTC, zottima commented on content/java/concepts/deque/deque.md
> +Where [`DataType`](https://www.codecademy.com/resources/docs/java/data-types) is the data type to be stored in the deque, and `DequeClass` is a class implementing the `Deque` interface, for example,
Can you please elaborate? I don't think I understand what you mean.

2024-07-30 17:03 UTC, avdhoottt commented
Hey @zottima, its been two weeks since I suggested the changes. Are you still working on this PR?

2024-08-07 18:19 UTC, avdhoottt commented on content/java/concepts/deque/deque.md
> +
```suggestion
```

2024-08-07 18:24 UTC, avdhoottt approved these changes
LGTM!

2024-08-07 19:35 UTC, zottima commented
> Hey @zottima, its been two weeks since I suggested the changes. Are you still working on this PR?

Yeah, I've been waiting for your reply to my question regarding one of your comments.

2024-08-09 15:24 UTC, avdhoottt commented
> > Hey @zottima, its been two weeks since I suggested the changes. Are you still working on this PR?
> 
> Yeah, I've been waiting for your reply to my question regarding one of your comments.

Yes, you can ask it but I've already made the changes.

2024-08-09 15:24 UTC, merged