C# interface concept enhancement. Issue # 4894
Codecademy/docs pull request #4951
Opened 2024-07-18 08:50 UTC by LewisMK

### Description

Editing the existing code block to demonstrate default implementations for some of the Interface members. Default implementations are now supported from C# version 8.0. 

### Issue Solved

Closes #4894  

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-21 15:00 UTC, cigar-galaxy82 reviewed
Hi, I have suggested a change please modify

2024-07-21 15:11 UTC, cigar-galaxy82 requested changes

2024-07-21 15:11 UTC, cigar-galaxy82 commented on content/c-sharp/concepts/interfaces/interfaces.md
> +## Codebyte
give a blank line between the heading and the codeblock

2024-07-21 15:12 UTC, cigar-galaxy82 commented
Hi @LewisMK thank you for contributing to Codecademy docs. I have suggested few changes please modify

2024-07-22 11:43 UTC, LewisMK commented
Hi @cigar-galaxy82 , thank you for the feedback. Working on the changes.

2024-07-23 11:12 UTC, LewisMK commented
Hi @cigar-galaxy82 I have made the requested changes. Please check and let me know if there is anything more I can do to make it better. Thank you.

2024-08-07 02:01 UTC, cigar-galaxy82 approved these changes

2024-08-07 02:04 UTC, cigar-galaxy82 commented
Hi @LewisMK the changes look good its ready for next review

2024-08-08 11:10 UTC, Sriparno08 approved these changes
Looks good, @LewisMK! 👍

2024-08-08 11:11 UTC, merged

2024-08-08 13:54 UTC, LewisMK commented
Thank you @cigar-galaxy82  and @Sriparno08 for the guidance and review.