Pie
Codecademy/docs pull request #4953
Opened 2024-07-18 10:35 UTC by jmarsden8

### Description

Created plotly pie sheet.

### Issue Solved

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-19 08:11 UTC, mamtawardhani requested changes
@jmarsden8 Thank you for your contribution to the Codecademy Docs, the entry is nicely written! 😃 

I've suggested a few changes in the entry, could you please review and modify those at your earliest convenience? Also, here is a sample entry to highlight the `Syntax` and the parameter description part that I've mentioned in the comment: https://github.com/Codecademy/docs/pull/4789/files

Thank you! 😄

2024-07-19 08:11 UTC, mamtawardhani commented on content/plotly/concepts/express/terms/pie/pie.md
> +## .pie()
```suggestion
---
Title: '.pie()'
Description: 'Creates a pie chart, a circular statistical graphic divided into slices to illustrate numerical proportions.'
Subjects:
  - 'Data Science'
  - 'Data Visualization'
Tags:
  - 'Graphs'
  - 'Libraries'
  - 'Plotly'
  - 'Data'
CatalogContent:
  - 'learn-python-3'
  - 'paths/computer-science'
---
```

2024-07-19 08:11 UTC, mamtawardhani commented on content/plotly/concepts/express/terms/pie/pie.md
> +## .pie()
Meta data is needed at the start of every entry

2024-07-19 08:11 UTC, mamtawardhani commented on content/plotly/concepts/express/terms/pie/pie.md
> +to get a better idea about the relationships between variables.
```suggestion
In Python, the **`pie()`** method from the Plotly library is used to create a pie chart, which visually represents data proportions. This method helps transform data into an appealing visual format, making it easier for readers to understand the relationships between variables.
```

2024-07-19 08:11 UTC, mamtawardhani commented on content/plotly/concepts/express/terms/pie/pie.md
> +to get a better idea about the relationships between variables.
Reframed the sentence for better clarity. 
- Avoid using "we", "you" in the sentences.
- The first instance of the term should be in bold and backticks: **`.pie()`**

2024-07-19 08:11 UTC, mamtawardhani commented on content/plotly/concepts/express/terms/pie/pie.md
> +
After the introduction paragraph, use the `## Syntax` block to provide the syntax of the `.pie()` method. Additionally, describe the parameters in the syntax in the following format:
- `parameter1`: Its description
- `parameter2`: its description
- `parametern`: its description

2024-07-19 08:11 UTC, mamtawardhani commented on content/plotly/concepts/express/terms/pie/pie.md
> +```
These explanations can be added in the comments of the code itself

2024-07-19 08:11 UTC, mamtawardhani commented on content/plotly/concepts/express/terms/pie/pie.md
> +```
```suggestion
## Example

The example below shows the usage of the `.pie()` method as follows:

```py
```

2024-07-20 10:16 UTC, closed without merging

2024-07-22 09:41 UTC, jmarsden8 commented
> Hey @jmarsden8! Could you please provide some insight into why the PR was closed?
> Thank you!

Very sorry, that was unintentional. I will ensure this is sorted as soon as possible.
Thanks