[New Entry] Added SQL SUBSTRING function
Codecademy/docs pull request #4977
Opened 2024-07-26 14:00 UTC by sebasmagno007

### Description

Added a New Entry term for SQL string functions and created the topic SUBSTRING. My motivation is to contibute to Codeacademy docs in the topics that I am learning.

### Issue Solved
Closes issue #4960  

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-26 14:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4977) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4977) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4977) it.</sub>

2024-08-06 03:40 UTC, cigar-galaxy82 requested changes

2024-08-06 03:40 UTC, cigar-galaxy82 commented on content/sql/concepts/string-function/terms/substring/substring.md
> +Feel free to practice in this [data set](https://www.w3schools.com/sql/trysqlserver.asp?filename=trysql_func_sqlserver_substring2).
Please rather than text and images use code to explain this whole part

2024-08-06 03:42 UTC, cigar-galaxy82 commented
Hi @sebasmagno007 thank you for contributing to Codecademy docs, the entry is well written, I have suggested a few changes please modify

2024-08-12 17:49 UTC, sebasmagno007 commented
The changes have been made.

2024-09-02 15:25 UTC, cigar-galaxy82 approved these changes

2024-09-04 10:22 UTC, Sriparno08 approved these changes
Looks good, @sebasmagno007!

This entry will be merged soon.

2024-09-13 17:24 UTC, merged