Added new concept entry for Naive Bayes in Sklearn
Codecademy/docs pull request #4992
Opened 2024-07-29 20:51 UTC by uhck

### Description

Added a new concept entry file naive-bayes.md

### Issue Solved

Closes #4930

### Type of Change

- Adding a new entry
### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-29 20:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4992) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4992) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4992) it.</sub>

2024-07-30 05:48 UTC, mamtawardhani commented
> [![CLA assistant check](https://camo.githubusercontent.com/fbf2b4a56b8f8dacb3fb4f7f3cf7877b8c27f9cfee8546ff24c8df94facca0f6/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/Codecademy/docs?pullRequest=4992) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4992) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4992) it.

Hey @uhck, could you please sign the CLA so we can proceed with the review? Thank you!

2024-07-30 10:46 UTC, uhck commented
Signed!

2024-08-02 11:21 UTC, mamtawardhani commented
> Signed!

Thank you, will review it ASAP

2024-08-05 10:32 UTC, mamtawardhani requested changes
Hey @uhck! Thank you for your contribution to Codecademy Docs, the entry looks well written! 😃 

I've suggested a few changes, could you please review and modify them at your earliest convenience? Thank you!

2024-08-05 10:32 UTC, mamtawardhani commented on content/sklearn/concepts/naive-bayes/naive-bayes.md
> +```
This can be removed since it is a concept entry. For syntax and codebyte example we will be adding more term enteries.

2024-08-05 19:08 UTC, uhck commented on content/sklearn/concepts/naive-bayes/naive-bayes.md
> +---
Done

2024-08-05 19:10 UTC, uhck commented on content/sklearn/concepts/naive-bayes/naive-bayes.md
> +**Naive Bayes** are supervised learning algorithms that calculate the probability of an outcome based on input data and some prior knowledge, assuming all inputs are equal and independent of each oth
Thanks

2024-08-06 09:38 UTC, mamtawardhani approved these changes
Thank you for making the required changes @uhck, the entry looks good for a second round of review! 😄

2024-08-08 14:45 UTC, Sriparno08 approved these changes
Looks good, @uhck! 👍

2024-08-08 14:46 UTC, merged