[Term Entry] C++ vector .size()
Codecademy/docs pull request #4994
Opened 2024-07-31 13:08 UTC by eddiepeters00

### Description
Added a new term entry for the `.size()` method on vectors in c++.

### Issue Solved
Closes #4981

### Type of Change
- Adding a new entry

### Checklist
- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-07-31 13:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4994) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4994) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4994) it.</sub>

2024-08-01 19:04 UTC, SaviDahegaonkar approved these changes
Hey Author,
I had a look at your PR and hereby approve it for the next review.

Thanks,
Savi

2024-08-03 07:51 UTC, mamtawardhani requested changes
Hey @eddiepeters00, thank you so much for your contribution to Codecademy Docs! The entry is nicely written 😄 

I've suggested a few changes, could you please review and modify those at your earliest convenience? 
Also, please remove the `extensions.json` file from this branch.
Thank you! 😃

2024-08-03 07:51 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/size/size.md
> +`.size()` is there to follow the consistency of other standard library containers (e.g., [maps](https://www.codecademy.com/resources/docs/cpp/maps) and [strings](https://www.codecademy.com/resources/
```suggestion
The **`.size()`** method returns the number of elements in the vector. It follows the consistency of other standard library containers, such as [maps](https://www.codecademy.com/resources/docs/cpp/maps) and [strings](https://www.codecademy.com/resources/docs/cpp/strings).
```

2024-08-03 07:51 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/size/size.md
> +`.size()` is there to follow the consistency of other standard library containers (e.g., [maps](https://www.codecademy.com/resources/docs/cpp/maps) and [strings](https://www.codecademy.com/resources/
Reframed for better clarity

2024-08-03 07:51 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/size/size.md
> +## Codebyte Example
```suggestion
## Example
```

2024-08-03 07:51 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/size/size.md
> +```codebyte/cpp
```suggestion
```cpp
```

2024-08-03 07:51 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/size/size.md
> +```
Please add an output of the above code block below as follows: (use the ```shell``` block)

The output of the above code is:

```shell
4
```

2024-08-03 07:51 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/size/size.md
> +The `vector` must be defined with `std::vector` prior to using with the `.size()` method.
```suggestion
The `vector` must be defined using `std::vector` before the `.size()` method can be used.
```

2024-08-03 07:51 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/size/size.md
> +## Codebyte Example
For this issue, an Example block is needed

2024-08-03 07:51 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/size/size.md
> +```codebyte/cpp
In the example block, we use the ```cpp block. If it was a codebyte block, then we use the ```codebyte/cpp

2024-08-06 09:20 UTC, mamtawardhani approved these changes
Thank you for making the required changes @eddiepeters00. The entry is ready to be merged! 😄

2024-08-06 09:21 UTC, merged