Add .emplace() entry for C++ vector
Codecademy/docs pull request #4998
Opened 2024-08-05 17:47 UTC by makrischaralampos

### Description

This pull request introduces a new entry for the `.emplace()` function in C++ vectors. The entry provides an overview of the function, including its syntax, and includes an example demonstrating its usage. This addition is intended to enhance the documentation for C++ vectors by explaining how to efficiently construct elements directly within a vector.

### Issue Solved

Closes #4989 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-08-05 17:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4998) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4998) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4998) it.</sub>

2024-08-14 08:53 UTC, cigar-galaxy82 requested changes

2024-08-14 08:53 UTC, cigar-galaxy82 commented on content/cpp/concepts/vectors/terms/emplace/emplace.md
> +In this example, an object of `MyClass` is directly constructed at the beginning of the vector using `.emplace()`, with arguments `10` and `20`. This method is more efficient than `.push_back()` beca
Also, show the output of this code in a shell block

2024-08-23 06:27 UTC, mamtawardhani approved these changes
Thank you for your contribution @makrischaralampos 😄 

The entry is good to be merged! 🚀

2024-08-23 18:07 UTC, cigar-galaxy82 approved these changes

2024-08-24 12:47 UTC, merged