[Term Entry] C++ vector .assign()
Codecademy/docs pull request #5002
Opened 2024-08-05 23:37 UTC by Great-Visions-Code

### Description

- Added the vector.assign() term for C++

### Issue Solved

- Closes #4988 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-08-06 00:57 UTC, Great-Visions-Code commented
Ran scripts to have checks pass. Let me know if any other fixes are needed. Thank you.

2024-08-14 13:01 UTC, cigar-galaxy82 requested changes

2024-08-14 13:02 UTC, cigar-galaxy82 commented
Hi @Great-Visions-Code thank you for contributing to Codecademy docs, I have suggested a few changes please modify

2024-08-14 17:21 UTC, Great-Visions-Code commented on content/cpp/concepts/vectors/terms/assign/assign.md
> +}
@cigar-galaxy82 quick question. There is an added line on line 52 after the for loop. Should I also make that change to line 61? Add a line after line 60, after the 2nd for loop so they match?

2024-08-14 17:29 UTC, Great-Visions-Code commented
Hi @cigar-galaxy82. I have made the changes suggested. Let me know how it looks on your end and if any other modifications are needed. Thank you.

2024-08-22 19:38 UTC, cigar-galaxy82 commented on content/cpp/concepts/vectors/terms/assign/assign.md
> +}
I'll recommend adding a gap, I have made that changes

2024-08-23 18:08 UTC, cigar-galaxy82 approved these changes

2024-08-25 06:03 UTC, mamtawardhani approved these changes
Thank you for your contribution to Codecademy Docs @Great-Visions-Code 😄 

The entry is ready to be merged! 🚀

2024-08-25 06:05 UTC, merged