[Term Entry] C++ vector.erase() #4987
Codecademy/docs pull request #5008
Opened 2024-08-07 21:00 UTC by Son0-lory

### Description

Added a new term entry for the *.erase()* method on vectors in C++ language.

### Issue Solved

Close # 4987

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-08-08 19:53 UTC, Son0-lory commented on content/cpp/concepts/vectors/terms/erase/erase.md
> +Rooms available: 1 2 4 5 6 7
Rooms available: 1 2 3 4 5 6 7

2024-08-10 08:19 UTC, mamtawardhani requested changes
Hey @Son0-lory, thank you for contributing to the Codecademy Docs, the entry is well written! 😃 

I've suggested a few changes, please review and modify them at your earliest convenience. Feel free to dicuss any point. Thank you! 😄

2024-08-10 08:19 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/erase/erase.md
> +---
```suggestion
---
Title: '.erase()'
Description: 'Removes a single element or a range of elements from a vector.'
Subjects:
  - 'Computer Science'
  - 'Game Development'
Tags:
  - 'Arrays'
  - 'Data Structures'
  - 'Vectors'
CatalogContent:
  - 'learn-c-plus-plus'
  - 'paths/computer-science'
---
```

2024-08-10 08:19 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/erase/erase.md
> +---
Arranged the tags in an alphabetical manner

2024-08-10 08:19 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/erase/erase.md
> +The position of the elements to remove are identified with `.begin()` and/or `.end()` functions.
```suggestion
The **`.erase()`** function removes a single element or a range of elements from a specific position in the `vector`. When an element is removed with the `.erase()` function, the size of the `vector` decreases, and the elements after the deleted ones are shifted to fill the gap. The positions of the elements to remove are identified with `.begin()` and/or `.end()` functions.
```

2024-08-10 08:19 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/erase/erase.md
> +The position of the elements to remove are identified with `.begin()` and/or `.end()` functions.
Modifications:
1. the first instance of the term should be in **bold** and `backticks`
2. Reframed the sentence for better clarity, it had some spelling mistakes
3. Every time we use a term, always put it in backticks: `erase()`, `.end()`, etc
4. We can either call it as a function or a method, so I changed the instance of method to function in this sentence.

2024-08-10 08:19 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/erase/erase.md
> +The second syntax removes a range of elements.
```suggestion
```  
To remove a single element from the vector:

```
vector.erase(position)
```

- `position`: An iterator pointing to the element to be removed.

To eliminate a range of elements:

```
vector.erase(starting_position, ending_position)
```

- `starting_position`: An iterator indicating the beginning of the range to be removed.
- `ending_position`: An iterator indicating the end of the range to be removed.
```

2024-08-10 08:19 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/erase/erase.md
> +The second syntax removes a range of elements.
Modifications:
1. The above format maintains a structure for the reader.
2. Also, whenever we give a syntax, make sure to describe the parameters in short as above.

2024-08-10 08:19 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/erase/erase.md
> +In the example below *.erase()* removes a single element:
```suggestion
In the example below `.erase()` removes a single element:
```

2024-08-10 08:19 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/erase/erase.md
> +In the example below *.erase()* removes a single element:
backticks to represent a term

2024-08-10 08:19 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/erase/erase.md
> +Rooms available: 1 2 4 5 6 7 8 9 10
```suggestion
The output of the above code is :

```shell
Rooms available: 1 2 4 5 6 7 8 9 10
```

2024-08-10 08:19 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/erase/erase.md
> +Rooms available: 1 2 4 5 6 7 8 9 10
one line space is needed

2024-08-10 08:19 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/erase/erase.md
> +In the example below *.erase()* removes a range of element:
```suggestion
In the example below `.erase()` removes a range of element:
```

2024-08-10 08:19 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/erase/erase.md
> +In the example below *.erase()* removes a range of element:
backticks to represent a term

2024-08-10 08:19 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/erase/erase.md
> +Rooms available: 1 2 4 5 6 7
```suggestion
The output of the above code is :

```shell
Rooms available: 1 2 4 5 6 7
```

2024-08-10 08:19 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/erase/erase.md
> +Rooms available: 1 2 4 5 6 7
one line space is needed

2024-08-10 08:19 UTC, mamtawardhani commented on content/cpp/concepts/vectors/terms/erase/erase.md
> +    // Print out element left in the vector
```suggestion
    // Print out elements left in the vector
```

2024-08-10 12:05 UTC, Son0-lory commented
Hi,
the code as been modified as suggested, thanks. 
Syntax paragrapher is now improved.

2024-08-12 11:04 UTC, mamtawardhani approved these changes
Thank you for making the required changes @Son0-lory 😃 

The entry looks good for a second round of review! 🚀

2024-08-13 06:13 UTC, Sriparno08 approved these changes
Looks good, @Son0-lory! 👍

2024-08-13 06:14 UTC, merged