Add General/Routing, Issue #281
Codecademy/docs pull request #502
Opened 2022-01-02 14:39 UTC by SSwiniarski

### Description

Add entry for General/Routing.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

2022-01-03 22:51 UTC, Dusch4593 commented
I'll take on the first review for this one 😄

2022-01-03 23:03 UTC, Dusch4593 commented on content/general/concepts/routing/routing.md
> +
```suggestion

## Type of Routing

```

2022-01-03 23:10 UTC, Dusch4593 commented on content/general/concepts/routing/routing.md
> +When one device communicates to another across a network, such as a PC communicating to a printer across a LAN, or a phone's web browser communicating to a web server over the Internet, there are gen
```suggestion
Routing is the process of deciding what paths communication signals may take across one or more networks. This process is used in many scenarios related to computer networking, including:

- A PC communicating with a printer across a Local Area Network, or LAN.
- A phone's web browser communicating with a web server over the internet.


Through routing, these communication signals, called packets, can take multiple paths from the source to the destination.
```

2022-01-03 23:25 UTC, Dusch4593 commented on content/general/concepts/routing/routing.md
> +A router can be physical piece of hardware, or it can be software based. Software-based routers tend to be more limited in functionality.
```suggestion
## Routers

The process of routing is executed by devices known as  routers. They live on the network where there are junctions (nodes) between these various paths. Routers can either be physical pieces of hardware or software based, which tend to be more limited in functionality.
```

2022-01-03 23:26 UTC, Dusch4593 commented on content/general/concepts/routing/routing.md
> +Description: 'The process of deciding what path packets travel across a network is called routing.'
```suggestion
Description: 'Routing is the process of deciding what paths communication signals may take across one or more networks.'
```

2022-01-03 23:52 UTC, Dusch4593 commented on content/general/concepts/routing/routing.md
> +- Delay/Latency
Could be expand on what each of these items are in a full sentence?

2022-01-03 23:53 UTC, Dusch4593 requested changes
@SSwiniarski Just finished my review! Let us know when you've finished looking over the comments/suggestions.

2022-01-04 12:05 UTC, SSwiniarski commented
@Dusch4593, I implemented all your suggestions.

2022-01-04 15:28 UTC, Dusch4593 approved these changes
Looks good to move on to review 2️⃣!

2022-01-11 02:17 UTC, yangc95 commented on content/general/concepts/routing/routing.md
> +In deciding paths to route traffic, a router always has some default path to send traffic with no specific destination specified. For traffic with a specific destination, if there is more than one pa
Can we be explicit about what kind of traffic we're referring to here?

2022-01-11 02:19 UTC, yangc95 commented on content/general/concepts/routing/routing.md
> +- Anycast Routing: the destination consists of several devices with the same logical address, and the packet is routed to the closest of these devices.
```suggestion
- Unicast Routing: The packet is being sent to a single specified location.
- Broadcast Routing: The packet is sent to all nodes on the network, even nodes that haven't requested it.
- Multicast Routing: Similar to broadcast routing, but packets are only sent to nodes that want them.
- Anycast Routing: The destination consists of several devices with the same logical address and the packet is routed to the closest of these devices.
```

2022-01-11 02:20 UTC, yangc95 reviewed
Solid 👍  Review 2️⃣ done.

2022-01-13 05:12 UTC, yangc95 commented on content/general/concepts/routing/routing.md
> +In deciding paths to route traffic, a router always has some default path to send traffic with no specific destination specified. For traffic with a specific destination, if there is more than one pa
```suggestion
A router always has some default path to send network traffic if no specific destination is specified. For traffic with a specific destination, if there is more than one path, the router can make a decision on what path to use based on several criteria, which can include:
```

2022-01-17 15:47 UTC, SSwiniarski commented
@yangc95, @Dusch4593, I've updated this PR with the latest suggestions.

2022-01-19 22:28 UTC, yangc95 approved these changes
Looks good to me!

2022-01-21 17:08 UTC, Dusch4593 commented
Looks good to merge! 👍 I made a tiny edit in 5a793ba14baf4811bf184d4c7dea57106aa2a2c1

cc: @SSwiniarski @yangc95

2022-01-21 17:08 UTC, merged

2022-01-21 17:11 UTC, Dusch4593 commented
Nice! Live changes here:

https://github.com/Codecademy/docs/pull/502