Cpp inheritance
Codecademy/docs pull request #504
Opened 2022-01-03 17:21 UTC by SSwiniarski

### Description

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

2022-01-04 19:50 UTC, Dusch4593 commented
I'll take on the first review 😄

2022-01-04 19:58 UTC, Dusch4593 commented on content/cpp/concepts/inheritance/inheritance.md
> +Inheritance is generally used when it's necessary to implement a number of different objects that are all of the same type, sharing several characteristics in common.
```suggestion
Inheritance is the ability to create a new class based on an existing class, starting out with the same existing properties and methods. The class that inherits these properties and methods is called the "derived class" or "sub-class". The class that the sub-class inherits from is called the "base class".

Inheritance is generally used when it's necessary to implement a number of different objects that are all of the same type and share several common characteristics.
```

2022-01-04 19:59 UTC, Dusch4593 commented on content/cpp/concepts/inheritance/inheritance.md
> +Description: 'Inheritance is the ability to base a new class on an existing class, creating a class that starts out with the same properties and methods as the existing class.'
```suggestion
Description: 'Inheritance is the ability to create a new class based on an existing class, starting out with the same existing properties and methods.'
```

2022-01-04 20:07 UTC, Dusch4593 commented on content/cpp/concepts/inheritance/inheritance.md
> +## Syntax
```suggestion

## Example

A good example is a `Shape` class that might include:

- A `center` property with (x, y) coordinates.
- A `weight` property that defines a line width.
- A `color` property that would define a fill color. 

Some possible sub-classes derived from this base class might be:

- A`Rectangle` class which would have `height` and `width` properties.
- A `Circle` class that would have a `radius` property.

Both the `Circle` and `Rectangle` classes would share the properties and methods of their base `Shape` class, `Shape`, in addition to properties and methods unique to their own class definition.
```
Could the sub-classes in this example, perhaps, also have the following:

- One shared method from the base `Shape` class (maybe one for finding the area?)
- At least one unique method for each sub-class (ex. Circumference for `Circle` and Perimeter for `Rectangle`)

2022-01-04 20:11 UTC, Dusch4593 commented on content/cpp/concepts/inheritance/inheritance.md
> +- `private` members of the base class aren't accessible to the derived class.
I think this should be moved somewhere in the "Syntax" section and changed to a lv 3 header. (`### Access Specifiers`)

2022-01-04 20:15 UTC, Dusch4593 requested changes
@SSwiniarski Finished! Take a look and let me know when you finished 😃

2022-01-05 18:14 UTC, SSwiniarski commented
@Dusch4593, I've implemented all your suggestions and we're good for review #2.

2022-01-05 18:15 UTC, Dusch4593 approved these changes
LGTM 👍

2022-01-13 05:04 UTC, yangc95 commented
> LGTM 👍

Ditto 👍

2022-01-13 05:04 UTC, yangc95 approved these changes

2022-01-14 00:11 UTC, merged

2022-01-14 00:55 UTC, yangc95 commented
Hey @SSwiniarski, this took some time to display but your entry is live here:

https://www.codecademy.com/resources/docs/cpp/inheritance 🎈

ty @Dusch4593 ❗