[Term Entry] Adding Pytorch Tensor .tensor()
Codecademy/docs pull request #5040
Opened 2024-08-13 18:58 UTC by selenahuang017

Description
Adding new entry on the .tensor() term under PyTorch Tensors concept. It is under docs/content/pytorch/concepts/tensors/terms/tensor/tensor.md.

Issue Solved
[Addresses issue: https://github.com/Codecademy/docs/issues/4937](https://github.com/Codecademy/docs/issues/4935)

Type of Change
Adding a new entry

Checklist
[x ] All writings are my own.
[x ] My entry follows the Codecademy Docs style guide.
[x ] My changes generate no new warnings.
[x ] I have performed a self-review of my own writing and code.
[x ] I have checked my entry and corrected any misspellings.
[x ] I have made corresponding changes to the documentation if needed.
[x ] I have confirmed my changes are not being pushed from my forked main branch.
[x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
[x ] I have linked any issues that are relevant to this PR in the Issues Solved section.

2024-08-21 04:39 UTC, Sriparno08 requested changes
Hey @selenahuang017, thanks for contributing to Codecademy Docs!

I've listed all the modifications that you need to make in your entry below:

2024-08-21 04:39 UTC, Sriparno08 commented on content/pytorch/concepts/tensors/terms/tensor/tensor.md
> +The **`.tensor()`** function creates a tensor from given data input.
```suggestion
The **`.tensor()`** function creates a tensor from a given data input.
```

2024-08-21 04:39 UTC, Sriparno08 commented on content/pytorch/concepts/tensors/terms/tensor/tensor.md
> +Description: 'Creates a tensor of a given shape, and given values.'
```suggestion
Description: 'Creates a tensor of a given shape and given values.'
```

2024-08-21 04:39 UTC, Sriparno08 commented on content/pytorch/concepts/tensors/terms/tensor/tensor.md
> +- `data`: This parameter is the input data for the tensor. The data must be array-like or scalar.
```suggestion
- `data`: This required parameter is the input data for the tensor. The data must be array-like or scalar.
```

2024-08-21 04:39 UTC, Sriparno08 commented on content/pytorch/concepts/tensors/terms/tensor/tensor.md
> +print(t2)
Let's change the code to get the desired output:

```suggestion
import torch

t1 = torch.tensor(3)
print(t1, '\n')

t2 = torch.tensor([[1.0, 3.0, 5.0], [2.0, 6.0, 0.0]])
print(t2)
```

2024-08-22 16:13 UTC, Sriparno08 approved these changes
Good job, @selenahuang017!

This entry looks good for a second round of review. 👍

2024-08-23 09:14 UTC, mamtawardhani approved these changes
Thank you for your contribution @selenahuang017 😄 

The entry looks good to be merged! 🚀

2024-08-23 09:14 UTC, merged