added math.factorial() page
Codecademy/docs pull request #5043
Opened 2024-08-14 13:54 UTC by yuekaim

### Description

added math.factorial() page at python/concepts/math-module/terms

### Issue Solved
#5032

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-08-14 13:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5043) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5043) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5043) it.</sub>

2024-08-19 14:01 UTC, cigar-galaxy82 requested changes

2024-08-19 14:01 UTC, cigar-galaxy82 commented
Hi @yuekaim thank you for contributing to Codecademy docs, I have suggested a few suggestions please modify

2024-08-21 15:39 UTC, yuekaim commented
@cigar-galaxy82 Thanks for the feedback. Sorry for the delay. I have edited to reflect them. I am currently experiencing some local node issues that's taking a while to resolve. I'll push as soon as that's fixed. Thank you.

2024-09-05 17:57 UTC, SaviDahegaonkar requested changes
Hey Author,
The entry is nicely written. Please implement the changes I requested from you so that I can approve and merge them.

Thanks,
Savi

2024-09-05 17:57 UTC, SaviDahegaonkar commented on content/python/concepts/math-module/terms/math-factorial/math-factorial.md
> +The `math.factorial()` method returns the factorial of a positive number.
```suggestion
The `math.factorial()` method returns the factorial of a positive number.
```
The first mention of the concept must always be in **bold**. Please make this correction here.

2024-09-29 08:55 UTC, SaviDahegaonkar approved these changes
The entry LGTM!

Thanks,
Savi

2024-09-29 09:12 UTC, cigar-galaxy82 approved these changes

2024-09-29 10:11 UTC, merged