Python math-module math.copysign()
Codecademy/docs pull request #5044
Opened 2024-08-14 19:28 UTC by sturrdlefish

### Description

Created a term entry for math.copysign().

### Issue Solved

Closes #5029 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-08-16 09:09 UTC, mamtawardhani requested changes
Hey @sturrdlefish thank you for contributing to Codecademy Docs, the entry is nicely written! 😄 

I've two major points:
1. Please remove the `thematic-analysis.md` file from this branch.
2. I've suggested some changes for this file, please review and modify them at your earliest convenience.
Thank you! 😃

2024-08-16 09:09 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-copysign/math-copysign.md
> +---
Modifications: 
1. Description should start with a verb
2. Tags should be arranged in an alphabetical manner

2024-08-16 09:09 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-copysign/math-copysign.md
> +Takes two numeric data types and returns the value of the first data type with the sign of the second data type.
```suggestion
The `math.copysign()` function in Python takes two numeric values and returns a float with the magnitude of the first value and the sign of the second value.
```

2024-08-16 09:09 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-copysign/math-copysign.md
> +The value that is returned by **`math.copysign()`** will have the value of `x` and the sign (+ or -) of `y`. This value will be a float.
```suggestion
```

2024-08-16 09:09 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-copysign/math-copysign.md
> +The value that is returned by **`math.copysign()`** will have the value of `x` and the sign (+ or -) of `y`. This value will be a float.
We can avoid this since the description already covers this

2024-08-16 09:09 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-copysign/math-copysign.md
> +
```suggestion

- `x`: A numeric value (int or float) whose magnitude is used in the result.
- `y`: A numeric value (int or float) whose sign is used in the result.
```

2024-08-16 09:09 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-copysign/math-copysign.md
> +
parameters to be described. You can change these, these are just for your reference

2024-08-16 09:09 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-copysign/math-copysign.md
> +Use `math.copysign()` to return `10` with the same sign as `-5`:
```suggestion
In the example below, `math.copysign()` is used to return *10* with the same sign as *-5*:
```

2024-08-17 01:13 UTC, sturrdlefish commented
The changes have been made :)

2024-08-17 06:43 UTC, mamtawardhani approved these changes
Thank you for making the changes @sturrdlefish 😄 

The entry looks good for a second round of review 🚀

2024-08-17 15:12 UTC, Sriparno08 approved these changes
Looks good, @sturrdlefish!

2024-08-17 15:12 UTC, merged