Create concept entry for HEX function for MySQL
Codecademy/docs pull request #5046
Opened 2024-08-16 05:24 UTC by ebikatsudon

### Description

Created documentation for the MySQL hex function. Describes the function's usage, syntax, and includes some examples in action.

### Issue Solved

Closes #5023 

### Type of Change

- Adding a new entry

### Checklist

- [ x ] All writings are my own.
- [ x ] My entry follows the Codecademy Docs style guide.
- [ x ] My changes generate no new warnings.
- [ x ] I have performed a self-review of my own writing and code.
- [ x ] I have checked my entry and corrected any misspellings.
- [ x ] I have made corresponding changes to the documentation if needed.
- [ x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-08-16 05:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5046) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5046) before we can accept your contribution.<br/><hr/>**ebikatsudon** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5046) it.</sub>

2024-08-19 12:47 UTC, cigar-galaxy82 commented
Hi @ebikatsudon can you please sign the CLA

2024-08-19 23:27 UTC, ebikatsudon commented
Sorry about that -- I had forgotten to add the email used for the commit to my Github account. I have signed the CLA; please let me know if there is anything else I need to do. Thank you!

2024-08-20 18:46 UTC, cigar-galaxy82 requested changes

2024-08-20 18:46 UTC, cigar-galaxy82 commented on content/mysql/concepts/hex/hex.md
> +If the input is a string, the resulting hexadecimal representation will, by default, be a binary string. Each byte of each character in the original string argument is represented by a corresponding
```suggestion
When the input is a string, the resulting hexadecimal representation will, by default, be a binary string. In the output, each byte of each character in the original string argument is represented by a corresponding pair of hexadecimal digits. The resulting hexadecimal string can also be converted back into the original string by using the `UNHEX()` function.
```

2024-08-20 18:46 UTC, cigar-galaxy82 commented on content/mysql/concepts/hex/hex.md
> +On the other hand, if the input is a decimal number, the resulting hexadecimal will be treated as a longlong (BIGINT) number.  In this scenario where N is a decimal number, the function `HEX(N)` prod
```suggestion
When the input is a decimal number, HEX(N) and CONV(N, 10, 16) produce the same hexadecimal output. The hexadecimal result from HEX(N) can be converted back to the original number using CONV(HEX(N), 16, 10).
```

2024-08-20 18:46 UTC, cigar-galaxy82 commented on content/mysql/concepts/hex/hex.md
> +The **HEX()** function in MySQL takes an input and returns its equivalent hexadecimal representation. This input can be either a string or numeric value.
```suggestion
The **`HEX()`** function in MySQL takes an input and returns its equivalent hexadecimal representation. This input can be either a string or a numeric value.
```

2024-08-20 18:46 UTC, cigar-galaxy82 commented on content/mysql/concepts/hex/hex.md
> +```
Put this in a single code block, consisting of creating the table, inserting and verifying the data

2024-08-20 18:46 UTC, cigar-galaxy82 commented on content/mysql/concepts/hex/hex.md
> +The resulting table looks like:
```suggestion
The resulting table looks like this:
```

2024-08-20 18:46 UTC, cigar-galaxy82 commented on content/mysql/concepts/hex/hex.md
> +Title: 'Hex()'
```suggestion
Title: 'HEX()'
```

2024-08-20 18:46 UTC, cigar-galaxy82 commented on content/mysql/concepts/hex/hex.md
> +  - 'Database'
```suggestion
  - 'Functions'
  - 'Database'
  - 'MySQL'
  - 'Strings'
  - 'Numbers'
```

2024-08-20 18:46 UTC, cigar-galaxy82 commented on content/mysql/concepts/hex/hex.md
> +  Tags:
```suggestion
Tags:
```

2024-08-20 18:46 UTC, cigar-galaxy82 commented on content/mysql/concepts/hex/hex.md
> + ## Syntax
```suggestion
## Syntax
```

2024-08-20 18:46 UTC, cigar-galaxy82 commented on content/mysql/concepts/hex/hex.md
> +| Williams  | 57696C6C69616D73 |
Give one line after this

2024-08-20 18:47 UTC, cigar-galaxy82 commented
Hi @ebikatsudon thank you for contributing to Codecademy docs, I have suggested a few suggestions please modify

2024-08-22 03:08 UTC, ebikatsudon commented
Hello @cigar-galaxy82, I have made the requested changes. Please let me know if you have any additional comments or suggestions. Thank you!

2024-08-31 00:36 UTC, ebikatsudon commented
Hello, just wanted to double-check if there's anything else I need to do for this? @cigar-galaxy82

2024-09-05 05:46 UTC, mamtawardhani commented
@cigar-galaxy82 could you please check this on priority? It's been two weeks to this. Thank you

2024-09-05 19:28 UTC, cigar-galaxy82 approved these changes

2024-09-09 06:32 UTC, Sriparno08 approved these changes
Looks good, @ebikatsudon!

2024-09-09 06:33 UTC, merged