[Term Entry] Python Random function: .triangular()
Codecademy/docs pull request #5055
Opened 2024-08-19 01:35 UTC by auvaydov

### Description

-Added the random.triangular() method for python

### Issue Solved

-Closes #issue-5026

### Type of Change

- Adding a new entry

### Checklist

- [ x] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-08-19 01:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5055) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5055) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5055) it.</sub>

2024-08-20 09:22 UTC, mamtawardhani requested changes
Hey @auvaydov thank you for contributing to Codecademy Docs, the entry is nicely written!

I've suggested a few modifications, could you please review and modify them at your earliest convenience? Thank you! 😄

2024-08-20 09:22 UTC, mamtawardhani commented on content/python/concepts/random-module/terms/triangular/triangular.md
> +---
```suggestion
---
Title: '.triangular()'
Description: 'Returns a random floating number from a triangular distribution.'
Subjects: 
  -'Computer Science'
  -'Data Science'
Tags:
  -'Functions'
  -'Methods'
  -'Random'
Catalog Content: 
  -'learn-python-3'
  -'paths/computer-science'
  -"paths/data-science'
---
```

2024-08-20 09:22 UTC, mamtawardhani commented on content/python/concepts/random-module/terms/triangular/triangular.md
> +---
Meta data to be written in single quotes ( ' ' ) and the title should be the term itself.

2024-08-20 09:22 UTC, mamtawardhani commented on content/python/concepts/random-module/terms/triangular/triangular.md
> +"The ** `.triangular()` ** method returns a random floating number from a triangular distribution. Input parameters are `low`, `high` and `mode`. If `mode` not provided, the midpoint is set to defaul
```suggestion
The **`.triangular()`** method returns a random floating-point number from a triangular distribution. The input parameters are `low`, `high`, and `mode`. If `mode` is not provided, it defaults to the midpoint between `low` and `high`.
```

2024-08-20 09:22 UTC, mamtawardhani commented on content/python/concepts/random-module/terms/triangular/triangular.md
> +random.triangular(low,high,mode)
```suggestion
random.triangular(low, high, mode)
```

2024-08-20 09:22 UTC, mamtawardhani commented on content/python/concepts/random-module/terms/triangular/triangular.md
> +Where `low` and `high` correspond to the required lower and upper limits of distribution, and `mode` is an optional input for peak of the distribution.
Instead of this, could you define the parameters in the following format:

- `low`: description
- `high`: description
- `mode`: description

2024-08-20 09:22 UTC, mamtawardhani commented on content/python/concepts/random-module/terms/triangular/triangular.md
> +Example output:
```suggestion
The code above produces the following output:

```

2024-08-20 09:22 UTC, mamtawardhani commented on content/python/concepts/random-module/terms/triangular/triangular.md
> +print('random.triangular(1,100)
```suggestion
import random

print(random.triangular(1,100,80))
print(random.triangular(350,1000,385))
print(random.triangular(4,5,4))
print(random.triangular(1,100))
```

2024-08-20 09:22 UTC, mamtawardhani commented on content/python/concepts/random-module/terms/triangular/triangular.md
> +The following examples prints a random floating-point value between 1 and 100, biased towards 70; 350 and 1000, biased towards 385; 4 and 5, biased towards 4; 1 and 100 with default bias at midpoint.
```suggestion
Run the following code to see how random.triangular() generates random values with different biases:
```

2024-08-20 09:22 UTC, mamtawardhani commented on content/python/concepts/random-module/terms/triangular/triangular.md
> +
We can add a note here, after the output, saying that it will always generate a random value.

2024-08-20 09:22 UTC, mamtawardhani commented on content/python/concepts/random-module/terms/triangular/triangular.md
> +print(random.triangular(50,500,400)
```suggestion
print(random.triangular(50,500,400))
```

2024-08-20 09:22 UTC, mamtawardhani commented on content/python/concepts/random-module/terms/triangular/triangular.md
> +print(random.triangular(50,500,400)
missing `)`

2024-08-22 06:52 UTC, mamtawardhani approved these changes
Thank you for making the changes @auvaydov 😄 

The entry looks good for a second round of review! 🚀

2024-08-28 08:35 UTC, Sriparno08 approved these changes
Looks good, @auvaydov! 👍

2024-08-28 08:38 UTC, merged