[New Term for Existing Concept Entry] Pytorch Tensore .size()
Codecademy/docs pull request #5088
Opened 2024-08-22 18:52 UTC by maroline-johnson

Add a new term entry about the .size() method for Tensors.

### Description

I've added a new term entry - .size() - for an existing concept - content/pytorch/concepts/tensors. I created a new folder - size - with a new file - size.md. 

### Issue Solved

Closes #5058

### Type of Change

- Adding a new entry

### Checklist

- [X ] All writings are my own.
- [X ] My entry follows the Codecademy Docs style guide.
- [X ] My changes generate no new warnings.
- [X ] I have performed a self-review of my own writing and code.
- [X ] I have checked my entry and corrected any misspellings.
- [X ] I have made corresponding changes to the documentation if needed.
- [X ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-08-22 18:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5088) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5088) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5088) it.</sub>

2024-08-23 17:06 UTC, SaviDahegaonkar requested changes
Hey @maroline-johnson,
First of all, I must say, the entry is nicely written. I would suggest a very few minor changes to this PR to get it approved for the first review. Please do the suggested changes. Also, I would like to add that you should add a small codebyte example at the end of this entry. Please do it asap and let me know.

Thanks,
Savi

2024-08-31 18:21 UTC, SaviDahegaonkar requested changes
Hey @maroline-johnson,
The entry is nicely written. I have again suggested a very few changes, please do it asap.

Thanks,
Savi

2024-08-31 18:21 UTC, SaviDahegaonkar commented on content/pytorch/concepts/tensors/size/size.md
> +The **`size()`** method returns a `torch-size` object containing the size information of a Pytorch tensor. It is a fundamental function used in PyTorch to obtain the tensor's shape and is specificall
```suggestion
The **`size()`** method returns a `torch.Size` object containing the size information of a Pytorch tensor. It is a fundamental function used in PyTorch to obtain the tensor's shape and is specifically used for dynamic operations. You can also access specific dimensions using tuples. 
```

2024-08-31 18:21 UTC, SaviDahegaonkar commented on content/pytorch/concepts/tensors/size/size.md
> +    - If `dim` is specified, the returned value is an __int__ holding the size of the given dimension.
```suggestion
- `dim`: (`int`) This optional parameter specifies the dimension for which to retrieve the size. The default value is `None`. 
    - If `dim` is not provided, the returned value is a `torch.Size`, a subclass of __tuple__. 
    - If `dim` is specified, the returned value is an int holding the size of the given dimension. 
```

2024-08-31 18:21 UTC, SaviDahegaonkar commented on content/pytorch/concepts/tensors/size/size.md
> +print(t.size(dim=1))
```suggestion
import torch

t = torch.empty(3, 4, 5)

print(t.size())
print(t.size(dim=1))
```
Please add another codebyte example.

2024-09-20 19:17 UTC, SaviDahegaonkar commented
Hey @maroline-johnson ,
Have you implemented the suggested changes? If yes then let me know so I can review it and approve it.


Thanks,
Savi

2024-09-20 22:37 UTC, maroline-johnson commented
@SaviDahegaonkar Yes, I have. You can see them here: [Changes for code review - c1270b2](https://github.com/Codecademy/docs/pull/5088/commits/c1270b2ee8bfcab35fc10606eb35965d4601dd18)

2024-09-21 14:44 UTC, SaviDahegaonkar requested changes
Hello @maroline-johnson ,
I had a look at your file suggested a change please make it asap.

Thanks,
Savi

2024-09-21 14:44 UTC, SaviDahegaonkar commented on content/pytorch/concepts/tensors/size/size.md
> +```
```suggestion
```pseudo
t.size(dim=None)
```
```

2024-10-10 22:11 UTC, SaviDahegaonkar approved these changes
Hey @maroline-johnson ,
LGTM, I hereby approve this PR.

2024-10-10 22:11 UTC, SaviDahegaonkar commented on content/pytorch/concepts/tensors/size/size.md
> +The **`size()`** method returns a `torch.Size` object containing the size information of a Pytorch tensor. It is a fundamental function used in PyTorch to obtain the tensor's shape and is specificall
```suggestion
The **`size()`** method returns a `torch.Size` object that behaves like a tuple containing the size and information of a PyTorch tensor. This function is a fundamental one used in PyTorch to obtain the tensor's shape. You can also access specific dimensions using index-based access, same as tuples. 
```

2024-10-12 06:39 UTC, mamtawardhani approved these changes
Thank you for contributing @maroline-johnson 😄 

The entry looks good to be merged! 🚀

2024-10-12 07:08 UTC, merged