Added Utility Types in Typescript
Codecademy/docs pull request #5093
Opened 2024-08-23 08:18 UTC by Mandipbhattarai

### Description

### Issue Solved

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-08-23 19:00 UTC, Mandipbhattarai commented
Sure working on it. Thanks for the review!

2024-08-23 19:23 UTC, Mandipbhattarai commented
I have applied the changes. Can you review it @dakshdeepHERE?

2024-08-24 16:07 UTC, Mandipbhattarai commented
@dakshdeepHERE is there any other changes I must apply?

2024-08-28 19:47 UTC, Mandipbhattarai commented
Hi @dakshdeepHERE ! Can you please provide me with the update?

2024-09-23 16:16 UTC, Mandipbhattarai commented
@SaviDahegaonkar why is the review taking so long time?

2024-09-24 20:27 UTC, Mandipbhattarai commented
@SaviDahegaonkar thanks for the response!

2024-10-10 22:53 UTC, SaviDahegaonkar requested changes
Hey @Mandipbhattarai 
I have suggested a few changes please make them and let me know. Also I want you to include the stage 'Utility types' in the [tags.md file](documentation/tags.md).

2024-10-10 22:53 UTC, SaviDahegaonkar commented on content/typescript/concepts/utility-types/utility-types.md
> +TypeScript consists of several predefined generic types known as Utility Types. These utility types are useful for manipulating or creating new types more efficiently.
```suggestion
TypeScript consists of several predefined generic types known as **Utility Types**. These utility types are useful for manipulating or creating new types more efficiently.
```
The first mention of the concept must be in bold.

2024-10-10 22:53 UTC, SaviDahegaonkar commented on content/typescript/concepts/utility-types/utility-types.md
> +Partial is used to create a type with all properties marked as optional.
```suggestion
Partial is  a utility type that is used to create a type where all properties are marked as optional.
```

2024-10-10 22:53 UTC, SaviDahegaonkar commented on content/typescript/concepts/utility-types/utility-types.md
> +`Required` is used to create a type with all properties of `T` marked as `Required`. It is the opposite of `Partial`.
```suggestion
`Required` is a utility type that is used to create a type with all properties of `T` marked as `Required`. It is the opposite of `Partial`.
```

2024-10-10 22:53 UTC, SaviDahegaonkar commented on content/typescript/concepts/utility-types/utility-types.md
> +const requiredUser: Required<User> = {
```suggestion
const requiredUser: Required<{ name: string; age: number}> = {
```
When we use Required utility type we must make sure to provide the values for all the properties that we have defined.

2024-10-10 22:53 UTC, SaviDahegaonkar commented on content/typescript/concepts/utility-types/utility-types.md
> +`Readonly` is to mark all the properties in `T` as `Readonly`, which prevents any reassignment.
```suggestion
`Readonly`  is a utility type that marks all the properties in `T` as `readonly`, preventing any reassignment.
```

2024-10-10 22:53 UTC, SaviDahegaonkar commented on content/typescript/concepts/utility-types/utility-types.md
> +where `U` are the properties you want to exclude from `T`.
```suggestion
where `U` represents the types you want to exclude from the union type`T`.
```

2024-10-10 22:53 UTC, SaviDahegaonkar commented on content/typescript/concepts/utility-types/utility-types.md
> +type ExcludedFruits = Exclude<T, 'apple' | 'banana'>; // "orange"
```suggestion
type ExcludedFruits = Exclude<fruits, 'apple' | 'banana'>; // "orange"
```

2024-10-12 11:45 UTC, Mandipbhattarai commented
@SaviDahegaonkar as per your changes i have updated it and also included the utility types.

2024-10-15 11:22 UTC, Mandipbhattarai commented
Can you recheck it @SaviDahegaonkar because I had already added the tag.
![image](https://github.com/user-attachments/assets/080a5fcc-576c-48b3-bb59-ba48ba1e6c84)

2024-10-15 11:27 UTC, SaviDahegaonkar commented
Hey @Mandipbhattarai , Are you sure you added the tag in the tags.md list for the forked repository because as you can see I can't find any 'utility types' tag . 
![Screenshot 2024-10-15 165524](https://github.com/user-attachments/assets/ad48688f-fded-4bad-8df4-39218284814a)

2024-10-15 11:40 UTC, Mandipbhattarai commented
@SaviDahegaonkar can you check the file changed because it shows the addition of 'Utility Types' in the tags.md from my pr.
![image](https://github.com/user-attachments/assets/4f9dba5f-b1c6-422f-9ffd-c716c3d927a8)

2024-10-15 11:43 UTC, SaviDahegaonkar commented
> @SaviDahegaonkar can you check the file changed because it shows the addition of 'Utility Types' in the tags.md from my pr. ![image](https://private-user-images.githubusercontent.com/97532160/376592436-4f9dba5f-b1c6-422f-9ffd-c716c3d927a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5OTI3NDgsIm5iZiI6MTcyODk5MjQ0OCwicGF0aCI6Ii85NzUzMjE2MC8zNzY1OTI0MzYtNGY5ZGJhNWYtYjFjNi00MjJmLTlmZmQtYzcxNmMzZDkyN2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDExNDA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NGI0YTY2OTdhNTMyZDY1NTdkNGM3MGJjZjlhZjVmOTU1YzM5YzY0YTY5ODYyY2UwNjVjNTdiNzAwZWRkNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Olp_Gl-68BPC89aKINyWp6kv9XDHD2TF14AwqrfACqg)

Yeah I got it, it was a network issue from my end so I was unable to find the reflected changes.

2024-10-15 11:44 UTC, SaviDahegaonkar approved these changes
Hey @Mandipbhattarai ,
The entry LGTM!

Thanks,
Savi

2024-10-15 11:47 UTC, Mandipbhattarai commented
@SaviDahegaonkar can i get to know the issue so I can perform the necessary changes if its from my side. 

Thanks,
Mandip

2024-10-16 03:37 UTC, Mandipbhattarai commented
@SaviDahegaonkar is there any changes to be done?

2024-10-17 12:08 UTC, SaviDahegaonkar commented
> @SaviDahegaonkar is there any changes to be done?

Nope, I will merge this PR.

2024-10-20 09:55 UTC, merged