[Term Entry] Python Math Module: math.acos()
Codecademy/docs pull request #5095
Opened 2024-08-23 14:00 UTC by raheep06

### Description

### Issue Solved
Closes #5076 

### Type of Change

- Adding a new entry

### Checklist

- ✅ All writings are my own.
- ✅ My entry follows the Codecademy Docs style guide.
- ✅ My changes generate no new warnings.
- ✅ I have performed a self-review of my own writing and code.
- ✅ I have checked my entry and corrected any misspellings.
- ✅ I have made corresponding changes to the documentation if needed.
- ✅ I have confirmed my changes are not being pushed from my forked `main` branch.
- ✅ I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- ✅ I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-08-25 06:54 UTC, mamtawardhani requested changes
Hey @raheep06 thank you for contributing to the Codecademy Docs, the entry looks nicely written! 😃 

I've suggested a few changes, could you please review and modify them at your earliest convenience? Thank you! 😄

2024-08-25 06:54 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-acos/math-acos.md
> +---
```suggestion
---
Title: 'math.acos()'
Description: 'Returns the arc cosine (inverse cosine) of a number.'
Subjects:
  - 'Computer Science'
  - 'Data Science'
Tags:
  - 'Arithmetic'
  - 'Functions'
CatalogContent:
  - 'learn-python-3'
  - 'paths/computer-science'
---

```

2024-08-25 06:54 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-acos/math-acos.md
> +---
The description should be the function, and the tags should be alphabetically arranged

2024-08-25 06:54 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-acos/math-acos.md
> +The **`math.acos()`** function returns the inverse cosine (in radians) of a value between -1 and 1.
```suggestion
In Python, the **`math.acos()`** function returns the arc cosine (inverse cosine) in radians of a value between `-1` and `1`.
```

2024-08-25 06:54 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-acos/math-acos.md
> +math.acos(n)
```suggestion
math.acos(x)

```

2024-08-25 06:54 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-acos/math-acos.md
> +
```suggestion

- `x`: A number between `-1` and `1` representing the cosine value for which the arc cosine is to be calculated.

```

2024-08-25 06:54 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-acos/math-acos.md
> +
The parameter needs to be described, feel free to change the description this is just for reference

2024-08-25 06:54 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-acos/math-acos.md
> +The `math.acos()` function returns a numeric value between 0 and π, which represents the inverse cosine of the value `n`.
```suggestion
The `math.acos()` function returns a numeric value between 0 and π, which represents the inverse cosine of the value `x`.

```

2024-08-25 06:54 UTC, mamtawardhani commented on content/python/concepts/math-module/terms/math-acos/math-acos.md
> +Use `math.acos()` to return the inverse cosine of a numeric value between 0 and π:
```suggestion
The example below demonstrates the use of `math.acos()` function to return the inverse cosine of a numeric value:

```

2024-08-26 20:34 UTC, raheep06 reviewed
Updated all sections based on feedback. Thank you

2024-08-27 07:33 UTC, mamtawardhani approved these changes
Well done @raheep06 😃 

The entry looks good for a second round of review 🚀

2024-09-17 04:37 UTC, Sriparno08 approved these changes
Looks good, @raheep06!

2024-09-17 04:37 UTC, merged