add getrandbits entry
Codecademy/docs pull request #5102
Opened 2024-08-24 19:23 UTC by cjdemille

### Description

### Issue Solved

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-08-25 09:10 UTC, SaviDahegaonkar requested changes
Hey @cjdemille,
I must say the entry is nicely written. I have suggested some changes please do it soon to get this PR approved for the first review

Thanks,
Savi

2024-08-25 09:10 UTC, SaviDahegaonkar commented on content/python/concepts/random-module/terms/getrandbits/getrandbits.md
> +In the Python `random` module, the `.getrandbits()` method is used to generate a pseudo-random integer with a specified number of bits
```suggestion
In the Python `random` module, the `.getrandbits()` method is used to generate a pseudo-random integer with a specified number of bits
```
Make sure that the first mention of the concept should always be in bold (**bold**).

2024-08-25 09:10 UTC, SaviDahegaonkar commented on content/python/concepts/random-module/terms/getrandbits/getrandbits.md
> +Where `k` is the number of bits in the generated integer. The `k` must be a non-negative integer. The result will range from 0 —2<sup>k</sup> - 1.
``` suggestion
Where `k` is the number of bits in the generated integer. The `k` must be a non-negative integer. The result will range from 0 —2<sup>k</sup> - 1.
```

2024-08-25 09:10 UTC, SaviDahegaonkar commented on content/python/concepts/random-module/terms/getrandbits/getrandbits.md
> +```
```suggestion
In the example below, `.getrandbits()` returns an integer with 256 bits: 

```py 
import random 

random_bits = random.getrandbits(256)

```
```
I would suggest you add another code that properly demonstrates the use of  `getrandbits` in Python. Also, add s shell block to show the output of the code.

2024-09-29 10:52 UTC, SaviDahegaonkar commented
Hey @cjdemille ,
Have you made all the suggestion I requested you, If not then please make them asap.

Thanks,
Savi

2024-10-15 11:40 UTC, SaviDahegaonkar approved these changes
Hey @cjdemille , 
I had a look at your file applied some changes and approving it. Please mention which issue does this PR closes.

Thanks,
Savi

2024-10-16 08:22 UTC, mamtawardhani approved these changes
Thank you for contributing @cjdemille 😄 

The entry is ready to be merged 🚀

2024-10-16 08:27 UTC, merged