[Topic Entry] Python math-module math.cosh()
Codecademy/docs pull request #5105
Opened 2024-08-25 17:57 UTC by FiFiTM

### Description

- Added the math.cosh() topic to Python math-module

### Issue Solved

- Closes Issue #5083

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-08-25 17:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5105) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5105) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5105) it.</sub>

2024-09-14 23:09 UTC, cigar-galaxy82 requested changes

2024-09-14 23:09 UTC, cigar-galaxy82 commented on content/python/concepts/math-module/terms/math-cosh/math-cosh.md
> +## Example
```suggestion
## Example 1
```

2024-09-14 23:09 UTC, cigar-galaxy82 commented on content/python/concepts/math-module/terms/math-cosh/math-cosh.md
> +```
After a heading as Example 2

2024-09-14 23:09 UTC, cigar-galaxy82 commented
Hi, @FiFiTM thank you for contributing to Codecademy docs, I have suggested a few changes please modify them.

2024-09-26 19:46 UTC, cigar-galaxy82 approved these changes

2024-09-27 07:36 UTC, mamtawardhani approved these changes
Thank you for contributing @FiFiTM 😄 

The entry is ready to be merged 🚀

2024-09-27 07:40 UTC, merged