[Term Entry] Python:Pandas dataframe at #4520
Codecademy/docs pull request #5107
Opened 2024-08-26 17:13 UTC by aSagCoder

### Description

- Created a new branch in order to make merging easier for the given term entry. Has already undergone two reviews and just needs to get merged into the main branch. 
- Added the .at[] function for Pandas.
- Can be located here - docs/content/pandas/concepts/dataframe/terms/at/at.md.

### Issue Solved
Closes #4520 

### Type of Change

- Adding a new entry
- ~~Editing an existing entry (fixing a typo, bug, issues, etc)~~
- ~~Updating the documentation~~

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-08-27 17:19 UTC, SaviDahegaonkar requested changes
Hey @aSagCoder,
I had a look at your file and have suggested a few changes. Please do it as soon as possible.

Thanks,
Savi

2024-08-27 17:19 UTC, SaviDahegaonkar commented on content/pandas/concepts/dataframe/terms/at/at.md
> +In Pandas, the **`.at[]`** function is used as an accessor to fetch a specific value from a [`DataFrame`](https://www.codecademy.com/resources/docs/pandas/dataframe) using row/column pairs.
``` suggestion
In Pandas, the **`.at[]`** function is used as an accessor to fetch a specific value from a [`DataFrame`](https://www.codecademy.com/resources/docs/pandas/dataframe) using row and column pairs.
```
Made a slight change for `row/column pairs`. In pandas for the `.at[ ]` function fetch using both row and column pairs, the use of the `/` symbol shows that the `.at[ ]` function either uses rows or columns to fetch a specific value.

2024-08-28 09:39 UTC, aSagCoder commented
@SaviDahegaonkar Hello there! I made the necessary changes that you suggested. If there's anything else you want me to do, just ping me!

2024-08-29 08:49 UTC, mamtawardhani commented
Hey @SaviDahegaonkar please check this on priority, since this issue is very old.

2024-08-30 18:35 UTC, SaviDahegaonkar approved these changes
Hey @aSagCoder ,
I reviewed your file and you did all the necessary changes. I hereby approve it.

2024-08-30 18:44 UTC, SaviDahegaonkar commented
> Hey @SaviDahegaonkar please check this on priority, since this issue is very old.

Should I merge this PR?

2024-09-01 17:13 UTC, mamtawardhani approved these changes
Thank you for your contribution @aSagCoder 😄 

The entry is ready to be merged! 🚀

2024-09-01 17:15 UTC, merged