Create entry on pytorch tensors sum
Codecademy/docs pull request #5137
Opened 2024-08-31 13:04 UTC by arisdelacruz

### Description

This is an attempt to create an entry on pytorch's sum function (on tensors)

### Issue Solved

Closes #5061

### Type of Change

- Adding a new entry

### Checklist

- [ / ] All writings are my own.
- [ / ] My entry follows the Codecademy Docs style guide.
- [ / ] My changes generate no new warnings.
- [ / ] I have performed a self-review of my own writing and code.
- [ / ] I have checked my entry and corrected any misspellings.
- [ / ] I have made corresponding changes to the documentation if needed.
- [ / ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ / ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ / ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-08-31 13:05 UTC, arisdelacruz commented
just created a pull request, thanks

2024-09-03 13:45 UTC, mamtawardhani requested changes
Hey @arisdelacruz thank you for contributing to Codecademy Docs! TThe entry is nicely written 😄 

I've suggested a few modifications, could you please review and modify them at your earliest convenience? Feel free to discuss any concerns, thank you! 😄

2024-09-03 13:45 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/sum/sum.md
> +---
```suggestion
---
Title: '.sum()'
Description: 'Computes the sum of all elements in a tensor.'
Subjects:
  - 'AI'
  - 'Data Science'
Tags:
  - 'AI'
  - 'Deep Learning'
  - 'Functions'
  - 'Machine Learning'
CatalogContent:
  - 'intro-to-py-torch-and-neural-networks'
  - 'py-torch-for-classification'
---
```

2024-09-03 13:45 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/sum/sum.md
> +---
Keep the description small and to the point. Additional stuff is added in the introductory paragraph below

2024-09-03 13:45 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/sum/sum.md
> +- `out`: Stores the output into existing tensor (if there is any).
Can we add both the syntax here? Like this:

To calculate the sum of all elements, the following syntax is used:

```pseudo
torch.sum(input, *, dtype=None)
```

- `input`: The input tensor.
- `dtype` (optional): The data type of the output tensor.

To calculate the sum along specific dimensions, the following syntax is used:

```pseudo
torch.sum(input, *, dim=None, keepdim=False, out=None)
```

- `input`: The input tensor.
- `dim` (optional): Specifies the dimension(s) along which the sum is computed. If not specified, the sum is computed over all elements.
- `keepdim` (optional): If set to `True`, the output tensor retains dimensions of size one for the reduced dimensions. The default is `False`.
- `out` (optional): A tensor to store the output into. If not provided, a new tensor is created.

2024-09-03 13:45 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/sum/sum.md
> +## Example
```suggestion
## Example 1
```

2024-09-03 13:45 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/sum/sum.md
> +The `.sum()` function can also be used to compute the sum along a specific dimension of the tensor. For example, to compute the sum along the rows of a 2D tensor, you can specify the `dim` parameter
```suggestion
```

2024-09-03 13:45 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/sum/sum.md
> +The `.sum()` function can also be used to compute the sum along a specific dimension of the tensor. For example, to compute the sum along the rows of a 2D tensor, you can specify the `dim` parameter
Since we will be adding in the syntax, let us avoid it from here

2024-09-03 13:45 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/sum/sum.md
> +
```suggestion
## Example 2

```

2024-09-03 13:45 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/sum/sum.md
> +In this example, the sum of all elements in the input tensor `[[1, 2], [3, 4]]` is computed, resulting in a tensor with a single element `10`. The sum is calculated as `1 + 2 + 3 + 4 = 10`.
Let us add the descriptions before the code

2024-09-03 13:45 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/sum/sum.md
> +In this example, the sum is computed along the rows of the input tensor `[[1, 2], [3, 4]]`, resulting in a tensor with two elements `[4, 6]`. The sum along the rows is calculated as `[1 + 3, 2 + 4] =
Let us add the descriptions before the code

2024-09-03 13:58 UTC, arisdelacruz commented
@mamtawardhani 

i hope i was able to come to terms with the suggested edits

thanks much

2024-09-03 14:23 UTC, mamtawardhani approved these changes
Thank you for contributing @arisdelacruz 😄 

The entry looks good for a second round of review! 🚀

2024-09-12 15:23 UTC, Sriparno08 approved these changes
Looks good, @arisdelacruz!

2024-09-12 15:24 UTC, merged