Creation of the math-erfc term
Codecademy/docs pull request #5144
Opened 2024-09-02 09:30 UTC by Alhassane379

### Description

### Issue Solved

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-09-02 09:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5144) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5144) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5144) it.</sub>

2024-09-09 08:09 UTC, Sriparno08 requested changes
Hey @Alhassane379, thanks for contributing to Codecademy Docs!

Here is a list of modifications that you need to make in your entry below:

2024-09-17 09:50 UTC, Sriparno08 approved these changes
Good job, @Alhassane379!

This looks good for a second round of review!

2024-09-17 12:51 UTC, mamtawardhani approved these changes
Thank you for contributing @Alhassane379 😄 

The entry is ready to be merged 🚀

2024-09-17 12:53 UTC, merged