Adds [Concept Entry] Sklearn Gaussian Processes
Codecademy/docs pull request #5183
Opened 2024-09-03 17:52 UTC by negarvahid

### Description

### Issue Solved

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-09-03 17:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5183) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5183) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5183) it.</sub>

2024-09-03 18:35 UTC, SaviDahegaonkar requested changes
Hey Author,
I had a look at your entry and suggested some changes to you please make them asap also add an example section and a codebyte example section as mentioned in the [issue](https://github.com/Codecademy/docs/issues/4896) related to this PR.

Thanks,
Savi

2024-09-03 18:35 UTC, SaviDahegaonkar commented on content/sklearn/concepts/gaussian-processes/gaussian-processes.md
> +Description: 'Gaussian Processes are a supervised learning algorithm that predicts outcomes as distributions, assuming that any set of input points follows a joint Gaussian distribution.'
``` suggestion
Description: 'Gaussian Processes is a supervised learning framework. that predicts outcomes as distributions, assuming that any set of input points follows a joint Gaussian distribution.'
```
The use of the word `framework` would be more efficient than using the word `algorithm` as the term algorithm suggests that the Gaussian Processes are a single algorithm which is not accurate they are a framework that can be used in various supervised learning models.

2024-09-03 18:35 UTC, SaviDahegaonkar commented on content/sklearn/concepts/gaussian-processes/gaussian-processes.md
> +
```suggestion


```

```
Remove the extra space here.

2024-09-29 10:16 UTC, SaviDahegaonkar commented
Hey @negarvahid , Have you implemented the changes I suggested you, if not please let me know.


Thanks,
Savi

2024-10-14 15:09 UTC, negarvahid commented
> Hey @negarvahid , Have you implemented the changes I suggested you, if not please let me know.
> 
> Thanks, Savi

Hi there @SaviDahegaonkar, I somehow had never gotten an email notification and wasn't aware you had already gone through my submission. I will submit an updated version this week. Thanks

2024-10-14 17:45 UTC, SaviDahegaonkar commented
> > Hey @negarvahid , Have you implemented the changes I suggested you, if not please let me know.
> > Thanks, Savi
> 
> Hi there @SaviDahegaonkar, I somehow had never gotten an email notification and wasn't aware you had already gone through my submission. I will submit an updated version this week. Thanks

Yes, please make the changes asap. So I can get your PR merged.

2024-10-15 18:45 UTC, SaviDahegaonkar approved these changes
Hey @negarvahid ,
There is no need to make the changes; I have already approved this PR. Thank you for contributing to Docs. Also, I want to suggest that you please try to mention the issue that is closed by a particular PR every time you push a new PR. It makes us easy to review a PR.

2024-10-17 12:58 UTC, mamtawardhani commented
Hey @negarvahid, this PR has been raised from the main branch. Can you create a feature branch and raise the issue?
Codecademy requires authors to create a feature branch to merge entries. 
Please do it at your earliest convenience, thank you! 😃

2024-10-19 10:59 UTC, mamtawardhani commented
Hey @negarvahid I'll be closing this PR for now, please re-raise it from the feature branch in the next one week.
Thank you! 😄

2024-10-19 10:59 UTC, closed without merging