[Term Entry] Adding Pytorch Tensor arange
Codecademy/docs pull request #5191
Opened 2024-09-07 02:22 UTC by selenahuang017

Description
Adding new entry on the .arange() term under PyTorch Tensors concept. It is under docs/content/pytorch/concepts/tensors/terms/arange/arange.md.

Issue Solved
Addresses issue: https://github.com/Codecademy/docs/issues/5057

Type of Change
Adding a new entry

Checklist
[x ] All writings are my own.
[x ] My entry follows the Codecademy Docs style guide.
[x ] My changes generate no new warnings.
[x ] I have performed a self-review of my own writing and code.
[x ] I have checked my entry and corrected any misspellings.
[x ] I have made corresponding changes to the documentation if needed.
[x ] I have confirmed my changes are not being pushed from my forked main branch.
[x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
[x ] I have linked any issues that are relevant to this PR in the Issues Solved section.

2024-09-07 10:21 UTC, mamtawardhani requested changes
Hey @selenahuang017 thank you for contributing to Codecademy Docs, the entry is well written! 😄 

I've suggested a few changes, could you please review and modify those at your earliest convenience? Thank you! 😃

2024-09-07 10:21 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/arange/arange.md
> +The **`.arange()`** method returns a tensor created from a given interval `[start, end)`, with a specified `step` size. Note: when the step size is not an integer, there may be floating point roundin
```suggestion
The **`.arange()`** method returns a tensor containing values from a given interval `[start, end)` with a specified `step` size. When the step size is not an integer, floating-point rounding errors may occur, so it is recommended to subtract a small epsilon from the `end` value for consistency.
```

2024-09-07 10:21 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/arange/arange.md
> +---
```suggestion
---
Title: '.arange()'
Description: 'Returns a 1-dimentional tensor with values from a specified range.'
Subjects:
  - 'AI'
  - 'Data Science'
  - 'Machine Learning'
Tags:
  - 'AI'
  - 'Arrays'
  - 'Data Structures'
  - 'Deep Learning'
CatalogContent:
  - 'intro-to-py-torch-and-neural-networks'
  - 'paths/computer-science'
---
```

2024-09-07 10:21 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/arange/arange.md
> +---
The catalog content should have 2 values

2024-09-07 10:21 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/arange/arange.md
> +- `requires_grad`: A boolean indicating whether autograd will record operations on the output tensor, defaults to `False`.
```suggestion
- `start`: The starting value of the range, inclusive. Defaults to `0`.
- `end`: The ending value of the range, exclusive. This parameter is required.
- `step`: The difference between each consecutive value in the range. Default value is `1`.
- `out`: A tensor in which to store the output. If `None`, a new tensor is created. Default value is `None`.
- `dtype`: The desired data type of the output tensor (`torch.dtype`). If `None`, the data type will be inferred from other input arguments. Default value is `None`.
- `layout`: The desired layout of the output tensor. Default: `torch.strided`.
- `device`: The device on which the tensor will be allocated (`torch.device`). Default: `None`.
- requires_grad: A boolean indicating whether autograd should track operations on the output tensor. Default: `False`.
```

2024-09-10 07:10 UTC, mamtawardhani approved these changes
Hey @selenahuang017 thank you for making the changes. The entry looks good for a second round of review 🚀

2024-09-25 15:32 UTC, mamtawardhani commented
@cigar-galaxy82 kindly finish the second review for this ASAP, its already been 2+ weeks :)

2024-09-30 01:31 UTC, cigar-galaxy82 commented
@mamtawardhani second review done

2024-09-30 01:31 UTC, cigar-galaxy82 approved these changes

2024-09-30 01:32 UTC, merged