[Term Entry] Add Python Plotly- graph_objects .Surface() to codeacademy docs
Codecademy/docs pull request #5198
Opened 2024-09-08 18:20 UTC by saldanhad

### Description

Added documentation for the `.Surface()` method of the graph_objects module in Plotly.

### Issue Solved

Closes  [Term Entry] Python Plotly- graph_objects .Surface() #5179 

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-09-08 18:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5198) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5198) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5198) it.</sub>

2024-09-09 11:07 UTC, SaviDahegaonkar requested changes
Hey @saldanhad ,
The entry is nicely written. Though I have suggested you some changes please make them asap.

2024-09-09 11:07 UTC, SaviDahegaonkar commented on content/plotly/concepts/graph-objects/terms/surface/surface.md
> +```
```suggestion
```pseudo
plotly.graph_objects.Surface(
    z=None,
    x=None,
    y=None,
    colorscale=None,
    cmin=None,
    cmax=None,
    opacity=None,
    surfacecolor=None,
    **kwargs
)
```

```
The syntax in docs is written inside the ```pseudo ``` blocks, not the ```python``` blocks. You can have a look at the [style-guide ](documentation/style-guide.md) for better information and understanding.

2024-09-09 11:07 UTC, SaviDahegaonkar commented on content/plotly/concepts/graph-objects/terms/surface/surface.md
> +- `surfacecolor` : array-like, optional. An array of values to color the surface.
```suggestion
- `z` : 2D array-like, required. The Z coordinates for the surface plot.
- `x` : 1D array-like, optional. The X coordinates. Defaults to the range of the number of columns in z if not provided.
- `y` : 1D array-like, optional. The Y coordinates. Defaults to the range of the number of rows in z if not provided.
- `colorscale` : list of tuples, optional. Colorscale for the surface.
- `cmin` : float, optional. Minimum value for the color scale.
- `cmax` : float, optional. Maximum value for the color scale.
- `opacity` : float, optional. The opacity of the surface.
- `surfacecolor` : array-like, optional. An array of values to color the surface.

```

2024-09-09 11:07 UTC, SaviDahegaonkar commented on content/plotly/concepts/graph-objects/terms/surface/surface.md
> +The following example showcases the use of the `.Surface()` function:
```suggestion
The following example showcases the use of the `Surface` class :

```
Surface is a class and not a function.

2024-09-09 11:07 UTC, SaviDahegaonkar commented on content/plotly/concepts/graph-objects/terms/surface/surface.md
> +This example allows for a visual representation of a mathematical function, with customizable parameters like the colorscale to highlight different levels on the surface. The z values create the heig
```suggestion
This example allows for a visual representation of a mathematical function, with customizable parameters like the color scale to highlight different levels on the surface. The z values create the height of the surface, while x and y form the base grid, enabling an intuitive understanding of how the function behaves across the input space.

```

2024-09-09 11:49 UTC, saldanhad commented
Hi @SaviDahegaonkar, thank you for your review and apologies for missing a few changes earlier. Please refer to the last commit for the updated changes.

2024-09-12 15:23 UTC, saldanhad commented
Hi @SaviDahegaonkar, apologize for the multiple commits here due to some errors from my end, however I have made the changes suggested by you, for the sake of simplicity do you prefer me closing this PR and generating a new PR for this issue ?

2024-09-15 19:05 UTC, SaviDahegaonkar commented
Hello @saldanhad ,
As we discussed, I am closing this OR for now. You can create a new PR on this entry. Let me know if you have any more questions.

2024-09-15 19:05 UTC, closed without merging

2024-09-15 19:18 UTC, saldanhad commented
Hi @SaviDahegaonkar, I believe there might be some miscommunication, may I know what we discussed on and why was this PR closed ?

2024-09-15 19:22 UTC, SaviDahegaonkar commented
I had got a mail from your side to close the PR and let you create a new PR
on the same issue with the specific edits.


On Mon, Sep 16, 2024 at 12:48 AM Deepak Saldanha ***@***.***>
wrote:

> Hi @SaviDahegaonkar <https://github.com/SaviDahegaonkar>, I believe there
> might be some miscommunication, may I know what we discussed on and why was
> this PR closed ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Codecademy/docs/pull/5198#issuecomment-2351754095>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5UD3MTZJC4SJUPUS5L6NXDZWXMRZAVCNFSM6AAAAABN3GLRQ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNJRG42TIMBZGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-15 19:39 UTC, saldanhad commented
Hi @SaviDahegaonkar, Thanks for clarifying, will raise a new PR for the same.