[Term Entry] Python Plotly-graph_objects .Mesh3d()
Codecademy/docs pull request #5201
Opened 2024-09-09 08:25 UTC by FelixOmollo

### Description

-Added the Plotly-graph_objects .Mesh3d() module for Python.

### Issue Solved

-Closes issue #5178 

### Type of Change

- Adding a new entry

### Checklist

- [x ] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-09-09 08:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5201) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5201) before we can accept your contribution.<br/><hr/>**Your Name** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5201) it.</sub>

2024-09-09 09:28 UTC, mamtawardhani commented
> [![CLA assistant check](https://camo.githubusercontent.com/bb14f9741a98be03eb447ca21a4a5e96201df401e5be70f9ef52130f4e1ff903/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/Codecademy/docs?pullRequest=5201) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5201) before we can accept your contribution.
> 
> **Your Name** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5201) it.

@FelixOmollo please sign the CLA, so that we can start with the review for this PR, thank you 😀

2024-09-09 20:58 UTC, FelixOmollo commented
Hello, signed the CLA. Looking forward to your review. Thank you.

2024-09-10 05:33 UTC, mamtawardhani requested changes
Hey @FelixOmollo thank you for contributing to Codecademy Docs, the entry is nicely written 😄 

I've suggested a few changes, could you review and modify them at your earliest convenience? Feel free to discuss any concerns, thank you! 😃

2024-09-10 05:33 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +---
```suggestion
---
Title: '.Mesh3d()'
Description: 'Creates 3D triangular mesh plots for visualizing 3D surfaces or volumetric data.'
Subjects:
- 'Data Science'
- 'Data Visualization'
Tags:
- 'Charts'
- 'Data'
- 'Plotly'
CatalogContent:
- 'learn-python-3'
- 'paths/computer-science'
---
```

2024-09-10 05:33 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +---
The tags, subjects and catalog are needed to be added from here: [tags](https://github.com/Codecademy/docs/blob/main/documentation/tags.md), [subjects](https://github.com/Codecademy/docs/blob/main/documentation/subjects.md) and c[atalog content](https://github.com/Codecademy/docs/blob/main/documentation/catalog-content.md)

Also, a short description of the term has to be added, I've added one, you can change it, that is just for reference.

2024-09-10 05:33 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +The **`.Mesh3d()`** is a function in Plotly's graph-objects module used to create 3D mesh plots. The surface is constructed from a set of vertices in 3D space `(x,y,z)` and triangles that are defined
```suggestion
The **`.Mesh3d()`** function in Plotly's graph-objects module is used to create 3D mesh plots. The surface is constructed from a set of vertices in 3D space `(x, y, z)` and triangles defined by three vertices. These triangles are specified using index arrays `(i, j, k)`, where each index refers to a vertex.
```

2024-09-10 05:33 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +The **`.Mesh3d()`** is a function in Plotly's graph-objects module used to create 3D mesh plots. The surface is constructed from a set of vertices in 3D space `(x,y,z)` and triangles that are defined
reframed for better readability

2024-09-10 05:33 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +
```suggestion
plotly.graph_objects.Mesh3d(x=None, y=None, z=None, i=None, j=None, k=None, color=None, opacity=None, ...)
```

2024-09-10 05:33 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +
removed the empty spacing

2024-09-10 05:33 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +-  `intensity`: This can be used to apply a color scale to the mesh based on a data array, similar to a heatmap on the mesh surface
```suggestion

- `x`: An array of X-coordinates of the vertices in 3D space.
- `y`: An array of Y-coordinates of the vertices in 3D space.
- `z`: An array of Z-coordinates of the vertices in 3D space.
- `i`: An array that defines the first vertex of each triangle by its index in the `x`, `y`, and `z` arrays.
- `j`: An array that defines the second vertex of each triangle by its index in the `x`, `y`, and `z` arrays.
- `k`: An array that defines the third vertex of each triangle by its index in the `x`, `y`, and `z` arrays.
- `color`: The color of the mesh surface.
- `opacity`: A float value between 0 and 1 that sets the transparency of the mesh surface.
```

2024-09-10 05:33 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +This example creates a 3D mesh representing a simple triangular surface. The mesh is defined using three vertices forming a triangular shape, each associated with `x, y,` and `z` coordinates. The `co
```suggestion
This example creates a 3D mesh plot representing a triangular surface using Plotly. The mesh is defined with vertices specified by `x`, `y`, and `z` coordinates, forming triangular faces through the indices provided by `i`, `j`, and `k`. The `colorscale` parameter is used to apply a gradient from gold to magenta, representing the `intensity` values of each vertex, which are interpolated across the surface. The `colorbar_title` and `showscale` parameters control the appearance of the color bar and its display.
```

2024-09-10 05:33 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +This example creates a 3D mesh representing a simple triangular surface. The mesh is defined using three vertices forming a triangular shape, each associated with `x, y,` and `z` coordinates. The `co
Added a bit more of description based on the code

2024-09-10 18:09 UTC, FelixOmollo commented
Hello Mamta, I have reviewed and committed your proposed changes. I would greatly appreciate your feedback.

2024-09-11 07:00 UTC, mamtawardhani approved these changes
Thank you for contributing to Codecademy Docs @FelixOmollo 😃 

The entry looks good for a second round of review! 🚀

2024-09-11 07:04 UTC, mamtawardhani commented
> [![CLA assistant check](https://camo.githubusercontent.com/bb14f9741a98be03eb447ca21a4a5e96201df401e5be70f9ef52130f4e1ff903/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/Codecademy/docs?pullRequest=5201) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5201) before we can accept your contribution.**2** out of **3** committers have signed the CLA.✅ FelixOmollo✅ mamtawardhani❌ Your Name
> 
> **Your Name** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5201) it.

Hey @Sriparno08 looks like the author has made some commits with the local device ID as well, could you please help resolve this?

@FelixOmollo could you please visit [this link](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user) and look through the process of adding your email id to your GitHub account.

2024-09-11 10:38 UTC, Sriparno08 commented
Okay @mamtawardhani, I'll take a look at it.

2024-09-20 16:04 UTC, Sriparno08 approved these changes
Looks good, @FelixOmollo!

2024-09-20 16:10 UTC, Sriparno08 commented
Hey @FelixOmollo, have you visited [this link](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user) and looked through the process of adding your email id to your GitHub account? If not, please do so that the entry can be merged.

Note: If there's no response from your side in a week, this PR will be closed unfortunately.

2024-09-28 07:23 UTC, Sriparno08 commented
Closing this PR since the author is inactive.

2024-09-28 07:23 UTC, closed without merging