[Term Entry] Swift dictionary.mapValues()
Codecademy/docs pull request #5212
Opened 2024-09-12 22:56 UTC by Great-Visions-Code

### Description

- Add .mapValues() term entry for Swift

### Issue Solved

- Closes #5123 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-09-28 23:03 UTC, cigar-galaxy82 requested changes

2024-09-28 23:03 UTC, cigar-galaxy82 commented on content/swift/concepts/dictionaries/terms/mapValues/mapValues.md
> +In the following example, the `mapValues()` method is used to increase each student's grade by 10 points in the `studentGrades` dictionary:
```suggestion
In the following example, the `mapValues()` method is used to increase each student's grade by `10` points while keeping the keys unchanged in the `studentGrades` dictionary:
```

2024-09-28 23:04 UTC, cigar-galaxy82 commented
Hi @Great-Visions-Code thank you for contributing to Codecademy docs, I have suggested a few changes please modify them.

2024-09-29 21:53 UTC, cigar-galaxy82 commented
Hi, @Great-Visions-Code thank you for contributing to Codecademy docs, I have suggested a few changes please modify them.

2024-09-30 17:55 UTC, Great-Visions-Code commented
@cigar-galaxy82 I have made the suggested changes. Please let me know if anything else is needed. Thank you,

2024-10-07 02:06 UTC, cigar-galaxy82 approved these changes

2024-10-07 11:07 UTC, mamtawardhani approved these changes
Thank you for contributing @Great-Visions-Code 😄 

The entry is ready to be merged! 🚀

2024-10-07 11:11 UTC, merged