Create math-frexp.md
Codecademy/docs pull request #5214
Opened 2024-09-13 16:41 UTC by haruharu1017

Description
My topic is math.frexp(). I used the topic entry template and rename it as the file needed then edit in that file.

Issue Solved
Closes https://github.com/Codecademy/docs/issues/5085

Type of Change
Adding a new entry
Checklist
[✅] All writings are my own.
[✅] My entry follows the Codecademy Docs style guide.
[✅] My changes generate no new warnings.
[✅] I have performed a self-review of my own writing and code.
[✅] I have checked my entry and corrected any misspellings.
[✅] I have made corresponding changes to the documentation if needed.
[✅] I have confirmed my changes are not being pushed from my forked main branch.
[✅] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
[✅] I have linked any issues that are relevant to this PR in the Issues Solved section.

2024-09-13 16:42 UTC, haruharu1017 commented
@cigar-galaxy82 I launched a new pr, please review it, thank you!

2024-09-14 19:30 UTC, haruharu1017 commented
@cigar-galaxy82 I noticed that my code failed the format:verify and lint:md checks, but I'm having trouble identifying the exact issues. Could you please help me understand what went wrong with these checks?

2024-09-22 08:50 UTC, cigar-galaxy82 requested changes

2024-09-22 08:50 UTC, cigar-galaxy82 commented on content/python/concepts/math-module/terms/math-frexp/math-frexp.md
> +print(math.frexp(10))
```suggestion
import math

mantissa, exponent = math.frexp(10)

print("Mantissa of 10: ", mantissa)
print("Exponent of 10: ", exponent)
```

2024-09-22 08:50 UTC, cigar-galaxy82 commented on content/python/concepts/math-module/terms/math-frexp/math-frexp.md
> +(0.625, 4)
```suggestion
Mantissa of 10:  0.625
Exponent of 10:  4
```

2024-09-22 08:50 UTC, cigar-galaxy82 commented
hi @haruharu1017 thank you for contributing to Codecademy docs, I have suggested some changes please modify them.

2024-09-22 08:51 UTC, cigar-galaxy82 commented
The error you were getting was because of extra space in some lines.

2024-10-17 13:09 UTC, cigar-galaxy82 approved these changes

2024-10-19 10:58 UTC, closed without merging

2024-10-19 10:58 UTC, mamtawardhani commented
Hey @haruharu1017, since this PR has been raised from the `main` branch, you will have to re-raise it. Make sure you create a feature branch first, then edit the content and make other changes on the feature branch itself. Please refer to the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) to look through the steps.

Closing this PR, thank you! 😄