add postgresql functions concept
Codecademy/docs pull request #5220
Opened 2024-09-16 08:35 UTC by hakdo99

### Description

Add a concept entry about PostgreSQL functions. The new file is functions.md.

### Issue Solved

 Closes #4589

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-09-18 13:54 UTC, SaviDahegaonkar requested changes
Hey @hakdo99 ,
The entry is nicely written, and I have suggested a few changes. Please make them asap.

Thanks,
Savi

2024-09-18 13:54 UTC, SaviDahegaonkar commented on content/postgresql/concepts/functions/functions.md
> +  - 'learn-postgresql'
```suggestion
  - 'learn-postgresql'
```
Include only those course paths that are already available in the [catalog-content.md file](documentation/catalog-content.md). You can add one if you want it to get included in the PR.  Here `learn-postgresql` is not available in the catalog-content file so it makes it invalid to get included in PR.

2024-09-18 13:54 UTC, SaviDahegaonkar commented on content/postgresql/concepts/functions/functions.md
> +**`Functions`** in PostgreSQL, also known as Stored Procedures, are sets of SQL and procedural commands stored on the database server. They enable us to perform executions within the database within
```suggestion
**`Functions`** in PostgreSQL, also known as Stored Procedures, are sets of SQL and procedural commands stored on the database server. They enable us to perform executions within the database within a single function that usually requires several commands and round trips.
```

2024-09-18 13:54 UTC, SaviDahegaonkar commented on content/postgresql/concepts/functions/functions.md
> +   $$ LANGUAGE lang_name;
```suggestion
CREATE [OR REPLACE] FUNCTION function_name (parameters) 
RETURNS return_type AS $$
   DECLARE
      < variable_declaration >
      [...]
   BEGIN
      < function_body >
      [...]
      RETURN { variable_name | value } ;
   END; 
   $$ LANGUAGE lang_name;
```
Added semicolon at line number 32 for correct syntax.

2024-09-26 07:46 UTC, SaviDahegaonkar commented
Hey @NelsonSanti ,
Can I know if you have implemented the suggested changes so I can make it available for a second review?

2024-09-26 15:59 UTC, NelsonSanti commented
Hello @SaviDahegaonkar 
it seems you were mistaken,
This job is not assigned to me.
No worries and thank you!

2024-09-29 08:16 UTC, SaviDahegaonkar commented
> Hello @SaviDahegaonkar it seems you were mistaken, This job is not assigned to me. No worries and thank you!

Yeah, I am really sorry for the misunderstanding.

2024-09-30 10:23 UTC, SaviDahegaonkar commented
Hey @hakdo99 ,
Can I know if you have implemented the suggested changes so I can make it available for a second review?

Thanks,
Savi

2024-10-15 12:06 UTC, SaviDahegaonkar approved these changes
Hey @hakdo99 ,
LGTM! Thank You for Contributing to docs :)

Thanks,
Savi

2024-10-15 12:06 UTC, SaviDahegaonkar commented on content/postgresql/concepts/functions/functions.md
> +* `language lang_name` defines the name of the language that the function is implemented in. Note that PostgreSQL supports many languages including  SQL, C, PL/pgSQL, or the name of a user-defined pr
```suggestion
- `function_name` refers to the name of the function.

- [OR REPLACE] option allows you to update an existing function.

- In `parameters`, list out the parameters that the function takes in. A function can have zero or more parameters.

- Define the datatype of the returned value after `returns`. The `return_type` could be a base, composite, domain type, or even reference a table column's type.

- The `AS` keyword is used when defining a standalone function.

- `function_body` contains the logic of the function that will be executed.

- `language lang_name` defines the name of the language that the function is implemented in. Note that PostgreSQL supports many languages including  SQL, C, PL/pgSQL, or the name of a user-defined procedural language.
```

2024-10-15 12:06 UTC, SaviDahegaonkar commented on content/postgresql/concepts/functions/functions.md
> +Breaking down the syntax:
```suggestion
Breaking down the code:
```

2024-11-15 07:16 UTC, Radhika-okhade commented on content/postgresql/concepts/functions/functions.md
> +  - 'Computer Science'
```suggestion
  - 'Computer Science'
  - 'Data Science'
```

2024-11-15 08:43 UTC, Radhika-okhade commented on content/postgresql/concepts/functions/functions.md
> +  - 'Functions'
```suggestion
  - 'Functions'
  - 'PostgreSQL'
```

2024-11-15 08:50 UTC, Radhika-okhade commented on content/postgresql/concepts/functions/functions.md
> +Here's the basic syntax used to define a function:
```suggestion
Here is the syntax used to define a function:
```

2024-11-15 13:13 UTC, SaviDahegaonkar approved these changes

2024-11-15 13:13 UTC, SaviDahegaonkar commented on content/postgresql/concepts/functions/functions.md
> +
```suggestion
Here the `average_salary` variable is used to store the result of the AVG(salary) calculation, and the function will return the average salary.

```

2024-11-15 13:13 UTC, SaviDahegaonkar commented on content/postgresql/concepts/functions/functions.md
> +Call the function to get the average salary:
```suggestion
To call the avg_salary() function and get the average salary, we can use the `SELECT` statement as follows:
```

2024-11-15 13:24 UTC, SaviDahegaonkar approved these changes

2024-11-15 13:24 UTC, SaviDahegaonkar commented on content/postgresql/concepts/functions/functions.md
> +
```suggestion
```
```

2024-11-15 13:27 UTC, SaviDahegaonkar approved these changes

2024-11-15 13:27 UTC, SaviDahegaonkar commented on content/postgresql/concepts/functions/functions.md
> +
```suggestion
```pseudo
CREATE [OR REPLACE] FUNCTION function_name(parameters) 
RETURNS return_type AS $$
DECLARE
    <variable_name> <data_type>;
BEGIN
   <function_logic>;
   RETURN <value_or_variable>;
END;
$$ LANGUAGE lang_name;
```
```

2024-11-15 13:28 UTC, SaviDahegaonkar approved these changes

2024-11-15 13:28 UTC, SaviDahegaonkar commented on content/postgresql/concepts/functions/functions.md
> +Suppose we have a table `employees` containing the employees' names and salaries, with the following records:
```suggestion
Suppose we have a table `employees` containing employees names and salaries, with the following records:
```

2024-11-28 07:34 UTC, codecademy-docs commented on content/postgresql/concepts/functions/functions.md
> +- `LANGUAGE lang_name` : Defines the name of the language in which the function is written.
```suggestion
- `function_name`: Refers to the name of the function.
- `[OR REPLACE]`: It updates an existing function with the same name. If the function does not exist, PostgreSQL will create a new one. 
- `parameters`: These are the input parameters that the function accepts. 
- `RETURNS return_type`: Specifies the type of value that the function will return.
- `AS`: It is used to introduce the function body. 
- `function_body`: This field contains the function's logic that will be executed when the function is called.
- `LANGUAGE lang_name`: Defines the name of the language in which the function is written.
```

2024-11-28 07:53 UTC, Radhika-okhade commented on content/postgresql/concepts/functions/functions.md
> +- `LANGUAGE lang_name` : Defines the name of the language in which the function is written.
```suggestion
- `function_name`: Refers to the name of the function.
- `[OR REPLACE]`: It allows you to update an existing function with the same name. If the function does not exist, PostgreSQL will create a new one.
- `parameters`: These are the input parameters that the function accepts. 
- `RETURNS return_type`: Specifies the type of value that the function will return.
- `AS`: It is used to introduce the function body. 
- `function_body`: This field contains the function's logic that will be executed when called.
- `LANGUAGE lang_name`: Defines the name of the language in which the function is written.
```

2024-11-28 08:07 UTC, Radhika-okhade commented on content/postgresql/concepts/functions/functions.md
> +**`Functions`** in PostgreSQL are reusable sets of SQL and procedural commands stored on the database server. They are also referred to as Stored Procedures. They enable us to perform complex operati
```suggestion
**`Functions`** in PostgreSQL are reusable sets of SQL and procedural commands stored on the database server. They are also referred to as *Stored Procedures*. They enable us to perform complex operations within the database within a single function that usually requires several commands and round trips.
```

2024-11-28 08:14 UTC, Radhika-okhade commented on content/postgresql/concepts/functions/functions.md
> +- `LANGUAGE lang_name`: Defines the name of the language in which the function is written.
```suggestion
- `function_name`: Specifies the function name.
- `[OR REPLACE]`: Allows updating an existing function with the same name. PostgreSQL will create a new function if the function does not exist
- `parameters`: These are the input parameters that the function accepts. 
- `RETURNS return_type`: Specifies the type of value that the function will return.
- `AS`: Introduces the function body. 
- `function_body`: This field contains the function's logic that will be executed when the function is called.
- `LANGUAGE lang_name`: Defines the name of the language in which the function is written.
```

2024-11-28 08:17 UTC, Radhika-okhade commented on content/postgresql/concepts/functions/functions.md
> +We would like to create a function that calculates the average salary of all employees in the table. Our function `avg_salary()` , can be defined as follows:
```suggestion
We want to create a function that calculates the average salary of all employees in the table. The function `avg_salary()` can be defined as follows:
```

2024-11-28 08:21 UTC, Radhika-okhade commented on content/postgresql/concepts/functions/functions.md
> +To call the avg_salary() function and get the average salary, we can use the `SELECT` statement as follows:
```suggestion
To call the `avg_salary()` function and get the average salary, use the `SELECT` statement as follows:
```

2024-11-28 08:22 UTC, Radhika-okhade commented on content/postgresql/concepts/functions/functions.md
> +Thie above code will call the `avg_salary( )` function and return the calculated average salary of all the emplyees in the `employee` table.
```suggestion
The above code will call the `avg_salary( )` function and return all the employees calculated average salaries in the `employee` table.
```

2024-11-28 08:23 UTC, Radhika-okhade commented on content/postgresql/concepts/functions/functions.md
> +```
```suggestion
```

```

2024-11-28 08:25 UTC, Radhika-okhade commented on content/postgresql/concepts/functions/functions.md
> +We want to create a function that calculates the average salary of all employees in the table. The function `avg_salary()` can be defined as follows:
```suggestion

We want to create a function that calculates the average salary of all employees in the table. The function `avg_salary()` can be defined as follows:
```

2024-11-28 08:32 UTC, Radhika-okhade approved these changes

2024-11-28 08:33 UTC, merged