[Edit] JavaScript Variables
Codecademy/docs pull request #5277
Opened 2024-09-17 14:53 UTC by smiosso

### Description

- Added new codebite examples.

### Issue Solved
- Closes issue #5204 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ x] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-09-17 15:23 UTC, smiosso commented
Something went wrong, and I do not know why or how to fix it.

2024-09-17 15:32 UTC, Sriparno08 commented
No worries, @smiosso. The reviewers will fix it.

2024-09-17 16:07 UTC, smiosso commented
Thank youuuuuu!!! ☺️

_________________________________
Samantha A. Colognese Tamiosso
+49 157 8510 6917



Em ter., 17 de set. de 2024 às 17:32, Sriparno Roy ***@***.***>
escreveu:

> No worries, @smiosso <https://github.com/smiosso>. The reviewers will fix
> it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Codecademy/docs/pull/5277#issuecomment-2356259300>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFZ5FAFCCEXBLSMTH5ECGYDZXBDQ7AVCNFSM6AAAAABOLVK3S2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNJWGI2TSMZQGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-20 15:09 UTC, Sriparno08 requested changes
Hey @smiosso, thanks for contributing to Codecademy Docs!

I've listed all the modifications that you need to make in your entry below:

2024-09-20 15:09 UTC, Sriparno08 commented on content/javascript/concepts/variables/variables.md
> +```js
Let's do the same changes as the previous one:

````suggestion
## Codebyte Example

The following codebyte example shows how to declare variables in JavaScript:

```codebyte/javascript
````

2024-09-20 15:09 UTC, Sriparno08 commented on content/javascript/concepts/variables/variables.md
> +```
Let's remove this codebyte example as there's nothing to output here:

````suggestion
let audienceNumber = 300; // Number
```
````

2024-10-04 15:19 UTC, Sriparno08 approved these changes
Hey @smiosso, this PR looks good for a second round of review!

2024-10-05 12:55 UTC, mamtawardhani approved these changes
Thank you for contributing to Codecademy Docs @smiosso 😄 

The entry is ready to be merged! 🚀

2024-10-05 13:10 UTC, merged