Doc contributions
Codecademy/docs pull request #5278
Opened 2024-09-17 16:32 UTC by aSagCoder

### Description

- added the term entry for in-built Python function .slice(). 
- Can be located here - content/python/concepts/built-in-functions/terms/slice/slice.md

### Issue Solved

Closes #5117 

### Type of Change

- Adding a new entry
 - ~~Editing an existing entry (fixing a typo, bug, issues, etc)~~
- ~~Updating the documentation~~

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-09-20 14:44 UTC, Sriparno08 requested changes
Hey @aSagCoder, thanks for contributing to Codecademy Docs!

I've listed all the modifications that you need to make in your entry below:

2024-09-20 14:44 UTC, Sriparno08 commented on content/python/concepts/built-in-functions/terms/slice/slice.md
> +
Modifications:

- Let's remove the introductory line as it's not needed
- Let's do some minor changes in the bulleted list

```suggestion
- `start`: This optional integer indicates where the slicing of the object begins. The default value is `None` if not provided.
- `stop`: This integer indicates up to where the slicing takes place. It stops at index `stop-1` (the last element of the sequence).
- `step`: This optional integer fixes the increment between each index for slicing. The default value is `None` if not provided.
```

2024-09-20 14:44 UTC, Sriparno08 commented on content/python/concepts/built-in-functions/terms/slice/slice.md
> +The following example shows the use of the `.slice()' function:
Let's do some minor changes:

```suggestion
The following example shows the use of the `slice()` function:
```

2024-09-20 14:44 UTC, Sriparno08 commented on content/python/concepts/built-in-functions/terms/slice/slice.md
> +
Let's start the comments using capital letters and do some minor changes:

```suggestion
# Create a tuple with some values in it
fruits = ("Apple", "Banana", "Orange", "Kiwi", "Strawberry", "Plum", "Watermelon")

# Create a slice object
a = slice(3)

# Return the resultant slice object
print(fruits[a])
```

2024-09-20 14:44 UTC, Sriparno08 commented on content/python/concepts/built-in-functions/terms/slice/slice.md
> +```
Let's do some minor changes:

````suggestion
```

The output of the code is as follows:

```shell
('Apple', 'Banana', 'Orange')
```
````

2024-09-20 14:44 UTC, Sriparno08 commented on content/python/concepts/built-in-functions/terms/slice/slice.md
> +```
Modifications:

- Let's remove 'if applicable' and the comments as they're not needed
- Let's do some minor changes

````suggestion
## Codebyte Example

The following codebyte example demonstrates how the `slice()` function is used to create a slice object from a given sequence (here, a string) between a defined range:

```codebyte/python
my_string = 'CompetitiveProgramming'
slice_obj1 = slice(5)
slice_obj2 = slice(1, 8, 2)

print("Resulting slices:")
print(my_string[slice_obj1])
print(my_string[slice_obj2])
```
````

2024-09-22 07:12 UTC, aSagCoder commented
> Hey @aSagCoder, thanks for contributing to Codecademy Docs!
> 
> I've listed all the modifications that you need to make in your entry below:

Hi there, thanks for the suggestions! I have gone over those and committed them.

2024-09-23 04:59 UTC, Sriparno08 approved these changes
Good job, @aSagCoder!

This entry looks good for a second round of review.

2024-09-26 13:31 UTC, mamtawardhani approved these changes
Thank you for contributing @aSagCoder 😄 

The entry is ready to be merged! 🚀

2024-09-26 13:36 UTC, merged