Python NumPy - Math functions .nanprod()
Codecademy/docs pull request #5293
Opened 2024-09-23 14:02 UTC by gourabdg47

Created new file docs/content/numpy/concepts/math-methods/terms/nanprod/nanprod.md

### Description

### Issue Solved

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [+] All writings are my own.
- [+] My entry follows the Codecademy Docs style guide.
- [+] My changes generate no new warnings.
- [+] I have performed a self-review of my own writing and code.
- [+] I have checked my entry and corrected any misspellings.
- [+] I have made corresponding changes to the documentation if needed.
- [+] I have confirmed my changes are not being pushed from my forked `main` branch.
- [+] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [+] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-09-23 14:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5293) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5293) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5293) it.</sub>

2024-09-23 14:16 UTC, gourabdg47 commented
Issue : 
https://github.com/Codecademy/docs/issues/5243

2024-10-07 03:22 UTC, cigar-galaxy82 requested changes

2024-10-07 03:22 UTC, cigar-galaxy82 commented on content/numpy/concepts/math-methods/terms/nanprod/nanprod.md
> +In NumPy, the **`.nanprod()`** function calculates the product of array elements over a specified axis, treating NaN (Not a Number) values as 1. This function is particularly useful when working with
```suggestion
In NumPy, the **`.nanprod()`** function calculates the product of array elements over a specified axis, treating `NaN` (Not a Number) values as 1. This function is particularly useful when working with arrays that may contain missing or undefined values represented as `NaN`.
```

2024-10-07 03:22 UTC, cigar-galaxy82 commented on content/numpy/concepts/math-methods/terms/nanprod/nanprod.md
> +- `keepdims` (optional): If set to True, the axes which are reduced are left in the result as dimensions with size one.
```suggestion
- `a`: An array for which the product is calculated.
- `axis`: An optional parameter used as the axis along which the product is computed. If not specified, the product of all elements is calculated.
- `dtype` : An optional parameter used as the data type of the output. If not specified, then the data type the input is used.
- `out`: An optional parameter specifying the array to store the result. If not provided, a new array is created.
- `keepdims`: An optional parameter if set to True, the axes that are reduced are left in the result as dimensions with size one.
```

2024-10-07 03:22 UTC, cigar-galaxy82 commented on content/numpy/concepts/math-methods/terms/nanprod/nanprod.md
> +This example demonstrates using `.nanprod()` function to calculate the product of an array containing NaN values:
```suggestion
This example demonstrates using `.nanprod()` function to calculate the product of an array containing `NaN` values:
```

2024-10-07 03:22 UTC, cigar-galaxy82 commented on content/numpy/concepts/math-methods/terms/nanprod/nanprod.md
> +Description: 'Calculates the product of array elements over a given axis, treating NaN (Not a Number) values as 1.'
```suggestion
Description: 'Calculates the product of array elements.'
```

2024-10-07 03:22 UTC, cigar-galaxy82 commented on content/numpy/concepts/math-methods/terms/nanprod/nanprod.md
> +This example showcases how `.nanprod()` handles NaN values and maintains the dimensions of the output when `keepdims=True`.
Give a blank line after this

2024-10-07 03:22 UTC, cigar-galaxy82 commented on content/numpy/concepts/math-methods/terms/nanprod/nanprod.md
> +Description: 'Calculates the product of array elements over a given axis, treating NaN (Not a Number) values as 1.'
reframed as this gives a basic description and later in-depth explanation is given

2024-10-07 03:23 UTC, cigar-galaxy82 commented
Hi @gourabdg47 thank you for contributing to Codecademy docs, I have suggested a few changes please modify them.

2024-10-07 10:04 UTC, gourabdg47 commented
Hi @cigar-galaxy82  I have committed your  suggestions

2024-10-17 13:21 UTC, cigar-galaxy82 approved these changes

2024-10-17 13:27 UTC, cigar-galaxy82 approved these changes

2024-10-18 14:35 UTC, mamtawardhani approved these changes
Thank you for contributing @gourabdg47 😄 

The entry is ready to be merged 🚀

2024-10-19 10:56 UTC, merged