[Term Entry] Python NumPy - Math functions .unwrap()
Codecademy/docs pull request #5297
Opened 2024-09-23 17:07 UTC by toshydev

### Description

Added The `unwrap()` term for NumPy
Location of file: content/numpy/concepts/math-methods/terms/unwrap/unwrap.md

### Issue Solved

Closes #5236

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-09-23 18:02 UTC, SaviDahegaonkar requested changes
Hey @toshydev ,
The entry LGTM. I have suggested a few changes to you please make them asap.

Thanks,
Savi

2024-09-24 13:32 UTC, toshydev commented
I made the requested changes. ✅️

2024-10-01 13:32 UTC, mamtawardhani commented
@SaviDahegaonkar kindly check this on priority :)

2024-10-06 19:46 UTC, SaviDahegaonkar approved these changes
Hey @toshydev,
LGTM! The entry looks good for second round of review.


Thanks,
Savi

2024-10-06 19:46 UTC, SaviDahegaonkar commented on content/numpy/concepts/math-methods/terms/unwrap/unwrap.md
> +numpy.unwrap(input_value, discont=pi, axis=-1, period=2*numpy.pi)
```suggestion
numpy.unwrap(input_value, discont=numpy.pi, axis=-1, period=2*numpy.pi)
```

2024-10-08 14:01 UTC, mamtawardhani approved these changes
Thank you for contributing @toshydev 😄 

The entry is ready to be merged 🚀

2024-10-08 14:09 UTC, merged