Python plotly funnel
Codecademy/docs pull request #5298
Opened 2024-09-24 05:00 UTC by ebikatsudon

### Description

Created term entry for the `.funnel()` method in Python Plotly Express module. Also added images docs\media\plotly-express-funnel-example1.png and docs\media\plotly-express-funnel-example2.png

### Issue Solved

Closes #5172 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-09-24 08:40 UTC, SaviDahegaonkar requested changes
Hey @ebikatsudon ,
The entry LGTM, I have suggested a change please make it asap.

Thanks,
Savi

2024-09-24 08:40 UTC, SaviDahegaonkar commented on content/plotly/concepts/express/terms/funnel/funnel.md
> +The **.funnel()** method in Plotly Express creates a chart showing the progressive reduction, or "funneling," of data as it moves through sequential stages. The chart is composed of stacked horizonta
```suggestion
The **`.funnel()`** method in Plotly Express creates a chart showing the progressive reduction, or "funneling," of data as it moves through sequential stages. The chart is composed of stacked horizontal bars, with the length of each bar representing a value at each stage in the process. This helps visualize how the values change as they move through each stage and can highlight bottlenecks or drop-offs in values.
```
The method name should be included inside (`.....`) single backticks.

2024-09-25 01:09 UTC, ebikatsudon commented
Hi @SaviDahegaonkar, thank you for your review! I have made and committed the change you suggested.

2024-10-06 19:33 UTC, SaviDahegaonkar approved these changes
Hey @ebikatsudon ,
LGTM! This entry looks good for second round of review.

Thanks,
Savi

2024-10-10 07:10 UTC, mamtawardhani approved these changes
Thank you for contributing @ebikatsudon 😄 

The entry is ready to be merged! 🚀

2024-10-10 07:12 UTC, merged