#5237 fix added around method to docs
Codecademy/docs pull request #5299
Opened 2024-09-24 05:20 UTC by fazil-shaik

### Description

I had maken changes on issue and added fix for #5237 a numpy method of around docs is created and motivation behind this documentation is to provide clear, accessible information for learners in computer science and data science, helping them understand and effectively utilize the .around() method in their projects.
### Issue Solved
#5237 is created and no issues found 
#5237

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [* ] All writings are my own.
- [* ] My entry follows the Codecademy Docs style guide.
- [ *] My changes generate no new warnings.
- [ *] I have performed a self-review of my own writing and code.
- [ *] I have checked my entry and corrected any misspellings.
- [ *] I have made corresponding changes to the documentation if needed.
- [ *] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ *] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ *] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-09-24 05:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5299) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5299) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5299) it.</sub>

2024-10-03 05:13 UTC, fazil-shaik commented
hey hi merge my PR that i had opened assign me this issue

2024-10-13 19:22 UTC, SaviDahegaonkar requested changes
Hey @fazil-shaik ,
I had a look at your file, Please make the suggested changes asap so I can get this PR ready for second round of review.

Thanks,
Savi

2024-10-13 19:22 UTC, SaviDahegaonkar commented on content/numpy/concepts/math-methods/terms/around/around.md
> +| CatalogContent | learn-python-3, paths/computer-science |
```suggestion
| Field | Value |
| --- | --- |
| Title | .around() |
| Description | Rounds each element in an array to the given number of decimals. |
| Subjects | Computer Science, Data Science |
| Tags | Arrays, Methods, NumPy, Rounding |
| CatalogContent | learn-python-3, paths/computer-science |
```
Remove all the vertical lines over here. 
 Title: 
Description: 
Subjects:
-
The correct format should be like this.

2024-10-13 19:22 UTC, SaviDahegaonkar commented on content/numpy/concepts/math-methods/terms/around/around.md
> +##out: This is an optional parameter. It specifies an output array to store the result. If not provided or set to None, a new array is created for the result.
```suggestion
- x: This is the input array containing the numbers you want to round.
- decimals: The number of decimal places to which each element will be rounded. The default value is 0, which rounds to the nearest integer. Negative values are allowed to round to the left of the decimal point.
- out: This is an optional parameter. It specifies an output array to store the result. If not provided or set to None, a new array is created for the result.
```
Parameters explanation format should be like this.

2024-10-13 19:22 UTC, SaviDahegaonkar commented on content/numpy/concepts/math-methods/terms/around/around.md
> +Example
```suggestion
## Example
```
Example section should be written using the hash symbol.

2024-10-13 19:22 UTC, SaviDahegaonkar commented on content/numpy/concepts/math-methods/terms/around/around.md
> +Codebyte Example
```suggestion
## Codebyte Example
```

2024-10-13 19:22 UTC, SaviDahegaonkar commented on content/numpy/concepts/math-methods/terms/around/around.md
> +```
```suggestion

```

2024-10-13 19:22 UTC, SaviDahegaonkar commented on content/numpy/concepts/math-methods/terms/around/around.md
> +```
```suggestion

```

2024-10-17 19:09 UTC, SaviDahegaonkar commented
Hey @fazil-shaik, Can you please implement the changes I suggested so we can merge this PR?

2024-11-13 17:52 UTC, SaviDahegaonkar approved these changes

2024-11-20 15:01 UTC, Sriparno08 approved these changes
Looks good, @fazil-shaik!

2024-11-20 15:04 UTC, merged