Created .linspace() entry
Codecademy/docs pull request #5301
Opened 2024-09-24 15:58 UTC by arisdelacruz

### Description

This is an attempt to create an entry for the .linspace() function for Pytorch

### Issue Solved

Closes #5224 

### Type of Change

- Adding a new entry

### Checklist

- [ / ] All writings are my own.
- [ / ] My entry follows the Codecademy Docs style guide.
- [ / ] My changes generate no new warnings.
- [ / ] I have performed a self-review of my own writing and code.
- [ / ] I have checked my entry and corrected any misspellings.
- [ / ] I have made corresponding changes to the documentation if needed.
- [ / ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ / ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ / ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-10-09 07:35 UTC, Sriparno08 requested changes
Hey @arisdelacruz, thanks for contributing to Codecademy Docs!

I've listed all the modifications that you need to make in your entry below:

2024-10-09 07:35 UTC, Sriparno08 commented on content/pytorch/concepts/tensors/terms/linspace/linspace.md
> +---
Let's change the description a bit for uniqueness:

```suggestion
---
Title: '.linspace()'
Description: 'Returns a one-dimensional tensor of the specified size, whose values are equally spaced from the given starting and ending values.'
Subjects:
  - 'Data Science'
  - 'Machine Learning'
Tags:
  - 'AI'
  - 'Data Types'
  - 'Deep Learning'
  - 'Functions'
CatalogContent:
  - 'intro-to-py-torch-and-neural-networks'
  - 'py-torch-for-classification'
---
```

2024-10-09 07:35 UTC, Sriparno08 commented on content/pytorch/concepts/tensors/terms/linspace/linspace.md
> +The function returns a one-dimensional tensor of equally spaced points between the start and end values.
Modifications:

- Let's remove the second line as it's already mentioned in `Syntax`
- Let's remove the third line as it resembles the first line
- Let's change the first line a bit for uniqueness

```suggestion
The **`.linspace()`** function in PyTorch is used to return a one-dimensional tensor of the specified size, whose values are equally spaced from the given starting and ending values.
```

2024-10-09 07:35 UTC, Sriparno08 commented on content/pytorch/concepts/tensors/terms/linspace/linspace.md
> +- `steps` is the number of steps to be taken between the start and end values.
Let's do some minor changes in the bulleted list:

```suggestion
- `start`: The starting value to be used.
- `end`: The ending value to be used.
- `steps`: The number of steps to be taken between the starting and ending values.
```

2024-10-09 07:35 UTC, Sriparno08 commented on content/pytorch/concepts/tensors/terms/linspace/linspace.md
> +This function is particularly useful when you need to create a tensor of equally spaced points for plotting graphs or for other numerical computations.
Let's change this line a bit:

```suggestion
This function is particularly useful when there is a need to create a tensor of equally spaced points for plotting graphs or for performing other numerical computations.
```

2024-10-09 07:35 UTC, Sriparno08 commented on content/pytorch/concepts/tensors/terms/linspace/linspace.md
> +Let's see an example of how to use the `.linspace()` function in PyTorch:
Let's change this line a bit:

```suggestion
The following example shows how to use the `.linspace()` function in PyTorch:
```

2024-10-09 07:35 UTC, Sriparno08 commented on content/pytorch/concepts/tensors/terms/linspace/linspace.md
> +```
Let's change the example a bit for uniqueness:

````suggestion
```py
import torch

# Create a tensor of 5 equally spaced points between 0 and 1
x = torch.linspace(0, 1, 5)

print(x)
```
````

2024-10-09 07:35 UTC, Sriparno08 commented on content/pytorch/concepts/tensors/terms/linspace/linspace.md
> +The `.linspace()` function is a convenient way to create a tensor of equally spaced points for various numerical computations in PyTorch.
Modifications:

- Let's insert the output of the modified code
- Let's remove the second last paragraph as it's not needed
- Let's remove the last line as it's already mentioned before

````suggestion
```shell
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
```
````

2024-10-09 15:59 UTC, Sriparno08 approved these changes
Good job, @arisdelacruz!

This entry looks good for a second round of review.

2024-10-10 06:28 UTC, mamtawardhani approved these changes
Thank you for contributing @arisdelacruz 😄 

The entry is ready to be merged! 🚀

2024-10-10 06:57 UTC, merged