Creation of the logspace entry
Codecademy/docs pull request #5327
Opened 2024-09-25 07:09 UTC by arisdelacruz

### Description

This is an attempt to create the information on the logspace function for Pytorch. Hoping to help learners expand their knowledge on the subject.

### Issue Solved

Closes #5225 

### Type of Change

- Adding a new entry

### Checklist

- [/] All writings are my own.
- [/] My entry follows the Codecademy Docs style guide.
- [/] My changes generate no new warnings.
- [/] I have performed a self-review of my own writing and code.
- [/] I have checked my entry and corrected any misspellings.
- [/] I have made corresponding changes to the documentation if needed.
- [/] I have confirmed my changes are not being pushed from my forked `main` branch.
- [/] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [/] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-09-30 01:24 UTC, cigar-galaxy82 requested changes

2024-09-30 01:24 UTC, cigar-galaxy82 commented on content/pytorch/concepts/tensors/terms/logspace/logspace.md
> +- `dtype` is the data type of the tensor.
```suggestion
- `start`: The first number in the range expressed as a logarithm.
- `end`: The last number in the range expressed as a logarithm.
- `steps`: Number of elements to be returned in the tensor.
- `base`: The base of the logarithm used for calculating the values default value is 10.
- `dtype`: Specifies the data type of the returned tensor.
```

2024-09-30 01:24 UTC, cigar-galaxy82 commented on content/pytorch/concepts/tensors/terms/logspace/logspace.md
> +In the first example, we created a tensor `tensor` containing 5 logarithmically spaced values between 1 and 1000 using the `.logspace()` function. The tensor `tensor` contains the values `[10.0000, 1
Mention this after first example

2024-09-30 01:24 UTC, cigar-galaxy82 commented on content/pytorch/concepts/tensors/terms/logspace/logspace.md
> +In the second example, we created a tensor `tensor` containing 3 logarithmically spaced values between 0 and 1 using the `.logspace()` function with a data type of `torch.float64`. The tensor `tensor
Mention this after second example

2024-09-30 01:25 UTC, cigar-galaxy82 commented
Hi @arisdelacruz thank you for contributing to Codecademy docs, I have suggested a few changes please modify them.

2024-09-30 03:12 UTC, arisdelacruz commented
> Hi @arisdelacruz thank you for contributing to Codecademy docs, I have suggested a few changes please modify them.

@cigar-galaxy82 

 done with the edits. Hope I hit them right. Thank you

2024-10-07 17:53 UTC, cigar-galaxy82 approved these changes

2024-10-08 14:42 UTC, mamtawardhani approved these changes
Thhank you for contributing @arisdelacruz 😄 

The entry looks good for a second round of review! 🚀

2024-10-08 16:35 UTC, merged