[Term Entry] PyTorch Tensor Operations: .mm()
Codecademy/docs pull request #5328
Opened 2024-09-25 07:58 UTC by Sriparno08

### Description

Created a new term entry for the `.mm()` method under `Tensor Operations` in PyTorch.

### Issue Solved

Closes #5059

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-10-09 08:56 UTC, cigar-galaxy82 requested changes

2024-10-09 08:56 UTC, cigar-galaxy82 commented on content/pytorch/concepts/tensor-operations/terms/mm/mm.md
> +If `ten1` is a `(m x n)` tensor and `ten2` is a `(n x p)` tensor, then `out` will be a `(m x p)` tensor.
mentioned this as a note

2024-10-09 08:57 UTC, cigar-galaxy82 commented
Hi @Sriparno08 thank you for contributing to Codecademy docs, I have suggested a single changes please modify them.

2024-10-09 09:54 UTC, Sriparno08 commented
Done, @cigar-galaxy82.

2024-10-13 06:23 UTC, cigar-galaxy82 approved these changes

2024-10-16 08:51 UTC, mamtawardhani commented
@cigar-galaxy82 kindly merge this

2024-10-17 07:07 UTC, merged