[Concept Entry]: Add codebyte example - sklearn concepts
Codecademy/docs pull request #5335
Opened 2024-09-25 13:58 UTC by saldanhad

### Description
Added the `codebyte examples` for multiple concept entries under`sklearn`.

### Issue Solved
closes #5334

- Added the `codebyte example` for below algorithms under concept entry for `sklearn`:
    - `Multitask Classification`
    - `Naive Bayes` (added example and codebyte example)
    - `Support Vector Machines`

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-09-29 14:00 UTC, saldanhad commented
Hi @cigar-galaxy82, would we need a second review here or can we merge the changes ?

2024-10-06 03:28 UTC, saldanhad commented
any update here?

2024-10-07 03:28 UTC, cigar-galaxy82 commented
Hi @saldanhad thank you for contributing to Codecademy docs, I have a few suggestions for each Codebyte example use a different example code then the one used in the Example section

2024-10-07 03:29 UTC, cigar-galaxy82 requested changes

2024-10-07 03:29 UTC, cigar-galaxy82 commented on content/sklearn/concepts/naive-bayes/naive-bayes.md
> +
remove this blank line

2024-10-09 10:32 UTC, cigar-galaxy82 commented
Hi @saldanhad once @SaviDahegaonkar reviews for the second time it will get merged

2024-10-09 10:51 UTC, saldanhad commented
Hi @cigar-galaxy82, thanks for your reply, still waiting on  #5209 to get merged.

2024-10-09 11:03 UTC, SaviDahegaonkar approved these changes
Hey @saldanhad , 
LGTM! Thanks for contributing to docs.


Thanks,
Savi

2024-10-17 13:12 UTC, cigar-galaxy82 approved these changes

2024-10-17 13:16 UTC, merged