[Concept Entry] C++ List
Codecademy/docs pull request #5337
Opened 2024-09-26 13:49 UTC by SaviDahegaonkar

### Description

A new entry on C++ lists

### Issue Solved
#5314 

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-09-29 21:49 UTC, cigar-galaxy82 requested changes

2024-09-29 21:49 UTC, cigar-galaxy82 commented on content/cpp/concepts/list/list.md
> +To implement std::list in C++, you need to include the following header:
Mention this part as a note

2024-09-29 21:49 UTC, cigar-galaxy82 commented on content/cpp/concepts/list/list.md
> +```
In this part mention pseudo code for list

2024-09-29 21:49 UTC, cigar-galaxy82 commented on content/cpp/concepts/list/list.md
> +
Remove this line

2024-09-29 21:49 UTC, cigar-galaxy82 commented on content/cpp/concepts/list/list.md
> +}
```suggestion
#include <iostream>
#include <list>

int main() {
  // Declare a list of integers

  std::list < int > myList;
  // Adding elements to the list

  myList.push_back(10); // Adds 10 to the back
  myList.push_back(20); // Adds 20 to the back
  myList.push_front(5); // Adds 5 to the front
  // Displaying elements in the list
  std::cout << "List elements: ";
  for (const auto & value: myList) {
    std::cout << value << " "; // Output: 5 10 20
  }
  std::cout << std::endl;
  // Removing an element
  myList.remove(10); // Removes the element with value 10
  // Displaying the updated list
  std::cout << "Updated list elements after deletion: ";
  for (const auto & value: myList) {
    std::cout << value << " "; // Output: 5 20
  }
  std::cout << std::endl;
  return 0;
}
```

2024-09-29 21:49 UTC, cigar-galaxy82 commented on content/cpp/concepts/list/list.md
> +
Remove this blank line

2024-09-29 21:49 UTC, cigar-galaxy82 commented on content/cpp/concepts/list/list.md
> +int main() {
Give a blank line after line 30

2024-09-29 21:49 UTC, cigar-galaxy82 commented on content/cpp/concepts/list/list.md
> +The output for the above code is:
Give a blank line after line 50

2024-09-29 21:49 UTC, cigar-galaxy82 commented on content/cpp/concepts/list/list.md
> +Description: 'In C++, list is a doubly linked list from the STL. It allows efficient insertions and deletions of data'
```suggestion
Description: 'List is a sequential container that stores elements non-contiguous memory locations.' 
```

2024-09-29 21:49 UTC, cigar-galaxy82 commented on content/cpp/concepts/list/list.md
> +Title: 'List'
```suggestion
Title: 'List'
```

2024-09-29 21:50 UTC, cigar-galaxy82 commented
Hi @SaviDahegaonkar thank you for contributing to Codecademy docs, I have suggested a few changes please modify them.

2024-10-16 08:52 UTC, mamtawardhani commented
Hi @Sriparno08, quick question: the branch here is incorrect, right? I mean this PR has been raised from the main docs and not the forked repo, correct?
This needs to be closed I guess

2024-10-16 10:58 UTC, cigar-galaxy82 commented
Hi @SaviDahegaonkar I see what @mamtawardhani mentioned is correct please raise the PR again

2024-10-16 12:11 UTC, mamtawardhani commented
@cigar-galaxy82 you can close this PR

2024-10-16 13:40 UTC, SaviDahegaonkar commented
Hey @cigar-galaxy82 , Can you close this PR, I am going to re-raise a new PR for this.

2024-10-17 12:26 UTC, cigar-galaxy82 commented
Closing the PR

2024-10-17 12:26 UTC, closed without merging