Forward list
Codecademy/docs pull request #5343
Opened 2024-09-27 20:19 UTC by AlejandroAndrouin

### Description

### Issue Solved

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-09-27 20:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5343) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5343) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5343) it.</sub>

2024-10-23 14:01 UTC, cigar-galaxy82 commented
I think we can remove the Useful function section for now for this PR and keep everything before it in the document and as the whole thing is very large for docs standard

2024-10-23 14:02 UTC, cigar-galaxy82 requested changes

2024-10-23 14:04 UTC, cigar-galaxy82 commented
Hi @AlejandroAndrouin thank you for contributing to Codecademy docs, I have suggested a few changes please modify them.

2024-11-04 17:27 UTC, Radhika-okhade commented on content/cpp/concepts/forward-list/forward-list.md
> +Description: 'Forward List is a sequence container that allows efficient insertions and deletions from the front of the list.'
Description should always start with a verb.

2024-11-04 17:43 UTC, Radhika-okhade commented on content/cpp/concepts/forward-list/forward-list.md
> +std::forward_list<type> forwardlist;
```suggestion
std::forward_list<type> forwardlist; // Replace 'type' with any data type as needed.
```

2024-11-04 17:52 UTC, Radhika-okhade commented on content/cpp/concepts/forward-list/forward-list.md
> +```
Please remove all this and just a Codebyte Example section that provides an example demonstrating how to use forward_list

2024-11-04 17:55 UTC, Radhika-okhade commented
Thank you for contributing to Codecademy Docs @AlejandroAndrouin 🙂
There are a few changes I have suggested. Could you please go through them?

2024-11-08 05:27 UTC, Radhika-okhade approved these changes

2024-11-12 10:57 UTC, mamtawardhani approved these changes
Thank you for contributing to Codecademy docs @alejandroAndrowin 😄 

The entry looks good to be merged! 🚀

2024-11-12 11:02 UTC, merged