CSS Anatomy, resolves 525
Codecademy/docs pull request #536
Opened 2022-02-01 17:55 UTC by SSwiniarski

### Description

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

2022-02-16 20:12 UTC, Dusch4593 commented on content/css/concepts/anatomy/anatomy.md
> +Description: 'There are two syntaxes used to apply CSS to a web-page. The first is as a _ruleset_, the second is as an _inline style_. A ruleset is defined within a block inside an HTML document, or
```suggestion
Description: `The anatomy of CSS syntax spans between a rulesets in a stylesheet and inline styles within the markup.`
```

2022-02-16 20:27 UTC, Dusch4593 commented on content/css/concepts/anatomy/anatomy.md
> +There are two syntaxes used to apply CSS to a web-page. The first is as a _ruleset_, the second is as an _inline style_. A ruleset is defined within a block inside an HTML document, or in a separate
```suggestion
There are two syntaxes for the anatomy of [CSS](https://www.codecademy.com/resources/docs/css) styles that are applied to a web-page:

* A _ruleset_ that is defined within either an [HTML](https://www.codecademy.com/resources/docs/html) document or in a separate file (known as stylesheets) that uses the **.css** extension.

* _Inline styles_ can be applied [attributes](https://www.codecademy.com/resources/docs/html/attributes) for styling [HTML elements](https://www.codecademy.com/resources/docs/html/elements) directly.

While inline styles are directly applied to a single element, rulesets can define multiple styles across multiple elements. Another key difference between the two is that a ruleset can utilize `id` and `class` [selectors](https://www.codecademy.com/resources/docs/css/selectors) for an improved styling experience.
```

2022-02-16 20:31 UTC, Dusch4593 commented on content/css/concepts/anatomy/anatomy.md
> +Typically an inline style is used mainly for unique situations in HTML code where the style won't be repeated, in cases where HTML is dynamically generated and the CSS stylesheet is static, or in oth
```suggestion
Inline styles are commonly used for situations such as the following:

* The style being applied in the markup is unique and won't be repeated.
* The HTML markup is dynamically generated and the CSS stylesheet is static.
* Other situations where it isn't advisable (or possible) to edit the stylesheet(s) for a page.
```

2022-02-16 20:43 UTC, Dusch4593 commented on content/css/concepts/anatomy/anatomy.md
> +}
```suggestion
/* Start of Ruleset */
selector:pseudo-class::pseudo-element {

  /* Declaration */
  property: value-or-keyword;

}
/* End of Ruleset */
```

2022-02-16 20:43 UTC, Dusch4593 commented on content/css/concepts/anatomy/anatomy.md
> +```css
```suggestion
```pseudo
```

2022-02-16 20:44 UTC, Dusch4593 commented on content/css/concepts/anatomy/anatomy.md
> +<p style="color:blue;">Hello World!</p>
```suggestion
<element style="property:value;">Hello World!</element>
```

2022-02-16 20:44 UTC, Dusch4593 commented on content/css/concepts/anatomy/anatomy.md
> +```html
```suggestion
```pseudo
```

2022-02-16 20:46 UTC, Dusch4593 commented on content/css/concepts/anatomy/anatomy.md
> +Stylesheet/ruleset syntax (this will affect every `<p>` element in the HTML this apples to):
```suggestion
Rulesets use the following syntax for selecting and styling any and every instance of an existing element:
```

2022-02-16 20:47 UTC, Dusch4593 commented on content/css/concepts/anatomy/anatomy.md
> +Inline style syntax (this only affects this single `<p>` element):
```suggestion
Conversely, inline styles apply a visually-similar syntax to a single element:
```

2022-02-16 20:55 UTC, Dusch4593 commented on content/css/concepts/anatomy/anatomy.md
> +In the ruleset example, the initial `p` is known as a selector. In its simplest form, the selector can just be the element tag it applies to, i.e. `img`, `div`, `span`, `p`, though the selector can b
```suggestion
In the ruleset example, the initial `p` is a selector that can is applied to any and every valid instance of that element. Selectors possess a wide range of specificity, including:

* General selection by HTML element-name.
* Specific `class` and `id` selectors for elements.
* Pseudo-class and pseudo-element selectors.
* Reserved keyword rules like `!important` and `@media`.
```

2022-02-16 20:57 UTC, Dusch4593 commented on content/css/concepts/anatomy/anatomy.md
> +The declaration block, or attribute value, is made up of one or more declarations. In the examples, `color:blue;` is a declaration. A declaration is made up of a CSS property name, followed by a colo
```suggestion
The declaration block, or attribute value, is made up of one or more declarations. In the examples, `color:blue;` is a declaration. A declaration is made up of a CSS property name, followed by a colon (`color:`) then a value, followed by a semicolon, (`blue;`).

For either syntax, there can be an arbitrary number of declarations. While whitespacing has no effect, ruleset declarations are usually set on their own lines while inline style declarations are all placed on the same line.
```

2022-02-16 21:00 UTC, Dusch4593 requested changes
@SSwiniarski Finished with my review and ready for you to take a look for more changes. 😃

2022-02-17 13:27 UTC, SSwiniarski commented
@Dusch4593, I applied suggestions and made a few more revisions.

2022-02-18 22:27 UTC, KTom101 approved these changes
@SSwiniarski This looks good, just two minor changes!

2022-02-18 22:27 UTC, KTom101 commented on content/css/concepts/anatomy/anatomy.md
> +In the ruleset example above, the initial `p` is a selector that can is applied to any and every valid instance of that element. Selectors possess a wide range of specificity, including:
```suggestion
In the ruleset example above, the initial `p` is a selector that can be applied to any and every valid instance of that element. Selectors possess a wide range of specificity, including:
```

2022-02-18 22:27 UTC, KTom101 commented on content/css/concepts/anatomy/anatomy.md
> +For either syntax, there can be an arbitrary number of declarations. While whitespacing has no effect, ruleset declarations are usually set on their own lines while inline style declarations are all
```suggestion
For either syntax, there can be an arbitrary number of declarations. While whitespace has no effect, ruleset declarations are usually set on their own lines while inline style declarations are all placed on the same line.
```

2022-02-19 12:39 UTC, SSwiniarski commented
@KTom101, done and done.

2022-02-20 18:58 UTC, KTom101 commented
@SSwiniarski We have to remove the italics on lines 18 & 20. @yangc95 brought it to @Dusch4593 and my attention that the product team doesn't want italics in the docs. Did you want to do something else instead or would just removing the italics be fine with you?

2022-02-21 12:13 UTC, SSwiniarski commented
@KTom101. It still works without the italics. I pondered using quotes to set off the words, but I think just rewriting the two lines would work. I'll tweak it.

2022-02-21 21:15 UTC, KTom101 commented
@SSwiniarski Great! I think this is all good to merge if it's good with everyone else!

2022-02-22 20:38 UTC, yangc95 commented
@SSwiniarski I made some very minor changes to the visuals like removing extra spacing. I'm wondering if I could replace the images with the ones here:

![Screen Shot 2022-02-22 at 3 30 51 PM](https://user-images.githubusercontent.com/72277593/155214687-04ca4abc-7a97-4864-a738-43f5bd771313.png)
![Screen Shot 2022-02-22 at 3 32 48 PM](https://user-images.githubusercontent.com/72277593/155214689-f7f8d671-07bb-478b-8285-fd057a886443.png)

In any case, this entry looks ready to go @KTom101 @Dusch4593

2022-02-22 20:38 UTC, yangc95 approved these changes

2022-02-25 16:50 UTC, SSwiniarski commented
@yangc95, I updated the graphics, so we should be good to go.

2022-02-25 17:57 UTC, merged

2022-02-25 18:09 UTC, Dusch4593 commented
Nice work, everyone! 🙌  The changes are now live: https://www.codecademy.com/resources/docs/css/anatomy