Term Entry: C++ Deque Push_Back()
Codecademy/docs pull request #5364
Opened 2024-10-02 14:49 UTC by Cibiyanna26

### Description

    Added new entry .push_back() in the deque topic of c++.

### Issue Solved

Closes #5362

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-10-02 14:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5364) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5364) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5364) it.</sub>

2024-10-02 14:52 UTC, mamtawardhani commented
> [![CLA assistant check](https://camo.githubusercontent.com/bb14f9741a98be03eb447ca21a4a5e96201df401e5be70f9ef52130f4e1ff903/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/Codecademy/docs?pullRequest=5364) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5364) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5364) it.

@Cibiyanna26 please sign the CLA so that team can start reviewing this PR

2024-10-03 11:43 UTC, mamtawardhani requested changes
Hey @Cibiyanna26 thank you for contributing to Codecademy Docs! The entry is nicely written 😄 

I've suggested a few modifications, could you review and make those changes at your earliest convenience? Thank you! 😃

2024-10-03 11:43 UTC, mamtawardhani commented on content/cpp/concepts/deque/terms/push_back/push_back.md
> +The **`deque.push_back()`** method adds an element to the end of the `deque`.
```suggestion
The **`.push_back()`** method adds an element to the end of the `deque`.
```

2024-10-03 11:43 UTC, mamtawardhani commented on content/cpp/concepts/deque/terms/push_back/push_back.md
> +
```suggestion

- `value`: The element to be added to the back of the deque. It can be of any data type that the deque holds.

```

2024-10-03 11:43 UTC, mamtawardhani commented on content/cpp/concepts/deque/terms/push_back/push_back.md
> +
The parameter needs to be described, you can change the description, this is just for example

2024-10-03 11:43 UTC, mamtawardhani commented on content/cpp/concepts/deque/terms/push_back/push_back.md
> +
Also add an ## Example block here, which will have an example showcasing the term followed by an output block ```shell```

2024-10-03 12:42 UTC, Cibiyanna26 commented
@mamtawardhani I will look into the changes requested and will you notify you as soon as I complete. If I have any query I will reach out to you, Thanks.

2024-10-03 15:09 UTC, mamtawardhani commented
> @mamtawardhani I will look into the changes requested and will you notify you as soon as I complete. If I have any query I will reach out to you, Thanks.

sure thing! Also regarding your hacktober fest query - we will be pushing some issues today on the docs, which will be for hacktober fest, feel free to contribute! 😄

2024-10-03 19:32 UTC, Cibiyanna26 commented
@mamtawardhani I have made the modifications and updated the pr, check it out!

2024-10-04 07:05 UTC, mamtawardhani approved these changes
Thank you for contributing @Cibiyanna26 😄 

The entry looks good for a second round of review! 🚀

2024-10-14 15:28 UTC, Sriparno08 approved these changes
Looks good, @Cibiyanna26!

2024-10-14 15:29 UTC, merged