Creation of cat.md for pytorch
Codecademy/docs pull request #5405
Opened 2024-10-05 10:50 UTC by arisdelacruz

### Description

This is an attempt to create the .cat() entry for PyTorch. This aims to provide additional information to the body of knowledge on the topic.

### Issue Solved

Closes #5350 

### Type of Change

- Adding a new entry

### Checklist

- [/] All writings are my own.
- [/] My entry follows the Codecademy Docs style guide.
- [/] My changes generate no new warnings.
- [/] I have performed a self-review of my own writing and code.
- [/] I have checked my entry and corrected any misspellings.
- [/] I have made corresponding changes to the documentation if needed.
- [/] I have confirmed my changes are not being pushed from my forked `main` branch.
- [/] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [/] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-10-05 10:55 UTC, arisdelacruz commented
@mamtawardhani 

I think I got it right. Thanks

2024-10-05 12:07 UTC, mamtawardhani requested changes
Hey @arisdelacruz thank you for contributing to Codecademy Docs! The entry is very well written! 😄 

I've suggested some minor changes, could you please review and modify those at your earliest convenience? Thank you! 😃

2024-10-05 12:07 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/cat/cat.md
> +torch.cat(tensors, dim=0)
Can we also mention the out parameter here? I think it would be helpful. Example:

torch.cat(tensors, dim=0, out=None)

2024-10-05 12:07 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/cat/cat.md
> +- **dim** (int) – The dimension along which the tensors are concatenated.
```suggestion
- `tensors`: A sequence of tensors to be concatenated. All tensors must have the same shape in all dimensions except for the specified dimension.
- `dim`: An integer specifying the dimension along which the tensors will be concatenated. The default value is 0, which means concatenation will occur along the first dimension.
```

2024-10-05 12:07 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/cat/cat.md
> +- **dim** (int) – The dimension along which the tensors are concatenated.
if you add the `out` in syntax, please do add it here as well :)

2024-10-05 12:07 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/cat/cat.md
> +## Example
```suggestion
## Example 1
```

2024-10-05 12:07 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/cat/cat.md
> +## 1. Concatenating tensors along the first dimension
```suggestion
The example below showcases concatenating tensors along the first dimension using the `.cat()` function:
```

2024-10-05 12:07 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/cat/cat.md
> +## 2. Concatenating tensors along the second dimension
```suggestion
## Example 2

The example below showcases concatenating tensors along the second dimension using the `.cat()` function:
```

2024-10-05 12:07 UTC, mamtawardhani commented on content/pytorch/concepts/tensors/terms/cat/cat.md
> +## 3. Concatenating tensors along the third dimension
```suggestion
## Example 3

The example below showcases concatenating tensors along the third dimension using the `.cat()` function:
```

2024-10-05 12:51 UTC, arisdelacruz commented
done, @mamtawardhani 

thanks

2024-10-07 11:40 UTC, mamtawardhani approved these changes
Thank you for the modifications @arisdelacruz 😄 

The entry looks good for a second round of review 🚀

2024-11-15 09:55 UTC, Radhika-okhade approved these changes
Thank you for contributing to Codecademy docs. The entry looks good to be merged.

2024-11-15 09:59 UTC, merged