update: built-in-functions.md
Codecademy/docs pull request #5436
Opened 2024-10-09 06:14 UTC by rrayhka

### Description
I changed python's built-in function definitions and added usage examples

### Issue Solved
#5386 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-10-14 03:01 UTC, cigar-galaxy82 requested changes

2024-10-14 03:01 UTC, cigar-galaxy82 commented on content/python/concepts/built-in-functions/built-in-functions.md
> +
Only give 1 blank line after the para so remove 2 blank lines

2024-10-14 03:02 UTC, cigar-galaxy82 commented
Hi @rrayhka thank you for contributing to Codecademy docs, I have suggested a few changes please modify them.

2024-10-14 03:05 UTC, rrayhka commented
> Hi @rrayhka thank you for contributing to Codecademy docs, I have suggested a few changes please modify them.

okay, wait a sec

2024-10-14 03:22 UTC, rrayhka commented
@cigar-galaxy82  done man

2024-10-20 15:37 UTC, cigar-galaxy82 approved these changes

2024-10-21 10:02 UTC, mamtawardhani approved these changes
Thank you for contributing to Codecademy Docs @rrayhka 😄 

The entry is ready to be merged! 🚀

2024-10-21 10:03 UTC, merged