Summarized the description of JS Modules
Codecademy/docs pull request #5459
Opened 2024-10-13 11:01 UTC by RashmitTopG

### Description

### Issue Solved

Sumamrized the description of JS Modules.

### Type of Change

- Editing an existing entry (fixed typos)
- Updating the documentation

### Checklist

- [✓] All writings are my own.
- [✓] My entry follows the Codecademy Docs style guide.
- [✓] My changes generate no new warnings.
- [✓] I have performed a self-review of my own writing and code.
- [✓] I have checked my entry and corrected any misspellings.
- [✓] I have made corresponding changes to the documentation if needed.
- [✓] I have confirmed my changes are not being pushed from my forked `main` branch.
- [✓] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [✓] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-10-14 16:27 UTC, RashmitTopG commented
Can you please check the PR.

2024-10-17 07:49 UTC, cigar-galaxy82 requested changes

2024-10-17 07:49 UTC, cigar-galaxy82 commented on content/javascript/concepts/modules/modules.md
> +When exporting from module.js, new names (newName1, newName2) are assigned to functions. The new names must be used when importing and referencing them.
```suggestion
When exporting from module.js, new names (`newName1`, `newName2`) are assigned to functions, the new names must be used when importing and referencing them.
```

2024-10-17 07:49 UTC, cigar-galaxy82 commented on content/javascript/concepts/modules/modules.md
> +Suppose a file named **greetPerson.js** contains the following code:
```suggestion
Suppose a file named `greetPerson.js` contains the following code:
```

2024-10-17 07:49 UTC, cigar-galaxy82 commented
Hi @RashmitTopG thank you for contributing to Codecademy docs, I have suggested a few changes please modify them.

2024-10-17 11:01 UTC, RashmitTopG commented
@cigar-galaxy82 can you please review them hope this commit solves the issue.

2024-10-17 13:39 UTC, cigar-galaxy82 approved these changes

2024-10-18 09:56 UTC, mamtawardhani approved these changes
Thank you for contributing @RashmitTopG 😄 

The entry is ready to be merged 🚀

2024-10-18 09:58 UTC, merged