shortened description for pointers.md
Codecademy/docs pull request #5511
Opened 2024-10-17 10:13 UTC by raym293

### Description

### Issue Solved
#5488 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-10-17 10:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5511) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5511) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5511) it.</sub>

2024-10-23 12:38 UTC, cigar-galaxy82 commented
Hi @raym293 I see that the description is still above 160 characters please shorten that too

2024-10-23 13:10 UTC, cigar-galaxy82 requested changes
Hi please change the description too

2024-10-28 10:04 UTC, mamtawardhani commented
Hey @raym293 can you please also shorten the description at your earliest convenience?

2024-10-28 11:42 UTC, closed without merging