Added sticky position term to CSS concepts
Codecademy/docs pull request #5519
Opened 2024-10-18 05:08 UTC by melan-variya

### Description

Added a new entry about how the `position: sticky` property works in CSS. Edited the `position.md` file and added more examples to improve the documentation.

### Issue Solved

closses #5448 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-11-16 05:36 UTC, PragatiVerma18 requested changes
Hey @melan-variya, thanks for the contribution, I have reviewed it and have some suggestions. Please have a look and do the required changes, and let me know if you have any questions or need my help.

2024-11-18 19:54 UTC, PragatiVerma18 commented on content/css/concepts/position/terms/sticky/sticky.md
> +## Example 1
Since there is only one example, we can simply use the heading `Example`.

```suggestion
## Example
```

2024-11-18 19:56 UTC, PragatiVerma18 approved these changes
The PR looks good for a second review!

2024-11-20 10:55 UTC, Radhika-okhade commented on content/css/concepts/position/terms/sticky/sticky.md
> +  - 'Web Design'
```suggestion
  - 'Web Design'
  - 'Web Development'
```

2024-11-20 10:55 UTC, Radhika-okhade commented on content/css/concepts/position/terms/sticky/sticky.md
> +  - 'CSS'
```suggestion
  - 'CSS '
  - 'Positioning'
```

2024-11-20 10:58 UTC, Radhika-okhade commented on content/css/concepts/position/terms/sticky/sticky.md
> +  - 'paths/full-stack-engineer-career-path'
```suggestion
  - 'learn-css'
  - 'paths/front-end-engineer-career-path'
```

2024-11-20 16:18 UTC, Radhika-okhade commented on content/css/concepts/position/terms/sticky/sticky.md
> +> **Note:**  To ensure `position:sticky` works, the containing block must have a defined height, and the sticky element should not be covered by other positioned elements.
```suggestion
> **Note:**  To ensure `position: sticky` works, the containing block must have a defined height, and the sticky element should not be covered by other positioned elements.
```

2024-11-20 16:19 UTC, Radhika-okhade commented on content/css/concepts/position/terms/sticky/sticky.md
> +Make the `.header` element sticky, so it remains visible at the top when scrolling past it.
```suggestion
Make the `.header` element sticky so it remains visible at the top when scrolling past it.
```

2024-11-20 16:24 UTC, Radhika-okhade commented on content/css/concepts/position/terms/sticky/sticky.md
> +Sticky Position in CSS allows an element to toggle between relative and fixed positioning based on the user's scroll position. It's commonly used to keep certain elements, such as headers or navigati
Rewrite according to Codecademy style
```suggestion
Sticky Position in CSS allows an element to toggle between relative and fixed positioning based on the person's scroll position. It commonly keeps certain elements, such as headers or navigation menus, in view when scrolling through content.
```

2024-11-20 16:24 UTC, Radhika-okhade commented on content/css/concepts/position/terms/sticky/sticky.md
> +```
```suggestion
```

```

2024-11-20 16:26 UTC, Radhika-okhade commented on content/css/concepts/position/terms/sticky/sticky.md
> +```css
```suggestion
```pseudo
```

2024-11-20 16:28 UTC, Radhika-okhade commented on content/css/concepts/position/terms/sticky/sticky.md
> +position: sticky;
```suggestion
position: sticky;
```

```

2024-11-20 16:58 UTC, Radhika-okhade approved these changes
Thank you for contributing to Codecademy Docs. The entry looks good to be merged.

2024-11-21 05:30 UTC, merged