Added count for Cpp
Codecademy/docs pull request #5525
Opened 2024-10-18 19:57 UTC by RashmitTopG

### Description

Added term entry for cpp.count()

### Issue Solved

Added a new term entry for cpp.count() in unordered_map

### Type of Change

- Adding a new entry

### Checklist

- [✓] All writings are my own.
- [✓] My entry follows the Codecademy Docs style guide.
- [✓] My changes generate no new warnings.
- [✓] I have performed a self-review of my own writing and code.
- [✓] I have checked my entry and corrected any misspellings.
- [✓] I have made corresponding changes to the documentation if needed.
- [✓] I have confirmed my changes are not being pushed from my forked `main` branch.
- [✓] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [✓] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-10-20 19:32 UTC, RashmitTopG commented
@cigar-galaxy82 can you review this PR ??

2024-10-21 20:14 UTC, cigar-galaxy82 requested changes

2024-10-21 20:14 UTC, cigar-galaxy82 commented on content/cpp/concepts/unordered-map/terms/count/count.md
> +## Codebyte Example 2
```suggestion
## Codebyte Example
```

2024-10-21 20:14 UTC, cigar-galaxy82 commented on content/cpp/concepts/unordered-map/terms/count/count.md
> +The following codebyte example demonstrates the use of the .count() method with an unordered_map to check for the presence of various fruits and their prices:
```suggestion
The following codebyte example demonstrates the use of the `.count()` method with an unordered map to check for the presence of various fruits and their prices:
```

2024-10-21 20:15 UTC, cigar-galaxy82 commented
Hi @RashmitTopG thank you for contributing to Codecademy docs, I have suggested a few changes please modify them.

2024-10-28 12:50 UTC, mamtawardhani approved these changes
Thank you for making the required changes and contributing to Codecademy Docs @RashmitTopG 😄 

The entry looks good for a second round of review! 🚀

2024-11-07 10:26 UTC, Radhika-okhade commented on content/cpp/concepts/unordered-map/terms/count/count.md
> +  - 'Classes'
```suggestion
  - 'Classes'
  - 'Objects'
  - 'OOP'
```

2024-11-07 10:36 UTC, Radhika-okhade commented on content/cpp/concepts/unordered-map/terms/count/count.md
> +The code above produces the output as follows:
```suggestion
This example results in the following output:
```

2024-11-08 07:31 UTC, Radhika-okhade approved these changes

2024-11-08 14:28 UTC, merged