[Term Entry] PyTorch Tensor Operations .hstack()
Codecademy/docs pull request #5528
Opened 2024-10-19 11:13 UTC by clonymontana

### Description

-Added the  .hstack() function term under PyTorch
-Closes Issues #5468 

### Issue Solved

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-10-19 11:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5528) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5528) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5528) it.</sub>

2024-10-19 12:36 UTC, mamtawardhani requested changes
Hey @clonymontana thank you for contributing to Codecademy Docs 😄 

I've suggested some changes, could you please review and modify those at your earliest convenience? Thank you! 🚀

2024-10-19 12:36 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/hstack/hstack.md
> +---
```suggestion
---
Title: '.hstack()'
Description: 'Concatenates two or more tensors along the horizontal axis (column-wise)'
Subjects:
  - 'AI'
  - 'Data Science'
Tags:
  - 'AI'
  - 'Data Types'
  - 'Deep Learning'
  - 'Functions'
CatalogContent:
  - 'intro-to-py-torch-and-neural-networks'
  - 'paths/data-science'
---
```

2024-10-19 12:36 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/hstack/hstack.md
> +---
description should start with a verb

2024-10-19 12:36 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/hstack/hstack.md
> +In PyTorch, **`.hastack()`** (short for horizontal stack)is a function used to concatenate two or more tensors along the horizontal axis (axis1). This operation is useful for combining data with the
```suggestion
In PyTorch, **`.hstack()`** (short for horizontal stack) is a function used to concatenate two or more tensors along the horizontal axis (`axis=1`). This operation is helpful in combining data with the same number of rows but differing in the number of columns. It acts similarly to NumPy's `np.hstack()` and is particularly handy for data that needs to be concatenated side by side before being fed into a model for training or inference.
```

2024-10-19 12:36 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/hstack/hstack.md
> +In PyTorch, **`.hastack()`** (short for horizontal stack)is a function used to concatenate two or more tensors along the horizontal axis (axis1). This operation is useful for combining data with the
fixed spelling mistakes and reframed the sentence a bit

2024-10-19 12:36 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/hstack/hstack.md
> +```python
```suggestion
```pseudo
```

2024-10-19 12:36 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/hstack/hstack.md
> +```python
syntax is to be wrapped in the ```pseudo``` block

2024-10-19 12:36 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/hstack/hstack.md
> + - `tensors` is a sequence of tesors with the same numbers of rows.
```suggestion
 - `tensors`: A sequence of tensors with the same number of rows. All tensors must have the same number of dimensions and the same size in all dimensions except for the dimension corresponding to the horizontal stacking.

2024-10-19 12:36 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/hstack/hstack.md
> + - `tensors` is a sequence of tesors with the same numbers of rows.
Can be elaborated

2024-10-19 12:36 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/hstack/hstack.md
> + - The function returns a new tensor containing the horizontal concatenation of the imput tensors.
```suggestion
The function returns a new tensor containing the horizontal concatenation of the input tensors.
```

2024-10-19 12:36 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/hstack/hstack.md
> + - The function returns a new tensor containing the horizontal concatenation of the imput tensors.
No bullet point needed as it is not a parameter

2024-10-19 12:36 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/hstack/hstack.md
> +c = toarch.hstack((a, b))
```suggestion
c = torch.hstack((a, b))
```

2024-10-19 12:36 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/hstack/hstack.md
> +Here's simple example demonstrating how '.hstack()' can be used to concatenate tensors:
```suggestion
Here's an example demonstrating how `.hstack()` can be used to concatenate tensors:
```

2024-10-19 12:36 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/hstack/hstack.md
> +
This can be removed since the Codecademy Compiler does not have PyTorch dependencies yet.

2024-10-21 10:46 UTC, mamtawardhani approved these changes
Thank you for contributing to Codecademy Docs @clonymontana 😄 

The entry looks good for a second round of review! 🚀

2024-11-02 11:34 UTC, Sriparno08 approved these changes
Looks good, @clonymontana!

2024-11-02 11:35 UTC, merged