[Term entry] Python:Numpy Math Function: .hypot()
Codecademy/docs pull request #5550
Opened 2024-10-22 22:24 UTC by JMhuautla

### Description

- Added the hypot() term to Python:Numpy math-methods
- Closes issue #5235 

### Type of Change

- Adding a new entry

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-10-22 22:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5550) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5550) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5550) it.</sub>

2024-10-28 06:14 UTC, mamtawardhani commented
Hey @JMhuautla looks like the entry is empty, can you please check it on your local device and push the content?

2024-11-07 09:15 UTC, mamtawardhani requested changes
Hey @JMhuautla, thank you for contributing to Codecademy Docs, the entry is nicely written! 😄 

I've suggested a few changes, could you please review and modify those at your earliest convenience? Thank you! 😃

2024-11-07 09:15 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/hypot/hypot.md
> +Description: 'Returns the hypotenuse, given the "legs" of a triangle or triangles.'
```suggestion
Description: 'Returns the hypotenuse of a right triangle, given the "legs".'

```

2024-11-07 09:15 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/hypot/hypot.md
> +In [Numpy](https://www.codecademy.com/resources/docs/numpy), given the "legs" of a right triangle, the **`.hypot`** function returns the hypotenuse.
```suggestion
In [Numpy](https://www.codecademy.com/resources/docs/numpy), given the "legs" of a right triangle, the **`.hypot()`** function returns the hypotenuse.
```

2024-11-07 09:15 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/hypot/hypot.md
> +- `where`: An array-like optional parameter that determines the elements on which the method is to be applied. At locations where the condition is True, the _out_ array will be set to the ufunc resul
```suggestion
- `x1`, `x2`: These are the "legs" of the triangle(s). If the shapes of `x1` and `x2` are not identical, they must be broadcastable to a common shape.
- `out` (Optional): This parameter specifies an array where the result will be stored. The shape of `out` must match the shape of the output. If not provided, a new array will be allocated for the result.
- `where` (Optional): An optional condition that can be applied element-wise on the input arrays. The result will only be computed where the condition is `True`. If the condition is `False` for an element, that element’s result will be ignored.
```

2024-11-07 09:15 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/hypot/hypot.md
> +- `where`: An array-like optional parameter that determines the elements on which the method is to be applied. At locations where the condition is True, the _out_ array will be set to the ufunc resul
reframed for better readability

2024-11-07 09:15 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/hypot/hypot.md
> +The below example calculates the hypotenuse of one right triangle.
```suggestion
The below example calculates the hypotenuse of one right triangle:
```

2024-11-07 09:15 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/hypot/hypot.md
> +The code above generates  the following output:
```suggestion
The code above generates the following output:

```

2024-11-07 09:15 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/hypot/hypot.md
> +If the first leg is 3 and the second is 4, the hypotenuse is 5
```suggestion
If the first leg is 3 and the second is 4, the hypotenuse is  5.0
```

2024-11-07 09:15 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/hypot/hypot.md
> +The below example calculates the hypotenuses of 3 right triangles
```suggestion
The following example calculates the hypotenuses of three right triangles:
```

2024-11-07 09:15 UTC, mamtawardhani commented on content/numpy/concepts/math-methods/terms/hypot/hypot.md
> +In this codebyte, `hypot()` computes the hypotenuses for two triangles. The first one has legs of 2 and 3, and the second one legs of 8 and 15.
```suggestion
In this codebyte, `.hypot()` computes the hypotenuses for two triangles. The first triangle has legs of *2* and *3*, and the second triangle has legs of *8* and *15*.
```

2024-11-12 11:16 UTC, mamtawardhani approved these changes
Thank you for making the changes @JMhuautla 😄 

The entry looks good for a second round of review 🚀

2024-11-14 07:25 UTC, PragatiVerma18 commented on content/numpy/concepts/math-methods/terms/hypot/hypot.md
> +Description: 'Returns the hypotenuse of a right triangle, given the "legs".'
According to the [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), we should not use apostrophes or quotes in Title: or Description:.

```suggestion
Description: 'Returns the hypotenuse of a right triangle, given the legs.'
```

2024-11-14 08:05 UTC, PragatiVerma18 requested changes
Hey @JMhuautla, the entry looks good, I have some suggestions, please go through them and make the required changes. Do let me know if you have any questions. Thanks.

2024-11-14 08:05 UTC, PragatiVerma18 commented on content/numpy/concepts/math-methods/terms/hypot/hypot.md
> +```
We should use more relatable comments and variable names to make the code example easier to understand -

```suggestion
import numpy as np

# Creating the sides of three triangles
triangle_leg1 = [3,5,6]  # First leg of each triangle
triangle_leg2 = [4,12,8]  # Second leg of each triangle

# Computing the hypotenuses
hypotenuses = np.hypot(array1, array2)

print("Calculated hypotenuses:", hypotenuses)
print("\nThe hypotenuses are {}, {} and {}, respectively.".format(hypotenuses[0], hypotenuses[1], hypotenuses[2]))
```

```

2024-11-14 08:05 UTC, PragatiVerma18 commented on content/numpy/concepts/math-methods/terms/hypot/hypot.md
> +The hypotenuses are 5.0, 13.0 and 10.0, respectively.
Based on above code changes, output will also change as following - 

```suggestion
Calculated hypotenuses: [ 5. 13. 10.]

The hypotenuses are 5.0, 13.0 and 10.0, respectively.

```

2024-11-14 08:05 UTC, PragatiVerma18 commented on content/numpy/concepts/math-methods/terms/hypot/hypot.md
> +print(result)
Similar suggestions as above example - we should use more descriptive/relatable variable names and comments for more clarity.

```suggestion
import numpy as np

first_leg = [2, 8]  # First leg of each triangle
second_leg = [3, 15]  # Second leg of each triangle

# Calculate the hypotenuses for each triangle
hypotenuses = np.hypot(first_leg, second_leg)

print("The calculated hypotenuses are:", hypotenuses)
```

2024-11-16 06:36 UTC, PragatiVerma18 approved these changes

2024-11-16 06:56 UTC, merged