New entry mutable variables
Codecademy/docs pull request #5555
Opened 2024-10-25 18:45 UTC by braanj

### Description

Add new concept entry term for cpp mutable variables.

### Issue Solved

#5473 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-10-25 18:47 UTC, braanj commented
Hey @codecademy-docs please review

2024-10-28 18:05 UTC, braanj commented
Hey @Sriparno08 please review

2024-10-29 05:18 UTC, Sriparno08 commented
Hey @braanj, I'll review this by the end of the week.

2024-11-01 14:43 UTC, Sriparno08 requested changes
Hey @braanj, thank you for contributing to Codecademy Docs!

I've listed all the modifications that you need to make in your entry below:

2024-11-01 14:43 UTC, Sriparno08 commented on content/cpp/concepts/variables/terms/mutable-variables/mutable-variables.md
> +---
Modifications:

- Let's write the title in title case
- Let's change the description a bit
- Let's add some more tags

```suggestion
---
Title: 'Mutable Variables'
Description: 'Mutable variables are variables that can be modified even within constant functions.'
Subjects:
  - 'Computer Science'
  - 'Game Development'
Tags:
  - 'Functions'
  - 'Values'
  - 'Variable Types'
  - 'Variables'
CatalogContent:
  - 'learn-c-plus-plus'
  - 'paths/computer-science'
---
```

2024-11-01 14:43 UTC, Sriparno08 commented on content/cpp/concepts/variables/terms/mutable-variables/mutable-variables.md
> +In C++, the `mutable` keyword in C++ allows certain class variables to be modified even within const functions, useful for managing internal state flexibly.
Let's make some minor changes:

```suggestion
In C++, mutable variables are variables that can be modified even within constant functions, useful for managing internal state flexibly.
```

2024-11-01 14:43 UTC, Sriparno08 commented on content/cpp/concepts/variables/terms/mutable-variables/mutable-variables.md
> +To declare a variable as `mutable`, simply place the `mutable` keyword before the variable type:
Let's make some minor changes:

```suggestion
To declare a variable as mutable, the `mutable` keyword needs to be placed before the variable type:
```

2024-11-01 14:43 UTC, Sriparno08 commented on content/cpp/concepts/variables/terms/mutable-variables/mutable-variables.md
> +- **name** - The name of the variable.
Let's make some minor changes:

```suggestion
- `type`: The type of the variable (e.g., `int`, `char`).
- `name`: The name of the variable.
```

2024-11-01 14:43 UTC, Sriparno08 commented on content/cpp/concepts/variables/terms/mutable-variables/mutable-variables.md
> +In the example below, `accessCount` is marked `mutable`, allowing it to be modified within the const `displayData` function:
Let's make some minor changes:

```suggestion
In the example below, `accessCount` is marked `mutable`, allowing it to be modified within the constant `displayData()` function:
```

2024-11-01 14:43 UTC, Sriparno08 commented on content/cpp/concepts/variables/terms/mutable-variables/mutable-variables.md
> +```
Let's change the indentation to 2 spaces and make some minor changes:

````suggestion
```cpp
#include <iostream>
#include <string>

class Data {
public:
  Data(std::string value) : data(value), accessCount(0) {}
  
  void displayData() const {
    ++accessCount; // Modification allowed due to 'mutable'
    std::cout << "Data: " << data << ", Access count: " << accessCount << std::endl;
  }

private:
  std::string data;
  mutable int accessCount; // Can be modified in constant methods
};

int main() {
  Data d("Sample");
  d.displayData();
  d.displayData();
  return 0;
}
```
````

2024-11-01 14:43 UTC, Sriparno08 commented on content/cpp/concepts/variables/terms/mutable-variables/mutable-variables.md
> +```
Let's add a sentence to introduce the output:

````suggestion
The above code produces the following output:

```shell
Data: Sample, Access count: 1
Data: Sample, Access count: 2
```
````

2024-11-01 14:43 UTC, Sriparno08 commented on content/cpp/concepts/variables/terms/mutable-variables/mutable-variables.md
> +Here, even though `displayData` is a const member function, `accessCount` can be incremented due to its `mutable` declaration.
Let's make some minor changes:

```suggestion
Here, even though `displayData()` is a constant member function, `accessCount` can be incremented due to its `mutable` declaration.
```

2024-11-01 14:43 UTC, Sriparno08 commented on content/cpp/concepts/variables/terms/mutable-variables/mutable-variables.md
> +Use this example to experiment with mutable variables in C++. Enjoy coding!
Let's change the sentence:

```suggestion
The following codebyte example demonstrates the usage of mutable variables:
```

2024-11-01 14:43 UTC, Sriparno08 commented on content/cpp/concepts/variables/terms/mutable-variables/mutable-variables.md
> +```
Let's change the indentation to 2 spaces and make some minor changes:

````suggestion
```codebyte/cpp
#include <iostream>

class Counter {
public:
  Counter() : count(0) {}
  
  void increment() const {
    ++count;  // 'count' is mutable, so this modification is allowed in this constant method
  }
  
  int getCount() const {
    return count;
  }

private:
  mutable int count;
};

int main() {
  Counter counter;
  counter.increment();
  counter.increment();
  std::cout << "Count: " << counter.getCount() << std::endl;
  return 0;
}
```
````

2024-11-09 08:25 UTC, Sriparno08 approved these changes
Hey @braanj, this entry looks good for a second round of review!

2024-11-15 07:27 UTC, mamtawardhani approved these changes
Thank you for contributing to Codecademy Docs @braanj 😄 

The entry looks good for a second round of review! 🚀

2024-11-15 07:29 UTC, merged