Feat: [Term Entry] C# Strings .PadLeft()
Codecademy/docs pull request #5590
Opened 2024-11-03 12:13 UTC by SaiTeja-002

### Description

I've added a new entry for C# string methods - `.PadLeft()`. This entry can be found at `content/c-sharp/concepts/strings/terms/padleft/padleft.md`.

### Issue Solved

closes #5567 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-11-03 15:54 UTC, mamtawardhani requested changes
Hey @SaiTeja-002 Please also add a ## Codebyte Example block at the end.

2024-11-06 11:07 UTC, mamtawardhani requested changes
Please change the codebyte example block, since that is quite similar to the example block.

2024-11-06 11:07 UTC, mamtawardhani commented on content/c-sharp/concepts/strings/terms/padleft/padleft.md
> +```
Hey @SaiTeja-002 can we change the string here? As it is similar to the example block above

2024-11-09 07:44 UTC, mamtawardhani approved these changes
Hey @SaiTeja-002 thank you for contributing to Codecademy Docs! 😄 

The entry looks good for a second round of review! 🚀

2024-11-16 07:34 UTC, Sriparno08 approved these changes
Looks good, @SaiTeja-002!

2024-11-16 07:35 UTC, merged