Added Term Entry for Python Built-in Function `range()`
Codecademy/docs pull request #561
Opened 2022-02-18 05:41 UTC by denisCabrera

### Description

Added new term entry for python `.range()` built-in function

- Added syntax and example sections with code snippets.
- Added at least one `codebyte/py`

Closes #557 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

2022-02-18 19:18 UTC, denisCabrera commented
Hi,

I am relatively new to contributing. I am curious about the check that failed and where to go from here. Would love any feedback.

Thank you.

2022-02-18 19:47 UTC, denisCabrera commented
@SSwiniarski  Yes

2022-02-18 19:55 UTC, SSwiniarski requested changes
@denisCabrera, I've left my comments on your PR.

2022-02-18 19:55 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/range/range.md
> +```python
```suggestion
```pseudo
```

2022-02-18 19:55 UTC, SSwiniarski commented on content/html/concepts/tags/terms/picture/picture.md
> +Another use case is **Page Load Time Optimization**. In situations when certain images take longer to load, having an alternative image that loads faster improves the page load time.
This file should be deleted as I think it's in this PR by mistake.

2022-02-18 19:55 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/range/range.md
> +Here the range is set to `stop` before 5.
```suggestion
Here the range is set to stop before 5.
```

2022-02-18 19:55 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/range/range.md
> +Here the range is set to `start` at 5 and `stop` before 11.
```suggestion
Here the range is set to start at 5 and stop before 11.
```

2022-02-18 19:55 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/range/range.md
> +Here the range is set to `start` at 10, `stop` before 60, and `step` or increment by 10.
```suggestion
Here the range is set to start at 10, stop before 60, and increment by 10.
```

2022-02-18 19:55 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/range/range.md
> +print(list(z))
```suggestion
print(list(z))

# Output: [10,20,30,40,50]
```

2022-02-18 20:13 UTC, denisCabrera commented
@SSwiniarski  I have finished committing the suggested changes. Thank you for the feedback. Let me know if there is anything else to do.

2022-02-18 20:24 UTC, SSwiniarski approved these changes
@denisCabrera, looks good for a second review.

2022-02-20 15:09 UTC, Dusch4593 commented
Hey @denisCabrera! I'll take a look at your contribution next and tag you once I'm finished with leaving some comments/suggestions. 😄

2022-02-20 15:12 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/range/range.md
> +## Example 1
```suggestion
## Example
```

2022-02-20 15:14 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/range/range.md
> +
```suggestion

```

I think examples #1 and #2 should be consolidated as one example section with two code snippets (a Python ```py and regular output ```)l

2022-02-20 15:18 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/range/range.md
> +## Example 3
```suggestion
## Codebyte Example
```

2022-02-20 15:20 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/range/range.md
> +Here the range is set to start at 10, stop before 60, and increment by 10.
```suggestion
In the example below, the range is set to 10 and increments by 10, stopping before 60:
```

2022-02-20 15:21 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/range/range.md
> +`range(start, stop, step)`
```suggestion

```

I don't think there is a need to restate the syntax here.

2022-02-20 15:24 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/range/range.md
> +# Output: [10,20,30,40,50]
```suggestion
```

Since this a codebyte snippet, the output will be displayed when the code is run.

2022-02-20 15:26 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/range/range.md
> +- `stop` (required) specifies where to stop. Range ends at `stop - 1`.
```suggestion
- `stop` (required): specifies where the range will stop, ending at `stop - 1` due to zero-indexing.
```

2022-02-20 15:29 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/range/range.md
> +range(start, stop, step)
```suggestion
range(start = 0, stop, step = 1)
```

2022-02-20 15:30 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/range/range.md
> +range(start, stop)
```suggestion
range(start = 0, stop)
```

2022-02-20 15:30 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/range/range.md
> +range(start, stop, step)
Just to further define the default values of some of the arguments of `range()`.

2022-02-20 15:31 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/range/range.md
> +- `step` (optional) specifies incrementation. Default is 1.
```suggestion
- `start` (optional): specifies where the range will start, defaulting at 0.
- `step` (optional): specifies how many steps the range will increment be reaching the end, defaulting to 1.
```

2022-02-20 15:32 UTC, Dusch4593 commented
@denisCabrera Finished with my comments/suggestions! 😃 Take a look and tag one of us when you're finished resolving them and we can proceed onward.

2022-02-20 18:48 UTC, denisCabrera commented
@Dusch4593 Completed committing all the suggestions. Thank you so much for the feedback. Looking forward to more assignments.

2022-02-21 12:26 UTC, SSwiniarski commented
@denisCabrera, once the formatting issue is fixed we should be good to go.

2022-02-21 16:04 UTC, Dusch4593 approved these changes
@denisCabrera Awesome! Thank you for incorporating those changes 😃 This is gonna be a solid addition to our Python entries. 

We're good for this review, I think. I made a few recent commits that I wanted to fill you in on.

From 25d17acb4343ce338367678a31b97a009bda6e6c:

- Fixed the format errors. (All checks were passing after that)

From c35152181cedc877f15e4802a9fd6fc73778b5fb:

- I separated the shell output from the actual python code into two code snippets with a transition sentence in between. 
- I altered the `print()` statements to output text (intended to act as a label) for a given list range.

```py
print("x: ", list(x))
```

2022-02-21 16:09 UTC, Dusch4593 commented
Could we actually perform one more review before merging this PR? cc: @yangc95 @KTom101

2022-02-22 20:46 UTC, KTom101 reviewed
Here's another review! @Dusch4593, I'm tagging you because part of my suggestion is on a previous suggestion from you.

2022-02-22 20:46 UTC, KTom101 commented on content/python/concepts/built-in-functions/terms/range/range.md
> +Here, the range is set to stop before 5.
```suggestion
Here, two variables are created. One with the range set to stop before 5. The other is set to start at 5 and stop before 11. Both are converted to [lists](https://www.codecademy.com/resources/docs/python/lists) before being printed.
```

2022-02-22 21:27 UTC, Dusch4593 commented on content/python/concepts/built-in-functions/terms/range/range.md
> +- `step` (optional): specifies how many steps the range will increment be reaching the end, defaulting to 1.
Yes! This is much better! 😀

2022-02-22 21:35 UTC, KTom101 commented on content/python/concepts/built-in-functions/terms/range/range.md
> +- `step` (optional): specifies how many steps the range will increment be reaching the end, defaulting to 1.
Cool!

2022-02-25 19:57 UTC, denisCabrera commented
@KTom101 @Dusch4593 Hi guys, I have completed all the recent suggestions.

2022-02-25 22:08 UTC, Dusch4593 commented
Thanks @denisCabrera! This LGTM 👍 

How do we feel @KTom101 @yangc95 ?

2022-02-28 21:26 UTC, KTom101 commented
@Dusch4593 It looks good to me!

2022-02-28 22:01 UTC, KTom101 approved these changes

2022-02-28 22:03 UTC, Dusch4593 commented
@denisCabrera, this is about ready to be merged. I wanted to let you know about a change I just made in 2e5aae66b56cc796ff00b01cd5a1cf894080b4d6 where I changed the Codebyte signature from `codebyte/py` to `codebyte/python` (w/ the language spelled out, per a spec in [Codecademy's `client-modules` repo](https://github.com/Codecademy/client-modules/blob/main/packages/codebytes/src/consts.ts))

cc: @SSwiniarski @KTom101 @yangc95

2022-02-28 22:06 UTC, merged

2022-02-28 22:33 UTC, Dusch4593 commented
Congrats @denisCabrera the entry is now live on the Docs site! https://www.codecademy.com/resources/docs/python/built-in-functions/range

2022-02-28 22:36 UTC, denisCabrera commented
@Dusch4593  Sounds good to me. Thank you so much for the feedback. I learned a lot just from this single issue. I am looking forward to working together.