Added file on take()
Codecademy/docs pull request #5612
Opened 2024-11-11 12:45 UTC by Neema-Joju

### Description

Added a new entry file on .take(). Improving documentation and providing more context for the users to understand.

### Issue Solved

Closes #5598 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-11-13 12:38 UTC, mamtawardhani requested changes
Hey @Neema-Joju thank you for contributing to Codecademy Docs! 😄 

I've suggested some modifications, could you please review and make those changes at your earliest convenience? Thank you! 😃

2024-11-13 12:38 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/take/take.md
> +Description: 'Returns a new tensor from a given tensor.'
```suggestion
Description: 'Returns a 1D tensor containing elements from input at the specified indices.'
```

2024-11-13 12:38 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/take/take.md
> +Description: 'Returns a new tensor from a given tensor.'
This can be elaborated

2024-11-13 12:38 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/take/take.md
> +The **.take()** function returns a tensor from the given tensor. The resulting tensor will always be a 1-D tensor irrespective of the size of the given tensor.
```suggestion
The **`.take()`** function returns a 1D tensor containing elements from the given tensor at the specified indices. The resulting tensor will always be a 1D tensor irrespective of the size of the given tensor. 
```

2024-11-13 12:38 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/take/take.md
> +-`index`: the position of the elements you want to extract.
```suggestion
-`input`: The input tensor from which the elements will be selected.
-`index`: A 1D tensor containing the indices of the elements to extract from `input`.
```

2024-11-13 12:38 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/take/take.md
> +The following example demonstrates the usuage of `.take()` method:
```suggestion
The following example demonstrates the usage of `.take()` function:
```

2024-11-13 12:38 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/take/take.md
> +torch.take(data, torch.take([0,2,5]))
```suggestion
import torch

# Define a tensor
data = torch.tensor([[4, 2, -1], [7, 8, 0]])

# Define indices as a tensor
indices = torch.tensor([0, 2, 5])

# Use torch.take with data and indices
result = torch.take(data, indices)

print(result)
```

2024-11-13 12:38 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/take/take.md
> +torch.take(data, torch.take([0,2,5]))
There is an error in the code due to a misuse of `torch.take()` in the `indices` argument. The correct code should use a tensor for the `indices` argument in `torch.take`, not calling `torch.take` again inside it.

2024-11-13 12:38 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/take/take.md
> +
```suggestion
```

2024-11-13 12:38 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/take/take.md
> +
This can be removed, we only need ## Example block for this entry

2024-11-13 12:38 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/take/take.md
> +-`index`: the position of the elements you want to extract.
We avoid using pronouns like "you" and "we"

2024-11-13 12:38 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/take/take.md
> +The following example demonstrates the usuage of `.take()` method:
Since we referred to as a 'function' earlier, let us stick to that

2024-11-13 12:38 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/take/take.md
> +```psuedo
```suggestion
```pseudo
```

2024-11-15 06:47 UTC, mamtawardhani approved these changes
Thank you for contributing to Codecademy Docs @Neema-Joju 😄 

The entry looks good for a second round of review! 🚀

2024-11-15 07:58 UTC, SaviDahegaonkar approved these changes
Hey @Neema-Joju, The entry is nicely written, it LGTM to get it merged. Thank you for contributing to Codecademy Docs :)

Thanks,
Savi

2024-11-15 08:00 UTC, merged

2024-11-15 08:04 UTC, Neema-Joju commented
@SaviDahegaonkar 
Is there any way to be listed as a contributor instead of anonymous? I have updated my profile with my github details. It didn't seem to work.