initial commit, messed up branch commits, deleted and created new
Codecademy/docs pull request #5617
Opened 2024-11-11 21:16 UTC by danitellini

### Description

Summary of Change:

Topic: Python Plotly `graph_object` `.mesh3d()` function
Files created: `docs/content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md`
Files added: `docs/media/mesh3d-example-result.png` and `docs/media/mesh3d-dataset-sphere.png`
Description: Created a new **Term Entry** for Python Plotly `graph_object` `.mesh3d()` function

Open issue, and a great way to practice and learn is to teach!

### Issue Solved

Closes #5178 

### Type of Change

- Adding a new entry
- ~Editing an existing entry (fixing a typo, bug, issues, etc)~
- ~Updating the documentation~

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-11-12 14:59 UTC, danitellini commented
@mamtawardhani I have no idea my last commit became the title of the pull request 🤕 This one has beat my head in for sure haha

2024-11-15 08:50 UTC, mamtawardhani requested changes
Hey @danitellini thank you for contributing to Codecademy Docs, the entry is nicely written! 😄 

I've suggested a few changes, could you please review and modify those at your earliest convenience? Thank you! 😃

2024-11-15 08:50 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +**`.Mesh3d()`** is a method in Plotly's `graph_objects` module that generates 3D mesh plots by defining vertices and connecting faces (triangles).
```suggestion
**`.Mesh3d()`** is a method in Plotly's [`graph_objects`](https://www.codecademy.com/resources/docs/plotly/graph-objects) module that generates 3D mesh plots by defining vertices and connecting them with faces (typically triangles).
```

2024-11-15 08:50 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +)
```suggestion
plotly.graph_objects.Mesh3d( x=None, y=None, z=None, i=None, j=None, k=None, color=None, opacity=None, ...)   
```

2024-11-15 08:50 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +- `opacity`: Sets the mesh transparency (0 to 1)
```suggestion
- `x`, `y`, `z`: Coordinates of the vertices in 3D space (arrays or lists).
- `i`, `j`, `k`: Indices that define the triangular faces, where each set of three indices corresponds to a triangle formed by the vertices defined by `x`, `y`, and `z`.
- `Color`: The color of the mesh, which can be a single color or an array of colors for each face.
- `opacity`: Controls the transparency of the mesh, ranging from 0 (fully transparent) to 1 (fully opaque).
```

2024-11-15 08:50 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +- `opacity`: Sets the mesh transparency (0 to 1)
reframed and added some details

2024-11-15 08:50 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +)
default values are `None` which should be mentioned

2024-11-15 08:50 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +> Note: If you don't specify the triangle indices, the mesh will automatically be generated using algorithms like Delaunay triangulation. You can also use the `alphahull` parameter to control the gen
```suggestion
> Note: If triangle indices (`i`, `j`, `k`) are not specified, the mesh will be automatically generated using algorithms like Delaunay triangulation. The `alphahull` parameter can be used to control the mesh generation process without the indices:
- `alphahull = -1`: Uses Delaunay triangulation.
- `alphahull = 0`: Computes the convex hull of the point set.
- `alphahull > 0`: Uses the alpha shape algorithm with the specified alpha value.
```

2024-11-15 08:50 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +> Note: If you don't specify the triangle indices, the mesh will automatically be generated using algorithms like Delaunay triangulation. You can also use the `alphahull` parameter to control the gen
We don't usually use you and we

2024-11-15 08:50 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +Dataset information can also be used to create the mesh. This visualizes a sphere by using vertex and face data from a CSV file:
```suggestion
 The dataset information can be used to create a 3D mesh plot, as demonstrated in the example below, which visualizes a sphere using vertex and face data from a CSV file:
```

2024-11-15 08:50 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +  - 'paths/data-science-foundations'
```suggestion
```

2024-11-15 08:50 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +  - 'paths/data-science-foundations'
Let us only have 2 paths

2024-11-20 11:55 UTC, mamtawardhani commented
Hey @danitellini are you still working on this?

2024-11-20 12:12 UTC, danitellini commented
Yes ma'am, I'll have the updates done later today. Work was heavy this week 😅

2024-11-20 16:56 UTC, mamtawardhani commented
> Yes ma'am, I'll have the updates done later today. Work was heavy this week 😅

No problemo, was just checking 😃

2024-11-20 22:35 UTC, danitellini commented
@mamtawardhani All set for next step!

2024-11-22 11:17 UTC, mamtawardhani approved these changes
Thank you for contributing to Codecademy Docs @danitellini 😄 

The entry looks good for a second round of review! 🚀

2024-11-23 12:18 UTC, PragatiVerma18 requested changes
Hey @danitellini, the entry looks mostly good to me, I just have a few suggestions, please have a look and do the required changes.

2024-11-23 12:18 UTC, PragatiVerma18 commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +- `alphahull > 0`: Uses the alpha shape algorithm with the specified alpha value.
The Delaunay triangulation explanation could be more informative here for a beginner.

Also, we should divide the text into smaller paragraphs to make it easy to follow.

```suggestion
If triangle indices (`i`, `j`, `k`) are not specified, the mesh will be automatically generated using algorithms like **Delaunay triangulation**.

_Delaunay triangulation_ is a method for dividing a set of points into non-overlapping triangles, ensuring that no points lie inside the circumcircle of any triangle. 

The `alphahull` parameter can be used to control the mesh generation process without the indices:
- `alphahull = -1`: Uses Delaunay triangulation.
- `alphahull = 0`: Computes the convex hull of the point set.
- `alphahull > 0`: Uses the alpha shape algorithm with the specified alpha value.
```

2024-11-23 12:18 UTC, PragatiVerma18 commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +![Example 2 Output]("https://raw.githubusercontent.com/Codecademy/docs/main/media/mesh3d-example-results.png")
The image description should be more descriptive.

```suggestion
![The output will be a 3D triangular pyramid (tetrahedron) visualized using Plotly.]("https://raw.githubusercontent.com/Codecademy/docs/main/media/mesh3d-example-results.png")
```

2024-11-23 12:18 UTC, PragatiVerma18 commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +![Example 2 Output]("https://raw.githubusercontent.com/Codecademy/docs/main/media/mesh3d-dataset-sphere.png")
The image description should be more descriptive.

```suggestion
![The output will be a 3D sphere.]("https://raw.githubusercontent.com/Codecademy/docs/main/media/mesh3d-dataset-sphere.png")
```

2024-11-23 12:18 UTC, PragatiVerma18 commented on content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
> +The dataset information can be used to create a 3D mesh plot, as demonstrated in the example below, which visualizes a sphere using vertex and face data from a CSV file:
We should mention the CSV file separately as well.

```suggestion
The dataset information can be used to create a 3D mesh plot, as demonstrated in the example below, which visualizes a sphere using vertex and face data from a [CSV file](https://raw.githubusercontent.com/plotly/datasets/master/ply/sphere-ply.csv):
```

2024-11-23 12:26 UTC, danitellini commented
All set! @PragatiVerma18

2024-11-23 12:33 UTC, PragatiVerma18 approved these changes
This looks good to go! 🚀

2024-11-23 12:34 UTC, merged