Edit c sharp comments.md
Codecademy/docs pull request #5625
Opened 2024-11-15 20:49 UTC by scardonacervantes

### Description

### Issue Solved

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-11-15 20:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5625) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5625) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5625) it.</sub>

2024-11-15 20:53 UTC, scardonacervantes commented
Did not touch XML comments section, as I believe they should have a separate entry.

2024-11-18 19:47 UTC, PragatiVerma18 requested changes
Hey @scardonacervantes, thanks for the contribution, I have some suggestions. Please check and do the required changes. Let me know if you have any questions.

2024-11-18 19:47 UTC, PragatiVerma18 commented on content/c-sharp/concepts/comments/comments.md
> +```
This is not really required, the above explanation already covers this. We should remove it.

2024-11-18 19:47 UTC, PragatiVerma18 commented on content/c-sharp/concepts/comments/comments.md
> +}
This example is too long, we should keep it simple as the existing example.

2024-11-18 19:47 UTC, PragatiVerma18 commented on content/c-sharp/concepts/comments/comments.md
> +### Syntax
Syntax should be kept as H2

```suggestion
## Syntax
```

2024-11-18 19:47 UTC, PragatiVerma18 commented on content/c-sharp/concepts/comments/comments.md
> +### Example
Example should also be kept as H2

```suggestion
## Example
```

2024-11-19 06:12 UTC, PragatiVerma18 commented
Hi @scardonacervantes, Thank you for your contribution! While we appreciate your effort, we aim to keep the docs concise, and some of these changes may not align with that goal. 

For now, I’ll close this PR, but we’d love to see more relevant suggestions in the future. Happy contributing!

2024-11-19 06:12 UTC, closed without merging