[Term Entry] PyTorch Tensor Operations .index_add() #5614
Codecademy/docs pull request #5626
Opened 2024-11-17 14:57 UTC by LilyS222

### Description

New term entry for the tensor operation `.index_add()` in Pytorch.

### Issue Solved

#5614

### Type of Change

- Adding a new entry

### Checklist

- ☑️ All writings are my own.
- ☑️ My entry follows the Codecademy Docs style guide.
- ☑️ My changes generate no new warnings.
- ☑️ I have performed a self-review of my own writing and code.
- ☑️ I have checked my entry and corrected any misspellings.
- ☑️ I have made corresponding changes to the documentation if needed.
- ☑️ I have confirmed my changes are not being pushed from my forked `main` branch.
- ☑️ I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- ☑️ I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-11-17 17:26 UTC, SaviDahegaonkar requested changes
Hey @LilyS222 ,
Thank you for Contributing to Docs :) I had a look at your file and suggested a few changes. Please make them asap.

Thanks,
Savi

2024-11-17 17:26 UTC, SaviDahegaonkar commented on content/pytorch/concepts/tensor-operations/terms/index-add/index-add.md
> +- `source`: The tensor containing values to add.
```suggestion
- `input`: The tensor to which values will be added.
- `dim`: The dimension along which to index and add.
- `index`: It is a 1-D tensor with the element indices to be added to.
- `source`: The tensor containing values to add.
- `alpha`: It is a scalar multiplier which is used before adding the source values. It is an optional parameter.
- `out` : If provided, the result will be written to this tensor. It is also an optional parameter.

```

2024-11-18 17:11 UTC, SaviDahegaonkar commented
Hey @LilyS222 ,
Thank You for your Contribution :) This entry looks good for a second round of review.

2024-11-18 17:13 UTC, SaviDahegaonkar approved these changes

2024-11-23 14:29 UTC, Sriparno08 approved these changes
Looks good, @LilyS222!

2024-11-23 14:30 UTC, merged