Create Python Entry for random.sample()
Codecademy/docs pull request #566
Opened 2022-02-19 15:12 UTC by SSwiniarski

### Description

Add entry for python/concepts/random-module/terms/sample

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

2022-02-19 15:13 UTC, SSwiniarski commented
Another orphan from original assignment sheet.

2022-02-22 23:37 UTC, KTom101 reviewed
@SSwiniarski Just completed my review for this entry.

2022-02-22 23:37 UTC, KTom101 commented on content/python/concepts/random-module/terms/sample/sample.md
> +The `random.sample()` method takes a population (list, range, set) and a number as arguments and returns a list consisting of that number of randomly selected, non-duplicated, items from the populati
```suggestion
The `random.sample()` method takes a population (list, range, set, or string) and a number as arguments. It returns a list with the specified number of items. Each item is randomly selected without duplication from the population.
```

2022-02-22 23:37 UTC, KTom101 commented on content/python/concepts/random-module/terms/sample/sample.md
> +Where `<population>` is the list (or range, or set) where items are being selected from, and `<number>` is the number of items selected to return.
```suggestion
Where `<population>` is the sequence the items are selected from, and `<number>` is the number of item(s) to be returned.
```

2022-02-25 17:01 UTC, SSwiniarski commented
@KTom101, I implemented your suggestions.

2022-02-28 21:18 UTC, Dusch4593 commented on content/python/concepts/random-module/terms/sample/sample.md
> +```codebyte/py
```suggestion
```codebyte/python
```

According to the `LanguageOptions` constants for codebytes in [Codecademy's `client-modules` repo](https://github.com/Codecademy/client-modules/blob/main/packages/codebytes/src/consts.ts) should be spelled out. This is also the case when commenting on [the discuss forums](https://discuss.codecademy.com/)

2022-02-28 21:19 UTC, Dusch4593 commented on content/python/concepts/random-module/terms/sample/sample.md
> +Description: 'Returns a given number of randomly selected items from a given population.'
```suggestion
Description: 'Returns a list of items randomly selected from a given population.'
```

2022-02-28 22:13 UTC, Dusch4593 requested changes
@SSwiniarski Done with my review and left some comments/suggestions. 😄

2022-02-28 22:13 UTC, Dusch4593 commented on content/python/concepts/random-module/terms/sample/sample.md
> +Where `<population>` is the sequence the items are selected from, and `<number>` is the number of item(s) to be returned.
```suggestion
The `population` is a sequence of items can either be a [list](https://www.codecademy.com/resources/docs/python/lists), [string](https://www.codecademy.com/resources/docs/python/strings), or [range](https://www.codecademy.com/resources/docs/python/built-in-functions/range). If [sets](https://www.codecademy.com/resources/docs/python/sets) are used, they should be converted to a list or [tuple](https://www.codecademy.com/resources/docs/python/tuples) before being passed to this method.
```

Looks like [newer versions of `random.sample()` aren't so nice to sets](https://docs.python.org/3/library/random.html#:~:text=Deprecated%20since%20version%203.9%3A%20In%20the%20future%2C%20the%20population%20must%20be%20a%20sequence.%20Instances%20of%20set%20are%20no%20longer%20supported.%20The%20set%20must%20first%20be%20converted%20to%20a%20list%20or%20tuple%2C%20preferably%20in%20a%20deterministic%20order%20so%20that%20the%20sample%20is%20reproducible.). Let's err on the side of caution and use the recommendations described in the suggestion above.

2022-02-28 22:13 UTC, Dusch4593 commented on content/python/concepts/random-module/terms/sample/sample.md
> +print(mySample)
```suggestion
my_range = range(1000)

my_sample = random.sample(my_range,10)

print(my_sample)
```

2022-03-01 12:13 UTC, SSwiniarski commented
@Dusch4593, I committed your suggestion and rewrote the one sentence to avoid the potential misunderstanding you mentioned about selection affecting subsequent samples.

2022-03-01 13:49 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM!

2022-03-03 15:28 UTC, Dusch4593 commented
@yangc95 @KTom101 anything left to check or approve before we merge this one?

2022-03-03 15:31 UTC, yangc95 approved these changes
LGTM 👌🏻

2022-03-03 15:43 UTC, merged

2022-03-03 15:46 UTC, Dusch4593 commented
@SSwiniarski Another solid entry! 💪 Live url here: https://www.codecademy.com/resources/docs/python/random-module/sample