Feat: [Term Entry] PyTorch Tensor Operations .index_copy_()
Codecademy/docs pull request #5663
Opened 2024-11-22 10:34 UTC by SaiTeja-002

### Description

I've added a new entry for `.index_copy_()` in PyTorch at `docs/content/pytorch/concepts/tensor-operations/terms/index-copy/index-copy.md`

### Issue Solved

closes #5615 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-11-23 08:27 UTC, mamtawardhani requested changes
Hey @SaiTeja-002, thank you for contributing to Codecademy Docs! 

The issue #5615 is about the `.index_copy()` in PyTorch, however, the `.index_copy()` is not a stable version, so can you just modify the entry to the stable version `.index_copy_()`?

I've left some suggestions in the entry as well, let me know when you make the changes 😄 
Thank you!

2024-11-23 08:27 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/index-copy/index-copy.md
> +Description: 'Returns a new tensor by copying values to specified indices of a given tensor along the specified dimension.'
```suggestion
Description: 'Returns a new tensor by copying values from a source tensor to specified indices in the target tensor along a given dimension.'
```

2024-11-23 08:27 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/index-copy/index-copy.md
> +Description: 'Returns a new tensor by copying values to specified indices of a given tensor along the specified dimension.'
reframed for better readability

2024-11-23 08:27 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/index-copy/index-copy.md
> +The **`index_copy()`** function in PyTorch creates a new [tensor](https://www.codecademy.com/resources/docs/pytorch/tensors) with values from a source tensor copied to specific indices of input tenso
```suggestion
The **`.index_copy()`** function in PyTorch creates a new [tensor](https://www.codecademy.com/resources/docs/pytorch/tensors) with values from a source tensor copied to specific indices of the target tensor along the specified dimension.
```

2024-11-23 08:27 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/index-copy/index-copy.md
> +torch.index_copy(input_tensor, dim, index, source_tensor)
```suggestion
torch.index_copy_(dim, index, tensor)
```

2024-11-23 08:27 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/index-copy/index-copy.md
> +Title: 'index_copy()'
```suggestion
Title: '.index_copy_()'
```

2024-11-23 08:27 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/index-copy/index-copy.md
> +- `source_tensor`: A tensor containing the values to be copied, matching dimension with the specified indices.
please change these based on the above syntax suggestion

2024-11-23 08:27 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/index-copy/index-copy.md
> +print("\nResult Tensor (Column Copy):\n", result)
can you make slight changes in this code, so that it fits with the `.index_copy_()`

2024-11-27 06:58 UTC, mamtawardhani approved these changes
Thank you for making the changes @SaiTeja-002 😄 

The entry looks good for a second round of review! 🚀

2024-11-30 05:46 UTC, Sriparno08 approved these changes
Looks good, @SaiTeja-002!

2024-11-30 05:47 UTC, merged