[Term Entry] Python SQL Connectors: SQLite3
Codecademy/docs pull request #5681
Opened 2024-11-26 12:09 UTC by ralfze

### Description

- Added term sqlite3 for Python SQL Connector
- Closes #5635

### Issue Solved

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-11-26 12:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5681) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5681) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5681) it.</sub>

2024-11-26 15:26 UTC, SaviDahegaonkar requested changes
Hey @ralfze ,
The entry is nicely written. I had a look at your file and suggested a few changes please make them asap and let me know.

Thanks,
Savi

2024-11-26 17:24 UTC, ralfze commented
Hey @SaviDahegaonkar,
thank you very much for the feedback.
I added the suggested edits and pushed it in a new commit.

Best,
Ralf

2024-12-08 11:33 UTC, SaviDahegaonkar approved these changes

2024-12-08 11:33 UTC, SaviDahegaonkar commented on content/python/concepts/sql-connectors/terms/sqlite3/sqlite3.md
> +In order to check all inserted rows, the function **`.fetchall()`** can be used.
```suggestion
To check all inserted rows, the  **`.fetchall()`**  function can be used.
```

2024-12-08 11:33 UTC, SaviDahegaonkar commented on content/python/concepts/sql-connectors/terms/sqlite3/sqlite3.md
> +After all transactions are completed, the connection should be closed with **`.close()`**.
```suggestion
After completing all the transactions , connection can be closed with **`.close()`**.
```

2024-12-08 11:33 UTC, SaviDahegaonkar commented on content/python/concepts/sql-connectors/terms/sqlite3/sqlite3.md
> +The complete example for tinkering.
```suggestion
"An example showing how to connect to an `SQLite` database, `create a table`, `insert/query data`, and `close the connection.`"
```

2024-12-10 09:52 UTC, ralfze commented
I updated the code that caused the prettier code test to fail.

2024-12-17 15:55 UTC, Sriparno08 approved these changes
Looks good, @ralfze!

2024-12-17 15:56 UTC, merged

2024-12-17 15:57 UTC, ralfze commented
> Looks good, @ralfze!

Thank you @Sriparno08!