[Term Entry] Python statsmodels: ARMA
Codecademy/docs pull request #5696
Opened 2024-11-27 07:39 UTC by Mofizik

### Description

Add new term entry `docs/content/python/concepts/statsmodels/terms/arma/arma.md`
Add new `.png` file for the entry `media/arma-forecast-example.png`

Motivation: project on Codeacademy Git & GitHub course

### Issue Solved
#5641

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-11-27 07:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5696) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5696) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5696) it.</sub>

2024-11-29 16:50 UTC, PragatiVerma18 commented on content/python/concepts/statsmodels/terms/arma/arma.md
> +Description: 'A class of statistical models used for analyzing and forecasting time series data.'
We should rewrite the description for more relevant definition as follows:

```suggestion
Description: 'Represent stationary time series data, where statistical properties remain consistent over time.'
```

2024-11-29 17:14 UTC, PragatiVerma18 requested changes
Hey @Mofizik, thanks for contributing this entry. I have a few suggestions, please go through them and make the suggested changes. Let me know if you have any questions.

2024-11-29 17:14 UTC, PragatiVerma18 commented on content/python/concepts/statsmodels/terms/arma/arma.md
> +To implement ARMA in python ARIMA (Autoregressive integrated moving average) model will be used.
We should simply this sentence to make it easier to understand for the learner.

```suggestion
To implement ARMA in Python, the **ARIMA(Autoregressive integrated moving average) model** will be used.
```

2024-11-29 17:14 UTC, PragatiVerma18 commented on content/python/concepts/statsmodels/terms/arma/arma.md
> +model = ARIMA(endog, order=(p, d, q))
We `py` when defining Python code blocks:

```suggestion
```py
model = ARIMA(endog, order=(p, d, q))
```

2024-11-29 17:14 UTC, PragatiVerma18 commented on content/python/concepts/statsmodels/terms/arma/arma.md
> +- - q: Order of the moving average (MA) component.
We can improve the list formatting for better understanding:

```suggestion
- `endog`: The time series data (y-axis).
- `order`: A tuple (p, d, q) where:
  - `p`: Order of the autoregressive (AR) component.
  - `d`: Differencing order (set to 0 for ARMA).
  - `q`: Order of the moving average (MA) component.
```

2024-11-29 17:14 UTC, PragatiVerma18 commented on content/python/concepts/statsmodels/terms/arma/arma.md
> +Once the ARIMA model is initialized, the ```.fit()``` method trains it on the data.
We should use single backticks for an inline code block.

```suggestion
Once the ARIMA model is initialized, the `.fit()` method trains it on the data.
```

2024-11-29 17:14 UTC, PragatiVerma18 commented on content/python/concepts/statsmodels/terms/arma/arma.md
> +model_fit = model.fit()
We use `py` when defining Python code block:

```suggestion
```py
model_fit = model.fit()
```

2024-11-29 17:14 UTC, PragatiVerma18 commented on content/python/concepts/statsmodels/terms/arma/arma.md
> +The result, ```model_fit```, contains:
We should use single backticks for an inline code block.

```suggestion
The result, `model_fit`, contains:
```

2024-11-29 17:14 UTC, PragatiVerma18 commented on content/python/concepts/statsmodels/terms/arma/arma.md
> +Methods for forecasting and evaluating the model.
This should either be a list or part of a complete sentence.

```suggestion
- Parameters of the fitted ARMA model.
- Methods for forecasting and evaluating the model.
```

2024-11-29 17:14 UTC, PragatiVerma18 commented on content/python/concepts/statsmodels/terms/arma/arma.md
> +The .forecast() method generates predictions for a specified number of future steps.
We should always enclose exact function/method names in backticks to signify the exact usage:

```suggestion
The `.forecast()` method generates predictions for a specified number of future steps.
```

2024-11-29 17:14 UTC, PragatiVerma18 commented on content/python/concepts/statsmodels/terms/arma/arma.md
> +forecast = model_fit.forecast(steps=n)
We use `py` when defining Python code block:

```suggestion
```py
forecast = model_fit.forecast(steps=n)
```

2024-11-29 17:14 UTC, PragatiVerma18 commented on content/python/concepts/statsmodels/terms/arma/arma.md
> +plt.plot(future_dates, forecast, label="Forecast", color="red")
We use `py` when defining Python code block:

```suggestion
```py
plt.plot(data.index, data["temperature"], label="Historical Data")
plt.plot(future_dates, forecast, label="Forecast", color="red")
```

2024-11-29 17:14 UTC, PragatiVerma18 commented on content/python/concepts/statsmodels/terms/arma/arma.md
> +- ```future_dates```: Generated dates for the forecast period.
These are all inline code blocks, so we should use single backticks here:

```suggestion
- `data.index`: Dates for the historical data.
- `forecast`: Forecasted values for the next steps days.
- `future_dates`: Generated dates for the forecast period.
```

2024-11-29 17:14 UTC, PragatiVerma18 commented on content/python/concepts/statsmodels/terms/arma/arma.md
> +| ```plt.plot()```	| Plots the time series data and forecast for visualization.|
These are all inline code blocks, so we should use single backticks here:

```suggestion
| `ARIMA(endog, order=(p, d, q))`	| Initializes the ARIMA (or ARMA when d=0) model. |
| `.fit()`| Fits the ARIMA/ARMA model to the data. |
| `.forecast(steps=n)` | Predicts the next n time points. |
| `plt.plot()`	| Plots the time series data and forecast for visualization.| 
```

2024-11-29 17:14 UTC, PragatiVerma18 commented on content/python/concepts/statsmodels/terms/arma/arma.md
> +```python
We use `py` when defining Python code block:

```suggestion
```py
```

2024-11-29 17:14 UTC, PragatiVerma18 commented on content/python/concepts/statsmodels/terms/arma/arma.md
> +plt.show()
We should add more inline comments for easier readability:

```suggestion
import pandas as pd
import numpy as np
from statsmodels.tsa.arima.model import ARIMA
import matplotlib.pyplot as plt

# Generate synthetic time series data
np.random.seed(42)  # Set seed for reproducibility
dates = pd.date_range(start="2023-01-01", periods=100)
temperatures = 20 + np.sin(np.linspace(0, 3 * np.pi, 100)) + np.random.normal(0, 0.5, 100)
data = pd.DataFrame({"date": dates, "temperature": temperatures})
data.set_index("date", inplace=True)

# Fit ARMA model (ARIMA with no differencing)
model = ARIMA(data["temperature"], order=(2, 0, 2))
model_fit = model.fit()

# Forecast for the next 10 days
forecast = model_fit.forecast(steps=10)

# Generate future dates for the forecast
future_dates = pd.date_range(start=data.index[-1] + pd.Timedelta(days=1), periods=10)

# Plot historical data and forecast
plt.figure(figsize=(10, 6))
plt.plot(data.index, data["temperature"], label="Historical Data")
plt.plot(future_dates, forecast, label="Forecast", color="red")
plt.title("ARMA Forecast")
plt.xlabel("Date")
plt.ylabel("Temperature (°C)")
plt.legend()
plt.grid()
plt.show()
```

2024-12-01 16:39 UTC, PragatiVerma18 approved these changes
Hey @Mofizik, thanks for promptly addressing the suggested changes. This PR is now good for the next review! 🚀

2024-12-03 07:55 UTC, Sriparno08 approved these changes
Looks good, @Mofizik!

2024-12-03 07:55 UTC, merged