Create CSS Entry for border-radius
Codecademy/docs pull request #572
Opened 2022-02-20 14:20 UTC by SSwiniarski

### Description

Create new entry for docs/content/css/concepts/borders/terms/border-radius

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

2022-02-20 14:20 UTC, SSwiniarski commented
Orphan entry from original assignment sheet.

2022-02-23 04:18 UTC, yangc95 reviewed
First review completed @SSwiniarski. Going to take a look at your other CSS entries as well.

Thanks for all of these 👍

2022-02-23 04:18 UTC, yangc95 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +p (
```suggestion
p {
```

2022-02-23 04:18 UTC, yangc95 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +Sets a 1px blue border around each paragraph with 10px rounded corners.
```suggestion
Sets a 1-pixel blue border around each paragraph with 10-pixel rounded corners.
```

2022-02-23 04:18 UTC, yangc95 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +Sets a 3px solid black border around each header 1 element with 25px rounding only on the top right and bottom left.
```suggestion
Sets a 3-pixel solid black border around each heading element with 25-pixel rounding only on the top right and bottom left.
```

2022-02-23 04:18 UTC, yangc95 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +The #with-background element will have 25px rounded corners, even if no border is displayed.
```suggestion
The element with an `id` of `with-background`, will have 25-pixel rounded corners, even if no border is displayed.
```

2022-02-23 04:18 UTC, yangc95 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +The `border-radius` property defines rounded corners on an element. It allows separate radii for each corner and can have from one to four values.
```suggestion
The `border-radius` property defines rounded corners on an element. It allows separate radii for each corner and can have one to four values.
```

2022-02-25 17:29 UTC, SSwiniarski commented
@yangc95, I implemented all your suggestions.

2022-02-25 19:10 UTC, yangc95 approved these changes
Thanks for those changes! This is ready for a second review 👍

2022-02-25 20:49 UTC, Dusch4593 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +The element with an `id` of `with-background`, will have 25-pixel rounded corners, even if no border is displayed.
```suggestion
The element with an `id` of `#with-background` will have 25-pixel rounded corners, even if no border is displayed.
```

2022-02-25 20:54 UTC, Dusch4593 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +The element with an `id` of `with-background`, will have 25-pixel rounded corners, even if no border is displayed.
Wondering if there should be a small image placed here to further demonstrate this ideal?

2022-02-25 20:55 UTC, Dusch4593 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +The `border-radius` property defines rounded corners on an element. It allows separate radii for each corner and can have one to four values.
```suggestion
The `border-radius` property defines rounded corners on an element. It measures the radii for each corner and can have one to four specified values.
```

2022-02-25 20:56 UTC, Dusch4593 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +
```suggestion

Both [absolute and relative units](https://www.codecademy.com/resources/docs/css/units) can be used as values for this property.

```

2022-02-25 20:57 UTC, Dusch4593 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +/* Using one value */
```suggestion
/* One value */
```

2022-02-25 20:57 UTC, Dusch4593 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +border-radius: <all>;
```suggestion
border-radius: <all corners>;
```

2022-02-25 20:57 UTC, Dusch4593 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +/* Using two values */
```suggestion
/* Two values */
```

2022-02-25 20:58 UTC, Dusch4593 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +border-radius: <top left + bottom right> <top right + bottom left>;
```suggestion
border-radius: <top-left + bottom-right> <top-right + bottom-left>;
```

2022-02-25 20:58 UTC, Dusch4593 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +border-radius: <top left> <top right + bottom left> <bottom right>;
```suggestion
border-radius: <top-left> <top-right + bottom-left> <bottom-right>;
```

2022-02-25 20:58 UTC, Dusch4593 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +/* Using three values */
```suggestion
/* Three values */
```

2022-02-25 20:59 UTC, Dusch4593 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +border-radius: <top left> <top right> <bottom right> <bottom left>;
```suggestion
/* Four values */
border-radius: <top-left> <top-right> <bottom-right> <bottom-left>;
```

2022-02-25 21:00 UTC, Dusch4593 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +Description: 'Adds rounded corners to an element.'
```suggestion
Description: 'Makes the corners of an element rounder.'
```

2022-02-25 21:01 UTC, Dusch4593 requested changes
@SSwiniarski Finished my review and left you some comments/suggestions. Btw, I rellay appreciate your help with getting more entries in Docs and improving existing ones. 😄

2022-02-26 13:50 UTC, SSwiniarski commented
@Dusch4593, applied your comments and added some images.

2022-02-26 16:48 UTC, Dusch4593 approved these changes
@SSwiniarski Excellent, thanks for adding those images! Everything LGTM 👍

2022-02-26 17:26 UTC, yangc95 commented on content/css/concepts/borders/terms/border-radius/border-radius.md
> +Description: 'Makes the corners of an element rounder.'
```suggestion
Description: 'Rounds the corners of an element.'
```

2022-02-27 12:44 UTC, SSwiniarski commented
@yangc95, @Dusch4593 I committed the last suggestion.

2022-02-27 13:33 UTC, merged

2022-02-27 13:53 UTC, yangc95 commented
Entry is live here:

- https://www.codecademy.com/resources/docs/css/borders/border-radius

✨ Thanks to @SSwiniarski @Dusch4593