Create deg2rad.md
Codecademy/docs pull request #5726
Opened 2024-11-30 20:17 UTC by Good-Soma

### Description

### Issue Solved

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-12-01 07:53 UTC, mamtawardhani requested changes
Hey @Good-Soma thank you for contributing to Codecademy Docs 😄 

Could you please add a ##Codebyte Example block at the end of this entry that showcases the term in the entry. Thank you!

2024-12-06 05:56 UTC, mamtawardhani commented
Hey @Good-Soma could you please remove the mixedlm entry from this branch? This is supposed to be only for the deg2rad.md file

2024-12-06 06:34 UTC, Good-Soma commented
> Hey @Good-Soma thank you for contributing to Codecademy Docs 😄
> 
> Could you please add a ##Codebyte Example block at the end of this entry that showcases the term in the entry. Thank you!

Okay, that means I will have to create a separate branch for the mixedlm content?

2024-12-11 13:10 UTC, mamtawardhani approved these changes
Thank you for contributing to Codecademy Docs @Good-Soma  😄 

The entry looks good for a second round of review! 🚀

2024-12-16 09:22 UTC, PragatiVerma18 commented on content/numpy/concepts/math-methods/terms/deg2rad/deg2rad.md
> +In NumPy, the **`.deg2rad()`** function converts angles from degrees to radians.
To make it clearer, we should rephrase the first sentence to:

```suggestion
In NumPy, the **`.deg2rad()`** function converts an angle from degrees to radians.
```

2024-12-16 09:23 UTC, PragatiVerma18 commented on content/numpy/concepts/math-methods/terms/deg2rad/deg2rad.md
> +> **Note:** In NumPy, the default unit for angles is radians. Therefore, the `.deg2rad()` function converts degree inputs to radians when applied.
Second sentence can be simplified as follows:

```suggestion
> **Note:** In NumPy, the default unit for angles is radians. Therefore, the `.deg2rad()` function is used to convert angle values from degrees to radians.
```

2024-12-16 09:32 UTC, merged

2024-12-17 19:35 UTC, Good-Soma commented
Okay, thanks @mamtawardhani and @PragatiVerma18 for reviewing, editing the document for clarity and finally merging it. It is really blissful to work with you!

I have completed the survey and filled out all the necessary details in it as you requested.