[Concept Entry] Sklearn linear-regression-analysis
Codecademy/docs pull request #5729
Opened 2024-12-01 14:42 UTC by SaviDahegaonkar

### Description

Created a new entry on the Linear Regression Analysis concept under Sklearn.

### Issue Solved
#4823 

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-12-03 16:37 UTC, PragatiVerma18 requested changes
Hey @SaviDahegaonkar, thanks for adding this entry. I have added some comments, please check and do the required changes.

2024-12-03 16:37 UTC, PragatiVerma18 commented on content/sklearn/concepts/linear-regression-analysis/linear-regression-analysis.md
> +Title: 'Linear Regresssion Analysis'
There's an extra 's' in Regression:

```suggestion
Title: 'Linear Regression Analysis'
```

2024-12-03 16:37 UTC, PragatiVerma18 commented on content/sklearn/concepts/linear-regression-analysis/linear-regression-analysis.md
> +Description: 'A machine learning technique that involves training a model to predict a dependent variable from one or more independent variables, assuming a linear relationship between them.'
We can simplify this as follows:

```suggestion
Description: 'A machine learning technique used to predict a dependent variable from one or more independent variables, assuming a linear relationship between them.'
```

2024-12-03 16:37 UTC, PragatiVerma18 commented on content/sklearn/concepts/linear-regression-analysis/linear-regression-analysis.md
> +In sklearn,**Linear Regression Analysis** is a technique for simulating the relationship between a dependent variable and one or more independent variables. In simpler terms, it can use it to predict
There's a missing space in the first line, and also we can skip the second sentence as it is just repitition.

```suggestion
In sklearn, **Linear Regression Analysis** is a machine learning technique used to predict a dependent variable based on one or more independent variables, assuming a linear relationship.
```

2024-12-03 16:37 UTC, PragatiVerma18 commented on content/sklearn/concepts/linear-regression-analysis/linear-regression-analysis.md
> +$$
Please explain each parameter with some context.

2024-12-03 16:37 UTC, PragatiVerma18 commented on content/sklearn/concepts/linear-regression-analysis/linear-regression-analysis.md
> +
It is missing import for `plt`.

```suggestion
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Example data: Hours studied (X) and scores (y)
X = np.array([[1], [2], [3], [4], [5]])  # Hours studied
y = np.array([2, 4, 5, 4, 5])  # Scores achieved

# Create a linear regression model
model = LinearRegression()

# Train the model on the data
model.fit(X, y)

# Get the model's predictions
predictions = model.predict(X)

# Output the results
print("Intercept (β₀):", model.intercept_)
print("Coefficient (β₁):", model.coef_[0])
print("Predictions:", predictions)
plt.scatter(X, y, color='red', label='Data Points')
plt.plot(X, predictions, color='green', label='Regression Line')
plt.xlabel('X')
plt.ylabel('y')
plt.title('Simple Linear Regression')
plt.legend()
plt.show()

```

2024-12-03 16:37 UTC, PragatiVerma18 commented on content/sklearn/concepts/linear-regression-analysis/linear-regression-analysis.md
> +![Simple Linear Regression]
The image description should be more descriptive.

```suggestion
![A scatter plot showing the data points (red dots) and the corresponding regression line (green) representing the simple linear regression model.]
```

2024-12-04 13:10 UTC, SaviDahegaonkar commented
> @SaviDahegaonkar just a suggestion i think you need to Run `yarn format:verify` in order to get rid of failing checks. Also for lint run `yarn lint:md`

Yup, Will keep this in mind. Thanks @Anshgrover23

2024-12-04 13:40 UTC, SaviDahegaonkar commented
Hey @PragatiVerma18, I made the changes you suggested. Please have a look at them.

2024-12-05 19:50 UTC, PragatiVerma18 approved these changes
Hey @SaviDahegaonkar, thanks for doing the changes, this looks good to go!

2024-12-05 19:50 UTC, merged