Create CSS Entry for grid
Codecademy/docs pull request #573
Opened 2022-02-20 16:09 UTC by SSwiniarski

### Description

Create entry for docs/content/css/concepts/grids/terms/grid

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

2022-02-20 16:09 UTC, SSwiniarski commented
Orphan entry from original assignment sheet

2022-02-24 05:36 UTC, yangc95 reviewed
@SSwiniarski done with first review 👍

2022-02-24 05:36 UTC, yangc95 commented on content/css/concepts/grids/terms/grid/grid.md
> +
```suggestion

Define a grid with three rows that are 200-pixel high, and two columns; the first column at `25%` wide, and the second at 75% wide.

```

2022-02-24 05:36 UTC, yangc95 commented on content/css/concepts/grids/terms/grid/grid.md
> +
```suggestion
```

2022-02-25 17:31 UTC, SSwiniarski commented
@yangc95, I implemented your suggestions.

2022-02-25 19:16 UTC, yangc95 approved these changes
Ready for second review 👍

2022-02-25 21:13 UTC, Dusch4593 commented on content/css/concepts/grids/terms/grid/grid.md
> +Define a grid with three rows that are 200-pixel high, and two columns; the first column at `25%` wide, and the second at 75% wide.
```suggestion
In the example below is a `grid` declaration for the rows and column (separated by a `/`) with the following:

* There are three rows that are 200-pixels high each.
* There are two columns, with one being `25%` of the grid's width and another at `75%`-wide.
```

2022-02-25 21:21 UTC, Dusch4593 commented on content/css/concepts/grids/terms/grid/grid.md
> +Defines a grid that's three columns wide and has auto-sized rows and columns.
```suggestion
Defines a grid that's three columns wide and has auto-sized rows and columns.
```
```suggestion
The example above defines a grid that has three columns. Each column and row is `auto`-sized.
```

2022-02-25 21:21 UTC, Dusch4593 commented on content/css/concepts/grids/terms/grid/grid.md
> +Description: 'Shorthand for setting grid property values.'
```suggestion
Description: 'Shorthand for setting multiple grid property values.'
```

2022-02-25 21:22 UTC, Dusch4593 requested changes
@SSwiniarski Finished with my review and left some comments/suggestions for you.

2022-02-26 13:53 UTC, SSwiniarski commented
@Dusch4593, I applied your suggestions.

2022-02-26 16:47 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM 👍

2022-02-26 17:24 UTC, yangc95 commented on content/css/concepts/grids/terms/grid/grid.md
> +The `grid` property is shorthand for setting the following properties:
```suggestion
The `grid` property is a shorthand for setting the following properties:
```

2022-02-26 17:25 UTC, yangc95 commented on content/css/concepts/grids/terms/grid/grid.md
> +In the example below is a `grid` declaration for the rows and column (separated by a `/`) with the following:
```suggestion
The example below is a `grid` declaration for the rows and columns (separated by a `/`) with the following:
```

2022-02-26 17:26 UTC, yangc95 commented on content/css/concepts/grids/terms/grid/grid.md
> +- There are three rows that are 200-pixels high each.
```suggestion
- There are three rows that are each 200-pixels high.
```

2022-02-27 12:45 UTC, SSwiniarski commented
@Dusch4593, @yangc95 I committed the last few suggestions.

2022-02-27 13:32 UTC, merged

2022-02-27 13:54 UTC, yangc95 commented
Entry is live here:

- https://www.codecademy.com/resources/docs/css/grids/grid

✨ Thanks to @SSwiniarski @Dusch4593