Added file on movedim
Codecademy/docs pull request #5734
Opened 2024-12-02 06:45 UTC by Neema-Joju

### Description

Added a new file entry on movedim(). Improving documentation and providing more context for the users to understand.

### Issue Solved

Closes #5631 
### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-12-03 10:04 UTC, mamtawardhani requested changes
Hey @Neema-Joju thank you for contributing to Codecademy Docs, the entry is nicely written! 😄 

I've suggested a few changes, could you please review and modify those at your earliest convenience? Thank you! 😃

2024-12-03 10:04 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/movedim/movedim.md
> +- `destination`: Destination position for each of the original dimension. It must be unique.
```suggestion
- `input`: The input tensor whose dimensions are to be rearranged.
- `source`: The dimensions to be moved. Can be a single integer or a tuple of integers.
- `destination`: The target positions for the dimensions specified in `source`. It should have the same length as `source`.
```

2024-12-03 10:04 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/movedim/movedim.md
> +- `destination`: Destination position for each of the original dimension. It must be unique.
reframed for better clarity

2024-12-03 10:04 UTC, mamtawardhani commented on content/pytorch/concepts/tensor-operations/terms/movedim/movedim.md
> +# Move dimensions [0, 1] to positions [2, 3]
```suggestion
# Move dimensions [0, 1] to positions [2, 3] for 4D tensor
```

2024-12-06 11:28 UTC, mamtawardhani approved these changes
Thank you for making the changes @Neema-Joju 😄 

The entry looks good for a second round of review! 🚀

2024-12-19 18:26 UTC, Radhika-okhade commented on content/pytorch/concepts/tensor-operations/terms/movedim/movedim.md
> +
```suggestion
This example will generate the following output:

```

2024-12-19 18:27 UTC, Radhika-okhade commented on content/pytorch/concepts/tensor-operations/terms/movedim/movedim.md
> +This example will generate the following output:
```suggestion

This example will generate the following output:
```

2024-12-19 18:37 UTC, Radhika-okhade approved these changes

2024-12-19 18:37 UTC, merged