Create CSS Entries for translateX & translateY and update translate
Codecademy/docs pull request #576
Opened 2022-02-21 13:02 UTC by SSwiniarski

### Description

Create new entries for docs/css/concepts/transform-functions/terms/translateX and docs/css/concepts/transform-functions/terms/translateX.

Updated some wording in docs/css/concepts/transform-functions/terms/translate

### Type of Change

- Adding a new entry
- Editing an existing entry 

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

2022-02-23 04:51 UTC, yangc95 reviewed
@SSwiniarski First review complete~

Assisted with making everything as explicit as possible and some other minor issues.

2022-02-23 04:51 UTC, yangc95 commented on content/css/concepts/transform-functions/terms/translateY/translateY.md
> +The `translateY` function translates an element along the Y axis.
```suggestion
The `translateY` function translates an element along the vertical Y-axis.
```

2022-02-23 04:51 UTC, yangc95 commented on content/css/concepts/transform-functions/terms/translateX/translateX.md
> +The `translateX` function translates an element along the X axis.
```suggestion
The `translateX` function moves an element along the horizontal X-axis.
```

2022-02-23 04:51 UTC, yangc95 commented on content/css/concepts/transform-functions/terms/translate/translate.md
> +The `translate` function translates an element along the X and/or Y axes.
```suggestion
The `translate` function moves an element along the X- and/or Y-axis.
```

2022-02-23 04:51 UTC, yangc95 commented on content/css/concepts/transform-functions/terms/translate/translate.md
>  where a required `<value>` can be one of the following:
```suggestion
A required `<X-value>` or `<Y-value` can be one of the following:
```

2022-02-23 04:51 UTC, yangc95 commented on content/css/concepts/transform-functions/terms/translate/translate.md
> +Providing only a single value will represent the horizontal axis. Providing a second comma separated value will represent the vertical axis. A positive value moves the element right along the horizon
```suggestion
Providing only a single value will represent the horizontal axis. Providing a second comma-separated value will represent the vertical axis. A positive value moves the element towards the right along the horizontal X-axis and down the vertical Y-axis. A negative value moves the element left along the horizontal X-axis and up the vertical Y-axis.
```

2022-02-23 04:51 UTC, yangc95 commented on content/css/concepts/transform-functions/terms/translate/translate.md
> +Move the `.box` element `100px` right along the horizontal axis:
```suggestion
Move the element, with a `class` of `box`, `100px` right along the horizontal X-axis:
```

2022-02-23 04:51 UTC, yangc95 commented on content/css/concepts/transform-functions/terms/translate/translate.md
> +Move the `.box` element `200px` tight along the horizontal axis and `100px` up the vertical axis:
```suggestion
Move the `.box` element `200px` along the horizontal X-axis and `100px` up the vertical Y-axis:
```

2022-02-23 04:51 UTC, yangc95 commented on content/css/concepts/transform-functions/terms/translateX/translateX.md
> +A positive value moves an element right along the horizontal axis while a negative value will move an element left.
```suggestion
A positive value moves an element towards the right along the horizontal X-axis, while a negative value will move an element left.
```

2022-02-23 04:51 UTC, yangc95 commented on content/css/concepts/transform-functions/terms/translateX/translateX.md
> +Move the `.box` element `100px` right:
```suggestion
Move the element, with a `class` of `box`, `100px` to the right:
```

2022-02-23 04:51 UTC, yangc95 commented on content/css/concepts/transform-functions/terms/translateY/translateY.md
> +Description: 'Translates an element along the Y axis.'
```suggestion
Description: 'Translates an element along the Y-axis.'
```

2022-02-23 04:51 UTC, yangc95 commented on content/css/concepts/transform-functions/terms/translateX/translateX.md
> +Description: 'Translates an element along the X axis.'
```suggestion
Description: 'Translates an element along the X-axis.'
```

2022-02-23 04:51 UTC, yangc95 commented on content/css/concepts/transform-functions/terms/translateY/translateY.md
> +A positive value moves the element down the vertical axis while a negative value will move an element up.
```suggestion
A positive value moves the element down the vertical Y-axis, while a negative value will move an element up.
```

2022-02-23 04:51 UTC, yangc95 commented on content/css/concepts/transform-functions/terms/translateY/translateY.md
> +  transform: translateX(-10em);
```suggestion
  transform: translateY(-10em);
```

2022-02-25 17:37 UTC, SSwiniarski commented
@yangc95, I implemented your suggestions.

2022-02-25 17:42 UTC, SSwiniarski commented
@yangc95, I implemented your suggestions.

2022-02-25 19:23 UTC, yangc95 approved these changes
LGTM, ready for a second review!

2022-02-25 21:38 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translate/translate.md
>  - Percentage value: `25%`, `50%`
```suggestion
```
I recommend moving this above the snippet.

2022-02-25 21:41 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translate/translate.md
```suggestion

The required `<X-value>` or `<Y-value>` can be one of the following:

- Length value: `100px`, `1.5em`
- Percentage value: `25%`, `50%`

```

2022-02-25 21:41 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translate/translate.md
> +/* With a single value */
```suggestion
/* Single value */
```

2022-02-25 21:41 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translate/translate.md
> +/* With both values */
```suggestion
/* Double values */
```

2022-02-25 21:44 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translate/translate.md
> +Providing only a single value will represent the horizontal axis. Providing a second comma-separated value will represent the vertical axis. A positive value moves the element towards the right along
```suggestion
A single value will represent only the horizontal axis. Providing a second comma-separated value will represent the vertical axis, as well. As as the direction goes:

* A positive value moves the element towards the right along the horizontal X-axis and down the vertical Y-axis (southeast). 
* A negative value moves the element left along the horizontal X-axis and up the vertical Y-axis (northwest).
```

2022-02-25 21:46 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translate/translate.md
> +Move the element, with a `class` of `box`, `100px` right along the horizontal X-axis:
```suggestion
In the example below, an element with a `.box` class is moved `100px` to the right, along the horizontal X-axis:
```

2022-02-25 21:48 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translate/translate.md
> +Providing only a single value will represent the horizontal axis. Providing a second comma-separated value will represent the vertical axis. A positive value moves the element towards the right along
Is there more to this with respect to moving in a northeast or southwest direction?

2022-02-25 21:50 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translate/translate.md
> +Move the `.box` element `200px` right along the horizontal X-axis and `100px` up the vertical Y-axis:
```suggestion
In this example, the `.box` class element is moved `200px` to the right, along the X-axis, and `100px` up the vertical Y-axis.
```

2022-02-25 21:52 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translateX/translateX.md
> +Description: 'Translates an element along the X-axis.'
```suggestion
Description: 'Moves an element horizontally along the X-axis.'
```

2022-02-25 21:53 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translateX/translateX.md
> +The `translateX` function moves an element along the horizontal X-axis.
```suggestion
The `translateX()` function moves an element along the horizontal X-axis.
```

2022-02-25 21:54 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translateX/translateX.md
> +Note: `translateX(<value>)` is functionally equivalent to `translate(<value>)` when [`translate`](https://www.codecademy.com/resources/docs/css/transform-functions/transform) is called with a single
```suggestion
**Note**: `translateX(<value>)` is functionally equivalent to `translate(<value>)` when [`translate`](https://www.codecademy.com/resources/docs/css/transform-functions/transform) is called with a single value.
```

2022-02-25 21:54 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translateX/translateX.md
> +Move the element, with a `class` of `box`, `100px` to the right:
```suggestion
In the example below, an element with a `.box` class is moved `100px` to the right:
```

2022-02-25 21:56 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translateX/translateX.md
> +Move the `.box` element `10em` left:
```suggestion
In this example, the element is moved to the left by `10em`, relative to the width of its direct parent:
```

2022-02-25 21:57 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translateY/translateY.md
> +Description: 'Translates an element along the Y-axis.'
```suggestion
Description: 'Moves an element vertically along the Y-axis.'
```

2022-02-25 21:57 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translateY/translateY.md
> +The `translateY` function translates an element along the vertical Y-axis.
```suggestion
The `translateY()` function moves an element along the vertical Y-axis.
```

2022-02-25 21:58 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translateY/translateY.md
> +Move the `.box` element `100px` down:
```suggestion
In the example below, a `.box` element is moved down the Y-axis by `100px`:
```

2022-02-25 21:59 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translateY/translateY.md
> +Move the `.box` element `10em` up:
```suggestion
In this example, the element is moved up the Y-axis by `-10em`, relative to the height of its direct parent element.
```

2022-02-25 21:59 UTC, Dusch4593 requested changes
@SSwiniarski Finished with my review of this one and left some comments/suggestions.

2022-02-26 14:03 UTC, SSwiniarski commented
@Dusch4593, I implemented your suggestions and tried to clarify the northeast/southwest confusion.

2022-02-26 16:44 UTC, Dusch4593 commented on content/css/concepts/transform-functions/terms/translate/translate.md
> +A single value will represent only the horizontal axis. Providing a second comma-separated value will represent the vertical axis, as well. As as the direction goes:
```suggestion
A single value will represent only the horizontal axis. Providing a second comma-separated value will represent the vertical axis, as well. As far as the direction goes:
```

2022-02-27 12:47 UTC, SSwiniarski commented
@Dusch4593, I committed the last suggestion.

2022-02-27 13:31 UTC, merged

2022-02-27 13:56 UTC, yangc95 commented
Entries are live here:

- https://www.codecademy.com/resources/docs/css/transform-functions/translate
- https://www.codecademy.com/resources/docs/css/transform-functions/translateX
- https://www.codecademy.com/resources/docs/css/transform-functions/translateY

✨ Thanks to @SSwiniarski @Dusch4593