[Term Entry] Python Plotly - express .sunburst()
Codecademy/docs pull request #5777
Opened 2024-12-07 09:21 UTC by mamtawardhani

### Description
added a new Term Entry for Python Plotly - express `.sunburst()`

### Issue Solved
Closes #5173 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-12-09 03:47 UTC, PragatiVerma18 requested changes
Hey @mamtawardhani, thanks for adding this entry. I have some suggestions, please check the comments and do the required changes. Let me know if you have any questions or need any help. Thanks.

2024-12-09 03:47 UTC, PragatiVerma18 commented on content/plotly/concepts/express/terms/sunburst/sunburst.md
> +> **Note:** The ellipsis in the syntax (...) indicates that there are additional optional parameters beyond those listed here to customize the 3D mesh.
The Note section mentions "customize the 3D mesh," which is irrelevant for this topic. This appears to be copied from documentation about 3D Plotly charts and should be removed or reworded to:

```suggestion
> **Note:** The ellipsis in the syntax (...) indicates that there are additional optional parameters beyond those listed here to customize the appearance and behavior of the sunburst chart.
```

2024-12-09 03:47 UTC, PragatiVerma18 commented on content/plotly/concepts/express/terms/sunburst/sunburst.md
> +Below is an example that demonstrates how to use the `.sunburst()` method with a hierarchical dataset in a Pandas DataFrame:
We should link Pandas here:

```suggestion
Below is an example that demonstrates how to use the `.sunburst()` method with a hierarchical dataset in a [Pandas](https://www.codecademy.com/resources/docs/pandas) `DataFrame`:
```

2024-12-09 03:47 UTC, PragatiVerma18 commented on content/plotly/concepts/express/terms/sunburst/sunburst.md
> +The **`.sunburst()`** method in the Plotly express module creates sunburst charts, which are circular charts that represent hierarchical data. The chart uses sectors to represent levels in the hierar
We should link Plotly here:

```suggestion
The **`.sunburst()`** method in the [Plotly](https://www.codecademy.com/resources/docs/plotly) `express` module creates sunburst charts, which are circular charts that represent hierarchical data. The chart uses sectors to represent levels in the hierarchy, with the root level at the centre and child levels radiating outward. Sunburst charts are particularly useful for visualizing nested data and their relationships.
```

2024-12-09 03:47 UTC, PragatiVerma18 commented on content/plotly/concepts/express/terms/sunburst/sunburst.md
> +![The output for the example above](https://raw.githubusercontent.com/Codecademy/docs/main/media/sunburst-plotly.png)
The alt text for the image should be more descriptive:

```suggestion
![The output chart displays a circular hierarchy with the root at the centre and child nodes radiating outward. Each sector's size and color are proportional to its respective values and color attributes.](https://raw.githubusercontent.com/Codecademy/docs/main/media/sunburst-plotly.png)
```

2024-12-09 06:24 UTC, mamtawardhani commented
Hey @PragatiVerma18, the changes are made. You can merge the PR. Thanks for the suggestions 😃

2024-12-10 07:34 UTC, PragatiVerma18 approved these changes

2024-12-10 07:35 UTC, merged