[Term Entry] Neural Networks ai gradient descent
Codecademy/docs pull request #5785
Opened 2024-12-09 08:17 UTC by PragatiVerma18

### Description

Add a new term entry in the AI concept for [neural-network](https://www.codecademy.com/resources/docs/ai/neural-networks): gradient descent.

### Issue Solved

Closes #4526

### Type of Change

- [x] Adding a new entry
- [ ] Editing an existing entry (fixing a typo, bug, issues, etc)
- [ ] Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-12-16 09:16 UTC, mamtawardhani requested changes
Hey @PragatiVerma18 , thank you for contributing to Codecademy Docs, the entry is nicely written! 😄 

I've suggested a few changes, could you please review and modify those at your earliest convenience? Thank you! 😃

2024-12-16 09:16 UTC, mamtawardhani commented on content/ai/concepts/neural-networks/terms/gradient-descent/gradient-descent.md
> +learning_rate = value  # Learning rate
```suggestion
theta = initial_value  # Model Parameters (weights)
learning_rate = value  # Learning rate (step size)
```

2024-12-16 09:16 UTC, mamtawardhani commented on content/ai/concepts/neural-networks/terms/gradient-descent/gradient-descent.md
> +    gradient = compute_gradient(X, y, theta)
```suggestion
    gradient = compute_gradient(X, y, theta) # Gradient calculation
```

2024-12-16 09:16 UTC, mamtawardhani commented on content/ai/concepts/neural-networks/terms/gradient-descent/gradient-descent.md
> +    cost = (1/(2*m)) * np.sum((X*theta - y)**2)
```suggestion
    cost = (1/(2*m)) * np.sum((X*theta - y)**2) # The cost function for linear regression
```

2024-12-17 06:23 UTC, PragatiVerma18 commented
Hey @mamtawardhani, I am done with the changes. Please review. Thanks. 🫡

2024-12-18 13:00 UTC, mamtawardhani approved these changes
Thank you for contributing to Codecademy Docs @PragatiVerma18  😄 

The entry looks good to be merged! 🚀

2024-12-18 13:01 UTC, merged