Add custom exceptions md
Codecademy/docs pull request #5788
Opened 2024-12-09 16:17 UTC by timm167

### Description

Changes made in `content/python/concepts/errors/errors.md`. 

Adds sub-section in errors.md to provide a description and example usage of Custom Exceptions in Python.

The section includes three subheadings describing the process of first defining, second using, and third the results of custom exceptions.

### Issue Solved

Closes #5764

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-12-09 16:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5788) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5788) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: timm167<br/>:x: Tim Charteris<br/><hr/>**Tim Charteris** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5788) it.</sub>

2024-12-15 09:32 UTC, SaviDahegaonkar approved these changes

2024-12-16 09:00 UTC, PragatiVerma18 requested changes
Hey @timm167, thanks for contributing this entry. I have few minor suggestions, rest is looking good!

2024-12-16 09:01 UTC, PragatiVerma18 approved these changes

2024-12-17 06:53 UTC, PragatiVerma18 commented
Hey @timm167, you seem to have two different GitHub accounts, and you have signed the CLA only from ✅ @timm167 and not the other account, but there are commits linked to both. Can you please sign the CLA so that we can merge this PR?

Feel free to let me know if you need any help. If you're not able to figure it out, maybe close this PR and raise a new PR from your primary GitHub account.

2024-12-17 13:16 UTC, closed without merging