[Concept Entry] Sklearn multiclass-classification
Codecademy/docs pull request #5814
Opened 2024-12-13 09:27 UTC by SaviDahegaonkar

### Description

Created a new concept entry on the Multiclass Classification concept under Sklearn.

### Issue Solved
#4966 

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-12-16 11:12 UTC, mamtawardhani commented on content/sklearn/concepts/multiclass-classification/multiclass-classification.md
> +print(f"Accuracy: {accuracy:.2f}")
```suggestion
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Generate synthetic data for multiclass classification (3 classes)
X, y = make_classification(n_samples=1000, n_features=20, n_informative=4, n_classes=3, random_state=42)

# Split the dataset into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the RandomForestClassifier
model = RandomForestClassifier()

# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Evaluate the model by calculating accuracy
accuracy = accuracy_score(y_test, y_pred)

# Print the accuracy of the model
print(f"Accuracy: {accuracy:.2f}")
```

2024-12-18 21:10 UTC, SaviDahegaonkar commented
Hey @mamtawardhani ,
Incorporated the changes suggested by you.

Thanks,
Savi

2024-12-20 10:19 UTC, mamtawardhani requested changes
Please change the syntax

2024-12-20 10:19 UTC, mamtawardhani commented on content/sklearn/concepts/multiclass-classification/multiclass-classification.md
> +print(f"Accuracy: {accuracy:.2f}")
You can simply add the syntax of RandomForestClassifier:

please refer to this: https://scikit-learn.org/1.5/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier

Why do we need the iris dataset in syntax? @SaviDahegaonkar 
This should be a generic syntax

2024-12-20 10:25 UTC, SaviDahegaonkar commented
Will do it now.

On Fri, 20 Dec 2024 at 3:50 PM, Mamta Wardhani ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Please change the syntax
> ------------------------------
>
> In
> content/sklearn/concepts/multiclass-classification/multiclass-classification.md
> <https://github.com/Codecademy/docs/pull/5814#discussion_r1893750676>:
>
> > +from sklearn.datasets import load_iris
> +from sklearn.model_selection import train_test_split
> +from sklearn.ensemble import RandomForestClassifier
> +from sklearn.metrics import accuracy_score
> +
> +# Load the Iris dataset (for multiclass classification)
> +data = load_iris()
> +X, y = data.data, data.target
> +
> +# Split the dataset into training and testing sets (80% train, 20% test)
> +X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
> +
> +# Initialize the RandomForestClassifier
> +model = RandomForestClassifier()
> +
> +# Train the model on the training data
> +model.fit(X_train, y_train)
> +
> +# Make predictions on the test data
> +y_pred = model.predict(X_test)
> +
> +# Evaluate the model by calculating accuracy
> +accuracy = accuracy_score(y_test, y_pred)
> +
> +# Print the accuracy of the model
> +print(f"Accuracy: {accuracy:.2f}")
>
> You can simply add the syntax of RandomForestClassifier:
>
> please refer to this:
> https://scikit-learn.org/1.5/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier
>
> Why do we need the iris dataset in syntax? @SaviDahegaonkar
> <https://github.com/SaviDahegaonkar>
> This should be a generic syntax
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Codecademy/docs/pull/5814#pullrequestreview-2517230267>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5UD3MSSLZ34LYLUMPINEVL2GPVOFAVCNFSM6AAAAABTRSOKCOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMJXGIZTAMRWG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-22 06:24 UTC, mamtawardhani approved these changes
Thank you for contributing to Codecademy Docs @SaviDahegaonkar  😄 

The entry looks good to be merged! 🚀

2024-12-22 06:27 UTC, merged