[Term Entry] Python Plotly- graph_objects .Candlestick()
Codecademy/docs pull request #5819
Opened 2024-12-14 13:37 UTC by SaviDahegaonkar

### Description

Created a new term entry on the .Candlestick() method of the [graph_objects module](https://www.codecademy.com/resources/docs/plotly/graph-objects) in Plotly, Python.

### Issue Solved
#5177 

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-12-15 06:27 UTC, mamtawardhani commented
@SaviDahegaonkar please add the output image as well

2024-12-16 11:40 UTC, mamtawardhani requested changes
Hey @SaviDahegaonkar , thank you for contributing to Codecademy Docs, the entry is nicely written! 😄 

I've suggested a few changes, could you please review and modify those at your earliest convenience? Thank you! 😃

2024-12-16 11:40 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/candlestick/candlestick.md
> +Description: 'Creates candlestick charts for visualizing financial data with open, high, low, and close values.'
```suggestion
Description: 'Creates candlestick charts to visualize financial data, showing open, high, low, and close values over time.'
```

2024-12-16 11:40 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/candlestick/candlestick.md
> +The **`.Candlestick()`** method in the `graph_objects` module in Plotly is used to create candlestick charts widely for visualizing financial data. A candlestick chart displays four key data points f
```suggestion
The **`.Candlestick()`** method in Plotly's `graph_objects` module is used to create candlestick charts, widely used for visualizing financial data. A candlestick chart displays four key data points for a specific time period:
```

2024-12-16 11:40 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/candlestick/candlestick.md
> +2. **High** - The highest value achieved within the time period.
instead of within, let us use "The highest value achieved during the time period. and ":" instead of "-"

2024-12-16 11:40 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/candlestick/candlestick.md
> +3. **Low** - The smallest value during the period.
instead of smallest, let us use - "The lowest value during the period."

2024-12-20 10:23 UTC, mamtawardhani reviewed
please change the syntax

2024-12-20 10:23 UTC, mamtawardhani commented on content/plotly/concepts/graph-objects/terms/candlestick/candlestick.md
> +```
Please refer to this and correct the parameters and their values - https://plotly.github.io/plotly.py-docs/generated/plotly.graph_objects.Candlestick.html

2024-12-20 10:25 UTC, SaviDahegaonkar commented
Will do it now.

On Fri, 20 Dec 2024 at 3:53 PM, Mamta Wardhani ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> please change the syntax
> ------------------------------
>
> In content/plotly/concepts/graph-objects/terms/candlestick/candlestick.md
> <https://github.com/Codecademy/docs/pull/5819#discussion_r1893754063>:
>
> > +```pseudo
> +import plotly.graph_objects as go
> +
> +fig = go.Figure(data=[go.Candlestick(
> +    x=df['date'],  # Time or date data
> +    open=df['open'],  # Opening prices
> +    high=df['high'],  # Highest prices
> +    low=df['low'],  # Lowest prices
> +    close=df['close'],  # Closing prices
> +    increasing_line_color='green',  # Color for increasing candlesticks
> +    decreasing_line_color='red',  # Color for decreasing candlesticks
> +    increasing_fillcolor='rgba(0, 255, 0, 0.3)',  # Fill color for increasing candlesticks
> +    decreasing_fillcolor='rgba(255, 0, 0, 0.3)'  # Fill color for decreasing candlesticks
> +)])
> +
> +fig.update_layout(
> +    title='Candlestick Chart',  # Title for the chart
> +    xaxis_title='Date',  # X-axis label
> +    yaxis_title='Price',  # Y-axis label
> +    xaxis_rangeslider_visible=False  # Disables the range slider under the candlestick chart
> +)
> +
> +fig.show()
> +```
>
> Please refer to this and correct the parameters and their values -
> https://plotly.github.io/plotly.py-docs/generated/plotly.graph_objects.Candlestick.html
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Codecademy/docs/pull/5819#pullrequestreview-2517235917>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5UD3MTTNA3R77IATOGZNKD2GPV2FAVCNFSM6AAAAABTTRN6AWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMJXGIZTKOJRG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-20 14:18 UTC, SaviDahegaonkar commented
Hello @mamtawardhani ,
I have made the changes, I hope now it is written in the expected manner.

2024-12-21 06:50 UTC, mamtawardhani approved these changes
The entry looks good to be merged! 🚀

2024-12-21 06:52 UTC, merged