[Concept Entry] Sklearn: Linear Discriminant Analysis
Codecademy/docs pull request #5824
Opened 2024-12-15 15:53 UTC by Sriparno08

### Description

Added a new term entry on `Linear Discriminant Analysis` in Sklearn.

### Issue Solved

Closes #5306

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-12-20 11:54 UTC, mamtawardhani requested changes
Hey @Sriparno08, thank you for contributing to Codecademy Docs, the entry is nicely written! 😄 

I've suggested a few changes, could you please review and modify those at your earliest convenience? Thank you! 😃

2024-12-20 15:21 UTC, Sriparno08 commented on content/sklearn/concepts/linear-discriminant-analysis/linear-discriminant-analysis.md
> +model = LinearDiscriminantAnalysis()
Yup, we can certainly do that.

2024-12-20 15:22 UTC, Sriparno08 commented
Made the changes, @mamtawardhani.

2024-12-21 06:39 UTC, mamtawardhani approved these changes
Thank you for contributing to Codecademy Docs @Sriparno08  😄 

The entry looks good to be merged! 🚀

2024-12-21 06:41 UTC, merged