Add custom exceptions md #5788
Codecademy/docs pull request #5833
Opened 2024-12-17 13:45 UTC by timm167

### Description

Changes made in `content/python/concepts/errors/errors.md`. 

Adds sub-section in errors.md to provide a description and example usage of Custom Exceptions in Python.

The section includes three subheadings describing the process of first defining, second using, and third the results of custom exceptions.

### Issue Solved

Closes #5764

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-12-17 13:46 UTC, timm167 commented
Apologies for previous errors i had to close the last pull request and re-fork the repo. I hope this works fine now.

2024-12-18 19:34 UTC, SaviDahegaonkar commented
Hey @timm167,
Have you implemented the changes? Please let me know so that I can do the review.

Thanks,
Savi

2024-12-18 21:34 UTC, timm167 commented
Hi @SaviDahegaonkar  

Apologies I am not certain what changes you mean?

For context I previously submitted a pull request but I had made a mistake submitting it so even though the changes were approved it wasn't possible for me to sign the CLA.

I have signed the CLA if that is what you are asking?

I also implemented all my initial changes to the docs that were previously accepted as well as the tweaks made my the approver.

Or do you mean some other changes that I need to make?

Apologies for my confusion.

2025-01-06 20:05 UTC, timm167 commented
Hi, just wanted to check in if I need to do anything here :)

2025-01-06 22:03 UTC, SaviDahegaonkar commented
Hey @timm167 ,
I'm sorry for the inconvenience. I will do the review today and try to move it to the second review.

2025-01-10 07:34 UTC, PragatiVerma18 requested changes
Hey @timm167, thanks for contributing to Codecademy docs. I have few minor suggestions, once those are resolved, this is good to go for a second review.

2025-01-10 07:34 UTC, PragatiVerma18 commented on content/python/concepts/errors/errors.md
> +Custom exceptions can be used to define and handle application-specific errors. This can be done by creating a sub-class of the built-in `Exception` class. Custom exceptions are useful for providing
The last 2 sentences can be merged together for better readability.

```suggestion
Custom exceptions can be used to define and handle application-specific errors. This can be done by creating a sub-class of the built-in `Exception` class. 

Custom exceptions help provide clear feedback to users about unexpected behavior, aid in debugging, and can be used throughout the program. 
```

2025-01-10 07:34 UTC, PragatiVerma18 commented on content/python/concepts/errors/errors.md
> +Once a custom exception has been created, it can be used to raise custom error messages for invalid inputs. For example, this function raises an error if the user inputs an age not between 0 and 130.
```suggestion
Once a custom exception has been created, it can raise custom error messages for invalid inputs. For example, the following function raises an error if the user inputs an age not between 0 and 130.
```

2025-01-10 07:34 UTC, PragatiVerma18 commented on content/python/concepts/errors/errors.md
> +Once the custom exception has been used in a function, this function can be used to throw the custom error to the user.
It can be rewritten with a little more context as follows:

```suggestion
Once the custom exception is defined, it can be used to handle errors in a `try-except` block. The following example demonstrates how to raise the custom exception when an invalid age is provided.
```

2025-01-10 07:36 UTC, PragatiVerma18 approved these changes
Hey @timm167, this is good for a second review now! Happy contributing 🚀

2025-01-12 07:33 UTC, Sriparno08 approved these changes
Looks good, @timm167!

2025-01-12 07:34 UTC, merged

2025-01-12 17:02 UTC, timm167 commented
Thanks !