Updated doc for python strftime module
Codecademy/docs pull request #5835
Opened 2024-12-18 12:21 UTC by meleknurb

### Description

Changes were made to the strftime module document based on feedback

### Issue Solved

Closes https://github.com/Codecademy/docs/issues/5754

### Type of Change
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-12-24 15:29 UTC, meleknurb commented
@PragatiVerma18

2024-12-25 15:24 UTC, meleknurb commented
@codecademy-docs

2025-01-01 19:20 UTC, SaviDahegaonkar requested changes
Hey Author,
I reviewed your file, and the entry is well-written. I have suggested a few changes. Please also include an example section and make the changes as soon as possible.

Thanks,
Savi

2025-01-01 19:20 UTC, SaviDahegaonkar commented on content/python/concepts/dates/terms/strftime/strftime.md
> +The formatted time can be retrieved and stored in a variable as shown below:
```suggestion
The formatted time can be retrieved and stored in a variable as shown in this codebyte example :
```
Avoid using the directional words.

2025-01-01 19:20 UTC, SaviDahegaonkar commented on content/python/concepts/dates/terms/strftime/strftime.md
> +| `%p`      | Locale’s equivalent of either AM or PM.    |AM, PM                                   |
```suggestion
| Directive | Meaning                                    | Example                                |
| ----------| ------------------------------------------ | ---------------------------------------|
| `%a`      | Abbreviated name of days                   | Sun, Mon, …, Sat                       |
| `%d`      | Day of the month                           | 01, 02, …, 31                          |
| `%b`      | Abbreviated name of months                 | Jan, Feb, …, Dec                       |
| `%Y`      | Year                                       | 0001, 0002, …, 2013, 2014, …, 9998, 9999|
| `%m`      | Month                                      | 01, 02, …, 12                          |
| `%I`      | Hour (12-hour clock)                       | 01, 02, …, 12                          |
| `%M`      | Minute                                     | 00, 01, …, 59                          |
| `%p`      | Locale’s equivalent of either AM or PM     | AM, PM                                 |
```
Aligned the table for consistency.

2025-01-02 06:18 UTC, meleknurb commented
@SaviDahegaonkar Changes have been committed as per the suggestion. Ready for review. 
By the way, I didn't understand what was about the example section.

2025-01-06 21:36 UTC, SaviDahegaonkar approved these changes
Hey @meleknurb ,
The entry looks good for second round of review. Thanks for contributing to Codecademy docs! :)

Thanks,
Savi

2025-01-06 21:36 UTC, SaviDahegaonkar commented on content/python/concepts/dates/terms/strftime/strftime.md
> +> **Note**: The actual output will vary depending on the current date and time when the script is executed.
```suggestion
> **Note:** The actual output will vary depending on the current date and time when the script is executed.
```

2025-01-07 20:01 UTC, meleknurb commented
Thank you for your valuable comment. It was my great pleasure to contribute to codecademy docs. I hope it will be published soon.

2025-01-09 16:55 UTC, Radhika-okhade commented
Thank you for contributing to Codecademy docs @meleknurb. The entry looks good to be merged.

2025-01-09 16:56 UTC, merged

2025-01-10 11:58 UTC, Radhika-okhade commented
Hey! @meleknurb, You are not appearing as anonymous. This is what is coming as your name "code7986111719".
You need to go to https://www.codecademy.com -> Click on your profile -> Click on Edit Profile, and there, change your username.