Docs squash
Codecademy/docs pull request #5883
Opened 2024-12-21 17:51 UTC by guobyti

### Description

Added documentation of what squash is in Gir, including one example. 

### Issue Solved

#5796

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-12-21 17:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5883) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5883) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5883) it.</sub>

2025-01-11 10:37 UTC, SaviDahegaonkar requested changes
Hey @guobyti , I had a look at your file and left some comments stating the suggestions that should be made in this entry, Overall the entry is nicely written.

Thanks,
Savi

2025-01-11 10:37 UTC, SaviDahegaonkar commented on content/git/concepts/squash/squash.md
> +pick 23456789 Added Santa`s new address
```suggestion
pick 23456789 Added Santa's new address
```
Made some grammatical adjustments.

2025-01-11 10:37 UTC, SaviDahegaonkar commented on content/git/concepts/squash/squash.md
> +23456789 Added Santa`s new address
```suggestion
23456789 Added Santa's new address
```
Please replace the curly apostrophe in 'Santa`s' with the standard ('Santa's').

2025-01-11 10:37 UTC, SaviDahegaonkar commented on content/git/concepts/squash/squash.md
> +These last three commits relate to updates and corrections to the same component, and combining them will create a more meaningful history.
```suggestion
These last three commits relate to updates and corrections to the same component, and quashing them into a single commit will make the commit history more concise and meaningful.
```
Grammatically made the sentence more concise.

2025-01-11 10:37 UTC, SaviDahegaonkar commented on content/git/concepts/squash/squash.md
> +Imagine you’ve been working on a feature branch, generating several incremental commits. Before integrating these changes into the main branch, you decide it’s best to `squash` your commits to mainta
```suggestion
Imagine  working on a feature branch, generating several incremental commits. Before integrating these changes into the main branch,  it’s best to `squash` your commits to maintain a clean history.
```
Avoid using first and second-person pronouns, i.e. "I", "we", and "you", as much as possible.

2025-01-11 10:37 UTC, SaviDahegaonkar commented on content/git/concepts/squash/squash.md
> +Your current commit log might look something like this:
```suggestion
The current commit log might look something like this:
```
Avoud using words like 'you', 'your'.

2025-01-11 10:37 UTC, SaviDahegaonkar commented on content/git/concepts/squash/squash.md
> +Merging a series of smaller commits into a single, cohesive one can significantly clean up your project’s commit history. This practice, commonly known as "squashing", is particularly helpful when pr
```suggestion
Merging a series of smaller commits into a single, cohesive one can significantly clean up your project’s commit history. This practice, commonly known as "squashing", is particularly helpful when previous commits contain minor changes that clutter the commit history.
```
Made the sentence a little grammatically correct.

2025-01-11 10:37 UTC, SaviDahegaonkar commented on content/git/concepts/squash/squash.md
> +After saving and closing the editor, `Git` will prompt you to draft a new commit message:
```suggestion
After saving and closing the editor, `Git` will prompt you to draft a new commit message:
```
Avoid using the first, second person pronouns.

2025-01-11 10:46 UTC, SaviDahegaonkar approved these changes
Hey @guobyti ,
Thank you for contributing to Codecademy Docs! The entry looks suitable for the second round of review 😇.

Thanks,
Savi

2025-01-11 15:10 UTC, PragatiVerma18 approved these changes
Hey @guobyti, this is good to be merged! Thanks for contributing 🚀

2025-01-11 16:52 UTC, guobyti commented
Hey @PragatiVerma18 and @SaviDahegaonkar thanks for the reviews!
Can someone please approve workflows for me? 🤩

2025-01-11 16:54 UTC, PragatiVerma18 commented
Hey @guobyti, I'm waiting for the GitHub workflow to run. Then, we can merge the PR. Let's wait for a while for the same.

2025-01-13 06:58 UTC, merged