Specifying data types
Codecademy/docs pull request #5893
Opened 2024-12-24 10:52 UTC by sachyko

### Description

- added documentation for specifying and converting data types in PyTorch tensors. This includes : writing brief description and examples of common data types, and demonstrating how to use the dtype parameter when creating or converting tensors.
### Issue Solved

#5842 
### Type of Change

- Adding a new entry

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-12-24 10:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5893) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5893) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5893) it.</sub>

2024-12-26 06:17 UTC, mamtawardhani commented
Hey, @sachyko, it looks like you haven't pushed the main file. Could you please check and push the main file on this branch. Thank you! 😄

2025-01-09 05:45 UTC, mamtawardhani commented
Hey @sachyko, are you still working on this? Please note that if you do not respond within the next 2 days, we will have to unassign you from the issue and close this PR.

2025-01-09 22:38 UTC, sachyko commented
I am still working on it .

2025-01-12 12:38 UTC, sachyko commented
@mamtawardhani please check if I've pushed the main file?

2025-01-13 11:41 UTC, mamtawardhani reviewed
Thank you for contributing to Codecademy Docs @sachyko  😄 

The entry looks good for a second round of review! 🚀

2025-01-13 14:49 UTC, mamtawardhani approved these changes
LGTM 😄 

Ready for next review! 🚀

2025-01-13 15:38 UTC, PragatiVerma18 requested changes
Hey @sachyko, thanks for contributing to docs; this entry looks good, but I have some minor suggestions, once they are resolved, this is good to be merged.

2025-01-13 15:38 UTC, PragatiVerma18 commented on content/pytorch/concepts/tensor-operations/terms/specifiying-data-types/specifying-data-types.md
> +In PyTorch, specifying the data types for [`tensors`](https://www.codecademy.com/resources/docs/pytorch/tensors) is crucial as they are the core data structures used to store and process data. Each t
The code-related keywords should be inside backticks.

```suggestion
In PyTorch, specifying the data types for [`tensors`](https://www.codecademy.com/resources/docs/pytorch/tensors) is crucial as they are the core data structures used to store and process data. Each tensor's data type (`dtype`) defines the kind of values it holds (e.g., `integer`, `float`, `boolean`), ensuring precision, improving performance, and maintaining compatibility during computations.
```

2025-01-13 15:38 UTC, PragatiVerma18 commented on content/pytorch/concepts/tensor-operations/terms/specifiying-data-types/specifying-data-types.md
> +  - `torch.bool`: Boolean.
No need for full stops as these are not complete sentences.

```suggestion
  - `torch.float32` (default): 32-bit floating-point
  - `torch.float64`: 64-bit floating-point
  - `torch.int32`: 32-bit integer
  - `torch.int64`: 64-bit integer
  - `torch.bool`: Boolean
```

2025-01-13 15:38 UTC, PragatiVerma18 commented on content/pytorch/concepts/tensor-operations/terms/specifiying-data-types/specifying-data-types.md
> +### Syntax for specifying `dtype` when creating a tensor
We can skip the word syntax as it is inside the same section.

```suggestion
### For specifying `dtype` when creating a tensor
```

2025-01-13 15:38 UTC, PragatiVerma18 commented on content/pytorch/concepts/tensor-operations/terms/specifiying-data-types/specifying-data-types.md
> +### Syntax for converting an existing tensor to a different data type
We can skip the word syntax as it is inside the same section.

```suggestion
### For converting an existing tensor to a different data type
```

2025-01-13 15:40 UTC, PragatiVerma18 approved these changes
This is good to be merged now! 🚀

2025-01-13 15:49 UTC, merged