[Term Entry] Python Scipy Function: find_peaks()
Codecademy/docs pull request #5895
Opened 2024-12-26 01:22 UTC by naajiha

### Description

-Added the find_peaks() term for python from the scipy package
-Closes issue #5853 
### Issue Solved

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-12-26 01:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5895) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5895) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5895) it.</sub>

2024-12-26 03:56 UTC, mamtawardhani commented
> [![CLA assistant check](https://camo.githubusercontent.com/bb14f9741a98be03eb447ca21a4a5e96201df401e5be70f9ef52130f4e1ff903/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/Codecademy/docs?pullRequest=5895) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5895) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5895) it.

Hey @naajiha please sign the CLA

2024-12-26 04:00 UTC, naajiha commented
signed

2024-12-30 10:54 UTC, mamtawardhani requested changes
Hey @naajiha , thank you for contributing to Codecademy Docs, the entry is nicely written! 😄 

I've suggested a few changes, could you please review and modify those at your earliest convenience? Thank you! 😃

2024-12-30 10:54 UTC, mamtawardhani commented on content/scipy/concepts/scipy-signal/terms/find-peaks/find-peaks.md
> +Description: 'Finds the peaks in a signal.'
```suggestion
Description: 'Finds the indices of local maxima (peaks) in a 1D signal array based on specified conditions.'
```

2024-12-30 10:54 UTC, mamtawardhani commented on content/scipy/concepts/scipy-signal/terms/find-peaks/find-peaks.md
> +The **`find_peaks()`** function is used to find peaks in a signal. It returns the indices of local maxima in a signal.
```suggestion
In SciPy, the **`find_peaks()`** function identifies the indices of local maxima (peaks) in a 1D signal array based on specified conditions.
```

2024-12-30 10:54 UTC, mamtawardhani commented on content/scipy/concepts/scipy-signal/terms/find-peaks/find-peaks.md
> +find_peaks(signal);
Please correct the syntax. Here is the reference documentation: https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html

2024-12-30 10:54 UTC, mamtawardhani commented on content/scipy/concepts/scipy-signal/terms/find-peaks/find-peaks.md
> +The default height of the peaks is defined by the height parameter. If the parameter is unspecified, the height is set to 0. The width parameter is used to filter out peaks that have a width less tha
All the parameters should be in bullet points, an example could be:
- `x`: The input 1D array or signal in which peaks are to be identified.
- `height`: Specifies the required height of peaks. A tuple can set minimum and maximum peak heights.
- `threshold`: Specifies the required threshold for the vertical distance between a peak and its neighbors.
- .
- .
- .

2024-12-30 10:54 UTC, mamtawardhani commented on content/scipy/concepts/scipy-signal/terms/find-peaks/find-peaks.md
> +The above code creates a signal with some peaks, finds the peaks in the signal, and prints the indices of the peaks.
Showcase the output of this code using a ```shell``` block

2025-01-08 05:10 UTC, mamtawardhani commented
Hey @naajiha are you still working on this?

2025-01-10 01:43 UTC, naajiha commented
yes, sorry, my computer was getting fixed, it was broken

2025-01-10 05:06 UTC, naajiha commented
I pushed the changes, let me know if you are able to see them

2025-01-15 11:10 UTC, mamtawardhani approved these changes
Thank you for contributing to Codecademy Docs @naajiha 😄 

The entry looks good for a second round of review! 🚀

2025-01-18 06:33 UTC, Sriparno08 approved these changes
Looks good, @naajiha!

2025-01-18 06:35 UTC, merged