[Term Entry] Python Dates: .strptime() #5755
Codecademy/docs pull request #5900
Opened 2024-12-27 19:14 UTC by EduardoGallego94

### Description

This is a new entry on .strptime() method in Python.
New file "strptime.md" in content/python/concepts/dates/terms/strptime/

### Issue Solved

Closes #5755 issue-number

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-12-27 19:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5900) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5900) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5900) it.</sub>

2024-12-30 11:40 UTC, mamtawardhani requested changes
Hey @EduardoGallego94, thank you for contributing to Codecademy Docs, the entry is nicely written! 😄 

I've suggested a few changes, could you please review and modify those at your earliest convenience? Thank you! 😃

2024-12-30 11:40 UTC, mamtawardhani commented on content/python/concepts/dates/terms/strptime/strptime.md
> +Description: 'Return a datetime corresponding to date_string, parsed according to format.'
```suggestion
Description: 'Returns a datetime object that represents the parsed date and time from the given string, based on the specified format.'
```

2024-12-30 11:40 UTC, mamtawardhani commented on content/python/concepts/dates/terms/strptime/strptime.md
> +The **`.strptime()`** is a method included in the `datetime` module. It is used to parse a string representing a date and/or time and convert it into a `datetime` object using a specified format.
```suggestion
The **`.strptime()`** is a method included in the [`datetime`](https://www.codecademy.com/resources/docs/python/dates) module. It is used to parse a string representing a date and/or time and convert it into a `datetime` object using a specified format.
```

2024-12-30 11:40 UTC, mamtawardhani commented on content/python/concepts/dates/terms/strptime/strptime.md
> +- `date_string` (str): The string representing the date and/or time.
```suggestion
- `date_string` (str): The string representing the date and/or time to be parsed..
```

2024-12-30 11:40 UTC, mamtawardhani commented on content/python/concepts/dates/terms/strptime/strptime.md
> +- `format` (str): The format that defines the structure of `date_string`. This uses the directives from the `datetime` module (e.g., `%Y` for a four-digit year, `%m` for a two-digit month).
```suggestion
- `format` (str): A string that defines the structure of `date_string` using format codes from the `datetime` module (e.g., `%Y` for a four-digit year, `%m` for a two-digit month).
```

2024-12-30 11:40 UTC, mamtawardhani commented on content/python/concepts/dates/terms/strptime/strptime.md
> +- A `datetime` object corresponding to the parsed date and time.
```suggestion
It returns a `datetime` object, which represents the parsed date and time from the provided `date_string` according to the specified `format`.
```

2024-12-30 11:40 UTC, mamtawardhani commented on content/python/concepts/dates/terms/strptime/strptime.md
> +```python
```suggestion
```pseudo
```

2024-12-30 11:40 UTC, mamtawardhani commented on content/python/concepts/dates/terms/strptime/strptime.md
> +
Please add an ## Example section above this, followed by the output showcasing as well

2024-12-30 18:52 UTC, EduardoGallego94 commented
reviewed, thanks!

2025-01-08 06:11 UTC, mamtawardhani approved these changes
Thank you for contributing to Codecademy Docs @EduardoGallego94  😄 

The entry looks good for a second round of review!🚀

2025-01-12 07:50 UTC, Sriparno08 approved these changes
Looks good, @EduardoGallego94!

2025-01-12 07:50 UTC, merged