Added docs/content/pytorch/concepts/using-functional-api/using-functional-api.md
Codecademy/docs pull request #5902
Opened 2024-12-28 02:37 UTC by ericgeiger1

…onal-api.md

### Description

### Issue Solved

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-12-28 02:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5902) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5902) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5902) it.</sub>

2024-12-28 02:38 UTC, ericgeiger1 commented
Waiting for approval on the issue, finished the project and just need to make the pull request and wait for review.

2025-01-10 07:24 UTC, PragatiVerma18 requested changes
Hey @ericgeiger1, Thanks for contributing to Codecademy docs. I have some suggestions; please go through them and make the required changes. Let me know if you need any help or have any questions.

2025-01-10 07:24 UTC, PragatiVerma18 commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +
Please include a syntax section first before you move on to Example.

```suggestion
## Syntax

```pseudo
import torch
import torch.nn.functional as F

output = F.layer_name(input, *parameters, **kwargs)
```
```

2025-01-10 07:24 UTC, PragatiVerma18 commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +Example:
Make this a heading.

```suggestion
## Example
```

2025-01-10 07:24 UTC, PragatiVerma18 commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +
Add output for the above code like this:

```suggestion
The code will output a tensor of shape `(10, 5)` representing the result of the linear transformation. However, the actual values of the tensor will be random due to the use of `torch.randn`, which generates random values from a normal distribution. 

The output might look like this:

```shell
tensor([[-1.1570, -1.0890, -0.4154, -0.1795,  1.6989],
        [-0.5629, -0.3360, -0.3411, -0.2352,  1.0300],
        [-0.3185,  0.2398,  0.5389,  0.2491,  1.0749],
        ...
        [ 0.0665,  0.4579, -0.1494, -0.5361,  0.7465],
        [-0.5970,  0.3147,  0.1569,  0.1582,  0.5355],
        [-0.4481, -0.5795,  0.4445, -0.0623,  0.7024]])
```
```

2025-01-10 07:24 UTC, PragatiVerma18 commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +
Include syntax first and then move to example.

```suggestion
## Syntax

```pseudo
import torch

def custom_loss(output, target):
    # Define the loss calculation
    loss = some_loss_function(output, target)
    return loss
```
```

2025-01-10 07:24 UTC, PragatiVerma18 commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +loss = custom_loss(output, target)
Add a print statement to print the loss and also include the output here.

```suggestion
loss = custom_loss(output, target)
print("Custom MSE Loss:", loss)
```

The output might look something like this (the actual number will change due to randomness):

```shell
Custom MSE Loss: tensor(1.2135)
```

2025-01-10 07:24 UTC, PragatiVerma18 commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +```
Similar comment, add syntax first, then add example, add output for example.

2025-01-10 07:24 UTC, PragatiVerma18 commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +For more information, refer to the [PyTorch documentation](https://pytorch.org/docs/stable/nn.functional.html).
We can skip conclusion section, docs concept entries are not that long that we would need a conclusion section.

```suggestion
```

2025-01-11 06:22 UTC, PragatiVerma18 approved these changes
Hey @ericgeiger1, this is now ready for a second review! 🚀

2025-01-15 05:39 UTC, ericgeiger1 reviewed
This is my first pull request!

2025-01-15 09:35 UTC, Radhika-okhade commented
@ericgeiger1 Please correct the file path. This is the correct path `docs/content/pytorch/concepts/using-functional-api/using-functional-api.md`

2025-01-15 09:36 UTC, Radhika-okhade commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +Title: 'Using Functional APIs'
```suggestion
Title: 'Using Functional API'
```

2025-01-15 09:37 UTC, Radhika-okhade commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +Description: 'Functional APIs in PyTorch provide a flexible way to define and manipulate neural networks using functions rather than object-oriented classes.'
```suggestion
Description: 'Functional API in PyTorch provide a flexible way to define and manipulate neural networks using functions rather than object-oriented classes.'
```

2025-01-15 09:37 UTC, Radhika-okhade commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +  - 'Data Science'
```suggestion
  - 'Data Science'
  - 'Machine Learning' 
```

2025-01-15 09:38 UTC, Radhika-okhade commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +  - 'Neural Networks'
```suggestion
  - 'Deep Learning'
  - 'Neural Networks'
  - 'PyTorch'
```

2025-01-15 09:39 UTC, Radhika-okhade commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +**Functional APIs** in PyTorch provide a flexible and powerful way to define and manipulate neural networks. Unlike the `torch.nn.Module` class, which uses an object-oriented approach, functional API
```suggestion
**Functional API** in PyTorch provides a flexible and powerful way to define and manipulate neural networks. Unlike the `torch.nn.Module` class, which uses an object-oriented approach, functional API allows you to define models using functions. 
```

2025-01-15 09:40 UTC, Radhika-okhade commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +Using functional APIs, you can easily define custom loss functions. This is useful when the predefined loss functions in PyTorch do not meet your requirements.
```suggestion
Using functional API, you can easily define custom loss functions. This is useful when the predefined loss functions in PyTorch do not meet your requirements.
```

2025-01-15 09:43 UTC, Radhika-okhade commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +
Only one line break is required. Remove the extra line break.

2025-01-15 09:45 UTC, Radhika-okhade commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +The code will output a tensor of shape `(10, 5)` representing the result of the linear transformation. However, the actual values of the tensor will be random due to the use of `torch.randn`, which g
Add a line break above this line.

2025-01-15 09:46 UTC, Radhika-okhade commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +```python
```suggestion
```py
```

2025-01-15 09:47 UTC, Radhika-okhade commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +## Advantages of Using Functional APIs
```suggestion
## Advantages of Using Functional API
```

2025-01-15 09:48 UTC, Radhika-okhade commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +1. **Flexibility**: Functional APIs provide more control over the forward pass and allow for easy experimentation with different architectures.
```suggestion
1. **Flexibility**: Functional API provide more control over the forward pass and allow for easy experimentation with different architectures.
```

2025-01-15 09:50 UTC, Radhika-okhade commented on content/pytorch/concepts/using-functional-apis/using-functional-api.md
> +Functional APIs offer several advantages and unique features that set them apart. Below are essential concepts to understand how they work and how to use them effectively.
```suggestion
Functional API offer several advantages and unique features that set them apart. Below are essential concepts to understand how they work and how to use them effectively.
```

2025-01-15 09:51 UTC, Radhika-okhade commented
Hey @ericgeiger1, Thanks for contributing to Codecademy docs. I have some suggestions; please go through them and make the required changes.

2025-01-20 06:37 UTC, ericgeiger1 reviewed
Thank You!

2025-01-20 10:58 UTC, Radhika-okhade commented
Hey! @ericgeiger1, Please make the changes that I suggested.

2025-01-22 06:05 UTC, Radhika-okhade approved these changes

2025-01-22 08:34 UTC, Radhika-okhade commented
Thank you for contributing to Codecademy docs @ericgeiger1. The entry looks good to be merged.

2025-01-22 08:48 UTC, merged