Add Entry General: Vim
Codecademy/docs pull request #593
Opened 2022-03-06 04:46 UTC by paulpetelski

### Description

Added a new entry about the vim text editors - content/general/concepts/vim/vim.md

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

2022-03-06 04:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=593) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=593) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=593) it.</sub>

2022-03-06 14:19 UTC, paulpetelski commented
Hi, sorry I used my other computer to run the yarn commands but I committed the last changes using my other GitHub account that is signed in on that computer. Is this an issue or do I just need to sign the CLA on that account as well?

2022-03-07 11:47 UTC, SSwiniarski commented
> Hi, sorry I used my other computer to run the yarn commands but I committed the last changes using my other GitHub account that is signed in on that computer. Is this an issue or do I just need to sign the CLA on that account as well?

@paulpetelski, That should do it.

2022-03-07 11:48 UTC, SSwiniarski commented
@paulpetelski, I'll be doing the first review.

2022-03-07 12:12 UTC, SSwiniarski requested changes
@paulpetelski, I reviewed this and left some broad suggestions.

2022-03-14 00:03 UTC, paulpetelski commented
@SSwiniarski Thank you for your feedback! I have implemented your suggestions.

2022-03-14 11:04 UTC, SSwiniarski approved these changes
Let's go on to the second review.

2022-03-15 18:42 UTC, Dusch4593 commented
> Hi, sorry I used my other computer to run the yarn commands but I committed the last changes using my other GitHub account that is signed in on that computer. Is this an issue or do I just need to sign the CLA on that account as well?

Hey @paulpetelski that should not be an issue as long as all account involved with this PR have signed the CLA (which seems to be the case here 😄). There were two things I would like to run by you, though:

* Is the email associated with the @paulpetelski GH account the same email associated with your Codeademy profile? If not, those would have to be synced in order for your profile to be credited on the live entry.
* Did you want to use a profile image besides what seems to be the default one set for @paulpetelski?

2022-03-16 20:22 UTC, paulpetelski commented
> > Hi, sorry I used my other computer to run the yarn commands but I committed the last changes using my other GitHub account that is signed in on that computer. Is this an issue or do I just need to sign the CLA on that account as well?
> 
> Hey @paulpetelski that should not be an issue as long as all account involved with this PR have signed the CLA (which seems to be the case here 😄). There were two things I would like to run by you, though:
> 
> * Is the email associated with the @paulpetelski GH account the same email associated with your Codeademy profile? If not, those would have to be synced in order for your profile to be credited on the live entry.
> * Did you want to use a profile image besides what seems to be the default one set for @paulpetelski?

Great! My email address is different, how can I go about syncing it with my Codecademy profile? Also, I am fine with using the default profile image.

2022-03-16 23:14 UTC, Dusch4593 commented
@paulpetelski Sure thing, happy to help out! 😄 

To change account/email settings on Codecademy to be the same as what's on your GH:
1. Click on your profile image at the top-right and select "Account + Billing"
2. Under the "Account" tab, click on the "Change" next to "Email" to update it.
3. Save the changes.

To sync your Codecademy profile with your GH account (for credit on entries):
1. Log out of your account completely.
2. On the sign-in screen, click on the GitHub icon to sign in through there.
3. You should be good to go! 👍

2022-03-17 13:58 UTC, Dusch4593 requested changes
@paulpetelski Finished with review 2️⃣ 

I'm pretty excited for this one b/c I've always been curious to know more about Vim. Thank you for this contribution! 🙏 

Tag me whenever you're finished going through and incorporating my comments/suggestions. 😄

2022-03-17 13:58 UTC, Dusch4593 commented on content/general/concepts/vim/vim.md
> +![Vim screenshot](/media/vim.png)
```suggestion
![Vim screenshot](https://raw.githubusercontent.com/Codecademy/docs/main/media/vim.png)
```

2022-03-17 13:58 UTC, Dusch4593 commented on content/general/concepts/vim/vim.md
> +  - 'paths/computer-science'
```suggestion
  - 'learn-the-command-line'
  - 'paths/computer-science'
```

The `CatalogContent` should always include two links:

 - One free course slug.
 - One paid `paths/` slug.

2022-03-17 13:58 UTC, Dusch4593 commented on content/general/concepts/vim/vim.md
> +![Vim screenshot](/media/vim.png)
Also could we switch this image with what the screen would look like after running just `vim`?

<img width="682" alt="Screen Shot 2022-03-17 at 9 54 27 AM" src="https://user-images.githubusercontent.com/23144845/158824185-86d1cb3d-2e0c-4f05-aa89-90d6051149e3.png">

2022-03-17 13:58 UTC, Dusch4593 commented on content/general/concepts/vim/vim.md
> +
```suggestion

Vim can be run directly from the command line interface or from its GUI.

```

> from its GUI interface

Could we include a small screenshot of this, as well?

2022-03-17 13:58 UTC, Dusch4593 commented on content/general/concepts/vim/vim.md
> +
Maybe a short sentence or two below this snippet explaining what the command is doing? Is it opening a new Vim window with the contents of `filename.txt`?

2022-03-21 21:58 UTC, Dusch4593 commented
@paulpetelski Hey there! Thanks for implementing those changes 👍 

> I am having trouble getting the new screenshots to show up using the full file path you suggested. They only show up when I use (/media/vim-terminal.png), I was wondering if you could help me fix this.

I think this is because the entry hasn't yet gone live and,  therefore, the full file path won't work (not yet, at least). It renders locally with `/media/vim-terminal.png` because this is actual relative path reference to that file.

> Also I am getting an error when running yarn format:verify but I do not see what is causing the error. Thank you!

It doesn't look like any of the GH checks are failing (woot! 🙌). If `format:verify` _does_ bring up a file in the future, however, I would just do one of the following:

- Update/save the file(s) and then run `git add` + `commit` and let our [husky hook](https://github.com/Codecademy/docs/blob/main/.husky/pre-commit) perform the lint/format for you.
  - If you go with this option, just know that this only seems to work when you make changes _locally_ (with an editor + terminal) and not anywhere inside GitHub (on the internet).
- After running `format:verify` you could run `format path/to/this/file path/to/that/file` to format multiple files (or run `format:all` to format all of them).

2022-03-21 21:59 UTC, Dusch4593 commented on content/general/concepts/vim/vim.md
> +Description: 'Vim is a free, open source, and customizable text editor for Linux.'
```suggestion
Description: 'Vim is a free, open source text editor that is customizable text and available on many operating systems.'
```

2022-03-21 22:01 UTC, Dusch4593 commented on content/general/concepts/vim/vim.md
> +![Vim terminal screenshot](https://raw.githubusercontent.com/Codecademy/docs/main/media/vim-terminal.png)
```suggestion
```

2022-03-21 22:03 UTC, Dusch4593 commented on content/general/concepts/vim/vim.md
> +Vim can be run directly from the command line interface or from its GUI.
```suggestion
Vim can be launch directly from the terminal by running the `vim` command. The start screen will look like this:

![Vim terminal screenshot](https://raw.githubusercontent.com/Codecademy/docs/main/media/vim-terminal.png)
```

2022-03-21 22:03 UTC, Dusch4593 commented on content/general/concepts/vim/vim.md
> +## Vim Screenshot
```suggestion
## Vim GUI
```

2022-03-21 22:07 UTC, Dusch4593 approved these changes
@paulpetelski I left a few last-minute comments/suggestions but after that we can go ahead with the next review! 👍

2022-03-22 02:07 UTC, paulpetelski commented
> @paulpetelski I left a few last-minute comments/suggestions but after that we can go ahead with the next review! 👍

Thank you! I applied all your suggestions!

2022-03-22 15:35 UTC, Dusch4593 approved these changes
LGTM! 👍 @yangc95 @KTom101 should we conduct one more review for this entry before merging?

2022-03-23 18:35 UTC, KTom101 approved these changes
Looks good, only saw one minor change

2022-03-23 18:35 UTC, KTom101 commented on content/general/concepts/vim/vim.md
> +Vim can be launch directly from the terminal by running the `vim` command. The start screen will look like this:
```suggestion
Vim can be launched directly from the terminal by running the `vim` command. The start screen will look like this:
```

2022-03-23 20:08 UTC, paulpetelski commented
@KTom101 Thank you, I have made the correction!

2022-03-23 20:49 UTC, yangc95 commented on content/general/concepts/vim/vim.md
> +This section describes some of the important features of the Vim editor.
```suggestion
This section describes some important features of the Vim editor.
```

2022-03-23 20:51 UTC, yangc95 commented on content/general/concepts/vim/vim.md
> +- Users can perform complicated tasks using commands.
Do you mean "using keyboard shortcuts"?

2022-03-23 20:54 UTC, yangc95 commented on content/general/concepts/vim/vim.md
> +## Vim GUI
```suggestion
## Vim Graphical User Interface (GUI)
```

2022-03-23 20:55 UTC, yangc95 commented
@paulpetelski two suggestions! Tys for your work on this entry ☺️

2022-03-23 20:59 UTC, paulpetelski commented
@yangc95 Thank you! I implemented your suggestions!

2022-03-23 21:39 UTC, yangc95 approved these changes

2022-03-23 22:06 UTC, merged

2022-03-23 22:45 UTC, yangc95 commented
4 👀 > 1 👁️ ! Went ahead and merged this after four solid reviews 🚀 

Live link: https://www.codecademy.com/resources/docs/general/vim

TY @Dusch4593 @KTom101 @SSwiniarski