Add Entry: HTML Blink
Codecademy/docs pull request #617
Opened 2022-03-13 15:24 UTC by SSwiniarski

### Description

Add entry for the old HTML blink tag prompted by the Target Keywords list.

Assumes the tag 'Obsolete' is added to the list from PR  606

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

2022-03-16 17:39 UTC, yangc95 reviewed
Hi @SSwiniarski ! Review 1️⃣ in for this. Looks like a quick merge entry. No particular technical suggestions, just a few word choice suggestions, and minor things.

2022-03-16 17:39 UTC, yangc95 commented on content/html/concepts/tags/terms/blink/blink.md
> +Using this element is bad design practice and is discouraged by accesability standards. The CSS specification allows browsers to ignore this tag.
```suggestion
Using this element is a bad design practice and is discouraged by accessibility standards. The CSS specification allows browsers to ignore this tag.
```

2022-03-16 17:39 UTC, yangc95 commented on content/html/concepts/tags/terms/blink/blink.md
> +The `<blink>` tag is an obsolete tag that was used historically to make the text it contained flash on and off. It is non-standard, depreciated, and not part of the HTML specifications and should not
```suggestion
The `<blink>` tag is an obsolete tag that was used historically to make text flash on and off. It is non-standard, depreciated, and not part of the HTML specifications.
```

2022-03-16 17:39 UTC, yangc95 commented on content/html/concepts/tags/terms/blink/blink.md
> +Description: 'Obsolete tag that originally caused text to flash on and off. It is now depreciated and should not be used.'
```suggestion
Description: 'Obsolete tag that originally caused text to flash on and off. It is now deprecated and non-standard.'
```

2022-03-16 17:39 UTC, yangc95 commented on content/html/concepts/tags/terms/blink/blink.md
> +<blink><!-- blinking text goes here --></blink>
```suggestion
<blink><!-- Blinking text goes here --></blink>
```

2022-03-16 17:39 UTC, yangc95 commented on content/html/concepts/tags/terms/blink/blink.md
> +<!-- Don't use this tag! -->
```suggestion
<!-- Not advised to use this tag! -->
```

2022-03-17 12:21 UTC, SSwiniarski commented
@yangc95, I implemented your suggestions.

2022-03-17 12:52 UTC, Dusch4593 commented
Cool cool! I'll go ahead with review 2️⃣

2022-03-17 13:03 UTC, Dusch4593 requested changes
@SSwiniarski Finished with my review. Not much to suggest but the last one is more like an opening for a discussion rather than a pure suggested change.

2022-03-17 13:03 UTC, Dusch4593 commented on content/html/concepts/tags/terms/blink/blink.md
> +Using this element is a bad design practice and is discouraged by accessibility standards. The CSS specification allows browsers to ignore this tag.
```suggestion
The `<blink>` tag was used historically used to make text flash on and off. However, it is now considered to be obsolete and non-standard. It is now, or in the middle of being, depreciated from most browsers is not a part of the HTML specifications.

Using this tag is a bad design practice and is heavily discouraged by accessibility standards. The CSS specification allows browsers to ignore this tag.
```

I feel like there are some things that we could/should link to in these paragraphs:

- "HTML specifications" (are we talking about [this](https://html.spec.whatwg.org/)?)
- "accessibility standards" (are we talking about [this](https://www.w3.org/WAI/standards-guidelines/wcag/)?)
- "CSS specification" (most recent snapshot from 2021 appears be [this](https://www.w3.org/TR/css-2021/))

2022-03-18 12:09 UTC, SSwiniarski commented
@Dusch4593, I implemented yor suggestions, including the links.

2022-03-18 12:36 UTC, Dusch4593 commented on content/html/concepts/tags/terms/blink/blink.md
> +Description: 'Used to make text to flash on and off and is now obsolete, deprecated, and non-standard.'
```suggestion
Description: 'Used to make text flash on and off and is now obsolete, deprecated, and non-standard.'
```

2022-03-18 15:09 UTC, yangc95 approved these changes

2022-03-19 19:40 UTC, Dusch4593 approved these changes
LGTM!

2022-03-19 19:40 UTC, Dusch4593 commented
@KTom101 Did you want to take a quick look at this before we merge?

2022-03-20 00:50 UTC, KTom101 approved these changes
LGTM

2022-03-20 01:52 UTC, merged

2022-03-20 01:53 UTC, Dusch4593 commented
Awesome! 🚀 

Once the entry goes live, we can view it here: https://www.codecademy.com/resources/docs/html/tags/blink