Add Entry - JavaScript: Closures
Codecademy/docs pull request #638
Opened 2022-03-19 23:20 UTC by Dusch4593

### Description

Created a new entry for JavaScript closures, per our ongoing work with keywords.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

2022-03-20 13:35 UTC, SSwiniarski commented on content/javascript/concepts/closures/closures.md
> +Another common instance of JavaScript closures with with [callbacks](https://www.codecademy.com/resources/docs/javascript/callbacks).
```suggestion
Another common instance of JavaScript closures is with [callbacks](https://www.codecademy.com/resources/docs/javascript/callbacks).
```

2022-03-20 13:39 UTC, SSwiniarski requested changes
@Dusch4593, I reviewed this and had a couple of suggestions.

2022-03-20 13:39 UTC, SSwiniarski commented on content/javascript/concepts/closures/closures.md
> +Closures are [functions](https://www.codecademy.com/resources/docs/javascript/functions) that can refer to [variables](https://www.codecademy.com/resources/docs/javascript/variables) and other bindin
```suggestion
Closures are [functions](https://www.codecademy.com/resources/docs/javascript/functions) that can refer to [variables](https://www.codecademy.com/resources/docs/javascript/variables) and other bindings beyond their scope, even after being called.
```

2022-03-21 12:49 UTC, Dusch4593 commented
@SSwiniarski finished implementing your suggestions 😄

2022-03-21 13:48 UTC, SSwiniarski approved these changes
Looks good for review two. 👍

2022-03-25 14:29 UTC, yangc95 reviewed
Just one suggestion. This is really well-worded! Thanks for this entry @Dusch4593 🚀

2022-03-25 17:37 UTC, Dusch4593 commented
@yangc95 applied your suggestion.

2022-03-25 18:11 UTC, yangc95 approved these changes
LGTM 😃

2022-03-25 19:09 UTC, merged