Edit React state
Codecademy/docs pull request #639
Opened 2022-03-20 02:46 UTC by yangc95

### Description

Closes #457  

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-03-23 11:52 UTC, SSwiniarski approved these changes
@yangc95, I looked this over and didn't see any changes I'd suggest. I'd pas it on to another review or merge as-is. (@Dusch4593 , @KTom101 )

2022-03-26 21:27 UTC, Dusch4593 requested changes
@yangc95 Left a few comments/suggestions for you. Solid edits! 👍

2022-03-26 21:27 UTC, Dusch4593 commented on content/react/concepts/state/state.md
>  Props are passed down by parent components, whereas state is created and maintained by the component itself.
```suggestion
[Props](https://www.codecademy.com/resources/docs/react/props) are passed down by parent components, whereas state is created and maintained by the component itself.
```

2022-03-26 21:27 UTC, Dusch4593 commented on content/react/concepts/state/state.md
> +<p>It is a white Chevrolet Malibu from 1998. 🚙</p>
```suggestion
<p>It is a white Chevrolet Malibu made in 1998. 🚙</p>
```

2022-03-26 21:27 UTC, Dusch4593 commented on content/react/concepts/state/state.md
>  ## Caution
Can we edit the text below this header and remove all "you"-voices?

2022-03-26 21:27 UTC, Dusch4593 commented on content/react/concepts/state/state.md
>  It will look like:
```suggestion
It will look like this:
```

2022-03-26 23:54 UTC, yangc95 commented
> @yangc95 Left a few comments/suggestions for you. Solid edits! 👍

Thanks @Dusch4593 ! MMade some changes based on your suggestions/comments~

2022-03-27 00:28 UTC, Dusch4593 approved these changes
LGTM! 👍 Ready for merge?

2022-03-29 01:12 UTC, merged

2022-03-29 01:13 UTC, yangc95 commented
Edits should appear here: https://www.codecademy.com/resources/docs/react/state

ty! @SSwiniarski @Dusch4593