Add Entry: Java `.split()` method
Codecademy/docs pull request #642
Opened 2022-03-21 12:07 UTC by SSwiniarski

### Description

From Target Keywords list: Java string term `.split()`

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-03-26 20:17 UTC, KTom101 requested changes
@SSwiniarski Made some suggestions.

2022-03-26 20:17 UTC, KTom101 commented on content/java/concepts/strings/terms/split/split.md
> +## Example
```suggestion
## Example 1
```

2022-03-26 20:17 UTC, KTom101 commented on content/java/concepts/strings/terms/split/split.md
> +```
Maybe add a third example further showing the limit parameter.

2022-03-27 12:30 UTC, SSwiniarski commented on content/java/concepts/strings/terms/split/split.md
> +This example uses the pattern ",\s\*" which matches a comma followed by zero or more whitespace characters, it also uses a limit parameter.
@KTom101. No. In the example the `\` needs to be escaped in the Java string. The actual regular expression is `,\s*`

2022-03-27 12:47 UTC, SSwiniarski commented
@KTom101, I implemented most of your suggestions.

2022-03-27 16:12 UTC, KTom101 commented on content/java/concepts/strings/terms/split/split.md
> +This example uses the pattern ",\s\*" which matches a comma followed by zero or more whitespace characters, it also uses a limit parameter.
@SSwiniarski sorry I meant to say is it supposed to be written `,\s*` in the explanation. Currently, it's written as `,\s\*`.

2022-03-27 16:17 UTC, SSwiniarski commented on content/java/concepts/strings/terms/split/split.md
> +This example uses the pattern ",\s\*" which matches a comma followed by zero or more whitespace characters, it also uses a limit parameter.
That's escaping the asterisk for markdown.

2022-03-27 16:20 UTC, KTom101 commented on content/java/concepts/strings/terms/split/split.md
> +This example uses the pattern ",\s\*" which matches a comma followed by zero or more whitespace characters, it also uses a limit parameter.
@SSwiniarski Yes, thank you! I couldn't figure it out for anything. I wasn't thinking about the markdown 😂

2022-03-27 16:27 UTC, KTom101 approved these changes
@SSwiniarski All the changes look good. I just added another suggestion which is changing the program outputs to "shell". I think this is good for a second review though and thank you for clearing up my confusion with the regex!

2022-03-27 16:27 UTC, KTom101 commented on content/java/concepts/strings/terms/split/split.md
> +```pseudo
```suggestion
```shell
```

2022-03-27 16:27 UTC, KTom101 commented on content/java/concepts/strings/terms/split/split.md
> +```pseudo
```suggestion
```shell
```

2022-03-27 16:27 UTC, KTom101 commented on content/java/concepts/strings/terms/split/split.md
> +```pseudo
```suggestion
```shell
```

2022-03-28 11:09 UTC, SSwiniarski commented on content/java/concepts/strings/terms/split/split.md
> +This example uses the pattern ",\s\*" which matches a comma followed by zero or more whitespace characters, it also uses a limit parameter.
@KTom101. No problem. Regex is opaque enough _before_ you introduce all the escaping 🤣

2022-03-28 21:04 UTC, yangc95 reviewed
@SSwiniarski I just added a few points 🟢 along with @KTom101 !

2022-03-29 12:04 UTC, SSwiniarski commented on content/java/concepts/strings/terms/split/split.md
> +    String[] result = words.split(",\\s*",6); // splits words on matching commas followed by arbitrary whitespace.
@yangc95. In this case I'll agree with yo, since the comma alone, and the comma + space, show the pattern working.

2022-03-29 12:05 UTC, SSwiniarski commented
@yangc95: I implemented most of your suggestions.

2022-03-30 03:57 UTC, yangc95 approved these changes

2022-03-30 03:59 UTC, merged

2022-03-30 04:04 UTC, yangc95 commented
@SSwiniarski another one  🎉 !

Live link here: https://www.codecademy.com/resources/docs/java/strings/split

ty @KTom101 🙌