New Entry: Java Strings `.replace()`
Codecademy/docs pull request #657
Opened 2022-03-25 16:51 UTC by SSwiniarski

### Description

Added entry for the Java string method `.replace()`. From the Target Keyword list.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-04-02 15:24 UTC, Dusch4593 requested changes
@SSwiniarski Finished my review and left you some comments/suggestions.

2022-04-02 15:24 UTC, Dusch4593 commented on content/java/concepts/strings/terms/replace/replace.md
> +Description: 'Takes a String and replaces a given char or CharSequence with another given char or CharSequence.'
```suggestion
Description: 'Returns a new string where a given char or CharSequence replaced with another char or CharSequence.'
```

2022-04-02 15:24 UTC, Dusch4593 commented on content/java/concepts/strings/terms/replace/replace.md
> +  - 'Computer Science'
```suggestion
  - 'Code Foundations'
  - 'Computer Science'
```

2022-04-02 15:24 UTC, Dusch4593 commented on content/java/concepts/strings/terms/replace/replace.md
> +In both cases the result will be `string` with all instances of `oldValue` replaced with `newValue`.
```suggestion
In both cases the result will be a new `string` with all instances of `oldValue` replaced with `newValue`.
```

2022-04-02 15:24 UTC, Dusch4593 commented on content/java/concepts/strings/terms/replace/replace.md
> +```
```suggestion
```

2022-04-02 15:24 UTC, Dusch4593 commented on content/java/concepts/strings/terms/replace/replace.md
> +    System.out.println(s);
```suggestion
    System.out.println(s);
    // Output: Goodbye World!
```

2022-04-02 15:24 UTC, Dusch4593 commented on content/java/concepts/strings/terms/replace/replace.md
> +  public static void main(String args[]){
```suggestion
public class ReplaceMe {
  public static void main(String args[]) {
```

2022-04-02 15:24 UTC, Dusch4593 commented on content/java/concepts/strings/terms/replace/replace.md
> +The `.replace()` String method takes a string and replaces a given char or CharSequence with another given char or CharSequence.
```suggestion
The `.replace()` String method takes a string and replaces a given char or `CharSequence` with another char or `CharSequence`, returning the new string.
```

2022-04-02 15:24 UTC, Dusch4593 commented on content/java/concepts/strings/terms/replace/replace.md
> +string.replace(CharSequence oldValue, CharSequence newValue)
```suggestion

string.replace(CharSequence oldValue, CharSequence newValue)
```

2022-04-02 15:24 UTC, Dusch4593 commented on content/java/concepts/strings/terms/replace/replace.md
> +
```suggestion

In the example below, a substring in `s`, "Hello", is replaced with "Goodbye" and reassigned:

```

2022-04-03 11:52 UTC, SSwiniarski commented
@Dusch4593, I implemented your suggestions.

2022-04-04 23:16 UTC, Dusch4593 approved these changes
LGTM for the next review 👍

2022-04-08 23:29 UTC, yangc95 commented
Taking this on for a 2️⃣ nd review~

2022-04-08 23:50 UTC, yangc95 reviewed
@SSwiniarski another solid entry, just two points

2022-04-08 23:50 UTC, yangc95 commented on content/java/concepts/strings/terms/replace/replace.md
> +The `.replace()` String method takes a string and replaces a given char or `CharSequence` with another char or `CharSequence`, returning the new string.
Can we place the reference to the capitalized string object in some backticks? `String`.

2022-04-08 23:50 UTC, yangc95 commented on content/java/concepts/strings/terms/replace/replace.md
> +The `.replace()` String method takes a string and replaces a given char or `CharSequence` with another char or `CharSequence`, returning the new string.
Do you think we can either include some info here about the difference between `CharSequence` and just `char`? I get that one is a "sequence of char values" but I noticed it's not mentioned in the [data types](codecademy.com/resources/docs/java/data-types)

2022-04-09 12:47 UTC, SSwiniarski commented
@yangc95, I implemented your suggestions.

2022-04-11 12:04 UTC, Dusch4593 commented
This is getting close to being ready for merge! 👍🏻 Was there anything else left to add, check, etc.?

cc: @yangc95 @KTom101

2022-04-14 00:52 UTC, KTom101 reviewed
@SSwiniarski I have included some minor edits.

2022-04-14 00:52 UTC, KTom101 commented on content/java/concepts/strings/terms/replace/replace.md
> +string.replace(char oldValue, char newValue)
```suggestion
string.replace(char oldValue, char newValue);
```

2022-04-14 00:52 UTC, KTom101 commented on content/java/concepts/strings/terms/replace/replace.md
> +string.replace(CharSequence oldValue, CharSequence newValue)
```suggestion
string.replace(CharSequence oldValue, CharSequence newValue);
```

2022-04-14 00:52 UTC, KTom101 commented on content/java/concepts/strings/terms/replace/replace.md
> +The `.replace()` `String` method takes a string and replaces a given char or `CharSequence` with another char or `CharSequence`, returning the new string.
```suggestion
The `.replace()` `String` method takes a string and replaces the given char or `CharSequence` with another char or `CharSequence`, returning the new string.
```

2022-04-14 11:08 UTC, SSwiniarski commented
@KTom101, I implemented your edits.

2022-04-15 00:41 UTC, Dusch4593 requested changes
@SSwiniarski I left a few final comments/suggestions and then after everyone approves, we should be ready to merge! 👍🏻

2022-04-15 00:41 UTC, Dusch4593 commented on content/java/concepts/strings/terms/replace/replace.md
> +The `.replace()` `String` method takes a string and replaces the given char or `CharSequence` with another char or `CharSequence`, returning the new string.
```suggestion
The `.replace()` method belongs to the `String` class and returns a new string where all instances of a given value is switched with a new value. 
```

2022-04-15 00:41 UTC, Dusch4593 commented on content/java/concepts/strings/terms/replace/replace.md
> +string.replace(CharSequence oldValue, CharSequence newValue);
```suggestion
string.replace(char oldValue, char newValue);
```

2022-04-15 00:41 UTC, Dusch4593 commented on content/java/concepts/strings/terms/replace/replace.md
> +In both cases the result will be a new `string` with all instances of `oldValue` replaced with `newValue`.
```suggestion
A char represents a single character. Other legitimate values that can be applied to the `.replace()` method include the following:

- An instance of the `Character` class that resolves to a single character.
- A `CharSequence` interface that represents a sequence of characters (the `String` class is one implementation of this interface).

In any case, the returned result will always be a new `String` object with all instances of `oldValue` replaced with the `newValue`.
```

2022-04-15 00:41 UTC, Dusch4593 commented on content/java/concepts/strings/terms/replace/replace.md
> +    // Output: Goodbye World!
```suggestion
    String s = "Hello World!";
    System.out.println("Original String: " + s);

    char testA = 'e';
    System.out.println("With primitive char: " + s.replace(s.charAt(2), testA));

    Character testB = new Character('o');
    System.out.println("With Character class: " + s.replace(s.charAt(6), testB));

    CharSequence testC = "Goodbye";
    System.out.println("With CharSequence: " + s.replace("Hello", testC));
```

2022-04-15 00:41 UTC, Dusch4593 commented on content/java/concepts/strings/terms/replace/replace.md
> +```
Let's add a sentence with output snippet below here, like so:

The output will look like this:

```shell

Output:
Original String: Hello World!
With primitive char: Heeeo Wored!
With Character class: Hello oorld!
With CharSequence: Goodbye World!
```

2022-04-15 00:41 UTC, Dusch4593 commented on content/java/concepts/strings/terms/replace/replace.md
> +In the example below, a substring in `s`, "Hello", is replaced with "Goodbye" and reassigned:
```suggestion
The example below tests a string `s` with the usage of char values, `Character` instances, and a `CharSequence` where a substring, "Hello", is replaced with "Goodbye" and reassigned:
```

2022-04-15 00:41 UTC, Dusch4593 commented on content/java/concepts/strings/terms/replace/replace.md
> +A char represents a single character while `CharSequence` is the interface representing a sequence of characters. The `String` class is one implementation of this interface.
```suggestion
```

This could be incorporated down below in the "Syntax" section, I think.

2022-04-15 11:11 UTC, SSwiniarski commented
@Dusch4593, I implemented your suggestions.

2022-04-15 15:33 UTC, Dusch4593 approved these changes
LGTM! Thanks Steve 🙏🏻

2022-04-15 16:38 UTC, Dusch4593 commented
@yangc95 @KTom101 What do we think about merging this one?

2022-04-15 23:30 UTC, KTom101 commented
@Dusch4593 To me, it looks good to merge.

2022-04-16 15:16 UTC, merged

2022-04-16 15:18 UTC, Dusch4593 commented
Thanks everyone! The live entry will be here: https://www.codecademy.com/resources/docs/java/strings/replace

I made a small edit in 17e600636f0f215742ae317e107c99cf1bd5d2c5 before merging.