add new points to general writing tips
Codecademy/docs pull request #673
Opened 2022-04-02 15:41 UTC by dharmelolar

### Description

Added extra points to the general writing tips.

### Type of Change

- Updating the documentation

### Checklist

- ✅ All writings are my own.
- ✅ My entry follows the Codecademy Docs style guide.
- ✅ My changes generate no new warnings.
- ✅ I have performed a self-review of my own writing and code.
- ✅ I have checked my entry and corrected any misspellings.
- ✅ I have made corresponding changes to the documentation if needed.
- ✅ I have confirmed my changes are not being pushed from my forked `main` branch.
- ✅ I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- ✅ Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-04-02 15:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=673) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=673) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=673) it.</sub>

2022-04-02 18:31 UTC, Dusch4593 requested changes
Hi @dharmelolar thank you for contributing these edits to our Content Standards! 😄

I left some comments/suggestions for you to check out. Let us know when you're finished and we'll move forward with the review process.

2022-04-02 18:31 UTC, Dusch4593 commented on documentation/content-standards.md
> +- Be clear and concise
```suggestion
```

I think this could be incorporated with the exiting tip beginning with "Brevity without sacrificing..."

2022-04-02 18:31 UTC, Dusch4593 commented on documentation/content-standards.md
> +- Avoid using complex and non-contextual grammar.
```suggestion
- Avoid using idioms as well as complex and non-contextual grammar.
```

2022-04-02 18:31 UTC, Dusch4593 commented on documentation/content-standards.md
> +- Use white spaces and bullet points as much as you can (this makes words easier to read and aids comprehension)
```suggestion
- Use white spaces, lists, and markdown tables wherever possible to improve readability and aid comprehension.
```

2022-04-02 18:31 UTC, Dusch4593 commented on documentation/content-standards.md
> +- Run your contents through writing tools (Grammarly, Prowriting Aid, Hemingway App) to check for grammar errors.
```suggestion
- Run your contents through proofreading tools (e.g. Grammarly, Prowriting Aid, Hemingway App) to check for grammar errors.
```

2022-04-02 18:31 UTC, Dusch4593 commented on documentation/content-standards.md
> +- Minimize the length of your sentence,and each one should communicate a point (paragraphs should be a maximum of 4-6 lines)
```suggestion
- Minimize the length of your sentence,and each one should communicate a point (paragraphs should be a maximum of 4-6 lines).
```

2022-04-02 18:31 UTC, Dusch4593 commented on documentation/content-standards.md
> +- The title of your content should contain keywords for SEO purposes.
```suggestion
- The title of your content should contain keywords for SEO purposes.

```

2022-04-02 18:51 UTC, dharmelolar commented
@Dusch4593 I've implemented the chnages.

2022-04-02 19:05 UTC, Dusch4593 commented on documentation/content-standards.md
> +- The title of your content should contain keywords for SEO purposes.
```suggestion
- The title of your content should contain keywords for SEO purposes.

```

If we add the empty line here that should allow the "verify" GitHub check to pass.

2022-04-02 19:05 UTC, Dusch4593 approved these changes
@dharmelolar Changes LGTM! 👍 

I left a small comment for you but we should let another reviewer take a look. 😄

2022-04-02 19:13 UTC, dharmelolar commented
@Dusch4593 found the comment. Thank you

2022-04-02 19:27 UTC, Dusch4593 commented
@yangc95 @KTom101 this is ready for review 2️⃣!

2022-04-07 10:56 UTC, SSwiniarski requested changes
@dharmelolar, I wrote up some comments for you.

2022-04-07 10:56 UTC, SSwiniarski commented on documentation/content-standards.md
> +- The title of your content should contain keywords for SEO purposes.
```suggestion
- The description of your content should contain keywords for SEO purposes.
```

For Docs entries, the writer has little flexibility in titles. They generally have to be the class/function/method name. Descriptions are where they have some control.

2022-04-07 10:56 UTC, SSwiniarski commented on documentation/content-standards.md
> +- Run your contents through proofreading tools (e.g. Grammarly, Prowriting Aid, Hemingway App) to check for grammar errors.
```suggestion
- Run your contents through proofreading tools (e.g. Grammarly, Prowriting Aid, Hemingway App) to check for grammar and spelling errors.
```

2022-04-07 10:56 UTC, SSwiniarski commented on documentation/content-standards.md
> +- Use punctuations properly.
```suggestion
- Use punctuation properly.
```

2022-04-07 10:56 UTC, SSwiniarski commented on documentation/content-standards.md
> +- Identify your target audience.
```suggestion
- Be aware of your target audience and write to their level.
```

Prior verbiage implies the author is picking the target audience, Docs has its own intended audience that should be written to.

2022-04-07 10:56 UTC, SSwiniarski commented on documentation/content-standards.md
> +- Minimize the length of your sentence,and each one should communicate a point (paragraphs should be a maximum of 4-6 lines).
```suggestion
- Minimize the length of your sentences, and each one should communicate a point (paragraphs should be a maximum of 4-6 lines).
```

2022-04-09 16:06 UTC, dharmelolar commented
@SSwiniarski made the changes already

2022-04-10 12:26 UTC, SSwiniarski requested changes
@dharmelolar left a couple more edits.

2022-04-10 12:26 UTC, SSwiniarski commented on documentation/content-standards.md
> +<<<<<<< HEAD
```suggestion
```

2022-04-10 12:26 UTC, SSwiniarski commented on documentation/content-standards.md
> +>>>>>>> fb649c55aeab0bfb31037821228f7d3f20014d10
```suggestion
```

2022-04-10 12:28 UTC, SSwiniarski requested changes

2022-04-10 12:28 UTC, SSwiniarski commented on documentation/content-standards.md
> +=======
```suggestion
```

2022-04-10 12:28 UTC, SSwiniarski commented on documentation/content-standards.md
> +- The title of your content should contain keywords for SEO purposes.
```suggestion
```

2022-04-11 21:47 UTC, dharmelolar commented
@SSwiniarski fixed!

2022-04-12 11:04 UTC, SSwiniarski approved these changes
@dharmelolar LGTM!

2022-04-12 13:55 UTC, Dusch4593 commented
@yangc95 @KTom101 was there anything left to add or check before we merged these changes?

2022-04-14 00:04 UTC, KTom101 reviewed
@dharmelolar I have some very minor edits otherwise it looks good.

2022-04-14 00:04 UTC, KTom101 commented on documentation/content-standards.md
> +- Run your contents through proofreading tools (e.g. Grammarly, Prowriting Aid, Hemingway App) to check for grammar and spelling errors.
```suggestion
- Run your content through proofreading tools (e.g. Grammarly, Prowriting Aid, Hemingway App) to check for grammar and spelling errors.
```

2022-04-14 13:20 UTC, dharmelolar commented
@KTom101 Fixed!

2022-04-15 11:29 UTC, KTom101 approved these changes
@dharmelolar Looks good 👍
@Dusch4593 @SSwiniarski Anything else you want to include?

2022-04-15 15:31 UTC, Dusch4593 approved these changes
LGTM! 👍🏻

2022-04-15 15:34 UTC, merged