Add Term: HTML Tags `<select>`,`<option>`
Codecademy/docs pull request #677
Opened 2022-04-04 19:25 UTC by SSwiniarski

### Description

Add terms for HTML Tags `<select>` and `<option>`, from the Target Keyword list

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-04-04 21:36 UTC, lukeecart approved these changes
Looks good to me. I see some of your commits say "yarn format". Are the git hooks (husky) not running?

2022-04-08 17:21 UTC, Dusch4593 requested changes
@SSwiniarski Left a few comments/suggestions for you. 😄

2022-04-08 17:21 UTC, Dusch4593 commented on content/html/concepts/tags/terms/select/select.md
> +The `<select>` element is given a `name` attribute to reference it in the form data, and the `<option>` elements will each have a `value` attribute to pass along when the form is submitted with that
```suggestion
The `<select>` element is referenced in the form data with a `name` attribute. Inside, the `<option>` elements will each have a `value` attribute that is submitted with the form if that option is selected.
```

2022-04-08 17:21 UTC, Dusch4593 commented on content/html/concepts/tags/terms/select/select.md
> +The `<select>` element is typically used with the `<option>` elements to gather user input in a [form](https://www.codecademy.com/resources/docs/html/forms).
```suggestion
The `<select>` element is normally used with `<option>` elements for gathering user input in a [form](https://www.codecademy.com/resources/docs/html/forms).
```

2022-04-08 17:21 UTC, Dusch4593 commented on content/html/concepts/tags/terms/option/option.md
> +Here's a simple form that allows the user to select one of four different types of meals.
```suggestion
The example form below allows the user to select one of four different types of meals:
```

2022-04-09 13:13 UTC, SSwiniarski commented
@Dusch4593, I implemented your suggestions.

2022-04-10 01:14 UTC, Dusch4593 approved these changes
Just 2 more suggested edits from me but we should be good for the next review 👍🏻

2022-04-10 01:14 UTC, Dusch4593 commented on content/html/concepts/tags/terms/select/select.md
> +        <option value"4">Vegetarian</option>
```suggestion
        <option value="1">Beef</option>
        <option value="2">Chicken</option>
        <option value="3">Fish</option>
        <option value="4">Vegetarian</option>
```

2022-04-10 01:14 UTC, Dusch4593 commented on content/html/concepts/tags/terms/option/option.md
> +        <option value"4">Vegetarian</option>
```suggestion
        <option value="1">Beef</option>
        <option value="2">Chicken</option>
        <option value="3">Fish</option>
        <option value="4">Vegetarian</option>
```

2022-04-16 22:14 UTC, KTom101 requested changes
@SSwiniarski I don't have much to suggest for this. I only suggested adding attributes sections for the other attributes used with `<option>` and `<select>`.

2022-04-17 15:08 UTC, SSwiniarski commented
@KTom101, I implemented your suggestions

2022-04-18 00:13 UTC, KTom101 approved these changes
@SSwiniarski Thank you! This looks good to me.

@Dusch4593 Anything else you want to add to this?

2022-04-19 20:32 UTC, Dusch4593 approved these changes
LGTM! 👍🏻

2022-04-19 20:32 UTC, merged

2022-04-19 20:33 UTC, Dusch4593 commented
Live entries here:

- `<option>`: https://www.codecademy.com/resources/docs/html/tags/option
- `<select>`: https://www.codecademy.com/resources/docs/html/tags/select