New Entry: Java Queue
Codecademy/docs pull request #681
Opened 2022-04-06 16:54 UTC by SSwiniarski

### Description

New entry for Java Queue. From the earlier collections PR.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-04-08 08:45 UTC, KTom101 requested changes
@SSwiniarski I've added some comments to this.

2022-04-08 08:45 UTC, KTom101 commented on content/java/concepts/queue/queue.md
> +The `Queue` interface utilizes the following methods:
Line 17 and below can have their own subheading.

2022-04-08 08:45 UTC, KTom101 commented on content/java/concepts/queue/queue.md
> +- `.peek()` : returns the head of the `Queue` without removing it.
Can a couple of these methods be shown being used on a Queue?

2022-04-09 14:29 UTC, SSwiniarski commented
@KTom101, I implemented your suggestions by adding an example using a LinkedList.

2022-04-15 11:19 UTC, KTom101 approved these changes

2022-04-15 15:04 UTC, Dusch4593 requested changes
@SSwiniarski Finished with my review for this one and left a few comments/suggestions.

2022-04-15 15:04 UTC, Dusch4593 commented on content/java/concepts/queue/queue.md
> +## Mehods
I think we should move this section somewhere below the "Syntax" section.

2022-04-15 15:04 UTC, Dusch4593 commented on content/java/concepts/queue/queue.md
> +## Syntax
But this seems more like an example section? Could include both a "Syntax" and "Example" section for this?

2022-04-15 16:37 UTC, SSwiniarski commented on content/java/concepts/queue/queue.md
> +Description: 'A collection interface offering additional operations to access or manipulate items at the head of the queue.'
A Queue interface is not inherently FIFO.

2022-04-15 16:44 UTC, SSwiniarski commented
@Dusch4593, I implemented most of your suggestions.

2022-04-17 00:52 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM! 👍🏻 Made a super small edit in 0a7246a0f9e80ecd3c35091d04ed949ee41febc0. This seems good for merge. 😄

2022-04-17 00:53 UTC, merged