Add Item: Java Set
Codecademy/docs pull request #685
Opened 2022-04-07 11:27 UTC by SSwiniarski

### Description

Add Java Set entry from Target Keyword list.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-04-07 21:40 UTC, KTom101 requested changes
@SSwiniarski I've finished the first review of this.

2022-04-07 21:40 UTC, KTom101 commented on content/java/concepts/set/set.md
> +A `Set` is an interface provided in `java.util` that implements collections that have no duplicate elements. Some implementations will have restrictions on the elements the `Set` can contain, such as
```suggestion
A `Set` is an interface provided in the `java.util` package that implements collections that have no duplicate elements. Some implementations will have restrictions on the elements the `Set` can contain, such as excluding `null` elements. Adding an ineligible element will typically throw an unchecked `NullPointerException` or a `ClassCastException`.
```

2022-04-07 21:40 UTC, KTom101 commented on content/java/concepts/set/set.md
> +
Can there be an example of a set being created?

2022-04-07 21:40 UTC, KTom101 commented on content/java/concepts/set/set.md
> +- `.size()` : Returns the number of items in the `Set`.
Can a couple of these methods be shown in an example? Almost like how it was done in the [javascript sets entry ](https://www.codecademy.com/resources/docs/javascript/sets).

2022-04-07 21:40 UTC, KTom101 commented on content/java/concepts/set/set.md
> +SetClass<DataType> mySet = new SetClass<DataType>
```suggestion
SetClass<DataType> mySet = new SetClass<DataType> ();
```

2022-04-07 21:40 UTC, KTom101 commented on content/java/concepts/set/set.md
> +The `SetClass` is a class that implements the `Set` interface, and is initialized with a generic type inside angle brackets `< ... >`.
Can you briefly mention the different set classes that can be used like HashSet, TreeSet, and LinkedHashSet?

2022-04-09 14:39 UTC, SSwiniarski commented
@KTom101 I added a `HashSet` example to address your comments.

2022-04-15 11:17 UTC, KTom101 approved these changes
@Dusch4593 @yangc95 This is ready for a second review

2022-04-15 14:32 UTC, Dusch4593 commented on content/java/concepts/set/set.md
> +This will output:
```suggestion
This will output the following:
```

2022-04-15 14:35 UTC, Dusch4593 requested changes
@SSwiniarski Not too much from me for this one 😄 Review finished.

2022-04-15 14:35 UTC, Dusch4593 commented on content/java/concepts/set/set.md
> +This will output:
```suggestion
This will output the following:
```

2022-04-15 14:35 UTC, Dusch4593 commented on content/java/concepts/set/set.md
> +A `Set` is an interface provided in the `java.util` package that implements collections that have no duplicate elements. Some implementations will have restrictions on the elements the `Set` can cont
```suggestion
A `Set` is an interface provided in the `java.util` package that implements collections with zero duplicate elements. Some implementations will have restrictions on the elements the `Set` can contain, such as excluding `null` elements. Adding an ineligible element will typically throw an unchecked `NullPointerException` or a `ClassCastException`.
```

2022-04-15 14:35 UTC, Dusch4593 commented on content/java/concepts/set/set.md
> +Description: 'An interface for collections that contain no duplicate elements.'
```suggestion
Description: 'A Set is an interface for collections that contain zero duplicate elements.'
```

2022-04-15 16:47 UTC, SSwiniarski commented
@Dusch4593, I implemented your suggestions.

2022-04-17 00:58 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM! 👍🏻

2022-04-17 02:27 UTC, KTom101 commented
@Dusch4593 Does this look good to merge with you? I have nothing else to add.

2022-04-18 12:21 UTC, merged

2022-04-18 12:28 UTC, Dusch4593 commented
PR merged! Live entry here: https://www.codecademy.com/resources/docs/java/set