New Item: Java PriorityQueue
Codecademy/docs pull request #693
Opened 2022-04-13 12:36 UTC by SSwiniarski

### Description

New item from Target Keyword list, Java PriorityQueue

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-04-18 22:45 UTC, yangc95 commented
I'll be doing a review of this entry first 👍

2022-04-19 02:38 UTC, yangc95 commented
@SSwiniarski Made some suggestions!

2022-04-19 18:05 UTC, yangc95 reviewed
Oops, my comments were pending, they should be visible now!

2022-04-20 17:05 UTC, SSwiniarski commented
@yangc95, I implemented your suggestions and added a link to the `Query` entry.

2022-04-26 21:37 UTC, KTom101 reviewed
@SSwiniarski I've finished my review of this

2022-04-27 12:53 UTC, SSwiniarski commented
@KTom101 I implemented your suggestions.

2022-04-27 18:23 UTC, KTom101 approved these changes
@SSwiniarski I think the formatting got messed up a little while making the changes, I've put in comments for those and a couple more things. Otherwise, this looks good.

2022-04-27 18:23 UTC, KTom101 commented on content/java/concepts/priorityqueue/priorityqueue.md
> +``java
```suggestion
```java
```

2022-04-27 18:23 UTC, KTom101 commented on content/java/concepts/priorityqueue/priorityqueue.md
> +
```suggestion
```

2022-04-27 18:23 UTC, KTom101 commented on content/java/concepts/priorityqueue/priorityqueue.md
> +````
remove one backquote

2022-04-27 18:23 UTC, KTom101 commented on content/java/concepts/priorityqueue/priorityqueue.md
> +   while (food.size() >0) {
```suggestion
   while (food.size() > 0) {
```

2022-04-27 18:23 UTC, KTom101 commented on content/java/concepts/priorityqueue/priorityqueue.md
> +   while (food.size() >0) {
```suggestion
   while (food.size() > 0) {
```

2022-04-27 18:23 UTC, KTom101 commented on content/java/concepts/priorityqueue/priorityqueue.md
> +   while (food.size() >0) {
```suggestion
   while (food.size() > 0) {
```

2022-04-28 12:08 UTC, SSwiniarski commented
@KTom101, implemented the latest updates.

2022-04-28 22:09 UTC, KTom101 approved these changes
@SSwiniarski Great!

2022-04-28 22:10 UTC, KTom101 commented
@yangc95 Any other changes needed?

2022-05-08 14:44 UTC, SSwiniarski commented
@yangc95, @Dusch4593 Does this look ok to merge?

2022-05-09 20:54 UTC, Dusch4593 requested changes
@SSwiniarski Just had a few comments/suggestions for this one 😄

2022-05-09 20:54 UTC, Dusch4593 commented on content/java/concepts/priorityqueue/priorityqueue.md
> +```java
```suggestion
```pseudo
```

2022-05-09 20:54 UTC, Dusch4593 commented on content/java/concepts/priorityqueue/priorityqueue.md
> +```java
```suggestion
```pseudo
```

2022-05-09 20:54 UTC, Dusch4593 commented on content/java/concepts/priorityqueue/priorityqueue.md
> +```java
```suggestion
```pseudo
```

Since this is a "Syntax" section, let's replace language-specific signatures with \```pseudo.

2022-05-10 01:39 UTC, yangc95 approved these changes
@SSwiniarski one thing! I had a suggestion for a particular type of sentence in these entries, but feel free to commit if you agree, or you can resolve it.

Hopefully, this will be good for merge once all the comments/suggestions are looked over!

2022-05-10 01:54 UTC, yangc95 commented on content/java/concepts/priorityqueue/priorityqueue.md
> +Where `item` is the item to be removed from `priorityqueue`. If `item` is not part of `priorityqueue` the method has no effect.
@SSwiniarski, @Dusch4593 pointed out that there are other entries (like [Java Queues](https://www.codecademy.com/resources/docs/java/queue)) with this similar style so I'm going to resolve these for consistency

2022-05-10 11:27 UTC, SSwiniarski commented
@Dusch4593, I applied your suggestions.

2022-05-10 15:08 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM! 👍🏻

2022-05-10 15:08 UTC, merged