Add Comparison to Python Strings
Codecademy/docs pull request #695
Opened 2022-04-13 17:03 UTC by SSwiniarski

### Description

From the target keyword list, added a comparison section to Python Strings. Also eliminated some redundancy so the resulting entry is not much longer than the prior version.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-04-19 19:38 UTC, Dusch4593 requested changes
@SSwiniarski Finished with my review! 😄 With regards to code snippets:
- Can we reduce to just one Codebyte snippet and the rest stay as regular \```py snippets?
- Can we place the Codebyte as the last snippet of the entry, towards the bottom?

2022-04-19 19:38 UTC, Dusch4593 commented on content/python/concepts/strings/strings.md
> +Strings in Python are technically a type of list—one in which each character is a separate element in that list. This means each letter in a string can be accessed by indexing, as with the elements i
```suggestion
Strings in Python are technically a type of [list](https://www.codecademy.com/resources/docs/python/lists) — one in which each character is a separate element. This means each character in a string can be individually accessed by index, like with the elements in a list:
```

2022-04-19 19:38 UTC, Dusch4593 commented on content/python/concepts/strings/strings.md
> +```py
To keep uniform with other Docs entries, the Codebyte snippet (if one can be used) should be the last snippet mentioned in the entry, located towards the bottom.

2022-04-20 04:28 UTC, yangc95 commented on content/python/concepts/strings/strings.md
> +```py
Plus one on this! Docs users can copy/paste code to this codebyte on the bottom of the entries if desired.

2022-04-20 04:40 UTC, yangc95 reviewed
@SSwiniarski took a second look in tandem!

2022-04-20 04:40 UTC, yangc95 commented on content/python/concepts/strings/strings.md
> +```codebyte/py
(See last comment) can we turn this into a regular code block?

2022-04-20 04:40 UTC, yangc95 commented on content/python/concepts/strings/strings.md
> +Description: 'A string is a sequence of characters contained within a pair of single quotes or double quotes.'
Can we change to "single or double quotes" rather than "single quotes or double quotes"

2022-04-20 04:40 UTC, yangc95 commented on content/python/concepts/strings/strings.md
> +- Greater than or equal to, `>=`, for returning `True` if the left string is equal to or comes lexically after the right string.
@Dusch4593 wondering what you think about having the operator col come first?

2022-04-21 12:23 UTC, SSwiniarski commented
@Dusch4593, @yangc95, I implemented your suggestions.

2022-04-21 15:28 UTC, Dusch4593 approved these changes
@SSwiniarski Everything LGTM 👍🏻 

Added a Codebyte near the bottom in 088a439733a1c91e72d61d5b3152b6922fb3d31f

2022-05-04 10:55 UTC, SSwiniarski commented
@yangc95, do we look good to merge?

2022-05-10 01:45 UTC, yangc95 approved these changes

2022-05-10 01:46 UTC, merged