json mod entries
Codecademy/docs pull request #696
Opened 2022-04-14 17:45 UTC by caupolicandiaz

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-04-20 23:58 UTC, KTom101 requested changes
@caupolicandiaz Here's my review of this entry, thanks!

2022-04-20 23:58 UTC, KTom101 commented on content/python/concepts/json-module/terms/json-load/json-load.md
> +The `json.load` function can be used to convert a json file to a Python object:
```suggestion
The `json.load()` function can be used to convert a json file to a Python object:
```

2022-04-20 23:58 UTC, KTom101 commented on content/python/concepts/json-module/terms/json-load/json-load.md
> +Title: 'json.load()'
```suggestion
Title: '.load()'
```

2022-04-20 23:58 UTC, KTom101 commented on content/python/concepts/json-module/terms/json-dump/json-dump.md
> +Title: 'json.dump()'
```suggestion
Title: '.dump()'
```

2022-04-20 23:58 UTC, KTom101 commented on content/python/concepts/json-module/terms/json-load/json-load.md
> +---
Please change the folder name from `json-load`--> `load` and file name from `json-load.md` --> `load.md`

2022-04-20 23:58 UTC, KTom101 commented on content/python/concepts/json-module/terms/json-dump/json-dump.md
> +---
Please change folder name from `json-dump` --> `dump` and file name from `json-dump.md` to `dump.md`

2022-04-21 17:01 UTC, caupolicandiaz commented on content/python/concepts/json-module/terms/json-dump/json-dump.md
> +# Output: <class 'str'> <class 'dict'>
I double checked this, and I still get the appropriate results. Not sure why you wouldn't

2022-04-21 17:21 UTC, caupolicandiaz commented on content/python/concepts/json-module/terms/json-dump/json-dump.md
> +# Output: <class 'str'> <class 'dict'>
the second one should've been loads not dumps

2022-04-21 17:26 UTC, caupolicandiaz commented
@KTom101 I've updated the files with your comments, should be all set. Thanks

2022-04-21 17:55 UTC, KTom101 approved these changes
@caupolicandiaz Thanks! This looks ready for the next review.

2022-04-22 00:01 UTC, Dusch4593 requested changes
@caupolicandiaz Finished with my review and left some comments/suggestions for you 😄

2022-04-22 19:58 UTC, caupolicandiaz commented on content/python/concepts/json-module/json-module.md
> +The `json` module provides tools for working with the json format. It can be imported with the following line:
I believe JSON is correct

2022-04-22 20:17 UTC, caupolicandiaz commented
@Dusch4593 all set implementing your comments. Thanks

2022-04-22 21:00 UTC, Dusch4593 approved these changes
@caupolicandiaz LGTM! 👍🏻

2022-04-22 22:18 UTC, Dusch4593 commented
Given that there are multiple files in this PR, let's give it one more review. @SSwiniarski or @yangc95?

2022-04-23 11:34 UTC, SSwiniarski requested changes
@caupolicandiaz, I reviewed and had a couple of comments.

2022-04-23 11:34 UTC, SSwiniarski commented on content/python/concepts/json-module/json-module.md
> +  - 'Strings'
```suggestion
  - 'Strings'
  - 'JSON'
```

2022-04-23 11:34 UTC, SSwiniarski commented on content/python/concepts/json-module/terms/dump/dump.md
> +  - 'Strings'
```suggestion
  - 'Strings'
  - `JSON`
```

2022-04-23 11:34 UTC, SSwiniarski commented on content/python/concepts/json-module/terms/dump/dump.md
> +json.dump(py_obj)
Are we missing an output file here?

2022-04-23 11:34 UTC, SSwiniarski commented on content/python/concepts/json-module/terms/load/load.md
> +  - 'Strings'
```suggestion
  - 'Strings'
  - 'JSON'
```

2022-04-23 21:24 UTC, yangc95 commented on content/python/concepts/json-module/json-module.md
> +The `json` module provides tools for working with the Javascript Object Notation (JSON) format. It can be imported with the following line:
Javascript -> JavaScript

2022-04-25 19:52 UTC, caupolicandiaz commented
@SSwiniarski I've incorporated your comments, should be all set now. Thanks

2022-04-26 11:03 UTC, SSwiniarski requested changes
LGTM! 👍

2022-04-26 17:09 UTC, Dusch4593 commented
> LGTM! 👍

@SSwiniarski did you mean to approve?

2022-05-04 10:56 UTC, SSwiniarski approved these changes
I meant to approve this. Looks good to merge.

2022-05-04 16:31 UTC, Dusch4593 commented
Yup we are ready to merge! 👍🏻 Made some light edits to `CatalogContent` in 7798534cdf623655b5fed2fa93dde3dcc337f6b3, 322b9c1260f77a91c6afe3b8dff6d859a6d9cce9, and c857fd16193bb1b0bc8f669915fcc445a7519e20.

2022-05-04 16:32 UTC, merged