New Term Entry: PHP String Functions, `substr()`
Codecademy/docs pull request #702
Opened 2022-04-16 12:45 UTC by SSwiniarski

### Description

Add new term for PHP string functions, `substr()`. From the Target Keyword list. Assumes the directory structure from merging  [660](https://github.com/Codecademy/docs/pull/660)

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-04-23 01:50 UTC, KTom101 requested changes
@SSwiniarski I'm requesting a couple of minor changes.

2022-04-23 01:50 UTC, KTom101 commented on content/php/concepts/string-functions/terms/substr/substr.md
> +The `$offset` parameter is an `int` value ad specifies the start of the substring in the following manner:
```suggestion
The `$offset` parameter is an `int` value and specifies the start of the substring in the following manner:
```

2022-04-23 10:58 UTC, SSwiniarski commented
@KTom101, I applied your suggestions.

2022-04-24 02:54 UTC, KTom101 approved these changes
@SSwiniarski Looks ready for the next review.

2022-04-26 15:49 UTC, Dusch4593 commented on content/php/concepts/string-functions/terms/substr/substr.md
> +```php
```suggestion
```pseudo
```

2022-04-26 15:55 UTC, Dusch4593 commented on content/php/concepts/string-functions/terms/substr/substr.md
> +- An `$offset` greater than the length of `$string` will return an empty string.
```suggestion
- A value greater than the length of `$string` will return an empty string.
```

2022-04-26 15:58 UTC, Dusch4593 commented on content/php/concepts/string-functions/terms/substr/substr.md
> +
Let's add a brief sentence here that describes what's going on in the codebyte below.

2022-04-27 13:04 UTC, SSwiniarski commented
@Dusch4593, applied your changes.

2022-04-28 21:32 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM! 👍🏻

2022-05-04 10:58 UTC, SSwiniarski commented
@Dusch4593, @KTom101 do we look ok to merge?

2022-05-04 16:41 UTC, merged