New Term Entry: PHP String Functions `explode()`
Codecademy/docs pull request #703
Opened 2022-04-16 14:52 UTC by SSwiniarski

### Description

Added term entry for PHP String Function `explode()` from Target Keyword list. Uses directory structure from [660](https://github.com/Codecademy/docs/pull/660)

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-04-24 02:21 UTC, KTom101 requested changes
@SSwiniarski I've made a review of this.

2022-04-24 02:21 UTC, KTom101 commented on content/php/concepts/string-functions/terms/explode/explode.md
> +- If `$delimiter` is found at the start or end of `$string` empty values for each `$delimiter` will be added to the start or end of the returned array respectively.
```suggestion
- If `$delimiter` is found at the start or end of `$string`, empty values for each `$delimiter` will be added to the start or end of the returned array respectively.
```

2022-04-24 02:21 UTC, KTom101 commented on content/php/concepts/string-functions/terms/explode/explode.md
> +```php
```suggestion
```pseudo
```

2022-04-24 11:29 UTC, SSwiniarski commented
@KTom101, I implemented your suggestions.

2022-04-25 18:44 UTC, KTom101 approved these changes
@SSwiniarski Looks good for the next review.

2022-04-26 16:04 UTC, Dusch4593 requested changes
@SSwiniarski Finished my review and left you a couple comments/suggestions.

2022-04-26 16:04 UTC, Dusch4593 commented on content/php/concepts/string-functions/terms/explode/explode.md
> +
```suggestion
?>\
```

2022-04-26 16:04 UTC, Dusch4593 commented on content/php/concepts/string-functions/terms/explode/explode.md
> +
Let's a brief sentence here that describes what's happening in the codebyte below:

2022-04-27 13:14 UTC, SSwiniarski commented
@Dusch4593 I've implemented your suggestion.

2022-04-28 17:45 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/explode/explode.md
> +- A negative `$limit` will omit the last -`$limit` elements from the result.
```suggestion
- A negative `$limit` will omit the last n elements from the result.
```

2022-04-28 17:47 UTC, caupolicandiaz requested changes
@SSwiniarski looks pretty good, just one comment

2022-04-28 17:47 UTC, caupolicandiaz commented on content/php/concepts/string-functions/terms/explode/explode.md
> +- A negative `$limit` will omit the last -`$limit` elements from the result.
I found this description confusing, perhaps revise to something similar to the suggestion above

2022-04-29 11:08 UTC, SSwiniarski commented
@caupolicandiaz, I implemented your suggestion.

2022-04-29 19:20 UTC, Dusch4593 approved these changes
LGTM! 👍🏻

2022-05-04 10:59 UTC, SSwiniarski commented
@caupolicandiaz, do we look ok to merge now?

2022-05-11 03:16 UTC, yangc95 commented on content/php/concepts/string-functions/terms/explode/explode.md
> +The `explode()` function takes a string and splits it on a given delimiter string, and returns an array of the substrings produced.
```suggestion
The `explode()` function takes a string and splits it on a given delimiter string. It returns an array of the substrings produced.
```

2022-05-11 16:47 UTC, SSwiniarski commented
@Dusch4593, I took care of it.

2022-05-11 17:14 UTC, Dusch4593 commented
> @caupolicandiaz, do we look ok to merge now?

Re-bump.

2022-05-13 01:33 UTC, yangc95 approved these changes

2022-05-19 23:27 UTC, caupolicandiaz approved these changes

2022-05-23 16:08 UTC, Dusch4593 commented
@SSwiniarski This looks good for merge 😄 I made a small edit in 41b3fad24707bb029f3606818143f10ea2aec4f1 where I removed an empty line and added spacing in the Codebyte snippet.

2022-05-23 16:09 UTC, merged

2022-05-23 16:12 UTC, Dusch4593 commented
Live entry here: https://www.codecademy.com/resources/docs/php/string-functions/explode