New Entries: PHP Date Functions
Codecademy/docs pull request #708
Opened 2022-04-20 11:18 UTC by SSwiniarski

### Description

Created a PHP Date Functions Entry, with a fre terms for date functions. From the Target Keyword list.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-04-24 01:30 UTC, KTom101 requested changes
@SSwiniarski A few changes.

2022-04-24 01:30 UTC, KTom101 commented on content/php/concepts/date-functions/terms/date/date.md
> +The `date()` function crates a formatted date-time string from a local date-time.
```suggestion
The `date()` function creates a formatted date-time string from a local date-time.
```

2022-04-24 11:25 UTC, SSwiniarski commented
@KTom101, I implemented your suggestions.

2022-04-26 16:48 UTC, Dusch4593 requested changes
@SSwiniarski Finished with my review and left you some comments/suggestions to check out.

2022-04-26 16:48 UTC, Dusch4593 commented on content/php/concepts/date-functions/terms/date-create/date-create.md
> +```php
```suggestion
```pseudo
```

2022-04-26 16:48 UTC, Dusch4593 commented on content/php/concepts/date-functions/terms/date-create/date-create.md
> +date_create($datetime,$timezone)
```suggestion
date_create($datetime, $timezone)
```

2022-04-26 16:48 UTC, Dusch4593 commented on content/php/concepts/date-functions/terms/date-create/date-create.md
> +
For these sections, let's add a brief sentence here that describes what's happening in the Codebyte below.

2022-04-26 16:48 UTC, Dusch4593 commented on content/php/concepts/date-functions/terms/date-format/date-format.md
> +| --------- | ---------------------------------------------------------------------------------- |
```suggestion
| :---------: | ---------------------------------------------------------------------------------- |
```

2022-04-26 16:48 UTC, Dusch4593 commented on content/php/concepts/date-functions/terms/date-format/date-format.md
> +```php
```suggestion
```pseudo
```

2022-04-26 16:48 UTC, Dusch4593 commented on content/php/concepts/date-functions/terms/date-format/date-format.md
> +$datestring = date_format($object,$format);
```suggestion
$datestring = date_format($object, $format);
```

2022-04-26 16:48 UTC, Dusch4593 commented on content/php/concepts/date-functions/terms/date-format/date-format.md
> +  echo(date_format($date,"G:i l, F jS, Y"));
```suggestion
  echo(date_format($date, "G:i l, F jS, Y"));
```

2022-04-26 16:48 UTC, Dusch4593 commented on content/php/concepts/date-functions/terms/getdate/getdate.md
> +```php
```suggestion
```codebyte/php
```

2022-04-26 16:48 UTC, Dusch4593 commented on content/php/concepts/date-functions/terms/time/time.md
> +```php
```suggestion
```codebyte/php
```

2022-04-26 16:48 UTC, Dusch4593 commented on content/php/concepts/date-functions/terms/date/date.md
> +```php
```suggestion
```pseudo
```

2022-04-26 16:48 UTC, Dusch4593 commented on content/php/concepts/date-functions/terms/getdate/getdate.md
> +```php
```suggestion
```pseudo
```

2022-04-26 16:48 UTC, Dusch4593 commented on content/php/concepts/date-functions/terms/getdate/getdate.md
> +
What do we think about turning this list into a markdown table that looks similar to this?

```
| Member | Data Type | Description | Range |
| :-------: | :---------: | ----------- | ------- |
| `$t["seconds"]` | int | Number of seconds. | 0-59 |
| `$t["weekday"]` | string | Full name of the weekday. | "January" - "December" |
```

2022-04-28 11:56 UTC, SSwiniarski commented
@Dusch4593, I implemented all your suggestions.

2022-04-28 19:46 UTC, caupolicandiaz requested changes
@SSwiniarski looks pretty good, just some minor edits.

2022-04-28 19:46 UTC, caupolicandiaz commented on content/php/concepts/date-functions/date-functions.md
> +PHP manipulates dates in a number of ways, using arrays, strings, Unix timestamps, or `DateTime` objects. PHP provides a number of built-in functions manipulating dates using these various data types
```suggestion
PHP manipulates dates in a number of ways, using arrays, strings, Unix timestamps, or `DateTime` objects. PHP provides a number of built-in functions for manipulating dates using these various data types.
```

2022-04-28 19:46 UTC, caupolicandiaz commented on content/php/concepts/date-functions/terms/date-create/date-create.md
> +The below example creates `DateTime` objects using two different string formats.
```suggestion
The example below creates `DateTime` objects using two different string formats.
```

2022-04-28 19:46 UTC, caupolicandiaz commented on content/php/concepts/date-functions/terms/date/date.md
> +The below example prints the current date and time using the `date()` function.
```suggestion
The example below prints the current date and time using the `date()` function.
```

2022-04-28 19:46 UTC, caupolicandiaz commented on content/php/concepts/date-functions/terms/date-format/date-format.md
> +The below example creates as `DateTime` object, then prints the date with a format string.
```suggestion
The example below creates a `DateTime` object, then prints the date with a format string.
```

2022-04-28 19:46 UTC, caupolicandiaz commented on content/php/concepts/date-functions/terms/getdate/getdate.md
> +The below example gets an array from the `getdate()` function, and prints out various elements from it.
```suggestion
The example below gets an array from the `getdate()` function, and prints out various elements from it.
```

2022-04-28 19:46 UTC, caupolicandiaz commented on content/php/concepts/date-functions/terms/time/time.md
> +The below example prints out the Unix timestamp for the current date.
```suggestion
The example below prints out the Unix timestamp for the current date.
```

2022-04-28 22:43 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM! 👍🏻 

After addressing @caupolicandiaz's comments we should be good to merge. 😄

2022-04-29 11:13 UTC, SSwiniarski commented
@caupolicandiaz, @Dusch4593, done.

2022-05-03 20:32 UTC, SSwiniarski commented
@caupolicandiaz, are we good to merge?

2022-05-13 03:06 UTC, yangc95 approved these changes

2022-05-19 17:00 UTC, SSwiniarski commented
> @caupolicandiaz, are we good to merge?

Bump.

2022-05-19 23:24 UTC, caupolicandiaz approved these changes

2022-05-23 14:56 UTC, Dusch4593 commented
@SSwiniarski Looks good for merge! I made one small edit in 297ef053b072e029cdeda2052db7ae75ffa99bb4 where I moved the sentence in `date-create.md` out of the Codebyte snippet and placed above it.

2022-05-23 14:56 UTC, merged

2022-05-23 15:03 UTC, Dusch4593 commented
cc @SSwiniarski @caupolicandiaz @KTom101 @yangc95

Here are the live entry links:

- PHP Date Functions: https://www.codecademy.com/resources/docs/php/date-functions
- date_create(): https://www.codecademy.com/resources/docs/php/date-functions/date-create
- date_format(): https://www.codecademy.com/resources/docs/php/date-functions/date-format
- date(): https://www.codecademy.com/resources/docs/php/date-functions/date
- getdate(): https://www.codecademy.com/resources/docs/php/date-functions/getdate
- time(): https://www.codecademy.com/resources/docs/php/date-functions/time

If we find anything that needs updated, let's open a quick patch PR and we can review/merge the edits.