Add Entry: C++ Maps
Codecademy/docs pull request #724
Opened 2022-04-28 23:02 UTC by KTom101

New entry on C++ Maps and terms; keyword 19.

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-04-30 12:32 UTC, SSwiniarski requested changes
@KTom101, reviewed and left a few comments.

2022-04-30 12:32 UTC, SSwiniarski commented on content/cpp/concepts/maps/maps.md
> +map<type1, type2,  std::greater<dataType>> mapName { {key1, value1}, {key2, value2}, ...};
```suggestion
std::map <type1, type2,  std::greater<dataType>> mapName { {key1, value1}, {key2, value2}, ...};
```

2022-04-30 12:32 UTC, SSwiniarski commented on content/cpp/concepts/maps/maps.md
> +map<type1, type2> mapName;
```suggestion
std::map <type1, type2> mapName;
```

2022-04-30 12:32 UTC, SSwiniarski commented on content/cpp/concepts/maps/maps.md
> +map<type1, type2> mapName { {key1, value1}, {key2, value2}, ...};
```suggestion
std::map <type1, type2> mapName { {key1, value1}, {key2, value2}, ...};
```

2022-04-30 12:32 UTC, SSwiniarski commented on content/cpp/concepts/maps/maps.md
> +  std::map<std::string, int> emptyMap;
```suggestion
  std::map <std::string, int> emptyMap;
```

2022-04-30 12:32 UTC, SSwiniarski commented on content/cpp/concepts/maps/maps.md
> +  std::map<std::string, int> clothingStore {{"tshirt", 10}, {"pants", 12}, {"sweaters", 18}};
```suggestion
  std::map <std::string, int> clothingStore {{"tshirt", 10}, {"pants", 12}, {"sweaters", 18}};
```

2022-04-30 12:32 UTC, SSwiniarski commented on content/cpp/concepts/maps/maps.md
> +std::cout<< clothingStore["sweaters"]; // Output: 18
```suggestion
std::cout << clothingStore["sweaters"]; // Output: 18
```

2022-04-30 12:32 UTC, SSwiniarski commented on content/cpp/concepts/maps/maps.md
> +  std::map<int, std::string> :: iterator iter;
```suggestion
  std::map <int, std::string> :: iterator iter;
```

2022-04-30 12:32 UTC, SSwiniarski commented on content/cpp/concepts/maps/terms/clear/clear.md
> +  std::map<std::string, int> supplies {{"pen", 5}, {"pencils", 3}, {"paper", 12}};
```suggestion
  std::map <std::string, int> supplies {{"pen", 5}, {"pencils", 3}, {"paper", 12}};
```

2022-04-30 12:32 UTC, SSwiniarski commented on content/cpp/concepts/maps/terms/clear/clear.md
> +  std::cout<<supplies.size();
```suggestion
  std::cout << supplies.size();
```

2022-04-30 12:32 UTC, SSwiniarski commented on content/cpp/concepts/maps/terms/insert/insert.md
> +  std::map<std::string, int> :: iterator iter;
```suggestion
  std::map <std::string, int> :: iterator iter;
```

2022-04-30 12:32 UTC, SSwiniarski commented on content/cpp/concepts/maps/terms/remove/remove.md
> +The `.erase()` method removes an element by it's key from a map.
Is it `.erase()` or `.remove()`?

2022-04-30 12:32 UTC, SSwiniarski commented on content/cpp/concepts/maps/terms/remove/remove.md
> +  std::map<std::string, std::string> fields {{"zero", "0"}, {"one", "1"},  {"two", "2"}, {"three", "3"}};
```suggestion
  std::map <std::string, std::string> fields {{"zero", "0"}, {"one", "1"},  {"two", "2"}, {"three", "3"}};
```

2022-04-30 12:58 UTC, SSwiniarski requested changes

2022-04-30 12:58 UTC, SSwiniarski commented on content/cpp/concepts/maps/maps.md
> + std::map <int, std::string> reptiles {
```suggestion
 std::map<int, std::string> reptiles {
```

2022-04-30 12:58 UTC, SSwiniarski commented on content/cpp/concepts/maps/maps.md
> +std::map <type1, type2, std::greater<dataType>> mapName;
```suggestion
std::map<type1, type2, std::greater<dataType>> mapName;
```

2022-04-30 12:58 UTC, SSwiniarski commented on content/cpp/concepts/maps/maps.md
> + std::map <int, std::string, std::greater<int>> reptiles {
```suggestion
 std::map<int, std::string, std::greater<int>> reptiles {
```

2022-04-30 12:58 UTC, SSwiniarski commented on content/cpp/concepts/maps/terms/remove/remove.md
> +Title: '.remove()'
```suggestion
Title: '.erase()'
```

2022-04-30 12:58 UTC, SSwiniarski commented on content/cpp/concepts/maps/terms/remove/remove.md
> +Title: '.remove()'
If this is `.erase()` the file needs to be renamed.

2022-05-01 00:24 UTC, KTom101 commented
@SSwiniarski I believe I made all your changes including the one about the file name. Please make sure, though. I had an issue where some of the direct commits didn't go through. So I made some of the changes locally. Thanks!

2022-05-01 12:31 UTC, SSwiniarski approved these changes
Looks good for next review.

2022-05-04 13:30 UTC, Dusch4593 requested changes
@KTom101 Finished with my review and left some comments/suggestions.

2022-05-04 13:30 UTC, Dusch4593 commented on content/cpp/concepts/maps/terms/insert/insert.md
> +
Could we add a sentence or two here about the snippet above?

2022-05-04 13:30 UTC, Dusch4593 commented on content/cpp/concepts/maps/terms/clear/clear.md
> +
Could we add a sentence or two here about the snippet above?

2022-05-04 13:30 UTC, Dusch4593 commented on content/cpp/concepts/maps/maps.md
> +### Example
```suggestion
### Codebyte Example
```

2022-05-04 13:30 UTC, Dusch4593 commented on content/cpp/concepts/maps/maps.md
> +- `dataType` for the comparison function must be the same as `type1` which is the data type for the keys.
```suggestion
The `dataType` for the comparison function above must be the same as `type1` which is the data type for the keys.
```

2022-05-04 13:30 UTC, Dusch4593 commented on content/cpp/concepts/maps/maps.md
> +The above outputs the following:
```suggestion
The snippet above outputs the following:
```

2022-05-05 22:20 UTC, KTom101 commented
@Dusch4593 I think I've finished with your changes. Let me know if you want to switch things around.

2022-05-05 22:24 UTC, Dusch4593 approved these changes
@KTom101 LGTM! 👍🏻

2022-05-05 22:24 UTC, Dusch4593 commented
@yangc95 @caupolicandiaz does this PR need one more review before merge?

2022-05-10 19:22 UTC, caupolicandiaz reviewed
LGTM!

2022-05-10 19:28 UTC, merged

2022-05-10 19:33 UTC, Dusch4593 commented
Thank you so much for these new entries @KTom101! 🚀

Once the entries go live we can check them out with the links below:
C++: Maps - https://www.codecademy.com/resources/docs/cpp/maps
C++ Maps: .clear() - https://www.codecademy.com/resources/docs/cpp/maps/clear
C++ Maps: .erase() - https://www.codecademy.com/resources/docs/cpp/maps/erase
C++ Maps: .insert() - https://www.codecademy.com/resources/docs/cpp/maps/insert