New Entry : Regular Expressions
Codecademy/docs pull request #741
Opened 2022-05-08 13:50 UTC by SSwiniarski

### Description

Added a general Regular Expressions Entry, and a Java Regular expressions entry. From Target Keyword List.

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-05-20 22:51 UTC, KTom101 requested changes
@SSwiniarski I've added the first review for this.

2022-05-20 22:51 UTC, KTom101 commented on content/python/concepts/regex/regex.md
> +Description: 'Regex, short for Regular Expressions, is a powerful system for searching text.'
We should lowercase "regular expressions" to maintain the consistency we have.

```suggestion
Description: 'Regex, short for regular expressions, is a powerful system for searching text.'
```

2022-05-20 22:51 UTC, KTom101 commented on content/python/concepts/regex/regex.md
> +Regex, short for [Regular Expressions](https://www.codecademy.com/resources/docs/regular-expressions), is a powerful system for searching text. Regular expressions are implemented in a variety of lan
```suggestion
Regex, short for [regular expressions](https://www.codecademy.com/resources/docs/regular-expressions), is a powerful system for searching text. Regular expressions are implemented in a variety of languages including java and python.
```

2022-05-20 22:51 UTC, KTom101 commented on content/python/concepts/regex/terms/findall/findall.md
> +where `<pattern>` is a [regular expression](https://www.codecademy.com/resources/docs/regular-expressions) that can include any of the following:
```suggestion
Where `<pattern>` is a [regular expression](https://www.codecademy.com/resources/docs/regular-expressions) that can include any of the following:
```

2022-05-20 22:51 UTC, KTom101 commented on content/general/concepts/regular-expressions/regular-expressions.md
> +|      `?`      | Matches the preceding element zero or one time.                                                     | `co?t` matches "ct","cot" but not "coot"              |
```suggestion
|      `?`      | Matches the preceding element zero or one time.                                                     | `co?t` matches "ct", "cot" but not "coot"              |
```

2022-05-20 22:51 UTC, KTom101 commented on content/general/concepts/regular-expressions/regular-expressions.md
> +|   `{,max}`    | Matches the preceding element zero to `max` times.                                                  | `co{,2]t` matches "ct","cot","coot" but not "cooot"   |
```suggestion
|   `{,max}`    | Matches the preceding element zero to `max` times.                                                  | `co{,2]t` matches "ct", "cot", "coot" but not "cooot"   |
```

2022-05-20 22:51 UTC, KTom101 commented on content/general/concepts/regular-expressions/regular-expressions.md
> +|      `.`      | Matches any one character.                                                                          | `.` matches "c","a" and "t" in "cat"                  |
Add spacing after commas; I find it easier to read.
```suggestion
|      `.`      | Matches any one character.                                                                          | `.` matches "c", "a" and "t" in "cat"                  |
```

2022-05-20 22:51 UTC, KTom101 commented on content/general/concepts/regular-expressions/regular-expressions.md
> +|      `+`      | Matches the preceding element one or more times.                                                    | `co+t` matches "cot","coot" but not "ct"              |
```suggestion
|      `+`      | Matches the preceding element one or more times.                                                    | `co+t` matches "cot", "coot" but not "ct"              |
```

2022-05-20 22:51 UTC, KTom101 commented on content/general/concepts/regular-expressions/regular-expressions.md
> +A regular expression pattern is a string made up of normal characters mixed with metacharacters that have special meanings defining how characters should be matched. For instance, the pattern "h" by
```suggestion
A regular expression pattern is a string made up of normal characters mixed with metacharacters that have special meanings defining how characters should be matched. For instance, the pattern "h" by itself would match the single letter "h", whereas if we add the metacharacter ".", which matches any one character, then "h." would match sequences such as "ha", "ho", "h5" and "h!".
```

2022-05-20 22:51 UTC, KTom101 commented on content/java/concepts/regular-expressions/regular-expressions.md
> +  - 'Strings'
```suggestion
  - 'Regular Expressions'
  - 'Strings'
```

2022-05-21 11:07 UTC, SSwiniarski commented
@KTom101, I implemented your suggestions.

2022-05-21 16:22 UTC, KTom101 approved these changes
@SSwiniarski Looks good! It's ready for the next review.

2022-05-21 16:23 UTC, KTom101 commented
@yangc95, @Dusch4593 This is ready for a second review when you're ready.

2022-05-24 21:23 UTC, Dusch4593 requested changes
@SSwiniarski While reviewing, I noticed that you used the following link in the most of the files when referring to "regular expressions":

`https://www.codecademy.com/resources/docs/regular-expressions`

Was there supposed to be a topic entry about Regex?

2022-05-26 11:09 UTC, SSwiniarski commented
@Dusch4593, I completed your suggestions. Thanks for catching that link error.

2022-05-30 12:33 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM! 👍🏻

2022-06-03 12:35 UTC, Dusch4593 commented
@SSwiniarski About to merge but I made a change in 1a3918451045e46fef6a2bb79e3372c2c6483512 where I fixed the broken link to the General regex entry and removed the duplicate link.

2022-06-03 12:35 UTC, merged