Add Terms to Java Arrays
Codecademy/docs pull request #742
Opened 2022-05-08 15:59 UTC by SSwiniarski

### Description

From Target Keyword list. Added terms to Java Arrays.

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-05-20 00:47 UTC, KTom101 requested changes
@SSwiniarski Added a few changes to this entry.

2022-05-20 00:47 UTC, KTom101 commented on content/java/concepts/arrays/terms/fill/fill.md
> +  - 'Computer Science'
I think another subject should be added maybe 'Code Foundations'?
```suggestion
  - 'Code Foundations'
  - 'Computer Science'
```

2022-05-20 00:47 UTC, KTom101 commented on content/java/concepts/arrays/terms/sort/sort.md
> +  - 'Computer Science'
Same here, like in "fill.md", perhaps add a second subject:
```suggestion
  - 'Computer Foundations'
  - 'Computer Science'
```

2022-05-20 11:17 UTC, SSwiniarski commented
@KTom101, I implemented your suggestions.

2022-05-20 15:10 UTC, KTom101 approved these changes
@SSwiniarski  Nice! I'll pass this on for a second review.

2022-05-24 14:54 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM! Nothing to add 👍🏻

2022-05-25 16:42 UTC, merged