Added entry for HTML`<output>` tag
Codecademy/docs pull request #745
Opened 2022-05-10 20:02 UTC by Antonio-Riccelli

### Description

Closes #653 

### Type of Change

- Adding a new entry

Hi all, 
This is the first draft of the entry. I have run the format/lint scripts before pushing.

Please let me know all your suggestions and corrections. 

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-05-11 21:07 UTC, ethan-master-coding requested changes
@Antonio-Riccelli On lines 43-46 we should have all the attributes on one line because the other attributes are on 1 line for the other tags.

2022-05-13 00:25 UTC, ethan-master-coding requested changes
Forgot 1 thing. We like when there is a screenshot of the output of the example currently in the file.

2022-05-13 08:29 UTC, Antonio-Riccelli commented
@ethan-master-coding thanks for your feedback 👍I'm about to push the update.

It was all on one line initially, but I think the formatting/linting scripts changed that. Currently, it puts the closing tag on a new line, I'm not sure why. See below: 
![demo3](https://user-images.githubusercontent.com/39813213/168243520-9a8ddab5-d86b-4d8d-8ebd-d29cb3e8a5ce.gif)


As we want to add a picture, I thought of making the example a bit more descriptive, as the current one only showed a slider and a number. I added a label showing the actual value of the slider. This way it highlights the difference with the output.

A static image didn't really convey the example well, so I thought of making a gif. 

Let me know if this works, or else I can switch to a different and simpler example.

2022-05-13 11:40 UTC, ethan-master-coding approved these changes
@Antonio-Riccelli  Looks good. We may be able to use a `prettier ignore` or something similar so the checks still pass. A maintainer can help with that since I don't know it too well.

2022-05-13 15:14 UTC, SSwiniarski approved these changes
@Antonio-Riccelli, I did a first review, and I don't have any changes to suggest. On to review number 2.

2022-05-28 18:29 UTC, Antonio-Riccelli commented
Hi @SSwiniarski,
I was just wondering if there's anything else I should change on this to allow it to progress?

2022-05-29 11:10 UTC, SSwiniarski commented
We're just waiting on a second review.

2022-05-30 11:25 UTC, Dusch4593 requested changes
@Antonio-Riccelli Just had a few comments/suggestion for you but this looks great, otherwise! 😄

2022-05-30 11:25 UTC, Dusch4593 commented on content/html/concepts/tags/terms/output/output.md
> +The `<output>` tag is typically used inside of a `<form>` element to dynamically show the result of user input, but it can also be used on its own.
```suggestion
The `<output>` tag displays the result of a calculation or user action. It is commonly used inside of a [`<form>`](https://www.codecademy.com/resources/docs/html/tags/form) element to dynamically show the result of user input. However, the `<output>` tag can be used on its own.
```

2022-05-30 11:25 UTC, Dusch4593 commented on content/html/concepts/tags/terms/output/output.md
> +Description: 'Represents the result of a calculation or user action.'
```suggestion
Description: 'Displays the result of a calculation or user action.'
```

2022-06-01 12:40 UTC, Antonio-Riccelli commented
Thank you, @Dusch4593! Suggestions applied.

2022-06-02 15:48 UTC, Dusch4593 approved these changes
@Antonio-Riccelli LGTM! 👍🏻

2022-06-02 15:50 UTC, merged

2022-06-02 15:57 UTC, Dusch4593 commented
Congrats on another contribution to Docs, @Antonio-Riccelli 🙏🏻 🎊 🎉 When the entry goes live, it can be found with this link: https://www.codecademy.com/resources/docs/html/tags/output