New Term: Pandas `.fillna()`
Codecademy/docs pull request #747
Opened 2022-05-12 17:04 UTC by SSwiniarski

### Description

Method from the Target Keyword list I missed with the Pandas PR

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-05-23 14:43 UTC, Dusch4593 requested changes
@SSwiniarski Just a few comments/suggestion from me for this one. 😄

2022-05-23 16:06 UTC, SSwiniarski commented
@Dusch4593, I implemented your suggestions.

2022-05-24 00:20 UTC, KTom101 reviewed
@SSwiniarski This looks pretty much ready to merge, in my opinion. I just added a couple minor things.

2022-05-24 00:20 UTC, KTom101 commented on content/pandas/concepts/dataframe/terms/fillna/fillna.md
> +In the following example, the `.fillna()` method is used in to fill `NA` values in a DataFrame first with a scalar, then with a dict:
```suggestion
In the following example, the `.fillna()` method is used to fill in `NA` values in a DataFrame first with a scalar, then with a dict:
```

2022-05-24 11:18 UTC, SSwiniarski commented
@KTom101, I implemented your suggestions.

2022-05-24 21:47 UTC, Dusch4593 approved these changes

2022-05-25 00:55 UTC, KTom101 approved these changes
@SSwiniarski This looks like it's ready to merge. 
@Dusch4593 How does it look to you?

2022-05-25 17:13 UTC, merged