New Term: C++ Sting `.replace()`
Codecademy/docs pull request #750
Opened 2022-05-14 13:54 UTC by SSwiniarski

### Description

From Target Keyword list

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-05-20 16:16 UTC, KTom101 reviewed
@SSwiniarski I only see one thing I would change.

2022-05-20 16:16 UTC, KTom101 commented on content/cpp/concepts/strings/terms/replace/replace.md
> +basestring.replace(pos, len, str, subpos, sublen)
Can we use camelcase for "basestring" in the syntax? I feel it's a little bit easier to read.
```suggestion
baseString.replace(pos, len, str, subpos, sublen)
```

2022-05-20 16:16 UTC, KTom101 commented on content/cpp/concepts/strings/terms/replace/replace.md
> +- `basestring` is the string whose contents are being replaced.
```suggestion
- `baseString` is the string whose contents are being replaced.
```

2022-05-21 11:10 UTC, SSwiniarski commented
@KTom101, I went and committed your suggestion.

2022-05-21 17:40 UTC, KTom101 approved these changes
@SSwiniarski Let's get this to the 2nd review!

2022-05-24 21:25 UTC, Dusch4593 requested changes
@SSwiniarski Just had one suggestion but nothing else to add 😄

2022-05-24 21:25 UTC, Dusch4593 commented on content/cpp/concepts/strings/terms/replace/replace.md
> +- `sublen` is optional, and is the number of replacement characters used from `str`
```suggestion
- `sublen` is optional, and is the number of replacement characters used from `str`.
```

2022-05-26 11:11 UTC, SSwiniarski commented
@Dusch4593, done!

2022-05-30 12:34 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM! 👍🏻

2022-06-03 12:48 UTC, merged