New Term: C++ Strings `.substr()`
Codecademy/docs pull request #752
Opened 2022-05-15 13:07 UTC by SSwiniarski

### Description

From Target Keyword List: C++ Strings `.substr()`
### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-05-24 11:15 UTC, SSwiniarski commented
@KTom101, I implemented your suggestions.

2022-05-25 00:44 UTC, KTom101 approved these changes
@SSwiniarski Time for a second review.

2022-05-25 17:11 UTC, Dusch4593 requested changes
@SSwiniarski Just one requested change and then I think this should be good to go! 👍🏻

2022-05-25 17:11 UTC, Dusch4593 commented on content/cpp/concepts/strings/terms/substr/substr.md
> +```codebyte\cpp
```suggestion
```codebyte/cpp
```

2022-05-26 11:13 UTC, SSwiniarski commented
@Dusch4593, Done!

2022-05-30 12:39 UTC, Dusch4593 requested changes
@SSwiniarski One _super small_ suggestion but then I think we're good after that.

2022-05-30 12:39 UTC, Dusch4593 commented on content/cpp/concepts/strings/terms/substr/substr.md
> +- `basestring` is the string whose substring is being returned.
I noticed in #750 that we used `baseString` (capital "S") instead of lowercase `basestring`. Can we pick one of the other?

2022-05-30 14:57 UTC, SSwiniarski commented
@Dusch4593, done!

2022-06-02 14:08 UTC, merged