Made a bunch of edits
Codecademy/docs pull request #772
Opened 2022-05-28 02:11 UTC by ethan-master-coding

### Description

Added more file formats and put them into separate tables.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- 
### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-05-28 13:41 UTC, ethan-master-coding commented
@yangc95 2 things.

1. Should they be in alphabetical order?
2. Should we have a secret table for Microsoft formats. Excel, Word, PowerPoint ect.

2022-05-31 16:33 UTC, SSwiniarski requested changes
@ethan-master-coding, Reviewed and have a couple of comments.

2022-05-31 16:33 UTC, SSwiniarski commented on content/general/concepts/file-formats/file-formats.md
> +| Executable                                                                              | **.exe**  | Contains and executable.
```suggestion
| Executable                                                                              | **.exe**  | Contains an executable.                                                                                     |
```

2022-05-31 16:33 UTC, SSwiniarski commented on content/general/concepts/file-formats/file-formats.md
> +| Zip                                                                                     | **.zip**  | Compresses files into a fold that can be uncompresed into its original form.
```suggestion
| Zip                                                                                     | **.zip**  | Compresses files into a folder that can be uncompressed into its original form.                                 |
```

2022-06-01 16:44 UTC, yangc95 commented
> @yangc95 2 things.
> 
> 
> 
> 1. Should they be in alphabetical order?
> 
> 2. Should we have a secret table for Microsoft formats. Excel, Word, PowerPoint ect.

@ethan-master-coding
Alphabetical order would be great!

What do you mean be secret table?

2022-06-02 22:55 UTC, yangc95 reviewed
@ethan-master-coding thanks for working on this! Just a few more comments/suggestions.

2022-06-02 22:55 UTC, yangc95 commented on content/general/concepts/file-formats/file-formats.md
> +| JS (Javascript)                                                                         | **.js**   | Contains a Javasript program.
```suggestion
| JS (JavaScript)                                                                         | **.js**   | Contains a JavaScript program.                                                                                |
```

2022-06-02 22:55 UTC, yangc95 commented on content/general/concepts/file-formats/file-formats.md
> +| Python                                                                                  | **.py**   | Contrains a Python program.
```suggestion
| Python                                                                                  | **.py**   | Contains a Python program.                                                                                  |
```

2022-06-02 23:48 UTC, ethan-master-coding commented
@yangc95 All edits look good. I accepted the changes and made the requested changes.

2022-06-03 14:52 UTC, Dusch4593 requested changes
@ethan-master-coding just one general comment/suggestion pertaining to the [style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) mentioned previously.

2022-06-03 14:52 UTC, Dusch4593 commented on content/general/concepts/file-formats/file-formats.md
> +| [C++](https://www.codecademy.com/resources/docs/cpp)                                    | **.cpp**  | Conatins a C++ program.
Instead of being in **bold**, these extensions should be in `back-ticks`.

~**.cpp**~ -> `.cpp`

2022-06-03 15:02 UTC, Dusch4593 requested changes
A few last things - let's also remove these spaces in the hyperlinks (I think this is what's causing the lint check to fail)

2022-06-03 15:02 UTC, Dusch4593 commented on content/general/concepts/file-formats/file-formats.md
> +| [Go ](https://www.codecademy.com/resources/docs/go)                                     | `.go`     | Conatins a Go program.
```suggestion
| [Go](https://www.codecademy.com/resources/docs/go)                                     | `.go`     | Conatins a Go program.                                                                                       |
```

2022-06-03 15:02 UTC, Dusch4593 commented on content/general/concepts/file-formats/file-formats.md
> +| [PHP (Hypertext Preprocessor)  ](https://www.codecademy.com/resources/docs/php)         | `.php`    | Contains a PHP program.
```suggestion
| [PHP (Hypertext Preprocessor)](https://www.codecademy.com/resources/docs/php)         | `.php`    | Contains a PHP program.                                                                                      |
```

2022-06-03 17:07 UTC, ethan-master-coding commented
@Dusch4593 All edits look good. I accepted the changes.

2022-06-03 17:32 UTC, Dusch4593 approved these changes
LGTM! 👍🏻 Anything to add @SSwiniarski @yangc95 ?

2022-06-03 21:20 UTC, ethan-master-coding commented
@Dusch4593 And out of curiosity what is the free team exactly?

Also you forgot to remove the waiting on OP label.

2022-06-04 11:11 UTC, SSwiniarski approved these changes
@ethan-master-coding, Looks good!

2022-06-04 13:32 UTC, Dusch4593 commented
> @Dusch4593 And out of curiosity what is the free team exactly?

The free team is the group that I specifically work with at CC. Reviewers like myself, @yangc95, and @SSwiniarski are part of this team.

2022-06-04 14:02 UTC, Dusch4593 requested changes
@ethan-master-coding Catch a few typos that need fixed before we merge. Also, this is kind of nit-picky, but could we alphabetize the rows under "Programming File Formats", "Image File Formats", and "Other File Formats" by `File Format`?

2022-06-04 14:02 UTC, Dusch4593 commented on content/general/concepts/file-formats/file-formats.md
> +### Image file formats
```suggestion
### Image File Formats
```

2022-06-04 14:02 UTC, Dusch4593 commented on content/general/concepts/file-formats/file-formats.md
> +### Other file formats
```suggestion
### Other File Formats
```

2022-06-04 14:21 UTC, ethan-master-coding commented
@Dusch4593 I believe I already alphabetize it.

2022-06-04 14:29 UTC, Dusch4593 commented
> @Dusch4593 I believe I already alphabetize it.

I would check them again because last time I did, for example, `.html` was all the way at the bottom of the "Programming File Formats" table between "S" and "T".

> And a lot of issues need to be labled

Will do, but I think working on these open PRs is the higher priority right now.

2022-06-04 14:38 UTC, ethan-master-coding commented
@Dusch4593 Put them in order

2022-06-04 14:41 UTC, Dusch4593 commented
> @Dusch4593 Put them in order

Not quite. Can we check again?
<img width="1358" alt="Screen Shot 2022-06-04 at 10 40 19 AM" src="https://user-images.githubusercontent.com/23144845/172007872-1cca2806-8239-4931-ab82-30a1ae5c59f4.png">

2022-06-04 14:45 UTC, ethan-master-coding commented
@Dusch4593 fixed everthing I think

2022-06-04 15:00 UTC, Dusch4593 commented
> @Dusch4593 fixed everthing I think

Appreciated! There were a few last rows that needed re-sorted but I took care of it in 54bda41547ea858b34ee041e7f1fd2a7843807be

2022-06-04 15:01 UTC, Dusch4593 approved these changes

2022-06-04 15:02 UTC, merged

2022-06-04 15:03 UTC, ethan-master-coding commented
Link to the entry: https://www.codecademy.com/resources/docs/general/file-formats