New Term: NumPy `.sum()`
Codecademy/docs pull request #773
Opened 2022-05-28 15:18 UTC by SSwiniarski

### Description

New keyword entry

### Type of Change

- New Entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-06-03 14:33 UTC, Dusch4593 requested changes
@SSwiniarski Finished with my review and left some comments/suggestions.

2022-06-03 14:33 UTC, Dusch4593 commented on content/numpy/concepts/built-in-functions/terms/sum/sum.md
> +- `where` : A boolean array that maps to `array` and selects elements to include into the sum.
```suggestion
- `axis`: An int or tuple of ints specifying the axis/axes along which to sum.
- `dtype`: The type of the returned array and the accumulator used to sum elements. Defaults to the dtype of `array`.
- `out`: An [`ndarray`](https://www.codecademy.com/resources/docs/numpy/ndarray) to receive result. Must have the same shape as expected output.
- `keepdims`: A boolean if true will keep reduced axes in the result as dimensions with size one.
- `inital`: The starting value for sum.
- `where`: A boolean array that maps to `array` and selects elements to include into the sum.
```

2022-06-03 14:33 UTC, Dusch4593 commented on content/numpy/concepts/built-in-functions/terms/sum/sum.md
> +[ 6 15]
```suggestion
21
[5 7 9]
[ 6 15]
```

2022-06-03 14:33 UTC, Dusch4593 commented on content/numpy/concepts/built-in-functions/terms/sum/sum.md
> +All arguments except `a`, the array of elements to sum, are optional. Using `a` by itself will result in a scalar that sums all the elements of the array.
```suggestion
The `a` argument is required and represents the array of elements to sum. All other arguments are optional. Used by itself, `a` will result in a scalar that sums all the elements of the array.
```

2022-06-03 14:33 UTC, Dusch4593 commented on content/numpy/concepts/built-in-functions/terms/sum/sum.md
> +- `a`: the array of elements to sum.
```suggestion
- `a`: The array of elements to sum.
```

2022-06-03 14:33 UTC, Dusch4593 commented on content/numpy/concepts/built-in-functions/terms/sum/sum.md
> +The following example creates an array then uses some `.sum` operations to sum the elements.
```suggestion
The following example creates an array then uses a few `.sum()` operations to sum the elements.
```

2022-06-04 10:44 UTC, SSwiniarski commented
@Dusch4593, I applied your changes.

2022-06-04 13:25 UTC, Dusch4593 approved these changes
@SSwiniarski Just one tiny suggestion but LGTM otherwise 👍🏻

2022-06-04 13:25 UTC, Dusch4593 commented on content/numpy/concepts/built-in-functions/terms/sum/sum.md
> +```python
```suggestion
```py
```

2022-06-04 14:26 UTC, SSwiniarski commented
@Dusch4593, done!

2022-06-04 20:16 UTC, KTom101 approved these changes
@SSwiniarski No changes from me.

cc @Dusch4593

2022-06-04 22:24 UTC, merged