Updates To JSON Entries
Codecademy/docs pull request #780
Opened 2022-06-04 12:05 UTC by SSwiniarski

### Description

Revision of my last PR, that crossed streams with another General JSON entry PR. This version merges the last PR with the new General JSON entry

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-06-04 22:53 UTC, Dusch4593 requested changes
@SSwiniarski Only one suggestion from me 😄

2022-06-04 22:53 UTC, Dusch4593 commented on content/general/concepts/json/json.md
> +}
```suggestion
{
  "make" : "Chevy",
  "model" : "Silverado",
  "miles" : 27500,
  "year" : 2020,
  "owner" : {
    "firstName" : "John",
    "lastName" : "Doe"
   },
  "features" : ["4WD", "Towing Package", "Lift Kit"],
  "lease" : false
}
```

2022-06-05 10:40 UTC, SSwiniarski commented
@Dusch4593, I applied your suggestion.

2022-06-05 10:46 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM! 👍🏻 Just one small suggestion, but I think this is ready for at least one more review.

2022-06-05 10:46 UTC, Dusch4593 commented on content/general/concepts/json/json.md
> +JavaScript Object Notation (JSON) is a data format that is readable, writable, and parsable for both humans and machines. JSON is based on the syntax of the third edition of [JavaScript](https://www.
```suggestion
**JavaScript Object Notation (JSON)** is a data format that is readable, writable, and parsable for both humans and machines. JSON is based on the syntax of the third edition of [JavaScript](https://www.codecademy.com/resources/docs/javascript) (ECMA-262) that was released back in December 1999. However, it is language-independent. Many programming languages, such as [Python](https://www.codecademy.com/resources/docs/python), have implemented [libraries](https://www.codecademy.com/resources/docs/python/json-module) to parse and generate JSON-formatted data.
```

One last super minor suggestion, per our updated [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/#bold) re: bolded text.

2022-06-05 14:39 UTC, SSwiniarski commented
@Dusch4593, committed last suggestion.

2022-06-05 16:14 UTC, Dusch4593 requested changes
@SSwiniarski Just one suggestion 😄

2022-06-05 16:14 UTC, Dusch4593 commented on content/general/concepts/json/json.md
> +- `null`: An empty value represented by the word `null`.
```suggestion
- [Array](https://www.codecademy.com/resources/docs/general/array): An ordered, comma delimited, list of zero or more elements of one of JSON's data types, enclosed in square brackets.
- [Boolean](https://www.codecademy.com/resources/docs/general/boolean): Either `true` or `false`.
- [Number](https://www.codecademy.com/resources/docs/general/number): A signed decimal number. JSON makes no distinction between integer and floating point.
- [Object](https://www.codecademy.com/resources/docs/general/object): A collection of name-value pairs inside curly brackets.
- [String](https://www.codecademy.com/resources/docs/general/string): A sequence of zero or more Unicode characters enclosed in double quotes.
- `null`: An empty value represented by the word `null`.
```

2022-06-05 18:33 UTC, SSwiniarski commented
@Dusch4593, done. Any more suggestions?

2022-06-07 20:03 UTC, caupolicandiaz requested changes
@SSwiniarski looks pretty good, just a minor comment

2022-06-08 10:58 UTC, SSwiniarski commented
@caupolicandiaz, I implemented your suggestion.

2022-06-08 13:24 UTC, Dusch4593 commented
@SSwiniarski I just merged #789 and the [general JSON entry](https://www.codecademy.com/resources/docs/general/json) should be updated. Sorry about crossing the streams with this one (again on my part). Fwiw, I transferred every change you'd made in this PR.

To avoid resolving conflicts, I'm going to delete the `json.md` file from this PR and then we can continue with the other files. 😄

2022-06-08 16:31 UTC, SSwiniarski commented
@Dusch4593, I updated the json.md in this branch so it matches the current one, so now it's just a couple of added links. @caupolicandiaz, if yo can approve this, I think we can merge.

2022-06-08 19:47 UTC, caupolicandiaz reviewed
@SSwiniarski looks pretty good, just one small edit

2022-06-08 19:47 UTC, caupolicandiaz commented on content/general/concepts/json/json.md
> +JSON is commonly used for transferring data between clients and servers for tasks such as web browsing or form submission. Some companies also use JSON to allow their data to use in other application
```suggestion
JSON is commonly used for transferring data between clients and servers for tasks such as web browsing or form submission. Some companies also use JSON to allow their data to be accessed in other applications via [API](https://www.codecademy.com/resources/docs/general/api). Some examples include:
```

2022-06-15 17:29 UTC, caupolicandiaz approved these changes
@Dusch4593 good to go

2022-06-15 17:34 UTC, merged