New Entry: C Operators
Codecademy/docs pull request #782
Opened 2022-06-05 11:21 UTC by SSwiniarski

### Description

From target keyword list.
### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-06-05 16:35 UTC, Dusch4593 requested changes
@SSwiniarski Finished with my review and left some comments/suggestions.

2022-06-05 16:35 UTC, Dusch4593 commented on content/c/concepts/operators/operators.md
> +Operators are used to perform operations on variables and values. They are symbols that tell the compiler to perform specific mathematical or logical functions. The C language provides the following
```suggestion
**Operators** are used to perform operations on variables and values. They are symbols that tell the compiler to perform specific mathematical or logical functions. The C language provides the following types of operators:
```

2022-06-05 16:35 UTC, Dusch4593 commented on content/c/concepts/operators/operators.md
> +| -------- | -------------- | ----------------------------------------------------------- |
```suggestion
| :--------: | :--------------: | ----------------------------------------------------------- |
```

2022-06-05 16:35 UTC, Dusch4593 commented on content/c/concepts/operators/operators.md
> +| -------- | ------------------------ | ---------------------------------------------------------- |
```suggestion
| :--------: | :------------------------: | ---------------------------------------------------------- |
```

2022-06-05 16:35 UTC, Dusch4593 commented on content/c/concepts/operators/operators.md
> +| -------- | ---- | ------------------------------------------------------------------ |
```suggestion
| :--------: | :----: | ------------------------------------------------------------------ |
```

2022-06-05 16:35 UTC, Dusch4593 commented on content/c/concepts/operators/operators.md
> +| -------- | ----------- | -------------------------------------------------------------- |
```suggestion
| :--------: | :-----------: | -------------------------------------------------------------- |
```

2022-06-05 16:35 UTC, Dusch4593 commented on content/c/concepts/operators/operators.md
> +| -------- | ------------------------- | ------------------------------------------ |
```suggestion
| :--------: | :-------------------------: | ------------------------------------------ |
```

2022-06-05 16:35 UTC, Dusch4593 commented on content/c/concepts/operators/operators.md
> +| ---------- | ---------------------- | ------------------------------------------------------------------------------- |
```suggestion
| :----------: | :----------------------: | ------------------------------------------------------------------------------- |
```

2022-06-05 18:45 UTC, SSwiniarski commented
@Dusch4593, I applied your suggestions.

2022-06-06 12:19 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM! 👍🏻

2022-06-08 22:12 UTC, KTom101 reviewed
@SSwiniarski Looks good. I only have a couple suggestions.

2022-06-10 21:40 UTC, KTom101 approved these changes

2022-06-10 22:51 UTC, merged