New Term: NumPy `.linspace()`
Codecademy/docs pull request #785
Opened 2022-06-05 19:34 UTC by SSwiniarski

### Description

From Target Keyword list.
### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-06-09 19:26 UTC, KTom101 requested changes
@SSwiniarski I took a look at this and left a review, thanks!

2022-06-09 19:26 UTC, KTom101 commented on content/numpy/concepts/built-in-functions/terms/linspace/linspace.md
> +- `dtype`: The `dtype` of the returned array, if omitted, dtype is inferred from `start` and `stop`. Defaults to `None`.
```suggestion
- `dtype`: The `dtype` of the returned array, if omitted, `dtype` is inferred from `start` and `stop`. Defaults to `None`.
```

2022-06-09 19:26 UTC, KTom101 commented on content/numpy/concepts/built-in-functions/terms/linspace/linspace.md
> +- `axis`: If `start` and `stop` are arrays, specifies on what axis the values will be added. If `0` the axis is added at the beginning. If `-1` it's added at the end. Defaults to `0`.
```suggestion
- `axis`: If `start` and `stop` are arrays, this specifies on what axis the values will be added. If `0` the axis is added at the beginning. If `-1` it's added at the end. Defaults to `0`.
```

2022-06-09 19:26 UTC, KTom101 commented on content/numpy/concepts/built-in-functions/terms/linspace/linspace.md
> +```
Can we add another example where `start` and `stop` are arrays?

2022-06-10 11:07 UTC, SSwiniarski commented
@KTom101, I implemented your suggestions.

2022-06-10 21:16 UTC, KTom101 approved these changes
@SSwiniarski I'll pass this on to a second reviewer!

2022-06-10 22:48 UTC, Dusch4593 requested changes
@SSwiniarski Just one suggestion 😄

2022-06-10 22:48 UTC, Dusch4593 commented on content/numpy/concepts/built-in-functions/terms/linspace/linspace.md
> +
```suggestion
print(result3)
```

2022-06-11 02:54 UTC, yangc95 commented
Taking a look as well, will tag you once I'm fin~

2022-06-11 02:56 UTC, yangc95 commented on content/numpy/concepts/built-in-functions/terms/linspace/linspace.md
> +- `endpoint`: Boolean flag. If `True` then `stop` is included as the last value. If `False`, `stop` is excluded. Defaults to `True`.
```suggestion
- `endpoint`: Boolean flag. If `True`, `stop` is included as the last value. If `False`, `stop` is excluded. Defaults to `True`.
```

2022-06-11 03:01 UTC, yangc95 reviewed
Minor suggestions @SSwiniarski 🙏

2022-06-11 10:47 UTC, SSwiniarski commented
@yangc95, I implemented your changes. @Dusch4593: Your suggestion didn't actually change anything, what is it you wanted to do?

2022-06-11 21:02 UTC, yangc95 commented
@SSwiniarski thanks! I think @Dusch4593's suggestion was just to remove the extra line in that code block

2022-06-11 21:04 UTC, yangc95 commented on content/numpy/concepts/built-in-functions/terms/linspace/linspace.md
> +
```suggestion
```

2022-06-11 21:05 UTC, yangc95 approved these changes

2022-06-13 12:11 UTC, Dusch4593 approved these changes
LGTM! 👍🏻

2022-06-13 12:12 UTC, merged