[New Term Entry]: Java String `.format()` method
Codecademy/docs pull request #809
Opened 2022-06-15 04:30 UTC by yangc95

### Description

New term entry for `.format()` method, as per Keywords 🔑 
Trying to also figure out if the format specifiers need a separate entry eventually. I noted that there's only one other chart like this on in C | Basic Output.

### Type of Change

- Adding a new term entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-06-15 04:31 UTC, yangc95 commented on content/java/concepts/strings/terms/format/format.md
> +Description: 'The .format() method returns a string with additional arguments in a specifically defined format'
```suggestion
Description: 'Returns a string with additional arguments in a specifically defined format'
```

2022-06-15 04:35 UTC, yangc95 commented on content/java/concepts/strings/terms/format/format.md
> +**Note:** `NullPointerException` will be thrown if the format is `null`. An `IllegalFormatException` will be thrown if the specifier and argument don't match or the specifier does not exist.
```suggestion
**Note:** `NullPointerException` will be thrown if the format is `null`. An `IllegalFormatException` will be thrown if the specifier and argument do not match or the specifier does not exist.
```

2022-06-15 13:04 UTC, Dusch4593 requested changes
@yangc95 finished my review and left you a few comments/suggestions 😄

2022-06-15 13:04 UTC, Dusch4593 commented on content/java/concepts/strings/terms/format/format.md
> +The `.format()` method returns a string with additional arguments in a specifically defined format.
```suggestion
The **`.format()`** method returns a string with additional arguments in a specifically defined format.
```

2022-06-15 13:04 UTC, Dusch4593 commented on content/java/concepts/strings/terms/format/format.md
> +string.format(String str, ...args)
```suggestion
string.format(String str, ...args);
```

2022-06-15 13:04 UTC, Dusch4593 commented on content/java/concepts/strings/terms/format/format.md
> +| ---------------- | -------- |
```suggestion
| :----------------: | :--------: |
```

2022-06-15 13:04 UTC, Dusch4593 commented on content/java/concepts/strings/terms/format/format.md
> +## Format Specifiers
```suggestion
### Format Specifiers
```

Wondering if this should be a lv. 3 header since this sort of falls under "syntax"?

2022-06-16 01:50 UTC, yangc95 commented
@Dusch4593 took a look! I'll run the format script right before merge btw~

2022-06-16 02:01 UTC, Dusch4593 approved these changes
LGTM! 👍

2022-06-16 16:38 UTC, SSwiniarski commented
@yangc95, FYI, this has a lot of overlap with the `.printf()` entry in [796](https://github.com/Codecademy/docs/pull/796). Yo might want to pull from that entry, which covers most of the formatting specifier info.

2022-06-22 23:07 UTC, yangc95 commented
@SSwiniarski I added a line after the format table referring to the `.printf()` method, let me know if this is sufficient! I still think it'd be helpful to keep the table here for basic examples

2022-06-27 19:32 UTC, KTom101 approved these changes
@yangc95 Looks good. I only added a couple of commas. 😄

2022-06-27 19:32 UTC, KTom101 commented on content/java/concepts/strings/terms/format/format.md
> +- `args` is an optional argument which can be of any data type to be returned with the first string argument.
```suggestion
- `args` is an optional argument, which can be of any data type, to be returned with the first string argument.
```

2022-07-06 12:46 UTC, merged

2022-07-06 12:48 UTC, KTom101 approved these changes
@yangc95 If there aren't any other last-minute changes, this looks good to merge as-is. Update: just saw you merged as I was writing this lol 👍