New Entry: General Endianness
Codecademy/docs pull request #821
Opened 2022-06-21 16:27 UTC by SSwiniarski

### Description

From Target Keyword List

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-06-25 14:15 UTC, Dusch4593 requested changes
@SSwiniarski Just a few comments/suggestions from me 😄

2022-06-25 14:15 UTC, Dusch4593 commented on content/general/concepts/endianness/endianness.md
> +Endianness is a description of the order bytes are stored in memory for multi-byte values. The options are generally described as big-endian or little-endian. A big-endian system stores the most sign
```suggestion
**Endianness** describes the order in which bytes are stored in memory for multi-byte values. The options are generally described as big-endian or little-endian. A big-endian system stores the most significant byte at the smallest memory address and the least significant byte at the largest. A little-endian system stores the least significant byte at the smallest memory address and the most significant byte at the largest.
```

2022-06-25 14:15 UTC, Dusch4593 commented on content/general/concepts/endianness/endianness.md
> +To store the 32-bit integer `0x0A0B0C0D` it is broken down into four bytes `0x0A`,`0x0B`,`0x0C`,`0x0D`. The endianness of the computer system defines in what order these bytes are stored in memory. T
```suggestion
To store the 32-bit integer `0x0A0B0C0D` it is broken down into four bytes:

- `0x0A`
- `0x0B`
- `0x0C`
- `0x0D`

The endianness of the computer system defines in what order these bytes are stored in memory. The following examples show it stored at memory address `0xFFF0` for both big- and little-endian systems:
```

2022-06-25 14:15 UTC, Dusch4593 commented on content/general/concepts/endianness/endianness.md
> +Description: 'Endianness is a description of the order bytes are stored in memory for multi-byte values.'
```suggestion
Description: 'Endianness describes the order in which bytes are stored in memory for multi-byte values.'
```

2022-06-25 14:37 UTC, SSwiniarski commented
@Dusch4593, I implemented your suggestions.

2022-06-25 14:48 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM for one more review 👍🏻

2022-06-28 20:03 UTC, KTom101 approved these changes
@SSwiniarski I don't see any edits that are needed. I've suggested a comma in one spot.

2022-06-28 21:00 UTC, SSwiniarski commented
@KTom101, I inserted your comma.

2022-06-29 13:20 UTC, merged