Modify string length/size entries
Codecademy/docs pull request #830
Opened 2022-06-30 15:59 UTC by Dusch4593

### Description

For SEO keyword efforts

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-07-01 11:14 UTC, SSwiniarski requested changes
@Dusch4593, I did a first review and only had a couple of comments.

2022-07-01 11:14 UTC, SSwiniarski commented on content/php/concepts/string-functions/terms/strlen/strlen.md
> +Description: 'Returns the number of byte in a given string.'
```suggestion
Description: 'Returns the number of bytes in a given string.'
```

2022-07-01 11:40 UTC, Dusch4593 commented
@SSwiniarski Implemented your feedback 😄

2022-07-02 11:13 UTC, SSwiniarski approved these changes
@Dusch4593, Looks good for review two.

2022-07-02 17:50 UTC, KTom101 requested changes
@Dusch4593 Added a few changes!

2022-07-02 17:50 UTC, KTom101 commented on content/c/concepts/strings/terms/strlen/strlen.md
> +The **`strlen()`** string function returns the length of the string without including terminating character `'\n'`.
```suggestion
The **`strlen()`** string function returns the length of the string without including the terminating character, `'\n'`.
```

2022-07-02 17:50 UTC, KTom101 commented on content/javascript/concepts/strings/strings.md
> +In JavaScript, multiple strings can be concatenated, or joined, together using the `+` [operator](https://www.codecademy.com/resources/docs/javascript/operators).
```suggestion
In JavaScript, multiple strings can be concatenated or joined together using the `+` [operator](https://www.codecademy.com/resources/docs/javascript/operators).
```

2022-07-02 17:50 UTC, KTom101 commented on content/javascript/concepts/strings/strings.md
> +In the example below, multiple strings and variables containing string values have been concatenated. After code block is run, the `displayText` variable will contain the concatenated string:
```suggestion
In the example below, multiple strings and variables containing string values have been concatenated. After the code block is run, the `displayText` variable will contain the concatenated string:
```

2022-07-02 17:50 UTC, KTom101 commented on content/javascript/concepts/strings/terms/length/length.md
> +The `string` can either be a literal sequence of characters surrounded in quotes or a variable that refers to such a sequence.
```suggestion
The `string` can either be a literal sequence of characters surrounded by quotes or a variable that refers to such a sequence.
```

2022-07-02 17:50 UTC, KTom101 commented on content/php/concepts/string-functions/terms/strlen/strlen.md
> +The `string` can either be a literal sequence of characters surrounded in quotes or a variable that refers to such a sequence.
```suggestion
The `string` can either be a literal sequence of characters surrounded by quotes or a variable that refers to such a sequence.
```

2022-07-02 17:50 UTC, KTom101 commented on content/php/concepts/string-functions/terms/strlen/strlen.md
> +In the following example showcases the two ways of using the `strlen()` method:
```suggestion
The following example showcases the two ways of using the `strlen()` method:
```

2022-07-02 17:50 UTC, KTom101 commented on content/ruby/concepts/strings/terms/length/length.md
> +The `string` can either be a literal sequence of characters surrounded in quotes or a variable that refers to such a sequence.
```suggestion
The `string` can either be a literal sequence of characters surrounded by quotes or a variable that refers to such a sequence.
```

2022-07-02 17:50 UTC, KTom101 commented on content/cpp/concepts/strings/terms/size/size.md
> +The **`.size()`** method returns the size of a given string in terms of bytes. It functions just like the [`.length()`](https://www.codecademy.com/resources/docs/python/strings/length) method, but `.
```suggestion
The **`.size()`** method returns the size of a given string in terms of bytes. It functions just like the [`.length()`](https://www.codecademy.com/resources/docs/python/strings/length) method, but `.size()` is there to follow the consistency of other standard library containers (e.g., [maps](https://www.codecademy.com/resources/docs/cpp/maps) and [vectors](https://www.codecademy.com/resources/docs/cpp/vectors)).
```

2022-07-02 17:50 UTC, KTom101 commented on content/cpp/concepts/strings/terms/size/size.md
> +The `string` must be defined with `std::string` prior to using to the `.size()` method.
```suggestion
The `string` must be defined with `std::string` prior to using with the `.size()` method.
```

2022-07-05 13:25 UTC, Dusch4593 commented
@KTom101 Finished implementing your suggested changes 😄

2022-07-05 16:31 UTC, KTom101 approved these changes
@Dusch4593 just one more thing but otherwise looks great!

2022-07-05 16:31 UTC, KTom101 commented on content/cpp/concepts/strings/terms/length/length.md
> +The `string` must be defined with `std::string` prior to using to the `.length()` method.
```suggestion
The `string` must be defined with `std::string` prior to using with the `.length()` method.
```

2022-07-05 18:43 UTC, merged