New Entries: Java Comparator & Comparable
Codecademy/docs pull request #832
Opened 2022-06-30 19:43 UTC by SSwiniarski

### Description

From the Target Keyword List

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-06-30 21:22 UTC, Dusch4593 requested changes
@SSwiniarski Finished my review. I left some comments in your "Example" sections about adding comments, but I'm now wondering if it makes more sense to the "Example" snippet into two (`Employee.java` and `SortExample.java`) with their own respective `import` statements?

2022-06-30 21:22 UTC, Dusch4593 commented on content/java/concepts/comparable/comparable.md
> +The **Comparable** interface is used to define how a class is to be sorted. It is not to be confused with the [Comparator](https://www.codecademy.com/resources/docs/java/comparator) interface, which
```suggestion
The **`Comparable`** interface is used to define how a [class](https://www.codecademy.com/resources/docs/java/classes) is to be sorted. It is not to be confused with the [`Comparator`](https://www.codecademy.com/resources/docs/java/comparator) interface, which is implemented in a separate class. The `Comparable` interface is implemented in the class to be sorted.
```

2022-06-30 21:22 UTC, Dusch4593 commented on content/java/concepts/comparable/comparable.md
> +This method determines how items are sorted by methods such as `Arrays.sort()` and `Collections.sort()`.
```suggestion
This method determines how items are sorted by methods such as [`Arrays.sort()`](https://www.codecademy.com/resources/docs/java/arrays/sort) and `Collections.sort()`.
```

2022-06-30 21:22 UTC, Dusch4593 commented on content/java/concepts/comparable/comparable.md
> +class Employee implements Comparable<Employee> {
```suggestion

// Employee.java
class Employee implements Comparable<Employee> {
```

2022-06-30 21:22 UTC, Dusch4593 commented on content/java/concepts/comparable/comparable.md
> +public class SortExample {
```suggestion

// SortExample.java
public class SortExample {
```

2022-06-30 21:22 UTC, Dusch4593 commented on content/java/concepts/comparable/comparable.md
> +public class SortExample {
This might be helpful to anyone who tests this code, runs it, and gets errors. They'd need to separate into two appropriately-named `.java` files.

2022-06-30 21:22 UTC, Dusch4593 commented on content/java/concepts/comparable/comparable.md
> +The Comparable interface only has one method, `.compareTo()` that is used to compare the current instance of the class with another instance of the same class, and the sort is based on the return val
```suggestion
The `Comparable` interface only has one method, `.compareTo()` that is used to compare the current instance of the class with another instance of the same class, and the sort is based on the return value of `.compareTo()`:
```

2022-06-30 21:22 UTC, Dusch4593 commented on content/java/concepts/comparator/comparator.md
> +The Comparator interface has a method, `.compare()` that is used to compare two instances of the same class, passed as agruments. The sorting is based on the return value of `.compare()`:
```suggestion
The `Comparator` interface has a `.compare()` method that is used to compare two instances of the same class, passed as arguments. The sorting is based on the return value of `.compare()`:
```

2022-06-30 21:22 UTC, Dusch4593 commented on content/java/concepts/comparator/comparator.md
> +A Comparator class can be passed as an argument to methods such as `Arrays.sort()` and `Collections.sort()` to specify the sort order, potentially overriding the natural sort order defined by the cla
```suggestion
A Comparator class can be passed as an argument to methods such as [`Arrays.sort()`](https://www.codecademy.com/resources/docs/java/arrays/sort) and `Collections.sort()` to specify the sort order, potentially overriding the natural sort order defined by the class’s own `.compareTo()` method.
```

2022-06-30 21:22 UTC, Dusch4593 commented on content/java/concepts/comparator/comparator.md
> +The Comparator class `MyComparator` will define a sort order for `MyClass` using its `.compare()` method, which takes two `MyClass` instances as arguments. The `.compare()` method will use its compar
```suggestion
The `MyComparator` class will define a sort order for `MyClass` using its `.compare()` method, which takes two `MyClass` instances as arguments. The `.compare()` method will use its comparison logic to return a result reflecting the relative ordering of `MyClass`, `a`, and `b`.
```

2022-07-02 13:01 UTC, SSwiniarski commented
> @SSwiniarski Finished my review. I left some comments in your "Example" sections about adding comments, but I'm now wondering if it makes more sense to the "Example" snippet into two (`Employee.java` and `SortExample.java`) with their own respective `import` statements?

That gets into packages and/or compiling things at the same time, which is a little complex for the sake of this example.

2022-07-02 13:02 UTC, SSwiniarski commented
@Dusch4593, I implemented your suggestions.

2022-07-03 20:56 UTC, KTom101 reviewed
@SSwiniarski I've added some suggestions to this.

2022-07-03 20:56 UTC, KTom101 commented on content/java/concepts/comparable/comparable.md
> +The following example defines an `Employee` class that sorts based on `lastName` then on `firstName`.
```suggestion
The following example defines an `Employee` class that sorts based on `lastName` and then on `firstName`.
```

2022-07-03 20:56 UTC, KTom101 commented on content/java/concepts/comparator/comparator.md
> +The following example defines an `Employee` class and a Comparator class that sorts based on `lastName` then on `firstName`.
```suggestion
The following example defines an `Employee` class and a Comparator class that sorts based on `lastName` and then on `firstName`.
```

2022-07-03 20:56 UTC, KTom101 commented on content/java/concepts/comparable/comparable.md
> +import java.io.*;
Since this example is a little long it might be a good idea to add comments just to explain what is going on.

2022-07-03 20:56 UTC, KTom101 commented on content/java/concepts/comparator/comparator.md
> +import java.io.*;
Comments should be added to this, as well.

2022-07-04 11:20 UTC, SSwiniarski commented
@KTom101, I implemented your suggestions.

2022-07-05 13:48 UTC, Dusch4593 approved these changes
@SSwiniarski This LGTM for the most part. My only is what we think about a mix of complete and incomplete sentences being used as comments in the code snippets?

ex:

```java
// SortExample class
public class SortExample {
  public static void main(String[] args)
  {
    // Set up array with a few Employee classes
    Employee a[] = new Employee[5];
    a[0] = new Employee("Kirk","Douglas");
    a[1] = new Employee("Mel","Brooks");
    a[2] = new Employee("Martin","Sheen");
    a[3] = new Employee("Charlie","Sheen");
    a[4] = new Employee("Michael","Douglas");
    // The .sort() method uses the Comparable interface.
    Arrays.sort(a);
```

2022-07-11 15:18 UTC, Dusch4593 requested changes
@SSwiniarski Finished with my review and left you some comments/suggestions.

2022-07-11 15:18 UTC, Dusch4593 commented on content/java/concepts/comparable/comparable.md
> +Using the interface in `MyClass` requires it to implement `Comparable<MyClass>` and override the `.compareTo()` method. The `.compareTo()` method can then use any applicable logic to decide if `this`
```suggestion
Applying the `Comparable` interface to `MyClass` requires the `implements` keyword (e.g., `Comparable<MyClass>`). This interface has a single `.compareTo()` method that returns an `int` value based on whether the `value` of a current class instance (referenced by `this`) can be logically sorted with the value of another instance of the same class.

| Return Value | Meaning                        |
| :----------: | ------------------------------- |
|    `>= 1`    | this instance > passed instance |
|     `0`      | this instance = passed instance |
|   `<= -1`    | this instance < passed instance |

This method determines how items are sorted by methods such as [`Arrays.sort()`](https://www.codecademy.com/resources/docs/java/arrays/sort) and `Collections.sort()`.
```

2022-07-11 15:18 UTC, Dusch4593 commented on content/java/concepts/comparable/comparable.md
> +This method determines how items are sorted by methods such as [`Arrays.sort()`](https://www.codecademy.com/resources/docs/java/arrays/sort) and `Collections.sort()`.
```suggestion
```
I think this should be incorporated into the "Syntax" section.

2022-07-11 15:18 UTC, Dusch4593 commented on content/java/concepts/comparator/comparator.md
> +A Comparator class can be passed as an argument to methods such as [`Arrays.sort()`](https://www.codecademy.com/resources/docs/java/arrays/sort) and `Collections.sort()` to specify the sort order, po
```suggestion
```

I think this can be implemented (pun intended) in the Syntax section.

2022-07-11 15:18 UTC, Dusch4593 commented on content/java/concepts/comparator/comparator.md
> +The `MyComparator` class will define a sort order for `MyClass` using its `.compare()` method, which takes two `MyClass` instances as arguments. The `.compare()` method will use its comparison logic
```suggestion
Applying the `Comparator` interface to a class, `MyComparator`, requires the `implements` keyword (e.g., `Comparator<MyClass>`). This interface has a single `.compareTo()` method that returns an `int` value based on whether two `MyClass` instances, `a` and `b`, can be logically sorted.

| Return Value | Meaning                                          |
| :----------: | ---------------------------------------------- |
|    `>= 1`    | first object instance > second object instance |
|     `0`      | first object instance = second object instance |
|   `<= -1`    | first object instance < second object instance |

A `Comparator` class can be passed as an argument to methods such as [`Arrays.sort()`](https://www.codecademy.com/resources/docs/java/arrays/sort) and `Collections.sort()` to specify the sort order, potentially overriding the natural sort order defined by the class’s own `.compareTo()` method.
```

2022-07-11 16:21 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM!

2022-07-13 00:34 UTC, Dusch4593 reviewed
@SSwiniarski This is about ready to merge but I wanted to get your thoughts on the comments I left just now.

2022-07-13 00:34 UTC, Dusch4593 commented on content/java/concepts/comparable/comparable.md
> +|   `<= -1`    | this instance < passed instance |
```suggestion
|    >= 1    | this instance > passed instance |
|     0      | this instance = passed instance |
|   <= -1    | this instance < passed instance |
```

Although this is return output, I'm not sure if they should necessarily be in back-ticks (to [a point made in a separate PR](https://github.com/Codecademy/docs/pull/840#discussion_r919231406)).

2022-07-13 00:34 UTC, Dusch4593 commented on content/java/concepts/comparator/comparator.md
> +|   `<= -1`    | first object instance < second object instance |
```suggestion
|    >= 1    | first object instance > second object instance |
|     0      | first object instance = second object instance |
|   <= -1    | first object instance < second object instance |
```

Although  this is return output, I'm not sure if they should necessarily be in back-ticks (to [a point made in a separate PR](https://github.com/Codecademy/docs/pull/840#discussion_r919231406)).

2022-07-13 10:51 UTC, SSwiniarski commented
@Dusch4593, I implemented your suggestions.

2022-07-13 19:11 UTC, merged