SQL target keywords
Codecademy/docs pull request #833
Opened 2022-06-30 20:58 UTC by Dusch4593

### Description

For our Docs SEO work

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-07-02 12:46 UTC, SSwiniarski requested changes
@Dusch4593, First review, with only a few suggestions.

2022-07-02 12:46 UTC, SSwiniarski commented on content/sql/concepts/commands/terms/full-outer-join/full-outer-join.md
> +The **`FULL OUTER JOIN`** command combines matching rows with rows from both the left- and right-side tables.
```suggestion
The **`FULL OUTER JOIN`** command combines matching rows with all rows from both the left- and right-side tables.
```

2022-07-02 12:46 UTC, SSwiniarski commented on content/sql/concepts/commands/terms/full-outer-join/full-outer-join.md
> +One or more matching `column(s)` can be selected and joined from `table_A` and `table_B` based on matching columns between tables in the `ON` clause. The results can be further filtered based on a `c
```suggestion
One or more matching `column(s)` can be selected and joined from `table_A` and `table_B` based on matching columns between tables in the `ON` clause to define which rows are combined. Other rows from each table appear in the result separately. The results can be further filtered based on a `condition` in the [`WHERE`](https://www.codecademy.com/resources/docs/sql/commands/where) clause.
```

2022-07-02 12:46 UTC, SSwiniarski commented on content/sql/concepts/commands/terms/full-outer-join/full-outer-join.md
> +The following example selects the all rows (`*`) from the tables `books` and `authors` that have matching author IDs less than 11:
```suggestion
The following example selects the all rows (`*`) from the table `books` with an `author_id` less than 11, and any rows from the `authors` table that have a matching `id` in the filtered `books` table:
```

2022-07-05 12:53 UTC, Dusch4593 commented
@SSwiniarski Finished implementing your suggestions

2022-07-05 16:00 UTC, SSwiniarski approved these changes
Looks good for review two.

2022-07-05 16:46 UTC, KTom101 reviewed
@Dusch4593 Added a few suggestions for these entries!

2022-07-05 18:29 UTC, Dusch4593 commented on content/sql/concepts/operators/terms/between/between.md
> +The `column` must exist, and `value_A` and `value_B` must define a valid range. `BETWEEN` works with numbers, text, or date data types.
Nah, I think that was a typo of mine 😂

2022-07-05 18:49 UTC, KTom101 commented on content/sql/concepts/commands/terms/inner-join/inner-join.md
> +![INNER JOIN GIF](https://content.codecademy.com/courses/learn-sql/multiple-tables/inner-join.gif)
Yeah I was talking about width/height. It's ok then, thanks!

2022-07-06 12:39 UTC, yangc95 commented on content/sql/concepts/commands/terms/full-outer-join/full-outer-join.md
> +ON table_A.column(s) = table_B.column(s)
```suggestion
  ON table_A.column(s) = table_B.column(s)
```

2022-07-07 03:39 UTC, yangc95 commented on content/sql/concepts/commands/terms/case/case.md
> +The **`CASE`** command is a logical test that returns different output based on the conditions of each statement, closes with an `END` clause.
```suggestion
The **`CASE`** command is a logical test that returns different output based on the conditions of each statement and closes with an `END` clause.
```

2022-07-07 03:41 UTC, yangc95 commented on content/sql/concepts/commands/terms/full-outer-join/full-outer-join.md
> +The following example selects the all rows (`*`) from the table `books` with an `author_id` less than 11, and any rows from the `authors` table that have a matching `id` in the filtered `books` table
```suggestion
The following example selects all the rows (`*`) from the `books` table with an `author_id` less than 11, and any rows from the `authors` table that have a matching `id` in the filtered `books` table:
```

2022-07-07 03:45 UTC, yangc95 commented on content/sql/concepts/commands/terms/right-join/right-join.md
> +To create a result set of every row in the `students` table combined with the `transfer_data` table where student IDs match. And if the `ON` condition is not met, then `NULL` values are used to fill
```suggestion
To create a result set of every row in the `students` table combined with the `transfer_data` table where student IDs match. If the `ON` condition is not met, then `NULL` values are used to fill in the columns from the `transfer_data` table.
```

Personal preference! Feel free to reject

2022-07-07 03:49 UTC, yangc95 reviewed
@Dusch4593 🙌 much improvement, took a look and only had a few comments/suggestions

2022-07-13 00:37 UTC, merged