New Entry: Java Generics
Codecademy/docs pull request #842
Opened 2022-07-15 11:56 UTC by SSwiniarski

### Description

From Target Keyword List.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-07-15 13:53 UTC, Dusch4593 requested changes
@SSwiniarski Left a few comments/suggestions for you 😄

2022-07-15 13:53 UTC, Dusch4593 commented on content/java/concepts/generics/generics.md
> +**Generics** refer to the ability to use a type as a parameter to methods and classes. This provides the ability to define a set of related classes or methods that can operate on many different types
```suggestion
**Generics** refer to the ability to use a [type](https://www.codecademy.com/resources/docs/java/data-types) as a parameter to [methods](https://www.codecademy.com/resources/docs/java/methods) and [classes](https://www.codecademy.com/resources/docs/java/classes). This provides the ability to define a set of related classes or methods that can operate on many different types with a single declaration. This also allows type safety at compile-time allowing invalid types to be caught during compilation.
```

2022-07-15 13:53 UTC, Dusch4593 commented on content/java/concepts/generics/generics.md
> +
```suggestion
```pseudo
```

2022-07-15 13:53 UTC, Dusch4593 commented on content/java/concepts/generics/generics.md
> +The following example shows how a generic method can accept arrays of different types.
```suggestion
The following example shows how a generic method can accept [arrays](https://www.codecademy.com/resources/docs/java/arrays) of different types:
```

2022-07-15 13:53 UTC, Dusch4593 commented on content/java/concepts/generics/generics.md
> +  }
```suggestion
<T> void myMethod( T argument ) {
  // Method body
}
```

2022-07-15 13:53 UTC, Dusch4593 commented on content/java/concepts/generics/generics.md
> +  // Use example
```suggestion
  }
  
  // Use example
```

2022-07-15 13:53 UTC, Dusch4593 commented on content/java/concepts/generics/generics.md
> +A generic class takes one or more type parameters when it is declared. One of the more familiar uses of a generic class is with Java's various collection classes. An `ArrayList` for instance is a gen
```suggestion
A generic class takes one or more type parameters when it is declared. One of the more familiar uses of a generic class is with Java's various collection classes. An [`ArrayList`](https://www.codecademy.com/resources/docs/java/array-list) for instance is a generic class. When it is declared it requires a type parameter to specify what kind of type the `ArrayList` contains. For example:
```

2022-07-15 15:47 UTC, SSwiniarski commented
@Dusch4593, I implemented your suggestions.

2022-07-16 23:53 UTC, Dusch4593 requested changes
@SSwiniarski Just a few last-minute comments/suggestions

2022-07-16 23:53 UTC, Dusch4593 commented on content/java/concepts/generics/generics.md
> +**Note:** Java type parameters can only be reference types, not primitive types (like `int`, `double` or `char`).
```suggestion
**Note:** Java type parameters can only be reference types, not primitive types (like `int`, `double`, or `char`).
```

2022-07-16 23:53 UTC, Dusch4593 commented on content/java/concepts/generics/generics.md
> +  - 'OOP'
```suggestion
  - 'OOP'
  - 'Parameters'
```

2022-07-17 11:12 UTC, SSwiniarski commented
@Dusch4593, I committed those changes.

2022-07-20 15:46 UTC, KTom101 reviewed
@SSwiniarski I only see a minor change and have one comment.

2022-07-20 16:14 UTC, SSwiniarski commented on content/java/concepts/generics/generics.md
> +**Note:** Java type parameters can only be reference types, not primitive types (like `int`, `double`, or `char`).
Might be worth opening an issue. @Dusch4593, thoughts?

2022-07-20 16:15 UTC, SSwiniarski commented
@KTom101, I applied your suggestion.

2022-07-20 16:18 UTC, KTom101 approved these changes

2022-07-22 13:48 UTC, Dusch4593 commented on content/java/concepts/generics/generics.md
> +**Note:** Java type parameters can only be reference types, not primitive types (like `int`, `double`, or `char`).
Excellent suggestion! I just [filed an issue](https://github.com/Codecademy/docs/issues/850) 👍🏻

2022-07-22 13:51 UTC, merged