SEO Work: JS, Python, Git
Codecademy/docs pull request #847
Opened 2022-07-20 01:18 UTC by Dusch4593

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-07-20 11:11 UTC, SSwiniarski requested changes
@Dusch4593, reviewed and had only a couple of minor changes.

2022-07-20 11:11 UTC, SSwiniarski commented on content/python/concepts/built-in-functions/terms/input/input.md
> +Description: 'Prompts the user for data and returns as a string.'
```suggestion
Description: 'Prompts the user for data and returns it as a string.'
```

2022-07-20 11:11 UTC, SSwiniarski commented on content/python/concepts/keywords/terms/global/global.md
> +Description: 'Creates a global variable that can be updated '
```suggestion
Description: 'Creates a global variable that can be updated.'
```

2022-07-22 13:39 UTC, Dusch4593 commented
@SSwiniarski Implemented your suggestions! 😄

2022-07-22 15:36 UTC, SSwiniarski approved these changes
Looks good for another review.

2022-07-27 16:46 UTC, KTom101 requested changes
@Dusch4593 I added some changes to this entry.

2022-07-27 16:46 UTC, KTom101 commented on content/javascript/concepts/arrays/terms/splice/splice.md
>    - 'Computer Science'
Update description to say "Modifies an array"

2022-07-27 19:00 UTC, Dusch4593 commented on content/javascript/concepts/arrays/terms/sort/sort.md
>  Sort strings in an array alphabetically:
Sorry, I meant to remove that 😂

2022-07-27 19:02 UTC, Dusch4593 commented
@KTom101 Finished implementing your feedback 😄

2022-07-30 04:39 UTC, KTom101 approved these changes
👍

2022-07-30 12:31 UTC, merged