New Entry: R Functions
Codecademy/docs pull request #854
Opened 2022-07-24 14:16 UTC by SSwiniarski

### Description

From Target Keyword List

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-07-26 16:23 UTC, Dusch4593 commented on content/r/concepts/functions/functions.md
> +## The `return()` Function
```suggestion
### The `return()` Function
```

2022-07-26 16:24 UTC, Dusch4593 commented on content/r/concepts/functions/functions.md
> +## Default Parameter Values
```suggestion
### Default Parameter Values
```

2022-07-26 16:24 UTC, Dusch4593 commented on content/r/concepts/functions/functions.md
> +}
```suggestion
}

my_function(parameters)
```

2022-07-26 16:25 UTC, Dusch4593 commented on content/r/concepts/functions/functions.md
> +
```suggestion

```

2022-07-26 16:25 UTC, Dusch4593 commented on content/r/concepts/functions/functions.md
> +Arguments can be passed to a function by position or by name. By position passes arguments in the order they were defined in the function. By name specifies the name of the parameter given by the fun
```suggestion
### Arguments

Arguments can be passed to a function by position or by name. By position passes arguments in the order they were defined in the function. By name specifies the name of the parameter given by the function.
```

2022-07-26 16:26 UTC, Dusch4593 commented on content/r/concepts/functions/functions.md
> +```r
```suggestion
```pseudo
```

2022-07-26 16:26 UTC, Dusch4593 commented on content/r/concepts/functions/functions.md
> +- `code to execute`: The code that executes when the function is called.
```suggestion
- `# Code to execute`: The code that executes when the function is called.
```

2022-07-26 16:27 UTC, Dusch4593 commented on content/r/concepts/functions/functions.md
> +A function is called by using its name, followed by parenthesis enclosing any parameters the function expects:
```suggestion
A function is called with its name, followed by any parameters that are expected in the parentheses.
```

2022-07-26 16:29 UTC, Dusch4593 commented on content/r/concepts/functions/functions.md
> +The following takes a numeric argument and prints a string saying if it is even or odd:
```suggestion
The following example defines an `odd_or_even()` function that takes a `num` argument. When called, it prints a message saying if `num` is even or odd:
```

2022-07-26 16:29 UTC, Dusch4593 commented on content/r/concepts/functions/functions.md
> +  # The following lines are never executed.
```suggestion
  return (x)
  
  # The following lines are never executed.
```

2022-07-27 10:56 UTC, SSwiniarski commented
@Dusch4593, I implemented your suggestions.

2022-07-27 18:49 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM for the next review! 👍🏻

2022-08-02 21:32 UTC, KTom101 requested changes
@SSwiniarski Just a couple changes from me.

2022-08-03 11:03 UTC, SSwiniarski commented
@KTom101, I implemented your suggestions.

2022-08-03 15:55 UTC, KTom101 approved these changes
@SSwiniarski 👍

2022-08-04 12:24 UTC, Dusch4593 commented
This seems ready to merge but I made some edits in b2a33093e2ec6fc15f9e5143aa7e79651ee2dc9c that include:

- Removing link to General: Functions entry (this isn't a practice I've seen with other language-specific "Function" entries).
- Changing to \```pseudo snippet in the top-level "Syntax" section.
- Adding list item about the `<-` operator used in the "Syntax" snippet.
- Changing "parenthesis" to "parentheses" (under "The `return()` Function").

cc: @SSwiniarski @KTom101

2022-08-04 12:24 UTC, merged