New Entry: General One Hot Encoding
Codecademy/docs pull request #863
Opened 2022-08-02 15:40 UTC by SSwiniarski

### Description

From Target Keyword List

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-08-04 13:04 UTC, Dusch4593 requested changes
@SSwiniarski Just one suggestion from me on this one 😄

2022-08-04 13:04 UTC, Dusch4593 commented on content/general/concepts/one-hot-encoding/one-hot-encoding.md
> +The process of one hot encoding is as follows:
Is this "process" supposed to be sequential? If so, should we turn this list into a numbered list?

2022-08-04 15:04 UTC, SSwiniarski commented
@Dusch4593, I implemented your suggestion.

2022-08-04 18:10 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM for the next review 👍🏻

2022-08-05 21:44 UTC, KTom101 reviewed
@SSwiniarski Just a few minor things from me!

2022-08-06 11:07 UTC, SSwiniarski commented
@KTom101, I implemented your suggestions.

2022-08-06 18:57 UTC, KTom101 approved these changes
@SSwiniarski Thank you, LGTM! 👍

2022-08-10 13:03 UTC, Dusch4593 commented
@SSwiniarski @KTom101 I think we're ready to merge this one! 😄 But I had a question for everyone regarding "vectors"; should we file an issue to (a) create a new General concept entry about vectors, or (b) edit the existing [General: Array](https://www.codecademy.com/resources/docs/general/array) to include info about how vectors are 1-dimensional arrays?

2022-08-10 13:04 UTC, merged

2022-08-10 15:55 UTC, SSwiniarski commented
> @SSwiniarski @KTom101 I think we're ready to merge this one! 😄 But I had a question for everyone regarding "vectors"; should we file an issue to (a) create a new General concept entry about vectors, or (b) edit the existing [General: Array](https://www.codecademy.com/resources/docs/general/array) to include info about how vectors are 1-dimensional arrays?

@Dusch4593, my vote is for a new entry.

2022-08-10 16:14 UTC, KTom101 commented
> > @SSwiniarski @KTom101 I think we're ready to merge this one! 😄 But I had a question for everyone regarding "vectors"; should we file an issue to (a) create a new General concept entry about vectors, or (b) edit the existing [General: Array](https://www.codecademy.com/resources/docs/general/array) to include info about how vectors are 1-dimensional arrays?
> 
> 
> 
> @Dusch4593, my vote is for a new entry.
> 
> 
> 
> 
@Dusch4593 +1 on what @SSwiniarski said