New Terms: C++ `strcpy()` & `strcmp()`
Codecademy/docs pull request #869
Opened 2022-08-05 12:06 UTC by SSwiniarski

### Description

From Target Keyword List.

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-08-08 00:52 UTC, KTom101 reviewed
@SSwiniarski I've added minor changes.

2022-08-08 00:52 UTC, KTom101 commented on content/cpp/concepts/strings/terms/strcmp/strcmp.md
> +```cpp
```suggestion
```pseudo
```

2022-08-08 00:52 UTC, KTom101 commented on content/cpp/concepts/strings/terms/strcmp/strcmp.md
> +strcmp(string1, string2)
```suggestion
strcmp(string1, string2);
```

2022-08-08 11:46 UTC, SSwiniarski commented
@KTom101, I implemented your suggestions.

2022-08-08 17:22 UTC, KTom101 approved these changes
@SSwiniarski Looks ready for a second review!

2022-08-10 14:46 UTC, Dusch4593 requested changes
@SSwiniarski Finished with my review and left some comments/suggestions. With regards to the suggestions for the "Syntax" section I made in the C++ `strcpy.md` and `strcmp.md` files, can be make similar edits to the "Syntax" sections in the C/`strcpy.md`?

2022-08-10 14:46 UTC, Dusch4593 commented on content/cpp/concepts/strings/terms/strcmp/strcmp.md
> +Description: 'Compares two C-style strings.'
```suggestion
Description: 'Compares two C-style strings and returns an integer value.'
```

2022-08-10 14:46 UTC, Dusch4593 commented on content/cpp/concepts/strings/terms/strcmp/strcmp.md
> +The **`strcmp()`** string function compares two C-style strings and returns an integer value.
```suggestion
The **`strcmp()`** function compares two strings and returns an integer value.
```

2022-08-10 14:46 UTC, Dusch4593 commented on content/cpp/concepts/strings/terms/strcmp/strcmp.md
> +> **Note:** `strcpy()` only works on C-style strings, not C++ style strings. So it only works with strings of type `char str[];` not `string str;`
```suggestion
> **Note:** `strcpy()` only works on [C-style strings](https://www.codecademy.com/resources/docs/c/strings) of type `char str[];`, not C++ style strings of type `string str;`.
```

2022-08-10 14:46 UTC, Dusch4593 commented on content/cpp/concepts/strings/terms/strcmp/strcmp.md
> +## Example
I think this section could be turned into a Codebyte section since C++ is a supported language.

2022-08-10 14:46 UTC, Dusch4593 commented on content/cpp/concepts/strings/terms/strcpy/strcpy.md
> +## Example
I think this section could be turned into a Codebyte section since C++ is a supported language.

2022-08-10 14:46 UTC, Dusch4593 commented on content/cpp/concepts/strings/terms/strcpy/strcpy.md
> +strcpy(string1, string2);
```suggestion
#include <string.h>

strcpy(string1, string2);
```

2022-08-10 14:46 UTC, Dusch4593 commented on content/cpp/concepts/strings/strings.md
> +**Strings** are objects that represent sequences of characters. In C++, there are two ways to create strings: `string` class or using C-style character strings.
```suggestion
**Strings** are objects that represent sequences of characters. In C++, the two ways to create strings are with the `string` class or with [C-style](https://www.codecademy.com/resources/docs/c/strings) character strings.
```

2022-08-10 14:46 UTC, Dusch4593 commented on content/c/concepts/strings/terms/strcmp/strcmp.md
> +The **`strcmp()`** string function compares two strings and returns an integer value.
Can we apply a similar edit to the `Description` on line # 3? (e.g., "Compares two strings and returns an integer value.")

2022-08-10 16:58 UTC, SSwiniarski commented
@Dusch4593, I implemented all your suggestions.

2022-08-13 10:04 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM! 👍🏻

2022-08-13 12:18 UTC, merged