New Terms: C/C++ `strtok()`
Codecademy/docs pull request #871
Opened 2022-08-07 13:23 UTC by SSwiniarski

### Description

From Target Keyword List

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-08-10 13:43 UTC, Dusch4593 requested changes
@SSwiniarski Finished with my review and left some comments/suggestions.

2022-08-10 13:43 UTC, Dusch4593 commented on content/c/concepts/strings/terms/strtok/strtok.md
> +The above example results in the following output:
```suggestion
This results in the following output:
```

2022-08-10 13:43 UTC, Dusch4593 commented on content/c/concepts/strings/terms/strtok/strtok.md
> +char *token = strtok(string, delimiters);
```suggestion
char *token = strtok(string, delimiters);

token = strtok(NULL, delimiters);
```

I feel like adding this line better supports the points made in the paragraph  below.

2022-08-10 13:43 UTC, Dusch4593 commented on content/c/concepts/strings/terms/strtok/strtok.md
> +The `strtok()` function splits the string `string` into tokens on occurrences of any character in the string `delimiters` and returns the pointer to the first token. Subsequent calls to strtok with `
```suggestion
The `strktok()` function splits the `string` parameter into tokens based on one or more `delimiters`, and returns the [pointer](https://www.codecademy.com/resources/docs/c/pointers) to the first token. Subsequent calls to `strtok()`, with `string` set to `NULL`, return a pointer to the next tokenized string. When there are no tokens left to retrieve, a `NULL` pointer is returned.
```

2022-08-10 13:43 UTC, Dusch4593 commented on content/cpp/concepts/strings/terms/strtok/strtok.md
> +> **Note:** `strtok()` only works on C-style strings, not C++ style strings. So it only works with strings of type `char str[];` not `string str;`
```suggestion
> **Note:** `strtok()` only works on [C-style strings](https://www.codecademy.com/resources/docs/c/strings) of type `char str[];`, not C++ style strings of type `string str;`.
```

2022-08-10 13:43 UTC, Dusch4593 commented on content/cpp/concepts/strings/terms/strtok/strtok.md
> +The **`strtok()`** function breaks a C-style string into a series of tokens using a list of delimiters.
```suggestion
The **`strtok()`** function breaks a string into a series of tokens using a list of delimiters.
```

2022-08-10 13:43 UTC, Dusch4593 commented on content/cpp/concepts/strings/terms/strtok/strtok.md
> +## Example
Wondering if we should change this section in a Codebyte example since C++ is a supported language?

2022-08-10 16:02 UTC, SSwiniarski commented
@Dusch4593, I implemented all your suggestions.

2022-08-13 12:27 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM!

2022-08-20 20:47 UTC, KTom101 reviewed
@SSwiniarski I just added line spacing to break up the paragraphs describing the syntax. Otherwise, it LGTM.

2022-08-20 20:47 UTC, KTom101 commented on content/c/concepts/strings/terms/strtok/strtok.md
> +The `strktok()` function splits the `string` parameter into tokens based on one or more `delimiters`, and returns the [pointer](https://www.codecademy.com/resources/docs/c/pointers) to the first toke
```suggestion
The `strktok()` function splits the `string` parameter into tokens based on one or more `delimiters`, and returns the [pointer](https://www.codecademy.com/resources/docs/c/pointers) to the first token. 

Subsequent calls to `strtok()`, with `string` set to `NULL`, return a pointer to the next tokenized string. When there are no tokens left to retrieve, a `NULL` pointer is returned.
```

2022-08-20 20:47 UTC, KTom101 commented on content/cpp/concepts/strings/terms/strtok/strtok.md
> +The `strtok()` function splits the C-style `string` parameter into tokens based on one or more `delimiters`, and returns the [pointer](https://www.codecademy.com/resources/docs/cpp/pointers) to the f
```suggestion
The `strtok()` function splits the C-style `string` parameter into tokens based on one or more `delimiters`, and returns the [pointer](https://www.codecademy.com/resources/docs/cpp/pointers) to the first token. 

Subsequent calls to `strtok()`, with `string` set to `NULL`, return a pointer to the next tokenized string. When there are no tokens left to retrieve, a `NULL` pointer is returned.
```

2022-08-21 12:00 UTC, SSwiniarski commented
@KTom101, I implemented your suggestions.

2022-08-21 20:15 UTC, HishamT approved these changes
Looks good to me!

2022-08-23 18:47 UTC, yangc95 commented on content/c/concepts/strings/terms/strtok/strtok.md
> +The `strktok()` function splits the `string` parameter into tokens based on one or more `delimiters`, and returns the [pointer](https://www.codecademy.com/resources/docs/c/pointers) to the first toke
```suggestion
The `strtok()` function splits the `string` parameter into tokens based on one or more `delimiters`, and returns the [pointer](https://www.codecademy.com/resources/docs/c/pointers) to the first token.
```

2022-08-23 18:53 UTC, yangc95 commented on content/cpp/concepts/strings/terms/strtok/strtok.md
> +```codebyte\cpp
```suggestion
```codebyte/cpp
```

2022-08-23 18:56 UTC, yangc95 commented
@SSwiniarski just 2 typos committed here: [
83b49a5](https://github.com/Codecademy/docs/pull/871/commits/83b49a50da63bafa0137f392b147f08781652d13)

2022-08-23 18:56 UTC, yangc95 approved these changes
LGTM as well!

2022-08-23 19:02 UTC, merged