Created SQL Commands Create Index entry
Codecademy/docs pull request #877
Opened 2022-08-10 16:32 UTC by sharkipelago

### Description

Created an entry for the SQL command Create Index
Closes #807 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-08-11 16:01 UTC, SSwiniarski requested changes
@sharkipelago, I completed a first review and left a few comments.

2022-08-11 16:01 UTC, SSwiniarski commented on content/sql/concepts/commands/terms/create-index/create-index.md
> +  - 'paths/design-databases-with-postgresql'
Generally we want to limit the CatalogContent to two entries now.

2022-08-11 16:04 UTC, SSwiniarski commented on content/sql/concepts/commands/terms/create-index/create-index.md
> +Description: 'Creates an index on existing column(s) in a table. Indexes can't be seen by the user of a database; they just help speed up queries.'
One additional thing. An apostrophe in the description throws off the tests, even when it's escaped. Best to leave it out.

2022-08-13 10:14 UTC, Dusch4593 commented on content/sql/concepts/commands/terms/create-index/create-index.md
> +Description: 'Creates an index on existing column(s) in a table. Indexes can't be seen by the user of a database; they just help speed up queries.'
For this line, I would also suggest using  "cannot" instead of "can not" (although both are valid, the former seems more common than the latter).

2022-08-14 22:24 UTC, sharkipelago commented
@SSwiniarski  Thank you for the comments! I just implemented the changes.

2022-08-15 11:13 UTC, SSwiniarski approved these changes
@sharkipelago, Looks good!

2022-08-15 17:50 UTC, Dusch4593 requested changes
@sharkipelago Finished with my review; just a few comments/suggestions from me.

2022-08-15 17:50 UTC, Dusch4593 commented on content/sql/concepts/commands/terms/create-index/create-index.md
> +This example creates an index called `ix_student_name` on the `student_name` column in the `students` table.
```suggestion
This example creates an index called `ix_student_name` on the `student_name` column in the `students` table:
```

2022-08-15 17:50 UTC, Dusch4593 commented on content/sql/concepts/commands/terms/create-index/create-index.md
> +  - 'Tables'
```suggestion
  - 'Database'
  - 'Index'
  - 'Queries'
  - 'PostgreSQL'
  - 'MySQL'
  - 'SQLite'
  - 'Tables'
```

2022-08-17 01:23 UTC, sharkipelago commented
@Dusch4593 Made the changes!

2022-08-22 20:39 UTC, Dusch4593 approved these changes
@sharkipelago LGTM! Made one small edit in 0c7e617a616d648ed1658aca05dbd52e44f40c9e in the `Description`.

2022-08-22 20:41 UTC, merged