New Entry: R loops
Codecademy/docs pull request #878
Opened 2022-08-11 17:03 UTC by yangc95

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-08-13 12:00 UTC, Dusch4593 requested changes
@yangc95 Finished my review and left some comments/suggestions.

2022-08-13 12:00 UTC, Dusch4593 commented on content/r/concepts/loops/loops.md
> +A loop is used to perform some operation given that a declared condition is truthy. In R, there are `while` and `for` loops.
```suggestion
A loop is used to perform some operation as long as declared condition is truthy. In R, there are `while` and `for` loops.
```

2022-08-24 18:07 UTC, yangc95 reviewed
@Dusch4593 implemented your suggestions, TY!

2022-08-24 21:20 UTC, KTom101 commented
@yangc95 Is this ready for a second review? I see a few unresolved changes.

2022-08-25 14:43 UTC, yangc95 commented
@KTom101 thanks for letting me know! I thought I applied the suggestions but it looks like it wasn't done successfully - just updated 🙌

2022-08-25 17:56 UTC, Dusch4593 approved these changes
@yangc95 LGTM for the next review 👍🏻

2022-08-27 12:30 UTC, SSwiniarski requested changes
@yangc95 I completed a second review and left a few comments.

2022-08-27 12:30 UTC, SSwiniarski commented on content/r/concepts/loops/loops.md
> +Description: 'A loop is used to perform some operation as long as a declared condition is truthy.'
```suggestion
Description: 'A loop is used to repeat some operation a multiple number of times.'
```

2022-08-27 12:30 UTC, SSwiniarski commented on content/r/concepts/loops/loops.md
> +Description: 'A loop is used to perform some operation as long as a declared condition is truthy.'
The original description applied to `while` loops, but not `for` loops.

2022-08-27 12:30 UTC, SSwiniarski commented on content/r/concepts/loops/loops.md
> +A loop is used to perform some operation as long as a declared condition is truthy. In R, there are `while` and `for` loops.
```suggestion
A loop is used to repeat some operation a multiple number of times. In R, there are `while` and `for` loops.
```

2022-08-27 12:30 UTC, SSwiniarski commented on content/r/concepts/loops/loops.md
> +A loop is used to perform some operation as long as a declared condition is truthy. In R, there are `while` and `for` loops.
Again, it needs to apply to `for` as well as `while` loops.

2022-08-27 12:30 UTC, SSwiniarski commented on content/r/concepts/loops/loops.md
> +The statement(s) within a `while` loop code block will continue to execute given that a declared condition is `TRUE`.
```suggestion
The statement(s) within a `while` loop code block will continue to execute as long as a declared condition is `TRUE`.
```

2022-08-29 19:51 UTC, yangc95 commented
@SSwiniarski thanks for those logical change! I've implemented your suggestions

2022-08-30 11:54 UTC, SSwiniarski approved these changes
@yangc95 Looks good!

2022-08-30 17:24 UTC, Dusch4593 commented
This looks ready to merge! 🚀

I went and bolded the concept "loop" in 87dc9fe6dc2e03341da9d85c8dae3ee7415850fb.

cc: @yangc95 @SSwiniarski

2022-08-30 17:24 UTC, merged