New Entry: C++ Templates
Codecademy/docs pull request #879
Opened 2022-08-12 14:20 UTC by SSwiniarski

### Description

From target keyword list.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-08-13 12:07 UTC, Dusch4593 requested changes
@SSwiniarski Just a few suggestion from me for this one 😄

2022-08-13 12:07 UTC, Dusch4593 commented on content/cpp/concepts/templates/templates.md
> +**Templates** provide the ability to use a [type](https://www.codecademy.com/resources/docs/cpp/data-types) as a parameter in [functions](https://www.codecademy.com/resources/docs/cpp/functions) and
```suggestion
**Templates** provide the ability to use a [data type](https://www.codecademy.com/resources/docs/cpp/data-types) as a parameter in [functions](https://www.codecademy.com/resources/docs/cpp/functions) and [classes](https://www.codecademy.com/resources/docs/cpp/classes). These are referred to as generic types. This provides the ability to define a set of related classes or functions that can operate on many different types with a single declaration.
```

2022-08-13 12:07 UTC, Dusch4593 commented on content/cpp/concepts/templates/templates.md
> +  - 'Parameters'
```suggestion
  - 'Parameters'
  - 'Templates'
```

2022-08-13 15:40 UTC, SSwiniarski commented
@Dusch4593, implemented your suggestions.

2022-08-13 15:40 UTC, Dusch4593 approved these changes
@SSwiniarski Looks good for the next review 😄

2022-08-22 21:50 UTC, KTom101 reviewed
@SSwiniarski Just a few edits from me, mainly structural.

2022-08-23 11:52 UTC, SSwiniarski commented
@KTom101 I implemented your suggestions

2022-08-23 18:43 UTC, KTom101 approved these changes
@SSwiniarski Looks good!

2022-08-24 21:21 UTC, KTom101 commented
@Dusch4593 Was there anything you wanted to add before merging?

2022-08-24 21:51 UTC, Dusch4593 commented
@KTom101 LGTM! 👍🏻 I just linked to out to the [operators entry](https://www.codecademy.com/resources/docs/cpp/operators) in b68599d355cb1c09e4c7a6e1f4d557600b888a9c.

2022-08-24 21:51 UTC, merged