New Entry: General JSP
Codecademy/docs pull request #881
Opened 2022-08-13 16:34 UTC by SSwiniarski

### Description

From Target Keyword list.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-08-13 19:41 UTC, Dusch4593 requested changes
@SSwiniarski Finished with my review and left some comments/suggestions.

2022-08-13 19:41 UTC, Dusch4593 commented on content/general/concepts/jsp/jsp.md
> +## Advantages
No disadvantages?

2022-08-13 19:41 UTC, Dusch4593 commented on content/general/concepts/jsp/jsp.md
> +  - 'Server-Side Rendering'
```suggestion
  - 'Dynamic Programming'
  - 'Servers'
  - 'Server-Side Rendering'
```

2022-08-13 19:41 UTC, Dusch4593 commented on content/general/concepts/jsp/jsp.md
> +  - 'Server-Side Rendering'
If possible, let's have at least two tags.

2022-08-13 19:41 UTC, Dusch4593 commented on content/general/concepts/jsp/jsp.md
> +- JSP pages are compiled before being processed by the server reducing the load on the server.
```suggestion
- JSP pages are compiled before being processed by the server, reducing the load on the server.
```

Is it me, or does this read weirdly without a comma?

2022-08-13 19:41 UTC, Dusch4593 commented on content/general/concepts/jsp/jsp.md
> +- Since JSP uses the Java Virtual Machine, JSP is platform agnostic and portable.
```suggestion
- Since JSP uses the Java Virtual Machine, JSP is platform-agnostic and portable.
```

2022-08-14 13:47 UTC, SSwiniarski commented
@Dusch4593, I implemented your suggestions.

2022-08-19 15:40 UTC, caupolicandiaz requested changes
@SSwiniarski Not much here, just one edit

2022-08-19 15:40 UTC, caupolicandiaz commented on content/general/concepts/jsp/jsp.md
> +- JSP file must be compled on the server when first accessed, which can cause a noticable delay on the first visit to a page.
```suggestion
-  A JSP file must be compiled on the server when first accessed, which can cause a noticeable delay on the first visit to a page.
```

2022-08-20 14:12 UTC, SSwiniarski commented
@caupolicandiaz, I implemented your suggestion.

2022-08-22 17:17 UTC, Dusch4593 requested changes
@SSwiniarski Had a few final comments/suggestions for this one.

- Since "Servers" and "Server-Side Rendering" are mentioned in both the text and meta-`Tags`, let's link to their respective General entries.
- Oxford-comma at the end of the opening paragraph on line # 16.
- Colon on line # 22 for sentence preceding the list.
- Slight turn-of-phrase on line # 27.

2022-08-22 17:17 UTC, Dusch4593 commented on content/general/concepts/jsp/jsp.md
> +JSP has the following advantages compared to other methods of creating dynamic web pages.
```suggestion
JSP has the following advantages compared to other methods of creating dynamic web pages:
```

2022-08-22 17:17 UTC, Dusch4593 commented on content/general/concepts/jsp/jsp.md
> +- Since JSP uses the Java Virtual Machine, JSP is platform-agnostic and portable.
```suggestion
- Since JSP uses the Java Virtual Machine, it is portable and platform-agnostic.
```

2022-08-22 17:17 UTC, Dusch4593 commented on content/general/concepts/jsp/jsp.md
> +**JSP** (Jakarta Server Pages, formerly JavaServer Pages) is a technology that allows a web developer to mix textual content with [Java](https://www.codecademy.com/resources/docs/java) code that is e
```suggestion
**JSP** (Jakarta Server Pages, formerly JavaServer Pages) is a technology that allows a web developer to mix textual content with [Java](https://www.codecademy.com/resources/docs/java) code that is executed on the web [server](https://www.codecademy.com/resources/docs/general/server) to [render](https://www.codecademy.com/resources/docs/general/server-side-rendering) the final web page. In this way it is similar to [PHP](https://www.codecademy.com/resources/docs/php) except that it uses the Java programming language. With JSP the developer can create dynamic pages based on [HTML](https://www.codecademy.com/resources/docs/html), [XML](https://www.codecademy.com/resources/docs/general/xml), SOAP, or other document types.
```

2022-08-23 11:18 UTC, SSwiniarski commented
@Dusch4593 I applied your new suggestions.

2022-08-23 16:42 UTC, caupolicandiaz approved these changes

2022-08-23 18:44 UTC, Dusch4593 approved these changes
@SSwiniarski Looks ready for merge to me! 😄

2022-08-23 18:46 UTC, merged