Add Entry: General Objective-C
Codecademy/docs pull request #891
Opened 2022-08-22 16:35 UTC by SSwiniarski

### Description

From Target Keyword List

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-08-22 23:00 UTC, Dusch4593 requested changes
@SSwiniarski Finished my review; just a few comments/suggestions from me.

2022-08-22 23:00 UTC, Dusch4593 commented on content/general/concepts/objective-c/objective-c.md
> +  - 'OOP'
```suggestion
  - 'iOS'
  - 'OOP'
```

2022-08-22 23:00 UTC, Dusch4593 commented on content/general/concepts/objective-c/objective-c.md
> +Description: 'Objective-C is a programming language that builds upon the C language by adding object-oriented programming with Smalltalk-style messaging. '
```suggestion
Description: 'Objective-C is a programming language that builds upon the C language by adding object-oriented programming with Smalltalk-style messaging.'
```

2022-08-23 12:20 UTC, SSwiniarski commented
@Dusch4593 I implemented your suggestions and added a line about current Objective-C history.

2022-08-23 18:43 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM for the next review! 👍🏻

2022-08-24 20:37 UTC, HishamT approved these changes
LGTM

2022-08-24 20:41 UTC, Dusch4593 commented
Looks good for merge! I made a small change in 9bbbce12d85e7aeb9e59cc20ed2b7332f6b45d0e where I made "Operating system" all lowercase.

2022-08-24 20:42 UTC, merged