New Entry: Python unittest module
Codecademy/docs pull request #931
Opened 2022-08-26 17:02 UTC by SSwiniarski

### Description

From Target Keyword List.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-09-01 20:30 UTC, Dusch4593 requested changes
@SSwiniarski Finished with my review and left some comments/suggestions.

2022-09-01 20:30 UTC, Dusch4593 commented on content/python/concepts/unittest-module/unittest-module.md
> +The **`unittest`** module provides features for [unit testing](https://www.codecademy.com/resources/docs/general/unit-testing) Python code. It is similar to unit testing frameworks in other languages
```suggestion
The **`unittest`** module provides features for [unit testing](https://www.codecademy.com/resources/docs/general/unit-testing) Python code. Similar to unit testing frameworks in other languages ,`unittest` allows for the automation of unit tests, sharing of setup and shutdown code for tests, and aggregation of tests into collections.
```

2022-09-01 20:30 UTC, Dusch4593 commented on content/python/concepts/unittest-module/unittest-module.md
> +Suppose the following code for a `Rectangle` class needs to be tested.
```suggestion
Suppose the following code for a `Rectangle` class needs to be tested:
```

2022-09-01 20:30 UTC, Dusch4593 commented on content/python/concepts/unittest-module/unittest-module.md
> +  - 'Development'
```suggestion
  - 'Automation'
  - 'Debugging'
  - 'Development'
  - 'Modules'
  - 'Units'
```

2022-09-01 20:30 UTC, Dusch4593 commented on content/python/concepts/unittest-module/unittest-module.md
> +First the `unittest.TestCase` class is subclassed for our test case object. Then tests are defined with methods with names starting with `test`. This naming convention is to allow the test runner to
```suggestion
First the `unittest.TestCase` class is subclassed for our test case object. Then tests are defined with methods with names starting with `test`. This naming convention allows the test runner to find the methods that represent tests.
```

2022-09-01 20:30 UTC, Dusch4593 commented on content/python/concepts/unittest-module/unittest-module.md
> +Running the above produces the following
```suggestion
Running the above produces the following:
```

2022-09-02 14:49 UTC, SSwiniarski commented
@Dusch4593 I implemented your suggestions.

2022-09-03 14:16 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM! 👍🏻 One last suggestion from me but I think we're ready for the next review 😄

2022-09-03 14:16 UTC, Dusch4593 commented on content/python/concepts/unittest-module/unittest-module.md
> +Using the `-v` option on the command line will produce a more verbose test.
```suggestion
Using the `-v` option on the command line will produce a more verbose test:
```

2022-09-08 18:21 UTC, KTom101 requested changes
@SSwiniarski Added a few suggestions to this!

2022-09-09 15:48 UTC, SSwiniarski commented
@KTom101 I implemented your suggestions.

2022-09-09 20:41 UTC, KTom101 approved these changes
@SSwiniarski 👍

2022-09-09 20:42 UTC, KTom101 commented
@Dusch4593 Any other additions?

2022-09-10 01:55 UTC, HishamT approved these changes
Looks good. I left comments addressing some things that I feel should be added or explained.

2022-09-10 01:55 UTC, HishamT commented on content/python/concepts/unittest-module/unittest-module.md
> +The **`unittest`** [module](https://www.codecademy.com/resources/docs/python/modules) provides features for [unit testing](https://www.codecademy.com/resources/docs/general/unit-testing) Python code.
Instead of "shutdown" use "tear down" to be more consistent with the function name: `tearDown()`.

2022-09-10 01:55 UTC, HishamT commented on content/python/concepts/unittest-module/unittest-module.md
> +First the `unittest.TestCase` class is subclassed for our test case object. Then tests are defined as methods with names starting with `test`. This naming convention allows the test runner to find th
It should be mentioned that `test` is mandatory as the first word in the test function's name.

2022-09-10 01:55 UTC, HishamT commented on content/python/concepts/unittest-module/unittest-module.md
> +```
Explain the important information that is conveyed by this output. 

Perhaps explain that the dots are not decorative but represent successful tests.

2022-09-10 13:49 UTC, SSwiniarski commented
@HishamT I applied your suggestions.

2022-09-14 00:50 UTC, Dusch4593 commented
This is looking good to merge! 👍🏻

I made a few last edits for the `unittest.md` file in 7e201877aeabf97e6438a3427a48accc4ddf8296 with the following:

- Added `'Functions'` and `'Methods'` to `Tags` since "method(s)" is mentioned heavily in the entry (and is related to "function(s).")
- Repurposed last sentence on line # 20 as an unordered list.
- Rephrased the beginning of line # 28 to be more declarative (same with lines # 103 and 118 <-- formerly line # 112).
- Repurposed the last sentence of the entry as an unordered list.
  - Replaced "function(s)" with "method(s)" to keep consistent with their being referred to as methods on line # 81.

2022-09-14 00:51 UTC, merged