update sqrt method
Codecademy/docs pull request #936
Opened 2022-08-30 17:50 UTC by Yash-Var

### Description

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-08-30 17:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=936) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=936) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=936) it.</sub>

2022-09-01 11:26 UTC, SSwiniarski requested changes
@Yash-Var, Thanks for your contribution! I did the first review and left a few comments.

Please remember to sign the CLA.

2022-09-01 11:26 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/sqrt/sqrt.md
> +The **`Math.sqrt()`** method returns the ` Square root ` of a number.
```suggestion
The **`Math.sqrt()`** method returns the square root of a double value passed to it as argument.
```

2022-09-01 11:26 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/sqrt/sqrt.md
> +Description: 'Returns the square root of a value of type double passed to it as argument.'
```suggestion
Description: 'Returns the square root of a double value passed to it as argument.'
```

2022-09-01 11:26 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/sqrt/sqrt.md
> +The `.sqrt()` method takes one parameters.
```suggestion
The `.sqrt()` method takes one parameter.
```

2022-09-01 11:26 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/sqrt/sqrt.md
> +To show working of `Math.sqrt()` method.
```suggestion
This example shows the working of the `Math.sqrt()` method.  
```

2022-09-01 11:26 UTC, SSwiniarski commented on content/java/concepts/math-methods/terms/sqrt/sqrt.md
> +## Output:
```suggestion
This results in the following output:
```

2022-09-01 12:19 UTC, Yash-Var commented
@SSwiniarski what i do next ......

2022-09-01 12:46 UTC, SSwiniarski commented
@Yash-Var, first you should [sign the CLA](https://cla-assistant.io/Codecademy/docs?pullRequest=936) which is a requirement for contributing. Then you should review my comments and either commit the suggestion or edit your entry directly in response to the editorial feedback. Tag me in a comment here when you're done editing your entry.

2022-09-01 13:45 UTC, Yash-Var commented
@SSwiniarski completed pls review

2022-09-01 18:53 UTC, Dusch4593 requested changes
@Yash-Var First of all, I want to thank you very much for the quick turnaround on this rewrite. This is much better! 😄 🚀

I've finished my review and left you some comments/suggestions to look over. Let us know if you have any questions and tag either myself or @SSwiniarski to let us know you've implemented the new changes.

2022-09-01 18:53 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/sqrt/sqrt.md
> +  - 'Sqrt'
```suggestion
  - 'Arithmetic'
  - 'Functions'
  - 'Methods'
  - 'Numbers'
```

For the meta-`Tags`, let's use what's inside the [tags.md](https://github.com/Codecademy/docs/blob/main/documentation/tags.md) file. I suggest adding `'Functions'` for SEO-purposes, as well as the `'Numbers'` tag.

2022-09-01 18:53 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/sqrt/sqrt.md
> +The **`Math.sqrt()`** method returns the square root of a double value passed to it as an argument.
```suggestion
The **`Math.sqrt()`** method returns the positive, properly rounded square root of a double-type value.
```

2022-09-01 18:53 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/sqrt/sqrt.md
> +The `.sqrt()` method takes one parameter.
```suggestion
The return type of the `.sqrt()` method is a double. The data type of the `num` parameter is also a double. However, if a decimal is not provided, `num` will still be treated like a double-type.

Some edge cases for the `.sqrt()` method include the following:

 - If `num` is less than zero or it is not a numeric type (`NaN`), then `NaN` is returned.
 - If `num` is positive infinity (`Double.POSITIVE_INFINITY`), then `Infinity` is returned. 
```

The "Syntax" section is a good place to list out, if any, the edge cases of parameters used in a method/function.

2022-09-01 18:53 UTC, Dusch4593 commented on content/java/concepts/math-methods/terms/sqrt/sqrt.md
> +This example shows the working of the `Math.sqrt()` method.
```suggestion
The following example showcases the `.sqrt()` method being applied to two variables:
```

2022-09-02 14:51 UTC, SSwiniarski approved these changes

2022-09-03 14:32 UTC, Dusch4593 approved these changes
@Yash-Var This entry is looking good to me! 😄 To get the GitHub checks to pass, I removed extra/trailing spaces in 57a715656f08e682fca63087463fd6bebc75baaa and 98ffe448f478156076320def42baa67d9533669a.

This entry looks ready to merge (🚀) but a few things for you to note for your next pull request:

- Try not create new folders/files in the `main` branch of your forked Docs repo. Instead, we recommend creating a new Git branch and creating/pushing commits from there. The name of the PR branch should reflect the work being done (in this case, I would have named this one `java-math-sqrt`). 
  - The way I do this is with `git checkout -b [name-of-new-branch]` where I create and check out to the new branch in one command.
  - Alternatively, you could run `git branch [name-of-new-branch]` followed by `git checkout [name-of-new-branch]`.
- When you create the new pull request here on GitHub, make sure to review and check the boxes (I went ahead and checked them since this PR is about to be merged):
<img width="1006" alt="Screen Shot 2022-09-03 at 10 30 33 AM" src="https://user-images.githubusercontent.com/23144845/188274985-cede8150-d147-45dc-a698-b140bb33e2e0.png">

2022-09-03 14:33 UTC, merged

2022-09-03 14:41 UTC, Dusch4593 commented
On another note, congratulations @Yash-Var for your first contribution to Docs. The entry is now live here: https://www.codecademy.com/resources/docs/java/math-methods/sqrt

Something I noticed, though. Your profile isn't showing under the list of Contributors for this entry:

<img width="901" alt="Screen Shot 2022-09-03 at 10 38 25 AM" src="https://user-images.githubusercontent.com/23144845/188275432-8697403e-ff32-4cfd-af00-1cdcddecb743.png">

If you would like to receive credit for your contribution to an entry, make sure to have your Codecademy user profile linked to your GitHub account:

1. Go to your Codecademy dashboard.
2. Click on your profile image in the top-right and then choose "Profile".
3. Then click "Edit Profile".
4. In the "GitHub Username" field, add your username (without the @).
5. Click "Save Changes"

After this, I recommend logging out of your Codecademy account and re-logging in through GitHub:

<img width="607" alt="Screen Shot 2022-08-22 at 6 46 51 PM" src="https://user-images.githubusercontent.com/23144845/186031956-ba293977-ebfd-4309-b014-d8f01f6f03c2.png">

Of course, you can opt not to do this and be listed as an "Anonymous contributor", instead. :)

2022-09-03 15:38 UTC, Yash-Var commented
@Dusch4593 @SSwiniarski thanks for guidance .....

2022-09-03 15:41 UTC, Dusch4593 commented
<img width="803" alt="Screen Shot 2022-09-03 at 11 40 52 AM" src="https://user-images.githubusercontent.com/23144845/188277985-254c4539-c0b0-439b-a6c3-2dc484ec0783.png">

There you are! 😄