Update Entry: General IDE
Codecademy/docs pull request #937
Opened 2022-09-01 12:40 UTC by SSwiniarski

### Description

From Target Keyword List.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-09-01 20:05 UTC, Dusch4593 requested changes
@SSwiniarski Finished with my review and left some comments/suggestions.

2022-09-01 20:05 UTC, Dusch4593 commented on content/general/concepts/ide/ide.md
For the header on the next line, I would suggest renaming it to "Common Features". Then, I would add a hashtag `#` to the following headers:

- ~Autocomplete~ (change this to "Autocompletion")
- Building Executables
- Debugging

2022-09-01 20:05 UTC, Dusch4593 commented on content/general/concepts/ide/ide.md
> +An **IDE**, or Integrated Development Environment, enables programmers to consolidate the different aspects of writing a computer program.
```suggestion
An **Integrated Development Environment (IDE)**, enables programmers to consolidate the different aspects of writing a computer program.
```

2022-09-01 20:05 UTC, Dusch4593 commented on content/general/concepts/ide/ide.md
>  IDEs increase programmer productivity by combining common activities of writing software into a single application: editing source code, building executables, and debugging.
```suggestion
IDEs increase programmer productivity by featuring common activities of writing software into a single application..
```

2022-09-01 20:05 UTC, Dusch4593 commented on content/general/concepts/ide/ide.md
> +One example is Codecademy's own [Codebyte Editor](https://www.codecademy.com/codebyte-editor). It allows experimenting with [C++](https://www.codecademy.com/resources/docs/cpp), C#, [Go](https://www.
```suggestion
One example is Codecademy's own [Codebyte Editor](https://www.codecademy.com/codebyte-editor). It allows experimenting with [C++](https://www.codecademy.com/resources/docs/cpp), C#, [Go](https://www.codecademy.com/resources/docs/go), [JavaScript](https://www.codecademy.com/resources/docs/javascript), [PHP](https://www.codecademy.com/resources/docs/php), [Python 3](https://www.codecademy.com/resources/docs/python), [Ruby](https://www.codecademy.com/resources/docs/ruby), and Scheme.
```

2022-09-01 20:05 UTC, Dusch4593 commented on content/general/concepts/ide/ide.md
> +Another example is [JDoodle](https://www.jdoodle.com/) which offers support for over 75 languages including [Java](https://www.codecademy.com/resources/docs/java), [Python 2](https://www.codecademy.c
```suggestion
Another example is [JDoodle](https://www.jdoodle.com/) which offers support for over 75 languages including [Java](https://www.codecademy.com/resources/docs/java), [Python 2](https://www.codecademy.com/resources/docs/python), [R](https://www.codecademy.com/resources/docs/r), and [Swift](https://www.codecademy.com/resources/docs/swift).
```

2022-09-02 12:06 UTC, SSwiniarski commented
@Dusch4593, I implemented your suggestions

2022-09-03 14:10 UTC, Dusch4593 approved these changes
@SSwiniarski LGTM! 👍🏻 I think we can just merge this with one review since this is only edits for one file.

2022-09-03 14:10 UTC, merged