Add details on JSON
Codecademy/docs pull request #941
Opened 2022-09-02 01:17 UTC by YanisaHS

### Description

I added information to the following pages:
- General: JSON
  - Added ) after “EcmaScript” in the first paragraph
  - Noted that JavaScript can parse JSON directly
  - Noted that JavaScript is language independent with more details
- Python: JSON Module
  - Noted that JSON is based on JavaScript object-literal syntax
  - Added a list of data types that can be converted to JSON strings in Python
- JavaScript: JSON
  - Added info on how the JSON object is built into JavaScript

Closes #829 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-09-02 01:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=941) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=941) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=941) it.</sub>

2022-09-03 13:42 UTC, SSwiniarski requested changes
@YanisaHS I completed the first review and only had one comment.

2022-09-03 13:42 UTC, SSwiniarski commented on content/general/concepts/json/json.md
> +Although JSON was originally based on a subset of JavaScript syntax, JSON is language independent and does not require JavaScript. JSON uses some conventions from C-descendent languages, such as C, C
```suggestion
Although JSON was originally based on a subset of JavaScript syntax, JSON is language independent and does not require JavaScript. JSON uses some conventions from C-descendent languages, such as [C](https://www.codecademy.com/resources/docs/c), [C++](https://www.codecademy.com/resources/docs/cpp), JavaScript, and [Java](https://www.codecademy.com/resources/docs/java).
```

2022-09-07 18:09 UTC, YanisaHS commented
Thanks @SSwiniarski! Just added those changes.

2022-09-08 16:07 UTC, SSwiniarski approved these changes
@YanisaHS Looks good for next review.

2022-09-09 10:41 UTC, Dusch4593 requested changes
@YanisaHS Finished my review and left you some comments/suggestions 😄

2022-09-09 10:41 UTC, Dusch4593 commented on content/general/concepts/json/json.md
On line # 50, can we link "Whitespace" to the following Docs entry?

https://www.codecademy.com/resources/docs/general/whitespace

Also, on this same line, can rewrite as this?

```
Whitespace (e.g., spaces, tabs, line feeds, and carriage returns) is ignored between names, values, and punctuation.
```

2022-09-09 10:41 UTC, Dusch4593 commented on content/general/concepts/json/json.md
Then on line # 52, let's link "comments" out to the following Docs entry: https://www.codecademy.com/resources/docs/general/comment

2022-09-09 10:41 UTC, Dusch4593 commented on content/general/concepts/json/json.md
Lastly for this file, on line # 81, let's link "XML" out to this Docs entry: https://www.codecademy.com/resources/docs/general/xml

2022-09-09 10:41 UTC, Dusch4593 commented on content/python/concepts/json-module/json-module.md
On line # 17, **bold** the following: `json` module.

2022-09-09 10:41 UTC, Dusch4593 commented on content/python/concepts/json-module/json-module.md
> +JSON in Python is based on the object-literal syntax of JavaScript. The following Python [data types](https://www.codecademy.com/resources/docs/python/data-types) can be converted to JSON strings in
```suggestion
JSON in Python is based on the object-literal syntax of [JavaScript](https://www.codecademy.com/resources/docs/javascript). The following Python [data types](https://www.codecademy.com/resources/docs/python/data-types) can be converted to JSON strings in Python:
```

2022-09-09 10:41 UTC, Dusch4593 commented on content/python/concepts/json-module/json-module.md
> +- NoneType
```suggestion
- Booleans (`bool` type)
- [Dictionaries](https://www.codecademy.com/resources/docs/python/dictionaries) (`dict` type)
- Number types (i.e., `int` and `float`)
- Sequence types (i.e., [lists](https://www.codecademy.com/resources/docs/python/lists) and [tuples](https://www.codecademy.com/resources/docs/python/tuples))
- [Strings](https://www.codecademy.com/resources/docs/python/strings) (`str` type)
- `NoneType`
```

2022-09-09 10:41 UTC, Dusch4593 commented on content/javascript/concepts/json/json.md
> +In JavaScript, the reserved `JSON` object is used to convert values to JavaScript Object Notation ([JSON](https://www.codecademy.com/resources/docs/general/json)). It can also be used for parsing JSO
```suggestion
In JavaScript, the built-in **`JSON`** object is used to convert values to [JavaScript Object Notation (JSON)](https://www.codecademy.com/resources/docs/general/json) as well as parse those values. `JSON` is a standard JavaScript object, so there is no need to import any external packages.
```

I think the last sentence make more sense in the "Syntax" section.

2022-09-09 10:41 UTC, Dusch4593 commented on content/javascript/concepts/json/json.md
Could we prepend the sentence on line # 23 with the following?

"No constructor function is needed to create `JSON` objects."

2022-09-09 10:41 UTC, Dusch4593 commented on content/python/concepts/json-module/json-module.md
>  import json
Above in the list of meta-`Tags` (lines # 7-11), let's add `'Modules'` to it

2022-09-09 10:41 UTC, Dusch4593 commented on content/general/concepts/json/json.md
> +Although JSON was originally based on a subset of JavaScript syntax, JSON is language independent and does not require JavaScript. JSON uses some conventions from C-descendent languages, such as [C](
```suggestion
In addition to JavaScript, JSON uses some conventions from the [C](https://www.codecademy.com/resources/docs/c)-descendent languages, including C , [C++](https://www.codecademy.com/resources/docs/cpp), and [Java](https://www.codecademy.com/resources/docs/java).
```

I think the ideas from the first sentence is already covered in the previous paragraph.

2022-09-09 10:41 UTC, Dusch4593 commented on content/general/concepts/json/json.md
>  JSON is commonly used for transferring data between clients and servers for tasks such as web browsing or form submission. Some companies also use JSON to allow their data to be accessed in other app
```suggestion
JSON is commonly used for transferring data between clients and [servers](https://www.codecademy.com/resources/docs/general/server) for tasks such as web browsing or form submission. Some companies also use JSON to allow their data to be accessed in other applications via [API](https://www.codecademy.com/resources/docs/general/api). Some examples include:
```

2022-09-09 17:18 UTC, YanisaHS commented
Thanks @Dusch4593 ! Just pushed the changes. 🥳

2022-09-09 18:32 UTC, Dusch4593 approved these changes
@YanisaHS LGTM! Just one last little suggestion.

2022-09-09 18:32 UTC, Dusch4593 commented on content/general/concepts/json/json.md
Could we add the following to the meta-`Tags` above?

- 'Properties'
- 'Values'

2022-09-09 18:48 UTC, YanisaHS commented
@Dusch4593 Yep! Done! 👼

2022-09-29 17:19 UTC, Dusch4593 commented
@YanisaHS This PR seems good for merge! 😄 I pushed a few last-minute changes in 567bb2b298c1c605f1af5eff3b3fcfb654dc3e45, including:

- Light edits to the rendered curly brackets `{ }` in General: JSON.
- In JavaScript: JSON, I embeded "JSON" in back-ticks within the meta-`Description`.

2022-09-29 17:20 UTC, merged

2022-09-29 17:28 UTC, Dusch4593 commented
Congrats @YanisaHS your changes should now be live! 🚀 🎊 🎉 Live links below.

- General: JSON - https://www.codecademy.com/resources/docs/general/json
- JavaScript: JSON - https://www.codecademy.com/resources/docs/javascript/json
- Python: JSON Module - https://www.codecademy.com/resources/docs/python/json-module

Let us know if everything looks ok on your end and if you can also see your profile credited on those entry pages. Looking forward to merging your next contribution! 😄

2022-09-30 03:47 UTC, YanisaHS commented
@Dusch4593 Yay!! Looks amazing! 🥳🥳🎉