New Entry: C++ Math Functions: log()
Codecademy/docs pull request #975
Opened 2022-09-07 21:13 UTC by Hitarth-Kothari

### Description

Closes #956 

Created folder named log in path : c++/concepts/math-functions/terms/
Created a file named log.md, which includes all requirements for a Term Entry Issue

### Type of Change

- Adding a new entry

### Checklist

- [*] All writings are my own.
- [*] My entry follows the Codecademy Docs style guide.
- [*] My changes generate no new warnings.
- [*] I have performed a self-review of my own writing and code.
- [*] I have checked my entry and corrected any misspellings.
- [*] I have made corresponding changes to the documentation if needed.
- [*] I have confirmed my changes are not being pushed from my forked `main` branch.
- [*] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [*] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2022-09-08 14:07 UTC, Dusch4593 requested changes
@Hitarth-Kothari Finished with my review and left you some comments/suggestions. 😄

2022-09-08 14:07 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/log/log.md
> +}
```suggestion
#include <iostream>
#include <math.h>

int main() {
  double x = 10;
  double result;
  result = log(x);
  std::cout << "The log of " << x << " is " << result << "\n";
}
```

2022-09-08 14:07 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/log/log.md
> +Description: 'Returns the natural log of the argument.'
```suggestion
Description: 'Returns the natural, base-e logarithm of the argument.'
```

2022-09-08 15:31 UTC, Hitarth-Kothari commented
@Dusch4593 I tried running yarn to fix some of these issues, but I keep getting an error
Invalid configuration file `content\cpp\concepts\math-functions\terms\sqrt\sqrt.md`: Cannot find module '@codecademy/prettier-config'
Any idea how to fix?

2022-09-08 17:21 UTC, Dusch4593 commented
@Hitarth-Kothari The GH checks to all be passing. But I'm wondering still how you got that error? Especially because it's complaining about a different file pertaining to a different function other than `log()`. What `yarn` command did you run?

2022-09-08 17:43 UTC, Hitarth-Kothari commented
Yarn format <path to file>

2022-09-08 17:50 UTC, Dusch4593 commented
> Yarn format

I think if meant to format all files, it's `yarn format:all`. For a specific file, it's `yarn format path/to/markdown/file.md`.

However, usually when you `commit` new changes in your branch, we have a [husky hook](https://github.com/Codecademy/docs/blob/main/.husky/pre-commit) that formats/lints all relevant files for you prior to `push`ing back up to the PR. 😄

2022-09-08 17:53 UTC, Hitarth-Kothari commented
Tbh I tried both for the isfinite file, and i kept getting the same error, and i dont know if the isfinite will pass the workflow tests since I was unable to run the yarn code

2022-09-08 17:59 UTC, Dusch4593 commented
> Tbh I tried both for the isfinite file, and i kept getting the same error, and i dont know if the isfinite will pass the workflow tests since I was unable to run the yarn code

I just tried out on my end and ran:

```
yarn format content/cpp/concepts/math-functions/terms/log/log.md
```
It formatted as expected. This command is what's giving you the error?

2022-09-08 19:38 UTC, Dusch4593 approved these changes
@Hitarth-Kothari formatting aside, this PR looks good from my end. 😄 I left one last suggestion but am approving for the next review.

2022-09-08 19:38 UTC, Dusch4593 commented on content/cpp/concepts/math-functions/terms/log/log.md
> +
```suggestion

The following example is runnable and returns the natural log of `10`:

```

2022-09-09 00:00 UTC, Hitarth-Kothari commented
I just retried running the command, it still doent work
I think I'm missing a file name preetier-config

2022-09-09 00:08 UTC, Dusch4593 commented
> @Dusch4593 I just retried running the command, it still doent work I think I'm missing a file name preetier-config

Hmm 🤔 And you're still getting the error even after running with forward slashes `/`?

`yarn format content/cpp/concepts/math-functions/terms/log/log.md`

2022-09-09 00:10 UTC, Dusch4593 commented
Would you be able to post a screenshot of the error you got on the command line?

2022-09-09 03:25 UTC, Hitarth-Kothari commented
![Screenshot (31)](https://user-images.githubusercontent.com/71833799/189265640-1f03973b-a05b-4eb8-9fb3-225d6e6b1893.png)

2022-09-09 03:39 UTC, Hitarth-Kothari commented
![Screenshot (32)](https://user-images.githubusercontent.com/71833799/189266991-b96df792-7198-434e-b382-c8f1e187aece.png)

2022-09-09 09:54 UTC, Dusch4593 commented
@Hitarth-Kothari Hmm 🤔 When you're editing entries locally, such as `log.md` in this case, are you doing so from a code editor like VS Code?

2022-09-09 16:25 UTC, Hitarth-Kothari commented
I've been using VScode

2022-09-09 16:39 UTC, SSwiniarski reviewed
@Hitarth-Kothari here's an edit I think will fix the test failure.

2022-09-09 16:39 UTC, SSwiniarski commented on content/cpp/concepts/math-functions/terms/log/log.md
> +The following example is runnable and returns the natural log of `10`:
```suggestion
The following example is runnable and returns the natural log of `10`:

```

2022-09-09 16:40 UTC, Hitarth-Kothari commented
Thanks for the suggestions. I am unable to run yarn for some reason and just cant find the formatting issues

2022-09-09 17:49 UTC, Dusch4593 commented
@Hitarth-Kothari no worries 😄 I went ahead and fixed the formatting with ae2711556977abd09d557851e0570101ee8a1ca9 to get the checks to pass. I'm sorry for what's going through with `yarn` on your end. I want you to know that I've pinged my team about this and want to learn more about what caused the error and how to navigate it next time.

For now, though, @SSwiniarski do you think this now looks good to merge?

2022-09-10 11:44 UTC, SSwiniarski approved these changes
@Dusch4593 Looks Good.

2022-09-14 13:07 UTC, Dusch4593 commented
@Hitarth-Kothari This looks good to merge! 👍🏻 I made some last-minute, light edits in 7894ea13e53bc9b8f7fb8fb2ff3ed528382e478f and c13baaef263e595dc3dd9aa93735737e29f0320f.

2022-09-14 13:08 UTC, merged

2022-09-14 13:11 UTC, Dusch4593 commented
@Hitarth-Kothari Congrats, your contribution is now live! 🎉 🎊 🥳

Live entry link here: https://www.codecademy.com/resources/docs/cpp/math-functions/log